package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/s3/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"abort-multipart-upload", "complete-multipart-upload", "copy-object", "create-bucket", "create-bucket-metadata-configuration", "create-bucket-metadata-table-configuration", "create-multipart-upload", "create-session", "delete-bucket", "delete-bucket-analytics-configuration", "delete-bucket-cors", "delete-bucket-encryption", "delete-bucket-intelligent-tiering-configuration", "delete-bucket-inventory-configuration", "delete-bucket-lifecycle", "delete-bucket-metadata-configuration", "delete-bucket-metadata-table-configuration", "delete-bucket-metrics-configuration", "delete-bucket-ownership-controls", "delete-bucket-policy", "delete-bucket-replication", "delete-bucket-tagging", "delete-bucket-website", "delete-object", "delete-object-tagging", "delete-objects", "delete-public-access-block", "get-bucket-abac", "get-bucket-accelerate-configuration", "get-bucket-acl", "get-bucket-analytics-configuration", "get-bucket-cors", "get-bucket-encryption", "get-bucket-intelligent-tiering-configuration", "get-bucket-inventory-configuration", "get-bucket-lifecycle-configuration", "get-bucket-location", "get-bucket-logging", "get-bucket-metadata-configuration", "get-bucket-metadata-table-configuration", "get-bucket-metrics-configuration", "get-bucket-notification-configuration", "get-bucket-ownership-controls", "get-bucket-policy", "get-bucket-policy-status", "get-bucket-replication", "get-bucket-request-payment", "get-bucket-tagging", "get-bucket-versioning", "get-bucket-website", "get-object", "get-object-acl", "get-object-attributes", "get-object-legal-hold", "get-object-lock-configuration", "get-object-retention", "get-object-tagging", "get-object-torrent", "get-public-access-block", "head-bucket", "head-object", "list-bucket-analytics-configurations", "list-bucket-intelligent-tiering-configurations", "list-bucket-inventory-configurations", "list-bucket-metrics-configurations", "list-buckets", "list-directory-buckets", "list-multipart-uploads", "list-object-versions", "list-objects", "list-objects-v2", "list-parts", "put-bucket-abac", "put-bucket-accelerate-configuration", "put-bucket-acl", "put-bucket-analytics-configuration", "put-bucket-cors", "put-bucket-encryption", "put-bucket-intelligent-tiering-configuration", "put-bucket-inventory-configuration", "put-bucket-lifecycle-configuration", "put-bucket-logging", "put-bucket-metrics-configuration", "put-bucket-notification-configuration", "put-bucket-ownership-controls", "put-bucket-policy", "put-bucket-replication", "put-bucket-request-payment", "put-bucket-tagging", "put-bucket-versioning", "put-bucket-website", "put-object", "put-object-acl", "put-object-legal-hold", "put-object-lock-configuration", "put-object-retention", "put-object-tagging", "put-public-access-block", "rename-object", "restore-object", "select-object-content", "update-bucket-metadata-inventory-table-configuration", "update-bucket-metadata-journal-table-configuration", "update-object-encryption", "upload-part", "upload-part-copy", "write-get-object-response"},
		OperationSet: map[string]bool{"abort-multipart-upload": true, "complete-multipart-upload": true, "copy-object": true, "create-bucket": true, "create-bucket-metadata-configuration": true, "create-bucket-metadata-table-configuration": true, "create-multipart-upload": true, "create-session": true, "delete-bucket": true, "delete-bucket-analytics-configuration": true, "delete-bucket-cors": true, "delete-bucket-encryption": true, "delete-bucket-intelligent-tiering-configuration": true, "delete-bucket-inventory-configuration": true, "delete-bucket-lifecycle": true, "delete-bucket-metadata-configuration": true, "delete-bucket-metadata-table-configuration": true, "delete-bucket-metrics-configuration": true, "delete-bucket-ownership-controls": true, "delete-bucket-policy": true, "delete-bucket-replication": true, "delete-bucket-tagging": true, "delete-bucket-website": true, "delete-object": true, "delete-object-tagging": true, "delete-objects": true, "delete-public-access-block": true, "get-bucket-abac": true, "get-bucket-accelerate-configuration": true, "get-bucket-acl": true, "get-bucket-analytics-configuration": true, "get-bucket-cors": true, "get-bucket-encryption": true, "get-bucket-intelligent-tiering-configuration": true, "get-bucket-inventory-configuration": true, "get-bucket-lifecycle-configuration": true, "get-bucket-location": true, "get-bucket-logging": true, "get-bucket-metadata-configuration": true, "get-bucket-metadata-table-configuration": true, "get-bucket-metrics-configuration": true, "get-bucket-notification-configuration": true, "get-bucket-ownership-controls": true, "get-bucket-policy": true, "get-bucket-policy-status": true, "get-bucket-replication": true, "get-bucket-request-payment": true, "get-bucket-tagging": true, "get-bucket-versioning": true, "get-bucket-website": true, "get-object": true, "get-object-acl": true, "get-object-attributes": true, "get-object-legal-hold": true, "get-object-lock-configuration": true, "get-object-retention": true, "get-object-tagging": true, "get-object-torrent": true, "get-public-access-block": true, "head-bucket": true, "head-object": true, "list-bucket-analytics-configurations": true, "list-bucket-intelligent-tiering-configurations": true, "list-bucket-inventory-configurations": true, "list-bucket-metrics-configurations": true, "list-buckets": true, "list-directory-buckets": true, "list-multipart-uploads": true, "list-object-versions": true, "list-objects": true, "list-objects-v2": true, "list-parts": true, "put-bucket-abac": true, "put-bucket-accelerate-configuration": true, "put-bucket-acl": true, "put-bucket-analytics-configuration": true, "put-bucket-cors": true, "put-bucket-encryption": true, "put-bucket-intelligent-tiering-configuration": true, "put-bucket-inventory-configuration": true, "put-bucket-lifecycle-configuration": true, "put-bucket-logging": true, "put-bucket-metrics-configuration": true, "put-bucket-notification-configuration": true, "put-bucket-ownership-controls": true, "put-bucket-policy": true, "put-bucket-replication": true, "put-bucket-request-payment": true, "put-bucket-tagging": true, "put-bucket-versioning": true, "put-bucket-website": true, "put-object": true, "put-object-acl": true, "put-object-legal-hold": true, "put-object-lock-configuration": true, "put-object-retention": true, "put-object-tagging": true, "put-public-access-block": true, "rename-object": true, "restore-object": true, "select-object-content": true, "update-bucket-metadata-inventory-table-configuration": true, "update-bucket-metadata-journal-table-configuration": true, "update-object-encryption": true, "upload-part": true, "upload-part-copy": true, "write-get-object-response": true},
		OperationInputs: map[string][]string{
			"abort-multipart-upload":                               {"Bucket", "ExpectedBucketOwner", "IfMatchInitiatedTime", "Key", "RequestPayer", "UploadId"},
			"complete-multipart-upload":                            {"Bucket", "ChecksumCRC32", "ChecksumCRC32C", "ChecksumCRC64NVME", "ChecksumSHA1", "ChecksumSHA256", "ChecksumType", "ExpectedBucketOwner", "IfMatch", "IfNoneMatch", "Key", "MpuObjectSize", "MultipartUpload", "RequestPayer", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "UploadId"},
			"copy-object":                                          {"ACL", "Bucket", "BucketKeyEnabled", "CacheControl", "ChecksumAlgorithm", "ContentDisposition", "ContentEncoding", "ContentLanguage", "ContentType", "CopySource", "CopySourceIfMatch", "CopySourceIfModifiedSince", "CopySourceIfNoneMatch", "CopySourceIfUnmodifiedSince", "CopySourceSSECustomerAlgorithm", "CopySourceSSECustomerKey", "CopySourceSSECustomerKeyMD5", "ExpectedBucketOwner", "ExpectedSourceBucketOwner", "Expires", "GrantFullControl", "GrantRead", "GrantReadACP", "GrantWriteACP", "IfMatch", "IfNoneMatch", "Key", "Metadata", "MetadataDirective", "ObjectLockLegalHoldStatus", "ObjectLockMode", "ObjectLockRetainUntilDate", "RequestPayer", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "SSEKMSEncryptionContext", "SSEKMSKeyId", "ServerSideEncryption", "StorageClass", "Tagging", "TaggingDirective", "WebsiteRedirectLocation"},
			"create-bucket":                                        {"ACL", "Bucket", "CreateBucketConfiguration", "GrantFullControl", "GrantRead", "GrantReadACP", "GrantWrite", "GrantWriteACP", "ObjectLockEnabledForBucket", "ObjectOwnership"},
			"create-bucket-metadata-configuration":                 {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "MetadataConfiguration"},
			"create-bucket-metadata-table-configuration":           {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "MetadataTableConfiguration"},
			"create-multipart-upload":                              {"ACL", "Bucket", "BucketKeyEnabled", "CacheControl", "ChecksumAlgorithm", "ChecksumType", "ContentDisposition", "ContentEncoding", "ContentLanguage", "ContentType", "ExpectedBucketOwner", "Expires", "GrantFullControl", "GrantRead", "GrantReadACP", "GrantWriteACP", "Key", "Metadata", "ObjectLockLegalHoldStatus", "ObjectLockMode", "ObjectLockRetainUntilDate", "RequestPayer", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "SSEKMSEncryptionContext", "SSEKMSKeyId", "ServerSideEncryption", "StorageClass", "Tagging", "WebsiteRedirectLocation"},
			"create-session":                                       {"Bucket", "BucketKeyEnabled", "SSEKMSEncryptionContext", "SSEKMSKeyId", "ServerSideEncryption", "SessionMode"},
			"delete-bucket":                                        {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-analytics-configuration":                {"Bucket", "ExpectedBucketOwner", "Id"},
			"delete-bucket-cors":                                   {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-encryption":                             {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-intelligent-tiering-configuration":      {"Bucket", "ExpectedBucketOwner", "Id"},
			"delete-bucket-inventory-configuration":                {"Bucket", "ExpectedBucketOwner", "Id"},
			"delete-bucket-lifecycle":                              {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-metadata-configuration":                 {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-metadata-table-configuration":           {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-metrics-configuration":                  {"Bucket", "ExpectedBucketOwner", "Id"},
			"delete-bucket-ownership-controls":                     {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-policy":                                 {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-replication":                            {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-tagging":                                {"Bucket", "ExpectedBucketOwner"},
			"delete-bucket-website":                                {"Bucket", "ExpectedBucketOwner"},
			"delete-object":                                        {"Bucket", "BypassGovernanceRetention", "ExpectedBucketOwner", "IfMatch", "IfMatchLastModifiedTime", "IfMatchSize", "Key", "MFA", "RequestPayer", "VersionId"},
			"delete-object-tagging":                                {"Bucket", "ExpectedBucketOwner", "Key", "VersionId"},
			"delete-objects":                                       {"Bucket", "BypassGovernanceRetention", "ChecksumAlgorithm", "Delete", "ExpectedBucketOwner", "MFA", "RequestPayer"},
			"delete-public-access-block":                           {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-abac":                                      {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-accelerate-configuration":                  {"Bucket", "ExpectedBucketOwner", "RequestPayer"},
			"get-bucket-acl":                                       {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-analytics-configuration":                   {"Bucket", "ExpectedBucketOwner", "Id"},
			"get-bucket-cors":                                      {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-encryption":                                {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-intelligent-tiering-configuration":         {"Bucket", "ExpectedBucketOwner", "Id"},
			"get-bucket-inventory-configuration":                   {"Bucket", "ExpectedBucketOwner", "Id"},
			"get-bucket-lifecycle-configuration":                   {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-location":                                  {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-logging":                                   {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-metadata-configuration":                    {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-metadata-table-configuration":              {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-metrics-configuration":                     {"Bucket", "ExpectedBucketOwner", "Id"},
			"get-bucket-notification-configuration":                {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-ownership-controls":                        {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-policy":                                    {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-policy-status":                             {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-replication":                               {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-request-payment":                           {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-tagging":                                   {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-versioning":                                {"Bucket", "ExpectedBucketOwner"},
			"get-bucket-website":                                   {"Bucket", "ExpectedBucketOwner"},
			"get-object":                                           {"Bucket", "ChecksumMode", "ExpectedBucketOwner", "IfMatch", "IfModifiedSince", "IfNoneMatch", "IfUnmodifiedSince", "Key", "PartNumber", "Range", "RequestPayer", "ResponseCacheControl", "ResponseContentDisposition", "ResponseContentEncoding", "ResponseContentLanguage", "ResponseContentType", "ResponseExpires", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "VersionId"},
			"get-object-acl":                                       {"Bucket", "ExpectedBucketOwner", "Key", "RequestPayer", "VersionId"},
			"get-object-attributes":                                {"Bucket", "ExpectedBucketOwner", "Key", "MaxParts", "ObjectAttributes", "PartNumberMarker", "RequestPayer", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "VersionId"},
			"get-object-legal-hold":                                {"Bucket", "ExpectedBucketOwner", "Key", "RequestPayer", "VersionId"},
			"get-object-lock-configuration":                        {"Bucket", "ExpectedBucketOwner"},
			"get-object-retention":                                 {"Bucket", "ExpectedBucketOwner", "Key", "RequestPayer", "VersionId"},
			"get-object-tagging":                                   {"Bucket", "ExpectedBucketOwner", "Key", "RequestPayer", "VersionId"},
			"get-object-torrent":                                   {"Bucket", "ExpectedBucketOwner", "Key", "RequestPayer"},
			"get-public-access-block":                              {"Bucket", "ExpectedBucketOwner"},
			"head-bucket":                                          {"Bucket", "ExpectedBucketOwner"},
			"head-object":                                          {"Bucket", "ChecksumMode", "ExpectedBucketOwner", "IfMatch", "IfModifiedSince", "IfNoneMatch", "IfUnmodifiedSince", "Key", "PartNumber", "Range", "RequestPayer", "ResponseCacheControl", "ResponseContentDisposition", "ResponseContentEncoding", "ResponseContentLanguage", "ResponseContentType", "ResponseExpires", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "VersionId"},
			"list-bucket-analytics-configurations":                 {"Bucket", "ContinuationToken", "ExpectedBucketOwner"},
			"list-bucket-intelligent-tiering-configurations":       {"Bucket", "ContinuationToken", "ExpectedBucketOwner"},
			"list-bucket-inventory-configurations":                 {"Bucket", "ContinuationToken", "ExpectedBucketOwner"},
			"list-bucket-metrics-configurations":                   {"Bucket", "ContinuationToken", "ExpectedBucketOwner"},
			"list-buckets":                                         {"BucketRegion", "ContinuationToken", "MaxBuckets", "Prefix"},
			"list-directory-buckets":                               {"ContinuationToken", "MaxDirectoryBuckets"},
			"list-multipart-uploads":                               {"Bucket", "Delimiter", "EncodingType", "ExpectedBucketOwner", "KeyMarker", "MaxUploads", "Prefix", "RequestPayer", "UploadIdMarker"},
			"list-object-versions":                                 {"Bucket", "Delimiter", "EncodingType", "ExpectedBucketOwner", "KeyMarker", "MaxKeys", "OptionalObjectAttributes", "Prefix", "RequestPayer", "VersionIdMarker"},
			"list-objects":                                         {"Bucket", "Delimiter", "EncodingType", "ExpectedBucketOwner", "Marker", "MaxKeys", "OptionalObjectAttributes", "Prefix", "RequestPayer"},
			"list-objects-v2":                                      {"Bucket", "ContinuationToken", "Delimiter", "EncodingType", "ExpectedBucketOwner", "FetchOwner", "MaxKeys", "OptionalObjectAttributes", "Prefix", "RequestPayer", "StartAfter"},
			"list-parts":                                           {"Bucket", "ExpectedBucketOwner", "Key", "MaxParts", "PartNumberMarker", "RequestPayer", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "UploadId"},
			"put-bucket-abac":                                      {"AbacStatus", "Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner"},
			"put-bucket-accelerate-configuration":                  {"AccelerateConfiguration", "Bucket", "ChecksumAlgorithm", "ExpectedBucketOwner"},
			"put-bucket-acl":                                       {"ACL", "AccessControlPolicy", "Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "GrantFullControl", "GrantRead", "GrantReadACP", "GrantWrite", "GrantWriteACP"},
			"put-bucket-analytics-configuration":                   {"AnalyticsConfiguration", "Bucket", "ExpectedBucketOwner", "Id"},
			"put-bucket-cors":                                      {"Bucket", "CORSConfiguration", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner"},
			"put-bucket-encryption":                                {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "ServerSideEncryptionConfiguration"},
			"put-bucket-intelligent-tiering-configuration":         {"Bucket", "ExpectedBucketOwner", "Id", "IntelligentTieringConfiguration"},
			"put-bucket-inventory-configuration":                   {"Bucket", "ExpectedBucketOwner", "Id", "InventoryConfiguration"},
			"put-bucket-lifecycle-configuration":                   {"Bucket", "ChecksumAlgorithm", "ExpectedBucketOwner", "LifecycleConfiguration", "TransitionDefaultMinimumObjectSize"},
			"put-bucket-logging":                                   {"Bucket", "BucketLoggingStatus", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner"},
			"put-bucket-metrics-configuration":                     {"Bucket", "ExpectedBucketOwner", "Id", "MetricsConfiguration"},
			"put-bucket-notification-configuration":                {"Bucket", "ExpectedBucketOwner", "NotificationConfiguration", "SkipDestinationValidation"},
			"put-bucket-ownership-controls":                        {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "OwnershipControls"},
			"put-bucket-policy":                                    {"Bucket", "ChecksumAlgorithm", "ConfirmRemoveSelfBucketAccess", "ContentMD5", "ExpectedBucketOwner", "Policy"},
			"put-bucket-replication":                               {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "ReplicationConfiguration", "Token"},
			"put-bucket-request-payment":                           {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "RequestPaymentConfiguration"},
			"put-bucket-tagging":                                   {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "Tagging"},
			"put-bucket-versioning":                                {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "MFA", "VersioningConfiguration"},
			"put-bucket-website":                                   {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "WebsiteConfiguration"},
			"put-object":                                           {"ACL", "Body", "Bucket", "BucketKeyEnabled", "CacheControl", "ChecksumAlgorithm", "ChecksumCRC32", "ChecksumCRC32C", "ChecksumCRC64NVME", "ChecksumSHA1", "ChecksumSHA256", "ContentDisposition", "ContentEncoding", "ContentLanguage", "ContentLength", "ContentMD5", "ContentType", "ExpectedBucketOwner", "Expires", "GrantFullControl", "GrantRead", "GrantReadACP", "GrantWriteACP", "IfMatch", "IfNoneMatch", "Key", "Metadata", "ObjectLockLegalHoldStatus", "ObjectLockMode", "ObjectLockRetainUntilDate", "RequestPayer", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "SSEKMSEncryptionContext", "SSEKMSKeyId", "ServerSideEncryption", "StorageClass", "Tagging", "WebsiteRedirectLocation", "WriteOffsetBytes"},
			"put-object-acl":                                       {"ACL", "AccessControlPolicy", "Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "GrantFullControl", "GrantRead", "GrantReadACP", "GrantWrite", "GrantWriteACP", "Key", "RequestPayer", "VersionId"},
			"put-object-legal-hold":                                {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "Key", "LegalHold", "RequestPayer", "VersionId"},
			"put-object-lock-configuration":                        {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "ObjectLockConfiguration", "RequestPayer", "Token"},
			"put-object-retention":                                 {"Bucket", "BypassGovernanceRetention", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "Key", "RequestPayer", "Retention", "VersionId"},
			"put-object-tagging":                                   {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "Key", "RequestPayer", "Tagging", "VersionId"},
			"put-public-access-block":                              {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "PublicAccessBlockConfiguration"},
			"rename-object":                                        {"Bucket", "ClientToken", "DestinationIfMatch", "DestinationIfModifiedSince", "DestinationIfNoneMatch", "DestinationIfUnmodifiedSince", "Key", "RenameSource", "SourceIfMatch", "SourceIfModifiedSince", "SourceIfNoneMatch", "SourceIfUnmodifiedSince"},
			"restore-object":                                       {"Bucket", "ChecksumAlgorithm", "ExpectedBucketOwner", "Key", "RequestPayer", "RestoreRequest", "VersionId"},
			"select-object-content":                                {"Bucket", "ExpectedBucketOwner", "Expression", "ExpressionType", "InputSerialization", "Key", "OutputSerialization", "RequestProgress", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "ScanRange"},
			"update-bucket-metadata-inventory-table-configuration": {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "InventoryTableConfiguration"},
			"update-bucket-metadata-journal-table-configuration":   {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "JournalTableConfiguration"},
			"update-object-encryption":                             {"Bucket", "ChecksumAlgorithm", "ContentMD5", "ExpectedBucketOwner", "Key", "ObjectEncryption", "RequestPayer", "VersionId"},
			"upload-part":                                          {"Body", "Bucket", "ChecksumAlgorithm", "ChecksumCRC32", "ChecksumCRC32C", "ChecksumCRC64NVME", "ChecksumSHA1", "ChecksumSHA256", "ContentLength", "ContentMD5", "ExpectedBucketOwner", "Key", "PartNumber", "RequestPayer", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "UploadId"},
			"upload-part-copy":                                     {"Bucket", "CopySource", "CopySourceIfMatch", "CopySourceIfModifiedSince", "CopySourceIfNoneMatch", "CopySourceIfUnmodifiedSince", "CopySourceRange", "CopySourceSSECustomerAlgorithm", "CopySourceSSECustomerKey", "CopySourceSSECustomerKeyMD5", "ExpectedBucketOwner", "ExpectedSourceBucketOwner", "Key", "PartNumber", "RequestPayer", "SSECustomerAlgorithm", "SSECustomerKey", "SSECustomerKeyMD5", "UploadId"},
			"write-get-object-response":                            {"AcceptRanges", "Body", "BucketKeyEnabled", "CacheControl", "ChecksumCRC32", "ChecksumCRC32C", "ChecksumCRC64NVME", "ChecksumSHA1", "ChecksumSHA256", "ContentDisposition", "ContentEncoding", "ContentLanguage", "ContentLength", "ContentRange", "ContentType", "DeleteMarker", "ETag", "ErrorCode", "ErrorMessage", "Expiration", "Expires", "LastModified", "Metadata", "MissingMeta", "ObjectLockLegalHoldStatus", "ObjectLockMode", "ObjectLockRetainUntilDate", "PartsCount", "ReplicationStatus", "RequestCharged", "RequestRoute", "RequestToken", "Restore", "SSECustomerAlgorithm", "SSECustomerKeyMD5", "SSEKMSKeyId", "ServerSideEncryption", "StatusCode", "StorageClass", "TagCount", "VersionId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"abort-multipart-upload":                               {"Bucket": "*string", "ExpectedBucketOwner": "*string", "IfMatchInitiatedTime": "*time.Time", "Key": "*string", "RequestPayer": "types.RequestPayer", "UploadId": "*string"},
			"complete-multipart-upload":                            {"Bucket": "*string", "ChecksumCRC32": "*string", "ChecksumCRC32C": "*string", "ChecksumCRC64NVME": "*string", "ChecksumSHA1": "*string", "ChecksumSHA256": "*string", "ChecksumType": "types.ChecksumType", "ExpectedBucketOwner": "*string", "IfMatch": "*string", "IfNoneMatch": "*string", "Key": "*string", "MpuObjectSize": "*int64", "MultipartUpload": "*types.CompletedMultipartUpload", "RequestPayer": "types.RequestPayer", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "UploadId": "*string"},
			"copy-object":                                          {"ACL": "types.ObjectCannedACL", "Bucket": "*string", "BucketKeyEnabled": "*bool", "CacheControl": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentDisposition": "*string", "ContentEncoding": "*string", "ContentLanguage": "*string", "ContentType": "*string", "CopySource": "*string", "CopySourceIfMatch": "*string", "CopySourceIfModifiedSince": "*time.Time", "CopySourceIfNoneMatch": "*string", "CopySourceIfUnmodifiedSince": "*time.Time", "CopySourceSSECustomerAlgorithm": "*string", "CopySourceSSECustomerKey": "*string", "CopySourceSSECustomerKeyMD5": "*string", "ExpectedBucketOwner": "*string", "ExpectedSourceBucketOwner": "*string", "Expires": "*time.Time", "GrantFullControl": "*string", "GrantRead": "*string", "GrantReadACP": "*string", "GrantWriteACP": "*string", "IfMatch": "*string", "IfNoneMatch": "*string", "Key": "*string", "Metadata": "map[string]string", "MetadataDirective": "types.MetadataDirective", "ObjectLockLegalHoldStatus": "types.ObjectLockLegalHoldStatus", "ObjectLockMode": "types.ObjectLockMode", "ObjectLockRetainUntilDate": "*time.Time", "RequestPayer": "types.RequestPayer", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "SSEKMSEncryptionContext": "*string", "SSEKMSKeyId": "*string", "ServerSideEncryption": "types.ServerSideEncryption", "StorageClass": "types.StorageClass", "Tagging": "*string", "TaggingDirective": "types.TaggingDirective", "WebsiteRedirectLocation": "*string"},
			"create-bucket":                                        {"ACL": "types.BucketCannedACL", "Bucket": "*string", "CreateBucketConfiguration": "*types.CreateBucketConfiguration", "GrantFullControl": "*string", "GrantRead": "*string", "GrantReadACP": "*string", "GrantWrite": "*string", "GrantWriteACP": "*string", "ObjectLockEnabledForBucket": "*bool", "ObjectOwnership": "types.ObjectOwnership"},
			"create-bucket-metadata-configuration":                 {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "MetadataConfiguration": "*types.MetadataConfiguration"},
			"create-bucket-metadata-table-configuration":           {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "MetadataTableConfiguration": "*types.MetadataTableConfiguration"},
			"create-multipart-upload":                              {"ACL": "types.ObjectCannedACL", "Bucket": "*string", "BucketKeyEnabled": "*bool", "CacheControl": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ChecksumType": "types.ChecksumType", "ContentDisposition": "*string", "ContentEncoding": "*string", "ContentLanguage": "*string", "ContentType": "*string", "ExpectedBucketOwner": "*string", "Expires": "*time.Time", "GrantFullControl": "*string", "GrantRead": "*string", "GrantReadACP": "*string", "GrantWriteACP": "*string", "Key": "*string", "Metadata": "map[string]string", "ObjectLockLegalHoldStatus": "types.ObjectLockLegalHoldStatus", "ObjectLockMode": "types.ObjectLockMode", "ObjectLockRetainUntilDate": "*time.Time", "RequestPayer": "types.RequestPayer", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "SSEKMSEncryptionContext": "*string", "SSEKMSKeyId": "*string", "ServerSideEncryption": "types.ServerSideEncryption", "StorageClass": "types.StorageClass", "Tagging": "*string", "WebsiteRedirectLocation": "*string"},
			"create-session":                                       {"Bucket": "*string", "BucketKeyEnabled": "*bool", "SSEKMSEncryptionContext": "*string", "SSEKMSKeyId": "*string", "ServerSideEncryption": "types.ServerSideEncryption", "SessionMode": "types.SessionMode"},
			"delete-bucket":                                        {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-analytics-configuration":                {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"delete-bucket-cors":                                   {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-encryption":                             {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-intelligent-tiering-configuration":      {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"delete-bucket-inventory-configuration":                {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"delete-bucket-lifecycle":                              {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-metadata-configuration":                 {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-metadata-table-configuration":           {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-metrics-configuration":                  {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"delete-bucket-ownership-controls":                     {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-policy":                                 {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-replication":                            {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-tagging":                                {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-bucket-website":                                {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"delete-object":                                        {"Bucket": "*string", "BypassGovernanceRetention": "*bool", "ExpectedBucketOwner": "*string", "IfMatch": "*string", "IfMatchLastModifiedTime": "*time.Time", "IfMatchSize": "*int64", "Key": "*string", "MFA": "*string", "RequestPayer": "types.RequestPayer", "VersionId": "*string"},
			"delete-object-tagging":                                {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "VersionId": "*string"},
			"delete-objects":                                       {"Bucket": "*string", "BypassGovernanceRetention": "*bool", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "Delete": "*types.Delete", "ExpectedBucketOwner": "*string", "MFA": "*string", "RequestPayer": "types.RequestPayer"},
			"delete-public-access-block":                           {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-abac":                                      {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-accelerate-configuration":                  {"Bucket": "*string", "ExpectedBucketOwner": "*string", "RequestPayer": "types.RequestPayer"},
			"get-bucket-acl":                                       {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-analytics-configuration":                   {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"get-bucket-cors":                                      {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-encryption":                                {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-intelligent-tiering-configuration":         {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"get-bucket-inventory-configuration":                   {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"get-bucket-lifecycle-configuration":                   {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-location":                                  {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-logging":                                   {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-metadata-configuration":                    {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-metadata-table-configuration":              {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-metrics-configuration":                     {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"get-bucket-notification-configuration":                {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-ownership-controls":                        {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-policy":                                    {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-policy-status":                             {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-replication":                               {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-request-payment":                           {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-tagging":                                   {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-versioning":                                {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-bucket-website":                                   {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-object":                                           {"Bucket": "*string", "ChecksumMode": "types.ChecksumMode", "ExpectedBucketOwner": "*string", "IfMatch": "*string", "IfModifiedSince": "*time.Time", "IfNoneMatch": "*string", "IfUnmodifiedSince": "*time.Time", "Key": "*string", "PartNumber": "*int32", "Range": "*string", "RequestPayer": "types.RequestPayer", "ResponseCacheControl": "*string", "ResponseContentDisposition": "*string", "ResponseContentEncoding": "*string", "ResponseContentLanguage": "*string", "ResponseContentType": "*string", "ResponseExpires": "*time.Time", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "VersionId": "*string"},
			"get-object-acl":                                       {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer", "VersionId": "*string"},
			"get-object-attributes":                                {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "MaxParts": "*int32", "ObjectAttributes": "[]types.ObjectAttributes", "PartNumberMarker": "*string", "RequestPayer": "types.RequestPayer", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "VersionId": "*string"},
			"get-object-legal-hold":                                {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer", "VersionId": "*string"},
			"get-object-lock-configuration":                        {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"get-object-retention":                                 {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer", "VersionId": "*string"},
			"get-object-tagging":                                   {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer", "VersionId": "*string"},
			"get-object-torrent":                                   {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer"},
			"get-public-access-block":                              {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"head-bucket":                                          {"Bucket": "*string", "ExpectedBucketOwner": "*string"},
			"head-object":                                          {"Bucket": "*string", "ChecksumMode": "types.ChecksumMode", "ExpectedBucketOwner": "*string", "IfMatch": "*string", "IfModifiedSince": "*time.Time", "IfNoneMatch": "*string", "IfUnmodifiedSince": "*time.Time", "Key": "*string", "PartNumber": "*int32", "Range": "*string", "RequestPayer": "types.RequestPayer", "ResponseCacheControl": "*string", "ResponseContentDisposition": "*string", "ResponseContentEncoding": "*string", "ResponseContentLanguage": "*string", "ResponseContentType": "*string", "ResponseExpires": "*time.Time", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "VersionId": "*string"},
			"list-bucket-analytics-configurations":                 {"Bucket": "*string", "ContinuationToken": "*string", "ExpectedBucketOwner": "*string"},
			"list-bucket-intelligent-tiering-configurations":       {"Bucket": "*string", "ContinuationToken": "*string", "ExpectedBucketOwner": "*string"},
			"list-bucket-inventory-configurations":                 {"Bucket": "*string", "ContinuationToken": "*string", "ExpectedBucketOwner": "*string"},
			"list-bucket-metrics-configurations":                   {"Bucket": "*string", "ContinuationToken": "*string", "ExpectedBucketOwner": "*string"},
			"list-buckets":                                         {"BucketRegion": "*string", "ContinuationToken": "*string", "MaxBuckets": "*int32", "Prefix": "*string"},
			"list-directory-buckets":                               {"ContinuationToken": "*string", "MaxDirectoryBuckets": "*int32"},
			"list-multipart-uploads":                               {"Bucket": "*string", "Delimiter": "*string", "EncodingType": "types.EncodingType", "ExpectedBucketOwner": "*string", "KeyMarker": "*string", "MaxUploads": "*int32", "Prefix": "*string", "RequestPayer": "types.RequestPayer", "UploadIdMarker": "*string"},
			"list-object-versions":                                 {"Bucket": "*string", "Delimiter": "*string", "EncodingType": "types.EncodingType", "ExpectedBucketOwner": "*string", "KeyMarker": "*string", "MaxKeys": "*int32", "OptionalObjectAttributes": "[]types.OptionalObjectAttributes", "Prefix": "*string", "RequestPayer": "types.RequestPayer", "VersionIdMarker": "*string"},
			"list-objects":                                         {"Bucket": "*string", "Delimiter": "*string", "EncodingType": "types.EncodingType", "ExpectedBucketOwner": "*string", "Marker": "*string", "MaxKeys": "*int32", "OptionalObjectAttributes": "[]types.OptionalObjectAttributes", "Prefix": "*string", "RequestPayer": "types.RequestPayer"},
			"list-objects-v2":                                      {"Bucket": "*string", "ContinuationToken": "*string", "Delimiter": "*string", "EncodingType": "types.EncodingType", "ExpectedBucketOwner": "*string", "FetchOwner": "*bool", "MaxKeys": "*int32", "OptionalObjectAttributes": "[]types.OptionalObjectAttributes", "Prefix": "*string", "RequestPayer": "types.RequestPayer", "StartAfter": "*string"},
			"list-parts":                                           {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "MaxParts": "*int32", "PartNumberMarker": "*string", "RequestPayer": "types.RequestPayer", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "UploadId": "*string"},
			"put-bucket-abac":                                      {"AbacStatus": "*types.AbacStatus", "Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string"},
			"put-bucket-accelerate-configuration":                  {"AccelerateConfiguration": "*types.AccelerateConfiguration", "Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ExpectedBucketOwner": "*string"},
			"put-bucket-acl":                                       {"ACL": "types.BucketCannedACL", "AccessControlPolicy": "*types.AccessControlPolicy", "Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "GrantFullControl": "*string", "GrantRead": "*string", "GrantReadACP": "*string", "GrantWrite": "*string", "GrantWriteACP": "*string"},
			"put-bucket-analytics-configuration":                   {"AnalyticsConfiguration": "*types.AnalyticsConfiguration", "Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string"},
			"put-bucket-cors":                                      {"Bucket": "*string", "CORSConfiguration": "*types.CORSConfiguration", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string"},
			"put-bucket-encryption":                                {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "ServerSideEncryptionConfiguration": "*types.ServerSideEncryptionConfiguration"},
			"put-bucket-intelligent-tiering-configuration":         {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string", "IntelligentTieringConfiguration": "*types.IntelligentTieringConfiguration"},
			"put-bucket-inventory-configuration":                   {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string", "InventoryConfiguration": "*types.InventoryConfiguration"},
			"put-bucket-lifecycle-configuration":                   {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ExpectedBucketOwner": "*string", "LifecycleConfiguration": "*types.BucketLifecycleConfiguration", "TransitionDefaultMinimumObjectSize": "types.TransitionDefaultMinimumObjectSize"},
			"put-bucket-logging":                                   {"Bucket": "*string", "BucketLoggingStatus": "*types.BucketLoggingStatus", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string"},
			"put-bucket-metrics-configuration":                     {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Id": "*string", "MetricsConfiguration": "*types.MetricsConfiguration"},
			"put-bucket-notification-configuration":                {"Bucket": "*string", "ExpectedBucketOwner": "*string", "NotificationConfiguration": "*types.NotificationConfiguration", "SkipDestinationValidation": "*bool"},
			"put-bucket-ownership-controls":                        {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "OwnershipControls": "*types.OwnershipControls"},
			"put-bucket-policy":                                    {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ConfirmRemoveSelfBucketAccess": "*bool", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "Policy": "*string"},
			"put-bucket-replication":                               {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "ReplicationConfiguration": "*types.ReplicationConfiguration", "Token": "*string"},
			"put-bucket-request-payment":                           {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "RequestPaymentConfiguration": "*types.RequestPaymentConfiguration"},
			"put-bucket-tagging":                                   {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "Tagging": "*types.Tagging"},
			"put-bucket-versioning":                                {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "MFA": "*string", "VersioningConfiguration": "*types.VersioningConfiguration"},
			"put-bucket-website":                                   {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "WebsiteConfiguration": "*types.WebsiteConfiguration"},
			"put-object":                                           {"ACL": "types.ObjectCannedACL", "Body": "io.Reader", "Bucket": "*string", "BucketKeyEnabled": "*bool", "CacheControl": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ChecksumCRC32": "*string", "ChecksumCRC32C": "*string", "ChecksumCRC64NVME": "*string", "ChecksumSHA1": "*string", "ChecksumSHA256": "*string", "ContentDisposition": "*string", "ContentEncoding": "*string", "ContentLanguage": "*string", "ContentLength": "*int64", "ContentMD5": "*string", "ContentType": "*string", "ExpectedBucketOwner": "*string", "Expires": "*time.Time", "GrantFullControl": "*string", "GrantRead": "*string", "GrantReadACP": "*string", "GrantWriteACP": "*string", "IfMatch": "*string", "IfNoneMatch": "*string", "Key": "*string", "Metadata": "map[string]string", "ObjectLockLegalHoldStatus": "types.ObjectLockLegalHoldStatus", "ObjectLockMode": "types.ObjectLockMode", "ObjectLockRetainUntilDate": "*time.Time", "RequestPayer": "types.RequestPayer", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "SSEKMSEncryptionContext": "*string", "SSEKMSKeyId": "*string", "ServerSideEncryption": "types.ServerSideEncryption", "StorageClass": "types.StorageClass", "Tagging": "*string", "WebsiteRedirectLocation": "*string", "WriteOffsetBytes": "*int64"},
			"put-object-acl":                                       {"ACL": "types.ObjectCannedACL", "AccessControlPolicy": "*types.AccessControlPolicy", "Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "GrantFullControl": "*string", "GrantRead": "*string", "GrantReadACP": "*string", "GrantWrite": "*string", "GrantWriteACP": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer", "VersionId": "*string"},
			"put-object-legal-hold":                                {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "LegalHold": "*types.ObjectLockLegalHold", "RequestPayer": "types.RequestPayer", "VersionId": "*string"},
			"put-object-lock-configuration":                        {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "ObjectLockConfiguration": "*types.ObjectLockConfiguration", "RequestPayer": "types.RequestPayer", "Token": "*string"},
			"put-object-retention":                                 {"Bucket": "*string", "BypassGovernanceRetention": "*bool", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer", "Retention": "*types.ObjectLockRetention", "VersionId": "*string"},
			"put-object-tagging":                                   {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer", "Tagging": "*types.Tagging", "VersionId": "*string"},
			"put-public-access-block":                              {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "PublicAccessBlockConfiguration": "*types.PublicAccessBlockConfiguration"},
			"rename-object":                                        {"Bucket": "*string", "ClientToken": "*string", "DestinationIfMatch": "*string", "DestinationIfModifiedSince": "*time.Time", "DestinationIfNoneMatch": "*string", "DestinationIfUnmodifiedSince": "*time.Time", "Key": "*string", "RenameSource": "*string", "SourceIfMatch": "*string", "SourceIfModifiedSince": "*time.Time", "SourceIfNoneMatch": "*string", "SourceIfUnmodifiedSince": "*time.Time"},
			"restore-object":                                       {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ExpectedBucketOwner": "*string", "Key": "*string", "RequestPayer": "types.RequestPayer", "RestoreRequest": "*types.RestoreRequest", "VersionId": "*string"},
			"select-object-content":                                {"Bucket": "*string", "ExpectedBucketOwner": "*string", "Expression": "*string", "ExpressionType": "types.ExpressionType", "InputSerialization": "*types.InputSerialization", "Key": "*string", "OutputSerialization": "*types.OutputSerialization", "RequestProgress": "*types.RequestProgress", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "ScanRange": "*types.ScanRange"},
			"update-bucket-metadata-inventory-table-configuration": {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "InventoryTableConfiguration": "*types.InventoryTableConfigurationUpdates"},
			"update-bucket-metadata-journal-table-configuration":   {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "JournalTableConfiguration": "*types.JournalTableConfigurationUpdates"},
			"update-object-encryption":                             {"Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "ObjectEncryption": "types.ObjectEncryption", "RequestPayer": "types.RequestPayer", "VersionId": "*string"},
			"upload-part":                                          {"Body": "io.Reader", "Bucket": "*string", "ChecksumAlgorithm": "types.ChecksumAlgorithm", "ChecksumCRC32": "*string", "ChecksumCRC32C": "*string", "ChecksumCRC64NVME": "*string", "ChecksumSHA1": "*string", "ChecksumSHA256": "*string", "ContentLength": "*int64", "ContentMD5": "*string", "ExpectedBucketOwner": "*string", "Key": "*string", "PartNumber": "*int32", "RequestPayer": "types.RequestPayer", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "UploadId": "*string"},
			"upload-part-copy":                                     {"Bucket": "*string", "CopySource": "*string", "CopySourceIfMatch": "*string", "CopySourceIfModifiedSince": "*time.Time", "CopySourceIfNoneMatch": "*string", "CopySourceIfUnmodifiedSince": "*time.Time", "CopySourceRange": "*string", "CopySourceSSECustomerAlgorithm": "*string", "CopySourceSSECustomerKey": "*string", "CopySourceSSECustomerKeyMD5": "*string", "ExpectedBucketOwner": "*string", "ExpectedSourceBucketOwner": "*string", "Key": "*string", "PartNumber": "*int32", "RequestPayer": "types.RequestPayer", "SSECustomerAlgorithm": "*string", "SSECustomerKey": "*string", "SSECustomerKeyMD5": "*string", "UploadId": "*string"},
			"write-get-object-response":                            {"AcceptRanges": "*string", "Body": "io.Reader", "BucketKeyEnabled": "*bool", "CacheControl": "*string", "ChecksumCRC32": "*string", "ChecksumCRC32C": "*string", "ChecksumCRC64NVME": "*string", "ChecksumSHA1": "*string", "ChecksumSHA256": "*string", "ContentDisposition": "*string", "ContentEncoding": "*string", "ContentLanguage": "*string", "ContentLength": "*int64", "ContentRange": "*string", "ContentType": "*string", "DeleteMarker": "*bool", "ETag": "*string", "ErrorCode": "*string", "ErrorMessage": "*string", "Expiration": "*string", "Expires": "*time.Time", "LastModified": "*time.Time", "Metadata": "map[string]string", "MissingMeta": "*int32", "ObjectLockLegalHoldStatus": "types.ObjectLockLegalHoldStatus", "ObjectLockMode": "types.ObjectLockMode", "ObjectLockRetainUntilDate": "*time.Time", "PartsCount": "*int32", "ReplicationStatus": "types.ReplicationStatus", "RequestCharged": "types.RequestCharged", "RequestRoute": "*string", "RequestToken": "*string", "Restore": "*string", "SSECustomerAlgorithm": "*string", "SSECustomerKeyMD5": "*string", "SSEKMSKeyId": "*string", "ServerSideEncryption": "types.ServerSideEncryption", "StatusCode": "*int32", "StorageClass": "types.StorageClass", "TagCount": "*int32", "VersionId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"abort-multipart-upload":                               {"Bucket", "Key", "UploadId"},
			"complete-multipart-upload":                            {"Bucket", "Key", "UploadId"},
			"copy-object":                                          {"Bucket", "CopySource", "Key"},
			"create-bucket":                                        {"Bucket"},
			"create-bucket-metadata-configuration":                 {"Bucket", "MetadataConfiguration"},
			"create-bucket-metadata-table-configuration":           {"Bucket", "MetadataTableConfiguration"},
			"create-multipart-upload":                              {"Bucket", "Key"},
			"create-session":                                       {"Bucket"},
			"delete-bucket":                                        {"Bucket"},
			"delete-bucket-analytics-configuration":                {"Bucket", "Id"},
			"delete-bucket-cors":                                   {"Bucket"},
			"delete-bucket-encryption":                             {"Bucket"},
			"delete-bucket-intelligent-tiering-configuration":      {"Bucket", "Id"},
			"delete-bucket-inventory-configuration":                {"Bucket", "Id"},
			"delete-bucket-lifecycle":                              {"Bucket"},
			"delete-bucket-metadata-configuration":                 {"Bucket"},
			"delete-bucket-metadata-table-configuration":           {"Bucket"},
			"delete-bucket-metrics-configuration":                  {"Bucket", "Id"},
			"delete-bucket-ownership-controls":                     {"Bucket"},
			"delete-bucket-policy":                                 {"Bucket"},
			"delete-bucket-replication":                            {"Bucket"},
			"delete-bucket-tagging":                                {"Bucket"},
			"delete-bucket-website":                                {"Bucket"},
			"delete-object":                                        {"Bucket", "Key"},
			"delete-object-tagging":                                {"Bucket", "Key"},
			"delete-objects":                                       {"Bucket", "Delete"},
			"delete-public-access-block":                           {"Bucket"},
			"get-bucket-abac":                                      {"Bucket"},
			"get-bucket-accelerate-configuration":                  {"Bucket"},
			"get-bucket-acl":                                       {"Bucket"},
			"get-bucket-analytics-configuration":                   {"Bucket", "Id"},
			"get-bucket-cors":                                      {"Bucket"},
			"get-bucket-encryption":                                {"Bucket"},
			"get-bucket-intelligent-tiering-configuration":         {"Bucket", "Id"},
			"get-bucket-inventory-configuration":                   {"Bucket", "Id"},
			"get-bucket-lifecycle-configuration":                   {"Bucket"},
			"get-bucket-location":                                  {"Bucket"},
			"get-bucket-logging":                                   {"Bucket"},
			"get-bucket-metadata-configuration":                    {"Bucket"},
			"get-bucket-metadata-table-configuration":              {"Bucket"},
			"get-bucket-metrics-configuration":                     {"Bucket", "Id"},
			"get-bucket-notification-configuration":                {"Bucket"},
			"get-bucket-ownership-controls":                        {"Bucket"},
			"get-bucket-policy":                                    {"Bucket"},
			"get-bucket-policy-status":                             {"Bucket"},
			"get-bucket-replication":                               {"Bucket"},
			"get-bucket-request-payment":                           {"Bucket"},
			"get-bucket-tagging":                                   {"Bucket"},
			"get-bucket-versioning":                                {"Bucket"},
			"get-bucket-website":                                   {"Bucket"},
			"get-object":                                           {"Bucket", "Key"},
			"get-object-acl":                                       {"Bucket", "Key"},
			"get-object-attributes":                                {"Bucket", "Key", "ObjectAttributes"},
			"get-object-legal-hold":                                {"Bucket", "Key"},
			"get-object-lock-configuration":                        {"Bucket"},
			"get-object-retention":                                 {"Bucket", "Key"},
			"get-object-tagging":                                   {"Bucket", "Key"},
			"get-object-torrent":                                   {"Bucket", "Key"},
			"get-public-access-block":                              {"Bucket"},
			"head-bucket":                                          {"Bucket"},
			"head-object":                                          {"Bucket", "Key"},
			"list-bucket-analytics-configurations":                 {"Bucket"},
			"list-bucket-intelligent-tiering-configurations":       {"Bucket"},
			"list-bucket-inventory-configurations":                 {"Bucket"},
			"list-bucket-metrics-configurations":                   {"Bucket"},
			"list-buckets":                                         {},
			"list-directory-buckets":                               {},
			"list-multipart-uploads":                               {"Bucket"},
			"list-object-versions":                                 {"Bucket"},
			"list-objects":                                         {"Bucket"},
			"list-objects-v2":                                      {"Bucket"},
			"list-parts":                                           {"Bucket", "Key", "UploadId"},
			"put-bucket-abac":                                      {"AbacStatus", "Bucket"},
			"put-bucket-accelerate-configuration":                  {"AccelerateConfiguration", "Bucket"},
			"put-bucket-acl":                                       {"Bucket"},
			"put-bucket-analytics-configuration":                   {"AnalyticsConfiguration", "Bucket", "Id"},
			"put-bucket-cors":                                      {"Bucket", "CORSConfiguration"},
			"put-bucket-encryption":                                {"Bucket", "ServerSideEncryptionConfiguration"},
			"put-bucket-intelligent-tiering-configuration":         {"Bucket", "Id", "IntelligentTieringConfiguration"},
			"put-bucket-inventory-configuration":                   {"Bucket", "Id", "InventoryConfiguration"},
			"put-bucket-lifecycle-configuration":                   {"Bucket"},
			"put-bucket-logging":                                   {"Bucket", "BucketLoggingStatus"},
			"put-bucket-metrics-configuration":                     {"Bucket", "Id", "MetricsConfiguration"},
			"put-bucket-notification-configuration":                {"Bucket", "NotificationConfiguration"},
			"put-bucket-ownership-controls":                        {"Bucket", "OwnershipControls"},
			"put-bucket-policy":                                    {"Bucket", "Policy"},
			"put-bucket-replication":                               {"Bucket", "ReplicationConfiguration"},
			"put-bucket-request-payment":                           {"Bucket", "RequestPaymentConfiguration"},
			"put-bucket-tagging":                                   {"Bucket", "Tagging"},
			"put-bucket-versioning":                                {"Bucket", "VersioningConfiguration"},
			"put-bucket-website":                                   {"Bucket", "WebsiteConfiguration"},
			"put-object":                                           {"Bucket", "Key"},
			"put-object-acl":                                       {"Bucket", "Key"},
			"put-object-legal-hold":                                {"Bucket", "Key"},
			"put-object-lock-configuration":                        {"Bucket"},
			"put-object-retention":                                 {"Bucket", "Key"},
			"put-object-tagging":                                   {"Bucket", "Key", "Tagging"},
			"put-public-access-block":                              {"Bucket", "PublicAccessBlockConfiguration"},
			"rename-object":                                        {"Bucket", "Key", "RenameSource"},
			"restore-object":                                       {"Bucket", "Key"},
			"select-object-content":                                {"Bucket", "Expression", "ExpressionType", "InputSerialization", "Key", "OutputSerialization"},
			"update-bucket-metadata-inventory-table-configuration": {"Bucket", "InventoryTableConfiguration"},
			"update-bucket-metadata-journal-table-configuration":   {"Bucket", "JournalTableConfiguration"},
			"update-object-encryption":                             {"Bucket", "Key", "ObjectEncryption"},
			"upload-part":                                          {"Bucket", "Key", "PartNumber", "UploadId"},
			"upload-part-copy":                                     {"Bucket", "CopySource", "Key", "PartNumber", "UploadId"},
			"write-get-object-response":                            {"RequestRoute", "RequestToken"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("s3", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
