package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/directoryservice/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-shared-directory", "add-ip-routes", "add-region", "add-tags-to-resource", "cancel-schema-extension", "connect-directory", "create-alias", "create-computer", "create-conditional-forwarder", "create-directory", "create-hybrid-ad", "create-log-subscription", "create-microsoft-ad", "create-snapshot", "create-trust", "delete-ad-assessment", "delete-conditional-forwarder", "delete-directory", "delete-log-subscription", "delete-snapshot", "delete-trust", "deregister-certificate", "deregister-event-topic", "describe-ad-assessment", "describe-ca-enrollment-policy", "describe-certificate", "describe-client-authentication-settings", "describe-conditional-forwarders", "describe-directories", "describe-directory-data-access", "describe-domain-controllers", "describe-event-topics", "describe-hybrid-ad-update", "describe-ldaps-settings", "describe-regions", "describe-settings", "describe-shared-directories", "describe-snapshots", "describe-trusts", "describe-update-directory", "disable-ca-enrollment-policy", "disable-client-authentication", "disable-directory-data-access", "disable-ldaps", "disable-radius", "disable-sso", "enable-ca-enrollment-policy", "enable-client-authentication", "enable-directory-data-access", "enable-ldaps", "enable-radius", "enable-sso", "get-directory-limits", "get-snapshot-limits", "list-ad-assessments", "list-certificates", "list-ip-routes", "list-log-subscriptions", "list-schema-extensions", "list-tags-for-resource", "register-certificate", "register-event-topic", "reject-shared-directory", "remove-ip-routes", "remove-region", "remove-tags-from-resource", "reset-user-password", "restore-from-snapshot", "share-directory", "start-ad-assessment", "start-schema-extension", "unshare-directory", "update-conditional-forwarder", "update-directory-setup", "update-hybrid-ad", "update-number-of-domain-controllers", "update-radius", "update-settings", "update-trust", "verify-trust"},
		OperationSet: map[string]bool{"accept-shared-directory": true, "add-ip-routes": true, "add-region": true, "add-tags-to-resource": true, "cancel-schema-extension": true, "connect-directory": true, "create-alias": true, "create-computer": true, "create-conditional-forwarder": true, "create-directory": true, "create-hybrid-ad": true, "create-log-subscription": true, "create-microsoft-ad": true, "create-snapshot": true, "create-trust": true, "delete-ad-assessment": true, "delete-conditional-forwarder": true, "delete-directory": true, "delete-log-subscription": true, "delete-snapshot": true, "delete-trust": true, "deregister-certificate": true, "deregister-event-topic": true, "describe-ad-assessment": true, "describe-ca-enrollment-policy": true, "describe-certificate": true, "describe-client-authentication-settings": true, "describe-conditional-forwarders": true, "describe-directories": true, "describe-directory-data-access": true, "describe-domain-controllers": true, "describe-event-topics": true, "describe-hybrid-ad-update": true, "describe-ldaps-settings": true, "describe-regions": true, "describe-settings": true, "describe-shared-directories": true, "describe-snapshots": true, "describe-trusts": true, "describe-update-directory": true, "disable-ca-enrollment-policy": true, "disable-client-authentication": true, "disable-directory-data-access": true, "disable-ldaps": true, "disable-radius": true, "disable-sso": true, "enable-ca-enrollment-policy": true, "enable-client-authentication": true, "enable-directory-data-access": true, "enable-ldaps": true, "enable-radius": true, "enable-sso": true, "get-directory-limits": true, "get-snapshot-limits": true, "list-ad-assessments": true, "list-certificates": true, "list-ip-routes": true, "list-log-subscriptions": true, "list-schema-extensions": true, "list-tags-for-resource": true, "register-certificate": true, "register-event-topic": true, "reject-shared-directory": true, "remove-ip-routes": true, "remove-region": true, "remove-tags-from-resource": true, "reset-user-password": true, "restore-from-snapshot": true, "share-directory": true, "start-ad-assessment": true, "start-schema-extension": true, "unshare-directory": true, "update-conditional-forwarder": true, "update-directory-setup": true, "update-hybrid-ad": true, "update-number-of-domain-controllers": true, "update-radius": true, "update-settings": true, "update-trust": true, "verify-trust": true},
		OperationInputs: map[string][]string{
			"accept-shared-directory":                 {"SharedDirectoryId"},
			"add-ip-routes":                           {"DirectoryId", "IpRoutes", "UpdateSecurityGroupForDirectoryControllers"},
			"add-region":                              {"DirectoryId", "RegionName", "VPCSettings"},
			"add-tags-to-resource":                    {"ResourceId", "Tags"},
			"cancel-schema-extension":                 {"DirectoryId", "SchemaExtensionId"},
			"connect-directory":                       {"ConnectSettings", "Description", "Name", "NetworkType", "Password", "ShortName", "Size", "Tags"},
			"create-alias":                            {"Alias", "DirectoryId"},
			"create-computer":                         {"ComputerAttributes", "ComputerName", "DirectoryId", "OrganizationalUnitDistinguishedName", "Password"},
			"create-conditional-forwarder":            {"DirectoryId", "DnsIpAddrs", "DnsIpv6Addrs", "RemoteDomainName"},
			"create-directory":                        {"Description", "Name", "NetworkType", "Password", "ShortName", "Size", "Tags", "VpcSettings"},
			"create-hybrid-ad":                        {"AssessmentId", "SecretArn", "Tags"},
			"create-log-subscription":                 {"DirectoryId", "LogGroupName"},
			"create-microsoft-ad":                     {"Description", "Edition", "Name", "NetworkType", "Password", "ShortName", "Tags", "VpcSettings"},
			"create-snapshot":                         {"DirectoryId", "Name"},
			"create-trust":                            {"ConditionalForwarderIpAddrs", "ConditionalForwarderIpv6Addrs", "DirectoryId", "RemoteDomainName", "SelectiveAuth", "TrustDirection", "TrustPassword", "TrustType"},
			"delete-ad-assessment":                    {"AssessmentId"},
			"delete-conditional-forwarder":            {"DirectoryId", "RemoteDomainName"},
			"delete-directory":                        {"DirectoryId"},
			"delete-log-subscription":                 {"DirectoryId"},
			"delete-snapshot":                         {"SnapshotId"},
			"delete-trust":                            {"DeleteAssociatedConditionalForwarder", "TrustId"},
			"deregister-certificate":                  {"CertificateId", "DirectoryId"},
			"deregister-event-topic":                  {"DirectoryId", "TopicName"},
			"describe-ad-assessment":                  {"AssessmentId"},
			"describe-ca-enrollment-policy":           {"DirectoryId"},
			"describe-certificate":                    {"CertificateId", "DirectoryId"},
			"describe-client-authentication-settings": {"DirectoryId", "Limit", "NextToken", "Type"},
			"describe-conditional-forwarders":         {"DirectoryId", "RemoteDomainNames"},
			"describe-directories":                    {"DirectoryIds", "Limit", "NextToken"},
			"describe-directory-data-access":          {"DirectoryId"},
			"describe-domain-controllers":             {"DirectoryId", "DomainControllerIds", "Limit", "NextToken"},
			"describe-event-topics":                   {"DirectoryId", "TopicNames"},
			"describe-hybrid-ad-update":               {"DirectoryId", "NextToken", "UpdateType"},
			"describe-ldaps-settings":                 {"DirectoryId", "Limit", "NextToken", "Type"},
			"describe-regions":                        {"DirectoryId", "NextToken", "RegionName"},
			"describe-settings":                       {"DirectoryId", "NextToken", "Status"},
			"describe-shared-directories":             {"Limit", "NextToken", "OwnerDirectoryId", "SharedDirectoryIds"},
			"describe-snapshots":                      {"DirectoryId", "Limit", "NextToken", "SnapshotIds"},
			"describe-trusts":                         {"DirectoryId", "Limit", "NextToken", "TrustIds"},
			"describe-update-directory":               {"DirectoryId", "NextToken", "RegionName", "UpdateType"},
			"disable-ca-enrollment-policy":            {"DirectoryId"},
			"disable-client-authentication":           {"DirectoryId", "Type"},
			"disable-directory-data-access":           {"DirectoryId"},
			"disable-ldaps":                           {"DirectoryId", "Type"},
			"disable-radius":                          {"DirectoryId"},
			"disable-sso":                             {"DirectoryId", "Password", "UserName"},
			"enable-ca-enrollment-policy":             {"DirectoryId", "PcaConnectorArn"},
			"enable-client-authentication":            {"DirectoryId", "Type"},
			"enable-directory-data-access":            {"DirectoryId"},
			"enable-ldaps":                            {"DirectoryId", "Type"},
			"enable-radius":                           {"DirectoryId", "RadiusSettings"},
			"enable-sso":                              {"DirectoryId", "Password", "UserName"},
			"get-directory-limits":                    {},
			"get-snapshot-limits":                     {"DirectoryId"},
			"list-ad-assessments":                     {"DirectoryId", "Limit", "NextToken"},
			"list-certificates":                       {"DirectoryId", "Limit", "NextToken"},
			"list-ip-routes":                          {"DirectoryId", "Limit", "NextToken"},
			"list-log-subscriptions":                  {"DirectoryId", "Limit", "NextToken"},
			"list-schema-extensions":                  {"DirectoryId", "Limit", "NextToken"},
			"list-tags-for-resource":                  {"Limit", "NextToken", "ResourceId"},
			"register-certificate":                    {"CertificateData", "ClientCertAuthSettings", "DirectoryId", "Type"},
			"register-event-topic":                    {"DirectoryId", "TopicName"},
			"reject-shared-directory":                 {"SharedDirectoryId"},
			"remove-ip-routes":                        {"CidrIps", "CidrIpv6s", "DirectoryId"},
			"remove-region":                           {"DirectoryId"},
			"remove-tags-from-resource":               {"ResourceId", "TagKeys"},
			"reset-user-password":                     {"DirectoryId", "NewPassword", "UserName"},
			"restore-from-snapshot":                   {"SnapshotId"},
			"share-directory":                         {"DirectoryId", "ShareMethod", "ShareNotes", "ShareTarget"},
			"start-ad-assessment":                     {"AssessmentConfiguration", "DirectoryId"},
			"start-schema-extension":                  {"CreateSnapshotBeforeSchemaExtension", "Description", "DirectoryId", "LdifContent"},
			"unshare-directory":                       {"DirectoryId", "UnshareTarget"},
			"update-conditional-forwarder":            {"DirectoryId", "DnsIpAddrs", "DnsIpv6Addrs", "RemoteDomainName"},
			"update-directory-setup":                  {"CreateSnapshotBeforeUpdate", "DirectoryId", "DirectorySizeUpdateSettings", "NetworkUpdateSettings", "OSUpdateSettings", "UpdateType"},
			"update-hybrid-ad":                        {"DirectoryId", "HybridAdministratorAccountUpdate", "SelfManagedInstancesSettings"},
			"update-number-of-domain-controllers":     {"DesiredNumber", "DirectoryId"},
			"update-radius":                           {"DirectoryId", "RadiusSettings"},
			"update-settings":                         {"DirectoryId", "Settings"},
			"update-trust":                            {"SelectiveAuth", "TrustId"},
			"verify-trust":                            {"TrustId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-shared-directory":                 {"SharedDirectoryId": "*string"},
			"add-ip-routes":                           {"DirectoryId": "*string", "IpRoutes": "[]types.IpRoute", "UpdateSecurityGroupForDirectoryControllers": "bool"},
			"add-region":                              {"DirectoryId": "*string", "RegionName": "*string", "VPCSettings": "*types.DirectoryVpcSettings"},
			"add-tags-to-resource":                    {"ResourceId": "*string", "Tags": "[]types.Tag"},
			"cancel-schema-extension":                 {"DirectoryId": "*string", "SchemaExtensionId": "*string"},
			"connect-directory":                       {"ConnectSettings": "*types.DirectoryConnectSettings", "Description": "*string", "Name": "*string", "NetworkType": "types.NetworkType", "Password": "*string", "ShortName": "*string", "Size": "types.DirectorySize", "Tags": "[]types.Tag"},
			"create-alias":                            {"Alias": "*string", "DirectoryId": "*string"},
			"create-computer":                         {"ComputerAttributes": "[]types.Attribute", "ComputerName": "*string", "DirectoryId": "*string", "OrganizationalUnitDistinguishedName": "*string", "Password": "*string"},
			"create-conditional-forwarder":            {"DirectoryId": "*string", "DnsIpAddrs": "[]string", "DnsIpv6Addrs": "[]string", "RemoteDomainName": "*string"},
			"create-directory":                        {"Description": "*string", "Name": "*string", "NetworkType": "types.NetworkType", "Password": "*string", "ShortName": "*string", "Size": "types.DirectorySize", "Tags": "[]types.Tag", "VpcSettings": "*types.DirectoryVpcSettings"},
			"create-hybrid-ad":                        {"AssessmentId": "*string", "SecretArn": "*string", "Tags": "[]types.Tag"},
			"create-log-subscription":                 {"DirectoryId": "*string", "LogGroupName": "*string"},
			"create-microsoft-ad":                     {"Description": "*string", "Edition": "types.DirectoryEdition", "Name": "*string", "NetworkType": "types.NetworkType", "Password": "*string", "ShortName": "*string", "Tags": "[]types.Tag", "VpcSettings": "*types.DirectoryVpcSettings"},
			"create-snapshot":                         {"DirectoryId": "*string", "Name": "*string"},
			"create-trust":                            {"ConditionalForwarderIpAddrs": "[]string", "ConditionalForwarderIpv6Addrs": "[]string", "DirectoryId": "*string", "RemoteDomainName": "*string", "SelectiveAuth": "types.SelectiveAuth", "TrustDirection": "types.TrustDirection", "TrustPassword": "*string", "TrustType": "types.TrustType"},
			"delete-ad-assessment":                    {"AssessmentId": "*string"},
			"delete-conditional-forwarder":            {"DirectoryId": "*string", "RemoteDomainName": "*string"},
			"delete-directory":                        {"DirectoryId": "*string"},
			"delete-log-subscription":                 {"DirectoryId": "*string"},
			"delete-snapshot":                         {"SnapshotId": "*string"},
			"delete-trust":                            {"DeleteAssociatedConditionalForwarder": "bool", "TrustId": "*string"},
			"deregister-certificate":                  {"CertificateId": "*string", "DirectoryId": "*string"},
			"deregister-event-topic":                  {"DirectoryId": "*string", "TopicName": "*string"},
			"describe-ad-assessment":                  {"AssessmentId": "*string"},
			"describe-ca-enrollment-policy":           {"DirectoryId": "*string"},
			"describe-certificate":                    {"CertificateId": "*string", "DirectoryId": "*string"},
			"describe-client-authentication-settings": {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string", "Type": "types.ClientAuthenticationType"},
			"describe-conditional-forwarders":         {"DirectoryId": "*string", "RemoteDomainNames": "[]string"},
			"describe-directories":                    {"DirectoryIds": "[]string", "Limit": "*int32", "NextToken": "*string"},
			"describe-directory-data-access":          {"DirectoryId": "*string"},
			"describe-domain-controllers":             {"DirectoryId": "*string", "DomainControllerIds": "[]string", "Limit": "*int32", "NextToken": "*string"},
			"describe-event-topics":                   {"DirectoryId": "*string", "TopicNames": "[]string"},
			"describe-hybrid-ad-update":               {"DirectoryId": "*string", "NextToken": "*string", "UpdateType": "types.HybridUpdateType"},
			"describe-ldaps-settings":                 {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string", "Type": "types.LDAPSType"},
			"describe-regions":                        {"DirectoryId": "*string", "NextToken": "*string", "RegionName": "*string"},
			"describe-settings":                       {"DirectoryId": "*string", "NextToken": "*string", "Status": "types.DirectoryConfigurationStatus"},
			"describe-shared-directories":             {"Limit": "*int32", "NextToken": "*string", "OwnerDirectoryId": "*string", "SharedDirectoryIds": "[]string"},
			"describe-snapshots":                      {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string", "SnapshotIds": "[]string"},
			"describe-trusts":                         {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string", "TrustIds": "[]string"},
			"describe-update-directory":               {"DirectoryId": "*string", "NextToken": "*string", "RegionName": "*string", "UpdateType": "types.UpdateType"},
			"disable-ca-enrollment-policy":            {"DirectoryId": "*string"},
			"disable-client-authentication":           {"DirectoryId": "*string", "Type": "types.ClientAuthenticationType"},
			"disable-directory-data-access":           {"DirectoryId": "*string"},
			"disable-ldaps":                           {"DirectoryId": "*string", "Type": "types.LDAPSType"},
			"disable-radius":                          {"DirectoryId": "*string"},
			"disable-sso":                             {"DirectoryId": "*string", "Password": "*string", "UserName": "*string"},
			"enable-ca-enrollment-policy":             {"DirectoryId": "*string", "PcaConnectorArn": "*string"},
			"enable-client-authentication":            {"DirectoryId": "*string", "Type": "types.ClientAuthenticationType"},
			"enable-directory-data-access":            {"DirectoryId": "*string"},
			"enable-ldaps":                            {"DirectoryId": "*string", "Type": "types.LDAPSType"},
			"enable-radius":                           {"DirectoryId": "*string", "RadiusSettings": "*types.RadiusSettings"},
			"enable-sso":                              {"DirectoryId": "*string", "Password": "*string", "UserName": "*string"},
			"get-directory-limits":                    {},
			"get-snapshot-limits":                     {"DirectoryId": "*string"},
			"list-ad-assessments":                     {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-certificates":                       {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-ip-routes":                          {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-log-subscriptions":                  {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-schema-extensions":                  {"DirectoryId": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                  {"Limit": "*int32", "NextToken": "*string", "ResourceId": "*string"},
			"register-certificate":                    {"CertificateData": "*string", "ClientCertAuthSettings": "*types.ClientCertAuthSettings", "DirectoryId": "*string", "Type": "types.CertificateType"},
			"register-event-topic":                    {"DirectoryId": "*string", "TopicName": "*string"},
			"reject-shared-directory":                 {"SharedDirectoryId": "*string"},
			"remove-ip-routes":                        {"CidrIps": "[]string", "CidrIpv6s": "[]string", "DirectoryId": "*string"},
			"remove-region":                           {"DirectoryId": "*string"},
			"remove-tags-from-resource":               {"ResourceId": "*string", "TagKeys": "[]string"},
			"reset-user-password":                     {"DirectoryId": "*string", "NewPassword": "*string", "UserName": "*string"},
			"restore-from-snapshot":                   {"SnapshotId": "*string"},
			"share-directory":                         {"DirectoryId": "*string", "ShareMethod": "types.ShareMethod", "ShareNotes": "*string", "ShareTarget": "*types.ShareTarget"},
			"start-ad-assessment":                     {"AssessmentConfiguration": "*types.AssessmentConfiguration", "DirectoryId": "*string"},
			"start-schema-extension":                  {"CreateSnapshotBeforeSchemaExtension": "bool", "Description": "*string", "DirectoryId": "*string", "LdifContent": "*string"},
			"unshare-directory":                       {"DirectoryId": "*string", "UnshareTarget": "*types.UnshareTarget"},
			"update-conditional-forwarder":            {"DirectoryId": "*string", "DnsIpAddrs": "[]string", "DnsIpv6Addrs": "[]string", "RemoteDomainName": "*string"},
			"update-directory-setup":                  {"CreateSnapshotBeforeUpdate": "*bool", "DirectoryId": "*string", "DirectorySizeUpdateSettings": "*types.DirectorySizeUpdateSettings", "NetworkUpdateSettings": "*types.NetworkUpdateSettings", "OSUpdateSettings": "*types.OSUpdateSettings", "UpdateType": "types.UpdateType"},
			"update-hybrid-ad":                        {"DirectoryId": "*string", "HybridAdministratorAccountUpdate": "*types.HybridAdministratorAccountUpdate", "SelfManagedInstancesSettings": "*types.HybridCustomerInstancesSettings"},
			"update-number-of-domain-controllers":     {"DesiredNumber": "*int32", "DirectoryId": "*string"},
			"update-radius":                           {"DirectoryId": "*string", "RadiusSettings": "*types.RadiusSettings"},
			"update-settings":                         {"DirectoryId": "*string", "Settings": "[]types.Setting"},
			"update-trust":                            {"SelectiveAuth": "types.SelectiveAuth", "TrustId": "*string"},
			"verify-trust":                            {"TrustId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-shared-directory":                 {"SharedDirectoryId"},
			"add-ip-routes":                           {"DirectoryId", "IpRoutes"},
			"add-region":                              {"DirectoryId", "RegionName", "VPCSettings"},
			"add-tags-to-resource":                    {"ResourceId", "Tags"},
			"cancel-schema-extension":                 {"DirectoryId", "SchemaExtensionId"},
			"connect-directory":                       {"ConnectSettings", "Name", "Password", "Size"},
			"create-alias":                            {"Alias", "DirectoryId"},
			"create-computer":                         {"ComputerName", "DirectoryId", "Password"},
			"create-conditional-forwarder":            {"DirectoryId", "RemoteDomainName"},
			"create-directory":                        {"Name", "Password", "Size"},
			"create-hybrid-ad":                        {"AssessmentId", "SecretArn"},
			"create-log-subscription":                 {"DirectoryId", "LogGroupName"},
			"create-microsoft-ad":                     {"Name", "Password", "VpcSettings"},
			"create-snapshot":                         {"DirectoryId"},
			"create-trust":                            {"DirectoryId", "RemoteDomainName", "TrustDirection", "TrustPassword"},
			"delete-ad-assessment":                    {"AssessmentId"},
			"delete-conditional-forwarder":            {"DirectoryId", "RemoteDomainName"},
			"delete-directory":                        {"DirectoryId"},
			"delete-log-subscription":                 {"DirectoryId"},
			"delete-snapshot":                         {"SnapshotId"},
			"delete-trust":                            {"TrustId"},
			"deregister-certificate":                  {"CertificateId", "DirectoryId"},
			"deregister-event-topic":                  {"DirectoryId", "TopicName"},
			"describe-ad-assessment":                  {"AssessmentId"},
			"describe-ca-enrollment-policy":           {"DirectoryId"},
			"describe-certificate":                    {"CertificateId", "DirectoryId"},
			"describe-client-authentication-settings": {"DirectoryId"},
			"describe-conditional-forwarders":         {"DirectoryId"},
			"describe-directories":                    {},
			"describe-directory-data-access":          {"DirectoryId"},
			"describe-domain-controllers":             {"DirectoryId"},
			"describe-event-topics":                   {},
			"describe-hybrid-ad-update":               {"DirectoryId"},
			"describe-ldaps-settings":                 {"DirectoryId"},
			"describe-regions":                        {"DirectoryId"},
			"describe-settings":                       {"DirectoryId"},
			"describe-shared-directories":             {"OwnerDirectoryId"},
			"describe-snapshots":                      {},
			"describe-trusts":                         {},
			"describe-update-directory":               {"DirectoryId", "UpdateType"},
			"disable-ca-enrollment-policy":            {"DirectoryId"},
			"disable-client-authentication":           {"DirectoryId", "Type"},
			"disable-directory-data-access":           {"DirectoryId"},
			"disable-ldaps":                           {"DirectoryId", "Type"},
			"disable-radius":                          {"DirectoryId"},
			"disable-sso":                             {"DirectoryId"},
			"enable-ca-enrollment-policy":             {"DirectoryId", "PcaConnectorArn"},
			"enable-client-authentication":            {"DirectoryId", "Type"},
			"enable-directory-data-access":            {"DirectoryId"},
			"enable-ldaps":                            {"DirectoryId", "Type"},
			"enable-radius":                           {"DirectoryId", "RadiusSettings"},
			"enable-sso":                              {"DirectoryId"},
			"get-directory-limits":                    {},
			"get-snapshot-limits":                     {"DirectoryId"},
			"list-ad-assessments":                     {},
			"list-certificates":                       {"DirectoryId"},
			"list-ip-routes":                          {"DirectoryId"},
			"list-log-subscriptions":                  {},
			"list-schema-extensions":                  {"DirectoryId"},
			"list-tags-for-resource":                  {"ResourceId"},
			"register-certificate":                    {"CertificateData", "DirectoryId"},
			"register-event-topic":                    {"DirectoryId", "TopicName"},
			"reject-shared-directory":                 {"SharedDirectoryId"},
			"remove-ip-routes":                        {"DirectoryId"},
			"remove-region":                           {"DirectoryId"},
			"remove-tags-from-resource":               {"ResourceId", "TagKeys"},
			"reset-user-password":                     {"DirectoryId", "NewPassword", "UserName"},
			"restore-from-snapshot":                   {"SnapshotId"},
			"share-directory":                         {"DirectoryId", "ShareMethod", "ShareTarget"},
			"start-ad-assessment":                     {},
			"start-schema-extension":                  {"CreateSnapshotBeforeSchemaExtension", "Description", "DirectoryId", "LdifContent"},
			"unshare-directory":                       {"DirectoryId", "UnshareTarget"},
			"update-conditional-forwarder":            {"DirectoryId", "RemoteDomainName"},
			"update-directory-setup":                  {"DirectoryId", "UpdateType"},
			"update-hybrid-ad":                        {"DirectoryId"},
			"update-number-of-domain-controllers":     {"DesiredNumber", "DirectoryId"},
			"update-radius":                           {"DirectoryId", "RadiusSettings"},
			"update-settings":                         {"DirectoryId", "Settings"},
			"update-trust":                            {"TrustId"},
			"verify-trust":                            {"TrustId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("directoryservice", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
