package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/comprehend/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-detect-dominant-language", "batch-detect-entities", "batch-detect-key-phrases", "batch-detect-sentiment", "batch-detect-syntax", "batch-detect-targeted-sentiment", "classify-document", "contains-pii-entities", "create-dataset", "create-document-classifier", "create-endpoint", "create-entity-recognizer", "create-flywheel", "delete-document-classifier", "delete-endpoint", "delete-entity-recognizer", "delete-flywheel", "delete-resource-policy", "describe-dataset", "describe-document-classification-job", "describe-document-classifier", "describe-dominant-language-detection-job", "describe-endpoint", "describe-entities-detection-job", "describe-entity-recognizer", "describe-events-detection-job", "describe-flywheel", "describe-flywheel-iteration", "describe-key-phrases-detection-job", "describe-pii-entities-detection-job", "describe-resource-policy", "describe-sentiment-detection-job", "describe-targeted-sentiment-detection-job", "describe-topics-detection-job", "detect-dominant-language", "detect-entities", "detect-key-phrases", "detect-pii-entities", "detect-sentiment", "detect-syntax", "detect-targeted-sentiment", "detect-toxic-content", "import-model", "list-datasets", "list-document-classification-jobs", "list-document-classifier-summaries", "list-document-classifiers", "list-dominant-language-detection-jobs", "list-endpoints", "list-entities-detection-jobs", "list-entity-recognizer-summaries", "list-entity-recognizers", "list-events-detection-jobs", "list-flywheel-iteration-history", "list-flywheels", "list-key-phrases-detection-jobs", "list-pii-entities-detection-jobs", "list-sentiment-detection-jobs", "list-tags-for-resource", "list-targeted-sentiment-detection-jobs", "list-topics-detection-jobs", "put-resource-policy", "start-document-classification-job", "start-dominant-language-detection-job", "start-entities-detection-job", "start-events-detection-job", "start-flywheel-iteration", "start-key-phrases-detection-job", "start-pii-entities-detection-job", "start-sentiment-detection-job", "start-targeted-sentiment-detection-job", "start-topics-detection-job", "stop-dominant-language-detection-job", "stop-entities-detection-job", "stop-events-detection-job", "stop-key-phrases-detection-job", "stop-pii-entities-detection-job", "stop-sentiment-detection-job", "stop-targeted-sentiment-detection-job", "stop-training-document-classifier", "stop-training-entity-recognizer", "tag-resource", "untag-resource", "update-endpoint", "update-flywheel"},
		OperationSet: map[string]bool{"batch-detect-dominant-language": true, "batch-detect-entities": true, "batch-detect-key-phrases": true, "batch-detect-sentiment": true, "batch-detect-syntax": true, "batch-detect-targeted-sentiment": true, "classify-document": true, "contains-pii-entities": true, "create-dataset": true, "create-document-classifier": true, "create-endpoint": true, "create-entity-recognizer": true, "create-flywheel": true, "delete-document-classifier": true, "delete-endpoint": true, "delete-entity-recognizer": true, "delete-flywheel": true, "delete-resource-policy": true, "describe-dataset": true, "describe-document-classification-job": true, "describe-document-classifier": true, "describe-dominant-language-detection-job": true, "describe-endpoint": true, "describe-entities-detection-job": true, "describe-entity-recognizer": true, "describe-events-detection-job": true, "describe-flywheel": true, "describe-flywheel-iteration": true, "describe-key-phrases-detection-job": true, "describe-pii-entities-detection-job": true, "describe-resource-policy": true, "describe-sentiment-detection-job": true, "describe-targeted-sentiment-detection-job": true, "describe-topics-detection-job": true, "detect-dominant-language": true, "detect-entities": true, "detect-key-phrases": true, "detect-pii-entities": true, "detect-sentiment": true, "detect-syntax": true, "detect-targeted-sentiment": true, "detect-toxic-content": true, "import-model": true, "list-datasets": true, "list-document-classification-jobs": true, "list-document-classifier-summaries": true, "list-document-classifiers": true, "list-dominant-language-detection-jobs": true, "list-endpoints": true, "list-entities-detection-jobs": true, "list-entity-recognizer-summaries": true, "list-entity-recognizers": true, "list-events-detection-jobs": true, "list-flywheel-iteration-history": true, "list-flywheels": true, "list-key-phrases-detection-jobs": true, "list-pii-entities-detection-jobs": true, "list-sentiment-detection-jobs": true, "list-tags-for-resource": true, "list-targeted-sentiment-detection-jobs": true, "list-topics-detection-jobs": true, "put-resource-policy": true, "start-document-classification-job": true, "start-dominant-language-detection-job": true, "start-entities-detection-job": true, "start-events-detection-job": true, "start-flywheel-iteration": true, "start-key-phrases-detection-job": true, "start-pii-entities-detection-job": true, "start-sentiment-detection-job": true, "start-targeted-sentiment-detection-job": true, "start-topics-detection-job": true, "stop-dominant-language-detection-job": true, "stop-entities-detection-job": true, "stop-events-detection-job": true, "stop-key-phrases-detection-job": true, "stop-pii-entities-detection-job": true, "stop-sentiment-detection-job": true, "stop-targeted-sentiment-detection-job": true, "stop-training-document-classifier": true, "stop-training-entity-recognizer": true, "tag-resource": true, "untag-resource": true, "update-endpoint": true, "update-flywheel": true},
		OperationInputs: map[string][]string{
			"batch-detect-dominant-language":            {"TextList"},
			"batch-detect-entities":                     {"LanguageCode", "TextList"},
			"batch-detect-key-phrases":                  {"LanguageCode", "TextList"},
			"batch-detect-sentiment":                    {"LanguageCode", "TextList"},
			"batch-detect-syntax":                       {"LanguageCode", "TextList"},
			"batch-detect-targeted-sentiment":           {"LanguageCode", "TextList"},
			"classify-document":                         {"Bytes", "DocumentReaderConfig", "EndpointArn", "Text"},
			"contains-pii-entities":                     {"LanguageCode", "Text"},
			"create-dataset":                            {"ClientRequestToken", "DatasetName", "DatasetType", "Description", "FlywheelArn", "InputDataConfig", "Tags"},
			"create-document-classifier":                {"ClientRequestToken", "DataAccessRoleArn", "DocumentClassifierName", "InputDataConfig", "LanguageCode", "Mode", "ModelKmsKeyId", "ModelPolicy", "OutputDataConfig", "Tags", "VersionName", "VolumeKmsKeyId", "VpcConfig"},
			"create-endpoint":                           {"ClientRequestToken", "DataAccessRoleArn", "DesiredInferenceUnits", "EndpointName", "FlywheelArn", "ModelArn", "Tags"},
			"create-entity-recognizer":                  {"ClientRequestToken", "DataAccessRoleArn", "InputDataConfig", "LanguageCode", "ModelKmsKeyId", "ModelPolicy", "RecognizerName", "Tags", "VersionName", "VolumeKmsKeyId", "VpcConfig"},
			"create-flywheel":                           {"ActiveModelArn", "ClientRequestToken", "DataAccessRoleArn", "DataLakeS3Uri", "DataSecurityConfig", "FlywheelName", "ModelType", "Tags", "TaskConfig"},
			"delete-document-classifier":                {"DocumentClassifierArn"},
			"delete-endpoint":                           {"EndpointArn"},
			"delete-entity-recognizer":                  {"EntityRecognizerArn"},
			"delete-flywheel":                           {"FlywheelArn"},
			"delete-resource-policy":                    {"PolicyRevisionId", "ResourceArn"},
			"describe-dataset":                          {"DatasetArn"},
			"describe-document-classification-job":      {"JobId"},
			"describe-document-classifier":              {"DocumentClassifierArn"},
			"describe-dominant-language-detection-job":  {"JobId"},
			"describe-endpoint":                         {"EndpointArn"},
			"describe-entities-detection-job":           {"JobId"},
			"describe-entity-recognizer":                {"EntityRecognizerArn"},
			"describe-events-detection-job":             {"JobId"},
			"describe-flywheel":                         {"FlywheelArn"},
			"describe-flywheel-iteration":               {"FlywheelArn", "FlywheelIterationId"},
			"describe-key-phrases-detection-job":        {"JobId"},
			"describe-pii-entities-detection-job":       {"JobId"},
			"describe-resource-policy":                  {"ResourceArn"},
			"describe-sentiment-detection-job":          {"JobId"},
			"describe-targeted-sentiment-detection-job": {"JobId"},
			"describe-topics-detection-job":             {"JobId"},
			"detect-dominant-language":                  {"Text"},
			"detect-entities":                           {"Bytes", "DocumentReaderConfig", "EndpointArn", "LanguageCode", "Text"},
			"detect-key-phrases":                        {"LanguageCode", "Text"},
			"detect-pii-entities":                       {"LanguageCode", "Text"},
			"detect-sentiment":                          {"LanguageCode", "Text"},
			"detect-syntax":                             {"LanguageCode", "Text"},
			"detect-targeted-sentiment":                 {"LanguageCode", "Text"},
			"detect-toxic-content":                      {"LanguageCode", "TextSegments"},
			"import-model":                              {"DataAccessRoleArn", "ModelKmsKeyId", "ModelName", "SourceModelArn", "Tags", "VersionName"},
			"list-datasets":                             {"Filter", "FlywheelArn", "MaxResults", "NextToken"},
			"list-document-classification-jobs":         {"Filter", "MaxResults", "NextToken"},
			"list-document-classifier-summaries":        {"MaxResults", "NextToken"},
			"list-document-classifiers":                 {"Filter", "MaxResults", "NextToken"},
			"list-dominant-language-detection-jobs":     {"Filter", "MaxResults", "NextToken"},
			"list-endpoints":                            {"Filter", "MaxResults", "NextToken"},
			"list-entities-detection-jobs":              {"Filter", "MaxResults", "NextToken"},
			"list-entity-recognizer-summaries":          {"MaxResults", "NextToken"},
			"list-entity-recognizers":                   {"Filter", "MaxResults", "NextToken"},
			"list-events-detection-jobs":                {"Filter", "MaxResults", "NextToken"},
			"list-flywheel-iteration-history":           {"Filter", "FlywheelArn", "MaxResults", "NextToken"},
			"list-flywheels":                            {"Filter", "MaxResults", "NextToken"},
			"list-key-phrases-detection-jobs":           {"Filter", "MaxResults", "NextToken"},
			"list-pii-entities-detection-jobs":          {"Filter", "MaxResults", "NextToken"},
			"list-sentiment-detection-jobs":             {"Filter", "MaxResults", "NextToken"},
			"list-tags-for-resource":                    {"ResourceArn"},
			"list-targeted-sentiment-detection-jobs":    {"Filter", "MaxResults", "NextToken"},
			"list-topics-detection-jobs":                {"Filter", "MaxResults", "NextToken"},
			"put-resource-policy":                       {"PolicyRevisionId", "ResourceArn", "ResourcePolicy"},
			"start-document-classification-job":         {"ClientRequestToken", "DataAccessRoleArn", "DocumentClassifierArn", "FlywheelArn", "InputDataConfig", "JobName", "OutputDataConfig", "Tags", "VolumeKmsKeyId", "VpcConfig"},
			"start-dominant-language-detection-job":     {"ClientRequestToken", "DataAccessRoleArn", "InputDataConfig", "JobName", "OutputDataConfig", "Tags", "VolumeKmsKeyId", "VpcConfig"},
			"start-entities-detection-job":              {"ClientRequestToken", "DataAccessRoleArn", "EntityRecognizerArn", "FlywheelArn", "InputDataConfig", "JobName", "LanguageCode", "OutputDataConfig", "Tags", "VolumeKmsKeyId", "VpcConfig"},
			"start-events-detection-job":                {"ClientRequestToken", "DataAccessRoleArn", "InputDataConfig", "JobName", "LanguageCode", "OutputDataConfig", "Tags", "TargetEventTypes"},
			"start-flywheel-iteration":                  {"ClientRequestToken", "FlywheelArn"},
			"start-key-phrases-detection-job":           {"ClientRequestToken", "DataAccessRoleArn", "InputDataConfig", "JobName", "LanguageCode", "OutputDataConfig", "Tags", "VolumeKmsKeyId", "VpcConfig"},
			"start-pii-entities-detection-job":          {"ClientRequestToken", "DataAccessRoleArn", "InputDataConfig", "JobName", "LanguageCode", "Mode", "OutputDataConfig", "RedactionConfig", "Tags"},
			"start-sentiment-detection-job":             {"ClientRequestToken", "DataAccessRoleArn", "InputDataConfig", "JobName", "LanguageCode", "OutputDataConfig", "Tags", "VolumeKmsKeyId", "VpcConfig"},
			"start-targeted-sentiment-detection-job":    {"ClientRequestToken", "DataAccessRoleArn", "InputDataConfig", "JobName", "LanguageCode", "OutputDataConfig", "Tags", "VolumeKmsKeyId", "VpcConfig"},
			"start-topics-detection-job":                {"ClientRequestToken", "DataAccessRoleArn", "InputDataConfig", "JobName", "NumberOfTopics", "OutputDataConfig", "Tags", "VolumeKmsKeyId", "VpcConfig"},
			"stop-dominant-language-detection-job":      {"JobId"},
			"stop-entities-detection-job":               {"JobId"},
			"stop-events-detection-job":                 {"JobId"},
			"stop-key-phrases-detection-job":            {"JobId"},
			"stop-pii-entities-detection-job":           {"JobId"},
			"stop-sentiment-detection-job":              {"JobId"},
			"stop-targeted-sentiment-detection-job":     {"JobId"},
			"stop-training-document-classifier":         {"DocumentClassifierArn"},
			"stop-training-entity-recognizer":           {"EntityRecognizerArn"},
			"tag-resource":                              {"ResourceArn", "Tags"},
			"untag-resource":                            {"ResourceArn", "TagKeys"},
			"update-endpoint":                           {"DesiredDataAccessRoleArn", "DesiredInferenceUnits", "DesiredModelArn", "EndpointArn", "FlywheelArn"},
			"update-flywheel":                           {"ActiveModelArn", "DataAccessRoleArn", "DataSecurityConfig", "FlywheelArn"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-detect-dominant-language":            {"TextList": "[]string"},
			"batch-detect-entities":                     {"LanguageCode": "types.LanguageCode", "TextList": "[]string"},
			"batch-detect-key-phrases":                  {"LanguageCode": "types.LanguageCode", "TextList": "[]string"},
			"batch-detect-sentiment":                    {"LanguageCode": "types.LanguageCode", "TextList": "[]string"},
			"batch-detect-syntax":                       {"LanguageCode": "types.SyntaxLanguageCode", "TextList": "[]string"},
			"batch-detect-targeted-sentiment":           {"LanguageCode": "types.LanguageCode", "TextList": "[]string"},
			"classify-document":                         {"Bytes": "[]byte", "DocumentReaderConfig": "*types.DocumentReaderConfig", "EndpointArn": "*string", "Text": "*string"},
			"contains-pii-entities":                     {"LanguageCode": "types.LanguageCode", "Text": "*string"},
			"create-dataset":                            {"ClientRequestToken": "*string", "DatasetName": "*string", "DatasetType": "types.DatasetType", "Description": "*string", "FlywheelArn": "*string", "InputDataConfig": "*types.DatasetInputDataConfig", "Tags": "[]types.Tag"},
			"create-document-classifier":                {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "DocumentClassifierName": "*string", "InputDataConfig": "*types.DocumentClassifierInputDataConfig", "LanguageCode": "types.LanguageCode", "Mode": "types.DocumentClassifierMode", "ModelKmsKeyId": "*string", "ModelPolicy": "*string", "OutputDataConfig": "*types.DocumentClassifierOutputDataConfig", "Tags": "[]types.Tag", "VersionName": "*string", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"create-endpoint":                           {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "DesiredInferenceUnits": "*int32", "EndpointName": "*string", "FlywheelArn": "*string", "ModelArn": "*string", "Tags": "[]types.Tag"},
			"create-entity-recognizer":                  {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "InputDataConfig": "*types.EntityRecognizerInputDataConfig", "LanguageCode": "types.LanguageCode", "ModelKmsKeyId": "*string", "ModelPolicy": "*string", "RecognizerName": "*string", "Tags": "[]types.Tag", "VersionName": "*string", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"create-flywheel":                           {"ActiveModelArn": "*string", "ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "DataLakeS3Uri": "*string", "DataSecurityConfig": "*types.DataSecurityConfig", "FlywheelName": "*string", "ModelType": "types.ModelType", "Tags": "[]types.Tag", "TaskConfig": "*types.TaskConfig"},
			"delete-document-classifier":                {"DocumentClassifierArn": "*string"},
			"delete-endpoint":                           {"EndpointArn": "*string"},
			"delete-entity-recognizer":                  {"EntityRecognizerArn": "*string"},
			"delete-flywheel":                           {"FlywheelArn": "*string"},
			"delete-resource-policy":                    {"PolicyRevisionId": "*string", "ResourceArn": "*string"},
			"describe-dataset":                          {"DatasetArn": "*string"},
			"describe-document-classification-job":      {"JobId": "*string"},
			"describe-document-classifier":              {"DocumentClassifierArn": "*string"},
			"describe-dominant-language-detection-job":  {"JobId": "*string"},
			"describe-endpoint":                         {"EndpointArn": "*string"},
			"describe-entities-detection-job":           {"JobId": "*string"},
			"describe-entity-recognizer":                {"EntityRecognizerArn": "*string"},
			"describe-events-detection-job":             {"JobId": "*string"},
			"describe-flywheel":                         {"FlywheelArn": "*string"},
			"describe-flywheel-iteration":               {"FlywheelArn": "*string", "FlywheelIterationId": "*string"},
			"describe-key-phrases-detection-job":        {"JobId": "*string"},
			"describe-pii-entities-detection-job":       {"JobId": "*string"},
			"describe-resource-policy":                  {"ResourceArn": "*string"},
			"describe-sentiment-detection-job":          {"JobId": "*string"},
			"describe-targeted-sentiment-detection-job": {"JobId": "*string"},
			"describe-topics-detection-job":             {"JobId": "*string"},
			"detect-dominant-language":                  {"Text": "*string"},
			"detect-entities":                           {"Bytes": "[]byte", "DocumentReaderConfig": "*types.DocumentReaderConfig", "EndpointArn": "*string", "LanguageCode": "types.LanguageCode", "Text": "*string"},
			"detect-key-phrases":                        {"LanguageCode": "types.LanguageCode", "Text": "*string"},
			"detect-pii-entities":                       {"LanguageCode": "types.LanguageCode", "Text": "*string"},
			"detect-sentiment":                          {"LanguageCode": "types.LanguageCode", "Text": "*string"},
			"detect-syntax":                             {"LanguageCode": "types.SyntaxLanguageCode", "Text": "*string"},
			"detect-targeted-sentiment":                 {"LanguageCode": "types.LanguageCode", "Text": "*string"},
			"detect-toxic-content":                      {"LanguageCode": "types.LanguageCode", "TextSegments": "[]types.TextSegment"},
			"import-model":                              {"DataAccessRoleArn": "*string", "ModelKmsKeyId": "*string", "ModelName": "*string", "SourceModelArn": "*string", "Tags": "[]types.Tag", "VersionName": "*string"},
			"list-datasets":                             {"Filter": "*types.DatasetFilter", "FlywheelArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-document-classification-jobs":         {"Filter": "*types.DocumentClassificationJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-document-classifier-summaries":        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-document-classifiers":                 {"Filter": "*types.DocumentClassifierFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-dominant-language-detection-jobs":     {"Filter": "*types.DominantLanguageDetectionJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-endpoints":                            {"Filter": "*types.EndpointFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-entities-detection-jobs":              {"Filter": "*types.EntitiesDetectionJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-entity-recognizer-summaries":          {"MaxResults": "*int32", "NextToken": "*string"},
			"list-entity-recognizers":                   {"Filter": "*types.EntityRecognizerFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-events-detection-jobs":                {"Filter": "*types.EventsDetectionJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-flywheel-iteration-history":           {"Filter": "*types.FlywheelIterationFilter", "FlywheelArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-flywheels":                            {"Filter": "*types.FlywheelFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-key-phrases-detection-jobs":           {"Filter": "*types.KeyPhrasesDetectionJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-pii-entities-detection-jobs":          {"Filter": "*types.PiiEntitiesDetectionJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-sentiment-detection-jobs":             {"Filter": "*types.SentimentDetectionJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                    {"ResourceArn": "*string"},
			"list-targeted-sentiment-detection-jobs":    {"Filter": "*types.TargetedSentimentDetectionJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-topics-detection-jobs":                {"Filter": "*types.TopicsDetectionJobFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"put-resource-policy":                       {"PolicyRevisionId": "*string", "ResourceArn": "*string", "ResourcePolicy": "*string"},
			"start-document-classification-job":         {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "DocumentClassifierArn": "*string", "FlywheelArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "OutputDataConfig": "*types.OutputDataConfig", "Tags": "[]types.Tag", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"start-dominant-language-detection-job":     {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "OutputDataConfig": "*types.OutputDataConfig", "Tags": "[]types.Tag", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"start-entities-detection-job":              {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "EntityRecognizerArn": "*string", "FlywheelArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "LanguageCode": "types.LanguageCode", "OutputDataConfig": "*types.OutputDataConfig", "Tags": "[]types.Tag", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"start-events-detection-job":                {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "LanguageCode": "types.LanguageCode", "OutputDataConfig": "*types.OutputDataConfig", "Tags": "[]types.Tag", "TargetEventTypes": "[]string"},
			"start-flywheel-iteration":                  {"ClientRequestToken": "*string", "FlywheelArn": "*string"},
			"start-key-phrases-detection-job":           {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "LanguageCode": "types.LanguageCode", "OutputDataConfig": "*types.OutputDataConfig", "Tags": "[]types.Tag", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"start-pii-entities-detection-job":          {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "LanguageCode": "types.LanguageCode", "Mode": "types.PiiEntitiesDetectionMode", "OutputDataConfig": "*types.OutputDataConfig", "RedactionConfig": "*types.RedactionConfig", "Tags": "[]types.Tag"},
			"start-sentiment-detection-job":             {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "LanguageCode": "types.LanguageCode", "OutputDataConfig": "*types.OutputDataConfig", "Tags": "[]types.Tag", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"start-targeted-sentiment-detection-job":    {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "LanguageCode": "types.LanguageCode", "OutputDataConfig": "*types.OutputDataConfig", "Tags": "[]types.Tag", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"start-topics-detection-job":                {"ClientRequestToken": "*string", "DataAccessRoleArn": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "NumberOfTopics": "*int32", "OutputDataConfig": "*types.OutputDataConfig", "Tags": "[]types.Tag", "VolumeKmsKeyId": "*string", "VpcConfig": "*types.VpcConfig"},
			"stop-dominant-language-detection-job":      {"JobId": "*string"},
			"stop-entities-detection-job":               {"JobId": "*string"},
			"stop-events-detection-job":                 {"JobId": "*string"},
			"stop-key-phrases-detection-job":            {"JobId": "*string"},
			"stop-pii-entities-detection-job":           {"JobId": "*string"},
			"stop-sentiment-detection-job":              {"JobId": "*string"},
			"stop-targeted-sentiment-detection-job":     {"JobId": "*string"},
			"stop-training-document-classifier":         {"DocumentClassifierArn": "*string"},
			"stop-training-entity-recognizer":           {"EntityRecognizerArn": "*string"},
			"tag-resource":                              {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                            {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-endpoint":                           {"DesiredDataAccessRoleArn": "*string", "DesiredInferenceUnits": "*int32", "DesiredModelArn": "*string", "EndpointArn": "*string", "FlywheelArn": "*string"},
			"update-flywheel":                           {"ActiveModelArn": "*string", "DataAccessRoleArn": "*string", "DataSecurityConfig": "*types.UpdateDataSecurityConfig", "FlywheelArn": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-detect-dominant-language":            {"TextList"},
			"batch-detect-entities":                     {"LanguageCode", "TextList"},
			"batch-detect-key-phrases":                  {"LanguageCode", "TextList"},
			"batch-detect-sentiment":                    {"LanguageCode", "TextList"},
			"batch-detect-syntax":                       {"LanguageCode", "TextList"},
			"batch-detect-targeted-sentiment":           {"LanguageCode", "TextList"},
			"classify-document":                         {"EndpointArn"},
			"contains-pii-entities":                     {"LanguageCode", "Text"},
			"create-dataset":                            {"DatasetName", "FlywheelArn", "InputDataConfig"},
			"create-document-classifier":                {"DataAccessRoleArn", "DocumentClassifierName", "InputDataConfig", "LanguageCode"},
			"create-endpoint":                           {"DesiredInferenceUnits", "EndpointName"},
			"create-entity-recognizer":                  {"DataAccessRoleArn", "InputDataConfig", "LanguageCode", "RecognizerName"},
			"create-flywheel":                           {"DataAccessRoleArn", "DataLakeS3Uri", "FlywheelName"},
			"delete-document-classifier":                {"DocumentClassifierArn"},
			"delete-endpoint":                           {"EndpointArn"},
			"delete-entity-recognizer":                  {"EntityRecognizerArn"},
			"delete-flywheel":                           {"FlywheelArn"},
			"delete-resource-policy":                    {"ResourceArn"},
			"describe-dataset":                          {"DatasetArn"},
			"describe-document-classification-job":      {"JobId"},
			"describe-document-classifier":              {"DocumentClassifierArn"},
			"describe-dominant-language-detection-job":  {"JobId"},
			"describe-endpoint":                         {"EndpointArn"},
			"describe-entities-detection-job":           {"JobId"},
			"describe-entity-recognizer":                {"EntityRecognizerArn"},
			"describe-events-detection-job":             {"JobId"},
			"describe-flywheel":                         {"FlywheelArn"},
			"describe-flywheel-iteration":               {"FlywheelArn", "FlywheelIterationId"},
			"describe-key-phrases-detection-job":        {"JobId"},
			"describe-pii-entities-detection-job":       {"JobId"},
			"describe-resource-policy":                  {"ResourceArn"},
			"describe-sentiment-detection-job":          {"JobId"},
			"describe-targeted-sentiment-detection-job": {"JobId"},
			"describe-topics-detection-job":             {"JobId"},
			"detect-dominant-language":                  {"Text"},
			"detect-entities":                           {},
			"detect-key-phrases":                        {"LanguageCode", "Text"},
			"detect-pii-entities":                       {"LanguageCode", "Text"},
			"detect-sentiment":                          {"LanguageCode", "Text"},
			"detect-syntax":                             {"LanguageCode", "Text"},
			"detect-targeted-sentiment":                 {"LanguageCode", "Text"},
			"detect-toxic-content":                      {"LanguageCode", "TextSegments"},
			"import-model":                              {"SourceModelArn"},
			"list-datasets":                             {},
			"list-document-classification-jobs":         {},
			"list-document-classifier-summaries":        {},
			"list-document-classifiers":                 {},
			"list-dominant-language-detection-jobs":     {},
			"list-endpoints":                            {},
			"list-entities-detection-jobs":              {},
			"list-entity-recognizer-summaries":          {},
			"list-entity-recognizers":                   {},
			"list-events-detection-jobs":                {},
			"list-flywheel-iteration-history":           {"FlywheelArn"},
			"list-flywheels":                            {},
			"list-key-phrases-detection-jobs":           {},
			"list-pii-entities-detection-jobs":          {},
			"list-sentiment-detection-jobs":             {},
			"list-tags-for-resource":                    {"ResourceArn"},
			"list-targeted-sentiment-detection-jobs":    {},
			"list-topics-detection-jobs":                {},
			"put-resource-policy":                       {"ResourceArn", "ResourcePolicy"},
			"start-document-classification-job":         {"DataAccessRoleArn", "InputDataConfig", "OutputDataConfig"},
			"start-dominant-language-detection-job":     {"DataAccessRoleArn", "InputDataConfig", "OutputDataConfig"},
			"start-entities-detection-job":              {"DataAccessRoleArn", "InputDataConfig", "LanguageCode", "OutputDataConfig"},
			"start-events-detection-job":                {"DataAccessRoleArn", "InputDataConfig", "LanguageCode", "OutputDataConfig", "TargetEventTypes"},
			"start-flywheel-iteration":                  {"FlywheelArn"},
			"start-key-phrases-detection-job":           {"DataAccessRoleArn", "InputDataConfig", "LanguageCode", "OutputDataConfig"},
			"start-pii-entities-detection-job":          {"DataAccessRoleArn", "InputDataConfig", "LanguageCode", "Mode", "OutputDataConfig"},
			"start-sentiment-detection-job":             {"DataAccessRoleArn", "InputDataConfig", "LanguageCode", "OutputDataConfig"},
			"start-targeted-sentiment-detection-job":    {"DataAccessRoleArn", "InputDataConfig", "LanguageCode", "OutputDataConfig"},
			"start-topics-detection-job":                {"DataAccessRoleArn", "InputDataConfig", "OutputDataConfig"},
			"stop-dominant-language-detection-job":      {"JobId"},
			"stop-entities-detection-job":               {"JobId"},
			"stop-events-detection-job":                 {"JobId"},
			"stop-key-phrases-detection-job":            {"JobId"},
			"stop-pii-entities-detection-job":           {"JobId"},
			"stop-sentiment-detection-job":              {"JobId"},
			"stop-targeted-sentiment-detection-job":     {"JobId"},
			"stop-training-document-classifier":         {"DocumentClassifierArn"},
			"stop-training-entity-recognizer":           {"EntityRecognizerArn"},
			"tag-resource":                              {"ResourceArn", "Tags"},
			"untag-resource":                            {"ResourceArn", "TagKeys"},
			"update-endpoint":                           {"EndpointArn"},
			"update-flywheel":                           {"FlywheelArn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("comprehend", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
