package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/transcribe/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-call-analytics-category", "create-language-model", "create-medical-vocabulary", "create-vocabulary", "create-vocabulary-filter", "delete-call-analytics-category", "delete-call-analytics-job", "delete-language-model", "delete-medical-scribe-job", "delete-medical-transcription-job", "delete-medical-vocabulary", "delete-transcription-job", "delete-vocabulary", "delete-vocabulary-filter", "describe-language-model", "get-call-analytics-category", "get-call-analytics-job", "get-medical-scribe-job", "get-medical-transcription-job", "get-medical-vocabulary", "get-transcription-job", "get-vocabulary", "get-vocabulary-filter", "list-call-analytics-categories", "list-call-analytics-jobs", "list-language-models", "list-medical-scribe-jobs", "list-medical-transcription-jobs", "list-medical-vocabularies", "list-tags-for-resource", "list-transcription-jobs", "list-vocabularies", "list-vocabulary-filters", "start-call-analytics-job", "start-medical-scribe-job", "start-medical-transcription-job", "start-transcription-job", "tag-resource", "untag-resource", "update-call-analytics-category", "update-medical-vocabulary", "update-vocabulary", "update-vocabulary-filter"},
		OperationSet: map[string]bool{"create-call-analytics-category": true, "create-language-model": true, "create-medical-vocabulary": true, "create-vocabulary": true, "create-vocabulary-filter": true, "delete-call-analytics-category": true, "delete-call-analytics-job": true, "delete-language-model": true, "delete-medical-scribe-job": true, "delete-medical-transcription-job": true, "delete-medical-vocabulary": true, "delete-transcription-job": true, "delete-vocabulary": true, "delete-vocabulary-filter": true, "describe-language-model": true, "get-call-analytics-category": true, "get-call-analytics-job": true, "get-medical-scribe-job": true, "get-medical-transcription-job": true, "get-medical-vocabulary": true, "get-transcription-job": true, "get-vocabulary": true, "get-vocabulary-filter": true, "list-call-analytics-categories": true, "list-call-analytics-jobs": true, "list-language-models": true, "list-medical-scribe-jobs": true, "list-medical-transcription-jobs": true, "list-medical-vocabularies": true, "list-tags-for-resource": true, "list-transcription-jobs": true, "list-vocabularies": true, "list-vocabulary-filters": true, "start-call-analytics-job": true, "start-medical-scribe-job": true, "start-medical-transcription-job": true, "start-transcription-job": true, "tag-resource": true, "untag-resource": true, "update-call-analytics-category": true, "update-medical-vocabulary": true, "update-vocabulary": true, "update-vocabulary-filter": true},
		OperationInputs: map[string][]string{
			"create-call-analytics-category":   {"CategoryName", "InputType", "Rules", "Tags"},
			"create-language-model":            {"BaseModelName", "InputDataConfig", "LanguageCode", "ModelName", "Tags"},
			"create-medical-vocabulary":        {"LanguageCode", "Tags", "VocabularyFileUri", "VocabularyName"},
			"create-vocabulary":                {"DataAccessRoleArn", "LanguageCode", "Phrases", "Tags", "VocabularyFileUri", "VocabularyName"},
			"create-vocabulary-filter":         {"DataAccessRoleArn", "LanguageCode", "Tags", "VocabularyFilterFileUri", "VocabularyFilterName", "Words"},
			"delete-call-analytics-category":   {"CategoryName"},
			"delete-call-analytics-job":        {"CallAnalyticsJobName"},
			"delete-language-model":            {"ModelName"},
			"delete-medical-scribe-job":        {"MedicalScribeJobName"},
			"delete-medical-transcription-job": {"MedicalTranscriptionJobName"},
			"delete-medical-vocabulary":        {"VocabularyName"},
			"delete-transcription-job":         {"TranscriptionJobName"},
			"delete-vocabulary":                {"VocabularyName"},
			"delete-vocabulary-filter":         {"VocabularyFilterName"},
			"describe-language-model":          {"ModelName"},
			"get-call-analytics-category":      {"CategoryName"},
			"get-call-analytics-job":           {"CallAnalyticsJobName"},
			"get-medical-scribe-job":           {"MedicalScribeJobName"},
			"get-medical-transcription-job":    {"MedicalTranscriptionJobName"},
			"get-medical-vocabulary":           {"VocabularyName"},
			"get-transcription-job":            {"TranscriptionJobName"},
			"get-vocabulary":                   {"VocabularyName"},
			"get-vocabulary-filter":            {"VocabularyFilterName"},
			"list-call-analytics-categories":   {"MaxResults", "NextToken"},
			"list-call-analytics-jobs":         {"JobNameContains", "MaxResults", "NextToken", "Status"},
			"list-language-models":             {"MaxResults", "NameContains", "NextToken", "StatusEquals"},
			"list-medical-scribe-jobs":         {"JobNameContains", "MaxResults", "NextToken", "Status"},
			"list-medical-transcription-jobs":  {"JobNameContains", "MaxResults", "NextToken", "Status"},
			"list-medical-vocabularies":        {"MaxResults", "NameContains", "NextToken", "StateEquals"},
			"list-tags-for-resource":           {"ResourceArn"},
			"list-transcription-jobs":          {"JobNameContains", "MaxResults", "NextToken", "Status"},
			"list-vocabularies":                {"MaxResults", "NameContains", "NextToken", "StateEquals"},
			"list-vocabulary-filters":          {"MaxResults", "NameContains", "NextToken"},
			"start-call-analytics-job":         {"CallAnalyticsJobName", "ChannelDefinitions", "DataAccessRoleArn", "Media", "OutputEncryptionKMSKeyId", "OutputLocation", "Settings", "Tags"},
			"start-medical-scribe-job":         {"ChannelDefinitions", "DataAccessRoleArn", "KMSEncryptionContext", "Media", "MedicalScribeContext", "MedicalScribeJobName", "OutputBucketName", "OutputEncryptionKMSKeyId", "Settings", "Tags"},
			"start-medical-transcription-job":  {"ContentIdentificationType", "KMSEncryptionContext", "LanguageCode", "Media", "MediaFormat", "MediaSampleRateHertz", "MedicalTranscriptionJobName", "OutputBucketName", "OutputEncryptionKMSKeyId", "OutputKey", "Settings", "Specialty", "Tags", "Type"},
			"start-transcription-job":          {"ContentRedaction", "IdentifyLanguage", "IdentifyMultipleLanguages", "JobExecutionSettings", "KMSEncryptionContext", "LanguageCode", "LanguageIdSettings", "LanguageOptions", "Media", "MediaFormat", "MediaSampleRateHertz", "ModelSettings", "OutputBucketName", "OutputEncryptionKMSKeyId", "OutputKey", "Settings", "Subtitles", "Tags", "ToxicityDetection", "TranscriptionJobName"},
			"tag-resource":                     {"ResourceArn", "Tags"},
			"untag-resource":                   {"ResourceArn", "TagKeys"},
			"update-call-analytics-category":   {"CategoryName", "InputType", "Rules"},
			"update-medical-vocabulary":        {"LanguageCode", "VocabularyFileUri", "VocabularyName"},
			"update-vocabulary":                {"DataAccessRoleArn", "LanguageCode", "Phrases", "VocabularyFileUri", "VocabularyName"},
			"update-vocabulary-filter":         {"DataAccessRoleArn", "VocabularyFilterFileUri", "VocabularyFilterName", "Words"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-call-analytics-category":   {"CategoryName": "*string", "InputType": "types.InputType", "Rules": "[]types.Rule", "Tags": "[]types.Tag"},
			"create-language-model":            {"BaseModelName": "types.BaseModelName", "InputDataConfig": "*types.InputDataConfig", "LanguageCode": "types.CLMLanguageCode", "ModelName": "*string", "Tags": "[]types.Tag"},
			"create-medical-vocabulary":        {"LanguageCode": "types.LanguageCode", "Tags": "[]types.Tag", "VocabularyFileUri": "*string", "VocabularyName": "*string"},
			"create-vocabulary":                {"DataAccessRoleArn": "*string", "LanguageCode": "types.LanguageCode", "Phrases": "[]string", "Tags": "[]types.Tag", "VocabularyFileUri": "*string", "VocabularyName": "*string"},
			"create-vocabulary-filter":         {"DataAccessRoleArn": "*string", "LanguageCode": "types.LanguageCode", "Tags": "[]types.Tag", "VocabularyFilterFileUri": "*string", "VocabularyFilterName": "*string", "Words": "[]string"},
			"delete-call-analytics-category":   {"CategoryName": "*string"},
			"delete-call-analytics-job":        {"CallAnalyticsJobName": "*string"},
			"delete-language-model":            {"ModelName": "*string"},
			"delete-medical-scribe-job":        {"MedicalScribeJobName": "*string"},
			"delete-medical-transcription-job": {"MedicalTranscriptionJobName": "*string"},
			"delete-medical-vocabulary":        {"VocabularyName": "*string"},
			"delete-transcription-job":         {"TranscriptionJobName": "*string"},
			"delete-vocabulary":                {"VocabularyName": "*string"},
			"delete-vocabulary-filter":         {"VocabularyFilterName": "*string"},
			"describe-language-model":          {"ModelName": "*string"},
			"get-call-analytics-category":      {"CategoryName": "*string"},
			"get-call-analytics-job":           {"CallAnalyticsJobName": "*string"},
			"get-medical-scribe-job":           {"MedicalScribeJobName": "*string"},
			"get-medical-transcription-job":    {"MedicalTranscriptionJobName": "*string"},
			"get-medical-vocabulary":           {"VocabularyName": "*string"},
			"get-transcription-job":            {"TranscriptionJobName": "*string"},
			"get-vocabulary":                   {"VocabularyName": "*string"},
			"get-vocabulary-filter":            {"VocabularyFilterName": "*string"},
			"list-call-analytics-categories":   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-call-analytics-jobs":         {"JobNameContains": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.CallAnalyticsJobStatus"},
			"list-language-models":             {"MaxResults": "*int32", "NameContains": "*string", "NextToken": "*string", "StatusEquals": "types.ModelStatus"},
			"list-medical-scribe-jobs":         {"JobNameContains": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.MedicalScribeJobStatus"},
			"list-medical-transcription-jobs":  {"JobNameContains": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.TranscriptionJobStatus"},
			"list-medical-vocabularies":        {"MaxResults": "*int32", "NameContains": "*string", "NextToken": "*string", "StateEquals": "types.VocabularyState"},
			"list-tags-for-resource":           {"ResourceArn": "*string"},
			"list-transcription-jobs":          {"JobNameContains": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.TranscriptionJobStatus"},
			"list-vocabularies":                {"MaxResults": "*int32", "NameContains": "*string", "NextToken": "*string", "StateEquals": "types.VocabularyState"},
			"list-vocabulary-filters":          {"MaxResults": "*int32", "NameContains": "*string", "NextToken": "*string"},
			"start-call-analytics-job":         {"CallAnalyticsJobName": "*string", "ChannelDefinitions": "[]types.ChannelDefinition", "DataAccessRoleArn": "*string", "Media": "*types.Media", "OutputEncryptionKMSKeyId": "*string", "OutputLocation": "*string", "Settings": "*types.CallAnalyticsJobSettings", "Tags": "[]types.Tag"},
			"start-medical-scribe-job":         {"ChannelDefinitions": "[]types.MedicalScribeChannelDefinition", "DataAccessRoleArn": "*string", "KMSEncryptionContext": "map[string]string", "Media": "*types.Media", "MedicalScribeContext": "*types.MedicalScribeContext", "MedicalScribeJobName": "*string", "OutputBucketName": "*string", "OutputEncryptionKMSKeyId": "*string", "Settings": "*types.MedicalScribeSettings", "Tags": "[]types.Tag"},
			"start-medical-transcription-job":  {"ContentIdentificationType": "types.MedicalContentIdentificationType", "KMSEncryptionContext": "map[string]string", "LanguageCode": "types.LanguageCode", "Media": "*types.Media", "MediaFormat": "types.MediaFormat", "MediaSampleRateHertz": "*int32", "MedicalTranscriptionJobName": "*string", "OutputBucketName": "*string", "OutputEncryptionKMSKeyId": "*string", "OutputKey": "*string", "Settings": "*types.MedicalTranscriptionSetting", "Specialty": "types.Specialty", "Tags": "[]types.Tag", "Type": "types.Type"},
			"start-transcription-job":          {"ContentRedaction": "*types.ContentRedaction", "IdentifyLanguage": "*bool", "IdentifyMultipleLanguages": "*bool", "JobExecutionSettings": "*types.JobExecutionSettings", "KMSEncryptionContext": "map[string]string", "LanguageCode": "types.LanguageCode", "LanguageIdSettings": "map[string]types.LanguageIdSettings", "LanguageOptions": "[]types.LanguageCode", "Media": "*types.Media", "MediaFormat": "types.MediaFormat", "MediaSampleRateHertz": "*int32", "ModelSettings": "*types.ModelSettings", "OutputBucketName": "*string", "OutputEncryptionKMSKeyId": "*string", "OutputKey": "*string", "Settings": "*types.Settings", "Subtitles": "*types.Subtitles", "Tags": "[]types.Tag", "ToxicityDetection": "[]types.ToxicityDetectionSettings", "TranscriptionJobName": "*string"},
			"tag-resource":                     {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                   {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-call-analytics-category":   {"CategoryName": "*string", "InputType": "types.InputType", "Rules": "[]types.Rule"},
			"update-medical-vocabulary":        {"LanguageCode": "types.LanguageCode", "VocabularyFileUri": "*string", "VocabularyName": "*string"},
			"update-vocabulary":                {"DataAccessRoleArn": "*string", "LanguageCode": "types.LanguageCode", "Phrases": "[]string", "VocabularyFileUri": "*string", "VocabularyName": "*string"},
			"update-vocabulary-filter":         {"DataAccessRoleArn": "*string", "VocabularyFilterFileUri": "*string", "VocabularyFilterName": "*string", "Words": "[]string"},
		},
		OperationInputRequired: map[string][]string{
			"create-call-analytics-category":   {"CategoryName", "Rules"},
			"create-language-model":            {"BaseModelName", "InputDataConfig", "LanguageCode", "ModelName"},
			"create-medical-vocabulary":        {"LanguageCode", "VocabularyFileUri", "VocabularyName"},
			"create-vocabulary":                {"LanguageCode", "VocabularyName"},
			"create-vocabulary-filter":         {"LanguageCode", "VocabularyFilterName"},
			"delete-call-analytics-category":   {"CategoryName"},
			"delete-call-analytics-job":        {"CallAnalyticsJobName"},
			"delete-language-model":            {"ModelName"},
			"delete-medical-scribe-job":        {"MedicalScribeJobName"},
			"delete-medical-transcription-job": {"MedicalTranscriptionJobName"},
			"delete-medical-vocabulary":        {"VocabularyName"},
			"delete-transcription-job":         {"TranscriptionJobName"},
			"delete-vocabulary":                {"VocabularyName"},
			"delete-vocabulary-filter":         {"VocabularyFilterName"},
			"describe-language-model":          {"ModelName"},
			"get-call-analytics-category":      {"CategoryName"},
			"get-call-analytics-job":           {"CallAnalyticsJobName"},
			"get-medical-scribe-job":           {"MedicalScribeJobName"},
			"get-medical-transcription-job":    {"MedicalTranscriptionJobName"},
			"get-medical-vocabulary":           {"VocabularyName"},
			"get-transcription-job":            {"TranscriptionJobName"},
			"get-vocabulary":                   {"VocabularyName"},
			"get-vocabulary-filter":            {"VocabularyFilterName"},
			"list-call-analytics-categories":   {},
			"list-call-analytics-jobs":         {},
			"list-language-models":             {},
			"list-medical-scribe-jobs":         {},
			"list-medical-transcription-jobs":  {},
			"list-medical-vocabularies":        {},
			"list-tags-for-resource":           {"ResourceArn"},
			"list-transcription-jobs":          {},
			"list-vocabularies":                {},
			"list-vocabulary-filters":          {},
			"start-call-analytics-job":         {"CallAnalyticsJobName", "Media"},
			"start-medical-scribe-job":         {"DataAccessRoleArn", "Media", "MedicalScribeJobName", "OutputBucketName", "Settings"},
			"start-medical-transcription-job":  {"LanguageCode", "Media", "MedicalTranscriptionJobName", "OutputBucketName", "Specialty", "Type"},
			"start-transcription-job":          {"Media", "TranscriptionJobName"},
			"tag-resource":                     {"ResourceArn", "Tags"},
			"untag-resource":                   {"ResourceArn", "TagKeys"},
			"update-call-analytics-category":   {"CategoryName", "Rules"},
			"update-medical-vocabulary":        {"LanguageCode", "VocabularyFileUri", "VocabularyName"},
			"update-vocabulary":                {"LanguageCode", "VocabularyName"},
			"update-vocabulary-filter":         {"VocabularyFilterName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("transcribe", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
