package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/schemas/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-discoverer", "create-registry", "create-schema", "delete-discoverer", "delete-registry", "delete-resource-policy", "delete-schema", "delete-schema-version", "describe-code-binding", "describe-discoverer", "describe-registry", "describe-schema", "export-schema", "get-code-binding-source", "get-discovered-schema", "get-resource-policy", "list-discoverers", "list-registries", "list-schema-versions", "list-schemas", "list-tags-for-resource", "put-code-binding", "put-resource-policy", "search-schemas", "start-discoverer", "stop-discoverer", "tag-resource", "untag-resource", "update-discoverer", "update-registry", "update-schema"},
		OperationSet: map[string]bool{"create-discoverer": true, "create-registry": true, "create-schema": true, "delete-discoverer": true, "delete-registry": true, "delete-resource-policy": true, "delete-schema": true, "delete-schema-version": true, "describe-code-binding": true, "describe-discoverer": true, "describe-registry": true, "describe-schema": true, "export-schema": true, "get-code-binding-source": true, "get-discovered-schema": true, "get-resource-policy": true, "list-discoverers": true, "list-registries": true, "list-schema-versions": true, "list-schemas": true, "list-tags-for-resource": true, "put-code-binding": true, "put-resource-policy": true, "search-schemas": true, "start-discoverer": true, "stop-discoverer": true, "tag-resource": true, "untag-resource": true, "update-discoverer": true, "update-registry": true, "update-schema": true},
		OperationInputs: map[string][]string{
			"create-discoverer":       {"CrossAccount", "Description", "SourceArn", "Tags"},
			"create-registry":         {"Description", "RegistryName", "Tags"},
			"create-schema":           {"Content", "Description", "RegistryName", "SchemaName", "Tags", "Type"},
			"delete-discoverer":       {"DiscovererId"},
			"delete-registry":         {"RegistryName"},
			"delete-resource-policy":  {"RegistryName"},
			"delete-schema":           {"RegistryName", "SchemaName"},
			"delete-schema-version":   {"RegistryName", "SchemaName", "SchemaVersion"},
			"describe-code-binding":   {"Language", "RegistryName", "SchemaName", "SchemaVersion"},
			"describe-discoverer":     {"DiscovererId"},
			"describe-registry":       {"RegistryName"},
			"describe-schema":         {"RegistryName", "SchemaName", "SchemaVersion"},
			"export-schema":           {"RegistryName", "SchemaName", "SchemaVersion", "Type"},
			"get-code-binding-source": {"Language", "RegistryName", "SchemaName", "SchemaVersion"},
			"get-discovered-schema":   {"Events", "Type"},
			"get-resource-policy":     {"RegistryName"},
			"list-discoverers":        {"DiscovererIdPrefix", "Limit", "NextToken", "SourceArnPrefix"},
			"list-registries":         {"Limit", "NextToken", "RegistryNamePrefix", "Scope"},
			"list-schema-versions":    {"Limit", "NextToken", "RegistryName", "SchemaName"},
			"list-schemas":            {"Limit", "NextToken", "RegistryName", "SchemaNamePrefix"},
			"list-tags-for-resource":  {"ResourceArn"},
			"put-code-binding":        {"Language", "RegistryName", "SchemaName", "SchemaVersion"},
			"put-resource-policy":     {"Policy", "RegistryName", "RevisionId"},
			"search-schemas":          {"Keywords", "Limit", "NextToken", "RegistryName"},
			"start-discoverer":        {"DiscovererId"},
			"stop-discoverer":         {"DiscovererId"},
			"tag-resource":            {"ResourceArn", "Tags"},
			"untag-resource":          {"ResourceArn", "TagKeys"},
			"update-discoverer":       {"CrossAccount", "Description", "DiscovererId"},
			"update-registry":         {"Description", "RegistryName"},
			"update-schema":           {"ClientTokenId", "Content", "Description", "RegistryName", "SchemaName", "Type"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-discoverer":       {"CrossAccount": "*bool", "Description": "*string", "SourceArn": "*string", "Tags": "map[string]string"},
			"create-registry":         {"Description": "*string", "RegistryName": "*string", "Tags": "map[string]string"},
			"create-schema":           {"Content": "*string", "Description": "*string", "RegistryName": "*string", "SchemaName": "*string", "Tags": "map[string]string", "Type": "types.Type"},
			"delete-discoverer":       {"DiscovererId": "*string"},
			"delete-registry":         {"RegistryName": "*string"},
			"delete-resource-policy":  {"RegistryName": "*string"},
			"delete-schema":           {"RegistryName": "*string", "SchemaName": "*string"},
			"delete-schema-version":   {"RegistryName": "*string", "SchemaName": "*string", "SchemaVersion": "*string"},
			"describe-code-binding":   {"Language": "*string", "RegistryName": "*string", "SchemaName": "*string", "SchemaVersion": "*string"},
			"describe-discoverer":     {"DiscovererId": "*string"},
			"describe-registry":       {"RegistryName": "*string"},
			"describe-schema":         {"RegistryName": "*string", "SchemaName": "*string", "SchemaVersion": "*string"},
			"export-schema":           {"RegistryName": "*string", "SchemaName": "*string", "SchemaVersion": "*string", "Type": "*string"},
			"get-code-binding-source": {"Language": "*string", "RegistryName": "*string", "SchemaName": "*string", "SchemaVersion": "*string"},
			"get-discovered-schema":   {"Events": "[]string", "Type": "types.Type"},
			"get-resource-policy":     {"RegistryName": "*string"},
			"list-discoverers":        {"DiscovererIdPrefix": "*string", "Limit": "*int32", "NextToken": "*string", "SourceArnPrefix": "*string"},
			"list-registries":         {"Limit": "*int32", "NextToken": "*string", "RegistryNamePrefix": "*string", "Scope": "*string"},
			"list-schema-versions":    {"Limit": "*int32", "NextToken": "*string", "RegistryName": "*string", "SchemaName": "*string"},
			"list-schemas":            {"Limit": "*int32", "NextToken": "*string", "RegistryName": "*string", "SchemaNamePrefix": "*string"},
			"list-tags-for-resource":  {"ResourceArn": "*string"},
			"put-code-binding":        {"Language": "*string", "RegistryName": "*string", "SchemaName": "*string", "SchemaVersion": "*string"},
			"put-resource-policy":     {"Policy": "*string", "RegistryName": "*string", "RevisionId": "*string"},
			"search-schemas":          {"Keywords": "*string", "Limit": "*int32", "NextToken": "*string", "RegistryName": "*string"},
			"start-discoverer":        {"DiscovererId": "*string"},
			"stop-discoverer":         {"DiscovererId": "*string"},
			"tag-resource":            {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":          {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-discoverer":       {"CrossAccount": "*bool", "Description": "*string", "DiscovererId": "*string"},
			"update-registry":         {"Description": "*string", "RegistryName": "*string"},
			"update-schema":           {"ClientTokenId": "*string", "Content": "*string", "Description": "*string", "RegistryName": "*string", "SchemaName": "*string", "Type": "types.Type"},
		},
		OperationInputRequired: map[string][]string{
			"create-discoverer":       {"SourceArn"},
			"create-registry":         {"RegistryName"},
			"create-schema":           {"Content", "RegistryName", "SchemaName", "Type"},
			"delete-discoverer":       {"DiscovererId"},
			"delete-registry":         {"RegistryName"},
			"delete-resource-policy":  {},
			"delete-schema":           {"RegistryName", "SchemaName"},
			"delete-schema-version":   {"RegistryName", "SchemaName", "SchemaVersion"},
			"describe-code-binding":   {"Language", "RegistryName", "SchemaName"},
			"describe-discoverer":     {"DiscovererId"},
			"describe-registry":       {"RegistryName"},
			"describe-schema":         {"RegistryName", "SchemaName"},
			"export-schema":           {"RegistryName", "SchemaName", "Type"},
			"get-code-binding-source": {"Language", "RegistryName", "SchemaName"},
			"get-discovered-schema":   {"Events", "Type"},
			"get-resource-policy":     {},
			"list-discoverers":        {},
			"list-registries":         {},
			"list-schema-versions":    {"RegistryName", "SchemaName"},
			"list-schemas":            {"RegistryName"},
			"list-tags-for-resource":  {"ResourceArn"},
			"put-code-binding":        {"Language", "RegistryName", "SchemaName"},
			"put-resource-policy":     {"Policy"},
			"search-schemas":          {"Keywords", "RegistryName"},
			"start-discoverer":        {"DiscovererId"},
			"stop-discoverer":         {"DiscovererId"},
			"tag-resource":            {"ResourceArn", "Tags"},
			"untag-resource":          {"ResourceArn", "TagKeys"},
			"update-discoverer":       {"DiscovererId"},
			"update-registry":         {"RegistryName"},
			"update-schema":           {"RegistryName", "SchemaName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("schemas", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
