package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/workdocs/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"abort-document-version-upload", "activate-user", "add-resource-permissions", "create-comment", "create-custom-metadata", "create-folder", "create-labels", "create-notification-subscription", "create-user", "deactivate-user", "delete-comment", "delete-custom-metadata", "delete-document", "delete-document-version", "delete-folder", "delete-folder-contents", "delete-labels", "delete-notification-subscription", "delete-user", "describe-activities", "describe-comments", "describe-document-versions", "describe-folder-contents", "describe-groups", "describe-notification-subscriptions", "describe-resource-permissions", "describe-root-folders", "describe-users", "get-current-user", "get-document", "get-document-path", "get-document-version", "get-folder", "get-folder-path", "get-resources", "initiate-document-version-upload", "remove-all-resource-permissions", "remove-resource-permission", "restore-document-versions", "search-resources", "update-document", "update-document-version", "update-folder", "update-user"},
		OperationSet: map[string]bool{"abort-document-version-upload": true, "activate-user": true, "add-resource-permissions": true, "create-comment": true, "create-custom-metadata": true, "create-folder": true, "create-labels": true, "create-notification-subscription": true, "create-user": true, "deactivate-user": true, "delete-comment": true, "delete-custom-metadata": true, "delete-document": true, "delete-document-version": true, "delete-folder": true, "delete-folder-contents": true, "delete-labels": true, "delete-notification-subscription": true, "delete-user": true, "describe-activities": true, "describe-comments": true, "describe-document-versions": true, "describe-folder-contents": true, "describe-groups": true, "describe-notification-subscriptions": true, "describe-resource-permissions": true, "describe-root-folders": true, "describe-users": true, "get-current-user": true, "get-document": true, "get-document-path": true, "get-document-version": true, "get-folder": true, "get-folder-path": true, "get-resources": true, "initiate-document-version-upload": true, "remove-all-resource-permissions": true, "remove-resource-permission": true, "restore-document-versions": true, "search-resources": true, "update-document": true, "update-document-version": true, "update-folder": true, "update-user": true},
		OperationInputs: map[string][]string{
			"abort-document-version-upload":       {"AuthenticationToken", "DocumentId", "VersionId"},
			"activate-user":                       {"AuthenticationToken", "UserId"},
			"add-resource-permissions":            {"AuthenticationToken", "NotificationOptions", "Principals", "ResourceId"},
			"create-comment":                      {"AuthenticationToken", "DocumentId", "NotifyCollaborators", "ParentId", "Text", "ThreadId", "VersionId", "Visibility"},
			"create-custom-metadata":              {"AuthenticationToken", "CustomMetadata", "ResourceId", "VersionId"},
			"create-folder":                       {"AuthenticationToken", "Name", "ParentFolderId"},
			"create-labels":                       {"AuthenticationToken", "Labels", "ResourceId"},
			"create-notification-subscription":    {"Endpoint", "OrganizationId", "Protocol", "SubscriptionType"},
			"create-user":                         {"AuthenticationToken", "EmailAddress", "GivenName", "OrganizationId", "Password", "StorageRule", "Surname", "TimeZoneId", "Username"},
			"deactivate-user":                     {"AuthenticationToken", "UserId"},
			"delete-comment":                      {"AuthenticationToken", "CommentId", "DocumentId", "VersionId"},
			"delete-custom-metadata":              {"AuthenticationToken", "DeleteAll", "Keys", "ResourceId", "VersionId"},
			"delete-document":                     {"AuthenticationToken", "DocumentId"},
			"delete-document-version":             {"AuthenticationToken", "DeletePriorVersions", "DocumentId", "VersionId"},
			"delete-folder":                       {"AuthenticationToken", "FolderId"},
			"delete-folder-contents":              {"AuthenticationToken", "FolderId"},
			"delete-labels":                       {"AuthenticationToken", "DeleteAll", "Labels", "ResourceId"},
			"delete-notification-subscription":    {"OrganizationId", "SubscriptionId"},
			"delete-user":                         {"AuthenticationToken", "UserId"},
			"describe-activities":                 {"ActivityTypes", "AuthenticationToken", "EndTime", "IncludeIndirectActivities", "Limit", "Marker", "OrganizationId", "ResourceId", "StartTime", "UserId"},
			"describe-comments":                   {"AuthenticationToken", "DocumentId", "Limit", "Marker", "VersionId"},
			"describe-document-versions":          {"AuthenticationToken", "DocumentId", "Fields", "Include", "Limit", "Marker"},
			"describe-folder-contents":            {"AuthenticationToken", "FolderId", "Include", "Limit", "Marker", "Order", "Sort", "Type"},
			"describe-groups":                     {"AuthenticationToken", "Limit", "Marker", "OrganizationId", "SearchQuery"},
			"describe-notification-subscriptions": {"Limit", "Marker", "OrganizationId"},
			"describe-resource-permissions":       {"AuthenticationToken", "Limit", "Marker", "PrincipalId", "ResourceId"},
			"describe-root-folders":               {"AuthenticationToken", "Limit", "Marker"},
			"describe-users":                      {"AuthenticationToken", "Fields", "Include", "Limit", "Marker", "Order", "OrganizationId", "Query", "Sort", "UserIds"},
			"get-current-user":                    {"AuthenticationToken"},
			"get-document":                        {"AuthenticationToken", "DocumentId", "IncludeCustomMetadata"},
			"get-document-path":                   {"AuthenticationToken", "DocumentId", "Fields", "Limit", "Marker"},
			"get-document-version":                {"AuthenticationToken", "DocumentId", "Fields", "IncludeCustomMetadata", "VersionId"},
			"get-folder":                          {"AuthenticationToken", "FolderId", "IncludeCustomMetadata"},
			"get-folder-path":                     {"AuthenticationToken", "Fields", "FolderId", "Limit", "Marker"},
			"get-resources":                       {"AuthenticationToken", "CollectionType", "Limit", "Marker", "UserId"},
			"initiate-document-version-upload":    {"AuthenticationToken", "ContentCreatedTimestamp", "ContentModifiedTimestamp", "ContentType", "DocumentSizeInBytes", "Id", "Name", "ParentFolderId"},
			"remove-all-resource-permissions":     {"AuthenticationToken", "ResourceId"},
			"remove-resource-permission":          {"AuthenticationToken", "PrincipalId", "PrincipalType", "ResourceId"},
			"restore-document-versions":           {"AuthenticationToken", "DocumentId"},
			"search-resources":                    {"AdditionalResponseFields", "AuthenticationToken", "Filters", "Limit", "Marker", "OrderBy", "OrganizationId", "QueryScopes", "QueryText"},
			"update-document":                     {"AuthenticationToken", "DocumentId", "Name", "ParentFolderId", "ResourceState"},
			"update-document-version":             {"AuthenticationToken", "DocumentId", "VersionId", "VersionStatus"},
			"update-folder":                       {"AuthenticationToken", "FolderId", "Name", "ParentFolderId", "ResourceState"},
			"update-user":                         {"AuthenticationToken", "GivenName", "GrantPoweruserPrivileges", "Locale", "StorageRule", "Surname", "TimeZoneId", "Type", "UserId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"abort-document-version-upload":       {"AuthenticationToken": "*string", "DocumentId": "*string", "VersionId": "*string"},
			"activate-user":                       {"AuthenticationToken": "*string", "UserId": "*string"},
			"add-resource-permissions":            {"AuthenticationToken": "*string", "NotificationOptions": "*types.NotificationOptions", "Principals": "[]types.SharePrincipal", "ResourceId": "*string"},
			"create-comment":                      {"AuthenticationToken": "*string", "DocumentId": "*string", "NotifyCollaborators": "bool", "ParentId": "*string", "Text": "*string", "ThreadId": "*string", "VersionId": "*string", "Visibility": "types.CommentVisibilityType"},
			"create-custom-metadata":              {"AuthenticationToken": "*string", "CustomMetadata": "map[string]string", "ResourceId": "*string", "VersionId": "*string"},
			"create-folder":                       {"AuthenticationToken": "*string", "Name": "*string", "ParentFolderId": "*string"},
			"create-labels":                       {"AuthenticationToken": "*string", "Labels": "[]string", "ResourceId": "*string"},
			"create-notification-subscription":    {"Endpoint": "*string", "OrganizationId": "*string", "Protocol": "types.SubscriptionProtocolType", "SubscriptionType": "types.SubscriptionType"},
			"create-user":                         {"AuthenticationToken": "*string", "EmailAddress": "*string", "GivenName": "*string", "OrganizationId": "*string", "Password": "*string", "StorageRule": "*types.StorageRuleType", "Surname": "*string", "TimeZoneId": "*string", "Username": "*string"},
			"deactivate-user":                     {"AuthenticationToken": "*string", "UserId": "*string"},
			"delete-comment":                      {"AuthenticationToken": "*string", "CommentId": "*string", "DocumentId": "*string", "VersionId": "*string"},
			"delete-custom-metadata":              {"AuthenticationToken": "*string", "DeleteAll": "bool", "Keys": "[]string", "ResourceId": "*string", "VersionId": "*string"},
			"delete-document":                     {"AuthenticationToken": "*string", "DocumentId": "*string"},
			"delete-document-version":             {"AuthenticationToken": "*string", "DeletePriorVersions": "bool", "DocumentId": "*string", "VersionId": "*string"},
			"delete-folder":                       {"AuthenticationToken": "*string", "FolderId": "*string"},
			"delete-folder-contents":              {"AuthenticationToken": "*string", "FolderId": "*string"},
			"delete-labels":                       {"AuthenticationToken": "*string", "DeleteAll": "bool", "Labels": "[]string", "ResourceId": "*string"},
			"delete-notification-subscription":    {"OrganizationId": "*string", "SubscriptionId": "*string"},
			"delete-user":                         {"AuthenticationToken": "*string", "UserId": "*string"},
			"describe-activities":                 {"ActivityTypes": "*string", "AuthenticationToken": "*string", "EndTime": "*time.Time", "IncludeIndirectActivities": "bool", "Limit": "*int32", "Marker": "*string", "OrganizationId": "*string", "ResourceId": "*string", "StartTime": "*time.Time", "UserId": "*string"},
			"describe-comments":                   {"AuthenticationToken": "*string", "DocumentId": "*string", "Limit": "*int32", "Marker": "*string", "VersionId": "*string"},
			"describe-document-versions":          {"AuthenticationToken": "*string", "DocumentId": "*string", "Fields": "*string", "Include": "*string", "Limit": "*int32", "Marker": "*string"},
			"describe-folder-contents":            {"AuthenticationToken": "*string", "FolderId": "*string", "Include": "*string", "Limit": "*int32", "Marker": "*string", "Order": "types.OrderType", "Sort": "types.ResourceSortType", "Type": "types.FolderContentType"},
			"describe-groups":                     {"AuthenticationToken": "*string", "Limit": "*int32", "Marker": "*string", "OrganizationId": "*string", "SearchQuery": "*string"},
			"describe-notification-subscriptions": {"Limit": "*int32", "Marker": "*string", "OrganizationId": "*string"},
			"describe-resource-permissions":       {"AuthenticationToken": "*string", "Limit": "*int32", "Marker": "*string", "PrincipalId": "*string", "ResourceId": "*string"},
			"describe-root-folders":               {"AuthenticationToken": "*string", "Limit": "*int32", "Marker": "*string"},
			"describe-users":                      {"AuthenticationToken": "*string", "Fields": "*string", "Include": "types.UserFilterType", "Limit": "*int32", "Marker": "*string", "Order": "types.OrderType", "OrganizationId": "*string", "Query": "*string", "Sort": "types.UserSortType", "UserIds": "*string"},
			"get-current-user":                    {"AuthenticationToken": "*string"},
			"get-document":                        {"AuthenticationToken": "*string", "DocumentId": "*string", "IncludeCustomMetadata": "bool"},
			"get-document-path":                   {"AuthenticationToken": "*string", "DocumentId": "*string", "Fields": "*string", "Limit": "*int32", "Marker": "*string"},
			"get-document-version":                {"AuthenticationToken": "*string", "DocumentId": "*string", "Fields": "*string", "IncludeCustomMetadata": "bool", "VersionId": "*string"},
			"get-folder":                          {"AuthenticationToken": "*string", "FolderId": "*string", "IncludeCustomMetadata": "bool"},
			"get-folder-path":                     {"AuthenticationToken": "*string", "Fields": "*string", "FolderId": "*string", "Limit": "*int32", "Marker": "*string"},
			"get-resources":                       {"AuthenticationToken": "*string", "CollectionType": "types.ResourceCollectionType", "Limit": "*int32", "Marker": "*string", "UserId": "*string"},
			"initiate-document-version-upload":    {"AuthenticationToken": "*string", "ContentCreatedTimestamp": "*time.Time", "ContentModifiedTimestamp": "*time.Time", "ContentType": "*string", "DocumentSizeInBytes": "*int64", "Id": "*string", "Name": "*string", "ParentFolderId": "*string"},
			"remove-all-resource-permissions":     {"AuthenticationToken": "*string", "ResourceId": "*string"},
			"remove-resource-permission":          {"AuthenticationToken": "*string", "PrincipalId": "*string", "PrincipalType": "types.PrincipalType", "ResourceId": "*string"},
			"restore-document-versions":           {"AuthenticationToken": "*string", "DocumentId": "*string"},
			"search-resources":                    {"AdditionalResponseFields": "[]types.AdditionalResponseFieldType", "AuthenticationToken": "*string", "Filters": "*types.Filters", "Limit": "*int32", "Marker": "*string", "OrderBy": "[]types.SearchSortResult", "OrganizationId": "*string", "QueryScopes": "[]types.SearchQueryScopeType", "QueryText": "*string"},
			"update-document":                     {"AuthenticationToken": "*string", "DocumentId": "*string", "Name": "*string", "ParentFolderId": "*string", "ResourceState": "types.ResourceStateType"},
			"update-document-version":             {"AuthenticationToken": "*string", "DocumentId": "*string", "VersionId": "*string", "VersionStatus": "types.DocumentVersionStatus"},
			"update-folder":                       {"AuthenticationToken": "*string", "FolderId": "*string", "Name": "*string", "ParentFolderId": "*string", "ResourceState": "types.ResourceStateType"},
			"update-user":                         {"AuthenticationToken": "*string", "GivenName": "*string", "GrantPoweruserPrivileges": "types.BooleanEnumType", "Locale": "types.LocaleType", "StorageRule": "*types.StorageRuleType", "Surname": "*string", "TimeZoneId": "*string", "Type": "types.UserType", "UserId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"abort-document-version-upload":       {"DocumentId", "VersionId"},
			"activate-user":                       {"UserId"},
			"add-resource-permissions":            {"Principals", "ResourceId"},
			"create-comment":                      {"DocumentId", "Text", "VersionId"},
			"create-custom-metadata":              {"CustomMetadata", "ResourceId"},
			"create-folder":                       {"ParentFolderId"},
			"create-labels":                       {"Labels", "ResourceId"},
			"create-notification-subscription":    {"Endpoint", "OrganizationId", "Protocol", "SubscriptionType"},
			"create-user":                         {"GivenName", "Password", "Surname", "Username"},
			"deactivate-user":                     {"UserId"},
			"delete-comment":                      {"CommentId", "DocumentId", "VersionId"},
			"delete-custom-metadata":              {"ResourceId"},
			"delete-document":                     {"DocumentId"},
			"delete-document-version":             {"DeletePriorVersions", "DocumentId", "VersionId"},
			"delete-folder":                       {"FolderId"},
			"delete-folder-contents":              {"FolderId"},
			"delete-labels":                       {"ResourceId"},
			"delete-notification-subscription":    {"OrganizationId", "SubscriptionId"},
			"delete-user":                         {"UserId"},
			"describe-activities":                 {},
			"describe-comments":                   {"DocumentId", "VersionId"},
			"describe-document-versions":          {"DocumentId"},
			"describe-folder-contents":            {"FolderId"},
			"describe-groups":                     {"SearchQuery"},
			"describe-notification-subscriptions": {"OrganizationId"},
			"describe-resource-permissions":       {"ResourceId"},
			"describe-root-folders":               {"AuthenticationToken"},
			"describe-users":                      {},
			"get-current-user":                    {"AuthenticationToken"},
			"get-document":                        {"DocumentId"},
			"get-document-path":                   {"DocumentId"},
			"get-document-version":                {"DocumentId", "VersionId"},
			"get-folder":                          {"FolderId"},
			"get-folder-path":                     {"FolderId"},
			"get-resources":                       {},
			"initiate-document-version-upload":    {},
			"remove-all-resource-permissions":     {"ResourceId"},
			"remove-resource-permission":          {"PrincipalId", "ResourceId"},
			"restore-document-versions":           {"DocumentId"},
			"search-resources":                    {},
			"update-document":                     {"DocumentId"},
			"update-document-version":             {"DocumentId", "VersionId"},
			"update-folder":                       {"FolderId"},
			"update-user":                         {"UserId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("workdocs", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
