package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/sesv2/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-get-metric-data", "cancel-export-job", "create-configuration-set", "create-configuration-set-event-destination", "create-contact", "create-contact-list", "create-custom-verification-email-template", "create-dedicated-ip-pool", "create-deliverability-test-report", "create-email-identity", "create-email-identity-policy", "create-email-template", "create-export-job", "create-import-job", "create-multi-region-endpoint", "create-tenant", "create-tenant-resource-association", "delete-configuration-set", "delete-configuration-set-event-destination", "delete-contact", "delete-contact-list", "delete-custom-verification-email-template", "delete-dedicated-ip-pool", "delete-email-identity", "delete-email-identity-policy", "delete-email-template", "delete-multi-region-endpoint", "delete-suppressed-destination", "delete-tenant", "delete-tenant-resource-association", "get-account", "get-blacklist-reports", "get-configuration-set", "get-configuration-set-event-destinations", "get-contact", "get-contact-list", "get-custom-verification-email-template", "get-dedicated-ip", "get-dedicated-ip-pool", "get-dedicated-ips", "get-deliverability-dashboard-options", "get-deliverability-test-report", "get-domain-deliverability-campaign", "get-domain-statistics-report", "get-email-address-insights", "get-email-identity", "get-email-identity-policies", "get-email-template", "get-export-job", "get-import-job", "get-message-insights", "get-multi-region-endpoint", "get-reputation-entity", "get-suppressed-destination", "get-tenant", "list-configuration-sets", "list-contact-lists", "list-contacts", "list-custom-verification-email-templates", "list-dedicated-ip-pools", "list-deliverability-test-reports", "list-domain-deliverability-campaigns", "list-email-identities", "list-email-templates", "list-export-jobs", "list-import-jobs", "list-multi-region-endpoints", "list-recommendations", "list-reputation-entities", "list-resource-tenants", "list-suppressed-destinations", "list-tags-for-resource", "list-tenant-resources", "list-tenants", "put-account-dedicated-ip-warmup-attributes", "put-account-details", "put-account-sending-attributes", "put-account-suppression-attributes", "put-account-vdm-attributes", "put-configuration-set-archiving-options", "put-configuration-set-delivery-options", "put-configuration-set-reputation-options", "put-configuration-set-sending-options", "put-configuration-set-suppression-options", "put-configuration-set-tracking-options", "put-configuration-set-vdm-options", "put-dedicated-ip-in-pool", "put-dedicated-ip-pool-scaling-attributes", "put-dedicated-ip-warmup-attributes", "put-deliverability-dashboard-option", "put-email-identity-configuration-set-attributes", "put-email-identity-dkim-attributes", "put-email-identity-dkim-signing-attributes", "put-email-identity-feedback-attributes", "put-email-identity-mail-from-attributes", "put-suppressed-destination", "send-bulk-email", "send-custom-verification-email", "send-email", "tag-resource", "test-render-email-template", "untag-resource", "update-configuration-set-event-destination", "update-contact", "update-contact-list", "update-custom-verification-email-template", "update-email-identity-policy", "update-email-template", "update-reputation-entity-customer-managed-status", "update-reputation-entity-policy"},
		OperationSet: map[string]bool{"batch-get-metric-data": true, "cancel-export-job": true, "create-configuration-set": true, "create-configuration-set-event-destination": true, "create-contact": true, "create-contact-list": true, "create-custom-verification-email-template": true, "create-dedicated-ip-pool": true, "create-deliverability-test-report": true, "create-email-identity": true, "create-email-identity-policy": true, "create-email-template": true, "create-export-job": true, "create-import-job": true, "create-multi-region-endpoint": true, "create-tenant": true, "create-tenant-resource-association": true, "delete-configuration-set": true, "delete-configuration-set-event-destination": true, "delete-contact": true, "delete-contact-list": true, "delete-custom-verification-email-template": true, "delete-dedicated-ip-pool": true, "delete-email-identity": true, "delete-email-identity-policy": true, "delete-email-template": true, "delete-multi-region-endpoint": true, "delete-suppressed-destination": true, "delete-tenant": true, "delete-tenant-resource-association": true, "get-account": true, "get-blacklist-reports": true, "get-configuration-set": true, "get-configuration-set-event-destinations": true, "get-contact": true, "get-contact-list": true, "get-custom-verification-email-template": true, "get-dedicated-ip": true, "get-dedicated-ip-pool": true, "get-dedicated-ips": true, "get-deliverability-dashboard-options": true, "get-deliverability-test-report": true, "get-domain-deliverability-campaign": true, "get-domain-statistics-report": true, "get-email-address-insights": true, "get-email-identity": true, "get-email-identity-policies": true, "get-email-template": true, "get-export-job": true, "get-import-job": true, "get-message-insights": true, "get-multi-region-endpoint": true, "get-reputation-entity": true, "get-suppressed-destination": true, "get-tenant": true, "list-configuration-sets": true, "list-contact-lists": true, "list-contacts": true, "list-custom-verification-email-templates": true, "list-dedicated-ip-pools": true, "list-deliverability-test-reports": true, "list-domain-deliverability-campaigns": true, "list-email-identities": true, "list-email-templates": true, "list-export-jobs": true, "list-import-jobs": true, "list-multi-region-endpoints": true, "list-recommendations": true, "list-reputation-entities": true, "list-resource-tenants": true, "list-suppressed-destinations": true, "list-tags-for-resource": true, "list-tenant-resources": true, "list-tenants": true, "put-account-dedicated-ip-warmup-attributes": true, "put-account-details": true, "put-account-sending-attributes": true, "put-account-suppression-attributes": true, "put-account-vdm-attributes": true, "put-configuration-set-archiving-options": true, "put-configuration-set-delivery-options": true, "put-configuration-set-reputation-options": true, "put-configuration-set-sending-options": true, "put-configuration-set-suppression-options": true, "put-configuration-set-tracking-options": true, "put-configuration-set-vdm-options": true, "put-dedicated-ip-in-pool": true, "put-dedicated-ip-pool-scaling-attributes": true, "put-dedicated-ip-warmup-attributes": true, "put-deliverability-dashboard-option": true, "put-email-identity-configuration-set-attributes": true, "put-email-identity-dkim-attributes": true, "put-email-identity-dkim-signing-attributes": true, "put-email-identity-feedback-attributes": true, "put-email-identity-mail-from-attributes": true, "put-suppressed-destination": true, "send-bulk-email": true, "send-custom-verification-email": true, "send-email": true, "tag-resource": true, "test-render-email-template": true, "untag-resource": true, "update-configuration-set-event-destination": true, "update-contact": true, "update-contact-list": true, "update-custom-verification-email-template": true, "update-email-identity-policy": true, "update-email-template": true, "update-reputation-entity-customer-managed-status": true, "update-reputation-entity-policy": true},
		OperationInputs: map[string][]string{
			"batch-get-metric-data":                            {"Queries"},
			"cancel-export-job":                                {"JobId"},
			"create-configuration-set":                         {"ArchivingOptions", "ConfigurationSetName", "DeliveryOptions", "ReputationOptions", "SendingOptions", "SuppressionOptions", "Tags", "TrackingOptions", "VdmOptions"},
			"create-configuration-set-event-destination":       {"ConfigurationSetName", "EventDestination", "EventDestinationName"},
			"create-contact":                                   {"AttributesData", "ContactListName", "EmailAddress", "TopicPreferences", "UnsubscribeAll"},
			"create-contact-list":                              {"ContactListName", "Description", "Tags", "Topics"},
			"create-custom-verification-email-template":        {"FailureRedirectionURL", "FromEmailAddress", "SuccessRedirectionURL", "Tags", "TemplateContent", "TemplateName", "TemplateSubject"},
			"create-dedicated-ip-pool":                         {"PoolName", "ScalingMode", "Tags"},
			"create-deliverability-test-report":                {"Content", "FromEmailAddress", "ReportName", "Tags"},
			"create-email-identity":                            {"ConfigurationSetName", "DkimSigningAttributes", "EmailIdentity", "Tags"},
			"create-email-identity-policy":                     {"EmailIdentity", "Policy", "PolicyName"},
			"create-email-template":                            {"Tags", "TemplateContent", "TemplateName"},
			"create-export-job":                                {"ExportDataSource", "ExportDestination"},
			"create-import-job":                                {"ImportDataSource", "ImportDestination"},
			"create-multi-region-endpoint":                     {"Details", "EndpointName", "Tags"},
			"create-tenant":                                    {"Tags", "TenantName"},
			"create-tenant-resource-association":               {"ResourceArn", "TenantName"},
			"delete-configuration-set":                         {"ConfigurationSetName"},
			"delete-configuration-set-event-destination":       {"ConfigurationSetName", "EventDestinationName"},
			"delete-contact":                                   {"ContactListName", "EmailAddress"},
			"delete-contact-list":                              {"ContactListName"},
			"delete-custom-verification-email-template":        {"TemplateName"},
			"delete-dedicated-ip-pool":                         {"PoolName"},
			"delete-email-identity":                            {"EmailIdentity"},
			"delete-email-identity-policy":                     {"EmailIdentity", "PolicyName"},
			"delete-email-template":                            {"TemplateName"},
			"delete-multi-region-endpoint":                     {"EndpointName"},
			"delete-suppressed-destination":                    {"EmailAddress"},
			"delete-tenant":                                    {"TenantName"},
			"delete-tenant-resource-association":               {"ResourceArn", "TenantName"},
			"get-account":                                      {},
			"get-blacklist-reports":                            {"BlacklistItemNames"},
			"get-configuration-set":                            {"ConfigurationSetName"},
			"get-configuration-set-event-destinations":         {"ConfigurationSetName"},
			"get-contact":                                      {"ContactListName", "EmailAddress"},
			"get-contact-list":                                 {"ContactListName"},
			"get-custom-verification-email-template":           {"TemplateName"},
			"get-dedicated-ip":                                 {"Ip"},
			"get-dedicated-ip-pool":                            {"PoolName"},
			"get-dedicated-ips":                                {"NextToken", "PageSize", "PoolName"},
			"get-deliverability-dashboard-options":             {},
			"get-deliverability-test-report":                   {"ReportId"},
			"get-domain-deliverability-campaign":               {"CampaignId"},
			"get-domain-statistics-report":                     {"Domain", "EndDate", "StartDate"},
			"get-email-address-insights":                       {"EmailAddress"},
			"get-email-identity":                               {"EmailIdentity"},
			"get-email-identity-policies":                      {"EmailIdentity"},
			"get-email-template":                               {"TemplateName"},
			"get-export-job":                                   {"JobId"},
			"get-import-job":                                   {"JobId"},
			"get-message-insights":                             {"MessageId"},
			"get-multi-region-endpoint":                        {"EndpointName"},
			"get-reputation-entity":                            {"ReputationEntityReference", "ReputationEntityType"},
			"get-suppressed-destination":                       {"EmailAddress"},
			"get-tenant":                                       {"TenantName"},
			"list-configuration-sets":                          {"NextToken", "PageSize"},
			"list-contact-lists":                               {"NextToken", "PageSize"},
			"list-contacts":                                    {"ContactListName", "Filter", "NextToken", "PageSize"},
			"list-custom-verification-email-templates":         {"NextToken", "PageSize"},
			"list-dedicated-ip-pools":                          {"NextToken", "PageSize"},
			"list-deliverability-test-reports":                 {"NextToken", "PageSize"},
			"list-domain-deliverability-campaigns":             {"EndDate", "NextToken", "PageSize", "StartDate", "SubscribedDomain"},
			"list-email-identities":                            {"NextToken", "PageSize"},
			"list-email-templates":                             {"NextToken", "PageSize"},
			"list-export-jobs":                                 {"ExportSourceType", "JobStatus", "NextToken", "PageSize"},
			"list-import-jobs":                                 {"ImportDestinationType", "NextToken", "PageSize"},
			"list-multi-region-endpoints":                      {"NextToken", "PageSize"},
			"list-recommendations":                             {"Filter", "NextToken", "PageSize"},
			"list-reputation-entities":                         {"Filter", "NextToken", "PageSize"},
			"list-resource-tenants":                            {"NextToken", "PageSize", "ResourceArn"},
			"list-suppressed-destinations":                     {"EndDate", "NextToken", "PageSize", "Reasons", "StartDate"},
			"list-tags-for-resource":                           {"ResourceArn"},
			"list-tenant-resources":                            {"Filter", "NextToken", "PageSize", "TenantName"},
			"list-tenants":                                     {"NextToken", "PageSize"},
			"put-account-dedicated-ip-warmup-attributes":       {"AutoWarmupEnabled"},
			"put-account-details":                              {"AdditionalContactEmailAddresses", "ContactLanguage", "MailType", "ProductionAccessEnabled", "UseCaseDescription", "WebsiteURL"},
			"put-account-sending-attributes":                   {"SendingEnabled"},
			"put-account-suppression-attributes":               {"SuppressedReasons", "ValidationAttributes"},
			"put-account-vdm-attributes":                       {"VdmAttributes"},
			"put-configuration-set-archiving-options":          {"ArchiveArn", "ConfigurationSetName"},
			"put-configuration-set-delivery-options":           {"ConfigurationSetName", "MaxDeliverySeconds", "SendingPoolName", "TlsPolicy"},
			"put-configuration-set-reputation-options":         {"ConfigurationSetName", "ReputationMetricsEnabled"},
			"put-configuration-set-sending-options":            {"ConfigurationSetName", "SendingEnabled"},
			"put-configuration-set-suppression-options":        {"ConfigurationSetName", "SuppressedReasons", "ValidationOptions"},
			"put-configuration-set-tracking-options":           {"ConfigurationSetName", "CustomRedirectDomain", "HttpsPolicy"},
			"put-configuration-set-vdm-options":                {"ConfigurationSetName", "VdmOptions"},
			"put-dedicated-ip-in-pool":                         {"DestinationPoolName", "Ip"},
			"put-dedicated-ip-pool-scaling-attributes":         {"PoolName", "ScalingMode"},
			"put-dedicated-ip-warmup-attributes":               {"Ip", "WarmupPercentage"},
			"put-deliverability-dashboard-option":              {"DashboardEnabled", "SubscribedDomains"},
			"put-email-identity-configuration-set-attributes":  {"ConfigurationSetName", "EmailIdentity"},
			"put-email-identity-dkim-attributes":               {"EmailIdentity", "SigningEnabled"},
			"put-email-identity-dkim-signing-attributes":       {"EmailIdentity", "SigningAttributes", "SigningAttributesOrigin"},
			"put-email-identity-feedback-attributes":           {"EmailForwardingEnabled", "EmailIdentity"},
			"put-email-identity-mail-from-attributes":          {"BehaviorOnMxFailure", "EmailIdentity", "MailFromDomain"},
			"put-suppressed-destination":                       {"EmailAddress", "Reason"},
			"send-bulk-email":                                  {"BulkEmailEntries", "ConfigurationSetName", "DefaultContent", "DefaultEmailTags", "EndpointId", "FeedbackForwardingEmailAddress", "FeedbackForwardingEmailAddressIdentityArn", "FromEmailAddress", "FromEmailAddressIdentityArn", "ReplyToAddresses", "TenantName"},
			"send-custom-verification-email":                   {"ConfigurationSetName", "EmailAddress", "TemplateName"},
			"send-email":                                       {"ConfigurationSetName", "Content", "Destination", "EmailTags", "EndpointId", "FeedbackForwardingEmailAddress", "FeedbackForwardingEmailAddressIdentityArn", "FromEmailAddress", "FromEmailAddressIdentityArn", "ListManagementOptions", "ReplyToAddresses", "TenantName"},
			"tag-resource":                                     {"ResourceArn", "Tags"},
			"test-render-email-template":                       {"TemplateData", "TemplateName"},
			"untag-resource":                                   {"ResourceArn", "TagKeys"},
			"update-configuration-set-event-destination":       {"ConfigurationSetName", "EventDestination", "EventDestinationName"},
			"update-contact":                                   {"AttributesData", "ContactListName", "EmailAddress", "TopicPreferences", "UnsubscribeAll"},
			"update-contact-list":                              {"ContactListName", "Description", "Topics"},
			"update-custom-verification-email-template":        {"FailureRedirectionURL", "FromEmailAddress", "SuccessRedirectionURL", "TemplateContent", "TemplateName", "TemplateSubject"},
			"update-email-identity-policy":                     {"EmailIdentity", "Policy", "PolicyName"},
			"update-email-template":                            {"TemplateContent", "TemplateName"},
			"update-reputation-entity-customer-managed-status": {"ReputationEntityReference", "ReputationEntityType", "SendingStatus"},
			"update-reputation-entity-policy":                  {"ReputationEntityPolicy", "ReputationEntityReference", "ReputationEntityType"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-get-metric-data":                            {"Queries": "[]types.BatchGetMetricDataQuery"},
			"cancel-export-job":                                {"JobId": "*string"},
			"create-configuration-set":                         {"ArchivingOptions": "*types.ArchivingOptions", "ConfigurationSetName": "*string", "DeliveryOptions": "*types.DeliveryOptions", "ReputationOptions": "*types.ReputationOptions", "SendingOptions": "*types.SendingOptions", "SuppressionOptions": "*types.SuppressionOptions", "Tags": "[]types.Tag", "TrackingOptions": "*types.TrackingOptions", "VdmOptions": "*types.VdmOptions"},
			"create-configuration-set-event-destination":       {"ConfigurationSetName": "*string", "EventDestination": "*types.EventDestinationDefinition", "EventDestinationName": "*string"},
			"create-contact":                                   {"AttributesData": "*string", "ContactListName": "*string", "EmailAddress": "*string", "TopicPreferences": "[]types.TopicPreference", "UnsubscribeAll": "bool"},
			"create-contact-list":                              {"ContactListName": "*string", "Description": "*string", "Tags": "[]types.Tag", "Topics": "[]types.Topic"},
			"create-custom-verification-email-template":        {"FailureRedirectionURL": "*string", "FromEmailAddress": "*string", "SuccessRedirectionURL": "*string", "Tags": "[]types.Tag", "TemplateContent": "*string", "TemplateName": "*string", "TemplateSubject": "*string"},
			"create-dedicated-ip-pool":                         {"PoolName": "*string", "ScalingMode": "types.ScalingMode", "Tags": "[]types.Tag"},
			"create-deliverability-test-report":                {"Content": "*types.EmailContent", "FromEmailAddress": "*string", "ReportName": "*string", "Tags": "[]types.Tag"},
			"create-email-identity":                            {"ConfigurationSetName": "*string", "DkimSigningAttributes": "*types.DkimSigningAttributes", "EmailIdentity": "*string", "Tags": "[]types.Tag"},
			"create-email-identity-policy":                     {"EmailIdentity": "*string", "Policy": "*string", "PolicyName": "*string"},
			"create-email-template":                            {"Tags": "[]types.Tag", "TemplateContent": "*types.EmailTemplateContent", "TemplateName": "*string"},
			"create-export-job":                                {"ExportDataSource": "*types.ExportDataSource", "ExportDestination": "*types.ExportDestination"},
			"create-import-job":                                {"ImportDataSource": "*types.ImportDataSource", "ImportDestination": "*types.ImportDestination"},
			"create-multi-region-endpoint":                     {"Details": "*types.Details", "EndpointName": "*string", "Tags": "[]types.Tag"},
			"create-tenant":                                    {"Tags": "[]types.Tag", "TenantName": "*string"},
			"create-tenant-resource-association":               {"ResourceArn": "*string", "TenantName": "*string"},
			"delete-configuration-set":                         {"ConfigurationSetName": "*string"},
			"delete-configuration-set-event-destination":       {"ConfigurationSetName": "*string", "EventDestinationName": "*string"},
			"delete-contact":                                   {"ContactListName": "*string", "EmailAddress": "*string"},
			"delete-contact-list":                              {"ContactListName": "*string"},
			"delete-custom-verification-email-template":        {"TemplateName": "*string"},
			"delete-dedicated-ip-pool":                         {"PoolName": "*string"},
			"delete-email-identity":                            {"EmailIdentity": "*string"},
			"delete-email-identity-policy":                     {"EmailIdentity": "*string", "PolicyName": "*string"},
			"delete-email-template":                            {"TemplateName": "*string"},
			"delete-multi-region-endpoint":                     {"EndpointName": "*string"},
			"delete-suppressed-destination":                    {"EmailAddress": "*string"},
			"delete-tenant":                                    {"TenantName": "*string"},
			"delete-tenant-resource-association":               {"ResourceArn": "*string", "TenantName": "*string"},
			"get-account":                                      {},
			"get-blacklist-reports":                            {"BlacklistItemNames": "[]string"},
			"get-configuration-set":                            {"ConfigurationSetName": "*string"},
			"get-configuration-set-event-destinations":         {"ConfigurationSetName": "*string"},
			"get-contact":                                      {"ContactListName": "*string", "EmailAddress": "*string"},
			"get-contact-list":                                 {"ContactListName": "*string"},
			"get-custom-verification-email-template":           {"TemplateName": "*string"},
			"get-dedicated-ip":                                 {"Ip": "*string"},
			"get-dedicated-ip-pool":                            {"PoolName": "*string"},
			"get-dedicated-ips":                                {"NextToken": "*string", "PageSize": "*int32", "PoolName": "*string"},
			"get-deliverability-dashboard-options":             {},
			"get-deliverability-test-report":                   {"ReportId": "*string"},
			"get-domain-deliverability-campaign":               {"CampaignId": "*string"},
			"get-domain-statistics-report":                     {"Domain": "*string", "EndDate": "*time.Time", "StartDate": "*time.Time"},
			"get-email-address-insights":                       {"EmailAddress": "*string"},
			"get-email-identity":                               {"EmailIdentity": "*string"},
			"get-email-identity-policies":                      {"EmailIdentity": "*string"},
			"get-email-template":                               {"TemplateName": "*string"},
			"get-export-job":                                   {"JobId": "*string"},
			"get-import-job":                                   {"JobId": "*string"},
			"get-message-insights":                             {"MessageId": "*string"},
			"get-multi-region-endpoint":                        {"EndpointName": "*string"},
			"get-reputation-entity":                            {"ReputationEntityReference": "*string", "ReputationEntityType": "types.ReputationEntityType"},
			"get-suppressed-destination":                       {"EmailAddress": "*string"},
			"get-tenant":                                       {"TenantName": "*string"},
			"list-configuration-sets":                          {"NextToken": "*string", "PageSize": "*int32"},
			"list-contact-lists":                               {"NextToken": "*string", "PageSize": "*int32"},
			"list-contacts":                                    {"ContactListName": "*string", "Filter": "*types.ListContactsFilter", "NextToken": "*string", "PageSize": "*int32"},
			"list-custom-verification-email-templates":         {"NextToken": "*string", "PageSize": "*int32"},
			"list-dedicated-ip-pools":                          {"NextToken": "*string", "PageSize": "*int32"},
			"list-deliverability-test-reports":                 {"NextToken": "*string", "PageSize": "*int32"},
			"list-domain-deliverability-campaigns":             {"EndDate": "*time.Time", "NextToken": "*string", "PageSize": "*int32", "StartDate": "*time.Time", "SubscribedDomain": "*string"},
			"list-email-identities":                            {"NextToken": "*string", "PageSize": "*int32"},
			"list-email-templates":                             {"NextToken": "*string", "PageSize": "*int32"},
			"list-export-jobs":                                 {"ExportSourceType": "types.ExportSourceType", "JobStatus": "types.JobStatus", "NextToken": "*string", "PageSize": "*int32"},
			"list-import-jobs":                                 {"ImportDestinationType": "types.ImportDestinationType", "NextToken": "*string", "PageSize": "*int32"},
			"list-multi-region-endpoints":                      {"NextToken": "*string", "PageSize": "*int32"},
			"list-recommendations":                             {"Filter": "map[string]string", "NextToken": "*string", "PageSize": "*int32"},
			"list-reputation-entities":                         {"Filter": "map[string]string", "NextToken": "*string", "PageSize": "*int32"},
			"list-resource-tenants":                            {"NextToken": "*string", "PageSize": "*int32", "ResourceArn": "*string"},
			"list-suppressed-destinations":                     {"EndDate": "*time.Time", "NextToken": "*string", "PageSize": "*int32", "Reasons": "[]types.SuppressionListReason", "StartDate": "*time.Time"},
			"list-tags-for-resource":                           {"ResourceArn": "*string"},
			"list-tenant-resources":                            {"Filter": "map[string]string", "NextToken": "*string", "PageSize": "*int32", "TenantName": "*string"},
			"list-tenants":                                     {"NextToken": "*string", "PageSize": "*int32"},
			"put-account-dedicated-ip-warmup-attributes":       {"AutoWarmupEnabled": "bool"},
			"put-account-details":                              {"AdditionalContactEmailAddresses": "[]string", "ContactLanguage": "types.ContactLanguage", "MailType": "types.MailType", "ProductionAccessEnabled": "*bool", "UseCaseDescription": "*string", "WebsiteURL": "*string"},
			"put-account-sending-attributes":                   {"SendingEnabled": "bool"},
			"put-account-suppression-attributes":               {"SuppressedReasons": "[]types.SuppressionListReason", "ValidationAttributes": "*types.SuppressionValidationAttributes"},
			"put-account-vdm-attributes":                       {"VdmAttributes": "*types.VdmAttributes"},
			"put-configuration-set-archiving-options":          {"ArchiveArn": "*string", "ConfigurationSetName": "*string"},
			"put-configuration-set-delivery-options":           {"ConfigurationSetName": "*string", "MaxDeliverySeconds": "*int64", "SendingPoolName": "*string", "TlsPolicy": "types.TlsPolicy"},
			"put-configuration-set-reputation-options":         {"ConfigurationSetName": "*string", "ReputationMetricsEnabled": "bool"},
			"put-configuration-set-sending-options":            {"ConfigurationSetName": "*string", "SendingEnabled": "bool"},
			"put-configuration-set-suppression-options":        {"ConfigurationSetName": "*string", "SuppressedReasons": "[]types.SuppressionListReason", "ValidationOptions": "*types.SuppressionValidationOptions"},
			"put-configuration-set-tracking-options":           {"ConfigurationSetName": "*string", "CustomRedirectDomain": "*string", "HttpsPolicy": "types.HttpsPolicy"},
			"put-configuration-set-vdm-options":                {"ConfigurationSetName": "*string", "VdmOptions": "*types.VdmOptions"},
			"put-dedicated-ip-in-pool":                         {"DestinationPoolName": "*string", "Ip": "*string"},
			"put-dedicated-ip-pool-scaling-attributes":         {"PoolName": "*string", "ScalingMode": "types.ScalingMode"},
			"put-dedicated-ip-warmup-attributes":               {"Ip": "*string", "WarmupPercentage": "*int32"},
			"put-deliverability-dashboard-option":              {"DashboardEnabled": "bool", "SubscribedDomains": "[]types.DomainDeliverabilityTrackingOption"},
			"put-email-identity-configuration-set-attributes":  {"ConfigurationSetName": "*string", "EmailIdentity": "*string"},
			"put-email-identity-dkim-attributes":               {"EmailIdentity": "*string", "SigningEnabled": "bool"},
			"put-email-identity-dkim-signing-attributes":       {"EmailIdentity": "*string", "SigningAttributes": "*types.DkimSigningAttributes", "SigningAttributesOrigin": "types.DkimSigningAttributesOrigin"},
			"put-email-identity-feedback-attributes":           {"EmailForwardingEnabled": "bool", "EmailIdentity": "*string"},
			"put-email-identity-mail-from-attributes":          {"BehaviorOnMxFailure": "types.BehaviorOnMxFailure", "EmailIdentity": "*string", "MailFromDomain": "*string"},
			"put-suppressed-destination":                       {"EmailAddress": "*string", "Reason": "types.SuppressionListReason"},
			"send-bulk-email":                                  {"BulkEmailEntries": "[]types.BulkEmailEntry", "ConfigurationSetName": "*string", "DefaultContent": "*types.BulkEmailContent", "DefaultEmailTags": "[]types.MessageTag", "EndpointId": "*string", "FeedbackForwardingEmailAddress": "*string", "FeedbackForwardingEmailAddressIdentityArn": "*string", "FromEmailAddress": "*string", "FromEmailAddressIdentityArn": "*string", "ReplyToAddresses": "[]string", "TenantName": "*string"},
			"send-custom-verification-email":                   {"ConfigurationSetName": "*string", "EmailAddress": "*string", "TemplateName": "*string"},
			"send-email":                                       {"ConfigurationSetName": "*string", "Content": "*types.EmailContent", "Destination": "*types.Destination", "EmailTags": "[]types.MessageTag", "EndpointId": "*string", "FeedbackForwardingEmailAddress": "*string", "FeedbackForwardingEmailAddressIdentityArn": "*string", "FromEmailAddress": "*string", "FromEmailAddressIdentityArn": "*string", "ListManagementOptions": "*types.ListManagementOptions", "ReplyToAddresses": "[]string", "TenantName": "*string"},
			"tag-resource":                                     {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"test-render-email-template":                       {"TemplateData": "*string", "TemplateName": "*string"},
			"untag-resource":                                   {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-configuration-set-event-destination":       {"ConfigurationSetName": "*string", "EventDestination": "*types.EventDestinationDefinition", "EventDestinationName": "*string"},
			"update-contact":                                   {"AttributesData": "*string", "ContactListName": "*string", "EmailAddress": "*string", "TopicPreferences": "[]types.TopicPreference", "UnsubscribeAll": "bool"},
			"update-contact-list":                              {"ContactListName": "*string", "Description": "*string", "Topics": "[]types.Topic"},
			"update-custom-verification-email-template":        {"FailureRedirectionURL": "*string", "FromEmailAddress": "*string", "SuccessRedirectionURL": "*string", "TemplateContent": "*string", "TemplateName": "*string", "TemplateSubject": "*string"},
			"update-email-identity-policy":                     {"EmailIdentity": "*string", "Policy": "*string", "PolicyName": "*string"},
			"update-email-template":                            {"TemplateContent": "*types.EmailTemplateContent", "TemplateName": "*string"},
			"update-reputation-entity-customer-managed-status": {"ReputationEntityReference": "*string", "ReputationEntityType": "types.ReputationEntityType", "SendingStatus": "types.SendingStatus"},
			"update-reputation-entity-policy":                  {"ReputationEntityPolicy": "*string", "ReputationEntityReference": "*string", "ReputationEntityType": "types.ReputationEntityType"},
		},
		OperationInputRequired: map[string][]string{
			"batch-get-metric-data":                            {"Queries"},
			"cancel-export-job":                                {"JobId"},
			"create-configuration-set":                         {"ConfigurationSetName"},
			"create-configuration-set-event-destination":       {"ConfigurationSetName", "EventDestination", "EventDestinationName"},
			"create-contact":                                   {"ContactListName", "EmailAddress"},
			"create-contact-list":                              {"ContactListName"},
			"create-custom-verification-email-template":        {"FailureRedirectionURL", "FromEmailAddress", "SuccessRedirectionURL", "TemplateContent", "TemplateName", "TemplateSubject"},
			"create-dedicated-ip-pool":                         {"PoolName"},
			"create-deliverability-test-report":                {"Content", "FromEmailAddress"},
			"create-email-identity":                            {"EmailIdentity"},
			"create-email-identity-policy":                     {"EmailIdentity", "Policy", "PolicyName"},
			"create-email-template":                            {"TemplateContent", "TemplateName"},
			"create-export-job":                                {"ExportDataSource", "ExportDestination"},
			"create-import-job":                                {"ImportDataSource", "ImportDestination"},
			"create-multi-region-endpoint":                     {"Details", "EndpointName"},
			"create-tenant":                                    {"TenantName"},
			"create-tenant-resource-association":               {"ResourceArn", "TenantName"},
			"delete-configuration-set":                         {"ConfigurationSetName"},
			"delete-configuration-set-event-destination":       {"ConfigurationSetName", "EventDestinationName"},
			"delete-contact":                                   {"ContactListName", "EmailAddress"},
			"delete-contact-list":                              {"ContactListName"},
			"delete-custom-verification-email-template":        {"TemplateName"},
			"delete-dedicated-ip-pool":                         {"PoolName"},
			"delete-email-identity":                            {"EmailIdentity"},
			"delete-email-identity-policy":                     {"EmailIdentity", "PolicyName"},
			"delete-email-template":                            {"TemplateName"},
			"delete-multi-region-endpoint":                     {"EndpointName"},
			"delete-suppressed-destination":                    {"EmailAddress"},
			"delete-tenant":                                    {"TenantName"},
			"delete-tenant-resource-association":               {"ResourceArn", "TenantName"},
			"get-account":                                      {},
			"get-blacklist-reports":                            {"BlacklistItemNames"},
			"get-configuration-set":                            {"ConfigurationSetName"},
			"get-configuration-set-event-destinations":         {"ConfigurationSetName"},
			"get-contact":                                      {"ContactListName", "EmailAddress"},
			"get-contact-list":                                 {"ContactListName"},
			"get-custom-verification-email-template":           {"TemplateName"},
			"get-dedicated-ip":                                 {"Ip"},
			"get-dedicated-ip-pool":                            {"PoolName"},
			"get-dedicated-ips":                                {},
			"get-deliverability-dashboard-options":             {},
			"get-deliverability-test-report":                   {"ReportId"},
			"get-domain-deliverability-campaign":               {"CampaignId"},
			"get-domain-statistics-report":                     {"Domain", "EndDate", "StartDate"},
			"get-email-address-insights":                       {"EmailAddress"},
			"get-email-identity":                               {"EmailIdentity"},
			"get-email-identity-policies":                      {"EmailIdentity"},
			"get-email-template":                               {"TemplateName"},
			"get-export-job":                                   {"JobId"},
			"get-import-job":                                   {"JobId"},
			"get-message-insights":                             {"MessageId"},
			"get-multi-region-endpoint":                        {"EndpointName"},
			"get-reputation-entity":                            {"ReputationEntityReference", "ReputationEntityType"},
			"get-suppressed-destination":                       {"EmailAddress"},
			"get-tenant":                                       {"TenantName"},
			"list-configuration-sets":                          {},
			"list-contact-lists":                               {},
			"list-contacts":                                    {"ContactListName"},
			"list-custom-verification-email-templates":         {},
			"list-dedicated-ip-pools":                          {},
			"list-deliverability-test-reports":                 {},
			"list-domain-deliverability-campaigns":             {"EndDate", "StartDate", "SubscribedDomain"},
			"list-email-identities":                            {},
			"list-email-templates":                             {},
			"list-export-jobs":                                 {},
			"list-import-jobs":                                 {},
			"list-multi-region-endpoints":                      {},
			"list-recommendations":                             {},
			"list-reputation-entities":                         {},
			"list-resource-tenants":                            {"ResourceArn"},
			"list-suppressed-destinations":                     {},
			"list-tags-for-resource":                           {"ResourceArn"},
			"list-tenant-resources":                            {"TenantName"},
			"list-tenants":                                     {},
			"put-account-dedicated-ip-warmup-attributes":       {},
			"put-account-details":                              {"MailType", "WebsiteURL"},
			"put-account-sending-attributes":                   {},
			"put-account-suppression-attributes":               {},
			"put-account-vdm-attributes":                       {"VdmAttributes"},
			"put-configuration-set-archiving-options":          {"ConfigurationSetName"},
			"put-configuration-set-delivery-options":           {"ConfigurationSetName"},
			"put-configuration-set-reputation-options":         {"ConfigurationSetName"},
			"put-configuration-set-sending-options":            {"ConfigurationSetName"},
			"put-configuration-set-suppression-options":        {"ConfigurationSetName"},
			"put-configuration-set-tracking-options":           {"ConfigurationSetName"},
			"put-configuration-set-vdm-options":                {"ConfigurationSetName"},
			"put-dedicated-ip-in-pool":                         {"DestinationPoolName", "Ip"},
			"put-dedicated-ip-pool-scaling-attributes":         {"PoolName", "ScalingMode"},
			"put-dedicated-ip-warmup-attributes":               {"Ip", "WarmupPercentage"},
			"put-deliverability-dashboard-option":              {"DashboardEnabled"},
			"put-email-identity-configuration-set-attributes":  {"EmailIdentity"},
			"put-email-identity-dkim-attributes":               {"EmailIdentity"},
			"put-email-identity-dkim-signing-attributes":       {"EmailIdentity", "SigningAttributesOrigin"},
			"put-email-identity-feedback-attributes":           {"EmailIdentity"},
			"put-email-identity-mail-from-attributes":          {"EmailIdentity"},
			"put-suppressed-destination":                       {"EmailAddress", "Reason"},
			"send-bulk-email":                                  {"BulkEmailEntries", "DefaultContent"},
			"send-custom-verification-email":                   {"EmailAddress", "TemplateName"},
			"send-email":                                       {"Content"},
			"tag-resource":                                     {"ResourceArn", "Tags"},
			"test-render-email-template":                       {"TemplateData", "TemplateName"},
			"untag-resource":                                   {"ResourceArn", "TagKeys"},
			"update-configuration-set-event-destination":       {"ConfigurationSetName", "EventDestination", "EventDestinationName"},
			"update-contact":                                   {"ContactListName", "EmailAddress"},
			"update-contact-list":                              {"ContactListName"},
			"update-custom-verification-email-template":        {"FailureRedirectionURL", "FromEmailAddress", "SuccessRedirectionURL", "TemplateContent", "TemplateName", "TemplateSubject"},
			"update-email-identity-policy":                     {"EmailIdentity", "Policy", "PolicyName"},
			"update-email-template":                            {"TemplateContent", "TemplateName"},
			"update-reputation-entity-customer-managed-status": {"ReputationEntityReference", "ReputationEntityType", "SendingStatus"},
			"update-reputation-entity-policy":                  {"ReputationEntityPolicy", "ReputationEntityReference", "ReputationEntityType"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("sesv2", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
