package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/voiceid/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-fraudster", "create-domain", "create-watchlist", "delete-domain", "delete-fraudster", "delete-speaker", "delete-watchlist", "describe-domain", "describe-fraudster", "describe-fraudster-registration-job", "describe-speaker", "describe-speaker-enrollment-job", "describe-watchlist", "disassociate-fraudster", "evaluate-session", "list-domains", "list-fraudster-registration-jobs", "list-fraudsters", "list-speaker-enrollment-jobs", "list-speakers", "list-tags-for-resource", "list-watchlists", "opt-out-speaker", "start-fraudster-registration-job", "start-speaker-enrollment-job", "tag-resource", "untag-resource", "update-domain", "update-watchlist"},
		OperationSet: map[string]bool{"associate-fraudster": true, "create-domain": true, "create-watchlist": true, "delete-domain": true, "delete-fraudster": true, "delete-speaker": true, "delete-watchlist": true, "describe-domain": true, "describe-fraudster": true, "describe-fraudster-registration-job": true, "describe-speaker": true, "describe-speaker-enrollment-job": true, "describe-watchlist": true, "disassociate-fraudster": true, "evaluate-session": true, "list-domains": true, "list-fraudster-registration-jobs": true, "list-fraudsters": true, "list-speaker-enrollment-jobs": true, "list-speakers": true, "list-tags-for-resource": true, "list-watchlists": true, "opt-out-speaker": true, "start-fraudster-registration-job": true, "start-speaker-enrollment-job": true, "tag-resource": true, "untag-resource": true, "update-domain": true, "update-watchlist": true},
		OperationInputs: map[string][]string{
			"associate-fraudster":                 {"DomainId", "FraudsterId", "WatchlistId"},
			"create-domain":                       {"ClientToken", "Description", "Name", "ServerSideEncryptionConfiguration", "Tags"},
			"create-watchlist":                    {"ClientToken", "Description", "DomainId", "Name"},
			"delete-domain":                       {"DomainId"},
			"delete-fraudster":                    {"DomainId", "FraudsterId"},
			"delete-speaker":                      {"DomainId", "SpeakerId"},
			"delete-watchlist":                    {"DomainId", "WatchlistId"},
			"describe-domain":                     {"DomainId"},
			"describe-fraudster":                  {"DomainId", "FraudsterId"},
			"describe-fraudster-registration-job": {"DomainId", "JobId"},
			"describe-speaker":                    {"DomainId", "SpeakerId"},
			"describe-speaker-enrollment-job":     {"DomainId", "JobId"},
			"describe-watchlist":                  {"DomainId", "WatchlistId"},
			"disassociate-fraudster":              {"DomainId", "FraudsterId", "WatchlistId"},
			"evaluate-session":                    {"DomainId", "SessionNameOrId"},
			"list-domains":                        {"MaxResults", "NextToken"},
			"list-fraudster-registration-jobs":    {"DomainId", "JobStatus", "MaxResults", "NextToken"},
			"list-fraudsters":                     {"DomainId", "MaxResults", "NextToken", "WatchlistId"},
			"list-speaker-enrollment-jobs":        {"DomainId", "JobStatus", "MaxResults", "NextToken"},
			"list-speakers":                       {"DomainId", "MaxResults", "NextToken"},
			"list-tags-for-resource":              {"ResourceArn"},
			"list-watchlists":                     {"DomainId", "MaxResults", "NextToken"},
			"opt-out-speaker":                     {"DomainId", "SpeakerId"},
			"start-fraudster-registration-job":    {"ClientToken", "DataAccessRoleArn", "DomainId", "InputDataConfig", "JobName", "OutputDataConfig", "RegistrationConfig"},
			"start-speaker-enrollment-job":        {"ClientToken", "DataAccessRoleArn", "DomainId", "EnrollmentConfig", "InputDataConfig", "JobName", "OutputDataConfig"},
			"tag-resource":                        {"ResourceArn", "Tags"},
			"untag-resource":                      {"ResourceArn", "TagKeys"},
			"update-domain":                       {"Description", "DomainId", "Name", "ServerSideEncryptionConfiguration"},
			"update-watchlist":                    {"Description", "DomainId", "Name", "WatchlistId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-fraudster":                 {"DomainId": "*string", "FraudsterId": "*string", "WatchlistId": "*string"},
			"create-domain":                       {"ClientToken": "*string", "Description": "*string", "Name": "*string", "ServerSideEncryptionConfiguration": "*types.ServerSideEncryptionConfiguration", "Tags": "[]types.Tag"},
			"create-watchlist":                    {"ClientToken": "*string", "Description": "*string", "DomainId": "*string", "Name": "*string"},
			"delete-domain":                       {"DomainId": "*string"},
			"delete-fraudster":                    {"DomainId": "*string", "FraudsterId": "*string"},
			"delete-speaker":                      {"DomainId": "*string", "SpeakerId": "*string"},
			"delete-watchlist":                    {"DomainId": "*string", "WatchlistId": "*string"},
			"describe-domain":                     {"DomainId": "*string"},
			"describe-fraudster":                  {"DomainId": "*string", "FraudsterId": "*string"},
			"describe-fraudster-registration-job": {"DomainId": "*string", "JobId": "*string"},
			"describe-speaker":                    {"DomainId": "*string", "SpeakerId": "*string"},
			"describe-speaker-enrollment-job":     {"DomainId": "*string", "JobId": "*string"},
			"describe-watchlist":                  {"DomainId": "*string", "WatchlistId": "*string"},
			"disassociate-fraudster":              {"DomainId": "*string", "FraudsterId": "*string", "WatchlistId": "*string"},
			"evaluate-session":                    {"DomainId": "*string", "SessionNameOrId": "*string"},
			"list-domains":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-fraudster-registration-jobs":    {"DomainId": "*string", "JobStatus": "types.FraudsterRegistrationJobStatus", "MaxResults": "*int32", "NextToken": "*string"},
			"list-fraudsters":                     {"DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string", "WatchlistId": "*string"},
			"list-speaker-enrollment-jobs":        {"DomainId": "*string", "JobStatus": "types.SpeakerEnrollmentJobStatus", "MaxResults": "*int32", "NextToken": "*string"},
			"list-speakers":                       {"DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":              {"ResourceArn": "*string"},
			"list-watchlists":                     {"DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"opt-out-speaker":                     {"DomainId": "*string", "SpeakerId": "*string"},
			"start-fraudster-registration-job":    {"ClientToken": "*string", "DataAccessRoleArn": "*string", "DomainId": "*string", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "OutputDataConfig": "*types.OutputDataConfig", "RegistrationConfig": "*types.RegistrationConfig"},
			"start-speaker-enrollment-job":        {"ClientToken": "*string", "DataAccessRoleArn": "*string", "DomainId": "*string", "EnrollmentConfig": "*types.EnrollmentConfig", "InputDataConfig": "*types.InputDataConfig", "JobName": "*string", "OutputDataConfig": "*types.OutputDataConfig"},
			"tag-resource":                        {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                      {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-domain":                       {"Description": "*string", "DomainId": "*string", "Name": "*string", "ServerSideEncryptionConfiguration": "*types.ServerSideEncryptionConfiguration"},
			"update-watchlist":                    {"Description": "*string", "DomainId": "*string", "Name": "*string", "WatchlistId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-fraudster":                 {"DomainId", "FraudsterId", "WatchlistId"},
			"create-domain":                       {"Name", "ServerSideEncryptionConfiguration"},
			"create-watchlist":                    {"DomainId", "Name"},
			"delete-domain":                       {"DomainId"},
			"delete-fraudster":                    {"DomainId", "FraudsterId"},
			"delete-speaker":                      {"DomainId", "SpeakerId"},
			"delete-watchlist":                    {"DomainId", "WatchlistId"},
			"describe-domain":                     {"DomainId"},
			"describe-fraudster":                  {"DomainId", "FraudsterId"},
			"describe-fraudster-registration-job": {"DomainId", "JobId"},
			"describe-speaker":                    {"DomainId", "SpeakerId"},
			"describe-speaker-enrollment-job":     {"DomainId", "JobId"},
			"describe-watchlist":                  {"DomainId", "WatchlistId"},
			"disassociate-fraudster":              {"DomainId", "FraudsterId", "WatchlistId"},
			"evaluate-session":                    {"DomainId", "SessionNameOrId"},
			"list-domains":                        {},
			"list-fraudster-registration-jobs":    {"DomainId"},
			"list-fraudsters":                     {"DomainId"},
			"list-speaker-enrollment-jobs":        {"DomainId"},
			"list-speakers":                       {"DomainId"},
			"list-tags-for-resource":              {"ResourceArn"},
			"list-watchlists":                     {"DomainId"},
			"opt-out-speaker":                     {"DomainId", "SpeakerId"},
			"start-fraudster-registration-job":    {"DataAccessRoleArn", "DomainId", "InputDataConfig", "OutputDataConfig"},
			"start-speaker-enrollment-job":        {"DataAccessRoleArn", "DomainId", "InputDataConfig", "OutputDataConfig"},
			"tag-resource":                        {"ResourceArn", "Tags"},
			"untag-resource":                      {"ResourceArn", "TagKeys"},
			"update-domain":                       {"DomainId", "Name", "ServerSideEncryptionConfiguration"},
			"update-watchlist":                    {"DomainId", "WatchlistId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("voiceid", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
