package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/chimesdkvoice/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-phone-numbers-with-voice-connector", "associate-phone-numbers-with-voice-connector-group", "batch-delete-phone-number", "batch-update-phone-number", "create-phone-number-order", "create-proxy-session", "create-sip-media-application", "create-sip-media-application-call", "create-sip-rule", "create-voice-connector", "create-voice-connector-group", "create-voice-profile", "create-voice-profile-domain", "delete-phone-number", "delete-proxy-session", "delete-sip-media-application", "delete-sip-rule", "delete-voice-connector", "delete-voice-connector-emergency-calling-configuration", "delete-voice-connector-external-systems-configuration", "delete-voice-connector-group", "delete-voice-connector-origination", "delete-voice-connector-proxy", "delete-voice-connector-streaming-configuration", "delete-voice-connector-termination", "delete-voice-connector-termination-credentials", "delete-voice-profile", "delete-voice-profile-domain", "disassociate-phone-numbers-from-voice-connector", "disassociate-phone-numbers-from-voice-connector-group", "get-global-settings", "get-phone-number", "get-phone-number-order", "get-phone-number-settings", "get-proxy-session", "get-sip-media-application", "get-sip-media-application-alexa-skill-configuration", "get-sip-media-application-logging-configuration", "get-sip-rule", "get-speaker-search-task", "get-voice-connector", "get-voice-connector-emergency-calling-configuration", "get-voice-connector-external-systems-configuration", "get-voice-connector-group", "get-voice-connector-logging-configuration", "get-voice-connector-origination", "get-voice-connector-proxy", "get-voice-connector-streaming-configuration", "get-voice-connector-termination", "get-voice-connector-termination-health", "get-voice-profile", "get-voice-profile-domain", "get-voice-tone-analysis-task", "list-available-voice-connector-regions", "list-phone-number-orders", "list-phone-numbers", "list-proxy-sessions", "list-sip-media-applications", "list-sip-rules", "list-supported-phone-number-countries", "list-tags-for-resource", "list-voice-connector-groups", "list-voice-connector-termination-credentials", "list-voice-connectors", "list-voice-profile-domains", "list-voice-profiles", "put-sip-media-application-alexa-skill-configuration", "put-sip-media-application-logging-configuration", "put-voice-connector-emergency-calling-configuration", "put-voice-connector-external-systems-configuration", "put-voice-connector-logging-configuration", "put-voice-connector-origination", "put-voice-connector-proxy", "put-voice-connector-streaming-configuration", "put-voice-connector-termination", "put-voice-connector-termination-credentials", "restore-phone-number", "search-available-phone-numbers", "start-speaker-search-task", "start-voice-tone-analysis-task", "stop-speaker-search-task", "stop-voice-tone-analysis-task", "tag-resource", "untag-resource", "update-global-settings", "update-phone-number", "update-phone-number-settings", "update-proxy-session", "update-sip-media-application", "update-sip-media-application-call", "update-sip-rule", "update-voice-connector", "update-voice-connector-group", "update-voice-profile", "update-voice-profile-domain", "validate-e911-address"},
		OperationSet: map[string]bool{"associate-phone-numbers-with-voice-connector": true, "associate-phone-numbers-with-voice-connector-group": true, "batch-delete-phone-number": true, "batch-update-phone-number": true, "create-phone-number-order": true, "create-proxy-session": true, "create-sip-media-application": true, "create-sip-media-application-call": true, "create-sip-rule": true, "create-voice-connector": true, "create-voice-connector-group": true, "create-voice-profile": true, "create-voice-profile-domain": true, "delete-phone-number": true, "delete-proxy-session": true, "delete-sip-media-application": true, "delete-sip-rule": true, "delete-voice-connector": true, "delete-voice-connector-emergency-calling-configuration": true, "delete-voice-connector-external-systems-configuration": true, "delete-voice-connector-group": true, "delete-voice-connector-origination": true, "delete-voice-connector-proxy": true, "delete-voice-connector-streaming-configuration": true, "delete-voice-connector-termination": true, "delete-voice-connector-termination-credentials": true, "delete-voice-profile": true, "delete-voice-profile-domain": true, "disassociate-phone-numbers-from-voice-connector": true, "disassociate-phone-numbers-from-voice-connector-group": true, "get-global-settings": true, "get-phone-number": true, "get-phone-number-order": true, "get-phone-number-settings": true, "get-proxy-session": true, "get-sip-media-application": true, "get-sip-media-application-alexa-skill-configuration": true, "get-sip-media-application-logging-configuration": true, "get-sip-rule": true, "get-speaker-search-task": true, "get-voice-connector": true, "get-voice-connector-emergency-calling-configuration": true, "get-voice-connector-external-systems-configuration": true, "get-voice-connector-group": true, "get-voice-connector-logging-configuration": true, "get-voice-connector-origination": true, "get-voice-connector-proxy": true, "get-voice-connector-streaming-configuration": true, "get-voice-connector-termination": true, "get-voice-connector-termination-health": true, "get-voice-profile": true, "get-voice-profile-domain": true, "get-voice-tone-analysis-task": true, "list-available-voice-connector-regions": true, "list-phone-number-orders": true, "list-phone-numbers": true, "list-proxy-sessions": true, "list-sip-media-applications": true, "list-sip-rules": true, "list-supported-phone-number-countries": true, "list-tags-for-resource": true, "list-voice-connector-groups": true, "list-voice-connector-termination-credentials": true, "list-voice-connectors": true, "list-voice-profile-domains": true, "list-voice-profiles": true, "put-sip-media-application-alexa-skill-configuration": true, "put-sip-media-application-logging-configuration": true, "put-voice-connector-emergency-calling-configuration": true, "put-voice-connector-external-systems-configuration": true, "put-voice-connector-logging-configuration": true, "put-voice-connector-origination": true, "put-voice-connector-proxy": true, "put-voice-connector-streaming-configuration": true, "put-voice-connector-termination": true, "put-voice-connector-termination-credentials": true, "restore-phone-number": true, "search-available-phone-numbers": true, "start-speaker-search-task": true, "start-voice-tone-analysis-task": true, "stop-speaker-search-task": true, "stop-voice-tone-analysis-task": true, "tag-resource": true, "untag-resource": true, "update-global-settings": true, "update-phone-number": true, "update-phone-number-settings": true, "update-proxy-session": true, "update-sip-media-application": true, "update-sip-media-application-call": true, "update-sip-rule": true, "update-voice-connector": true, "update-voice-connector-group": true, "update-voice-profile": true, "update-voice-profile-domain": true, "validate-e911-address": true},
		OperationInputs: map[string][]string{
			"associate-phone-numbers-with-voice-connector":           {"E164PhoneNumbers", "ForceAssociate", "VoiceConnectorId"},
			"associate-phone-numbers-with-voice-connector-group":     {"E164PhoneNumbers", "ForceAssociate", "VoiceConnectorGroupId"},
			"batch-delete-phone-number":                              {"PhoneNumberIds"},
			"batch-update-phone-number":                              {"UpdatePhoneNumberRequestItems"},
			"create-phone-number-order":                              {"E164PhoneNumbers", "Name", "ProductType"},
			"create-proxy-session":                                   {"Capabilities", "ExpiryMinutes", "GeoMatchLevel", "GeoMatchParams", "Name", "NumberSelectionBehavior", "ParticipantPhoneNumbers", "VoiceConnectorId"},
			"create-sip-media-application":                           {"AwsRegion", "Endpoints", "Name", "Tags"},
			"create-sip-media-application-call":                      {"ArgumentsMap", "FromPhoneNumber", "SipHeaders", "SipMediaApplicationId", "ToPhoneNumber"},
			"create-sip-rule":                                        {"Disabled", "Name", "TargetApplications", "TriggerType", "TriggerValue"},
			"create-voice-connector":                                 {"AwsRegion", "IntegrationType", "Name", "NetworkType", "RequireEncryption", "Tags"},
			"create-voice-connector-group":                           {"Name", "VoiceConnectorItems"},
			"create-voice-profile":                                   {"SpeakerSearchTaskId"},
			"create-voice-profile-domain":                            {"ClientRequestToken", "Description", "Name", "ServerSideEncryptionConfiguration", "Tags"},
			"delete-phone-number":                                    {"PhoneNumberId"},
			"delete-proxy-session":                                   {"ProxySessionId", "VoiceConnectorId"},
			"delete-sip-media-application":                           {"SipMediaApplicationId"},
			"delete-sip-rule":                                        {"SipRuleId"},
			"delete-voice-connector":                                 {"VoiceConnectorId"},
			"delete-voice-connector-emergency-calling-configuration": {"VoiceConnectorId"},
			"delete-voice-connector-external-systems-configuration":  {"VoiceConnectorId"},
			"delete-voice-connector-group":                           {"VoiceConnectorGroupId"},
			"delete-voice-connector-origination":                     {"VoiceConnectorId"},
			"delete-voice-connector-proxy":                           {"VoiceConnectorId"},
			"delete-voice-connector-streaming-configuration":         {"VoiceConnectorId"},
			"delete-voice-connector-termination":                     {"VoiceConnectorId"},
			"delete-voice-connector-termination-credentials":         {"Usernames", "VoiceConnectorId"},
			"delete-voice-profile":                                   {"VoiceProfileId"},
			"delete-voice-profile-domain":                            {"VoiceProfileDomainId"},
			"disassociate-phone-numbers-from-voice-connector":        {"E164PhoneNumbers", "VoiceConnectorId"},
			"disassociate-phone-numbers-from-voice-connector-group":  {"E164PhoneNumbers", "VoiceConnectorGroupId"},
			"get-global-settings":                                    {},
			"get-phone-number":                                       {"PhoneNumberId"},
			"get-phone-number-order":                                 {"PhoneNumberOrderId"},
			"get-phone-number-settings":                              {},
			"get-proxy-session":                                      {"ProxySessionId", "VoiceConnectorId"},
			"get-sip-media-application":                              {"SipMediaApplicationId"},
			"get-sip-media-application-alexa-skill-configuration":    {"SipMediaApplicationId"},
			"get-sip-media-application-logging-configuration":        {"SipMediaApplicationId"},
			"get-sip-rule":                                           {"SipRuleId"},
			"get-speaker-search-task":                                {"SpeakerSearchTaskId", "VoiceConnectorId"},
			"get-voice-connector":                                    {"VoiceConnectorId"},
			"get-voice-connector-emergency-calling-configuration":    {"VoiceConnectorId"},
			"get-voice-connector-external-systems-configuration":     {"VoiceConnectorId"},
			"get-voice-connector-group":                              {"VoiceConnectorGroupId"},
			"get-voice-connector-logging-configuration":              {"VoiceConnectorId"},
			"get-voice-connector-origination":                        {"VoiceConnectorId"},
			"get-voice-connector-proxy":                              {"VoiceConnectorId"},
			"get-voice-connector-streaming-configuration":            {"VoiceConnectorId"},
			"get-voice-connector-termination":                        {"VoiceConnectorId"},
			"get-voice-connector-termination-health":                 {"VoiceConnectorId"},
			"get-voice-profile":                                      {"VoiceProfileId"},
			"get-voice-profile-domain":                               {"VoiceProfileDomainId"},
			"get-voice-tone-analysis-task":                           {"IsCaller", "VoiceConnectorId", "VoiceToneAnalysisTaskId"},
			"list-available-voice-connector-regions":                 {},
			"list-phone-number-orders":                               {"MaxResults", "NextToken"},
			"list-phone-numbers":                                     {"FilterName", "FilterValue", "MaxResults", "NextToken", "ProductType", "Status"},
			"list-proxy-sessions":                                    {"MaxResults", "NextToken", "Status", "VoiceConnectorId"},
			"list-sip-media-applications":                            {"MaxResults", "NextToken"},
			"list-sip-rules":                                         {"MaxResults", "NextToken", "SipMediaApplicationId"},
			"list-supported-phone-number-countries":                  {"ProductType"},
			"list-tags-for-resource":                                 {"ResourceARN"},
			"list-voice-connector-groups":                            {"MaxResults", "NextToken"},
			"list-voice-connector-termination-credentials":           {"VoiceConnectorId"},
			"list-voice-connectors":                                  {"MaxResults", "NextToken"},
			"list-voice-profile-domains":                             {"MaxResults", "NextToken"},
			"list-voice-profiles":                                    {"MaxResults", "NextToken", "VoiceProfileDomainId"},
			"put-sip-media-application-alexa-skill-configuration":    {"SipMediaApplicationAlexaSkillConfiguration", "SipMediaApplicationId"},
			"put-sip-media-application-logging-configuration":        {"SipMediaApplicationId", "SipMediaApplicationLoggingConfiguration"},
			"put-voice-connector-emergency-calling-configuration":    {"EmergencyCallingConfiguration", "VoiceConnectorId"},
			"put-voice-connector-external-systems-configuration":     {"ContactCenterSystemTypes", "SessionBorderControllerTypes", "VoiceConnectorId"},
			"put-voice-connector-logging-configuration":              {"LoggingConfiguration", "VoiceConnectorId"},
			"put-voice-connector-origination":                        {"Origination", "VoiceConnectorId"},
			"put-voice-connector-proxy":                              {"DefaultSessionExpiryMinutes", "Disabled", "FallBackPhoneNumber", "PhoneNumberPoolCountries", "VoiceConnectorId"},
			"put-voice-connector-streaming-configuration":            {"StreamingConfiguration", "VoiceConnectorId"},
			"put-voice-connector-termination":                        {"Termination", "VoiceConnectorId"},
			"put-voice-connector-termination-credentials":            {"Credentials", "VoiceConnectorId"},
			"restore-phone-number":                                   {"PhoneNumberId"},
			"search-available-phone-numbers":                         {"AreaCode", "City", "Country", "MaxResults", "NextToken", "PhoneNumberType", "State", "TollFreePrefix"},
			"start-speaker-search-task":                              {"CallLeg", "ClientRequestToken", "TransactionId", "VoiceConnectorId", "VoiceProfileDomainId"},
			"start-voice-tone-analysis-task":                         {"ClientRequestToken", "LanguageCode", "TransactionId", "VoiceConnectorId"},
			"stop-speaker-search-task":                               {"SpeakerSearchTaskId", "VoiceConnectorId"},
			"stop-voice-tone-analysis-task":                          {"VoiceConnectorId", "VoiceToneAnalysisTaskId"},
			"tag-resource":                                           {"ResourceARN", "Tags"},
			"untag-resource":                                         {"ResourceARN", "TagKeys"},
			"update-global-settings":                                 {"VoiceConnector"},
			"update-phone-number":                                    {"CallingName", "Name", "PhoneNumberId", "ProductType"},
			"update-phone-number-settings":                           {"CallingName"},
			"update-proxy-session":                                   {"Capabilities", "ExpiryMinutes", "ProxySessionId", "VoiceConnectorId"},
			"update-sip-media-application":                           {"Endpoints", "Name", "SipMediaApplicationId"},
			"update-sip-media-application-call":                      {"Arguments", "SipMediaApplicationId", "TransactionId"},
			"update-sip-rule":                                        {"Disabled", "Name", "SipRuleId", "TargetApplications"},
			"update-voice-connector":                                 {"Name", "RequireEncryption", "VoiceConnectorId"},
			"update-voice-connector-group":                           {"Name", "VoiceConnectorGroupId", "VoiceConnectorItems"},
			"update-voice-profile":                                   {"SpeakerSearchTaskId", "VoiceProfileId"},
			"update-voice-profile-domain":                            {"Description", "Name", "VoiceProfileDomainId"},
			"validate-e911-address":                                  {"AwsAccountId", "City", "Country", "PostalCode", "State", "StreetInfo", "StreetNumber"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-phone-numbers-with-voice-connector":           {"E164PhoneNumbers": "[]string", "ForceAssociate": "*bool", "VoiceConnectorId": "*string"},
			"associate-phone-numbers-with-voice-connector-group":     {"E164PhoneNumbers": "[]string", "ForceAssociate": "*bool", "VoiceConnectorGroupId": "*string"},
			"batch-delete-phone-number":                              {"PhoneNumberIds": "[]string"},
			"batch-update-phone-number":                              {"UpdatePhoneNumberRequestItems": "[]types.UpdatePhoneNumberRequestItem"},
			"create-phone-number-order":                              {"E164PhoneNumbers": "[]string", "Name": "*string", "ProductType": "types.PhoneNumberProductType"},
			"create-proxy-session":                                   {"Capabilities": "[]types.Capability", "ExpiryMinutes": "*int32", "GeoMatchLevel": "types.GeoMatchLevel", "GeoMatchParams": "*types.GeoMatchParams", "Name": "*string", "NumberSelectionBehavior": "types.NumberSelectionBehavior", "ParticipantPhoneNumbers": "[]string", "VoiceConnectorId": "*string"},
			"create-sip-media-application":                           {"AwsRegion": "*string", "Endpoints": "[]types.SipMediaApplicationEndpoint", "Name": "*string", "Tags": "[]types.Tag"},
			"create-sip-media-application-call":                      {"ArgumentsMap": "map[string]string", "FromPhoneNumber": "*string", "SipHeaders": "map[string]string", "SipMediaApplicationId": "*string", "ToPhoneNumber": "*string"},
			"create-sip-rule":                                        {"Disabled": "*bool", "Name": "*string", "TargetApplications": "[]types.SipRuleTargetApplication", "TriggerType": "types.SipRuleTriggerType", "TriggerValue": "*string"},
			"create-voice-connector":                                 {"AwsRegion": "types.VoiceConnectorAwsRegion", "IntegrationType": "types.VoiceConnectorIntegrationType", "Name": "*string", "NetworkType": "types.NetworkType", "RequireEncryption": "*bool", "Tags": "[]types.Tag"},
			"create-voice-connector-group":                           {"Name": "*string", "VoiceConnectorItems": "[]types.VoiceConnectorItem"},
			"create-voice-profile":                                   {"SpeakerSearchTaskId": "*string"},
			"create-voice-profile-domain":                            {"ClientRequestToken": "*string", "Description": "*string", "Name": "*string", "ServerSideEncryptionConfiguration": "*types.ServerSideEncryptionConfiguration", "Tags": "[]types.Tag"},
			"delete-phone-number":                                    {"PhoneNumberId": "*string"},
			"delete-proxy-session":                                   {"ProxySessionId": "*string", "VoiceConnectorId": "*string"},
			"delete-sip-media-application":                           {"SipMediaApplicationId": "*string"},
			"delete-sip-rule":                                        {"SipRuleId": "*string"},
			"delete-voice-connector":                                 {"VoiceConnectorId": "*string"},
			"delete-voice-connector-emergency-calling-configuration": {"VoiceConnectorId": "*string"},
			"delete-voice-connector-external-systems-configuration":  {"VoiceConnectorId": "*string"},
			"delete-voice-connector-group":                           {"VoiceConnectorGroupId": "*string"},
			"delete-voice-connector-origination":                     {"VoiceConnectorId": "*string"},
			"delete-voice-connector-proxy":                           {"VoiceConnectorId": "*string"},
			"delete-voice-connector-streaming-configuration":         {"VoiceConnectorId": "*string"},
			"delete-voice-connector-termination":                     {"VoiceConnectorId": "*string"},
			"delete-voice-connector-termination-credentials":         {"Usernames": "[]string", "VoiceConnectorId": "*string"},
			"delete-voice-profile":                                   {"VoiceProfileId": "*string"},
			"delete-voice-profile-domain":                            {"VoiceProfileDomainId": "*string"},
			"disassociate-phone-numbers-from-voice-connector":        {"E164PhoneNumbers": "[]string", "VoiceConnectorId": "*string"},
			"disassociate-phone-numbers-from-voice-connector-group":  {"E164PhoneNumbers": "[]string", "VoiceConnectorGroupId": "*string"},
			"get-global-settings":                                    {},
			"get-phone-number":                                       {"PhoneNumberId": "*string"},
			"get-phone-number-order":                                 {"PhoneNumberOrderId": "*string"},
			"get-phone-number-settings":                              {},
			"get-proxy-session":                                      {"ProxySessionId": "*string", "VoiceConnectorId": "*string"},
			"get-sip-media-application":                              {"SipMediaApplicationId": "*string"},
			"get-sip-media-application-alexa-skill-configuration":    {"SipMediaApplicationId": "*string"},
			"get-sip-media-application-logging-configuration":        {"SipMediaApplicationId": "*string"},
			"get-sip-rule":                                           {"SipRuleId": "*string"},
			"get-speaker-search-task":                                {"SpeakerSearchTaskId": "*string", "VoiceConnectorId": "*string"},
			"get-voice-connector":                                    {"VoiceConnectorId": "*string"},
			"get-voice-connector-emergency-calling-configuration":    {"VoiceConnectorId": "*string"},
			"get-voice-connector-external-systems-configuration":     {"VoiceConnectorId": "*string"},
			"get-voice-connector-group":                              {"VoiceConnectorGroupId": "*string"},
			"get-voice-connector-logging-configuration":              {"VoiceConnectorId": "*string"},
			"get-voice-connector-origination":                        {"VoiceConnectorId": "*string"},
			"get-voice-connector-proxy":                              {"VoiceConnectorId": "*string"},
			"get-voice-connector-streaming-configuration":            {"VoiceConnectorId": "*string"},
			"get-voice-connector-termination":                        {"VoiceConnectorId": "*string"},
			"get-voice-connector-termination-health":                 {"VoiceConnectorId": "*string"},
			"get-voice-profile":                                      {"VoiceProfileId": "*string"},
			"get-voice-profile-domain":                               {"VoiceProfileDomainId": "*string"},
			"get-voice-tone-analysis-task":                           {"IsCaller": "*bool", "VoiceConnectorId": "*string", "VoiceToneAnalysisTaskId": "*string"},
			"list-available-voice-connector-regions":                 {},
			"list-phone-number-orders":                               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-phone-numbers":                                     {"FilterName": "types.PhoneNumberAssociationName", "FilterValue": "*string", "MaxResults": "*int32", "NextToken": "*string", "ProductType": "types.PhoneNumberProductType", "Status": "*string"},
			"list-proxy-sessions":                                    {"MaxResults": "*int32", "NextToken": "*string", "Status": "types.ProxySessionStatus", "VoiceConnectorId": "*string"},
			"list-sip-media-applications":                            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-sip-rules":                                         {"MaxResults": "*int32", "NextToken": "*string", "SipMediaApplicationId": "*string"},
			"list-supported-phone-number-countries":                  {"ProductType": "types.PhoneNumberProductType"},
			"list-tags-for-resource":                                 {"ResourceARN": "*string"},
			"list-voice-connector-groups":                            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-voice-connector-termination-credentials":           {"VoiceConnectorId": "*string"},
			"list-voice-connectors":                                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-voice-profile-domains":                             {"MaxResults": "*int32", "NextToken": "*string"},
			"list-voice-profiles":                                    {"MaxResults": "*int32", "NextToken": "*string", "VoiceProfileDomainId": "*string"},
			"put-sip-media-application-alexa-skill-configuration":    {"SipMediaApplicationAlexaSkillConfiguration": "*types.SipMediaApplicationAlexaSkillConfiguration", "SipMediaApplicationId": "*string"},
			"put-sip-media-application-logging-configuration":        {"SipMediaApplicationId": "*string", "SipMediaApplicationLoggingConfiguration": "*types.SipMediaApplicationLoggingConfiguration"},
			"put-voice-connector-emergency-calling-configuration":    {"EmergencyCallingConfiguration": "*types.EmergencyCallingConfiguration", "VoiceConnectorId": "*string"},
			"put-voice-connector-external-systems-configuration":     {"ContactCenterSystemTypes": "[]types.ContactCenterSystemType", "SessionBorderControllerTypes": "[]types.SessionBorderControllerType", "VoiceConnectorId": "*string"},
			"put-voice-connector-logging-configuration":              {"LoggingConfiguration": "*types.LoggingConfiguration", "VoiceConnectorId": "*string"},
			"put-voice-connector-origination":                        {"Origination": "*types.Origination", "VoiceConnectorId": "*string"},
			"put-voice-connector-proxy":                              {"DefaultSessionExpiryMinutes": "*int32", "Disabled": "*bool", "FallBackPhoneNumber": "*string", "PhoneNumberPoolCountries": "[]string", "VoiceConnectorId": "*string"},
			"put-voice-connector-streaming-configuration":            {"StreamingConfiguration": "*types.StreamingConfiguration", "VoiceConnectorId": "*string"},
			"put-voice-connector-termination":                        {"Termination": "*types.Termination", "VoiceConnectorId": "*string"},
			"put-voice-connector-termination-credentials":            {"Credentials": "[]types.Credential", "VoiceConnectorId": "*string"},
			"restore-phone-number":                                   {"PhoneNumberId": "*string"},
			"search-available-phone-numbers":                         {"AreaCode": "*string", "City": "*string", "Country": "*string", "MaxResults": "*int32", "NextToken": "*string", "PhoneNumberType": "types.PhoneNumberType", "State": "*string", "TollFreePrefix": "*string"},
			"start-speaker-search-task":                              {"CallLeg": "types.CallLegType", "ClientRequestToken": "*string", "TransactionId": "*string", "VoiceConnectorId": "*string", "VoiceProfileDomainId": "*string"},
			"start-voice-tone-analysis-task":                         {"ClientRequestToken": "*string", "LanguageCode": "types.LanguageCode", "TransactionId": "*string", "VoiceConnectorId": "*string"},
			"stop-speaker-search-task":                               {"SpeakerSearchTaskId": "*string", "VoiceConnectorId": "*string"},
			"stop-voice-tone-analysis-task":                          {"VoiceConnectorId": "*string", "VoiceToneAnalysisTaskId": "*string"},
			"tag-resource":                                           {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                                         {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-global-settings":                                 {"VoiceConnector": "*types.VoiceConnectorSettings"},
			"update-phone-number":                                    {"CallingName": "*string", "Name": "*string", "PhoneNumberId": "*string", "ProductType": "types.PhoneNumberProductType"},
			"update-phone-number-settings":                           {"CallingName": "*string"},
			"update-proxy-session":                                   {"Capabilities": "[]types.Capability", "ExpiryMinutes": "*int32", "ProxySessionId": "*string", "VoiceConnectorId": "*string"},
			"update-sip-media-application":                           {"Endpoints": "[]types.SipMediaApplicationEndpoint", "Name": "*string", "SipMediaApplicationId": "*string"},
			"update-sip-media-application-call":                      {"Arguments": "map[string]string", "SipMediaApplicationId": "*string", "TransactionId": "*string"},
			"update-sip-rule":                                        {"Disabled": "*bool", "Name": "*string", "SipRuleId": "*string", "TargetApplications": "[]types.SipRuleTargetApplication"},
			"update-voice-connector":                                 {"Name": "*string", "RequireEncryption": "*bool", "VoiceConnectorId": "*string"},
			"update-voice-connector-group":                           {"Name": "*string", "VoiceConnectorGroupId": "*string", "VoiceConnectorItems": "[]types.VoiceConnectorItem"},
			"update-voice-profile":                                   {"SpeakerSearchTaskId": "*string", "VoiceProfileId": "*string"},
			"update-voice-profile-domain":                            {"Description": "*string", "Name": "*string", "VoiceProfileDomainId": "*string"},
			"validate-e911-address":                                  {"AwsAccountId": "*string", "City": "*string", "Country": "*string", "PostalCode": "*string", "State": "*string", "StreetInfo": "*string", "StreetNumber": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-phone-numbers-with-voice-connector":           {"E164PhoneNumbers", "VoiceConnectorId"},
			"associate-phone-numbers-with-voice-connector-group":     {"E164PhoneNumbers", "VoiceConnectorGroupId"},
			"batch-delete-phone-number":                              {"PhoneNumberIds"},
			"batch-update-phone-number":                              {"UpdatePhoneNumberRequestItems"},
			"create-phone-number-order":                              {"E164PhoneNumbers", "ProductType"},
			"create-proxy-session":                                   {"Capabilities", "ParticipantPhoneNumbers", "VoiceConnectorId"},
			"create-sip-media-application":                           {"AwsRegion", "Endpoints", "Name"},
			"create-sip-media-application-call":                      {"FromPhoneNumber", "SipMediaApplicationId", "ToPhoneNumber"},
			"create-sip-rule":                                        {"Name", "TriggerType", "TriggerValue"},
			"create-voice-connector":                                 {"Name", "RequireEncryption"},
			"create-voice-connector-group":                           {"Name"},
			"create-voice-profile":                                   {"SpeakerSearchTaskId"},
			"create-voice-profile-domain":                            {"Name", "ServerSideEncryptionConfiguration"},
			"delete-phone-number":                                    {"PhoneNumberId"},
			"delete-proxy-session":                                   {"ProxySessionId", "VoiceConnectorId"},
			"delete-sip-media-application":                           {"SipMediaApplicationId"},
			"delete-sip-rule":                                        {"SipRuleId"},
			"delete-voice-connector":                                 {"VoiceConnectorId"},
			"delete-voice-connector-emergency-calling-configuration": {"VoiceConnectorId"},
			"delete-voice-connector-external-systems-configuration":  {"VoiceConnectorId"},
			"delete-voice-connector-group":                           {"VoiceConnectorGroupId"},
			"delete-voice-connector-origination":                     {"VoiceConnectorId"},
			"delete-voice-connector-proxy":                           {"VoiceConnectorId"},
			"delete-voice-connector-streaming-configuration":         {"VoiceConnectorId"},
			"delete-voice-connector-termination":                     {"VoiceConnectorId"},
			"delete-voice-connector-termination-credentials":         {"Usernames", "VoiceConnectorId"},
			"delete-voice-profile":                                   {"VoiceProfileId"},
			"delete-voice-profile-domain":                            {"VoiceProfileDomainId"},
			"disassociate-phone-numbers-from-voice-connector":        {"E164PhoneNumbers", "VoiceConnectorId"},
			"disassociate-phone-numbers-from-voice-connector-group":  {"E164PhoneNumbers", "VoiceConnectorGroupId"},
			"get-global-settings":                                    {},
			"get-phone-number":                                       {"PhoneNumberId"},
			"get-phone-number-order":                                 {"PhoneNumberOrderId"},
			"get-phone-number-settings":                              {},
			"get-proxy-session":                                      {"ProxySessionId", "VoiceConnectorId"},
			"get-sip-media-application":                              {"SipMediaApplicationId"},
			"get-sip-media-application-alexa-skill-configuration":    {"SipMediaApplicationId"},
			"get-sip-media-application-logging-configuration":        {"SipMediaApplicationId"},
			"get-sip-rule":                                           {"SipRuleId"},
			"get-speaker-search-task":                                {"SpeakerSearchTaskId", "VoiceConnectorId"},
			"get-voice-connector":                                    {"VoiceConnectorId"},
			"get-voice-connector-emergency-calling-configuration":    {"VoiceConnectorId"},
			"get-voice-connector-external-systems-configuration":     {"VoiceConnectorId"},
			"get-voice-connector-group":                              {"VoiceConnectorGroupId"},
			"get-voice-connector-logging-configuration":              {"VoiceConnectorId"},
			"get-voice-connector-origination":                        {"VoiceConnectorId"},
			"get-voice-connector-proxy":                              {"VoiceConnectorId"},
			"get-voice-connector-streaming-configuration":            {"VoiceConnectorId"},
			"get-voice-connector-termination":                        {"VoiceConnectorId"},
			"get-voice-connector-termination-health":                 {"VoiceConnectorId"},
			"get-voice-profile":                                      {"VoiceProfileId"},
			"get-voice-profile-domain":                               {"VoiceProfileDomainId"},
			"get-voice-tone-analysis-task":                           {"IsCaller", "VoiceConnectorId", "VoiceToneAnalysisTaskId"},
			"list-available-voice-connector-regions":                 {},
			"list-phone-number-orders":                               {},
			"list-phone-numbers":                                     {},
			"list-proxy-sessions":                                    {"VoiceConnectorId"},
			"list-sip-media-applications":                            {},
			"list-sip-rules":                                         {},
			"list-supported-phone-number-countries":                  {"ProductType"},
			"list-tags-for-resource":                                 {"ResourceARN"},
			"list-voice-connector-groups":                            {},
			"list-voice-connector-termination-credentials":           {"VoiceConnectorId"},
			"list-voice-connectors":                                  {},
			"list-voice-profile-domains":                             {},
			"list-voice-profiles":                                    {"VoiceProfileDomainId"},
			"put-sip-media-application-alexa-skill-configuration":    {"SipMediaApplicationId"},
			"put-sip-media-application-logging-configuration":        {"SipMediaApplicationId"},
			"put-voice-connector-emergency-calling-configuration":    {"EmergencyCallingConfiguration", "VoiceConnectorId"},
			"put-voice-connector-external-systems-configuration":     {"VoiceConnectorId"},
			"put-voice-connector-logging-configuration":              {"LoggingConfiguration", "VoiceConnectorId"},
			"put-voice-connector-origination":                        {"Origination", "VoiceConnectorId"},
			"put-voice-connector-proxy":                              {"DefaultSessionExpiryMinutes", "PhoneNumberPoolCountries", "VoiceConnectorId"},
			"put-voice-connector-streaming-configuration":            {"StreamingConfiguration", "VoiceConnectorId"},
			"put-voice-connector-termination":                        {"Termination", "VoiceConnectorId"},
			"put-voice-connector-termination-credentials":            {"VoiceConnectorId"},
			"restore-phone-number":                                   {"PhoneNumberId"},
			"search-available-phone-numbers":                         {},
			"start-speaker-search-task":                              {"TransactionId", "VoiceConnectorId", "VoiceProfileDomainId"},
			"start-voice-tone-analysis-task":                         {"LanguageCode", "TransactionId", "VoiceConnectorId"},
			"stop-speaker-search-task":                               {"SpeakerSearchTaskId", "VoiceConnectorId"},
			"stop-voice-tone-analysis-task":                          {"VoiceConnectorId", "VoiceToneAnalysisTaskId"},
			"tag-resource":                                           {"ResourceARN", "Tags"},
			"untag-resource":                                         {"ResourceARN", "TagKeys"},
			"update-global-settings":                                 {},
			"update-phone-number":                                    {"PhoneNumberId"},
			"update-phone-number-settings":                           {"CallingName"},
			"update-proxy-session":                                   {"Capabilities", "ProxySessionId", "VoiceConnectorId"},
			"update-sip-media-application":                           {"SipMediaApplicationId"},
			"update-sip-media-application-call":                      {"Arguments", "SipMediaApplicationId", "TransactionId"},
			"update-sip-rule":                                        {"Name", "SipRuleId"},
			"update-voice-connector":                                 {"Name", "RequireEncryption", "VoiceConnectorId"},
			"update-voice-connector-group":                           {"Name", "VoiceConnectorGroupId", "VoiceConnectorItems"},
			"update-voice-profile":                                   {"SpeakerSearchTaskId", "VoiceProfileId"},
			"update-voice-profile-domain":                            {"VoiceProfileDomainId"},
			"validate-e911-address":                                  {"AwsAccountId", "City", "Country", "PostalCode", "State", "StreetInfo", "StreetNumber"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("chimesdkvoice", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
