package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/batch/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"cancel-job", "create-compute-environment", "create-consumable-resource", "create-job-queue", "create-scheduling-policy", "create-service-environment", "delete-compute-environment", "delete-consumable-resource", "delete-job-queue", "delete-scheduling-policy", "delete-service-environment", "deregister-job-definition", "describe-compute-environments", "describe-consumable-resource", "describe-job-definitions", "describe-job-queues", "describe-jobs", "describe-scheduling-policies", "describe-service-environments", "describe-service-job", "get-job-queue-snapshot", "list-consumable-resources", "list-jobs", "list-jobs-by-consumable-resource", "list-scheduling-policies", "list-service-jobs", "list-tags-for-resource", "register-job-definition", "submit-job", "submit-service-job", "tag-resource", "terminate-job", "terminate-service-job", "untag-resource", "update-compute-environment", "update-consumable-resource", "update-job-queue", "update-scheduling-policy", "update-service-environment"},
		OperationSet: map[string]bool{"cancel-job": true, "create-compute-environment": true, "create-consumable-resource": true, "create-job-queue": true, "create-scheduling-policy": true, "create-service-environment": true, "delete-compute-environment": true, "delete-consumable-resource": true, "delete-job-queue": true, "delete-scheduling-policy": true, "delete-service-environment": true, "deregister-job-definition": true, "describe-compute-environments": true, "describe-consumable-resource": true, "describe-job-definitions": true, "describe-job-queues": true, "describe-jobs": true, "describe-scheduling-policies": true, "describe-service-environments": true, "describe-service-job": true, "get-job-queue-snapshot": true, "list-consumable-resources": true, "list-jobs": true, "list-jobs-by-consumable-resource": true, "list-scheduling-policies": true, "list-service-jobs": true, "list-tags-for-resource": true, "register-job-definition": true, "submit-job": true, "submit-service-job": true, "tag-resource": true, "terminate-job": true, "terminate-service-job": true, "untag-resource": true, "update-compute-environment": true, "update-consumable-resource": true, "update-job-queue": true, "update-scheduling-policy": true, "update-service-environment": true},
		OperationInputs: map[string][]string{
			"cancel-job":                       {"JobId", "Reason"},
			"create-compute-environment":       {"ComputeEnvironmentName", "ComputeResources", "Context", "EksConfiguration", "ServiceRole", "State", "Tags", "Type", "UnmanagedvCpus"},
			"create-consumable-resource":       {"ConsumableResourceName", "ResourceType", "Tags", "TotalQuantity"},
			"create-job-queue":                 {"ComputeEnvironmentOrder", "JobQueueName", "JobQueueType", "JobStateTimeLimitActions", "Priority", "SchedulingPolicyArn", "ServiceEnvironmentOrder", "State", "Tags"},
			"create-scheduling-policy":         {"FairsharePolicy", "Name", "Tags"},
			"create-service-environment":       {"CapacityLimits", "ServiceEnvironmentName", "ServiceEnvironmentType", "State", "Tags"},
			"delete-compute-environment":       {"ComputeEnvironment"},
			"delete-consumable-resource":       {"ConsumableResource"},
			"delete-job-queue":                 {"JobQueue"},
			"delete-scheduling-policy":         {"Arn"},
			"delete-service-environment":       {"ServiceEnvironment"},
			"deregister-job-definition":        {"JobDefinition"},
			"describe-compute-environments":    {"ComputeEnvironments", "MaxResults", "NextToken"},
			"describe-consumable-resource":     {"ConsumableResource"},
			"describe-job-definitions":         {"JobDefinitionName", "JobDefinitions", "MaxResults", "NextToken", "Status"},
			"describe-job-queues":              {"JobQueues", "MaxResults", "NextToken"},
			"describe-jobs":                    {"Jobs"},
			"describe-scheduling-policies":     {"Arns"},
			"describe-service-environments":    {"MaxResults", "NextToken", "ServiceEnvironments"},
			"describe-service-job":             {"JobId"},
			"get-job-queue-snapshot":           {"JobQueue"},
			"list-consumable-resources":        {"Filters", "MaxResults", "NextToken"},
			"list-jobs":                        {"ArrayJobId", "Filters", "JobQueue", "JobStatus", "MaxResults", "MultiNodeJobId", "NextToken"},
			"list-jobs-by-consumable-resource": {"ConsumableResource", "Filters", "MaxResults", "NextToken"},
			"list-scheduling-policies":         {"MaxResults", "NextToken"},
			"list-service-jobs":                {"Filters", "JobQueue", "JobStatus", "MaxResults", "NextToken"},
			"list-tags-for-resource":           {"ResourceArn"},
			"register-job-definition":          {"ConsumableResourceProperties", "ContainerProperties", "EcsProperties", "EksProperties", "JobDefinitionName", "NodeProperties", "Parameters", "PlatformCapabilities", "PropagateTags", "RetryStrategy", "SchedulingPriority", "Tags", "Timeout", "Type"},
			"submit-job":                       {"ArrayProperties", "ConsumableResourcePropertiesOverride", "ContainerOverrides", "DependsOn", "EcsPropertiesOverride", "EksPropertiesOverride", "JobDefinition", "JobName", "JobQueue", "NodeOverrides", "Parameters", "PropagateTags", "RetryStrategy", "SchedulingPriorityOverride", "ShareIdentifier", "Tags", "Timeout"},
			"submit-service-job":               {"ClientToken", "JobName", "JobQueue", "RetryStrategy", "SchedulingPriority", "ServiceJobType", "ServiceRequestPayload", "ShareIdentifier", "Tags", "TimeoutConfig"},
			"tag-resource":                     {"ResourceArn", "Tags"},
			"terminate-job":                    {"JobId", "Reason"},
			"terminate-service-job":            {"JobId", "Reason"},
			"untag-resource":                   {"ResourceArn", "TagKeys"},
			"update-compute-environment":       {"ComputeEnvironment", "ComputeResources", "Context", "ServiceRole", "State", "UnmanagedvCpus", "UpdatePolicy"},
			"update-consumable-resource":       {"ClientToken", "ConsumableResource", "Operation", "Quantity"},
			"update-job-queue":                 {"ComputeEnvironmentOrder", "JobQueue", "JobStateTimeLimitActions", "Priority", "SchedulingPolicyArn", "ServiceEnvironmentOrder", "State"},
			"update-scheduling-policy":         {"Arn", "FairsharePolicy"},
			"update-service-environment":       {"CapacityLimits", "ServiceEnvironment", "State"},
		},
		OperationInputTypes: map[string]map[string]string{
			"cancel-job":                       {"JobId": "*string", "Reason": "*string"},
			"create-compute-environment":       {"ComputeEnvironmentName": "*string", "ComputeResources": "*types.ComputeResource", "Context": "*string", "EksConfiguration": "*types.EksConfiguration", "ServiceRole": "*string", "State": "types.CEState", "Tags": "map[string]string", "Type": "types.CEType", "UnmanagedvCpus": "*int32"},
			"create-consumable-resource":       {"ConsumableResourceName": "*string", "ResourceType": "*string", "Tags": "map[string]string", "TotalQuantity": "*int64"},
			"create-job-queue":                 {"ComputeEnvironmentOrder": "[]types.ComputeEnvironmentOrder", "JobQueueName": "*string", "JobQueueType": "types.JobQueueType", "JobStateTimeLimitActions": "[]types.JobStateTimeLimitAction", "Priority": "*int32", "SchedulingPolicyArn": "*string", "ServiceEnvironmentOrder": "[]types.ServiceEnvironmentOrder", "State": "types.JQState", "Tags": "map[string]string"},
			"create-scheduling-policy":         {"FairsharePolicy": "*types.FairsharePolicy", "Name": "*string", "Tags": "map[string]string"},
			"create-service-environment":       {"CapacityLimits": "[]types.CapacityLimit", "ServiceEnvironmentName": "*string", "ServiceEnvironmentType": "types.ServiceEnvironmentType", "State": "types.ServiceEnvironmentState", "Tags": "map[string]string"},
			"delete-compute-environment":       {"ComputeEnvironment": "*string"},
			"delete-consumable-resource":       {"ConsumableResource": "*string"},
			"delete-job-queue":                 {"JobQueue": "*string"},
			"delete-scheduling-policy":         {"Arn": "*string"},
			"delete-service-environment":       {"ServiceEnvironment": "*string"},
			"deregister-job-definition":        {"JobDefinition": "*string"},
			"describe-compute-environments":    {"ComputeEnvironments": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-consumable-resource":     {"ConsumableResource": "*string"},
			"describe-job-definitions":         {"JobDefinitionName": "*string", "JobDefinitions": "[]string", "MaxResults": "*int32", "NextToken": "*string", "Status": "*string"},
			"describe-job-queues":              {"JobQueues": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-jobs":                    {"Jobs": "[]string"},
			"describe-scheduling-policies":     {"Arns": "[]string"},
			"describe-service-environments":    {"MaxResults": "*int32", "NextToken": "*string", "ServiceEnvironments": "[]string"},
			"describe-service-job":             {"JobId": "*string"},
			"get-job-queue-snapshot":           {"JobQueue": "*string"},
			"list-consumable-resources":        {"Filters": "[]types.KeyValuesPair", "MaxResults": "*int32", "NextToken": "*string"},
			"list-jobs":                        {"ArrayJobId": "*string", "Filters": "[]types.KeyValuesPair", "JobQueue": "*string", "JobStatus": "types.JobStatus", "MaxResults": "*int32", "MultiNodeJobId": "*string", "NextToken": "*string"},
			"list-jobs-by-consumable-resource": {"ConsumableResource": "*string", "Filters": "[]types.KeyValuesPair", "MaxResults": "*int32", "NextToken": "*string"},
			"list-scheduling-policies":         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-service-jobs":                {"Filters": "[]types.KeyValuesPair", "JobQueue": "*string", "JobStatus": "types.ServiceJobStatus", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":           {"ResourceArn": "*string"},
			"register-job-definition":          {"ConsumableResourceProperties": "*types.ConsumableResourceProperties", "ContainerProperties": "*types.ContainerProperties", "EcsProperties": "*types.EcsProperties", "EksProperties": "*types.EksProperties", "JobDefinitionName": "*string", "NodeProperties": "*types.NodeProperties", "Parameters": "map[string]string", "PlatformCapabilities": "[]types.PlatformCapability", "PropagateTags": "*bool", "RetryStrategy": "*types.RetryStrategy", "SchedulingPriority": "*int32", "Tags": "map[string]string", "Timeout": "*types.JobTimeout", "Type": "types.JobDefinitionType"},
			"submit-job":                       {"ArrayProperties": "*types.ArrayProperties", "ConsumableResourcePropertiesOverride": "*types.ConsumableResourceProperties", "ContainerOverrides": "*types.ContainerOverrides", "DependsOn": "[]types.JobDependency", "EcsPropertiesOverride": "*types.EcsPropertiesOverride", "EksPropertiesOverride": "*types.EksPropertiesOverride", "JobDefinition": "*string", "JobName": "*string", "JobQueue": "*string", "NodeOverrides": "*types.NodeOverrides", "Parameters": "map[string]string", "PropagateTags": "*bool", "RetryStrategy": "*types.RetryStrategy", "SchedulingPriorityOverride": "*int32", "ShareIdentifier": "*string", "Tags": "map[string]string", "Timeout": "*types.JobTimeout"},
			"submit-service-job":               {"ClientToken": "*string", "JobName": "*string", "JobQueue": "*string", "RetryStrategy": "*types.ServiceJobRetryStrategy", "SchedulingPriority": "*int32", "ServiceJobType": "types.ServiceJobType", "ServiceRequestPayload": "*string", "ShareIdentifier": "*string", "Tags": "map[string]string", "TimeoutConfig": "*types.ServiceJobTimeout"},
			"tag-resource":                     {"ResourceArn": "*string", "Tags": "map[string]string"},
			"terminate-job":                    {"JobId": "*string", "Reason": "*string"},
			"terminate-service-job":            {"JobId": "*string", "Reason": "*string"},
			"untag-resource":                   {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-compute-environment":       {"ComputeEnvironment": "*string", "ComputeResources": "*types.ComputeResourceUpdate", "Context": "*string", "ServiceRole": "*string", "State": "types.CEState", "UnmanagedvCpus": "*int32", "UpdatePolicy": "*types.UpdatePolicy"},
			"update-consumable-resource":       {"ClientToken": "*string", "ConsumableResource": "*string", "Operation": "*string", "Quantity": "*int64"},
			"update-job-queue":                 {"ComputeEnvironmentOrder": "[]types.ComputeEnvironmentOrder", "JobQueue": "*string", "JobStateTimeLimitActions": "[]types.JobStateTimeLimitAction", "Priority": "*int32", "SchedulingPolicyArn": "*string", "ServiceEnvironmentOrder": "[]types.ServiceEnvironmentOrder", "State": "types.JQState"},
			"update-scheduling-policy":         {"Arn": "*string", "FairsharePolicy": "*types.FairsharePolicy"},
			"update-service-environment":       {"CapacityLimits": "[]types.CapacityLimit", "ServiceEnvironment": "*string", "State": "types.ServiceEnvironmentState"},
		},
		OperationInputRequired: map[string][]string{
			"cancel-job":                       {"JobId", "Reason"},
			"create-compute-environment":       {"ComputeEnvironmentName", "Type"},
			"create-consumable-resource":       {"ConsumableResourceName"},
			"create-job-queue":                 {"JobQueueName", "Priority"},
			"create-scheduling-policy":         {"Name"},
			"create-service-environment":       {"CapacityLimits", "ServiceEnvironmentName", "ServiceEnvironmentType"},
			"delete-compute-environment":       {"ComputeEnvironment"},
			"delete-consumable-resource":       {"ConsumableResource"},
			"delete-job-queue":                 {"JobQueue"},
			"delete-scheduling-policy":         {"Arn"},
			"delete-service-environment":       {"ServiceEnvironment"},
			"deregister-job-definition":        {"JobDefinition"},
			"describe-compute-environments":    {},
			"describe-consumable-resource":     {"ConsumableResource"},
			"describe-job-definitions":         {},
			"describe-job-queues":              {},
			"describe-jobs":                    {"Jobs"},
			"describe-scheduling-policies":     {"Arns"},
			"describe-service-environments":    {},
			"describe-service-job":             {"JobId"},
			"get-job-queue-snapshot":           {"JobQueue"},
			"list-consumable-resources":        {},
			"list-jobs":                        {},
			"list-jobs-by-consumable-resource": {"ConsumableResource"},
			"list-scheduling-policies":         {},
			"list-service-jobs":                {},
			"list-tags-for-resource":           {"ResourceArn"},
			"register-job-definition":          {"JobDefinitionName", "Type"},
			"submit-job":                       {"JobDefinition", "JobName", "JobQueue"},
			"submit-service-job":               {"JobName", "JobQueue", "ServiceJobType", "ServiceRequestPayload"},
			"tag-resource":                     {"ResourceArn", "Tags"},
			"terminate-job":                    {"JobId", "Reason"},
			"terminate-service-job":            {"JobId", "Reason"},
			"untag-resource":                   {"ResourceArn", "TagKeys"},
			"update-compute-environment":       {"ComputeEnvironment"},
			"update-consumable-resource":       {"ConsumableResource"},
			"update-job-queue":                 {"JobQueue"},
			"update-scheduling-policy":         {"Arn"},
			"update-service-environment":       {"ServiceEnvironment"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("batch", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
