package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/memorydb/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-update-cluster", "copy-snapshot", "create-acl", "create-cluster", "create-multi-region-cluster", "create-parameter-group", "create-snapshot", "create-subnet-group", "create-user", "delete-acl", "delete-cluster", "delete-multi-region-cluster", "delete-parameter-group", "delete-snapshot", "delete-subnet-group", "delete-user", "describe-acls", "describe-clusters", "describe-engine-versions", "describe-events", "describe-multi-region-clusters", "describe-multi-region-parameter-groups", "describe-multi-region-parameters", "describe-parameter-groups", "describe-parameters", "describe-reserved-nodes", "describe-reserved-nodes-offerings", "describe-service-updates", "describe-snapshots", "describe-subnet-groups", "describe-users", "failover-shard", "list-allowed-multi-region-cluster-updates", "list-allowed-node-type-updates", "list-tags", "purchase-reserved-nodes-offering", "reset-parameter-group", "tag-resource", "untag-resource", "update-acl", "update-cluster", "update-multi-region-cluster", "update-parameter-group", "update-subnet-group", "update-user"},
		OperationSet: map[string]bool{"batch-update-cluster": true, "copy-snapshot": true, "create-acl": true, "create-cluster": true, "create-multi-region-cluster": true, "create-parameter-group": true, "create-snapshot": true, "create-subnet-group": true, "create-user": true, "delete-acl": true, "delete-cluster": true, "delete-multi-region-cluster": true, "delete-parameter-group": true, "delete-snapshot": true, "delete-subnet-group": true, "delete-user": true, "describe-acls": true, "describe-clusters": true, "describe-engine-versions": true, "describe-events": true, "describe-multi-region-clusters": true, "describe-multi-region-parameter-groups": true, "describe-multi-region-parameters": true, "describe-parameter-groups": true, "describe-parameters": true, "describe-reserved-nodes": true, "describe-reserved-nodes-offerings": true, "describe-service-updates": true, "describe-snapshots": true, "describe-subnet-groups": true, "describe-users": true, "failover-shard": true, "list-allowed-multi-region-cluster-updates": true, "list-allowed-node-type-updates": true, "list-tags": true, "purchase-reserved-nodes-offering": true, "reset-parameter-group": true, "tag-resource": true, "untag-resource": true, "update-acl": true, "update-cluster": true, "update-multi-region-cluster": true, "update-parameter-group": true, "update-subnet-group": true, "update-user": true},
		OperationInputs: map[string][]string{
			"batch-update-cluster":                      {"ClusterNames", "ServiceUpdate"},
			"copy-snapshot":                             {"KmsKeyId", "SourceSnapshotName", "Tags", "TargetBucket", "TargetSnapshotName"},
			"create-acl":                                {"ACLName", "Tags", "UserNames"},
			"create-cluster":                            {"ACLName", "AutoMinorVersionUpgrade", "ClusterName", "DataTiering", "Description", "Engine", "EngineVersion", "IpDiscovery", "KmsKeyId", "MaintenanceWindow", "MultiRegionClusterName", "NetworkType", "NodeType", "NumReplicasPerShard", "NumShards", "ParameterGroupName", "Port", "SecurityGroupIds", "SnapshotArns", "SnapshotName", "SnapshotRetentionLimit", "SnapshotWindow", "SnsTopicArn", "SubnetGroupName", "TLSEnabled", "Tags"},
			"create-multi-region-cluster":               {"Description", "Engine", "EngineVersion", "MultiRegionClusterNameSuffix", "MultiRegionParameterGroupName", "NodeType", "NumShards", "TLSEnabled", "Tags"},
			"create-parameter-group":                    {"Description", "Family", "ParameterGroupName", "Tags"},
			"create-snapshot":                           {"ClusterName", "KmsKeyId", "SnapshotName", "Tags"},
			"create-subnet-group":                       {"Description", "SubnetGroupName", "SubnetIds", "Tags"},
			"create-user":                               {"AccessString", "AuthenticationMode", "Tags", "UserName"},
			"delete-acl":                                {"ACLName"},
			"delete-cluster":                            {"ClusterName", "FinalSnapshotName", "MultiRegionClusterName"},
			"delete-multi-region-cluster":               {"MultiRegionClusterName"},
			"delete-parameter-group":                    {"ParameterGroupName"},
			"delete-snapshot":                           {"SnapshotName"},
			"delete-subnet-group":                       {"SubnetGroupName"},
			"delete-user":                               {"UserName"},
			"describe-acls":                             {"ACLName", "MaxResults", "NextToken"},
			"describe-clusters":                         {"ClusterName", "MaxResults", "NextToken", "ShowShardDetails"},
			"describe-engine-versions":                  {"DefaultOnly", "Engine", "EngineVersion", "MaxResults", "NextToken", "ParameterGroupFamily"},
			"describe-events":                           {"Duration", "EndTime", "MaxResults", "NextToken", "SourceName", "SourceType", "StartTime"},
			"describe-multi-region-clusters":            {"MaxResults", "MultiRegionClusterName", "NextToken", "ShowClusterDetails"},
			"describe-multi-region-parameter-groups":    {"MaxResults", "MultiRegionParameterGroupName", "NextToken"},
			"describe-multi-region-parameters":          {"MaxResults", "MultiRegionParameterGroupName", "NextToken", "Source"},
			"describe-parameter-groups":                 {"MaxResults", "NextToken", "ParameterGroupName"},
			"describe-parameters":                       {"MaxResults", "NextToken", "ParameterGroupName"},
			"describe-reserved-nodes":                   {"Duration", "MaxResults", "NextToken", "NodeType", "OfferingType", "ReservationId", "ReservedNodesOfferingId"},
			"describe-reserved-nodes-offerings":         {"Duration", "MaxResults", "NextToken", "NodeType", "OfferingType", "ReservedNodesOfferingId"},
			"describe-service-updates":                  {"ClusterNames", "MaxResults", "NextToken", "ServiceUpdateName", "Status"},
			"describe-snapshots":                        {"ClusterName", "MaxResults", "NextToken", "ShowDetail", "SnapshotName", "Source"},
			"describe-subnet-groups":                    {"MaxResults", "NextToken", "SubnetGroupName"},
			"describe-users":                            {"Filters", "MaxResults", "NextToken", "UserName"},
			"failover-shard":                            {"ClusterName", "ShardName"},
			"list-allowed-multi-region-cluster-updates": {"MultiRegionClusterName"},
			"list-allowed-node-type-updates":            {"ClusterName"},
			"list-tags":                                 {"ResourceArn"},
			"purchase-reserved-nodes-offering":          {"NodeCount", "ReservationId", "ReservedNodesOfferingId", "Tags"},
			"reset-parameter-group":                     {"AllParameters", "ParameterGroupName", "ParameterNames"},
			"tag-resource":                              {"ResourceArn", "Tags"},
			"untag-resource":                            {"ResourceArn", "TagKeys"},
			"update-acl":                                {"ACLName", "UserNamesToAdd", "UserNamesToRemove"},
			"update-cluster":                            {"ACLName", "ClusterName", "Description", "Engine", "EngineVersion", "IpDiscovery", "MaintenanceWindow", "NodeType", "ParameterGroupName", "ReplicaConfiguration", "SecurityGroupIds", "ShardConfiguration", "SnapshotRetentionLimit", "SnapshotWindow", "SnsTopicArn", "SnsTopicStatus"},
			"update-multi-region-cluster":               {"Description", "EngineVersion", "MultiRegionClusterName", "MultiRegionParameterGroupName", "NodeType", "ShardConfiguration", "UpdateStrategy"},
			"update-parameter-group":                    {"ParameterGroupName", "ParameterNameValues"},
			"update-subnet-group":                       {"Description", "SubnetGroupName", "SubnetIds"},
			"update-user":                               {"AccessString", "AuthenticationMode", "UserName"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-update-cluster":                      {"ClusterNames": "[]string", "ServiceUpdate": "*types.ServiceUpdateRequest"},
			"copy-snapshot":                             {"KmsKeyId": "*string", "SourceSnapshotName": "*string", "Tags": "[]types.Tag", "TargetBucket": "*string", "TargetSnapshotName": "*string"},
			"create-acl":                                {"ACLName": "*string", "Tags": "[]types.Tag", "UserNames": "[]string"},
			"create-cluster":                            {"ACLName": "*string", "AutoMinorVersionUpgrade": "*bool", "ClusterName": "*string", "DataTiering": "*bool", "Description": "*string", "Engine": "*string", "EngineVersion": "*string", "IpDiscovery": "types.IpDiscovery", "KmsKeyId": "*string", "MaintenanceWindow": "*string", "MultiRegionClusterName": "*string", "NetworkType": "types.NetworkType", "NodeType": "*string", "NumReplicasPerShard": "*int32", "NumShards": "*int32", "ParameterGroupName": "*string", "Port": "*int32", "SecurityGroupIds": "[]string", "SnapshotArns": "[]string", "SnapshotName": "*string", "SnapshotRetentionLimit": "*int32", "SnapshotWindow": "*string", "SnsTopicArn": "*string", "SubnetGroupName": "*string", "TLSEnabled": "*bool", "Tags": "[]types.Tag"},
			"create-multi-region-cluster":               {"Description": "*string", "Engine": "*string", "EngineVersion": "*string", "MultiRegionClusterNameSuffix": "*string", "MultiRegionParameterGroupName": "*string", "NodeType": "*string", "NumShards": "*int32", "TLSEnabled": "*bool", "Tags": "[]types.Tag"},
			"create-parameter-group":                    {"Description": "*string", "Family": "*string", "ParameterGroupName": "*string", "Tags": "[]types.Tag"},
			"create-snapshot":                           {"ClusterName": "*string", "KmsKeyId": "*string", "SnapshotName": "*string", "Tags": "[]types.Tag"},
			"create-subnet-group":                       {"Description": "*string", "SubnetGroupName": "*string", "SubnetIds": "[]string", "Tags": "[]types.Tag"},
			"create-user":                               {"AccessString": "*string", "AuthenticationMode": "*types.AuthenticationMode", "Tags": "[]types.Tag", "UserName": "*string"},
			"delete-acl":                                {"ACLName": "*string"},
			"delete-cluster":                            {"ClusterName": "*string", "FinalSnapshotName": "*string", "MultiRegionClusterName": "*string"},
			"delete-multi-region-cluster":               {"MultiRegionClusterName": "*string"},
			"delete-parameter-group":                    {"ParameterGroupName": "*string"},
			"delete-snapshot":                           {"SnapshotName": "*string"},
			"delete-subnet-group":                       {"SubnetGroupName": "*string"},
			"delete-user":                               {"UserName": "*string"},
			"describe-acls":                             {"ACLName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-clusters":                         {"ClusterName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ShowShardDetails": "*bool"},
			"describe-engine-versions":                  {"DefaultOnly": "bool", "Engine": "*string", "EngineVersion": "*string", "MaxResults": "*int32", "NextToken": "*string", "ParameterGroupFamily": "*string"},
			"describe-events":                           {"Duration": "*int32", "EndTime": "*time.Time", "MaxResults": "*int32", "NextToken": "*string", "SourceName": "*string", "SourceType": "types.SourceType", "StartTime": "*time.Time"},
			"describe-multi-region-clusters":            {"MaxResults": "*int32", "MultiRegionClusterName": "*string", "NextToken": "*string", "ShowClusterDetails": "*bool"},
			"describe-multi-region-parameter-groups":    {"MaxResults": "*int32", "MultiRegionParameterGroupName": "*string", "NextToken": "*string"},
			"describe-multi-region-parameters":          {"MaxResults": "*int32", "MultiRegionParameterGroupName": "*string", "NextToken": "*string", "Source": "*string"},
			"describe-parameter-groups":                 {"MaxResults": "*int32", "NextToken": "*string", "ParameterGroupName": "*string"},
			"describe-parameters":                       {"MaxResults": "*int32", "NextToken": "*string", "ParameterGroupName": "*string"},
			"describe-reserved-nodes":                   {"Duration": "*string", "MaxResults": "*int32", "NextToken": "*string", "NodeType": "*string", "OfferingType": "*string", "ReservationId": "*string", "ReservedNodesOfferingId": "*string"},
			"describe-reserved-nodes-offerings":         {"Duration": "*string", "MaxResults": "*int32", "NextToken": "*string", "NodeType": "*string", "OfferingType": "*string", "ReservedNodesOfferingId": "*string"},
			"describe-service-updates":                  {"ClusterNames": "[]string", "MaxResults": "*int32", "NextToken": "*string", "ServiceUpdateName": "*string", "Status": "[]types.ServiceUpdateStatus"},
			"describe-snapshots":                        {"ClusterName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ShowDetail": "*bool", "SnapshotName": "*string", "Source": "*string"},
			"describe-subnet-groups":                    {"MaxResults": "*int32", "NextToken": "*string", "SubnetGroupName": "*string"},
			"describe-users":                            {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string", "UserName": "*string"},
			"failover-shard":                            {"ClusterName": "*string", "ShardName": "*string"},
			"list-allowed-multi-region-cluster-updates": {"MultiRegionClusterName": "*string"},
			"list-allowed-node-type-updates":            {"ClusterName": "*string"},
			"list-tags":                                 {"ResourceArn": "*string"},
			"purchase-reserved-nodes-offering":          {"NodeCount": "*int32", "ReservationId": "*string", "ReservedNodesOfferingId": "*string", "Tags": "[]types.Tag"},
			"reset-parameter-group":                     {"AllParameters": "bool", "ParameterGroupName": "*string", "ParameterNames": "[]string"},
			"tag-resource":                              {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                            {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-acl":                                {"ACLName": "*string", "UserNamesToAdd": "[]string", "UserNamesToRemove": "[]string"},
			"update-cluster":                            {"ACLName": "*string", "ClusterName": "*string", "Description": "*string", "Engine": "*string", "EngineVersion": "*string", "IpDiscovery": "types.IpDiscovery", "MaintenanceWindow": "*string", "NodeType": "*string", "ParameterGroupName": "*string", "ReplicaConfiguration": "*types.ReplicaConfigurationRequest", "SecurityGroupIds": "[]string", "ShardConfiguration": "*types.ShardConfigurationRequest", "SnapshotRetentionLimit": "*int32", "SnapshotWindow": "*string", "SnsTopicArn": "*string", "SnsTopicStatus": "*string"},
			"update-multi-region-cluster":               {"Description": "*string", "EngineVersion": "*string", "MultiRegionClusterName": "*string", "MultiRegionParameterGroupName": "*string", "NodeType": "*string", "ShardConfiguration": "*types.ShardConfigurationRequest", "UpdateStrategy": "types.UpdateStrategy"},
			"update-parameter-group":                    {"ParameterGroupName": "*string", "ParameterNameValues": "[]types.ParameterNameValue"},
			"update-subnet-group":                       {"Description": "*string", "SubnetGroupName": "*string", "SubnetIds": "[]string"},
			"update-user":                               {"AccessString": "*string", "AuthenticationMode": "*types.AuthenticationMode", "UserName": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-update-cluster":                      {"ClusterNames"},
			"copy-snapshot":                             {"SourceSnapshotName", "TargetSnapshotName"},
			"create-acl":                                {"ACLName"},
			"create-cluster":                            {"ACLName", "ClusterName", "NodeType"},
			"create-multi-region-cluster":               {"MultiRegionClusterNameSuffix", "NodeType"},
			"create-parameter-group":                    {"Family", "ParameterGroupName"},
			"create-snapshot":                           {"ClusterName", "SnapshotName"},
			"create-subnet-group":                       {"SubnetGroupName", "SubnetIds"},
			"create-user":                               {"AccessString", "AuthenticationMode", "UserName"},
			"delete-acl":                                {"ACLName"},
			"delete-cluster":                            {"ClusterName"},
			"delete-multi-region-cluster":               {"MultiRegionClusterName"},
			"delete-parameter-group":                    {"ParameterGroupName"},
			"delete-snapshot":                           {"SnapshotName"},
			"delete-subnet-group":                       {"SubnetGroupName"},
			"delete-user":                               {"UserName"},
			"describe-acls":                             {},
			"describe-clusters":                         {},
			"describe-engine-versions":                  {},
			"describe-events":                           {},
			"describe-multi-region-clusters":            {},
			"describe-multi-region-parameter-groups":    {},
			"describe-multi-region-parameters":          {"MultiRegionParameterGroupName"},
			"describe-parameter-groups":                 {},
			"describe-parameters":                       {"ParameterGroupName"},
			"describe-reserved-nodes":                   {},
			"describe-reserved-nodes-offerings":         {},
			"describe-service-updates":                  {},
			"describe-snapshots":                        {},
			"describe-subnet-groups":                    {},
			"describe-users":                            {},
			"failover-shard":                            {"ClusterName", "ShardName"},
			"list-allowed-multi-region-cluster-updates": {"MultiRegionClusterName"},
			"list-allowed-node-type-updates":            {"ClusterName"},
			"list-tags":                                 {"ResourceArn"},
			"purchase-reserved-nodes-offering":          {"ReservedNodesOfferingId"},
			"reset-parameter-group":                     {"ParameterGroupName"},
			"tag-resource":                              {"ResourceArn", "Tags"},
			"untag-resource":                            {"ResourceArn", "TagKeys"},
			"update-acl":                                {"ACLName"},
			"update-cluster":                            {"ClusterName"},
			"update-multi-region-cluster":               {"MultiRegionClusterName"},
			"update-parameter-group":                    {"ParameterGroupName", "ParameterNameValues"},
			"update-subnet-group":                       {"SubnetGroupName"},
			"update-user":                               {"UserName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("memorydb", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
