package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/s3control/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-access-grants-identity-center", "create-access-grant", "create-access-grants-instance", "create-access-grants-location", "create-access-point", "create-access-point-for-object-lambda", "create-bucket", "create-job", "create-multi-region-access-point", "create-storage-lens-group", "delete-access-grant", "delete-access-grants-instance", "delete-access-grants-instance-resource-policy", "delete-access-grants-location", "delete-access-point", "delete-access-point-for-object-lambda", "delete-access-point-policy", "delete-access-point-policy-for-object-lambda", "delete-access-point-scope", "delete-bucket", "delete-bucket-lifecycle-configuration", "delete-bucket-policy", "delete-bucket-replication", "delete-bucket-tagging", "delete-job-tagging", "delete-multi-region-access-point", "delete-public-access-block", "delete-storage-lens-configuration", "delete-storage-lens-configuration-tagging", "delete-storage-lens-group", "describe-job", "describe-multi-region-access-point-operation", "dissociate-access-grants-identity-center", "get-access-grant", "get-access-grants-instance", "get-access-grants-instance-for-prefix", "get-access-grants-instance-resource-policy", "get-access-grants-location", "get-access-point", "get-access-point-configuration-for-object-lambda", "get-access-point-for-object-lambda", "get-access-point-policy", "get-access-point-policy-for-object-lambda", "get-access-point-policy-status", "get-access-point-policy-status-for-object-lambda", "get-access-point-scope", "get-bucket", "get-bucket-lifecycle-configuration", "get-bucket-policy", "get-bucket-replication", "get-bucket-tagging", "get-bucket-versioning", "get-data-access", "get-job-tagging", "get-multi-region-access-point", "get-multi-region-access-point-policy", "get-multi-region-access-point-policy-status", "get-multi-region-access-point-routes", "get-public-access-block", "get-storage-lens-configuration", "get-storage-lens-configuration-tagging", "get-storage-lens-group", "list-access-grants", "list-access-grants-instances", "list-access-grants-locations", "list-access-points", "list-access-points-for-directory-buckets", "list-access-points-for-object-lambda", "list-caller-access-grants", "list-jobs", "list-multi-region-access-points", "list-regional-buckets", "list-storage-lens-configurations", "list-storage-lens-groups", "list-tags-for-resource", "put-access-grants-instance-resource-policy", "put-access-point-configuration-for-object-lambda", "put-access-point-policy", "put-access-point-policy-for-object-lambda", "put-access-point-scope", "put-bucket-lifecycle-configuration", "put-bucket-policy", "put-bucket-replication", "put-bucket-tagging", "put-bucket-versioning", "put-job-tagging", "put-multi-region-access-point-policy", "put-public-access-block", "put-storage-lens-configuration", "put-storage-lens-configuration-tagging", "submit-multi-region-access-point-routes", "tag-resource", "untag-resource", "update-access-grants-location", "update-job-priority", "update-job-status", "update-storage-lens-group"},
		OperationSet: map[string]bool{"associate-access-grants-identity-center": true, "create-access-grant": true, "create-access-grants-instance": true, "create-access-grants-location": true, "create-access-point": true, "create-access-point-for-object-lambda": true, "create-bucket": true, "create-job": true, "create-multi-region-access-point": true, "create-storage-lens-group": true, "delete-access-grant": true, "delete-access-grants-instance": true, "delete-access-grants-instance-resource-policy": true, "delete-access-grants-location": true, "delete-access-point": true, "delete-access-point-for-object-lambda": true, "delete-access-point-policy": true, "delete-access-point-policy-for-object-lambda": true, "delete-access-point-scope": true, "delete-bucket": true, "delete-bucket-lifecycle-configuration": true, "delete-bucket-policy": true, "delete-bucket-replication": true, "delete-bucket-tagging": true, "delete-job-tagging": true, "delete-multi-region-access-point": true, "delete-public-access-block": true, "delete-storage-lens-configuration": true, "delete-storage-lens-configuration-tagging": true, "delete-storage-lens-group": true, "describe-job": true, "describe-multi-region-access-point-operation": true, "dissociate-access-grants-identity-center": true, "get-access-grant": true, "get-access-grants-instance": true, "get-access-grants-instance-for-prefix": true, "get-access-grants-instance-resource-policy": true, "get-access-grants-location": true, "get-access-point": true, "get-access-point-configuration-for-object-lambda": true, "get-access-point-for-object-lambda": true, "get-access-point-policy": true, "get-access-point-policy-for-object-lambda": true, "get-access-point-policy-status": true, "get-access-point-policy-status-for-object-lambda": true, "get-access-point-scope": true, "get-bucket": true, "get-bucket-lifecycle-configuration": true, "get-bucket-policy": true, "get-bucket-replication": true, "get-bucket-tagging": true, "get-bucket-versioning": true, "get-data-access": true, "get-job-tagging": true, "get-multi-region-access-point": true, "get-multi-region-access-point-policy": true, "get-multi-region-access-point-policy-status": true, "get-multi-region-access-point-routes": true, "get-public-access-block": true, "get-storage-lens-configuration": true, "get-storage-lens-configuration-tagging": true, "get-storage-lens-group": true, "list-access-grants": true, "list-access-grants-instances": true, "list-access-grants-locations": true, "list-access-points": true, "list-access-points-for-directory-buckets": true, "list-access-points-for-object-lambda": true, "list-caller-access-grants": true, "list-jobs": true, "list-multi-region-access-points": true, "list-regional-buckets": true, "list-storage-lens-configurations": true, "list-storage-lens-groups": true, "list-tags-for-resource": true, "put-access-grants-instance-resource-policy": true, "put-access-point-configuration-for-object-lambda": true, "put-access-point-policy": true, "put-access-point-policy-for-object-lambda": true, "put-access-point-scope": true, "put-bucket-lifecycle-configuration": true, "put-bucket-policy": true, "put-bucket-replication": true, "put-bucket-tagging": true, "put-bucket-versioning": true, "put-job-tagging": true, "put-multi-region-access-point-policy": true, "put-public-access-block": true, "put-storage-lens-configuration": true, "put-storage-lens-configuration-tagging": true, "submit-multi-region-access-point-routes": true, "tag-resource": true, "untag-resource": true, "update-access-grants-location": true, "update-job-priority": true, "update-job-status": true, "update-storage-lens-group": true},
		OperationInputs: map[string][]string{
			"associate-access-grants-identity-center":          {"AccountId", "IdentityCenterArn"},
			"create-access-grant":                              {"AccessGrantsLocationConfiguration", "AccessGrantsLocationId", "AccountId", "ApplicationArn", "Grantee", "Permission", "S3PrefixType", "Tags"},
			"create-access-grants-instance":                    {"AccountId", "IdentityCenterArn", "Tags"},
			"create-access-grants-location":                    {"AccountId", "IAMRoleArn", "LocationScope", "Tags"},
			"create-access-point":                              {"AccountId", "Bucket", "BucketAccountId", "Name", "PublicAccessBlockConfiguration", "Scope", "Tags", "VpcConfiguration"},
			"create-access-point-for-object-lambda":            {"AccountId", "Configuration", "Name"},
			"create-bucket":                                    {"ACL", "Bucket", "CreateBucketConfiguration", "GrantFullControl", "GrantRead", "GrantReadACP", "GrantWrite", "GrantWriteACP", "ObjectLockEnabledForBucket", "OutpostId"},
			"create-job":                                       {"AccountId", "ClientRequestToken", "ConfirmationRequired", "Description", "Manifest", "ManifestGenerator", "Operation", "Priority", "Report", "RoleArn", "Tags"},
			"create-multi-region-access-point":                 {"AccountId", "ClientToken", "Details"},
			"create-storage-lens-group":                        {"AccountId", "StorageLensGroup", "Tags"},
			"delete-access-grant":                              {"AccessGrantId", "AccountId"},
			"delete-access-grants-instance":                    {"AccountId"},
			"delete-access-grants-instance-resource-policy":    {"AccountId"},
			"delete-access-grants-location":                    {"AccessGrantsLocationId", "AccountId"},
			"delete-access-point":                              {"AccountId", "Name"},
			"delete-access-point-for-object-lambda":            {"AccountId", "Name"},
			"delete-access-point-policy":                       {"AccountId", "Name"},
			"delete-access-point-policy-for-object-lambda":     {"AccountId", "Name"},
			"delete-access-point-scope":                        {"AccountId", "Name"},
			"delete-bucket":                                    {"AccountId", "Bucket"},
			"delete-bucket-lifecycle-configuration":            {"AccountId", "Bucket"},
			"delete-bucket-policy":                             {"AccountId", "Bucket"},
			"delete-bucket-replication":                        {"AccountId", "Bucket"},
			"delete-bucket-tagging":                            {"AccountId", "Bucket"},
			"delete-job-tagging":                               {"AccountId", "JobId"},
			"delete-multi-region-access-point":                 {"AccountId", "ClientToken", "Details"},
			"delete-public-access-block":                       {"AccountId"},
			"delete-storage-lens-configuration":                {"AccountId", "ConfigId"},
			"delete-storage-lens-configuration-tagging":        {"AccountId", "ConfigId"},
			"delete-storage-lens-group":                        {"AccountId", "Name"},
			"describe-job":                                     {"AccountId", "JobId"},
			"describe-multi-region-access-point-operation":     {"AccountId", "RequestTokenARN"},
			"dissociate-access-grants-identity-center":         {"AccountId"},
			"get-access-grant":                                 {"AccessGrantId", "AccountId"},
			"get-access-grants-instance":                       {"AccountId"},
			"get-access-grants-instance-for-prefix":            {"AccountId", "S3Prefix"},
			"get-access-grants-instance-resource-policy":       {"AccountId"},
			"get-access-grants-location":                       {"AccessGrantsLocationId", "AccountId"},
			"get-access-point":                                 {"AccountId", "Name"},
			"get-access-point-configuration-for-object-lambda": {"AccountId", "Name"},
			"get-access-point-for-object-lambda":               {"AccountId", "Name"},
			"get-access-point-policy":                          {"AccountId", "Name"},
			"get-access-point-policy-for-object-lambda":        {"AccountId", "Name"},
			"get-access-point-policy-status":                   {"AccountId", "Name"},
			"get-access-point-policy-status-for-object-lambda": {"AccountId", "Name"},
			"get-access-point-scope":                           {"AccountId", "Name"},
			"get-bucket":                                       {"AccountId", "Bucket"},
			"get-bucket-lifecycle-configuration":               {"AccountId", "Bucket"},
			"get-bucket-policy":                                {"AccountId", "Bucket"},
			"get-bucket-replication":                           {"AccountId", "Bucket"},
			"get-bucket-tagging":                               {"AccountId", "Bucket"},
			"get-bucket-versioning":                            {"AccountId", "Bucket"},
			"get-data-access":                                  {"AccountId", "DurationSeconds", "Permission", "Privilege", "Target", "TargetType"},
			"get-job-tagging":                                  {"AccountId", "JobId"},
			"get-multi-region-access-point":                    {"AccountId", "Name"},
			"get-multi-region-access-point-policy":             {"AccountId", "Name"},
			"get-multi-region-access-point-policy-status":      {"AccountId", "Name"},
			"get-multi-region-access-point-routes":             {"AccountId", "Mrap"},
			"get-public-access-block":                          {"AccountId"},
			"get-storage-lens-configuration":                   {"AccountId", "ConfigId"},
			"get-storage-lens-configuration-tagging":           {"AccountId", "ConfigId"},
			"get-storage-lens-group":                           {"AccountId", "Name"},
			"list-access-grants":                               {"AccountId", "ApplicationArn", "GrantScope", "GranteeIdentifier", "GranteeType", "MaxResults", "NextToken", "Permission"},
			"list-access-grants-instances":                     {"AccountId", "MaxResults", "NextToken"},
			"list-access-grants-locations":                     {"AccountId", "LocationScope", "MaxResults", "NextToken"},
			"list-access-points":                               {"AccountId", "Bucket", "DataSourceId", "DataSourceType", "MaxResults", "NextToken"},
			"list-access-points-for-directory-buckets":         {"AccountId", "DirectoryBucket", "MaxResults", "NextToken"},
			"list-access-points-for-object-lambda":             {"AccountId", "MaxResults", "NextToken"},
			"list-caller-access-grants":                        {"AccountId", "AllowedByApplication", "GrantScope", "MaxResults", "NextToken"},
			"list-jobs":                                        {"AccountId", "JobStatuses", "MaxResults", "NextToken"},
			"list-multi-region-access-points":                  {"AccountId", "MaxResults", "NextToken"},
			"list-regional-buckets":                            {"AccountId", "MaxResults", "NextToken", "OutpostId"},
			"list-storage-lens-configurations":                 {"AccountId", "NextToken"},
			"list-storage-lens-groups":                         {"AccountId", "NextToken"},
			"list-tags-for-resource":                           {"AccountId", "ResourceArn"},
			"put-access-grants-instance-resource-policy":       {"AccountId", "Organization", "Policy"},
			"put-access-point-configuration-for-object-lambda": {"AccountId", "Configuration", "Name"},
			"put-access-point-policy":                          {"AccountId", "Name", "Policy"},
			"put-access-point-policy-for-object-lambda":        {"AccountId", "Name", "Policy"},
			"put-access-point-scope":                           {"AccountId", "Name", "Scope"},
			"put-bucket-lifecycle-configuration":               {"AccountId", "Bucket", "LifecycleConfiguration"},
			"put-bucket-policy":                                {"AccountId", "Bucket", "ConfirmRemoveSelfBucketAccess", "Policy"},
			"put-bucket-replication":                           {"AccountId", "Bucket", "ReplicationConfiguration"},
			"put-bucket-tagging":                               {"AccountId", "Bucket", "Tagging"},
			"put-bucket-versioning":                            {"AccountId", "Bucket", "MFA", "VersioningConfiguration"},
			"put-job-tagging":                                  {"AccountId", "JobId", "Tags"},
			"put-multi-region-access-point-policy":             {"AccountId", "ClientToken", "Details"},
			"put-public-access-block":                          {"AccountId", "PublicAccessBlockConfiguration"},
			"put-storage-lens-configuration":                   {"AccountId", "ConfigId", "StorageLensConfiguration", "Tags"},
			"put-storage-lens-configuration-tagging":           {"AccountId", "ConfigId", "Tags"},
			"submit-multi-region-access-point-routes":          {"AccountId", "Mrap", "RouteUpdates"},
			"tag-resource":                                     {"AccountId", "ResourceArn", "Tags"},
			"untag-resource":                                   {"AccountId", "ResourceArn", "TagKeys"},
			"update-access-grants-location":                    {"AccessGrantsLocationId", "AccountId", "IAMRoleArn"},
			"update-job-priority":                              {"AccountId", "JobId", "Priority"},
			"update-job-status":                                {"AccountId", "JobId", "RequestedJobStatus", "StatusUpdateReason"},
			"update-storage-lens-group":                        {"AccountId", "Name", "StorageLensGroup"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-access-grants-identity-center":          {"AccountId": "*string", "IdentityCenterArn": "*string"},
			"create-access-grant":                              {"AccessGrantsLocationConfiguration": "*types.AccessGrantsLocationConfiguration", "AccessGrantsLocationId": "*string", "AccountId": "*string", "ApplicationArn": "*string", "Grantee": "*types.Grantee", "Permission": "types.Permission", "S3PrefixType": "types.S3PrefixType", "Tags": "[]types.Tag"},
			"create-access-grants-instance":                    {"AccountId": "*string", "IdentityCenterArn": "*string", "Tags": "[]types.Tag"},
			"create-access-grants-location":                    {"AccountId": "*string", "IAMRoleArn": "*string", "LocationScope": "*string", "Tags": "[]types.Tag"},
			"create-access-point":                              {"AccountId": "*string", "Bucket": "*string", "BucketAccountId": "*string", "Name": "*string", "PublicAccessBlockConfiguration": "*types.PublicAccessBlockConfiguration", "Scope": "*types.Scope", "Tags": "[]types.Tag", "VpcConfiguration": "*types.VpcConfiguration"},
			"create-access-point-for-object-lambda":            {"AccountId": "*string", "Configuration": "*types.ObjectLambdaConfiguration", "Name": "*string"},
			"create-bucket":                                    {"ACL": "types.BucketCannedACL", "Bucket": "*string", "CreateBucketConfiguration": "*types.CreateBucketConfiguration", "GrantFullControl": "*string", "GrantRead": "*string", "GrantReadACP": "*string", "GrantWrite": "*string", "GrantWriteACP": "*string", "ObjectLockEnabledForBucket": "bool", "OutpostId": "*string"},
			"create-job":                                       {"AccountId": "*string", "ClientRequestToken": "*string", "ConfirmationRequired": "*bool", "Description": "*string", "Manifest": "*types.JobManifest", "ManifestGenerator": "types.JobManifestGenerator", "Operation": "*types.JobOperation", "Priority": "*int32", "Report": "*types.JobReport", "RoleArn": "*string", "Tags": "[]types.S3Tag"},
			"create-multi-region-access-point":                 {"AccountId": "*string", "ClientToken": "*string", "Details": "*types.CreateMultiRegionAccessPointInput"},
			"create-storage-lens-group":                        {"AccountId": "*string", "StorageLensGroup": "*types.StorageLensGroup", "Tags": "[]types.Tag"},
			"delete-access-grant":                              {"AccessGrantId": "*string", "AccountId": "*string"},
			"delete-access-grants-instance":                    {"AccountId": "*string"},
			"delete-access-grants-instance-resource-policy":    {"AccountId": "*string"},
			"delete-access-grants-location":                    {"AccessGrantsLocationId": "*string", "AccountId": "*string"},
			"delete-access-point":                              {"AccountId": "*string", "Name": "*string"},
			"delete-access-point-for-object-lambda":            {"AccountId": "*string", "Name": "*string"},
			"delete-access-point-policy":                       {"AccountId": "*string", "Name": "*string"},
			"delete-access-point-policy-for-object-lambda":     {"AccountId": "*string", "Name": "*string"},
			"delete-access-point-scope":                        {"AccountId": "*string", "Name": "*string"},
			"delete-bucket":                                    {"AccountId": "*string", "Bucket": "*string"},
			"delete-bucket-lifecycle-configuration":            {"AccountId": "*string", "Bucket": "*string"},
			"delete-bucket-policy":                             {"AccountId": "*string", "Bucket": "*string"},
			"delete-bucket-replication":                        {"AccountId": "*string", "Bucket": "*string"},
			"delete-bucket-tagging":                            {"AccountId": "*string", "Bucket": "*string"},
			"delete-job-tagging":                               {"AccountId": "*string", "JobId": "*string"},
			"delete-multi-region-access-point":                 {"AccountId": "*string", "ClientToken": "*string", "Details": "*types.DeleteMultiRegionAccessPointInput"},
			"delete-public-access-block":                       {"AccountId": "*string"},
			"delete-storage-lens-configuration":                {"AccountId": "*string", "ConfigId": "*string"},
			"delete-storage-lens-configuration-tagging":        {"AccountId": "*string", "ConfigId": "*string"},
			"delete-storage-lens-group":                        {"AccountId": "*string", "Name": "*string"},
			"describe-job":                                     {"AccountId": "*string", "JobId": "*string"},
			"describe-multi-region-access-point-operation":     {"AccountId": "*string", "RequestTokenARN": "*string"},
			"dissociate-access-grants-identity-center":         {"AccountId": "*string"},
			"get-access-grant":                                 {"AccessGrantId": "*string", "AccountId": "*string"},
			"get-access-grants-instance":                       {"AccountId": "*string"},
			"get-access-grants-instance-for-prefix":            {"AccountId": "*string", "S3Prefix": "*string"},
			"get-access-grants-instance-resource-policy":       {"AccountId": "*string"},
			"get-access-grants-location":                       {"AccessGrantsLocationId": "*string", "AccountId": "*string"},
			"get-access-point":                                 {"AccountId": "*string", "Name": "*string"},
			"get-access-point-configuration-for-object-lambda": {"AccountId": "*string", "Name": "*string"},
			"get-access-point-for-object-lambda":               {"AccountId": "*string", "Name": "*string"},
			"get-access-point-policy":                          {"AccountId": "*string", "Name": "*string"},
			"get-access-point-policy-for-object-lambda":        {"AccountId": "*string", "Name": "*string"},
			"get-access-point-policy-status":                   {"AccountId": "*string", "Name": "*string"},
			"get-access-point-policy-status-for-object-lambda": {"AccountId": "*string", "Name": "*string"},
			"get-access-point-scope":                           {"AccountId": "*string", "Name": "*string"},
			"get-bucket":                                       {"AccountId": "*string", "Bucket": "*string"},
			"get-bucket-lifecycle-configuration":               {"AccountId": "*string", "Bucket": "*string"},
			"get-bucket-policy":                                {"AccountId": "*string", "Bucket": "*string"},
			"get-bucket-replication":                           {"AccountId": "*string", "Bucket": "*string"},
			"get-bucket-tagging":                               {"AccountId": "*string", "Bucket": "*string"},
			"get-bucket-versioning":                            {"AccountId": "*string", "Bucket": "*string"},
			"get-data-access":                                  {"AccountId": "*string", "DurationSeconds": "*int32", "Permission": "types.Permission", "Privilege": "types.Privilege", "Target": "*string", "TargetType": "types.S3PrefixType"},
			"get-job-tagging":                                  {"AccountId": "*string", "JobId": "*string"},
			"get-multi-region-access-point":                    {"AccountId": "*string", "Name": "*string"},
			"get-multi-region-access-point-policy":             {"AccountId": "*string", "Name": "*string"},
			"get-multi-region-access-point-policy-status":      {"AccountId": "*string", "Name": "*string"},
			"get-multi-region-access-point-routes":             {"AccountId": "*string", "Mrap": "*string"},
			"get-public-access-block":                          {"AccountId": "*string"},
			"get-storage-lens-configuration":                   {"AccountId": "*string", "ConfigId": "*string"},
			"get-storage-lens-configuration-tagging":           {"AccountId": "*string", "ConfigId": "*string"},
			"get-storage-lens-group":                           {"AccountId": "*string", "Name": "*string"},
			"list-access-grants":                               {"AccountId": "*string", "ApplicationArn": "*string", "GrantScope": "*string", "GranteeIdentifier": "*string", "GranteeType": "types.GranteeType", "MaxResults": "int32", "NextToken": "*string", "Permission": "types.Permission"},
			"list-access-grants-instances":                     {"AccountId": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-access-grants-locations":                     {"AccountId": "*string", "LocationScope": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-access-points":                               {"AccountId": "*string", "Bucket": "*string", "DataSourceId": "*string", "DataSourceType": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-access-points-for-directory-buckets":         {"AccountId": "*string", "DirectoryBucket": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-access-points-for-object-lambda":             {"AccountId": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-caller-access-grants":                        {"AccountId": "*string", "AllowedByApplication": "bool", "GrantScope": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-jobs":                                        {"AccountId": "*string", "JobStatuses": "[]types.JobStatus", "MaxResults": "*int32", "NextToken": "*string"},
			"list-multi-region-access-points":                  {"AccountId": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-regional-buckets":                            {"AccountId": "*string", "MaxResults": "int32", "NextToken": "*string", "OutpostId": "*string"},
			"list-storage-lens-configurations":                 {"AccountId": "*string", "NextToken": "*string"},
			"list-storage-lens-groups":                         {"AccountId": "*string", "NextToken": "*string"},
			"list-tags-for-resource":                           {"AccountId": "*string", "ResourceArn": "*string"},
			"put-access-grants-instance-resource-policy":       {"AccountId": "*string", "Organization": "*string", "Policy": "*string"},
			"put-access-point-configuration-for-object-lambda": {"AccountId": "*string", "Configuration": "*types.ObjectLambdaConfiguration", "Name": "*string"},
			"put-access-point-policy":                          {"AccountId": "*string", "Name": "*string", "Policy": "*string"},
			"put-access-point-policy-for-object-lambda":        {"AccountId": "*string", "Name": "*string", "Policy": "*string"},
			"put-access-point-scope":                           {"AccountId": "*string", "Name": "*string", "Scope": "*types.Scope"},
			"put-bucket-lifecycle-configuration":               {"AccountId": "*string", "Bucket": "*string", "LifecycleConfiguration": "*types.LifecycleConfiguration"},
			"put-bucket-policy":                                {"AccountId": "*string", "Bucket": "*string", "ConfirmRemoveSelfBucketAccess": "bool", "Policy": "*string"},
			"put-bucket-replication":                           {"AccountId": "*string", "Bucket": "*string", "ReplicationConfiguration": "*types.ReplicationConfiguration"},
			"put-bucket-tagging":                               {"AccountId": "*string", "Bucket": "*string", "Tagging": "*types.Tagging"},
			"put-bucket-versioning":                            {"AccountId": "*string", "Bucket": "*string", "MFA": "*string", "VersioningConfiguration": "*types.VersioningConfiguration"},
			"put-job-tagging":                                  {"AccountId": "*string", "JobId": "*string", "Tags": "[]types.S3Tag"},
			"put-multi-region-access-point-policy":             {"AccountId": "*string", "ClientToken": "*string", "Details": "*types.PutMultiRegionAccessPointPolicyInput"},
			"put-public-access-block":                          {"AccountId": "*string", "PublicAccessBlockConfiguration": "*types.PublicAccessBlockConfiguration"},
			"put-storage-lens-configuration":                   {"AccountId": "*string", "ConfigId": "*string", "StorageLensConfiguration": "*types.StorageLensConfiguration", "Tags": "[]types.StorageLensTag"},
			"put-storage-lens-configuration-tagging":           {"AccountId": "*string", "ConfigId": "*string", "Tags": "[]types.StorageLensTag"},
			"submit-multi-region-access-point-routes":          {"AccountId": "*string", "Mrap": "*string", "RouteUpdates": "[]types.MultiRegionAccessPointRoute"},
			"tag-resource":                                     {"AccountId": "*string", "ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                                   {"AccountId": "*string", "ResourceArn": "*string", "TagKeys": "[]string"},
			"update-access-grants-location":                    {"AccessGrantsLocationId": "*string", "AccountId": "*string", "IAMRoleArn": "*string"},
			"update-job-priority":                              {"AccountId": "*string", "JobId": "*string", "Priority": "int32"},
			"update-job-status":                                {"AccountId": "*string", "JobId": "*string", "RequestedJobStatus": "types.RequestedJobStatus", "StatusUpdateReason": "*string"},
			"update-storage-lens-group":                        {"AccountId": "*string", "Name": "*string", "StorageLensGroup": "*types.StorageLensGroup"},
		},
		OperationInputRequired: map[string][]string{
			"associate-access-grants-identity-center":          {"AccountId", "IdentityCenterArn"},
			"create-access-grant":                              {"AccessGrantsLocationId", "AccountId", "Grantee", "Permission"},
			"create-access-grants-instance":                    {"AccountId"},
			"create-access-grants-location":                    {"AccountId", "IAMRoleArn", "LocationScope"},
			"create-access-point":                              {"AccountId", "Bucket", "Name"},
			"create-access-point-for-object-lambda":            {"AccountId", "Configuration", "Name"},
			"create-bucket":                                    {"Bucket"},
			"create-job":                                       {"AccountId", "ClientRequestToken", "Operation", "Priority", "Report", "RoleArn"},
			"create-multi-region-access-point":                 {"AccountId", "ClientToken", "Details"},
			"create-storage-lens-group":                        {"AccountId", "StorageLensGroup"},
			"delete-access-grant":                              {"AccessGrantId", "AccountId"},
			"delete-access-grants-instance":                    {"AccountId"},
			"delete-access-grants-instance-resource-policy":    {"AccountId"},
			"delete-access-grants-location":                    {"AccessGrantsLocationId", "AccountId"},
			"delete-access-point":                              {"AccountId", "Name"},
			"delete-access-point-for-object-lambda":            {"AccountId", "Name"},
			"delete-access-point-policy":                       {"AccountId", "Name"},
			"delete-access-point-policy-for-object-lambda":     {"AccountId", "Name"},
			"delete-access-point-scope":                        {"AccountId", "Name"},
			"delete-bucket":                                    {"AccountId", "Bucket"},
			"delete-bucket-lifecycle-configuration":            {"AccountId", "Bucket"},
			"delete-bucket-policy":                             {"AccountId", "Bucket"},
			"delete-bucket-replication":                        {"AccountId", "Bucket"},
			"delete-bucket-tagging":                            {"AccountId", "Bucket"},
			"delete-job-tagging":                               {"AccountId", "JobId"},
			"delete-multi-region-access-point":                 {"AccountId", "ClientToken", "Details"},
			"delete-public-access-block":                       {"AccountId"},
			"delete-storage-lens-configuration":                {"AccountId", "ConfigId"},
			"delete-storage-lens-configuration-tagging":        {"AccountId", "ConfigId"},
			"delete-storage-lens-group":                        {"AccountId", "Name"},
			"describe-job":                                     {"AccountId", "JobId"},
			"describe-multi-region-access-point-operation":     {"AccountId", "RequestTokenARN"},
			"dissociate-access-grants-identity-center":         {"AccountId"},
			"get-access-grant":                                 {"AccessGrantId", "AccountId"},
			"get-access-grants-instance":                       {"AccountId"},
			"get-access-grants-instance-for-prefix":            {"AccountId", "S3Prefix"},
			"get-access-grants-instance-resource-policy":       {"AccountId"},
			"get-access-grants-location":                       {"AccessGrantsLocationId", "AccountId"},
			"get-access-point":                                 {"AccountId", "Name"},
			"get-access-point-configuration-for-object-lambda": {"AccountId", "Name"},
			"get-access-point-for-object-lambda":               {"AccountId", "Name"},
			"get-access-point-policy":                          {"AccountId", "Name"},
			"get-access-point-policy-for-object-lambda":        {"AccountId", "Name"},
			"get-access-point-policy-status":                   {"AccountId", "Name"},
			"get-access-point-policy-status-for-object-lambda": {"AccountId", "Name"},
			"get-access-point-scope":                           {"AccountId", "Name"},
			"get-bucket":                                       {"AccountId", "Bucket"},
			"get-bucket-lifecycle-configuration":               {"AccountId", "Bucket"},
			"get-bucket-policy":                                {"AccountId", "Bucket"},
			"get-bucket-replication":                           {"AccountId", "Bucket"},
			"get-bucket-tagging":                               {"AccountId", "Bucket"},
			"get-bucket-versioning":                            {"AccountId", "Bucket"},
			"get-data-access":                                  {"AccountId", "Permission", "Target"},
			"get-job-tagging":                                  {"AccountId", "JobId"},
			"get-multi-region-access-point":                    {"AccountId", "Name"},
			"get-multi-region-access-point-policy":             {"AccountId", "Name"},
			"get-multi-region-access-point-policy-status":      {"AccountId", "Name"},
			"get-multi-region-access-point-routes":             {"AccountId", "Mrap"},
			"get-public-access-block":                          {"AccountId"},
			"get-storage-lens-configuration":                   {"AccountId", "ConfigId"},
			"get-storage-lens-configuration-tagging":           {"AccountId", "ConfigId"},
			"get-storage-lens-group":                           {"AccountId", "Name"},
			"list-access-grants":                               {"AccountId"},
			"list-access-grants-instances":                     {"AccountId"},
			"list-access-grants-locations":                     {"AccountId"},
			"list-access-points":                               {"AccountId"},
			"list-access-points-for-directory-buckets":         {"AccountId"},
			"list-access-points-for-object-lambda":             {"AccountId"},
			"list-caller-access-grants":                        {"AccountId"},
			"list-jobs":                                        {"AccountId"},
			"list-multi-region-access-points":                  {"AccountId"},
			"list-regional-buckets":                            {"AccountId"},
			"list-storage-lens-configurations":                 {"AccountId"},
			"list-storage-lens-groups":                         {"AccountId"},
			"list-tags-for-resource":                           {"AccountId", "ResourceArn"},
			"put-access-grants-instance-resource-policy":       {"AccountId", "Policy"},
			"put-access-point-configuration-for-object-lambda": {"AccountId", "Configuration", "Name"},
			"put-access-point-policy":                          {"AccountId", "Name", "Policy"},
			"put-access-point-policy-for-object-lambda":        {"AccountId", "Name", "Policy"},
			"put-access-point-scope":                           {"AccountId", "Name", "Scope"},
			"put-bucket-lifecycle-configuration":               {"AccountId", "Bucket"},
			"put-bucket-policy":                                {"AccountId", "Bucket", "Policy"},
			"put-bucket-replication":                           {"AccountId", "Bucket", "ReplicationConfiguration"},
			"put-bucket-tagging":                               {"AccountId", "Bucket", "Tagging"},
			"put-bucket-versioning":                            {"AccountId", "Bucket", "VersioningConfiguration"},
			"put-job-tagging":                                  {"AccountId", "JobId", "Tags"},
			"put-multi-region-access-point-policy":             {"AccountId", "ClientToken", "Details"},
			"put-public-access-block":                          {"AccountId", "PublicAccessBlockConfiguration"},
			"put-storage-lens-configuration":                   {"AccountId", "ConfigId", "StorageLensConfiguration"},
			"put-storage-lens-configuration-tagging":           {"AccountId", "ConfigId", "Tags"},
			"submit-multi-region-access-point-routes":          {"AccountId", "Mrap", "RouteUpdates"},
			"tag-resource":                                     {"AccountId", "ResourceArn", "Tags"},
			"untag-resource":                                   {"AccountId", "ResourceArn", "TagKeys"},
			"update-access-grants-location":                    {"AccessGrantsLocationId", "AccountId", "IAMRoleArn"},
			"update-job-priority":                              {"AccountId", "JobId", "Priority"},
			"update-job-status":                                {"AccountId", "JobId", "RequestedJobStatus"},
			"update-storage-lens-group":                        {"AccountId", "Name", "StorageLensGroup"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("s3control", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
