package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/chimesdkidentity/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-app-instance", "create-app-instance-admin", "create-app-instance-bot", "create-app-instance-user", "delete-app-instance", "delete-app-instance-admin", "delete-app-instance-bot", "delete-app-instance-user", "deregister-app-instance-user-endpoint", "describe-app-instance", "describe-app-instance-admin", "describe-app-instance-bot", "describe-app-instance-user", "describe-app-instance-user-endpoint", "get-app-instance-retention-settings", "list-app-instance-admins", "list-app-instance-bots", "list-app-instance-user-endpoints", "list-app-instance-users", "list-app-instances", "list-tags-for-resource", "put-app-instance-retention-settings", "put-app-instance-user-expiration-settings", "register-app-instance-user-endpoint", "tag-resource", "untag-resource", "update-app-instance", "update-app-instance-bot", "update-app-instance-user", "update-app-instance-user-endpoint"},
		OperationSet: map[string]bool{"create-app-instance": true, "create-app-instance-admin": true, "create-app-instance-bot": true, "create-app-instance-user": true, "delete-app-instance": true, "delete-app-instance-admin": true, "delete-app-instance-bot": true, "delete-app-instance-user": true, "deregister-app-instance-user-endpoint": true, "describe-app-instance": true, "describe-app-instance-admin": true, "describe-app-instance-bot": true, "describe-app-instance-user": true, "describe-app-instance-user-endpoint": true, "get-app-instance-retention-settings": true, "list-app-instance-admins": true, "list-app-instance-bots": true, "list-app-instance-user-endpoints": true, "list-app-instance-users": true, "list-app-instances": true, "list-tags-for-resource": true, "put-app-instance-retention-settings": true, "put-app-instance-user-expiration-settings": true, "register-app-instance-user-endpoint": true, "tag-resource": true, "untag-resource": true, "update-app-instance": true, "update-app-instance-bot": true, "update-app-instance-user": true, "update-app-instance-user-endpoint": true},
		OperationInputs: map[string][]string{
			"create-app-instance":                       {"ClientRequestToken", "Metadata", "Name", "Tags"},
			"create-app-instance-admin":                 {"AppInstanceAdminArn", "AppInstanceArn"},
			"create-app-instance-bot":                   {"AppInstanceArn", "ClientRequestToken", "Configuration", "Metadata", "Name", "Tags"},
			"create-app-instance-user":                  {"AppInstanceArn", "AppInstanceUserId", "ClientRequestToken", "ExpirationSettings", "Metadata", "Name", "Tags"},
			"delete-app-instance":                       {"AppInstanceArn"},
			"delete-app-instance-admin":                 {"AppInstanceAdminArn", "AppInstanceArn"},
			"delete-app-instance-bot":                   {"AppInstanceBotArn"},
			"delete-app-instance-user":                  {"AppInstanceUserArn"},
			"deregister-app-instance-user-endpoint":     {"AppInstanceUserArn", "EndpointId"},
			"describe-app-instance":                     {"AppInstanceArn"},
			"describe-app-instance-admin":               {"AppInstanceAdminArn", "AppInstanceArn"},
			"describe-app-instance-bot":                 {"AppInstanceBotArn"},
			"describe-app-instance-user":                {"AppInstanceUserArn"},
			"describe-app-instance-user-endpoint":       {"AppInstanceUserArn", "EndpointId"},
			"get-app-instance-retention-settings":       {"AppInstanceArn"},
			"list-app-instance-admins":                  {"AppInstanceArn", "MaxResults", "NextToken"},
			"list-app-instance-bots":                    {"AppInstanceArn", "MaxResults", "NextToken"},
			"list-app-instance-user-endpoints":          {"AppInstanceUserArn", "MaxResults", "NextToken"},
			"list-app-instance-users":                   {"AppInstanceArn", "MaxResults", "NextToken"},
			"list-app-instances":                        {"MaxResults", "NextToken"},
			"list-tags-for-resource":                    {"ResourceARN"},
			"put-app-instance-retention-settings":       {"AppInstanceArn", "AppInstanceRetentionSettings"},
			"put-app-instance-user-expiration-settings": {"AppInstanceUserArn", "ExpirationSettings"},
			"register-app-instance-user-endpoint":       {"AllowMessages", "AppInstanceUserArn", "ClientRequestToken", "EndpointAttributes", "Name", "ResourceArn", "Type"},
			"tag-resource":                              {"ResourceARN", "Tags"},
			"untag-resource":                            {"ResourceARN", "TagKeys"},
			"update-app-instance":                       {"AppInstanceArn", "Metadata", "Name"},
			"update-app-instance-bot":                   {"AppInstanceBotArn", "Configuration", "Metadata", "Name"},
			"update-app-instance-user":                  {"AppInstanceUserArn", "Metadata", "Name"},
			"update-app-instance-user-endpoint":         {"AllowMessages", "AppInstanceUserArn", "EndpointId", "Name"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-app-instance":                       {"ClientRequestToken": "*string", "Metadata": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"create-app-instance-admin":                 {"AppInstanceAdminArn": "*string", "AppInstanceArn": "*string"},
			"create-app-instance-bot":                   {"AppInstanceArn": "*string", "ClientRequestToken": "*string", "Configuration": "*types.Configuration", "Metadata": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"create-app-instance-user":                  {"AppInstanceArn": "*string", "AppInstanceUserId": "*string", "ClientRequestToken": "*string", "ExpirationSettings": "*types.ExpirationSettings", "Metadata": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"delete-app-instance":                       {"AppInstanceArn": "*string"},
			"delete-app-instance-admin":                 {"AppInstanceAdminArn": "*string", "AppInstanceArn": "*string"},
			"delete-app-instance-bot":                   {"AppInstanceBotArn": "*string"},
			"delete-app-instance-user":                  {"AppInstanceUserArn": "*string"},
			"deregister-app-instance-user-endpoint":     {"AppInstanceUserArn": "*string", "EndpointId": "*string"},
			"describe-app-instance":                     {"AppInstanceArn": "*string"},
			"describe-app-instance-admin":               {"AppInstanceAdminArn": "*string", "AppInstanceArn": "*string"},
			"describe-app-instance-bot":                 {"AppInstanceBotArn": "*string"},
			"describe-app-instance-user":                {"AppInstanceUserArn": "*string"},
			"describe-app-instance-user-endpoint":       {"AppInstanceUserArn": "*string", "EndpointId": "*string"},
			"get-app-instance-retention-settings":       {"AppInstanceArn": "*string"},
			"list-app-instance-admins":                  {"AppInstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-instance-bots":                    {"AppInstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-instance-user-endpoints":          {"AppInstanceUserArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-instance-users":                   {"AppInstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-instances":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                    {"ResourceARN": "*string"},
			"put-app-instance-retention-settings":       {"AppInstanceArn": "*string", "AppInstanceRetentionSettings": "*types.AppInstanceRetentionSettings"},
			"put-app-instance-user-expiration-settings": {"AppInstanceUserArn": "*string", "ExpirationSettings": "*types.ExpirationSettings"},
			"register-app-instance-user-endpoint":       {"AllowMessages": "types.AllowMessages", "AppInstanceUserArn": "*string", "ClientRequestToken": "*string", "EndpointAttributes": "*types.EndpointAttributes", "Name": "*string", "ResourceArn": "*string", "Type": "types.AppInstanceUserEndpointType"},
			"tag-resource":                              {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                            {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-app-instance":                       {"AppInstanceArn": "*string", "Metadata": "*string", "Name": "*string"},
			"update-app-instance-bot":                   {"AppInstanceBotArn": "*string", "Configuration": "*types.Configuration", "Metadata": "*string", "Name": "*string"},
			"update-app-instance-user":                  {"AppInstanceUserArn": "*string", "Metadata": "*string", "Name": "*string"},
			"update-app-instance-user-endpoint":         {"AllowMessages": "types.AllowMessages", "AppInstanceUserArn": "*string", "EndpointId": "*string", "Name": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-app-instance":                       {"ClientRequestToken", "Name"},
			"create-app-instance-admin":                 {"AppInstanceAdminArn", "AppInstanceArn"},
			"create-app-instance-bot":                   {"AppInstanceArn", "ClientRequestToken", "Configuration"},
			"create-app-instance-user":                  {"AppInstanceArn", "AppInstanceUserId", "ClientRequestToken", "Name"},
			"delete-app-instance":                       {"AppInstanceArn"},
			"delete-app-instance-admin":                 {"AppInstanceAdminArn", "AppInstanceArn"},
			"delete-app-instance-bot":                   {"AppInstanceBotArn"},
			"delete-app-instance-user":                  {"AppInstanceUserArn"},
			"deregister-app-instance-user-endpoint":     {"AppInstanceUserArn", "EndpointId"},
			"describe-app-instance":                     {"AppInstanceArn"},
			"describe-app-instance-admin":               {"AppInstanceAdminArn", "AppInstanceArn"},
			"describe-app-instance-bot":                 {"AppInstanceBotArn"},
			"describe-app-instance-user":                {"AppInstanceUserArn"},
			"describe-app-instance-user-endpoint":       {"AppInstanceUserArn", "EndpointId"},
			"get-app-instance-retention-settings":       {"AppInstanceArn"},
			"list-app-instance-admins":                  {"AppInstanceArn"},
			"list-app-instance-bots":                    {"AppInstanceArn"},
			"list-app-instance-user-endpoints":          {"AppInstanceUserArn"},
			"list-app-instance-users":                   {"AppInstanceArn"},
			"list-app-instances":                        {},
			"list-tags-for-resource":                    {"ResourceARN"},
			"put-app-instance-retention-settings":       {"AppInstanceArn", "AppInstanceRetentionSettings"},
			"put-app-instance-user-expiration-settings": {"AppInstanceUserArn"},
			"register-app-instance-user-endpoint":       {"AppInstanceUserArn", "ClientRequestToken", "EndpointAttributes", "ResourceArn", "Type"},
			"tag-resource":                              {"ResourceARN", "Tags"},
			"untag-resource":                            {"ResourceARN", "TagKeys"},
			"update-app-instance":                       {"AppInstanceArn", "Metadata", "Name"},
			"update-app-instance-bot":                   {"AppInstanceBotArn", "Metadata", "Name"},
			"update-app-instance-user":                  {"AppInstanceUserArn", "Metadata", "Name"},
			"update-app-instance-user-endpoint":         {"AppInstanceUserArn", "EndpointId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("chimesdkidentity", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
