package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/mediapackagev2/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"cancel-harvest-job", "create-channel", "create-channel-group", "create-harvest-job", "create-origin-endpoint", "delete-channel", "delete-channel-group", "delete-channel-policy", "delete-origin-endpoint", "delete-origin-endpoint-policy", "get-channel", "get-channel-group", "get-channel-policy", "get-harvest-job", "get-origin-endpoint", "get-origin-endpoint-policy", "list-channel-groups", "list-channels", "list-harvest-jobs", "list-origin-endpoints", "list-tags-for-resource", "put-channel-policy", "put-origin-endpoint-policy", "reset-channel-state", "reset-origin-endpoint-state", "tag-resource", "untag-resource", "update-channel", "update-channel-group", "update-origin-endpoint"},
		OperationSet: map[string]bool{"cancel-harvest-job": true, "create-channel": true, "create-channel-group": true, "create-harvest-job": true, "create-origin-endpoint": true, "delete-channel": true, "delete-channel-group": true, "delete-channel-policy": true, "delete-origin-endpoint": true, "delete-origin-endpoint-policy": true, "get-channel": true, "get-channel-group": true, "get-channel-policy": true, "get-harvest-job": true, "get-origin-endpoint": true, "get-origin-endpoint-policy": true, "list-channel-groups": true, "list-channels": true, "list-harvest-jobs": true, "list-origin-endpoints": true, "list-tags-for-resource": true, "put-channel-policy": true, "put-origin-endpoint-policy": true, "reset-channel-state": true, "reset-origin-endpoint-state": true, "tag-resource": true, "untag-resource": true, "update-channel": true, "update-channel-group": true, "update-origin-endpoint": true},
		OperationInputs: map[string][]string{
			"cancel-harvest-job":            {"ChannelGroupName", "ChannelName", "ETag", "HarvestJobName", "OriginEndpointName"},
			"create-channel":                {"ChannelGroupName", "ChannelName", "ClientToken", "Description", "InputSwitchConfiguration", "InputType", "OutputHeaderConfiguration", "Tags"},
			"create-channel-group":          {"ChannelGroupName", "ClientToken", "Description", "Tags"},
			"create-harvest-job":            {"ChannelGroupName", "ChannelName", "ClientToken", "Description", "Destination", "HarvestJobName", "HarvestedManifests", "OriginEndpointName", "ScheduleConfiguration", "Tags"},
			"create-origin-endpoint":        {"ChannelGroupName", "ChannelName", "ClientToken", "ContainerType", "DashManifests", "Description", "ForceEndpointErrorConfiguration", "HlsManifests", "LowLatencyHlsManifests", "MssManifests", "OriginEndpointName", "Segment", "StartoverWindowSeconds", "Tags"},
			"delete-channel":                {"ChannelGroupName", "ChannelName"},
			"delete-channel-group":          {"ChannelGroupName"},
			"delete-channel-policy":         {"ChannelGroupName", "ChannelName"},
			"delete-origin-endpoint":        {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"delete-origin-endpoint-policy": {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"get-channel":                   {"ChannelGroupName", "ChannelName"},
			"get-channel-group":             {"ChannelGroupName"},
			"get-channel-policy":            {"ChannelGroupName", "ChannelName"},
			"get-harvest-job":               {"ChannelGroupName", "ChannelName", "HarvestJobName", "OriginEndpointName"},
			"get-origin-endpoint":           {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"get-origin-endpoint-policy":    {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"list-channel-groups":           {"MaxResults", "NextToken"},
			"list-channels":                 {"ChannelGroupName", "MaxResults", "NextToken"},
			"list-harvest-jobs":             {"ChannelGroupName", "ChannelName", "MaxResults", "NextToken", "OriginEndpointName", "Status"},
			"list-origin-endpoints":         {"ChannelGroupName", "ChannelName", "MaxResults", "NextToken"},
			"list-tags-for-resource":        {"ResourceArn"},
			"put-channel-policy":            {"ChannelGroupName", "ChannelName", "Policy"},
			"put-origin-endpoint-policy":    {"CdnAuthConfiguration", "ChannelGroupName", "ChannelName", "OriginEndpointName", "Policy"},
			"reset-channel-state":           {"ChannelGroupName", "ChannelName"},
			"reset-origin-endpoint-state":   {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"tag-resource":                  {"ResourceArn", "Tags"},
			"untag-resource":                {"ResourceArn", "TagKeys"},
			"update-channel":                {"ChannelGroupName", "ChannelName", "Description", "ETag", "InputSwitchConfiguration", "OutputHeaderConfiguration"},
			"update-channel-group":          {"ChannelGroupName", "Description", "ETag"},
			"update-origin-endpoint":        {"ChannelGroupName", "ChannelName", "ContainerType", "DashManifests", "Description", "ETag", "ForceEndpointErrorConfiguration", "HlsManifests", "LowLatencyHlsManifests", "MssManifests", "OriginEndpointName", "Segment", "StartoverWindowSeconds"},
		},
		OperationInputTypes: map[string]map[string]string{
			"cancel-harvest-job":            {"ChannelGroupName": "*string", "ChannelName": "*string", "ETag": "*string", "HarvestJobName": "*string", "OriginEndpointName": "*string"},
			"create-channel":                {"ChannelGroupName": "*string", "ChannelName": "*string", "ClientToken": "*string", "Description": "*string", "InputSwitchConfiguration": "*types.InputSwitchConfiguration", "InputType": "types.InputType", "OutputHeaderConfiguration": "*types.OutputHeaderConfiguration", "Tags": "map[string]string"},
			"create-channel-group":          {"ChannelGroupName": "*string", "ClientToken": "*string", "Description": "*string", "Tags": "map[string]string"},
			"create-harvest-job":            {"ChannelGroupName": "*string", "ChannelName": "*string", "ClientToken": "*string", "Description": "*string", "Destination": "*types.Destination", "HarvestJobName": "*string", "HarvestedManifests": "*types.HarvestedManifests", "OriginEndpointName": "*string", "ScheduleConfiguration": "*types.HarvesterScheduleConfiguration", "Tags": "map[string]string"},
			"create-origin-endpoint":        {"ChannelGroupName": "*string", "ChannelName": "*string", "ClientToken": "*string", "ContainerType": "types.ContainerType", "DashManifests": "[]types.CreateDashManifestConfiguration", "Description": "*string", "ForceEndpointErrorConfiguration": "*types.ForceEndpointErrorConfiguration", "HlsManifests": "[]types.CreateHlsManifestConfiguration", "LowLatencyHlsManifests": "[]types.CreateLowLatencyHlsManifestConfiguration", "MssManifests": "[]types.CreateMssManifestConfiguration", "OriginEndpointName": "*string", "Segment": "*types.Segment", "StartoverWindowSeconds": "*int32", "Tags": "map[string]string"},
			"delete-channel":                {"ChannelGroupName": "*string", "ChannelName": "*string"},
			"delete-channel-group":          {"ChannelGroupName": "*string"},
			"delete-channel-policy":         {"ChannelGroupName": "*string", "ChannelName": "*string"},
			"delete-origin-endpoint":        {"ChannelGroupName": "*string", "ChannelName": "*string", "OriginEndpointName": "*string"},
			"delete-origin-endpoint-policy": {"ChannelGroupName": "*string", "ChannelName": "*string", "OriginEndpointName": "*string"},
			"get-channel":                   {"ChannelGroupName": "*string", "ChannelName": "*string"},
			"get-channel-group":             {"ChannelGroupName": "*string"},
			"get-channel-policy":            {"ChannelGroupName": "*string", "ChannelName": "*string"},
			"get-harvest-job":               {"ChannelGroupName": "*string", "ChannelName": "*string", "HarvestJobName": "*string", "OriginEndpointName": "*string"},
			"get-origin-endpoint":           {"ChannelGroupName": "*string", "ChannelName": "*string", "OriginEndpointName": "*string"},
			"get-origin-endpoint-policy":    {"ChannelGroupName": "*string", "ChannelName": "*string", "OriginEndpointName": "*string"},
			"list-channel-groups":           {"MaxResults": "*int32", "NextToken": "*string"},
			"list-channels":                 {"ChannelGroupName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-harvest-jobs":             {"ChannelGroupName": "*string", "ChannelName": "*string", "MaxResults": "*int32", "NextToken": "*string", "OriginEndpointName": "*string", "Status": "types.HarvestJobStatus"},
			"list-origin-endpoints":         {"ChannelGroupName": "*string", "ChannelName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":        {"ResourceArn": "*string"},
			"put-channel-policy":            {"ChannelGroupName": "*string", "ChannelName": "*string", "Policy": "*string"},
			"put-origin-endpoint-policy":    {"CdnAuthConfiguration": "*types.CdnAuthConfiguration", "ChannelGroupName": "*string", "ChannelName": "*string", "OriginEndpointName": "*string", "Policy": "*string"},
			"reset-channel-state":           {"ChannelGroupName": "*string", "ChannelName": "*string"},
			"reset-origin-endpoint-state":   {"ChannelGroupName": "*string", "ChannelName": "*string", "OriginEndpointName": "*string"},
			"tag-resource":                  {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-channel":                {"ChannelGroupName": "*string", "ChannelName": "*string", "Description": "*string", "ETag": "*string", "InputSwitchConfiguration": "*types.InputSwitchConfiguration", "OutputHeaderConfiguration": "*types.OutputHeaderConfiguration"},
			"update-channel-group":          {"ChannelGroupName": "*string", "Description": "*string", "ETag": "*string"},
			"update-origin-endpoint":        {"ChannelGroupName": "*string", "ChannelName": "*string", "ContainerType": "types.ContainerType", "DashManifests": "[]types.CreateDashManifestConfiguration", "Description": "*string", "ETag": "*string", "ForceEndpointErrorConfiguration": "*types.ForceEndpointErrorConfiguration", "HlsManifests": "[]types.CreateHlsManifestConfiguration", "LowLatencyHlsManifests": "[]types.CreateLowLatencyHlsManifestConfiguration", "MssManifests": "[]types.CreateMssManifestConfiguration", "OriginEndpointName": "*string", "Segment": "*types.Segment", "StartoverWindowSeconds": "*int32"},
		},
		OperationInputRequired: map[string][]string{
			"cancel-harvest-job":            {"ChannelGroupName", "ChannelName", "HarvestJobName", "OriginEndpointName"},
			"create-channel":                {"ChannelGroupName", "ChannelName"},
			"create-channel-group":          {"ChannelGroupName"},
			"create-harvest-job":            {"ChannelGroupName", "ChannelName", "Destination", "HarvestedManifests", "OriginEndpointName", "ScheduleConfiguration"},
			"create-origin-endpoint":        {"ChannelGroupName", "ChannelName", "ContainerType", "OriginEndpointName"},
			"delete-channel":                {"ChannelGroupName", "ChannelName"},
			"delete-channel-group":          {"ChannelGroupName"},
			"delete-channel-policy":         {"ChannelGroupName", "ChannelName"},
			"delete-origin-endpoint":        {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"delete-origin-endpoint-policy": {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"get-channel":                   {"ChannelGroupName", "ChannelName"},
			"get-channel-group":             {"ChannelGroupName"},
			"get-channel-policy":            {"ChannelGroupName", "ChannelName"},
			"get-harvest-job":               {"ChannelGroupName", "ChannelName", "HarvestJobName", "OriginEndpointName"},
			"get-origin-endpoint":           {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"get-origin-endpoint-policy":    {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"list-channel-groups":           {},
			"list-channels":                 {"ChannelGroupName"},
			"list-harvest-jobs":             {"ChannelGroupName"},
			"list-origin-endpoints":         {"ChannelGroupName", "ChannelName"},
			"list-tags-for-resource":        {"ResourceArn"},
			"put-channel-policy":            {"ChannelGroupName", "ChannelName", "Policy"},
			"put-origin-endpoint-policy":    {"ChannelGroupName", "ChannelName", "OriginEndpointName", "Policy"},
			"reset-channel-state":           {"ChannelGroupName", "ChannelName"},
			"reset-origin-endpoint-state":   {"ChannelGroupName", "ChannelName", "OriginEndpointName"},
			"tag-resource":                  {"ResourceArn", "Tags"},
			"untag-resource":                {"ResourceArn", "TagKeys"},
			"update-channel":                {"ChannelGroupName", "ChannelName"},
			"update-channel-group":          {"ChannelGroupName"},
			"update-origin-endpoint":        {"ChannelGroupName", "ChannelName", "ContainerType", "OriginEndpointName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("mediapackagev2", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
