package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/opensearch/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-inbound-connection", "add-data-source", "add-direct-query-data-source", "add-tags", "associate-package", "associate-packages", "authorize-vpc-endpoint-access", "cancel-domain-config-change", "cancel-service-software-update", "create-application", "create-domain", "create-index", "create-outbound-connection", "create-package", "create-vpc-endpoint", "delete-application", "delete-data-source", "delete-direct-query-data-source", "delete-domain", "delete-inbound-connection", "delete-index", "delete-outbound-connection", "delete-package", "delete-vpc-endpoint", "describe-domain", "describe-domain-auto-tunes", "describe-domain-change-progress", "describe-domain-config", "describe-domain-health", "describe-domain-nodes", "describe-domains", "describe-dry-run-progress", "describe-inbound-connections", "describe-instance-type-limits", "describe-outbound-connections", "describe-packages", "describe-reserved-instance-offerings", "describe-reserved-instances", "describe-vpc-endpoints", "dissociate-package", "dissociate-packages", "get-application", "get-compatible-versions", "get-data-source", "get-default-application-setting", "get-direct-query-data-source", "get-domain-maintenance-status", "get-index", "get-package-version-history", "get-upgrade-history", "get-upgrade-status", "list-applications", "list-data-sources", "list-direct-query-data-sources", "list-domain-maintenances", "list-domain-names", "list-domains-for-package", "list-instance-type-details", "list-packages-for-domain", "list-scheduled-actions", "list-tags", "list-versions", "list-vpc-endpoint-access", "list-vpc-endpoints", "list-vpc-endpoints-for-domain", "purchase-reserved-instance-offering", "put-default-application-setting", "reject-inbound-connection", "remove-tags", "revoke-vpc-endpoint-access", "start-domain-maintenance", "start-service-software-update", "update-application", "update-data-source", "update-direct-query-data-source", "update-domain-config", "update-index", "update-package", "update-package-scope", "update-scheduled-action", "update-vpc-endpoint", "upgrade-domain"},
		OperationSet: map[string]bool{"accept-inbound-connection": true, "add-data-source": true, "add-direct-query-data-source": true, "add-tags": true, "associate-package": true, "associate-packages": true, "authorize-vpc-endpoint-access": true, "cancel-domain-config-change": true, "cancel-service-software-update": true, "create-application": true, "create-domain": true, "create-index": true, "create-outbound-connection": true, "create-package": true, "create-vpc-endpoint": true, "delete-application": true, "delete-data-source": true, "delete-direct-query-data-source": true, "delete-domain": true, "delete-inbound-connection": true, "delete-index": true, "delete-outbound-connection": true, "delete-package": true, "delete-vpc-endpoint": true, "describe-domain": true, "describe-domain-auto-tunes": true, "describe-domain-change-progress": true, "describe-domain-config": true, "describe-domain-health": true, "describe-domain-nodes": true, "describe-domains": true, "describe-dry-run-progress": true, "describe-inbound-connections": true, "describe-instance-type-limits": true, "describe-outbound-connections": true, "describe-packages": true, "describe-reserved-instance-offerings": true, "describe-reserved-instances": true, "describe-vpc-endpoints": true, "dissociate-package": true, "dissociate-packages": true, "get-application": true, "get-compatible-versions": true, "get-data-source": true, "get-default-application-setting": true, "get-direct-query-data-source": true, "get-domain-maintenance-status": true, "get-index": true, "get-package-version-history": true, "get-upgrade-history": true, "get-upgrade-status": true, "list-applications": true, "list-data-sources": true, "list-direct-query-data-sources": true, "list-domain-maintenances": true, "list-domain-names": true, "list-domains-for-package": true, "list-instance-type-details": true, "list-packages-for-domain": true, "list-scheduled-actions": true, "list-tags": true, "list-versions": true, "list-vpc-endpoint-access": true, "list-vpc-endpoints": true, "list-vpc-endpoints-for-domain": true, "purchase-reserved-instance-offering": true, "put-default-application-setting": true, "reject-inbound-connection": true, "remove-tags": true, "revoke-vpc-endpoint-access": true, "start-domain-maintenance": true, "start-service-software-update": true, "update-application": true, "update-data-source": true, "update-direct-query-data-source": true, "update-domain-config": true, "update-index": true, "update-package": true, "update-package-scope": true, "update-scheduled-action": true, "update-vpc-endpoint": true, "upgrade-domain": true},
		OperationInputs: map[string][]string{
			"accept-inbound-connection":            {"ConnectionId"},
			"add-data-source":                      {"DataSourceType", "Description", "DomainName", "Name"},
			"add-direct-query-data-source":         {"DataSourceName", "DataSourceType", "Description", "OpenSearchArns", "TagList"},
			"add-tags":                             {"ARN", "TagList"},
			"associate-package":                    {"AssociationConfiguration", "DomainName", "PackageID", "PrerequisitePackageIDList"},
			"associate-packages":                   {"DomainName", "PackageList"},
			"authorize-vpc-endpoint-access":        {"Account", "DomainName", "Service"},
			"cancel-domain-config-change":          {"DomainName", "DryRun"},
			"cancel-service-software-update":       {"DomainName"},
			"create-application":                   {"AppConfigs", "ClientToken", "DataSources", "IamIdentityCenterOptions", "KmsKeyArn", "Name", "TagList"},
			"create-domain":                        {"AIMLOptions", "AccessPolicies", "AdvancedOptions", "AdvancedSecurityOptions", "AutoTuneOptions", "ClusterConfig", "CognitoOptions", "DomainEndpointOptions", "DomainName", "EBSOptions", "EncryptionAtRestOptions", "EngineVersion", "IPAddressType", "IdentityCenterOptions", "LogPublishingOptions", "NodeToNodeEncryptionOptions", "OffPeakWindowOptions", "SnapshotOptions", "SoftwareUpdateOptions", "TagList", "VPCOptions"},
			"create-index":                         {"DomainName", "IndexName", "IndexSchema"},
			"create-outbound-connection":           {"ConnectionAlias", "ConnectionMode", "ConnectionProperties", "LocalDomainInfo", "RemoteDomainInfo"},
			"create-package":                       {"EngineVersion", "PackageConfiguration", "PackageDescription", "PackageEncryptionOptions", "PackageName", "PackageSource", "PackageType", "PackageVendingOptions"},
			"create-vpc-endpoint":                  {"ClientToken", "DomainArn", "VpcOptions"},
			"delete-application":                   {"Id"},
			"delete-data-source":                   {"DomainName", "Name"},
			"delete-direct-query-data-source":      {"DataSourceName"},
			"delete-domain":                        {"DomainName"},
			"delete-inbound-connection":            {"ConnectionId"},
			"delete-index":                         {"DomainName", "IndexName"},
			"delete-outbound-connection":           {"ConnectionId"},
			"delete-package":                       {"PackageID"},
			"delete-vpc-endpoint":                  {"VpcEndpointId"},
			"describe-domain":                      {"DomainName"},
			"describe-domain-auto-tunes":           {"DomainName", "MaxResults", "NextToken"},
			"describe-domain-change-progress":      {"ChangeId", "DomainName"},
			"describe-domain-config":               {"DomainName"},
			"describe-domain-health":               {"DomainName"},
			"describe-domain-nodes":                {"DomainName"},
			"describe-domains":                     {"DomainNames"},
			"describe-dry-run-progress":            {"DomainName", "DryRunId", "LoadDryRunConfig"},
			"describe-inbound-connections":         {"Filters", "MaxResults", "NextToken"},
			"describe-instance-type-limits":        {"DomainName", "EngineVersion", "InstanceType"},
			"describe-outbound-connections":        {"Filters", "MaxResults", "NextToken"},
			"describe-packages":                    {"Filters", "MaxResults", "NextToken"},
			"describe-reserved-instance-offerings": {"MaxResults", "NextToken", "ReservedInstanceOfferingId"},
			"describe-reserved-instances":          {"MaxResults", "NextToken", "ReservedInstanceId"},
			"describe-vpc-endpoints":               {"VpcEndpointIds"},
			"dissociate-package":                   {"DomainName", "PackageID"},
			"dissociate-packages":                  {"DomainName", "PackageList"},
			"get-application":                      {"Id"},
			"get-compatible-versions":              {"DomainName"},
			"get-data-source":                      {"DomainName", "Name"},
			"get-default-application-setting":      {},
			"get-direct-query-data-source":         {"DataSourceName"},
			"get-domain-maintenance-status":        {"DomainName", "MaintenanceId"},
			"get-index":                            {"DomainName", "IndexName"},
			"get-package-version-history":          {"MaxResults", "NextToken", "PackageID"},
			"get-upgrade-history":                  {"DomainName", "MaxResults", "NextToken"},
			"get-upgrade-status":                   {"DomainName"},
			"list-applications":                    {"MaxResults", "NextToken", "Statuses"},
			"list-data-sources":                    {"DomainName"},
			"list-direct-query-data-sources":       {"NextToken"},
			"list-domain-maintenances":             {"Action", "DomainName", "MaxResults", "NextToken", "Status"},
			"list-domain-names":                    {"EngineType"},
			"list-domains-for-package":             {"MaxResults", "NextToken", "PackageID"},
			"list-instance-type-details":           {"DomainName", "EngineVersion", "InstanceType", "MaxResults", "NextToken", "RetrieveAZs"},
			"list-packages-for-domain":             {"DomainName", "MaxResults", "NextToken"},
			"list-scheduled-actions":               {"DomainName", "MaxResults", "NextToken"},
			"list-tags":                            {"ARN"},
			"list-versions":                        {"MaxResults", "NextToken"},
			"list-vpc-endpoint-access":             {"DomainName", "NextToken"},
			"list-vpc-endpoints":                   {"NextToken"},
			"list-vpc-endpoints-for-domain":        {"DomainName", "NextToken"},
			"purchase-reserved-instance-offering":  {"InstanceCount", "ReservationName", "ReservedInstanceOfferingId"},
			"put-default-application-setting":      {"ApplicationArn", "SetAsDefault"},
			"reject-inbound-connection":            {"ConnectionId"},
			"remove-tags":                          {"ARN", "TagKeys"},
			"revoke-vpc-endpoint-access":           {"Account", "DomainName", "Service"},
			"start-domain-maintenance":             {"Action", "DomainName", "NodeId"},
			"start-service-software-update":        {"DesiredStartTime", "DomainName", "ScheduleAt"},
			"update-application":                   {"AppConfigs", "DataSources", "Id"},
			"update-data-source":                   {"DataSourceType", "Description", "DomainName", "Name", "Status"},
			"update-direct-query-data-source":      {"DataSourceName", "DataSourceType", "Description", "OpenSearchArns"},
			"update-domain-config":                 {"AIMLOptions", "AccessPolicies", "AdvancedOptions", "AdvancedSecurityOptions", "AutoTuneOptions", "ClusterConfig", "CognitoOptions", "DomainEndpointOptions", "DomainName", "DryRun", "DryRunMode", "EBSOptions", "EncryptionAtRestOptions", "IPAddressType", "IdentityCenterOptions", "LogPublishingOptions", "NodeToNodeEncryptionOptions", "OffPeakWindowOptions", "SnapshotOptions", "SoftwareUpdateOptions", "VPCOptions"},
			"update-index":                         {"DomainName", "IndexName", "IndexSchema"},
			"update-package":                       {"CommitMessage", "PackageConfiguration", "PackageDescription", "PackageEncryptionOptions", "PackageID", "PackageSource"},
			"update-package-scope":                 {"Operation", "PackageID", "PackageUserList"},
			"update-scheduled-action":              {"ActionID", "ActionType", "DesiredStartTime", "DomainName", "ScheduleAt"},
			"update-vpc-endpoint":                  {"VpcEndpointId", "VpcOptions"},
			"upgrade-domain":                       {"AdvancedOptions", "DomainName", "PerformCheckOnly", "TargetVersion"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-inbound-connection":            {"ConnectionId": "*string"},
			"add-data-source":                      {"DataSourceType": "types.DataSourceType", "Description": "*string", "DomainName": "*string", "Name": "*string"},
			"add-direct-query-data-source":         {"DataSourceName": "*string", "DataSourceType": "types.DirectQueryDataSourceType", "Description": "*string", "OpenSearchArns": "[]string", "TagList": "[]types.Tag"},
			"add-tags":                             {"ARN": "*string", "TagList": "[]types.Tag"},
			"associate-package":                    {"AssociationConfiguration": "*types.PackageAssociationConfiguration", "DomainName": "*string", "PackageID": "*string", "PrerequisitePackageIDList": "[]string"},
			"associate-packages":                   {"DomainName": "*string", "PackageList": "[]types.PackageDetailsForAssociation"},
			"authorize-vpc-endpoint-access":        {"Account": "*string", "DomainName": "*string", "Service": "types.AWSServicePrincipal"},
			"cancel-domain-config-change":          {"DomainName": "*string", "DryRun": "*bool"},
			"cancel-service-software-update":       {"DomainName": "*string"},
			"create-application":                   {"AppConfigs": "[]types.AppConfig", "ClientToken": "*string", "DataSources": "[]types.DataSource", "IamIdentityCenterOptions": "*types.IamIdentityCenterOptionsInput", "KmsKeyArn": "*string", "Name": "*string", "TagList": "[]types.Tag"},
			"create-domain":                        {"AIMLOptions": "*types.AIMLOptionsInput", "AccessPolicies": "*string", "AdvancedOptions": "map[string]string", "AdvancedSecurityOptions": "*types.AdvancedSecurityOptionsInput", "AutoTuneOptions": "*types.AutoTuneOptionsInput", "ClusterConfig": "*types.ClusterConfig", "CognitoOptions": "*types.CognitoOptions", "DomainEndpointOptions": "*types.DomainEndpointOptions", "DomainName": "*string", "EBSOptions": "*types.EBSOptions", "EncryptionAtRestOptions": "*types.EncryptionAtRestOptions", "EngineVersion": "*string", "IPAddressType": "types.IPAddressType", "IdentityCenterOptions": "*types.IdentityCenterOptionsInput", "LogPublishingOptions": "map[string]types.LogPublishingOption", "NodeToNodeEncryptionOptions": "*types.NodeToNodeEncryptionOptions", "OffPeakWindowOptions": "*types.OffPeakWindowOptions", "SnapshotOptions": "*types.SnapshotOptions", "SoftwareUpdateOptions": "*types.SoftwareUpdateOptions", "TagList": "[]types.Tag", "VPCOptions": "*types.VPCOptions"},
			"create-index":                         {"DomainName": "*string", "IndexName": "*string", "IndexSchema": "document.Interface"},
			"create-outbound-connection":           {"ConnectionAlias": "*string", "ConnectionMode": "types.ConnectionMode", "ConnectionProperties": "*types.ConnectionProperties", "LocalDomainInfo": "*types.DomainInformationContainer", "RemoteDomainInfo": "*types.DomainInformationContainer"},
			"create-package":                       {"EngineVersion": "*string", "PackageConfiguration": "*types.PackageConfiguration", "PackageDescription": "*string", "PackageEncryptionOptions": "*types.PackageEncryptionOptions", "PackageName": "*string", "PackageSource": "*types.PackageSource", "PackageType": "types.PackageType", "PackageVendingOptions": "*types.PackageVendingOptions"},
			"create-vpc-endpoint":                  {"ClientToken": "*string", "DomainArn": "*string", "VpcOptions": "*types.VPCOptions"},
			"delete-application":                   {"Id": "*string"},
			"delete-data-source":                   {"DomainName": "*string", "Name": "*string"},
			"delete-direct-query-data-source":      {"DataSourceName": "*string"},
			"delete-domain":                        {"DomainName": "*string"},
			"delete-inbound-connection":            {"ConnectionId": "*string"},
			"delete-index":                         {"DomainName": "*string", "IndexName": "*string"},
			"delete-outbound-connection":           {"ConnectionId": "*string"},
			"delete-package":                       {"PackageID": "*string"},
			"delete-vpc-endpoint":                  {"VpcEndpointId": "*string"},
			"describe-domain":                      {"DomainName": "*string"},
			"describe-domain-auto-tunes":           {"DomainName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"describe-domain-change-progress":      {"ChangeId": "*string", "DomainName": "*string"},
			"describe-domain-config":               {"DomainName": "*string"},
			"describe-domain-health":               {"DomainName": "*string"},
			"describe-domain-nodes":                {"DomainName": "*string"},
			"describe-domains":                     {"DomainNames": "[]string"},
			"describe-dry-run-progress":            {"DomainName": "*string", "DryRunId": "*string", "LoadDryRunConfig": "*bool"},
			"describe-inbound-connections":         {"Filters": "[]types.Filter", "MaxResults": "int32", "NextToken": "*string"},
			"describe-instance-type-limits":        {"DomainName": "*string", "EngineVersion": "*string", "InstanceType": "types.OpenSearchPartitionInstanceType"},
			"describe-outbound-connections":        {"Filters": "[]types.Filter", "MaxResults": "int32", "NextToken": "*string"},
			"describe-packages":                    {"Filters": "[]types.DescribePackagesFilter", "MaxResults": "int32", "NextToken": "*string"},
			"describe-reserved-instance-offerings": {"MaxResults": "int32", "NextToken": "*string", "ReservedInstanceOfferingId": "*string"},
			"describe-reserved-instances":          {"MaxResults": "int32", "NextToken": "*string", "ReservedInstanceId": "*string"},
			"describe-vpc-endpoints":               {"VpcEndpointIds": "[]string"},
			"dissociate-package":                   {"DomainName": "*string", "PackageID": "*string"},
			"dissociate-packages":                  {"DomainName": "*string", "PackageList": "[]string"},
			"get-application":                      {"Id": "*string"},
			"get-compatible-versions":              {"DomainName": "*string"},
			"get-data-source":                      {"DomainName": "*string", "Name": "*string"},
			"get-default-application-setting":      {},
			"get-direct-query-data-source":         {"DataSourceName": "*string"},
			"get-domain-maintenance-status":        {"DomainName": "*string", "MaintenanceId": "*string"},
			"get-index":                            {"DomainName": "*string", "IndexName": "*string"},
			"get-package-version-history":          {"MaxResults": "int32", "NextToken": "*string", "PackageID": "*string"},
			"get-upgrade-history":                  {"DomainName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"get-upgrade-status":                   {"DomainName": "*string"},
			"list-applications":                    {"MaxResults": "int32", "NextToken": "*string", "Statuses": "[]types.ApplicationStatus"},
			"list-data-sources":                    {"DomainName": "*string"},
			"list-direct-query-data-sources":       {"NextToken": "*string"},
			"list-domain-maintenances":             {"Action": "types.MaintenanceType", "DomainName": "*string", "MaxResults": "int32", "NextToken": "*string", "Status": "types.MaintenanceStatus"},
			"list-domain-names":                    {"EngineType": "types.EngineType"},
			"list-domains-for-package":             {"MaxResults": "int32", "NextToken": "*string", "PackageID": "*string"},
			"list-instance-type-details":           {"DomainName": "*string", "EngineVersion": "*string", "InstanceType": "*string", "MaxResults": "int32", "NextToken": "*string", "RetrieveAZs": "*bool"},
			"list-packages-for-domain":             {"DomainName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-scheduled-actions":               {"DomainName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-tags":                            {"ARN": "*string"},
			"list-versions":                        {"MaxResults": "int32", "NextToken": "*string"},
			"list-vpc-endpoint-access":             {"DomainName": "*string", "NextToken": "*string"},
			"list-vpc-endpoints":                   {"NextToken": "*string"},
			"list-vpc-endpoints-for-domain":        {"DomainName": "*string", "NextToken": "*string"},
			"purchase-reserved-instance-offering":  {"InstanceCount": "*int32", "ReservationName": "*string", "ReservedInstanceOfferingId": "*string"},
			"put-default-application-setting":      {"ApplicationArn": "*string", "SetAsDefault": "*bool"},
			"reject-inbound-connection":            {"ConnectionId": "*string"},
			"remove-tags":                          {"ARN": "*string", "TagKeys": "[]string"},
			"revoke-vpc-endpoint-access":           {"Account": "*string", "DomainName": "*string", "Service": "types.AWSServicePrincipal"},
			"start-domain-maintenance":             {"Action": "types.MaintenanceType", "DomainName": "*string", "NodeId": "*string"},
			"start-service-software-update":        {"DesiredStartTime": "*int64", "DomainName": "*string", "ScheduleAt": "types.ScheduleAt"},
			"update-application":                   {"AppConfigs": "[]types.AppConfig", "DataSources": "[]types.DataSource", "Id": "*string"},
			"update-data-source":                   {"DataSourceType": "types.DataSourceType", "Description": "*string", "DomainName": "*string", "Name": "*string", "Status": "types.DataSourceStatus"},
			"update-direct-query-data-source":      {"DataSourceName": "*string", "DataSourceType": "types.DirectQueryDataSourceType", "Description": "*string", "OpenSearchArns": "[]string"},
			"update-domain-config":                 {"AIMLOptions": "*types.AIMLOptionsInput", "AccessPolicies": "*string", "AdvancedOptions": "map[string]string", "AdvancedSecurityOptions": "*types.AdvancedSecurityOptionsInput", "AutoTuneOptions": "*types.AutoTuneOptions", "ClusterConfig": "*types.ClusterConfig", "CognitoOptions": "*types.CognitoOptions", "DomainEndpointOptions": "*types.DomainEndpointOptions", "DomainName": "*string", "DryRun": "*bool", "DryRunMode": "types.DryRunMode", "EBSOptions": "*types.EBSOptions", "EncryptionAtRestOptions": "*types.EncryptionAtRestOptions", "IPAddressType": "types.IPAddressType", "IdentityCenterOptions": "*types.IdentityCenterOptionsInput", "LogPublishingOptions": "map[string]types.LogPublishingOption", "NodeToNodeEncryptionOptions": "*types.NodeToNodeEncryptionOptions", "OffPeakWindowOptions": "*types.OffPeakWindowOptions", "SnapshotOptions": "*types.SnapshotOptions", "SoftwareUpdateOptions": "*types.SoftwareUpdateOptions", "VPCOptions": "*types.VPCOptions"},
			"update-index":                         {"DomainName": "*string", "IndexName": "*string", "IndexSchema": "document.Interface"},
			"update-package":                       {"CommitMessage": "*string", "PackageConfiguration": "*types.PackageConfiguration", "PackageDescription": "*string", "PackageEncryptionOptions": "*types.PackageEncryptionOptions", "PackageID": "*string", "PackageSource": "*types.PackageSource"},
			"update-package-scope":                 {"Operation": "types.PackageScopeOperationEnum", "PackageID": "*string", "PackageUserList": "[]string"},
			"update-scheduled-action":              {"ActionID": "*string", "ActionType": "types.ActionType", "DesiredStartTime": "*int64", "DomainName": "*string", "ScheduleAt": "types.ScheduleAt"},
			"update-vpc-endpoint":                  {"VpcEndpointId": "*string", "VpcOptions": "*types.VPCOptions"},
			"upgrade-domain":                       {"AdvancedOptions": "map[string]string", "DomainName": "*string", "PerformCheckOnly": "*bool", "TargetVersion": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-inbound-connection":            {"ConnectionId"},
			"add-data-source":                      {"DataSourceType", "DomainName", "Name"},
			"add-direct-query-data-source":         {"DataSourceName", "DataSourceType", "OpenSearchArns"},
			"add-tags":                             {"ARN", "TagList"},
			"associate-package":                    {"DomainName", "PackageID"},
			"associate-packages":                   {"DomainName", "PackageList"},
			"authorize-vpc-endpoint-access":        {"DomainName"},
			"cancel-domain-config-change":          {"DomainName"},
			"cancel-service-software-update":       {"DomainName"},
			"create-application":                   {"Name"},
			"create-domain":                        {"DomainName"},
			"create-index":                         {"DomainName", "IndexName", "IndexSchema"},
			"create-outbound-connection":           {"ConnectionAlias", "LocalDomainInfo", "RemoteDomainInfo"},
			"create-package":                       {"PackageName", "PackageSource", "PackageType"},
			"create-vpc-endpoint":                  {"DomainArn", "VpcOptions"},
			"delete-application":                   {"Id"},
			"delete-data-source":                   {"DomainName", "Name"},
			"delete-direct-query-data-source":      {"DataSourceName"},
			"delete-domain":                        {"DomainName"},
			"delete-inbound-connection":            {"ConnectionId"},
			"delete-index":                         {"DomainName", "IndexName"},
			"delete-outbound-connection":           {"ConnectionId"},
			"delete-package":                       {"PackageID"},
			"delete-vpc-endpoint":                  {"VpcEndpointId"},
			"describe-domain":                      {"DomainName"},
			"describe-domain-auto-tunes":           {"DomainName"},
			"describe-domain-change-progress":      {"DomainName"},
			"describe-domain-config":               {"DomainName"},
			"describe-domain-health":               {"DomainName"},
			"describe-domain-nodes":                {"DomainName"},
			"describe-domains":                     {"DomainNames"},
			"describe-dry-run-progress":            {"DomainName"},
			"describe-inbound-connections":         {},
			"describe-instance-type-limits":        {"EngineVersion", "InstanceType"},
			"describe-outbound-connections":        {},
			"describe-packages":                    {},
			"describe-reserved-instance-offerings": {},
			"describe-reserved-instances":          {},
			"describe-vpc-endpoints":               {"VpcEndpointIds"},
			"dissociate-package":                   {"DomainName", "PackageID"},
			"dissociate-packages":                  {"DomainName", "PackageList"},
			"get-application":                      {"Id"},
			"get-compatible-versions":              {},
			"get-data-source":                      {"DomainName", "Name"},
			"get-default-application-setting":      {},
			"get-direct-query-data-source":         {"DataSourceName"},
			"get-domain-maintenance-status":        {"DomainName", "MaintenanceId"},
			"get-index":                            {"DomainName", "IndexName"},
			"get-package-version-history":          {"PackageID"},
			"get-upgrade-history":                  {"DomainName"},
			"get-upgrade-status":                   {"DomainName"},
			"list-applications":                    {},
			"list-data-sources":                    {"DomainName"},
			"list-direct-query-data-sources":       {},
			"list-domain-maintenances":             {"DomainName"},
			"list-domain-names":                    {},
			"list-domains-for-package":             {"PackageID"},
			"list-instance-type-details":           {"EngineVersion"},
			"list-packages-for-domain":             {"DomainName"},
			"list-scheduled-actions":               {"DomainName"},
			"list-tags":                            {"ARN"},
			"list-versions":                        {},
			"list-vpc-endpoint-access":             {"DomainName"},
			"list-vpc-endpoints":                   {},
			"list-vpc-endpoints-for-domain":        {"DomainName"},
			"purchase-reserved-instance-offering":  {"ReservationName", "ReservedInstanceOfferingId"},
			"put-default-application-setting":      {"ApplicationArn", "SetAsDefault"},
			"reject-inbound-connection":            {"ConnectionId"},
			"remove-tags":                          {"ARN", "TagKeys"},
			"revoke-vpc-endpoint-access":           {"DomainName"},
			"start-domain-maintenance":             {"Action", "DomainName"},
			"start-service-software-update":        {"DomainName"},
			"update-application":                   {"Id"},
			"update-data-source":                   {"DataSourceType", "DomainName", "Name"},
			"update-direct-query-data-source":      {"DataSourceName", "DataSourceType", "OpenSearchArns"},
			"update-domain-config":                 {"DomainName"},
			"update-index":                         {"DomainName", "IndexName", "IndexSchema"},
			"update-package":                       {"PackageID", "PackageSource"},
			"update-package-scope":                 {"Operation", "PackageID", "PackageUserList"},
			"update-scheduled-action":              {"ActionID", "ActionType", "DomainName", "ScheduleAt"},
			"update-vpc-endpoint":                  {"VpcEndpointId", "VpcOptions"},
			"upgrade-domain":                       {"DomainName", "TargetVersion"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("opensearch", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
