package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/auditmanager/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-assessment-report-evidence-folder", "batch-associate-assessment-report-evidence", "batch-create-delegation-by-assessment", "batch-delete-delegation-by-assessment", "batch-disassociate-assessment-report-evidence", "batch-import-evidence-to-assessment-control", "create-assessment", "create-assessment-framework", "create-assessment-report", "create-control", "delete-assessment", "delete-assessment-framework", "delete-assessment-framework-share", "delete-assessment-report", "delete-control", "deregister-account", "deregister-organization-admin-account", "disassociate-assessment-report-evidence-folder", "get-account-status", "get-assessment", "get-assessment-framework", "get-assessment-report-url", "get-change-logs", "get-control", "get-delegations", "get-evidence", "get-evidence-by-evidence-folder", "get-evidence-file-upload-url", "get-evidence-folder", "get-evidence-folders-by-assessment", "get-evidence-folders-by-assessment-control", "get-insights", "get-insights-by-assessment", "get-organization-admin-account", "get-services-in-scope", "get-settings", "list-assessment-control-insights-by-control-domain", "list-assessment-framework-share-requests", "list-assessment-frameworks", "list-assessment-reports", "list-assessments", "list-control-domain-insights", "list-control-domain-insights-by-assessment", "list-control-insights-by-control-domain", "list-controls", "list-keywords-for-data-source", "list-notifications", "list-tags-for-resource", "register-account", "register-organization-admin-account", "start-assessment-framework-share", "tag-resource", "untag-resource", "update-assessment", "update-assessment-control", "update-assessment-control-set-status", "update-assessment-framework", "update-assessment-framework-share", "update-assessment-status", "update-control", "update-settings", "validate-assessment-report-integrity"},
		OperationSet: map[string]bool{"associate-assessment-report-evidence-folder": true, "batch-associate-assessment-report-evidence": true, "batch-create-delegation-by-assessment": true, "batch-delete-delegation-by-assessment": true, "batch-disassociate-assessment-report-evidence": true, "batch-import-evidence-to-assessment-control": true, "create-assessment": true, "create-assessment-framework": true, "create-assessment-report": true, "create-control": true, "delete-assessment": true, "delete-assessment-framework": true, "delete-assessment-framework-share": true, "delete-assessment-report": true, "delete-control": true, "deregister-account": true, "deregister-organization-admin-account": true, "disassociate-assessment-report-evidence-folder": true, "get-account-status": true, "get-assessment": true, "get-assessment-framework": true, "get-assessment-report-url": true, "get-change-logs": true, "get-control": true, "get-delegations": true, "get-evidence": true, "get-evidence-by-evidence-folder": true, "get-evidence-file-upload-url": true, "get-evidence-folder": true, "get-evidence-folders-by-assessment": true, "get-evidence-folders-by-assessment-control": true, "get-insights": true, "get-insights-by-assessment": true, "get-organization-admin-account": true, "get-services-in-scope": true, "get-settings": true, "list-assessment-control-insights-by-control-domain": true, "list-assessment-framework-share-requests": true, "list-assessment-frameworks": true, "list-assessment-reports": true, "list-assessments": true, "list-control-domain-insights": true, "list-control-domain-insights-by-assessment": true, "list-control-insights-by-control-domain": true, "list-controls": true, "list-keywords-for-data-source": true, "list-notifications": true, "list-tags-for-resource": true, "register-account": true, "register-organization-admin-account": true, "start-assessment-framework-share": true, "tag-resource": true, "untag-resource": true, "update-assessment": true, "update-assessment-control": true, "update-assessment-control-set-status": true, "update-assessment-framework": true, "update-assessment-framework-share": true, "update-assessment-status": true, "update-control": true, "update-settings": true, "validate-assessment-report-integrity": true},
		OperationInputs: map[string][]string{
			"associate-assessment-report-evidence-folder":        {"AssessmentId", "EvidenceFolderId"},
			"batch-associate-assessment-report-evidence":         {"AssessmentId", "EvidenceFolderId", "EvidenceIds"},
			"batch-create-delegation-by-assessment":              {"AssessmentId", "CreateDelegationRequests"},
			"batch-delete-delegation-by-assessment":              {"AssessmentId", "DelegationIds"},
			"batch-disassociate-assessment-report-evidence":      {"AssessmentId", "EvidenceFolderId", "EvidenceIds"},
			"batch-import-evidence-to-assessment-control":        {"AssessmentId", "ControlId", "ControlSetId", "ManualEvidence"},
			"create-assessment":                                  {"AssessmentReportsDestination", "Description", "FrameworkId", "Name", "Roles", "Scope", "Tags"},
			"create-assessment-framework":                        {"ComplianceType", "ControlSets", "Description", "Name", "Tags"},
			"create-assessment-report":                           {"AssessmentId", "Description", "Name", "QueryStatement"},
			"create-control":                                     {"ActionPlanInstructions", "ActionPlanTitle", "ControlMappingSources", "Description", "Name", "Tags", "TestingInformation"},
			"delete-assessment":                                  {"AssessmentId"},
			"delete-assessment-framework":                        {"FrameworkId"},
			"delete-assessment-framework-share":                  {"RequestId", "RequestType"},
			"delete-assessment-report":                           {"AssessmentId", "AssessmentReportId"},
			"delete-control":                                     {"ControlId"},
			"deregister-account":                                 {},
			"deregister-organization-admin-account":              {"AdminAccountId"},
			"disassociate-assessment-report-evidence-folder":     {"AssessmentId", "EvidenceFolderId"},
			"get-account-status":                                 {},
			"get-assessment":                                     {"AssessmentId"},
			"get-assessment-framework":                           {"FrameworkId"},
			"get-assessment-report-url":                          {"AssessmentId", "AssessmentReportId"},
			"get-change-logs":                                    {"AssessmentId", "ControlId", "ControlSetId", "MaxResults", "NextToken"},
			"get-control":                                        {"ControlId"},
			"get-delegations":                                    {"MaxResults", "NextToken"},
			"get-evidence":                                       {"AssessmentId", "ControlSetId", "EvidenceFolderId", "EvidenceId"},
			"get-evidence-by-evidence-folder":                    {"AssessmentId", "ControlSetId", "EvidenceFolderId", "MaxResults", "NextToken"},
			"get-evidence-file-upload-url":                       {"FileName"},
			"get-evidence-folder":                                {"AssessmentId", "ControlSetId", "EvidenceFolderId"},
			"get-evidence-folders-by-assessment":                 {"AssessmentId", "MaxResults", "NextToken"},
			"get-evidence-folders-by-assessment-control":         {"AssessmentId", "ControlId", "ControlSetId", "MaxResults", "NextToken"},
			"get-insights":                                       {},
			"get-insights-by-assessment":                         {"AssessmentId"},
			"get-organization-admin-account":                     {},
			"get-services-in-scope":                              {},
			"get-settings":                                       {"Attribute"},
			"list-assessment-control-insights-by-control-domain": {"AssessmentId", "ControlDomainId", "MaxResults", "NextToken"},
			"list-assessment-framework-share-requests":           {"MaxResults", "NextToken", "RequestType"},
			"list-assessment-frameworks":                         {"FrameworkType", "MaxResults", "NextToken"},
			"list-assessment-reports":                            {"MaxResults", "NextToken"},
			"list-assessments":                                   {"MaxResults", "NextToken", "Status"},
			"list-control-domain-insights":                       {"MaxResults", "NextToken"},
			"list-control-domain-insights-by-assessment":         {"AssessmentId", "MaxResults", "NextToken"},
			"list-control-insights-by-control-domain":            {"ControlDomainId", "MaxResults", "NextToken"},
			"list-controls":                                      {"ControlCatalogId", "ControlType", "MaxResults", "NextToken"},
			"list-keywords-for-data-source":                      {"MaxResults", "NextToken", "Source"},
			"list-notifications":                                 {"MaxResults", "NextToken"},
			"list-tags-for-resource":                             {"ResourceArn"},
			"register-account":                                   {"DelegatedAdminAccount", "KmsKey"},
			"register-organization-admin-account":                {"AdminAccountId"},
			"start-assessment-framework-share":                   {"Comment", "DestinationAccount", "DestinationRegion", "FrameworkId"},
			"tag-resource":                                       {"ResourceArn", "Tags"},
			"untag-resource":                                     {"ResourceArn", "TagKeys"},
			"update-assessment":                                  {"AssessmentDescription", "AssessmentId", "AssessmentName", "AssessmentReportsDestination", "Roles", "Scope"},
			"update-assessment-control":                          {"AssessmentId", "CommentBody", "ControlId", "ControlSetId", "ControlStatus"},
			"update-assessment-control-set-status":               {"AssessmentId", "Comment", "ControlSetId", "Status"},
			"update-assessment-framework":                        {"ComplianceType", "ControlSets", "Description", "FrameworkId", "Name"},
			"update-assessment-framework-share":                  {"Action", "RequestId", "RequestType"},
			"update-assessment-status":                           {"AssessmentId", "Status"},
			"update-control":                                     {"ActionPlanInstructions", "ActionPlanTitle", "ControlId", "ControlMappingSources", "Description", "Name", "TestingInformation"},
			"update-settings":                                    {"DefaultAssessmentReportsDestination", "DefaultExportDestination", "DefaultProcessOwners", "DeregistrationPolicy", "EvidenceFinderEnabled", "KmsKey", "SnsTopic"},
			"validate-assessment-report-integrity":               {"S3RelativePath"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-assessment-report-evidence-folder":        {"AssessmentId": "*string", "EvidenceFolderId": "*string"},
			"batch-associate-assessment-report-evidence":         {"AssessmentId": "*string", "EvidenceFolderId": "*string", "EvidenceIds": "[]string"},
			"batch-create-delegation-by-assessment":              {"AssessmentId": "*string", "CreateDelegationRequests": "[]types.CreateDelegationRequest"},
			"batch-delete-delegation-by-assessment":              {"AssessmentId": "*string", "DelegationIds": "[]string"},
			"batch-disassociate-assessment-report-evidence":      {"AssessmentId": "*string", "EvidenceFolderId": "*string", "EvidenceIds": "[]string"},
			"batch-import-evidence-to-assessment-control":        {"AssessmentId": "*string", "ControlId": "*string", "ControlSetId": "*string", "ManualEvidence": "[]types.ManualEvidence"},
			"create-assessment":                                  {"AssessmentReportsDestination": "*types.AssessmentReportsDestination", "Description": "*string", "FrameworkId": "*string", "Name": "*string", "Roles": "[]types.Role", "Scope": "*types.Scope", "Tags": "map[string]string"},
			"create-assessment-framework":                        {"ComplianceType": "*string", "ControlSets": "[]types.CreateAssessmentFrameworkControlSet", "Description": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-assessment-report":                           {"AssessmentId": "*string", "Description": "*string", "Name": "*string", "QueryStatement": "*string"},
			"create-control":                                     {"ActionPlanInstructions": "*string", "ActionPlanTitle": "*string", "ControlMappingSources": "[]types.CreateControlMappingSource", "Description": "*string", "Name": "*string", "Tags": "map[string]string", "TestingInformation": "*string"},
			"delete-assessment":                                  {"AssessmentId": "*string"},
			"delete-assessment-framework":                        {"FrameworkId": "*string"},
			"delete-assessment-framework-share":                  {"RequestId": "*string", "RequestType": "types.ShareRequestType"},
			"delete-assessment-report":                           {"AssessmentId": "*string", "AssessmentReportId": "*string"},
			"delete-control":                                     {"ControlId": "*string"},
			"deregister-account":                                 {},
			"deregister-organization-admin-account":              {"AdminAccountId": "*string"},
			"disassociate-assessment-report-evidence-folder":     {"AssessmentId": "*string", "EvidenceFolderId": "*string"},
			"get-account-status":                                 {},
			"get-assessment":                                     {"AssessmentId": "*string"},
			"get-assessment-framework":                           {"FrameworkId": "*string"},
			"get-assessment-report-url":                          {"AssessmentId": "*string", "AssessmentReportId": "*string"},
			"get-change-logs":                                    {"AssessmentId": "*string", "ControlId": "*string", "ControlSetId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-control":                                        {"ControlId": "*string"},
			"get-delegations":                                    {"MaxResults": "*int32", "NextToken": "*string"},
			"get-evidence":                                       {"AssessmentId": "*string", "ControlSetId": "*string", "EvidenceFolderId": "*string", "EvidenceId": "*string"},
			"get-evidence-by-evidence-folder":                    {"AssessmentId": "*string", "ControlSetId": "*string", "EvidenceFolderId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-evidence-file-upload-url":                       {"FileName": "*string"},
			"get-evidence-folder":                                {"AssessmentId": "*string", "ControlSetId": "*string", "EvidenceFolderId": "*string"},
			"get-evidence-folders-by-assessment":                 {"AssessmentId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-evidence-folders-by-assessment-control":         {"AssessmentId": "*string", "ControlId": "*string", "ControlSetId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-insights":                                       {},
			"get-insights-by-assessment":                         {"AssessmentId": "*string"},
			"get-organization-admin-account":                     {},
			"get-services-in-scope":                              {},
			"get-settings":                                       {"Attribute": "types.SettingAttribute"},
			"list-assessment-control-insights-by-control-domain": {"AssessmentId": "*string", "ControlDomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-assessment-framework-share-requests":           {"MaxResults": "*int32", "NextToken": "*string", "RequestType": "types.ShareRequestType"},
			"list-assessment-frameworks":                         {"FrameworkType": "types.FrameworkType", "MaxResults": "*int32", "NextToken": "*string"},
			"list-assessment-reports":                            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-assessments":                                   {"MaxResults": "*int32", "NextToken": "*string", "Status": "types.AssessmentStatus"},
			"list-control-domain-insights":                       {"MaxResults": "*int32", "NextToken": "*string"},
			"list-control-domain-insights-by-assessment":         {"AssessmentId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-control-insights-by-control-domain":            {"ControlDomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-controls":                                      {"ControlCatalogId": "*string", "ControlType": "types.ControlType", "MaxResults": "*int32", "NextToken": "*string"},
			"list-keywords-for-data-source":                      {"MaxResults": "*int32", "NextToken": "*string", "Source": "types.DataSourceType"},
			"list-notifications":                                 {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                             {"ResourceArn": "*string"},
			"register-account":                                   {"DelegatedAdminAccount": "*string", "KmsKey": "*string"},
			"register-organization-admin-account":                {"AdminAccountId": "*string"},
			"start-assessment-framework-share":                   {"Comment": "*string", "DestinationAccount": "*string", "DestinationRegion": "*string", "FrameworkId": "*string"},
			"tag-resource":                                       {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                                     {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-assessment":                                  {"AssessmentDescription": "*string", "AssessmentId": "*string", "AssessmentName": "*string", "AssessmentReportsDestination": "*types.AssessmentReportsDestination", "Roles": "[]types.Role", "Scope": "*types.Scope"},
			"update-assessment-control":                          {"AssessmentId": "*string", "CommentBody": "*string", "ControlId": "*string", "ControlSetId": "*string", "ControlStatus": "types.ControlStatus"},
			"update-assessment-control-set-status":               {"AssessmentId": "*string", "Comment": "*string", "ControlSetId": "*string", "Status": "types.ControlSetStatus"},
			"update-assessment-framework":                        {"ComplianceType": "*string", "ControlSets": "[]types.UpdateAssessmentFrameworkControlSet", "Description": "*string", "FrameworkId": "*string", "Name": "*string"},
			"update-assessment-framework-share":                  {"Action": "types.ShareRequestAction", "RequestId": "*string", "RequestType": "types.ShareRequestType"},
			"update-assessment-status":                           {"AssessmentId": "*string", "Status": "types.AssessmentStatus"},
			"update-control":                                     {"ActionPlanInstructions": "*string", "ActionPlanTitle": "*string", "ControlId": "*string", "ControlMappingSources": "[]types.ControlMappingSource", "Description": "*string", "Name": "*string", "TestingInformation": "*string"},
			"update-settings":                                    {"DefaultAssessmentReportsDestination": "*types.AssessmentReportsDestination", "DefaultExportDestination": "*types.DefaultExportDestination", "DefaultProcessOwners": "[]types.Role", "DeregistrationPolicy": "*types.DeregistrationPolicy", "EvidenceFinderEnabled": "*bool", "KmsKey": "*string", "SnsTopic": "*string"},
			"validate-assessment-report-integrity":               {"S3RelativePath": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-assessment-report-evidence-folder":        {"AssessmentId", "EvidenceFolderId"},
			"batch-associate-assessment-report-evidence":         {"AssessmentId", "EvidenceFolderId", "EvidenceIds"},
			"batch-create-delegation-by-assessment":              {"AssessmentId", "CreateDelegationRequests"},
			"batch-delete-delegation-by-assessment":              {"AssessmentId", "DelegationIds"},
			"batch-disassociate-assessment-report-evidence":      {"AssessmentId", "EvidenceFolderId", "EvidenceIds"},
			"batch-import-evidence-to-assessment-control":        {"AssessmentId", "ControlId", "ControlSetId", "ManualEvidence"},
			"create-assessment":                                  {"AssessmentReportsDestination", "FrameworkId", "Name", "Roles", "Scope"},
			"create-assessment-framework":                        {"ControlSets", "Name"},
			"create-assessment-report":                           {"AssessmentId", "Name"},
			"create-control":                                     {"ControlMappingSources", "Name"},
			"delete-assessment":                                  {"AssessmentId"},
			"delete-assessment-framework":                        {"FrameworkId"},
			"delete-assessment-framework-share":                  {"RequestId", "RequestType"},
			"delete-assessment-report":                           {"AssessmentId", "AssessmentReportId"},
			"delete-control":                                     {"ControlId"},
			"deregister-account":                                 {},
			"deregister-organization-admin-account":              {},
			"disassociate-assessment-report-evidence-folder":     {"AssessmentId", "EvidenceFolderId"},
			"get-account-status":                                 {},
			"get-assessment":                                     {"AssessmentId"},
			"get-assessment-framework":                           {"FrameworkId"},
			"get-assessment-report-url":                          {"AssessmentId", "AssessmentReportId"},
			"get-change-logs":                                    {"AssessmentId"},
			"get-control":                                        {"ControlId"},
			"get-delegations":                                    {},
			"get-evidence":                                       {"AssessmentId", "ControlSetId", "EvidenceFolderId", "EvidenceId"},
			"get-evidence-by-evidence-folder":                    {"AssessmentId", "ControlSetId", "EvidenceFolderId"},
			"get-evidence-file-upload-url":                       {"FileName"},
			"get-evidence-folder":                                {"AssessmentId", "ControlSetId", "EvidenceFolderId"},
			"get-evidence-folders-by-assessment":                 {"AssessmentId"},
			"get-evidence-folders-by-assessment-control":         {"AssessmentId", "ControlId", "ControlSetId"},
			"get-insights":                                       {},
			"get-insights-by-assessment":                         {"AssessmentId"},
			"get-organization-admin-account":                     {},
			"get-services-in-scope":                              {},
			"get-settings":                                       {"Attribute"},
			"list-assessment-control-insights-by-control-domain": {"AssessmentId", "ControlDomainId"},
			"list-assessment-framework-share-requests":           {"RequestType"},
			"list-assessment-frameworks":                         {"FrameworkType"},
			"list-assessment-reports":                            {},
			"list-assessments":                                   {},
			"list-control-domain-insights":                       {},
			"list-control-domain-insights-by-assessment":         {"AssessmentId"},
			"list-control-insights-by-control-domain":            {"ControlDomainId"},
			"list-controls":                                      {"ControlType"},
			"list-keywords-for-data-source":                      {"Source"},
			"list-notifications":                                 {},
			"list-tags-for-resource":                             {"ResourceArn"},
			"register-account":                                   {},
			"register-organization-admin-account":                {"AdminAccountId"},
			"start-assessment-framework-share":                   {"DestinationAccount", "DestinationRegion", "FrameworkId"},
			"tag-resource":                                       {"ResourceArn", "Tags"},
			"untag-resource":                                     {"ResourceArn", "TagKeys"},
			"update-assessment":                                  {"AssessmentId", "Scope"},
			"update-assessment-control":                          {"AssessmentId", "ControlId", "ControlSetId"},
			"update-assessment-control-set-status":               {"AssessmentId", "Comment", "ControlSetId", "Status"},
			"update-assessment-framework":                        {"ControlSets", "FrameworkId", "Name"},
			"update-assessment-framework-share":                  {"Action", "RequestId", "RequestType"},
			"update-assessment-status":                           {"AssessmentId", "Status"},
			"update-control":                                     {"ControlId", "ControlMappingSources", "Name"},
			"update-settings":                                    {},
			"validate-assessment-report-integrity":               {"S3RelativePath"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("auditmanager", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
