package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/amplify/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-app", "create-backend-environment", "create-branch", "create-deployment", "create-domain-association", "create-webhook", "delete-app", "delete-backend-environment", "delete-branch", "delete-domain-association", "delete-job", "delete-webhook", "generate-access-logs", "get-app", "get-artifact-url", "get-backend-environment", "get-branch", "get-domain-association", "get-job", "get-webhook", "list-apps", "list-artifacts", "list-backend-environments", "list-branches", "list-domain-associations", "list-jobs", "list-tags-for-resource", "list-webhooks", "start-deployment", "start-job", "stop-job", "tag-resource", "untag-resource", "update-app", "update-branch", "update-domain-association", "update-webhook"},
		OperationSet: map[string]bool{"create-app": true, "create-backend-environment": true, "create-branch": true, "create-deployment": true, "create-domain-association": true, "create-webhook": true, "delete-app": true, "delete-backend-environment": true, "delete-branch": true, "delete-domain-association": true, "delete-job": true, "delete-webhook": true, "generate-access-logs": true, "get-app": true, "get-artifact-url": true, "get-backend-environment": true, "get-branch": true, "get-domain-association": true, "get-job": true, "get-webhook": true, "list-apps": true, "list-artifacts": true, "list-backend-environments": true, "list-branches": true, "list-domain-associations": true, "list-jobs": true, "list-tags-for-resource": true, "list-webhooks": true, "start-deployment": true, "start-job": true, "stop-job": true, "tag-resource": true, "untag-resource": true, "update-app": true, "update-branch": true, "update-domain-association": true, "update-webhook": true},
		OperationInputs: map[string][]string{
			"create-app":                 {"AccessToken", "AutoBranchCreationConfig", "AutoBranchCreationPatterns", "BasicAuthCredentials", "BuildSpec", "CacheConfig", "ComputeRoleArn", "CustomHeaders", "CustomRules", "Description", "EnableAutoBranchCreation", "EnableBasicAuth", "EnableBranchAutoBuild", "EnableBranchAutoDeletion", "EnvironmentVariables", "IamServiceRoleArn", "JobConfig", "Name", "OauthToken", "Platform", "Repository", "Tags"},
			"create-backend-environment": {"AppId", "DeploymentArtifacts", "EnvironmentName", "StackName"},
			"create-branch":              {"AppId", "Backend", "BackendEnvironmentArn", "BasicAuthCredentials", "BranchName", "BuildSpec", "ComputeRoleArn", "Description", "DisplayName", "EnableAutoBuild", "EnableBasicAuth", "EnableNotification", "EnablePerformanceMode", "EnablePullRequestPreview", "EnableSkewProtection", "EnvironmentVariables", "Framework", "PullRequestEnvironmentName", "Stage", "Tags", "Ttl"},
			"create-deployment":          {"AppId", "BranchName", "FileMap"},
			"create-domain-association":  {"AppId", "AutoSubDomainCreationPatterns", "AutoSubDomainIAMRole", "CertificateSettings", "DomainName", "EnableAutoSubDomain", "SubDomainSettings"},
			"create-webhook":             {"AppId", "BranchName", "Description"},
			"delete-app":                 {"AppId"},
			"delete-backend-environment": {"AppId", "EnvironmentName"},
			"delete-branch":              {"AppId", "BranchName"},
			"delete-domain-association":  {"AppId", "DomainName"},
			"delete-job":                 {"AppId", "BranchName", "JobId"},
			"delete-webhook":             {"WebhookId"},
			"generate-access-logs":       {"AppId", "DomainName", "EndTime", "StartTime"},
			"get-app":                    {"AppId"},
			"get-artifact-url":           {"ArtifactId"},
			"get-backend-environment":    {"AppId", "EnvironmentName"},
			"get-branch":                 {"AppId", "BranchName"},
			"get-domain-association":     {"AppId", "DomainName"},
			"get-job":                    {"AppId", "BranchName", "JobId"},
			"get-webhook":                {"WebhookId"},
			"list-apps":                  {"MaxResults", "NextToken"},
			"list-artifacts":             {"AppId", "BranchName", "JobId", "MaxResults", "NextToken"},
			"list-backend-environments":  {"AppId", "EnvironmentName", "MaxResults", "NextToken"},
			"list-branches":              {"AppId", "MaxResults", "NextToken"},
			"list-domain-associations":   {"AppId", "MaxResults", "NextToken"},
			"list-jobs":                  {"AppId", "BranchName", "MaxResults", "NextToken"},
			"list-tags-for-resource":     {"ResourceArn"},
			"list-webhooks":              {"AppId", "MaxResults", "NextToken"},
			"start-deployment":           {"AppId", "BranchName", "JobId", "SourceUrl", "SourceUrlType"},
			"start-job":                  {"AppId", "BranchName", "CommitId", "CommitMessage", "CommitTime", "JobId", "JobReason", "JobType"},
			"stop-job":                   {"AppId", "BranchName", "JobId"},
			"tag-resource":               {"ResourceArn", "Tags"},
			"untag-resource":             {"ResourceArn", "TagKeys"},
			"update-app":                 {"AccessToken", "AppId", "AutoBranchCreationConfig", "AutoBranchCreationPatterns", "BasicAuthCredentials", "BuildSpec", "CacheConfig", "ComputeRoleArn", "CustomHeaders", "CustomRules", "Description", "EnableAutoBranchCreation", "EnableBasicAuth", "EnableBranchAutoBuild", "EnableBranchAutoDeletion", "EnvironmentVariables", "IamServiceRoleArn", "JobConfig", "Name", "OauthToken", "Platform", "Repository"},
			"update-branch":              {"AppId", "Backend", "BackendEnvironmentArn", "BasicAuthCredentials", "BranchName", "BuildSpec", "ComputeRoleArn", "Description", "DisplayName", "EnableAutoBuild", "EnableBasicAuth", "EnableNotification", "EnablePerformanceMode", "EnablePullRequestPreview", "EnableSkewProtection", "EnvironmentVariables", "Framework", "PullRequestEnvironmentName", "Stage", "Ttl"},
			"update-domain-association":  {"AppId", "AutoSubDomainCreationPatterns", "AutoSubDomainIAMRole", "CertificateSettings", "DomainName", "EnableAutoSubDomain", "SubDomainSettings"},
			"update-webhook":             {"BranchName", "Description", "WebhookId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-app":                 {"AccessToken": "*string", "AutoBranchCreationConfig": "*types.AutoBranchCreationConfig", "AutoBranchCreationPatterns": "[]string", "BasicAuthCredentials": "*string", "BuildSpec": "*string", "CacheConfig": "*types.CacheConfig", "ComputeRoleArn": "*string", "CustomHeaders": "*string", "CustomRules": "[]types.CustomRule", "Description": "*string", "EnableAutoBranchCreation": "*bool", "EnableBasicAuth": "*bool", "EnableBranchAutoBuild": "*bool", "EnableBranchAutoDeletion": "*bool", "EnvironmentVariables": "map[string]string", "IamServiceRoleArn": "*string", "JobConfig": "*types.JobConfig", "Name": "*string", "OauthToken": "*string", "Platform": "types.Platform", "Repository": "*string", "Tags": "map[string]string"},
			"create-backend-environment": {"AppId": "*string", "DeploymentArtifacts": "*string", "EnvironmentName": "*string", "StackName": "*string"},
			"create-branch":              {"AppId": "*string", "Backend": "*types.Backend", "BackendEnvironmentArn": "*string", "BasicAuthCredentials": "*string", "BranchName": "*string", "BuildSpec": "*string", "ComputeRoleArn": "*string", "Description": "*string", "DisplayName": "*string", "EnableAutoBuild": "*bool", "EnableBasicAuth": "*bool", "EnableNotification": "*bool", "EnablePerformanceMode": "*bool", "EnablePullRequestPreview": "*bool", "EnableSkewProtection": "*bool", "EnvironmentVariables": "map[string]string", "Framework": "*string", "PullRequestEnvironmentName": "*string", "Stage": "types.Stage", "Tags": "map[string]string", "Ttl": "*string"},
			"create-deployment":          {"AppId": "*string", "BranchName": "*string", "FileMap": "map[string]string"},
			"create-domain-association":  {"AppId": "*string", "AutoSubDomainCreationPatterns": "[]string", "AutoSubDomainIAMRole": "*string", "CertificateSettings": "*types.CertificateSettings", "DomainName": "*string", "EnableAutoSubDomain": "*bool", "SubDomainSettings": "[]types.SubDomainSetting"},
			"create-webhook":             {"AppId": "*string", "BranchName": "*string", "Description": "*string"},
			"delete-app":                 {"AppId": "*string"},
			"delete-backend-environment": {"AppId": "*string", "EnvironmentName": "*string"},
			"delete-branch":              {"AppId": "*string", "BranchName": "*string"},
			"delete-domain-association":  {"AppId": "*string", "DomainName": "*string"},
			"delete-job":                 {"AppId": "*string", "BranchName": "*string", "JobId": "*string"},
			"delete-webhook":             {"WebhookId": "*string"},
			"generate-access-logs":       {"AppId": "*string", "DomainName": "*string", "EndTime": "*time.Time", "StartTime": "*time.Time"},
			"get-app":                    {"AppId": "*string"},
			"get-artifact-url":           {"ArtifactId": "*string"},
			"get-backend-environment":    {"AppId": "*string", "EnvironmentName": "*string"},
			"get-branch":                 {"AppId": "*string", "BranchName": "*string"},
			"get-domain-association":     {"AppId": "*string", "DomainName": "*string"},
			"get-job":                    {"AppId": "*string", "BranchName": "*string", "JobId": "*string"},
			"get-webhook":                {"WebhookId": "*string"},
			"list-apps":                  {"MaxResults": "int32", "NextToken": "*string"},
			"list-artifacts":             {"AppId": "*string", "BranchName": "*string", "JobId": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-backend-environments":  {"AppId": "*string", "EnvironmentName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-branches":              {"AppId": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-domain-associations":   {"AppId": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-jobs":                  {"AppId": "*string", "BranchName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-tags-for-resource":     {"ResourceArn": "*string"},
			"list-webhooks":              {"AppId": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"start-deployment":           {"AppId": "*string", "BranchName": "*string", "JobId": "*string", "SourceUrl": "*string", "SourceUrlType": "types.SourceUrlType"},
			"start-job":                  {"AppId": "*string", "BranchName": "*string", "CommitId": "*string", "CommitMessage": "*string", "CommitTime": "*time.Time", "JobId": "*string", "JobReason": "*string", "JobType": "types.JobType"},
			"stop-job":                   {"AppId": "*string", "BranchName": "*string", "JobId": "*string"},
			"tag-resource":               {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":             {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-app":                 {"AccessToken": "*string", "AppId": "*string", "AutoBranchCreationConfig": "*types.AutoBranchCreationConfig", "AutoBranchCreationPatterns": "[]string", "BasicAuthCredentials": "*string", "BuildSpec": "*string", "CacheConfig": "*types.CacheConfig", "ComputeRoleArn": "*string", "CustomHeaders": "*string", "CustomRules": "[]types.CustomRule", "Description": "*string", "EnableAutoBranchCreation": "*bool", "EnableBasicAuth": "*bool", "EnableBranchAutoBuild": "*bool", "EnableBranchAutoDeletion": "*bool", "EnvironmentVariables": "map[string]string", "IamServiceRoleArn": "*string", "JobConfig": "*types.JobConfig", "Name": "*string", "OauthToken": "*string", "Platform": "types.Platform", "Repository": "*string"},
			"update-branch":              {"AppId": "*string", "Backend": "*types.Backend", "BackendEnvironmentArn": "*string", "BasicAuthCredentials": "*string", "BranchName": "*string", "BuildSpec": "*string", "ComputeRoleArn": "*string", "Description": "*string", "DisplayName": "*string", "EnableAutoBuild": "*bool", "EnableBasicAuth": "*bool", "EnableNotification": "*bool", "EnablePerformanceMode": "*bool", "EnablePullRequestPreview": "*bool", "EnableSkewProtection": "*bool", "EnvironmentVariables": "map[string]string", "Framework": "*string", "PullRequestEnvironmentName": "*string", "Stage": "types.Stage", "Ttl": "*string"},
			"update-domain-association":  {"AppId": "*string", "AutoSubDomainCreationPatterns": "[]string", "AutoSubDomainIAMRole": "*string", "CertificateSettings": "*types.CertificateSettings", "DomainName": "*string", "EnableAutoSubDomain": "*bool", "SubDomainSettings": "[]types.SubDomainSetting"},
			"update-webhook":             {"BranchName": "*string", "Description": "*string", "WebhookId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-app":                 {"Name"},
			"create-backend-environment": {"AppId", "EnvironmentName"},
			"create-branch":              {"AppId", "BranchName"},
			"create-deployment":          {"AppId", "BranchName"},
			"create-domain-association":  {"AppId", "DomainName", "SubDomainSettings"},
			"create-webhook":             {"AppId", "BranchName"},
			"delete-app":                 {"AppId"},
			"delete-backend-environment": {"AppId", "EnvironmentName"},
			"delete-branch":              {"AppId", "BranchName"},
			"delete-domain-association":  {"AppId", "DomainName"},
			"delete-job":                 {"AppId", "BranchName", "JobId"},
			"delete-webhook":             {"WebhookId"},
			"generate-access-logs":       {"AppId", "DomainName"},
			"get-app":                    {"AppId"},
			"get-artifact-url":           {"ArtifactId"},
			"get-backend-environment":    {"AppId", "EnvironmentName"},
			"get-branch":                 {"AppId", "BranchName"},
			"get-domain-association":     {"AppId", "DomainName"},
			"get-job":                    {"AppId", "BranchName", "JobId"},
			"get-webhook":                {"WebhookId"},
			"list-apps":                  {},
			"list-artifacts":             {"AppId", "BranchName", "JobId"},
			"list-backend-environments":  {"AppId"},
			"list-branches":              {"AppId"},
			"list-domain-associations":   {"AppId"},
			"list-jobs":                  {"AppId", "BranchName"},
			"list-tags-for-resource":     {"ResourceArn"},
			"list-webhooks":              {"AppId"},
			"start-deployment":           {"AppId", "BranchName"},
			"start-job":                  {"AppId", "BranchName", "JobType"},
			"stop-job":                   {"AppId", "BranchName", "JobId"},
			"tag-resource":               {"ResourceArn", "Tags"},
			"untag-resource":             {"ResourceArn", "TagKeys"},
			"update-app":                 {"AppId"},
			"update-branch":              {"AppId", "BranchName"},
			"update-domain-association":  {"AppId", "DomainName"},
			"update-webhook":             {"WebhookId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("amplify", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
