package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/rekognition/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-faces", "compare-faces", "copy-project-version", "create-collection", "create-dataset", "create-face-liveness-session", "create-project", "create-project-version", "create-stream-processor", "create-user", "delete-collection", "delete-dataset", "delete-faces", "delete-project", "delete-project-policy", "delete-project-version", "delete-stream-processor", "delete-user", "describe-collection", "describe-dataset", "describe-project-versions", "describe-projects", "describe-stream-processor", "detect-custom-labels", "detect-faces", "detect-labels", "detect-moderation-labels", "detect-protective-equipment", "detect-text", "disassociate-faces", "distribute-dataset-entries", "get-celebrity-info", "get-celebrity-recognition", "get-content-moderation", "get-face-detection", "get-face-liveness-session-results", "get-face-search", "get-label-detection", "get-media-analysis-job", "get-person-tracking", "get-segment-detection", "get-text-detection", "index-faces", "list-collections", "list-dataset-entries", "list-dataset-labels", "list-faces", "list-media-analysis-jobs", "list-project-policies", "list-stream-processors", "list-tags-for-resource", "list-users", "put-project-policy", "recognize-celebrities", "search-faces", "search-faces-by-image", "search-users", "search-users-by-image", "start-celebrity-recognition", "start-content-moderation", "start-face-detection", "start-face-search", "start-label-detection", "start-media-analysis-job", "start-person-tracking", "start-project-version", "start-segment-detection", "start-stream-processor", "start-text-detection", "stop-project-version", "stop-stream-processor", "tag-resource", "untag-resource", "update-dataset-entries", "update-stream-processor"},
		OperationSet: map[string]bool{"associate-faces": true, "compare-faces": true, "copy-project-version": true, "create-collection": true, "create-dataset": true, "create-face-liveness-session": true, "create-project": true, "create-project-version": true, "create-stream-processor": true, "create-user": true, "delete-collection": true, "delete-dataset": true, "delete-faces": true, "delete-project": true, "delete-project-policy": true, "delete-project-version": true, "delete-stream-processor": true, "delete-user": true, "describe-collection": true, "describe-dataset": true, "describe-project-versions": true, "describe-projects": true, "describe-stream-processor": true, "detect-custom-labels": true, "detect-faces": true, "detect-labels": true, "detect-moderation-labels": true, "detect-protective-equipment": true, "detect-text": true, "disassociate-faces": true, "distribute-dataset-entries": true, "get-celebrity-info": true, "get-celebrity-recognition": true, "get-content-moderation": true, "get-face-detection": true, "get-face-liveness-session-results": true, "get-face-search": true, "get-label-detection": true, "get-media-analysis-job": true, "get-person-tracking": true, "get-segment-detection": true, "get-text-detection": true, "index-faces": true, "list-collections": true, "list-dataset-entries": true, "list-dataset-labels": true, "list-faces": true, "list-media-analysis-jobs": true, "list-project-policies": true, "list-stream-processors": true, "list-tags-for-resource": true, "list-users": true, "put-project-policy": true, "recognize-celebrities": true, "search-faces": true, "search-faces-by-image": true, "search-users": true, "search-users-by-image": true, "start-celebrity-recognition": true, "start-content-moderation": true, "start-face-detection": true, "start-face-search": true, "start-label-detection": true, "start-media-analysis-job": true, "start-person-tracking": true, "start-project-version": true, "start-segment-detection": true, "start-stream-processor": true, "start-text-detection": true, "stop-project-version": true, "stop-stream-processor": true, "tag-resource": true, "untag-resource": true, "update-dataset-entries": true, "update-stream-processor": true},
		OperationInputs: map[string][]string{
			"associate-faces":                   {"ClientRequestToken", "CollectionId", "FaceIds", "UserId", "UserMatchThreshold"},
			"compare-faces":                     {"QualityFilter", "SimilarityThreshold", "SourceImage", "TargetImage"},
			"copy-project-version":              {"DestinationProjectArn", "KmsKeyId", "OutputConfig", "SourceProjectArn", "SourceProjectVersionArn", "Tags", "VersionName"},
			"create-collection":                 {"CollectionId", "Tags"},
			"create-dataset":                    {"DatasetSource", "DatasetType", "ProjectArn", "Tags"},
			"create-face-liveness-session":      {"ClientRequestToken", "KmsKeyId", "Settings"},
			"create-project":                    {"AutoUpdate", "Feature", "ProjectName", "Tags"},
			"create-project-version":            {"FeatureConfig", "KmsKeyId", "OutputConfig", "ProjectArn", "Tags", "TestingData", "TrainingData", "VersionDescription", "VersionName"},
			"create-stream-processor":           {"DataSharingPreference", "Input", "KmsKeyId", "Name", "NotificationChannel", "Output", "RegionsOfInterest", "RoleArn", "Settings", "Tags"},
			"create-user":                       {"ClientRequestToken", "CollectionId", "UserId"},
			"delete-collection":                 {"CollectionId"},
			"delete-dataset":                    {"DatasetArn"},
			"delete-faces":                      {"CollectionId", "FaceIds"},
			"delete-project":                    {"ProjectArn"},
			"delete-project-policy":             {"PolicyName", "PolicyRevisionId", "ProjectArn"},
			"delete-project-version":            {"ProjectVersionArn"},
			"delete-stream-processor":           {"Name"},
			"delete-user":                       {"ClientRequestToken", "CollectionId", "UserId"},
			"describe-collection":               {"CollectionId"},
			"describe-dataset":                  {"DatasetArn"},
			"describe-project-versions":         {"MaxResults", "NextToken", "ProjectArn", "VersionNames"},
			"describe-projects":                 {"Features", "MaxResults", "NextToken", "ProjectNames"},
			"describe-stream-processor":         {"Name"},
			"detect-custom-labels":              {"Image", "MaxResults", "MinConfidence", "ProjectVersionArn"},
			"detect-faces":                      {"Attributes", "Image"},
			"detect-labels":                     {"Features", "Image", "MaxLabels", "MinConfidence", "Settings"},
			"detect-moderation-labels":          {"HumanLoopConfig", "Image", "MinConfidence", "ProjectVersion"},
			"detect-protective-equipment":       {"Image", "SummarizationAttributes"},
			"detect-text":                       {"Filters", "Image"},
			"disassociate-faces":                {"ClientRequestToken", "CollectionId", "FaceIds", "UserId"},
			"distribute-dataset-entries":        {"Datasets"},
			"get-celebrity-info":                {"Id"},
			"get-celebrity-recognition":         {"JobId", "MaxResults", "NextToken", "SortBy"},
			"get-content-moderation":            {"AggregateBy", "JobId", "MaxResults", "NextToken", "SortBy"},
			"get-face-detection":                {"JobId", "MaxResults", "NextToken"},
			"get-face-liveness-session-results": {"SessionId"},
			"get-face-search":                   {"JobId", "MaxResults", "NextToken", "SortBy"},
			"get-label-detection":               {"AggregateBy", "JobId", "MaxResults", "NextToken", "SortBy"},
			"get-media-analysis-job":            {"JobId"},
			"get-person-tracking":               {"JobId", "MaxResults", "NextToken", "SortBy"},
			"get-segment-detection":             {"JobId", "MaxResults", "NextToken"},
			"get-text-detection":                {"JobId", "MaxResults", "NextToken"},
			"index-faces":                       {"CollectionId", "DetectionAttributes", "ExternalImageId", "Image", "MaxFaces", "QualityFilter"},
			"list-collections":                  {"MaxResults", "NextToken"},
			"list-dataset-entries":              {"ContainsLabels", "DatasetArn", "HasErrors", "Labeled", "MaxResults", "NextToken", "SourceRefContains"},
			"list-dataset-labels":               {"DatasetArn", "MaxResults", "NextToken"},
			"list-faces":                        {"CollectionId", "FaceIds", "MaxResults", "NextToken", "UserId"},
			"list-media-analysis-jobs":          {"MaxResults", "NextToken"},
			"list-project-policies":             {"MaxResults", "NextToken", "ProjectArn"},
			"list-stream-processors":            {"MaxResults", "NextToken"},
			"list-tags-for-resource":            {"ResourceArn"},
			"list-users":                        {"CollectionId", "MaxResults", "NextToken"},
			"put-project-policy":                {"PolicyDocument", "PolicyName", "PolicyRevisionId", "ProjectArn"},
			"recognize-celebrities":             {"Image"},
			"search-faces":                      {"CollectionId", "FaceId", "FaceMatchThreshold", "MaxFaces"},
			"search-faces-by-image":             {"CollectionId", "FaceMatchThreshold", "Image", "MaxFaces", "QualityFilter"},
			"search-users":                      {"CollectionId", "FaceId", "MaxUsers", "UserId", "UserMatchThreshold"},
			"search-users-by-image":             {"CollectionId", "Image", "MaxUsers", "QualityFilter", "UserMatchThreshold"},
			"start-celebrity-recognition":       {"ClientRequestToken", "JobTag", "NotificationChannel", "Video"},
			"start-content-moderation":          {"ClientRequestToken", "JobTag", "MinConfidence", "NotificationChannel", "Video"},
			"start-face-detection":              {"ClientRequestToken", "FaceAttributes", "JobTag", "NotificationChannel", "Video"},
			"start-face-search":                 {"ClientRequestToken", "CollectionId", "FaceMatchThreshold", "JobTag", "NotificationChannel", "Video"},
			"start-label-detection":             {"ClientRequestToken", "Features", "JobTag", "MinConfidence", "NotificationChannel", "Settings", "Video"},
			"start-media-analysis-job":          {"ClientRequestToken", "Input", "JobName", "KmsKeyId", "OperationsConfig", "OutputConfig"},
			"start-person-tracking":             {"ClientRequestToken", "JobTag", "NotificationChannel", "Video"},
			"start-project-version":             {"MaxInferenceUnits", "MinInferenceUnits", "ProjectVersionArn"},
			"start-segment-detection":           {"ClientRequestToken", "Filters", "JobTag", "NotificationChannel", "SegmentTypes", "Video"},
			"start-stream-processor":            {"Name", "StartSelector", "StopSelector"},
			"start-text-detection":              {"ClientRequestToken", "Filters", "JobTag", "NotificationChannel", "Video"},
			"stop-project-version":              {"ProjectVersionArn"},
			"stop-stream-processor":             {"Name"},
			"tag-resource":                      {"ResourceArn", "Tags"},
			"untag-resource":                    {"ResourceArn", "TagKeys"},
			"update-dataset-entries":            {"Changes", "DatasetArn"},
			"update-stream-processor":           {"DataSharingPreferenceForUpdate", "Name", "ParametersToDelete", "RegionsOfInterestForUpdate", "SettingsForUpdate"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-faces":                   {"ClientRequestToken": "*string", "CollectionId": "*string", "FaceIds": "[]string", "UserId": "*string", "UserMatchThreshold": "*float32"},
			"compare-faces":                     {"QualityFilter": "types.QualityFilter", "SimilarityThreshold": "*float32", "SourceImage": "*types.Image", "TargetImage": "*types.Image"},
			"copy-project-version":              {"DestinationProjectArn": "*string", "KmsKeyId": "*string", "OutputConfig": "*types.OutputConfig", "SourceProjectArn": "*string", "SourceProjectVersionArn": "*string", "Tags": "map[string]string", "VersionName": "*string"},
			"create-collection":                 {"CollectionId": "*string", "Tags": "map[string]string"},
			"create-dataset":                    {"DatasetSource": "*types.DatasetSource", "DatasetType": "types.DatasetType", "ProjectArn": "*string", "Tags": "map[string]string"},
			"create-face-liveness-session":      {"ClientRequestToken": "*string", "KmsKeyId": "*string", "Settings": "*types.CreateFaceLivenessSessionRequestSettings"},
			"create-project":                    {"AutoUpdate": "types.ProjectAutoUpdate", "Feature": "types.CustomizationFeature", "ProjectName": "*string", "Tags": "map[string]string"},
			"create-project-version":            {"FeatureConfig": "*types.CustomizationFeatureConfig", "KmsKeyId": "*string", "OutputConfig": "*types.OutputConfig", "ProjectArn": "*string", "Tags": "map[string]string", "TestingData": "*types.TestingData", "TrainingData": "*types.TrainingData", "VersionDescription": "*string", "VersionName": "*string"},
			"create-stream-processor":           {"DataSharingPreference": "*types.StreamProcessorDataSharingPreference", "Input": "*types.StreamProcessorInput", "KmsKeyId": "*string", "Name": "*string", "NotificationChannel": "*types.StreamProcessorNotificationChannel", "Output": "*types.StreamProcessorOutput", "RegionsOfInterest": "[]types.RegionOfInterest", "RoleArn": "*string", "Settings": "*types.StreamProcessorSettings", "Tags": "map[string]string"},
			"create-user":                       {"ClientRequestToken": "*string", "CollectionId": "*string", "UserId": "*string"},
			"delete-collection":                 {"CollectionId": "*string"},
			"delete-dataset":                    {"DatasetArn": "*string"},
			"delete-faces":                      {"CollectionId": "*string", "FaceIds": "[]string"},
			"delete-project":                    {"ProjectArn": "*string"},
			"delete-project-policy":             {"PolicyName": "*string", "PolicyRevisionId": "*string", "ProjectArn": "*string"},
			"delete-project-version":            {"ProjectVersionArn": "*string"},
			"delete-stream-processor":           {"Name": "*string"},
			"delete-user":                       {"ClientRequestToken": "*string", "CollectionId": "*string", "UserId": "*string"},
			"describe-collection":               {"CollectionId": "*string"},
			"describe-dataset":                  {"DatasetArn": "*string"},
			"describe-project-versions":         {"MaxResults": "*int32", "NextToken": "*string", "ProjectArn": "*string", "VersionNames": "[]string"},
			"describe-projects":                 {"Features": "[]types.CustomizationFeature", "MaxResults": "*int32", "NextToken": "*string", "ProjectNames": "[]string"},
			"describe-stream-processor":         {"Name": "*string"},
			"detect-custom-labels":              {"Image": "*types.Image", "MaxResults": "*int32", "MinConfidence": "*float32", "ProjectVersionArn": "*string"},
			"detect-faces":                      {"Attributes": "[]types.Attribute", "Image": "*types.Image"},
			"detect-labels":                     {"Features": "[]types.DetectLabelsFeatureName", "Image": "*types.Image", "MaxLabels": "*int32", "MinConfidence": "*float32", "Settings": "*types.DetectLabelsSettings"},
			"detect-moderation-labels":          {"HumanLoopConfig": "*types.HumanLoopConfig", "Image": "*types.Image", "MinConfidence": "*float32", "ProjectVersion": "*string"},
			"detect-protective-equipment":       {"Image": "*types.Image", "SummarizationAttributes": "*types.ProtectiveEquipmentSummarizationAttributes"},
			"detect-text":                       {"Filters": "*types.DetectTextFilters", "Image": "*types.Image"},
			"disassociate-faces":                {"ClientRequestToken": "*string", "CollectionId": "*string", "FaceIds": "[]string", "UserId": "*string"},
			"distribute-dataset-entries":        {"Datasets": "[]types.DistributeDataset"},
			"get-celebrity-info":                {"Id": "*string"},
			"get-celebrity-recognition":         {"JobId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SortBy": "types.CelebrityRecognitionSortBy"},
			"get-content-moderation":            {"AggregateBy": "types.ContentModerationAggregateBy", "JobId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SortBy": "types.ContentModerationSortBy"},
			"get-face-detection":                {"JobId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-face-liveness-session-results": {"SessionId": "*string"},
			"get-face-search":                   {"JobId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SortBy": "types.FaceSearchSortBy"},
			"get-label-detection":               {"AggregateBy": "types.LabelDetectionAggregateBy", "JobId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SortBy": "types.LabelDetectionSortBy"},
			"get-media-analysis-job":            {"JobId": "*string"},
			"get-person-tracking":               {"JobId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SortBy": "types.PersonTrackingSortBy"},
			"get-segment-detection":             {"JobId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-text-detection":                {"JobId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"index-faces":                       {"CollectionId": "*string", "DetectionAttributes": "[]types.Attribute", "ExternalImageId": "*string", "Image": "*types.Image", "MaxFaces": "*int32", "QualityFilter": "types.QualityFilter"},
			"list-collections":                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-dataset-entries":              {"ContainsLabels": "[]string", "DatasetArn": "*string", "HasErrors": "*bool", "Labeled": "*bool", "MaxResults": "*int32", "NextToken": "*string", "SourceRefContains": "*string"},
			"list-dataset-labels":               {"DatasetArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-faces":                        {"CollectionId": "*string", "FaceIds": "[]string", "MaxResults": "*int32", "NextToken": "*string", "UserId": "*string"},
			"list-media-analysis-jobs":          {"MaxResults": "*int32", "NextToken": "*string"},
			"list-project-policies":             {"MaxResults": "*int32", "NextToken": "*string", "ProjectArn": "*string"},
			"list-stream-processors":            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":            {"ResourceArn": "*string"},
			"list-users":                        {"CollectionId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"put-project-policy":                {"PolicyDocument": "*string", "PolicyName": "*string", "PolicyRevisionId": "*string", "ProjectArn": "*string"},
			"recognize-celebrities":             {"Image": "*types.Image"},
			"search-faces":                      {"CollectionId": "*string", "FaceId": "*string", "FaceMatchThreshold": "*float32", "MaxFaces": "*int32"},
			"search-faces-by-image":             {"CollectionId": "*string", "FaceMatchThreshold": "*float32", "Image": "*types.Image", "MaxFaces": "*int32", "QualityFilter": "types.QualityFilter"},
			"search-users":                      {"CollectionId": "*string", "FaceId": "*string", "MaxUsers": "*int32", "UserId": "*string", "UserMatchThreshold": "*float32"},
			"search-users-by-image":             {"CollectionId": "*string", "Image": "*types.Image", "MaxUsers": "*int32", "QualityFilter": "types.QualityFilter", "UserMatchThreshold": "*float32"},
			"start-celebrity-recognition":       {"ClientRequestToken": "*string", "JobTag": "*string", "NotificationChannel": "*types.NotificationChannel", "Video": "*types.Video"},
			"start-content-moderation":          {"ClientRequestToken": "*string", "JobTag": "*string", "MinConfidence": "*float32", "NotificationChannel": "*types.NotificationChannel", "Video": "*types.Video"},
			"start-face-detection":              {"ClientRequestToken": "*string", "FaceAttributes": "types.FaceAttributes", "JobTag": "*string", "NotificationChannel": "*types.NotificationChannel", "Video": "*types.Video"},
			"start-face-search":                 {"ClientRequestToken": "*string", "CollectionId": "*string", "FaceMatchThreshold": "*float32", "JobTag": "*string", "NotificationChannel": "*types.NotificationChannel", "Video": "*types.Video"},
			"start-label-detection":             {"ClientRequestToken": "*string", "Features": "[]types.LabelDetectionFeatureName", "JobTag": "*string", "MinConfidence": "*float32", "NotificationChannel": "*types.NotificationChannel", "Settings": "*types.LabelDetectionSettings", "Video": "*types.Video"},
			"start-media-analysis-job":          {"ClientRequestToken": "*string", "Input": "*types.MediaAnalysisInput", "JobName": "*string", "KmsKeyId": "*string", "OperationsConfig": "*types.MediaAnalysisOperationsConfig", "OutputConfig": "*types.MediaAnalysisOutputConfig"},
			"start-person-tracking":             {"ClientRequestToken": "*string", "JobTag": "*string", "NotificationChannel": "*types.NotificationChannel", "Video": "*types.Video"},
			"start-project-version":             {"MaxInferenceUnits": "*int32", "MinInferenceUnits": "*int32", "ProjectVersionArn": "*string"},
			"start-segment-detection":           {"ClientRequestToken": "*string", "Filters": "*types.StartSegmentDetectionFilters", "JobTag": "*string", "NotificationChannel": "*types.NotificationChannel", "SegmentTypes": "[]types.SegmentType", "Video": "*types.Video"},
			"start-stream-processor":            {"Name": "*string", "StartSelector": "*types.StreamProcessingStartSelector", "StopSelector": "*types.StreamProcessingStopSelector"},
			"start-text-detection":              {"ClientRequestToken": "*string", "Filters": "*types.StartTextDetectionFilters", "JobTag": "*string", "NotificationChannel": "*types.NotificationChannel", "Video": "*types.Video"},
			"stop-project-version":              {"ProjectVersionArn": "*string"},
			"stop-stream-processor":             {"Name": "*string"},
			"tag-resource":                      {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                    {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-dataset-entries":            {"Changes": "*types.DatasetChanges", "DatasetArn": "*string"},
			"update-stream-processor":           {"DataSharingPreferenceForUpdate": "*types.StreamProcessorDataSharingPreference", "Name": "*string", "ParametersToDelete": "[]types.StreamProcessorParameterToDelete", "RegionsOfInterestForUpdate": "[]types.RegionOfInterest", "SettingsForUpdate": "*types.StreamProcessorSettingsForUpdate"},
		},
		OperationInputRequired: map[string][]string{
			"associate-faces":                   {"CollectionId", "FaceIds", "UserId"},
			"compare-faces":                     {"SourceImage", "TargetImage"},
			"copy-project-version":              {"DestinationProjectArn", "OutputConfig", "SourceProjectArn", "SourceProjectVersionArn", "VersionName"},
			"create-collection":                 {"CollectionId"},
			"create-dataset":                    {"DatasetType", "ProjectArn"},
			"create-face-liveness-session":      {},
			"create-project":                    {"ProjectName"},
			"create-project-version":            {"OutputConfig", "ProjectArn", "VersionName"},
			"create-stream-processor":           {"Input", "Name", "Output", "RoleArn", "Settings"},
			"create-user":                       {"CollectionId", "UserId"},
			"delete-collection":                 {"CollectionId"},
			"delete-dataset":                    {"DatasetArn"},
			"delete-faces":                      {"CollectionId", "FaceIds"},
			"delete-project":                    {"ProjectArn"},
			"delete-project-policy":             {"PolicyName", "ProjectArn"},
			"delete-project-version":            {"ProjectVersionArn"},
			"delete-stream-processor":           {"Name"},
			"delete-user":                       {"CollectionId", "UserId"},
			"describe-collection":               {"CollectionId"},
			"describe-dataset":                  {"DatasetArn"},
			"describe-project-versions":         {"ProjectArn"},
			"describe-projects":                 {},
			"describe-stream-processor":         {"Name"},
			"detect-custom-labels":              {"Image", "ProjectVersionArn"},
			"detect-faces":                      {"Image"},
			"detect-labels":                     {"Image"},
			"detect-moderation-labels":          {"Image"},
			"detect-protective-equipment":       {"Image"},
			"detect-text":                       {"Image"},
			"disassociate-faces":                {"CollectionId", "FaceIds", "UserId"},
			"distribute-dataset-entries":        {"Datasets"},
			"get-celebrity-info":                {"Id"},
			"get-celebrity-recognition":         {"JobId"},
			"get-content-moderation":            {"JobId"},
			"get-face-detection":                {"JobId"},
			"get-face-liveness-session-results": {"SessionId"},
			"get-face-search":                   {"JobId"},
			"get-label-detection":               {"JobId"},
			"get-media-analysis-job":            {"JobId"},
			"get-person-tracking":               {"JobId"},
			"get-segment-detection":             {"JobId"},
			"get-text-detection":                {"JobId"},
			"index-faces":                       {"CollectionId", "Image"},
			"list-collections":                  {},
			"list-dataset-entries":              {"DatasetArn"},
			"list-dataset-labels":               {"DatasetArn"},
			"list-faces":                        {"CollectionId"},
			"list-media-analysis-jobs":          {},
			"list-project-policies":             {"ProjectArn"},
			"list-stream-processors":            {},
			"list-tags-for-resource":            {"ResourceArn"},
			"list-users":                        {"CollectionId"},
			"put-project-policy":                {"PolicyDocument", "PolicyName", "ProjectArn"},
			"recognize-celebrities":             {"Image"},
			"search-faces":                      {"CollectionId", "FaceId"},
			"search-faces-by-image":             {"CollectionId", "Image"},
			"search-users":                      {"CollectionId"},
			"search-users-by-image":             {"CollectionId", "Image"},
			"start-celebrity-recognition":       {"Video"},
			"start-content-moderation":          {"Video"},
			"start-face-detection":              {"Video"},
			"start-face-search":                 {"CollectionId", "Video"},
			"start-label-detection":             {"Video"},
			"start-media-analysis-job":          {"Input", "OperationsConfig", "OutputConfig"},
			"start-person-tracking":             {"Video"},
			"start-project-version":             {"MinInferenceUnits", "ProjectVersionArn"},
			"start-segment-detection":           {"SegmentTypes", "Video"},
			"start-stream-processor":            {"Name"},
			"start-text-detection":              {"Video"},
			"stop-project-version":              {"ProjectVersionArn"},
			"stop-stream-processor":             {"Name"},
			"tag-resource":                      {"ResourceArn", "Tags"},
			"untag-resource":                    {"ResourceArn", "TagKeys"},
			"update-dataset-entries":            {"Changes", "DatasetArn"},
			"update-stream-processor":           {"Name"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("rekognition", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
