package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/cloudwatchevents/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"activate-event-source", "cancel-replay", "create-api-destination", "create-archive", "create-connection", "create-event-bus", "create-partner-event-source", "deactivate-event-source", "deauthorize-connection", "delete-api-destination", "delete-archive", "delete-connection", "delete-event-bus", "delete-partner-event-source", "delete-rule", "describe-api-destination", "describe-archive", "describe-connection", "describe-event-bus", "describe-event-source", "describe-partner-event-source", "describe-replay", "describe-rule", "disable-rule", "enable-rule", "list-api-destinations", "list-archives", "list-connections", "list-event-buses", "list-event-sources", "list-partner-event-source-accounts", "list-partner-event-sources", "list-replays", "list-rule-names-by-target", "list-rules", "list-tags-for-resource", "list-targets-by-rule", "put-events", "put-partner-events", "put-permission", "put-rule", "put-targets", "remove-permission", "remove-targets", "start-replay", "tag-resource", "test-event-pattern", "untag-resource", "update-api-destination", "update-archive", "update-connection"},
		OperationSet: map[string]bool{"activate-event-source": true, "cancel-replay": true, "create-api-destination": true, "create-archive": true, "create-connection": true, "create-event-bus": true, "create-partner-event-source": true, "deactivate-event-source": true, "deauthorize-connection": true, "delete-api-destination": true, "delete-archive": true, "delete-connection": true, "delete-event-bus": true, "delete-partner-event-source": true, "delete-rule": true, "describe-api-destination": true, "describe-archive": true, "describe-connection": true, "describe-event-bus": true, "describe-event-source": true, "describe-partner-event-source": true, "describe-replay": true, "describe-rule": true, "disable-rule": true, "enable-rule": true, "list-api-destinations": true, "list-archives": true, "list-connections": true, "list-event-buses": true, "list-event-sources": true, "list-partner-event-source-accounts": true, "list-partner-event-sources": true, "list-replays": true, "list-rule-names-by-target": true, "list-rules": true, "list-tags-for-resource": true, "list-targets-by-rule": true, "put-events": true, "put-partner-events": true, "put-permission": true, "put-rule": true, "put-targets": true, "remove-permission": true, "remove-targets": true, "start-replay": true, "tag-resource": true, "test-event-pattern": true, "untag-resource": true, "update-api-destination": true, "update-archive": true, "update-connection": true},
		OperationInputs: map[string][]string{
			"activate-event-source":              {"Name"},
			"cancel-replay":                      {"ReplayName"},
			"create-api-destination":             {"ConnectionArn", "Description", "HttpMethod", "InvocationEndpoint", "InvocationRateLimitPerSecond", "Name"},
			"create-archive":                     {"ArchiveName", "Description", "EventPattern", "EventSourceArn", "RetentionDays"},
			"create-connection":                  {"AuthParameters", "AuthorizationType", "Description", "Name"},
			"create-event-bus":                   {"EventSourceName", "Name", "Tags"},
			"create-partner-event-source":        {"Account", "Name"},
			"deactivate-event-source":            {"Name"},
			"deauthorize-connection":             {"Name"},
			"delete-api-destination":             {"Name"},
			"delete-archive":                     {"ArchiveName"},
			"delete-connection":                  {"Name"},
			"delete-event-bus":                   {"Name"},
			"delete-partner-event-source":        {"Account", "Name"},
			"delete-rule":                        {"EventBusName", "Force", "Name"},
			"describe-api-destination":           {"Name"},
			"describe-archive":                   {"ArchiveName"},
			"describe-connection":                {"Name"},
			"describe-event-bus":                 {"Name"},
			"describe-event-source":              {"Name"},
			"describe-partner-event-source":      {"Name"},
			"describe-replay":                    {"ReplayName"},
			"describe-rule":                      {"EventBusName", "Name"},
			"disable-rule":                       {"EventBusName", "Name"},
			"enable-rule":                        {"EventBusName", "Name"},
			"list-api-destinations":              {"ConnectionArn", "Limit", "NamePrefix", "NextToken"},
			"list-archives":                      {"EventSourceArn", "Limit", "NamePrefix", "NextToken", "State"},
			"list-connections":                   {"ConnectionState", "Limit", "NamePrefix", "NextToken"},
			"list-event-buses":                   {"Limit", "NamePrefix", "NextToken"},
			"list-event-sources":                 {"Limit", "NamePrefix", "NextToken"},
			"list-partner-event-source-accounts": {"EventSourceName", "Limit", "NextToken"},
			"list-partner-event-sources":         {"Limit", "NamePrefix", "NextToken"},
			"list-replays":                       {"EventSourceArn", "Limit", "NamePrefix", "NextToken", "State"},
			"list-rule-names-by-target":          {"EventBusName", "Limit", "NextToken", "TargetArn"},
			"list-rules":                         {"EventBusName", "Limit", "NamePrefix", "NextToken"},
			"list-tags-for-resource":             {"ResourceARN"},
			"list-targets-by-rule":               {"EventBusName", "Limit", "NextToken", "Rule"},
			"put-events":                         {"Entries"},
			"put-partner-events":                 {"Entries"},
			"put-permission":                     {"Action", "Condition", "EventBusName", "Policy", "Principal", "StatementId"},
			"put-rule":                           {"Description", "EventBusName", "EventPattern", "Name", "RoleArn", "ScheduleExpression", "State", "Tags"},
			"put-targets":                        {"EventBusName", "Rule", "Targets"},
			"remove-permission":                  {"EventBusName", "RemoveAllPermissions", "StatementId"},
			"remove-targets":                     {"EventBusName", "Force", "Ids", "Rule"},
			"start-replay":                       {"Description", "Destination", "EventEndTime", "EventSourceArn", "EventStartTime", "ReplayName"},
			"tag-resource":                       {"ResourceARN", "Tags"},
			"test-event-pattern":                 {"Event", "EventPattern"},
			"untag-resource":                     {"ResourceARN", "TagKeys"},
			"update-api-destination":             {"ConnectionArn", "Description", "HttpMethod", "InvocationEndpoint", "InvocationRateLimitPerSecond", "Name"},
			"update-archive":                     {"ArchiveName", "Description", "EventPattern", "RetentionDays"},
			"update-connection":                  {"AuthParameters", "AuthorizationType", "Description", "Name"},
		},
		OperationInputTypes: map[string]map[string]string{
			"activate-event-source":              {"Name": "*string"},
			"cancel-replay":                      {"ReplayName": "*string"},
			"create-api-destination":             {"ConnectionArn": "*string", "Description": "*string", "HttpMethod": "types.ApiDestinationHttpMethod", "InvocationEndpoint": "*string", "InvocationRateLimitPerSecond": "*int32", "Name": "*string"},
			"create-archive":                     {"ArchiveName": "*string", "Description": "*string", "EventPattern": "*string", "EventSourceArn": "*string", "RetentionDays": "*int32"},
			"create-connection":                  {"AuthParameters": "*types.CreateConnectionAuthRequestParameters", "AuthorizationType": "types.ConnectionAuthorizationType", "Description": "*string", "Name": "*string"},
			"create-event-bus":                   {"EventSourceName": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"create-partner-event-source":        {"Account": "*string", "Name": "*string"},
			"deactivate-event-source":            {"Name": "*string"},
			"deauthorize-connection":             {"Name": "*string"},
			"delete-api-destination":             {"Name": "*string"},
			"delete-archive":                     {"ArchiveName": "*string"},
			"delete-connection":                  {"Name": "*string"},
			"delete-event-bus":                   {"Name": "*string"},
			"delete-partner-event-source":        {"Account": "*string", "Name": "*string"},
			"delete-rule":                        {"EventBusName": "*string", "Force": "bool", "Name": "*string"},
			"describe-api-destination":           {"Name": "*string"},
			"describe-archive":                   {"ArchiveName": "*string"},
			"describe-connection":                {"Name": "*string"},
			"describe-event-bus":                 {"Name": "*string"},
			"describe-event-source":              {"Name": "*string"},
			"describe-partner-event-source":      {"Name": "*string"},
			"describe-replay":                    {"ReplayName": "*string"},
			"describe-rule":                      {"EventBusName": "*string", "Name": "*string"},
			"disable-rule":                       {"EventBusName": "*string", "Name": "*string"},
			"enable-rule":                        {"EventBusName": "*string", "Name": "*string"},
			"list-api-destinations":              {"ConnectionArn": "*string", "Limit": "*int32", "NamePrefix": "*string", "NextToken": "*string"},
			"list-archives":                      {"EventSourceArn": "*string", "Limit": "*int32", "NamePrefix": "*string", "NextToken": "*string", "State": "types.ArchiveState"},
			"list-connections":                   {"ConnectionState": "types.ConnectionState", "Limit": "*int32", "NamePrefix": "*string", "NextToken": "*string"},
			"list-event-buses":                   {"Limit": "*int32", "NamePrefix": "*string", "NextToken": "*string"},
			"list-event-sources":                 {"Limit": "*int32", "NamePrefix": "*string", "NextToken": "*string"},
			"list-partner-event-source-accounts": {"EventSourceName": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-partner-event-sources":         {"Limit": "*int32", "NamePrefix": "*string", "NextToken": "*string"},
			"list-replays":                       {"EventSourceArn": "*string", "Limit": "*int32", "NamePrefix": "*string", "NextToken": "*string", "State": "types.ReplayState"},
			"list-rule-names-by-target":          {"EventBusName": "*string", "Limit": "*int32", "NextToken": "*string", "TargetArn": "*string"},
			"list-rules":                         {"EventBusName": "*string", "Limit": "*int32", "NamePrefix": "*string", "NextToken": "*string"},
			"list-tags-for-resource":             {"ResourceARN": "*string"},
			"list-targets-by-rule":               {"EventBusName": "*string", "Limit": "*int32", "NextToken": "*string", "Rule": "*string"},
			"put-events":                         {"Entries": "[]types.PutEventsRequestEntry"},
			"put-partner-events":                 {"Entries": "[]types.PutPartnerEventsRequestEntry"},
			"put-permission":                     {"Action": "*string", "Condition": "*types.Condition", "EventBusName": "*string", "Policy": "*string", "Principal": "*string", "StatementId": "*string"},
			"put-rule":                           {"Description": "*string", "EventBusName": "*string", "EventPattern": "*string", "Name": "*string", "RoleArn": "*string", "ScheduleExpression": "*string", "State": "types.RuleState", "Tags": "[]types.Tag"},
			"put-targets":                        {"EventBusName": "*string", "Rule": "*string", "Targets": "[]types.Target"},
			"remove-permission":                  {"EventBusName": "*string", "RemoveAllPermissions": "bool", "StatementId": "*string"},
			"remove-targets":                     {"EventBusName": "*string", "Force": "bool", "Ids": "[]string", "Rule": "*string"},
			"start-replay":                       {"Description": "*string", "Destination": "*types.ReplayDestination", "EventEndTime": "*time.Time", "EventSourceArn": "*string", "EventStartTime": "*time.Time", "ReplayName": "*string"},
			"tag-resource":                       {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"test-event-pattern":                 {"Event": "*string", "EventPattern": "*string"},
			"untag-resource":                     {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-api-destination":             {"ConnectionArn": "*string", "Description": "*string", "HttpMethod": "types.ApiDestinationHttpMethod", "InvocationEndpoint": "*string", "InvocationRateLimitPerSecond": "*int32", "Name": "*string"},
			"update-archive":                     {"ArchiveName": "*string", "Description": "*string", "EventPattern": "*string", "RetentionDays": "*int32"},
			"update-connection":                  {"AuthParameters": "*types.UpdateConnectionAuthRequestParameters", "AuthorizationType": "types.ConnectionAuthorizationType", "Description": "*string", "Name": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"activate-event-source":              {"Name"},
			"cancel-replay":                      {"ReplayName"},
			"create-api-destination":             {"ConnectionArn", "HttpMethod", "InvocationEndpoint", "Name"},
			"create-archive":                     {"ArchiveName", "EventSourceArn"},
			"create-connection":                  {"AuthParameters", "AuthorizationType", "Name"},
			"create-event-bus":                   {"Name"},
			"create-partner-event-source":        {"Account", "Name"},
			"deactivate-event-source":            {"Name"},
			"deauthorize-connection":             {"Name"},
			"delete-api-destination":             {"Name"},
			"delete-archive":                     {"ArchiveName"},
			"delete-connection":                  {"Name"},
			"delete-event-bus":                   {"Name"},
			"delete-partner-event-source":        {"Account", "Name"},
			"delete-rule":                        {"Name"},
			"describe-api-destination":           {"Name"},
			"describe-archive":                   {"ArchiveName"},
			"describe-connection":                {"Name"},
			"describe-event-bus":                 {},
			"describe-event-source":              {"Name"},
			"describe-partner-event-source":      {"Name"},
			"describe-replay":                    {"ReplayName"},
			"describe-rule":                      {"Name"},
			"disable-rule":                       {"Name"},
			"enable-rule":                        {"Name"},
			"list-api-destinations":              {},
			"list-archives":                      {},
			"list-connections":                   {},
			"list-event-buses":                   {},
			"list-event-sources":                 {},
			"list-partner-event-source-accounts": {"EventSourceName"},
			"list-partner-event-sources":         {"NamePrefix"},
			"list-replays":                       {},
			"list-rule-names-by-target":          {"TargetArn"},
			"list-rules":                         {},
			"list-tags-for-resource":             {"ResourceARN"},
			"list-targets-by-rule":               {"Rule"},
			"put-events":                         {"Entries"},
			"put-partner-events":                 {"Entries"},
			"put-permission":                     {},
			"put-rule":                           {"Name"},
			"put-targets":                        {"Rule", "Targets"},
			"remove-permission":                  {},
			"remove-targets":                     {"Ids", "Rule"},
			"start-replay":                       {"Destination", "EventEndTime", "EventSourceArn", "EventStartTime", "ReplayName"},
			"tag-resource":                       {"ResourceARN", "Tags"},
			"test-event-pattern":                 {"Event", "EventPattern"},
			"untag-resource":                     {"ResourceARN", "TagKeys"},
			"update-api-destination":             {"Name"},
			"update-archive":                     {"ArchiveName"},
			"update-connection":                  {"Name"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("cloudwatchevents", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
