package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/cleanroomsml/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"cancel-trained-model", "cancel-trained-model-inference-job", "create-audience-model", "create-configured-audience-model", "create-configured-model-algorithm", "create-configured-model-algorithm-association", "create-ml-input-channel", "create-trained-model", "create-training-dataset", "delete-audience-generation-job", "delete-audience-model", "delete-configured-audience-model", "delete-configured-audience-model-policy", "delete-configured-model-algorithm", "delete-configured-model-algorithm-association", "delete-ml-configuration", "delete-ml-input-channel-data", "delete-trained-model-output", "delete-training-dataset", "get-audience-generation-job", "get-audience-model", "get-collaboration-configured-model-algorithm-association", "get-collaboration-ml-input-channel", "get-collaboration-trained-model", "get-configured-audience-model", "get-configured-audience-model-policy", "get-configured-model-algorithm", "get-configured-model-algorithm-association", "get-ml-configuration", "get-ml-input-channel", "get-trained-model", "get-trained-model-inference-job", "get-training-dataset", "list-audience-export-jobs", "list-audience-generation-jobs", "list-audience-models", "list-collaboration-configured-model-algorithm-associations", "list-collaboration-ml-input-channels", "list-collaboration-trained-model-export-jobs", "list-collaboration-trained-model-inference-jobs", "list-collaboration-trained-models", "list-configured-audience-models", "list-configured-model-algorithm-associations", "list-configured-model-algorithms", "list-ml-input-channels", "list-tags-for-resource", "list-trained-model-inference-jobs", "list-trained-model-versions", "list-trained-models", "list-training-datasets", "put-configured-audience-model-policy", "put-ml-configuration", "start-audience-export-job", "start-audience-generation-job", "start-trained-model-export-job", "start-trained-model-inference-job", "tag-resource", "untag-resource", "update-configured-audience-model"},
		OperationSet: map[string]bool{"cancel-trained-model": true, "cancel-trained-model-inference-job": true, "create-audience-model": true, "create-configured-audience-model": true, "create-configured-model-algorithm": true, "create-configured-model-algorithm-association": true, "create-ml-input-channel": true, "create-trained-model": true, "create-training-dataset": true, "delete-audience-generation-job": true, "delete-audience-model": true, "delete-configured-audience-model": true, "delete-configured-audience-model-policy": true, "delete-configured-model-algorithm": true, "delete-configured-model-algorithm-association": true, "delete-ml-configuration": true, "delete-ml-input-channel-data": true, "delete-trained-model-output": true, "delete-training-dataset": true, "get-audience-generation-job": true, "get-audience-model": true, "get-collaboration-configured-model-algorithm-association": true, "get-collaboration-ml-input-channel": true, "get-collaboration-trained-model": true, "get-configured-audience-model": true, "get-configured-audience-model-policy": true, "get-configured-model-algorithm": true, "get-configured-model-algorithm-association": true, "get-ml-configuration": true, "get-ml-input-channel": true, "get-trained-model": true, "get-trained-model-inference-job": true, "get-training-dataset": true, "list-audience-export-jobs": true, "list-audience-generation-jobs": true, "list-audience-models": true, "list-collaboration-configured-model-algorithm-associations": true, "list-collaboration-ml-input-channels": true, "list-collaboration-trained-model-export-jobs": true, "list-collaboration-trained-model-inference-jobs": true, "list-collaboration-trained-models": true, "list-configured-audience-models": true, "list-configured-model-algorithm-associations": true, "list-configured-model-algorithms": true, "list-ml-input-channels": true, "list-tags-for-resource": true, "list-trained-model-inference-jobs": true, "list-trained-model-versions": true, "list-trained-models": true, "list-training-datasets": true, "put-configured-audience-model-policy": true, "put-ml-configuration": true, "start-audience-export-job": true, "start-audience-generation-job": true, "start-trained-model-export-job": true, "start-trained-model-inference-job": true, "tag-resource": true, "untag-resource": true, "update-configured-audience-model": true},
		OperationInputs: map[string][]string{
			"cancel-trained-model":                                       {"MembershipIdentifier", "TrainedModelArn", "VersionIdentifier"},
			"cancel-trained-model-inference-job":                         {"MembershipIdentifier", "TrainedModelInferenceJobArn"},
			"create-audience-model":                                      {"Description", "KmsKeyArn", "Name", "Tags", "TrainingDataEndTime", "TrainingDataStartTime", "TrainingDatasetArn"},
			"create-configured-audience-model":                           {"AudienceModelArn", "AudienceSizeConfig", "ChildResourceTagOnCreatePolicy", "Description", "MinMatchingSeedSize", "Name", "OutputConfig", "SharedAudienceMetrics", "Tags"},
			"create-configured-model-algorithm":                          {"Description", "InferenceContainerConfig", "KmsKeyArn", "Name", "RoleArn", "Tags", "TrainingContainerConfig"},
			"create-configured-model-algorithm-association":              {"ConfiguredModelAlgorithmArn", "Description", "MembershipIdentifier", "Name", "PrivacyConfiguration", "Tags"},
			"create-ml-input-channel":                                    {"ConfiguredModelAlgorithmAssociations", "Description", "InputChannel", "KmsKeyArn", "MembershipIdentifier", "Name", "RetentionInDays", "Tags"},
			"create-trained-model":                                       {"ConfiguredModelAlgorithmAssociationArn", "DataChannels", "Description", "Environment", "Hyperparameters", "IncrementalTrainingDataChannels", "KmsKeyArn", "MembershipIdentifier", "Name", "ResourceConfig", "StoppingCondition", "Tags", "TrainingInputMode"},
			"create-training-dataset":                                    {"Description", "Name", "RoleArn", "Tags", "TrainingData"},
			"delete-audience-generation-job":                             {"AudienceGenerationJobArn"},
			"delete-audience-model":                                      {"AudienceModelArn"},
			"delete-configured-audience-model":                           {"ConfiguredAudienceModelArn"},
			"delete-configured-audience-model-policy":                    {"ConfiguredAudienceModelArn"},
			"delete-configured-model-algorithm":                          {"ConfiguredModelAlgorithmArn"},
			"delete-configured-model-algorithm-association":              {"ConfiguredModelAlgorithmAssociationArn", "MembershipIdentifier"},
			"delete-ml-configuration":                                    {"MembershipIdentifier"},
			"delete-ml-input-channel-data":                               {"MembershipIdentifier", "MlInputChannelArn"},
			"delete-trained-model-output":                                {"MembershipIdentifier", "TrainedModelArn", "VersionIdentifier"},
			"delete-training-dataset":                                    {"TrainingDatasetArn"},
			"get-audience-generation-job":                                {"AudienceGenerationJobArn"},
			"get-audience-model":                                         {"AudienceModelArn"},
			"get-collaboration-configured-model-algorithm-association":   {"CollaborationIdentifier", "ConfiguredModelAlgorithmAssociationArn"},
			"get-collaboration-ml-input-channel":                         {"CollaborationIdentifier", "MlInputChannelArn"},
			"get-collaboration-trained-model":                            {"CollaborationIdentifier", "TrainedModelArn", "VersionIdentifier"},
			"get-configured-audience-model":                              {"ConfiguredAudienceModelArn"},
			"get-configured-audience-model-policy":                       {"ConfiguredAudienceModelArn"},
			"get-configured-model-algorithm":                             {"ConfiguredModelAlgorithmArn"},
			"get-configured-model-algorithm-association":                 {"ConfiguredModelAlgorithmAssociationArn", "MembershipIdentifier"},
			"get-ml-configuration":                                       {"MembershipIdentifier"},
			"get-ml-input-channel":                                       {"MembershipIdentifier", "MlInputChannelArn"},
			"get-trained-model":                                          {"MembershipIdentifier", "TrainedModelArn", "VersionIdentifier"},
			"get-trained-model-inference-job":                            {"MembershipIdentifier", "TrainedModelInferenceJobArn"},
			"get-training-dataset":                                       {"TrainingDatasetArn"},
			"list-audience-export-jobs":                                  {"AudienceGenerationJobArn", "MaxResults", "NextToken"},
			"list-audience-generation-jobs":                              {"CollaborationId", "ConfiguredAudienceModelArn", "MaxResults", "NextToken"},
			"list-audience-models":                                       {"MaxResults", "NextToken"},
			"list-collaboration-configured-model-algorithm-associations": {"CollaborationIdentifier", "MaxResults", "NextToken"},
			"list-collaboration-ml-input-channels":                       {"CollaborationIdentifier", "MaxResults", "NextToken"},
			"list-collaboration-trained-model-export-jobs":               {"CollaborationIdentifier", "MaxResults", "NextToken", "TrainedModelArn", "TrainedModelVersionIdentifier"},
			"list-collaboration-trained-model-inference-jobs":            {"CollaborationIdentifier", "MaxResults", "NextToken", "TrainedModelArn", "TrainedModelVersionIdentifier"},
			"list-collaboration-trained-models":                          {"CollaborationIdentifier", "MaxResults", "NextToken"},
			"list-configured-audience-models":                            {"MaxResults", "NextToken"},
			"list-configured-model-algorithm-associations":               {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-configured-model-algorithms":                           {"MaxResults", "NextToken"},
			"list-ml-input-channels":                                     {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-tags-for-resource":                                     {"ResourceArn"},
			"list-trained-model-inference-jobs":                          {"MaxResults", "MembershipIdentifier", "NextToken", "TrainedModelArn", "TrainedModelVersionIdentifier"},
			"list-trained-model-versions":                                {"MaxResults", "MembershipIdentifier", "NextToken", "Status", "TrainedModelArn"},
			"list-trained-models":                                        {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-training-datasets":                                     {"MaxResults", "NextToken"},
			"put-configured-audience-model-policy":                       {"ConfiguredAudienceModelArn", "ConfiguredAudienceModelPolicy", "PolicyExistenceCondition", "PreviousPolicyHash"},
			"put-ml-configuration":                                       {"DefaultOutputLocation", "MembershipIdentifier"},
			"start-audience-export-job":                                  {"AudienceGenerationJobArn", "AudienceSize", "Description", "Name"},
			"start-audience-generation-job":                              {"CollaborationId", "ConfiguredAudienceModelArn", "Description", "IncludeSeedInOutput", "Name", "SeedAudience", "Tags"},
			"start-trained-model-export-job":                             {"Description", "MembershipIdentifier", "Name", "OutputConfiguration", "TrainedModelArn", "TrainedModelVersionIdentifier"},
			"start-trained-model-inference-job":                          {"ConfiguredModelAlgorithmAssociationArn", "ContainerExecutionParameters", "DataSource", "Description", "Environment", "KmsKeyArn", "MembershipIdentifier", "Name", "OutputConfiguration", "ResourceConfig", "Tags", "TrainedModelArn", "TrainedModelVersionIdentifier"},
			"tag-resource":                                               {"ResourceArn", "Tags"},
			"untag-resource":                                             {"ResourceArn", "TagKeys"},
			"update-configured-audience-model":                           {"AudienceModelArn", "AudienceSizeConfig", "ConfiguredAudienceModelArn", "Description", "MinMatchingSeedSize", "OutputConfig", "SharedAudienceMetrics"},
		},
		OperationInputTypes: map[string]map[string]string{
			"cancel-trained-model":                                       {"MembershipIdentifier": "*string", "TrainedModelArn": "*string", "VersionIdentifier": "*string"},
			"cancel-trained-model-inference-job":                         {"MembershipIdentifier": "*string", "TrainedModelInferenceJobArn": "*string"},
			"create-audience-model":                                      {"Description": "*string", "KmsKeyArn": "*string", "Name": "*string", "Tags": "map[string]string", "TrainingDataEndTime": "*time.Time", "TrainingDataStartTime": "*time.Time", "TrainingDatasetArn": "*string"},
			"create-configured-audience-model":                           {"AudienceModelArn": "*string", "AudienceSizeConfig": "*types.AudienceSizeConfig", "ChildResourceTagOnCreatePolicy": "types.TagOnCreatePolicy", "Description": "*string", "MinMatchingSeedSize": "*int32", "Name": "*string", "OutputConfig": "*types.ConfiguredAudienceModelOutputConfig", "SharedAudienceMetrics": "[]types.SharedAudienceMetrics", "Tags": "map[string]string"},
			"create-configured-model-algorithm":                          {"Description": "*string", "InferenceContainerConfig": "*types.InferenceContainerConfig", "KmsKeyArn": "*string", "Name": "*string", "RoleArn": "*string", "Tags": "map[string]string", "TrainingContainerConfig": "*types.ContainerConfig"},
			"create-configured-model-algorithm-association":              {"ConfiguredModelAlgorithmArn": "*string", "Description": "*string", "MembershipIdentifier": "*string", "Name": "*string", "PrivacyConfiguration": "*types.PrivacyConfiguration", "Tags": "map[string]string"},
			"create-ml-input-channel":                                    {"ConfiguredModelAlgorithmAssociations": "[]string", "Description": "*string", "InputChannel": "*types.InputChannel", "KmsKeyArn": "*string", "MembershipIdentifier": "*string", "Name": "*string", "RetentionInDays": "*int32", "Tags": "map[string]string"},
			"create-trained-model":                                       {"ConfiguredModelAlgorithmAssociationArn": "*string", "DataChannels": "[]types.ModelTrainingDataChannel", "Description": "*string", "Environment": "map[string]string", "Hyperparameters": "map[string]string", "IncrementalTrainingDataChannels": "[]types.IncrementalTrainingDataChannel", "KmsKeyArn": "*string", "MembershipIdentifier": "*string", "Name": "*string", "ResourceConfig": "*types.ResourceConfig", "StoppingCondition": "*types.StoppingCondition", "Tags": "map[string]string", "TrainingInputMode": "types.TrainingInputMode"},
			"create-training-dataset":                                    {"Description": "*string", "Name": "*string", "RoleArn": "*string", "Tags": "map[string]string", "TrainingData": "[]types.Dataset"},
			"delete-audience-generation-job":                             {"AudienceGenerationJobArn": "*string"},
			"delete-audience-model":                                      {"AudienceModelArn": "*string"},
			"delete-configured-audience-model":                           {"ConfiguredAudienceModelArn": "*string"},
			"delete-configured-audience-model-policy":                    {"ConfiguredAudienceModelArn": "*string"},
			"delete-configured-model-algorithm":                          {"ConfiguredModelAlgorithmArn": "*string"},
			"delete-configured-model-algorithm-association":              {"ConfiguredModelAlgorithmAssociationArn": "*string", "MembershipIdentifier": "*string"},
			"delete-ml-configuration":                                    {"MembershipIdentifier": "*string"},
			"delete-ml-input-channel-data":                               {"MembershipIdentifier": "*string", "MlInputChannelArn": "*string"},
			"delete-trained-model-output":                                {"MembershipIdentifier": "*string", "TrainedModelArn": "*string", "VersionIdentifier": "*string"},
			"delete-training-dataset":                                    {"TrainingDatasetArn": "*string"},
			"get-audience-generation-job":                                {"AudienceGenerationJobArn": "*string"},
			"get-audience-model":                                         {"AudienceModelArn": "*string"},
			"get-collaboration-configured-model-algorithm-association":   {"CollaborationIdentifier": "*string", "ConfiguredModelAlgorithmAssociationArn": "*string"},
			"get-collaboration-ml-input-channel":                         {"CollaborationIdentifier": "*string", "MlInputChannelArn": "*string"},
			"get-collaboration-trained-model":                            {"CollaborationIdentifier": "*string", "TrainedModelArn": "*string", "VersionIdentifier": "*string"},
			"get-configured-audience-model":                              {"ConfiguredAudienceModelArn": "*string"},
			"get-configured-audience-model-policy":                       {"ConfiguredAudienceModelArn": "*string"},
			"get-configured-model-algorithm":                             {"ConfiguredModelAlgorithmArn": "*string"},
			"get-configured-model-algorithm-association":                 {"ConfiguredModelAlgorithmAssociationArn": "*string", "MembershipIdentifier": "*string"},
			"get-ml-configuration":                                       {"MembershipIdentifier": "*string"},
			"get-ml-input-channel":                                       {"MembershipIdentifier": "*string", "MlInputChannelArn": "*string"},
			"get-trained-model":                                          {"MembershipIdentifier": "*string", "TrainedModelArn": "*string", "VersionIdentifier": "*string"},
			"get-trained-model-inference-job":                            {"MembershipIdentifier": "*string", "TrainedModelInferenceJobArn": "*string"},
			"get-training-dataset":                                       {"TrainingDatasetArn": "*string"},
			"list-audience-export-jobs":                                  {"AudienceGenerationJobArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-audience-generation-jobs":                              {"CollaborationId": "*string", "ConfiguredAudienceModelArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-audience-models":                                       {"MaxResults": "*int32", "NextToken": "*string"},
			"list-collaboration-configured-model-algorithm-associations": {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-collaboration-ml-input-channels":                       {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-collaboration-trained-model-export-jobs":               {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "TrainedModelArn": "*string", "TrainedModelVersionIdentifier": "*string"},
			"list-collaboration-trained-model-inference-jobs":            {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "TrainedModelArn": "*string", "TrainedModelVersionIdentifier": "*string"},
			"list-collaboration-trained-models":                          {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-configured-audience-models":                            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-configured-model-algorithm-associations":               {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-configured-model-algorithms":                           {"MaxResults": "*int32", "NextToken": "*string"},
			"list-ml-input-channels":                                     {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-tags-for-resource":                                     {"ResourceArn": "*string"},
			"list-trained-model-inference-jobs":                          {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string", "TrainedModelArn": "*string", "TrainedModelVersionIdentifier": "*string"},
			"list-trained-model-versions":                                {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string", "Status": "types.TrainedModelStatus", "TrainedModelArn": "*string"},
			"list-trained-models":                                        {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-training-datasets":                                     {"MaxResults": "*int32", "NextToken": "*string"},
			"put-configured-audience-model-policy":                       {"ConfiguredAudienceModelArn": "*string", "ConfiguredAudienceModelPolicy": "*string", "PolicyExistenceCondition": "types.PolicyExistenceCondition", "PreviousPolicyHash": "*string"},
			"put-ml-configuration":                                       {"DefaultOutputLocation": "*types.MLOutputConfiguration", "MembershipIdentifier": "*string"},
			"start-audience-export-job":                                  {"AudienceGenerationJobArn": "*string", "AudienceSize": "*types.AudienceSize", "Description": "*string", "Name": "*string"},
			"start-audience-generation-job":                              {"CollaborationId": "*string", "ConfiguredAudienceModelArn": "*string", "Description": "*string", "IncludeSeedInOutput": "bool", "Name": "*string", "SeedAudience": "*types.AudienceGenerationJobDataSource", "Tags": "map[string]string"},
			"start-trained-model-export-job":                             {"Description": "*string", "MembershipIdentifier": "*string", "Name": "*string", "OutputConfiguration": "*types.TrainedModelExportOutputConfiguration", "TrainedModelArn": "*string", "TrainedModelVersionIdentifier": "*string"},
			"start-trained-model-inference-job":                          {"ConfiguredModelAlgorithmAssociationArn": "*string", "ContainerExecutionParameters": "*types.InferenceContainerExecutionParameters", "DataSource": "*types.ModelInferenceDataSource", "Description": "*string", "Environment": "map[string]string", "KmsKeyArn": "*string", "MembershipIdentifier": "*string", "Name": "*string", "OutputConfiguration": "*types.InferenceOutputConfiguration", "ResourceConfig": "*types.InferenceResourceConfig", "Tags": "map[string]string", "TrainedModelArn": "*string", "TrainedModelVersionIdentifier": "*string"},
			"tag-resource":                                               {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                                             {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-configured-audience-model":                           {"AudienceModelArn": "*string", "AudienceSizeConfig": "*types.AudienceSizeConfig", "ConfiguredAudienceModelArn": "*string", "Description": "*string", "MinMatchingSeedSize": "*int32", "OutputConfig": "*types.ConfiguredAudienceModelOutputConfig", "SharedAudienceMetrics": "[]types.SharedAudienceMetrics"},
		},
		OperationInputRequired: map[string][]string{
			"cancel-trained-model":                                       {"MembershipIdentifier", "TrainedModelArn"},
			"cancel-trained-model-inference-job":                         {"MembershipIdentifier", "TrainedModelInferenceJobArn"},
			"create-audience-model":                                      {"Name", "TrainingDatasetArn"},
			"create-configured-audience-model":                           {"AudienceModelArn", "Name", "OutputConfig", "SharedAudienceMetrics"},
			"create-configured-model-algorithm":                          {"Name", "RoleArn"},
			"create-configured-model-algorithm-association":              {"ConfiguredModelAlgorithmArn", "MembershipIdentifier", "Name"},
			"create-ml-input-channel":                                    {"ConfiguredModelAlgorithmAssociations", "InputChannel", "MembershipIdentifier", "Name", "RetentionInDays"},
			"create-trained-model":                                       {"ConfiguredModelAlgorithmAssociationArn", "DataChannels", "MembershipIdentifier", "Name", "ResourceConfig"},
			"create-training-dataset":                                    {"Name", "RoleArn", "TrainingData"},
			"delete-audience-generation-job":                             {"AudienceGenerationJobArn"},
			"delete-audience-model":                                      {"AudienceModelArn"},
			"delete-configured-audience-model":                           {"ConfiguredAudienceModelArn"},
			"delete-configured-audience-model-policy":                    {"ConfiguredAudienceModelArn"},
			"delete-configured-model-algorithm":                          {"ConfiguredModelAlgorithmArn"},
			"delete-configured-model-algorithm-association":              {"ConfiguredModelAlgorithmAssociationArn", "MembershipIdentifier"},
			"delete-ml-configuration":                                    {"MembershipIdentifier"},
			"delete-ml-input-channel-data":                               {"MembershipIdentifier", "MlInputChannelArn"},
			"delete-trained-model-output":                                {"MembershipIdentifier", "TrainedModelArn"},
			"delete-training-dataset":                                    {"TrainingDatasetArn"},
			"get-audience-generation-job":                                {"AudienceGenerationJobArn"},
			"get-audience-model":                                         {"AudienceModelArn"},
			"get-collaboration-configured-model-algorithm-association":   {"CollaborationIdentifier", "ConfiguredModelAlgorithmAssociationArn"},
			"get-collaboration-ml-input-channel":                         {"CollaborationIdentifier", "MlInputChannelArn"},
			"get-collaboration-trained-model":                            {"CollaborationIdentifier", "TrainedModelArn"},
			"get-configured-audience-model":                              {"ConfiguredAudienceModelArn"},
			"get-configured-audience-model-policy":                       {"ConfiguredAudienceModelArn"},
			"get-configured-model-algorithm":                             {"ConfiguredModelAlgorithmArn"},
			"get-configured-model-algorithm-association":                 {"ConfiguredModelAlgorithmAssociationArn", "MembershipIdentifier"},
			"get-ml-configuration":                                       {"MembershipIdentifier"},
			"get-ml-input-channel":                                       {"MembershipIdentifier", "MlInputChannelArn"},
			"get-trained-model":                                          {"MembershipIdentifier", "TrainedModelArn"},
			"get-trained-model-inference-job":                            {"MembershipIdentifier", "TrainedModelInferenceJobArn"},
			"get-training-dataset":                                       {"TrainingDatasetArn"},
			"list-audience-export-jobs":                                  {},
			"list-audience-generation-jobs":                              {},
			"list-audience-models":                                       {},
			"list-collaboration-configured-model-algorithm-associations": {"CollaborationIdentifier"},
			"list-collaboration-ml-input-channels":                       {"CollaborationIdentifier"},
			"list-collaboration-trained-model-export-jobs":               {"CollaborationIdentifier", "TrainedModelArn"},
			"list-collaboration-trained-model-inference-jobs":            {"CollaborationIdentifier"},
			"list-collaboration-trained-models":                          {"CollaborationIdentifier"},
			"list-configured-audience-models":                            {},
			"list-configured-model-algorithm-associations":               {"MembershipIdentifier"},
			"list-configured-model-algorithms":                           {},
			"list-ml-input-channels":                                     {"MembershipIdentifier"},
			"list-tags-for-resource":                                     {"ResourceArn"},
			"list-trained-model-inference-jobs":                          {"MembershipIdentifier"},
			"list-trained-model-versions":                                {"MembershipIdentifier", "TrainedModelArn"},
			"list-trained-models":                                        {"MembershipIdentifier"},
			"list-training-datasets":                                     {},
			"put-configured-audience-model-policy":                       {"ConfiguredAudienceModelArn", "ConfiguredAudienceModelPolicy"},
			"put-ml-configuration":                                       {"DefaultOutputLocation", "MembershipIdentifier"},
			"start-audience-export-job":                                  {"AudienceGenerationJobArn", "AudienceSize", "Name"},
			"start-audience-generation-job":                              {"ConfiguredAudienceModelArn", "Name", "SeedAudience"},
			"start-trained-model-export-job":                             {"MembershipIdentifier", "Name", "OutputConfiguration", "TrainedModelArn"},
			"start-trained-model-inference-job":                          {"DataSource", "MembershipIdentifier", "Name", "OutputConfiguration", "ResourceConfig", "TrainedModelArn"},
			"tag-resource":                                               {"ResourceArn", "Tags"},
			"untag-resource":                                             {"ResourceArn", "TagKeys"},
			"update-configured-audience-model":                           {"ConfiguredAudienceModelArn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("cleanroomsml", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
