package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/emr/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-instance-fleet", "add-instance-groups", "add-job-flow-steps", "add-tags", "cancel-steps", "create-persistent-app-ui", "create-security-configuration", "create-studio", "create-studio-session-mapping", "delete-security-configuration", "delete-studio", "delete-studio-session-mapping", "describe-cluster", "describe-job-flows", "describe-notebook-execution", "describe-persistent-app-ui", "describe-release-label", "describe-security-configuration", "describe-step", "describe-studio", "get-auto-termination-policy", "get-block-public-access-configuration", "get-cluster-session-credentials", "get-managed-scaling-policy", "get-on-cluster-app-ui-presigned-url", "get-persistent-app-ui-presigned-url", "get-studio-session-mapping", "list-bootstrap-actions", "list-clusters", "list-instance-fleets", "list-instance-groups", "list-instances", "list-notebook-executions", "list-release-labels", "list-security-configurations", "list-steps", "list-studio-session-mappings", "list-studios", "list-supported-instance-types", "modify-cluster", "modify-instance-fleet", "modify-instance-groups", "put-auto-scaling-policy", "put-auto-termination-policy", "put-block-public-access-configuration", "put-managed-scaling-policy", "remove-auto-scaling-policy", "remove-auto-termination-policy", "remove-managed-scaling-policy", "remove-tags", "run-job-flow", "set-keep-job-flow-alive-when-no-steps", "set-termination-protection", "set-unhealthy-node-replacement", "set-visible-to-all-users", "start-notebook-execution", "stop-notebook-execution", "terminate-job-flows", "update-studio", "update-studio-session-mapping"},
		OperationSet: map[string]bool{"add-instance-fleet": true, "add-instance-groups": true, "add-job-flow-steps": true, "add-tags": true, "cancel-steps": true, "create-persistent-app-ui": true, "create-security-configuration": true, "create-studio": true, "create-studio-session-mapping": true, "delete-security-configuration": true, "delete-studio": true, "delete-studio-session-mapping": true, "describe-cluster": true, "describe-job-flows": true, "describe-notebook-execution": true, "describe-persistent-app-ui": true, "describe-release-label": true, "describe-security-configuration": true, "describe-step": true, "describe-studio": true, "get-auto-termination-policy": true, "get-block-public-access-configuration": true, "get-cluster-session-credentials": true, "get-managed-scaling-policy": true, "get-on-cluster-app-ui-presigned-url": true, "get-persistent-app-ui-presigned-url": true, "get-studio-session-mapping": true, "list-bootstrap-actions": true, "list-clusters": true, "list-instance-fleets": true, "list-instance-groups": true, "list-instances": true, "list-notebook-executions": true, "list-release-labels": true, "list-security-configurations": true, "list-steps": true, "list-studio-session-mappings": true, "list-studios": true, "list-supported-instance-types": true, "modify-cluster": true, "modify-instance-fleet": true, "modify-instance-groups": true, "put-auto-scaling-policy": true, "put-auto-termination-policy": true, "put-block-public-access-configuration": true, "put-managed-scaling-policy": true, "remove-auto-scaling-policy": true, "remove-auto-termination-policy": true, "remove-managed-scaling-policy": true, "remove-tags": true, "run-job-flow": true, "set-keep-job-flow-alive-when-no-steps": true, "set-termination-protection": true, "set-unhealthy-node-replacement": true, "set-visible-to-all-users": true, "start-notebook-execution": true, "stop-notebook-execution": true, "terminate-job-flows": true, "update-studio": true, "update-studio-session-mapping": true},
		OperationInputs: map[string][]string{
			"add-instance-fleet":                    {"ClusterId", "InstanceFleet"},
			"add-instance-groups":                   {"InstanceGroups", "JobFlowId"},
			"add-job-flow-steps":                    {"ExecutionRoleArn", "JobFlowId", "Steps"},
			"add-tags":                              {"ResourceId", "Tags"},
			"cancel-steps":                          {"ClusterId", "StepCancellationOption", "StepIds"},
			"create-persistent-app-ui":              {"EMRContainersConfig", "ProfilerType", "Tags", "TargetResourceArn", "XReferer"},
			"create-security-configuration":         {"Name", "SecurityConfiguration"},
			"create-studio":                         {"AuthMode", "DefaultS3Location", "Description", "EncryptionKeyArn", "EngineSecurityGroupId", "IdcInstanceArn", "IdcUserAssignment", "IdpAuthUrl", "IdpRelayStateParameterName", "Name", "ServiceRole", "SubnetIds", "Tags", "TrustedIdentityPropagationEnabled", "UserRole", "VpcId", "WorkspaceSecurityGroupId"},
			"create-studio-session-mapping":         {"IdentityId", "IdentityName", "IdentityType", "SessionPolicyArn", "StudioId"},
			"delete-security-configuration":         {"Name"},
			"delete-studio":                         {"StudioId"},
			"delete-studio-session-mapping":         {"IdentityId", "IdentityName", "IdentityType", "StudioId"},
			"describe-cluster":                      {"ClusterId"},
			"describe-job-flows":                    {"CreatedAfter", "CreatedBefore", "JobFlowIds", "JobFlowStates"},
			"describe-notebook-execution":           {"NotebookExecutionId"},
			"describe-persistent-app-ui":            {"PersistentAppUIId"},
			"describe-release-label":                {"MaxResults", "NextToken", "ReleaseLabel"},
			"describe-security-configuration":       {"Name"},
			"describe-step":                         {"ClusterId", "StepId"},
			"describe-studio":                       {"StudioId"},
			"get-auto-termination-policy":           {"ClusterId"},
			"get-block-public-access-configuration": {},
			"get-cluster-session-credentials":       {"ClusterId", "ExecutionRoleArn"},
			"get-managed-scaling-policy":            {"ClusterId"},
			"get-on-cluster-app-ui-presigned-url":   {"ApplicationId", "ClusterId", "DryRun", "ExecutionRoleArn", "OnClusterAppUIType"},
			"get-persistent-app-ui-presigned-url":   {"ApplicationId", "AuthProxyCall", "ExecutionRoleArn", "PersistentAppUIId", "PersistentAppUIType"},
			"get-studio-session-mapping":            {"IdentityId", "IdentityName", "IdentityType", "StudioId"},
			"list-bootstrap-actions":                {"ClusterId", "Marker"},
			"list-clusters":                         {"ClusterStates", "CreatedAfter", "CreatedBefore", "Marker"},
			"list-instance-fleets":                  {"ClusterId", "Marker"},
			"list-instance-groups":                  {"ClusterId", "Marker"},
			"list-instances":                        {"ClusterId", "InstanceFleetId", "InstanceFleetType", "InstanceGroupId", "InstanceGroupTypes", "InstanceStates", "Marker"},
			"list-notebook-executions":              {"EditorId", "ExecutionEngineId", "From", "Marker", "Status", "To"},
			"list-release-labels":                   {"Filters", "MaxResults", "NextToken"},
			"list-security-configurations":          {"Marker"},
			"list-steps":                            {"ClusterId", "Marker", "StepIds", "StepStates"},
			"list-studio-session-mappings":          {"IdentityType", "Marker", "StudioId"},
			"list-studios":                          {"Marker"},
			"list-supported-instance-types":         {"Marker", "ReleaseLabel"},
			"modify-cluster":                        {"ClusterId", "ExtendedSupport", "StepConcurrencyLevel"},
			"modify-instance-fleet":                 {"ClusterId", "InstanceFleet"},
			"modify-instance-groups":                {"ClusterId", "InstanceGroups"},
			"put-auto-scaling-policy":               {"AutoScalingPolicy", "ClusterId", "InstanceGroupId"},
			"put-auto-termination-policy":           {"AutoTerminationPolicy", "ClusterId"},
			"put-block-public-access-configuration": {"BlockPublicAccessConfiguration"},
			"put-managed-scaling-policy":            {"ClusterId", "ManagedScalingPolicy"},
			"remove-auto-scaling-policy":            {"ClusterId", "InstanceGroupId"},
			"remove-auto-termination-policy":        {"ClusterId"},
			"remove-managed-scaling-policy":         {"ClusterId"},
			"remove-tags":                           {"ResourceId", "TagKeys"},
			"run-job-flow":                          {"AdditionalInfo", "AmiVersion", "Applications", "AutoScalingRole", "AutoTerminationPolicy", "BootstrapActions", "Configurations", "CustomAmiId", "EbsRootVolumeIops", "EbsRootVolumeSize", "EbsRootVolumeThroughput", "ExtendedSupport", "Instances", "JobFlowRole", "KerberosAttributes", "LogEncryptionKmsKeyId", "LogUri", "ManagedScalingPolicy", "MonitoringConfiguration", "Name", "NewSupportedProducts", "OSReleaseLabel", "PlacementGroupConfigs", "ReleaseLabel", "RepoUpgradeOnBoot", "ScaleDownBehavior", "SecurityConfiguration", "ServiceRole", "StepConcurrencyLevel", "Steps", "SupportedProducts", "Tags", "VisibleToAllUsers"},
			"set-keep-job-flow-alive-when-no-steps": {"JobFlowIds", "KeepJobFlowAliveWhenNoSteps"},
			"set-termination-protection":            {"JobFlowIds", "TerminationProtected"},
			"set-unhealthy-node-replacement":        {"JobFlowIds", "UnhealthyNodeReplacement"},
			"set-visible-to-all-users":              {"JobFlowIds", "VisibleToAllUsers"},
			"start-notebook-execution":              {"EditorId", "EnvironmentVariables", "ExecutionEngine", "NotebookExecutionName", "NotebookInstanceSecurityGroupId", "NotebookParams", "NotebookS3Location", "OutputNotebookFormat", "OutputNotebookS3Location", "RelativePath", "ServiceRole", "Tags"},
			"stop-notebook-execution":               {"NotebookExecutionId"},
			"terminate-job-flows":                   {"JobFlowIds"},
			"update-studio":                         {"DefaultS3Location", "Description", "EncryptionKeyArn", "Name", "StudioId", "SubnetIds"},
			"update-studio-session-mapping":         {"IdentityId", "IdentityName", "IdentityType", "SessionPolicyArn", "StudioId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-instance-fleet":                    {"ClusterId": "*string", "InstanceFleet": "*types.InstanceFleetConfig"},
			"add-instance-groups":                   {"InstanceGroups": "[]types.InstanceGroupConfig", "JobFlowId": "*string"},
			"add-job-flow-steps":                    {"ExecutionRoleArn": "*string", "JobFlowId": "*string", "Steps": "[]types.StepConfig"},
			"add-tags":                              {"ResourceId": "*string", "Tags": "[]types.Tag"},
			"cancel-steps":                          {"ClusterId": "*string", "StepCancellationOption": "types.StepCancellationOption", "StepIds": "[]string"},
			"create-persistent-app-ui":              {"EMRContainersConfig": "*types.EMRContainersConfig", "ProfilerType": "types.ProfilerType", "Tags": "[]types.Tag", "TargetResourceArn": "*string", "XReferer": "*string"},
			"create-security-configuration":         {"Name": "*string", "SecurityConfiguration": "*string"},
			"create-studio":                         {"AuthMode": "types.AuthMode", "DefaultS3Location": "*string", "Description": "*string", "EncryptionKeyArn": "*string", "EngineSecurityGroupId": "*string", "IdcInstanceArn": "*string", "IdcUserAssignment": "types.IdcUserAssignment", "IdpAuthUrl": "*string", "IdpRelayStateParameterName": "*string", "Name": "*string", "ServiceRole": "*string", "SubnetIds": "[]string", "Tags": "[]types.Tag", "TrustedIdentityPropagationEnabled": "*bool", "UserRole": "*string", "VpcId": "*string", "WorkspaceSecurityGroupId": "*string"},
			"create-studio-session-mapping":         {"IdentityId": "*string", "IdentityName": "*string", "IdentityType": "types.IdentityType", "SessionPolicyArn": "*string", "StudioId": "*string"},
			"delete-security-configuration":         {"Name": "*string"},
			"delete-studio":                         {"StudioId": "*string"},
			"delete-studio-session-mapping":         {"IdentityId": "*string", "IdentityName": "*string", "IdentityType": "types.IdentityType", "StudioId": "*string"},
			"describe-cluster":                      {"ClusterId": "*string"},
			"describe-job-flows":                    {"CreatedAfter": "*time.Time", "CreatedBefore": "*time.Time", "JobFlowIds": "[]string", "JobFlowStates": "[]types.JobFlowExecutionState"},
			"describe-notebook-execution":           {"NotebookExecutionId": "*string"},
			"describe-persistent-app-ui":            {"PersistentAppUIId": "*string"},
			"describe-release-label":                {"MaxResults": "*int32", "NextToken": "*string", "ReleaseLabel": "*string"},
			"describe-security-configuration":       {"Name": "*string"},
			"describe-step":                         {"ClusterId": "*string", "StepId": "*string"},
			"describe-studio":                       {"StudioId": "*string"},
			"get-auto-termination-policy":           {"ClusterId": "*string"},
			"get-block-public-access-configuration": {},
			"get-cluster-session-credentials":       {"ClusterId": "*string", "ExecutionRoleArn": "*string"},
			"get-managed-scaling-policy":            {"ClusterId": "*string"},
			"get-on-cluster-app-ui-presigned-url":   {"ApplicationId": "*string", "ClusterId": "*string", "DryRun": "*bool", "ExecutionRoleArn": "*string", "OnClusterAppUIType": "types.OnClusterAppUIType"},
			"get-persistent-app-ui-presigned-url":   {"ApplicationId": "*string", "AuthProxyCall": "*bool", "ExecutionRoleArn": "*string", "PersistentAppUIId": "*string", "PersistentAppUIType": "types.PersistentAppUIType"},
			"get-studio-session-mapping":            {"IdentityId": "*string", "IdentityName": "*string", "IdentityType": "types.IdentityType", "StudioId": "*string"},
			"list-bootstrap-actions":                {"ClusterId": "*string", "Marker": "*string"},
			"list-clusters":                         {"ClusterStates": "[]types.ClusterState", "CreatedAfter": "*time.Time", "CreatedBefore": "*time.Time", "Marker": "*string"},
			"list-instance-fleets":                  {"ClusterId": "*string", "Marker": "*string"},
			"list-instance-groups":                  {"ClusterId": "*string", "Marker": "*string"},
			"list-instances":                        {"ClusterId": "*string", "InstanceFleetId": "*string", "InstanceFleetType": "types.InstanceFleetType", "InstanceGroupId": "*string", "InstanceGroupTypes": "[]types.InstanceGroupType", "InstanceStates": "[]types.InstanceState", "Marker": "*string"},
			"list-notebook-executions":              {"EditorId": "*string", "ExecutionEngineId": "*string", "From": "*time.Time", "Marker": "*string", "Status": "types.NotebookExecutionStatus", "To": "*time.Time"},
			"list-release-labels":                   {"Filters": "*types.ReleaseLabelFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-security-configurations":          {"Marker": "*string"},
			"list-steps":                            {"ClusterId": "*string", "Marker": "*string", "StepIds": "[]string", "StepStates": "[]types.StepState"},
			"list-studio-session-mappings":          {"IdentityType": "types.IdentityType", "Marker": "*string", "StudioId": "*string"},
			"list-studios":                          {"Marker": "*string"},
			"list-supported-instance-types":         {"Marker": "*string", "ReleaseLabel": "*string"},
			"modify-cluster":                        {"ClusterId": "*string", "ExtendedSupport": "*bool", "StepConcurrencyLevel": "*int32"},
			"modify-instance-fleet":                 {"ClusterId": "*string", "InstanceFleet": "*types.InstanceFleetModifyConfig"},
			"modify-instance-groups":                {"ClusterId": "*string", "InstanceGroups": "[]types.InstanceGroupModifyConfig"},
			"put-auto-scaling-policy":               {"AutoScalingPolicy": "*types.AutoScalingPolicy", "ClusterId": "*string", "InstanceGroupId": "*string"},
			"put-auto-termination-policy":           {"AutoTerminationPolicy": "*types.AutoTerminationPolicy", "ClusterId": "*string"},
			"put-block-public-access-configuration": {"BlockPublicAccessConfiguration": "*types.BlockPublicAccessConfiguration"},
			"put-managed-scaling-policy":            {"ClusterId": "*string", "ManagedScalingPolicy": "*types.ManagedScalingPolicy"},
			"remove-auto-scaling-policy":            {"ClusterId": "*string", "InstanceGroupId": "*string"},
			"remove-auto-termination-policy":        {"ClusterId": "*string"},
			"remove-managed-scaling-policy":         {"ClusterId": "*string"},
			"remove-tags":                           {"ResourceId": "*string", "TagKeys": "[]string"},
			"run-job-flow":                          {"AdditionalInfo": "*string", "AmiVersion": "*string", "Applications": "[]types.Application", "AutoScalingRole": "*string", "AutoTerminationPolicy": "*types.AutoTerminationPolicy", "BootstrapActions": "[]types.BootstrapActionConfig", "Configurations": "[]types.Configuration", "CustomAmiId": "*string", "EbsRootVolumeIops": "*int32", "EbsRootVolumeSize": "*int32", "EbsRootVolumeThroughput": "*int32", "ExtendedSupport": "*bool", "Instances": "*types.JobFlowInstancesConfig", "JobFlowRole": "*string", "KerberosAttributes": "*types.KerberosAttributes", "LogEncryptionKmsKeyId": "*string", "LogUri": "*string", "ManagedScalingPolicy": "*types.ManagedScalingPolicy", "MonitoringConfiguration": "*types.MonitoringConfiguration", "Name": "*string", "NewSupportedProducts": "[]types.SupportedProductConfig", "OSReleaseLabel": "*string", "PlacementGroupConfigs": "[]types.PlacementGroupConfig", "ReleaseLabel": "*string", "RepoUpgradeOnBoot": "types.RepoUpgradeOnBoot", "ScaleDownBehavior": "types.ScaleDownBehavior", "SecurityConfiguration": "*string", "ServiceRole": "*string", "StepConcurrencyLevel": "*int32", "Steps": "[]types.StepConfig", "SupportedProducts": "[]string", "Tags": "[]types.Tag", "VisibleToAllUsers": "*bool"},
			"set-keep-job-flow-alive-when-no-steps": {"JobFlowIds": "[]string", "KeepJobFlowAliveWhenNoSteps": "*bool"},
			"set-termination-protection":            {"JobFlowIds": "[]string", "TerminationProtected": "*bool"},
			"set-unhealthy-node-replacement":        {"JobFlowIds": "[]string", "UnhealthyNodeReplacement": "*bool"},
			"set-visible-to-all-users":              {"JobFlowIds": "[]string", "VisibleToAllUsers": "*bool"},
			"start-notebook-execution":              {"EditorId": "*string", "EnvironmentVariables": "map[string]string", "ExecutionEngine": "*types.ExecutionEngineConfig", "NotebookExecutionName": "*string", "NotebookInstanceSecurityGroupId": "*string", "NotebookParams": "*string", "NotebookS3Location": "*types.NotebookS3LocationFromInput", "OutputNotebookFormat": "types.OutputNotebookFormat", "OutputNotebookS3Location": "*types.OutputNotebookS3LocationFromInput", "RelativePath": "*string", "ServiceRole": "*string", "Tags": "[]types.Tag"},
			"stop-notebook-execution":               {"NotebookExecutionId": "*string"},
			"terminate-job-flows":                   {"JobFlowIds": "[]string"},
			"update-studio":                         {"DefaultS3Location": "*string", "Description": "*string", "EncryptionKeyArn": "*string", "Name": "*string", "StudioId": "*string", "SubnetIds": "[]string"},
			"update-studio-session-mapping":         {"IdentityId": "*string", "IdentityName": "*string", "IdentityType": "types.IdentityType", "SessionPolicyArn": "*string", "StudioId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"add-instance-fleet":                    {"ClusterId", "InstanceFleet"},
			"add-instance-groups":                   {"InstanceGroups", "JobFlowId"},
			"add-job-flow-steps":                    {"JobFlowId", "Steps"},
			"add-tags":                              {"ResourceId", "Tags"},
			"cancel-steps":                          {"ClusterId", "StepIds"},
			"create-persistent-app-ui":              {"TargetResourceArn"},
			"create-security-configuration":         {"Name", "SecurityConfiguration"},
			"create-studio":                         {"AuthMode", "DefaultS3Location", "EngineSecurityGroupId", "Name", "ServiceRole", "SubnetIds", "VpcId", "WorkspaceSecurityGroupId"},
			"create-studio-session-mapping":         {"IdentityType", "SessionPolicyArn", "StudioId"},
			"delete-security-configuration":         {"Name"},
			"delete-studio":                         {"StudioId"},
			"delete-studio-session-mapping":         {"IdentityType", "StudioId"},
			"describe-cluster":                      {"ClusterId"},
			"describe-job-flows":                    {},
			"describe-notebook-execution":           {"NotebookExecutionId"},
			"describe-persistent-app-ui":            {"PersistentAppUIId"},
			"describe-release-label":                {},
			"describe-security-configuration":       {"Name"},
			"describe-step":                         {"ClusterId", "StepId"},
			"describe-studio":                       {"StudioId"},
			"get-auto-termination-policy":           {"ClusterId"},
			"get-block-public-access-configuration": {},
			"get-cluster-session-credentials":       {"ClusterId"},
			"get-managed-scaling-policy":            {"ClusterId"},
			"get-on-cluster-app-ui-presigned-url":   {"ClusterId"},
			"get-persistent-app-ui-presigned-url":   {"PersistentAppUIId"},
			"get-studio-session-mapping":            {"IdentityType", "StudioId"},
			"list-bootstrap-actions":                {"ClusterId"},
			"list-clusters":                         {},
			"list-instance-fleets":                  {"ClusterId"},
			"list-instance-groups":                  {"ClusterId"},
			"list-instances":                        {"ClusterId"},
			"list-notebook-executions":              {},
			"list-release-labels":                   {},
			"list-security-configurations":          {},
			"list-steps":                            {"ClusterId"},
			"list-studio-session-mappings":          {},
			"list-studios":                          {},
			"list-supported-instance-types":         {"ReleaseLabel"},
			"modify-cluster":                        {"ClusterId"},
			"modify-instance-fleet":                 {"ClusterId", "InstanceFleet"},
			"modify-instance-groups":                {},
			"put-auto-scaling-policy":               {"AutoScalingPolicy", "ClusterId", "InstanceGroupId"},
			"put-auto-termination-policy":           {"ClusterId"},
			"put-block-public-access-configuration": {"BlockPublicAccessConfiguration"},
			"put-managed-scaling-policy":            {"ClusterId", "ManagedScalingPolicy"},
			"remove-auto-scaling-policy":            {"ClusterId", "InstanceGroupId"},
			"remove-auto-termination-policy":        {"ClusterId"},
			"remove-managed-scaling-policy":         {"ClusterId"},
			"remove-tags":                           {"ResourceId", "TagKeys"},
			"run-job-flow":                          {"Instances", "Name"},
			"set-keep-job-flow-alive-when-no-steps": {"JobFlowIds", "KeepJobFlowAliveWhenNoSteps"},
			"set-termination-protection":            {"JobFlowIds", "TerminationProtected"},
			"set-unhealthy-node-replacement":        {"JobFlowIds", "UnhealthyNodeReplacement"},
			"set-visible-to-all-users":              {"JobFlowIds", "VisibleToAllUsers"},
			"start-notebook-execution":              {"ExecutionEngine", "ServiceRole"},
			"stop-notebook-execution":               {"NotebookExecutionId"},
			"terminate-job-flows":                   {"JobFlowIds"},
			"update-studio":                         {"StudioId"},
			"update-studio-session-mapping":         {"IdentityType", "SessionPolicyArn", "StudioId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("emr", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
