package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/amplifyuibuilder/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-component", "create-form", "create-theme", "delete-component", "delete-form", "delete-theme", "exchange-code-for-token", "export-components", "export-forms", "export-themes", "get-codegen-job", "get-component", "get-form", "get-metadata", "get-theme", "list-codegen-jobs", "list-components", "list-forms", "list-tags-for-resource", "list-themes", "put-metadata-flag", "refresh-token", "start-codegen-job", "tag-resource", "untag-resource", "update-component", "update-form", "update-theme"},
		OperationSet: map[string]bool{"create-component": true, "create-form": true, "create-theme": true, "delete-component": true, "delete-form": true, "delete-theme": true, "exchange-code-for-token": true, "export-components": true, "export-forms": true, "export-themes": true, "get-codegen-job": true, "get-component": true, "get-form": true, "get-metadata": true, "get-theme": true, "list-codegen-jobs": true, "list-components": true, "list-forms": true, "list-tags-for-resource": true, "list-themes": true, "put-metadata-flag": true, "refresh-token": true, "start-codegen-job": true, "tag-resource": true, "untag-resource": true, "update-component": true, "update-form": true, "update-theme": true},
		OperationInputs: map[string][]string{
			"create-component":        {"AppId", "ClientToken", "ComponentToCreate", "EnvironmentName"},
			"create-form":             {"AppId", "ClientToken", "EnvironmentName", "FormToCreate"},
			"create-theme":            {"AppId", "ClientToken", "EnvironmentName", "ThemeToCreate"},
			"delete-component":        {"AppId", "EnvironmentName", "Id"},
			"delete-form":             {"AppId", "EnvironmentName", "Id"},
			"delete-theme":            {"AppId", "EnvironmentName", "Id"},
			"exchange-code-for-token": {"Provider", "Request"},
			"export-components":       {"AppId", "EnvironmentName", "NextToken"},
			"export-forms":            {"AppId", "EnvironmentName", "NextToken"},
			"export-themes":           {"AppId", "EnvironmentName", "NextToken"},
			"get-codegen-job":         {"AppId", "EnvironmentName", "Id"},
			"get-component":           {"AppId", "EnvironmentName", "Id"},
			"get-form":                {"AppId", "EnvironmentName", "Id"},
			"get-metadata":            {"AppId", "EnvironmentName"},
			"get-theme":               {"AppId", "EnvironmentName", "Id"},
			"list-codegen-jobs":       {"AppId", "EnvironmentName", "MaxResults", "NextToken"},
			"list-components":         {"AppId", "EnvironmentName", "MaxResults", "NextToken"},
			"list-forms":              {"AppId", "EnvironmentName", "MaxResults", "NextToken"},
			"list-tags-for-resource":  {"ResourceArn"},
			"list-themes":             {"AppId", "EnvironmentName", "MaxResults", "NextToken"},
			"put-metadata-flag":       {"AppId", "Body", "EnvironmentName", "FeatureName"},
			"refresh-token":           {"Provider", "RefreshTokenBody"},
			"start-codegen-job":       {"AppId", "ClientToken", "CodegenJobToCreate", "EnvironmentName"},
			"tag-resource":            {"ResourceArn", "Tags"},
			"untag-resource":          {"ResourceArn", "TagKeys"},
			"update-component":        {"AppId", "ClientToken", "EnvironmentName", "Id", "UpdatedComponent"},
			"update-form":             {"AppId", "ClientToken", "EnvironmentName", "Id", "UpdatedForm"},
			"update-theme":            {"AppId", "ClientToken", "EnvironmentName", "Id", "UpdatedTheme"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-component":        {"AppId": "*string", "ClientToken": "*string", "ComponentToCreate": "*types.CreateComponentData", "EnvironmentName": "*string"},
			"create-form":             {"AppId": "*string", "ClientToken": "*string", "EnvironmentName": "*string", "FormToCreate": "*types.CreateFormData"},
			"create-theme":            {"AppId": "*string", "ClientToken": "*string", "EnvironmentName": "*string", "ThemeToCreate": "*types.CreateThemeData"},
			"delete-component":        {"AppId": "*string", "EnvironmentName": "*string", "Id": "*string"},
			"delete-form":             {"AppId": "*string", "EnvironmentName": "*string", "Id": "*string"},
			"delete-theme":            {"AppId": "*string", "EnvironmentName": "*string", "Id": "*string"},
			"exchange-code-for-token": {"Provider": "types.TokenProviders", "Request": "*types.ExchangeCodeForTokenRequestBody"},
			"export-components":       {"AppId": "*string", "EnvironmentName": "*string", "NextToken": "*string"},
			"export-forms":            {"AppId": "*string", "EnvironmentName": "*string", "NextToken": "*string"},
			"export-themes":           {"AppId": "*string", "EnvironmentName": "*string", "NextToken": "*string"},
			"get-codegen-job":         {"AppId": "*string", "EnvironmentName": "*string", "Id": "*string"},
			"get-component":           {"AppId": "*string", "EnvironmentName": "*string", "Id": "*string"},
			"get-form":                {"AppId": "*string", "EnvironmentName": "*string", "Id": "*string"},
			"get-metadata":            {"AppId": "*string", "EnvironmentName": "*string"},
			"get-theme":               {"AppId": "*string", "EnvironmentName": "*string", "Id": "*string"},
			"list-codegen-jobs":       {"AppId": "*string", "EnvironmentName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-components":         {"AppId": "*string", "EnvironmentName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-forms":              {"AppId": "*string", "EnvironmentName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":  {"ResourceArn": "*string"},
			"list-themes":             {"AppId": "*string", "EnvironmentName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"put-metadata-flag":       {"AppId": "*string", "Body": "*types.PutMetadataFlagBody", "EnvironmentName": "*string", "FeatureName": "*string"},
			"refresh-token":           {"Provider": "types.TokenProviders", "RefreshTokenBody": "*types.RefreshTokenRequestBody"},
			"start-codegen-job":       {"AppId": "*string", "ClientToken": "*string", "CodegenJobToCreate": "*types.StartCodegenJobData", "EnvironmentName": "*string"},
			"tag-resource":            {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":          {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-component":        {"AppId": "*string", "ClientToken": "*string", "EnvironmentName": "*string", "Id": "*string", "UpdatedComponent": "*types.UpdateComponentData"},
			"update-form":             {"AppId": "*string", "ClientToken": "*string", "EnvironmentName": "*string", "Id": "*string", "UpdatedForm": "*types.UpdateFormData"},
			"update-theme":            {"AppId": "*string", "ClientToken": "*string", "EnvironmentName": "*string", "Id": "*string", "UpdatedTheme": "*types.UpdateThemeData"},
		},
		OperationInputRequired: map[string][]string{
			"create-component":        {"AppId", "ComponentToCreate", "EnvironmentName"},
			"create-form":             {"AppId", "EnvironmentName", "FormToCreate"},
			"create-theme":            {"AppId", "EnvironmentName", "ThemeToCreate"},
			"delete-component":        {"AppId", "EnvironmentName", "Id"},
			"delete-form":             {"AppId", "EnvironmentName", "Id"},
			"delete-theme":            {"AppId", "EnvironmentName", "Id"},
			"exchange-code-for-token": {"Provider", "Request"},
			"export-components":       {"AppId", "EnvironmentName"},
			"export-forms":            {"AppId", "EnvironmentName"},
			"export-themes":           {"AppId", "EnvironmentName"},
			"get-codegen-job":         {"AppId", "EnvironmentName", "Id"},
			"get-component":           {"AppId", "EnvironmentName", "Id"},
			"get-form":                {"AppId", "EnvironmentName", "Id"},
			"get-metadata":            {"AppId", "EnvironmentName"},
			"get-theme":               {"AppId", "EnvironmentName", "Id"},
			"list-codegen-jobs":       {"AppId", "EnvironmentName"},
			"list-components":         {"AppId", "EnvironmentName"},
			"list-forms":              {"AppId", "EnvironmentName"},
			"list-tags-for-resource":  {"ResourceArn"},
			"list-themes":             {"AppId", "EnvironmentName"},
			"put-metadata-flag":       {"AppId", "Body", "EnvironmentName", "FeatureName"},
			"refresh-token":           {"Provider", "RefreshTokenBody"},
			"start-codegen-job":       {"AppId", "CodegenJobToCreate", "EnvironmentName"},
			"tag-resource":            {"ResourceArn", "Tags"},
			"untag-resource":          {"ResourceArn", "TagKeys"},
			"update-component":        {"AppId", "EnvironmentName", "Id", "UpdatedComponent"},
			"update-form":             {"AppId", "EnvironmentName", "Id", "UpdatedForm"},
			"update-theme":            {"AppId", "EnvironmentName", "Id", "UpdatedTheme"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("amplifyuibuilder", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
