package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/cloudwatchlogs/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-kms-key", "associate-source-to-s3-table-integration", "cancel-export-task", "cancel-import-task", "create-delivery", "create-export-task", "create-import-task", "create-log-anomaly-detector", "create-log-group", "create-log-stream", "create-scheduled-query", "delete-account-policy", "delete-data-protection-policy", "delete-delivery", "delete-delivery-destination", "delete-delivery-destination-policy", "delete-delivery-source", "delete-destination", "delete-index-policy", "delete-integration", "delete-log-anomaly-detector", "delete-log-group", "delete-log-stream", "delete-metric-filter", "delete-query-definition", "delete-resource-policy", "delete-retention-policy", "delete-scheduled-query", "delete-subscription-filter", "delete-transformer", "describe-account-policies", "describe-configuration-templates", "describe-deliveries", "describe-delivery-destinations", "describe-delivery-sources", "describe-destinations", "describe-export-tasks", "describe-field-indexes", "describe-import-task-batches", "describe-import-tasks", "describe-index-policies", "describe-log-groups", "describe-log-streams", "describe-metric-filters", "describe-queries", "describe-query-definitions", "describe-resource-policies", "describe-subscription-filters", "disassociate-kms-key", "disassociate-source-from-s3-table-integration", "filter-log-events", "get-data-protection-policy", "get-delivery", "get-delivery-destination", "get-delivery-destination-policy", "get-delivery-source", "get-integration", "get-log-anomaly-detector", "get-log-events", "get-log-fields", "get-log-group-fields", "get-log-object", "get-log-record", "get-query-results", "get-scheduled-query", "get-scheduled-query-history", "get-transformer", "list-aggregate-log-group-summaries", "list-anomalies", "list-integrations", "list-log-anomaly-detectors", "list-log-groups", "list-log-groups-for-query", "list-scheduled-queries", "list-sources-for-s3-table-integration", "list-tags-for-resource", "list-tags-log-group", "put-account-policy", "put-bearer-token-authentication", "put-data-protection-policy", "put-delivery-destination", "put-delivery-destination-policy", "put-delivery-source", "put-destination", "put-destination-policy", "put-index-policy", "put-integration", "put-log-events", "put-log-group-deletion-protection", "put-metric-filter", "put-query-definition", "put-resource-policy", "put-retention-policy", "put-subscription-filter", "put-transformer", "start-live-tail", "start-query", "stop-query", "tag-log-group", "tag-resource", "test-metric-filter", "test-transformer", "untag-log-group", "untag-resource", "update-anomaly", "update-delivery-configuration", "update-log-anomaly-detector", "update-scheduled-query"},
		OperationSet: map[string]bool{"associate-kms-key": true, "associate-source-to-s3-table-integration": true, "cancel-export-task": true, "cancel-import-task": true, "create-delivery": true, "create-export-task": true, "create-import-task": true, "create-log-anomaly-detector": true, "create-log-group": true, "create-log-stream": true, "create-scheduled-query": true, "delete-account-policy": true, "delete-data-protection-policy": true, "delete-delivery": true, "delete-delivery-destination": true, "delete-delivery-destination-policy": true, "delete-delivery-source": true, "delete-destination": true, "delete-index-policy": true, "delete-integration": true, "delete-log-anomaly-detector": true, "delete-log-group": true, "delete-log-stream": true, "delete-metric-filter": true, "delete-query-definition": true, "delete-resource-policy": true, "delete-retention-policy": true, "delete-scheduled-query": true, "delete-subscription-filter": true, "delete-transformer": true, "describe-account-policies": true, "describe-configuration-templates": true, "describe-deliveries": true, "describe-delivery-destinations": true, "describe-delivery-sources": true, "describe-destinations": true, "describe-export-tasks": true, "describe-field-indexes": true, "describe-import-task-batches": true, "describe-import-tasks": true, "describe-index-policies": true, "describe-log-groups": true, "describe-log-streams": true, "describe-metric-filters": true, "describe-queries": true, "describe-query-definitions": true, "describe-resource-policies": true, "describe-subscription-filters": true, "disassociate-kms-key": true, "disassociate-source-from-s3-table-integration": true, "filter-log-events": true, "get-data-protection-policy": true, "get-delivery": true, "get-delivery-destination": true, "get-delivery-destination-policy": true, "get-delivery-source": true, "get-integration": true, "get-log-anomaly-detector": true, "get-log-events": true, "get-log-fields": true, "get-log-group-fields": true, "get-log-object": true, "get-log-record": true, "get-query-results": true, "get-scheduled-query": true, "get-scheduled-query-history": true, "get-transformer": true, "list-aggregate-log-group-summaries": true, "list-anomalies": true, "list-integrations": true, "list-log-anomaly-detectors": true, "list-log-groups": true, "list-log-groups-for-query": true, "list-scheduled-queries": true, "list-sources-for-s3-table-integration": true, "list-tags-for-resource": true, "list-tags-log-group": true, "put-account-policy": true, "put-bearer-token-authentication": true, "put-data-protection-policy": true, "put-delivery-destination": true, "put-delivery-destination-policy": true, "put-delivery-source": true, "put-destination": true, "put-destination-policy": true, "put-index-policy": true, "put-integration": true, "put-log-events": true, "put-log-group-deletion-protection": true, "put-metric-filter": true, "put-query-definition": true, "put-resource-policy": true, "put-retention-policy": true, "put-subscription-filter": true, "put-transformer": true, "start-live-tail": true, "start-query": true, "stop-query": true, "tag-log-group": true, "tag-resource": true, "test-metric-filter": true, "test-transformer": true, "untag-log-group": true, "untag-resource": true, "update-anomaly": true, "update-delivery-configuration": true, "update-log-anomaly-detector": true, "update-scheduled-query": true},
		OperationInputs: map[string][]string{
			"associate-kms-key":                             {"KmsKeyId", "LogGroupName", "ResourceIdentifier"},
			"associate-source-to-s3-table-integration":      {"DataSource", "IntegrationArn"},
			"cancel-export-task":                            {"TaskId"},
			"cancel-import-task":                            {"ImportId"},
			"create-delivery":                               {"DeliveryDestinationArn", "DeliverySourceName", "FieldDelimiter", "RecordFields", "S3DeliveryConfiguration", "Tags"},
			"create-export-task":                            {"Destination", "DestinationPrefix", "From", "LogGroupName", "LogStreamNamePrefix", "TaskName", "To"},
			"create-import-task":                            {"ImportFilter", "ImportRoleArn", "ImportSourceArn"},
			"create-log-anomaly-detector":                   {"AnomalyVisibilityTime", "DetectorName", "EvaluationFrequency", "FilterPattern", "KmsKeyId", "LogGroupArnList", "Tags"},
			"create-log-group":                              {"DeletionProtectionEnabled", "KmsKeyId", "LogGroupClass", "LogGroupName", "Tags"},
			"create-log-stream":                             {"LogGroupName", "LogStreamName"},
			"create-scheduled-query":                        {"Description", "DestinationConfiguration", "ExecutionRoleArn", "LogGroupIdentifiers", "Name", "QueryLanguage", "QueryString", "ScheduleEndTime", "ScheduleExpression", "ScheduleStartTime", "StartTimeOffset", "State", "Tags", "Timezone"},
			"delete-account-policy":                         {"PolicyName", "PolicyType"},
			"delete-data-protection-policy":                 {"LogGroupIdentifier"},
			"delete-delivery":                               {"Id"},
			"delete-delivery-destination":                   {"Name"},
			"delete-delivery-destination-policy":            {"DeliveryDestinationName"},
			"delete-delivery-source":                        {"Name"},
			"delete-destination":                            {"DestinationName"},
			"delete-index-policy":                           {"LogGroupIdentifier"},
			"delete-integration":                            {"Force", "IntegrationName"},
			"delete-log-anomaly-detector":                   {"AnomalyDetectorArn"},
			"delete-log-group":                              {"LogGroupName"},
			"delete-log-stream":                             {"LogGroupName", "LogStreamName"},
			"delete-metric-filter":                          {"FilterName", "LogGroupName"},
			"delete-query-definition":                       {"QueryDefinitionId"},
			"delete-resource-policy":                        {"ExpectedRevisionId", "PolicyName", "ResourceArn"},
			"delete-retention-policy":                       {"LogGroupName"},
			"delete-scheduled-query":                        {"Identifier"},
			"delete-subscription-filter":                    {"FilterName", "LogGroupName"},
			"delete-transformer":                            {"LogGroupIdentifier"},
			"describe-account-policies":                     {"AccountIdentifiers", "NextToken", "PolicyName", "PolicyType"},
			"describe-configuration-templates":              {"DeliveryDestinationTypes", "Limit", "LogTypes", "NextToken", "ResourceTypes", "Service"},
			"describe-deliveries":                           {"Limit", "NextToken"},
			"describe-delivery-destinations":                {"Limit", "NextToken"},
			"describe-delivery-sources":                     {"Limit", "NextToken"},
			"describe-destinations":                         {"DestinationNamePrefix", "Limit", "NextToken"},
			"describe-export-tasks":                         {"Limit", "NextToken", "StatusCode", "TaskId"},
			"describe-field-indexes":                        {"LogGroupIdentifiers", "NextToken"},
			"describe-import-task-batches":                  {"BatchImportStatus", "ImportId", "Limit", "NextToken"},
			"describe-import-tasks":                         {"ImportId", "ImportSourceArn", "ImportStatus", "Limit", "NextToken"},
			"describe-index-policies":                       {"LogGroupIdentifiers", "NextToken"},
			"describe-log-groups":                           {"AccountIdentifiers", "IncludeLinkedAccounts", "Limit", "LogGroupClass", "LogGroupIdentifiers", "LogGroupNamePattern", "LogGroupNamePrefix", "NextToken"},
			"describe-log-streams":                          {"Descending", "Limit", "LogGroupIdentifier", "LogGroupName", "LogStreamNamePrefix", "NextToken", "OrderBy"},
			"describe-metric-filters":                       {"FilterNamePrefix", "Limit", "LogGroupName", "MetricName", "MetricNamespace", "NextToken"},
			"describe-queries":                              {"LogGroupName", "MaxResults", "NextToken", "QueryLanguage", "Status"},
			"describe-query-definitions":                    {"MaxResults", "NextToken", "QueryDefinitionNamePrefix", "QueryLanguage"},
			"describe-resource-policies":                    {"Limit", "NextToken", "PolicyScope", "ResourceArn"},
			"describe-subscription-filters":                 {"FilterNamePrefix", "Limit", "LogGroupName", "NextToken"},
			"disassociate-kms-key":                          {"LogGroupName", "ResourceIdentifier"},
			"disassociate-source-from-s3-table-integration": {"Identifier"},
			"filter-log-events":                             {"EndTime", "FilterPattern", "Interleaved", "Limit", "LogGroupIdentifier", "LogGroupName", "LogStreamNamePrefix", "LogStreamNames", "NextToken", "StartTime", "Unmask"},
			"get-data-protection-policy":                    {"LogGroupIdentifier"},
			"get-delivery":                                  {"Id"},
			"get-delivery-destination":                      {"Name"},
			"get-delivery-destination-policy":               {"DeliveryDestinationName"},
			"get-delivery-source":                           {"Name"},
			"get-integration":                               {"IntegrationName"},
			"get-log-anomaly-detector":                      {"AnomalyDetectorArn"},
			"get-log-events":                                {"EndTime", "Limit", "LogGroupIdentifier", "LogGroupName", "LogStreamName", "NextToken", "StartFromHead", "StartTime", "Unmask"},
			"get-log-fields":                                {"DataSourceName", "DataSourceType"},
			"get-log-group-fields":                          {"LogGroupIdentifier", "LogGroupName", "Time"},
			"get-log-object":                                {"LogObjectPointer", "Unmask"},
			"get-log-record":                                {"LogRecordPointer", "Unmask"},
			"get-query-results":                             {"QueryId"},
			"get-scheduled-query":                           {"Identifier"},
			"get-scheduled-query-history":                   {"EndTime", "ExecutionStatuses", "Identifier", "MaxResults", "NextToken", "StartTime"},
			"get-transformer":                               {"LogGroupIdentifier"},
			"list-aggregate-log-group-summaries":            {"AccountIdentifiers", "DataSources", "GroupBy", "IncludeLinkedAccounts", "Limit", "LogGroupClass", "LogGroupNamePattern", "NextToken"},
			"list-anomalies":                                {"AnomalyDetectorArn", "Limit", "NextToken", "SuppressionState"},
			"list-integrations":                             {"IntegrationNamePrefix", "IntegrationStatus", "IntegrationType"},
			"list-log-anomaly-detectors":                    {"FilterLogGroupArn", "Limit", "NextToken"},
			"list-log-groups":                               {"AccountIdentifiers", "DataSources", "FieldIndexNames", "IncludeLinkedAccounts", "Limit", "LogGroupClass", "LogGroupNamePattern", "NextToken"},
			"list-log-groups-for-query":                     {"MaxResults", "NextToken", "QueryId"},
			"list-scheduled-queries":                        {"MaxResults", "NextToken", "State"},
			"list-sources-for-s3-table-integration":         {"IntegrationArn", "MaxResults", "NextToken"},
			"list-tags-for-resource":                        {"ResourceArn"},
			"list-tags-log-group":                           {"LogGroupName"},
			"put-account-policy":                            {"PolicyDocument", "PolicyName", "PolicyType", "Scope", "SelectionCriteria"},
			"put-bearer-token-authentication":               {"BearerTokenAuthenticationEnabled", "LogGroupIdentifier"},
			"put-data-protection-policy":                    {"LogGroupIdentifier", "PolicyDocument"},
			"put-delivery-destination":                      {"DeliveryDestinationConfiguration", "DeliveryDestinationType", "Name", "OutputFormat", "Tags"},
			"put-delivery-destination-policy":               {"DeliveryDestinationName", "DeliveryDestinationPolicy"},
			"put-delivery-source":                           {"LogType", "Name", "ResourceArn", "Tags"},
			"put-destination":                               {"DestinationName", "RoleArn", "Tags", "TargetArn"},
			"put-destination-policy":                        {"AccessPolicy", "DestinationName", "ForceUpdate"},
			"put-index-policy":                              {"LogGroupIdentifier", "PolicyDocument"},
			"put-integration":                               {"IntegrationName", "IntegrationType", "ResourceConfig"},
			"put-log-events":                                {"Entity", "LogEvents", "LogGroupName", "LogStreamName", "SequenceToken"},
			"put-log-group-deletion-protection":             {"DeletionProtectionEnabled", "LogGroupIdentifier"},
			"put-metric-filter":                             {"ApplyOnTransformedLogs", "EmitSystemFieldDimensions", "FieldSelectionCriteria", "FilterName", "FilterPattern", "LogGroupName", "MetricTransformations"},
			"put-query-definition":                          {"ClientToken", "LogGroupNames", "Name", "QueryDefinitionId", "QueryLanguage", "QueryString"},
			"put-resource-policy":                           {"ExpectedRevisionId", "PolicyDocument", "PolicyName", "ResourceArn"},
			"put-retention-policy":                          {"LogGroupName", "RetentionInDays"},
			"put-subscription-filter":                       {"ApplyOnTransformedLogs", "DestinationArn", "Distribution", "EmitSystemFields", "FieldSelectionCriteria", "FilterName", "FilterPattern", "LogGroupName", "RoleArn"},
			"put-transformer":                               {"LogGroupIdentifier", "TransformerConfig"},
			"start-live-tail":                               {"LogEventFilterPattern", "LogGroupIdentifiers", "LogStreamNamePrefixes", "LogStreamNames"},
			"start-query":                                   {"EndTime", "Limit", "LogGroupIdentifiers", "LogGroupName", "LogGroupNames", "QueryLanguage", "QueryString", "StartTime"},
			"stop-query":                                    {"QueryId"},
			"tag-log-group":                                 {"LogGroupName", "Tags"},
			"tag-resource":                                  {"ResourceArn", "Tags"},
			"test-metric-filter":                            {"FilterPattern", "LogEventMessages"},
			"test-transformer":                              {"LogEventMessages", "TransformerConfig"},
			"untag-log-group":                               {"LogGroupName", "Tags"},
			"untag-resource":                                {"ResourceArn", "TagKeys"},
			"update-anomaly":                                {"AnomalyDetectorArn", "AnomalyId", "Baseline", "PatternId", "SuppressionPeriod", "SuppressionType"},
			"update-delivery-configuration":                 {"FieldDelimiter", "Id", "RecordFields", "S3DeliveryConfiguration"},
			"update-log-anomaly-detector":                   {"AnomalyDetectorArn", "AnomalyVisibilityTime", "Enabled", "EvaluationFrequency", "FilterPattern"},
			"update-scheduled-query":                        {"Description", "DestinationConfiguration", "ExecutionRoleArn", "Identifier", "LogGroupIdentifiers", "QueryLanguage", "QueryString", "ScheduleEndTime", "ScheduleExpression", "ScheduleStartTime", "StartTimeOffset", "State", "Timezone"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-kms-key":                             {"KmsKeyId": "*string", "LogGroupName": "*string", "ResourceIdentifier": "*string"},
			"associate-source-to-s3-table-integration":      {"DataSource": "*types.DataSource", "IntegrationArn": "*string"},
			"cancel-export-task":                            {"TaskId": "*string"},
			"cancel-import-task":                            {"ImportId": "*string"},
			"create-delivery":                               {"DeliveryDestinationArn": "*string", "DeliverySourceName": "*string", "FieldDelimiter": "*string", "RecordFields": "[]string", "S3DeliveryConfiguration": "*types.S3DeliveryConfiguration", "Tags": "map[string]string"},
			"create-export-task":                            {"Destination": "*string", "DestinationPrefix": "*string", "From": "*int64", "LogGroupName": "*string", "LogStreamNamePrefix": "*string", "TaskName": "*string", "To": "*int64"},
			"create-import-task":                            {"ImportFilter": "*types.ImportFilter", "ImportRoleArn": "*string", "ImportSourceArn": "*string"},
			"create-log-anomaly-detector":                   {"AnomalyVisibilityTime": "*int64", "DetectorName": "*string", "EvaluationFrequency": "types.EvaluationFrequency", "FilterPattern": "*string", "KmsKeyId": "*string", "LogGroupArnList": "[]string", "Tags": "map[string]string"},
			"create-log-group":                              {"DeletionProtectionEnabled": "*bool", "KmsKeyId": "*string", "LogGroupClass": "types.LogGroupClass", "LogGroupName": "*string", "Tags": "map[string]string"},
			"create-log-stream":                             {"LogGroupName": "*string", "LogStreamName": "*string"},
			"create-scheduled-query":                        {"Description": "*string", "DestinationConfiguration": "*types.DestinationConfiguration", "ExecutionRoleArn": "*string", "LogGroupIdentifiers": "[]string", "Name": "*string", "QueryLanguage": "types.QueryLanguage", "QueryString": "*string", "ScheduleEndTime": "*int64", "ScheduleExpression": "*string", "ScheduleStartTime": "*int64", "StartTimeOffset": "*int64", "State": "types.ScheduledQueryState", "Tags": "map[string]string", "Timezone": "*string"},
			"delete-account-policy":                         {"PolicyName": "*string", "PolicyType": "types.PolicyType"},
			"delete-data-protection-policy":                 {"LogGroupIdentifier": "*string"},
			"delete-delivery":                               {"Id": "*string"},
			"delete-delivery-destination":                   {"Name": "*string"},
			"delete-delivery-destination-policy":            {"DeliveryDestinationName": "*string"},
			"delete-delivery-source":                        {"Name": "*string"},
			"delete-destination":                            {"DestinationName": "*string"},
			"delete-index-policy":                           {"LogGroupIdentifier": "*string"},
			"delete-integration":                            {"Force": "bool", "IntegrationName": "*string"},
			"delete-log-anomaly-detector":                   {"AnomalyDetectorArn": "*string"},
			"delete-log-group":                              {"LogGroupName": "*string"},
			"delete-log-stream":                             {"LogGroupName": "*string", "LogStreamName": "*string"},
			"delete-metric-filter":                          {"FilterName": "*string", "LogGroupName": "*string"},
			"delete-query-definition":                       {"QueryDefinitionId": "*string"},
			"delete-resource-policy":                        {"ExpectedRevisionId": "*string", "PolicyName": "*string", "ResourceArn": "*string"},
			"delete-retention-policy":                       {"LogGroupName": "*string"},
			"delete-scheduled-query":                        {"Identifier": "*string"},
			"delete-subscription-filter":                    {"FilterName": "*string", "LogGroupName": "*string"},
			"delete-transformer":                            {"LogGroupIdentifier": "*string"},
			"describe-account-policies":                     {"AccountIdentifiers": "[]string", "NextToken": "*string", "PolicyName": "*string", "PolicyType": "types.PolicyType"},
			"describe-configuration-templates":              {"DeliveryDestinationTypes": "[]types.DeliveryDestinationType", "Limit": "*int32", "LogTypes": "[]string", "NextToken": "*string", "ResourceTypes": "[]string", "Service": "*string"},
			"describe-deliveries":                           {"Limit": "*int32", "NextToken": "*string"},
			"describe-delivery-destinations":                {"Limit": "*int32", "NextToken": "*string"},
			"describe-delivery-sources":                     {"Limit": "*int32", "NextToken": "*string"},
			"describe-destinations":                         {"DestinationNamePrefix": "*string", "Limit": "*int32", "NextToken": "*string"},
			"describe-export-tasks":                         {"Limit": "*int32", "NextToken": "*string", "StatusCode": "types.ExportTaskStatusCode", "TaskId": "*string"},
			"describe-field-indexes":                        {"LogGroupIdentifiers": "[]string", "NextToken": "*string"},
			"describe-import-task-batches":                  {"BatchImportStatus": "[]types.ImportStatus", "ImportId": "*string", "Limit": "*int32", "NextToken": "*string"},
			"describe-import-tasks":                         {"ImportId": "*string", "ImportSourceArn": "*string", "ImportStatus": "types.ImportStatus", "Limit": "*int32", "NextToken": "*string"},
			"describe-index-policies":                       {"LogGroupIdentifiers": "[]string", "NextToken": "*string"},
			"describe-log-groups":                           {"AccountIdentifiers": "[]string", "IncludeLinkedAccounts": "*bool", "Limit": "*int32", "LogGroupClass": "types.LogGroupClass", "LogGroupIdentifiers": "[]string", "LogGroupNamePattern": "*string", "LogGroupNamePrefix": "*string", "NextToken": "*string"},
			"describe-log-streams":                          {"Descending": "*bool", "Limit": "*int32", "LogGroupIdentifier": "*string", "LogGroupName": "*string", "LogStreamNamePrefix": "*string", "NextToken": "*string", "OrderBy": "types.OrderBy"},
			"describe-metric-filters":                       {"FilterNamePrefix": "*string", "Limit": "*int32", "LogGroupName": "*string", "MetricName": "*string", "MetricNamespace": "*string", "NextToken": "*string"},
			"describe-queries":                              {"LogGroupName": "*string", "MaxResults": "*int32", "NextToken": "*string", "QueryLanguage": "types.QueryLanguage", "Status": "types.QueryStatus"},
			"describe-query-definitions":                    {"MaxResults": "*int32", "NextToken": "*string", "QueryDefinitionNamePrefix": "*string", "QueryLanguage": "types.QueryLanguage"},
			"describe-resource-policies":                    {"Limit": "*int32", "NextToken": "*string", "PolicyScope": "types.PolicyScope", "ResourceArn": "*string"},
			"describe-subscription-filters":                 {"FilterNamePrefix": "*string", "Limit": "*int32", "LogGroupName": "*string", "NextToken": "*string"},
			"disassociate-kms-key":                          {"LogGroupName": "*string", "ResourceIdentifier": "*string"},
			"disassociate-source-from-s3-table-integration": {"Identifier": "*string"},
			"filter-log-events":                             {"EndTime": "*int64", "FilterPattern": "*string", "Interleaved": "*bool", "Limit": "*int32", "LogGroupIdentifier": "*string", "LogGroupName": "*string", "LogStreamNamePrefix": "*string", "LogStreamNames": "[]string", "NextToken": "*string", "StartTime": "*int64", "Unmask": "bool"},
			"get-data-protection-policy":                    {"LogGroupIdentifier": "*string"},
			"get-delivery":                                  {"Id": "*string"},
			"get-delivery-destination":                      {"Name": "*string"},
			"get-delivery-destination-policy":               {"DeliveryDestinationName": "*string"},
			"get-delivery-source":                           {"Name": "*string"},
			"get-integration":                               {"IntegrationName": "*string"},
			"get-log-anomaly-detector":                      {"AnomalyDetectorArn": "*string"},
			"get-log-events":                                {"EndTime": "*int64", "Limit": "*int32", "LogGroupIdentifier": "*string", "LogGroupName": "*string", "LogStreamName": "*string", "NextToken": "*string", "StartFromHead": "*bool", "StartTime": "*int64", "Unmask": "bool"},
			"get-log-fields":                                {"DataSourceName": "*string", "DataSourceType": "*string"},
			"get-log-group-fields":                          {"LogGroupIdentifier": "*string", "LogGroupName": "*string", "Time": "*int64"},
			"get-log-object":                                {"LogObjectPointer": "*string", "Unmask": "bool"},
			"get-log-record":                                {"LogRecordPointer": "*string", "Unmask": "bool"},
			"get-query-results":                             {"QueryId": "*string"},
			"get-scheduled-query":                           {"Identifier": "*string"},
			"get-scheduled-query-history":                   {"EndTime": "*int64", "ExecutionStatuses": "[]types.ExecutionStatus", "Identifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "StartTime": "*int64"},
			"get-transformer":                               {"LogGroupIdentifier": "*string"},
			"list-aggregate-log-group-summaries":            {"AccountIdentifiers": "[]string", "DataSources": "[]types.DataSourceFilter", "GroupBy": "types.ListAggregateLogGroupSummariesGroupBy", "IncludeLinkedAccounts": "*bool", "Limit": "*int32", "LogGroupClass": "types.LogGroupClass", "LogGroupNamePattern": "*string", "NextToken": "*string"},
			"list-anomalies":                                {"AnomalyDetectorArn": "*string", "Limit": "*int32", "NextToken": "*string", "SuppressionState": "types.SuppressionState"},
			"list-integrations":                             {"IntegrationNamePrefix": "*string", "IntegrationStatus": "types.IntegrationStatus", "IntegrationType": "types.IntegrationType"},
			"list-log-anomaly-detectors":                    {"FilterLogGroupArn": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-log-groups":                               {"AccountIdentifiers": "[]string", "DataSources": "[]types.DataSourceFilter", "FieldIndexNames": "[]string", "IncludeLinkedAccounts": "*bool", "Limit": "*int32", "LogGroupClass": "types.LogGroupClass", "LogGroupNamePattern": "*string", "NextToken": "*string"},
			"list-log-groups-for-query":                     {"MaxResults": "*int32", "NextToken": "*string", "QueryId": "*string"},
			"list-scheduled-queries":                        {"MaxResults": "*int32", "NextToken": "*string", "State": "types.ScheduledQueryState"},
			"list-sources-for-s3-table-integration":         {"IntegrationArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                        {"ResourceArn": "*string"},
			"list-tags-log-group":                           {"LogGroupName": "*string"},
			"put-account-policy":                            {"PolicyDocument": "*string", "PolicyName": "*string", "PolicyType": "types.PolicyType", "Scope": "types.Scope", "SelectionCriteria": "*string"},
			"put-bearer-token-authentication":               {"BearerTokenAuthenticationEnabled": "*bool", "LogGroupIdentifier": "*string"},
			"put-data-protection-policy":                    {"LogGroupIdentifier": "*string", "PolicyDocument": "*string"},
			"put-delivery-destination":                      {"DeliveryDestinationConfiguration": "*types.DeliveryDestinationConfiguration", "DeliveryDestinationType": "types.DeliveryDestinationType", "Name": "*string", "OutputFormat": "types.OutputFormat", "Tags": "map[string]string"},
			"put-delivery-destination-policy":               {"DeliveryDestinationName": "*string", "DeliveryDestinationPolicy": "*string"},
			"put-delivery-source":                           {"LogType": "*string", "Name": "*string", "ResourceArn": "*string", "Tags": "map[string]string"},
			"put-destination":                               {"DestinationName": "*string", "RoleArn": "*string", "Tags": "map[string]string", "TargetArn": "*string"},
			"put-destination-policy":                        {"AccessPolicy": "*string", "DestinationName": "*string", "ForceUpdate": "*bool"},
			"put-index-policy":                              {"LogGroupIdentifier": "*string", "PolicyDocument": "*string"},
			"put-integration":                               {"IntegrationName": "*string", "IntegrationType": "types.IntegrationType", "ResourceConfig": "types.ResourceConfig"},
			"put-log-events":                                {"Entity": "*types.Entity", "LogEvents": "[]types.InputLogEvent", "LogGroupName": "*string", "LogStreamName": "*string", "SequenceToken": "*string"},
			"put-log-group-deletion-protection":             {"DeletionProtectionEnabled": "*bool", "LogGroupIdentifier": "*string"},
			"put-metric-filter":                             {"ApplyOnTransformedLogs": "bool", "EmitSystemFieldDimensions": "[]string", "FieldSelectionCriteria": "*string", "FilterName": "*string", "FilterPattern": "*string", "LogGroupName": "*string", "MetricTransformations": "[]types.MetricTransformation"},
			"put-query-definition":                          {"ClientToken": "*string", "LogGroupNames": "[]string", "Name": "*string", "QueryDefinitionId": "*string", "QueryLanguage": "types.QueryLanguage", "QueryString": "*string"},
			"put-resource-policy":                           {"ExpectedRevisionId": "*string", "PolicyDocument": "*string", "PolicyName": "*string", "ResourceArn": "*string"},
			"put-retention-policy":                          {"LogGroupName": "*string", "RetentionInDays": "*int32"},
			"put-subscription-filter":                       {"ApplyOnTransformedLogs": "bool", "DestinationArn": "*string", "Distribution": "types.Distribution", "EmitSystemFields": "[]string", "FieldSelectionCriteria": "*string", "FilterName": "*string", "FilterPattern": "*string", "LogGroupName": "*string", "RoleArn": "*string"},
			"put-transformer":                               {"LogGroupIdentifier": "*string", "TransformerConfig": "[]types.Processor"},
			"start-live-tail":                               {"LogEventFilterPattern": "*string", "LogGroupIdentifiers": "[]string", "LogStreamNamePrefixes": "[]string", "LogStreamNames": "[]string"},
			"start-query":                                   {"EndTime": "*int64", "Limit": "*int32", "LogGroupIdentifiers": "[]string", "LogGroupName": "*string", "LogGroupNames": "[]string", "QueryLanguage": "types.QueryLanguage", "QueryString": "*string", "StartTime": "*int64"},
			"stop-query":                                    {"QueryId": "*string"},
			"tag-log-group":                                 {"LogGroupName": "*string", "Tags": "map[string]string"},
			"tag-resource":                                  {"ResourceArn": "*string", "Tags": "map[string]string"},
			"test-metric-filter":                            {"FilterPattern": "*string", "LogEventMessages": "[]string"},
			"test-transformer":                              {"LogEventMessages": "[]string", "TransformerConfig": "[]types.Processor"},
			"untag-log-group":                               {"LogGroupName": "*string", "Tags": "[]string"},
			"untag-resource":                                {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-anomaly":                                {"AnomalyDetectorArn": "*string", "AnomalyId": "*string", "Baseline": "*bool", "PatternId": "*string", "SuppressionPeriod": "*types.SuppressionPeriod", "SuppressionType": "types.SuppressionType"},
			"update-delivery-configuration":                 {"FieldDelimiter": "*string", "Id": "*string", "RecordFields": "[]string", "S3DeliveryConfiguration": "*types.S3DeliveryConfiguration"},
			"update-log-anomaly-detector":                   {"AnomalyDetectorArn": "*string", "AnomalyVisibilityTime": "*int64", "Enabled": "*bool", "EvaluationFrequency": "types.EvaluationFrequency", "FilterPattern": "*string"},
			"update-scheduled-query":                        {"Description": "*string", "DestinationConfiguration": "*types.DestinationConfiguration", "ExecutionRoleArn": "*string", "Identifier": "*string", "LogGroupIdentifiers": "[]string", "QueryLanguage": "types.QueryLanguage", "QueryString": "*string", "ScheduleEndTime": "*int64", "ScheduleExpression": "*string", "ScheduleStartTime": "*int64", "StartTimeOffset": "*int64", "State": "types.ScheduledQueryState", "Timezone": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-kms-key":                             {"KmsKeyId"},
			"associate-source-to-s3-table-integration":      {"DataSource", "IntegrationArn"},
			"cancel-export-task":                            {"TaskId"},
			"cancel-import-task":                            {"ImportId"},
			"create-delivery":                               {"DeliveryDestinationArn", "DeliverySourceName"},
			"create-export-task":                            {"Destination", "From", "LogGroupName", "To"},
			"create-import-task":                            {"ImportRoleArn", "ImportSourceArn"},
			"create-log-anomaly-detector":                   {"LogGroupArnList"},
			"create-log-group":                              {"LogGroupName"},
			"create-log-stream":                             {"LogGroupName", "LogStreamName"},
			"create-scheduled-query":                        {"ExecutionRoleArn", "Name", "QueryLanguage", "QueryString", "ScheduleExpression"},
			"delete-account-policy":                         {"PolicyName", "PolicyType"},
			"delete-data-protection-policy":                 {"LogGroupIdentifier"},
			"delete-delivery":                               {"Id"},
			"delete-delivery-destination":                   {"Name"},
			"delete-delivery-destination-policy":            {"DeliveryDestinationName"},
			"delete-delivery-source":                        {"Name"},
			"delete-destination":                            {"DestinationName"},
			"delete-index-policy":                           {"LogGroupIdentifier"},
			"delete-integration":                            {"IntegrationName"},
			"delete-log-anomaly-detector":                   {"AnomalyDetectorArn"},
			"delete-log-group":                              {"LogGroupName"},
			"delete-log-stream":                             {"LogGroupName", "LogStreamName"},
			"delete-metric-filter":                          {"FilterName", "LogGroupName"},
			"delete-query-definition":                       {"QueryDefinitionId"},
			"delete-resource-policy":                        {},
			"delete-retention-policy":                       {"LogGroupName"},
			"delete-scheduled-query":                        {"Identifier"},
			"delete-subscription-filter":                    {"FilterName", "LogGroupName"},
			"delete-transformer":                            {"LogGroupIdentifier"},
			"describe-account-policies":                     {"PolicyType"},
			"describe-configuration-templates":              {},
			"describe-deliveries":                           {},
			"describe-delivery-destinations":                {},
			"describe-delivery-sources":                     {},
			"describe-destinations":                         {},
			"describe-export-tasks":                         {},
			"describe-field-indexes":                        {"LogGroupIdentifiers"},
			"describe-import-task-batches":                  {"ImportId"},
			"describe-import-tasks":                         {},
			"describe-index-policies":                       {"LogGroupIdentifiers"},
			"describe-log-groups":                           {},
			"describe-log-streams":                          {},
			"describe-metric-filters":                       {},
			"describe-queries":                              {},
			"describe-query-definitions":                    {},
			"describe-resource-policies":                    {},
			"describe-subscription-filters":                 {"LogGroupName"},
			"disassociate-kms-key":                          {},
			"disassociate-source-from-s3-table-integration": {"Identifier"},
			"filter-log-events":                             {},
			"get-data-protection-policy":                    {"LogGroupIdentifier"},
			"get-delivery":                                  {"Id"},
			"get-delivery-destination":                      {"Name"},
			"get-delivery-destination-policy":               {"DeliveryDestinationName"},
			"get-delivery-source":                           {"Name"},
			"get-integration":                               {"IntegrationName"},
			"get-log-anomaly-detector":                      {"AnomalyDetectorArn"},
			"get-log-events":                                {"LogStreamName"},
			"get-log-fields":                                {"DataSourceName", "DataSourceType"},
			"get-log-group-fields":                          {},
			"get-log-object":                                {"LogObjectPointer"},
			"get-log-record":                                {"LogRecordPointer"},
			"get-query-results":                             {"QueryId"},
			"get-scheduled-query":                           {"Identifier"},
			"get-scheduled-query-history":                   {"EndTime", "Identifier", "StartTime"},
			"get-transformer":                               {"LogGroupIdentifier"},
			"list-aggregate-log-group-summaries":            {"GroupBy"},
			"list-anomalies":                                {},
			"list-integrations":                             {},
			"list-log-anomaly-detectors":                    {},
			"list-log-groups":                               {},
			"list-log-groups-for-query":                     {"QueryId"},
			"list-scheduled-queries":                        {},
			"list-sources-for-s3-table-integration":         {"IntegrationArn"},
			"list-tags-for-resource":                        {"ResourceArn"},
			"list-tags-log-group":                           {"LogGroupName"},
			"put-account-policy":                            {"PolicyDocument", "PolicyName", "PolicyType"},
			"put-bearer-token-authentication":               {"BearerTokenAuthenticationEnabled", "LogGroupIdentifier"},
			"put-data-protection-policy":                    {"LogGroupIdentifier", "PolicyDocument"},
			"put-delivery-destination":                      {"Name"},
			"put-delivery-destination-policy":               {"DeliveryDestinationName", "DeliveryDestinationPolicy"},
			"put-delivery-source":                           {"LogType", "Name", "ResourceArn"},
			"put-destination":                               {"DestinationName", "RoleArn", "TargetArn"},
			"put-destination-policy":                        {"AccessPolicy", "DestinationName"},
			"put-index-policy":                              {"LogGroupIdentifier", "PolicyDocument"},
			"put-integration":                               {"IntegrationName", "IntegrationType", "ResourceConfig"},
			"put-log-events":                                {"LogEvents", "LogGroupName", "LogStreamName"},
			"put-log-group-deletion-protection":             {"DeletionProtectionEnabled", "LogGroupIdentifier"},
			"put-metric-filter":                             {"FilterName", "FilterPattern", "LogGroupName", "MetricTransformations"},
			"put-query-definition":                          {"Name", "QueryString"},
			"put-resource-policy":                           {},
			"put-retention-policy":                          {"LogGroupName", "RetentionInDays"},
			"put-subscription-filter":                       {"DestinationArn", "FilterName", "FilterPattern", "LogGroupName"},
			"put-transformer":                               {"LogGroupIdentifier", "TransformerConfig"},
			"start-live-tail":                               {"LogGroupIdentifiers"},
			"start-query":                                   {"EndTime", "QueryString", "StartTime"},
			"stop-query":                                    {"QueryId"},
			"tag-log-group":                                 {"LogGroupName", "Tags"},
			"tag-resource":                                  {"ResourceArn", "Tags"},
			"test-metric-filter":                            {"FilterPattern", "LogEventMessages"},
			"test-transformer":                              {"LogEventMessages", "TransformerConfig"},
			"untag-log-group":                               {"LogGroupName", "Tags"},
			"untag-resource":                                {"ResourceArn", "TagKeys"},
			"update-anomaly":                                {"AnomalyDetectorArn"},
			"update-delivery-configuration":                 {"Id"},
			"update-log-anomaly-detector":                   {"AnomalyDetectorArn", "Enabled"},
			"update-scheduled-query":                        {"ExecutionRoleArn", "Identifier", "QueryLanguage", "QueryString", "ScheduleExpression"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("cloudwatchlogs", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
