package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/route53/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"activate-key-signing-key", "associate-vpc-with-hosted-zone", "change-cidr-collection", "change-resource-record-sets", "change-tags-for-resource", "create-cidr-collection", "create-health-check", "create-hosted-zone", "create-key-signing-key", "create-query-logging-config", "create-reusable-delegation-set", "create-traffic-policy", "create-traffic-policy-instance", "create-traffic-policy-version", "create-vpc-association-authorization", "deactivate-key-signing-key", "delete-cidr-collection", "delete-health-check", "delete-hosted-zone", "delete-key-signing-key", "delete-query-logging-config", "delete-reusable-delegation-set", "delete-traffic-policy", "delete-traffic-policy-instance", "delete-vpc-association-authorization", "disable-hosted-zone-dnssec", "disassociate-vpc-from-hosted-zone", "enable-hosted-zone-dnssec", "get-account-limit", "get-change", "get-checker-ip-ranges", "get-dnssec", "get-geo-location", "get-health-check", "get-health-check-count", "get-health-check-last-failure-reason", "get-health-check-status", "get-hosted-zone", "get-hosted-zone-count", "get-hosted-zone-limit", "get-query-logging-config", "get-reusable-delegation-set", "get-reusable-delegation-set-limit", "get-traffic-policy", "get-traffic-policy-instance", "get-traffic-policy-instance-count", "list-cidr-blocks", "list-cidr-collections", "list-cidr-locations", "list-geo-locations", "list-health-checks", "list-hosted-zones", "list-hosted-zones-by-name", "list-hosted-zones-by-vpc", "list-query-logging-configs", "list-resource-record-sets", "list-reusable-delegation-sets", "list-tags-for-resource", "list-tags-for-resources", "list-traffic-policies", "list-traffic-policy-instances", "list-traffic-policy-instances-by-hosted-zone", "list-traffic-policy-instances-by-policy", "list-traffic-policy-versions", "list-vpc-association-authorizations", "test-dns-answer", "update-health-check", "update-hosted-zone-comment", "update-hosted-zone-features", "update-traffic-policy-comment", "update-traffic-policy-instance"},
		OperationSet: map[string]bool{"activate-key-signing-key": true, "associate-vpc-with-hosted-zone": true, "change-cidr-collection": true, "change-resource-record-sets": true, "change-tags-for-resource": true, "create-cidr-collection": true, "create-health-check": true, "create-hosted-zone": true, "create-key-signing-key": true, "create-query-logging-config": true, "create-reusable-delegation-set": true, "create-traffic-policy": true, "create-traffic-policy-instance": true, "create-traffic-policy-version": true, "create-vpc-association-authorization": true, "deactivate-key-signing-key": true, "delete-cidr-collection": true, "delete-health-check": true, "delete-hosted-zone": true, "delete-key-signing-key": true, "delete-query-logging-config": true, "delete-reusable-delegation-set": true, "delete-traffic-policy": true, "delete-traffic-policy-instance": true, "delete-vpc-association-authorization": true, "disable-hosted-zone-dnssec": true, "disassociate-vpc-from-hosted-zone": true, "enable-hosted-zone-dnssec": true, "get-account-limit": true, "get-change": true, "get-checker-ip-ranges": true, "get-dnssec": true, "get-geo-location": true, "get-health-check": true, "get-health-check-count": true, "get-health-check-last-failure-reason": true, "get-health-check-status": true, "get-hosted-zone": true, "get-hosted-zone-count": true, "get-hosted-zone-limit": true, "get-query-logging-config": true, "get-reusable-delegation-set": true, "get-reusable-delegation-set-limit": true, "get-traffic-policy": true, "get-traffic-policy-instance": true, "get-traffic-policy-instance-count": true, "list-cidr-blocks": true, "list-cidr-collections": true, "list-cidr-locations": true, "list-geo-locations": true, "list-health-checks": true, "list-hosted-zones": true, "list-hosted-zones-by-name": true, "list-hosted-zones-by-vpc": true, "list-query-logging-configs": true, "list-resource-record-sets": true, "list-reusable-delegation-sets": true, "list-tags-for-resource": true, "list-tags-for-resources": true, "list-traffic-policies": true, "list-traffic-policy-instances": true, "list-traffic-policy-instances-by-hosted-zone": true, "list-traffic-policy-instances-by-policy": true, "list-traffic-policy-versions": true, "list-vpc-association-authorizations": true, "test-dns-answer": true, "update-health-check": true, "update-hosted-zone-comment": true, "update-hosted-zone-features": true, "update-traffic-policy-comment": true, "update-traffic-policy-instance": true},
		OperationInputs: map[string][]string{
			"activate-key-signing-key":                     {"HostedZoneId", "Name"},
			"associate-vpc-with-hosted-zone":               {"Comment", "HostedZoneId", "VPC"},
			"change-cidr-collection":                       {"Changes", "CollectionVersion", "Id"},
			"change-resource-record-sets":                  {"ChangeBatch", "HostedZoneId"},
			"change-tags-for-resource":                     {"AddTags", "RemoveTagKeys", "ResourceId", "ResourceType"},
			"create-cidr-collection":                       {"CallerReference", "Name"},
			"create-health-check":                          {"CallerReference", "HealthCheckConfig"},
			"create-hosted-zone":                           {"CallerReference", "DelegationSetId", "HostedZoneConfig", "Name", "VPC"},
			"create-key-signing-key":                       {"CallerReference", "HostedZoneId", "KeyManagementServiceArn", "Name", "Status"},
			"create-query-logging-config":                  {"CloudWatchLogsLogGroupArn", "HostedZoneId"},
			"create-reusable-delegation-set":               {"CallerReference", "HostedZoneId"},
			"create-traffic-policy":                        {"Comment", "Document", "Name"},
			"create-traffic-policy-instance":               {"HostedZoneId", "Name", "TTL", "TrafficPolicyId", "TrafficPolicyVersion"},
			"create-traffic-policy-version":                {"Comment", "Document", "Id"},
			"create-vpc-association-authorization":         {"HostedZoneId", "VPC"},
			"deactivate-key-signing-key":                   {"HostedZoneId", "Name"},
			"delete-cidr-collection":                       {"Id"},
			"delete-health-check":                          {"HealthCheckId"},
			"delete-hosted-zone":                           {"Id"},
			"delete-key-signing-key":                       {"HostedZoneId", "Name"},
			"delete-query-logging-config":                  {"Id"},
			"delete-reusable-delegation-set":               {"Id"},
			"delete-traffic-policy":                        {"Id", "Version"},
			"delete-traffic-policy-instance":               {"Id"},
			"delete-vpc-association-authorization":         {"HostedZoneId", "VPC"},
			"disable-hosted-zone-dnssec":                   {"HostedZoneId"},
			"disassociate-vpc-from-hosted-zone":            {"Comment", "HostedZoneId", "VPC"},
			"enable-hosted-zone-dnssec":                    {"HostedZoneId"},
			"get-account-limit":                            {"Type"},
			"get-change":                                   {"Id"},
			"get-checker-ip-ranges":                        {},
			"get-dnssec":                                   {"HostedZoneId"},
			"get-geo-location":                             {"ContinentCode", "CountryCode", "SubdivisionCode"},
			"get-health-check":                             {"HealthCheckId"},
			"get-health-check-count":                       {},
			"get-health-check-last-failure-reason":         {"HealthCheckId"},
			"get-health-check-status":                      {"HealthCheckId"},
			"get-hosted-zone":                              {"Id"},
			"get-hosted-zone-count":                        {},
			"get-hosted-zone-limit":                        {"HostedZoneId", "Type"},
			"get-query-logging-config":                     {"Id"},
			"get-reusable-delegation-set":                  {"Id"},
			"get-reusable-delegation-set-limit":            {"DelegationSetId", "Type"},
			"get-traffic-policy":                           {"Id", "Version"},
			"get-traffic-policy-instance":                  {"Id"},
			"get-traffic-policy-instance-count":            {},
			"list-cidr-blocks":                             {"CollectionId", "LocationName", "MaxResults", "NextToken"},
			"list-cidr-collections":                        {"MaxResults", "NextToken"},
			"list-cidr-locations":                          {"CollectionId", "MaxResults", "NextToken"},
			"list-geo-locations":                           {"MaxItems", "StartContinentCode", "StartCountryCode", "StartSubdivisionCode"},
			"list-health-checks":                           {"Marker", "MaxItems"},
			"list-hosted-zones":                            {"DelegationSetId", "HostedZoneType", "Marker", "MaxItems"},
			"list-hosted-zones-by-name":                    {"DNSName", "HostedZoneId", "MaxItems"},
			"list-hosted-zones-by-vpc":                     {"MaxItems", "NextToken", "VPCId", "VPCRegion"},
			"list-query-logging-configs":                   {"HostedZoneId", "MaxResults", "NextToken"},
			"list-resource-record-sets":                    {"HostedZoneId", "MaxItems", "StartRecordIdentifier", "StartRecordName", "StartRecordType"},
			"list-reusable-delegation-sets":                {"Marker", "MaxItems"},
			"list-tags-for-resource":                       {"ResourceId", "ResourceType"},
			"list-tags-for-resources":                      {"ResourceIds", "ResourceType"},
			"list-traffic-policies":                        {"MaxItems", "TrafficPolicyIdMarker"},
			"list-traffic-policy-instances":                {"HostedZoneIdMarker", "MaxItems", "TrafficPolicyInstanceNameMarker", "TrafficPolicyInstanceTypeMarker"},
			"list-traffic-policy-instances-by-hosted-zone": {"HostedZoneId", "MaxItems", "TrafficPolicyInstanceNameMarker", "TrafficPolicyInstanceTypeMarker"},
			"list-traffic-policy-instances-by-policy":      {"HostedZoneIdMarker", "MaxItems", "TrafficPolicyId", "TrafficPolicyInstanceNameMarker", "TrafficPolicyInstanceTypeMarker", "TrafficPolicyVersion"},
			"list-traffic-policy-versions":                 {"Id", "MaxItems", "TrafficPolicyVersionMarker"},
			"list-vpc-association-authorizations":          {"HostedZoneId", "MaxResults", "NextToken"},
			"test-dns-answer":                              {"EDNS0ClientSubnetIP", "EDNS0ClientSubnetMask", "HostedZoneId", "RecordName", "RecordType", "ResolverIP"},
			"update-health-check":                          {"AlarmIdentifier", "ChildHealthChecks", "Disabled", "EnableSNI", "FailureThreshold", "FullyQualifiedDomainName", "HealthCheckId", "HealthCheckVersion", "HealthThreshold", "IPAddress", "InsufficientDataHealthStatus", "Inverted", "Port", "Regions", "ResetElements", "ResourcePath", "SearchString"},
			"update-hosted-zone-comment":                   {"Comment", "Id"},
			"update-hosted-zone-features":                  {"EnableAcceleratedRecovery", "HostedZoneId"},
			"update-traffic-policy-comment":                {"Comment", "Id", "Version"},
			"update-traffic-policy-instance":               {"Id", "TTL", "TrafficPolicyId", "TrafficPolicyVersion"},
		},
		OperationInputTypes: map[string]map[string]string{
			"activate-key-signing-key":                     {"HostedZoneId": "*string", "Name": "*string"},
			"associate-vpc-with-hosted-zone":               {"Comment": "*string", "HostedZoneId": "*string", "VPC": "*types.VPC"},
			"change-cidr-collection":                       {"Changes": "[]types.CidrCollectionChange", "CollectionVersion": "*int64", "Id": "*string"},
			"change-resource-record-sets":                  {"ChangeBatch": "*types.ChangeBatch", "HostedZoneId": "*string"},
			"change-tags-for-resource":                     {"AddTags": "[]types.Tag", "RemoveTagKeys": "[]string", "ResourceId": "*string", "ResourceType": "types.TagResourceType"},
			"create-cidr-collection":                       {"CallerReference": "*string", "Name": "*string"},
			"create-health-check":                          {"CallerReference": "*string", "HealthCheckConfig": "*types.HealthCheckConfig"},
			"create-hosted-zone":                           {"CallerReference": "*string", "DelegationSetId": "*string", "HostedZoneConfig": "*types.HostedZoneConfig", "Name": "*string", "VPC": "*types.VPC"},
			"create-key-signing-key":                       {"CallerReference": "*string", "HostedZoneId": "*string", "KeyManagementServiceArn": "*string", "Name": "*string", "Status": "*string"},
			"create-query-logging-config":                  {"CloudWatchLogsLogGroupArn": "*string", "HostedZoneId": "*string"},
			"create-reusable-delegation-set":               {"CallerReference": "*string", "HostedZoneId": "*string"},
			"create-traffic-policy":                        {"Comment": "*string", "Document": "*string", "Name": "*string"},
			"create-traffic-policy-instance":               {"HostedZoneId": "*string", "Name": "*string", "TTL": "*int64", "TrafficPolicyId": "*string", "TrafficPolicyVersion": "*int32"},
			"create-traffic-policy-version":                {"Comment": "*string", "Document": "*string", "Id": "*string"},
			"create-vpc-association-authorization":         {"HostedZoneId": "*string", "VPC": "*types.VPC"},
			"deactivate-key-signing-key":                   {"HostedZoneId": "*string", "Name": "*string"},
			"delete-cidr-collection":                       {"Id": "*string"},
			"delete-health-check":                          {"HealthCheckId": "*string"},
			"delete-hosted-zone":                           {"Id": "*string"},
			"delete-key-signing-key":                       {"HostedZoneId": "*string", "Name": "*string"},
			"delete-query-logging-config":                  {"Id": "*string"},
			"delete-reusable-delegation-set":               {"Id": "*string"},
			"delete-traffic-policy":                        {"Id": "*string", "Version": "*int32"},
			"delete-traffic-policy-instance":               {"Id": "*string"},
			"delete-vpc-association-authorization":         {"HostedZoneId": "*string", "VPC": "*types.VPC"},
			"disable-hosted-zone-dnssec":                   {"HostedZoneId": "*string"},
			"disassociate-vpc-from-hosted-zone":            {"Comment": "*string", "HostedZoneId": "*string", "VPC": "*types.VPC"},
			"enable-hosted-zone-dnssec":                    {"HostedZoneId": "*string"},
			"get-account-limit":                            {"Type": "types.AccountLimitType"},
			"get-change":                                   {"Id": "*string"},
			"get-checker-ip-ranges":                        {},
			"get-dnssec":                                   {"HostedZoneId": "*string"},
			"get-geo-location":                             {"ContinentCode": "*string", "CountryCode": "*string", "SubdivisionCode": "*string"},
			"get-health-check":                             {"HealthCheckId": "*string"},
			"get-health-check-count":                       {},
			"get-health-check-last-failure-reason":         {"HealthCheckId": "*string"},
			"get-health-check-status":                      {"HealthCheckId": "*string"},
			"get-hosted-zone":                              {"Id": "*string"},
			"get-hosted-zone-count":                        {},
			"get-hosted-zone-limit":                        {"HostedZoneId": "*string", "Type": "types.HostedZoneLimitType"},
			"get-query-logging-config":                     {"Id": "*string"},
			"get-reusable-delegation-set":                  {"Id": "*string"},
			"get-reusable-delegation-set-limit":            {"DelegationSetId": "*string", "Type": "types.ReusableDelegationSetLimitType"},
			"get-traffic-policy":                           {"Id": "*string", "Version": "*int32"},
			"get-traffic-policy-instance":                  {"Id": "*string"},
			"get-traffic-policy-instance-count":            {},
			"list-cidr-blocks":                             {"CollectionId": "*string", "LocationName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-cidr-collections":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-cidr-locations":                          {"CollectionId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-geo-locations":                           {"MaxItems": "*int32", "StartContinentCode": "*string", "StartCountryCode": "*string", "StartSubdivisionCode": "*string"},
			"list-health-checks":                           {"Marker": "*string", "MaxItems": "*int32"},
			"list-hosted-zones":                            {"DelegationSetId": "*string", "HostedZoneType": "types.HostedZoneType", "Marker": "*string", "MaxItems": "*int32"},
			"list-hosted-zones-by-name":                    {"DNSName": "*string", "HostedZoneId": "*string", "MaxItems": "*int32"},
			"list-hosted-zones-by-vpc":                     {"MaxItems": "*int32", "NextToken": "*string", "VPCId": "*string", "VPCRegion": "types.VPCRegion"},
			"list-query-logging-configs":                   {"HostedZoneId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-resource-record-sets":                    {"HostedZoneId": "*string", "MaxItems": "*int32", "StartRecordIdentifier": "*string", "StartRecordName": "*string", "StartRecordType": "types.RRType"},
			"list-reusable-delegation-sets":                {"Marker": "*string", "MaxItems": "*int32"},
			"list-tags-for-resource":                       {"ResourceId": "*string", "ResourceType": "types.TagResourceType"},
			"list-tags-for-resources":                      {"ResourceIds": "[]string", "ResourceType": "types.TagResourceType"},
			"list-traffic-policies":                        {"MaxItems": "*int32", "TrafficPolicyIdMarker": "*string"},
			"list-traffic-policy-instances":                {"HostedZoneIdMarker": "*string", "MaxItems": "*int32", "TrafficPolicyInstanceNameMarker": "*string", "TrafficPolicyInstanceTypeMarker": "types.RRType"},
			"list-traffic-policy-instances-by-hosted-zone": {"HostedZoneId": "*string", "MaxItems": "*int32", "TrafficPolicyInstanceNameMarker": "*string", "TrafficPolicyInstanceTypeMarker": "types.RRType"},
			"list-traffic-policy-instances-by-policy":      {"HostedZoneIdMarker": "*string", "MaxItems": "*int32", "TrafficPolicyId": "*string", "TrafficPolicyInstanceNameMarker": "*string", "TrafficPolicyInstanceTypeMarker": "types.RRType", "TrafficPolicyVersion": "*int32"},
			"list-traffic-policy-versions":                 {"Id": "*string", "MaxItems": "*int32", "TrafficPolicyVersionMarker": "*string"},
			"list-vpc-association-authorizations":          {"HostedZoneId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"test-dns-answer":                              {"EDNS0ClientSubnetIP": "*string", "EDNS0ClientSubnetMask": "*string", "HostedZoneId": "*string", "RecordName": "*string", "RecordType": "types.RRType", "ResolverIP": "*string"},
			"update-health-check":                          {"AlarmIdentifier": "*types.AlarmIdentifier", "ChildHealthChecks": "[]string", "Disabled": "*bool", "EnableSNI": "*bool", "FailureThreshold": "*int32", "FullyQualifiedDomainName": "*string", "HealthCheckId": "*string", "HealthCheckVersion": "*int64", "HealthThreshold": "*int32", "IPAddress": "*string", "InsufficientDataHealthStatus": "types.InsufficientDataHealthStatus", "Inverted": "*bool", "Port": "*int32", "Regions": "[]types.HealthCheckRegion", "ResetElements": "[]types.ResettableElementName", "ResourcePath": "*string", "SearchString": "*string"},
			"update-hosted-zone-comment":                   {"Comment": "*string", "Id": "*string"},
			"update-hosted-zone-features":                  {"EnableAcceleratedRecovery": "*bool", "HostedZoneId": "*string"},
			"update-traffic-policy-comment":                {"Comment": "*string", "Id": "*string", "Version": "*int32"},
			"update-traffic-policy-instance":               {"Id": "*string", "TTL": "*int64", "TrafficPolicyId": "*string", "TrafficPolicyVersion": "*int32"},
		},
		OperationInputRequired: map[string][]string{
			"activate-key-signing-key":                     {"HostedZoneId", "Name"},
			"associate-vpc-with-hosted-zone":               {"HostedZoneId", "VPC"},
			"change-cidr-collection":                       {"Changes", "Id"},
			"change-resource-record-sets":                  {"ChangeBatch", "HostedZoneId"},
			"change-tags-for-resource":                     {"ResourceId", "ResourceType"},
			"create-cidr-collection":                       {"CallerReference", "Name"},
			"create-health-check":                          {"CallerReference", "HealthCheckConfig"},
			"create-hosted-zone":                           {"CallerReference", "Name"},
			"create-key-signing-key":                       {"CallerReference", "HostedZoneId", "KeyManagementServiceArn", "Name", "Status"},
			"create-query-logging-config":                  {"CloudWatchLogsLogGroupArn", "HostedZoneId"},
			"create-reusable-delegation-set":               {"CallerReference"},
			"create-traffic-policy":                        {"Document", "Name"},
			"create-traffic-policy-instance":               {"HostedZoneId", "Name", "TTL", "TrafficPolicyId", "TrafficPolicyVersion"},
			"create-traffic-policy-version":                {"Document", "Id"},
			"create-vpc-association-authorization":         {"HostedZoneId", "VPC"},
			"deactivate-key-signing-key":                   {"HostedZoneId", "Name"},
			"delete-cidr-collection":                       {"Id"},
			"delete-health-check":                          {"HealthCheckId"},
			"delete-hosted-zone":                           {"Id"},
			"delete-key-signing-key":                       {"HostedZoneId", "Name"},
			"delete-query-logging-config":                  {"Id"},
			"delete-reusable-delegation-set":               {"Id"},
			"delete-traffic-policy":                        {"Id", "Version"},
			"delete-traffic-policy-instance":               {"Id"},
			"delete-vpc-association-authorization":         {"HostedZoneId", "VPC"},
			"disable-hosted-zone-dnssec":                   {"HostedZoneId"},
			"disassociate-vpc-from-hosted-zone":            {"HostedZoneId", "VPC"},
			"enable-hosted-zone-dnssec":                    {"HostedZoneId"},
			"get-account-limit":                            {"Type"},
			"get-change":                                   {"Id"},
			"get-checker-ip-ranges":                        {},
			"get-dnssec":                                   {"HostedZoneId"},
			"get-geo-location":                             {},
			"get-health-check":                             {"HealthCheckId"},
			"get-health-check-count":                       {},
			"get-health-check-last-failure-reason":         {"HealthCheckId"},
			"get-health-check-status":                      {"HealthCheckId"},
			"get-hosted-zone":                              {"Id"},
			"get-hosted-zone-count":                        {},
			"get-hosted-zone-limit":                        {"HostedZoneId", "Type"},
			"get-query-logging-config":                     {"Id"},
			"get-reusable-delegation-set":                  {"Id"},
			"get-reusable-delegation-set-limit":            {"DelegationSetId", "Type"},
			"get-traffic-policy":                           {"Id", "Version"},
			"get-traffic-policy-instance":                  {"Id"},
			"get-traffic-policy-instance-count":            {},
			"list-cidr-blocks":                             {"CollectionId"},
			"list-cidr-collections":                        {},
			"list-cidr-locations":                          {"CollectionId"},
			"list-geo-locations":                           {},
			"list-health-checks":                           {},
			"list-hosted-zones":                            {},
			"list-hosted-zones-by-name":                    {},
			"list-hosted-zones-by-vpc":                     {"VPCId", "VPCRegion"},
			"list-query-logging-configs":                   {},
			"list-resource-record-sets":                    {"HostedZoneId"},
			"list-reusable-delegation-sets":                {},
			"list-tags-for-resource":                       {"ResourceId", "ResourceType"},
			"list-tags-for-resources":                      {"ResourceIds", "ResourceType"},
			"list-traffic-policies":                        {},
			"list-traffic-policy-instances":                {},
			"list-traffic-policy-instances-by-hosted-zone": {"HostedZoneId"},
			"list-traffic-policy-instances-by-policy":      {"TrafficPolicyId", "TrafficPolicyVersion"},
			"list-traffic-policy-versions":                 {"Id"},
			"list-vpc-association-authorizations":          {"HostedZoneId"},
			"test-dns-answer":                              {"HostedZoneId", "RecordName", "RecordType"},
			"update-health-check":                          {"HealthCheckId"},
			"update-hosted-zone-comment":                   {"Id"},
			"update-hosted-zone-features":                  {"HostedZoneId"},
			"update-traffic-policy-comment":                {"Comment", "Id", "Version"},
			"update-traffic-policy-instance":               {"Id", "TTL", "TrafficPolicyId", "TrafficPolicyVersion"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("route53", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
