package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/bedrockagentcore/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-create-memory-records", "batch-delete-memory-records", "batch-update-memory-records", "complete-resource-token-auth", "create-event", "delete-event", "delete-memory-record", "evaluate", "get-agent-card", "get-browser-session", "get-code-interpreter-session", "get-event", "get-memory-record", "get-resource-api-key", "get-resource-oauth2-token", "get-workload-access-token", "get-workload-access-token-for-jwt", "get-workload-access-token-for-user-id", "invoke-agent-runtime", "invoke-code-interpreter", "list-actors", "list-browser-sessions", "list-code-interpreter-sessions", "list-events", "list-memory-extraction-jobs", "list-memory-records", "list-sessions", "retrieve-memory-records", "save-browser-session-profile", "start-browser-session", "start-code-interpreter-session", "start-memory-extraction-job", "stop-browser-session", "stop-code-interpreter-session", "stop-runtime-session", "update-browser-stream"},
		OperationSet: map[string]bool{"batch-create-memory-records": true, "batch-delete-memory-records": true, "batch-update-memory-records": true, "complete-resource-token-auth": true, "create-event": true, "delete-event": true, "delete-memory-record": true, "evaluate": true, "get-agent-card": true, "get-browser-session": true, "get-code-interpreter-session": true, "get-event": true, "get-memory-record": true, "get-resource-api-key": true, "get-resource-oauth2-token": true, "get-workload-access-token": true, "get-workload-access-token-for-jwt": true, "get-workload-access-token-for-user-id": true, "invoke-agent-runtime": true, "invoke-code-interpreter": true, "list-actors": true, "list-browser-sessions": true, "list-code-interpreter-sessions": true, "list-events": true, "list-memory-extraction-jobs": true, "list-memory-records": true, "list-sessions": true, "retrieve-memory-records": true, "save-browser-session-profile": true, "start-browser-session": true, "start-code-interpreter-session": true, "start-memory-extraction-job": true, "stop-browser-session": true, "stop-code-interpreter-session": true, "stop-runtime-session": true, "update-browser-stream": true},
		OperationInputs: map[string][]string{
			"batch-create-memory-records":           {"ClientToken", "MemoryId", "Records"},
			"batch-delete-memory-records":           {"MemoryId", "Records"},
			"batch-update-memory-records":           {"MemoryId", "Records"},
			"complete-resource-token-auth":          {"SessionUri", "UserIdentifier"},
			"create-event":                          {"ActorId", "Branch", "ClientToken", "EventTimestamp", "MemoryId", "Metadata", "Payload", "SessionId"},
			"delete-event":                          {"ActorId", "EventId", "MemoryId", "SessionId"},
			"delete-memory-record":                  {"MemoryId", "MemoryRecordId"},
			"evaluate":                              {"EvaluationInput", "EvaluationTarget", "EvaluatorId"},
			"get-agent-card":                        {"AgentRuntimeArn", "Qualifier", "RuntimeSessionId"},
			"get-browser-session":                   {"BrowserIdentifier", "SessionId"},
			"get-code-interpreter-session":          {"CodeInterpreterIdentifier", "SessionId"},
			"get-event":                             {"ActorId", "EventId", "MemoryId", "SessionId"},
			"get-memory-record":                     {"MemoryId", "MemoryRecordId"},
			"get-resource-api-key":                  {"ResourceCredentialProviderName", "WorkloadIdentityToken"},
			"get-resource-oauth2-token":             {"CustomParameters", "CustomState", "ForceAuthentication", "Oauth2Flow", "ResourceCredentialProviderName", "ResourceOauth2ReturnUrl", "Scopes", "SessionUri", "WorkloadIdentityToken"},
			"get-workload-access-token":             {"WorkloadName"},
			"get-workload-access-token-for-jwt":     {"UserToken", "WorkloadName"},
			"get-workload-access-token-for-user-id": {"UserId", "WorkloadName"},
			"invoke-agent-runtime":                  {"Accept", "AccountId", "AgentRuntimeArn", "Baggage", "ContentType", "McpProtocolVersion", "McpSessionId", "Payload", "Qualifier", "RuntimeSessionId", "RuntimeUserId", "TraceId", "TraceParent", "TraceState"},
			"invoke-code-interpreter":               {"Arguments", "CodeInterpreterIdentifier", "Name", "SessionId", "TraceId", "TraceParent"},
			"list-actors":                           {"MaxResults", "MemoryId", "NextToken"},
			"list-browser-sessions":                 {"BrowserIdentifier", "MaxResults", "NextToken", "Status"},
			"list-code-interpreter-sessions":        {"CodeInterpreterIdentifier", "MaxResults", "NextToken", "Status"},
			"list-events":                           {"ActorId", "Filter", "IncludePayloads", "MaxResults", "MemoryId", "NextToken", "SessionId"},
			"list-memory-extraction-jobs":           {"Filter", "MaxResults", "MemoryId", "NextToken"},
			"list-memory-records":                   {"MaxResults", "MemoryId", "MemoryStrategyId", "Namespace", "NextToken"},
			"list-sessions":                         {"ActorId", "MaxResults", "MemoryId", "NextToken"},
			"retrieve-memory-records":               {"MaxResults", "MemoryId", "Namespace", "NextToken", "SearchCriteria"},
			"save-browser-session-profile":          {"BrowserIdentifier", "ClientToken", "ProfileIdentifier", "SessionId", "TraceId", "TraceParent"},
			"start-browser-session":                 {"BrowserIdentifier", "ClientToken", "Extensions", "Name", "ProfileConfiguration", "ProxyConfiguration", "SessionTimeoutSeconds", "TraceId", "TraceParent", "ViewPort"},
			"start-code-interpreter-session":        {"ClientToken", "CodeInterpreterIdentifier", "Name", "SessionTimeoutSeconds", "TraceId", "TraceParent"},
			"start-memory-extraction-job":           {"ClientToken", "ExtractionJob", "MemoryId"},
			"stop-browser-session":                  {"BrowserIdentifier", "ClientToken", "SessionId", "TraceId", "TraceParent"},
			"stop-code-interpreter-session":         {"ClientToken", "CodeInterpreterIdentifier", "SessionId", "TraceId", "TraceParent"},
			"stop-runtime-session":                  {"AgentRuntimeArn", "ClientToken", "Qualifier", "RuntimeSessionId"},
			"update-browser-stream":                 {"BrowserIdentifier", "ClientToken", "SessionId", "StreamUpdate"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-create-memory-records":           {"ClientToken": "*string", "MemoryId": "*string", "Records": "[]types.MemoryRecordCreateInput"},
			"batch-delete-memory-records":           {"MemoryId": "*string", "Records": "[]types.MemoryRecordDeleteInput"},
			"batch-update-memory-records":           {"MemoryId": "*string", "Records": "[]types.MemoryRecordUpdateInput"},
			"complete-resource-token-auth":          {"SessionUri": "*string", "UserIdentifier": "types.UserIdentifier"},
			"create-event":                          {"ActorId": "*string", "Branch": "*types.Branch", "ClientToken": "*string", "EventTimestamp": "*time.Time", "MemoryId": "*string", "Metadata": "map[string]types.MetadataValue", "Payload": "[]types.PayloadType", "SessionId": "*string"},
			"delete-event":                          {"ActorId": "*string", "EventId": "*string", "MemoryId": "*string", "SessionId": "*string"},
			"delete-memory-record":                  {"MemoryId": "*string", "MemoryRecordId": "*string"},
			"evaluate":                              {"EvaluationInput": "types.EvaluationInput", "EvaluationTarget": "types.EvaluationTarget", "EvaluatorId": "*string"},
			"get-agent-card":                        {"AgentRuntimeArn": "*string", "Qualifier": "*string", "RuntimeSessionId": "*string"},
			"get-browser-session":                   {"BrowserIdentifier": "*string", "SessionId": "*string"},
			"get-code-interpreter-session":          {"CodeInterpreterIdentifier": "*string", "SessionId": "*string"},
			"get-event":                             {"ActorId": "*string", "EventId": "*string", "MemoryId": "*string", "SessionId": "*string"},
			"get-memory-record":                     {"MemoryId": "*string", "MemoryRecordId": "*string"},
			"get-resource-api-key":                  {"ResourceCredentialProviderName": "*string", "WorkloadIdentityToken": "*string"},
			"get-resource-oauth2-token":             {"CustomParameters": "map[string]string", "CustomState": "*string", "ForceAuthentication": "*bool", "Oauth2Flow": "types.Oauth2FlowType", "ResourceCredentialProviderName": "*string", "ResourceOauth2ReturnUrl": "*string", "Scopes": "[]string", "SessionUri": "*string", "WorkloadIdentityToken": "*string"},
			"get-workload-access-token":             {"WorkloadName": "*string"},
			"get-workload-access-token-for-jwt":     {"UserToken": "*string", "WorkloadName": "*string"},
			"get-workload-access-token-for-user-id": {"UserId": "*string", "WorkloadName": "*string"},
			"invoke-agent-runtime":                  {"Accept": "*string", "AccountId": "*string", "AgentRuntimeArn": "*string", "Baggage": "*string", "ContentType": "*string", "McpProtocolVersion": "*string", "McpSessionId": "*string", "Payload": "[]byte", "Qualifier": "*string", "RuntimeSessionId": "*string", "RuntimeUserId": "*string", "TraceId": "*string", "TraceParent": "*string", "TraceState": "*string"},
			"invoke-code-interpreter":               {"Arguments": "*types.ToolArguments", "CodeInterpreterIdentifier": "*string", "Name": "types.ToolName", "SessionId": "*string", "TraceId": "*string", "TraceParent": "*string"},
			"list-actors":                           {"MaxResults": "*int32", "MemoryId": "*string", "NextToken": "*string"},
			"list-browser-sessions":                 {"BrowserIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.BrowserSessionStatus"},
			"list-code-interpreter-sessions":        {"CodeInterpreterIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.CodeInterpreterSessionStatus"},
			"list-events":                           {"ActorId": "*string", "Filter": "*types.FilterInput", "IncludePayloads": "*bool", "MaxResults": "*int32", "MemoryId": "*string", "NextToken": "*string", "SessionId": "*string"},
			"list-memory-extraction-jobs":           {"Filter": "*types.ExtractionJobFilterInput", "MaxResults": "*int32", "MemoryId": "*string", "NextToken": "*string"},
			"list-memory-records":                   {"MaxResults": "*int32", "MemoryId": "*string", "MemoryStrategyId": "*string", "Namespace": "*string", "NextToken": "*string"},
			"list-sessions":                         {"ActorId": "*string", "MaxResults": "*int32", "MemoryId": "*string", "NextToken": "*string"},
			"retrieve-memory-records":               {"MaxResults": "*int32", "MemoryId": "*string", "Namespace": "*string", "NextToken": "*string", "SearchCriteria": "*types.SearchCriteria"},
			"save-browser-session-profile":          {"BrowserIdentifier": "*string", "ClientToken": "*string", "ProfileIdentifier": "*string", "SessionId": "*string", "TraceId": "*string", "TraceParent": "*string"},
			"start-browser-session":                 {"BrowserIdentifier": "*string", "ClientToken": "*string", "Extensions": "[]types.BrowserExtension", "Name": "*string", "ProfileConfiguration": "*types.BrowserProfileConfiguration", "ProxyConfiguration": "*types.ProxyConfiguration", "SessionTimeoutSeconds": "*int32", "TraceId": "*string", "TraceParent": "*string", "ViewPort": "*types.ViewPort"},
			"start-code-interpreter-session":        {"ClientToken": "*string", "CodeInterpreterIdentifier": "*string", "Name": "*string", "SessionTimeoutSeconds": "*int32", "TraceId": "*string", "TraceParent": "*string"},
			"start-memory-extraction-job":           {"ClientToken": "*string", "ExtractionJob": "*types.ExtractionJob", "MemoryId": "*string"},
			"stop-browser-session":                  {"BrowserIdentifier": "*string", "ClientToken": "*string", "SessionId": "*string", "TraceId": "*string", "TraceParent": "*string"},
			"stop-code-interpreter-session":         {"ClientToken": "*string", "CodeInterpreterIdentifier": "*string", "SessionId": "*string", "TraceId": "*string", "TraceParent": "*string"},
			"stop-runtime-session":                  {"AgentRuntimeArn": "*string", "ClientToken": "*string", "Qualifier": "*string", "RuntimeSessionId": "*string"},
			"update-browser-stream":                 {"BrowserIdentifier": "*string", "ClientToken": "*string", "SessionId": "*string", "StreamUpdate": "types.StreamUpdate"},
		},
		OperationInputRequired: map[string][]string{
			"batch-create-memory-records":           {"MemoryId", "Records"},
			"batch-delete-memory-records":           {"MemoryId", "Records"},
			"batch-update-memory-records":           {"MemoryId", "Records"},
			"complete-resource-token-auth":          {"SessionUri", "UserIdentifier"},
			"create-event":                          {"ActorId", "EventTimestamp", "MemoryId", "Payload"},
			"delete-event":                          {"ActorId", "EventId", "MemoryId", "SessionId"},
			"delete-memory-record":                  {"MemoryId", "MemoryRecordId"},
			"evaluate":                              {"EvaluationInput", "EvaluatorId"},
			"get-agent-card":                        {"AgentRuntimeArn"},
			"get-browser-session":                   {"BrowserIdentifier", "SessionId"},
			"get-code-interpreter-session":          {"CodeInterpreterIdentifier", "SessionId"},
			"get-event":                             {"ActorId", "EventId", "MemoryId", "SessionId"},
			"get-memory-record":                     {"MemoryId", "MemoryRecordId"},
			"get-resource-api-key":                  {"ResourceCredentialProviderName", "WorkloadIdentityToken"},
			"get-resource-oauth2-token":             {"Oauth2Flow", "ResourceCredentialProviderName", "Scopes", "WorkloadIdentityToken"},
			"get-workload-access-token":             {"WorkloadName"},
			"get-workload-access-token-for-jwt":     {"UserToken", "WorkloadName"},
			"get-workload-access-token-for-user-id": {"UserId", "WorkloadName"},
			"invoke-agent-runtime":                  {"AgentRuntimeArn", "Payload"},
			"invoke-code-interpreter":               {"CodeInterpreterIdentifier", "Name"},
			"list-actors":                           {"MemoryId"},
			"list-browser-sessions":                 {"BrowserIdentifier"},
			"list-code-interpreter-sessions":        {"CodeInterpreterIdentifier"},
			"list-events":                           {"ActorId", "MemoryId", "SessionId"},
			"list-memory-extraction-jobs":           {"MemoryId"},
			"list-memory-records":                   {"MemoryId", "Namespace"},
			"list-sessions":                         {"ActorId", "MemoryId"},
			"retrieve-memory-records":               {"MemoryId", "Namespace", "SearchCriteria"},
			"save-browser-session-profile":          {"BrowserIdentifier", "ProfileIdentifier", "SessionId"},
			"start-browser-session":                 {"BrowserIdentifier"},
			"start-code-interpreter-session":        {"CodeInterpreterIdentifier"},
			"start-memory-extraction-job":           {"ExtractionJob", "MemoryId"},
			"stop-browser-session":                  {"BrowserIdentifier", "SessionId"},
			"stop-code-interpreter-session":         {"CodeInterpreterIdentifier", "SessionId"},
			"stop-runtime-session":                  {"AgentRuntimeArn", "RuntimeSessionId"},
			"update-browser-stream":                 {"BrowserIdentifier", "SessionId", "StreamUpdate"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("bedrockagentcore", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
