package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/docdb/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-source-identifier-to-subscription", "add-tags-to-resource", "apply-pending-maintenance-action", "copy-db-cluster-parameter-group", "copy-db-cluster-snapshot", "create-db-cluster", "create-db-cluster-parameter-group", "create-db-cluster-snapshot", "create-db-instance", "create-db-subnet-group", "create-event-subscription", "create-global-cluster", "delete-db-cluster", "delete-db-cluster-parameter-group", "delete-db-cluster-snapshot", "delete-db-instance", "delete-db-subnet-group", "delete-event-subscription", "delete-global-cluster", "describe-certificates", "describe-db-cluster-parameter-groups", "describe-db-cluster-parameters", "describe-db-cluster-snapshot-attributes", "describe-db-cluster-snapshots", "describe-db-clusters", "describe-db-engine-versions", "describe-db-instances", "describe-db-subnet-groups", "describe-engine-default-cluster-parameters", "describe-event-categories", "describe-event-subscriptions", "describe-events", "describe-global-clusters", "describe-orderable-db-instance-options", "describe-pending-maintenance-actions", "failover-db-cluster", "failover-global-cluster", "list-tags-for-resource", "modify-db-cluster", "modify-db-cluster-parameter-group", "modify-db-cluster-snapshot-attribute", "modify-db-instance", "modify-db-subnet-group", "modify-event-subscription", "modify-global-cluster", "reboot-db-instance", "remove-from-global-cluster", "remove-source-identifier-from-subscription", "remove-tags-from-resource", "reset-db-cluster-parameter-group", "restore-db-cluster-from-snapshot", "restore-db-cluster-to-point-in-time", "start-db-cluster", "stop-db-cluster", "switchover-global-cluster"},
		OperationSet: map[string]bool{"add-source-identifier-to-subscription": true, "add-tags-to-resource": true, "apply-pending-maintenance-action": true, "copy-db-cluster-parameter-group": true, "copy-db-cluster-snapshot": true, "create-db-cluster": true, "create-db-cluster-parameter-group": true, "create-db-cluster-snapshot": true, "create-db-instance": true, "create-db-subnet-group": true, "create-event-subscription": true, "create-global-cluster": true, "delete-db-cluster": true, "delete-db-cluster-parameter-group": true, "delete-db-cluster-snapshot": true, "delete-db-instance": true, "delete-db-subnet-group": true, "delete-event-subscription": true, "delete-global-cluster": true, "describe-certificates": true, "describe-db-cluster-parameter-groups": true, "describe-db-cluster-parameters": true, "describe-db-cluster-snapshot-attributes": true, "describe-db-cluster-snapshots": true, "describe-db-clusters": true, "describe-db-engine-versions": true, "describe-db-instances": true, "describe-db-subnet-groups": true, "describe-engine-default-cluster-parameters": true, "describe-event-categories": true, "describe-event-subscriptions": true, "describe-events": true, "describe-global-clusters": true, "describe-orderable-db-instance-options": true, "describe-pending-maintenance-actions": true, "failover-db-cluster": true, "failover-global-cluster": true, "list-tags-for-resource": true, "modify-db-cluster": true, "modify-db-cluster-parameter-group": true, "modify-db-cluster-snapshot-attribute": true, "modify-db-instance": true, "modify-db-subnet-group": true, "modify-event-subscription": true, "modify-global-cluster": true, "reboot-db-instance": true, "remove-from-global-cluster": true, "remove-source-identifier-from-subscription": true, "remove-tags-from-resource": true, "reset-db-cluster-parameter-group": true, "restore-db-cluster-from-snapshot": true, "restore-db-cluster-to-point-in-time": true, "start-db-cluster": true, "stop-db-cluster": true, "switchover-global-cluster": true},
		OperationInputs: map[string][]string{
			"add-source-identifier-to-subscription":      {"SourceIdentifier", "SubscriptionName"},
			"add-tags-to-resource":                       {"ResourceName", "Tags"},
			"apply-pending-maintenance-action":           {"ApplyAction", "OptInType", "ResourceIdentifier"},
			"copy-db-cluster-parameter-group":            {"SourceDBClusterParameterGroupIdentifier", "Tags", "TargetDBClusterParameterGroupDescription", "TargetDBClusterParameterGroupIdentifier"},
			"copy-db-cluster-snapshot":                   {"CopyTags", "KmsKeyId", "PreSignedUrl", "SourceDBClusterSnapshotIdentifier", "SourceRegion", "Tags", "TargetDBClusterSnapshotIdentifier", "destinationRegion"},
			"create-db-cluster":                          {"AvailabilityZones", "BackupRetentionPeriod", "DBClusterIdentifier", "DBClusterParameterGroupName", "DBSubnetGroupName", "DeletionProtection", "EnableCloudwatchLogsExports", "Engine", "EngineVersion", "GlobalClusterIdentifier", "KmsKeyId", "ManageMasterUserPassword", "MasterUserPassword", "MasterUserSecretKmsKeyId", "MasterUsername", "NetworkType", "Port", "PreSignedUrl", "PreferredBackupWindow", "PreferredMaintenanceWindow", "ServerlessV2ScalingConfiguration", "SourceRegion", "StorageEncrypted", "StorageType", "Tags", "VpcSecurityGroupIds", "destinationRegion"},
			"create-db-cluster-parameter-group":          {"DBClusterParameterGroupName", "DBParameterGroupFamily", "Description", "Tags"},
			"create-db-cluster-snapshot":                 {"DBClusterIdentifier", "DBClusterSnapshotIdentifier", "Tags"},
			"create-db-instance":                         {"AutoMinorVersionUpgrade", "AvailabilityZone", "CACertificateIdentifier", "CopyTagsToSnapshot", "DBClusterIdentifier", "DBInstanceClass", "DBInstanceIdentifier", "EnablePerformanceInsights", "Engine", "PerformanceInsightsKMSKeyId", "PreferredMaintenanceWindow", "PromotionTier", "Tags"},
			"create-db-subnet-group":                     {"DBSubnetGroupDescription", "DBSubnetGroupName", "SubnetIds", "Tags"},
			"create-event-subscription":                  {"Enabled", "EventCategories", "SnsTopicArn", "SourceIds", "SourceType", "SubscriptionName", "Tags"},
			"create-global-cluster":                      {"DatabaseName", "DeletionProtection", "Engine", "EngineVersion", "GlobalClusterIdentifier", "SourceDBClusterIdentifier", "StorageEncrypted"},
			"delete-db-cluster":                          {"DBClusterIdentifier", "FinalDBSnapshotIdentifier", "SkipFinalSnapshot"},
			"delete-db-cluster-parameter-group":          {"DBClusterParameterGroupName"},
			"delete-db-cluster-snapshot":                 {"DBClusterSnapshotIdentifier"},
			"delete-db-instance":                         {"DBInstanceIdentifier"},
			"delete-db-subnet-group":                     {"DBSubnetGroupName"},
			"delete-event-subscription":                  {"SubscriptionName"},
			"delete-global-cluster":                      {"GlobalClusterIdentifier"},
			"describe-certificates":                      {"CertificateIdentifier", "Filters", "Marker", "MaxRecords"},
			"describe-db-cluster-parameter-groups":       {"DBClusterParameterGroupName", "Filters", "Marker", "MaxRecords"},
			"describe-db-cluster-parameters":             {"DBClusterParameterGroupName", "Filters", "Marker", "MaxRecords", "Source"},
			"describe-db-cluster-snapshot-attributes":    {"DBClusterSnapshotIdentifier"},
			"describe-db-cluster-snapshots":              {"DBClusterIdentifier", "DBClusterSnapshotIdentifier", "Filters", "IncludePublic", "IncludeShared", "Marker", "MaxRecords", "SnapshotType"},
			"describe-db-clusters":                       {"DBClusterIdentifier", "Filters", "Marker", "MaxRecords"},
			"describe-db-engine-versions":                {"DBParameterGroupFamily", "DefaultOnly", "Engine", "EngineVersion", "Filters", "ListSupportedCharacterSets", "ListSupportedTimezones", "Marker", "MaxRecords"},
			"describe-db-instances":                      {"DBInstanceIdentifier", "Filters", "Marker", "MaxRecords"},
			"describe-db-subnet-groups":                  {"DBSubnetGroupName", "Filters", "Marker", "MaxRecords"},
			"describe-engine-default-cluster-parameters": {"DBParameterGroupFamily", "Filters", "Marker", "MaxRecords"},
			"describe-event-categories":                  {"Filters", "SourceType"},
			"describe-event-subscriptions":               {"Filters", "Marker", "MaxRecords", "SubscriptionName"},
			"describe-events":                            {"Duration", "EndTime", "EventCategories", "Filters", "Marker", "MaxRecords", "SourceIdentifier", "SourceType", "StartTime"},
			"describe-global-clusters":                   {"Filters", "GlobalClusterIdentifier", "Marker", "MaxRecords"},
			"describe-orderable-db-instance-options":     {"DBInstanceClass", "Engine", "EngineVersion", "Filters", "LicenseModel", "Marker", "MaxRecords", "Vpc"},
			"describe-pending-maintenance-actions":       {"Filters", "Marker", "MaxRecords", "ResourceIdentifier"},
			"failover-db-cluster":                        {"DBClusterIdentifier", "TargetDBInstanceIdentifier"},
			"failover-global-cluster":                    {"AllowDataLoss", "GlobalClusterIdentifier", "Switchover", "TargetDbClusterIdentifier"},
			"list-tags-for-resource":                     {"Filters", "ResourceName"},
			"modify-db-cluster":                          {"AllowMajorVersionUpgrade", "ApplyImmediately", "BackupRetentionPeriod", "CloudwatchLogsExportConfiguration", "DBClusterIdentifier", "DBClusterParameterGroupName", "DeletionProtection", "EngineVersion", "ManageMasterUserPassword", "MasterUserPassword", "MasterUserSecretKmsKeyId", "NetworkType", "NewDBClusterIdentifier", "Port", "PreferredBackupWindow", "PreferredMaintenanceWindow", "RotateMasterUserPassword", "ServerlessV2ScalingConfiguration", "StorageType", "VpcSecurityGroupIds"},
			"modify-db-cluster-parameter-group":          {"DBClusterParameterGroupName", "Parameters"},
			"modify-db-cluster-snapshot-attribute":       {"AttributeName", "DBClusterSnapshotIdentifier", "ValuesToAdd", "ValuesToRemove"},
			"modify-db-instance":                         {"ApplyImmediately", "AutoMinorVersionUpgrade", "CACertificateIdentifier", "CertificateRotationRestart", "CopyTagsToSnapshot", "DBInstanceClass", "DBInstanceIdentifier", "EnablePerformanceInsights", "NewDBInstanceIdentifier", "PerformanceInsightsKMSKeyId", "PreferredMaintenanceWindow", "PromotionTier"},
			"modify-db-subnet-group":                     {"DBSubnetGroupDescription", "DBSubnetGroupName", "SubnetIds"},
			"modify-event-subscription":                  {"Enabled", "EventCategories", "SnsTopicArn", "SourceType", "SubscriptionName"},
			"modify-global-cluster":                      {"DeletionProtection", "GlobalClusterIdentifier", "NewGlobalClusterIdentifier"},
			"reboot-db-instance":                         {"DBInstanceIdentifier", "ForceFailover"},
			"remove-from-global-cluster":                 {"DbClusterIdentifier", "GlobalClusterIdentifier"},
			"remove-source-identifier-from-subscription": {"SourceIdentifier", "SubscriptionName"},
			"remove-tags-from-resource":                  {"ResourceName", "TagKeys"},
			"reset-db-cluster-parameter-group":           {"DBClusterParameterGroupName", "Parameters", "ResetAllParameters"},
			"restore-db-cluster-from-snapshot":           {"AvailabilityZones", "DBClusterIdentifier", "DBClusterParameterGroupName", "DBSubnetGroupName", "DeletionProtection", "EnableCloudwatchLogsExports", "Engine", "EngineVersion", "KmsKeyId", "NetworkType", "Port", "ServerlessV2ScalingConfiguration", "SnapshotIdentifier", "StorageType", "Tags", "VpcSecurityGroupIds"},
			"restore-db-cluster-to-point-in-time":        {"DBClusterIdentifier", "DBSubnetGroupName", "DeletionProtection", "EnableCloudwatchLogsExports", "KmsKeyId", "NetworkType", "Port", "RestoreToTime", "RestoreType", "ServerlessV2ScalingConfiguration", "SourceDBClusterIdentifier", "StorageType", "Tags", "UseLatestRestorableTime", "VpcSecurityGroupIds"},
			"start-db-cluster":                           {"DBClusterIdentifier"},
			"stop-db-cluster":                            {"DBClusterIdentifier"},
			"switchover-global-cluster":                  {"GlobalClusterIdentifier", "TargetDbClusterIdentifier"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-source-identifier-to-subscription":      {"SourceIdentifier": "*string", "SubscriptionName": "*string"},
			"add-tags-to-resource":                       {"ResourceName": "*string", "Tags": "[]types.Tag"},
			"apply-pending-maintenance-action":           {"ApplyAction": "*string", "OptInType": "*string", "ResourceIdentifier": "*string"},
			"copy-db-cluster-parameter-group":            {"SourceDBClusterParameterGroupIdentifier": "*string", "Tags": "[]types.Tag", "TargetDBClusterParameterGroupDescription": "*string", "TargetDBClusterParameterGroupIdentifier": "*string"},
			"copy-db-cluster-snapshot":                   {"CopyTags": "*bool", "KmsKeyId": "*string", "PreSignedUrl": "*string", "SourceDBClusterSnapshotIdentifier": "*string", "SourceRegion": "*string", "Tags": "[]types.Tag", "TargetDBClusterSnapshotIdentifier": "*string", "destinationRegion": "*string"},
			"create-db-cluster":                          {"AvailabilityZones": "[]string", "BackupRetentionPeriod": "*int32", "DBClusterIdentifier": "*string", "DBClusterParameterGroupName": "*string", "DBSubnetGroupName": "*string", "DeletionProtection": "*bool", "EnableCloudwatchLogsExports": "[]string", "Engine": "*string", "EngineVersion": "*string", "GlobalClusterIdentifier": "*string", "KmsKeyId": "*string", "ManageMasterUserPassword": "*bool", "MasterUserPassword": "*string", "MasterUserSecretKmsKeyId": "*string", "MasterUsername": "*string", "NetworkType": "*string", "Port": "*int32", "PreSignedUrl": "*string", "PreferredBackupWindow": "*string", "PreferredMaintenanceWindow": "*string", "ServerlessV2ScalingConfiguration": "*types.ServerlessV2ScalingConfiguration", "SourceRegion": "*string", "StorageEncrypted": "*bool", "StorageType": "*string", "Tags": "[]types.Tag", "VpcSecurityGroupIds": "[]string", "destinationRegion": "*string"},
			"create-db-cluster-parameter-group":          {"DBClusterParameterGroupName": "*string", "DBParameterGroupFamily": "*string", "Description": "*string", "Tags": "[]types.Tag"},
			"create-db-cluster-snapshot":                 {"DBClusterIdentifier": "*string", "DBClusterSnapshotIdentifier": "*string", "Tags": "[]types.Tag"},
			"create-db-instance":                         {"AutoMinorVersionUpgrade": "*bool", "AvailabilityZone": "*string", "CACertificateIdentifier": "*string", "CopyTagsToSnapshot": "*bool", "DBClusterIdentifier": "*string", "DBInstanceClass": "*string", "DBInstanceIdentifier": "*string", "EnablePerformanceInsights": "*bool", "Engine": "*string", "PerformanceInsightsKMSKeyId": "*string", "PreferredMaintenanceWindow": "*string", "PromotionTier": "*int32", "Tags": "[]types.Tag"},
			"create-db-subnet-group":                     {"DBSubnetGroupDescription": "*string", "DBSubnetGroupName": "*string", "SubnetIds": "[]string", "Tags": "[]types.Tag"},
			"create-event-subscription":                  {"Enabled": "*bool", "EventCategories": "[]string", "SnsTopicArn": "*string", "SourceIds": "[]string", "SourceType": "*string", "SubscriptionName": "*string", "Tags": "[]types.Tag"},
			"create-global-cluster":                      {"DatabaseName": "*string", "DeletionProtection": "*bool", "Engine": "*string", "EngineVersion": "*string", "GlobalClusterIdentifier": "*string", "SourceDBClusterIdentifier": "*string", "StorageEncrypted": "*bool"},
			"delete-db-cluster":                          {"DBClusterIdentifier": "*string", "FinalDBSnapshotIdentifier": "*string", "SkipFinalSnapshot": "*bool"},
			"delete-db-cluster-parameter-group":          {"DBClusterParameterGroupName": "*string"},
			"delete-db-cluster-snapshot":                 {"DBClusterSnapshotIdentifier": "*string"},
			"delete-db-instance":                         {"DBInstanceIdentifier": "*string"},
			"delete-db-subnet-group":                     {"DBSubnetGroupName": "*string"},
			"delete-event-subscription":                  {"SubscriptionName": "*string"},
			"delete-global-cluster":                      {"GlobalClusterIdentifier": "*string"},
			"describe-certificates":                      {"CertificateIdentifier": "*string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-db-cluster-parameter-groups":       {"DBClusterParameterGroupName": "*string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-db-cluster-parameters":             {"DBClusterParameterGroupName": "*string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "Source": "*string"},
			"describe-db-cluster-snapshot-attributes":    {"DBClusterSnapshotIdentifier": "*string"},
			"describe-db-cluster-snapshots":              {"DBClusterIdentifier": "*string", "DBClusterSnapshotIdentifier": "*string", "Filters": "[]types.Filter", "IncludePublic": "*bool", "IncludeShared": "*bool", "Marker": "*string", "MaxRecords": "*int32", "SnapshotType": "*string"},
			"describe-db-clusters":                       {"DBClusterIdentifier": "*string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-db-engine-versions":                {"DBParameterGroupFamily": "*string", "DefaultOnly": "*bool", "Engine": "*string", "EngineVersion": "*string", "Filters": "[]types.Filter", "ListSupportedCharacterSets": "*bool", "ListSupportedTimezones": "*bool", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-db-instances":                      {"DBInstanceIdentifier": "*string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-db-subnet-groups":                  {"DBSubnetGroupName": "*string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-engine-default-cluster-parameters": {"DBParameterGroupFamily": "*string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-event-categories":                  {"Filters": "[]types.Filter", "SourceType": "*string"},
			"describe-event-subscriptions":               {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "SubscriptionName": "*string"},
			"describe-events":                            {"Duration": "*int32", "EndTime": "*time.Time", "EventCategories": "[]string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "SourceIdentifier": "*string", "SourceType": "types.SourceType", "StartTime": "*time.Time"},
			"describe-global-clusters":                   {"Filters": "[]types.Filter", "GlobalClusterIdentifier": "*string", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-orderable-db-instance-options":     {"DBInstanceClass": "*string", "Engine": "*string", "EngineVersion": "*string", "Filters": "[]types.Filter", "LicenseModel": "*string", "Marker": "*string", "MaxRecords": "*int32", "Vpc": "*bool"},
			"describe-pending-maintenance-actions":       {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "ResourceIdentifier": "*string"},
			"failover-db-cluster":                        {"DBClusterIdentifier": "*string", "TargetDBInstanceIdentifier": "*string"},
			"failover-global-cluster":                    {"AllowDataLoss": "*bool", "GlobalClusterIdentifier": "*string", "Switchover": "*bool", "TargetDbClusterIdentifier": "*string"},
			"list-tags-for-resource":                     {"Filters": "[]types.Filter", "ResourceName": "*string"},
			"modify-db-cluster":                          {"AllowMajorVersionUpgrade": "*bool", "ApplyImmediately": "*bool", "BackupRetentionPeriod": "*int32", "CloudwatchLogsExportConfiguration": "*types.CloudwatchLogsExportConfiguration", "DBClusterIdentifier": "*string", "DBClusterParameterGroupName": "*string", "DeletionProtection": "*bool", "EngineVersion": "*string", "ManageMasterUserPassword": "*bool", "MasterUserPassword": "*string", "MasterUserSecretKmsKeyId": "*string", "NetworkType": "*string", "NewDBClusterIdentifier": "*string", "Port": "*int32", "PreferredBackupWindow": "*string", "PreferredMaintenanceWindow": "*string", "RotateMasterUserPassword": "*bool", "ServerlessV2ScalingConfiguration": "*types.ServerlessV2ScalingConfiguration", "StorageType": "*string", "VpcSecurityGroupIds": "[]string"},
			"modify-db-cluster-parameter-group":          {"DBClusterParameterGroupName": "*string", "Parameters": "[]types.Parameter"},
			"modify-db-cluster-snapshot-attribute":       {"AttributeName": "*string", "DBClusterSnapshotIdentifier": "*string", "ValuesToAdd": "[]string", "ValuesToRemove": "[]string"},
			"modify-db-instance":                         {"ApplyImmediately": "*bool", "AutoMinorVersionUpgrade": "*bool", "CACertificateIdentifier": "*string", "CertificateRotationRestart": "*bool", "CopyTagsToSnapshot": "*bool", "DBInstanceClass": "*string", "DBInstanceIdentifier": "*string", "EnablePerformanceInsights": "*bool", "NewDBInstanceIdentifier": "*string", "PerformanceInsightsKMSKeyId": "*string", "PreferredMaintenanceWindow": "*string", "PromotionTier": "*int32"},
			"modify-db-subnet-group":                     {"DBSubnetGroupDescription": "*string", "DBSubnetGroupName": "*string", "SubnetIds": "[]string"},
			"modify-event-subscription":                  {"Enabled": "*bool", "EventCategories": "[]string", "SnsTopicArn": "*string", "SourceType": "*string", "SubscriptionName": "*string"},
			"modify-global-cluster":                      {"DeletionProtection": "*bool", "GlobalClusterIdentifier": "*string", "NewGlobalClusterIdentifier": "*string"},
			"reboot-db-instance":                         {"DBInstanceIdentifier": "*string", "ForceFailover": "*bool"},
			"remove-from-global-cluster":                 {"DbClusterIdentifier": "*string", "GlobalClusterIdentifier": "*string"},
			"remove-source-identifier-from-subscription": {"SourceIdentifier": "*string", "SubscriptionName": "*string"},
			"remove-tags-from-resource":                  {"ResourceName": "*string", "TagKeys": "[]string"},
			"reset-db-cluster-parameter-group":           {"DBClusterParameterGroupName": "*string", "Parameters": "[]types.Parameter", "ResetAllParameters": "*bool"},
			"restore-db-cluster-from-snapshot":           {"AvailabilityZones": "[]string", "DBClusterIdentifier": "*string", "DBClusterParameterGroupName": "*string", "DBSubnetGroupName": "*string", "DeletionProtection": "*bool", "EnableCloudwatchLogsExports": "[]string", "Engine": "*string", "EngineVersion": "*string", "KmsKeyId": "*string", "NetworkType": "*string", "Port": "*int32", "ServerlessV2ScalingConfiguration": "*types.ServerlessV2ScalingConfiguration", "SnapshotIdentifier": "*string", "StorageType": "*string", "Tags": "[]types.Tag", "VpcSecurityGroupIds": "[]string"},
			"restore-db-cluster-to-point-in-time":        {"DBClusterIdentifier": "*string", "DBSubnetGroupName": "*string", "DeletionProtection": "*bool", "EnableCloudwatchLogsExports": "[]string", "KmsKeyId": "*string", "NetworkType": "*string", "Port": "*int32", "RestoreToTime": "*time.Time", "RestoreType": "*string", "ServerlessV2ScalingConfiguration": "*types.ServerlessV2ScalingConfiguration", "SourceDBClusterIdentifier": "*string", "StorageType": "*string", "Tags": "[]types.Tag", "UseLatestRestorableTime": "*bool", "VpcSecurityGroupIds": "[]string"},
			"start-db-cluster":                           {"DBClusterIdentifier": "*string"},
			"stop-db-cluster":                            {"DBClusterIdentifier": "*string"},
			"switchover-global-cluster":                  {"GlobalClusterIdentifier": "*string", "TargetDbClusterIdentifier": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"add-source-identifier-to-subscription":      {"SourceIdentifier", "SubscriptionName"},
			"add-tags-to-resource":                       {"ResourceName", "Tags"},
			"apply-pending-maintenance-action":           {"ApplyAction", "OptInType", "ResourceIdentifier"},
			"copy-db-cluster-parameter-group":            {"SourceDBClusterParameterGroupIdentifier", "TargetDBClusterParameterGroupDescription", "TargetDBClusterParameterGroupIdentifier"},
			"copy-db-cluster-snapshot":                   {"SourceDBClusterSnapshotIdentifier", "TargetDBClusterSnapshotIdentifier"},
			"create-db-cluster":                          {"DBClusterIdentifier", "Engine"},
			"create-db-cluster-parameter-group":          {"DBClusterParameterGroupName", "DBParameterGroupFamily", "Description"},
			"create-db-cluster-snapshot":                 {"DBClusterIdentifier", "DBClusterSnapshotIdentifier"},
			"create-db-instance":                         {"DBClusterIdentifier", "DBInstanceClass", "DBInstanceIdentifier", "Engine"},
			"create-db-subnet-group":                     {"DBSubnetGroupDescription", "DBSubnetGroupName", "SubnetIds"},
			"create-event-subscription":                  {"SnsTopicArn", "SubscriptionName"},
			"create-global-cluster":                      {"GlobalClusterIdentifier"},
			"delete-db-cluster":                          {"DBClusterIdentifier"},
			"delete-db-cluster-parameter-group":          {"DBClusterParameterGroupName"},
			"delete-db-cluster-snapshot":                 {"DBClusterSnapshotIdentifier"},
			"delete-db-instance":                         {"DBInstanceIdentifier"},
			"delete-db-subnet-group":                     {"DBSubnetGroupName"},
			"delete-event-subscription":                  {"SubscriptionName"},
			"delete-global-cluster":                      {"GlobalClusterIdentifier"},
			"describe-certificates":                      {},
			"describe-db-cluster-parameter-groups":       {},
			"describe-db-cluster-parameters":             {"DBClusterParameterGroupName"},
			"describe-db-cluster-snapshot-attributes":    {"DBClusterSnapshotIdentifier"},
			"describe-db-cluster-snapshots":              {},
			"describe-db-clusters":                       {},
			"describe-db-engine-versions":                {},
			"describe-db-instances":                      {},
			"describe-db-subnet-groups":                  {},
			"describe-engine-default-cluster-parameters": {"DBParameterGroupFamily"},
			"describe-event-categories":                  {},
			"describe-event-subscriptions":               {},
			"describe-events":                            {},
			"describe-global-clusters":                   {},
			"describe-orderable-db-instance-options":     {"Engine"},
			"describe-pending-maintenance-actions":       {},
			"failover-db-cluster":                        {},
			"failover-global-cluster":                    {"GlobalClusterIdentifier", "TargetDbClusterIdentifier"},
			"list-tags-for-resource":                     {"ResourceName"},
			"modify-db-cluster":                          {"DBClusterIdentifier"},
			"modify-db-cluster-parameter-group":          {"DBClusterParameterGroupName", "Parameters"},
			"modify-db-cluster-snapshot-attribute":       {"AttributeName", "DBClusterSnapshotIdentifier"},
			"modify-db-instance":                         {"DBInstanceIdentifier"},
			"modify-db-subnet-group":                     {"DBSubnetGroupName", "SubnetIds"},
			"modify-event-subscription":                  {"SubscriptionName"},
			"modify-global-cluster":                      {"GlobalClusterIdentifier"},
			"reboot-db-instance":                         {"DBInstanceIdentifier"},
			"remove-from-global-cluster":                 {"DbClusterIdentifier", "GlobalClusterIdentifier"},
			"remove-source-identifier-from-subscription": {"SourceIdentifier", "SubscriptionName"},
			"remove-tags-from-resource":                  {"ResourceName", "TagKeys"},
			"reset-db-cluster-parameter-group":           {"DBClusterParameterGroupName"},
			"restore-db-cluster-from-snapshot":           {"DBClusterIdentifier", "Engine", "SnapshotIdentifier"},
			"restore-db-cluster-to-point-in-time":        {"DBClusterIdentifier", "SourceDBClusterIdentifier"},
			"start-db-cluster":                           {"DBClusterIdentifier"},
			"stop-db-cluster":                            {"DBClusterIdentifier"},
			"switchover-global-cluster":                  {"GlobalClusterIdentifier", "TargetDbClusterIdentifier"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("docdb", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
