package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/connectcases/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-get-case-rule", "batch-get-field", "batch-put-field-options", "create-case", "create-case-rule", "create-domain", "create-field", "create-layout", "create-related-item", "create-template", "delete-case", "delete-case-rule", "delete-domain", "delete-field", "delete-layout", "delete-related-item", "delete-template", "get-case", "get-case-audit-events", "get-case-event-configuration", "get-domain", "get-layout", "get-template", "list-case-rules", "list-cases-for-contact", "list-domains", "list-field-options", "list-fields", "list-layouts", "list-tags-for-resource", "list-templates", "put-case-event-configuration", "search-all-related-items", "search-cases", "search-related-items", "tag-resource", "untag-resource", "update-case", "update-case-rule", "update-field", "update-layout", "update-template"},
		OperationSet: map[string]bool{"batch-get-case-rule": true, "batch-get-field": true, "batch-put-field-options": true, "create-case": true, "create-case-rule": true, "create-domain": true, "create-field": true, "create-layout": true, "create-related-item": true, "create-template": true, "delete-case": true, "delete-case-rule": true, "delete-domain": true, "delete-field": true, "delete-layout": true, "delete-related-item": true, "delete-template": true, "get-case": true, "get-case-audit-events": true, "get-case-event-configuration": true, "get-domain": true, "get-layout": true, "get-template": true, "list-case-rules": true, "list-cases-for-contact": true, "list-domains": true, "list-field-options": true, "list-fields": true, "list-layouts": true, "list-tags-for-resource": true, "list-templates": true, "put-case-event-configuration": true, "search-all-related-items": true, "search-cases": true, "search-related-items": true, "tag-resource": true, "untag-resource": true, "update-case": true, "update-case-rule": true, "update-field": true, "update-layout": true, "update-template": true},
		OperationInputs: map[string][]string{
			"batch-get-case-rule":          {"CaseRules", "DomainId"},
			"batch-get-field":              {"DomainId", "Fields"},
			"batch-put-field-options":      {"DomainId", "FieldId", "Options"},
			"create-case":                  {"ClientToken", "DomainId", "Fields", "PerformedBy", "Tags", "TemplateId"},
			"create-case-rule":             {"Description", "DomainId", "Name", "Rule"},
			"create-domain":                {"Name"},
			"create-field":                 {"Attributes", "Description", "DomainId", "Name", "Type"},
			"create-layout":                {"Content", "DomainId", "Name"},
			"create-related-item":          {"CaseId", "Content", "DomainId", "PerformedBy", "Type"},
			"create-template":              {"Description", "DomainId", "LayoutConfiguration", "Name", "RequiredFields", "Rules", "Status", "TagPropagationConfigurations"},
			"delete-case":                  {"CaseId", "DomainId"},
			"delete-case-rule":             {"CaseRuleId", "DomainId"},
			"delete-domain":                {"DomainId"},
			"delete-field":                 {"DomainId", "FieldId"},
			"delete-layout":                {"DomainId", "LayoutId"},
			"delete-related-item":          {"CaseId", "DomainId", "RelatedItemId"},
			"delete-template":              {"DomainId", "TemplateId"},
			"get-case":                     {"CaseId", "DomainId", "Fields", "NextToken"},
			"get-case-audit-events":        {"CaseId", "DomainId", "MaxResults", "NextToken"},
			"get-case-event-configuration": {"DomainId"},
			"get-domain":                   {"DomainId"},
			"get-layout":                   {"DomainId", "LayoutId"},
			"get-template":                 {"DomainId", "TemplateId"},
			"list-case-rules":              {"DomainId", "MaxResults", "NextToken"},
			"list-cases-for-contact":       {"ContactArn", "DomainId", "MaxResults", "NextToken"},
			"list-domains":                 {"MaxResults", "NextToken"},
			"list-field-options":           {"DomainId", "FieldId", "MaxResults", "NextToken", "Values"},
			"list-fields":                  {"DomainId", "MaxResults", "NextToken"},
			"list-layouts":                 {"DomainId", "MaxResults", "NextToken"},
			"list-tags-for-resource":       {"Arn"},
			"list-templates":               {"DomainId", "MaxResults", "NextToken", "Status"},
			"put-case-event-configuration": {"DomainId", "EventBridge"},
			"search-all-related-items":     {"DomainId", "Filters", "MaxResults", "NextToken", "Sorts"},
			"search-cases":                 {"DomainId", "Fields", "Filter", "MaxResults", "NextToken", "SearchTerm", "Sorts"},
			"search-related-items":         {"CaseId", "DomainId", "Filters", "MaxResults", "NextToken"},
			"tag-resource":                 {"Arn", "Tags"},
			"untag-resource":               {"Arn", "TagKeys"},
			"update-case":                  {"CaseId", "DomainId", "Fields", "PerformedBy"},
			"update-case-rule":             {"CaseRuleId", "Description", "DomainId", "Name", "Rule"},
			"update-field":                 {"Attributes", "Description", "DomainId", "FieldId", "Name"},
			"update-layout":                {"Content", "DomainId", "LayoutId", "Name"},
			"update-template":              {"Description", "DomainId", "LayoutConfiguration", "Name", "RequiredFields", "Rules", "Status", "TagPropagationConfigurations", "TemplateId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-get-case-rule":          {"CaseRules": "[]types.CaseRuleIdentifier", "DomainId": "*string"},
			"batch-get-field":              {"DomainId": "*string", "Fields": "[]types.FieldIdentifier"},
			"batch-put-field-options":      {"DomainId": "*string", "FieldId": "*string", "Options": "[]types.FieldOption"},
			"create-case":                  {"ClientToken": "*string", "DomainId": "*string", "Fields": "[]types.FieldValue", "PerformedBy": "types.UserUnion", "Tags": "map[string]string", "TemplateId": "*string"},
			"create-case-rule":             {"Description": "*string", "DomainId": "*string", "Name": "*string", "Rule": "types.CaseRuleDetails"},
			"create-domain":                {"Name": "*string"},
			"create-field":                 {"Attributes": "types.FieldAttributes", "Description": "*string", "DomainId": "*string", "Name": "*string", "Type": "types.FieldType"},
			"create-layout":                {"Content": "types.LayoutContent", "DomainId": "*string", "Name": "*string"},
			"create-related-item":          {"CaseId": "*string", "Content": "types.RelatedItemInputContent", "DomainId": "*string", "PerformedBy": "types.UserUnion", "Type": "types.RelatedItemType"},
			"create-template":              {"Description": "*string", "DomainId": "*string", "LayoutConfiguration": "*types.LayoutConfiguration", "Name": "*string", "RequiredFields": "[]types.RequiredField", "Rules": "[]types.TemplateRule", "Status": "types.TemplateStatus", "TagPropagationConfigurations": "[]types.TagPropagationConfiguration"},
			"delete-case":                  {"CaseId": "*string", "DomainId": "*string"},
			"delete-case-rule":             {"CaseRuleId": "*string", "DomainId": "*string"},
			"delete-domain":                {"DomainId": "*string"},
			"delete-field":                 {"DomainId": "*string", "FieldId": "*string"},
			"delete-layout":                {"DomainId": "*string", "LayoutId": "*string"},
			"delete-related-item":          {"CaseId": "*string", "DomainId": "*string", "RelatedItemId": "*string"},
			"delete-template":              {"DomainId": "*string", "TemplateId": "*string"},
			"get-case":                     {"CaseId": "*string", "DomainId": "*string", "Fields": "[]types.FieldIdentifier", "NextToken": "*string"},
			"get-case-audit-events":        {"CaseId": "*string", "DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-case-event-configuration": {"DomainId": "*string"},
			"get-domain":                   {"DomainId": "*string"},
			"get-layout":                   {"DomainId": "*string", "LayoutId": "*string"},
			"get-template":                 {"DomainId": "*string", "TemplateId": "*string"},
			"list-case-rules":              {"DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-cases-for-contact":       {"ContactArn": "*string", "DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-domains":                 {"MaxResults": "*int32", "NextToken": "*string"},
			"list-field-options":           {"DomainId": "*string", "FieldId": "*string", "MaxResults": "*int32", "NextToken": "*string", "Values": "[]string"},
			"list-fields":                  {"DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-layouts":                 {"DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":       {"Arn": "*string"},
			"list-templates":               {"DomainId": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "[]types.TemplateStatus"},
			"put-case-event-configuration": {"DomainId": "*string", "EventBridge": "*types.EventBridgeConfiguration"},
			"search-all-related-items":     {"DomainId": "*string", "Filters": "[]types.RelatedItemTypeFilter", "MaxResults": "*int32", "NextToken": "*string", "Sorts": "[]types.SearchAllRelatedItemsSort"},
			"search-cases":                 {"DomainId": "*string", "Fields": "[]types.FieldIdentifier", "Filter": "types.CaseFilter", "MaxResults": "*int32", "NextToken": "*string", "SearchTerm": "*string", "Sorts": "[]types.Sort"},
			"search-related-items":         {"CaseId": "*string", "DomainId": "*string", "Filters": "[]types.RelatedItemTypeFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"tag-resource":                 {"Arn": "*string", "Tags": "map[string]*string"},
			"untag-resource":               {"Arn": "*string", "TagKeys": "[]string"},
			"update-case":                  {"CaseId": "*string", "DomainId": "*string", "Fields": "[]types.FieldValue", "PerformedBy": "types.UserUnion"},
			"update-case-rule":             {"CaseRuleId": "*string", "Description": "*string", "DomainId": "*string", "Name": "*string", "Rule": "types.CaseRuleDetails"},
			"update-field":                 {"Attributes": "types.FieldAttributes", "Description": "*string", "DomainId": "*string", "FieldId": "*string", "Name": "*string"},
			"update-layout":                {"Content": "types.LayoutContent", "DomainId": "*string", "LayoutId": "*string", "Name": "*string"},
			"update-template":              {"Description": "*string", "DomainId": "*string", "LayoutConfiguration": "*types.LayoutConfiguration", "Name": "*string", "RequiredFields": "[]types.RequiredField", "Rules": "[]types.TemplateRule", "Status": "types.TemplateStatus", "TagPropagationConfigurations": "[]types.TagPropagationConfiguration", "TemplateId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-get-case-rule":          {"CaseRules", "DomainId"},
			"batch-get-field":              {"DomainId", "Fields"},
			"batch-put-field-options":      {"DomainId", "FieldId", "Options"},
			"create-case":                  {"DomainId", "Fields", "TemplateId"},
			"create-case-rule":             {"DomainId", "Name", "Rule"},
			"create-domain":                {"Name"},
			"create-field":                 {"DomainId", "Name", "Type"},
			"create-layout":                {"Content", "DomainId", "Name"},
			"create-related-item":          {"CaseId", "Content", "DomainId", "Type"},
			"create-template":              {"DomainId", "Name"},
			"delete-case":                  {"CaseId", "DomainId"},
			"delete-case-rule":             {"CaseRuleId", "DomainId"},
			"delete-domain":                {"DomainId"},
			"delete-field":                 {"DomainId", "FieldId"},
			"delete-layout":                {"DomainId", "LayoutId"},
			"delete-related-item":          {"CaseId", "DomainId", "RelatedItemId"},
			"delete-template":              {"DomainId", "TemplateId"},
			"get-case":                     {"CaseId", "DomainId", "Fields"},
			"get-case-audit-events":        {"CaseId", "DomainId"},
			"get-case-event-configuration": {"DomainId"},
			"get-domain":                   {"DomainId"},
			"get-layout":                   {"DomainId", "LayoutId"},
			"get-template":                 {"DomainId", "TemplateId"},
			"list-case-rules":              {"DomainId"},
			"list-cases-for-contact":       {"ContactArn", "DomainId"},
			"list-domains":                 {},
			"list-field-options":           {"DomainId", "FieldId"},
			"list-fields":                  {"DomainId"},
			"list-layouts":                 {"DomainId"},
			"list-tags-for-resource":       {"Arn"},
			"list-templates":               {"DomainId"},
			"put-case-event-configuration": {"DomainId", "EventBridge"},
			"search-all-related-items":     {"DomainId"},
			"search-cases":                 {"DomainId"},
			"search-related-items":         {"CaseId", "DomainId"},
			"tag-resource":                 {"Arn", "Tags"},
			"untag-resource":               {"Arn", "TagKeys"},
			"update-case":                  {"CaseId", "DomainId", "Fields"},
			"update-case-rule":             {"CaseRuleId", "DomainId"},
			"update-field":                 {"DomainId", "FieldId"},
			"update-layout":                {"DomainId", "LayoutId"},
			"update-template":              {"DomainId", "TemplateId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("connectcases", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
