package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/customerprofiles/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-profile-key", "batch-get-calculated-attribute-for-profile", "batch-get-profile", "create-calculated-attribute-definition", "create-domain", "create-domain-layout", "create-event-stream", "create-event-trigger", "create-integration-workflow", "create-profile", "create-recommender", "create-segment-definition", "create-segment-estimate", "create-segment-snapshot", "create-upload-job", "delete-calculated-attribute-definition", "delete-domain", "delete-domain-layout", "delete-domain-object-type", "delete-event-stream", "delete-event-trigger", "delete-integration", "delete-profile", "delete-profile-key", "delete-profile-object", "delete-profile-object-type", "delete-recommender", "delete-segment-definition", "delete-workflow", "detect-profile-object-type", "get-auto-merging-preview", "get-calculated-attribute-definition", "get-calculated-attribute-for-profile", "get-domain", "get-domain-layout", "get-domain-object-type", "get-event-stream", "get-event-trigger", "get-identity-resolution-job", "get-integration", "get-matches", "get-object-type-attribute-statistics", "get-profile-history-record", "get-profile-object-type", "get-profile-object-type-template", "get-profile-recommendations", "get-recommender", "get-segment-definition", "get-segment-estimate", "get-segment-membership", "get-segment-snapshot", "get-similar-profiles", "get-upload-job", "get-upload-job-path", "get-workflow", "get-workflow-steps", "list-account-integrations", "list-calculated-attribute-definitions", "list-calculated-attributes-for-profile", "list-domain-layouts", "list-domain-object-types", "list-domains", "list-event-streams", "list-event-triggers", "list-identity-resolution-jobs", "list-integrations", "list-object-type-attribute-values", "list-object-type-attributes", "list-profile-attribute-values", "list-profile-history-records", "list-profile-object-type-templates", "list-profile-object-types", "list-profile-objects", "list-recommender-recipes", "list-recommenders", "list-rule-based-matches", "list-segment-definitions", "list-tags-for-resource", "list-upload-jobs", "list-workflows", "merge-profiles", "put-domain-object-type", "put-integration", "put-profile-object", "put-profile-object-type", "search-profiles", "start-recommender", "start-upload-job", "stop-recommender", "stop-upload-job", "tag-resource", "untag-resource", "update-calculated-attribute-definition", "update-domain", "update-domain-layout", "update-event-trigger", "update-profile", "update-recommender"},
		OperationSet: map[string]bool{"add-profile-key": true, "batch-get-calculated-attribute-for-profile": true, "batch-get-profile": true, "create-calculated-attribute-definition": true, "create-domain": true, "create-domain-layout": true, "create-event-stream": true, "create-event-trigger": true, "create-integration-workflow": true, "create-profile": true, "create-recommender": true, "create-segment-definition": true, "create-segment-estimate": true, "create-segment-snapshot": true, "create-upload-job": true, "delete-calculated-attribute-definition": true, "delete-domain": true, "delete-domain-layout": true, "delete-domain-object-type": true, "delete-event-stream": true, "delete-event-trigger": true, "delete-integration": true, "delete-profile": true, "delete-profile-key": true, "delete-profile-object": true, "delete-profile-object-type": true, "delete-recommender": true, "delete-segment-definition": true, "delete-workflow": true, "detect-profile-object-type": true, "get-auto-merging-preview": true, "get-calculated-attribute-definition": true, "get-calculated-attribute-for-profile": true, "get-domain": true, "get-domain-layout": true, "get-domain-object-type": true, "get-event-stream": true, "get-event-trigger": true, "get-identity-resolution-job": true, "get-integration": true, "get-matches": true, "get-object-type-attribute-statistics": true, "get-profile-history-record": true, "get-profile-object-type": true, "get-profile-object-type-template": true, "get-profile-recommendations": true, "get-recommender": true, "get-segment-definition": true, "get-segment-estimate": true, "get-segment-membership": true, "get-segment-snapshot": true, "get-similar-profiles": true, "get-upload-job": true, "get-upload-job-path": true, "get-workflow": true, "get-workflow-steps": true, "list-account-integrations": true, "list-calculated-attribute-definitions": true, "list-calculated-attributes-for-profile": true, "list-domain-layouts": true, "list-domain-object-types": true, "list-domains": true, "list-event-streams": true, "list-event-triggers": true, "list-identity-resolution-jobs": true, "list-integrations": true, "list-object-type-attribute-values": true, "list-object-type-attributes": true, "list-profile-attribute-values": true, "list-profile-history-records": true, "list-profile-object-type-templates": true, "list-profile-object-types": true, "list-profile-objects": true, "list-recommender-recipes": true, "list-recommenders": true, "list-rule-based-matches": true, "list-segment-definitions": true, "list-tags-for-resource": true, "list-upload-jobs": true, "list-workflows": true, "merge-profiles": true, "put-domain-object-type": true, "put-integration": true, "put-profile-object": true, "put-profile-object-type": true, "search-profiles": true, "start-recommender": true, "start-upload-job": true, "stop-recommender": true, "stop-upload-job": true, "tag-resource": true, "untag-resource": true, "update-calculated-attribute-definition": true, "update-domain": true, "update-domain-layout": true, "update-event-trigger": true, "update-profile": true, "update-recommender": true},
		OperationInputs: map[string][]string{
			"add-profile-key": {"DomainName", "KeyName", "ProfileId", "Values"},
			"batch-get-calculated-attribute-for-profile": {"CalculatedAttributeName", "ConditionOverrides", "DomainName", "ProfileIds"},
			"batch-get-profile":                          {"DomainName", "ProfileIds"},
			"create-calculated-attribute-definition":     {"AttributeDetails", "CalculatedAttributeName", "Conditions", "Description", "DisplayName", "DomainName", "Filter", "Statistic", "Tags", "UseHistoricalData"},
			"create-domain":                              {"DataStore", "DeadLetterQueueUrl", "DefaultEncryptionKey", "DefaultExpirationDays", "DomainName", "Matching", "RuleBasedMatching", "Tags"},
			"create-domain-layout":                       {"Description", "DisplayName", "DomainName", "IsDefault", "Layout", "LayoutDefinitionName", "LayoutType", "Tags"},
			"create-event-stream":                        {"DomainName", "EventStreamName", "Tags", "Uri"},
			"create-event-trigger":                       {"Description", "DomainName", "EventTriggerConditions", "EventTriggerLimits", "EventTriggerName", "ObjectTypeName", "SegmentFilter", "Tags"},
			"create-integration-workflow":                {"DomainName", "IntegrationConfig", "ObjectTypeName", "RoleArn", "Tags", "WorkflowType"},
			"create-profile":                             {"AccountNumber", "AdditionalInformation", "Address", "Attributes", "BillingAddress", "BirthDate", "BusinessEmailAddress", "BusinessName", "BusinessPhoneNumber", "DomainName", "EmailAddress", "EngagementPreferences", "FirstName", "Gender", "GenderString", "HomePhoneNumber", "LastName", "MailingAddress", "MiddleName", "MobilePhoneNumber", "PartyType", "PartyTypeString", "PersonalEmailAddress", "PhoneNumber", "ProfileType", "ShippingAddress"},
			"create-recommender":                         {"Description", "DomainName", "RecommenderConfig", "RecommenderName", "RecommenderRecipeName", "Tags"},
			"create-segment-definition":                  {"Description", "DisplayName", "DomainName", "SegmentDefinitionName", "SegmentGroups", "SegmentSqlQuery", "Tags"},
			"create-segment-estimate":                    {"DomainName", "SegmentQuery", "SegmentSqlQuery"},
			"create-segment-snapshot":                    {"DataFormat", "DestinationUri", "DomainName", "EncryptionKey", "RoleArn", "SegmentDefinitionName"},
			"create-upload-job":                          {"DataExpiry", "DisplayName", "DomainName", "Fields", "UniqueKey"},
			"delete-calculated-attribute-definition":     {"CalculatedAttributeName", "DomainName"},
			"delete-domain":                              {"DomainName"},
			"delete-domain-layout":                       {"DomainName", "LayoutDefinitionName"},
			"delete-domain-object-type":                  {"DomainName", "ObjectTypeName"},
			"delete-event-stream":                        {"DomainName", "EventStreamName"},
			"delete-event-trigger":                       {"DomainName", "EventTriggerName"},
			"delete-integration":                         {"DomainName", "Uri"},
			"delete-profile":                             {"DomainName", "ProfileId"},
			"delete-profile-key":                         {"DomainName", "KeyName", "ProfileId", "Values"},
			"delete-profile-object":                      {"DomainName", "ObjectTypeName", "ProfileId", "ProfileObjectUniqueKey"},
			"delete-profile-object-type":                 {"DomainName", "ObjectTypeName"},
			"delete-recommender":                         {"DomainName", "RecommenderName"},
			"delete-segment-definition":                  {"DomainName", "SegmentDefinitionName"},
			"delete-workflow":                            {"DomainName", "WorkflowId"},
			"detect-profile-object-type":                 {"DomainName", "Objects"},
			"get-auto-merging-preview":                   {"ConflictResolution", "Consolidation", "DomainName", "MinAllowedConfidenceScoreForMerging"},
			"get-calculated-attribute-definition":        {"CalculatedAttributeName", "DomainName"},
			"get-calculated-attribute-for-profile":       {"CalculatedAttributeName", "DomainName", "ProfileId"},
			"get-domain":                                 {"DomainName"},
			"get-domain-layout":                          {"DomainName", "LayoutDefinitionName"},
			"get-domain-object-type":                     {"DomainName", "ObjectTypeName"},
			"get-event-stream":                           {"DomainName", "EventStreamName"},
			"get-event-trigger":                          {"DomainName", "EventTriggerName"},
			"get-identity-resolution-job":                {"DomainName", "JobId"},
			"get-integration":                            {"DomainName", "Uri"},
			"get-matches":                                {"DomainName", "MaxResults", "NextToken"},
			"get-object-type-attribute-statistics":       {"AttributeName", "DomainName", "ObjectTypeName"},
			"get-profile-history-record":                 {"DomainName", "Id", "ProfileId"},
			"get-profile-object-type":                    {"DomainName", "ObjectTypeName"},
			"get-profile-object-type-template":           {"TemplateId"},
			"get-profile-recommendations":                {"Context", "DomainName", "MaxResults", "ProfileId", "RecommenderName"},
			"get-recommender":                            {"DomainName", "RecommenderName", "TrainingMetricsCount"},
			"get-segment-definition":                     {"DomainName", "SegmentDefinitionName"},
			"get-segment-estimate":                       {"DomainName", "EstimateId"},
			"get-segment-membership":                     {"DomainName", "ProfileIds", "SegmentDefinitionName"},
			"get-segment-snapshot":                       {"DomainName", "SegmentDefinitionName", "SnapshotId"},
			"get-similar-profiles":                       {"DomainName", "MatchType", "MaxResults", "NextToken", "SearchKey", "SearchValue"},
			"get-upload-job":                             {"DomainName", "JobId"},
			"get-upload-job-path":                        {"DomainName", "JobId"},
			"get-workflow":                               {"DomainName", "WorkflowId"},
			"get-workflow-steps":                         {"DomainName", "MaxResults", "NextToken", "WorkflowId"},
			"list-account-integrations":                  {"IncludeHidden", "MaxResults", "NextToken", "Uri"},
			"list-calculated-attribute-definitions":      {"DomainName", "MaxResults", "NextToken"},
			"list-calculated-attributes-for-profile":     {"DomainName", "MaxResults", "NextToken", "ProfileId"},
			"list-domain-layouts":                        {"DomainName", "MaxResults", "NextToken"},
			"list-domain-object-types":                   {"DomainName", "MaxResults", "NextToken"},
			"list-domains":                               {"MaxResults", "NextToken"},
			"list-event-streams":                         {"DomainName", "MaxResults", "NextToken"},
			"list-event-triggers":                        {"DomainName", "MaxResults", "NextToken"},
			"list-identity-resolution-jobs":              {"DomainName", "MaxResults", "NextToken"},
			"list-integrations":                          {"DomainName", "IncludeHidden", "MaxResults", "NextToken"},
			"list-object-type-attribute-values":          {"AttributeName", "DomainName", "MaxResults", "NextToken", "ObjectTypeName"},
			"list-object-type-attributes":                {"DomainName", "MaxResults", "NextToken", "ObjectTypeName"},
			"list-profile-attribute-values":              {"AttributeName", "DomainName"},
			"list-profile-history-records":               {"ActionType", "DomainName", "MaxResults", "NextToken", "ObjectTypeName", "PerformedBy", "ProfileId"},
			"list-profile-object-type-templates":         {"MaxResults", "NextToken"},
			"list-profile-object-types":                  {"DomainName", "MaxResults", "NextToken"},
			"list-profile-objects":                       {"DomainName", "MaxResults", "NextToken", "ObjectFilter", "ObjectTypeName", "ProfileId"},
			"list-recommender-recipes":                   {"MaxResults", "NextToken"},
			"list-recommenders":                          {"DomainName", "MaxResults", "NextToken"},
			"list-rule-based-matches":                    {"DomainName", "MaxResults", "NextToken"},
			"list-segment-definitions":                   {"DomainName", "MaxResults", "NextToken"},
			"list-tags-for-resource":                     {"ResourceArn"},
			"list-upload-jobs":                           {"DomainName", "MaxResults", "NextToken"},
			"list-workflows":                             {"DomainName", "MaxResults", "NextToken", "QueryEndDate", "QueryStartDate", "Status", "WorkflowType"},
			"merge-profiles":                             {"DomainName", "FieldSourceProfileIds", "MainProfileId", "ProfileIdsToBeMerged"},
			"put-domain-object-type":                     {"Description", "DomainName", "EncryptionKey", "Fields", "ObjectTypeName", "Tags"},
			"put-integration":                            {"DomainName", "EventTriggerNames", "FlowDefinition", "ObjectTypeName", "ObjectTypeNames", "RoleArn", "Scope", "Tags", "Uri"},
			"put-profile-object":                         {"DomainName", "Object", "ObjectTypeName"},
			"put-profile-object-type":                    {"AllowProfileCreation", "Description", "DomainName", "EncryptionKey", "ExpirationDays", "Fields", "Keys", "MaxProfileObjectCount", "ObjectTypeName", "SourceLastUpdatedTimestampFormat", "SourcePriority", "Tags", "TemplateId"},
			"search-profiles":                            {"AdditionalSearchKeys", "DomainName", "KeyName", "LogicalOperator", "MaxResults", "NextToken", "Values"},
			"start-recommender":                          {"DomainName", "RecommenderName"},
			"start-upload-job":                           {"DomainName", "JobId"},
			"stop-recommender":                           {"DomainName", "RecommenderName"},
			"stop-upload-job":                            {"DomainName", "JobId"},
			"tag-resource":                               {"ResourceArn", "Tags"},
			"untag-resource":                             {"ResourceArn", "TagKeys"},
			"update-calculated-attribute-definition":     {"CalculatedAttributeName", "Conditions", "Description", "DisplayName", "DomainName"},
			"update-domain":                              {"DataStore", "DeadLetterQueueUrl", "DefaultEncryptionKey", "DefaultExpirationDays", "DomainName", "Matching", "RuleBasedMatching", "Tags"},
			"update-domain-layout":                       {"Description", "DisplayName", "DomainName", "IsDefault", "Layout", "LayoutDefinitionName", "LayoutType"},
			"update-event-trigger":                       {"Description", "DomainName", "EventTriggerConditions", "EventTriggerLimits", "EventTriggerName", "ObjectTypeName", "SegmentFilter"},
			"update-profile":                             {"AccountNumber", "AdditionalInformation", "Address", "Attributes", "BillingAddress", "BirthDate", "BusinessEmailAddress", "BusinessName", "BusinessPhoneNumber", "DomainName", "EmailAddress", "EngagementPreferences", "FirstName", "Gender", "GenderString", "HomePhoneNumber", "LastName", "MailingAddress", "MiddleName", "MobilePhoneNumber", "PartyType", "PartyTypeString", "PersonalEmailAddress", "PhoneNumber", "ProfileId", "ProfileType", "ShippingAddress"},
			"update-recommender":                         {"Description", "DomainName", "RecommenderConfig", "RecommenderName"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-profile-key": {"DomainName": "*string", "KeyName": "*string", "ProfileId": "*string", "Values": "[]string"},
			"batch-get-calculated-attribute-for-profile": {"CalculatedAttributeName": "*string", "ConditionOverrides": "*types.ConditionOverrides", "DomainName": "*string", "ProfileIds": "[]string"},
			"batch-get-profile":                          {"DomainName": "*string", "ProfileIds": "[]string"},
			"create-calculated-attribute-definition":     {"AttributeDetails": "*types.AttributeDetails", "CalculatedAttributeName": "*string", "Conditions": "*types.Conditions", "Description": "*string", "DisplayName": "*string", "DomainName": "*string", "Filter": "*types.Filter", "Statistic": "types.Statistic", "Tags": "map[string]string", "UseHistoricalData": "*bool"},
			"create-domain":                              {"DataStore": "*types.DataStoreRequest", "DeadLetterQueueUrl": "*string", "DefaultEncryptionKey": "*string", "DefaultExpirationDays": "*int32", "DomainName": "*string", "Matching": "*types.MatchingRequest", "RuleBasedMatching": "*types.RuleBasedMatchingRequest", "Tags": "map[string]string"},
			"create-domain-layout":                       {"Description": "*string", "DisplayName": "*string", "DomainName": "*string", "IsDefault": "bool", "Layout": "*string", "LayoutDefinitionName": "*string", "LayoutType": "types.LayoutType", "Tags": "map[string]string"},
			"create-event-stream":                        {"DomainName": "*string", "EventStreamName": "*string", "Tags": "map[string]string", "Uri": "*string"},
			"create-event-trigger":                       {"Description": "*string", "DomainName": "*string", "EventTriggerConditions": "[]types.EventTriggerCondition", "EventTriggerLimits": "*types.EventTriggerLimits", "EventTriggerName": "*string", "ObjectTypeName": "*string", "SegmentFilter": "*string", "Tags": "map[string]string"},
			"create-integration-workflow":                {"DomainName": "*string", "IntegrationConfig": "*types.IntegrationConfig", "ObjectTypeName": "*string", "RoleArn": "*string", "Tags": "map[string]string", "WorkflowType": "types.WorkflowType"},
			"create-profile":                             {"AccountNumber": "*string", "AdditionalInformation": "*string", "Address": "*types.Address", "Attributes": "map[string]string", "BillingAddress": "*types.Address", "BirthDate": "*string", "BusinessEmailAddress": "*string", "BusinessName": "*string", "BusinessPhoneNumber": "*string", "DomainName": "*string", "EmailAddress": "*string", "EngagementPreferences": "*types.EngagementPreferences", "FirstName": "*string", "Gender": "types.Gender", "GenderString": "*string", "HomePhoneNumber": "*string", "LastName": "*string", "MailingAddress": "*types.Address", "MiddleName": "*string", "MobilePhoneNumber": "*string", "PartyType": "types.PartyType", "PartyTypeString": "*string", "PersonalEmailAddress": "*string", "PhoneNumber": "*string", "ProfileType": "types.ProfileType", "ShippingAddress": "*types.Address"},
			"create-recommender":                         {"Description": "*string", "DomainName": "*string", "RecommenderConfig": "*types.RecommenderConfig", "RecommenderName": "*string", "RecommenderRecipeName": "types.RecommenderRecipeName", "Tags": "map[string]string"},
			"create-segment-definition":                  {"Description": "*string", "DisplayName": "*string", "DomainName": "*string", "SegmentDefinitionName": "*string", "SegmentGroups": "*types.SegmentGroup", "SegmentSqlQuery": "*string", "Tags": "map[string]string"},
			"create-segment-estimate":                    {"DomainName": "*string", "SegmentQuery": "*types.SegmentGroupStructure", "SegmentSqlQuery": "*string"},
			"create-segment-snapshot":                    {"DataFormat": "types.DataFormat", "DestinationUri": "*string", "DomainName": "*string", "EncryptionKey": "*string", "RoleArn": "*string", "SegmentDefinitionName": "*string"},
			"create-upload-job":                          {"DataExpiry": "*int32", "DisplayName": "*string", "DomainName": "*string", "Fields": "map[string]types.ObjectTypeField", "UniqueKey": "*string"},
			"delete-calculated-attribute-definition":     {"CalculatedAttributeName": "*string", "DomainName": "*string"},
			"delete-domain":                              {"DomainName": "*string"},
			"delete-domain-layout":                       {"DomainName": "*string", "LayoutDefinitionName": "*string"},
			"delete-domain-object-type":                  {"DomainName": "*string", "ObjectTypeName": "*string"},
			"delete-event-stream":                        {"DomainName": "*string", "EventStreamName": "*string"},
			"delete-event-trigger":                       {"DomainName": "*string", "EventTriggerName": "*string"},
			"delete-integration":                         {"DomainName": "*string", "Uri": "*string"},
			"delete-profile":                             {"DomainName": "*string", "ProfileId": "*string"},
			"delete-profile-key":                         {"DomainName": "*string", "KeyName": "*string", "ProfileId": "*string", "Values": "[]string"},
			"delete-profile-object":                      {"DomainName": "*string", "ObjectTypeName": "*string", "ProfileId": "*string", "ProfileObjectUniqueKey": "*string"},
			"delete-profile-object-type":                 {"DomainName": "*string", "ObjectTypeName": "*string"},
			"delete-recommender":                         {"DomainName": "*string", "RecommenderName": "*string"},
			"delete-segment-definition":                  {"DomainName": "*string", "SegmentDefinitionName": "*string"},
			"delete-workflow":                            {"DomainName": "*string", "WorkflowId": "*string"},
			"detect-profile-object-type":                 {"DomainName": "*string", "Objects": "[]string"},
			"get-auto-merging-preview":                   {"ConflictResolution": "*types.ConflictResolution", "Consolidation": "*types.Consolidation", "DomainName": "*string", "MinAllowedConfidenceScoreForMerging": "*float64"},
			"get-calculated-attribute-definition":        {"CalculatedAttributeName": "*string", "DomainName": "*string"},
			"get-calculated-attribute-for-profile":       {"CalculatedAttributeName": "*string", "DomainName": "*string", "ProfileId": "*string"},
			"get-domain":                                 {"DomainName": "*string"},
			"get-domain-layout":                          {"DomainName": "*string", "LayoutDefinitionName": "*string"},
			"get-domain-object-type":                     {"DomainName": "*string", "ObjectTypeName": "*string"},
			"get-event-stream":                           {"DomainName": "*string", "EventStreamName": "*string"},
			"get-event-trigger":                          {"DomainName": "*string", "EventTriggerName": "*string"},
			"get-identity-resolution-job":                {"DomainName": "*string", "JobId": "*string"},
			"get-integration":                            {"DomainName": "*string", "Uri": "*string"},
			"get-matches":                                {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-object-type-attribute-statistics":       {"AttributeName": "*string", "DomainName": "*string", "ObjectTypeName": "*string"},
			"get-profile-history-record":                 {"DomainName": "*string", "Id": "*string", "ProfileId": "*string"},
			"get-profile-object-type":                    {"DomainName": "*string", "ObjectTypeName": "*string"},
			"get-profile-object-type-template":           {"TemplateId": "*string"},
			"get-profile-recommendations":                {"Context": "map[string]string", "DomainName": "*string", "MaxResults": "*int32", "ProfileId": "*string", "RecommenderName": "*string"},
			"get-recommender":                            {"DomainName": "*string", "RecommenderName": "*string", "TrainingMetricsCount": "*int32"},
			"get-segment-definition":                     {"DomainName": "*string", "SegmentDefinitionName": "*string"},
			"get-segment-estimate":                       {"DomainName": "*string", "EstimateId": "*string"},
			"get-segment-membership":                     {"DomainName": "*string", "ProfileIds": "[]string", "SegmentDefinitionName": "*string"},
			"get-segment-snapshot":                       {"DomainName": "*string", "SegmentDefinitionName": "*string", "SnapshotId": "*string"},
			"get-similar-profiles":                       {"DomainName": "*string", "MatchType": "types.MatchType", "MaxResults": "*int32", "NextToken": "*string", "SearchKey": "*string", "SearchValue": "*string"},
			"get-upload-job":                             {"DomainName": "*string", "JobId": "*string"},
			"get-upload-job-path":                        {"DomainName": "*string", "JobId": "*string"},
			"get-workflow":                               {"DomainName": "*string", "WorkflowId": "*string"},
			"get-workflow-steps":                         {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string", "WorkflowId": "*string"},
			"list-account-integrations":                  {"IncludeHidden": "*bool", "MaxResults": "*int32", "NextToken": "*string", "Uri": "*string"},
			"list-calculated-attribute-definitions":      {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-calculated-attributes-for-profile":     {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ProfileId": "*string"},
			"list-domain-layouts":                        {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-domain-object-types":                   {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-domains":                               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-event-streams":                         {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-event-triggers":                        {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-identity-resolution-jobs":              {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-integrations":                          {"DomainName": "*string", "IncludeHidden": "*bool", "MaxResults": "*int32", "NextToken": "*string"},
			"list-object-type-attribute-values":          {"AttributeName": "*string", "DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ObjectTypeName": "*string"},
			"list-object-type-attributes":                {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ObjectTypeName": "*string"},
			"list-profile-attribute-values":              {"AttributeName": "*string", "DomainName": "*string"},
			"list-profile-history-records":               {"ActionType": "types.ActionType", "DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ObjectTypeName": "*string", "PerformedBy": "*string", "ProfileId": "*string"},
			"list-profile-object-type-templates":         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-profile-object-types":                  {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-profile-objects":                       {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ObjectFilter": "*types.ObjectFilter", "ObjectTypeName": "*string", "ProfileId": "*string"},
			"list-recommender-recipes":                   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-recommenders":                          {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-rule-based-matches":                    {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-segment-definitions":                   {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                     {"ResourceArn": "*string"},
			"list-upload-jobs":                           {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-workflows":                             {"DomainName": "*string", "MaxResults": "*int32", "NextToken": "*string", "QueryEndDate": "*time.Time", "QueryStartDate": "*time.Time", "Status": "types.Status", "WorkflowType": "types.WorkflowType"},
			"merge-profiles":                             {"DomainName": "*string", "FieldSourceProfileIds": "*types.FieldSourceProfileIds", "MainProfileId": "*string", "ProfileIdsToBeMerged": "[]string"},
			"put-domain-object-type":                     {"Description": "*string", "DomainName": "*string", "EncryptionKey": "*string", "Fields": "map[string]types.DomainObjectTypeField", "ObjectTypeName": "*string", "Tags": "map[string]string"},
			"put-integration":                            {"DomainName": "*string", "EventTriggerNames": "[]string", "FlowDefinition": "*types.FlowDefinition", "ObjectTypeName": "*string", "ObjectTypeNames": "map[string]string", "RoleArn": "*string", "Scope": "types.Scope", "Tags": "map[string]string", "Uri": "*string"},
			"put-profile-object":                         {"DomainName": "*string", "Object": "*string", "ObjectTypeName": "*string"},
			"put-profile-object-type":                    {"AllowProfileCreation": "bool", "Description": "*string", "DomainName": "*string", "EncryptionKey": "*string", "ExpirationDays": "*int32", "Fields": "map[string]types.ObjectTypeField", "Keys": "map[string][]types.ObjectTypeKey", "MaxProfileObjectCount": "*int32", "ObjectTypeName": "*string", "SourceLastUpdatedTimestampFormat": "*string", "SourcePriority": "*int32", "Tags": "map[string]string", "TemplateId": "*string"},
			"search-profiles":                            {"AdditionalSearchKeys": "[]types.AdditionalSearchKey", "DomainName": "*string", "KeyName": "*string", "LogicalOperator": "types.LogicalOperator", "MaxResults": "*int32", "NextToken": "*string", "Values": "[]string"},
			"start-recommender":                          {"DomainName": "*string", "RecommenderName": "*string"},
			"start-upload-job":                           {"DomainName": "*string", "JobId": "*string"},
			"stop-recommender":                           {"DomainName": "*string", "RecommenderName": "*string"},
			"stop-upload-job":                            {"DomainName": "*string", "JobId": "*string"},
			"tag-resource":                               {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                             {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-calculated-attribute-definition":     {"CalculatedAttributeName": "*string", "Conditions": "*types.Conditions", "Description": "*string", "DisplayName": "*string", "DomainName": "*string"},
			"update-domain":                              {"DataStore": "*types.DataStoreRequest", "DeadLetterQueueUrl": "*string", "DefaultEncryptionKey": "*string", "DefaultExpirationDays": "*int32", "DomainName": "*string", "Matching": "*types.MatchingRequest", "RuleBasedMatching": "*types.RuleBasedMatchingRequest", "Tags": "map[string]string"},
			"update-domain-layout":                       {"Description": "*string", "DisplayName": "*string", "DomainName": "*string", "IsDefault": "bool", "Layout": "*string", "LayoutDefinitionName": "*string", "LayoutType": "types.LayoutType"},
			"update-event-trigger":                       {"Description": "*string", "DomainName": "*string", "EventTriggerConditions": "[]types.EventTriggerCondition", "EventTriggerLimits": "*types.EventTriggerLimits", "EventTriggerName": "*string", "ObjectTypeName": "*string", "SegmentFilter": "*string"},
			"update-profile":                             {"AccountNumber": "*string", "AdditionalInformation": "*string", "Address": "*types.UpdateAddress", "Attributes": "map[string]string", "BillingAddress": "*types.UpdateAddress", "BirthDate": "*string", "BusinessEmailAddress": "*string", "BusinessName": "*string", "BusinessPhoneNumber": "*string", "DomainName": "*string", "EmailAddress": "*string", "EngagementPreferences": "*types.EngagementPreferences", "FirstName": "*string", "Gender": "types.Gender", "GenderString": "*string", "HomePhoneNumber": "*string", "LastName": "*string", "MailingAddress": "*types.UpdateAddress", "MiddleName": "*string", "MobilePhoneNumber": "*string", "PartyType": "types.PartyType", "PartyTypeString": "*string", "PersonalEmailAddress": "*string", "PhoneNumber": "*string", "ProfileId": "*string", "ProfileType": "types.ProfileType", "ShippingAddress": "*types.UpdateAddress"},
			"update-recommender":                         {"Description": "*string", "DomainName": "*string", "RecommenderConfig": "*types.RecommenderConfig", "RecommenderName": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"add-profile-key": {"DomainName", "KeyName", "ProfileId", "Values"},
			"batch-get-calculated-attribute-for-profile": {"CalculatedAttributeName", "DomainName", "ProfileIds"},
			"batch-get-profile":                          {"DomainName", "ProfileIds"},
			"create-calculated-attribute-definition":     {"AttributeDetails", "CalculatedAttributeName", "DomainName", "Statistic"},
			"create-domain":                              {"DefaultExpirationDays", "DomainName"},
			"create-domain-layout":                       {"Description", "DisplayName", "DomainName", "Layout", "LayoutDefinitionName", "LayoutType"},
			"create-event-stream":                        {"DomainName", "EventStreamName", "Uri"},
			"create-event-trigger":                       {"DomainName", "EventTriggerConditions", "EventTriggerName", "ObjectTypeName"},
			"create-integration-workflow":                {"DomainName", "IntegrationConfig", "ObjectTypeName", "RoleArn", "WorkflowType"},
			"create-profile":                             {"DomainName"},
			"create-recommender":                         {"DomainName", "RecommenderName", "RecommenderRecipeName"},
			"create-segment-definition":                  {"DisplayName", "DomainName", "SegmentDefinitionName"},
			"create-segment-estimate":                    {"DomainName"},
			"create-segment-snapshot":                    {"DataFormat", "DomainName", "SegmentDefinitionName"},
			"create-upload-job":                          {"DisplayName", "DomainName", "Fields", "UniqueKey"},
			"delete-calculated-attribute-definition":     {"CalculatedAttributeName", "DomainName"},
			"delete-domain":                              {"DomainName"},
			"delete-domain-layout":                       {"DomainName", "LayoutDefinitionName"},
			"delete-domain-object-type":                  {"DomainName", "ObjectTypeName"},
			"delete-event-stream":                        {"DomainName", "EventStreamName"},
			"delete-event-trigger":                       {"DomainName", "EventTriggerName"},
			"delete-integration":                         {"DomainName", "Uri"},
			"delete-profile":                             {"DomainName", "ProfileId"},
			"delete-profile-key":                         {"DomainName", "KeyName", "ProfileId", "Values"},
			"delete-profile-object":                      {"DomainName", "ObjectTypeName", "ProfileId", "ProfileObjectUniqueKey"},
			"delete-profile-object-type":                 {"DomainName", "ObjectTypeName"},
			"delete-recommender":                         {"DomainName", "RecommenderName"},
			"delete-segment-definition":                  {"DomainName", "SegmentDefinitionName"},
			"delete-workflow":                            {"DomainName", "WorkflowId"},
			"detect-profile-object-type":                 {"DomainName", "Objects"},
			"get-auto-merging-preview":                   {"ConflictResolution", "Consolidation", "DomainName"},
			"get-calculated-attribute-definition":        {"CalculatedAttributeName", "DomainName"},
			"get-calculated-attribute-for-profile":       {"CalculatedAttributeName", "DomainName", "ProfileId"},
			"get-domain":                                 {"DomainName"},
			"get-domain-layout":                          {"DomainName", "LayoutDefinitionName"},
			"get-domain-object-type":                     {"DomainName", "ObjectTypeName"},
			"get-event-stream":                           {"DomainName", "EventStreamName"},
			"get-event-trigger":                          {"DomainName", "EventTriggerName"},
			"get-identity-resolution-job":                {"DomainName", "JobId"},
			"get-integration":                            {"DomainName", "Uri"},
			"get-matches":                                {"DomainName"},
			"get-object-type-attribute-statistics":       {"AttributeName", "DomainName", "ObjectTypeName"},
			"get-profile-history-record":                 {"DomainName", "Id", "ProfileId"},
			"get-profile-object-type":                    {"DomainName", "ObjectTypeName"},
			"get-profile-object-type-template":           {"TemplateId"},
			"get-profile-recommendations":                {"DomainName", "ProfileId", "RecommenderName"},
			"get-recommender":                            {"DomainName", "RecommenderName"},
			"get-segment-definition":                     {"DomainName", "SegmentDefinitionName"},
			"get-segment-estimate":                       {"DomainName", "EstimateId"},
			"get-segment-membership":                     {"DomainName", "ProfileIds", "SegmentDefinitionName"},
			"get-segment-snapshot":                       {"DomainName", "SegmentDefinitionName", "SnapshotId"},
			"get-similar-profiles":                       {"DomainName", "MatchType", "SearchKey", "SearchValue"},
			"get-upload-job":                             {"DomainName", "JobId"},
			"get-upload-job-path":                        {"DomainName", "JobId"},
			"get-workflow":                               {"DomainName", "WorkflowId"},
			"get-workflow-steps":                         {"DomainName", "WorkflowId"},
			"list-account-integrations":                  {"Uri"},
			"list-calculated-attribute-definitions":      {"DomainName"},
			"list-calculated-attributes-for-profile":     {"DomainName", "ProfileId"},
			"list-domain-layouts":                        {"DomainName"},
			"list-domain-object-types":                   {"DomainName"},
			"list-domains":                               {},
			"list-event-streams":                         {"DomainName"},
			"list-event-triggers":                        {"DomainName"},
			"list-identity-resolution-jobs":              {"DomainName"},
			"list-integrations":                          {"DomainName"},
			"list-object-type-attribute-values":          {"AttributeName", "DomainName", "ObjectTypeName"},
			"list-object-type-attributes":                {"DomainName", "ObjectTypeName"},
			"list-profile-attribute-values":              {"AttributeName", "DomainName"},
			"list-profile-history-records":               {"DomainName", "ProfileId"},
			"list-profile-object-type-templates":         {},
			"list-profile-object-types":                  {"DomainName"},
			"list-profile-objects":                       {"DomainName", "ObjectTypeName", "ProfileId"},
			"list-recommender-recipes":                   {},
			"list-recommenders":                          {"DomainName"},
			"list-rule-based-matches":                    {"DomainName"},
			"list-segment-definitions":                   {"DomainName"},
			"list-tags-for-resource":                     {"ResourceArn"},
			"list-upload-jobs":                           {"DomainName"},
			"list-workflows":                             {"DomainName"},
			"merge-profiles":                             {"DomainName", "MainProfileId", "ProfileIdsToBeMerged"},
			"put-domain-object-type":                     {"DomainName", "Fields", "ObjectTypeName"},
			"put-integration":                            {"DomainName"},
			"put-profile-object":                         {"DomainName", "Object", "ObjectTypeName"},
			"put-profile-object-type":                    {"Description", "DomainName", "ObjectTypeName"},
			"search-profiles":                            {"DomainName", "KeyName", "Values"},
			"start-recommender":                          {"DomainName", "RecommenderName"},
			"start-upload-job":                           {"DomainName", "JobId"},
			"stop-recommender":                           {"DomainName", "RecommenderName"},
			"stop-upload-job":                            {"DomainName", "JobId"},
			"tag-resource":                               {"ResourceArn", "Tags"},
			"untag-resource":                             {"ResourceArn", "TagKeys"},
			"update-calculated-attribute-definition":     {"CalculatedAttributeName", "DomainName"},
			"update-domain":                              {"DomainName"},
			"update-domain-layout":                       {"DomainName", "LayoutDefinitionName"},
			"update-event-trigger":                       {"DomainName", "EventTriggerName"},
			"update-profile":                             {"DomainName", "ProfileId"},
			"update-recommender":                         {"DomainName", "RecommenderName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("customerprofiles", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
