package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/databasemigrationservice/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-tags-to-resource", "apply-pending-maintenance-action", "batch-start-recommendations", "cancel-metadata-model-conversion", "cancel-metadata-model-creation", "cancel-replication-task-assessment-run", "create-data-migration", "create-data-provider", "create-endpoint", "create-event-subscription", "create-fleet-advisor-collector", "create-instance-profile", "create-migration-project", "create-replication-config", "create-replication-instance", "create-replication-subnet-group", "create-replication-task", "delete-certificate", "delete-connection", "delete-data-migration", "delete-data-provider", "delete-endpoint", "delete-event-subscription", "delete-fleet-advisor-collector", "delete-fleet-advisor-databases", "delete-instance-profile", "delete-migration-project", "delete-replication-config", "delete-replication-instance", "delete-replication-subnet-group", "delete-replication-task", "delete-replication-task-assessment-run", "describe-account-attributes", "describe-applicable-individual-assessments", "describe-certificates", "describe-connections", "describe-conversion-configuration", "describe-data-migrations", "describe-data-providers", "describe-endpoint-settings", "describe-endpoint-types", "describe-endpoints", "describe-engine-versions", "describe-event-categories", "describe-event-subscriptions", "describe-events", "describe-extension-pack-associations", "describe-fleet-advisor-collectors", "describe-fleet-advisor-databases", "describe-fleet-advisor-lsa-analysis", "describe-fleet-advisor-schema-object-summary", "describe-fleet-advisor-schemas", "describe-instance-profiles", "describe-metadata-model", "describe-metadata-model-assessments", "describe-metadata-model-children", "describe-metadata-model-conversions", "describe-metadata-model-creations", "describe-metadata-model-exports-as-script", "describe-metadata-model-exports-to-target", "describe-metadata-model-imports", "describe-migration-projects", "describe-orderable-replication-instances", "describe-pending-maintenance-actions", "describe-recommendation-limitations", "describe-recommendations", "describe-refresh-schemas-status", "describe-replication-configs", "describe-replication-instance-task-logs", "describe-replication-instances", "describe-replication-subnet-groups", "describe-replication-table-statistics", "describe-replication-task-assessment-results", "describe-replication-task-assessment-runs", "describe-replication-task-individual-assessments", "describe-replication-tasks", "describe-replications", "describe-schemas", "describe-table-statistics", "export-metadata-model-assessment", "get-target-selection-rules", "import-certificate", "list-tags-for-resource", "modify-conversion-configuration", "modify-data-migration", "modify-data-provider", "modify-endpoint", "modify-event-subscription", "modify-instance-profile", "modify-migration-project", "modify-replication-config", "modify-replication-instance", "modify-replication-subnet-group", "modify-replication-task", "move-replication-task", "reboot-replication-instance", "refresh-schemas", "reload-replication-tables", "reload-tables", "remove-tags-from-resource", "run-fleet-advisor-lsa-analysis", "start-data-migration", "start-extension-pack-association", "start-metadata-model-assessment", "start-metadata-model-conversion", "start-metadata-model-creation", "start-metadata-model-export-as-script", "start-metadata-model-export-to-target", "start-metadata-model-import", "start-recommendations", "start-replication", "start-replication-task", "start-replication-task-assessment", "start-replication-task-assessment-run", "stop-data-migration", "stop-replication", "stop-replication-task", "test-connection", "update-subscriptions-to-event-bridge"},
		OperationSet: map[string]bool{"add-tags-to-resource": true, "apply-pending-maintenance-action": true, "batch-start-recommendations": true, "cancel-metadata-model-conversion": true, "cancel-metadata-model-creation": true, "cancel-replication-task-assessment-run": true, "create-data-migration": true, "create-data-provider": true, "create-endpoint": true, "create-event-subscription": true, "create-fleet-advisor-collector": true, "create-instance-profile": true, "create-migration-project": true, "create-replication-config": true, "create-replication-instance": true, "create-replication-subnet-group": true, "create-replication-task": true, "delete-certificate": true, "delete-connection": true, "delete-data-migration": true, "delete-data-provider": true, "delete-endpoint": true, "delete-event-subscription": true, "delete-fleet-advisor-collector": true, "delete-fleet-advisor-databases": true, "delete-instance-profile": true, "delete-migration-project": true, "delete-replication-config": true, "delete-replication-instance": true, "delete-replication-subnet-group": true, "delete-replication-task": true, "delete-replication-task-assessment-run": true, "describe-account-attributes": true, "describe-applicable-individual-assessments": true, "describe-certificates": true, "describe-connections": true, "describe-conversion-configuration": true, "describe-data-migrations": true, "describe-data-providers": true, "describe-endpoint-settings": true, "describe-endpoint-types": true, "describe-endpoints": true, "describe-engine-versions": true, "describe-event-categories": true, "describe-event-subscriptions": true, "describe-events": true, "describe-extension-pack-associations": true, "describe-fleet-advisor-collectors": true, "describe-fleet-advisor-databases": true, "describe-fleet-advisor-lsa-analysis": true, "describe-fleet-advisor-schema-object-summary": true, "describe-fleet-advisor-schemas": true, "describe-instance-profiles": true, "describe-metadata-model": true, "describe-metadata-model-assessments": true, "describe-metadata-model-children": true, "describe-metadata-model-conversions": true, "describe-metadata-model-creations": true, "describe-metadata-model-exports-as-script": true, "describe-metadata-model-exports-to-target": true, "describe-metadata-model-imports": true, "describe-migration-projects": true, "describe-orderable-replication-instances": true, "describe-pending-maintenance-actions": true, "describe-recommendation-limitations": true, "describe-recommendations": true, "describe-refresh-schemas-status": true, "describe-replication-configs": true, "describe-replication-instance-task-logs": true, "describe-replication-instances": true, "describe-replication-subnet-groups": true, "describe-replication-table-statistics": true, "describe-replication-task-assessment-results": true, "describe-replication-task-assessment-runs": true, "describe-replication-task-individual-assessments": true, "describe-replication-tasks": true, "describe-replications": true, "describe-schemas": true, "describe-table-statistics": true, "export-metadata-model-assessment": true, "get-target-selection-rules": true, "import-certificate": true, "list-tags-for-resource": true, "modify-conversion-configuration": true, "modify-data-migration": true, "modify-data-provider": true, "modify-endpoint": true, "modify-event-subscription": true, "modify-instance-profile": true, "modify-migration-project": true, "modify-replication-config": true, "modify-replication-instance": true, "modify-replication-subnet-group": true, "modify-replication-task": true, "move-replication-task": true, "reboot-replication-instance": true, "refresh-schemas": true, "reload-replication-tables": true, "reload-tables": true, "remove-tags-from-resource": true, "run-fleet-advisor-lsa-analysis": true, "start-data-migration": true, "start-extension-pack-association": true, "start-metadata-model-assessment": true, "start-metadata-model-conversion": true, "start-metadata-model-creation": true, "start-metadata-model-export-as-script": true, "start-metadata-model-export-to-target": true, "start-metadata-model-import": true, "start-recommendations": true, "start-replication": true, "start-replication-task": true, "start-replication-task-assessment": true, "start-replication-task-assessment-run": true, "stop-data-migration": true, "stop-replication": true, "stop-replication-task": true, "test-connection": true, "update-subscriptions-to-event-bridge": true},
		OperationInputs: map[string][]string{
			"add-tags-to-resource":                             {"ResourceArn", "Tags"},
			"apply-pending-maintenance-action":                 {"ApplyAction", "OptInType", "ReplicationInstanceArn"},
			"batch-start-recommendations":                      {"Data"},
			"cancel-metadata-model-conversion":                 {"MigrationProjectIdentifier", "RequestIdentifier"},
			"cancel-metadata-model-creation":                   {"MigrationProjectIdentifier", "RequestIdentifier"},
			"cancel-replication-task-assessment-run":           {"ReplicationTaskAssessmentRunArn"},
			"create-data-migration":                            {"DataMigrationName", "DataMigrationType", "EnableCloudwatchLogs", "MigrationProjectIdentifier", "NumberOfJobs", "SelectionRules", "ServiceAccessRoleArn", "SourceDataSettings", "Tags", "TargetDataSettings"},
			"create-data-provider":                             {"DataProviderName", "Description", "Engine", "Settings", "Tags", "Virtual"},
			"create-endpoint":                                  {"CertificateArn", "DatabaseName", "DmsTransferSettings", "DocDbSettings", "DynamoDbSettings", "ElasticsearchSettings", "EndpointIdentifier", "EndpointType", "EngineName", "ExternalTableDefinition", "ExtraConnectionAttributes", "GcpMySQLSettings", "IBMDb2Settings", "KafkaSettings", "KinesisSettings", "KmsKeyId", "MicrosoftSQLServerSettings", "MongoDbSettings", "MySQLSettings", "NeptuneSettings", "OracleSettings", "Password", "Port", "PostgreSQLSettings", "RedisSettings", "RedshiftSettings", "ResourceIdentifier", "S3Settings", "ServerName", "ServiceAccessRoleArn", "SslMode", "SybaseSettings", "Tags", "TimestreamSettings", "Username"},
			"create-event-subscription":                        {"Enabled", "EventCategories", "SnsTopicArn", "SourceIds", "SourceType", "SubscriptionName", "Tags"},
			"create-fleet-advisor-collector":                   {"CollectorName", "Description", "S3BucketName", "ServiceAccessRoleArn"},
			"create-instance-profile":                          {"AvailabilityZone", "Description", "InstanceProfileName", "KmsKeyArn", "NetworkType", "PubliclyAccessible", "SubnetGroupIdentifier", "Tags", "VpcSecurityGroups"},
			"create-migration-project":                         {"Description", "InstanceProfileIdentifier", "MigrationProjectName", "SchemaConversionApplicationAttributes", "SourceDataProviderDescriptors", "Tags", "TargetDataProviderDescriptors", "TransformationRules"},
			"create-replication-config":                        {"ComputeConfig", "ReplicationConfigIdentifier", "ReplicationSettings", "ReplicationType", "ResourceIdentifier", "SourceEndpointArn", "SupplementalSettings", "TableMappings", "Tags", "TargetEndpointArn"},
			"create-replication-instance":                      {"AllocatedStorage", "AutoMinorVersionUpgrade", "AvailabilityZone", "DnsNameServers", "EngineVersion", "KerberosAuthenticationSettings", "KmsKeyId", "MultiAZ", "NetworkType", "PreferredMaintenanceWindow", "PubliclyAccessible", "ReplicationInstanceClass", "ReplicationInstanceIdentifier", "ReplicationSubnetGroupIdentifier", "ResourceIdentifier", "Tags", "VpcSecurityGroupIds"},
			"create-replication-subnet-group":                  {"ReplicationSubnetGroupDescription", "ReplicationSubnetGroupIdentifier", "SubnetIds", "Tags"},
			"create-replication-task":                          {"CdcStartPosition", "CdcStartTime", "CdcStopPosition", "MigrationType", "ReplicationInstanceArn", "ReplicationTaskIdentifier", "ReplicationTaskSettings", "ResourceIdentifier", "SourceEndpointArn", "TableMappings", "Tags", "TargetEndpointArn", "TaskData"},
			"delete-certificate":                               {"CertificateArn"},
			"delete-connection":                                {"EndpointArn", "ReplicationInstanceArn"},
			"delete-data-migration":                            {"DataMigrationIdentifier"},
			"delete-data-provider":                             {"DataProviderIdentifier"},
			"delete-endpoint":                                  {"EndpointArn"},
			"delete-event-subscription":                        {"SubscriptionName"},
			"delete-fleet-advisor-collector":                   {"CollectorReferencedId"},
			"delete-fleet-advisor-databases":                   {"DatabaseIds"},
			"delete-instance-profile":                          {"InstanceProfileIdentifier"},
			"delete-migration-project":                         {"MigrationProjectIdentifier"},
			"delete-replication-config":                        {"ReplicationConfigArn"},
			"delete-replication-instance":                      {"ReplicationInstanceArn"},
			"delete-replication-subnet-group":                  {"ReplicationSubnetGroupIdentifier"},
			"delete-replication-task":                          {"ReplicationTaskArn"},
			"delete-replication-task-assessment-run":           {"ReplicationTaskAssessmentRunArn"},
			"describe-account-attributes":                      {},
			"describe-applicable-individual-assessments":       {"Marker", "MaxRecords", "MigrationType", "ReplicationConfigArn", "ReplicationInstanceArn", "ReplicationTaskArn", "SourceEngineName", "TargetEngineName"},
			"describe-certificates":                            {"Filters", "Marker", "MaxRecords"},
			"describe-connections":                             {"Filters", "Marker", "MaxRecords"},
			"describe-conversion-configuration":                {"MigrationProjectIdentifier"},
			"describe-data-migrations":                         {"Filters", "Marker", "MaxRecords", "WithoutSettings", "WithoutStatistics"},
			"describe-data-providers":                          {"Filters", "Marker", "MaxRecords"},
			"describe-endpoint-settings":                       {"EngineName", "Marker", "MaxRecords"},
			"describe-endpoint-types":                          {"Filters", "Marker", "MaxRecords"},
			"describe-endpoints":                               {"Filters", "Marker", "MaxRecords"},
			"describe-engine-versions":                         {"Marker", "MaxRecords"},
			"describe-event-categories":                        {"Filters", "SourceType"},
			"describe-event-subscriptions":                     {"Filters", "Marker", "MaxRecords", "SubscriptionName"},
			"describe-events":                                  {"Duration", "EndTime", "EventCategories", "Filters", "Marker", "MaxRecords", "SourceIdentifier", "SourceType", "StartTime"},
			"describe-extension-pack-associations":             {"Filters", "Marker", "MaxRecords", "MigrationProjectIdentifier"},
			"describe-fleet-advisor-collectors":                {"Filters", "MaxRecords", "NextToken"},
			"describe-fleet-advisor-databases":                 {"Filters", "MaxRecords", "NextToken"},
			"describe-fleet-advisor-lsa-analysis":              {"MaxRecords", "NextToken"},
			"describe-fleet-advisor-schema-object-summary":     {"Filters", "MaxRecords", "NextToken"},
			"describe-fleet-advisor-schemas":                   {"Filters", "MaxRecords", "NextToken"},
			"describe-instance-profiles":                       {"Filters", "Marker", "MaxRecords"},
			"describe-metadata-model":                          {"MigrationProjectIdentifier", "Origin", "SelectionRules"},
			"describe-metadata-model-assessments":              {"Filters", "Marker", "MaxRecords", "MigrationProjectIdentifier"},
			"describe-metadata-model-children":                 {"Marker", "MaxRecords", "MigrationProjectIdentifier", "Origin", "SelectionRules"},
			"describe-metadata-model-conversions":              {"Filters", "Marker", "MaxRecords", "MigrationProjectIdentifier"},
			"describe-metadata-model-creations":                {"Filters", "Marker", "MaxRecords", "MigrationProjectIdentifier"},
			"describe-metadata-model-exports-as-script":        {"Filters", "Marker", "MaxRecords", "MigrationProjectIdentifier"},
			"describe-metadata-model-exports-to-target":        {"Filters", "Marker", "MaxRecords", "MigrationProjectIdentifier"},
			"describe-metadata-model-imports":                  {"Filters", "Marker", "MaxRecords", "MigrationProjectIdentifier"},
			"describe-migration-projects":                      {"Filters", "Marker", "MaxRecords"},
			"describe-orderable-replication-instances":         {"Marker", "MaxRecords"},
			"describe-pending-maintenance-actions":             {"Filters", "Marker", "MaxRecords", "ReplicationInstanceArn"},
			"describe-recommendation-limitations":              {"Filters", "MaxRecords", "NextToken"},
			"describe-recommendations":                         {"Filters", "MaxRecords", "NextToken"},
			"describe-refresh-schemas-status":                  {"EndpointArn"},
			"describe-replication-configs":                     {"Filters", "Marker", "MaxRecords"},
			"describe-replication-instance-task-logs":          {"Marker", "MaxRecords", "ReplicationInstanceArn"},
			"describe-replication-instances":                   {"Filters", "Marker", "MaxRecords"},
			"describe-replication-subnet-groups":               {"Filters", "Marker", "MaxRecords"},
			"describe-replication-table-statistics":            {"Filters", "Marker", "MaxRecords", "ReplicationConfigArn"},
			"describe-replication-task-assessment-results":     {"Marker", "MaxRecords", "ReplicationTaskArn"},
			"describe-replication-task-assessment-runs":        {"Filters", "Marker", "MaxRecords"},
			"describe-replication-task-individual-assessments": {"Filters", "Marker", "MaxRecords"},
			"describe-replication-tasks":                       {"Filters", "Marker", "MaxRecords", "WithoutSettings"},
			"describe-replications":                            {"Filters", "Marker", "MaxRecords"},
			"describe-schemas":                                 {"EndpointArn", "Marker", "MaxRecords"},
			"describe-table-statistics":                        {"Filters", "Marker", "MaxRecords", "ReplicationTaskArn"},
			"export-metadata-model-assessment":                 {"AssessmentReportTypes", "FileName", "MigrationProjectIdentifier", "SelectionRules"},
			"get-target-selection-rules":                       {"MigrationProjectIdentifier", "SelectionRules"},
			"import-certificate":                               {"CertificateIdentifier", "CertificatePem", "CertificateWallet", "KmsKeyId", "Tags"},
			"list-tags-for-resource":                           {"ResourceArn", "ResourceArnList"},
			"modify-conversion-configuration":                  {"ConversionConfiguration", "MigrationProjectIdentifier"},
			"modify-data-migration":                            {"DataMigrationIdentifier", "DataMigrationName", "DataMigrationType", "EnableCloudwatchLogs", "NumberOfJobs", "SelectionRules", "ServiceAccessRoleArn", "SourceDataSettings", "TargetDataSettings"},
			"modify-data-provider":                             {"DataProviderIdentifier", "DataProviderName", "Description", "Engine", "ExactSettings", "Settings", "Virtual"},
			"modify-endpoint":                                  {"CertificateArn", "DatabaseName", "DmsTransferSettings", "DocDbSettings", "DynamoDbSettings", "ElasticsearchSettings", "EndpointArn", "EndpointIdentifier", "EndpointType", "EngineName", "ExactSettings", "ExternalTableDefinition", "ExtraConnectionAttributes", "GcpMySQLSettings", "IBMDb2Settings", "KafkaSettings", "KinesisSettings", "MicrosoftSQLServerSettings", "MongoDbSettings", "MySQLSettings", "NeptuneSettings", "OracleSettings", "Password", "Port", "PostgreSQLSettings", "RedisSettings", "RedshiftSettings", "S3Settings", "ServerName", "ServiceAccessRoleArn", "SslMode", "SybaseSettings", "TimestreamSettings", "Username"},
			"modify-event-subscription":                        {"Enabled", "EventCategories", "SnsTopicArn", "SourceType", "SubscriptionName"},
			"modify-instance-profile":                          {"AvailabilityZone", "Description", "InstanceProfileIdentifier", "InstanceProfileName", "KmsKeyArn", "NetworkType", "PubliclyAccessible", "SubnetGroupIdentifier", "VpcSecurityGroups"},
			"modify-migration-project":                         {"Description", "InstanceProfileIdentifier", "MigrationProjectIdentifier", "MigrationProjectName", "SchemaConversionApplicationAttributes", "SourceDataProviderDescriptors", "TargetDataProviderDescriptors", "TransformationRules"},
			"modify-replication-config":                        {"ComputeConfig", "ReplicationConfigArn", "ReplicationConfigIdentifier", "ReplicationSettings", "ReplicationType", "SourceEndpointArn", "SupplementalSettings", "TableMappings", "TargetEndpointArn"},
			"modify-replication-instance":                      {"AllocatedStorage", "AllowMajorVersionUpgrade", "ApplyImmediately", "AutoMinorVersionUpgrade", "EngineVersion", "KerberosAuthenticationSettings", "MultiAZ", "NetworkType", "PreferredMaintenanceWindow", "ReplicationInstanceArn", "ReplicationInstanceClass", "ReplicationInstanceIdentifier", "VpcSecurityGroupIds"},
			"modify-replication-subnet-group":                  {"ReplicationSubnetGroupDescription", "ReplicationSubnetGroupIdentifier", "SubnetIds"},
			"modify-replication-task":                          {"CdcStartPosition", "CdcStartTime", "CdcStopPosition", "MigrationType", "ReplicationTaskArn", "ReplicationTaskIdentifier", "ReplicationTaskSettings", "TableMappings", "TaskData"},
			"move-replication-task":                            {"ReplicationTaskArn", "TargetReplicationInstanceArn"},
			"reboot-replication-instance":                      {"ForceFailover", "ForcePlannedFailover", "ReplicationInstanceArn"},
			"refresh-schemas":                                  {"EndpointArn", "ReplicationInstanceArn"},
			"reload-replication-tables":                        {"ReloadOption", "ReplicationConfigArn", "TablesToReload"},
			"reload-tables":                                    {"ReloadOption", "ReplicationTaskArn", "TablesToReload"},
			"remove-tags-from-resource":                        {"ResourceArn", "TagKeys"},
			"run-fleet-advisor-lsa-analysis":                   {},
			"start-data-migration":                             {"DataMigrationIdentifier", "StartType"},
			"start-extension-pack-association":                 {"MigrationProjectIdentifier"},
			"start-metadata-model-assessment":                  {"MigrationProjectIdentifier", "SelectionRules"},
			"start-metadata-model-conversion":                  {"MigrationProjectIdentifier", "SelectionRules"},
			"start-metadata-model-creation":                    {"MetadataModelName", "MigrationProjectIdentifier", "Properties", "SelectionRules"},
			"start-metadata-model-export-as-script":            {"FileName", "MigrationProjectIdentifier", "Origin", "SelectionRules"},
			"start-metadata-model-export-to-target":            {"MigrationProjectIdentifier", "OverwriteExtensionPack", "SelectionRules"},
			"start-metadata-model-import":                      {"MigrationProjectIdentifier", "Origin", "Refresh", "SelectionRules"},
			"start-recommendations":                            {"DatabaseId", "Settings"},
			"start-replication":                                {"CdcStartPosition", "CdcStartTime", "CdcStopPosition", "PremigrationAssessmentSettings", "ReplicationConfigArn", "StartReplicationType"},
			"start-replication-task":                           {"CdcStartPosition", "CdcStartTime", "CdcStopPosition", "ReplicationTaskArn", "StartReplicationTaskType"},
			"start-replication-task-assessment":                {"ReplicationTaskArn"},
			"start-replication-task-assessment-run":            {"AssessmentRunName", "Exclude", "IncludeOnly", "ReplicationTaskArn", "ResultEncryptionMode", "ResultKmsKeyArn", "ResultLocationBucket", "ResultLocationFolder", "ServiceAccessRoleArn", "Tags"},
			"stop-data-migration":                              {"DataMigrationIdentifier"},
			"stop-replication":                                 {"ReplicationConfigArn"},
			"stop-replication-task":                            {"ReplicationTaskArn"},
			"test-connection":                                  {"EndpointArn", "ReplicationInstanceArn"},
			"update-subscriptions-to-event-bridge":             {"ForceMove"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-tags-to-resource":                             {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"apply-pending-maintenance-action":                 {"ApplyAction": "*string", "OptInType": "*string", "ReplicationInstanceArn": "*string"},
			"batch-start-recommendations":                      {"Data": "[]types.StartRecommendationsRequestEntry"},
			"cancel-metadata-model-conversion":                 {"MigrationProjectIdentifier": "*string", "RequestIdentifier": "*string"},
			"cancel-metadata-model-creation":                   {"MigrationProjectIdentifier": "*string", "RequestIdentifier": "*string"},
			"cancel-replication-task-assessment-run":           {"ReplicationTaskAssessmentRunArn": "*string"},
			"create-data-migration":                            {"DataMigrationName": "*string", "DataMigrationType": "types.MigrationTypeValue", "EnableCloudwatchLogs": "*bool", "MigrationProjectIdentifier": "*string", "NumberOfJobs": "*int32", "SelectionRules": "*string", "ServiceAccessRoleArn": "*string", "SourceDataSettings": "[]types.SourceDataSetting", "Tags": "[]types.Tag", "TargetDataSettings": "[]types.TargetDataSetting"},
			"create-data-provider":                             {"DataProviderName": "*string", "Description": "*string", "Engine": "*string", "Settings": "types.DataProviderSettings", "Tags": "[]types.Tag", "Virtual": "*bool"},
			"create-endpoint":                                  {"CertificateArn": "*string", "DatabaseName": "*string", "DmsTransferSettings": "*types.DmsTransferSettings", "DocDbSettings": "*types.DocDbSettings", "DynamoDbSettings": "*types.DynamoDbSettings", "ElasticsearchSettings": "*types.ElasticsearchSettings", "EndpointIdentifier": "*string", "EndpointType": "types.ReplicationEndpointTypeValue", "EngineName": "*string", "ExternalTableDefinition": "*string", "ExtraConnectionAttributes": "*string", "GcpMySQLSettings": "*types.GcpMySQLSettings", "IBMDb2Settings": "*types.IBMDb2Settings", "KafkaSettings": "*types.KafkaSettings", "KinesisSettings": "*types.KinesisSettings", "KmsKeyId": "*string", "MicrosoftSQLServerSettings": "*types.MicrosoftSQLServerSettings", "MongoDbSettings": "*types.MongoDbSettings", "MySQLSettings": "*types.MySQLSettings", "NeptuneSettings": "*types.NeptuneSettings", "OracleSettings": "*types.OracleSettings", "Password": "*string", "Port": "*int32", "PostgreSQLSettings": "*types.PostgreSQLSettings", "RedisSettings": "*types.RedisSettings", "RedshiftSettings": "*types.RedshiftSettings", "ResourceIdentifier": "*string", "S3Settings": "*types.S3Settings", "ServerName": "*string", "ServiceAccessRoleArn": "*string", "SslMode": "types.DmsSslModeValue", "SybaseSettings": "*types.SybaseSettings", "Tags": "[]types.Tag", "TimestreamSettings": "*types.TimestreamSettings", "Username": "*string"},
			"create-event-subscription":                        {"Enabled": "*bool", "EventCategories": "[]string", "SnsTopicArn": "*string", "SourceIds": "[]string", "SourceType": "*string", "SubscriptionName": "*string", "Tags": "[]types.Tag"},
			"create-fleet-advisor-collector":                   {"CollectorName": "*string", "Description": "*string", "S3BucketName": "*string", "ServiceAccessRoleArn": "*string"},
			"create-instance-profile":                          {"AvailabilityZone": "*string", "Description": "*string", "InstanceProfileName": "*string", "KmsKeyArn": "*string", "NetworkType": "*string", "PubliclyAccessible": "*bool", "SubnetGroupIdentifier": "*string", "Tags": "[]types.Tag", "VpcSecurityGroups": "[]string"},
			"create-migration-project":                         {"Description": "*string", "InstanceProfileIdentifier": "*string", "MigrationProjectName": "*string", "SchemaConversionApplicationAttributes": "*types.SCApplicationAttributes", "SourceDataProviderDescriptors": "[]types.DataProviderDescriptorDefinition", "Tags": "[]types.Tag", "TargetDataProviderDescriptors": "[]types.DataProviderDescriptorDefinition", "TransformationRules": "*string"},
			"create-replication-config":                        {"ComputeConfig": "*types.ComputeConfig", "ReplicationConfigIdentifier": "*string", "ReplicationSettings": "*string", "ReplicationType": "types.MigrationTypeValue", "ResourceIdentifier": "*string", "SourceEndpointArn": "*string", "SupplementalSettings": "*string", "TableMappings": "*string", "Tags": "[]types.Tag", "TargetEndpointArn": "*string"},
			"create-replication-instance":                      {"AllocatedStorage": "*int32", "AutoMinorVersionUpgrade": "*bool", "AvailabilityZone": "*string", "DnsNameServers": "*string", "EngineVersion": "*string", "KerberosAuthenticationSettings": "*types.KerberosAuthenticationSettings", "KmsKeyId": "*string", "MultiAZ": "*bool", "NetworkType": "*string", "PreferredMaintenanceWindow": "*string", "PubliclyAccessible": "*bool", "ReplicationInstanceClass": "*string", "ReplicationInstanceIdentifier": "*string", "ReplicationSubnetGroupIdentifier": "*string", "ResourceIdentifier": "*string", "Tags": "[]types.Tag", "VpcSecurityGroupIds": "[]string"},
			"create-replication-subnet-group":                  {"ReplicationSubnetGroupDescription": "*string", "ReplicationSubnetGroupIdentifier": "*string", "SubnetIds": "[]string", "Tags": "[]types.Tag"},
			"create-replication-task":                          {"CdcStartPosition": "*string", "CdcStartTime": "*time.Time", "CdcStopPosition": "*string", "MigrationType": "types.MigrationTypeValue", "ReplicationInstanceArn": "*string", "ReplicationTaskIdentifier": "*string", "ReplicationTaskSettings": "*string", "ResourceIdentifier": "*string", "SourceEndpointArn": "*string", "TableMappings": "*string", "Tags": "[]types.Tag", "TargetEndpointArn": "*string", "TaskData": "*string"},
			"delete-certificate":                               {"CertificateArn": "*string"},
			"delete-connection":                                {"EndpointArn": "*string", "ReplicationInstanceArn": "*string"},
			"delete-data-migration":                            {"DataMigrationIdentifier": "*string"},
			"delete-data-provider":                             {"DataProviderIdentifier": "*string"},
			"delete-endpoint":                                  {"EndpointArn": "*string"},
			"delete-event-subscription":                        {"SubscriptionName": "*string"},
			"delete-fleet-advisor-collector":                   {"CollectorReferencedId": "*string"},
			"delete-fleet-advisor-databases":                   {"DatabaseIds": "[]string"},
			"delete-instance-profile":                          {"InstanceProfileIdentifier": "*string"},
			"delete-migration-project":                         {"MigrationProjectIdentifier": "*string"},
			"delete-replication-config":                        {"ReplicationConfigArn": "*string"},
			"delete-replication-instance":                      {"ReplicationInstanceArn": "*string"},
			"delete-replication-subnet-group":                  {"ReplicationSubnetGroupIdentifier": "*string"},
			"delete-replication-task":                          {"ReplicationTaskArn": "*string"},
			"delete-replication-task-assessment-run":           {"ReplicationTaskAssessmentRunArn": "*string"},
			"describe-account-attributes":                      {},
			"describe-applicable-individual-assessments":       {"Marker": "*string", "MaxRecords": "*int32", "MigrationType": "types.MigrationTypeValue", "ReplicationConfigArn": "*string", "ReplicationInstanceArn": "*string", "ReplicationTaskArn": "*string", "SourceEngineName": "*string", "TargetEngineName": "*string"},
			"describe-certificates":                            {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-connections":                             {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-conversion-configuration":                {"MigrationProjectIdentifier": "*string"},
			"describe-data-migrations":                         {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "WithoutSettings": "*bool", "WithoutStatistics": "*bool"},
			"describe-data-providers":                          {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-endpoint-settings":                       {"EngineName": "*string", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-endpoint-types":                          {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-endpoints":                               {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-engine-versions":                         {"Marker": "*string", "MaxRecords": "*int32"},
			"describe-event-categories":                        {"Filters": "[]types.Filter", "SourceType": "*string"},
			"describe-event-subscriptions":                     {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "SubscriptionName": "*string"},
			"describe-events":                                  {"Duration": "*int32", "EndTime": "*time.Time", "EventCategories": "[]string", "Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "SourceIdentifier": "*string", "SourceType": "types.SourceType", "StartTime": "*time.Time"},
			"describe-extension-pack-associations":             {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "MigrationProjectIdentifier": "*string"},
			"describe-fleet-advisor-collectors":                {"Filters": "[]types.Filter", "MaxRecords": "*int32", "NextToken": "*string"},
			"describe-fleet-advisor-databases":                 {"Filters": "[]types.Filter", "MaxRecords": "*int32", "NextToken": "*string"},
			"describe-fleet-advisor-lsa-analysis":              {"MaxRecords": "*int32", "NextToken": "*string"},
			"describe-fleet-advisor-schema-object-summary":     {"Filters": "[]types.Filter", "MaxRecords": "*int32", "NextToken": "*string"},
			"describe-fleet-advisor-schemas":                   {"Filters": "[]types.Filter", "MaxRecords": "*int32", "NextToken": "*string"},
			"describe-instance-profiles":                       {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-metadata-model":                          {"MigrationProjectIdentifier": "*string", "Origin": "types.OriginTypeValue", "SelectionRules": "*string"},
			"describe-metadata-model-assessments":              {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "MigrationProjectIdentifier": "*string"},
			"describe-metadata-model-children":                 {"Marker": "*string", "MaxRecords": "*int32", "MigrationProjectIdentifier": "*string", "Origin": "types.OriginTypeValue", "SelectionRules": "*string"},
			"describe-metadata-model-conversions":              {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "MigrationProjectIdentifier": "*string"},
			"describe-metadata-model-creations":                {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "MigrationProjectIdentifier": "*string"},
			"describe-metadata-model-exports-as-script":        {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "MigrationProjectIdentifier": "*string"},
			"describe-metadata-model-exports-to-target":        {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "MigrationProjectIdentifier": "*string"},
			"describe-metadata-model-imports":                  {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "MigrationProjectIdentifier": "*string"},
			"describe-migration-projects":                      {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-orderable-replication-instances":         {"Marker": "*string", "MaxRecords": "*int32"},
			"describe-pending-maintenance-actions":             {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "ReplicationInstanceArn": "*string"},
			"describe-recommendation-limitations":              {"Filters": "[]types.Filter", "MaxRecords": "*int32", "NextToken": "*string"},
			"describe-recommendations":                         {"Filters": "[]types.Filter", "MaxRecords": "*int32", "NextToken": "*string"},
			"describe-refresh-schemas-status":                  {"EndpointArn": "*string"},
			"describe-replication-configs":                     {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-replication-instance-task-logs":          {"Marker": "*string", "MaxRecords": "*int32", "ReplicationInstanceArn": "*string"},
			"describe-replication-instances":                   {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-replication-subnet-groups":               {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-replication-table-statistics":            {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "ReplicationConfigArn": "*string"},
			"describe-replication-task-assessment-results":     {"Marker": "*string", "MaxRecords": "*int32", "ReplicationTaskArn": "*string"},
			"describe-replication-task-assessment-runs":        {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-replication-task-individual-assessments": {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-replication-tasks":                       {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "WithoutSettings": "*bool"},
			"describe-replications":                            {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-schemas":                                 {"EndpointArn": "*string", "Marker": "*string", "MaxRecords": "*int32"},
			"describe-table-statistics":                        {"Filters": "[]types.Filter", "Marker": "*string", "MaxRecords": "*int32", "ReplicationTaskArn": "*string"},
			"export-metadata-model-assessment":                 {"AssessmentReportTypes": "[]types.AssessmentReportType", "FileName": "*string", "MigrationProjectIdentifier": "*string", "SelectionRules": "*string"},
			"get-target-selection-rules":                       {"MigrationProjectIdentifier": "*string", "SelectionRules": "*string"},
			"import-certificate":                               {"CertificateIdentifier": "*string", "CertificatePem": "*string", "CertificateWallet": "[]byte", "KmsKeyId": "*string", "Tags": "[]types.Tag"},
			"list-tags-for-resource":                           {"ResourceArn": "*string", "ResourceArnList": "[]string"},
			"modify-conversion-configuration":                  {"ConversionConfiguration": "*string", "MigrationProjectIdentifier": "*string"},
			"modify-data-migration":                            {"DataMigrationIdentifier": "*string", "DataMigrationName": "*string", "DataMigrationType": "types.MigrationTypeValue", "EnableCloudwatchLogs": "*bool", "NumberOfJobs": "*int32", "SelectionRules": "*string", "ServiceAccessRoleArn": "*string", "SourceDataSettings": "[]types.SourceDataSetting", "TargetDataSettings": "[]types.TargetDataSetting"},
			"modify-data-provider":                             {"DataProviderIdentifier": "*string", "DataProviderName": "*string", "Description": "*string", "Engine": "*string", "ExactSettings": "*bool", "Settings": "types.DataProviderSettings", "Virtual": "*bool"},
			"modify-endpoint":                                  {"CertificateArn": "*string", "DatabaseName": "*string", "DmsTransferSettings": "*types.DmsTransferSettings", "DocDbSettings": "*types.DocDbSettings", "DynamoDbSettings": "*types.DynamoDbSettings", "ElasticsearchSettings": "*types.ElasticsearchSettings", "EndpointArn": "*string", "EndpointIdentifier": "*string", "EndpointType": "types.ReplicationEndpointTypeValue", "EngineName": "*string", "ExactSettings": "*bool", "ExternalTableDefinition": "*string", "ExtraConnectionAttributes": "*string", "GcpMySQLSettings": "*types.GcpMySQLSettings", "IBMDb2Settings": "*types.IBMDb2Settings", "KafkaSettings": "*types.KafkaSettings", "KinesisSettings": "*types.KinesisSettings", "MicrosoftSQLServerSettings": "*types.MicrosoftSQLServerSettings", "MongoDbSettings": "*types.MongoDbSettings", "MySQLSettings": "*types.MySQLSettings", "NeptuneSettings": "*types.NeptuneSettings", "OracleSettings": "*types.OracleSettings", "Password": "*string", "Port": "*int32", "PostgreSQLSettings": "*types.PostgreSQLSettings", "RedisSettings": "*types.RedisSettings", "RedshiftSettings": "*types.RedshiftSettings", "S3Settings": "*types.S3Settings", "ServerName": "*string", "ServiceAccessRoleArn": "*string", "SslMode": "types.DmsSslModeValue", "SybaseSettings": "*types.SybaseSettings", "TimestreamSettings": "*types.TimestreamSettings", "Username": "*string"},
			"modify-event-subscription":                        {"Enabled": "*bool", "EventCategories": "[]string", "SnsTopicArn": "*string", "SourceType": "*string", "SubscriptionName": "*string"},
			"modify-instance-profile":                          {"AvailabilityZone": "*string", "Description": "*string", "InstanceProfileIdentifier": "*string", "InstanceProfileName": "*string", "KmsKeyArn": "*string", "NetworkType": "*string", "PubliclyAccessible": "*bool", "SubnetGroupIdentifier": "*string", "VpcSecurityGroups": "[]string"},
			"modify-migration-project":                         {"Description": "*string", "InstanceProfileIdentifier": "*string", "MigrationProjectIdentifier": "*string", "MigrationProjectName": "*string", "SchemaConversionApplicationAttributes": "*types.SCApplicationAttributes", "SourceDataProviderDescriptors": "[]types.DataProviderDescriptorDefinition", "TargetDataProviderDescriptors": "[]types.DataProviderDescriptorDefinition", "TransformationRules": "*string"},
			"modify-replication-config":                        {"ComputeConfig": "*types.ComputeConfig", "ReplicationConfigArn": "*string", "ReplicationConfigIdentifier": "*string", "ReplicationSettings": "*string", "ReplicationType": "types.MigrationTypeValue", "SourceEndpointArn": "*string", "SupplementalSettings": "*string", "TableMappings": "*string", "TargetEndpointArn": "*string"},
			"modify-replication-instance":                      {"AllocatedStorage": "*int32", "AllowMajorVersionUpgrade": "bool", "ApplyImmediately": "bool", "AutoMinorVersionUpgrade": "*bool", "EngineVersion": "*string", "KerberosAuthenticationSettings": "*types.KerberosAuthenticationSettings", "MultiAZ": "*bool", "NetworkType": "*string", "PreferredMaintenanceWindow": "*string", "ReplicationInstanceArn": "*string", "ReplicationInstanceClass": "*string", "ReplicationInstanceIdentifier": "*string", "VpcSecurityGroupIds": "[]string"},
			"modify-replication-subnet-group":                  {"ReplicationSubnetGroupDescription": "*string", "ReplicationSubnetGroupIdentifier": "*string", "SubnetIds": "[]string"},
			"modify-replication-task":                          {"CdcStartPosition": "*string", "CdcStartTime": "*time.Time", "CdcStopPosition": "*string", "MigrationType": "types.MigrationTypeValue", "ReplicationTaskArn": "*string", "ReplicationTaskIdentifier": "*string", "ReplicationTaskSettings": "*string", "TableMappings": "*string", "TaskData": "*string"},
			"move-replication-task":                            {"ReplicationTaskArn": "*string", "TargetReplicationInstanceArn": "*string"},
			"reboot-replication-instance":                      {"ForceFailover": "*bool", "ForcePlannedFailover": "*bool", "ReplicationInstanceArn": "*string"},
			"refresh-schemas":                                  {"EndpointArn": "*string", "ReplicationInstanceArn": "*string"},
			"reload-replication-tables":                        {"ReloadOption": "types.ReloadOptionValue", "ReplicationConfigArn": "*string", "TablesToReload": "[]types.TableToReload"},
			"reload-tables":                                    {"ReloadOption": "types.ReloadOptionValue", "ReplicationTaskArn": "*string", "TablesToReload": "[]types.TableToReload"},
			"remove-tags-from-resource":                        {"ResourceArn": "*string", "TagKeys": "[]string"},
			"run-fleet-advisor-lsa-analysis":                   {},
			"start-data-migration":                             {"DataMigrationIdentifier": "*string", "StartType": "types.StartReplicationMigrationTypeValue"},
			"start-extension-pack-association":                 {"MigrationProjectIdentifier": "*string"},
			"start-metadata-model-assessment":                  {"MigrationProjectIdentifier": "*string", "SelectionRules": "*string"},
			"start-metadata-model-conversion":                  {"MigrationProjectIdentifier": "*string", "SelectionRules": "*string"},
			"start-metadata-model-creation":                    {"MetadataModelName": "*string", "MigrationProjectIdentifier": "*string", "Properties": "types.MetadataModelProperties", "SelectionRules": "*string"},
			"start-metadata-model-export-as-script":            {"FileName": "*string", "MigrationProjectIdentifier": "*string", "Origin": "types.OriginTypeValue", "SelectionRules": "*string"},
			"start-metadata-model-export-to-target":            {"MigrationProjectIdentifier": "*string", "OverwriteExtensionPack": "*bool", "SelectionRules": "*string"},
			"start-metadata-model-import":                      {"MigrationProjectIdentifier": "*string", "Origin": "types.OriginTypeValue", "Refresh": "bool", "SelectionRules": "*string"},
			"start-recommendations":                            {"DatabaseId": "*string", "Settings": "*types.RecommendationSettings"},
			"start-replication":                                {"CdcStartPosition": "*string", "CdcStartTime": "*time.Time", "CdcStopPosition": "*string", "PremigrationAssessmentSettings": "*string", "ReplicationConfigArn": "*string", "StartReplicationType": "*string"},
			"start-replication-task":                           {"CdcStartPosition": "*string", "CdcStartTime": "*time.Time", "CdcStopPosition": "*string", "ReplicationTaskArn": "*string", "StartReplicationTaskType": "types.StartReplicationTaskTypeValue"},
			"start-replication-task-assessment":                {"ReplicationTaskArn": "*string"},
			"start-replication-task-assessment-run":            {"AssessmentRunName": "*string", "Exclude": "[]string", "IncludeOnly": "[]string", "ReplicationTaskArn": "*string", "ResultEncryptionMode": "*string", "ResultKmsKeyArn": "*string", "ResultLocationBucket": "*string", "ResultLocationFolder": "*string", "ServiceAccessRoleArn": "*string", "Tags": "[]types.Tag"},
			"stop-data-migration":                              {"DataMigrationIdentifier": "*string"},
			"stop-replication":                                 {"ReplicationConfigArn": "*string"},
			"stop-replication-task":                            {"ReplicationTaskArn": "*string"},
			"test-connection":                                  {"EndpointArn": "*string", "ReplicationInstanceArn": "*string"},
			"update-subscriptions-to-event-bridge":             {"ForceMove": "*bool"},
		},
		OperationInputRequired: map[string][]string{
			"add-tags-to-resource":                             {"ResourceArn", "Tags"},
			"apply-pending-maintenance-action":                 {"ApplyAction", "OptInType", "ReplicationInstanceArn"},
			"batch-start-recommendations":                      {},
			"cancel-metadata-model-conversion":                 {"MigrationProjectIdentifier", "RequestIdentifier"},
			"cancel-metadata-model-creation":                   {"MigrationProjectIdentifier", "RequestIdentifier"},
			"cancel-replication-task-assessment-run":           {"ReplicationTaskAssessmentRunArn"},
			"create-data-migration":                            {"DataMigrationType", "MigrationProjectIdentifier", "ServiceAccessRoleArn"},
			"create-data-provider":                             {"Engine", "Settings"},
			"create-endpoint":                                  {"EndpointIdentifier", "EndpointType", "EngineName"},
			"create-event-subscription":                        {"SnsTopicArn", "SubscriptionName"},
			"create-fleet-advisor-collector":                   {"CollectorName", "S3BucketName", "ServiceAccessRoleArn"},
			"create-instance-profile":                          {},
			"create-migration-project":                         {"InstanceProfileIdentifier", "SourceDataProviderDescriptors", "TargetDataProviderDescriptors"},
			"create-replication-config":                        {"ComputeConfig", "ReplicationConfigIdentifier", "ReplicationType", "SourceEndpointArn", "TableMappings", "TargetEndpointArn"},
			"create-replication-instance":                      {"ReplicationInstanceClass", "ReplicationInstanceIdentifier"},
			"create-replication-subnet-group":                  {"ReplicationSubnetGroupDescription", "ReplicationSubnetGroupIdentifier", "SubnetIds"},
			"create-replication-task":                          {"MigrationType", "ReplicationInstanceArn", "ReplicationTaskIdentifier", "SourceEndpointArn", "TableMappings", "TargetEndpointArn"},
			"delete-certificate":                               {"CertificateArn"},
			"delete-connection":                                {"EndpointArn", "ReplicationInstanceArn"},
			"delete-data-migration":                            {"DataMigrationIdentifier"},
			"delete-data-provider":                             {"DataProviderIdentifier"},
			"delete-endpoint":                                  {"EndpointArn"},
			"delete-event-subscription":                        {"SubscriptionName"},
			"delete-fleet-advisor-collector":                   {"CollectorReferencedId"},
			"delete-fleet-advisor-databases":                   {"DatabaseIds"},
			"delete-instance-profile":                          {"InstanceProfileIdentifier"},
			"delete-migration-project":                         {"MigrationProjectIdentifier"},
			"delete-replication-config":                        {"ReplicationConfigArn"},
			"delete-replication-instance":                      {"ReplicationInstanceArn"},
			"delete-replication-subnet-group":                  {"ReplicationSubnetGroupIdentifier"},
			"delete-replication-task":                          {"ReplicationTaskArn"},
			"delete-replication-task-assessment-run":           {"ReplicationTaskAssessmentRunArn"},
			"describe-account-attributes":                      {},
			"describe-applicable-individual-assessments":       {},
			"describe-certificates":                            {},
			"describe-connections":                             {},
			"describe-conversion-configuration":                {"MigrationProjectIdentifier"},
			"describe-data-migrations":                         {},
			"describe-data-providers":                          {},
			"describe-endpoint-settings":                       {"EngineName"},
			"describe-endpoint-types":                          {},
			"describe-endpoints":                               {},
			"describe-engine-versions":                         {},
			"describe-event-categories":                        {},
			"describe-event-subscriptions":                     {},
			"describe-events":                                  {},
			"describe-extension-pack-associations":             {"MigrationProjectIdentifier"},
			"describe-fleet-advisor-collectors":                {},
			"describe-fleet-advisor-databases":                 {},
			"describe-fleet-advisor-lsa-analysis":              {},
			"describe-fleet-advisor-schema-object-summary":     {},
			"describe-fleet-advisor-schemas":                   {},
			"describe-instance-profiles":                       {},
			"describe-metadata-model":                          {"MigrationProjectIdentifier", "Origin", "SelectionRules"},
			"describe-metadata-model-assessments":              {"MigrationProjectIdentifier"},
			"describe-metadata-model-children":                 {"MigrationProjectIdentifier", "Origin", "SelectionRules"},
			"describe-metadata-model-conversions":              {"MigrationProjectIdentifier"},
			"describe-metadata-model-creations":                {"MigrationProjectIdentifier"},
			"describe-metadata-model-exports-as-script":        {"MigrationProjectIdentifier"},
			"describe-metadata-model-exports-to-target":        {"MigrationProjectIdentifier"},
			"describe-metadata-model-imports":                  {"MigrationProjectIdentifier"},
			"describe-migration-projects":                      {},
			"describe-orderable-replication-instances":         {},
			"describe-pending-maintenance-actions":             {},
			"describe-recommendation-limitations":              {},
			"describe-recommendations":                         {},
			"describe-refresh-schemas-status":                  {"EndpointArn"},
			"describe-replication-configs":                     {},
			"describe-replication-instance-task-logs":          {"ReplicationInstanceArn"},
			"describe-replication-instances":                   {},
			"describe-replication-subnet-groups":               {},
			"describe-replication-table-statistics":            {"ReplicationConfigArn"},
			"describe-replication-task-assessment-results":     {},
			"describe-replication-task-assessment-runs":        {},
			"describe-replication-task-individual-assessments": {},
			"describe-replication-tasks":                       {},
			"describe-replications":                            {},
			"describe-schemas":                                 {"EndpointArn"},
			"describe-table-statistics":                        {"ReplicationTaskArn"},
			"export-metadata-model-assessment":                 {"MigrationProjectIdentifier", "SelectionRules"},
			"get-target-selection-rules":                       {"MigrationProjectIdentifier", "SelectionRules"},
			"import-certificate":                               {"CertificateIdentifier"},
			"list-tags-for-resource":                           {},
			"modify-conversion-configuration":                  {"ConversionConfiguration", "MigrationProjectIdentifier"},
			"modify-data-migration":                            {"DataMigrationIdentifier"},
			"modify-data-provider":                             {"DataProviderIdentifier"},
			"modify-endpoint":                                  {"EndpointArn"},
			"modify-event-subscription":                        {"SubscriptionName"},
			"modify-instance-profile":                          {"InstanceProfileIdentifier"},
			"modify-migration-project":                         {"MigrationProjectIdentifier"},
			"modify-replication-config":                        {"ReplicationConfigArn"},
			"modify-replication-instance":                      {"ReplicationInstanceArn"},
			"modify-replication-subnet-group":                  {"ReplicationSubnetGroupIdentifier", "SubnetIds"},
			"modify-replication-task":                          {"ReplicationTaskArn"},
			"move-replication-task":                            {"ReplicationTaskArn", "TargetReplicationInstanceArn"},
			"reboot-replication-instance":                      {"ReplicationInstanceArn"},
			"refresh-schemas":                                  {"EndpointArn", "ReplicationInstanceArn"},
			"reload-replication-tables":                        {"ReplicationConfigArn", "TablesToReload"},
			"reload-tables":                                    {"ReplicationTaskArn", "TablesToReload"},
			"remove-tags-from-resource":                        {"ResourceArn", "TagKeys"},
			"run-fleet-advisor-lsa-analysis":                   {},
			"start-data-migration":                             {"DataMigrationIdentifier", "StartType"},
			"start-extension-pack-association":                 {"MigrationProjectIdentifier"},
			"start-metadata-model-assessment":                  {"MigrationProjectIdentifier", "SelectionRules"},
			"start-metadata-model-conversion":                  {"MigrationProjectIdentifier", "SelectionRules"},
			"start-metadata-model-creation":                    {"MetadataModelName", "MigrationProjectIdentifier", "Properties", "SelectionRules"},
			"start-metadata-model-export-as-script":            {"MigrationProjectIdentifier", "Origin", "SelectionRules"},
			"start-metadata-model-export-to-target":            {"MigrationProjectIdentifier", "SelectionRules"},
			"start-metadata-model-import":                      {"MigrationProjectIdentifier", "Origin", "SelectionRules"},
			"start-recommendations":                            {"DatabaseId", "Settings"},
			"start-replication":                                {"ReplicationConfigArn", "StartReplicationType"},
			"start-replication-task":                           {"ReplicationTaskArn", "StartReplicationTaskType"},
			"start-replication-task-assessment":                {"ReplicationTaskArn"},
			"start-replication-task-assessment-run":            {"AssessmentRunName", "ReplicationTaskArn", "ResultLocationBucket", "ServiceAccessRoleArn"},
			"stop-data-migration":                              {"DataMigrationIdentifier"},
			"stop-replication":                                 {"ReplicationConfigArn"},
			"stop-replication-task":                            {"ReplicationTaskArn"},
			"test-connection":                                  {"EndpointArn", "ReplicationInstanceArn"},
			"update-subscriptions-to-event-bridge":             {},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("databasemigrationservice", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
