package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/migrationhuborchestrator/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-template", "create-workflow", "create-workflow-step", "create-workflow-step-group", "delete-template", "delete-workflow", "delete-workflow-step", "delete-workflow-step-group", "get-template", "get-template-step", "get-template-step-group", "get-workflow", "get-workflow-step", "get-workflow-step-group", "list-plugins", "list-tags-for-resource", "list-template-step-groups", "list-template-steps", "list-templates", "list-workflow-step-groups", "list-workflow-steps", "list-workflows", "retry-workflow-step", "start-workflow", "stop-workflow", "tag-resource", "untag-resource", "update-template", "update-workflow", "update-workflow-step", "update-workflow-step-group"},
		OperationSet: map[string]bool{"create-template": true, "create-workflow": true, "create-workflow-step": true, "create-workflow-step-group": true, "delete-template": true, "delete-workflow": true, "delete-workflow-step": true, "delete-workflow-step-group": true, "get-template": true, "get-template-step": true, "get-template-step-group": true, "get-workflow": true, "get-workflow-step": true, "get-workflow-step-group": true, "list-plugins": true, "list-tags-for-resource": true, "list-template-step-groups": true, "list-template-steps": true, "list-templates": true, "list-workflow-step-groups": true, "list-workflow-steps": true, "list-workflows": true, "retry-workflow-step": true, "start-workflow": true, "stop-workflow": true, "tag-resource": true, "untag-resource": true, "update-template": true, "update-workflow": true, "update-workflow-step": true, "update-workflow-step-group": true},
		OperationInputs: map[string][]string{
			"create-template":            {"ClientToken", "Tags", "TemplateDescription", "TemplateName", "TemplateSource"},
			"create-workflow":            {"ApplicationConfigurationId", "Description", "InputParameters", "Name", "StepTargets", "Tags", "TemplateId"},
			"create-workflow-step":       {"Description", "Name", "Next", "Outputs", "Previous", "StepActionType", "StepGroupId", "StepTarget", "WorkflowId", "WorkflowStepAutomationConfiguration"},
			"create-workflow-step-group": {"Description", "Name", "Next", "Previous", "WorkflowId"},
			"delete-template":            {"Id"},
			"delete-workflow":            {"Id"},
			"delete-workflow-step":       {"Id", "StepGroupId", "WorkflowId"},
			"delete-workflow-step-group": {"Id", "WorkflowId"},
			"get-template":               {"Id"},
			"get-template-step":          {"Id", "StepGroupId", "TemplateId"},
			"get-template-step-group":    {"Id", "TemplateId"},
			"get-workflow":               {"Id"},
			"get-workflow-step":          {"Id", "StepGroupId", "WorkflowId"},
			"get-workflow-step-group":    {"Id", "WorkflowId"},
			"list-plugins":               {"MaxResults", "NextToken"},
			"list-tags-for-resource":     {"ResourceArn"},
			"list-template-step-groups":  {"MaxResults", "NextToken", "TemplateId"},
			"list-template-steps":        {"MaxResults", "NextToken", "StepGroupId", "TemplateId"},
			"list-templates":             {"MaxResults", "Name", "NextToken"},
			"list-workflow-step-groups":  {"MaxResults", "NextToken", "WorkflowId"},
			"list-workflow-steps":        {"MaxResults", "NextToken", "StepGroupId", "WorkflowId"},
			"list-workflows":             {"AdsApplicationConfigurationName", "MaxResults", "Name", "NextToken", "Status", "TemplateId"},
			"retry-workflow-step":        {"Id", "StepGroupId", "WorkflowId"},
			"start-workflow":             {"Id"},
			"stop-workflow":              {"Id"},
			"tag-resource":               {"ResourceArn", "Tags"},
			"untag-resource":             {"ResourceArn", "TagKeys"},
			"update-template":            {"ClientToken", "Id", "TemplateDescription", "TemplateName"},
			"update-workflow":            {"Description", "Id", "InputParameters", "Name", "StepTargets"},
			"update-workflow-step":       {"Description", "Id", "Name", "Next", "Outputs", "Previous", "Status", "StepActionType", "StepGroupId", "StepTarget", "WorkflowId", "WorkflowStepAutomationConfiguration"},
			"update-workflow-step-group": {"Description", "Id", "Name", "Next", "Previous", "WorkflowId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-template":            {"ClientToken": "*string", "Tags": "map[string]string", "TemplateDescription": "*string", "TemplateName": "*string", "TemplateSource": "types.TemplateSource"},
			"create-workflow":            {"ApplicationConfigurationId": "*string", "Description": "*string", "InputParameters": "map[string]types.StepInput", "Name": "*string", "StepTargets": "[]string", "Tags": "map[string]string", "TemplateId": "*string"},
			"create-workflow-step":       {"Description": "*string", "Name": "*string", "Next": "[]string", "Outputs": "[]types.WorkflowStepOutput", "Previous": "[]string", "StepActionType": "types.StepActionType", "StepGroupId": "*string", "StepTarget": "[]string", "WorkflowId": "*string", "WorkflowStepAutomationConfiguration": "*types.WorkflowStepAutomationConfiguration"},
			"create-workflow-step-group": {"Description": "*string", "Name": "*string", "Next": "[]string", "Previous": "[]string", "WorkflowId": "*string"},
			"delete-template":            {"Id": "*string"},
			"delete-workflow":            {"Id": "*string"},
			"delete-workflow-step":       {"Id": "*string", "StepGroupId": "*string", "WorkflowId": "*string"},
			"delete-workflow-step-group": {"Id": "*string", "WorkflowId": "*string"},
			"get-template":               {"Id": "*string"},
			"get-template-step":          {"Id": "*string", "StepGroupId": "*string", "TemplateId": "*string"},
			"get-template-step-group":    {"Id": "*string", "TemplateId": "*string"},
			"get-workflow":               {"Id": "*string"},
			"get-workflow-step":          {"Id": "*string", "StepGroupId": "*string", "WorkflowId": "*string"},
			"get-workflow-step-group":    {"Id": "*string", "WorkflowId": "*string"},
			"list-plugins":               {"MaxResults": "int32", "NextToken": "*string"},
			"list-tags-for-resource":     {"ResourceArn": "*string"},
			"list-template-step-groups":  {"MaxResults": "int32", "NextToken": "*string", "TemplateId": "*string"},
			"list-template-steps":        {"MaxResults": "int32", "NextToken": "*string", "StepGroupId": "*string", "TemplateId": "*string"},
			"list-templates":             {"MaxResults": "int32", "Name": "*string", "NextToken": "*string"},
			"list-workflow-step-groups":  {"MaxResults": "int32", "NextToken": "*string", "WorkflowId": "*string"},
			"list-workflow-steps":        {"MaxResults": "int32", "NextToken": "*string", "StepGroupId": "*string", "WorkflowId": "*string"},
			"list-workflows":             {"AdsApplicationConfigurationName": "*string", "MaxResults": "int32", "Name": "*string", "NextToken": "*string", "Status": "types.MigrationWorkflowStatusEnum", "TemplateId": "*string"},
			"retry-workflow-step":        {"Id": "*string", "StepGroupId": "*string", "WorkflowId": "*string"},
			"start-workflow":             {"Id": "*string"},
			"stop-workflow":              {"Id": "*string"},
			"tag-resource":               {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":             {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-template":            {"ClientToken": "*string", "Id": "*string", "TemplateDescription": "*string", "TemplateName": "*string"},
			"update-workflow":            {"Description": "*string", "Id": "*string", "InputParameters": "map[string]types.StepInput", "Name": "*string", "StepTargets": "[]string"},
			"update-workflow-step":       {"Description": "*string", "Id": "*string", "Name": "*string", "Next": "[]string", "Outputs": "[]types.WorkflowStepOutput", "Previous": "[]string", "Status": "types.StepStatus", "StepActionType": "types.StepActionType", "StepGroupId": "*string", "StepTarget": "[]string", "WorkflowId": "*string", "WorkflowStepAutomationConfiguration": "*types.WorkflowStepAutomationConfiguration"},
			"update-workflow-step-group": {"Description": "*string", "Id": "*string", "Name": "*string", "Next": "[]string", "Previous": "[]string", "WorkflowId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-template":            {"TemplateName", "TemplateSource"},
			"create-workflow":            {"InputParameters", "Name", "TemplateId"},
			"create-workflow-step":       {"Name", "StepActionType", "StepGroupId", "WorkflowId"},
			"create-workflow-step-group": {"Name", "WorkflowId"},
			"delete-template":            {"Id"},
			"delete-workflow":            {"Id"},
			"delete-workflow-step":       {"Id", "StepGroupId", "WorkflowId"},
			"delete-workflow-step-group": {"Id", "WorkflowId"},
			"get-template":               {"Id"},
			"get-template-step":          {"Id", "StepGroupId", "TemplateId"},
			"get-template-step-group":    {"Id", "TemplateId"},
			"get-workflow":               {"Id"},
			"get-workflow-step":          {"Id", "StepGroupId", "WorkflowId"},
			"get-workflow-step-group":    {"Id", "WorkflowId"},
			"list-plugins":               {},
			"list-tags-for-resource":     {"ResourceArn"},
			"list-template-step-groups":  {"TemplateId"},
			"list-template-steps":        {"StepGroupId", "TemplateId"},
			"list-templates":             {},
			"list-workflow-step-groups":  {"WorkflowId"},
			"list-workflow-steps":        {"StepGroupId", "WorkflowId"},
			"list-workflows":             {},
			"retry-workflow-step":        {"Id", "StepGroupId", "WorkflowId"},
			"start-workflow":             {"Id"},
			"stop-workflow":              {"Id"},
			"tag-resource":               {"ResourceArn", "Tags"},
			"untag-resource":             {"ResourceArn", "TagKeys"},
			"update-template":            {"Id"},
			"update-workflow":            {"Id"},
			"update-workflow-step":       {"Id", "StepGroupId", "WorkflowId"},
			"update-workflow-step-group": {"Id", "WorkflowId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("migrationhuborchestrator", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
