package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/vpclattice/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-update-rule", "create-access-log-subscription", "create-listener", "create-resource-configuration", "create-resource-gateway", "create-rule", "create-service", "create-service-network", "create-service-network-resource-association", "create-service-network-service-association", "create-service-network-vpc-association", "create-target-group", "delete-access-log-subscription", "delete-auth-policy", "delete-domain-verification", "delete-listener", "delete-resource-configuration", "delete-resource-endpoint-association", "delete-resource-gateway", "delete-resource-policy", "delete-rule", "delete-service", "delete-service-network", "delete-service-network-resource-association", "delete-service-network-service-association", "delete-service-network-vpc-association", "delete-target-group", "deregister-targets", "get-access-log-subscription", "get-auth-policy", "get-domain-verification", "get-listener", "get-resource-configuration", "get-resource-gateway", "get-resource-policy", "get-rule", "get-service", "get-service-network", "get-service-network-resource-association", "get-service-network-service-association", "get-service-network-vpc-association", "get-target-group", "list-access-log-subscriptions", "list-domain-verifications", "list-listeners", "list-resource-configurations", "list-resource-endpoint-associations", "list-resource-gateways", "list-rules", "list-service-network-resource-associations", "list-service-network-service-associations", "list-service-network-vpc-associations", "list-service-network-vpc-endpoint-associations", "list-service-networks", "list-services", "list-tags-for-resource", "list-target-groups", "list-targets", "put-auth-policy", "put-resource-policy", "register-targets", "start-domain-verification", "tag-resource", "untag-resource", "update-access-log-subscription", "update-listener", "update-resource-configuration", "update-resource-gateway", "update-rule", "update-service", "update-service-network", "update-service-network-vpc-association", "update-target-group"},
		OperationSet: map[string]bool{"batch-update-rule": true, "create-access-log-subscription": true, "create-listener": true, "create-resource-configuration": true, "create-resource-gateway": true, "create-rule": true, "create-service": true, "create-service-network": true, "create-service-network-resource-association": true, "create-service-network-service-association": true, "create-service-network-vpc-association": true, "create-target-group": true, "delete-access-log-subscription": true, "delete-auth-policy": true, "delete-domain-verification": true, "delete-listener": true, "delete-resource-configuration": true, "delete-resource-endpoint-association": true, "delete-resource-gateway": true, "delete-resource-policy": true, "delete-rule": true, "delete-service": true, "delete-service-network": true, "delete-service-network-resource-association": true, "delete-service-network-service-association": true, "delete-service-network-vpc-association": true, "delete-target-group": true, "deregister-targets": true, "get-access-log-subscription": true, "get-auth-policy": true, "get-domain-verification": true, "get-listener": true, "get-resource-configuration": true, "get-resource-gateway": true, "get-resource-policy": true, "get-rule": true, "get-service": true, "get-service-network": true, "get-service-network-resource-association": true, "get-service-network-service-association": true, "get-service-network-vpc-association": true, "get-target-group": true, "list-access-log-subscriptions": true, "list-domain-verifications": true, "list-listeners": true, "list-resource-configurations": true, "list-resource-endpoint-associations": true, "list-resource-gateways": true, "list-rules": true, "list-service-network-resource-associations": true, "list-service-network-service-associations": true, "list-service-network-vpc-associations": true, "list-service-network-vpc-endpoint-associations": true, "list-service-networks": true, "list-services": true, "list-tags-for-resource": true, "list-target-groups": true, "list-targets": true, "put-auth-policy": true, "put-resource-policy": true, "register-targets": true, "start-domain-verification": true, "tag-resource": true, "untag-resource": true, "update-access-log-subscription": true, "update-listener": true, "update-resource-configuration": true, "update-resource-gateway": true, "update-rule": true, "update-service": true, "update-service-network": true, "update-service-network-vpc-association": true, "update-target-group": true},
		OperationInputs: map[string][]string{
			"batch-update-rule":                              {"ListenerIdentifier", "Rules", "ServiceIdentifier"},
			"create-access-log-subscription":                 {"ClientToken", "DestinationArn", "ResourceIdentifier", "ServiceNetworkLogType", "Tags"},
			"create-listener":                                {"ClientToken", "DefaultAction", "Name", "Port", "Protocol", "ServiceIdentifier", "Tags"},
			"create-resource-configuration":                  {"AllowAssociationToShareableServiceNetwork", "ClientToken", "CustomDomainName", "DomainVerificationIdentifier", "GroupDomain", "Name", "PortRanges", "Protocol", "ResourceConfigurationDefinition", "ResourceConfigurationGroupIdentifier", "ResourceGatewayIdentifier", "Tags", "Type"},
			"create-resource-gateway":                        {"ClientToken", "IpAddressType", "Ipv4AddressesPerEni", "Name", "SecurityGroupIds", "SubnetIds", "Tags", "VpcIdentifier"},
			"create-rule":                                    {"Action", "ClientToken", "ListenerIdentifier", "Match", "Name", "Priority", "ServiceIdentifier", "Tags"},
			"create-service":                                 {"AuthType", "CertificateArn", "ClientToken", "CustomDomainName", "Name", "Tags"},
			"create-service-network":                         {"AuthType", "ClientToken", "Name", "SharingConfig", "Tags"},
			"create-service-network-resource-association":    {"ClientToken", "PrivateDnsEnabled", "ResourceConfigurationIdentifier", "ServiceNetworkIdentifier", "Tags"},
			"create-service-network-service-association":     {"ClientToken", "ServiceIdentifier", "ServiceNetworkIdentifier", "Tags"},
			"create-service-network-vpc-association":         {"ClientToken", "DnsOptions", "PrivateDnsEnabled", "SecurityGroupIds", "ServiceNetworkIdentifier", "Tags", "VpcIdentifier"},
			"create-target-group":                            {"ClientToken", "Config", "Name", "Tags", "Type"},
			"delete-access-log-subscription":                 {"AccessLogSubscriptionIdentifier"},
			"delete-auth-policy":                             {"ResourceIdentifier"},
			"delete-domain-verification":                     {"DomainVerificationIdentifier"},
			"delete-listener":                                {"ListenerIdentifier", "ServiceIdentifier"},
			"delete-resource-configuration":                  {"ResourceConfigurationIdentifier"},
			"delete-resource-endpoint-association":           {"ResourceEndpointAssociationIdentifier"},
			"delete-resource-gateway":                        {"ResourceGatewayIdentifier"},
			"delete-resource-policy":                         {"ResourceArn"},
			"delete-rule":                                    {"ListenerIdentifier", "RuleIdentifier", "ServiceIdentifier"},
			"delete-service":                                 {"ServiceIdentifier"},
			"delete-service-network":                         {"ServiceNetworkIdentifier"},
			"delete-service-network-resource-association":    {"ServiceNetworkResourceAssociationIdentifier"},
			"delete-service-network-service-association":     {"ServiceNetworkServiceAssociationIdentifier"},
			"delete-service-network-vpc-association":         {"ServiceNetworkVpcAssociationIdentifier"},
			"delete-target-group":                            {"TargetGroupIdentifier"},
			"deregister-targets":                             {"TargetGroupIdentifier", "Targets"},
			"get-access-log-subscription":                    {"AccessLogSubscriptionIdentifier"},
			"get-auth-policy":                                {"ResourceIdentifier"},
			"get-domain-verification":                        {"DomainVerificationIdentifier"},
			"get-listener":                                   {"ListenerIdentifier", "ServiceIdentifier"},
			"get-resource-configuration":                     {"ResourceConfigurationIdentifier"},
			"get-resource-gateway":                           {"ResourceGatewayIdentifier"},
			"get-resource-policy":                            {"ResourceArn"},
			"get-rule":                                       {"ListenerIdentifier", "RuleIdentifier", "ServiceIdentifier"},
			"get-service":                                    {"ServiceIdentifier"},
			"get-service-network":                            {"ServiceNetworkIdentifier"},
			"get-service-network-resource-association":       {"ServiceNetworkResourceAssociationIdentifier"},
			"get-service-network-service-association":        {"ServiceNetworkServiceAssociationIdentifier"},
			"get-service-network-vpc-association":            {"ServiceNetworkVpcAssociationIdentifier"},
			"get-target-group":                               {"TargetGroupIdentifier"},
			"list-access-log-subscriptions":                  {"MaxResults", "NextToken", "ResourceIdentifier"},
			"list-domain-verifications":                      {"MaxResults", "NextToken"},
			"list-listeners":                                 {"MaxResults", "NextToken", "ServiceIdentifier"},
			"list-resource-configurations":                   {"DomainVerificationIdentifier", "MaxResults", "NextToken", "ResourceConfigurationGroupIdentifier", "ResourceGatewayIdentifier"},
			"list-resource-endpoint-associations":            {"MaxResults", "NextToken", "ResourceConfigurationIdentifier", "ResourceEndpointAssociationIdentifier", "VpcEndpointId", "VpcEndpointOwner"},
			"list-resource-gateways":                         {"MaxResults", "NextToken"},
			"list-rules":                                     {"ListenerIdentifier", "MaxResults", "NextToken", "ServiceIdentifier"},
			"list-service-network-resource-associations":     {"IncludeChildren", "MaxResults", "NextToken", "ResourceConfigurationIdentifier", "ServiceNetworkIdentifier"},
			"list-service-network-service-associations":      {"MaxResults", "NextToken", "ServiceIdentifier", "ServiceNetworkIdentifier"},
			"list-service-network-vpc-associations":          {"MaxResults", "NextToken", "ServiceNetworkIdentifier", "VpcIdentifier"},
			"list-service-network-vpc-endpoint-associations": {"MaxResults", "NextToken", "ServiceNetworkIdentifier"},
			"list-service-networks":                          {"MaxResults", "NextToken"},
			"list-services":                                  {"MaxResults", "NextToken"},
			"list-tags-for-resource":                         {"ResourceArn"},
			"list-target-groups":                             {"MaxResults", "NextToken", "TargetGroupType", "VpcIdentifier"},
			"list-targets":                                   {"MaxResults", "NextToken", "TargetGroupIdentifier", "Targets"},
			"put-auth-policy":                                {"Policy", "ResourceIdentifier"},
			"put-resource-policy":                            {"Policy", "ResourceArn"},
			"register-targets":                               {"TargetGroupIdentifier", "Targets"},
			"start-domain-verification":                      {"ClientToken", "DomainName", "Tags"},
			"tag-resource":                                   {"ResourceArn", "Tags"},
			"untag-resource":                                 {"ResourceArn", "TagKeys"},
			"update-access-log-subscription":                 {"AccessLogSubscriptionIdentifier", "DestinationArn"},
			"update-listener":                                {"DefaultAction", "ListenerIdentifier", "ServiceIdentifier"},
			"update-resource-configuration":                  {"AllowAssociationToShareableServiceNetwork", "PortRanges", "ResourceConfigurationDefinition", "ResourceConfigurationIdentifier"},
			"update-resource-gateway":                        {"ResourceGatewayIdentifier", "SecurityGroupIds"},
			"update-rule":                                    {"Action", "ListenerIdentifier", "Match", "Priority", "RuleIdentifier", "ServiceIdentifier"},
			"update-service":                                 {"AuthType", "CertificateArn", "ServiceIdentifier"},
			"update-service-network":                         {"AuthType", "ServiceNetworkIdentifier"},
			"update-service-network-vpc-association":         {"SecurityGroupIds", "ServiceNetworkVpcAssociationIdentifier"},
			"update-target-group":                            {"HealthCheck", "TargetGroupIdentifier"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-update-rule":                              {"ListenerIdentifier": "*string", "Rules": "[]types.RuleUpdate", "ServiceIdentifier": "*string"},
			"create-access-log-subscription":                 {"ClientToken": "*string", "DestinationArn": "*string", "ResourceIdentifier": "*string", "ServiceNetworkLogType": "types.ServiceNetworkLogType", "Tags": "map[string]string"},
			"create-listener":                                {"ClientToken": "*string", "DefaultAction": "types.RuleAction", "Name": "*string", "Port": "*int32", "Protocol": "types.ListenerProtocol", "ServiceIdentifier": "*string", "Tags": "map[string]string"},
			"create-resource-configuration":                  {"AllowAssociationToShareableServiceNetwork": "*bool", "ClientToken": "*string", "CustomDomainName": "*string", "DomainVerificationIdentifier": "*string", "GroupDomain": "*string", "Name": "*string", "PortRanges": "[]string", "Protocol": "types.ProtocolType", "ResourceConfigurationDefinition": "types.ResourceConfigurationDefinition", "ResourceConfigurationGroupIdentifier": "*string", "ResourceGatewayIdentifier": "*string", "Tags": "map[string]string", "Type": "types.ResourceConfigurationType"},
			"create-resource-gateway":                        {"ClientToken": "*string", "IpAddressType": "types.ResourceGatewayIpAddressType", "Ipv4AddressesPerEni": "*int32", "Name": "*string", "SecurityGroupIds": "[]string", "SubnetIds": "[]string", "Tags": "map[string]string", "VpcIdentifier": "*string"},
			"create-rule":                                    {"Action": "types.RuleAction", "ClientToken": "*string", "ListenerIdentifier": "*string", "Match": "types.RuleMatch", "Name": "*string", "Priority": "*int32", "ServiceIdentifier": "*string", "Tags": "map[string]string"},
			"create-service":                                 {"AuthType": "types.AuthType", "CertificateArn": "*string", "ClientToken": "*string", "CustomDomainName": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-service-network":                         {"AuthType": "types.AuthType", "ClientToken": "*string", "Name": "*string", "SharingConfig": "*types.SharingConfig", "Tags": "map[string]string"},
			"create-service-network-resource-association":    {"ClientToken": "*string", "PrivateDnsEnabled": "*bool", "ResourceConfigurationIdentifier": "*string", "ServiceNetworkIdentifier": "*string", "Tags": "map[string]string"},
			"create-service-network-service-association":     {"ClientToken": "*string", "ServiceIdentifier": "*string", "ServiceNetworkIdentifier": "*string", "Tags": "map[string]string"},
			"create-service-network-vpc-association":         {"ClientToken": "*string", "DnsOptions": "*types.DnsOptions", "PrivateDnsEnabled": "*bool", "SecurityGroupIds": "[]string", "ServiceNetworkIdentifier": "*string", "Tags": "map[string]string", "VpcIdentifier": "*string"},
			"create-target-group":                            {"ClientToken": "*string", "Config": "*types.TargetGroupConfig", "Name": "*string", "Tags": "map[string]string", "Type": "types.TargetGroupType"},
			"delete-access-log-subscription":                 {"AccessLogSubscriptionIdentifier": "*string"},
			"delete-auth-policy":                             {"ResourceIdentifier": "*string"},
			"delete-domain-verification":                     {"DomainVerificationIdentifier": "*string"},
			"delete-listener":                                {"ListenerIdentifier": "*string", "ServiceIdentifier": "*string"},
			"delete-resource-configuration":                  {"ResourceConfigurationIdentifier": "*string"},
			"delete-resource-endpoint-association":           {"ResourceEndpointAssociationIdentifier": "*string"},
			"delete-resource-gateway":                        {"ResourceGatewayIdentifier": "*string"},
			"delete-resource-policy":                         {"ResourceArn": "*string"},
			"delete-rule":                                    {"ListenerIdentifier": "*string", "RuleIdentifier": "*string", "ServiceIdentifier": "*string"},
			"delete-service":                                 {"ServiceIdentifier": "*string"},
			"delete-service-network":                         {"ServiceNetworkIdentifier": "*string"},
			"delete-service-network-resource-association":    {"ServiceNetworkResourceAssociationIdentifier": "*string"},
			"delete-service-network-service-association":     {"ServiceNetworkServiceAssociationIdentifier": "*string"},
			"delete-service-network-vpc-association":         {"ServiceNetworkVpcAssociationIdentifier": "*string"},
			"delete-target-group":                            {"TargetGroupIdentifier": "*string"},
			"deregister-targets":                             {"TargetGroupIdentifier": "*string", "Targets": "[]types.Target"},
			"get-access-log-subscription":                    {"AccessLogSubscriptionIdentifier": "*string"},
			"get-auth-policy":                                {"ResourceIdentifier": "*string"},
			"get-domain-verification":                        {"DomainVerificationIdentifier": "*string"},
			"get-listener":                                   {"ListenerIdentifier": "*string", "ServiceIdentifier": "*string"},
			"get-resource-configuration":                     {"ResourceConfigurationIdentifier": "*string"},
			"get-resource-gateway":                           {"ResourceGatewayIdentifier": "*string"},
			"get-resource-policy":                            {"ResourceArn": "*string"},
			"get-rule":                                       {"ListenerIdentifier": "*string", "RuleIdentifier": "*string", "ServiceIdentifier": "*string"},
			"get-service":                                    {"ServiceIdentifier": "*string"},
			"get-service-network":                            {"ServiceNetworkIdentifier": "*string"},
			"get-service-network-resource-association":       {"ServiceNetworkResourceAssociationIdentifier": "*string"},
			"get-service-network-service-association":        {"ServiceNetworkServiceAssociationIdentifier": "*string"},
			"get-service-network-vpc-association":            {"ServiceNetworkVpcAssociationIdentifier": "*string"},
			"get-target-group":                               {"TargetGroupIdentifier": "*string"},
			"list-access-log-subscriptions":                  {"MaxResults": "*int32", "NextToken": "*string", "ResourceIdentifier": "*string"},
			"list-domain-verifications":                      {"MaxResults": "*int32", "NextToken": "*string"},
			"list-listeners":                                 {"MaxResults": "*int32", "NextToken": "*string", "ServiceIdentifier": "*string"},
			"list-resource-configurations":                   {"DomainVerificationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "ResourceConfigurationGroupIdentifier": "*string", "ResourceGatewayIdentifier": "*string"},
			"list-resource-endpoint-associations":            {"MaxResults": "*int32", "NextToken": "*string", "ResourceConfigurationIdentifier": "*string", "ResourceEndpointAssociationIdentifier": "*string", "VpcEndpointId": "*string", "VpcEndpointOwner": "*string"},
			"list-resource-gateways":                         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-rules":                                     {"ListenerIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "ServiceIdentifier": "*string"},
			"list-service-network-resource-associations":     {"IncludeChildren": "*bool", "MaxResults": "*int32", "NextToken": "*string", "ResourceConfigurationIdentifier": "*string", "ServiceNetworkIdentifier": "*string"},
			"list-service-network-service-associations":      {"MaxResults": "*int32", "NextToken": "*string", "ServiceIdentifier": "*string", "ServiceNetworkIdentifier": "*string"},
			"list-service-network-vpc-associations":          {"MaxResults": "*int32", "NextToken": "*string", "ServiceNetworkIdentifier": "*string", "VpcIdentifier": "*string"},
			"list-service-network-vpc-endpoint-associations": {"MaxResults": "*int32", "NextToken": "*string", "ServiceNetworkIdentifier": "*string"},
			"list-service-networks":                          {"MaxResults": "*int32", "NextToken": "*string"},
			"list-services":                                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                         {"ResourceArn": "*string"},
			"list-target-groups":                             {"MaxResults": "*int32", "NextToken": "*string", "TargetGroupType": "types.TargetGroupType", "VpcIdentifier": "*string"},
			"list-targets":                                   {"MaxResults": "*int32", "NextToken": "*string", "TargetGroupIdentifier": "*string", "Targets": "[]types.Target"},
			"put-auth-policy":                                {"Policy": "*string", "ResourceIdentifier": "*string"},
			"put-resource-policy":                            {"Policy": "*string", "ResourceArn": "*string"},
			"register-targets":                               {"TargetGroupIdentifier": "*string", "Targets": "[]types.Target"},
			"start-domain-verification":                      {"ClientToken": "*string", "DomainName": "*string", "Tags": "map[string]string"},
			"tag-resource":                                   {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                                 {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-access-log-subscription":                 {"AccessLogSubscriptionIdentifier": "*string", "DestinationArn": "*string"},
			"update-listener":                                {"DefaultAction": "types.RuleAction", "ListenerIdentifier": "*string", "ServiceIdentifier": "*string"},
			"update-resource-configuration":                  {"AllowAssociationToShareableServiceNetwork": "*bool", "PortRanges": "[]string", "ResourceConfigurationDefinition": "types.ResourceConfigurationDefinition", "ResourceConfigurationIdentifier": "*string"},
			"update-resource-gateway":                        {"ResourceGatewayIdentifier": "*string", "SecurityGroupIds": "[]string"},
			"update-rule":                                    {"Action": "types.RuleAction", "ListenerIdentifier": "*string", "Match": "types.RuleMatch", "Priority": "*int32", "RuleIdentifier": "*string", "ServiceIdentifier": "*string"},
			"update-service":                                 {"AuthType": "types.AuthType", "CertificateArn": "*string", "ServiceIdentifier": "*string"},
			"update-service-network":                         {"AuthType": "types.AuthType", "ServiceNetworkIdentifier": "*string"},
			"update-service-network-vpc-association":         {"SecurityGroupIds": "[]string", "ServiceNetworkVpcAssociationIdentifier": "*string"},
			"update-target-group":                            {"HealthCheck": "*types.HealthCheckConfig", "TargetGroupIdentifier": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-update-rule":                              {"ListenerIdentifier", "Rules", "ServiceIdentifier"},
			"create-access-log-subscription":                 {"DestinationArn", "ResourceIdentifier"},
			"create-listener":                                {"DefaultAction", "Name", "Protocol", "ServiceIdentifier"},
			"create-resource-configuration":                  {"Name", "Type"},
			"create-resource-gateway":                        {"Name"},
			"create-rule":                                    {"Action", "ListenerIdentifier", "Match", "Name", "Priority", "ServiceIdentifier"},
			"create-service":                                 {"Name"},
			"create-service-network":                         {"Name"},
			"create-service-network-resource-association":    {"ResourceConfigurationIdentifier", "ServiceNetworkIdentifier"},
			"create-service-network-service-association":     {"ServiceIdentifier", "ServiceNetworkIdentifier"},
			"create-service-network-vpc-association":         {"ServiceNetworkIdentifier", "VpcIdentifier"},
			"create-target-group":                            {"Name", "Type"},
			"delete-access-log-subscription":                 {"AccessLogSubscriptionIdentifier"},
			"delete-auth-policy":                             {"ResourceIdentifier"},
			"delete-domain-verification":                     {"DomainVerificationIdentifier"},
			"delete-listener":                                {"ListenerIdentifier", "ServiceIdentifier"},
			"delete-resource-configuration":                  {"ResourceConfigurationIdentifier"},
			"delete-resource-endpoint-association":           {"ResourceEndpointAssociationIdentifier"},
			"delete-resource-gateway":                        {"ResourceGatewayIdentifier"},
			"delete-resource-policy":                         {"ResourceArn"},
			"delete-rule":                                    {"ListenerIdentifier", "RuleIdentifier", "ServiceIdentifier"},
			"delete-service":                                 {"ServiceIdentifier"},
			"delete-service-network":                         {"ServiceNetworkIdentifier"},
			"delete-service-network-resource-association":    {"ServiceNetworkResourceAssociationIdentifier"},
			"delete-service-network-service-association":     {"ServiceNetworkServiceAssociationIdentifier"},
			"delete-service-network-vpc-association":         {"ServiceNetworkVpcAssociationIdentifier"},
			"delete-target-group":                            {"TargetGroupIdentifier"},
			"deregister-targets":                             {"TargetGroupIdentifier", "Targets"},
			"get-access-log-subscription":                    {"AccessLogSubscriptionIdentifier"},
			"get-auth-policy":                                {"ResourceIdentifier"},
			"get-domain-verification":                        {"DomainVerificationIdentifier"},
			"get-listener":                                   {"ListenerIdentifier", "ServiceIdentifier"},
			"get-resource-configuration":                     {"ResourceConfigurationIdentifier"},
			"get-resource-gateway":                           {"ResourceGatewayIdentifier"},
			"get-resource-policy":                            {"ResourceArn"},
			"get-rule":                                       {"ListenerIdentifier", "RuleIdentifier", "ServiceIdentifier"},
			"get-service":                                    {"ServiceIdentifier"},
			"get-service-network":                            {"ServiceNetworkIdentifier"},
			"get-service-network-resource-association":       {"ServiceNetworkResourceAssociationIdentifier"},
			"get-service-network-service-association":        {"ServiceNetworkServiceAssociationIdentifier"},
			"get-service-network-vpc-association":            {"ServiceNetworkVpcAssociationIdentifier"},
			"get-target-group":                               {"TargetGroupIdentifier"},
			"list-access-log-subscriptions":                  {"ResourceIdentifier"},
			"list-domain-verifications":                      {},
			"list-listeners":                                 {"ServiceIdentifier"},
			"list-resource-configurations":                   {},
			"list-resource-endpoint-associations":            {"ResourceConfigurationIdentifier"},
			"list-resource-gateways":                         {},
			"list-rules":                                     {"ListenerIdentifier", "ServiceIdentifier"},
			"list-service-network-resource-associations":     {},
			"list-service-network-service-associations":      {},
			"list-service-network-vpc-associations":          {},
			"list-service-network-vpc-endpoint-associations": {"ServiceNetworkIdentifier"},
			"list-service-networks":                          {},
			"list-services":                                  {},
			"list-tags-for-resource":                         {"ResourceArn"},
			"list-target-groups":                             {},
			"list-targets":                                   {"TargetGroupIdentifier"},
			"put-auth-policy":                                {"Policy", "ResourceIdentifier"},
			"put-resource-policy":                            {"Policy", "ResourceArn"},
			"register-targets":                               {"TargetGroupIdentifier", "Targets"},
			"start-domain-verification":                      {"DomainName"},
			"tag-resource":                                   {"ResourceArn", "Tags"},
			"untag-resource":                                 {"ResourceArn", "TagKeys"},
			"update-access-log-subscription":                 {"AccessLogSubscriptionIdentifier", "DestinationArn"},
			"update-listener":                                {"DefaultAction", "ListenerIdentifier", "ServiceIdentifier"},
			"update-resource-configuration":                  {"ResourceConfigurationIdentifier"},
			"update-resource-gateway":                        {"ResourceGatewayIdentifier"},
			"update-rule":                                    {"ListenerIdentifier", "RuleIdentifier", "ServiceIdentifier"},
			"update-service":                                 {"ServiceIdentifier"},
			"update-service-network":                         {"AuthType", "ServiceNetworkIdentifier"},
			"update-service-network-vpc-association":         {"SecurityGroupIds", "ServiceNetworkVpcAssociationIdentifier"},
			"update-target-group":                            {"HealthCheck", "TargetGroupIdentifier"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("vpclattice", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
