package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/bcmpricingcalculator/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-create-bill-scenario-commitment-modification", "batch-create-bill-scenario-usage-modification", "batch-create-workload-estimate-usage", "batch-delete-bill-scenario-commitment-modification", "batch-delete-bill-scenario-usage-modification", "batch-delete-workload-estimate-usage", "batch-update-bill-scenario-commitment-modification", "batch-update-bill-scenario-usage-modification", "batch-update-workload-estimate-usage", "create-bill-estimate", "create-bill-scenario", "create-workload-estimate", "delete-bill-estimate", "delete-bill-scenario", "delete-workload-estimate", "get-bill-estimate", "get-bill-scenario", "get-preferences", "get-workload-estimate", "list-bill-estimate-commitments", "list-bill-estimate-input-commitment-modifications", "list-bill-estimate-input-usage-modifications", "list-bill-estimate-line-items", "list-bill-estimates", "list-bill-scenario-commitment-modifications", "list-bill-scenario-usage-modifications", "list-bill-scenarios", "list-tags-for-resource", "list-workload-estimate-usage", "list-workload-estimates", "tag-resource", "untag-resource", "update-bill-estimate", "update-bill-scenario", "update-preferences", "update-workload-estimate"},
		OperationSet: map[string]bool{"batch-create-bill-scenario-commitment-modification": true, "batch-create-bill-scenario-usage-modification": true, "batch-create-workload-estimate-usage": true, "batch-delete-bill-scenario-commitment-modification": true, "batch-delete-bill-scenario-usage-modification": true, "batch-delete-workload-estimate-usage": true, "batch-update-bill-scenario-commitment-modification": true, "batch-update-bill-scenario-usage-modification": true, "batch-update-workload-estimate-usage": true, "create-bill-estimate": true, "create-bill-scenario": true, "create-workload-estimate": true, "delete-bill-estimate": true, "delete-bill-scenario": true, "delete-workload-estimate": true, "get-bill-estimate": true, "get-bill-scenario": true, "get-preferences": true, "get-workload-estimate": true, "list-bill-estimate-commitments": true, "list-bill-estimate-input-commitment-modifications": true, "list-bill-estimate-input-usage-modifications": true, "list-bill-estimate-line-items": true, "list-bill-estimates": true, "list-bill-scenario-commitment-modifications": true, "list-bill-scenario-usage-modifications": true, "list-bill-scenarios": true, "list-tags-for-resource": true, "list-workload-estimate-usage": true, "list-workload-estimates": true, "tag-resource": true, "untag-resource": true, "update-bill-estimate": true, "update-bill-scenario": true, "update-preferences": true, "update-workload-estimate": true},
		OperationInputs: map[string][]string{
			"batch-create-bill-scenario-commitment-modification": {"BillScenarioId", "ClientToken", "CommitmentModifications"},
			"batch-create-bill-scenario-usage-modification":      {"BillScenarioId", "ClientToken", "UsageModifications"},
			"batch-create-workload-estimate-usage":               {"ClientToken", "Usage", "WorkloadEstimateId"},
			"batch-delete-bill-scenario-commitment-modification": {"BillScenarioId", "Ids"},
			"batch-delete-bill-scenario-usage-modification":      {"BillScenarioId", "Ids"},
			"batch-delete-workload-estimate-usage":               {"Ids", "WorkloadEstimateId"},
			"batch-update-bill-scenario-commitment-modification": {"BillScenarioId", "CommitmentModifications"},
			"batch-update-bill-scenario-usage-modification":      {"BillScenarioId", "UsageModifications"},
			"batch-update-workload-estimate-usage":               {"Usage", "WorkloadEstimateId"},
			"create-bill-estimate":                               {"BillScenarioId", "ClientToken", "Name", "Tags"},
			"create-bill-scenario":                               {"ClientToken", "CostCategoryGroupSharingPreferenceArn", "GroupSharingPreference", "Name", "Tags"},
			"create-workload-estimate":                           {"ClientToken", "Name", "RateType", "Tags"},
			"delete-bill-estimate":                               {"Identifier"},
			"delete-bill-scenario":                               {"Identifier"},
			"delete-workload-estimate":                           {"Identifier"},
			"get-bill-estimate":                                  {"Identifier"},
			"get-bill-scenario":                                  {"Identifier"},
			"get-preferences":                                    {},
			"get-workload-estimate":                              {"Identifier"},
			"list-bill-estimate-commitments":                     {"BillEstimateId", "MaxResults", "NextToken"},
			"list-bill-estimate-input-commitment-modifications":  {"BillEstimateId", "MaxResults", "NextToken"},
			"list-bill-estimate-input-usage-modifications":       {"BillEstimateId", "Filters", "MaxResults", "NextToken"},
			"list-bill-estimate-line-items":                      {"BillEstimateId", "Filters", "MaxResults", "NextToken"},
			"list-bill-estimates":                                {"CreatedAtFilter", "ExpiresAtFilter", "Filters", "MaxResults", "NextToken"},
			"list-bill-scenario-commitment-modifications":        {"BillScenarioId", "MaxResults", "NextToken"},
			"list-bill-scenario-usage-modifications":             {"BillScenarioId", "Filters", "MaxResults", "NextToken"},
			"list-bill-scenarios":                                {"CreatedAtFilter", "ExpiresAtFilter", "Filters", "MaxResults", "NextToken"},
			"list-tags-for-resource":                             {"Arn"},
			"list-workload-estimate-usage":                       {"Filters", "MaxResults", "NextToken", "WorkloadEstimateId"},
			"list-workload-estimates":                            {"CreatedAtFilter", "ExpiresAtFilter", "Filters", "MaxResults", "NextToken"},
			"tag-resource":                                       {"Arn", "Tags"},
			"untag-resource":                                     {"Arn", "TagKeys"},
			"update-bill-estimate":                               {"ExpiresAt", "Identifier", "Name"},
			"update-bill-scenario":                               {"CostCategoryGroupSharingPreferenceArn", "ExpiresAt", "GroupSharingPreference", "Identifier", "Name"},
			"update-preferences":                                 {"ManagementAccountRateTypeSelections", "MemberAccountRateTypeSelections", "StandaloneAccountRateTypeSelections"},
			"update-workload-estimate":                           {"ExpiresAt", "Identifier", "Name"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-create-bill-scenario-commitment-modification": {"BillScenarioId": "*string", "ClientToken": "*string", "CommitmentModifications": "[]types.BatchCreateBillScenarioCommitmentModificationEntry"},
			"batch-create-bill-scenario-usage-modification":      {"BillScenarioId": "*string", "ClientToken": "*string", "UsageModifications": "[]types.BatchCreateBillScenarioUsageModificationEntry"},
			"batch-create-workload-estimate-usage":               {"ClientToken": "*string", "Usage": "[]types.BatchCreateWorkloadEstimateUsageEntry", "WorkloadEstimateId": "*string"},
			"batch-delete-bill-scenario-commitment-modification": {"BillScenarioId": "*string", "Ids": "[]string"},
			"batch-delete-bill-scenario-usage-modification":      {"BillScenarioId": "*string", "Ids": "[]string"},
			"batch-delete-workload-estimate-usage":               {"Ids": "[]string", "WorkloadEstimateId": "*string"},
			"batch-update-bill-scenario-commitment-modification": {"BillScenarioId": "*string", "CommitmentModifications": "[]types.BatchUpdateBillScenarioCommitmentModificationEntry"},
			"batch-update-bill-scenario-usage-modification":      {"BillScenarioId": "*string", "UsageModifications": "[]types.BatchUpdateBillScenarioUsageModificationEntry"},
			"batch-update-workload-estimate-usage":               {"Usage": "[]types.BatchUpdateWorkloadEstimateUsageEntry", "WorkloadEstimateId": "*string"},
			"create-bill-estimate":                               {"BillScenarioId": "*string", "ClientToken": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-bill-scenario":                               {"ClientToken": "*string", "CostCategoryGroupSharingPreferenceArn": "*string", "GroupSharingPreference": "types.GroupSharingPreferenceEnum", "Name": "*string", "Tags": "map[string]string"},
			"create-workload-estimate":                           {"ClientToken": "*string", "Name": "*string", "RateType": "types.WorkloadEstimateRateType", "Tags": "map[string]string"},
			"delete-bill-estimate":                               {"Identifier": "*string"},
			"delete-bill-scenario":                               {"Identifier": "*string"},
			"delete-workload-estimate":                           {"Identifier": "*string"},
			"get-bill-estimate":                                  {"Identifier": "*string"},
			"get-bill-scenario":                                  {"Identifier": "*string"},
			"get-preferences":                                    {},
			"get-workload-estimate":                              {"Identifier": "*string"},
			"list-bill-estimate-commitments":                     {"BillEstimateId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-bill-estimate-input-commitment-modifications":  {"BillEstimateId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-bill-estimate-input-usage-modifications":       {"BillEstimateId": "*string", "Filters": "[]types.ListUsageFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-bill-estimate-line-items":                      {"BillEstimateId": "*string", "Filters": "[]types.ListBillEstimateLineItemsFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-bill-estimates":                                {"CreatedAtFilter": "*types.FilterTimestamp", "ExpiresAtFilter": "*types.FilterTimestamp", "Filters": "[]types.ListBillEstimatesFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-bill-scenario-commitment-modifications":        {"BillScenarioId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-bill-scenario-usage-modifications":             {"BillScenarioId": "*string", "Filters": "[]types.ListUsageFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-bill-scenarios":                                {"CreatedAtFilter": "*types.FilterTimestamp", "ExpiresAtFilter": "*types.FilterTimestamp", "Filters": "[]types.ListBillScenariosFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                             {"Arn": "*string"},
			"list-workload-estimate-usage":                       {"Filters": "[]types.ListUsageFilter", "MaxResults": "*int32", "NextToken": "*string", "WorkloadEstimateId": "*string"},
			"list-workload-estimates":                            {"CreatedAtFilter": "*types.FilterTimestamp", "ExpiresAtFilter": "*types.FilterTimestamp", "Filters": "[]types.ListWorkloadEstimatesFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"tag-resource":                                       {"Arn": "*string", "Tags": "map[string]string"},
			"untag-resource":                                     {"Arn": "*string", "TagKeys": "[]string"},
			"update-bill-estimate":                               {"ExpiresAt": "*time.Time", "Identifier": "*string", "Name": "*string"},
			"update-bill-scenario":                               {"CostCategoryGroupSharingPreferenceArn": "*string", "ExpiresAt": "*time.Time", "GroupSharingPreference": "types.GroupSharingPreferenceEnum", "Identifier": "*string", "Name": "*string"},
			"update-preferences":                                 {"ManagementAccountRateTypeSelections": "[]types.RateType", "MemberAccountRateTypeSelections": "[]types.RateType", "StandaloneAccountRateTypeSelections": "[]types.RateType"},
			"update-workload-estimate":                           {"ExpiresAt": "*time.Time", "Identifier": "*string", "Name": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-create-bill-scenario-commitment-modification": {"BillScenarioId", "CommitmentModifications"},
			"batch-create-bill-scenario-usage-modification":      {"BillScenarioId", "UsageModifications"},
			"batch-create-workload-estimate-usage":               {"Usage", "WorkloadEstimateId"},
			"batch-delete-bill-scenario-commitment-modification": {"BillScenarioId", "Ids"},
			"batch-delete-bill-scenario-usage-modification":      {"BillScenarioId", "Ids"},
			"batch-delete-workload-estimate-usage":               {"Ids", "WorkloadEstimateId"},
			"batch-update-bill-scenario-commitment-modification": {"BillScenarioId", "CommitmentModifications"},
			"batch-update-bill-scenario-usage-modification":      {"BillScenarioId", "UsageModifications"},
			"batch-update-workload-estimate-usage":               {"Usage", "WorkloadEstimateId"},
			"create-bill-estimate":                               {"BillScenarioId", "Name"},
			"create-bill-scenario":                               {"Name"},
			"create-workload-estimate":                           {"Name"},
			"delete-bill-estimate":                               {"Identifier"},
			"delete-bill-scenario":                               {"Identifier"},
			"delete-workload-estimate":                           {"Identifier"},
			"get-bill-estimate":                                  {"Identifier"},
			"get-bill-scenario":                                  {"Identifier"},
			"get-preferences":                                    {},
			"get-workload-estimate":                              {"Identifier"},
			"list-bill-estimate-commitments":                     {"BillEstimateId"},
			"list-bill-estimate-input-commitment-modifications":  {"BillEstimateId"},
			"list-bill-estimate-input-usage-modifications":       {"BillEstimateId"},
			"list-bill-estimate-line-items":                      {"BillEstimateId"},
			"list-bill-estimates":                                {},
			"list-bill-scenario-commitment-modifications":        {"BillScenarioId"},
			"list-bill-scenario-usage-modifications":             {"BillScenarioId"},
			"list-bill-scenarios":                                {},
			"list-tags-for-resource":                             {"Arn"},
			"list-workload-estimate-usage":                       {"WorkloadEstimateId"},
			"list-workload-estimates":                            {},
			"tag-resource":                                       {"Arn", "Tags"},
			"untag-resource":                                     {"Arn", "TagKeys"},
			"update-bill-estimate":                               {"Identifier"},
			"update-bill-scenario":                               {"Identifier"},
			"update-preferences":                                 {},
			"update-workload-estimate":                           {"Identifier"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("bcmpricingcalculator", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
