package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/athena/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-get-named-query", "batch-get-prepared-statement", "batch-get-query-execution", "cancel-capacity-reservation", "create-capacity-reservation", "create-data-catalog", "create-named-query", "create-notebook", "create-prepared-statement", "create-presigned-notebook-url", "create-work-group", "delete-capacity-reservation", "delete-data-catalog", "delete-named-query", "delete-notebook", "delete-prepared-statement", "delete-work-group", "export-notebook", "get-calculation-execution", "get-calculation-execution-code", "get-calculation-execution-status", "get-capacity-assignment-configuration", "get-capacity-reservation", "get-data-catalog", "get-database", "get-named-query", "get-notebook-metadata", "get-prepared-statement", "get-query-execution", "get-query-results", "get-query-runtime-statistics", "get-resource-dashboard", "get-session", "get-session-endpoint", "get-session-status", "get-table-metadata", "get-work-group", "import-notebook", "list-application-dpu-sizes", "list-calculation-executions", "list-capacity-reservations", "list-data-catalogs", "list-databases", "list-engine-versions", "list-executors", "list-named-queries", "list-notebook-metadata", "list-notebook-sessions", "list-prepared-statements", "list-query-executions", "list-sessions", "list-table-metadata", "list-tags-for-resource", "list-work-groups", "put-capacity-assignment-configuration", "start-calculation-execution", "start-query-execution", "start-session", "stop-calculation-execution", "stop-query-execution", "tag-resource", "terminate-session", "untag-resource", "update-capacity-reservation", "update-data-catalog", "update-named-query", "update-notebook", "update-notebook-metadata", "update-prepared-statement", "update-work-group"},
		OperationSet: map[string]bool{"batch-get-named-query": true, "batch-get-prepared-statement": true, "batch-get-query-execution": true, "cancel-capacity-reservation": true, "create-capacity-reservation": true, "create-data-catalog": true, "create-named-query": true, "create-notebook": true, "create-prepared-statement": true, "create-presigned-notebook-url": true, "create-work-group": true, "delete-capacity-reservation": true, "delete-data-catalog": true, "delete-named-query": true, "delete-notebook": true, "delete-prepared-statement": true, "delete-work-group": true, "export-notebook": true, "get-calculation-execution": true, "get-calculation-execution-code": true, "get-calculation-execution-status": true, "get-capacity-assignment-configuration": true, "get-capacity-reservation": true, "get-data-catalog": true, "get-database": true, "get-named-query": true, "get-notebook-metadata": true, "get-prepared-statement": true, "get-query-execution": true, "get-query-results": true, "get-query-runtime-statistics": true, "get-resource-dashboard": true, "get-session": true, "get-session-endpoint": true, "get-session-status": true, "get-table-metadata": true, "get-work-group": true, "import-notebook": true, "list-application-dpu-sizes": true, "list-calculation-executions": true, "list-capacity-reservations": true, "list-data-catalogs": true, "list-databases": true, "list-engine-versions": true, "list-executors": true, "list-named-queries": true, "list-notebook-metadata": true, "list-notebook-sessions": true, "list-prepared-statements": true, "list-query-executions": true, "list-sessions": true, "list-table-metadata": true, "list-tags-for-resource": true, "list-work-groups": true, "put-capacity-assignment-configuration": true, "start-calculation-execution": true, "start-query-execution": true, "start-session": true, "stop-calculation-execution": true, "stop-query-execution": true, "tag-resource": true, "terminate-session": true, "untag-resource": true, "update-capacity-reservation": true, "update-data-catalog": true, "update-named-query": true, "update-notebook": true, "update-notebook-metadata": true, "update-prepared-statement": true, "update-work-group": true},
		OperationInputs: map[string][]string{
			"batch-get-named-query":                 {"NamedQueryIds"},
			"batch-get-prepared-statement":          {"PreparedStatementNames", "WorkGroup"},
			"batch-get-query-execution":             {"QueryExecutionIds"},
			"cancel-capacity-reservation":           {"Name"},
			"create-capacity-reservation":           {"Name", "Tags", "TargetDpus"},
			"create-data-catalog":                   {"Description", "Name", "Parameters", "Tags", "Type"},
			"create-named-query":                    {"ClientRequestToken", "Database", "Description", "Name", "QueryString", "WorkGroup"},
			"create-notebook":                       {"ClientRequestToken", "Name", "WorkGroup"},
			"create-prepared-statement":             {"Description", "QueryStatement", "StatementName", "WorkGroup"},
			"create-presigned-notebook-url":         {"SessionId"},
			"create-work-group":                     {"Configuration", "Description", "Name", "Tags"},
			"delete-capacity-reservation":           {"Name"},
			"delete-data-catalog":                   {"DeleteCatalogOnly", "Name"},
			"delete-named-query":                    {"NamedQueryId"},
			"delete-notebook":                       {"NotebookId"},
			"delete-prepared-statement":             {"StatementName", "WorkGroup"},
			"delete-work-group":                     {"RecursiveDeleteOption", "WorkGroup"},
			"export-notebook":                       {"NotebookId"},
			"get-calculation-execution":             {"CalculationExecutionId"},
			"get-calculation-execution-code":        {"CalculationExecutionId"},
			"get-calculation-execution-status":      {"CalculationExecutionId"},
			"get-capacity-assignment-configuration": {"CapacityReservationName"},
			"get-capacity-reservation":              {"Name"},
			"get-data-catalog":                      {"Name", "WorkGroup"},
			"get-database":                          {"CatalogName", "DatabaseName", "WorkGroup"},
			"get-named-query":                       {"NamedQueryId"},
			"get-notebook-metadata":                 {"NotebookId"},
			"get-prepared-statement":                {"StatementName", "WorkGroup"},
			"get-query-execution":                   {"QueryExecutionId"},
			"get-query-results":                     {"MaxResults", "NextToken", "QueryExecutionId", "QueryResultType"},
			"get-query-runtime-statistics":          {"QueryExecutionId"},
			"get-resource-dashboard":                {"ResourceARN"},
			"get-session":                           {"SessionId"},
			"get-session-endpoint":                  {"SessionId"},
			"get-session-status":                    {"SessionId"},
			"get-table-metadata":                    {"CatalogName", "DatabaseName", "TableName", "WorkGroup"},
			"get-work-group":                        {"WorkGroup"},
			"import-notebook":                       {"ClientRequestToken", "Name", "NotebookS3LocationUri", "Payload", "Type", "WorkGroup"},
			"list-application-dpu-sizes":            {"MaxResults", "NextToken"},
			"list-calculation-executions":           {"MaxResults", "NextToken", "SessionId", "StateFilter"},
			"list-capacity-reservations":            {"MaxResults", "NextToken"},
			"list-data-catalogs":                    {"MaxResults", "NextToken", "WorkGroup"},
			"list-databases":                        {"CatalogName", "MaxResults", "NextToken", "WorkGroup"},
			"list-engine-versions":                  {"MaxResults", "NextToken"},
			"list-executors":                        {"ExecutorStateFilter", "MaxResults", "NextToken", "SessionId"},
			"list-named-queries":                    {"MaxResults", "NextToken", "WorkGroup"},
			"list-notebook-metadata":                {"Filters", "MaxResults", "NextToken", "WorkGroup"},
			"list-notebook-sessions":                {"MaxResults", "NextToken", "NotebookId"},
			"list-prepared-statements":              {"MaxResults", "NextToken", "WorkGroup"},
			"list-query-executions":                 {"MaxResults", "NextToken", "WorkGroup"},
			"list-sessions":                         {"MaxResults", "NextToken", "StateFilter", "WorkGroup"},
			"list-table-metadata":                   {"CatalogName", "DatabaseName", "Expression", "MaxResults", "NextToken", "WorkGroup"},
			"list-tags-for-resource":                {"MaxResults", "NextToken", "ResourceARN"},
			"list-work-groups":                      {"MaxResults", "NextToken"},
			"put-capacity-assignment-configuration": {"CapacityAssignments", "CapacityReservationName"},
			"start-calculation-execution":           {"CalculationConfiguration", "ClientRequestToken", "CodeBlock", "Description", "SessionId"},
			"start-query-execution":                 {"ClientRequestToken", "EngineConfiguration", "ExecutionParameters", "QueryExecutionContext", "QueryString", "ResultConfiguration", "ResultReuseConfiguration", "WorkGroup"},
			"start-session":                         {"ClientRequestToken", "CopyWorkGroupTags", "Description", "EngineConfiguration", "ExecutionRole", "MonitoringConfiguration", "NotebookVersion", "SessionIdleTimeoutInMinutes", "Tags", "WorkGroup"},
			"stop-calculation-execution":            {"CalculationExecutionId"},
			"stop-query-execution":                  {"QueryExecutionId"},
			"tag-resource":                          {"ResourceARN", "Tags"},
			"terminate-session":                     {"SessionId"},
			"untag-resource":                        {"ResourceARN", "TagKeys"},
			"update-capacity-reservation":           {"Name", "TargetDpus"},
			"update-data-catalog":                   {"Description", "Name", "Parameters", "Type"},
			"update-named-query":                    {"Description", "Name", "NamedQueryId", "QueryString"},
			"update-notebook":                       {"ClientRequestToken", "NotebookId", "Payload", "SessionId", "Type"},
			"update-notebook-metadata":              {"ClientRequestToken", "Name", "NotebookId"},
			"update-prepared-statement":             {"Description", "QueryStatement", "StatementName", "WorkGroup"},
			"update-work-group":                     {"ConfigurationUpdates", "Description", "State", "WorkGroup"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-get-named-query":                 {"NamedQueryIds": "[]string"},
			"batch-get-prepared-statement":          {"PreparedStatementNames": "[]string", "WorkGroup": "*string"},
			"batch-get-query-execution":             {"QueryExecutionIds": "[]string"},
			"cancel-capacity-reservation":           {"Name": "*string"},
			"create-capacity-reservation":           {"Name": "*string", "Tags": "[]types.Tag", "TargetDpus": "*int32"},
			"create-data-catalog":                   {"Description": "*string", "Name": "*string", "Parameters": "map[string]string", "Tags": "[]types.Tag", "Type": "types.DataCatalogType"},
			"create-named-query":                    {"ClientRequestToken": "*string", "Database": "*string", "Description": "*string", "Name": "*string", "QueryString": "*string", "WorkGroup": "*string"},
			"create-notebook":                       {"ClientRequestToken": "*string", "Name": "*string", "WorkGroup": "*string"},
			"create-prepared-statement":             {"Description": "*string", "QueryStatement": "*string", "StatementName": "*string", "WorkGroup": "*string"},
			"create-presigned-notebook-url":         {"SessionId": "*string"},
			"create-work-group":                     {"Configuration": "*types.WorkGroupConfiguration", "Description": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"delete-capacity-reservation":           {"Name": "*string"},
			"delete-data-catalog":                   {"DeleteCatalogOnly": "bool", "Name": "*string"},
			"delete-named-query":                    {"NamedQueryId": "*string"},
			"delete-notebook":                       {"NotebookId": "*string"},
			"delete-prepared-statement":             {"StatementName": "*string", "WorkGroup": "*string"},
			"delete-work-group":                     {"RecursiveDeleteOption": "*bool", "WorkGroup": "*string"},
			"export-notebook":                       {"NotebookId": "*string"},
			"get-calculation-execution":             {"CalculationExecutionId": "*string"},
			"get-calculation-execution-code":        {"CalculationExecutionId": "*string"},
			"get-calculation-execution-status":      {"CalculationExecutionId": "*string"},
			"get-capacity-assignment-configuration": {"CapacityReservationName": "*string"},
			"get-capacity-reservation":              {"Name": "*string"},
			"get-data-catalog":                      {"Name": "*string", "WorkGroup": "*string"},
			"get-database":                          {"CatalogName": "*string", "DatabaseName": "*string", "WorkGroup": "*string"},
			"get-named-query":                       {"NamedQueryId": "*string"},
			"get-notebook-metadata":                 {"NotebookId": "*string"},
			"get-prepared-statement":                {"StatementName": "*string", "WorkGroup": "*string"},
			"get-query-execution":                   {"QueryExecutionId": "*string"},
			"get-query-results":                     {"MaxResults": "*int32", "NextToken": "*string", "QueryExecutionId": "*string", "QueryResultType": "types.QueryResultType"},
			"get-query-runtime-statistics":          {"QueryExecutionId": "*string"},
			"get-resource-dashboard":                {"ResourceARN": "*string"},
			"get-session":                           {"SessionId": "*string"},
			"get-session-endpoint":                  {"SessionId": "*string"},
			"get-session-status":                    {"SessionId": "*string"},
			"get-table-metadata":                    {"CatalogName": "*string", "DatabaseName": "*string", "TableName": "*string", "WorkGroup": "*string"},
			"get-work-group":                        {"WorkGroup": "*string"},
			"import-notebook":                       {"ClientRequestToken": "*string", "Name": "*string", "NotebookS3LocationUri": "*string", "Payload": "*string", "Type": "types.NotebookType", "WorkGroup": "*string"},
			"list-application-dpu-sizes":            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-calculation-executions":           {"MaxResults": "*int32", "NextToken": "*string", "SessionId": "*string", "StateFilter": "types.CalculationExecutionState"},
			"list-capacity-reservations":            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-data-catalogs":                    {"MaxResults": "*int32", "NextToken": "*string", "WorkGroup": "*string"},
			"list-databases":                        {"CatalogName": "*string", "MaxResults": "*int32", "NextToken": "*string", "WorkGroup": "*string"},
			"list-engine-versions":                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-executors":                        {"ExecutorStateFilter": "types.ExecutorState", "MaxResults": "*int32", "NextToken": "*string", "SessionId": "*string"},
			"list-named-queries":                    {"MaxResults": "*int32", "NextToken": "*string", "WorkGroup": "*string"},
			"list-notebook-metadata":                {"Filters": "*types.FilterDefinition", "MaxResults": "*int32", "NextToken": "*string", "WorkGroup": "*string"},
			"list-notebook-sessions":                {"MaxResults": "*int32", "NextToken": "*string", "NotebookId": "*string"},
			"list-prepared-statements":              {"MaxResults": "*int32", "NextToken": "*string", "WorkGroup": "*string"},
			"list-query-executions":                 {"MaxResults": "*int32", "NextToken": "*string", "WorkGroup": "*string"},
			"list-sessions":                         {"MaxResults": "*int32", "NextToken": "*string", "StateFilter": "types.SessionState", "WorkGroup": "*string"},
			"list-table-metadata":                   {"CatalogName": "*string", "DatabaseName": "*string", "Expression": "*string", "MaxResults": "*int32", "NextToken": "*string", "WorkGroup": "*string"},
			"list-tags-for-resource":                {"MaxResults": "*int32", "NextToken": "*string", "ResourceARN": "*string"},
			"list-work-groups":                      {"MaxResults": "*int32", "NextToken": "*string"},
			"put-capacity-assignment-configuration": {"CapacityAssignments": "[]types.CapacityAssignment", "CapacityReservationName": "*string"},
			"start-calculation-execution":           {"CalculationConfiguration": "*types.CalculationConfiguration", "ClientRequestToken": "*string", "CodeBlock": "*string", "Description": "*string", "SessionId": "*string"},
			"start-query-execution":                 {"ClientRequestToken": "*string", "EngineConfiguration": "*types.EngineConfiguration", "ExecutionParameters": "[]string", "QueryExecutionContext": "*types.QueryExecutionContext", "QueryString": "*string", "ResultConfiguration": "*types.ResultConfiguration", "ResultReuseConfiguration": "*types.ResultReuseConfiguration", "WorkGroup": "*string"},
			"start-session":                         {"ClientRequestToken": "*string", "CopyWorkGroupTags": "*bool", "Description": "*string", "EngineConfiguration": "*types.EngineConfiguration", "ExecutionRole": "*string", "MonitoringConfiguration": "*types.MonitoringConfiguration", "NotebookVersion": "*string", "SessionIdleTimeoutInMinutes": "*int32", "Tags": "[]types.Tag", "WorkGroup": "*string"},
			"stop-calculation-execution":            {"CalculationExecutionId": "*string"},
			"stop-query-execution":                  {"QueryExecutionId": "*string"},
			"tag-resource":                          {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"terminate-session":                     {"SessionId": "*string"},
			"untag-resource":                        {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-capacity-reservation":           {"Name": "*string", "TargetDpus": "*int32"},
			"update-data-catalog":                   {"Description": "*string", "Name": "*string", "Parameters": "map[string]string", "Type": "types.DataCatalogType"},
			"update-named-query":                    {"Description": "*string", "Name": "*string", "NamedQueryId": "*string", "QueryString": "*string"},
			"update-notebook":                       {"ClientRequestToken": "*string", "NotebookId": "*string", "Payload": "*string", "SessionId": "*string", "Type": "types.NotebookType"},
			"update-notebook-metadata":              {"ClientRequestToken": "*string", "Name": "*string", "NotebookId": "*string"},
			"update-prepared-statement":             {"Description": "*string", "QueryStatement": "*string", "StatementName": "*string", "WorkGroup": "*string"},
			"update-work-group":                     {"ConfigurationUpdates": "*types.WorkGroupConfigurationUpdates", "Description": "*string", "State": "types.WorkGroupState", "WorkGroup": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-get-named-query":                 {"NamedQueryIds"},
			"batch-get-prepared-statement":          {"PreparedStatementNames", "WorkGroup"},
			"batch-get-query-execution":             {"QueryExecutionIds"},
			"cancel-capacity-reservation":           {"Name"},
			"create-capacity-reservation":           {"Name", "TargetDpus"},
			"create-data-catalog":                   {"Name", "Type"},
			"create-named-query":                    {"Database", "Name", "QueryString"},
			"create-notebook":                       {"Name", "WorkGroup"},
			"create-prepared-statement":             {"QueryStatement", "StatementName", "WorkGroup"},
			"create-presigned-notebook-url":         {"SessionId"},
			"create-work-group":                     {"Name"},
			"delete-capacity-reservation":           {"Name"},
			"delete-data-catalog":                   {"Name"},
			"delete-named-query":                    {"NamedQueryId"},
			"delete-notebook":                       {"NotebookId"},
			"delete-prepared-statement":             {"StatementName", "WorkGroup"},
			"delete-work-group":                     {"WorkGroup"},
			"export-notebook":                       {"NotebookId"},
			"get-calculation-execution":             {"CalculationExecutionId"},
			"get-calculation-execution-code":        {"CalculationExecutionId"},
			"get-calculation-execution-status":      {"CalculationExecutionId"},
			"get-capacity-assignment-configuration": {"CapacityReservationName"},
			"get-capacity-reservation":              {"Name"},
			"get-data-catalog":                      {"Name"},
			"get-database":                          {"CatalogName", "DatabaseName"},
			"get-named-query":                       {"NamedQueryId"},
			"get-notebook-metadata":                 {"NotebookId"},
			"get-prepared-statement":                {"StatementName", "WorkGroup"},
			"get-query-execution":                   {"QueryExecutionId"},
			"get-query-results":                     {"QueryExecutionId"},
			"get-query-runtime-statistics":          {"QueryExecutionId"},
			"get-resource-dashboard":                {"ResourceARN"},
			"get-session":                           {"SessionId"},
			"get-session-endpoint":                  {"SessionId"},
			"get-session-status":                    {"SessionId"},
			"get-table-metadata":                    {"CatalogName", "DatabaseName", "TableName"},
			"get-work-group":                        {"WorkGroup"},
			"import-notebook":                       {"Name", "Type", "WorkGroup"},
			"list-application-dpu-sizes":            {},
			"list-calculation-executions":           {"SessionId"},
			"list-capacity-reservations":            {},
			"list-data-catalogs":                    {},
			"list-databases":                        {"CatalogName"},
			"list-engine-versions":                  {},
			"list-executors":                        {"SessionId"},
			"list-named-queries":                    {},
			"list-notebook-metadata":                {"WorkGroup"},
			"list-notebook-sessions":                {"NotebookId"},
			"list-prepared-statements":              {"WorkGroup"},
			"list-query-executions":                 {},
			"list-sessions":                         {"WorkGroup"},
			"list-table-metadata":                   {"CatalogName", "DatabaseName"},
			"list-tags-for-resource":                {"ResourceARN"},
			"list-work-groups":                      {},
			"put-capacity-assignment-configuration": {"CapacityAssignments", "CapacityReservationName"},
			"start-calculation-execution":           {"SessionId"},
			"start-query-execution":                 {"QueryString"},
			"start-session":                         {"EngineConfiguration", "WorkGroup"},
			"stop-calculation-execution":            {"CalculationExecutionId"},
			"stop-query-execution":                  {"QueryExecutionId"},
			"tag-resource":                          {"ResourceARN", "Tags"},
			"terminate-session":                     {"SessionId"},
			"untag-resource":                        {"ResourceARN", "TagKeys"},
			"update-capacity-reservation":           {"Name", "TargetDpus"},
			"update-data-catalog":                   {"Name", "Type"},
			"update-named-query":                    {"Name", "NamedQueryId", "QueryString"},
			"update-notebook":                       {"NotebookId", "Payload", "Type"},
			"update-notebook-metadata":              {"Name", "NotebookId"},
			"update-prepared-statement":             {"QueryStatement", "StatementName", "WorkGroup"},
			"update-work-group":                     {"WorkGroup"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("athena", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
