package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/kinesisvideo/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-signaling-channel", "create-stream", "delete-edge-configuration", "delete-signaling-channel", "delete-stream", "describe-edge-configuration", "describe-image-generation-configuration", "describe-mapped-resource-configuration", "describe-media-storage-configuration", "describe-notification-configuration", "describe-signaling-channel", "describe-stream", "describe-stream-storage-configuration", "get-data-endpoint", "get-signaling-channel-endpoint", "list-edge-agent-configurations", "list-signaling-channels", "list-streams", "list-tags-for-resource", "list-tags-for-stream", "start-edge-configuration-update", "tag-resource", "tag-stream", "untag-resource", "untag-stream", "update-data-retention", "update-image-generation-configuration", "update-media-storage-configuration", "update-notification-configuration", "update-signaling-channel", "update-stream", "update-stream-storage-configuration"},
		OperationSet: map[string]bool{"create-signaling-channel": true, "create-stream": true, "delete-edge-configuration": true, "delete-signaling-channel": true, "delete-stream": true, "describe-edge-configuration": true, "describe-image-generation-configuration": true, "describe-mapped-resource-configuration": true, "describe-media-storage-configuration": true, "describe-notification-configuration": true, "describe-signaling-channel": true, "describe-stream": true, "describe-stream-storage-configuration": true, "get-data-endpoint": true, "get-signaling-channel-endpoint": true, "list-edge-agent-configurations": true, "list-signaling-channels": true, "list-streams": true, "list-tags-for-resource": true, "list-tags-for-stream": true, "start-edge-configuration-update": true, "tag-resource": true, "tag-stream": true, "untag-resource": true, "untag-stream": true, "update-data-retention": true, "update-image-generation-configuration": true, "update-media-storage-configuration": true, "update-notification-configuration": true, "update-signaling-channel": true, "update-stream": true, "update-stream-storage-configuration": true},
		OperationInputs: map[string][]string{
			"create-signaling-channel":                {"ChannelName", "ChannelType", "SingleMasterConfiguration", "Tags"},
			"create-stream":                           {"DataRetentionInHours", "DeviceName", "KmsKeyId", "MediaType", "StreamName", "StreamStorageConfiguration", "Tags"},
			"delete-edge-configuration":               {"StreamARN", "StreamName"},
			"delete-signaling-channel":                {"ChannelARN", "CurrentVersion"},
			"delete-stream":                           {"CurrentVersion", "StreamARN"},
			"describe-edge-configuration":             {"StreamARN", "StreamName"},
			"describe-image-generation-configuration": {"StreamARN", "StreamName"},
			"describe-mapped-resource-configuration":  {"MaxResults", "NextToken", "StreamARN", "StreamName"},
			"describe-media-storage-configuration":    {"ChannelARN", "ChannelName"},
			"describe-notification-configuration":     {"StreamARN", "StreamName"},
			"describe-signaling-channel":              {"ChannelARN", "ChannelName"},
			"describe-stream":                         {"StreamARN", "StreamName"},
			"describe-stream-storage-configuration":   {"StreamARN", "StreamName"},
			"get-data-endpoint":                       {"APIName", "StreamARN", "StreamName"},
			"get-signaling-channel-endpoint":          {"ChannelARN", "SingleMasterChannelEndpointConfiguration"},
			"list-edge-agent-configurations":          {"HubDeviceArn", "MaxResults", "NextToken"},
			"list-signaling-channels":                 {"ChannelNameCondition", "MaxResults", "NextToken"},
			"list-streams":                            {"MaxResults", "NextToken", "StreamNameCondition"},
			"list-tags-for-resource":                  {"NextToken", "ResourceARN"},
			"list-tags-for-stream":                    {"NextToken", "StreamARN", "StreamName"},
			"start-edge-configuration-update":         {"EdgeConfig", "StreamARN", "StreamName"},
			"tag-resource":                            {"ResourceARN", "Tags"},
			"tag-stream":                              {"StreamARN", "StreamName", "Tags"},
			"untag-resource":                          {"ResourceARN", "TagKeyList"},
			"untag-stream":                            {"StreamARN", "StreamName", "TagKeyList"},
			"update-data-retention":                   {"CurrentVersion", "DataRetentionChangeInHours", "Operation", "StreamARN", "StreamName"},
			"update-image-generation-configuration":   {"ImageGenerationConfiguration", "StreamARN", "StreamName"},
			"update-media-storage-configuration":      {"ChannelARN", "MediaStorageConfiguration"},
			"update-notification-configuration":       {"NotificationConfiguration", "StreamARN", "StreamName"},
			"update-signaling-channel":                {"ChannelARN", "CurrentVersion", "SingleMasterConfiguration"},
			"update-stream":                           {"CurrentVersion", "DeviceName", "MediaType", "StreamARN", "StreamName"},
			"update-stream-storage-configuration":     {"CurrentVersion", "StreamARN", "StreamName", "StreamStorageConfiguration"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-signaling-channel":                {"ChannelName": "*string", "ChannelType": "types.ChannelType", "SingleMasterConfiguration": "*types.SingleMasterConfiguration", "Tags": "[]types.Tag"},
			"create-stream":                           {"DataRetentionInHours": "*int32", "DeviceName": "*string", "KmsKeyId": "*string", "MediaType": "*string", "StreamName": "*string", "StreamStorageConfiguration": "*types.StreamStorageConfiguration", "Tags": "map[string]string"},
			"delete-edge-configuration":               {"StreamARN": "*string", "StreamName": "*string"},
			"delete-signaling-channel":                {"ChannelARN": "*string", "CurrentVersion": "*string"},
			"delete-stream":                           {"CurrentVersion": "*string", "StreamARN": "*string"},
			"describe-edge-configuration":             {"StreamARN": "*string", "StreamName": "*string"},
			"describe-image-generation-configuration": {"StreamARN": "*string", "StreamName": "*string"},
			"describe-mapped-resource-configuration":  {"MaxResults": "*int32", "NextToken": "*string", "StreamARN": "*string", "StreamName": "*string"},
			"describe-media-storage-configuration":    {"ChannelARN": "*string", "ChannelName": "*string"},
			"describe-notification-configuration":     {"StreamARN": "*string", "StreamName": "*string"},
			"describe-signaling-channel":              {"ChannelARN": "*string", "ChannelName": "*string"},
			"describe-stream":                         {"StreamARN": "*string", "StreamName": "*string"},
			"describe-stream-storage-configuration":   {"StreamARN": "*string", "StreamName": "*string"},
			"get-data-endpoint":                       {"APIName": "types.APIName", "StreamARN": "*string", "StreamName": "*string"},
			"get-signaling-channel-endpoint":          {"ChannelARN": "*string", "SingleMasterChannelEndpointConfiguration": "*types.SingleMasterChannelEndpointConfiguration"},
			"list-edge-agent-configurations":          {"HubDeviceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-signaling-channels":                 {"ChannelNameCondition": "*types.ChannelNameCondition", "MaxResults": "*int32", "NextToken": "*string"},
			"list-streams":                            {"MaxResults": "*int32", "NextToken": "*string", "StreamNameCondition": "*types.StreamNameCondition"},
			"list-tags-for-resource":                  {"NextToken": "*string", "ResourceARN": "*string"},
			"list-tags-for-stream":                    {"NextToken": "*string", "StreamARN": "*string", "StreamName": "*string"},
			"start-edge-configuration-update":         {"EdgeConfig": "*types.EdgeConfig", "StreamARN": "*string", "StreamName": "*string"},
			"tag-resource":                            {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"tag-stream":                              {"StreamARN": "*string", "StreamName": "*string", "Tags": "map[string]string"},
			"untag-resource":                          {"ResourceARN": "*string", "TagKeyList": "[]string"},
			"untag-stream":                            {"StreamARN": "*string", "StreamName": "*string", "TagKeyList": "[]string"},
			"update-data-retention":                   {"CurrentVersion": "*string", "DataRetentionChangeInHours": "*int32", "Operation": "types.UpdateDataRetentionOperation", "StreamARN": "*string", "StreamName": "*string"},
			"update-image-generation-configuration":   {"ImageGenerationConfiguration": "*types.ImageGenerationConfiguration", "StreamARN": "*string", "StreamName": "*string"},
			"update-media-storage-configuration":      {"ChannelARN": "*string", "MediaStorageConfiguration": "*types.MediaStorageConfiguration"},
			"update-notification-configuration":       {"NotificationConfiguration": "*types.NotificationConfiguration", "StreamARN": "*string", "StreamName": "*string"},
			"update-signaling-channel":                {"ChannelARN": "*string", "CurrentVersion": "*string", "SingleMasterConfiguration": "*types.SingleMasterConfiguration"},
			"update-stream":                           {"CurrentVersion": "*string", "DeviceName": "*string", "MediaType": "*string", "StreamARN": "*string", "StreamName": "*string"},
			"update-stream-storage-configuration":     {"CurrentVersion": "*string", "StreamARN": "*string", "StreamName": "*string", "StreamStorageConfiguration": "*types.StreamStorageConfiguration"},
		},
		OperationInputRequired: map[string][]string{
			"create-signaling-channel":                {"ChannelName"},
			"create-stream":                           {"StreamName"},
			"delete-edge-configuration":               {},
			"delete-signaling-channel":                {"ChannelARN"},
			"delete-stream":                           {"StreamARN"},
			"describe-edge-configuration":             {},
			"describe-image-generation-configuration": {},
			"describe-mapped-resource-configuration":  {},
			"describe-media-storage-configuration":    {},
			"describe-notification-configuration":     {},
			"describe-signaling-channel":              {},
			"describe-stream":                         {},
			"describe-stream-storage-configuration":   {},
			"get-data-endpoint":                       {"APIName"},
			"get-signaling-channel-endpoint":          {"ChannelARN"},
			"list-edge-agent-configurations":          {"HubDeviceArn"},
			"list-signaling-channels":                 {},
			"list-streams":                            {},
			"list-tags-for-resource":                  {"ResourceARN"},
			"list-tags-for-stream":                    {},
			"start-edge-configuration-update":         {"EdgeConfig"},
			"tag-resource":                            {"ResourceARN", "Tags"},
			"tag-stream":                              {"Tags"},
			"untag-resource":                          {"ResourceARN", "TagKeyList"},
			"untag-stream":                            {"TagKeyList"},
			"update-data-retention":                   {"CurrentVersion", "DataRetentionChangeInHours", "Operation"},
			"update-image-generation-configuration":   {},
			"update-media-storage-configuration":      {"ChannelARN", "MediaStorageConfiguration"},
			"update-notification-configuration":       {},
			"update-signaling-channel":                {"ChannelARN", "CurrentVersion"},
			"update-stream":                           {"CurrentVersion"},
			"update-stream-storage-configuration":     {"CurrentVersion", "StreamStorageConfiguration"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("kinesisvideo", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
