package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/ecr/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-check-layer-availability", "batch-delete-image", "batch-get-image", "batch-get-repository-scanning-configuration", "complete-layer-upload", "create-pull-through-cache-rule", "create-repository", "create-repository-creation-template", "delete-lifecycle-policy", "delete-pull-through-cache-rule", "delete-registry-policy", "delete-repository", "delete-repository-creation-template", "delete-repository-policy", "delete-signing-configuration", "deregister-pull-time-update-exclusion", "describe-image-replication-status", "describe-image-scan-findings", "describe-image-signing-status", "describe-images", "describe-pull-through-cache-rules", "describe-registry", "describe-repositories", "describe-repository-creation-templates", "get-account-setting", "get-authorization-token", "get-download-url-for-layer", "get-lifecycle-policy", "get-lifecycle-policy-preview", "get-registry-policy", "get-registry-scanning-configuration", "get-repository-policy", "get-signing-configuration", "initiate-layer-upload", "list-image-referrers", "list-images", "list-pull-time-update-exclusions", "list-tags-for-resource", "put-account-setting", "put-image", "put-image-scanning-configuration", "put-image-tag-mutability", "put-lifecycle-policy", "put-registry-policy", "put-registry-scanning-configuration", "put-replication-configuration", "put-signing-configuration", "register-pull-time-update-exclusion", "set-repository-policy", "start-image-scan", "start-lifecycle-policy-preview", "tag-resource", "untag-resource", "update-image-storage-class", "update-pull-through-cache-rule", "update-repository-creation-template", "upload-layer-part", "validate-pull-through-cache-rule"},
		OperationSet: map[string]bool{"batch-check-layer-availability": true, "batch-delete-image": true, "batch-get-image": true, "batch-get-repository-scanning-configuration": true, "complete-layer-upload": true, "create-pull-through-cache-rule": true, "create-repository": true, "create-repository-creation-template": true, "delete-lifecycle-policy": true, "delete-pull-through-cache-rule": true, "delete-registry-policy": true, "delete-repository": true, "delete-repository-creation-template": true, "delete-repository-policy": true, "delete-signing-configuration": true, "deregister-pull-time-update-exclusion": true, "describe-image-replication-status": true, "describe-image-scan-findings": true, "describe-image-signing-status": true, "describe-images": true, "describe-pull-through-cache-rules": true, "describe-registry": true, "describe-repositories": true, "describe-repository-creation-templates": true, "get-account-setting": true, "get-authorization-token": true, "get-download-url-for-layer": true, "get-lifecycle-policy": true, "get-lifecycle-policy-preview": true, "get-registry-policy": true, "get-registry-scanning-configuration": true, "get-repository-policy": true, "get-signing-configuration": true, "initiate-layer-upload": true, "list-image-referrers": true, "list-images": true, "list-pull-time-update-exclusions": true, "list-tags-for-resource": true, "put-account-setting": true, "put-image": true, "put-image-scanning-configuration": true, "put-image-tag-mutability": true, "put-lifecycle-policy": true, "put-registry-policy": true, "put-registry-scanning-configuration": true, "put-replication-configuration": true, "put-signing-configuration": true, "register-pull-time-update-exclusion": true, "set-repository-policy": true, "start-image-scan": true, "start-lifecycle-policy-preview": true, "tag-resource": true, "untag-resource": true, "update-image-storage-class": true, "update-pull-through-cache-rule": true, "update-repository-creation-template": true, "upload-layer-part": true, "validate-pull-through-cache-rule": true},
		OperationInputs: map[string][]string{
			"batch-check-layer-availability":              {"LayerDigests", "RegistryId", "RepositoryName"},
			"batch-delete-image":                          {"ImageIds", "RegistryId", "RepositoryName"},
			"batch-get-image":                             {"AcceptedMediaTypes", "ImageIds", "RegistryId", "RepositoryName"},
			"batch-get-repository-scanning-configuration": {"RepositoryNames"},
			"complete-layer-upload":                       {"LayerDigests", "RegistryId", "RepositoryName", "UploadId"},
			"create-pull-through-cache-rule":              {"CredentialArn", "CustomRoleArn", "EcrRepositoryPrefix", "RegistryId", "UpstreamRegistry", "UpstreamRegistryUrl", "UpstreamRepositoryPrefix"},
			"create-repository":                           {"EncryptionConfiguration", "ImageScanningConfiguration", "ImageTagMutability", "ImageTagMutabilityExclusionFilters", "RegistryId", "RepositoryName", "Tags"},
			"create-repository-creation-template":         {"AppliedFor", "CustomRoleArn", "Description", "EncryptionConfiguration", "ImageTagMutability", "ImageTagMutabilityExclusionFilters", "LifecyclePolicy", "Prefix", "RepositoryPolicy", "ResourceTags"},
			"delete-lifecycle-policy":                     {"RegistryId", "RepositoryName"},
			"delete-pull-through-cache-rule":              {"EcrRepositoryPrefix", "RegistryId"},
			"delete-registry-policy":                      {},
			"delete-repository":                           {"Force", "RegistryId", "RepositoryName"},
			"delete-repository-creation-template":         {"Prefix"},
			"delete-repository-policy":                    {"RegistryId", "RepositoryName"},
			"delete-signing-configuration":                {},
			"deregister-pull-time-update-exclusion":       {"PrincipalArn"},
			"describe-image-replication-status":           {"ImageId", "RegistryId", "RepositoryName"},
			"describe-image-scan-findings":                {"ImageId", "MaxResults", "NextToken", "RegistryId", "RepositoryName"},
			"describe-image-signing-status":               {"ImageId", "RegistryId", "RepositoryName"},
			"describe-images":                             {"Filter", "ImageIds", "MaxResults", "NextToken", "RegistryId", "RepositoryName"},
			"describe-pull-through-cache-rules":           {"EcrRepositoryPrefixes", "MaxResults", "NextToken", "RegistryId"},
			"describe-registry":                           {},
			"describe-repositories":                       {"MaxResults", "NextToken", "RegistryId", "RepositoryNames"},
			"describe-repository-creation-templates":      {"MaxResults", "NextToken", "Prefixes"},
			"get-account-setting":                         {"Name"},
			"get-authorization-token":                     {"RegistryIds"},
			"get-download-url-for-layer":                  {"LayerDigest", "RegistryId", "RepositoryName"},
			"get-lifecycle-policy":                        {"RegistryId", "RepositoryName"},
			"get-lifecycle-policy-preview":                {"Filter", "ImageIds", "MaxResults", "NextToken", "RegistryId", "RepositoryName"},
			"get-registry-policy":                         {},
			"get-registry-scanning-configuration":         {},
			"get-repository-policy":                       {"RegistryId", "RepositoryName"},
			"get-signing-configuration":                   {},
			"initiate-layer-upload":                       {"RegistryId", "RepositoryName"},
			"list-image-referrers":                        {"Filter", "MaxResults", "NextToken", "RegistryId", "RepositoryName", "SubjectId"},
			"list-images":                                 {"Filter", "MaxResults", "NextToken", "RegistryId", "RepositoryName"},
			"list-pull-time-update-exclusions":            {"MaxResults", "NextToken"},
			"list-tags-for-resource":                      {"ResourceArn"},
			"put-account-setting":                         {"Name", "Value"},
			"put-image":                                   {"ImageDigest", "ImageManifest", "ImageManifestMediaType", "ImageTag", "RegistryId", "RepositoryName"},
			"put-image-scanning-configuration":            {"ImageScanningConfiguration", "RegistryId", "RepositoryName"},
			"put-image-tag-mutability":                    {"ImageTagMutability", "ImageTagMutabilityExclusionFilters", "RegistryId", "RepositoryName"},
			"put-lifecycle-policy":                        {"LifecyclePolicyText", "RegistryId", "RepositoryName"},
			"put-registry-policy":                         {"PolicyText"},
			"put-registry-scanning-configuration":         {"Rules", "ScanType"},
			"put-replication-configuration":               {"ReplicationConfiguration"},
			"put-signing-configuration":                   {"SigningConfiguration"},
			"register-pull-time-update-exclusion":         {"PrincipalArn"},
			"set-repository-policy":                       {"Force", "PolicyText", "RegistryId", "RepositoryName"},
			"start-image-scan":                            {"ImageId", "RegistryId", "RepositoryName"},
			"start-lifecycle-policy-preview":              {"LifecyclePolicyText", "RegistryId", "RepositoryName"},
			"tag-resource":                                {"ResourceArn", "Tags"},
			"untag-resource":                              {"ResourceArn", "TagKeys"},
			"update-image-storage-class":                  {"ImageId", "RegistryId", "RepositoryName", "TargetStorageClass"},
			"update-pull-through-cache-rule":              {"CredentialArn", "CustomRoleArn", "EcrRepositoryPrefix", "RegistryId"},
			"update-repository-creation-template":         {"AppliedFor", "CustomRoleArn", "Description", "EncryptionConfiguration", "ImageTagMutability", "ImageTagMutabilityExclusionFilters", "LifecyclePolicy", "Prefix", "RepositoryPolicy", "ResourceTags"},
			"upload-layer-part":                           {"LayerPartBlob", "PartFirstByte", "PartLastByte", "RegistryId", "RepositoryName", "UploadId"},
			"validate-pull-through-cache-rule":            {"EcrRepositoryPrefix", "RegistryId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-check-layer-availability":              {"LayerDigests": "[]string", "RegistryId": "*string", "RepositoryName": "*string"},
			"batch-delete-image":                          {"ImageIds": "[]types.ImageIdentifier", "RegistryId": "*string", "RepositoryName": "*string"},
			"batch-get-image":                             {"AcceptedMediaTypes": "[]string", "ImageIds": "[]types.ImageIdentifier", "RegistryId": "*string", "RepositoryName": "*string"},
			"batch-get-repository-scanning-configuration": {"RepositoryNames": "[]string"},
			"complete-layer-upload":                       {"LayerDigests": "[]string", "RegistryId": "*string", "RepositoryName": "*string", "UploadId": "*string"},
			"create-pull-through-cache-rule":              {"CredentialArn": "*string", "CustomRoleArn": "*string", "EcrRepositoryPrefix": "*string", "RegistryId": "*string", "UpstreamRegistry": "types.UpstreamRegistry", "UpstreamRegistryUrl": "*string", "UpstreamRepositoryPrefix": "*string"},
			"create-repository":                           {"EncryptionConfiguration": "*types.EncryptionConfiguration", "ImageScanningConfiguration": "*types.ImageScanningConfiguration", "ImageTagMutability": "types.ImageTagMutability", "ImageTagMutabilityExclusionFilters": "[]types.ImageTagMutabilityExclusionFilter", "RegistryId": "*string", "RepositoryName": "*string", "Tags": "[]types.Tag"},
			"create-repository-creation-template":         {"AppliedFor": "[]types.RCTAppliedFor", "CustomRoleArn": "*string", "Description": "*string", "EncryptionConfiguration": "*types.EncryptionConfigurationForRepositoryCreationTemplate", "ImageTagMutability": "types.ImageTagMutability", "ImageTagMutabilityExclusionFilters": "[]types.ImageTagMutabilityExclusionFilter", "LifecyclePolicy": "*string", "Prefix": "*string", "RepositoryPolicy": "*string", "ResourceTags": "[]types.Tag"},
			"delete-lifecycle-policy":                     {"RegistryId": "*string", "RepositoryName": "*string"},
			"delete-pull-through-cache-rule":              {"EcrRepositoryPrefix": "*string", "RegistryId": "*string"},
			"delete-registry-policy":                      {},
			"delete-repository":                           {"Force": "bool", "RegistryId": "*string", "RepositoryName": "*string"},
			"delete-repository-creation-template":         {"Prefix": "*string"},
			"delete-repository-policy":                    {"RegistryId": "*string", "RepositoryName": "*string"},
			"delete-signing-configuration":                {},
			"deregister-pull-time-update-exclusion":       {"PrincipalArn": "*string"},
			"describe-image-replication-status":           {"ImageId": "*types.ImageIdentifier", "RegistryId": "*string", "RepositoryName": "*string"},
			"describe-image-scan-findings":                {"ImageId": "*types.ImageIdentifier", "MaxResults": "*int32", "NextToken": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"describe-image-signing-status":               {"ImageId": "*types.ImageIdentifier", "RegistryId": "*string", "RepositoryName": "*string"},
			"describe-images":                             {"Filter": "*types.DescribeImagesFilter", "ImageIds": "[]types.ImageIdentifier", "MaxResults": "*int32", "NextToken": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"describe-pull-through-cache-rules":           {"EcrRepositoryPrefixes": "[]string", "MaxResults": "*int32", "NextToken": "*string", "RegistryId": "*string"},
			"describe-registry":                           {},
			"describe-repositories":                       {"MaxResults": "*int32", "NextToken": "*string", "RegistryId": "*string", "RepositoryNames": "[]string"},
			"describe-repository-creation-templates":      {"MaxResults": "*int32", "NextToken": "*string", "Prefixes": "[]string"},
			"get-account-setting":                         {"Name": "*string"},
			"get-authorization-token":                     {"RegistryIds": "[]string"},
			"get-download-url-for-layer":                  {"LayerDigest": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"get-lifecycle-policy":                        {"RegistryId": "*string", "RepositoryName": "*string"},
			"get-lifecycle-policy-preview":                {"Filter": "*types.LifecyclePolicyPreviewFilter", "ImageIds": "[]types.ImageIdentifier", "MaxResults": "*int32", "NextToken": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"get-registry-policy":                         {},
			"get-registry-scanning-configuration":         {},
			"get-repository-policy":                       {"RegistryId": "*string", "RepositoryName": "*string"},
			"get-signing-configuration":                   {},
			"initiate-layer-upload":                       {"RegistryId": "*string", "RepositoryName": "*string"},
			"list-image-referrers":                        {"Filter": "*types.ListImageReferrersFilter", "MaxResults": "*int32", "NextToken": "*string", "RegistryId": "*string", "RepositoryName": "*string", "SubjectId": "*types.SubjectIdentifier"},
			"list-images":                                 {"Filter": "*types.ListImagesFilter", "MaxResults": "*int32", "NextToken": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"list-pull-time-update-exclusions":            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                      {"ResourceArn": "*string"},
			"put-account-setting":                         {"Name": "*string", "Value": "*string"},
			"put-image":                                   {"ImageDigest": "*string", "ImageManifest": "*string", "ImageManifestMediaType": "*string", "ImageTag": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"put-image-scanning-configuration":            {"ImageScanningConfiguration": "*types.ImageScanningConfiguration", "RegistryId": "*string", "RepositoryName": "*string"},
			"put-image-tag-mutability":                    {"ImageTagMutability": "types.ImageTagMutability", "ImageTagMutabilityExclusionFilters": "[]types.ImageTagMutabilityExclusionFilter", "RegistryId": "*string", "RepositoryName": "*string"},
			"put-lifecycle-policy":                        {"LifecyclePolicyText": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"put-registry-policy":                         {"PolicyText": "*string"},
			"put-registry-scanning-configuration":         {"Rules": "[]types.RegistryScanningRule", "ScanType": "types.ScanType"},
			"put-replication-configuration":               {"ReplicationConfiguration": "*types.ReplicationConfiguration"},
			"put-signing-configuration":                   {"SigningConfiguration": "*types.SigningConfiguration"},
			"register-pull-time-update-exclusion":         {"PrincipalArn": "*string"},
			"set-repository-policy":                       {"Force": "bool", "PolicyText": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"start-image-scan":                            {"ImageId": "*types.ImageIdentifier", "RegistryId": "*string", "RepositoryName": "*string"},
			"start-lifecycle-policy-preview":              {"LifecyclePolicyText": "*string", "RegistryId": "*string", "RepositoryName": "*string"},
			"tag-resource":                                {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                              {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-image-storage-class":                  {"ImageId": "*types.ImageIdentifier", "RegistryId": "*string", "RepositoryName": "*string", "TargetStorageClass": "types.TargetStorageClass"},
			"update-pull-through-cache-rule":              {"CredentialArn": "*string", "CustomRoleArn": "*string", "EcrRepositoryPrefix": "*string", "RegistryId": "*string"},
			"update-repository-creation-template":         {"AppliedFor": "[]types.RCTAppliedFor", "CustomRoleArn": "*string", "Description": "*string", "EncryptionConfiguration": "*types.EncryptionConfigurationForRepositoryCreationTemplate", "ImageTagMutability": "types.ImageTagMutability", "ImageTagMutabilityExclusionFilters": "[]types.ImageTagMutabilityExclusionFilter", "LifecyclePolicy": "*string", "Prefix": "*string", "RepositoryPolicy": "*string", "ResourceTags": "[]types.Tag"},
			"upload-layer-part":                           {"LayerPartBlob": "[]byte", "PartFirstByte": "*int64", "PartLastByte": "*int64", "RegistryId": "*string", "RepositoryName": "*string", "UploadId": "*string"},
			"validate-pull-through-cache-rule":            {"EcrRepositoryPrefix": "*string", "RegistryId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-check-layer-availability":              {"LayerDigests", "RepositoryName"},
			"batch-delete-image":                          {"ImageIds", "RepositoryName"},
			"batch-get-image":                             {"ImageIds", "RepositoryName"},
			"batch-get-repository-scanning-configuration": {"RepositoryNames"},
			"complete-layer-upload":                       {"LayerDigests", "RepositoryName", "UploadId"},
			"create-pull-through-cache-rule":              {"EcrRepositoryPrefix", "UpstreamRegistryUrl"},
			"create-repository":                           {"RepositoryName"},
			"create-repository-creation-template":         {"AppliedFor", "Prefix"},
			"delete-lifecycle-policy":                     {"RepositoryName"},
			"delete-pull-through-cache-rule":              {"EcrRepositoryPrefix"},
			"delete-registry-policy":                      {},
			"delete-repository":                           {"RepositoryName"},
			"delete-repository-creation-template":         {"Prefix"},
			"delete-repository-policy":                    {"RepositoryName"},
			"delete-signing-configuration":                {},
			"deregister-pull-time-update-exclusion":       {"PrincipalArn"},
			"describe-image-replication-status":           {"ImageId", "RepositoryName"},
			"describe-image-scan-findings":                {"ImageId", "RepositoryName"},
			"describe-image-signing-status":               {"ImageId", "RepositoryName"},
			"describe-images":                             {"RepositoryName"},
			"describe-pull-through-cache-rules":           {},
			"describe-registry":                           {},
			"describe-repositories":                       {},
			"describe-repository-creation-templates":      {},
			"get-account-setting":                         {"Name"},
			"get-authorization-token":                     {},
			"get-download-url-for-layer":                  {"LayerDigest", "RepositoryName"},
			"get-lifecycle-policy":                        {"RepositoryName"},
			"get-lifecycle-policy-preview":                {"RepositoryName"},
			"get-registry-policy":                         {},
			"get-registry-scanning-configuration":         {},
			"get-repository-policy":                       {"RepositoryName"},
			"get-signing-configuration":                   {},
			"initiate-layer-upload":                       {"RepositoryName"},
			"list-image-referrers":                        {"RepositoryName", "SubjectId"},
			"list-images":                                 {"RepositoryName"},
			"list-pull-time-update-exclusions":            {},
			"list-tags-for-resource":                      {"ResourceArn"},
			"put-account-setting":                         {"Name", "Value"},
			"put-image":                                   {"ImageManifest", "RepositoryName"},
			"put-image-scanning-configuration":            {"ImageScanningConfiguration", "RepositoryName"},
			"put-image-tag-mutability":                    {"ImageTagMutability", "RepositoryName"},
			"put-lifecycle-policy":                        {"LifecyclePolicyText", "RepositoryName"},
			"put-registry-policy":                         {"PolicyText"},
			"put-registry-scanning-configuration":         {},
			"put-replication-configuration":               {"ReplicationConfiguration"},
			"put-signing-configuration":                   {"SigningConfiguration"},
			"register-pull-time-update-exclusion":         {"PrincipalArn"},
			"set-repository-policy":                       {"PolicyText", "RepositoryName"},
			"start-image-scan":                            {"ImageId", "RepositoryName"},
			"start-lifecycle-policy-preview":              {"RepositoryName"},
			"tag-resource":                                {"ResourceArn", "Tags"},
			"untag-resource":                              {"ResourceArn", "TagKeys"},
			"update-image-storage-class":                  {"ImageId", "RepositoryName", "TargetStorageClass"},
			"update-pull-through-cache-rule":              {"EcrRepositoryPrefix"},
			"update-repository-creation-template":         {"Prefix"},
			"upload-layer-part":                           {"LayerPartBlob", "PartFirstByte", "PartLastByte", "RepositoryName", "UploadId"},
			"validate-pull-through-cache-rule":            {"EcrRepositoryPrefix"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("ecr", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
