package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/wafv2/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-web-acl", "check-capacity", "create-api-key", "create-ip-set", "create-regex-pattern-set", "create-rule-group", "create-web-acl", "delete-api-key", "delete-firewall-manager-rule-groups", "delete-ip-set", "delete-logging-configuration", "delete-permission-policy", "delete-regex-pattern-set", "delete-rule-group", "delete-web-acl", "describe-all-managed-products", "describe-managed-products-by-vendor", "describe-managed-rule-group", "disassociate-web-acl", "generate-mobile-sdk-release-url", "get-decrypted-api-key", "get-ip-set", "get-logging-configuration", "get-managed-rule-set", "get-mobile-sdk-release", "get-permission-policy", "get-rate-based-statement-managed-keys", "get-regex-pattern-set", "get-rule-group", "get-sampled-requests", "get-top-path-statistics-by-traffic", "get-web-acl", "get-web-acl-for-resource", "list-api-keys", "list-available-managed-rule-group-versions", "list-available-managed-rule-groups", "list-ip-sets", "list-logging-configurations", "list-managed-rule-sets", "list-mobile-sdk-releases", "list-regex-pattern-sets", "list-resources-for-web-acl", "list-rule-groups", "list-tags-for-resource", "list-web-acls", "put-logging-configuration", "put-managed-rule-set-versions", "put-permission-policy", "tag-resource", "untag-resource", "update-ip-set", "update-managed-rule-set-version-expiry-date", "update-regex-pattern-set", "update-rule-group", "update-web-acl"},
		OperationSet: map[string]bool{"associate-web-acl": true, "check-capacity": true, "create-api-key": true, "create-ip-set": true, "create-regex-pattern-set": true, "create-rule-group": true, "create-web-acl": true, "delete-api-key": true, "delete-firewall-manager-rule-groups": true, "delete-ip-set": true, "delete-logging-configuration": true, "delete-permission-policy": true, "delete-regex-pattern-set": true, "delete-rule-group": true, "delete-web-acl": true, "describe-all-managed-products": true, "describe-managed-products-by-vendor": true, "describe-managed-rule-group": true, "disassociate-web-acl": true, "generate-mobile-sdk-release-url": true, "get-decrypted-api-key": true, "get-ip-set": true, "get-logging-configuration": true, "get-managed-rule-set": true, "get-mobile-sdk-release": true, "get-permission-policy": true, "get-rate-based-statement-managed-keys": true, "get-regex-pattern-set": true, "get-rule-group": true, "get-sampled-requests": true, "get-top-path-statistics-by-traffic": true, "get-web-acl": true, "get-web-acl-for-resource": true, "list-api-keys": true, "list-available-managed-rule-group-versions": true, "list-available-managed-rule-groups": true, "list-ip-sets": true, "list-logging-configurations": true, "list-managed-rule-sets": true, "list-mobile-sdk-releases": true, "list-regex-pattern-sets": true, "list-resources-for-web-acl": true, "list-rule-groups": true, "list-tags-for-resource": true, "list-web-acls": true, "put-logging-configuration": true, "put-managed-rule-set-versions": true, "put-permission-policy": true, "tag-resource": true, "untag-resource": true, "update-ip-set": true, "update-managed-rule-set-version-expiry-date": true, "update-regex-pattern-set": true, "update-rule-group": true, "update-web-acl": true},
		OperationInputs: map[string][]string{
			"associate-web-acl":                           {"ResourceArn", "WebACLArn"},
			"check-capacity":                              {"Rules", "Scope"},
			"create-api-key":                              {"Scope", "TokenDomains"},
			"create-ip-set":                               {"Addresses", "Description", "IPAddressVersion", "Name", "Scope", "Tags"},
			"create-regex-pattern-set":                    {"Description", "Name", "RegularExpressionList", "Scope", "Tags"},
			"create-rule-group":                           {"Capacity", "CustomResponseBodies", "Description", "Name", "Rules", "Scope", "Tags", "VisibilityConfig"},
			"create-web-acl":                              {"ApplicationConfig", "AssociationConfig", "CaptchaConfig", "ChallengeConfig", "CustomResponseBodies", "DataProtectionConfig", "DefaultAction", "Description", "Name", "OnSourceDDoSProtectionConfig", "Rules", "Scope", "Tags", "TokenDomains", "VisibilityConfig"},
			"delete-api-key":                              {"APIKey", "Scope"},
			"delete-firewall-manager-rule-groups":         {"WebACLArn", "WebACLLockToken"},
			"delete-ip-set":                               {"Id", "LockToken", "Name", "Scope"},
			"delete-logging-configuration":                {"LogScope", "LogType", "ResourceArn"},
			"delete-permission-policy":                    {"ResourceArn"},
			"delete-regex-pattern-set":                    {"Id", "LockToken", "Name", "Scope"},
			"delete-rule-group":                           {"Id", "LockToken", "Name", "Scope"},
			"delete-web-acl":                              {"Id", "LockToken", "Name", "Scope"},
			"describe-all-managed-products":               {"Scope"},
			"describe-managed-products-by-vendor":         {"Scope", "VendorName"},
			"describe-managed-rule-group":                 {"Name", "Scope", "VendorName", "VersionName"},
			"disassociate-web-acl":                        {"ResourceArn"},
			"generate-mobile-sdk-release-url":             {"Platform", "ReleaseVersion"},
			"get-decrypted-api-key":                       {"APIKey", "Scope"},
			"get-ip-set":                                  {"Id", "Name", "Scope"},
			"get-logging-configuration":                   {"LogScope", "LogType", "ResourceArn"},
			"get-managed-rule-set":                        {"Id", "Name", "Scope"},
			"get-mobile-sdk-release":                      {"Platform", "ReleaseVersion"},
			"get-permission-policy":                       {"ResourceArn"},
			"get-rate-based-statement-managed-keys":       {"RuleGroupRuleName", "RuleName", "Scope", "WebACLId", "WebACLName"},
			"get-regex-pattern-set":                       {"Id", "Name", "Scope"},
			"get-rule-group":                              {"ARN", "Id", "Name", "Scope"},
			"get-sampled-requests":                        {"MaxItems", "RuleMetricName", "Scope", "TimeWindow", "WebAclArn"},
			"get-top-path-statistics-by-traffic":          {"BotCategory", "BotName", "BotOrganization", "Limit", "NextMarker", "NumberOfTopTrafficBotsPerPath", "Scope", "TimeWindow", "UriPathPrefix", "WebAclArn"},
			"get-web-acl":                                 {"ARN", "Id", "Name", "Scope"},
			"get-web-acl-for-resource":                    {"ResourceArn"},
			"list-api-keys":                               {"Limit", "NextMarker", "Scope"},
			"list-available-managed-rule-group-versions":  {"Limit", "Name", "NextMarker", "Scope", "VendorName"},
			"list-available-managed-rule-groups":          {"Limit", "NextMarker", "Scope"},
			"list-ip-sets":                                {"Limit", "NextMarker", "Scope"},
			"list-logging-configurations":                 {"Limit", "LogScope", "NextMarker", "Scope"},
			"list-managed-rule-sets":                      {"Limit", "NextMarker", "Scope"},
			"list-mobile-sdk-releases":                    {"Limit", "NextMarker", "Platform"},
			"list-regex-pattern-sets":                     {"Limit", "NextMarker", "Scope"},
			"list-resources-for-web-acl":                  {"ResourceType", "WebACLArn"},
			"list-rule-groups":                            {"Limit", "NextMarker", "Scope"},
			"list-tags-for-resource":                      {"Limit", "NextMarker", "ResourceARN"},
			"list-web-acls":                               {"Limit", "NextMarker", "Scope"},
			"put-logging-configuration":                   {"LoggingConfiguration"},
			"put-managed-rule-set-versions":               {"Id", "LockToken", "Name", "RecommendedVersion", "Scope", "VersionsToPublish"},
			"put-permission-policy":                       {"Policy", "ResourceArn"},
			"tag-resource":                                {"ResourceARN", "Tags"},
			"untag-resource":                              {"ResourceARN", "TagKeys"},
			"update-ip-set":                               {"Addresses", "Description", "Id", "LockToken", "Name", "Scope"},
			"update-managed-rule-set-version-expiry-date": {"ExpiryTimestamp", "Id", "LockToken", "Name", "Scope", "VersionToExpire"},
			"update-regex-pattern-set":                    {"Description", "Id", "LockToken", "Name", "RegularExpressionList", "Scope"},
			"update-rule-group":                           {"CustomResponseBodies", "Description", "Id", "LockToken", "Name", "Rules", "Scope", "VisibilityConfig"},
			"update-web-acl":                              {"ApplicationConfig", "AssociationConfig", "CaptchaConfig", "ChallengeConfig", "CustomResponseBodies", "DataProtectionConfig", "DefaultAction", "Description", "Id", "LockToken", "Name", "OnSourceDDoSProtectionConfig", "Rules", "Scope", "TokenDomains", "VisibilityConfig"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-web-acl":                           {"ResourceArn": "*string", "WebACLArn": "*string"},
			"check-capacity":                              {"Rules": "[]types.Rule", "Scope": "types.Scope"},
			"create-api-key":                              {"Scope": "types.Scope", "TokenDomains": "[]string"},
			"create-ip-set":                               {"Addresses": "[]string", "Description": "*string", "IPAddressVersion": "types.IPAddressVersion", "Name": "*string", "Scope": "types.Scope", "Tags": "[]types.Tag"},
			"create-regex-pattern-set":                    {"Description": "*string", "Name": "*string", "RegularExpressionList": "[]types.Regex", "Scope": "types.Scope", "Tags": "[]types.Tag"},
			"create-rule-group":                           {"Capacity": "*int64", "CustomResponseBodies": "map[string]types.CustomResponseBody", "Description": "*string", "Name": "*string", "Rules": "[]types.Rule", "Scope": "types.Scope", "Tags": "[]types.Tag", "VisibilityConfig": "*types.VisibilityConfig"},
			"create-web-acl":                              {"ApplicationConfig": "*types.ApplicationConfig", "AssociationConfig": "*types.AssociationConfig", "CaptchaConfig": "*types.CaptchaConfig", "ChallengeConfig": "*types.ChallengeConfig", "CustomResponseBodies": "map[string]types.CustomResponseBody", "DataProtectionConfig": "*types.DataProtectionConfig", "DefaultAction": "*types.DefaultAction", "Description": "*string", "Name": "*string", "OnSourceDDoSProtectionConfig": "*types.OnSourceDDoSProtectionConfig", "Rules": "[]types.Rule", "Scope": "types.Scope", "Tags": "[]types.Tag", "TokenDomains": "[]string", "VisibilityConfig": "*types.VisibilityConfig"},
			"delete-api-key":                              {"APIKey": "*string", "Scope": "types.Scope"},
			"delete-firewall-manager-rule-groups":         {"WebACLArn": "*string", "WebACLLockToken": "*string"},
			"delete-ip-set":                               {"Id": "*string", "LockToken": "*string", "Name": "*string", "Scope": "types.Scope"},
			"delete-logging-configuration":                {"LogScope": "types.LogScope", "LogType": "types.LogType", "ResourceArn": "*string"},
			"delete-permission-policy":                    {"ResourceArn": "*string"},
			"delete-regex-pattern-set":                    {"Id": "*string", "LockToken": "*string", "Name": "*string", "Scope": "types.Scope"},
			"delete-rule-group":                           {"Id": "*string", "LockToken": "*string", "Name": "*string", "Scope": "types.Scope"},
			"delete-web-acl":                              {"Id": "*string", "LockToken": "*string", "Name": "*string", "Scope": "types.Scope"},
			"describe-all-managed-products":               {"Scope": "types.Scope"},
			"describe-managed-products-by-vendor":         {"Scope": "types.Scope", "VendorName": "*string"},
			"describe-managed-rule-group":                 {"Name": "*string", "Scope": "types.Scope", "VendorName": "*string", "VersionName": "*string"},
			"disassociate-web-acl":                        {"ResourceArn": "*string"},
			"generate-mobile-sdk-release-url":             {"Platform": "types.Platform", "ReleaseVersion": "*string"},
			"get-decrypted-api-key":                       {"APIKey": "*string", "Scope": "types.Scope"},
			"get-ip-set":                                  {"Id": "*string", "Name": "*string", "Scope": "types.Scope"},
			"get-logging-configuration":                   {"LogScope": "types.LogScope", "LogType": "types.LogType", "ResourceArn": "*string"},
			"get-managed-rule-set":                        {"Id": "*string", "Name": "*string", "Scope": "types.Scope"},
			"get-mobile-sdk-release":                      {"Platform": "types.Platform", "ReleaseVersion": "*string"},
			"get-permission-policy":                       {"ResourceArn": "*string"},
			"get-rate-based-statement-managed-keys":       {"RuleGroupRuleName": "*string", "RuleName": "*string", "Scope": "types.Scope", "WebACLId": "*string", "WebACLName": "*string"},
			"get-regex-pattern-set":                       {"Id": "*string", "Name": "*string", "Scope": "types.Scope"},
			"get-rule-group":                              {"ARN": "*string", "Id": "*string", "Name": "*string", "Scope": "types.Scope"},
			"get-sampled-requests":                        {"MaxItems": "*int64", "RuleMetricName": "*string", "Scope": "types.Scope", "TimeWindow": "*types.TimeWindow", "WebAclArn": "*string"},
			"get-top-path-statistics-by-traffic":          {"BotCategory": "*string", "BotName": "*string", "BotOrganization": "*string", "Limit": "*int32", "NextMarker": "*string", "NumberOfTopTrafficBotsPerPath": "*int32", "Scope": "types.Scope", "TimeWindow": "*types.TimeWindow", "UriPathPrefix": "*string", "WebAclArn": "*string"},
			"get-web-acl":                                 {"ARN": "*string", "Id": "*string", "Name": "*string", "Scope": "types.Scope"},
			"get-web-acl-for-resource":                    {"ResourceArn": "*string"},
			"list-api-keys":                               {"Limit": "*int32", "NextMarker": "*string", "Scope": "types.Scope"},
			"list-available-managed-rule-group-versions":  {"Limit": "*int32", "Name": "*string", "NextMarker": "*string", "Scope": "types.Scope", "VendorName": "*string"},
			"list-available-managed-rule-groups":          {"Limit": "*int32", "NextMarker": "*string", "Scope": "types.Scope"},
			"list-ip-sets":                                {"Limit": "*int32", "NextMarker": "*string", "Scope": "types.Scope"},
			"list-logging-configurations":                 {"Limit": "*int32", "LogScope": "types.LogScope", "NextMarker": "*string", "Scope": "types.Scope"},
			"list-managed-rule-sets":                      {"Limit": "*int32", "NextMarker": "*string", "Scope": "types.Scope"},
			"list-mobile-sdk-releases":                    {"Limit": "*int32", "NextMarker": "*string", "Platform": "types.Platform"},
			"list-regex-pattern-sets":                     {"Limit": "*int32", "NextMarker": "*string", "Scope": "types.Scope"},
			"list-resources-for-web-acl":                  {"ResourceType": "types.ResourceType", "WebACLArn": "*string"},
			"list-rule-groups":                            {"Limit": "*int32", "NextMarker": "*string", "Scope": "types.Scope"},
			"list-tags-for-resource":                      {"Limit": "*int32", "NextMarker": "*string", "ResourceARN": "*string"},
			"list-web-acls":                               {"Limit": "*int32", "NextMarker": "*string", "Scope": "types.Scope"},
			"put-logging-configuration":                   {"LoggingConfiguration": "*types.LoggingConfiguration"},
			"put-managed-rule-set-versions":               {"Id": "*string", "LockToken": "*string", "Name": "*string", "RecommendedVersion": "*string", "Scope": "types.Scope", "VersionsToPublish": "map[string]types.VersionToPublish"},
			"put-permission-policy":                       {"Policy": "*string", "ResourceArn": "*string"},
			"tag-resource":                                {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                              {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-ip-set":                               {"Addresses": "[]string", "Description": "*string", "Id": "*string", "LockToken": "*string", "Name": "*string", "Scope": "types.Scope"},
			"update-managed-rule-set-version-expiry-date": {"ExpiryTimestamp": "*time.Time", "Id": "*string", "LockToken": "*string", "Name": "*string", "Scope": "types.Scope", "VersionToExpire": "*string"},
			"update-regex-pattern-set":                    {"Description": "*string", "Id": "*string", "LockToken": "*string", "Name": "*string", "RegularExpressionList": "[]types.Regex", "Scope": "types.Scope"},
			"update-rule-group":                           {"CustomResponseBodies": "map[string]types.CustomResponseBody", "Description": "*string", "Id": "*string", "LockToken": "*string", "Name": "*string", "Rules": "[]types.Rule", "Scope": "types.Scope", "VisibilityConfig": "*types.VisibilityConfig"},
			"update-web-acl":                              {"ApplicationConfig": "*types.ApplicationConfig", "AssociationConfig": "*types.AssociationConfig", "CaptchaConfig": "*types.CaptchaConfig", "ChallengeConfig": "*types.ChallengeConfig", "CustomResponseBodies": "map[string]types.CustomResponseBody", "DataProtectionConfig": "*types.DataProtectionConfig", "DefaultAction": "*types.DefaultAction", "Description": "*string", "Id": "*string", "LockToken": "*string", "Name": "*string", "OnSourceDDoSProtectionConfig": "*types.OnSourceDDoSProtectionConfig", "Rules": "[]types.Rule", "Scope": "types.Scope", "TokenDomains": "[]string", "VisibilityConfig": "*types.VisibilityConfig"},
		},
		OperationInputRequired: map[string][]string{
			"associate-web-acl":                           {"ResourceArn", "WebACLArn"},
			"check-capacity":                              {"Rules", "Scope"},
			"create-api-key":                              {"Scope", "TokenDomains"},
			"create-ip-set":                               {"Addresses", "IPAddressVersion", "Name", "Scope"},
			"create-regex-pattern-set":                    {"Name", "RegularExpressionList", "Scope"},
			"create-rule-group":                           {"Capacity", "Name", "Scope", "VisibilityConfig"},
			"create-web-acl":                              {"DefaultAction", "Name", "Scope", "VisibilityConfig"},
			"delete-api-key":                              {"APIKey", "Scope"},
			"delete-firewall-manager-rule-groups":         {"WebACLArn", "WebACLLockToken"},
			"delete-ip-set":                               {"Id", "LockToken", "Name", "Scope"},
			"delete-logging-configuration":                {"ResourceArn"},
			"delete-permission-policy":                    {"ResourceArn"},
			"delete-regex-pattern-set":                    {"Id", "LockToken", "Name", "Scope"},
			"delete-rule-group":                           {"Id", "LockToken", "Name", "Scope"},
			"delete-web-acl":                              {"Id", "LockToken", "Name", "Scope"},
			"describe-all-managed-products":               {"Scope"},
			"describe-managed-products-by-vendor":         {"Scope", "VendorName"},
			"describe-managed-rule-group":                 {"Name", "Scope", "VendorName"},
			"disassociate-web-acl":                        {"ResourceArn"},
			"generate-mobile-sdk-release-url":             {"Platform", "ReleaseVersion"},
			"get-decrypted-api-key":                       {"APIKey", "Scope"},
			"get-ip-set":                                  {"Id", "Name", "Scope"},
			"get-logging-configuration":                   {"ResourceArn"},
			"get-managed-rule-set":                        {"Id", "Name", "Scope"},
			"get-mobile-sdk-release":                      {"Platform", "ReleaseVersion"},
			"get-permission-policy":                       {"ResourceArn"},
			"get-rate-based-statement-managed-keys":       {"RuleName", "Scope", "WebACLId", "WebACLName"},
			"get-regex-pattern-set":                       {"Id", "Name", "Scope"},
			"get-rule-group":                              {},
			"get-sampled-requests":                        {"MaxItems", "RuleMetricName", "Scope", "TimeWindow", "WebAclArn"},
			"get-top-path-statistics-by-traffic":          {"Limit", "NumberOfTopTrafficBotsPerPath", "Scope", "TimeWindow", "WebAclArn"},
			"get-web-acl":                                 {},
			"get-web-acl-for-resource":                    {"ResourceArn"},
			"list-api-keys":                               {"Scope"},
			"list-available-managed-rule-group-versions":  {"Name", "Scope", "VendorName"},
			"list-available-managed-rule-groups":          {"Scope"},
			"list-ip-sets":                                {"Scope"},
			"list-logging-configurations":                 {"Scope"},
			"list-managed-rule-sets":                      {"Scope"},
			"list-mobile-sdk-releases":                    {"Platform"},
			"list-regex-pattern-sets":                     {"Scope"},
			"list-resources-for-web-acl":                  {"WebACLArn"},
			"list-rule-groups":                            {"Scope"},
			"list-tags-for-resource":                      {"ResourceARN"},
			"list-web-acls":                               {"Scope"},
			"put-logging-configuration":                   {"LoggingConfiguration"},
			"put-managed-rule-set-versions":               {"Id", "LockToken", "Name", "Scope"},
			"put-permission-policy":                       {"Policy", "ResourceArn"},
			"tag-resource":                                {"ResourceARN", "Tags"},
			"untag-resource":                              {"ResourceARN", "TagKeys"},
			"update-ip-set":                               {"Addresses", "Id", "LockToken", "Name", "Scope"},
			"update-managed-rule-set-version-expiry-date": {"ExpiryTimestamp", "Id", "LockToken", "Name", "Scope", "VersionToExpire"},
			"update-regex-pattern-set":                    {"Id", "LockToken", "Name", "RegularExpressionList", "Scope"},
			"update-rule-group":                           {"Id", "LockToken", "Name", "Scope", "VisibilityConfig"},
			"update-web-acl":                              {"DefaultAction", "Id", "LockToken", "Name", "Scope", "VisibilityConfig"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("wafv2", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
