package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/iotthingsgraph/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-entity-to-thing", "create-flow-template", "create-system-instance", "create-system-template", "delete-flow-template", "delete-namespace", "delete-system-instance", "delete-system-template", "deploy-system-instance", "deprecate-flow-template", "deprecate-system-template", "describe-namespace", "dissociate-entity-from-thing", "get-entities", "get-flow-template", "get-flow-template-revisions", "get-namespace-deletion-status", "get-system-instance", "get-system-template", "get-system-template-revisions", "get-upload-status", "list-flow-execution-messages", "list-tags-for-resource", "search-entities", "search-flow-executions", "search-flow-templates", "search-system-instances", "search-system-templates", "search-things", "tag-resource", "undeploy-system-instance", "untag-resource", "update-flow-template", "update-system-template", "upload-entity-definitions"},
		OperationSet: map[string]bool{"associate-entity-to-thing": true, "create-flow-template": true, "create-system-instance": true, "create-system-template": true, "delete-flow-template": true, "delete-namespace": true, "delete-system-instance": true, "delete-system-template": true, "deploy-system-instance": true, "deprecate-flow-template": true, "deprecate-system-template": true, "describe-namespace": true, "dissociate-entity-from-thing": true, "get-entities": true, "get-flow-template": true, "get-flow-template-revisions": true, "get-namespace-deletion-status": true, "get-system-instance": true, "get-system-template": true, "get-system-template-revisions": true, "get-upload-status": true, "list-flow-execution-messages": true, "list-tags-for-resource": true, "search-entities": true, "search-flow-executions": true, "search-flow-templates": true, "search-system-instances": true, "search-system-templates": true, "search-things": true, "tag-resource": true, "undeploy-system-instance": true, "untag-resource": true, "update-flow-template": true, "update-system-template": true, "upload-entity-definitions": true},
		OperationInputs: map[string][]string{
			"associate-entity-to-thing":     {"EntityId", "NamespaceVersion", "ThingName"},
			"create-flow-template":          {"CompatibleNamespaceVersion", "Definition"},
			"create-system-instance":        {"Definition", "FlowActionsRoleArn", "GreengrassGroupName", "MetricsConfiguration", "S3BucketName", "Tags", "Target"},
			"create-system-template":        {"CompatibleNamespaceVersion", "Definition"},
			"delete-flow-template":          {"Id"},
			"delete-namespace":              {},
			"delete-system-instance":        {"Id"},
			"delete-system-template":        {"Id"},
			"deploy-system-instance":        {"Id"},
			"deprecate-flow-template":       {"Id"},
			"deprecate-system-template":     {"Id"},
			"describe-namespace":            {"NamespaceName"},
			"dissociate-entity-from-thing":  {"EntityType", "ThingName"},
			"get-entities":                  {"Ids", "NamespaceVersion"},
			"get-flow-template":             {"Id", "RevisionNumber"},
			"get-flow-template-revisions":   {"Id", "MaxResults", "NextToken"},
			"get-namespace-deletion-status": {},
			"get-system-instance":           {"Id"},
			"get-system-template":           {"Id", "RevisionNumber"},
			"get-system-template-revisions": {"Id", "MaxResults", "NextToken"},
			"get-upload-status":             {"UploadId"},
			"list-flow-execution-messages":  {"FlowExecutionId", "MaxResults", "NextToken"},
			"list-tags-for-resource":        {"MaxResults", "NextToken", "ResourceArn"},
			"search-entities":               {"EntityTypes", "Filters", "MaxResults", "NamespaceVersion", "NextToken"},
			"search-flow-executions":        {"EndTime", "FlowExecutionId", "MaxResults", "NextToken", "StartTime", "SystemInstanceId"},
			"search-flow-templates":         {"Filters", "MaxResults", "NextToken"},
			"search-system-instances":       {"Filters", "MaxResults", "NextToken"},
			"search-system-templates":       {"Filters", "MaxResults", "NextToken"},
			"search-things":                 {"EntityId", "MaxResults", "NamespaceVersion", "NextToken"},
			"tag-resource":                  {"ResourceArn", "Tags"},
			"undeploy-system-instance":      {"Id"},
			"untag-resource":                {"ResourceArn", "TagKeys"},
			"update-flow-template":          {"CompatibleNamespaceVersion", "Definition", "Id"},
			"update-system-template":        {"CompatibleNamespaceVersion", "Definition", "Id"},
			"upload-entity-definitions":     {"DeprecateExistingEntities", "Document", "SyncWithPublicNamespace"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-entity-to-thing":     {"EntityId": "*string", "NamespaceVersion": "*int64", "ThingName": "*string"},
			"create-flow-template":          {"CompatibleNamespaceVersion": "*int64", "Definition": "*types.DefinitionDocument"},
			"create-system-instance":        {"Definition": "*types.DefinitionDocument", "FlowActionsRoleArn": "*string", "GreengrassGroupName": "*string", "MetricsConfiguration": "*types.MetricsConfiguration", "S3BucketName": "*string", "Tags": "[]types.Tag", "Target": "types.DeploymentTarget"},
			"create-system-template":        {"CompatibleNamespaceVersion": "*int64", "Definition": "*types.DefinitionDocument"},
			"delete-flow-template":          {"Id": "*string"},
			"delete-namespace":              {},
			"delete-system-instance":        {"Id": "*string"},
			"delete-system-template":        {"Id": "*string"},
			"deploy-system-instance":        {"Id": "*string"},
			"deprecate-flow-template":       {"Id": "*string"},
			"deprecate-system-template":     {"Id": "*string"},
			"describe-namespace":            {"NamespaceName": "*string"},
			"dissociate-entity-from-thing":  {"EntityType": "types.EntityType", "ThingName": "*string"},
			"get-entities":                  {"Ids": "[]string", "NamespaceVersion": "*int64"},
			"get-flow-template":             {"Id": "*string", "RevisionNumber": "*int64"},
			"get-flow-template-revisions":   {"Id": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-namespace-deletion-status": {},
			"get-system-instance":           {"Id": "*string"},
			"get-system-template":           {"Id": "*string", "RevisionNumber": "*int64"},
			"get-system-template-revisions": {"Id": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-upload-status":             {"UploadId": "*string"},
			"list-flow-execution-messages":  {"FlowExecutionId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":        {"MaxResults": "*int32", "NextToken": "*string", "ResourceArn": "*string"},
			"search-entities":               {"EntityTypes": "[]types.EntityType", "Filters": "[]types.EntityFilter", "MaxResults": "*int32", "NamespaceVersion": "*int64", "NextToken": "*string"},
			"search-flow-executions":        {"EndTime": "*time.Time", "FlowExecutionId": "*string", "MaxResults": "*int32", "NextToken": "*string", "StartTime": "*time.Time", "SystemInstanceId": "*string"},
			"search-flow-templates":         {"Filters": "[]types.FlowTemplateFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"search-system-instances":       {"Filters": "[]types.SystemInstanceFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"search-system-templates":       {"Filters": "[]types.SystemTemplateFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"search-things":                 {"EntityId": "*string", "MaxResults": "*int32", "NamespaceVersion": "*int64", "NextToken": "*string"},
			"tag-resource":                  {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"undeploy-system-instance":      {"Id": "*string"},
			"untag-resource":                {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-flow-template":          {"CompatibleNamespaceVersion": "*int64", "Definition": "*types.DefinitionDocument", "Id": "*string"},
			"update-system-template":        {"CompatibleNamespaceVersion": "*int64", "Definition": "*types.DefinitionDocument", "Id": "*string"},
			"upload-entity-definitions":     {"DeprecateExistingEntities": "bool", "Document": "*types.DefinitionDocument", "SyncWithPublicNamespace": "bool"},
		},
		OperationInputRequired: map[string][]string{
			"associate-entity-to-thing":     {"EntityId", "ThingName"},
			"create-flow-template":          {"Definition"},
			"create-system-instance":        {"Definition", "Target"},
			"create-system-template":        {"Definition"},
			"delete-flow-template":          {"Id"},
			"delete-namespace":              {},
			"delete-system-instance":        {},
			"delete-system-template":        {"Id"},
			"deploy-system-instance":        {},
			"deprecate-flow-template":       {"Id"},
			"deprecate-system-template":     {"Id"},
			"describe-namespace":            {},
			"dissociate-entity-from-thing":  {"EntityType", "ThingName"},
			"get-entities":                  {"Ids"},
			"get-flow-template":             {"Id"},
			"get-flow-template-revisions":   {"Id"},
			"get-namespace-deletion-status": {},
			"get-system-instance":           {"Id"},
			"get-system-template":           {"Id"},
			"get-system-template-revisions": {"Id"},
			"get-upload-status":             {"UploadId"},
			"list-flow-execution-messages":  {"FlowExecutionId"},
			"list-tags-for-resource":        {"ResourceArn"},
			"search-entities":               {"EntityTypes"},
			"search-flow-executions":        {"SystemInstanceId"},
			"search-flow-templates":         {},
			"search-system-instances":       {},
			"search-system-templates":       {},
			"search-things":                 {"EntityId"},
			"tag-resource":                  {"ResourceArn", "Tags"},
			"undeploy-system-instance":      {},
			"untag-resource":                {"ResourceArn", "TagKeys"},
			"update-flow-template":          {"Definition", "Id"},
			"update-system-template":        {"Definition", "Id"},
			"upload-entity-definitions":     {},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("iotthingsgraph", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
