package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/codecommit/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-approval-rule-template-with-repository", "batch-associate-approval-rule-template-with-repositories", "batch-describe-merge-conflicts", "batch-disassociate-approval-rule-template-from-repositories", "batch-get-commits", "batch-get-repositories", "create-approval-rule-template", "create-branch", "create-commit", "create-pull-request", "create-pull-request-approval-rule", "create-repository", "create-unreferenced-merge-commit", "delete-approval-rule-template", "delete-branch", "delete-comment-content", "delete-file", "delete-pull-request-approval-rule", "delete-repository", "describe-merge-conflicts", "describe-pull-request-events", "disassociate-approval-rule-template-from-repository", "evaluate-pull-request-approval-rules", "get-approval-rule-template", "get-blob", "get-branch", "get-comment", "get-comment-reactions", "get-comments-for-compared-commit", "get-comments-for-pull-request", "get-commit", "get-differences", "get-file", "get-folder", "get-merge-commit", "get-merge-conflicts", "get-merge-options", "get-pull-request", "get-pull-request-approval-states", "get-pull-request-override-state", "get-repository", "get-repository-triggers", "list-approval-rule-templates", "list-associated-approval-rule-templates-for-repository", "list-branches", "list-file-commit-history", "list-pull-requests", "list-repositories", "list-repositories-for-approval-rule-template", "list-tags-for-resource", "merge-branches-by-fast-forward", "merge-branches-by-squash", "merge-branches-by-three-way", "merge-pull-request-by-fast-forward", "merge-pull-request-by-squash", "merge-pull-request-by-three-way", "override-pull-request-approval-rules", "post-comment-for-compared-commit", "post-comment-for-pull-request", "post-comment-reply", "put-comment-reaction", "put-file", "put-repository-triggers", "tag-resource", "test-repository-triggers", "untag-resource", "update-approval-rule-template-content", "update-approval-rule-template-description", "update-approval-rule-template-name", "update-comment", "update-default-branch", "update-pull-request-approval-rule-content", "update-pull-request-approval-state", "update-pull-request-description", "update-pull-request-status", "update-pull-request-title", "update-repository-description", "update-repository-encryption-key", "update-repository-name"},
		OperationSet: map[string]bool{"associate-approval-rule-template-with-repository": true, "batch-associate-approval-rule-template-with-repositories": true, "batch-describe-merge-conflicts": true, "batch-disassociate-approval-rule-template-from-repositories": true, "batch-get-commits": true, "batch-get-repositories": true, "create-approval-rule-template": true, "create-branch": true, "create-commit": true, "create-pull-request": true, "create-pull-request-approval-rule": true, "create-repository": true, "create-unreferenced-merge-commit": true, "delete-approval-rule-template": true, "delete-branch": true, "delete-comment-content": true, "delete-file": true, "delete-pull-request-approval-rule": true, "delete-repository": true, "describe-merge-conflicts": true, "describe-pull-request-events": true, "disassociate-approval-rule-template-from-repository": true, "evaluate-pull-request-approval-rules": true, "get-approval-rule-template": true, "get-blob": true, "get-branch": true, "get-comment": true, "get-comment-reactions": true, "get-comments-for-compared-commit": true, "get-comments-for-pull-request": true, "get-commit": true, "get-differences": true, "get-file": true, "get-folder": true, "get-merge-commit": true, "get-merge-conflicts": true, "get-merge-options": true, "get-pull-request": true, "get-pull-request-approval-states": true, "get-pull-request-override-state": true, "get-repository": true, "get-repository-triggers": true, "list-approval-rule-templates": true, "list-associated-approval-rule-templates-for-repository": true, "list-branches": true, "list-file-commit-history": true, "list-pull-requests": true, "list-repositories": true, "list-repositories-for-approval-rule-template": true, "list-tags-for-resource": true, "merge-branches-by-fast-forward": true, "merge-branches-by-squash": true, "merge-branches-by-three-way": true, "merge-pull-request-by-fast-forward": true, "merge-pull-request-by-squash": true, "merge-pull-request-by-three-way": true, "override-pull-request-approval-rules": true, "post-comment-for-compared-commit": true, "post-comment-for-pull-request": true, "post-comment-reply": true, "put-comment-reaction": true, "put-file": true, "put-repository-triggers": true, "tag-resource": true, "test-repository-triggers": true, "untag-resource": true, "update-approval-rule-template-content": true, "update-approval-rule-template-description": true, "update-approval-rule-template-name": true, "update-comment": true, "update-default-branch": true, "update-pull-request-approval-rule-content": true, "update-pull-request-approval-state": true, "update-pull-request-description": true, "update-pull-request-status": true, "update-pull-request-title": true, "update-repository-description": true, "update-repository-encryption-key": true, "update-repository-name": true},
		OperationInputs: map[string][]string{
			"associate-approval-rule-template-with-repository":            {"ApprovalRuleTemplateName", "RepositoryName"},
			"batch-associate-approval-rule-template-with-repositories":    {"ApprovalRuleTemplateName", "RepositoryNames"},
			"batch-describe-merge-conflicts":                              {"ConflictDetailLevel", "ConflictResolutionStrategy", "DestinationCommitSpecifier", "FilePaths", "MaxConflictFiles", "MaxMergeHunks", "MergeOption", "NextToken", "RepositoryName", "SourceCommitSpecifier"},
			"batch-disassociate-approval-rule-template-from-repositories": {"ApprovalRuleTemplateName", "RepositoryNames"},
			"batch-get-commits":                                   {"CommitIds", "RepositoryName"},
			"batch-get-repositories":                              {"RepositoryNames"},
			"create-approval-rule-template":                       {"ApprovalRuleTemplateContent", "ApprovalRuleTemplateDescription", "ApprovalRuleTemplateName"},
			"create-branch":                                       {"BranchName", "CommitId", "RepositoryName"},
			"create-commit":                                       {"AuthorName", "BranchName", "CommitMessage", "DeleteFiles", "Email", "KeepEmptyFolders", "ParentCommitId", "PutFiles", "RepositoryName", "SetFileModes"},
			"create-pull-request":                                 {"ClientRequestToken", "Description", "Targets", "Title"},
			"create-pull-request-approval-rule":                   {"ApprovalRuleContent", "ApprovalRuleName", "PullRequestId"},
			"create-repository":                                   {"KmsKeyId", "RepositoryDescription", "RepositoryName", "Tags"},
			"create-unreferenced-merge-commit":                    {"AuthorName", "CommitMessage", "ConflictDetailLevel", "ConflictResolution", "ConflictResolutionStrategy", "DestinationCommitSpecifier", "Email", "KeepEmptyFolders", "MergeOption", "RepositoryName", "SourceCommitSpecifier"},
			"delete-approval-rule-template":                       {"ApprovalRuleTemplateName"},
			"delete-branch":                                       {"BranchName", "RepositoryName"},
			"delete-comment-content":                              {"CommentId"},
			"delete-file":                                         {"BranchName", "CommitMessage", "Email", "FilePath", "KeepEmptyFolders", "Name", "ParentCommitId", "RepositoryName"},
			"delete-pull-request-approval-rule":                   {"ApprovalRuleName", "PullRequestId"},
			"delete-repository":                                   {"RepositoryName"},
			"describe-merge-conflicts":                            {"ConflictDetailLevel", "ConflictResolutionStrategy", "DestinationCommitSpecifier", "FilePath", "MaxMergeHunks", "MergeOption", "NextToken", "RepositoryName", "SourceCommitSpecifier"},
			"describe-pull-request-events":                        {"ActorArn", "MaxResults", "NextToken", "PullRequestEventType", "PullRequestId"},
			"disassociate-approval-rule-template-from-repository": {"ApprovalRuleTemplateName", "RepositoryName"},
			"evaluate-pull-request-approval-rules":                {"PullRequestId", "RevisionId"},
			"get-approval-rule-template":                          {"ApprovalRuleTemplateName"},
			"get-blob":                                            {"BlobId", "RepositoryName"},
			"get-branch":                                          {"BranchName", "RepositoryName"},
			"get-comment":                                         {"CommentId"},
			"get-comment-reactions":                               {"CommentId", "MaxResults", "NextToken", "ReactionUserArn"},
			"get-comments-for-compared-commit":                    {"AfterCommitId", "BeforeCommitId", "MaxResults", "NextToken", "RepositoryName"},
			"get-comments-for-pull-request":                       {"AfterCommitId", "BeforeCommitId", "MaxResults", "NextToken", "PullRequestId", "RepositoryName"},
			"get-commit":                                          {"CommitId", "RepositoryName"},
			"get-differences":                                     {"AfterCommitSpecifier", "AfterPath", "BeforeCommitSpecifier", "BeforePath", "MaxResults", "NextToken", "RepositoryName"},
			"get-file":                                            {"CommitSpecifier", "FilePath", "RepositoryName"},
			"get-folder":                                          {"CommitSpecifier", "FolderPath", "RepositoryName"},
			"get-merge-commit":                                    {"ConflictDetailLevel", "ConflictResolutionStrategy", "DestinationCommitSpecifier", "RepositoryName", "SourceCommitSpecifier"},
			"get-merge-conflicts":                                 {"ConflictDetailLevel", "ConflictResolutionStrategy", "DestinationCommitSpecifier", "MaxConflictFiles", "MergeOption", "NextToken", "RepositoryName", "SourceCommitSpecifier"},
			"get-merge-options":                                   {"ConflictDetailLevel", "ConflictResolutionStrategy", "DestinationCommitSpecifier", "RepositoryName", "SourceCommitSpecifier"},
			"get-pull-request":                                    {"PullRequestId"},
			"get-pull-request-approval-states":                    {"PullRequestId", "RevisionId"},
			"get-pull-request-override-state":                     {"PullRequestId", "RevisionId"},
			"get-repository":                                      {"RepositoryName"},
			"get-repository-triggers":                             {"RepositoryName"},
			"list-approval-rule-templates":                        {"MaxResults", "NextToken"},
			"list-associated-approval-rule-templates-for-repository": {"MaxResults", "NextToken", "RepositoryName"},
			"list-branches":                                {"NextToken", "RepositoryName"},
			"list-file-commit-history":                     {"CommitSpecifier", "FilePath", "MaxResults", "NextToken", "RepositoryName"},
			"list-pull-requests":                           {"AuthorArn", "MaxResults", "NextToken", "PullRequestStatus", "RepositoryName"},
			"list-repositories":                            {"NextToken", "Order", "SortBy"},
			"list-repositories-for-approval-rule-template": {"ApprovalRuleTemplateName", "MaxResults", "NextToken"},
			"list-tags-for-resource":                       {"NextToken", "ResourceArn"},
			"merge-branches-by-fast-forward":               {"DestinationCommitSpecifier", "RepositoryName", "SourceCommitSpecifier", "TargetBranch"},
			"merge-branches-by-squash":                     {"AuthorName", "CommitMessage", "ConflictDetailLevel", "ConflictResolution", "ConflictResolutionStrategy", "DestinationCommitSpecifier", "Email", "KeepEmptyFolders", "RepositoryName", "SourceCommitSpecifier", "TargetBranch"},
			"merge-branches-by-three-way":                  {"AuthorName", "CommitMessage", "ConflictDetailLevel", "ConflictResolution", "ConflictResolutionStrategy", "DestinationCommitSpecifier", "Email", "KeepEmptyFolders", "RepositoryName", "SourceCommitSpecifier", "TargetBranch"},
			"merge-pull-request-by-fast-forward":           {"PullRequestId", "RepositoryName", "SourceCommitId"},
			"merge-pull-request-by-squash":                 {"AuthorName", "CommitMessage", "ConflictDetailLevel", "ConflictResolution", "ConflictResolutionStrategy", "Email", "KeepEmptyFolders", "PullRequestId", "RepositoryName", "SourceCommitId"},
			"merge-pull-request-by-three-way":              {"AuthorName", "CommitMessage", "ConflictDetailLevel", "ConflictResolution", "ConflictResolutionStrategy", "Email", "KeepEmptyFolders", "PullRequestId", "RepositoryName", "SourceCommitId"},
			"override-pull-request-approval-rules":         {"OverrideStatus", "PullRequestId", "RevisionId"},
			"post-comment-for-compared-commit":             {"AfterCommitId", "BeforeCommitId", "ClientRequestToken", "Content", "Location", "RepositoryName"},
			"post-comment-for-pull-request":                {"AfterCommitId", "BeforeCommitId", "ClientRequestToken", "Content", "Location", "PullRequestId", "RepositoryName"},
			"post-comment-reply":                           {"ClientRequestToken", "Content", "InReplyTo"},
			"put-comment-reaction":                         {"CommentId", "ReactionValue"},
			"put-file":                                     {"BranchName", "CommitMessage", "Email", "FileContent", "FileMode", "FilePath", "Name", "ParentCommitId", "RepositoryName"},
			"put-repository-triggers":                      {"RepositoryName", "Triggers"},
			"tag-resource":                                 {"ResourceArn", "Tags"},
			"test-repository-triggers":                     {"RepositoryName", "Triggers"},
			"untag-resource":                               {"ResourceArn", "TagKeys"},
			"update-approval-rule-template-content":        {"ApprovalRuleTemplateName", "ExistingRuleContentSha256", "NewRuleContent"},
			"update-approval-rule-template-description":    {"ApprovalRuleTemplateDescription", "ApprovalRuleTemplateName"},
			"update-approval-rule-template-name":           {"NewApprovalRuleTemplateName", "OldApprovalRuleTemplateName"},
			"update-comment":                               {"CommentId", "Content"},
			"update-default-branch":                        {"DefaultBranchName", "RepositoryName"},
			"update-pull-request-approval-rule-content":    {"ApprovalRuleName", "ExistingRuleContentSha256", "NewRuleContent", "PullRequestId"},
			"update-pull-request-approval-state":           {"ApprovalState", "PullRequestId", "RevisionId"},
			"update-pull-request-description":              {"Description", "PullRequestId"},
			"update-pull-request-status":                   {"PullRequestId", "PullRequestStatus"},
			"update-pull-request-title":                    {"PullRequestId", "Title"},
			"update-repository-description":                {"RepositoryDescription", "RepositoryName"},
			"update-repository-encryption-key":             {"KmsKeyId", "RepositoryName"},
			"update-repository-name":                       {"NewName", "OldName"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-approval-rule-template-with-repository":            {"ApprovalRuleTemplateName": "*string", "RepositoryName": "*string"},
			"batch-associate-approval-rule-template-with-repositories":    {"ApprovalRuleTemplateName": "*string", "RepositoryNames": "[]string"},
			"batch-describe-merge-conflicts":                              {"ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "DestinationCommitSpecifier": "*string", "FilePaths": "[]string", "MaxConflictFiles": "*int32", "MaxMergeHunks": "*int32", "MergeOption": "types.MergeOptionTypeEnum", "NextToken": "*string", "RepositoryName": "*string", "SourceCommitSpecifier": "*string"},
			"batch-disassociate-approval-rule-template-from-repositories": {"ApprovalRuleTemplateName": "*string", "RepositoryNames": "[]string"},
			"batch-get-commits":                                   {"CommitIds": "[]string", "RepositoryName": "*string"},
			"batch-get-repositories":                              {"RepositoryNames": "[]string"},
			"create-approval-rule-template":                       {"ApprovalRuleTemplateContent": "*string", "ApprovalRuleTemplateDescription": "*string", "ApprovalRuleTemplateName": "*string"},
			"create-branch":                                       {"BranchName": "*string", "CommitId": "*string", "RepositoryName": "*string"},
			"create-commit":                                       {"AuthorName": "*string", "BranchName": "*string", "CommitMessage": "*string", "DeleteFiles": "[]types.DeleteFileEntry", "Email": "*string", "KeepEmptyFolders": "bool", "ParentCommitId": "*string", "PutFiles": "[]types.PutFileEntry", "RepositoryName": "*string", "SetFileModes": "[]types.SetFileModeEntry"},
			"create-pull-request":                                 {"ClientRequestToken": "*string", "Description": "*string", "Targets": "[]types.Target", "Title": "*string"},
			"create-pull-request-approval-rule":                   {"ApprovalRuleContent": "*string", "ApprovalRuleName": "*string", "PullRequestId": "*string"},
			"create-repository":                                   {"KmsKeyId": "*string", "RepositoryDescription": "*string", "RepositoryName": "*string", "Tags": "map[string]string"},
			"create-unreferenced-merge-commit":                    {"AuthorName": "*string", "CommitMessage": "*string", "ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolution": "*types.ConflictResolution", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "DestinationCommitSpecifier": "*string", "Email": "*string", "KeepEmptyFolders": "bool", "MergeOption": "types.MergeOptionTypeEnum", "RepositoryName": "*string", "SourceCommitSpecifier": "*string"},
			"delete-approval-rule-template":                       {"ApprovalRuleTemplateName": "*string"},
			"delete-branch":                                       {"BranchName": "*string", "RepositoryName": "*string"},
			"delete-comment-content":                              {"CommentId": "*string"},
			"delete-file":                                         {"BranchName": "*string", "CommitMessage": "*string", "Email": "*string", "FilePath": "*string", "KeepEmptyFolders": "bool", "Name": "*string", "ParentCommitId": "*string", "RepositoryName": "*string"},
			"delete-pull-request-approval-rule":                   {"ApprovalRuleName": "*string", "PullRequestId": "*string"},
			"delete-repository":                                   {"RepositoryName": "*string"},
			"describe-merge-conflicts":                            {"ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "DestinationCommitSpecifier": "*string", "FilePath": "*string", "MaxMergeHunks": "*int32", "MergeOption": "types.MergeOptionTypeEnum", "NextToken": "*string", "RepositoryName": "*string", "SourceCommitSpecifier": "*string"},
			"describe-pull-request-events":                        {"ActorArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PullRequestEventType": "types.PullRequestEventType", "PullRequestId": "*string"},
			"disassociate-approval-rule-template-from-repository": {"ApprovalRuleTemplateName": "*string", "RepositoryName": "*string"},
			"evaluate-pull-request-approval-rules":                {"PullRequestId": "*string", "RevisionId": "*string"},
			"get-approval-rule-template":                          {"ApprovalRuleTemplateName": "*string"},
			"get-blob":                                            {"BlobId": "*string", "RepositoryName": "*string"},
			"get-branch":                                          {"BranchName": "*string", "RepositoryName": "*string"},
			"get-comment":                                         {"CommentId": "*string"},
			"get-comment-reactions":                               {"CommentId": "*string", "MaxResults": "*int32", "NextToken": "*string", "ReactionUserArn": "*string"},
			"get-comments-for-compared-commit":                    {"AfterCommitId": "*string", "BeforeCommitId": "*string", "MaxResults": "*int32", "NextToken": "*string", "RepositoryName": "*string"},
			"get-comments-for-pull-request":                       {"AfterCommitId": "*string", "BeforeCommitId": "*string", "MaxResults": "*int32", "NextToken": "*string", "PullRequestId": "*string", "RepositoryName": "*string"},
			"get-commit":                                          {"CommitId": "*string", "RepositoryName": "*string"},
			"get-differences":                                     {"AfterCommitSpecifier": "*string", "AfterPath": "*string", "BeforeCommitSpecifier": "*string", "BeforePath": "*string", "MaxResults": "*int32", "NextToken": "*string", "RepositoryName": "*string"},
			"get-file":                                            {"CommitSpecifier": "*string", "FilePath": "*string", "RepositoryName": "*string"},
			"get-folder":                                          {"CommitSpecifier": "*string", "FolderPath": "*string", "RepositoryName": "*string"},
			"get-merge-commit":                                    {"ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "DestinationCommitSpecifier": "*string", "RepositoryName": "*string", "SourceCommitSpecifier": "*string"},
			"get-merge-conflicts":                                 {"ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "DestinationCommitSpecifier": "*string", "MaxConflictFiles": "*int32", "MergeOption": "types.MergeOptionTypeEnum", "NextToken": "*string", "RepositoryName": "*string", "SourceCommitSpecifier": "*string"},
			"get-merge-options":                                   {"ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "DestinationCommitSpecifier": "*string", "RepositoryName": "*string", "SourceCommitSpecifier": "*string"},
			"get-pull-request":                                    {"PullRequestId": "*string"},
			"get-pull-request-approval-states":                    {"PullRequestId": "*string", "RevisionId": "*string"},
			"get-pull-request-override-state":                     {"PullRequestId": "*string", "RevisionId": "*string"},
			"get-repository":                                      {"RepositoryName": "*string"},
			"get-repository-triggers":                             {"RepositoryName": "*string"},
			"list-approval-rule-templates":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-associated-approval-rule-templates-for-repository": {"MaxResults": "*int32", "NextToken": "*string", "RepositoryName": "*string"},
			"list-branches":                                {"NextToken": "*string", "RepositoryName": "*string"},
			"list-file-commit-history":                     {"CommitSpecifier": "*string", "FilePath": "*string", "MaxResults": "*int32", "NextToken": "*string", "RepositoryName": "*string"},
			"list-pull-requests":                           {"AuthorArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PullRequestStatus": "types.PullRequestStatusEnum", "RepositoryName": "*string"},
			"list-repositories":                            {"NextToken": "*string", "Order": "types.OrderEnum", "SortBy": "types.SortByEnum"},
			"list-repositories-for-approval-rule-template": {"ApprovalRuleTemplateName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                       {"NextToken": "*string", "ResourceArn": "*string"},
			"merge-branches-by-fast-forward":               {"DestinationCommitSpecifier": "*string", "RepositoryName": "*string", "SourceCommitSpecifier": "*string", "TargetBranch": "*string"},
			"merge-branches-by-squash":                     {"AuthorName": "*string", "CommitMessage": "*string", "ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolution": "*types.ConflictResolution", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "DestinationCommitSpecifier": "*string", "Email": "*string", "KeepEmptyFolders": "bool", "RepositoryName": "*string", "SourceCommitSpecifier": "*string", "TargetBranch": "*string"},
			"merge-branches-by-three-way":                  {"AuthorName": "*string", "CommitMessage": "*string", "ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolution": "*types.ConflictResolution", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "DestinationCommitSpecifier": "*string", "Email": "*string", "KeepEmptyFolders": "bool", "RepositoryName": "*string", "SourceCommitSpecifier": "*string", "TargetBranch": "*string"},
			"merge-pull-request-by-fast-forward":           {"PullRequestId": "*string", "RepositoryName": "*string", "SourceCommitId": "*string"},
			"merge-pull-request-by-squash":                 {"AuthorName": "*string", "CommitMessage": "*string", "ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolution": "*types.ConflictResolution", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "Email": "*string", "KeepEmptyFolders": "bool", "PullRequestId": "*string", "RepositoryName": "*string", "SourceCommitId": "*string"},
			"merge-pull-request-by-three-way":              {"AuthorName": "*string", "CommitMessage": "*string", "ConflictDetailLevel": "types.ConflictDetailLevelTypeEnum", "ConflictResolution": "*types.ConflictResolution", "ConflictResolutionStrategy": "types.ConflictResolutionStrategyTypeEnum", "Email": "*string", "KeepEmptyFolders": "bool", "PullRequestId": "*string", "RepositoryName": "*string", "SourceCommitId": "*string"},
			"override-pull-request-approval-rules":         {"OverrideStatus": "types.OverrideStatus", "PullRequestId": "*string", "RevisionId": "*string"},
			"post-comment-for-compared-commit":             {"AfterCommitId": "*string", "BeforeCommitId": "*string", "ClientRequestToken": "*string", "Content": "*string", "Location": "*types.Location", "RepositoryName": "*string"},
			"post-comment-for-pull-request":                {"AfterCommitId": "*string", "BeforeCommitId": "*string", "ClientRequestToken": "*string", "Content": "*string", "Location": "*types.Location", "PullRequestId": "*string", "RepositoryName": "*string"},
			"post-comment-reply":                           {"ClientRequestToken": "*string", "Content": "*string", "InReplyTo": "*string"},
			"put-comment-reaction":                         {"CommentId": "*string", "ReactionValue": "*string"},
			"put-file":                                     {"BranchName": "*string", "CommitMessage": "*string", "Email": "*string", "FileContent": "[]byte", "FileMode": "types.FileModeTypeEnum", "FilePath": "*string", "Name": "*string", "ParentCommitId": "*string", "RepositoryName": "*string"},
			"put-repository-triggers":                      {"RepositoryName": "*string", "Triggers": "[]types.RepositoryTrigger"},
			"tag-resource":                                 {"ResourceArn": "*string", "Tags": "map[string]string"},
			"test-repository-triggers":                     {"RepositoryName": "*string", "Triggers": "[]types.RepositoryTrigger"},
			"untag-resource":                               {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-approval-rule-template-content":        {"ApprovalRuleTemplateName": "*string", "ExistingRuleContentSha256": "*string", "NewRuleContent": "*string"},
			"update-approval-rule-template-description":    {"ApprovalRuleTemplateDescription": "*string", "ApprovalRuleTemplateName": "*string"},
			"update-approval-rule-template-name":           {"NewApprovalRuleTemplateName": "*string", "OldApprovalRuleTemplateName": "*string"},
			"update-comment":                               {"CommentId": "*string", "Content": "*string"},
			"update-default-branch":                        {"DefaultBranchName": "*string", "RepositoryName": "*string"},
			"update-pull-request-approval-rule-content":    {"ApprovalRuleName": "*string", "ExistingRuleContentSha256": "*string", "NewRuleContent": "*string", "PullRequestId": "*string"},
			"update-pull-request-approval-state":           {"ApprovalState": "types.ApprovalState", "PullRequestId": "*string", "RevisionId": "*string"},
			"update-pull-request-description":              {"Description": "*string", "PullRequestId": "*string"},
			"update-pull-request-status":                   {"PullRequestId": "*string", "PullRequestStatus": "types.PullRequestStatusEnum"},
			"update-pull-request-title":                    {"PullRequestId": "*string", "Title": "*string"},
			"update-repository-description":                {"RepositoryDescription": "*string", "RepositoryName": "*string"},
			"update-repository-encryption-key":             {"KmsKeyId": "*string", "RepositoryName": "*string"},
			"update-repository-name":                       {"NewName": "*string", "OldName": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-approval-rule-template-with-repository":            {"ApprovalRuleTemplateName", "RepositoryName"},
			"batch-associate-approval-rule-template-with-repositories":    {"ApprovalRuleTemplateName", "RepositoryNames"},
			"batch-describe-merge-conflicts":                              {"DestinationCommitSpecifier", "MergeOption", "RepositoryName", "SourceCommitSpecifier"},
			"batch-disassociate-approval-rule-template-from-repositories": {"ApprovalRuleTemplateName", "RepositoryNames"},
			"batch-get-commits":                                   {"CommitIds", "RepositoryName"},
			"batch-get-repositories":                              {"RepositoryNames"},
			"create-approval-rule-template":                       {"ApprovalRuleTemplateContent", "ApprovalRuleTemplateName"},
			"create-branch":                                       {"BranchName", "CommitId", "RepositoryName"},
			"create-commit":                                       {"BranchName", "RepositoryName"},
			"create-pull-request":                                 {"Targets", "Title"},
			"create-pull-request-approval-rule":                   {"ApprovalRuleContent", "ApprovalRuleName", "PullRequestId"},
			"create-repository":                                   {"RepositoryName"},
			"create-unreferenced-merge-commit":                    {"DestinationCommitSpecifier", "MergeOption", "RepositoryName", "SourceCommitSpecifier"},
			"delete-approval-rule-template":                       {"ApprovalRuleTemplateName"},
			"delete-branch":                                       {"BranchName", "RepositoryName"},
			"delete-comment-content":                              {"CommentId"},
			"delete-file":                                         {"BranchName", "FilePath", "ParentCommitId", "RepositoryName"},
			"delete-pull-request-approval-rule":                   {"ApprovalRuleName", "PullRequestId"},
			"delete-repository":                                   {"RepositoryName"},
			"describe-merge-conflicts":                            {"DestinationCommitSpecifier", "FilePath", "MergeOption", "RepositoryName", "SourceCommitSpecifier"},
			"describe-pull-request-events":                        {"PullRequestId"},
			"disassociate-approval-rule-template-from-repository": {"ApprovalRuleTemplateName", "RepositoryName"},
			"evaluate-pull-request-approval-rules":                {"PullRequestId", "RevisionId"},
			"get-approval-rule-template":                          {"ApprovalRuleTemplateName"},
			"get-blob":                                            {"BlobId", "RepositoryName"},
			"get-branch":                                          {},
			"get-comment":                                         {"CommentId"},
			"get-comment-reactions":                               {"CommentId"},
			"get-comments-for-compared-commit":                    {"AfterCommitId", "RepositoryName"},
			"get-comments-for-pull-request":                       {"PullRequestId"},
			"get-commit":                                          {"CommitId", "RepositoryName"},
			"get-differences":                                     {"AfterCommitSpecifier", "RepositoryName"},
			"get-file":                                            {"FilePath", "RepositoryName"},
			"get-folder":                                          {"FolderPath", "RepositoryName"},
			"get-merge-commit":                                    {"DestinationCommitSpecifier", "RepositoryName", "SourceCommitSpecifier"},
			"get-merge-conflicts":                                 {"DestinationCommitSpecifier", "MergeOption", "RepositoryName", "SourceCommitSpecifier"},
			"get-merge-options":                                   {"DestinationCommitSpecifier", "RepositoryName", "SourceCommitSpecifier"},
			"get-pull-request":                                    {"PullRequestId"},
			"get-pull-request-approval-states":                    {"PullRequestId", "RevisionId"},
			"get-pull-request-override-state":                     {"PullRequestId", "RevisionId"},
			"get-repository":                                      {"RepositoryName"},
			"get-repository-triggers":                             {"RepositoryName"},
			"list-approval-rule-templates":                        {},
			"list-associated-approval-rule-templates-for-repository": {"RepositoryName"},
			"list-branches":                                {"RepositoryName"},
			"list-file-commit-history":                     {"FilePath", "RepositoryName"},
			"list-pull-requests":                           {"RepositoryName"},
			"list-repositories":                            {},
			"list-repositories-for-approval-rule-template": {"ApprovalRuleTemplateName"},
			"list-tags-for-resource":                       {"ResourceArn"},
			"merge-branches-by-fast-forward":               {"DestinationCommitSpecifier", "RepositoryName", "SourceCommitSpecifier"},
			"merge-branches-by-squash":                     {"DestinationCommitSpecifier", "RepositoryName", "SourceCommitSpecifier"},
			"merge-branches-by-three-way":                  {"DestinationCommitSpecifier", "RepositoryName", "SourceCommitSpecifier"},
			"merge-pull-request-by-fast-forward":           {"PullRequestId", "RepositoryName"},
			"merge-pull-request-by-squash":                 {"PullRequestId", "RepositoryName"},
			"merge-pull-request-by-three-way":              {"PullRequestId", "RepositoryName"},
			"override-pull-request-approval-rules":         {"OverrideStatus", "PullRequestId", "RevisionId"},
			"post-comment-for-compared-commit":             {"AfterCommitId", "Content", "RepositoryName"},
			"post-comment-for-pull-request":                {"AfterCommitId", "BeforeCommitId", "Content", "PullRequestId", "RepositoryName"},
			"post-comment-reply":                           {"Content", "InReplyTo"},
			"put-comment-reaction":                         {"CommentId", "ReactionValue"},
			"put-file":                                     {"BranchName", "FileContent", "FilePath", "RepositoryName"},
			"put-repository-triggers":                      {"RepositoryName", "Triggers"},
			"tag-resource":                                 {"ResourceArn", "Tags"},
			"test-repository-triggers":                     {"RepositoryName", "Triggers"},
			"untag-resource":                               {"ResourceArn", "TagKeys"},
			"update-approval-rule-template-content":        {"ApprovalRuleTemplateName", "NewRuleContent"},
			"update-approval-rule-template-description":    {"ApprovalRuleTemplateDescription", "ApprovalRuleTemplateName"},
			"update-approval-rule-template-name":           {"NewApprovalRuleTemplateName", "OldApprovalRuleTemplateName"},
			"update-comment":                               {"CommentId", "Content"},
			"update-default-branch":                        {"DefaultBranchName", "RepositoryName"},
			"update-pull-request-approval-rule-content":    {"ApprovalRuleName", "NewRuleContent", "PullRequestId"},
			"update-pull-request-approval-state":           {"ApprovalState", "PullRequestId", "RevisionId"},
			"update-pull-request-description":              {"Description", "PullRequestId"},
			"update-pull-request-status":                   {"PullRequestId", "PullRequestStatus"},
			"update-pull-request-title":                    {"PullRequestId", "Title"},
			"update-repository-description":                {"RepositoryName"},
			"update-repository-encryption-key":             {"KmsKeyId", "RepositoryName"},
			"update-repository-name":                       {"NewName", "OldName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("codecommit", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
