package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/connectcampaignsv2/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-campaign", "delete-campaign", "delete-campaign-channel-subtype-config", "delete-campaign-communication-limits", "delete-campaign-communication-time", "delete-connect-instance-config", "delete-connect-instance-integration", "delete-instance-onboarding-job", "describe-campaign", "get-campaign-state", "get-campaign-state-batch", "get-connect-instance-config", "get-instance-communication-limits", "get-instance-onboarding-job-status", "list-campaigns", "list-connect-instance-integrations", "list-tags-for-resource", "pause-campaign", "put-connect-instance-integration", "put-instance-communication-limits", "put-outbound-request-batch", "put-profile-outbound-request-batch", "resume-campaign", "start-campaign", "start-instance-onboarding-job", "stop-campaign", "tag-resource", "untag-resource", "update-campaign-channel-subtype-config", "update-campaign-communication-limits", "update-campaign-communication-time", "update-campaign-flow-association", "update-campaign-name", "update-campaign-schedule", "update-campaign-source"},
		OperationSet: map[string]bool{"create-campaign": true, "delete-campaign": true, "delete-campaign-channel-subtype-config": true, "delete-campaign-communication-limits": true, "delete-campaign-communication-time": true, "delete-connect-instance-config": true, "delete-connect-instance-integration": true, "delete-instance-onboarding-job": true, "describe-campaign": true, "get-campaign-state": true, "get-campaign-state-batch": true, "get-connect-instance-config": true, "get-instance-communication-limits": true, "get-instance-onboarding-job-status": true, "list-campaigns": true, "list-connect-instance-integrations": true, "list-tags-for-resource": true, "pause-campaign": true, "put-connect-instance-integration": true, "put-instance-communication-limits": true, "put-outbound-request-batch": true, "put-profile-outbound-request-batch": true, "resume-campaign": true, "start-campaign": true, "start-instance-onboarding-job": true, "stop-campaign": true, "tag-resource": true, "untag-resource": true, "update-campaign-channel-subtype-config": true, "update-campaign-communication-limits": true, "update-campaign-communication-time": true, "update-campaign-flow-association": true, "update-campaign-name": true, "update-campaign-schedule": true, "update-campaign-source": true},
		OperationInputs: map[string][]string{
			"create-campaign":                        {"ChannelSubtypeConfig", "CommunicationLimitsOverride", "CommunicationTimeConfig", "ConnectCampaignFlowArn", "ConnectInstanceId", "Name", "Schedule", "Source", "Tags", "Type"},
			"delete-campaign":                        {"Id"},
			"delete-campaign-channel-subtype-config": {"ChannelSubtype", "Id"},
			"delete-campaign-communication-limits":   {"Config", "Id"},
			"delete-campaign-communication-time":     {"Config", "Id"},
			"delete-connect-instance-config":         {"CampaignDeletionPolicy", "ConnectInstanceId"},
			"delete-connect-instance-integration":    {"ConnectInstanceId", "IntegrationIdentifier"},
			"delete-instance-onboarding-job":         {"ConnectInstanceId"},
			"describe-campaign":                      {"Id"},
			"get-campaign-state":                     {"Id"},
			"get-campaign-state-batch":               {"CampaignIds"},
			"get-connect-instance-config":            {"ConnectInstanceId"},
			"get-instance-communication-limits":      {"ConnectInstanceId"},
			"get-instance-onboarding-job-status":     {"ConnectInstanceId"},
			"list-campaigns":                         {"Filters", "MaxResults", "NextToken"},
			"list-connect-instance-integrations":     {"ConnectInstanceId", "MaxResults", "NextToken"},
			"list-tags-for-resource":                 {"Arn"},
			"pause-campaign":                         {"Id"},
			"put-connect-instance-integration":       {"ConnectInstanceId", "IntegrationConfig"},
			"put-instance-communication-limits":      {"CommunicationLimitsConfig", "ConnectInstanceId"},
			"put-outbound-request-batch":             {"Id", "OutboundRequests"},
			"put-profile-outbound-request-batch":     {"Id", "ProfileOutboundRequests"},
			"resume-campaign":                        {"Id"},
			"start-campaign":                         {"Id"},
			"start-instance-onboarding-job":          {"ConnectInstanceId", "EncryptionConfig"},
			"stop-campaign":                          {"Id"},
			"tag-resource":                           {"Arn", "Tags"},
			"untag-resource":                         {"Arn", "TagKeys"},
			"update-campaign-channel-subtype-config": {"ChannelSubtypeConfig", "Id"},
			"update-campaign-communication-limits":   {"CommunicationLimitsOverride", "Id"},
			"update-campaign-communication-time":     {"CommunicationTimeConfig", "Id"},
			"update-campaign-flow-association":       {"ConnectCampaignFlowArn", "Id"},
			"update-campaign-name":                   {"Id", "Name"},
			"update-campaign-schedule":               {"Id", "Schedule"},
			"update-campaign-source":                 {"Id", "Source"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-campaign":                        {"ChannelSubtypeConfig": "*types.ChannelSubtypeConfig", "CommunicationLimitsOverride": "*types.CommunicationLimitsConfig", "CommunicationTimeConfig": "*types.CommunicationTimeConfig", "ConnectCampaignFlowArn": "*string", "ConnectInstanceId": "*string", "Name": "*string", "Schedule": "*types.Schedule", "Source": "types.Source", "Tags": "map[string]string", "Type": "types.ExternalCampaignType"},
			"delete-campaign":                        {"Id": "*string"},
			"delete-campaign-channel-subtype-config": {"ChannelSubtype": "types.ChannelSubtype", "Id": "*string"},
			"delete-campaign-communication-limits":   {"Config": "types.CommunicationLimitsConfigType", "Id": "*string"},
			"delete-campaign-communication-time":     {"Config": "types.CommunicationTimeConfigType", "Id": "*string"},
			"delete-connect-instance-config":         {"CampaignDeletionPolicy": "types.CampaignDeletionPolicy", "ConnectInstanceId": "*string"},
			"delete-connect-instance-integration":    {"ConnectInstanceId": "*string", "IntegrationIdentifier": "types.IntegrationIdentifier"},
			"delete-instance-onboarding-job":         {"ConnectInstanceId": "*string"},
			"describe-campaign":                      {"Id": "*string"},
			"get-campaign-state":                     {"Id": "*string"},
			"get-campaign-state-batch":               {"CampaignIds": "[]string"},
			"get-connect-instance-config":            {"ConnectInstanceId": "*string"},
			"get-instance-communication-limits":      {"ConnectInstanceId": "*string"},
			"get-instance-onboarding-job-status":     {"ConnectInstanceId": "*string"},
			"list-campaigns":                         {"Filters": "*types.CampaignFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"list-connect-instance-integrations":     {"ConnectInstanceId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                 {"Arn": "*string"},
			"pause-campaign":                         {"Id": "*string"},
			"put-connect-instance-integration":       {"ConnectInstanceId": "*string", "IntegrationConfig": "types.IntegrationConfig"},
			"put-instance-communication-limits":      {"CommunicationLimitsConfig": "*types.InstanceCommunicationLimitsConfig", "ConnectInstanceId": "*string"},
			"put-outbound-request-batch":             {"Id": "*string", "OutboundRequests": "[]types.OutboundRequest"},
			"put-profile-outbound-request-batch":     {"Id": "*string", "ProfileOutboundRequests": "[]types.ProfileOutboundRequest"},
			"resume-campaign":                        {"Id": "*string"},
			"start-campaign":                         {"Id": "*string"},
			"start-instance-onboarding-job":          {"ConnectInstanceId": "*string", "EncryptionConfig": "*types.EncryptionConfig"},
			"stop-campaign":                          {"Id": "*string"},
			"tag-resource":                           {"Arn": "*string", "Tags": "map[string]string"},
			"untag-resource":                         {"Arn": "*string", "TagKeys": "[]string"},
			"update-campaign-channel-subtype-config": {"ChannelSubtypeConfig": "*types.ChannelSubtypeConfig", "Id": "*string"},
			"update-campaign-communication-limits":   {"CommunicationLimitsOverride": "*types.CommunicationLimitsConfig", "Id": "*string"},
			"update-campaign-communication-time":     {"CommunicationTimeConfig": "*types.CommunicationTimeConfig", "Id": "*string"},
			"update-campaign-flow-association":       {"ConnectCampaignFlowArn": "*string", "Id": "*string"},
			"update-campaign-name":                   {"Id": "*string", "Name": "*string"},
			"update-campaign-schedule":               {"Id": "*string", "Schedule": "*types.Schedule"},
			"update-campaign-source":                 {"Id": "*string", "Source": "types.Source"},
		},
		OperationInputRequired: map[string][]string{
			"create-campaign":                        {"ConnectInstanceId", "Name"},
			"delete-campaign":                        {"Id"},
			"delete-campaign-channel-subtype-config": {"ChannelSubtype", "Id"},
			"delete-campaign-communication-limits":   {"Config", "Id"},
			"delete-campaign-communication-time":     {"Config", "Id"},
			"delete-connect-instance-config":         {"ConnectInstanceId"},
			"delete-connect-instance-integration":    {"ConnectInstanceId", "IntegrationIdentifier"},
			"delete-instance-onboarding-job":         {"ConnectInstanceId"},
			"describe-campaign":                      {"Id"},
			"get-campaign-state":                     {"Id"},
			"get-campaign-state-batch":               {"CampaignIds"},
			"get-connect-instance-config":            {"ConnectInstanceId"},
			"get-instance-communication-limits":      {"ConnectInstanceId"},
			"get-instance-onboarding-job-status":     {"ConnectInstanceId"},
			"list-campaigns":                         {},
			"list-connect-instance-integrations":     {"ConnectInstanceId"},
			"list-tags-for-resource":                 {"Arn"},
			"pause-campaign":                         {"Id"},
			"put-connect-instance-integration":       {"ConnectInstanceId", "IntegrationConfig"},
			"put-instance-communication-limits":      {"CommunicationLimitsConfig", "ConnectInstanceId"},
			"put-outbound-request-batch":             {"Id", "OutboundRequests"},
			"put-profile-outbound-request-batch":     {"Id", "ProfileOutboundRequests"},
			"resume-campaign":                        {"Id"},
			"start-campaign":                         {"Id"},
			"start-instance-onboarding-job":          {"ConnectInstanceId", "EncryptionConfig"},
			"stop-campaign":                          {"Id"},
			"tag-resource":                           {"Arn", "Tags"},
			"untag-resource":                         {"Arn", "TagKeys"},
			"update-campaign-channel-subtype-config": {"ChannelSubtypeConfig", "Id"},
			"update-campaign-communication-limits":   {"CommunicationLimitsOverride", "Id"},
			"update-campaign-communication-time":     {"CommunicationTimeConfig", "Id"},
			"update-campaign-flow-association":       {"ConnectCampaignFlowArn", "Id"},
			"update-campaign-name":                   {"Id", "Name"},
			"update-campaign-schedule":               {"Id", "Schedule"},
			"update-campaign-source":                 {"Id", "Source"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("connectcampaignsv2", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
