package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/gamelift/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-match", "claim-game-server", "create-alias", "create-build", "create-container-fleet", "create-container-group-definition", "create-fleet", "create-fleet-locations", "create-game-server-group", "create-game-session", "create-game-session-queue", "create-location", "create-matchmaking-configuration", "create-matchmaking-rule-set", "create-player-session", "create-player-sessions", "create-script", "create-vpc-peering-authorization", "create-vpc-peering-connection", "delete-alias", "delete-build", "delete-container-fleet", "delete-container-group-definition", "delete-fleet", "delete-fleet-locations", "delete-game-server-group", "delete-game-session-queue", "delete-location", "delete-matchmaking-configuration", "delete-matchmaking-rule-set", "delete-scaling-policy", "delete-script", "delete-vpc-peering-authorization", "delete-vpc-peering-connection", "deregister-compute", "deregister-game-server", "describe-alias", "describe-build", "describe-compute", "describe-container-fleet", "describe-container-group-definition", "describe-ec2-instance-limits", "describe-fleet-attributes", "describe-fleet-capacity", "describe-fleet-deployment", "describe-fleet-events", "describe-fleet-location-attributes", "describe-fleet-location-capacity", "describe-fleet-location-utilization", "describe-fleet-port-settings", "describe-fleet-utilization", "describe-game-server", "describe-game-server-group", "describe-game-server-instances", "describe-game-session-details", "describe-game-session-placement", "describe-game-session-queues", "describe-game-sessions", "describe-instances", "describe-matchmaking", "describe-matchmaking-configurations", "describe-matchmaking-rule-sets", "describe-player-sessions", "describe-runtime-configuration", "describe-scaling-policies", "describe-script", "describe-vpc-peering-authorizations", "describe-vpc-peering-connections", "get-compute-access", "get-compute-auth-token", "get-game-session-log-url", "get-instance-access", "list-aliases", "list-builds", "list-compute", "list-container-fleets", "list-container-group-definition-versions", "list-container-group-definitions", "list-fleet-deployments", "list-fleets", "list-game-server-groups", "list-game-servers", "list-locations", "list-scripts", "list-tags-for-resource", "put-scaling-policy", "register-compute", "register-game-server", "request-upload-credentials", "resolve-alias", "resume-game-server-group", "search-game-sessions", "start-fleet-actions", "start-game-session-placement", "start-match-backfill", "start-matchmaking", "stop-fleet-actions", "stop-game-session-placement", "stop-matchmaking", "suspend-game-server-group", "tag-resource", "terminate-game-session", "untag-resource", "update-alias", "update-build", "update-container-fleet", "update-container-group-definition", "update-fleet-attributes", "update-fleet-capacity", "update-fleet-port-settings", "update-game-server", "update-game-server-group", "update-game-session", "update-game-session-queue", "update-matchmaking-configuration", "update-runtime-configuration", "update-script", "validate-matchmaking-rule-set"},
		OperationSet: map[string]bool{"accept-match": true, "claim-game-server": true, "create-alias": true, "create-build": true, "create-container-fleet": true, "create-container-group-definition": true, "create-fleet": true, "create-fleet-locations": true, "create-game-server-group": true, "create-game-session": true, "create-game-session-queue": true, "create-location": true, "create-matchmaking-configuration": true, "create-matchmaking-rule-set": true, "create-player-session": true, "create-player-sessions": true, "create-script": true, "create-vpc-peering-authorization": true, "create-vpc-peering-connection": true, "delete-alias": true, "delete-build": true, "delete-container-fleet": true, "delete-container-group-definition": true, "delete-fleet": true, "delete-fleet-locations": true, "delete-game-server-group": true, "delete-game-session-queue": true, "delete-location": true, "delete-matchmaking-configuration": true, "delete-matchmaking-rule-set": true, "delete-scaling-policy": true, "delete-script": true, "delete-vpc-peering-authorization": true, "delete-vpc-peering-connection": true, "deregister-compute": true, "deregister-game-server": true, "describe-alias": true, "describe-build": true, "describe-compute": true, "describe-container-fleet": true, "describe-container-group-definition": true, "describe-ec2-instance-limits": true, "describe-fleet-attributes": true, "describe-fleet-capacity": true, "describe-fleet-deployment": true, "describe-fleet-events": true, "describe-fleet-location-attributes": true, "describe-fleet-location-capacity": true, "describe-fleet-location-utilization": true, "describe-fleet-port-settings": true, "describe-fleet-utilization": true, "describe-game-server": true, "describe-game-server-group": true, "describe-game-server-instances": true, "describe-game-session-details": true, "describe-game-session-placement": true, "describe-game-session-queues": true, "describe-game-sessions": true, "describe-instances": true, "describe-matchmaking": true, "describe-matchmaking-configurations": true, "describe-matchmaking-rule-sets": true, "describe-player-sessions": true, "describe-runtime-configuration": true, "describe-scaling-policies": true, "describe-script": true, "describe-vpc-peering-authorizations": true, "describe-vpc-peering-connections": true, "get-compute-access": true, "get-compute-auth-token": true, "get-game-session-log-url": true, "get-instance-access": true, "list-aliases": true, "list-builds": true, "list-compute": true, "list-container-fleets": true, "list-container-group-definition-versions": true, "list-container-group-definitions": true, "list-fleet-deployments": true, "list-fleets": true, "list-game-server-groups": true, "list-game-servers": true, "list-locations": true, "list-scripts": true, "list-tags-for-resource": true, "put-scaling-policy": true, "register-compute": true, "register-game-server": true, "request-upload-credentials": true, "resolve-alias": true, "resume-game-server-group": true, "search-game-sessions": true, "start-fleet-actions": true, "start-game-session-placement": true, "start-match-backfill": true, "start-matchmaking": true, "stop-fleet-actions": true, "stop-game-session-placement": true, "stop-matchmaking": true, "suspend-game-server-group": true, "tag-resource": true, "terminate-game-session": true, "untag-resource": true, "update-alias": true, "update-build": true, "update-container-fleet": true, "update-container-group-definition": true, "update-fleet-attributes": true, "update-fleet-capacity": true, "update-fleet-port-settings": true, "update-game-server": true, "update-game-server-group": true, "update-game-session": true, "update-game-session-queue": true, "update-matchmaking-configuration": true, "update-runtime-configuration": true, "update-script": true, "validate-matchmaking-rule-set": true},
		OperationInputs: map[string][]string{
			"accept-match":                             {"AcceptanceType", "PlayerIds", "TicketId"},
			"claim-game-server":                        {"FilterOption", "GameServerData", "GameServerGroupName", "GameServerId"},
			"create-alias":                             {"Description", "Name", "RoutingStrategy", "Tags"},
			"create-build":                             {"Name", "OperatingSystem", "ServerSdkVersion", "StorageLocation", "Tags", "Version"},
			"create-container-fleet":                   {"BillingType", "Description", "FleetRoleArn", "GameServerContainerGroupDefinitionName", "GameServerContainerGroupsPerInstance", "GameSessionCreationLimitPolicy", "InstanceConnectionPortRange", "InstanceInboundPermissions", "InstanceType", "Locations", "LogConfiguration", "MetricGroups", "NewGameSessionProtectionPolicy", "PerInstanceContainerGroupDefinitionName", "Tags"},
			"create-container-group-definition":        {"ContainerGroupType", "GameServerContainerDefinition", "Name", "OperatingSystem", "SupportContainerDefinitions", "Tags", "TotalMemoryLimitMebibytes", "TotalVcpuLimit", "VersionDescription"},
			"create-fleet":                             {"AnywhereConfiguration", "BuildId", "CertificateConfiguration", "ComputeType", "Description", "EC2InboundPermissions", "EC2InstanceType", "FleetType", "InstanceRoleArn", "InstanceRoleCredentialsProvider", "Locations", "LogPaths", "MetricGroups", "Name", "NewGameSessionProtectionPolicy", "PeerVpcAwsAccountId", "PeerVpcId", "ResourceCreationLimitPolicy", "RuntimeConfiguration", "ScriptId", "ServerLaunchParameters", "ServerLaunchPath", "Tags"},
			"create-fleet-locations":                   {"FleetId", "Locations"},
			"create-game-server-group":                 {"AutoScalingPolicy", "BalancingStrategy", "GameServerGroupName", "GameServerProtectionPolicy", "InstanceDefinitions", "LaunchTemplate", "MaxSize", "MinSize", "RoleArn", "Tags", "VpcSubnets"},
			"create-game-session":                      {"AliasId", "CreatorId", "FleetId", "GameProperties", "GameSessionData", "GameSessionId", "IdempotencyToken", "Location", "MaximumPlayerSessionCount", "Name"},
			"create-game-session-queue":                {"CustomEventData", "Destinations", "FilterConfiguration", "Name", "NotificationTarget", "PlayerLatencyPolicies", "PriorityConfiguration", "Tags", "TimeoutInSeconds"},
			"create-location":                          {"LocationName", "Tags"},
			"create-matchmaking-configuration":         {"AcceptanceRequired", "AcceptanceTimeoutSeconds", "AdditionalPlayerCount", "BackfillMode", "CustomEventData", "Description", "FlexMatchMode", "GameProperties", "GameSessionData", "GameSessionQueueArns", "Name", "NotificationTarget", "RequestTimeoutSeconds", "RuleSetName", "Tags"},
			"create-matchmaking-rule-set":              {"Name", "RuleSetBody", "Tags"},
			"create-player-session":                    {"GameSessionId", "PlayerData", "PlayerId"},
			"create-player-sessions":                   {"GameSessionId", "PlayerDataMap", "PlayerIds"},
			"create-script":                            {"Name", "NodeJsVersion", "StorageLocation", "Tags", "Version", "ZipFile"},
			"create-vpc-peering-authorization":         {"GameLiftAwsAccountId", "PeerVpcId"},
			"create-vpc-peering-connection":            {"FleetId", "PeerVpcAwsAccountId", "PeerVpcId"},
			"delete-alias":                             {"AliasId"},
			"delete-build":                             {"BuildId"},
			"delete-container-fleet":                   {"FleetId"},
			"delete-container-group-definition":        {"Name", "VersionCountToRetain", "VersionNumber"},
			"delete-fleet":                             {"FleetId"},
			"delete-fleet-locations":                   {"FleetId", "Locations"},
			"delete-game-server-group":                 {"DeleteOption", "GameServerGroupName"},
			"delete-game-session-queue":                {"Name"},
			"delete-location":                          {"LocationName"},
			"delete-matchmaking-configuration":         {"Name"},
			"delete-matchmaking-rule-set":              {"Name"},
			"delete-scaling-policy":                    {"FleetId", "Name"},
			"delete-script":                            {"ScriptId"},
			"delete-vpc-peering-authorization":         {"GameLiftAwsAccountId", "PeerVpcId"},
			"delete-vpc-peering-connection":            {"FleetId", "VpcPeeringConnectionId"},
			"deregister-compute":                       {"ComputeName", "FleetId"},
			"deregister-game-server":                   {"GameServerGroupName", "GameServerId"},
			"describe-alias":                           {"AliasId"},
			"describe-build":                           {"BuildId"},
			"describe-compute":                         {"ComputeName", "FleetId"},
			"describe-container-fleet":                 {"FleetId"},
			"describe-container-group-definition":      {"Name", "VersionNumber"},
			"describe-ec2-instance-limits":             {"EC2InstanceType", "Location"},
			"describe-fleet-attributes":                {"FleetIds", "Limit", "NextToken"},
			"describe-fleet-capacity":                  {"FleetIds", "Limit", "NextToken"},
			"describe-fleet-deployment":                {"DeploymentId", "FleetId"},
			"describe-fleet-events":                    {"EndTime", "FleetId", "Limit", "NextToken", "StartTime"},
			"describe-fleet-location-attributes":       {"FleetId", "Limit", "Locations", "NextToken"},
			"describe-fleet-location-capacity":         {"FleetId", "Location"},
			"describe-fleet-location-utilization":      {"FleetId", "Location"},
			"describe-fleet-port-settings":             {"FleetId", "Location"},
			"describe-fleet-utilization":               {"FleetIds", "Limit", "NextToken"},
			"describe-game-server":                     {"GameServerGroupName", "GameServerId"},
			"describe-game-server-group":               {"GameServerGroupName"},
			"describe-game-server-instances":           {"GameServerGroupName", "InstanceIds", "Limit", "NextToken"},
			"describe-game-session-details":            {"AliasId", "FleetId", "GameSessionId", "Limit", "Location", "NextToken", "StatusFilter"},
			"describe-game-session-placement":          {"PlacementId"},
			"describe-game-session-queues":             {"Limit", "Names", "NextToken"},
			"describe-game-sessions":                   {"AliasId", "FleetId", "GameSessionId", "Limit", "Location", "NextToken", "StatusFilter"},
			"describe-instances":                       {"FleetId", "InstanceId", "Limit", "Location", "NextToken"},
			"describe-matchmaking":                     {"TicketIds"},
			"describe-matchmaking-configurations":      {"Limit", "Names", "NextToken", "RuleSetName"},
			"describe-matchmaking-rule-sets":           {"Limit", "Names", "NextToken"},
			"describe-player-sessions":                 {"GameSessionId", "Limit", "NextToken", "PlayerId", "PlayerSessionId", "PlayerSessionStatusFilter"},
			"describe-runtime-configuration":           {"FleetId"},
			"describe-scaling-policies":                {"FleetId", "Limit", "Location", "NextToken", "StatusFilter"},
			"describe-script":                          {"ScriptId"},
			"describe-vpc-peering-authorizations":      {},
			"describe-vpc-peering-connections":         {"FleetId"},
			"get-compute-access":                       {"ComputeName", "FleetId"},
			"get-compute-auth-token":                   {"ComputeName", "FleetId"},
			"get-game-session-log-url":                 {"GameSessionId"},
			"get-instance-access":                      {"FleetId", "InstanceId"},
			"list-aliases":                             {"Limit", "Name", "NextToken", "RoutingStrategyType"},
			"list-builds":                              {"Limit", "NextToken", "Status"},
			"list-compute":                             {"ComputeStatus", "ContainerGroupDefinitionName", "FleetId", "Limit", "Location", "NextToken"},
			"list-container-fleets":                    {"ContainerGroupDefinitionName", "Limit", "NextToken"},
			"list-container-group-definition-versions": {"Limit", "Name", "NextToken"},
			"list-container-group-definitions":         {"ContainerGroupType", "Limit", "NextToken"},
			"list-fleet-deployments":                   {"FleetId", "Limit", "NextToken"},
			"list-fleets":                              {"BuildId", "Limit", "NextToken", "ScriptId"},
			"list-game-server-groups":                  {"Limit", "NextToken"},
			"list-game-servers":                        {"GameServerGroupName", "Limit", "NextToken", "SortOrder"},
			"list-locations":                           {"Filters", "Limit", "NextToken"},
			"list-scripts":                             {"Limit", "NextToken"},
			"list-tags-for-resource":                   {"ResourceARN"},
			"put-scaling-policy":                       {"ComparisonOperator", "EvaluationPeriods", "FleetId", "MetricName", "Name", "PolicyType", "ScalingAdjustment", "ScalingAdjustmentType", "TargetConfiguration", "Threshold"},
			"register-compute":                         {"CertificatePath", "ComputeName", "DnsName", "FleetId", "IpAddress", "Location"},
			"register-game-server":                     {"ConnectionInfo", "GameServerData", "GameServerGroupName", "GameServerId", "InstanceId"},
			"request-upload-credentials":               {"BuildId"},
			"resolve-alias":                            {"AliasId"},
			"resume-game-server-group":                 {"GameServerGroupName", "ResumeActions"},
			"search-game-sessions":                     {"AliasId", "FilterExpression", "FleetId", "Limit", "Location", "NextToken", "SortExpression"},
			"start-fleet-actions":                      {"Actions", "FleetId", "Location"},
			"start-game-session-placement":             {"DesiredPlayerSessions", "GameProperties", "GameSessionData", "GameSessionName", "GameSessionQueueName", "MaximumPlayerSessionCount", "PlacementId", "PlayerLatencies", "PriorityConfigurationOverride"},
			"start-match-backfill":                     {"ConfigurationName", "GameSessionArn", "Players", "TicketId"},
			"start-matchmaking":                        {"ConfigurationName", "Players", "TicketId"},
			"stop-fleet-actions":                       {"Actions", "FleetId", "Location"},
			"stop-game-session-placement":              {"PlacementId"},
			"stop-matchmaking":                         {"TicketId"},
			"suspend-game-server-group":                {"GameServerGroupName", "SuspendActions"},
			"tag-resource":                             {"ResourceARN", "Tags"},
			"terminate-game-session":                   {"GameSessionId", "TerminationMode"},
			"untag-resource":                           {"ResourceARN", "TagKeys"},
			"update-alias":                             {"AliasId", "Description", "Name", "RoutingStrategy"},
			"update-build":                             {"BuildId", "Name", "Version"},
			"update-container-fleet":                   {"DeploymentConfiguration", "Description", "FleetId", "GameServerContainerGroupDefinitionName", "GameServerContainerGroupsPerInstance", "GameSessionCreationLimitPolicy", "InstanceConnectionPortRange", "InstanceInboundPermissionAuthorizations", "InstanceInboundPermissionRevocations", "LogConfiguration", "MetricGroups", "NewGameSessionProtectionPolicy", "PerInstanceContainerGroupDefinitionName", "RemoveAttributes"},
			"update-container-group-definition":        {"GameServerContainerDefinition", "Name", "OperatingSystem", "SourceVersionNumber", "SupportContainerDefinitions", "TotalMemoryLimitMebibytes", "TotalVcpuLimit", "VersionDescription"},
			"update-fleet-attributes":                  {"AnywhereConfiguration", "Description", "FleetId", "MetricGroups", "Name", "NewGameSessionProtectionPolicy", "ResourceCreationLimitPolicy"},
			"update-fleet-capacity":                    {"DesiredInstances", "FleetId", "Location", "ManagedCapacityConfiguration", "MaxSize", "MinSize"},
			"update-fleet-port-settings":               {"FleetId", "InboundPermissionAuthorizations", "InboundPermissionRevocations"},
			"update-game-server":                       {"GameServerData", "GameServerGroupName", "GameServerId", "HealthCheck", "UtilizationStatus"},
			"update-game-server-group":                 {"BalancingStrategy", "GameServerGroupName", "GameServerProtectionPolicy", "InstanceDefinitions", "RoleArn"},
			"update-game-session":                      {"GameProperties", "GameSessionId", "MaximumPlayerSessionCount", "Name", "PlayerSessionCreationPolicy", "ProtectionPolicy"},
			"update-game-session-queue":                {"CustomEventData", "Destinations", "FilterConfiguration", "Name", "NotificationTarget", "PlayerLatencyPolicies", "PriorityConfiguration", "TimeoutInSeconds"},
			"update-matchmaking-configuration":         {"AcceptanceRequired", "AcceptanceTimeoutSeconds", "AdditionalPlayerCount", "BackfillMode", "CustomEventData", "Description", "FlexMatchMode", "GameProperties", "GameSessionData", "GameSessionQueueArns", "Name", "NotificationTarget", "RequestTimeoutSeconds", "RuleSetName"},
			"update-runtime-configuration":             {"FleetId", "RuntimeConfiguration"},
			"update-script":                            {"Name", "ScriptId", "StorageLocation", "Version", "ZipFile"},
			"validate-matchmaking-rule-set":            {"RuleSetBody"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-match":                             {"AcceptanceType": "types.AcceptanceType", "PlayerIds": "[]string", "TicketId": "*string"},
			"claim-game-server":                        {"FilterOption": "*types.ClaimFilterOption", "GameServerData": "*string", "GameServerGroupName": "*string", "GameServerId": "*string"},
			"create-alias":                             {"Description": "*string", "Name": "*string", "RoutingStrategy": "*types.RoutingStrategy", "Tags": "[]types.Tag"},
			"create-build":                             {"Name": "*string", "OperatingSystem": "types.OperatingSystem", "ServerSdkVersion": "*string", "StorageLocation": "*types.S3Location", "Tags": "[]types.Tag", "Version": "*string"},
			"create-container-fleet":                   {"BillingType": "types.ContainerFleetBillingType", "Description": "*string", "FleetRoleArn": "*string", "GameServerContainerGroupDefinitionName": "*string", "GameServerContainerGroupsPerInstance": "*int32", "GameSessionCreationLimitPolicy": "*types.GameSessionCreationLimitPolicy", "InstanceConnectionPortRange": "*types.ConnectionPortRange", "InstanceInboundPermissions": "[]types.IpPermission", "InstanceType": "*string", "Locations": "[]types.LocationConfiguration", "LogConfiguration": "*types.LogConfiguration", "MetricGroups": "[]string", "NewGameSessionProtectionPolicy": "types.ProtectionPolicy", "PerInstanceContainerGroupDefinitionName": "*string", "Tags": "[]types.Tag"},
			"create-container-group-definition":        {"ContainerGroupType": "types.ContainerGroupType", "GameServerContainerDefinition": "*types.GameServerContainerDefinitionInput", "Name": "*string", "OperatingSystem": "types.ContainerOperatingSystem", "SupportContainerDefinitions": "[]types.SupportContainerDefinitionInput", "Tags": "[]types.Tag", "TotalMemoryLimitMebibytes": "*int32", "TotalVcpuLimit": "*float64", "VersionDescription": "*string"},
			"create-fleet":                             {"AnywhereConfiguration": "*types.AnywhereConfiguration", "BuildId": "*string", "CertificateConfiguration": "*types.CertificateConfiguration", "ComputeType": "types.ComputeType", "Description": "*string", "EC2InboundPermissions": "[]types.IpPermission", "EC2InstanceType": "types.EC2InstanceType", "FleetType": "types.FleetType", "InstanceRoleArn": "*string", "InstanceRoleCredentialsProvider": "types.InstanceRoleCredentialsProvider", "Locations": "[]types.LocationConfiguration", "LogPaths": "[]string", "MetricGroups": "[]string", "Name": "*string", "NewGameSessionProtectionPolicy": "types.ProtectionPolicy", "PeerVpcAwsAccountId": "*string", "PeerVpcId": "*string", "ResourceCreationLimitPolicy": "*types.ResourceCreationLimitPolicy", "RuntimeConfiguration": "*types.RuntimeConfiguration", "ScriptId": "*string", "ServerLaunchParameters": "*string", "ServerLaunchPath": "*string", "Tags": "[]types.Tag"},
			"create-fleet-locations":                   {"FleetId": "*string", "Locations": "[]types.LocationConfiguration"},
			"create-game-server-group":                 {"AutoScalingPolicy": "*types.GameServerGroupAutoScalingPolicy", "BalancingStrategy": "types.BalancingStrategy", "GameServerGroupName": "*string", "GameServerProtectionPolicy": "types.GameServerProtectionPolicy", "InstanceDefinitions": "[]types.InstanceDefinition", "LaunchTemplate": "*types.LaunchTemplateSpecification", "MaxSize": "*int32", "MinSize": "*int32", "RoleArn": "*string", "Tags": "[]types.Tag", "VpcSubnets": "[]string"},
			"create-game-session":                      {"AliasId": "*string", "CreatorId": "*string", "FleetId": "*string", "GameProperties": "[]types.GameProperty", "GameSessionData": "*string", "GameSessionId": "*string", "IdempotencyToken": "*string", "Location": "*string", "MaximumPlayerSessionCount": "*int32", "Name": "*string"},
			"create-game-session-queue":                {"CustomEventData": "*string", "Destinations": "[]types.GameSessionQueueDestination", "FilterConfiguration": "*types.FilterConfiguration", "Name": "*string", "NotificationTarget": "*string", "PlayerLatencyPolicies": "[]types.PlayerLatencyPolicy", "PriorityConfiguration": "*types.PriorityConfiguration", "Tags": "[]types.Tag", "TimeoutInSeconds": "*int32"},
			"create-location":                          {"LocationName": "*string", "Tags": "[]types.Tag"},
			"create-matchmaking-configuration":         {"AcceptanceRequired": "*bool", "AcceptanceTimeoutSeconds": "*int32", "AdditionalPlayerCount": "*int32", "BackfillMode": "types.BackfillMode", "CustomEventData": "*string", "Description": "*string", "FlexMatchMode": "types.FlexMatchMode", "GameProperties": "[]types.GameProperty", "GameSessionData": "*string", "GameSessionQueueArns": "[]string", "Name": "*string", "NotificationTarget": "*string", "RequestTimeoutSeconds": "*int32", "RuleSetName": "*string", "Tags": "[]types.Tag"},
			"create-matchmaking-rule-set":              {"Name": "*string", "RuleSetBody": "*string", "Tags": "[]types.Tag"},
			"create-player-session":                    {"GameSessionId": "*string", "PlayerData": "*string", "PlayerId": "*string"},
			"create-player-sessions":                   {"GameSessionId": "*string", "PlayerDataMap": "map[string]string", "PlayerIds": "[]string"},
			"create-script":                            {"Name": "*string", "NodeJsVersion": "*string", "StorageLocation": "*types.S3Location", "Tags": "[]types.Tag", "Version": "*string", "ZipFile": "[]byte"},
			"create-vpc-peering-authorization":         {"GameLiftAwsAccountId": "*string", "PeerVpcId": "*string"},
			"create-vpc-peering-connection":            {"FleetId": "*string", "PeerVpcAwsAccountId": "*string", "PeerVpcId": "*string"},
			"delete-alias":                             {"AliasId": "*string"},
			"delete-build":                             {"BuildId": "*string"},
			"delete-container-fleet":                   {"FleetId": "*string"},
			"delete-container-group-definition":        {"Name": "*string", "VersionCountToRetain": "*int32", "VersionNumber": "*int32"},
			"delete-fleet":                             {"FleetId": "*string"},
			"delete-fleet-locations":                   {"FleetId": "*string", "Locations": "[]string"},
			"delete-game-server-group":                 {"DeleteOption": "types.GameServerGroupDeleteOption", "GameServerGroupName": "*string"},
			"delete-game-session-queue":                {"Name": "*string"},
			"delete-location":                          {"LocationName": "*string"},
			"delete-matchmaking-configuration":         {"Name": "*string"},
			"delete-matchmaking-rule-set":              {"Name": "*string"},
			"delete-scaling-policy":                    {"FleetId": "*string", "Name": "*string"},
			"delete-script":                            {"ScriptId": "*string"},
			"delete-vpc-peering-authorization":         {"GameLiftAwsAccountId": "*string", "PeerVpcId": "*string"},
			"delete-vpc-peering-connection":            {"FleetId": "*string", "VpcPeeringConnectionId": "*string"},
			"deregister-compute":                       {"ComputeName": "*string", "FleetId": "*string"},
			"deregister-game-server":                   {"GameServerGroupName": "*string", "GameServerId": "*string"},
			"describe-alias":                           {"AliasId": "*string"},
			"describe-build":                           {"BuildId": "*string"},
			"describe-compute":                         {"ComputeName": "*string", "FleetId": "*string"},
			"describe-container-fleet":                 {"FleetId": "*string"},
			"describe-container-group-definition":      {"Name": "*string", "VersionNumber": "*int32"},
			"describe-ec2-instance-limits":             {"EC2InstanceType": "types.EC2InstanceType", "Location": "*string"},
			"describe-fleet-attributes":                {"FleetIds": "[]string", "Limit": "*int32", "NextToken": "*string"},
			"describe-fleet-capacity":                  {"FleetIds": "[]string", "Limit": "*int32", "NextToken": "*string"},
			"describe-fleet-deployment":                {"DeploymentId": "*string", "FleetId": "*string"},
			"describe-fleet-events":                    {"EndTime": "*time.Time", "FleetId": "*string", "Limit": "*int32", "NextToken": "*string", "StartTime": "*time.Time"},
			"describe-fleet-location-attributes":       {"FleetId": "*string", "Limit": "*int32", "Locations": "[]string", "NextToken": "*string"},
			"describe-fleet-location-capacity":         {"FleetId": "*string", "Location": "*string"},
			"describe-fleet-location-utilization":      {"FleetId": "*string", "Location": "*string"},
			"describe-fleet-port-settings":             {"FleetId": "*string", "Location": "*string"},
			"describe-fleet-utilization":               {"FleetIds": "[]string", "Limit": "*int32", "NextToken": "*string"},
			"describe-game-server":                     {"GameServerGroupName": "*string", "GameServerId": "*string"},
			"describe-game-server-group":               {"GameServerGroupName": "*string"},
			"describe-game-server-instances":           {"GameServerGroupName": "*string", "InstanceIds": "[]string", "Limit": "*int32", "NextToken": "*string"},
			"describe-game-session-details":            {"AliasId": "*string", "FleetId": "*string", "GameSessionId": "*string", "Limit": "*int32", "Location": "*string", "NextToken": "*string", "StatusFilter": "*string"},
			"describe-game-session-placement":          {"PlacementId": "*string"},
			"describe-game-session-queues":             {"Limit": "*int32", "Names": "[]string", "NextToken": "*string"},
			"describe-game-sessions":                   {"AliasId": "*string", "FleetId": "*string", "GameSessionId": "*string", "Limit": "*int32", "Location": "*string", "NextToken": "*string", "StatusFilter": "*string"},
			"describe-instances":                       {"FleetId": "*string", "InstanceId": "*string", "Limit": "*int32", "Location": "*string", "NextToken": "*string"},
			"describe-matchmaking":                     {"TicketIds": "[]string"},
			"describe-matchmaking-configurations":      {"Limit": "*int32", "Names": "[]string", "NextToken": "*string", "RuleSetName": "*string"},
			"describe-matchmaking-rule-sets":           {"Limit": "*int32", "Names": "[]string", "NextToken": "*string"},
			"describe-player-sessions":                 {"GameSessionId": "*string", "Limit": "*int32", "NextToken": "*string", "PlayerId": "*string", "PlayerSessionId": "*string", "PlayerSessionStatusFilter": "*string"},
			"describe-runtime-configuration":           {"FleetId": "*string"},
			"describe-scaling-policies":                {"FleetId": "*string", "Limit": "*int32", "Location": "*string", "NextToken": "*string", "StatusFilter": "types.ScalingStatusType"},
			"describe-script":                          {"ScriptId": "*string"},
			"describe-vpc-peering-authorizations":      {},
			"describe-vpc-peering-connections":         {"FleetId": "*string"},
			"get-compute-access":                       {"ComputeName": "*string", "FleetId": "*string"},
			"get-compute-auth-token":                   {"ComputeName": "*string", "FleetId": "*string"},
			"get-game-session-log-url":                 {"GameSessionId": "*string"},
			"get-instance-access":                      {"FleetId": "*string", "InstanceId": "*string"},
			"list-aliases":                             {"Limit": "*int32", "Name": "*string", "NextToken": "*string", "RoutingStrategyType": "types.RoutingStrategyType"},
			"list-builds":                              {"Limit": "*int32", "NextToken": "*string", "Status": "types.BuildStatus"},
			"list-compute":                             {"ComputeStatus": "types.ListComputeInputStatus", "ContainerGroupDefinitionName": "*string", "FleetId": "*string", "Limit": "*int32", "Location": "*string", "NextToken": "*string"},
			"list-container-fleets":                    {"ContainerGroupDefinitionName": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-container-group-definition-versions": {"Limit": "*int32", "Name": "*string", "NextToken": "*string"},
			"list-container-group-definitions":         {"ContainerGroupType": "types.ContainerGroupType", "Limit": "*int32", "NextToken": "*string"},
			"list-fleet-deployments":                   {"FleetId": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-fleets":                              {"BuildId": "*string", "Limit": "*int32", "NextToken": "*string", "ScriptId": "*string"},
			"list-game-server-groups":                  {"Limit": "*int32", "NextToken": "*string"},
			"list-game-servers":                        {"GameServerGroupName": "*string", "Limit": "*int32", "NextToken": "*string", "SortOrder": "types.SortOrder"},
			"list-locations":                           {"Filters": "[]types.LocationFilter", "Limit": "*int32", "NextToken": "*string"},
			"list-scripts":                             {"Limit": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                   {"ResourceARN": "*string"},
			"put-scaling-policy":                       {"ComparisonOperator": "types.ComparisonOperatorType", "EvaluationPeriods": "*int32", "FleetId": "*string", "MetricName": "types.MetricName", "Name": "*string", "PolicyType": "types.PolicyType", "ScalingAdjustment": "*int32", "ScalingAdjustmentType": "types.ScalingAdjustmentType", "TargetConfiguration": "*types.TargetConfiguration", "Threshold": "*float64"},
			"register-compute":                         {"CertificatePath": "*string", "ComputeName": "*string", "DnsName": "*string", "FleetId": "*string", "IpAddress": "*string", "Location": "*string"},
			"register-game-server":                     {"ConnectionInfo": "*string", "GameServerData": "*string", "GameServerGroupName": "*string", "GameServerId": "*string", "InstanceId": "*string"},
			"request-upload-credentials":               {"BuildId": "*string"},
			"resolve-alias":                            {"AliasId": "*string"},
			"resume-game-server-group":                 {"GameServerGroupName": "*string", "ResumeActions": "[]types.GameServerGroupAction"},
			"search-game-sessions":                     {"AliasId": "*string", "FilterExpression": "*string", "FleetId": "*string", "Limit": "*int32", "Location": "*string", "NextToken": "*string", "SortExpression": "*string"},
			"start-fleet-actions":                      {"Actions": "[]types.FleetAction", "FleetId": "*string", "Location": "*string"},
			"start-game-session-placement":             {"DesiredPlayerSessions": "[]types.DesiredPlayerSession", "GameProperties": "[]types.GameProperty", "GameSessionData": "*string", "GameSessionName": "*string", "GameSessionQueueName": "*string", "MaximumPlayerSessionCount": "*int32", "PlacementId": "*string", "PlayerLatencies": "[]types.PlayerLatency", "PriorityConfigurationOverride": "*types.PriorityConfigurationOverride"},
			"start-match-backfill":                     {"ConfigurationName": "*string", "GameSessionArn": "*string", "Players": "[]types.Player", "TicketId": "*string"},
			"start-matchmaking":                        {"ConfigurationName": "*string", "Players": "[]types.Player", "TicketId": "*string"},
			"stop-fleet-actions":                       {"Actions": "[]types.FleetAction", "FleetId": "*string", "Location": "*string"},
			"stop-game-session-placement":              {"PlacementId": "*string"},
			"stop-matchmaking":                         {"TicketId": "*string"},
			"suspend-game-server-group":                {"GameServerGroupName": "*string", "SuspendActions": "[]types.GameServerGroupAction"},
			"tag-resource":                             {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"terminate-game-session":                   {"GameSessionId": "*string", "TerminationMode": "types.TerminationMode"},
			"untag-resource":                           {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-alias":                             {"AliasId": "*string", "Description": "*string", "Name": "*string", "RoutingStrategy": "*types.RoutingStrategy"},
			"update-build":                             {"BuildId": "*string", "Name": "*string", "Version": "*string"},
			"update-container-fleet":                   {"DeploymentConfiguration": "*types.DeploymentConfiguration", "Description": "*string", "FleetId": "*string", "GameServerContainerGroupDefinitionName": "*string", "GameServerContainerGroupsPerInstance": "*int32", "GameSessionCreationLimitPolicy": "*types.GameSessionCreationLimitPolicy", "InstanceConnectionPortRange": "*types.ConnectionPortRange", "InstanceInboundPermissionAuthorizations": "[]types.IpPermission", "InstanceInboundPermissionRevocations": "[]types.IpPermission", "LogConfiguration": "*types.LogConfiguration", "MetricGroups": "[]string", "NewGameSessionProtectionPolicy": "types.ProtectionPolicy", "PerInstanceContainerGroupDefinitionName": "*string", "RemoveAttributes": "[]types.ContainerFleetRemoveAttribute"},
			"update-container-group-definition":        {"GameServerContainerDefinition": "*types.GameServerContainerDefinitionInput", "Name": "*string", "OperatingSystem": "types.ContainerOperatingSystem", "SourceVersionNumber": "*int32", "SupportContainerDefinitions": "[]types.SupportContainerDefinitionInput", "TotalMemoryLimitMebibytes": "*int32", "TotalVcpuLimit": "*float64", "VersionDescription": "*string"},
			"update-fleet-attributes":                  {"AnywhereConfiguration": "*types.AnywhereConfiguration", "Description": "*string", "FleetId": "*string", "MetricGroups": "[]string", "Name": "*string", "NewGameSessionProtectionPolicy": "types.ProtectionPolicy", "ResourceCreationLimitPolicy": "*types.ResourceCreationLimitPolicy"},
			"update-fleet-capacity":                    {"DesiredInstances": "*int32", "FleetId": "*string", "Location": "*string", "ManagedCapacityConfiguration": "*types.ManagedCapacityConfiguration", "MaxSize": "*int32", "MinSize": "*int32"},
			"update-fleet-port-settings":               {"FleetId": "*string", "InboundPermissionAuthorizations": "[]types.IpPermission", "InboundPermissionRevocations": "[]types.IpPermission"},
			"update-game-server":                       {"GameServerData": "*string", "GameServerGroupName": "*string", "GameServerId": "*string", "HealthCheck": "types.GameServerHealthCheck", "UtilizationStatus": "types.GameServerUtilizationStatus"},
			"update-game-server-group":                 {"BalancingStrategy": "types.BalancingStrategy", "GameServerGroupName": "*string", "GameServerProtectionPolicy": "types.GameServerProtectionPolicy", "InstanceDefinitions": "[]types.InstanceDefinition", "RoleArn": "*string"},
			"update-game-session":                      {"GameProperties": "[]types.GameProperty", "GameSessionId": "*string", "MaximumPlayerSessionCount": "*int32", "Name": "*string", "PlayerSessionCreationPolicy": "types.PlayerSessionCreationPolicy", "ProtectionPolicy": "types.ProtectionPolicy"},
			"update-game-session-queue":                {"CustomEventData": "*string", "Destinations": "[]types.GameSessionQueueDestination", "FilterConfiguration": "*types.FilterConfiguration", "Name": "*string", "NotificationTarget": "*string", "PlayerLatencyPolicies": "[]types.PlayerLatencyPolicy", "PriorityConfiguration": "*types.PriorityConfiguration", "TimeoutInSeconds": "*int32"},
			"update-matchmaking-configuration":         {"AcceptanceRequired": "*bool", "AcceptanceTimeoutSeconds": "*int32", "AdditionalPlayerCount": "*int32", "BackfillMode": "types.BackfillMode", "CustomEventData": "*string", "Description": "*string", "FlexMatchMode": "types.FlexMatchMode", "GameProperties": "[]types.GameProperty", "GameSessionData": "*string", "GameSessionQueueArns": "[]string", "Name": "*string", "NotificationTarget": "*string", "RequestTimeoutSeconds": "*int32", "RuleSetName": "*string"},
			"update-runtime-configuration":             {"FleetId": "*string", "RuntimeConfiguration": "*types.RuntimeConfiguration"},
			"update-script":                            {"Name": "*string", "ScriptId": "*string", "StorageLocation": "*types.S3Location", "Version": "*string", "ZipFile": "[]byte"},
			"validate-matchmaking-rule-set":            {"RuleSetBody": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-match":                             {"AcceptanceType", "PlayerIds", "TicketId"},
			"claim-game-server":                        {"GameServerGroupName"},
			"create-alias":                             {"Name", "RoutingStrategy"},
			"create-build":                             {},
			"create-container-fleet":                   {"FleetRoleArn"},
			"create-container-group-definition":        {"Name", "OperatingSystem", "TotalMemoryLimitMebibytes", "TotalVcpuLimit"},
			"create-fleet":                             {"Name"},
			"create-fleet-locations":                   {"FleetId", "Locations"},
			"create-game-server-group":                 {"GameServerGroupName", "InstanceDefinitions", "LaunchTemplate", "MaxSize", "MinSize", "RoleArn"},
			"create-game-session":                      {"MaximumPlayerSessionCount"},
			"create-game-session-queue":                {"Name"},
			"create-location":                          {"LocationName"},
			"create-matchmaking-configuration":         {"AcceptanceRequired", "Name", "RequestTimeoutSeconds", "RuleSetName"},
			"create-matchmaking-rule-set":              {"Name", "RuleSetBody"},
			"create-player-session":                    {"GameSessionId", "PlayerId"},
			"create-player-sessions":                   {"GameSessionId", "PlayerIds"},
			"create-script":                            {},
			"create-vpc-peering-authorization":         {"GameLiftAwsAccountId", "PeerVpcId"},
			"create-vpc-peering-connection":            {"FleetId", "PeerVpcAwsAccountId", "PeerVpcId"},
			"delete-alias":                             {"AliasId"},
			"delete-build":                             {"BuildId"},
			"delete-container-fleet":                   {"FleetId"},
			"delete-container-group-definition":        {"Name"},
			"delete-fleet":                             {"FleetId"},
			"delete-fleet-locations":                   {"FleetId", "Locations"},
			"delete-game-server-group":                 {"GameServerGroupName"},
			"delete-game-session-queue":                {"Name"},
			"delete-location":                          {"LocationName"},
			"delete-matchmaking-configuration":         {"Name"},
			"delete-matchmaking-rule-set":              {"Name"},
			"delete-scaling-policy":                    {"FleetId", "Name"},
			"delete-script":                            {"ScriptId"},
			"delete-vpc-peering-authorization":         {"GameLiftAwsAccountId", "PeerVpcId"},
			"delete-vpc-peering-connection":            {"FleetId", "VpcPeeringConnectionId"},
			"deregister-compute":                       {"ComputeName", "FleetId"},
			"deregister-game-server":                   {"GameServerGroupName", "GameServerId"},
			"describe-alias":                           {"AliasId"},
			"describe-build":                           {"BuildId"},
			"describe-compute":                         {"ComputeName", "FleetId"},
			"describe-container-fleet":                 {"FleetId"},
			"describe-container-group-definition":      {"Name"},
			"describe-ec2-instance-limits":             {},
			"describe-fleet-attributes":                {},
			"describe-fleet-capacity":                  {},
			"describe-fleet-deployment":                {"FleetId"},
			"describe-fleet-events":                    {"FleetId"},
			"describe-fleet-location-attributes":       {"FleetId"},
			"describe-fleet-location-capacity":         {"FleetId", "Location"},
			"describe-fleet-location-utilization":      {"FleetId", "Location"},
			"describe-fleet-port-settings":             {"FleetId"},
			"describe-fleet-utilization":               {},
			"describe-game-server":                     {"GameServerGroupName", "GameServerId"},
			"describe-game-server-group":               {"GameServerGroupName"},
			"describe-game-server-instances":           {"GameServerGroupName"},
			"describe-game-session-details":            {},
			"describe-game-session-placement":          {"PlacementId"},
			"describe-game-session-queues":             {},
			"describe-game-sessions":                   {},
			"describe-instances":                       {"FleetId"},
			"describe-matchmaking":                     {"TicketIds"},
			"describe-matchmaking-configurations":      {},
			"describe-matchmaking-rule-sets":           {},
			"describe-player-sessions":                 {},
			"describe-runtime-configuration":           {"FleetId"},
			"describe-scaling-policies":                {"FleetId"},
			"describe-script":                          {"ScriptId"},
			"describe-vpc-peering-authorizations":      {},
			"describe-vpc-peering-connections":         {},
			"get-compute-access":                       {"ComputeName", "FleetId"},
			"get-compute-auth-token":                   {"ComputeName", "FleetId"},
			"get-game-session-log-url":                 {"GameSessionId"},
			"get-instance-access":                      {"FleetId", "InstanceId"},
			"list-aliases":                             {},
			"list-builds":                              {},
			"list-compute":                             {"FleetId"},
			"list-container-fleets":                    {},
			"list-container-group-definition-versions": {"Name"},
			"list-container-group-definitions":         {},
			"list-fleet-deployments":                   {},
			"list-fleets":                              {},
			"list-game-server-groups":                  {},
			"list-game-servers":                        {"GameServerGroupName"},
			"list-locations":                           {},
			"list-scripts":                             {},
			"list-tags-for-resource":                   {"ResourceARN"},
			"put-scaling-policy":                       {"FleetId", "MetricName", "Name"},
			"register-compute":                         {"ComputeName", "FleetId"},
			"register-game-server":                     {"GameServerGroupName", "GameServerId", "InstanceId"},
			"request-upload-credentials":               {"BuildId"},
			"resolve-alias":                            {"AliasId"},
			"resume-game-server-group":                 {"GameServerGroupName", "ResumeActions"},
			"search-game-sessions":                     {},
			"start-fleet-actions":                      {"Actions", "FleetId"},
			"start-game-session-placement":             {"GameSessionQueueName", "MaximumPlayerSessionCount", "PlacementId"},
			"start-match-backfill":                     {"ConfigurationName", "Players"},
			"start-matchmaking":                        {"ConfigurationName", "Players"},
			"stop-fleet-actions":                       {"Actions", "FleetId"},
			"stop-game-session-placement":              {"PlacementId"},
			"stop-matchmaking":                         {"TicketId"},
			"suspend-game-server-group":                {"GameServerGroupName", "SuspendActions"},
			"tag-resource":                             {"ResourceARN", "Tags"},
			"terminate-game-session":                   {"GameSessionId", "TerminationMode"},
			"untag-resource":                           {"ResourceARN", "TagKeys"},
			"update-alias":                             {"AliasId"},
			"update-build":                             {"BuildId"},
			"update-container-fleet":                   {"FleetId"},
			"update-container-group-definition":        {"Name"},
			"update-fleet-attributes":                  {"FleetId"},
			"update-fleet-capacity":                    {"FleetId"},
			"update-fleet-port-settings":               {"FleetId"},
			"update-game-server":                       {"GameServerGroupName", "GameServerId"},
			"update-game-server-group":                 {"GameServerGroupName"},
			"update-game-session":                      {"GameSessionId"},
			"update-game-session-queue":                {"Name"},
			"update-matchmaking-configuration":         {"Name"},
			"update-runtime-configuration":             {"FleetId", "RuntimeConfiguration"},
			"update-script":                            {"ScriptId"},
			"validate-matchmaking-rule-set":            {"RuleSetBody"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("gamelift", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
