package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/partnercentralselling/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-engagement-invitation", "assign-opportunity", "associate-opportunity", "create-engagement", "create-engagement-context", "create-engagement-invitation", "create-opportunity", "create-resource-snapshot", "create-resource-snapshot-job", "delete-resource-snapshot-job", "disassociate-opportunity", "get-aws-opportunity-summary", "get-engagement", "get-engagement-invitation", "get-opportunity", "get-resource-snapshot", "get-resource-snapshot-job", "get-selling-system-settings", "list-engagement-by-accepting-invitation-tasks", "list-engagement-from-opportunity-tasks", "list-engagement-invitations", "list-engagement-members", "list-engagement-resource-associations", "list-engagements", "list-opportunities", "list-opportunity-from-engagement-tasks", "list-resource-snapshot-jobs", "list-resource-snapshots", "list-solutions", "list-tags-for-resource", "put-selling-system-settings", "reject-engagement-invitation", "start-engagement-by-accepting-invitation-task", "start-engagement-from-opportunity-task", "start-opportunity-from-engagement-task", "start-resource-snapshot-job", "stop-resource-snapshot-job", "submit-opportunity", "tag-resource", "untag-resource", "update-engagement-context", "update-opportunity"},
		OperationSet: map[string]bool{"accept-engagement-invitation": true, "assign-opportunity": true, "associate-opportunity": true, "create-engagement": true, "create-engagement-context": true, "create-engagement-invitation": true, "create-opportunity": true, "create-resource-snapshot": true, "create-resource-snapshot-job": true, "delete-resource-snapshot-job": true, "disassociate-opportunity": true, "get-aws-opportunity-summary": true, "get-engagement": true, "get-engagement-invitation": true, "get-opportunity": true, "get-resource-snapshot": true, "get-resource-snapshot-job": true, "get-selling-system-settings": true, "list-engagement-by-accepting-invitation-tasks": true, "list-engagement-from-opportunity-tasks": true, "list-engagement-invitations": true, "list-engagement-members": true, "list-engagement-resource-associations": true, "list-engagements": true, "list-opportunities": true, "list-opportunity-from-engagement-tasks": true, "list-resource-snapshot-jobs": true, "list-resource-snapshots": true, "list-solutions": true, "list-tags-for-resource": true, "put-selling-system-settings": true, "reject-engagement-invitation": true, "start-engagement-by-accepting-invitation-task": true, "start-engagement-from-opportunity-task": true, "start-opportunity-from-engagement-task": true, "start-resource-snapshot-job": true, "stop-resource-snapshot-job": true, "submit-opportunity": true, "tag-resource": true, "untag-resource": true, "update-engagement-context": true, "update-opportunity": true},
		OperationInputs: map[string][]string{
			"accept-engagement-invitation":                  {"Catalog", "Identifier"},
			"assign-opportunity":                            {"Assignee", "Catalog", "Identifier"},
			"associate-opportunity":                         {"Catalog", "OpportunityIdentifier", "RelatedEntityIdentifier", "RelatedEntityType"},
			"create-engagement":                             {"Catalog", "ClientToken", "Contexts", "Description", "Title"},
			"create-engagement-context":                     {"Catalog", "ClientToken", "EngagementIdentifier", "Payload", "Type"},
			"create-engagement-invitation":                  {"Catalog", "ClientToken", "EngagementIdentifier", "Invitation"},
			"create-opportunity":                            {"Catalog", "ClientToken", "Customer", "LifeCycle", "Marketing", "NationalSecurity", "OpportunityTeam", "OpportunityType", "Origin", "PartnerOpportunityIdentifier", "PrimaryNeedsFromAws", "Project", "SoftwareRevenue", "Tags"},
			"create-resource-snapshot":                      {"Catalog", "ClientToken", "EngagementIdentifier", "ResourceIdentifier", "ResourceSnapshotTemplateIdentifier", "ResourceType"},
			"create-resource-snapshot-job":                  {"Catalog", "ClientToken", "EngagementIdentifier", "ResourceIdentifier", "ResourceSnapshotTemplateIdentifier", "ResourceType", "Tags"},
			"delete-resource-snapshot-job":                  {"Catalog", "ResourceSnapshotJobIdentifier"},
			"disassociate-opportunity":                      {"Catalog", "OpportunityIdentifier", "RelatedEntityIdentifier", "RelatedEntityType"},
			"get-aws-opportunity-summary":                   {"Catalog", "RelatedOpportunityIdentifier"},
			"get-engagement":                                {"Catalog", "Identifier"},
			"get-engagement-invitation":                     {"Catalog", "Identifier"},
			"get-opportunity":                               {"Catalog", "Identifier"},
			"get-resource-snapshot":                         {"Catalog", "EngagementIdentifier", "ResourceIdentifier", "ResourceSnapshotTemplateIdentifier", "ResourceType", "Revision"},
			"get-resource-snapshot-job":                     {"Catalog", "ResourceSnapshotJobIdentifier"},
			"get-selling-system-settings":                   {"Catalog"},
			"list-engagement-by-accepting-invitation-tasks": {"Catalog", "EngagementInvitationIdentifier", "MaxResults", "NextToken", "OpportunityIdentifier", "Sort", "TaskIdentifier", "TaskStatus"},
			"list-engagement-from-opportunity-tasks":        {"Catalog", "EngagementIdentifier", "MaxResults", "NextToken", "OpportunityIdentifier", "Sort", "TaskIdentifier", "TaskStatus"},
			"list-engagement-invitations":                   {"Catalog", "EngagementIdentifier", "MaxResults", "NextToken", "ParticipantType", "PayloadType", "SenderAwsAccountId", "Sort", "Status"},
			"list-engagement-members":                       {"Catalog", "Identifier", "MaxResults", "NextToken"},
			"list-engagement-resource-associations":         {"Catalog", "CreatedBy", "EngagementIdentifier", "MaxResults", "NextToken", "ResourceIdentifier", "ResourceType"},
			"list-engagements":                              {"Catalog", "ContextTypes", "CreatedBy", "EngagementIdentifier", "ExcludeContextTypes", "ExcludeCreatedBy", "MaxResults", "NextToken", "Sort"},
			"list-opportunities":                            {"Catalog", "CreatedDate", "CustomerCompanyName", "Identifier", "LastModifiedDate", "LifeCycleReviewStatus", "LifeCycleStage", "MaxResults", "NextToken", "Sort", "TargetCloseDate"},
			"list-opportunity-from-engagement-tasks":        {"Catalog", "ContextIdentifier", "EngagementIdentifier", "MaxResults", "NextToken", "OpportunityIdentifier", "Sort", "TaskIdentifier", "TaskStatus"},
			"list-resource-snapshot-jobs":                   {"Catalog", "EngagementIdentifier", "MaxResults", "NextToken", "Sort", "Status"},
			"list-resource-snapshots":                       {"Catalog", "CreatedBy", "EngagementIdentifier", "MaxResults", "NextToken", "ResourceIdentifier", "ResourceSnapshotTemplateIdentifier", "ResourceType"},
			"list-solutions":                                {"Catalog", "Category", "Identifier", "MaxResults", "NextToken", "Sort", "Status"},
			"list-tags-for-resource":                        {"ResourceArn"},
			"put-selling-system-settings":                   {"Catalog", "ResourceSnapshotJobRoleIdentifier"},
			"reject-engagement-invitation":                  {"Catalog", "Identifier", "RejectionReason"},
			"start-engagement-by-accepting-invitation-task": {"Catalog", "ClientToken", "Identifier", "Tags"},
			"start-engagement-from-opportunity-task":        {"AwsSubmission", "Catalog", "ClientToken", "Identifier", "Tags"},
			"start-opportunity-from-engagement-task":        {"Catalog", "ClientToken", "ContextIdentifier", "Identifier", "Tags"},
			"start-resource-snapshot-job":                   {"Catalog", "ResourceSnapshotJobIdentifier"},
			"stop-resource-snapshot-job":                    {"Catalog", "ResourceSnapshotJobIdentifier"},
			"submit-opportunity":                            {"Catalog", "Identifier", "InvolvementType", "Visibility"},
			"tag-resource":                                  {"ResourceArn", "Tags"},
			"untag-resource":                                {"ResourceArn", "TagKeys"},
			"update-engagement-context":                     {"Catalog", "ContextIdentifier", "EngagementIdentifier", "EngagementLastModifiedAt", "Payload", "Type"},
			"update-opportunity":                            {"Catalog", "Customer", "Identifier", "LastModifiedDate", "LifeCycle", "Marketing", "NationalSecurity", "OpportunityType", "PartnerOpportunityIdentifier", "PrimaryNeedsFromAws", "Project", "SoftwareRevenue"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-engagement-invitation":                  {"Catalog": "*string", "Identifier": "*string"},
			"assign-opportunity":                            {"Assignee": "*types.AssigneeContact", "Catalog": "*string", "Identifier": "*string"},
			"associate-opportunity":                         {"Catalog": "*string", "OpportunityIdentifier": "*string", "RelatedEntityIdentifier": "*string", "RelatedEntityType": "types.RelatedEntityType"},
			"create-engagement":                             {"Catalog": "*string", "ClientToken": "*string", "Contexts": "[]types.EngagementContextDetails", "Description": "*string", "Title": "*string"},
			"create-engagement-context":                     {"Catalog": "*string", "ClientToken": "*string", "EngagementIdentifier": "*string", "Payload": "types.EngagementContextPayload", "Type": "types.EngagementContextType"},
			"create-engagement-invitation":                  {"Catalog": "*string", "ClientToken": "*string", "EngagementIdentifier": "*string", "Invitation": "*types.Invitation"},
			"create-opportunity":                            {"Catalog": "*string", "ClientToken": "*string", "Customer": "*types.Customer", "LifeCycle": "*types.LifeCycle", "Marketing": "*types.Marketing", "NationalSecurity": "types.NationalSecurity", "OpportunityTeam": "[]types.Contact", "OpportunityType": "types.OpportunityType", "Origin": "types.OpportunityOrigin", "PartnerOpportunityIdentifier": "*string", "PrimaryNeedsFromAws": "[]types.PrimaryNeedFromAws", "Project": "*types.Project", "SoftwareRevenue": "*types.SoftwareRevenue", "Tags": "[]types.Tag"},
			"create-resource-snapshot":                      {"Catalog": "*string", "ClientToken": "*string", "EngagementIdentifier": "*string", "ResourceIdentifier": "*string", "ResourceSnapshotTemplateIdentifier": "*string", "ResourceType": "types.ResourceType"},
			"create-resource-snapshot-job":                  {"Catalog": "*string", "ClientToken": "*string", "EngagementIdentifier": "*string", "ResourceIdentifier": "*string", "ResourceSnapshotTemplateIdentifier": "*string", "ResourceType": "types.ResourceType", "Tags": "[]types.Tag"},
			"delete-resource-snapshot-job":                  {"Catalog": "*string", "ResourceSnapshotJobIdentifier": "*string"},
			"disassociate-opportunity":                      {"Catalog": "*string", "OpportunityIdentifier": "*string", "RelatedEntityIdentifier": "*string", "RelatedEntityType": "types.RelatedEntityType"},
			"get-aws-opportunity-summary":                   {"Catalog": "*string", "RelatedOpportunityIdentifier": "*string"},
			"get-engagement":                                {"Catalog": "*string", "Identifier": "*string"},
			"get-engagement-invitation":                     {"Catalog": "*string", "Identifier": "*string"},
			"get-opportunity":                               {"Catalog": "*string", "Identifier": "*string"},
			"get-resource-snapshot":                         {"Catalog": "*string", "EngagementIdentifier": "*string", "ResourceIdentifier": "*string", "ResourceSnapshotTemplateIdentifier": "*string", "ResourceType": "types.ResourceType", "Revision": "*int32"},
			"get-resource-snapshot-job":                     {"Catalog": "*string", "ResourceSnapshotJobIdentifier": "*string"},
			"get-selling-system-settings":                   {"Catalog": "*string"},
			"list-engagement-by-accepting-invitation-tasks": {"Catalog": "*string", "EngagementInvitationIdentifier": "[]string", "MaxResults": "*int32", "NextToken": "*string", "OpportunityIdentifier": "[]string", "Sort": "*types.ListTasksSortBase", "TaskIdentifier": "[]string", "TaskStatus": "[]types.TaskStatus"},
			"list-engagement-from-opportunity-tasks":        {"Catalog": "*string", "EngagementIdentifier": "[]string", "MaxResults": "*int32", "NextToken": "*string", "OpportunityIdentifier": "[]string", "Sort": "*types.ListTasksSortBase", "TaskIdentifier": "[]string", "TaskStatus": "[]types.TaskStatus"},
			"list-engagement-invitations":                   {"Catalog": "*string", "EngagementIdentifier": "[]string", "MaxResults": "*int32", "NextToken": "*string", "ParticipantType": "types.ParticipantType", "PayloadType": "[]types.EngagementInvitationPayloadType", "SenderAwsAccountId": "[]string", "Sort": "*types.OpportunityEngagementInvitationSort", "Status": "[]types.InvitationStatus"},
			"list-engagement-members":                       {"Catalog": "*string", "Identifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-engagement-resource-associations":         {"Catalog": "*string", "CreatedBy": "*string", "EngagementIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "ResourceIdentifier": "*string", "ResourceType": "types.ResourceType"},
			"list-engagements":                              {"Catalog": "*string", "ContextTypes": "[]types.EngagementContextType", "CreatedBy": "[]string", "EngagementIdentifier": "[]string", "ExcludeContextTypes": "[]types.EngagementContextType", "ExcludeCreatedBy": "[]string", "MaxResults": "*int32", "NextToken": "*string", "Sort": "*types.EngagementSort"},
			"list-opportunities":                            {"Catalog": "*string", "CreatedDate": "*types.CreatedDateFilter", "CustomerCompanyName": "[]string", "Identifier": "[]string", "LastModifiedDate": "*types.LastModifiedDate", "LifeCycleReviewStatus": "[]types.ReviewStatus", "LifeCycleStage": "[]types.Stage", "MaxResults": "*int32", "NextToken": "*string", "Sort": "*types.OpportunitySort", "TargetCloseDate": "*types.TargetCloseDateFilter"},
			"list-opportunity-from-engagement-tasks":        {"Catalog": "*string", "ContextIdentifier": "[]string", "EngagementIdentifier": "[]string", "MaxResults": "*int32", "NextToken": "*string", "OpportunityIdentifier": "[]string", "Sort": "*types.ListTasksSortBase", "TaskIdentifier": "[]string", "TaskStatus": "[]types.TaskStatus"},
			"list-resource-snapshot-jobs":                   {"Catalog": "*string", "EngagementIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "Sort": "*types.SortObject", "Status": "types.ResourceSnapshotJobStatus"},
			"list-resource-snapshots":                       {"Catalog": "*string", "CreatedBy": "*string", "EngagementIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "ResourceIdentifier": "*string", "ResourceSnapshotTemplateIdentifier": "*string", "ResourceType": "types.ResourceType"},
			"list-solutions":                                {"Catalog": "*string", "Category": "[]string", "Identifier": "[]string", "MaxResults": "*int32", "NextToken": "*string", "Sort": "*types.SolutionSort", "Status": "[]types.SolutionStatus"},
			"list-tags-for-resource":                        {"ResourceArn": "*string"},
			"put-selling-system-settings":                   {"Catalog": "*string", "ResourceSnapshotJobRoleIdentifier": "*string"},
			"reject-engagement-invitation":                  {"Catalog": "*string", "Identifier": "*string", "RejectionReason": "*string"},
			"start-engagement-by-accepting-invitation-task": {"Catalog": "*string", "ClientToken": "*string", "Identifier": "*string", "Tags": "[]types.Tag"},
			"start-engagement-from-opportunity-task":        {"AwsSubmission": "*types.AwsSubmission", "Catalog": "*string", "ClientToken": "*string", "Identifier": "*string", "Tags": "[]types.Tag"},
			"start-opportunity-from-engagement-task":        {"Catalog": "*string", "ClientToken": "*string", "ContextIdentifier": "*string", "Identifier": "*string", "Tags": "[]types.Tag"},
			"start-resource-snapshot-job":                   {"Catalog": "*string", "ResourceSnapshotJobIdentifier": "*string"},
			"stop-resource-snapshot-job":                    {"Catalog": "*string", "ResourceSnapshotJobIdentifier": "*string"},
			"submit-opportunity":                            {"Catalog": "*string", "Identifier": "*string", "InvolvementType": "types.SalesInvolvementType", "Visibility": "types.Visibility"},
			"tag-resource":                                  {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                                {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-engagement-context":                     {"Catalog": "*string", "ContextIdentifier": "*string", "EngagementIdentifier": "*string", "EngagementLastModifiedAt": "*time.Time", "Payload": "types.UpdateEngagementContextPayload", "Type": "types.EngagementContextType"},
			"update-opportunity":                            {"Catalog": "*string", "Customer": "*types.Customer", "Identifier": "*string", "LastModifiedDate": "*time.Time", "LifeCycle": "*types.LifeCycle", "Marketing": "*types.Marketing", "NationalSecurity": "types.NationalSecurity", "OpportunityType": "types.OpportunityType", "PartnerOpportunityIdentifier": "*string", "PrimaryNeedsFromAws": "[]types.PrimaryNeedFromAws", "Project": "*types.Project", "SoftwareRevenue": "*types.SoftwareRevenue"},
		},
		OperationInputRequired: map[string][]string{
			"accept-engagement-invitation":                  {"Catalog", "Identifier"},
			"assign-opportunity":                            {"Assignee", "Catalog", "Identifier"},
			"associate-opportunity":                         {"Catalog", "OpportunityIdentifier", "RelatedEntityIdentifier", "RelatedEntityType"},
			"create-engagement":                             {"Catalog", "ClientToken", "Description", "Title"},
			"create-engagement-context":                     {"Catalog", "ClientToken", "EngagementIdentifier", "Payload", "Type"},
			"create-engagement-invitation":                  {"Catalog", "ClientToken", "EngagementIdentifier", "Invitation"},
			"create-opportunity":                            {"Catalog", "ClientToken"},
			"create-resource-snapshot":                      {"Catalog", "ClientToken", "EngagementIdentifier", "ResourceIdentifier", "ResourceSnapshotTemplateIdentifier", "ResourceType"},
			"create-resource-snapshot-job":                  {"Catalog", "ClientToken", "EngagementIdentifier", "ResourceIdentifier", "ResourceSnapshotTemplateIdentifier", "ResourceType"},
			"delete-resource-snapshot-job":                  {"Catalog", "ResourceSnapshotJobIdentifier"},
			"disassociate-opportunity":                      {"Catalog", "OpportunityIdentifier", "RelatedEntityIdentifier", "RelatedEntityType"},
			"get-aws-opportunity-summary":                   {"Catalog", "RelatedOpportunityIdentifier"},
			"get-engagement":                                {"Catalog", "Identifier"},
			"get-engagement-invitation":                     {"Catalog", "Identifier"},
			"get-opportunity":                               {"Catalog", "Identifier"},
			"get-resource-snapshot":                         {"Catalog", "EngagementIdentifier", "ResourceIdentifier", "ResourceSnapshotTemplateIdentifier", "ResourceType"},
			"get-resource-snapshot-job":                     {"Catalog", "ResourceSnapshotJobIdentifier"},
			"get-selling-system-settings":                   {"Catalog"},
			"list-engagement-by-accepting-invitation-tasks": {"Catalog"},
			"list-engagement-from-opportunity-tasks":        {"Catalog"},
			"list-engagement-invitations":                   {"Catalog", "ParticipantType"},
			"list-engagement-members":                       {"Catalog", "Identifier"},
			"list-engagement-resource-associations":         {"Catalog"},
			"list-engagements":                              {"Catalog"},
			"list-opportunities":                            {"Catalog"},
			"list-opportunity-from-engagement-tasks":        {"Catalog"},
			"list-resource-snapshot-jobs":                   {"Catalog"},
			"list-resource-snapshots":                       {"Catalog", "EngagementIdentifier"},
			"list-solutions":                                {"Catalog"},
			"list-tags-for-resource":                        {"ResourceArn"},
			"put-selling-system-settings":                   {"Catalog"},
			"reject-engagement-invitation":                  {"Catalog", "Identifier"},
			"start-engagement-by-accepting-invitation-task": {"Catalog", "ClientToken", "Identifier"},
			"start-engagement-from-opportunity-task":        {"AwsSubmission", "Catalog", "ClientToken", "Identifier"},
			"start-opportunity-from-engagement-task":        {"Catalog", "ClientToken", "ContextIdentifier", "Identifier"},
			"start-resource-snapshot-job":                   {"Catalog", "ResourceSnapshotJobIdentifier"},
			"stop-resource-snapshot-job":                    {"Catalog", "ResourceSnapshotJobIdentifier"},
			"submit-opportunity":                            {"Catalog", "Identifier", "InvolvementType"},
			"tag-resource":                                  {"ResourceArn", "Tags"},
			"untag-resource":                                {"ResourceArn", "TagKeys"},
			"update-engagement-context":                     {"Catalog", "ContextIdentifier", "EngagementIdentifier", "EngagementLastModifiedAt", "Payload", "Type"},
			"update-opportunity":                            {"Catalog", "Identifier", "LastModifiedDate"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("partnercentralselling", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
