package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/pinpointsmsvoicev2/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-origination-identity", "associate-protect-configuration", "carrier-lookup", "create-configuration-set", "create-event-destination", "create-opt-out-list", "create-pool", "create-protect-configuration", "create-registration", "create-registration-association", "create-registration-attachment", "create-registration-version", "create-verified-destination-number", "delete-account-default-protect-configuration", "delete-configuration-set", "delete-default-message-type", "delete-default-sender-id", "delete-event-destination", "delete-keyword", "delete-media-message-spend-limit-override", "delete-opt-out-list", "delete-opted-out-number", "delete-pool", "delete-protect-configuration", "delete-protect-configuration-rule-set-number-override", "delete-registration", "delete-registration-attachment", "delete-registration-field-value", "delete-resource-policy", "delete-text-message-spend-limit-override", "delete-verified-destination-number", "delete-voice-message-spend-limit-override", "describe-account-attributes", "describe-account-limits", "describe-configuration-sets", "describe-keywords", "describe-opt-out-lists", "describe-opted-out-numbers", "describe-phone-numbers", "describe-pools", "describe-protect-configurations", "describe-registration-attachments", "describe-registration-field-definitions", "describe-registration-field-values", "describe-registration-section-definitions", "describe-registration-type-definitions", "describe-registration-versions", "describe-registrations", "describe-sender-ids", "describe-spend-limits", "describe-verified-destination-numbers", "disassociate-origination-identity", "disassociate-protect-configuration", "discard-registration-version", "get-protect-configuration-country-rule-set", "get-resource-policy", "list-pool-origination-identities", "list-protect-configuration-rule-set-number-overrides", "list-registration-associations", "list-tags-for-resource", "put-keyword", "put-message-feedback", "put-opted-out-number", "put-protect-configuration-rule-set-number-override", "put-registration-field-value", "put-resource-policy", "release-phone-number", "release-sender-id", "request-phone-number", "request-sender-id", "send-destination-number-verification-code", "send-media-message", "send-text-message", "send-voice-message", "set-account-default-protect-configuration", "set-default-message-feedback-enabled", "set-default-message-type", "set-default-sender-id", "set-media-message-spend-limit-override", "set-text-message-spend-limit-override", "set-voice-message-spend-limit-override", "submit-registration-version", "tag-resource", "untag-resource", "update-event-destination", "update-phone-number", "update-pool", "update-protect-configuration", "update-protect-configuration-country-rule-set", "update-sender-id", "verify-destination-number"},
		OperationSet: map[string]bool{"associate-origination-identity": true, "associate-protect-configuration": true, "carrier-lookup": true, "create-configuration-set": true, "create-event-destination": true, "create-opt-out-list": true, "create-pool": true, "create-protect-configuration": true, "create-registration": true, "create-registration-association": true, "create-registration-attachment": true, "create-registration-version": true, "create-verified-destination-number": true, "delete-account-default-protect-configuration": true, "delete-configuration-set": true, "delete-default-message-type": true, "delete-default-sender-id": true, "delete-event-destination": true, "delete-keyword": true, "delete-media-message-spend-limit-override": true, "delete-opt-out-list": true, "delete-opted-out-number": true, "delete-pool": true, "delete-protect-configuration": true, "delete-protect-configuration-rule-set-number-override": true, "delete-registration": true, "delete-registration-attachment": true, "delete-registration-field-value": true, "delete-resource-policy": true, "delete-text-message-spend-limit-override": true, "delete-verified-destination-number": true, "delete-voice-message-spend-limit-override": true, "describe-account-attributes": true, "describe-account-limits": true, "describe-configuration-sets": true, "describe-keywords": true, "describe-opt-out-lists": true, "describe-opted-out-numbers": true, "describe-phone-numbers": true, "describe-pools": true, "describe-protect-configurations": true, "describe-registration-attachments": true, "describe-registration-field-definitions": true, "describe-registration-field-values": true, "describe-registration-section-definitions": true, "describe-registration-type-definitions": true, "describe-registration-versions": true, "describe-registrations": true, "describe-sender-ids": true, "describe-spend-limits": true, "describe-verified-destination-numbers": true, "disassociate-origination-identity": true, "disassociate-protect-configuration": true, "discard-registration-version": true, "get-protect-configuration-country-rule-set": true, "get-resource-policy": true, "list-pool-origination-identities": true, "list-protect-configuration-rule-set-number-overrides": true, "list-registration-associations": true, "list-tags-for-resource": true, "put-keyword": true, "put-message-feedback": true, "put-opted-out-number": true, "put-protect-configuration-rule-set-number-override": true, "put-registration-field-value": true, "put-resource-policy": true, "release-phone-number": true, "release-sender-id": true, "request-phone-number": true, "request-sender-id": true, "send-destination-number-verification-code": true, "send-media-message": true, "send-text-message": true, "send-voice-message": true, "set-account-default-protect-configuration": true, "set-default-message-feedback-enabled": true, "set-default-message-type": true, "set-default-sender-id": true, "set-media-message-spend-limit-override": true, "set-text-message-spend-limit-override": true, "set-voice-message-spend-limit-override": true, "submit-registration-version": true, "tag-resource": true, "untag-resource": true, "update-event-destination": true, "update-phone-number": true, "update-pool": true, "update-protect-configuration": true, "update-protect-configuration-country-rule-set": true, "update-sender-id": true, "verify-destination-number": true},
		OperationInputs: map[string][]string{
			"associate-origination-identity":                        {"ClientToken", "IsoCountryCode", "OriginationIdentity", "PoolId"},
			"associate-protect-configuration":                       {"ConfigurationSetName", "ProtectConfigurationId"},
			"carrier-lookup":                                        {"PhoneNumber"},
			"create-configuration-set":                              {"ClientToken", "ConfigurationSetName", "Tags"},
			"create-event-destination":                              {"ClientToken", "CloudWatchLogsDestination", "ConfigurationSetName", "EventDestinationName", "KinesisFirehoseDestination", "MatchingEventTypes", "SnsDestination"},
			"create-opt-out-list":                                   {"ClientToken", "OptOutListName", "Tags"},
			"create-pool":                                           {"ClientToken", "DeletionProtectionEnabled", "IsoCountryCode", "MessageType", "OriginationIdentity", "Tags"},
			"create-protect-configuration":                          {"ClientToken", "DeletionProtectionEnabled", "Tags"},
			"create-registration":                                   {"ClientToken", "RegistrationType", "Tags"},
			"create-registration-association":                       {"RegistrationId", "ResourceId"},
			"create-registration-attachment":                        {"AttachmentBody", "AttachmentUrl", "ClientToken", "Tags"},
			"create-registration-version":                           {"RegistrationId"},
			"create-verified-destination-number":                    {"ClientToken", "DestinationPhoneNumber", "Tags"},
			"delete-account-default-protect-configuration":          {},
			"delete-configuration-set":                              {"ConfigurationSetName"},
			"delete-default-message-type":                           {"ConfigurationSetName"},
			"delete-default-sender-id":                              {"ConfigurationSetName"},
			"delete-event-destination":                              {"ConfigurationSetName", "EventDestinationName"},
			"delete-keyword":                                        {"Keyword", "OriginationIdentity"},
			"delete-media-message-spend-limit-override":             {},
			"delete-opt-out-list":                                   {"OptOutListName"},
			"delete-opted-out-number":                               {"OptOutListName", "OptedOutNumber"},
			"delete-pool":                                           {"PoolId"},
			"delete-protect-configuration":                          {"ProtectConfigurationId"},
			"delete-protect-configuration-rule-set-number-override": {"DestinationPhoneNumber", "ProtectConfigurationId"},
			"delete-registration":                                   {"RegistrationId"},
			"delete-registration-attachment":                        {"RegistrationAttachmentId"},
			"delete-registration-field-value":                       {"FieldPath", "RegistrationId"},
			"delete-resource-policy":                                {"ResourceArn"},
			"delete-text-message-spend-limit-override":              {},
			"delete-verified-destination-number":                    {"VerifiedDestinationNumberId"},
			"delete-voice-message-spend-limit-override":             {},
			"describe-account-attributes":                           {"MaxResults", "NextToken"},
			"describe-account-limits":                               {"MaxResults", "NextToken"},
			"describe-configuration-sets":                           {"ConfigurationSetNames", "Filters", "MaxResults", "NextToken"},
			"describe-keywords":                                     {"Filters", "Keywords", "MaxResults", "NextToken", "OriginationIdentity"},
			"describe-opt-out-lists":                                {"MaxResults", "NextToken", "OptOutListNames", "Owner"},
			"describe-opted-out-numbers":                            {"Filters", "MaxResults", "NextToken", "OptOutListName", "OptedOutNumbers"},
			"describe-phone-numbers":                                {"Filters", "MaxResults", "NextToken", "Owner", "PhoneNumberIds"},
			"describe-pools":                                        {"Filters", "MaxResults", "NextToken", "Owner", "PoolIds"},
			"describe-protect-configurations":                       {"Filters", "MaxResults", "NextToken", "ProtectConfigurationIds"},
			"describe-registration-attachments":                     {"Filters", "MaxResults", "NextToken", "RegistrationAttachmentIds"},
			"describe-registration-field-definitions":               {"FieldPaths", "MaxResults", "NextToken", "RegistrationType", "SectionPath"},
			"describe-registration-field-values":                    {"FieldPaths", "MaxResults", "NextToken", "RegistrationId", "SectionPath", "VersionNumber"},
			"describe-registration-section-definitions":             {"MaxResults", "NextToken", "RegistrationType", "SectionPaths"},
			"describe-registration-type-definitions":                {"Filters", "MaxResults", "NextToken", "RegistrationTypes"},
			"describe-registration-versions":                        {"Filters", "MaxResults", "NextToken", "RegistrationId", "VersionNumbers"},
			"describe-registrations":                                {"Filters", "MaxResults", "NextToken", "RegistrationIds"},
			"describe-sender-ids":                                   {"Filters", "MaxResults", "NextToken", "Owner", "SenderIds"},
			"describe-spend-limits":                                 {"MaxResults", "NextToken"},
			"describe-verified-destination-numbers":                 {"DestinationPhoneNumbers", "Filters", "MaxResults", "NextToken", "VerifiedDestinationNumberIds"},
			"disassociate-origination-identity":                     {"ClientToken", "IsoCountryCode", "OriginationIdentity", "PoolId"},
			"disassociate-protect-configuration":                    {"ConfigurationSetName", "ProtectConfigurationId"},
			"discard-registration-version":                          {"RegistrationId"},
			"get-protect-configuration-country-rule-set":            {"NumberCapability", "ProtectConfigurationId"},
			"get-resource-policy":                                   {"ResourceArn"},
			"list-pool-origination-identities":                      {"Filters", "MaxResults", "NextToken", "PoolId"},
			"list-protect-configuration-rule-set-number-overrides":  {"Filters", "MaxResults", "NextToken", "ProtectConfigurationId"},
			"list-registration-associations":                        {"Filters", "MaxResults", "NextToken", "RegistrationId"},
			"list-tags-for-resource":                                {"ResourceArn"},
			"put-keyword":                                           {"Keyword", "KeywordAction", "KeywordMessage", "OriginationIdentity"},
			"put-message-feedback":                                  {"MessageFeedbackStatus", "MessageId"},
			"put-opted-out-number":                                  {"OptOutListName", "OptedOutNumber"},
			"put-protect-configuration-rule-set-number-override":    {"Action", "ClientToken", "DestinationPhoneNumber", "ExpirationTimestamp", "ProtectConfigurationId"},
			"put-registration-field-value":                          {"FieldPath", "RegistrationAttachmentId", "RegistrationId", "SelectChoices", "TextValue"},
			"put-resource-policy":                                   {"Policy", "ResourceArn"},
			"release-phone-number":                                  {"PhoneNumberId"},
			"release-sender-id":                                     {"IsoCountryCode", "SenderId"},
			"request-phone-number":                                  {"ClientToken", "DeletionProtectionEnabled", "InternationalSendingEnabled", "IsoCountryCode", "MessageType", "NumberCapabilities", "NumberType", "OptOutListName", "PoolId", "RegistrationId", "Tags"},
			"request-sender-id":                                     {"ClientToken", "DeletionProtectionEnabled", "IsoCountryCode", "MessageTypes", "SenderId", "Tags"},
			"send-destination-number-verification-code":             {"ConfigurationSetName", "Context", "DestinationCountryParameters", "LanguageCode", "OriginationIdentity", "VerificationChannel", "VerifiedDestinationNumberId"},
			"send-media-message":                                    {"ConfigurationSetName", "Context", "DestinationPhoneNumber", "DryRun", "MaxPrice", "MediaUrls", "MessageBody", "MessageFeedbackEnabled", "OriginationIdentity", "ProtectConfigurationId", "TimeToLive"},
			"send-text-message":                                     {"ConfigurationSetName", "Context", "DestinationCountryParameters", "DestinationPhoneNumber", "DryRun", "Keyword", "MaxPrice", "MessageBody", "MessageFeedbackEnabled", "MessageType", "OriginationIdentity", "ProtectConfigurationId", "TimeToLive"},
			"send-voice-message":                                    {"ConfigurationSetName", "Context", "DestinationPhoneNumber", "DryRun", "MaxPricePerMinute", "MessageBody", "MessageBodyTextType", "MessageFeedbackEnabled", "OriginationIdentity", "ProtectConfigurationId", "TimeToLive", "VoiceId"},
			"set-account-default-protect-configuration":             {"ProtectConfigurationId"},
			"set-default-message-feedback-enabled":                  {"ConfigurationSetName", "MessageFeedbackEnabled"},
			"set-default-message-type":                              {"ConfigurationSetName", "MessageType"},
			"set-default-sender-id":                                 {"ConfigurationSetName", "SenderId"},
			"set-media-message-spend-limit-override":                {"MonthlyLimit"},
			"set-text-message-spend-limit-override":                 {"MonthlyLimit"},
			"set-voice-message-spend-limit-override":                {"MonthlyLimit"},
			"submit-registration-version":                           {"AwsReview", "RegistrationId"},
			"tag-resource":                                          {"ResourceArn", "Tags"},
			"untag-resource":                                        {"ResourceArn", "TagKeys"},
			"update-event-destination":                              {"CloudWatchLogsDestination", "ConfigurationSetName", "Enabled", "EventDestinationName", "KinesisFirehoseDestination", "MatchingEventTypes", "SnsDestination"},
			"update-phone-number":                                   {"DeletionProtectionEnabled", "InternationalSendingEnabled", "OptOutListName", "PhoneNumberId", "SelfManagedOptOutsEnabled", "TwoWayChannelArn", "TwoWayChannelRole", "TwoWayEnabled"},
			"update-pool":                                           {"DeletionProtectionEnabled", "OptOutListName", "PoolId", "SelfManagedOptOutsEnabled", "SharedRoutesEnabled", "TwoWayChannelArn", "TwoWayChannelRole", "TwoWayEnabled"},
			"update-protect-configuration":                          {"DeletionProtectionEnabled", "ProtectConfigurationId"},
			"update-protect-configuration-country-rule-set":         {"CountryRuleSetUpdates", "NumberCapability", "ProtectConfigurationId"},
			"update-sender-id":                                      {"DeletionProtectionEnabled", "IsoCountryCode", "SenderId"},
			"verify-destination-number":                             {"VerificationCode", "VerifiedDestinationNumberId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-origination-identity":                        {"ClientToken": "*string", "IsoCountryCode": "*string", "OriginationIdentity": "*string", "PoolId": "*string"},
			"associate-protect-configuration":                       {"ConfigurationSetName": "*string", "ProtectConfigurationId": "*string"},
			"carrier-lookup":                                        {"PhoneNumber": "*string"},
			"create-configuration-set":                              {"ClientToken": "*string", "ConfigurationSetName": "*string", "Tags": "[]types.Tag"},
			"create-event-destination":                              {"ClientToken": "*string", "CloudWatchLogsDestination": "*types.CloudWatchLogsDestination", "ConfigurationSetName": "*string", "EventDestinationName": "*string", "KinesisFirehoseDestination": "*types.KinesisFirehoseDestination", "MatchingEventTypes": "[]types.EventType", "SnsDestination": "*types.SnsDestination"},
			"create-opt-out-list":                                   {"ClientToken": "*string", "OptOutListName": "*string", "Tags": "[]types.Tag"},
			"create-pool":                                           {"ClientToken": "*string", "DeletionProtectionEnabled": "*bool", "IsoCountryCode": "*string", "MessageType": "types.MessageType", "OriginationIdentity": "*string", "Tags": "[]types.Tag"},
			"create-protect-configuration":                          {"ClientToken": "*string", "DeletionProtectionEnabled": "*bool", "Tags": "[]types.Tag"},
			"create-registration":                                   {"ClientToken": "*string", "RegistrationType": "*string", "Tags": "[]types.Tag"},
			"create-registration-association":                       {"RegistrationId": "*string", "ResourceId": "*string"},
			"create-registration-attachment":                        {"AttachmentBody": "[]byte", "AttachmentUrl": "*string", "ClientToken": "*string", "Tags": "[]types.Tag"},
			"create-registration-version":                           {"RegistrationId": "*string"},
			"create-verified-destination-number":                    {"ClientToken": "*string", "DestinationPhoneNumber": "*string", "Tags": "[]types.Tag"},
			"delete-account-default-protect-configuration":          {},
			"delete-configuration-set":                              {"ConfigurationSetName": "*string"},
			"delete-default-message-type":                           {"ConfigurationSetName": "*string"},
			"delete-default-sender-id":                              {"ConfigurationSetName": "*string"},
			"delete-event-destination":                              {"ConfigurationSetName": "*string", "EventDestinationName": "*string"},
			"delete-keyword":                                        {"Keyword": "*string", "OriginationIdentity": "*string"},
			"delete-media-message-spend-limit-override":             {},
			"delete-opt-out-list":                                   {"OptOutListName": "*string"},
			"delete-opted-out-number":                               {"OptOutListName": "*string", "OptedOutNumber": "*string"},
			"delete-pool":                                           {"PoolId": "*string"},
			"delete-protect-configuration":                          {"ProtectConfigurationId": "*string"},
			"delete-protect-configuration-rule-set-number-override": {"DestinationPhoneNumber": "*string", "ProtectConfigurationId": "*string"},
			"delete-registration":                                   {"RegistrationId": "*string"},
			"delete-registration-attachment":                        {"RegistrationAttachmentId": "*string"},
			"delete-registration-field-value":                       {"FieldPath": "*string", "RegistrationId": "*string"},
			"delete-resource-policy":                                {"ResourceArn": "*string"},
			"delete-text-message-spend-limit-override":              {},
			"delete-verified-destination-number":                    {"VerifiedDestinationNumberId": "*string"},
			"delete-voice-message-spend-limit-override":             {},
			"describe-account-attributes":                           {"MaxResults": "*int32", "NextToken": "*string"},
			"describe-account-limits":                               {"MaxResults": "*int32", "NextToken": "*string"},
			"describe-configuration-sets":                           {"ConfigurationSetNames": "[]string", "Filters": "[]types.ConfigurationSetFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-keywords":                                     {"Filters": "[]types.KeywordFilter", "Keywords": "[]string", "MaxResults": "*int32", "NextToken": "*string", "OriginationIdentity": "*string"},
			"describe-opt-out-lists":                                {"MaxResults": "*int32", "NextToken": "*string", "OptOutListNames": "[]string", "Owner": "types.Owner"},
			"describe-opted-out-numbers":                            {"Filters": "[]types.OptedOutFilter", "MaxResults": "*int32", "NextToken": "*string", "OptOutListName": "*string", "OptedOutNumbers": "[]string"},
			"describe-phone-numbers":                                {"Filters": "[]types.PhoneNumberFilter", "MaxResults": "*int32", "NextToken": "*string", "Owner": "types.Owner", "PhoneNumberIds": "[]string"},
			"describe-pools":                                        {"Filters": "[]types.PoolFilter", "MaxResults": "*int32", "NextToken": "*string", "Owner": "types.Owner", "PoolIds": "[]string"},
			"describe-protect-configurations":                       {"Filters": "[]types.ProtectConfigurationFilter", "MaxResults": "*int32", "NextToken": "*string", "ProtectConfigurationIds": "[]string"},
			"describe-registration-attachments":                     {"Filters": "[]types.RegistrationAttachmentFilter", "MaxResults": "*int32", "NextToken": "*string", "RegistrationAttachmentIds": "[]string"},
			"describe-registration-field-definitions":               {"FieldPaths": "[]string", "MaxResults": "*int32", "NextToken": "*string", "RegistrationType": "*string", "SectionPath": "*string"},
			"describe-registration-field-values":                    {"FieldPaths": "[]string", "MaxResults": "*int32", "NextToken": "*string", "RegistrationId": "*string", "SectionPath": "*string", "VersionNumber": "*int64"},
			"describe-registration-section-definitions":             {"MaxResults": "*int32", "NextToken": "*string", "RegistrationType": "*string", "SectionPaths": "[]string"},
			"describe-registration-type-definitions":                {"Filters": "[]types.RegistrationTypeFilter", "MaxResults": "*int32", "NextToken": "*string", "RegistrationTypes": "[]string"},
			"describe-registration-versions":                        {"Filters": "[]types.RegistrationVersionFilter", "MaxResults": "*int32", "NextToken": "*string", "RegistrationId": "*string", "VersionNumbers": "[]int64"},
			"describe-registrations":                                {"Filters": "[]types.RegistrationFilter", "MaxResults": "*int32", "NextToken": "*string", "RegistrationIds": "[]string"},
			"describe-sender-ids":                                   {"Filters": "[]types.SenderIdFilter", "MaxResults": "*int32", "NextToken": "*string", "Owner": "types.Owner", "SenderIds": "[]types.SenderIdAndCountry"},
			"describe-spend-limits":                                 {"MaxResults": "*int32", "NextToken": "*string"},
			"describe-verified-destination-numbers":                 {"DestinationPhoneNumbers": "[]string", "Filters": "[]types.VerifiedDestinationNumberFilter", "MaxResults": "*int32", "NextToken": "*string", "VerifiedDestinationNumberIds": "[]string"},
			"disassociate-origination-identity":                     {"ClientToken": "*string", "IsoCountryCode": "*string", "OriginationIdentity": "*string", "PoolId": "*string"},
			"disassociate-protect-configuration":                    {"ConfigurationSetName": "*string", "ProtectConfigurationId": "*string"},
			"discard-registration-version":                          {"RegistrationId": "*string"},
			"get-protect-configuration-country-rule-set":            {"NumberCapability": "types.NumberCapability", "ProtectConfigurationId": "*string"},
			"get-resource-policy":                                   {"ResourceArn": "*string"},
			"list-pool-origination-identities":                      {"Filters": "[]types.PoolOriginationIdentitiesFilter", "MaxResults": "*int32", "NextToken": "*string", "PoolId": "*string"},
			"list-protect-configuration-rule-set-number-overrides":  {"Filters": "[]types.ProtectConfigurationRuleSetNumberOverrideFilterItem", "MaxResults": "*int32", "NextToken": "*string", "ProtectConfigurationId": "*string"},
			"list-registration-associations":                        {"Filters": "[]types.RegistrationAssociationFilter", "MaxResults": "*int32", "NextToken": "*string", "RegistrationId": "*string"},
			"list-tags-for-resource":                                {"ResourceArn": "*string"},
			"put-keyword":                                           {"Keyword": "*string", "KeywordAction": "types.KeywordAction", "KeywordMessage": "*string", "OriginationIdentity": "*string"},
			"put-message-feedback":                                  {"MessageFeedbackStatus": "types.MessageFeedbackStatus", "MessageId": "*string"},
			"put-opted-out-number":                                  {"OptOutListName": "*string", "OptedOutNumber": "*string"},
			"put-protect-configuration-rule-set-number-override":    {"Action": "types.ProtectConfigurationRuleOverrideAction", "ClientToken": "*string", "DestinationPhoneNumber": "*string", "ExpirationTimestamp": "*time.Time", "ProtectConfigurationId": "*string"},
			"put-registration-field-value":                          {"FieldPath": "*string", "RegistrationAttachmentId": "*string", "RegistrationId": "*string", "SelectChoices": "[]string", "TextValue": "*string"},
			"put-resource-policy":                                   {"Policy": "*string", "ResourceArn": "*string"},
			"release-phone-number":                                  {"PhoneNumberId": "*string"},
			"release-sender-id":                                     {"IsoCountryCode": "*string", "SenderId": "*string"},
			"request-phone-number":                                  {"ClientToken": "*string", "DeletionProtectionEnabled": "*bool", "InternationalSendingEnabled": "*bool", "IsoCountryCode": "*string", "MessageType": "types.MessageType", "NumberCapabilities": "[]types.NumberCapability", "NumberType": "types.RequestableNumberType", "OptOutListName": "*string", "PoolId": "*string", "RegistrationId": "*string", "Tags": "[]types.Tag"},
			"request-sender-id":                                     {"ClientToken": "*string", "DeletionProtectionEnabled": "*bool", "IsoCountryCode": "*string", "MessageTypes": "[]types.MessageType", "SenderId": "*string", "Tags": "[]types.Tag"},
			"send-destination-number-verification-code":             {"ConfigurationSetName": "*string", "Context": "map[string]string", "DestinationCountryParameters": "map[string]string", "LanguageCode": "types.LanguageCode", "OriginationIdentity": "*string", "VerificationChannel": "types.VerificationChannel", "VerifiedDestinationNumberId": "*string"},
			"send-media-message":                                    {"ConfigurationSetName": "*string", "Context": "map[string]string", "DestinationPhoneNumber": "*string", "DryRun": "bool", "MaxPrice": "*string", "MediaUrls": "[]string", "MessageBody": "*string", "MessageFeedbackEnabled": "*bool", "OriginationIdentity": "*string", "ProtectConfigurationId": "*string", "TimeToLive": "*int32"},
			"send-text-message":                                     {"ConfigurationSetName": "*string", "Context": "map[string]string", "DestinationCountryParameters": "map[string]string", "DestinationPhoneNumber": "*string", "DryRun": "bool", "Keyword": "*string", "MaxPrice": "*string", "MessageBody": "*string", "MessageFeedbackEnabled": "*bool", "MessageType": "types.MessageType", "OriginationIdentity": "*string", "ProtectConfigurationId": "*string", "TimeToLive": "*int32"},
			"send-voice-message":                                    {"ConfigurationSetName": "*string", "Context": "map[string]string", "DestinationPhoneNumber": "*string", "DryRun": "bool", "MaxPricePerMinute": "*string", "MessageBody": "*string", "MessageBodyTextType": "types.VoiceMessageBodyTextType", "MessageFeedbackEnabled": "*bool", "OriginationIdentity": "*string", "ProtectConfigurationId": "*string", "TimeToLive": "*int32", "VoiceId": "types.VoiceId"},
			"set-account-default-protect-configuration":             {"ProtectConfigurationId": "*string"},
			"set-default-message-feedback-enabled":                  {"ConfigurationSetName": "*string", "MessageFeedbackEnabled": "*bool"},
			"set-default-message-type":                              {"ConfigurationSetName": "*string", "MessageType": "types.MessageType"},
			"set-default-sender-id":                                 {"ConfigurationSetName": "*string", "SenderId": "*string"},
			"set-media-message-spend-limit-override":                {"MonthlyLimit": "*int64"},
			"set-text-message-spend-limit-override":                 {"MonthlyLimit": "*int64"},
			"set-voice-message-spend-limit-override":                {"MonthlyLimit": "*int64"},
			"submit-registration-version":                           {"AwsReview": "bool", "RegistrationId": "*string"},
			"tag-resource":                                          {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                                        {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-event-destination":                              {"CloudWatchLogsDestination": "*types.CloudWatchLogsDestination", "ConfigurationSetName": "*string", "Enabled": "*bool", "EventDestinationName": "*string", "KinesisFirehoseDestination": "*types.KinesisFirehoseDestination", "MatchingEventTypes": "[]types.EventType", "SnsDestination": "*types.SnsDestination"},
			"update-phone-number":                                   {"DeletionProtectionEnabled": "*bool", "InternationalSendingEnabled": "*bool", "OptOutListName": "*string", "PhoneNumberId": "*string", "SelfManagedOptOutsEnabled": "*bool", "TwoWayChannelArn": "*string", "TwoWayChannelRole": "*string", "TwoWayEnabled": "*bool"},
			"update-pool":                                           {"DeletionProtectionEnabled": "*bool", "OptOutListName": "*string", "PoolId": "*string", "SelfManagedOptOutsEnabled": "*bool", "SharedRoutesEnabled": "*bool", "TwoWayChannelArn": "*string", "TwoWayChannelRole": "*string", "TwoWayEnabled": "*bool"},
			"update-protect-configuration":                          {"DeletionProtectionEnabled": "*bool", "ProtectConfigurationId": "*string"},
			"update-protect-configuration-country-rule-set":         {"CountryRuleSetUpdates": "map[string]types.ProtectConfigurationCountryRuleSetInformation", "NumberCapability": "types.NumberCapability", "ProtectConfigurationId": "*string"},
			"update-sender-id":                                      {"DeletionProtectionEnabled": "*bool", "IsoCountryCode": "*string", "SenderId": "*string"},
			"verify-destination-number":                             {"VerificationCode": "*string", "VerifiedDestinationNumberId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-origination-identity":                        {"IsoCountryCode", "OriginationIdentity", "PoolId"},
			"associate-protect-configuration":                       {"ConfigurationSetName", "ProtectConfigurationId"},
			"carrier-lookup":                                        {"PhoneNumber"},
			"create-configuration-set":                              {"ConfigurationSetName"},
			"create-event-destination":                              {"ConfigurationSetName", "EventDestinationName", "MatchingEventTypes"},
			"create-opt-out-list":                                   {"OptOutListName"},
			"create-pool":                                           {"IsoCountryCode", "MessageType", "OriginationIdentity"},
			"create-protect-configuration":                          {},
			"create-registration":                                   {"RegistrationType"},
			"create-registration-association":                       {"RegistrationId", "ResourceId"},
			"create-registration-attachment":                        {},
			"create-registration-version":                           {"RegistrationId"},
			"create-verified-destination-number":                    {"DestinationPhoneNumber"},
			"delete-account-default-protect-configuration":          {},
			"delete-configuration-set":                              {"ConfigurationSetName"},
			"delete-default-message-type":                           {"ConfigurationSetName"},
			"delete-default-sender-id":                              {"ConfigurationSetName"},
			"delete-event-destination":                              {"ConfigurationSetName", "EventDestinationName"},
			"delete-keyword":                                        {"Keyword", "OriginationIdentity"},
			"delete-media-message-spend-limit-override":             {},
			"delete-opt-out-list":                                   {"OptOutListName"},
			"delete-opted-out-number":                               {"OptOutListName", "OptedOutNumber"},
			"delete-pool":                                           {"PoolId"},
			"delete-protect-configuration":                          {"ProtectConfigurationId"},
			"delete-protect-configuration-rule-set-number-override": {"DestinationPhoneNumber", "ProtectConfigurationId"},
			"delete-registration":                                   {"RegistrationId"},
			"delete-registration-attachment":                        {"RegistrationAttachmentId"},
			"delete-registration-field-value":                       {"FieldPath", "RegistrationId"},
			"delete-resource-policy":                                {"ResourceArn"},
			"delete-text-message-spend-limit-override":              {},
			"delete-verified-destination-number":                    {"VerifiedDestinationNumberId"},
			"delete-voice-message-spend-limit-override":             {},
			"describe-account-attributes":                           {},
			"describe-account-limits":                               {},
			"describe-configuration-sets":                           {},
			"describe-keywords":                                     {"OriginationIdentity"},
			"describe-opt-out-lists":                                {},
			"describe-opted-out-numbers":                            {"OptOutListName"},
			"describe-phone-numbers":                                {},
			"describe-pools":                                        {},
			"describe-protect-configurations":                       {},
			"describe-registration-attachments":                     {},
			"describe-registration-field-definitions":               {"RegistrationType"},
			"describe-registration-field-values":                    {"RegistrationId"},
			"describe-registration-section-definitions":             {"RegistrationType"},
			"describe-registration-type-definitions":                {},
			"describe-registration-versions":                        {"RegistrationId"},
			"describe-registrations":                                {},
			"describe-sender-ids":                                   {},
			"describe-spend-limits":                                 {},
			"describe-verified-destination-numbers":                 {},
			"disassociate-origination-identity":                     {"IsoCountryCode", "OriginationIdentity", "PoolId"},
			"disassociate-protect-configuration":                    {"ConfigurationSetName", "ProtectConfigurationId"},
			"discard-registration-version":                          {"RegistrationId"},
			"get-protect-configuration-country-rule-set":            {"NumberCapability", "ProtectConfigurationId"},
			"get-resource-policy":                                   {"ResourceArn"},
			"list-pool-origination-identities":                      {"PoolId"},
			"list-protect-configuration-rule-set-number-overrides":  {"ProtectConfigurationId"},
			"list-registration-associations":                        {"RegistrationId"},
			"list-tags-for-resource":                                {"ResourceArn"},
			"put-keyword":                                           {"Keyword", "KeywordMessage", "OriginationIdentity"},
			"put-message-feedback":                                  {"MessageFeedbackStatus", "MessageId"},
			"put-opted-out-number":                                  {"OptOutListName", "OptedOutNumber"},
			"put-protect-configuration-rule-set-number-override":    {"Action", "DestinationPhoneNumber", "ProtectConfigurationId"},
			"put-registration-field-value":                          {"FieldPath", "RegistrationId"},
			"put-resource-policy":                                   {"Policy", "ResourceArn"},
			"release-phone-number":                                  {"PhoneNumberId"},
			"release-sender-id":                                     {"IsoCountryCode", "SenderId"},
			"request-phone-number":                                  {"IsoCountryCode", "MessageType", "NumberCapabilities", "NumberType"},
			"request-sender-id":                                     {"IsoCountryCode", "SenderId"},
			"send-destination-number-verification-code":             {"VerificationChannel", "VerifiedDestinationNumberId"},
			"send-media-message":                                    {"DestinationPhoneNumber", "OriginationIdentity"},
			"send-text-message":                                     {"DestinationPhoneNumber"},
			"send-voice-message":                                    {"DestinationPhoneNumber", "OriginationIdentity"},
			"set-account-default-protect-configuration":             {"ProtectConfigurationId"},
			"set-default-message-feedback-enabled":                  {"ConfigurationSetName", "MessageFeedbackEnabled"},
			"set-default-message-type":                              {"ConfigurationSetName", "MessageType"},
			"set-default-sender-id":                                 {"ConfigurationSetName", "SenderId"},
			"set-media-message-spend-limit-override":                {"MonthlyLimit"},
			"set-text-message-spend-limit-override":                 {"MonthlyLimit"},
			"set-voice-message-spend-limit-override":                {"MonthlyLimit"},
			"submit-registration-version":                           {"RegistrationId"},
			"tag-resource":                                          {"ResourceArn", "Tags"},
			"untag-resource":                                        {"ResourceArn", "TagKeys"},
			"update-event-destination":                              {"ConfigurationSetName", "EventDestinationName"},
			"update-phone-number":                                   {"PhoneNumberId"},
			"update-pool":                                           {"PoolId"},
			"update-protect-configuration":                          {"ProtectConfigurationId"},
			"update-protect-configuration-country-rule-set":         {"CountryRuleSetUpdates", "NumberCapability", "ProtectConfigurationId"},
			"update-sender-id":                                      {"IsoCountryCode", "SenderId"},
			"verify-destination-number":                             {"VerificationCode", "VerifiedDestinationNumberId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("pinpointsmsvoicev2", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
