package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/controltower/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-landing-zone", "delete-landing-zone", "disable-baseline", "disable-control", "enable-baseline", "enable-control", "get-baseline", "get-baseline-operation", "get-control-operation", "get-enabled-baseline", "get-enabled-control", "get-landing-zone", "get-landing-zone-operation", "list-baselines", "list-control-operations", "list-enabled-baselines", "list-enabled-controls", "list-landing-zone-operations", "list-landing-zones", "list-tags-for-resource", "reset-enabled-baseline", "reset-enabled-control", "reset-landing-zone", "tag-resource", "untag-resource", "update-enabled-baseline", "update-enabled-control", "update-landing-zone"},
		OperationSet: map[string]bool{"create-landing-zone": true, "delete-landing-zone": true, "disable-baseline": true, "disable-control": true, "enable-baseline": true, "enable-control": true, "get-baseline": true, "get-baseline-operation": true, "get-control-operation": true, "get-enabled-baseline": true, "get-enabled-control": true, "get-landing-zone": true, "get-landing-zone-operation": true, "list-baselines": true, "list-control-operations": true, "list-enabled-baselines": true, "list-enabled-controls": true, "list-landing-zone-operations": true, "list-landing-zones": true, "list-tags-for-resource": true, "reset-enabled-baseline": true, "reset-enabled-control": true, "reset-landing-zone": true, "tag-resource": true, "untag-resource": true, "update-enabled-baseline": true, "update-enabled-control": true, "update-landing-zone": true},
		OperationInputs: map[string][]string{
			"create-landing-zone":          {"Manifest", "RemediationTypes", "Tags", "Version"},
			"delete-landing-zone":          {"LandingZoneIdentifier"},
			"disable-baseline":             {"EnabledBaselineIdentifier"},
			"disable-control":              {"ControlIdentifier", "EnabledControlIdentifier", "TargetIdentifier"},
			"enable-baseline":              {"BaselineIdentifier", "BaselineVersion", "Parameters", "Tags", "TargetIdentifier"},
			"enable-control":               {"ControlIdentifier", "Parameters", "Tags", "TargetIdentifier"},
			"get-baseline":                 {"BaselineIdentifier"},
			"get-baseline-operation":       {"OperationIdentifier"},
			"get-control-operation":        {"OperationIdentifier"},
			"get-enabled-baseline":         {"EnabledBaselineIdentifier"},
			"get-enabled-control":          {"EnabledControlIdentifier"},
			"get-landing-zone":             {"LandingZoneIdentifier"},
			"get-landing-zone-operation":   {"OperationIdentifier"},
			"list-baselines":               {"MaxResults", "NextToken"},
			"list-control-operations":      {"Filter", "MaxResults", "NextToken"},
			"list-enabled-baselines":       {"Filter", "IncludeChildren", "MaxResults", "NextToken"},
			"list-enabled-controls":        {"Filter", "IncludeChildren", "MaxResults", "NextToken", "TargetIdentifier"},
			"list-landing-zone-operations": {"Filter", "MaxResults", "NextToken"},
			"list-landing-zones":           {"MaxResults", "NextToken"},
			"list-tags-for-resource":       {"ResourceArn"},
			"reset-enabled-baseline":       {"EnabledBaselineIdentifier"},
			"reset-enabled-control":        {"EnabledControlIdentifier"},
			"reset-landing-zone":           {"LandingZoneIdentifier"},
			"tag-resource":                 {"ResourceArn", "Tags"},
			"untag-resource":               {"ResourceArn", "TagKeys"},
			"update-enabled-baseline":      {"BaselineVersion", "EnabledBaselineIdentifier", "Parameters"},
			"update-enabled-control":       {"EnabledControlIdentifier", "Parameters"},
			"update-landing-zone":          {"LandingZoneIdentifier", "Manifest", "RemediationTypes", "Version"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-landing-zone":          {"Manifest": "document.Interface", "RemediationTypes": "[]types.RemediationType", "Tags": "map[string]string", "Version": "*string"},
			"delete-landing-zone":          {"LandingZoneIdentifier": "*string"},
			"disable-baseline":             {"EnabledBaselineIdentifier": "*string"},
			"disable-control":              {"ControlIdentifier": "*string", "EnabledControlIdentifier": "*string", "TargetIdentifier": "*string"},
			"enable-baseline":              {"BaselineIdentifier": "*string", "BaselineVersion": "*string", "Parameters": "[]types.EnabledBaselineParameter", "Tags": "map[string]string", "TargetIdentifier": "*string"},
			"enable-control":               {"ControlIdentifier": "*string", "Parameters": "[]types.EnabledControlParameter", "Tags": "map[string]string", "TargetIdentifier": "*string"},
			"get-baseline":                 {"BaselineIdentifier": "*string"},
			"get-baseline-operation":       {"OperationIdentifier": "*string"},
			"get-control-operation":        {"OperationIdentifier": "*string"},
			"get-enabled-baseline":         {"EnabledBaselineIdentifier": "*string"},
			"get-enabled-control":          {"EnabledControlIdentifier": "*string"},
			"get-landing-zone":             {"LandingZoneIdentifier": "*string"},
			"get-landing-zone-operation":   {"OperationIdentifier": "*string"},
			"list-baselines":               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-control-operations":      {"Filter": "*types.ControlOperationFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-enabled-baselines":       {"Filter": "*types.EnabledBaselineFilter", "IncludeChildren": "bool", "MaxResults": "*int32", "NextToken": "*string"},
			"list-enabled-controls":        {"Filter": "*types.EnabledControlFilter", "IncludeChildren": "bool", "MaxResults": "*int32", "NextToken": "*string", "TargetIdentifier": "*string"},
			"list-landing-zone-operations": {"Filter": "*types.LandingZoneOperationFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-landing-zones":           {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":       {"ResourceArn": "*string"},
			"reset-enabled-baseline":       {"EnabledBaselineIdentifier": "*string"},
			"reset-enabled-control":        {"EnabledControlIdentifier": "*string"},
			"reset-landing-zone":           {"LandingZoneIdentifier": "*string"},
			"tag-resource":                 {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":               {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-enabled-baseline":      {"BaselineVersion": "*string", "EnabledBaselineIdentifier": "*string", "Parameters": "[]types.EnabledBaselineParameter"},
			"update-enabled-control":       {"EnabledControlIdentifier": "*string", "Parameters": "[]types.EnabledControlParameter"},
			"update-landing-zone":          {"LandingZoneIdentifier": "*string", "Manifest": "document.Interface", "RemediationTypes": "[]types.RemediationType", "Version": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-landing-zone":          {"Version"},
			"delete-landing-zone":          {"LandingZoneIdentifier"},
			"disable-baseline":             {"EnabledBaselineIdentifier"},
			"disable-control":              {},
			"enable-baseline":              {"BaselineIdentifier", "BaselineVersion", "TargetIdentifier"},
			"enable-control":               {"ControlIdentifier", "TargetIdentifier"},
			"get-baseline":                 {"BaselineIdentifier"},
			"get-baseline-operation":       {"OperationIdentifier"},
			"get-control-operation":        {"OperationIdentifier"},
			"get-enabled-baseline":         {"EnabledBaselineIdentifier"},
			"get-enabled-control":          {"EnabledControlIdentifier"},
			"get-landing-zone":             {"LandingZoneIdentifier"},
			"get-landing-zone-operation":   {"OperationIdentifier"},
			"list-baselines":               {},
			"list-control-operations":      {},
			"list-enabled-baselines":       {},
			"list-enabled-controls":        {},
			"list-landing-zone-operations": {},
			"list-landing-zones":           {},
			"list-tags-for-resource":       {"ResourceArn"},
			"reset-enabled-baseline":       {"EnabledBaselineIdentifier"},
			"reset-enabled-control":        {"EnabledControlIdentifier"},
			"reset-landing-zone":           {"LandingZoneIdentifier"},
			"tag-resource":                 {"ResourceArn", "Tags"},
			"untag-resource":               {"ResourceArn", "TagKeys"},
			"update-enabled-baseline":      {"BaselineVersion", "EnabledBaselineIdentifier"},
			"update-enabled-control":       {"EnabledControlIdentifier", "Parameters"},
			"update-landing-zone":          {"LandingZoneIdentifier", "Version"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("controltower", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
