package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/devopsguru/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-notification-channel", "delete-insight", "describe-account-health", "describe-account-overview", "describe-anomaly", "describe-event-sources-config", "describe-feedback", "describe-insight", "describe-organization-health", "describe-organization-overview", "describe-organization-resource-collection-health", "describe-resource-collection-health", "describe-service-integration", "get-cost-estimation", "get-resource-collection", "list-anomalies-for-insight", "list-anomalous-log-groups", "list-events", "list-insights", "list-monitored-resources", "list-notification-channels", "list-organization-insights", "list-recommendations", "put-feedback", "remove-notification-channel", "search-insights", "search-organization-insights", "start-cost-estimation", "update-event-sources-config", "update-resource-collection", "update-service-integration"},
		OperationSet: map[string]bool{"add-notification-channel": true, "delete-insight": true, "describe-account-health": true, "describe-account-overview": true, "describe-anomaly": true, "describe-event-sources-config": true, "describe-feedback": true, "describe-insight": true, "describe-organization-health": true, "describe-organization-overview": true, "describe-organization-resource-collection-health": true, "describe-resource-collection-health": true, "describe-service-integration": true, "get-cost-estimation": true, "get-resource-collection": true, "list-anomalies-for-insight": true, "list-anomalous-log-groups": true, "list-events": true, "list-insights": true, "list-monitored-resources": true, "list-notification-channels": true, "list-organization-insights": true, "list-recommendations": true, "put-feedback": true, "remove-notification-channel": true, "search-insights": true, "search-organization-insights": true, "start-cost-estimation": true, "update-event-sources-config": true, "update-resource-collection": true, "update-service-integration": true},
		OperationInputs: map[string][]string{
			"add-notification-channel":                         {"Config"},
			"delete-insight":                                   {"Id"},
			"describe-account-health":                          {},
			"describe-account-overview":                        {"FromTime", "ToTime"},
			"describe-anomaly":                                 {"AccountId", "Id"},
			"describe-event-sources-config":                    {},
			"describe-feedback":                                {"InsightId"},
			"describe-insight":                                 {"AccountId", "Id"},
			"describe-organization-health":                     {"AccountIds", "OrganizationalUnitIds"},
			"describe-organization-overview":                   {"AccountIds", "FromTime", "OrganizationalUnitIds", "ToTime"},
			"describe-organization-resource-collection-health": {"AccountIds", "MaxResults", "NextToken", "OrganizationResourceCollectionType", "OrganizationalUnitIds"},
			"describe-resource-collection-health":              {"NextToken", "ResourceCollectionType"},
			"describe-service-integration":                     {},
			"get-cost-estimation":                              {"NextToken"},
			"get-resource-collection":                          {"NextToken", "ResourceCollectionType"},
			"list-anomalies-for-insight":                       {"AccountId", "Filters", "InsightId", "MaxResults", "NextToken", "StartTimeRange"},
			"list-anomalous-log-groups":                        {"InsightId", "MaxResults", "NextToken"},
			"list-events":                                      {"AccountId", "Filters", "MaxResults", "NextToken"},
			"list-insights":                                    {"MaxResults", "NextToken", "StatusFilter"},
			"list-monitored-resources":                         {"Filters", "MaxResults", "NextToken"},
			"list-notification-channels":                       {"NextToken"},
			"list-organization-insights":                       {"AccountIds", "MaxResults", "NextToken", "OrganizationalUnitIds", "StatusFilter"},
			"list-recommendations":                             {"AccountId", "InsightId", "Locale", "NextToken"},
			"put-feedback":                                     {"InsightFeedback"},
			"remove-notification-channel":                      {"Id"},
			"search-insights":                                  {"Filters", "MaxResults", "NextToken", "StartTimeRange", "Type"},
			"search-organization-insights":                     {"AccountIds", "Filters", "MaxResults", "NextToken", "StartTimeRange", "Type"},
			"start-cost-estimation":                            {"ClientToken", "ResourceCollection"},
			"update-event-sources-config":                      {"EventSources"},
			"update-resource-collection":                       {"Action", "ResourceCollection"},
			"update-service-integration":                       {"ServiceIntegration"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-notification-channel":                         {"Config": "*types.NotificationChannelConfig"},
			"delete-insight":                                   {"Id": "*string"},
			"describe-account-health":                          {},
			"describe-account-overview":                        {"FromTime": "*time.Time", "ToTime": "*time.Time"},
			"describe-anomaly":                                 {"AccountId": "*string", "Id": "*string"},
			"describe-event-sources-config":                    {},
			"describe-feedback":                                {"InsightId": "*string"},
			"describe-insight":                                 {"AccountId": "*string", "Id": "*string"},
			"describe-organization-health":                     {"AccountIds": "[]string", "OrganizationalUnitIds": "[]string"},
			"describe-organization-overview":                   {"AccountIds": "[]string", "FromTime": "*time.Time", "OrganizationalUnitIds": "[]string", "ToTime": "*time.Time"},
			"describe-organization-resource-collection-health": {"AccountIds": "[]string", "MaxResults": "*int32", "NextToken": "*string", "OrganizationResourceCollectionType": "types.OrganizationResourceCollectionType", "OrganizationalUnitIds": "[]string"},
			"describe-resource-collection-health":              {"NextToken": "*string", "ResourceCollectionType": "types.ResourceCollectionType"},
			"describe-service-integration":                     {},
			"get-cost-estimation":                              {"NextToken": "*string"},
			"get-resource-collection":                          {"NextToken": "*string", "ResourceCollectionType": "types.ResourceCollectionType"},
			"list-anomalies-for-insight":                       {"AccountId": "*string", "Filters": "*types.ListAnomaliesForInsightFilters", "InsightId": "*string", "MaxResults": "*int32", "NextToken": "*string", "StartTimeRange": "*types.StartTimeRange"},
			"list-anomalous-log-groups":                        {"InsightId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-events":                                      {"AccountId": "*string", "Filters": "*types.ListEventsFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"list-insights":                                    {"MaxResults": "*int32", "NextToken": "*string", "StatusFilter": "*types.ListInsightsStatusFilter"},
			"list-monitored-resources":                         {"Filters": "*types.ListMonitoredResourcesFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"list-notification-channels":                       {"NextToken": "*string"},
			"list-organization-insights":                       {"AccountIds": "[]string", "MaxResults": "*int32", "NextToken": "*string", "OrganizationalUnitIds": "[]string", "StatusFilter": "*types.ListInsightsStatusFilter"},
			"list-recommendations":                             {"AccountId": "*string", "InsightId": "*string", "Locale": "types.Locale", "NextToken": "*string"},
			"put-feedback":                                     {"InsightFeedback": "*types.InsightFeedback"},
			"remove-notification-channel":                      {"Id": "*string"},
			"search-insights":                                  {"Filters": "*types.SearchInsightsFilters", "MaxResults": "*int32", "NextToken": "*string", "StartTimeRange": "*types.StartTimeRange", "Type": "types.InsightType"},
			"search-organization-insights":                     {"AccountIds": "[]string", "Filters": "*types.SearchOrganizationInsightsFilters", "MaxResults": "*int32", "NextToken": "*string", "StartTimeRange": "*types.StartTimeRange", "Type": "types.InsightType"},
			"start-cost-estimation":                            {"ClientToken": "*string", "ResourceCollection": "*types.CostEstimationResourceCollectionFilter"},
			"update-event-sources-config":                      {"EventSources": "*types.EventSourcesConfig"},
			"update-resource-collection":                       {"Action": "types.UpdateResourceCollectionAction", "ResourceCollection": "*types.UpdateResourceCollectionFilter"},
			"update-service-integration":                       {"ServiceIntegration": "*types.UpdateServiceIntegrationConfig"},
		},
		OperationInputRequired: map[string][]string{
			"add-notification-channel":                         {"Config"},
			"delete-insight":                                   {"Id"},
			"describe-account-health":                          {},
			"describe-account-overview":                        {"FromTime"},
			"describe-anomaly":                                 {"Id"},
			"describe-event-sources-config":                    {},
			"describe-feedback":                                {},
			"describe-insight":                                 {"Id"},
			"describe-organization-health":                     {},
			"describe-organization-overview":                   {"FromTime"},
			"describe-organization-resource-collection-health": {"OrganizationResourceCollectionType"},
			"describe-resource-collection-health":              {"ResourceCollectionType"},
			"describe-service-integration":                     {},
			"get-cost-estimation":                              {},
			"get-resource-collection":                          {"ResourceCollectionType"},
			"list-anomalies-for-insight":                       {"InsightId"},
			"list-anomalous-log-groups":                        {"InsightId"},
			"list-events":                                      {"Filters"},
			"list-insights":                                    {"StatusFilter"},
			"list-monitored-resources":                         {},
			"list-notification-channels":                       {},
			"list-organization-insights":                       {"StatusFilter"},
			"list-recommendations":                             {"InsightId"},
			"put-feedback":                                     {},
			"remove-notification-channel":                      {"Id"},
			"search-insights":                                  {"StartTimeRange", "Type"},
			"search-organization-insights":                     {"AccountIds", "StartTimeRange", "Type"},
			"start-cost-estimation":                            {"ResourceCollection"},
			"update-event-sources-config":                      {},
			"update-resource-collection":                       {"Action", "ResourceCollection"},
			"update-service-integration":                       {"ServiceIntegration"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("devopsguru", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
