package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/efs/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-access-point", "create-file-system", "create-mount-target", "create-replication-configuration", "create-tags", "delete-access-point", "delete-file-system", "delete-file-system-policy", "delete-mount-target", "delete-replication-configuration", "delete-tags", "describe-access-points", "describe-account-preferences", "describe-backup-policy", "describe-file-system-policy", "describe-file-systems", "describe-lifecycle-configuration", "describe-mount-target-security-groups", "describe-mount-targets", "describe-replication-configurations", "describe-tags", "list-tags-for-resource", "modify-mount-target-security-groups", "put-account-preferences", "put-backup-policy", "put-file-system-policy", "put-lifecycle-configuration", "tag-resource", "untag-resource", "update-file-system", "update-file-system-protection"},
		OperationSet: map[string]bool{"create-access-point": true, "create-file-system": true, "create-mount-target": true, "create-replication-configuration": true, "create-tags": true, "delete-access-point": true, "delete-file-system": true, "delete-file-system-policy": true, "delete-mount-target": true, "delete-replication-configuration": true, "delete-tags": true, "describe-access-points": true, "describe-account-preferences": true, "describe-backup-policy": true, "describe-file-system-policy": true, "describe-file-systems": true, "describe-lifecycle-configuration": true, "describe-mount-target-security-groups": true, "describe-mount-targets": true, "describe-replication-configurations": true, "describe-tags": true, "list-tags-for-resource": true, "modify-mount-target-security-groups": true, "put-account-preferences": true, "put-backup-policy": true, "put-file-system-policy": true, "put-lifecycle-configuration": true, "tag-resource": true, "untag-resource": true, "update-file-system": true, "update-file-system-protection": true},
		OperationInputs: map[string][]string{
			"create-access-point":                   {"ClientToken", "FileSystemId", "PosixUser", "RootDirectory", "Tags"},
			"create-file-system":                    {"AvailabilityZoneName", "Backup", "CreationToken", "Encrypted", "KmsKeyId", "PerformanceMode", "ProvisionedThroughputInMibps", "Tags", "ThroughputMode"},
			"create-mount-target":                   {"FileSystemId", "IpAddress", "IpAddressType", "Ipv6Address", "SecurityGroups", "SubnetId"},
			"create-replication-configuration":      {"Destinations", "SourceFileSystemId"},
			"create-tags":                           {"FileSystemId", "Tags"},
			"delete-access-point":                   {"AccessPointId"},
			"delete-file-system":                    {"FileSystemId"},
			"delete-file-system-policy":             {"FileSystemId"},
			"delete-mount-target":                   {"MountTargetId"},
			"delete-replication-configuration":      {"DeletionMode", "SourceFileSystemId"},
			"delete-tags":                           {"FileSystemId", "TagKeys"},
			"describe-access-points":                {"AccessPointId", "FileSystemId", "MaxResults", "NextToken"},
			"describe-account-preferences":          {"MaxResults", "NextToken"},
			"describe-backup-policy":                {"FileSystemId"},
			"describe-file-system-policy":           {"FileSystemId"},
			"describe-file-systems":                 {"CreationToken", "FileSystemId", "Marker", "MaxItems"},
			"describe-lifecycle-configuration":      {"FileSystemId"},
			"describe-mount-target-security-groups": {"MountTargetId"},
			"describe-mount-targets":                {"AccessPointId", "FileSystemId", "Marker", "MaxItems", "MountTargetId"},
			"describe-replication-configurations":   {"FileSystemId", "MaxResults", "NextToken"},
			"describe-tags":                         {"FileSystemId", "Marker", "MaxItems"},
			"list-tags-for-resource":                {"MaxResults", "NextToken", "ResourceId"},
			"modify-mount-target-security-groups":   {"MountTargetId", "SecurityGroups"},
			"put-account-preferences":               {"ResourceIdType"},
			"put-backup-policy":                     {"BackupPolicy", "FileSystemId"},
			"put-file-system-policy":                {"BypassPolicyLockoutSafetyCheck", "FileSystemId", "Policy"},
			"put-lifecycle-configuration":           {"FileSystemId", "LifecyclePolicies"},
			"tag-resource":                          {"ResourceId", "Tags"},
			"untag-resource":                        {"ResourceId", "TagKeys"},
			"update-file-system":                    {"FileSystemId", "ProvisionedThroughputInMibps", "ThroughputMode"},
			"update-file-system-protection":         {"FileSystemId", "ReplicationOverwriteProtection"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-access-point":                   {"ClientToken": "*string", "FileSystemId": "*string", "PosixUser": "*types.PosixUser", "RootDirectory": "*types.RootDirectory", "Tags": "[]types.Tag"},
			"create-file-system":                    {"AvailabilityZoneName": "*string", "Backup": "*bool", "CreationToken": "*string", "Encrypted": "*bool", "KmsKeyId": "*string", "PerformanceMode": "types.PerformanceMode", "ProvisionedThroughputInMibps": "*float64", "Tags": "[]types.Tag", "ThroughputMode": "types.ThroughputMode"},
			"create-mount-target":                   {"FileSystemId": "*string", "IpAddress": "*string", "IpAddressType": "types.IpAddressType", "Ipv6Address": "*string", "SecurityGroups": "[]string", "SubnetId": "*string"},
			"create-replication-configuration":      {"Destinations": "[]types.DestinationToCreate", "SourceFileSystemId": "*string"},
			"create-tags":                           {"FileSystemId": "*string", "Tags": "[]types.Tag"},
			"delete-access-point":                   {"AccessPointId": "*string"},
			"delete-file-system":                    {"FileSystemId": "*string"},
			"delete-file-system-policy":             {"FileSystemId": "*string"},
			"delete-mount-target":                   {"MountTargetId": "*string"},
			"delete-replication-configuration":      {"DeletionMode": "types.DeletionMode", "SourceFileSystemId": "*string"},
			"delete-tags":                           {"FileSystemId": "*string", "TagKeys": "[]string"},
			"describe-access-points":                {"AccessPointId": "*string", "FileSystemId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-account-preferences":          {"MaxResults": "*int32", "NextToken": "*string"},
			"describe-backup-policy":                {"FileSystemId": "*string"},
			"describe-file-system-policy":           {"FileSystemId": "*string"},
			"describe-file-systems":                 {"CreationToken": "*string", "FileSystemId": "*string", "Marker": "*string", "MaxItems": "*int32"},
			"describe-lifecycle-configuration":      {"FileSystemId": "*string"},
			"describe-mount-target-security-groups": {"MountTargetId": "*string"},
			"describe-mount-targets":                {"AccessPointId": "*string", "FileSystemId": "*string", "Marker": "*string", "MaxItems": "*int32", "MountTargetId": "*string"},
			"describe-replication-configurations":   {"FileSystemId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-tags":                         {"FileSystemId": "*string", "Marker": "*string", "MaxItems": "*int32"},
			"list-tags-for-resource":                {"MaxResults": "*int32", "NextToken": "*string", "ResourceId": "*string"},
			"modify-mount-target-security-groups":   {"MountTargetId": "*string", "SecurityGroups": "[]string"},
			"put-account-preferences":               {"ResourceIdType": "types.ResourceIdType"},
			"put-backup-policy":                     {"BackupPolicy": "*types.BackupPolicy", "FileSystemId": "*string"},
			"put-file-system-policy":                {"BypassPolicyLockoutSafetyCheck": "bool", "FileSystemId": "*string", "Policy": "*string"},
			"put-lifecycle-configuration":           {"FileSystemId": "*string", "LifecyclePolicies": "[]types.LifecyclePolicy"},
			"tag-resource":                          {"ResourceId": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                        {"ResourceId": "*string", "TagKeys": "[]string"},
			"update-file-system":                    {"FileSystemId": "*string", "ProvisionedThroughputInMibps": "*float64", "ThroughputMode": "types.ThroughputMode"},
			"update-file-system-protection":         {"FileSystemId": "*string", "ReplicationOverwriteProtection": "types.ReplicationOverwriteProtection"},
		},
		OperationInputRequired: map[string][]string{
			"create-access-point":                   {"ClientToken", "FileSystemId"},
			"create-file-system":                    {"CreationToken"},
			"create-mount-target":                   {"FileSystemId", "SubnetId"},
			"create-replication-configuration":      {"Destinations", "SourceFileSystemId"},
			"create-tags":                           {"FileSystemId", "Tags"},
			"delete-access-point":                   {"AccessPointId"},
			"delete-file-system":                    {"FileSystemId"},
			"delete-file-system-policy":             {"FileSystemId"},
			"delete-mount-target":                   {"MountTargetId"},
			"delete-replication-configuration":      {"SourceFileSystemId"},
			"delete-tags":                           {"FileSystemId", "TagKeys"},
			"describe-access-points":                {},
			"describe-account-preferences":          {},
			"describe-backup-policy":                {"FileSystemId"},
			"describe-file-system-policy":           {"FileSystemId"},
			"describe-file-systems":                 {},
			"describe-lifecycle-configuration":      {"FileSystemId"},
			"describe-mount-target-security-groups": {"MountTargetId"},
			"describe-mount-targets":                {},
			"describe-replication-configurations":   {},
			"describe-tags":                         {"FileSystemId"},
			"list-tags-for-resource":                {"ResourceId"},
			"modify-mount-target-security-groups":   {"MountTargetId"},
			"put-account-preferences":               {"ResourceIdType"},
			"put-backup-policy":                     {"BackupPolicy", "FileSystemId"},
			"put-file-system-policy":                {"FileSystemId", "Policy"},
			"put-lifecycle-configuration":           {"FileSystemId", "LifecyclePolicies"},
			"tag-resource":                          {"ResourceId", "Tags"},
			"untag-resource":                        {"ResourceId", "TagKeys"},
			"update-file-system":                    {"FileSystemId"},
			"update-file-system-protection":         {"FileSystemId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("efs", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
