package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/entityresolution/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-policy-statement", "batch-delete-unique-id", "create-id-mapping-workflow", "create-id-namespace", "create-matching-workflow", "create-schema-mapping", "delete-id-mapping-workflow", "delete-id-namespace", "delete-matching-workflow", "delete-policy-statement", "delete-schema-mapping", "generate-match-id", "get-id-mapping-job", "get-id-mapping-workflow", "get-id-namespace", "get-match-id", "get-matching-job", "get-matching-workflow", "get-policy", "get-provider-service", "get-schema-mapping", "list-id-mapping-jobs", "list-id-mapping-workflows", "list-id-namespaces", "list-matching-jobs", "list-matching-workflows", "list-provider-services", "list-schema-mappings", "list-tags-for-resource", "put-policy", "start-id-mapping-job", "start-matching-job", "tag-resource", "untag-resource", "update-id-mapping-workflow", "update-id-namespace", "update-matching-workflow", "update-schema-mapping"},
		OperationSet: map[string]bool{"add-policy-statement": true, "batch-delete-unique-id": true, "create-id-mapping-workflow": true, "create-id-namespace": true, "create-matching-workflow": true, "create-schema-mapping": true, "delete-id-mapping-workflow": true, "delete-id-namespace": true, "delete-matching-workflow": true, "delete-policy-statement": true, "delete-schema-mapping": true, "generate-match-id": true, "get-id-mapping-job": true, "get-id-mapping-workflow": true, "get-id-namespace": true, "get-match-id": true, "get-matching-job": true, "get-matching-workflow": true, "get-policy": true, "get-provider-service": true, "get-schema-mapping": true, "list-id-mapping-jobs": true, "list-id-mapping-workflows": true, "list-id-namespaces": true, "list-matching-jobs": true, "list-matching-workflows": true, "list-provider-services": true, "list-schema-mappings": true, "list-tags-for-resource": true, "put-policy": true, "start-id-mapping-job": true, "start-matching-job": true, "tag-resource": true, "untag-resource": true, "update-id-mapping-workflow": true, "update-id-namespace": true, "update-matching-workflow": true, "update-schema-mapping": true},
		OperationInputs: map[string][]string{
			"add-policy-statement":       {"Action", "Arn", "Condition", "Effect", "Principal", "StatementId"},
			"batch-delete-unique-id":     {"InputSource", "UniqueIds", "WorkflowName"},
			"create-id-mapping-workflow": {"Description", "IdMappingTechniques", "IncrementalRunConfig", "InputSourceConfig", "OutputSourceConfig", "RoleArn", "Tags", "WorkflowName"},
			"create-id-namespace":        {"Description", "IdMappingWorkflowProperties", "IdNamespaceName", "InputSourceConfig", "RoleArn", "Tags", "Type"},
			"create-matching-workflow":   {"Description", "IncrementalRunConfig", "InputSourceConfig", "OutputSourceConfig", "ResolutionTechniques", "RoleArn", "Tags", "WorkflowName"},
			"create-schema-mapping":      {"Description", "MappedInputFields", "SchemaName", "Tags"},
			"delete-id-mapping-workflow": {"WorkflowName"},
			"delete-id-namespace":        {"IdNamespaceName"},
			"delete-matching-workflow":   {"WorkflowName"},
			"delete-policy-statement":    {"Arn", "StatementId"},
			"delete-schema-mapping":      {"SchemaName"},
			"generate-match-id":          {"ProcessingType", "Records", "WorkflowName"},
			"get-id-mapping-job":         {"JobId", "WorkflowName"},
			"get-id-mapping-workflow":    {"WorkflowName"},
			"get-id-namespace":           {"IdNamespaceName"},
			"get-match-id":               {"ApplyNormalization", "Record", "WorkflowName"},
			"get-matching-job":           {"JobId", "WorkflowName"},
			"get-matching-workflow":      {"WorkflowName"},
			"get-policy":                 {"Arn"},
			"get-provider-service":       {"ProviderName", "ProviderServiceName"},
			"get-schema-mapping":         {"SchemaName"},
			"list-id-mapping-jobs":       {"MaxResults", "NextToken", "WorkflowName"},
			"list-id-mapping-workflows":  {"MaxResults", "NextToken"},
			"list-id-namespaces":         {"MaxResults", "NextToken"},
			"list-matching-jobs":         {"MaxResults", "NextToken", "WorkflowName"},
			"list-matching-workflows":    {"MaxResults", "NextToken"},
			"list-provider-services":     {"MaxResults", "NextToken", "ProviderName"},
			"list-schema-mappings":       {"MaxResults", "NextToken"},
			"list-tags-for-resource":     {"ResourceArn"},
			"put-policy":                 {"Arn", "Policy", "Token"},
			"start-id-mapping-job":       {"JobType", "OutputSourceConfig", "WorkflowName"},
			"start-matching-job":         {"WorkflowName"},
			"tag-resource":               {"ResourceArn", "Tags"},
			"untag-resource":             {"ResourceArn", "TagKeys"},
			"update-id-mapping-workflow": {"Description", "IdMappingTechniques", "IncrementalRunConfig", "InputSourceConfig", "OutputSourceConfig", "RoleArn", "WorkflowName"},
			"update-id-namespace":        {"Description", "IdMappingWorkflowProperties", "IdNamespaceName", "InputSourceConfig", "RoleArn"},
			"update-matching-workflow":   {"Description", "IncrementalRunConfig", "InputSourceConfig", "OutputSourceConfig", "ResolutionTechniques", "RoleArn", "WorkflowName"},
			"update-schema-mapping":      {"Description", "MappedInputFields", "SchemaName"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-policy-statement":       {"Action": "[]string", "Arn": "*string", "Condition": "*string", "Effect": "types.StatementEffect", "Principal": "[]string", "StatementId": "*string"},
			"batch-delete-unique-id":     {"InputSource": "*string", "UniqueIds": "[]string", "WorkflowName": "*string"},
			"create-id-mapping-workflow": {"Description": "*string", "IdMappingTechniques": "*types.IdMappingTechniques", "IncrementalRunConfig": "*types.IdMappingIncrementalRunConfig", "InputSourceConfig": "[]types.IdMappingWorkflowInputSource", "OutputSourceConfig": "[]types.IdMappingWorkflowOutputSource", "RoleArn": "*string", "Tags": "map[string]string", "WorkflowName": "*string"},
			"create-id-namespace":        {"Description": "*string", "IdMappingWorkflowProperties": "[]types.IdNamespaceIdMappingWorkflowProperties", "IdNamespaceName": "*string", "InputSourceConfig": "[]types.IdNamespaceInputSource", "RoleArn": "*string", "Tags": "map[string]string", "Type": "types.IdNamespaceType"},
			"create-matching-workflow":   {"Description": "*string", "IncrementalRunConfig": "*types.IncrementalRunConfig", "InputSourceConfig": "[]types.InputSource", "OutputSourceConfig": "[]types.OutputSource", "ResolutionTechniques": "*types.ResolutionTechniques", "RoleArn": "*string", "Tags": "map[string]string", "WorkflowName": "*string"},
			"create-schema-mapping":      {"Description": "*string", "MappedInputFields": "[]types.SchemaInputAttribute", "SchemaName": "*string", "Tags": "map[string]string"},
			"delete-id-mapping-workflow": {"WorkflowName": "*string"},
			"delete-id-namespace":        {"IdNamespaceName": "*string"},
			"delete-matching-workflow":   {"WorkflowName": "*string"},
			"delete-policy-statement":    {"Arn": "*string", "StatementId": "*string"},
			"delete-schema-mapping":      {"SchemaName": "*string"},
			"generate-match-id":          {"ProcessingType": "types.ProcessingType", "Records": "[]types.Record", "WorkflowName": "*string"},
			"get-id-mapping-job":         {"JobId": "*string", "WorkflowName": "*string"},
			"get-id-mapping-workflow":    {"WorkflowName": "*string"},
			"get-id-namespace":           {"IdNamespaceName": "*string"},
			"get-match-id":               {"ApplyNormalization": "*bool", "Record": "map[string]string", "WorkflowName": "*string"},
			"get-matching-job":           {"JobId": "*string", "WorkflowName": "*string"},
			"get-matching-workflow":      {"WorkflowName": "*string"},
			"get-policy":                 {"Arn": "*string"},
			"get-provider-service":       {"ProviderName": "*string", "ProviderServiceName": "*string"},
			"get-schema-mapping":         {"SchemaName": "*string"},
			"list-id-mapping-jobs":       {"MaxResults": "*int32", "NextToken": "*string", "WorkflowName": "*string"},
			"list-id-mapping-workflows":  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-id-namespaces":         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-matching-jobs":         {"MaxResults": "*int32", "NextToken": "*string", "WorkflowName": "*string"},
			"list-matching-workflows":    {"MaxResults": "*int32", "NextToken": "*string"},
			"list-provider-services":     {"MaxResults": "*int32", "NextToken": "*string", "ProviderName": "*string"},
			"list-schema-mappings":       {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":     {"ResourceArn": "*string"},
			"put-policy":                 {"Arn": "*string", "Policy": "*string", "Token": "*string"},
			"start-id-mapping-job":       {"JobType": "types.JobType", "OutputSourceConfig": "[]types.IdMappingJobOutputSource", "WorkflowName": "*string"},
			"start-matching-job":         {"WorkflowName": "*string"},
			"tag-resource":               {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":             {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-id-mapping-workflow": {"Description": "*string", "IdMappingTechniques": "*types.IdMappingTechniques", "IncrementalRunConfig": "*types.IdMappingIncrementalRunConfig", "InputSourceConfig": "[]types.IdMappingWorkflowInputSource", "OutputSourceConfig": "[]types.IdMappingWorkflowOutputSource", "RoleArn": "*string", "WorkflowName": "*string"},
			"update-id-namespace":        {"Description": "*string", "IdMappingWorkflowProperties": "[]types.IdNamespaceIdMappingWorkflowProperties", "IdNamespaceName": "*string", "InputSourceConfig": "[]types.IdNamespaceInputSource", "RoleArn": "*string"},
			"update-matching-workflow":   {"Description": "*string", "IncrementalRunConfig": "*types.IncrementalRunConfig", "InputSourceConfig": "[]types.InputSource", "OutputSourceConfig": "[]types.OutputSource", "ResolutionTechniques": "*types.ResolutionTechniques", "RoleArn": "*string", "WorkflowName": "*string"},
			"update-schema-mapping":      {"Description": "*string", "MappedInputFields": "[]types.SchemaInputAttribute", "SchemaName": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"add-policy-statement":       {"Action", "Arn", "Effect", "Principal", "StatementId"},
			"batch-delete-unique-id":     {"UniqueIds", "WorkflowName"},
			"create-id-mapping-workflow": {"IdMappingTechniques", "InputSourceConfig", "WorkflowName"},
			"create-id-namespace":        {"IdNamespaceName", "Type"},
			"create-matching-workflow":   {"InputSourceConfig", "OutputSourceConfig", "ResolutionTechniques", "RoleArn", "WorkflowName"},
			"create-schema-mapping":      {"MappedInputFields", "SchemaName"},
			"delete-id-mapping-workflow": {"WorkflowName"},
			"delete-id-namespace":        {"IdNamespaceName"},
			"delete-matching-workflow":   {"WorkflowName"},
			"delete-policy-statement":    {"Arn", "StatementId"},
			"delete-schema-mapping":      {"SchemaName"},
			"generate-match-id":          {"Records", "WorkflowName"},
			"get-id-mapping-job":         {"JobId", "WorkflowName"},
			"get-id-mapping-workflow":    {"WorkflowName"},
			"get-id-namespace":           {"IdNamespaceName"},
			"get-match-id":               {"Record", "WorkflowName"},
			"get-matching-job":           {"JobId", "WorkflowName"},
			"get-matching-workflow":      {"WorkflowName"},
			"get-policy":                 {"Arn"},
			"get-provider-service":       {"ProviderName", "ProviderServiceName"},
			"get-schema-mapping":         {"SchemaName"},
			"list-id-mapping-jobs":       {"WorkflowName"},
			"list-id-mapping-workflows":  {},
			"list-id-namespaces":         {},
			"list-matching-jobs":         {"WorkflowName"},
			"list-matching-workflows":    {},
			"list-provider-services":     {},
			"list-schema-mappings":       {},
			"list-tags-for-resource":     {"ResourceArn"},
			"put-policy":                 {"Arn", "Policy"},
			"start-id-mapping-job":       {"WorkflowName"},
			"start-matching-job":         {"WorkflowName"},
			"tag-resource":               {"ResourceArn", "Tags"},
			"untag-resource":             {"ResourceArn", "TagKeys"},
			"update-id-mapping-workflow": {"IdMappingTechniques", "InputSourceConfig", "WorkflowName"},
			"update-id-namespace":        {"IdNamespaceName"},
			"update-matching-workflow":   {"InputSourceConfig", "OutputSourceConfig", "ResolutionTechniques", "RoleArn", "WorkflowName"},
			"update-schema-mapping":      {"MappedInputFields", "SchemaName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("entityresolution", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
