package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/appconfig/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-application", "create-configuration-profile", "create-deployment-strategy", "create-environment", "create-extension", "create-extension-association", "create-hosted-configuration-version", "delete-application", "delete-configuration-profile", "delete-deployment-strategy", "delete-environment", "delete-extension", "delete-extension-association", "delete-hosted-configuration-version", "get-account-settings", "get-application", "get-configuration", "get-configuration-profile", "get-deployment", "get-deployment-strategy", "get-environment", "get-extension", "get-extension-association", "get-hosted-configuration-version", "list-applications", "list-configuration-profiles", "list-deployment-strategies", "list-deployments", "list-environments", "list-extension-associations", "list-extensions", "list-hosted-configuration-versions", "list-tags-for-resource", "start-deployment", "stop-deployment", "tag-resource", "untag-resource", "update-account-settings", "update-application", "update-configuration-profile", "update-deployment-strategy", "update-environment", "update-extension", "update-extension-association", "validate-configuration"},
		OperationSet: map[string]bool{"create-application": true, "create-configuration-profile": true, "create-deployment-strategy": true, "create-environment": true, "create-extension": true, "create-extension-association": true, "create-hosted-configuration-version": true, "delete-application": true, "delete-configuration-profile": true, "delete-deployment-strategy": true, "delete-environment": true, "delete-extension": true, "delete-extension-association": true, "delete-hosted-configuration-version": true, "get-account-settings": true, "get-application": true, "get-configuration": true, "get-configuration-profile": true, "get-deployment": true, "get-deployment-strategy": true, "get-environment": true, "get-extension": true, "get-extension-association": true, "get-hosted-configuration-version": true, "list-applications": true, "list-configuration-profiles": true, "list-deployment-strategies": true, "list-deployments": true, "list-environments": true, "list-extension-associations": true, "list-extensions": true, "list-hosted-configuration-versions": true, "list-tags-for-resource": true, "start-deployment": true, "stop-deployment": true, "tag-resource": true, "untag-resource": true, "update-account-settings": true, "update-application": true, "update-configuration-profile": true, "update-deployment-strategy": true, "update-environment": true, "update-extension": true, "update-extension-association": true, "validate-configuration": true},
		OperationInputs: map[string][]string{
			"create-application":                  {"Description", "Name", "Tags"},
			"create-configuration-profile":        {"ApplicationId", "Description", "KmsKeyIdentifier", "LocationUri", "Name", "RetrievalRoleArn", "Tags", "Type", "Validators"},
			"create-deployment-strategy":          {"DeploymentDurationInMinutes", "Description", "FinalBakeTimeInMinutes", "GrowthFactor", "GrowthType", "Name", "ReplicateTo", "Tags"},
			"create-environment":                  {"ApplicationId", "Description", "Monitors", "Name", "Tags"},
			"create-extension":                    {"Actions", "Description", "LatestVersionNumber", "Name", "Parameters", "Tags"},
			"create-extension-association":        {"ExtensionIdentifier", "ExtensionVersionNumber", "Parameters", "ResourceIdentifier", "Tags"},
			"create-hosted-configuration-version": {"ApplicationId", "ConfigurationProfileId", "Content", "ContentType", "Description", "LatestVersionNumber", "VersionLabel"},
			"delete-application":                  {"ApplicationId"},
			"delete-configuration-profile":        {"ApplicationId", "ConfigurationProfileId", "DeletionProtectionCheck"},
			"delete-deployment-strategy":          {"DeploymentStrategyId"},
			"delete-environment":                  {"ApplicationId", "DeletionProtectionCheck", "EnvironmentId"},
			"delete-extension":                    {"ExtensionIdentifier", "VersionNumber"},
			"delete-extension-association":        {"ExtensionAssociationId"},
			"delete-hosted-configuration-version": {"ApplicationId", "ConfigurationProfileId", "VersionNumber"},
			"get-account-settings":                {},
			"get-application":                     {"ApplicationId"},
			"get-configuration":                   {"Application", "ClientConfigurationVersion", "ClientId", "Configuration", "Environment"},
			"get-configuration-profile":           {"ApplicationId", "ConfigurationProfileId"},
			"get-deployment":                      {"ApplicationId", "DeploymentNumber", "EnvironmentId"},
			"get-deployment-strategy":             {"DeploymentStrategyId"},
			"get-environment":                     {"ApplicationId", "EnvironmentId"},
			"get-extension":                       {"ExtensionIdentifier", "VersionNumber"},
			"get-extension-association":           {"ExtensionAssociationId"},
			"get-hosted-configuration-version":    {"ApplicationId", "ConfigurationProfileId", "VersionNumber"},
			"list-applications":                   {"MaxResults", "NextToken"},
			"list-configuration-profiles":         {"ApplicationId", "MaxResults", "NextToken", "Type"},
			"list-deployment-strategies":          {"MaxResults", "NextToken"},
			"list-deployments":                    {"ApplicationId", "EnvironmentId", "MaxResults", "NextToken"},
			"list-environments":                   {"ApplicationId", "MaxResults", "NextToken"},
			"list-extension-associations":         {"ExtensionIdentifier", "ExtensionVersionNumber", "MaxResults", "NextToken", "ResourceIdentifier"},
			"list-extensions":                     {"MaxResults", "Name", "NextToken"},
			"list-hosted-configuration-versions":  {"ApplicationId", "ConfigurationProfileId", "MaxResults", "NextToken", "VersionLabel"},
			"list-tags-for-resource":              {"ResourceArn"},
			"start-deployment":                    {"ApplicationId", "ConfigurationProfileId", "ConfigurationVersion", "DeploymentStrategyId", "Description", "DynamicExtensionParameters", "EnvironmentId", "KmsKeyIdentifier", "Tags"},
			"stop-deployment":                     {"AllowRevert", "ApplicationId", "DeploymentNumber", "EnvironmentId"},
			"tag-resource":                        {"ResourceArn", "Tags"},
			"untag-resource":                      {"ResourceArn", "TagKeys"},
			"update-account-settings":             {"DeletionProtection"},
			"update-application":                  {"ApplicationId", "Description", "Name"},
			"update-configuration-profile":        {"ApplicationId", "ConfigurationProfileId", "Description", "KmsKeyIdentifier", "Name", "RetrievalRoleArn", "Validators"},
			"update-deployment-strategy":          {"DeploymentDurationInMinutes", "DeploymentStrategyId", "Description", "FinalBakeTimeInMinutes", "GrowthFactor", "GrowthType"},
			"update-environment":                  {"ApplicationId", "Description", "EnvironmentId", "Monitors", "Name"},
			"update-extension":                    {"Actions", "Description", "ExtensionIdentifier", "Parameters", "VersionNumber"},
			"update-extension-association":        {"ExtensionAssociationId", "Parameters"},
			"validate-configuration":              {"ApplicationId", "ConfigurationProfileId", "ConfigurationVersion"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-application":                  {"Description": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-configuration-profile":        {"ApplicationId": "*string", "Description": "*string", "KmsKeyIdentifier": "*string", "LocationUri": "*string", "Name": "*string", "RetrievalRoleArn": "*string", "Tags": "map[string]string", "Type": "*string", "Validators": "[]types.Validator"},
			"create-deployment-strategy":          {"DeploymentDurationInMinutes": "*int32", "Description": "*string", "FinalBakeTimeInMinutes": "int32", "GrowthFactor": "*float32", "GrowthType": "types.GrowthType", "Name": "*string", "ReplicateTo": "types.ReplicateTo", "Tags": "map[string]string"},
			"create-environment":                  {"ApplicationId": "*string", "Description": "*string", "Monitors": "[]types.Monitor", "Name": "*string", "Tags": "map[string]string"},
			"create-extension":                    {"Actions": "map[string][]types.Action", "Description": "*string", "LatestVersionNumber": "*int32", "Name": "*string", "Parameters": "map[string]types.Parameter", "Tags": "map[string]string"},
			"create-extension-association":        {"ExtensionIdentifier": "*string", "ExtensionVersionNumber": "*int32", "Parameters": "map[string]string", "ResourceIdentifier": "*string", "Tags": "map[string]string"},
			"create-hosted-configuration-version": {"ApplicationId": "*string", "ConfigurationProfileId": "*string", "Content": "[]byte", "ContentType": "*string", "Description": "*string", "LatestVersionNumber": "*int32", "VersionLabel": "*string"},
			"delete-application":                  {"ApplicationId": "*string"},
			"delete-configuration-profile":        {"ApplicationId": "*string", "ConfigurationProfileId": "*string", "DeletionProtectionCheck": "types.DeletionProtectionCheck"},
			"delete-deployment-strategy":          {"DeploymentStrategyId": "*string"},
			"delete-environment":                  {"ApplicationId": "*string", "DeletionProtectionCheck": "types.DeletionProtectionCheck", "EnvironmentId": "*string"},
			"delete-extension":                    {"ExtensionIdentifier": "*string", "VersionNumber": "*int32"},
			"delete-extension-association":        {"ExtensionAssociationId": "*string"},
			"delete-hosted-configuration-version": {"ApplicationId": "*string", "ConfigurationProfileId": "*string", "VersionNumber": "*int32"},
			"get-account-settings":                {},
			"get-application":                     {"ApplicationId": "*string"},
			"get-configuration":                   {"Application": "*string", "ClientConfigurationVersion": "*string", "ClientId": "*string", "Configuration": "*string", "Environment": "*string"},
			"get-configuration-profile":           {"ApplicationId": "*string", "ConfigurationProfileId": "*string"},
			"get-deployment":                      {"ApplicationId": "*string", "DeploymentNumber": "*int32", "EnvironmentId": "*string"},
			"get-deployment-strategy":             {"DeploymentStrategyId": "*string"},
			"get-environment":                     {"ApplicationId": "*string", "EnvironmentId": "*string"},
			"get-extension":                       {"ExtensionIdentifier": "*string", "VersionNumber": "*int32"},
			"get-extension-association":           {"ExtensionAssociationId": "*string"},
			"get-hosted-configuration-version":    {"ApplicationId": "*string", "ConfigurationProfileId": "*string", "VersionNumber": "*int32"},
			"list-applications":                   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-configuration-profiles":         {"ApplicationId": "*string", "MaxResults": "*int32", "NextToken": "*string", "Type": "*string"},
			"list-deployment-strategies":          {"MaxResults": "*int32", "NextToken": "*string"},
			"list-deployments":                    {"ApplicationId": "*string", "EnvironmentId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-environments":                   {"ApplicationId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-extension-associations":         {"ExtensionIdentifier": "*string", "ExtensionVersionNumber": "*int32", "MaxResults": "*int32", "NextToken": "*string", "ResourceIdentifier": "*string"},
			"list-extensions":                     {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string"},
			"list-hosted-configuration-versions":  {"ApplicationId": "*string", "ConfigurationProfileId": "*string", "MaxResults": "*int32", "NextToken": "*string", "VersionLabel": "*string"},
			"list-tags-for-resource":              {"ResourceArn": "*string"},
			"start-deployment":                    {"ApplicationId": "*string", "ConfigurationProfileId": "*string", "ConfigurationVersion": "*string", "DeploymentStrategyId": "*string", "Description": "*string", "DynamicExtensionParameters": "map[string]string", "EnvironmentId": "*string", "KmsKeyIdentifier": "*string", "Tags": "map[string]string"},
			"stop-deployment":                     {"AllowRevert": "*bool", "ApplicationId": "*string", "DeploymentNumber": "*int32", "EnvironmentId": "*string"},
			"tag-resource":                        {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                      {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-account-settings":             {"DeletionProtection": "*types.DeletionProtectionSettings"},
			"update-application":                  {"ApplicationId": "*string", "Description": "*string", "Name": "*string"},
			"update-configuration-profile":        {"ApplicationId": "*string", "ConfigurationProfileId": "*string", "Description": "*string", "KmsKeyIdentifier": "*string", "Name": "*string", "RetrievalRoleArn": "*string", "Validators": "[]types.Validator"},
			"update-deployment-strategy":          {"DeploymentDurationInMinutes": "*int32", "DeploymentStrategyId": "*string", "Description": "*string", "FinalBakeTimeInMinutes": "*int32", "GrowthFactor": "*float32", "GrowthType": "types.GrowthType"},
			"update-environment":                  {"ApplicationId": "*string", "Description": "*string", "EnvironmentId": "*string", "Monitors": "[]types.Monitor", "Name": "*string"},
			"update-extension":                    {"Actions": "map[string][]types.Action", "Description": "*string", "ExtensionIdentifier": "*string", "Parameters": "map[string]types.Parameter", "VersionNumber": "*int32"},
			"update-extension-association":        {"ExtensionAssociationId": "*string", "Parameters": "map[string]string"},
			"validate-configuration":              {"ApplicationId": "*string", "ConfigurationProfileId": "*string", "ConfigurationVersion": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-application":                  {"Name"},
			"create-configuration-profile":        {"ApplicationId", "LocationUri", "Name"},
			"create-deployment-strategy":          {"DeploymentDurationInMinutes", "GrowthFactor", "Name"},
			"create-environment":                  {"ApplicationId", "Name"},
			"create-extension":                    {"Actions", "Name"},
			"create-extension-association":        {"ExtensionIdentifier", "ResourceIdentifier"},
			"create-hosted-configuration-version": {"ApplicationId", "ConfigurationProfileId", "Content", "ContentType"},
			"delete-application":                  {"ApplicationId"},
			"delete-configuration-profile":        {"ApplicationId", "ConfigurationProfileId"},
			"delete-deployment-strategy":          {"DeploymentStrategyId"},
			"delete-environment":                  {"ApplicationId", "EnvironmentId"},
			"delete-extension":                    {"ExtensionIdentifier"},
			"delete-extension-association":        {"ExtensionAssociationId"},
			"delete-hosted-configuration-version": {"ApplicationId", "ConfigurationProfileId", "VersionNumber"},
			"get-account-settings":                {},
			"get-application":                     {"ApplicationId"},
			"get-configuration":                   {"Application", "ClientId", "Configuration", "Environment"},
			"get-configuration-profile":           {"ApplicationId", "ConfigurationProfileId"},
			"get-deployment":                      {"ApplicationId", "DeploymentNumber", "EnvironmentId"},
			"get-deployment-strategy":             {"DeploymentStrategyId"},
			"get-environment":                     {"ApplicationId", "EnvironmentId"},
			"get-extension":                       {"ExtensionIdentifier"},
			"get-extension-association":           {"ExtensionAssociationId"},
			"get-hosted-configuration-version":    {"ApplicationId", "ConfigurationProfileId", "VersionNumber"},
			"list-applications":                   {},
			"list-configuration-profiles":         {"ApplicationId"},
			"list-deployment-strategies":          {},
			"list-deployments":                    {"ApplicationId", "EnvironmentId"},
			"list-environments":                   {"ApplicationId"},
			"list-extension-associations":         {},
			"list-extensions":                     {},
			"list-hosted-configuration-versions":  {"ApplicationId", "ConfigurationProfileId"},
			"list-tags-for-resource":              {"ResourceArn"},
			"start-deployment":                    {"ApplicationId", "ConfigurationProfileId", "ConfigurationVersion", "DeploymentStrategyId", "EnvironmentId"},
			"stop-deployment":                     {"ApplicationId", "DeploymentNumber", "EnvironmentId"},
			"tag-resource":                        {"ResourceArn", "Tags"},
			"untag-resource":                      {"ResourceArn", "TagKeys"},
			"update-account-settings":             {},
			"update-application":                  {"ApplicationId"},
			"update-configuration-profile":        {"ApplicationId", "ConfigurationProfileId"},
			"update-deployment-strategy":          {"DeploymentStrategyId"},
			"update-environment":                  {"ApplicationId", "EnvironmentId"},
			"update-extension":                    {"ExtensionIdentifier"},
			"update-extension-association":        {"ExtensionAssociationId"},
			"validate-configuration":              {"ApplicationId", "ConfigurationProfileId", "ConfigurationVersion"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("appconfig", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
