package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/kinesis/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-tags-to-stream", "create-stream", "decrease-stream-retention-period", "delete-resource-policy", "delete-stream", "deregister-stream-consumer", "describe-account-settings", "describe-limits", "describe-stream", "describe-stream-consumer", "describe-stream-summary", "disable-enhanced-monitoring", "enable-enhanced-monitoring", "get-records", "get-resource-policy", "get-shard-iterator", "increase-stream-retention-period", "list-shards", "list-stream-consumers", "list-streams", "list-tags-for-resource", "list-tags-for-stream", "merge-shards", "put-record", "put-records", "put-resource-policy", "register-stream-consumer", "remove-tags-from-stream", "split-shard", "start-stream-encryption", "stop-stream-encryption", "subscribe-to-shard", "tag-resource", "untag-resource", "update-account-settings", "update-max-record-size", "update-shard-count", "update-stream-mode", "update-stream-warm-throughput"},
		OperationSet: map[string]bool{"add-tags-to-stream": true, "create-stream": true, "decrease-stream-retention-period": true, "delete-resource-policy": true, "delete-stream": true, "deregister-stream-consumer": true, "describe-account-settings": true, "describe-limits": true, "describe-stream": true, "describe-stream-consumer": true, "describe-stream-summary": true, "disable-enhanced-monitoring": true, "enable-enhanced-monitoring": true, "get-records": true, "get-resource-policy": true, "get-shard-iterator": true, "increase-stream-retention-period": true, "list-shards": true, "list-stream-consumers": true, "list-streams": true, "list-tags-for-resource": true, "list-tags-for-stream": true, "merge-shards": true, "put-record": true, "put-records": true, "put-resource-policy": true, "register-stream-consumer": true, "remove-tags-from-stream": true, "split-shard": true, "start-stream-encryption": true, "stop-stream-encryption": true, "subscribe-to-shard": true, "tag-resource": true, "untag-resource": true, "update-account-settings": true, "update-max-record-size": true, "update-shard-count": true, "update-stream-mode": true, "update-stream-warm-throughput": true},
		OperationInputs: map[string][]string{
			"add-tags-to-stream":               {"StreamARN", "StreamId", "StreamName", "Tags"},
			"create-stream":                    {"MaxRecordSizeInKiB", "ShardCount", "StreamModeDetails", "StreamName", "Tags", "WarmThroughputMiBps"},
			"decrease-stream-retention-period": {"RetentionPeriodHours", "StreamARN", "StreamId", "StreamName"},
			"delete-resource-policy":           {"ResourceARN", "StreamId"},
			"delete-stream":                    {"EnforceConsumerDeletion", "StreamARN", "StreamId", "StreamName"},
			"deregister-stream-consumer":       {"ConsumerARN", "ConsumerName", "StreamARN", "StreamId"},
			"describe-account-settings":        {},
			"describe-limits":                  {},
			"describe-stream":                  {"ExclusiveStartShardId", "Limit", "StreamARN", "StreamId", "StreamName"},
			"describe-stream-consumer":         {"ConsumerARN", "ConsumerName", "StreamARN", "StreamId"},
			"describe-stream-summary":          {"StreamARN", "StreamId", "StreamName"},
			"disable-enhanced-monitoring":      {"ShardLevelMetrics", "StreamARN", "StreamId", "StreamName"},
			"enable-enhanced-monitoring":       {"ShardLevelMetrics", "StreamARN", "StreamId", "StreamName"},
			"get-records":                      {"Limit", "ShardIterator", "StreamARN", "StreamId"},
			"get-resource-policy":              {"ResourceARN", "StreamId"},
			"get-shard-iterator":               {"ShardId", "ShardIteratorType", "StartingSequenceNumber", "StreamARN", "StreamId", "StreamName", "Timestamp"},
			"increase-stream-retention-period": {"RetentionPeriodHours", "StreamARN", "StreamId", "StreamName"},
			"list-shards":                      {"ExclusiveStartShardId", "MaxResults", "NextToken", "ShardFilter", "StreamARN", "StreamCreationTimestamp", "StreamId", "StreamName"},
			"list-stream-consumers":            {"MaxResults", "NextToken", "StreamARN", "StreamCreationTimestamp", "StreamId"},
			"list-streams":                     {"ExclusiveStartStreamName", "Limit", "NextToken"},
			"list-tags-for-resource":           {"ResourceARN", "StreamId"},
			"list-tags-for-stream":             {"ExclusiveStartTagKey", "Limit", "StreamARN", "StreamId", "StreamName"},
			"merge-shards":                     {"AdjacentShardToMerge", "ShardToMerge", "StreamARN", "StreamId", "StreamName"},
			"put-record":                       {"Data", "ExplicitHashKey", "PartitionKey", "SequenceNumberForOrdering", "StreamARN", "StreamId", "StreamName"},
			"put-records":                      {"Records", "StreamARN", "StreamId", "StreamName"},
			"put-resource-policy":              {"Policy", "ResourceARN", "StreamId"},
			"register-stream-consumer":         {"ConsumerName", "StreamARN", "StreamId", "Tags"},
			"remove-tags-from-stream":          {"StreamARN", "StreamId", "StreamName", "TagKeys"},
			"split-shard":                      {"NewStartingHashKey", "ShardToSplit", "StreamARN", "StreamId", "StreamName"},
			"start-stream-encryption":          {"EncryptionType", "KeyId", "StreamARN", "StreamId", "StreamName"},
			"stop-stream-encryption":           {"EncryptionType", "KeyId", "StreamARN", "StreamId", "StreamName"},
			"subscribe-to-shard":               {"ConsumerARN", "ShardId", "StartingPosition", "StreamId"},
			"tag-resource":                     {"ResourceARN", "StreamId", "Tags"},
			"untag-resource":                   {"ResourceARN", "StreamId", "TagKeys"},
			"update-account-settings":          {"MinimumThroughputBillingCommitment"},
			"update-max-record-size":           {"MaxRecordSizeInKiB", "StreamARN", "StreamId"},
			"update-shard-count":               {"ScalingType", "StreamARN", "StreamId", "StreamName", "TargetShardCount"},
			"update-stream-mode":               {"StreamARN", "StreamId", "StreamModeDetails", "WarmThroughputMiBps"},
			"update-stream-warm-throughput":    {"StreamARN", "StreamId", "StreamName", "WarmThroughputMiBps"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-tags-to-stream":               {"StreamARN": "*string", "StreamId": "*string", "StreamName": "*string", "Tags": "map[string]string"},
			"create-stream":                    {"MaxRecordSizeInKiB": "*int32", "ShardCount": "*int32", "StreamModeDetails": "*types.StreamModeDetails", "StreamName": "*string", "Tags": "map[string]string", "WarmThroughputMiBps": "*int32"},
			"decrease-stream-retention-period": {"RetentionPeriodHours": "*int32", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"delete-resource-policy":           {"ResourceARN": "*string", "StreamId": "*string"},
			"delete-stream":                    {"EnforceConsumerDeletion": "*bool", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"deregister-stream-consumer":       {"ConsumerARN": "*string", "ConsumerName": "*string", "StreamARN": "*string", "StreamId": "*string"},
			"describe-account-settings":        {},
			"describe-limits":                  {},
			"describe-stream":                  {"ExclusiveStartShardId": "*string", "Limit": "*int32", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"describe-stream-consumer":         {"ConsumerARN": "*string", "ConsumerName": "*string", "StreamARN": "*string", "StreamId": "*string"},
			"describe-stream-summary":          {"StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"disable-enhanced-monitoring":      {"ShardLevelMetrics": "[]types.MetricsName", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"enable-enhanced-monitoring":       {"ShardLevelMetrics": "[]types.MetricsName", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"get-records":                      {"Limit": "*int32", "ShardIterator": "*string", "StreamARN": "*string", "StreamId": "*string"},
			"get-resource-policy":              {"ResourceARN": "*string", "StreamId": "*string"},
			"get-shard-iterator":               {"ShardId": "*string", "ShardIteratorType": "types.ShardIteratorType", "StartingSequenceNumber": "*string", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string", "Timestamp": "*time.Time"},
			"increase-stream-retention-period": {"RetentionPeriodHours": "*int32", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"list-shards":                      {"ExclusiveStartShardId": "*string", "MaxResults": "*int32", "NextToken": "*string", "ShardFilter": "*types.ShardFilter", "StreamARN": "*string", "StreamCreationTimestamp": "*time.Time", "StreamId": "*string", "StreamName": "*string"},
			"list-stream-consumers":            {"MaxResults": "*int32", "NextToken": "*string", "StreamARN": "*string", "StreamCreationTimestamp": "*time.Time", "StreamId": "*string"},
			"list-streams":                     {"ExclusiveStartStreamName": "*string", "Limit": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":           {"ResourceARN": "*string", "StreamId": "*string"},
			"list-tags-for-stream":             {"ExclusiveStartTagKey": "*string", "Limit": "*int32", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"merge-shards":                     {"AdjacentShardToMerge": "*string", "ShardToMerge": "*string", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"put-record":                       {"Data": "[]byte", "ExplicitHashKey": "*string", "PartitionKey": "*string", "SequenceNumberForOrdering": "*string", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"put-records":                      {"Records": "[]types.PutRecordsRequestEntry", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"put-resource-policy":              {"Policy": "*string", "ResourceARN": "*string", "StreamId": "*string"},
			"register-stream-consumer":         {"ConsumerName": "*string", "StreamARN": "*string", "StreamId": "*string", "Tags": "map[string]string"},
			"remove-tags-from-stream":          {"StreamARN": "*string", "StreamId": "*string", "StreamName": "*string", "TagKeys": "[]string"},
			"split-shard":                      {"NewStartingHashKey": "*string", "ShardToSplit": "*string", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"start-stream-encryption":          {"EncryptionType": "types.EncryptionType", "KeyId": "*string", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"stop-stream-encryption":           {"EncryptionType": "types.EncryptionType", "KeyId": "*string", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string"},
			"subscribe-to-shard":               {"ConsumerARN": "*string", "ShardId": "*string", "StartingPosition": "*types.StartingPosition", "StreamId": "*string"},
			"tag-resource":                     {"ResourceARN": "*string", "StreamId": "*string", "Tags": "map[string]string"},
			"untag-resource":                   {"ResourceARN": "*string", "StreamId": "*string", "TagKeys": "[]string"},
			"update-account-settings":          {"MinimumThroughputBillingCommitment": "*types.MinimumThroughputBillingCommitmentInput"},
			"update-max-record-size":           {"MaxRecordSizeInKiB": "*int32", "StreamARN": "*string", "StreamId": "*string"},
			"update-shard-count":               {"ScalingType": "types.ScalingType", "StreamARN": "*string", "StreamId": "*string", "StreamName": "*string", "TargetShardCount": "*int32"},
			"update-stream-mode":               {"StreamARN": "*string", "StreamId": "*string", "StreamModeDetails": "*types.StreamModeDetails", "WarmThroughputMiBps": "*int32"},
			"update-stream-warm-throughput":    {"StreamARN": "*string", "StreamId": "*string", "StreamName": "*string", "WarmThroughputMiBps": "*int32"},
		},
		OperationInputRequired: map[string][]string{
			"add-tags-to-stream":               {"Tags"},
			"create-stream":                    {"StreamName"},
			"decrease-stream-retention-period": {"RetentionPeriodHours"},
			"delete-resource-policy":           {"ResourceARN"},
			"delete-stream":                    {},
			"deregister-stream-consumer":       {},
			"describe-account-settings":        {},
			"describe-limits":                  {},
			"describe-stream":                  {},
			"describe-stream-consumer":         {},
			"describe-stream-summary":          {},
			"disable-enhanced-monitoring":      {"ShardLevelMetrics"},
			"enable-enhanced-monitoring":       {"ShardLevelMetrics"},
			"get-records":                      {"ShardIterator"},
			"get-resource-policy":              {"ResourceARN"},
			"get-shard-iterator":               {"ShardId", "ShardIteratorType"},
			"increase-stream-retention-period": {"RetentionPeriodHours"},
			"list-shards":                      {},
			"list-stream-consumers":            {"StreamARN"},
			"list-streams":                     {},
			"list-tags-for-resource":           {"ResourceARN"},
			"list-tags-for-stream":             {},
			"merge-shards":                     {"AdjacentShardToMerge", "ShardToMerge"},
			"put-record":                       {"Data", "PartitionKey"},
			"put-records":                      {"Records"},
			"put-resource-policy":              {"Policy", "ResourceARN"},
			"register-stream-consumer":         {"ConsumerName", "StreamARN"},
			"remove-tags-from-stream":          {"TagKeys"},
			"split-shard":                      {"NewStartingHashKey", "ShardToSplit"},
			"start-stream-encryption":          {"EncryptionType", "KeyId"},
			"stop-stream-encryption":           {"EncryptionType", "KeyId"},
			"subscribe-to-shard":               {"ConsumerARN", "ShardId", "StartingPosition"},
			"tag-resource":                     {"ResourceARN", "Tags"},
			"untag-resource":                   {"ResourceARN", "TagKeys"},
			"update-account-settings":          {"MinimumThroughputBillingCommitment"},
			"update-max-record-size":           {"MaxRecordSizeInKiB"},
			"update-shard-count":               {"ScalingType", "TargetShardCount"},
			"update-stream-mode":               {"StreamARN", "StreamModeDetails"},
			"update-stream-warm-throughput":    {"WarmThroughputMiBps"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("kinesis", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
