package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/lookoutequipment/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-dataset", "create-inference-scheduler", "create-label", "create-label-group", "create-model", "create-retraining-scheduler", "delete-dataset", "delete-inference-scheduler", "delete-label", "delete-label-group", "delete-model", "delete-resource-policy", "delete-retraining-scheduler", "describe-data-ingestion-job", "describe-dataset", "describe-inference-scheduler", "describe-label", "describe-label-group", "describe-model", "describe-model-version", "describe-resource-policy", "describe-retraining-scheduler", "import-dataset", "import-model-version", "list-data-ingestion-jobs", "list-datasets", "list-inference-events", "list-inference-executions", "list-inference-schedulers", "list-label-groups", "list-labels", "list-model-versions", "list-models", "list-retraining-schedulers", "list-sensor-statistics", "list-tags-for-resource", "put-resource-policy", "start-data-ingestion-job", "start-inference-scheduler", "start-retraining-scheduler", "stop-inference-scheduler", "stop-retraining-scheduler", "tag-resource", "untag-resource", "update-active-model-version", "update-inference-scheduler", "update-label-group", "update-model", "update-retraining-scheduler"},
		OperationSet: map[string]bool{"create-dataset": true, "create-inference-scheduler": true, "create-label": true, "create-label-group": true, "create-model": true, "create-retraining-scheduler": true, "delete-dataset": true, "delete-inference-scheduler": true, "delete-label": true, "delete-label-group": true, "delete-model": true, "delete-resource-policy": true, "delete-retraining-scheduler": true, "describe-data-ingestion-job": true, "describe-dataset": true, "describe-inference-scheduler": true, "describe-label": true, "describe-label-group": true, "describe-model": true, "describe-model-version": true, "describe-resource-policy": true, "describe-retraining-scheduler": true, "import-dataset": true, "import-model-version": true, "list-data-ingestion-jobs": true, "list-datasets": true, "list-inference-events": true, "list-inference-executions": true, "list-inference-schedulers": true, "list-label-groups": true, "list-labels": true, "list-model-versions": true, "list-models": true, "list-retraining-schedulers": true, "list-sensor-statistics": true, "list-tags-for-resource": true, "put-resource-policy": true, "start-data-ingestion-job": true, "start-inference-scheduler": true, "start-retraining-scheduler": true, "stop-inference-scheduler": true, "stop-retraining-scheduler": true, "tag-resource": true, "untag-resource": true, "update-active-model-version": true, "update-inference-scheduler": true, "update-label-group": true, "update-model": true, "update-retraining-scheduler": true},
		OperationInputs: map[string][]string{
			"create-dataset":                {"ClientToken", "DatasetName", "DatasetSchema", "ServerSideKmsKeyId", "Tags"},
			"create-inference-scheduler":    {"ClientToken", "DataDelayOffsetInMinutes", "DataInputConfiguration", "DataOutputConfiguration", "DataUploadFrequency", "InferenceSchedulerName", "ModelName", "RoleArn", "ServerSideKmsKeyId", "Tags"},
			"create-label":                  {"ClientToken", "EndTime", "Equipment", "FaultCode", "LabelGroupName", "Notes", "Rating", "StartTime"},
			"create-label-group":            {"ClientToken", "FaultCodes", "LabelGroupName", "Tags"},
			"create-model":                  {"ClientToken", "DataPreProcessingConfiguration", "DatasetName", "DatasetSchema", "EvaluationDataEndTime", "EvaluationDataStartTime", "LabelsInputConfiguration", "ModelDiagnosticsOutputConfiguration", "ModelName", "OffCondition", "RoleArn", "ServerSideKmsKeyId", "Tags", "TrainingDataEndTime", "TrainingDataStartTime"},
			"create-retraining-scheduler":   {"ClientToken", "LookbackWindow", "ModelName", "PromoteMode", "RetrainingFrequency", "RetrainingStartDate"},
			"delete-dataset":                {"DatasetName"},
			"delete-inference-scheduler":    {"InferenceSchedulerName"},
			"delete-label":                  {"LabelGroupName", "LabelId"},
			"delete-label-group":            {"LabelGroupName"},
			"delete-model":                  {"ModelName"},
			"delete-resource-policy":        {"ResourceArn"},
			"delete-retraining-scheduler":   {"ModelName"},
			"describe-data-ingestion-job":   {"JobId"},
			"describe-dataset":              {"DatasetName"},
			"describe-inference-scheduler":  {"InferenceSchedulerName"},
			"describe-label":                {"LabelGroupName", "LabelId"},
			"describe-label-group":          {"LabelGroupName"},
			"describe-model":                {"ModelName"},
			"describe-model-version":        {"ModelName", "ModelVersion"},
			"describe-resource-policy":      {"ResourceArn"},
			"describe-retraining-scheduler": {"ModelName"},
			"import-dataset":                {"ClientToken", "DatasetName", "ServerSideKmsKeyId", "SourceDatasetArn", "Tags"},
			"import-model-version":          {"ClientToken", "DatasetName", "InferenceDataImportStrategy", "LabelsInputConfiguration", "ModelName", "RoleArn", "ServerSideKmsKeyId", "SourceModelVersionArn", "Tags"},
			"list-data-ingestion-jobs":      {"DatasetName", "MaxResults", "NextToken", "Status"},
			"list-datasets":                 {"DatasetNameBeginsWith", "MaxResults", "NextToken"},
			"list-inference-events":         {"InferenceSchedulerName", "IntervalEndTime", "IntervalStartTime", "MaxResults", "NextToken"},
			"list-inference-executions":     {"DataEndTimeBefore", "DataStartTimeAfter", "InferenceSchedulerName", "MaxResults", "NextToken", "Status"},
			"list-inference-schedulers":     {"InferenceSchedulerNameBeginsWith", "MaxResults", "ModelName", "NextToken", "Status"},
			"list-label-groups":             {"LabelGroupNameBeginsWith", "MaxResults", "NextToken"},
			"list-labels":                   {"Equipment", "FaultCode", "IntervalEndTime", "IntervalStartTime", "LabelGroupName", "MaxResults", "NextToken"},
			"list-model-versions":           {"CreatedAtEndTime", "CreatedAtStartTime", "MaxModelVersion", "MaxResults", "MinModelVersion", "ModelName", "NextToken", "SourceType", "Status"},
			"list-models":                   {"DatasetNameBeginsWith", "MaxResults", "ModelNameBeginsWith", "NextToken", "Status"},
			"list-retraining-schedulers":    {"MaxResults", "ModelNameBeginsWith", "NextToken", "Status"},
			"list-sensor-statistics":        {"DatasetName", "IngestionJobId", "MaxResults", "NextToken"},
			"list-tags-for-resource":        {"ResourceArn"},
			"put-resource-policy":           {"ClientToken", "PolicyRevisionId", "ResourceArn", "ResourcePolicy"},
			"start-data-ingestion-job":      {"ClientToken", "DatasetName", "IngestionInputConfiguration", "RoleArn"},
			"start-inference-scheduler":     {"InferenceSchedulerName"},
			"start-retraining-scheduler":    {"ModelName"},
			"stop-inference-scheduler":      {"InferenceSchedulerName"},
			"stop-retraining-scheduler":     {"ModelName"},
			"tag-resource":                  {"ResourceArn", "Tags"},
			"untag-resource":                {"ResourceArn", "TagKeys"},
			"update-active-model-version":   {"ModelName", "ModelVersion"},
			"update-inference-scheduler":    {"DataDelayOffsetInMinutes", "DataInputConfiguration", "DataOutputConfiguration", "DataUploadFrequency", "InferenceSchedulerName", "RoleArn"},
			"update-label-group":            {"FaultCodes", "LabelGroupName"},
			"update-model":                  {"LabelsInputConfiguration", "ModelDiagnosticsOutputConfiguration", "ModelName", "RoleArn"},
			"update-retraining-scheduler":   {"LookbackWindow", "ModelName", "PromoteMode", "RetrainingFrequency", "RetrainingStartDate"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-dataset":                {"ClientToken": "*string", "DatasetName": "*string", "DatasetSchema": "*types.DatasetSchema", "ServerSideKmsKeyId": "*string", "Tags": "[]types.Tag"},
			"create-inference-scheduler":    {"ClientToken": "*string", "DataDelayOffsetInMinutes": "*int64", "DataInputConfiguration": "*types.InferenceInputConfiguration", "DataOutputConfiguration": "*types.InferenceOutputConfiguration", "DataUploadFrequency": "types.DataUploadFrequency", "InferenceSchedulerName": "*string", "ModelName": "*string", "RoleArn": "*string", "ServerSideKmsKeyId": "*string", "Tags": "[]types.Tag"},
			"create-label":                  {"ClientToken": "*string", "EndTime": "*time.Time", "Equipment": "*string", "FaultCode": "*string", "LabelGroupName": "*string", "Notes": "*string", "Rating": "types.LabelRating", "StartTime": "*time.Time"},
			"create-label-group":            {"ClientToken": "*string", "FaultCodes": "[]string", "LabelGroupName": "*string", "Tags": "[]types.Tag"},
			"create-model":                  {"ClientToken": "*string", "DataPreProcessingConfiguration": "*types.DataPreProcessingConfiguration", "DatasetName": "*string", "DatasetSchema": "*types.DatasetSchema", "EvaluationDataEndTime": "*time.Time", "EvaluationDataStartTime": "*time.Time", "LabelsInputConfiguration": "*types.LabelsInputConfiguration", "ModelDiagnosticsOutputConfiguration": "*types.ModelDiagnosticsOutputConfiguration", "ModelName": "*string", "OffCondition": "*string", "RoleArn": "*string", "ServerSideKmsKeyId": "*string", "Tags": "[]types.Tag", "TrainingDataEndTime": "*time.Time", "TrainingDataStartTime": "*time.Time"},
			"create-retraining-scheduler":   {"ClientToken": "*string", "LookbackWindow": "*string", "ModelName": "*string", "PromoteMode": "types.ModelPromoteMode", "RetrainingFrequency": "*string", "RetrainingStartDate": "*time.Time"},
			"delete-dataset":                {"DatasetName": "*string"},
			"delete-inference-scheduler":    {"InferenceSchedulerName": "*string"},
			"delete-label":                  {"LabelGroupName": "*string", "LabelId": "*string"},
			"delete-label-group":            {"LabelGroupName": "*string"},
			"delete-model":                  {"ModelName": "*string"},
			"delete-resource-policy":        {"ResourceArn": "*string"},
			"delete-retraining-scheduler":   {"ModelName": "*string"},
			"describe-data-ingestion-job":   {"JobId": "*string"},
			"describe-dataset":              {"DatasetName": "*string"},
			"describe-inference-scheduler":  {"InferenceSchedulerName": "*string"},
			"describe-label":                {"LabelGroupName": "*string", "LabelId": "*string"},
			"describe-label-group":          {"LabelGroupName": "*string"},
			"describe-model":                {"ModelName": "*string"},
			"describe-model-version":        {"ModelName": "*string", "ModelVersion": "*int64"},
			"describe-resource-policy":      {"ResourceArn": "*string"},
			"describe-retraining-scheduler": {"ModelName": "*string"},
			"import-dataset":                {"ClientToken": "*string", "DatasetName": "*string", "ServerSideKmsKeyId": "*string", "SourceDatasetArn": "*string", "Tags": "[]types.Tag"},
			"import-model-version":          {"ClientToken": "*string", "DatasetName": "*string", "InferenceDataImportStrategy": "types.InferenceDataImportStrategy", "LabelsInputConfiguration": "*types.LabelsInputConfiguration", "ModelName": "*string", "RoleArn": "*string", "ServerSideKmsKeyId": "*string", "SourceModelVersionArn": "*string", "Tags": "[]types.Tag"},
			"list-data-ingestion-jobs":      {"DatasetName": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.IngestionJobStatus"},
			"list-datasets":                 {"DatasetNameBeginsWith": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-inference-events":         {"InferenceSchedulerName": "*string", "IntervalEndTime": "*time.Time", "IntervalStartTime": "*time.Time", "MaxResults": "*int32", "NextToken": "*string"},
			"list-inference-executions":     {"DataEndTimeBefore": "*time.Time", "DataStartTimeAfter": "*time.Time", "InferenceSchedulerName": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.InferenceExecutionStatus"},
			"list-inference-schedulers":     {"InferenceSchedulerNameBeginsWith": "*string", "MaxResults": "*int32", "ModelName": "*string", "NextToken": "*string", "Status": "types.InferenceSchedulerStatus"},
			"list-label-groups":             {"LabelGroupNameBeginsWith": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-labels":                   {"Equipment": "*string", "FaultCode": "*string", "IntervalEndTime": "*time.Time", "IntervalStartTime": "*time.Time", "LabelGroupName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-model-versions":           {"CreatedAtEndTime": "*time.Time", "CreatedAtStartTime": "*time.Time", "MaxModelVersion": "*int64", "MaxResults": "*int32", "MinModelVersion": "*int64", "ModelName": "*string", "NextToken": "*string", "SourceType": "types.ModelVersionSourceType", "Status": "types.ModelVersionStatus"},
			"list-models":                   {"DatasetNameBeginsWith": "*string", "MaxResults": "*int32", "ModelNameBeginsWith": "*string", "NextToken": "*string", "Status": "types.ModelStatus"},
			"list-retraining-schedulers":    {"MaxResults": "*int32", "ModelNameBeginsWith": "*string", "NextToken": "*string", "Status": "types.RetrainingSchedulerStatus"},
			"list-sensor-statistics":        {"DatasetName": "*string", "IngestionJobId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":        {"ResourceArn": "*string"},
			"put-resource-policy":           {"ClientToken": "*string", "PolicyRevisionId": "*string", "ResourceArn": "*string", "ResourcePolicy": "*string"},
			"start-data-ingestion-job":      {"ClientToken": "*string", "DatasetName": "*string", "IngestionInputConfiguration": "*types.IngestionInputConfiguration", "RoleArn": "*string"},
			"start-inference-scheduler":     {"InferenceSchedulerName": "*string"},
			"start-retraining-scheduler":    {"ModelName": "*string"},
			"stop-inference-scheduler":      {"InferenceSchedulerName": "*string"},
			"stop-retraining-scheduler":     {"ModelName": "*string"},
			"tag-resource":                  {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-active-model-version":   {"ModelName": "*string", "ModelVersion": "*int64"},
			"update-inference-scheduler":    {"DataDelayOffsetInMinutes": "*int64", "DataInputConfiguration": "*types.InferenceInputConfiguration", "DataOutputConfiguration": "*types.InferenceOutputConfiguration", "DataUploadFrequency": "types.DataUploadFrequency", "InferenceSchedulerName": "*string", "RoleArn": "*string"},
			"update-label-group":            {"FaultCodes": "[]string", "LabelGroupName": "*string"},
			"update-model":                  {"LabelsInputConfiguration": "*types.LabelsInputConfiguration", "ModelDiagnosticsOutputConfiguration": "*types.ModelDiagnosticsOutputConfiguration", "ModelName": "*string", "RoleArn": "*string"},
			"update-retraining-scheduler":   {"LookbackWindow": "*string", "ModelName": "*string", "PromoteMode": "types.ModelPromoteMode", "RetrainingFrequency": "*string", "RetrainingStartDate": "*time.Time"},
		},
		OperationInputRequired: map[string][]string{
			"create-dataset":                {"ClientToken", "DatasetName"},
			"create-inference-scheduler":    {"ClientToken", "DataInputConfiguration", "DataOutputConfiguration", "DataUploadFrequency", "InferenceSchedulerName", "ModelName", "RoleArn"},
			"create-label":                  {"ClientToken", "EndTime", "LabelGroupName", "Rating", "StartTime"},
			"create-label-group":            {"ClientToken", "LabelGroupName"},
			"create-model":                  {"ClientToken", "DatasetName", "ModelName"},
			"create-retraining-scheduler":   {"ClientToken", "LookbackWindow", "ModelName", "RetrainingFrequency"},
			"delete-dataset":                {"DatasetName"},
			"delete-inference-scheduler":    {"InferenceSchedulerName"},
			"delete-label":                  {"LabelGroupName", "LabelId"},
			"delete-label-group":            {"LabelGroupName"},
			"delete-model":                  {"ModelName"},
			"delete-resource-policy":        {"ResourceArn"},
			"delete-retraining-scheduler":   {"ModelName"},
			"describe-data-ingestion-job":   {"JobId"},
			"describe-dataset":              {"DatasetName"},
			"describe-inference-scheduler":  {"InferenceSchedulerName"},
			"describe-label":                {"LabelGroupName", "LabelId"},
			"describe-label-group":          {"LabelGroupName"},
			"describe-model":                {"ModelName"},
			"describe-model-version":        {"ModelName", "ModelVersion"},
			"describe-resource-policy":      {"ResourceArn"},
			"describe-retraining-scheduler": {"ModelName"},
			"import-dataset":                {"ClientToken", "SourceDatasetArn"},
			"import-model-version":          {"ClientToken", "DatasetName", "SourceModelVersionArn"},
			"list-data-ingestion-jobs":      {},
			"list-datasets":                 {},
			"list-inference-events":         {"InferenceSchedulerName", "IntervalEndTime", "IntervalStartTime"},
			"list-inference-executions":     {"InferenceSchedulerName"},
			"list-inference-schedulers":     {},
			"list-label-groups":             {},
			"list-labels":                   {"LabelGroupName"},
			"list-model-versions":           {"ModelName"},
			"list-models":                   {},
			"list-retraining-schedulers":    {},
			"list-sensor-statistics":        {"DatasetName"},
			"list-tags-for-resource":        {"ResourceArn"},
			"put-resource-policy":           {"ClientToken", "ResourceArn", "ResourcePolicy"},
			"start-data-ingestion-job":      {"ClientToken", "DatasetName", "IngestionInputConfiguration", "RoleArn"},
			"start-inference-scheduler":     {"InferenceSchedulerName"},
			"start-retraining-scheduler":    {"ModelName"},
			"stop-inference-scheduler":      {"InferenceSchedulerName"},
			"stop-retraining-scheduler":     {"ModelName"},
			"tag-resource":                  {"ResourceArn", "Tags"},
			"untag-resource":                {"ResourceArn", "TagKeys"},
			"update-active-model-version":   {"ModelName", "ModelVersion"},
			"update-inference-scheduler":    {"InferenceSchedulerName"},
			"update-label-group":            {"LabelGroupName"},
			"update-model":                  {"ModelName"},
			"update-retraining-scheduler":   {"ModelName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("lookoutequipment", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
