package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/neptunegraph/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"cancel-export-task", "cancel-import-task", "cancel-query", "create-graph", "create-graph-snapshot", "create-graph-using-import-task", "create-private-graph-endpoint", "delete-graph", "delete-graph-snapshot", "delete-private-graph-endpoint", "execute-query", "get-export-task", "get-graph", "get-graph-snapshot", "get-graph-summary", "get-import-task", "get-private-graph-endpoint", "get-query", "list-export-tasks", "list-graph-snapshots", "list-graphs", "list-import-tasks", "list-private-graph-endpoints", "list-queries", "list-tags-for-resource", "reset-graph", "restore-graph-from-snapshot", "start-export-task", "start-graph", "start-import-task", "stop-graph", "tag-resource", "untag-resource", "update-graph"},
		OperationSet: map[string]bool{"cancel-export-task": true, "cancel-import-task": true, "cancel-query": true, "create-graph": true, "create-graph-snapshot": true, "create-graph-using-import-task": true, "create-private-graph-endpoint": true, "delete-graph": true, "delete-graph-snapshot": true, "delete-private-graph-endpoint": true, "execute-query": true, "get-export-task": true, "get-graph": true, "get-graph-snapshot": true, "get-graph-summary": true, "get-import-task": true, "get-private-graph-endpoint": true, "get-query": true, "list-export-tasks": true, "list-graph-snapshots": true, "list-graphs": true, "list-import-tasks": true, "list-private-graph-endpoints": true, "list-queries": true, "list-tags-for-resource": true, "reset-graph": true, "restore-graph-from-snapshot": true, "start-export-task": true, "start-graph": true, "start-import-task": true, "stop-graph": true, "tag-resource": true, "untag-resource": true, "update-graph": true},
		OperationInputs: map[string][]string{
			"cancel-export-task":             {"TaskIdentifier"},
			"cancel-import-task":             {"TaskIdentifier"},
			"cancel-query":                   {"GraphIdentifier", "QueryId"},
			"create-graph":                   {"DeletionProtection", "GraphName", "KmsKeyIdentifier", "ProvisionedMemory", "PublicConnectivity", "ReplicaCount", "Tags", "VectorSearchConfiguration"},
			"create-graph-snapshot":          {"GraphIdentifier", "SnapshotName", "Tags"},
			"create-graph-using-import-task": {"BlankNodeHandling", "DeletionProtection", "FailOnError", "Format", "GraphName", "ImportOptions", "KmsKeyIdentifier", "MaxProvisionedMemory", "MinProvisionedMemory", "ParquetType", "PublicConnectivity", "ReplicaCount", "RoleArn", "Source", "Tags", "VectorSearchConfiguration"},
			"create-private-graph-endpoint":  {"GraphIdentifier", "SubnetIds", "VpcId", "VpcSecurityGroupIds"},
			"delete-graph":                   {"GraphIdentifier", "SkipSnapshot"},
			"delete-graph-snapshot":          {"SnapshotIdentifier"},
			"delete-private-graph-endpoint":  {"GraphIdentifier", "VpcId"},
			"execute-query":                  {"ExplainMode", "GraphIdentifier", "Language", "Parameters", "PlanCache", "QueryString", "QueryTimeoutMilliseconds"},
			"get-export-task":                {"TaskIdentifier"},
			"get-graph":                      {"GraphIdentifier"},
			"get-graph-snapshot":             {"SnapshotIdentifier"},
			"get-graph-summary":              {"GraphIdentifier", "Mode"},
			"get-import-task":                {"TaskIdentifier"},
			"get-private-graph-endpoint":     {"GraphIdentifier", "VpcId"},
			"get-query":                      {"GraphIdentifier", "QueryId"},
			"list-export-tasks":              {"GraphIdentifier", "MaxResults", "NextToken"},
			"list-graph-snapshots":           {"GraphIdentifier", "MaxResults", "NextToken"},
			"list-graphs":                    {"MaxResults", "NextToken"},
			"list-import-tasks":              {"MaxResults", "NextToken"},
			"list-private-graph-endpoints":   {"GraphIdentifier", "MaxResults", "NextToken"},
			"list-queries":                   {"GraphIdentifier", "MaxResults", "State"},
			"list-tags-for-resource":         {"ResourceArn"},
			"reset-graph":                    {"GraphIdentifier", "SkipSnapshot"},
			"restore-graph-from-snapshot":    {"DeletionProtection", "GraphName", "ProvisionedMemory", "PublicConnectivity", "ReplicaCount", "SnapshotIdentifier", "Tags"},
			"start-export-task":              {"Destination", "ExportFilter", "Format", "GraphIdentifier", "KmsKeyIdentifier", "ParquetType", "RoleArn", "Tags"},
			"start-graph":                    {"GraphIdentifier"},
			"start-import-task":              {"BlankNodeHandling", "FailOnError", "Format", "GraphIdentifier", "ImportOptions", "ParquetType", "RoleArn", "Source"},
			"stop-graph":                     {"GraphIdentifier"},
			"tag-resource":                   {"ResourceArn", "Tags"},
			"untag-resource":                 {"ResourceArn", "TagKeys"},
			"update-graph":                   {"DeletionProtection", "GraphIdentifier", "ProvisionedMemory", "PublicConnectivity"},
		},
		OperationInputTypes: map[string]map[string]string{
			"cancel-export-task":             {"TaskIdentifier": "*string"},
			"cancel-import-task":             {"TaskIdentifier": "*string"},
			"cancel-query":                   {"GraphIdentifier": "*string", "QueryId": "*string"},
			"create-graph":                   {"DeletionProtection": "*bool", "GraphName": "*string", "KmsKeyIdentifier": "*string", "ProvisionedMemory": "*int32", "PublicConnectivity": "*bool", "ReplicaCount": "*int32", "Tags": "map[string]string", "VectorSearchConfiguration": "*types.VectorSearchConfiguration"},
			"create-graph-snapshot":          {"GraphIdentifier": "*string", "SnapshotName": "*string", "Tags": "map[string]string"},
			"create-graph-using-import-task": {"BlankNodeHandling": "types.BlankNodeHandling", "DeletionProtection": "*bool", "FailOnError": "*bool", "Format": "types.Format", "GraphName": "*string", "ImportOptions": "types.ImportOptions", "KmsKeyIdentifier": "*string", "MaxProvisionedMemory": "*int32", "MinProvisionedMemory": "*int32", "ParquetType": "types.ParquetType", "PublicConnectivity": "*bool", "ReplicaCount": "*int32", "RoleArn": "*string", "Source": "*string", "Tags": "map[string]string", "VectorSearchConfiguration": "*types.VectorSearchConfiguration"},
			"create-private-graph-endpoint":  {"GraphIdentifier": "*string", "SubnetIds": "[]string", "VpcId": "*string", "VpcSecurityGroupIds": "[]string"},
			"delete-graph":                   {"GraphIdentifier": "*string", "SkipSnapshot": "*bool"},
			"delete-graph-snapshot":          {"SnapshotIdentifier": "*string"},
			"delete-private-graph-endpoint":  {"GraphIdentifier": "*string", "VpcId": "*string"},
			"execute-query":                  {"ExplainMode": "types.ExplainMode", "GraphIdentifier": "*string", "Language": "types.QueryLanguage", "Parameters": "map[string]document.Interface", "PlanCache": "types.PlanCacheType", "QueryString": "*string", "QueryTimeoutMilliseconds": "*int32"},
			"get-export-task":                {"TaskIdentifier": "*string"},
			"get-graph":                      {"GraphIdentifier": "*string"},
			"get-graph-snapshot":             {"SnapshotIdentifier": "*string"},
			"get-graph-summary":              {"GraphIdentifier": "*string", "Mode": "types.GraphSummaryMode"},
			"get-import-task":                {"TaskIdentifier": "*string"},
			"get-private-graph-endpoint":     {"GraphIdentifier": "*string", "VpcId": "*string"},
			"get-query":                      {"GraphIdentifier": "*string", "QueryId": "*string"},
			"list-export-tasks":              {"GraphIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-graph-snapshots":           {"GraphIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-graphs":                    {"MaxResults": "*int32", "NextToken": "*string"},
			"list-import-tasks":              {"MaxResults": "*int32", "NextToken": "*string"},
			"list-private-graph-endpoints":   {"GraphIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-queries":                   {"GraphIdentifier": "*string", "MaxResults": "*int32", "State": "types.QueryStateInput"},
			"list-tags-for-resource":         {"ResourceArn": "*string"},
			"reset-graph":                    {"GraphIdentifier": "*string", "SkipSnapshot": "*bool"},
			"restore-graph-from-snapshot":    {"DeletionProtection": "*bool", "GraphName": "*string", "ProvisionedMemory": "*int32", "PublicConnectivity": "*bool", "ReplicaCount": "*int32", "SnapshotIdentifier": "*string", "Tags": "map[string]string"},
			"start-export-task":              {"Destination": "*string", "ExportFilter": "*types.ExportFilter", "Format": "types.ExportFormat", "GraphIdentifier": "*string", "KmsKeyIdentifier": "*string", "ParquetType": "types.ParquetType", "RoleArn": "*string", "Tags": "map[string]string"},
			"start-graph":                    {"GraphIdentifier": "*string"},
			"start-import-task":              {"BlankNodeHandling": "types.BlankNodeHandling", "FailOnError": "*bool", "Format": "types.Format", "GraphIdentifier": "*string", "ImportOptions": "types.ImportOptions", "ParquetType": "types.ParquetType", "RoleArn": "*string", "Source": "*string"},
			"stop-graph":                     {"GraphIdentifier": "*string"},
			"tag-resource":                   {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                 {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-graph":                   {"DeletionProtection": "*bool", "GraphIdentifier": "*string", "ProvisionedMemory": "*int32", "PublicConnectivity": "*bool"},
		},
		OperationInputRequired: map[string][]string{
			"cancel-export-task":             {"TaskIdentifier"},
			"cancel-import-task":             {"TaskIdentifier"},
			"cancel-query":                   {"GraphIdentifier", "QueryId"},
			"create-graph":                   {"GraphName", "ProvisionedMemory"},
			"create-graph-snapshot":          {"GraphIdentifier", "SnapshotName"},
			"create-graph-using-import-task": {"GraphName", "RoleArn", "Source"},
			"create-private-graph-endpoint":  {"GraphIdentifier"},
			"delete-graph":                   {"GraphIdentifier", "SkipSnapshot"},
			"delete-graph-snapshot":          {"SnapshotIdentifier"},
			"delete-private-graph-endpoint":  {"GraphIdentifier", "VpcId"},
			"execute-query":                  {"GraphIdentifier", "Language", "QueryString"},
			"get-export-task":                {"TaskIdentifier"},
			"get-graph":                      {"GraphIdentifier"},
			"get-graph-snapshot":             {"SnapshotIdentifier"},
			"get-graph-summary":              {"GraphIdentifier"},
			"get-import-task":                {"TaskIdentifier"},
			"get-private-graph-endpoint":     {"GraphIdentifier", "VpcId"},
			"get-query":                      {"GraphIdentifier", "QueryId"},
			"list-export-tasks":              {},
			"list-graph-snapshots":           {},
			"list-graphs":                    {},
			"list-import-tasks":              {},
			"list-private-graph-endpoints":   {"GraphIdentifier"},
			"list-queries":                   {"GraphIdentifier", "MaxResults"},
			"list-tags-for-resource":         {"ResourceArn"},
			"reset-graph":                    {"GraphIdentifier", "SkipSnapshot"},
			"restore-graph-from-snapshot":    {"GraphName", "SnapshotIdentifier"},
			"start-export-task":              {"Destination", "Format", "GraphIdentifier", "KmsKeyIdentifier", "RoleArn"},
			"start-graph":                    {"GraphIdentifier"},
			"start-import-task":              {"GraphIdentifier", "RoleArn", "Source"},
			"stop-graph":                     {"GraphIdentifier"},
			"tag-resource":                   {"ResourceArn", "Tags"},
			"untag-resource":                 {"ResourceArn", "TagKeys"},
			"update-graph":                   {"GraphIdentifier"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("neptunegraph", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
