package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/kms/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"cancel-key-deletion", "connect-custom-key-store", "create-alias", "create-custom-key-store", "create-grant", "create-key", "decrypt", "delete-alias", "delete-custom-key-store", "delete-imported-key-material", "derive-shared-secret", "describe-custom-key-stores", "describe-key", "disable-key", "disable-key-rotation", "disconnect-custom-key-store", "enable-key", "enable-key-rotation", "encrypt", "generate-data-key", "generate-data-key-pair", "generate-data-key-pair-without-plaintext", "generate-data-key-without-plaintext", "generate-mac", "generate-random", "get-key-policy", "get-key-rotation-status", "get-parameters-for-import", "get-public-key", "import-key-material", "list-aliases", "list-grants", "list-key-policies", "list-key-rotations", "list-keys", "list-resource-tags", "list-retirable-grants", "put-key-policy", "re-encrypt", "replicate-key", "retire-grant", "revoke-grant", "rotate-key-on-demand", "schedule-key-deletion", "sign", "tag-resource", "untag-resource", "update-alias", "update-custom-key-store", "update-key-description", "update-primary-region", "verify", "verify-mac"},
		OperationSet: map[string]bool{"cancel-key-deletion": true, "connect-custom-key-store": true, "create-alias": true, "create-custom-key-store": true, "create-grant": true, "create-key": true, "decrypt": true, "delete-alias": true, "delete-custom-key-store": true, "delete-imported-key-material": true, "derive-shared-secret": true, "describe-custom-key-stores": true, "describe-key": true, "disable-key": true, "disable-key-rotation": true, "disconnect-custom-key-store": true, "enable-key": true, "enable-key-rotation": true, "encrypt": true, "generate-data-key": true, "generate-data-key-pair": true, "generate-data-key-pair-without-plaintext": true, "generate-data-key-without-plaintext": true, "generate-mac": true, "generate-random": true, "get-key-policy": true, "get-key-rotation-status": true, "get-parameters-for-import": true, "get-public-key": true, "import-key-material": true, "list-aliases": true, "list-grants": true, "list-key-policies": true, "list-key-rotations": true, "list-keys": true, "list-resource-tags": true, "list-retirable-grants": true, "put-key-policy": true, "re-encrypt": true, "replicate-key": true, "retire-grant": true, "revoke-grant": true, "rotate-key-on-demand": true, "schedule-key-deletion": true, "sign": true, "tag-resource": true, "untag-resource": true, "update-alias": true, "update-custom-key-store": true, "update-key-description": true, "update-primary-region": true, "verify": true, "verify-mac": true},
		OperationInputs: map[string][]string{
			"cancel-key-deletion":                      {"KeyId"},
			"connect-custom-key-store":                 {"CustomKeyStoreId"},
			"create-alias":                             {"AliasName", "TargetKeyId"},
			"create-custom-key-store":                  {"CloudHsmClusterId", "CustomKeyStoreName", "CustomKeyStoreType", "KeyStorePassword", "TrustAnchorCertificate", "XksProxyAuthenticationCredential", "XksProxyConnectivity", "XksProxyUriEndpoint", "XksProxyUriPath", "XksProxyVpcEndpointServiceName", "XksProxyVpcEndpointServiceOwner"},
			"create-grant":                             {"Constraints", "DryRun", "GrantTokens", "GranteePrincipal", "KeyId", "Name", "Operations", "RetiringPrincipal"},
			"create-key":                               {"BypassPolicyLockoutSafetyCheck", "CustomKeyStoreId", "CustomerMasterKeySpec", "Description", "KeySpec", "KeyUsage", "MultiRegion", "Origin", "Policy", "Tags", "XksKeyId"},
			"decrypt":                                  {"CiphertextBlob", "DryRun", "DryRunModifiers", "EncryptionAlgorithm", "EncryptionContext", "GrantTokens", "KeyId", "Recipient"},
			"delete-alias":                             {"AliasName"},
			"delete-custom-key-store":                  {"CustomKeyStoreId"},
			"delete-imported-key-material":             {"KeyId", "KeyMaterialId"},
			"derive-shared-secret":                     {"DryRun", "GrantTokens", "KeyAgreementAlgorithm", "KeyId", "PublicKey", "Recipient"},
			"describe-custom-key-stores":               {"CustomKeyStoreId", "CustomKeyStoreName", "Limit", "Marker"},
			"describe-key":                             {"GrantTokens", "KeyId"},
			"disable-key":                              {"KeyId"},
			"disable-key-rotation":                     {"KeyId"},
			"disconnect-custom-key-store":              {"CustomKeyStoreId"},
			"enable-key":                               {"KeyId"},
			"enable-key-rotation":                      {"KeyId", "RotationPeriodInDays"},
			"encrypt":                                  {"DryRun", "EncryptionAlgorithm", "EncryptionContext", "GrantTokens", "KeyId", "Plaintext"},
			"generate-data-key":                        {"DryRun", "EncryptionContext", "GrantTokens", "KeyId", "KeySpec", "NumberOfBytes", "Recipient"},
			"generate-data-key-pair":                   {"DryRun", "EncryptionContext", "GrantTokens", "KeyId", "KeyPairSpec", "Recipient"},
			"generate-data-key-pair-without-plaintext": {"DryRun", "EncryptionContext", "GrantTokens", "KeyId", "KeyPairSpec"},
			"generate-data-key-without-plaintext":      {"DryRun", "EncryptionContext", "GrantTokens", "KeyId", "KeySpec", "NumberOfBytes"},
			"generate-mac":                             {"DryRun", "GrantTokens", "KeyId", "MacAlgorithm", "Message"},
			"generate-random":                          {"CustomKeyStoreId", "NumberOfBytes", "Recipient"},
			"get-key-policy":                           {"KeyId", "PolicyName"},
			"get-key-rotation-status":                  {"KeyId"},
			"get-parameters-for-import":                {"KeyId", "WrappingAlgorithm", "WrappingKeySpec"},
			"get-public-key":                           {"GrantTokens", "KeyId"},
			"import-key-material":                      {"EncryptedKeyMaterial", "ExpirationModel", "ImportToken", "ImportType", "KeyId", "KeyMaterialDescription", "KeyMaterialId", "ValidTo"},
			"list-aliases":                             {"KeyId", "Limit", "Marker"},
			"list-grants":                              {"GrantId", "GranteePrincipal", "KeyId", "Limit", "Marker"},
			"list-key-policies":                        {"KeyId", "Limit", "Marker"},
			"list-key-rotations":                       {"IncludeKeyMaterial", "KeyId", "Limit", "Marker"},
			"list-keys":                                {"Limit", "Marker"},
			"list-resource-tags":                       {"KeyId", "Limit", "Marker"},
			"list-retirable-grants":                    {"Limit", "Marker", "RetiringPrincipal"},
			"put-key-policy":                           {"BypassPolicyLockoutSafetyCheck", "KeyId", "Policy", "PolicyName"},
			"re-encrypt":                               {"CiphertextBlob", "DestinationEncryptionAlgorithm", "DestinationEncryptionContext", "DestinationKeyId", "DryRun", "DryRunModifiers", "GrantTokens", "SourceEncryptionAlgorithm", "SourceEncryptionContext", "SourceKeyId"},
			"replicate-key":                            {"BypassPolicyLockoutSafetyCheck", "Description", "KeyId", "Policy", "ReplicaRegion", "Tags"},
			"retire-grant":                             {"DryRun", "GrantId", "GrantToken", "KeyId"},
			"revoke-grant":                             {"DryRun", "GrantId", "KeyId"},
			"rotate-key-on-demand":                     {"KeyId"},
			"schedule-key-deletion":                    {"KeyId", "PendingWindowInDays"},
			"sign":                                     {"DryRun", "GrantTokens", "KeyId", "Message", "MessageType", "SigningAlgorithm"},
			"tag-resource":                             {"KeyId", "Tags"},
			"untag-resource":                           {"KeyId", "TagKeys"},
			"update-alias":                             {"AliasName", "TargetKeyId"},
			"update-custom-key-store":                  {"CloudHsmClusterId", "CustomKeyStoreId", "KeyStorePassword", "NewCustomKeyStoreName", "XksProxyAuthenticationCredential", "XksProxyConnectivity", "XksProxyUriEndpoint", "XksProxyUriPath", "XksProxyVpcEndpointServiceName", "XksProxyVpcEndpointServiceOwner"},
			"update-key-description":                   {"Description", "KeyId"},
			"update-primary-region":                    {"KeyId", "PrimaryRegion"},
			"verify":                                   {"DryRun", "GrantTokens", "KeyId", "Message", "MessageType", "Signature", "SigningAlgorithm"},
			"verify-mac":                               {"DryRun", "GrantTokens", "KeyId", "Mac", "MacAlgorithm", "Message"},
		},
		OperationInputTypes: map[string]map[string]string{
			"cancel-key-deletion":                      {"KeyId": "*string"},
			"connect-custom-key-store":                 {"CustomKeyStoreId": "*string"},
			"create-alias":                             {"AliasName": "*string", "TargetKeyId": "*string"},
			"create-custom-key-store":                  {"CloudHsmClusterId": "*string", "CustomKeyStoreName": "*string", "CustomKeyStoreType": "types.CustomKeyStoreType", "KeyStorePassword": "*string", "TrustAnchorCertificate": "*string", "XksProxyAuthenticationCredential": "*types.XksProxyAuthenticationCredentialType", "XksProxyConnectivity": "types.XksProxyConnectivityType", "XksProxyUriEndpoint": "*string", "XksProxyUriPath": "*string", "XksProxyVpcEndpointServiceName": "*string", "XksProxyVpcEndpointServiceOwner": "*string"},
			"create-grant":                             {"Constraints": "*types.GrantConstraints", "DryRun": "*bool", "GrantTokens": "[]string", "GranteePrincipal": "*string", "KeyId": "*string", "Name": "*string", "Operations": "[]types.GrantOperation", "RetiringPrincipal": "*string"},
			"create-key":                               {"BypassPolicyLockoutSafetyCheck": "bool", "CustomKeyStoreId": "*string", "CustomerMasterKeySpec": "types.CustomerMasterKeySpec", "Description": "*string", "KeySpec": "types.KeySpec", "KeyUsage": "types.KeyUsageType", "MultiRegion": "*bool", "Origin": "types.OriginType", "Policy": "*string", "Tags": "[]types.Tag", "XksKeyId": "*string"},
			"decrypt":                                  {"CiphertextBlob": "[]byte", "DryRun": "*bool", "DryRunModifiers": "[]types.DryRunModifierType", "EncryptionAlgorithm": "types.EncryptionAlgorithmSpec", "EncryptionContext": "map[string]string", "GrantTokens": "[]string", "KeyId": "*string", "Recipient": "*types.RecipientInfo"},
			"delete-alias":                             {"AliasName": "*string"},
			"delete-custom-key-store":                  {"CustomKeyStoreId": "*string"},
			"delete-imported-key-material":             {"KeyId": "*string", "KeyMaterialId": "*string"},
			"derive-shared-secret":                     {"DryRun": "*bool", "GrantTokens": "[]string", "KeyAgreementAlgorithm": "types.KeyAgreementAlgorithmSpec", "KeyId": "*string", "PublicKey": "[]byte", "Recipient": "*types.RecipientInfo"},
			"describe-custom-key-stores":               {"CustomKeyStoreId": "*string", "CustomKeyStoreName": "*string", "Limit": "*int32", "Marker": "*string"},
			"describe-key":                             {"GrantTokens": "[]string", "KeyId": "*string"},
			"disable-key":                              {"KeyId": "*string"},
			"disable-key-rotation":                     {"KeyId": "*string"},
			"disconnect-custom-key-store":              {"CustomKeyStoreId": "*string"},
			"enable-key":                               {"KeyId": "*string"},
			"enable-key-rotation":                      {"KeyId": "*string", "RotationPeriodInDays": "*int32"},
			"encrypt":                                  {"DryRun": "*bool", "EncryptionAlgorithm": "types.EncryptionAlgorithmSpec", "EncryptionContext": "map[string]string", "GrantTokens": "[]string", "KeyId": "*string", "Plaintext": "[]byte"},
			"generate-data-key":                        {"DryRun": "*bool", "EncryptionContext": "map[string]string", "GrantTokens": "[]string", "KeyId": "*string", "KeySpec": "types.DataKeySpec", "NumberOfBytes": "*int32", "Recipient": "*types.RecipientInfo"},
			"generate-data-key-pair":                   {"DryRun": "*bool", "EncryptionContext": "map[string]string", "GrantTokens": "[]string", "KeyId": "*string", "KeyPairSpec": "types.DataKeyPairSpec", "Recipient": "*types.RecipientInfo"},
			"generate-data-key-pair-without-plaintext": {"DryRun": "*bool", "EncryptionContext": "map[string]string", "GrantTokens": "[]string", "KeyId": "*string", "KeyPairSpec": "types.DataKeyPairSpec"},
			"generate-data-key-without-plaintext":      {"DryRun": "*bool", "EncryptionContext": "map[string]string", "GrantTokens": "[]string", "KeyId": "*string", "KeySpec": "types.DataKeySpec", "NumberOfBytes": "*int32"},
			"generate-mac":                             {"DryRun": "*bool", "GrantTokens": "[]string", "KeyId": "*string", "MacAlgorithm": "types.MacAlgorithmSpec", "Message": "[]byte"},
			"generate-random":                          {"CustomKeyStoreId": "*string", "NumberOfBytes": "*int32", "Recipient": "*types.RecipientInfo"},
			"get-key-policy":                           {"KeyId": "*string", "PolicyName": "*string"},
			"get-key-rotation-status":                  {"KeyId": "*string"},
			"get-parameters-for-import":                {"KeyId": "*string", "WrappingAlgorithm": "types.AlgorithmSpec", "WrappingKeySpec": "types.WrappingKeySpec"},
			"get-public-key":                           {"GrantTokens": "[]string", "KeyId": "*string"},
			"import-key-material":                      {"EncryptedKeyMaterial": "[]byte", "ExpirationModel": "types.ExpirationModelType", "ImportToken": "[]byte", "ImportType": "types.ImportType", "KeyId": "*string", "KeyMaterialDescription": "*string", "KeyMaterialId": "*string", "ValidTo": "*time.Time"},
			"list-aliases":                             {"KeyId": "*string", "Limit": "*int32", "Marker": "*string"},
			"list-grants":                              {"GrantId": "*string", "GranteePrincipal": "*string", "KeyId": "*string", "Limit": "*int32", "Marker": "*string"},
			"list-key-policies":                        {"KeyId": "*string", "Limit": "*int32", "Marker": "*string"},
			"list-key-rotations":                       {"IncludeKeyMaterial": "types.IncludeKeyMaterial", "KeyId": "*string", "Limit": "*int32", "Marker": "*string"},
			"list-keys":                                {"Limit": "*int32", "Marker": "*string"},
			"list-resource-tags":                       {"KeyId": "*string", "Limit": "*int32", "Marker": "*string"},
			"list-retirable-grants":                    {"Limit": "*int32", "Marker": "*string", "RetiringPrincipal": "*string"},
			"put-key-policy":                           {"BypassPolicyLockoutSafetyCheck": "bool", "KeyId": "*string", "Policy": "*string", "PolicyName": "*string"},
			"re-encrypt":                               {"CiphertextBlob": "[]byte", "DestinationEncryptionAlgorithm": "types.EncryptionAlgorithmSpec", "DestinationEncryptionContext": "map[string]string", "DestinationKeyId": "*string", "DryRun": "*bool", "DryRunModifiers": "[]types.DryRunModifierType", "GrantTokens": "[]string", "SourceEncryptionAlgorithm": "types.EncryptionAlgorithmSpec", "SourceEncryptionContext": "map[string]string", "SourceKeyId": "*string"},
			"replicate-key":                            {"BypassPolicyLockoutSafetyCheck": "bool", "Description": "*string", "KeyId": "*string", "Policy": "*string", "ReplicaRegion": "*string", "Tags": "[]types.Tag"},
			"retire-grant":                             {"DryRun": "*bool", "GrantId": "*string", "GrantToken": "*string", "KeyId": "*string"},
			"revoke-grant":                             {"DryRun": "*bool", "GrantId": "*string", "KeyId": "*string"},
			"rotate-key-on-demand":                     {"KeyId": "*string"},
			"schedule-key-deletion":                    {"KeyId": "*string", "PendingWindowInDays": "*int32"},
			"sign":                                     {"DryRun": "*bool", "GrantTokens": "[]string", "KeyId": "*string", "Message": "[]byte", "MessageType": "types.MessageType", "SigningAlgorithm": "types.SigningAlgorithmSpec"},
			"tag-resource":                             {"KeyId": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                           {"KeyId": "*string", "TagKeys": "[]string"},
			"update-alias":                             {"AliasName": "*string", "TargetKeyId": "*string"},
			"update-custom-key-store":                  {"CloudHsmClusterId": "*string", "CustomKeyStoreId": "*string", "KeyStorePassword": "*string", "NewCustomKeyStoreName": "*string", "XksProxyAuthenticationCredential": "*types.XksProxyAuthenticationCredentialType", "XksProxyConnectivity": "types.XksProxyConnectivityType", "XksProxyUriEndpoint": "*string", "XksProxyUriPath": "*string", "XksProxyVpcEndpointServiceName": "*string", "XksProxyVpcEndpointServiceOwner": "*string"},
			"update-key-description":                   {"Description": "*string", "KeyId": "*string"},
			"update-primary-region":                    {"KeyId": "*string", "PrimaryRegion": "*string"},
			"verify":                                   {"DryRun": "*bool", "GrantTokens": "[]string", "KeyId": "*string", "Message": "[]byte", "MessageType": "types.MessageType", "Signature": "[]byte", "SigningAlgorithm": "types.SigningAlgorithmSpec"},
			"verify-mac":                               {"DryRun": "*bool", "GrantTokens": "[]string", "KeyId": "*string", "Mac": "[]byte", "MacAlgorithm": "types.MacAlgorithmSpec", "Message": "[]byte"},
		},
		OperationInputRequired: map[string][]string{
			"cancel-key-deletion":                      {"KeyId"},
			"connect-custom-key-store":                 {"CustomKeyStoreId"},
			"create-alias":                             {"AliasName", "TargetKeyId"},
			"create-custom-key-store":                  {"CustomKeyStoreName"},
			"create-grant":                             {"GranteePrincipal", "KeyId", "Operations"},
			"create-key":                               {},
			"decrypt":                                  {},
			"delete-alias":                             {"AliasName"},
			"delete-custom-key-store":                  {"CustomKeyStoreId"},
			"delete-imported-key-material":             {"KeyId"},
			"derive-shared-secret":                     {"KeyAgreementAlgorithm", "KeyId", "PublicKey"},
			"describe-custom-key-stores":               {},
			"describe-key":                             {"KeyId"},
			"disable-key":                              {"KeyId"},
			"disable-key-rotation":                     {"KeyId"},
			"disconnect-custom-key-store":              {"CustomKeyStoreId"},
			"enable-key":                               {"KeyId"},
			"enable-key-rotation":                      {"KeyId"},
			"encrypt":                                  {"KeyId", "Plaintext"},
			"generate-data-key":                        {"KeyId"},
			"generate-data-key-pair":                   {"KeyId", "KeyPairSpec"},
			"generate-data-key-pair-without-plaintext": {"KeyId", "KeyPairSpec"},
			"generate-data-key-without-plaintext":      {"KeyId"},
			"generate-mac":                             {"KeyId", "MacAlgorithm", "Message"},
			"generate-random":                          {},
			"get-key-policy":                           {"KeyId"},
			"get-key-rotation-status":                  {"KeyId"},
			"get-parameters-for-import":                {"KeyId", "WrappingAlgorithm", "WrappingKeySpec"},
			"get-public-key":                           {"KeyId"},
			"import-key-material":                      {"EncryptedKeyMaterial", "ImportToken", "KeyId"},
			"list-aliases":                             {},
			"list-grants":                              {"KeyId"},
			"list-key-policies":                        {"KeyId"},
			"list-key-rotations":                       {"KeyId"},
			"list-keys":                                {},
			"list-resource-tags":                       {"KeyId"},
			"list-retirable-grants":                    {"RetiringPrincipal"},
			"put-key-policy":                           {"KeyId", "Policy"},
			"re-encrypt":                               {"DestinationKeyId"},
			"replicate-key":                            {"KeyId", "ReplicaRegion"},
			"retire-grant":                             {},
			"revoke-grant":                             {"GrantId", "KeyId"},
			"rotate-key-on-demand":                     {"KeyId"},
			"schedule-key-deletion":                    {"KeyId"},
			"sign":                                     {"KeyId", "Message", "SigningAlgorithm"},
			"tag-resource":                             {"KeyId", "Tags"},
			"untag-resource":                           {"KeyId", "TagKeys"},
			"update-alias":                             {"AliasName", "TargetKeyId"},
			"update-custom-key-store":                  {"CustomKeyStoreId"},
			"update-key-description":                   {"Description", "KeyId"},
			"update-primary-region":                    {"KeyId", "PrimaryRegion"},
			"verify":                                   {"KeyId", "Message", "Signature", "SigningAlgorithm"},
			"verify-mac":                               {"KeyId", "Mac", "MacAlgorithm", "Message"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("kms", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
