package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/apigatewayv2/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-api", "create-api-mapping", "create-authorizer", "create-deployment", "create-domain-name", "create-integration", "create-integration-response", "create-model", "create-portal", "create-portal-product", "create-product-page", "create-product-rest-endpoint-page", "create-route", "create-route-response", "create-routing-rule", "create-stage", "create-vpc-link", "delete-access-log-settings", "delete-api", "delete-api-mapping", "delete-authorizer", "delete-cors-configuration", "delete-deployment", "delete-domain-name", "delete-integration", "delete-integration-response", "delete-model", "delete-portal", "delete-portal-product", "delete-portal-product-sharing-policy", "delete-product-page", "delete-product-rest-endpoint-page", "delete-route", "delete-route-request-parameter", "delete-route-response", "delete-route-settings", "delete-routing-rule", "delete-stage", "delete-vpc-link", "disable-portal", "export-api", "get-api", "get-api-mapping", "get-api-mappings", "get-apis", "get-authorizer", "get-authorizers", "get-deployment", "get-deployments", "get-domain-name", "get-domain-names", "get-integration", "get-integration-response", "get-integration-responses", "get-integrations", "get-model", "get-model-template", "get-models", "get-portal", "get-portal-product", "get-portal-product-sharing-policy", "get-product-page", "get-product-rest-endpoint-page", "get-route", "get-route-response", "get-route-responses", "get-routes", "get-routing-rule", "get-stage", "get-stages", "get-tags", "get-vpc-link", "get-vpc-links", "import-api", "list-portal-products", "list-portals", "list-product-pages", "list-product-rest-endpoint-pages", "list-routing-rules", "preview-portal", "publish-portal", "put-portal-product-sharing-policy", "put-routing-rule", "reimport-api", "reset-authorizers-cache", "tag-resource", "untag-resource", "update-api", "update-api-mapping", "update-authorizer", "update-deployment", "update-domain-name", "update-integration", "update-integration-response", "update-model", "update-portal", "update-portal-product", "update-product-page", "update-product-rest-endpoint-page", "update-route", "update-route-response", "update-stage", "update-vpc-link"},
		OperationSet: map[string]bool{"create-api": true, "create-api-mapping": true, "create-authorizer": true, "create-deployment": true, "create-domain-name": true, "create-integration": true, "create-integration-response": true, "create-model": true, "create-portal": true, "create-portal-product": true, "create-product-page": true, "create-product-rest-endpoint-page": true, "create-route": true, "create-route-response": true, "create-routing-rule": true, "create-stage": true, "create-vpc-link": true, "delete-access-log-settings": true, "delete-api": true, "delete-api-mapping": true, "delete-authorizer": true, "delete-cors-configuration": true, "delete-deployment": true, "delete-domain-name": true, "delete-integration": true, "delete-integration-response": true, "delete-model": true, "delete-portal": true, "delete-portal-product": true, "delete-portal-product-sharing-policy": true, "delete-product-page": true, "delete-product-rest-endpoint-page": true, "delete-route": true, "delete-route-request-parameter": true, "delete-route-response": true, "delete-route-settings": true, "delete-routing-rule": true, "delete-stage": true, "delete-vpc-link": true, "disable-portal": true, "export-api": true, "get-api": true, "get-api-mapping": true, "get-api-mappings": true, "get-apis": true, "get-authorizer": true, "get-authorizers": true, "get-deployment": true, "get-deployments": true, "get-domain-name": true, "get-domain-names": true, "get-integration": true, "get-integration-response": true, "get-integration-responses": true, "get-integrations": true, "get-model": true, "get-model-template": true, "get-models": true, "get-portal": true, "get-portal-product": true, "get-portal-product-sharing-policy": true, "get-product-page": true, "get-product-rest-endpoint-page": true, "get-route": true, "get-route-response": true, "get-route-responses": true, "get-routes": true, "get-routing-rule": true, "get-stage": true, "get-stages": true, "get-tags": true, "get-vpc-link": true, "get-vpc-links": true, "import-api": true, "list-portal-products": true, "list-portals": true, "list-product-pages": true, "list-product-rest-endpoint-pages": true, "list-routing-rules": true, "preview-portal": true, "publish-portal": true, "put-portal-product-sharing-policy": true, "put-routing-rule": true, "reimport-api": true, "reset-authorizers-cache": true, "tag-resource": true, "untag-resource": true, "update-api": true, "update-api-mapping": true, "update-authorizer": true, "update-deployment": true, "update-domain-name": true, "update-integration": true, "update-integration-response": true, "update-model": true, "update-portal": true, "update-portal-product": true, "update-product-page": true, "update-product-rest-endpoint-page": true, "update-route": true, "update-route-response": true, "update-stage": true, "update-vpc-link": true},
		OperationInputs: map[string][]string{
			"create-api":                           {"ApiKeySelectionExpression", "CorsConfiguration", "CredentialsArn", "Description", "DisableExecuteApiEndpoint", "DisableSchemaValidation", "IpAddressType", "Name", "ProtocolType", "RouteKey", "RouteSelectionExpression", "Tags", "Target", "Version"},
			"create-api-mapping":                   {"ApiId", "ApiMappingKey", "DomainName", "Stage"},
			"create-authorizer":                    {"ApiId", "AuthorizerCredentialsArn", "AuthorizerPayloadFormatVersion", "AuthorizerResultTtlInSeconds", "AuthorizerType", "AuthorizerUri", "EnableSimpleResponses", "IdentitySource", "IdentityValidationExpression", "JwtConfiguration", "Name"},
			"create-deployment":                    {"ApiId", "Description", "StageName"},
			"create-domain-name":                   {"DomainName", "DomainNameConfigurations", "MutualTlsAuthentication", "RoutingMode", "Tags"},
			"create-integration":                   {"ApiId", "ConnectionId", "ConnectionType", "ContentHandlingStrategy", "CredentialsArn", "Description", "IntegrationMethod", "IntegrationSubtype", "IntegrationType", "IntegrationUri", "PassthroughBehavior", "PayloadFormatVersion", "RequestParameters", "RequestTemplates", "ResponseParameters", "TemplateSelectionExpression", "TimeoutInMillis", "TlsConfig"},
			"create-integration-response":          {"ApiId", "ContentHandlingStrategy", "IntegrationId", "IntegrationResponseKey", "ResponseParameters", "ResponseTemplates", "TemplateSelectionExpression"},
			"create-model":                         {"ApiId", "ContentType", "Description", "Name", "Schema"},
			"create-portal":                        {"Authorization", "EndpointConfiguration", "IncludedPortalProductArns", "LogoUri", "PortalContent", "RumAppMonitorName", "Tags"},
			"create-portal-product":                {"Description", "DisplayName", "Tags"},
			"create-product-page":                  {"DisplayContent", "PortalProductId"},
			"create-product-rest-endpoint-page":    {"DisplayContent", "PortalProductId", "RestEndpointIdentifier", "TryItState"},
			"create-route":                         {"ApiId", "ApiKeyRequired", "AuthorizationScopes", "AuthorizationType", "AuthorizerId", "ModelSelectionExpression", "OperationName", "RequestModels", "RequestParameters", "RouteKey", "RouteResponseSelectionExpression", "Target"},
			"create-route-response":                {"ApiId", "ModelSelectionExpression", "ResponseModels", "ResponseParameters", "RouteId", "RouteResponseKey"},
			"create-routing-rule":                  {"Actions", "Conditions", "DomainName", "DomainNameId", "Priority"},
			"create-stage":                         {"AccessLogSettings", "ApiId", "AutoDeploy", "ClientCertificateId", "DefaultRouteSettings", "DeploymentId", "Description", "RouteSettings", "StageName", "StageVariables", "Tags"},
			"create-vpc-link":                      {"Name", "SecurityGroupIds", "SubnetIds", "Tags"},
			"delete-access-log-settings":           {"ApiId", "StageName"},
			"delete-api":                           {"ApiId"},
			"delete-api-mapping":                   {"ApiMappingId", "DomainName"},
			"delete-authorizer":                    {"ApiId", "AuthorizerId"},
			"delete-cors-configuration":            {"ApiId"},
			"delete-deployment":                    {"ApiId", "DeploymentId"},
			"delete-domain-name":                   {"DomainName"},
			"delete-integration":                   {"ApiId", "IntegrationId"},
			"delete-integration-response":          {"ApiId", "IntegrationId", "IntegrationResponseId"},
			"delete-model":                         {"ApiId", "ModelId"},
			"delete-portal":                        {"PortalId"},
			"delete-portal-product":                {"PortalProductId"},
			"delete-portal-product-sharing-policy": {"PortalProductId"},
			"delete-product-page":                  {"PortalProductId", "ProductPageId"},
			"delete-product-rest-endpoint-page":    {"PortalProductId", "ProductRestEndpointPageId"},
			"delete-route":                         {"ApiId", "RouteId"},
			"delete-route-request-parameter":       {"ApiId", "RequestParameterKey", "RouteId"},
			"delete-route-response":                {"ApiId", "RouteId", "RouteResponseId"},
			"delete-route-settings":                {"ApiId", "RouteKey", "StageName"},
			"delete-routing-rule":                  {"DomainName", "DomainNameId", "RoutingRuleId"},
			"delete-stage":                         {"ApiId", "StageName"},
			"delete-vpc-link":                      {"VpcLinkId"},
			"disable-portal":                       {"PortalId"},
			"export-api":                           {"ApiId", "ExportVersion", "IncludeExtensions", "OutputType", "Specification", "StageName"},
			"get-api":                              {"ApiId"},
			"get-api-mapping":                      {"ApiMappingId", "DomainName"},
			"get-api-mappings":                     {"DomainName", "MaxResults", "NextToken"},
			"get-apis":                             {"MaxResults", "NextToken"},
			"get-authorizer":                       {"ApiId", "AuthorizerId"},
			"get-authorizers":                      {"ApiId", "MaxResults", "NextToken"},
			"get-deployment":                       {"ApiId", "DeploymentId"},
			"get-deployments":                      {"ApiId", "MaxResults", "NextToken"},
			"get-domain-name":                      {"DomainName"},
			"get-domain-names":                     {"MaxResults", "NextToken"},
			"get-integration":                      {"ApiId", "IntegrationId"},
			"get-integration-response":             {"ApiId", "IntegrationId", "IntegrationResponseId"},
			"get-integration-responses":            {"ApiId", "IntegrationId", "MaxResults", "NextToken"},
			"get-integrations":                     {"ApiId", "MaxResults", "NextToken"},
			"get-model":                            {"ApiId", "ModelId"},
			"get-model-template":                   {"ApiId", "ModelId"},
			"get-models":                           {"ApiId", "MaxResults", "NextToken"},
			"get-portal":                           {"PortalId"},
			"get-portal-product":                   {"PortalProductId", "ResourceOwnerAccountId"},
			"get-portal-product-sharing-policy":    {"PortalProductId"},
			"get-product-page":                     {"PortalProductId", "ProductPageId", "ResourceOwnerAccountId"},
			"get-product-rest-endpoint-page":       {"IncludeRawDisplayContent", "PortalProductId", "ProductRestEndpointPageId", "ResourceOwnerAccountId"},
			"get-route":                            {"ApiId", "RouteId"},
			"get-route-response":                   {"ApiId", "RouteId", "RouteResponseId"},
			"get-route-responses":                  {"ApiId", "MaxResults", "NextToken", "RouteId"},
			"get-routes":                           {"ApiId", "MaxResults", "NextToken"},
			"get-routing-rule":                     {"DomainName", "DomainNameId", "RoutingRuleId"},
			"get-stage":                            {"ApiId", "StageName"},
			"get-stages":                           {"ApiId", "MaxResults", "NextToken"},
			"get-tags":                             {"ResourceArn"},
			"get-vpc-link":                         {"VpcLinkId"},
			"get-vpc-links":                        {"MaxResults", "NextToken"},
			"import-api":                           {"Basepath", "Body", "FailOnWarnings"},
			"list-portal-products":                 {"MaxResults", "NextToken", "ResourceOwner"},
			"list-portals":                         {"MaxResults", "NextToken"},
			"list-product-pages":                   {"MaxResults", "NextToken", "PortalProductId", "ResourceOwnerAccountId"},
			"list-product-rest-endpoint-pages":     {"MaxResults", "NextToken", "PortalProductId", "ResourceOwnerAccountId"},
			"list-routing-rules":                   {"DomainName", "DomainNameId", "MaxResults", "NextToken"},
			"preview-portal":                       {"PortalId"},
			"publish-portal":                       {"Description", "PortalId"},
			"put-portal-product-sharing-policy":    {"PolicyDocument", "PortalProductId"},
			"put-routing-rule":                     {"Actions", "Conditions", "DomainName", "DomainNameId", "Priority", "RoutingRuleId"},
			"reimport-api":                         {"ApiId", "Basepath", "Body", "FailOnWarnings"},
			"reset-authorizers-cache":              {"ApiId", "StageName"},
			"tag-resource":                         {"ResourceArn", "Tags"},
			"untag-resource":                       {"ResourceArn", "TagKeys"},
			"update-api":                           {"ApiId", "ApiKeySelectionExpression", "CorsConfiguration", "CredentialsArn", "Description", "DisableExecuteApiEndpoint", "DisableSchemaValidation", "IpAddressType", "Name", "RouteKey", "RouteSelectionExpression", "Target", "Version"},
			"update-api-mapping":                   {"ApiId", "ApiMappingId", "ApiMappingKey", "DomainName", "Stage"},
			"update-authorizer":                    {"ApiId", "AuthorizerCredentialsArn", "AuthorizerId", "AuthorizerPayloadFormatVersion", "AuthorizerResultTtlInSeconds", "AuthorizerType", "AuthorizerUri", "EnableSimpleResponses", "IdentitySource", "IdentityValidationExpression", "JwtConfiguration", "Name"},
			"update-deployment":                    {"ApiId", "DeploymentId", "Description"},
			"update-domain-name":                   {"DomainName", "DomainNameConfigurations", "MutualTlsAuthentication", "RoutingMode"},
			"update-integration":                   {"ApiId", "ConnectionId", "ConnectionType", "ContentHandlingStrategy", "CredentialsArn", "Description", "IntegrationId", "IntegrationMethod", "IntegrationSubtype", "IntegrationType", "IntegrationUri", "PassthroughBehavior", "PayloadFormatVersion", "RequestParameters", "RequestTemplates", "ResponseParameters", "TemplateSelectionExpression", "TimeoutInMillis", "TlsConfig"},
			"update-integration-response":          {"ApiId", "ContentHandlingStrategy", "IntegrationId", "IntegrationResponseId", "IntegrationResponseKey", "ResponseParameters", "ResponseTemplates", "TemplateSelectionExpression"},
			"update-model":                         {"ApiId", "ContentType", "Description", "ModelId", "Name", "Schema"},
			"update-portal":                        {"Authorization", "EndpointConfiguration", "IncludedPortalProductArns", "LogoUri", "PortalContent", "PortalId", "RumAppMonitorName"},
			"update-portal-product":                {"Description", "DisplayName", "DisplayOrder", "PortalProductId"},
			"update-product-page":                  {"DisplayContent", "PortalProductId", "ProductPageId"},
			"update-product-rest-endpoint-page":    {"DisplayContent", "PortalProductId", "ProductRestEndpointPageId", "TryItState"},
			"update-route":                         {"ApiId", "ApiKeyRequired", "AuthorizationScopes", "AuthorizationType", "AuthorizerId", "ModelSelectionExpression", "OperationName", "RequestModels", "RequestParameters", "RouteId", "RouteKey", "RouteResponseSelectionExpression", "Target"},
			"update-route-response":                {"ApiId", "ModelSelectionExpression", "ResponseModels", "ResponseParameters", "RouteId", "RouteResponseId", "RouteResponseKey"},
			"update-stage":                         {"AccessLogSettings", "ApiId", "AutoDeploy", "ClientCertificateId", "DefaultRouteSettings", "DeploymentId", "Description", "RouteSettings", "StageName", "StageVariables"},
			"update-vpc-link":                      {"Name", "VpcLinkId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-api":                           {"ApiKeySelectionExpression": "*string", "CorsConfiguration": "*types.Cors", "CredentialsArn": "*string", "Description": "*string", "DisableExecuteApiEndpoint": "*bool", "DisableSchemaValidation": "*bool", "IpAddressType": "types.IpAddressType", "Name": "*string", "ProtocolType": "types.ProtocolType", "RouteKey": "*string", "RouteSelectionExpression": "*string", "Tags": "map[string]string", "Target": "*string", "Version": "*string"},
			"create-api-mapping":                   {"ApiId": "*string", "ApiMappingKey": "*string", "DomainName": "*string", "Stage": "*string"},
			"create-authorizer":                    {"ApiId": "*string", "AuthorizerCredentialsArn": "*string", "AuthorizerPayloadFormatVersion": "*string", "AuthorizerResultTtlInSeconds": "*int32", "AuthorizerType": "types.AuthorizerType", "AuthorizerUri": "*string", "EnableSimpleResponses": "*bool", "IdentitySource": "[]string", "IdentityValidationExpression": "*string", "JwtConfiguration": "*types.JWTConfiguration", "Name": "*string"},
			"create-deployment":                    {"ApiId": "*string", "Description": "*string", "StageName": "*string"},
			"create-domain-name":                   {"DomainName": "*string", "DomainNameConfigurations": "[]types.DomainNameConfiguration", "MutualTlsAuthentication": "*types.MutualTlsAuthenticationInput", "RoutingMode": "types.RoutingMode", "Tags": "map[string]string"},
			"create-integration":                   {"ApiId": "*string", "ConnectionId": "*string", "ConnectionType": "types.ConnectionType", "ContentHandlingStrategy": "types.ContentHandlingStrategy", "CredentialsArn": "*string", "Description": "*string", "IntegrationMethod": "*string", "IntegrationSubtype": "*string", "IntegrationType": "types.IntegrationType", "IntegrationUri": "*string", "PassthroughBehavior": "types.PassthroughBehavior", "PayloadFormatVersion": "*string", "RequestParameters": "map[string]string", "RequestTemplates": "map[string]string", "ResponseParameters": "map[string]map[string]string", "TemplateSelectionExpression": "*string", "TimeoutInMillis": "*int32", "TlsConfig": "*types.TlsConfigInput"},
			"create-integration-response":          {"ApiId": "*string", "ContentHandlingStrategy": "types.ContentHandlingStrategy", "IntegrationId": "*string", "IntegrationResponseKey": "*string", "ResponseParameters": "map[string]string", "ResponseTemplates": "map[string]string", "TemplateSelectionExpression": "*string"},
			"create-model":                         {"ApiId": "*string", "ContentType": "*string", "Description": "*string", "Name": "*string", "Schema": "*string"},
			"create-portal":                        {"Authorization": "*types.Authorization", "EndpointConfiguration": "*types.EndpointConfigurationRequest", "IncludedPortalProductArns": "[]string", "LogoUri": "*string", "PortalContent": "*types.PortalContent", "RumAppMonitorName": "*string", "Tags": "map[string]string"},
			"create-portal-product":                {"Description": "*string", "DisplayName": "*string", "Tags": "map[string]string"},
			"create-product-page":                  {"DisplayContent": "*types.DisplayContent", "PortalProductId": "*string"},
			"create-product-rest-endpoint-page":    {"DisplayContent": "*types.EndpointDisplayContent", "PortalProductId": "*string", "RestEndpointIdentifier": "*types.RestEndpointIdentifier", "TryItState": "types.TryItState"},
			"create-route":                         {"ApiId": "*string", "ApiKeyRequired": "*bool", "AuthorizationScopes": "[]string", "AuthorizationType": "types.AuthorizationType", "AuthorizerId": "*string", "ModelSelectionExpression": "*string", "OperationName": "*string", "RequestModels": "map[string]string", "RequestParameters": "map[string]types.ParameterConstraints", "RouteKey": "*string", "RouteResponseSelectionExpression": "*string", "Target": "*string"},
			"create-route-response":                {"ApiId": "*string", "ModelSelectionExpression": "*string", "ResponseModels": "map[string]string", "ResponseParameters": "map[string]types.ParameterConstraints", "RouteId": "*string", "RouteResponseKey": "*string"},
			"create-routing-rule":                  {"Actions": "[]types.RoutingRuleAction", "Conditions": "[]types.RoutingRuleCondition", "DomainName": "*string", "DomainNameId": "*string", "Priority": "*int32"},
			"create-stage":                         {"AccessLogSettings": "*types.AccessLogSettings", "ApiId": "*string", "AutoDeploy": "*bool", "ClientCertificateId": "*string", "DefaultRouteSettings": "*types.RouteSettings", "DeploymentId": "*string", "Description": "*string", "RouteSettings": "map[string]types.RouteSettings", "StageName": "*string", "StageVariables": "map[string]string", "Tags": "map[string]string"},
			"create-vpc-link":                      {"Name": "*string", "SecurityGroupIds": "[]string", "SubnetIds": "[]string", "Tags": "map[string]string"},
			"delete-access-log-settings":           {"ApiId": "*string", "StageName": "*string"},
			"delete-api":                           {"ApiId": "*string"},
			"delete-api-mapping":                   {"ApiMappingId": "*string", "DomainName": "*string"},
			"delete-authorizer":                    {"ApiId": "*string", "AuthorizerId": "*string"},
			"delete-cors-configuration":            {"ApiId": "*string"},
			"delete-deployment":                    {"ApiId": "*string", "DeploymentId": "*string"},
			"delete-domain-name":                   {"DomainName": "*string"},
			"delete-integration":                   {"ApiId": "*string", "IntegrationId": "*string"},
			"delete-integration-response":          {"ApiId": "*string", "IntegrationId": "*string", "IntegrationResponseId": "*string"},
			"delete-model":                         {"ApiId": "*string", "ModelId": "*string"},
			"delete-portal":                        {"PortalId": "*string"},
			"delete-portal-product":                {"PortalProductId": "*string"},
			"delete-portal-product-sharing-policy": {"PortalProductId": "*string"},
			"delete-product-page":                  {"PortalProductId": "*string", "ProductPageId": "*string"},
			"delete-product-rest-endpoint-page":    {"PortalProductId": "*string", "ProductRestEndpointPageId": "*string"},
			"delete-route":                         {"ApiId": "*string", "RouteId": "*string"},
			"delete-route-request-parameter":       {"ApiId": "*string", "RequestParameterKey": "*string", "RouteId": "*string"},
			"delete-route-response":                {"ApiId": "*string", "RouteId": "*string", "RouteResponseId": "*string"},
			"delete-route-settings":                {"ApiId": "*string", "RouteKey": "*string", "StageName": "*string"},
			"delete-routing-rule":                  {"DomainName": "*string", "DomainNameId": "*string", "RoutingRuleId": "*string"},
			"delete-stage":                         {"ApiId": "*string", "StageName": "*string"},
			"delete-vpc-link":                      {"VpcLinkId": "*string"},
			"disable-portal":                       {"PortalId": "*string"},
			"export-api":                           {"ApiId": "*string", "ExportVersion": "*string", "IncludeExtensions": "*bool", "OutputType": "*string", "Specification": "*string", "StageName": "*string"},
			"get-api":                              {"ApiId": "*string"},
			"get-api-mapping":                      {"ApiMappingId": "*string", "DomainName": "*string"},
			"get-api-mappings":                     {"DomainName": "*string", "MaxResults": "*string", "NextToken": "*string"},
			"get-apis":                             {"MaxResults": "*string", "NextToken": "*string"},
			"get-authorizer":                       {"ApiId": "*string", "AuthorizerId": "*string"},
			"get-authorizers":                      {"ApiId": "*string", "MaxResults": "*string", "NextToken": "*string"},
			"get-deployment":                       {"ApiId": "*string", "DeploymentId": "*string"},
			"get-deployments":                      {"ApiId": "*string", "MaxResults": "*string", "NextToken": "*string"},
			"get-domain-name":                      {"DomainName": "*string"},
			"get-domain-names":                     {"MaxResults": "*string", "NextToken": "*string"},
			"get-integration":                      {"ApiId": "*string", "IntegrationId": "*string"},
			"get-integration-response":             {"ApiId": "*string", "IntegrationId": "*string", "IntegrationResponseId": "*string"},
			"get-integration-responses":            {"ApiId": "*string", "IntegrationId": "*string", "MaxResults": "*string", "NextToken": "*string"},
			"get-integrations":                     {"ApiId": "*string", "MaxResults": "*string", "NextToken": "*string"},
			"get-model":                            {"ApiId": "*string", "ModelId": "*string"},
			"get-model-template":                   {"ApiId": "*string", "ModelId": "*string"},
			"get-models":                           {"ApiId": "*string", "MaxResults": "*string", "NextToken": "*string"},
			"get-portal":                           {"PortalId": "*string"},
			"get-portal-product":                   {"PortalProductId": "*string", "ResourceOwnerAccountId": "*string"},
			"get-portal-product-sharing-policy":    {"PortalProductId": "*string"},
			"get-product-page":                     {"PortalProductId": "*string", "ProductPageId": "*string", "ResourceOwnerAccountId": "*string"},
			"get-product-rest-endpoint-page":       {"IncludeRawDisplayContent": "*string", "PortalProductId": "*string", "ProductRestEndpointPageId": "*string", "ResourceOwnerAccountId": "*string"},
			"get-route":                            {"ApiId": "*string", "RouteId": "*string"},
			"get-route-response":                   {"ApiId": "*string", "RouteId": "*string", "RouteResponseId": "*string"},
			"get-route-responses":                  {"ApiId": "*string", "MaxResults": "*string", "NextToken": "*string", "RouteId": "*string"},
			"get-routes":                           {"ApiId": "*string", "MaxResults": "*string", "NextToken": "*string"},
			"get-routing-rule":                     {"DomainName": "*string", "DomainNameId": "*string", "RoutingRuleId": "*string"},
			"get-stage":                            {"ApiId": "*string", "StageName": "*string"},
			"get-stages":                           {"ApiId": "*string", "MaxResults": "*string", "NextToken": "*string"},
			"get-tags":                             {"ResourceArn": "*string"},
			"get-vpc-link":                         {"VpcLinkId": "*string"},
			"get-vpc-links":                        {"MaxResults": "*string", "NextToken": "*string"},
			"import-api":                           {"Basepath": "*string", "Body": "*string", "FailOnWarnings": "*bool"},
			"list-portal-products":                 {"MaxResults": "*string", "NextToken": "*string", "ResourceOwner": "*string"},
			"list-portals":                         {"MaxResults": "*string", "NextToken": "*string"},
			"list-product-pages":                   {"MaxResults": "*string", "NextToken": "*string", "PortalProductId": "*string", "ResourceOwnerAccountId": "*string"},
			"list-product-rest-endpoint-pages":     {"MaxResults": "*string", "NextToken": "*string", "PortalProductId": "*string", "ResourceOwnerAccountId": "*string"},
			"list-routing-rules":                   {"DomainName": "*string", "DomainNameId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"preview-portal":                       {"PortalId": "*string"},
			"publish-portal":                       {"Description": "*string", "PortalId": "*string"},
			"put-portal-product-sharing-policy":    {"PolicyDocument": "*string", "PortalProductId": "*string"},
			"put-routing-rule":                     {"Actions": "[]types.RoutingRuleAction", "Conditions": "[]types.RoutingRuleCondition", "DomainName": "*string", "DomainNameId": "*string", "Priority": "*int32", "RoutingRuleId": "*string"},
			"reimport-api":                         {"ApiId": "*string", "Basepath": "*string", "Body": "*string", "FailOnWarnings": "*bool"},
			"reset-authorizers-cache":              {"ApiId": "*string", "StageName": "*string"},
			"tag-resource":                         {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                       {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-api":                           {"ApiId": "*string", "ApiKeySelectionExpression": "*string", "CorsConfiguration": "*types.Cors", "CredentialsArn": "*string", "Description": "*string", "DisableExecuteApiEndpoint": "*bool", "DisableSchemaValidation": "*bool", "IpAddressType": "types.IpAddressType", "Name": "*string", "RouteKey": "*string", "RouteSelectionExpression": "*string", "Target": "*string", "Version": "*string"},
			"update-api-mapping":                   {"ApiId": "*string", "ApiMappingId": "*string", "ApiMappingKey": "*string", "DomainName": "*string", "Stage": "*string"},
			"update-authorizer":                    {"ApiId": "*string", "AuthorizerCredentialsArn": "*string", "AuthorizerId": "*string", "AuthorizerPayloadFormatVersion": "*string", "AuthorizerResultTtlInSeconds": "*int32", "AuthorizerType": "types.AuthorizerType", "AuthorizerUri": "*string", "EnableSimpleResponses": "*bool", "IdentitySource": "[]string", "IdentityValidationExpression": "*string", "JwtConfiguration": "*types.JWTConfiguration", "Name": "*string"},
			"update-deployment":                    {"ApiId": "*string", "DeploymentId": "*string", "Description": "*string"},
			"update-domain-name":                   {"DomainName": "*string", "DomainNameConfigurations": "[]types.DomainNameConfiguration", "MutualTlsAuthentication": "*types.MutualTlsAuthenticationInput", "RoutingMode": "types.RoutingMode"},
			"update-integration":                   {"ApiId": "*string", "ConnectionId": "*string", "ConnectionType": "types.ConnectionType", "ContentHandlingStrategy": "types.ContentHandlingStrategy", "CredentialsArn": "*string", "Description": "*string", "IntegrationId": "*string", "IntegrationMethod": "*string", "IntegrationSubtype": "*string", "IntegrationType": "types.IntegrationType", "IntegrationUri": "*string", "PassthroughBehavior": "types.PassthroughBehavior", "PayloadFormatVersion": "*string", "RequestParameters": "map[string]string", "RequestTemplates": "map[string]string", "ResponseParameters": "map[string]map[string]string", "TemplateSelectionExpression": "*string", "TimeoutInMillis": "*int32", "TlsConfig": "*types.TlsConfigInput"},
			"update-integration-response":          {"ApiId": "*string", "ContentHandlingStrategy": "types.ContentHandlingStrategy", "IntegrationId": "*string", "IntegrationResponseId": "*string", "IntegrationResponseKey": "*string", "ResponseParameters": "map[string]string", "ResponseTemplates": "map[string]string", "TemplateSelectionExpression": "*string"},
			"update-model":                         {"ApiId": "*string", "ContentType": "*string", "Description": "*string", "ModelId": "*string", "Name": "*string", "Schema": "*string"},
			"update-portal":                        {"Authorization": "*types.Authorization", "EndpointConfiguration": "*types.EndpointConfigurationRequest", "IncludedPortalProductArns": "[]string", "LogoUri": "*string", "PortalContent": "*types.PortalContent", "PortalId": "*string", "RumAppMonitorName": "*string"},
			"update-portal-product":                {"Description": "*string", "DisplayName": "*string", "DisplayOrder": "*types.DisplayOrder", "PortalProductId": "*string"},
			"update-product-page":                  {"DisplayContent": "*types.DisplayContent", "PortalProductId": "*string", "ProductPageId": "*string"},
			"update-product-rest-endpoint-page":    {"DisplayContent": "*types.EndpointDisplayContent", "PortalProductId": "*string", "ProductRestEndpointPageId": "*string", "TryItState": "types.TryItState"},
			"update-route":                         {"ApiId": "*string", "ApiKeyRequired": "*bool", "AuthorizationScopes": "[]string", "AuthorizationType": "types.AuthorizationType", "AuthorizerId": "*string", "ModelSelectionExpression": "*string", "OperationName": "*string", "RequestModels": "map[string]string", "RequestParameters": "map[string]types.ParameterConstraints", "RouteId": "*string", "RouteKey": "*string", "RouteResponseSelectionExpression": "*string", "Target": "*string"},
			"update-route-response":                {"ApiId": "*string", "ModelSelectionExpression": "*string", "ResponseModels": "map[string]string", "ResponseParameters": "map[string]types.ParameterConstraints", "RouteId": "*string", "RouteResponseId": "*string", "RouteResponseKey": "*string"},
			"update-stage":                         {"AccessLogSettings": "*types.AccessLogSettings", "ApiId": "*string", "AutoDeploy": "*bool", "ClientCertificateId": "*string", "DefaultRouteSettings": "*types.RouteSettings", "DeploymentId": "*string", "Description": "*string", "RouteSettings": "map[string]types.RouteSettings", "StageName": "*string", "StageVariables": "map[string]string"},
			"update-vpc-link":                      {"Name": "*string", "VpcLinkId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-api":                           {"Name", "ProtocolType"},
			"create-api-mapping":                   {"ApiId", "DomainName", "Stage"},
			"create-authorizer":                    {"ApiId", "AuthorizerType", "IdentitySource", "Name"},
			"create-deployment":                    {"ApiId"},
			"create-domain-name":                   {"DomainName"},
			"create-integration":                   {"ApiId", "IntegrationType"},
			"create-integration-response":          {"ApiId", "IntegrationId", "IntegrationResponseKey"},
			"create-model":                         {"ApiId", "Name", "Schema"},
			"create-portal":                        {"Authorization", "EndpointConfiguration", "PortalContent"},
			"create-portal-product":                {"DisplayName"},
			"create-product-page":                  {"DisplayContent", "PortalProductId"},
			"create-product-rest-endpoint-page":    {"PortalProductId", "RestEndpointIdentifier"},
			"create-route":                         {"ApiId", "RouteKey"},
			"create-route-response":                {"ApiId", "RouteId", "RouteResponseKey"},
			"create-routing-rule":                  {"Actions", "Conditions", "DomainName", "Priority"},
			"create-stage":                         {"ApiId", "StageName"},
			"create-vpc-link":                      {"Name", "SubnetIds"},
			"delete-access-log-settings":           {"ApiId", "StageName"},
			"delete-api":                           {"ApiId"},
			"delete-api-mapping":                   {"ApiMappingId", "DomainName"},
			"delete-authorizer":                    {"ApiId", "AuthorizerId"},
			"delete-cors-configuration":            {"ApiId"},
			"delete-deployment":                    {"ApiId", "DeploymentId"},
			"delete-domain-name":                   {"DomainName"},
			"delete-integration":                   {"ApiId", "IntegrationId"},
			"delete-integration-response":          {"ApiId", "IntegrationId", "IntegrationResponseId"},
			"delete-model":                         {"ApiId", "ModelId"},
			"delete-portal":                        {"PortalId"},
			"delete-portal-product":                {"PortalProductId"},
			"delete-portal-product-sharing-policy": {"PortalProductId"},
			"delete-product-page":                  {"PortalProductId", "ProductPageId"},
			"delete-product-rest-endpoint-page":    {"PortalProductId", "ProductRestEndpointPageId"},
			"delete-route":                         {"ApiId", "RouteId"},
			"delete-route-request-parameter":       {"ApiId", "RequestParameterKey", "RouteId"},
			"delete-route-response":                {"ApiId", "RouteId", "RouteResponseId"},
			"delete-route-settings":                {"ApiId", "RouteKey", "StageName"},
			"delete-routing-rule":                  {"DomainName", "RoutingRuleId"},
			"delete-stage":                         {"ApiId", "StageName"},
			"delete-vpc-link":                      {"VpcLinkId"},
			"disable-portal":                       {"PortalId"},
			"export-api":                           {"ApiId", "OutputType", "Specification"},
			"get-api":                              {"ApiId"},
			"get-api-mapping":                      {"ApiMappingId", "DomainName"},
			"get-api-mappings":                     {"DomainName"},
			"get-apis":                             {},
			"get-authorizer":                       {"ApiId", "AuthorizerId"},
			"get-authorizers":                      {"ApiId"},
			"get-deployment":                       {"ApiId", "DeploymentId"},
			"get-deployments":                      {"ApiId"},
			"get-domain-name":                      {"DomainName"},
			"get-domain-names":                     {},
			"get-integration":                      {"ApiId", "IntegrationId"},
			"get-integration-response":             {"ApiId", "IntegrationId", "IntegrationResponseId"},
			"get-integration-responses":            {"ApiId", "IntegrationId"},
			"get-integrations":                     {"ApiId"},
			"get-model":                            {"ApiId", "ModelId"},
			"get-model-template":                   {"ApiId", "ModelId"},
			"get-models":                           {"ApiId"},
			"get-portal":                           {"PortalId"},
			"get-portal-product":                   {"PortalProductId"},
			"get-portal-product-sharing-policy":    {"PortalProductId"},
			"get-product-page":                     {"PortalProductId", "ProductPageId"},
			"get-product-rest-endpoint-page":       {"PortalProductId", "ProductRestEndpointPageId"},
			"get-route":                            {"ApiId", "RouteId"},
			"get-route-response":                   {"ApiId", "RouteId", "RouteResponseId"},
			"get-route-responses":                  {"ApiId", "RouteId"},
			"get-routes":                           {"ApiId"},
			"get-routing-rule":                     {"DomainName", "RoutingRuleId"},
			"get-stage":                            {"ApiId", "StageName"},
			"get-stages":                           {"ApiId"},
			"get-tags":                             {"ResourceArn"},
			"get-vpc-link":                         {"VpcLinkId"},
			"get-vpc-links":                        {},
			"import-api":                           {"Body"},
			"list-portal-products":                 {},
			"list-portals":                         {},
			"list-product-pages":                   {"PortalProductId"},
			"list-product-rest-endpoint-pages":     {"PortalProductId"},
			"list-routing-rules":                   {"DomainName"},
			"preview-portal":                       {"PortalId"},
			"publish-portal":                       {"PortalId"},
			"put-portal-product-sharing-policy":    {"PolicyDocument", "PortalProductId"},
			"put-routing-rule":                     {"Actions", "Conditions", "DomainName", "Priority", "RoutingRuleId"},
			"reimport-api":                         {"ApiId", "Body"},
			"reset-authorizers-cache":              {"ApiId", "StageName"},
			"tag-resource":                         {"ResourceArn"},
			"untag-resource":                       {"ResourceArn", "TagKeys"},
			"update-api":                           {"ApiId"},
			"update-api-mapping":                   {"ApiId", "ApiMappingId", "DomainName"},
			"update-authorizer":                    {"ApiId", "AuthorizerId"},
			"update-deployment":                    {"ApiId", "DeploymentId"},
			"update-domain-name":                   {"DomainName"},
			"update-integration":                   {"ApiId", "IntegrationId"},
			"update-integration-response":          {"ApiId", "IntegrationId", "IntegrationResponseId"},
			"update-model":                         {"ApiId", "ModelId"},
			"update-portal":                        {"PortalId"},
			"update-portal-product":                {"PortalProductId"},
			"update-product-page":                  {"PortalProductId", "ProductPageId"},
			"update-product-rest-endpoint-page":    {"PortalProductId", "ProductRestEndpointPageId"},
			"update-route":                         {"ApiId", "RouteId"},
			"update-route-response":                {"ApiId", "RouteId", "RouteResponseId"},
			"update-stage":                         {"ApiId", "StageName"},
			"update-vpc-link":                      {"VpcLinkId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("apigatewayv2", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
