package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/lakeformation/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-lf-tags-to-resource", "assume-decorated-role-with-saml", "batch-grant-permissions", "batch-revoke-permissions", "cancel-transaction", "commit-transaction", "create-data-cells-filter", "create-lake-formation-identity-center-configuration", "create-lake-formation-opt-in", "create-lf-tag", "create-lf-tag-expression", "delete-data-cells-filter", "delete-lake-formation-identity-center-configuration", "delete-lake-formation-opt-in", "delete-lf-tag", "delete-lf-tag-expression", "delete-objects-on-cancel", "deregister-resource", "describe-lake-formation-identity-center-configuration", "describe-resource", "describe-transaction", "extend-transaction", "get-data-cells-filter", "get-data-lake-principal", "get-data-lake-settings", "get-effective-permissions-for-path", "get-lf-tag", "get-lf-tag-expression", "get-query-state", "get-query-statistics", "get-resource-lf-tags", "get-table-objects", "get-temporary-data-location-credentials", "get-temporary-glue-partition-credentials", "get-temporary-glue-table-credentials", "get-work-unit-results", "get-work-units", "grant-permissions", "list-data-cells-filter", "list-lake-formation-opt-ins", "list-lf-tag-expressions", "list-lf-tags", "list-permissions", "list-resources", "list-table-storage-optimizers", "list-transactions", "put-data-lake-settings", "register-resource", "remove-lf-tags-from-resource", "revoke-permissions", "search-databases-by-lf-tags", "search-tables-by-lf-tags", "start-query-planning", "start-transaction", "update-data-cells-filter", "update-lake-formation-identity-center-configuration", "update-lf-tag", "update-lf-tag-expression", "update-resource", "update-table-objects", "update-table-storage-optimizer"},
		OperationSet: map[string]bool{"add-lf-tags-to-resource": true, "assume-decorated-role-with-saml": true, "batch-grant-permissions": true, "batch-revoke-permissions": true, "cancel-transaction": true, "commit-transaction": true, "create-data-cells-filter": true, "create-lake-formation-identity-center-configuration": true, "create-lake-formation-opt-in": true, "create-lf-tag": true, "create-lf-tag-expression": true, "delete-data-cells-filter": true, "delete-lake-formation-identity-center-configuration": true, "delete-lake-formation-opt-in": true, "delete-lf-tag": true, "delete-lf-tag-expression": true, "delete-objects-on-cancel": true, "deregister-resource": true, "describe-lake-formation-identity-center-configuration": true, "describe-resource": true, "describe-transaction": true, "extend-transaction": true, "get-data-cells-filter": true, "get-data-lake-principal": true, "get-data-lake-settings": true, "get-effective-permissions-for-path": true, "get-lf-tag": true, "get-lf-tag-expression": true, "get-query-state": true, "get-query-statistics": true, "get-resource-lf-tags": true, "get-table-objects": true, "get-temporary-data-location-credentials": true, "get-temporary-glue-partition-credentials": true, "get-temporary-glue-table-credentials": true, "get-work-unit-results": true, "get-work-units": true, "grant-permissions": true, "list-data-cells-filter": true, "list-lake-formation-opt-ins": true, "list-lf-tag-expressions": true, "list-lf-tags": true, "list-permissions": true, "list-resources": true, "list-table-storage-optimizers": true, "list-transactions": true, "put-data-lake-settings": true, "register-resource": true, "remove-lf-tags-from-resource": true, "revoke-permissions": true, "search-databases-by-lf-tags": true, "search-tables-by-lf-tags": true, "start-query-planning": true, "start-transaction": true, "update-data-cells-filter": true, "update-lake-formation-identity-center-configuration": true, "update-lf-tag": true, "update-lf-tag-expression": true, "update-resource": true, "update-table-objects": true, "update-table-storage-optimizer": true},
		OperationInputs: map[string][]string{
			"add-lf-tags-to-resource":                               {"CatalogId", "LFTags", "Resource"},
			"assume-decorated-role-with-saml":                       {"DurationSeconds", "PrincipalArn", "RoleArn", "SAMLAssertion"},
			"batch-grant-permissions":                               {"CatalogId", "Entries"},
			"batch-revoke-permissions":                              {"CatalogId", "Entries"},
			"cancel-transaction":                                    {"TransactionId"},
			"commit-transaction":                                    {"TransactionId"},
			"create-data-cells-filter":                              {"TableData"},
			"create-lake-formation-identity-center-configuration":   {"CatalogId", "ExternalFiltering", "InstanceArn", "ServiceIntegrations", "ShareRecipients"},
			"create-lake-formation-opt-in":                          {"Condition", "Principal", "Resource"},
			"create-lf-tag":                                         {"CatalogId", "TagKey", "TagValues"},
			"create-lf-tag-expression":                              {"CatalogId", "Description", "Expression", "Name"},
			"delete-data-cells-filter":                              {"DatabaseName", "Name", "TableCatalogId", "TableName"},
			"delete-lake-formation-identity-center-configuration":   {"CatalogId"},
			"delete-lake-formation-opt-in":                          {"Condition", "Principal", "Resource"},
			"delete-lf-tag":                                         {"CatalogId", "TagKey"},
			"delete-lf-tag-expression":                              {"CatalogId", "Name"},
			"delete-objects-on-cancel":                              {"CatalogId", "DatabaseName", "Objects", "TableName", "TransactionId"},
			"deregister-resource":                                   {"ResourceArn"},
			"describe-lake-formation-identity-center-configuration": {"CatalogId"},
			"describe-resource":                                     {"ResourceArn"},
			"describe-transaction":                                  {"TransactionId"},
			"extend-transaction":                                    {"TransactionId"},
			"get-data-cells-filter":                                 {"DatabaseName", "Name", "TableCatalogId", "TableName"},
			"get-data-lake-principal":                               {},
			"get-data-lake-settings":                                {"CatalogId"},
			"get-effective-permissions-for-path":                    {"CatalogId", "MaxResults", "NextToken", "ResourceArn"},
			"get-lf-tag":                                            {"CatalogId", "TagKey"},
			"get-lf-tag-expression":                                 {"CatalogId", "Name"},
			"get-query-state":                                       {"QueryId"},
			"get-query-statistics":                                  {"QueryId"},
			"get-resource-lf-tags":                                  {"CatalogId", "Resource", "ShowAssignedLFTags"},
			"get-table-objects":                                     {"CatalogId", "DatabaseName", "MaxResults", "NextToken", "PartitionPredicate", "QueryAsOfTime", "TableName", "TransactionId"},
			"get-temporary-data-location-credentials":               {"AuditContext", "CredentialsScope", "DataLocations", "DurationSeconds"},
			"get-temporary-glue-partition-credentials":              {"AuditContext", "DurationSeconds", "Partition", "Permissions", "SupportedPermissionTypes", "TableArn"},
			"get-temporary-glue-table-credentials":                  {"AuditContext", "DurationSeconds", "Permissions", "QuerySessionContext", "S3Path", "SupportedPermissionTypes", "TableArn"},
			"get-work-unit-results":                                 {"QueryId", "WorkUnitId", "WorkUnitToken"},
			"get-work-units":                                        {"NextToken", "PageSize", "QueryId"},
			"grant-permissions":                                     {"CatalogId", "Condition", "Permissions", "PermissionsWithGrantOption", "Principal", "Resource"},
			"list-data-cells-filter":                                {"MaxResults", "NextToken", "Table"},
			"list-lake-formation-opt-ins":                           {"MaxResults", "NextToken", "Principal", "Resource"},
			"list-lf-tag-expressions":                               {"CatalogId", "MaxResults", "NextToken"},
			"list-lf-tags":                                          {"CatalogId", "MaxResults", "NextToken", "ResourceShareType"},
			"list-permissions":                                      {"CatalogId", "IncludeRelated", "MaxResults", "NextToken", "Principal", "Resource", "ResourceType"},
			"list-resources":                                        {"FilterConditionList", "MaxResults", "NextToken"},
			"list-table-storage-optimizers":                         {"CatalogId", "DatabaseName", "MaxResults", "NextToken", "StorageOptimizerType", "TableName"},
			"list-transactions":                                     {"CatalogId", "MaxResults", "NextToken", "StatusFilter"},
			"put-data-lake-settings":                                {"CatalogId", "DataLakeSettings"},
			"register-resource":                                     {"ExpectedResourceOwnerAccount", "HybridAccessEnabled", "ResourceArn", "RoleArn", "UseServiceLinkedRole", "WithFederation", "WithPrivilegedAccess"},
			"remove-lf-tags-from-resource":                          {"CatalogId", "LFTags", "Resource"},
			"revoke-permissions":                                    {"CatalogId", "Condition", "Permissions", "PermissionsWithGrantOption", "Principal", "Resource"},
			"search-databases-by-lf-tags":                           {"CatalogId", "Expression", "MaxResults", "NextToken"},
			"search-tables-by-lf-tags":                              {"CatalogId", "Expression", "MaxResults", "NextToken"},
			"start-query-planning":                                  {"QueryPlanningContext", "QueryString"},
			"start-transaction":                                     {"TransactionType"},
			"update-data-cells-filter":                              {"TableData"},
			"update-lake-formation-identity-center-configuration":   {"ApplicationStatus", "CatalogId", "ExternalFiltering", "ServiceIntegrations", "ShareRecipients"},
			"update-lf-tag":                                         {"CatalogId", "TagKey", "TagValuesToAdd", "TagValuesToDelete"},
			"update-lf-tag-expression":                              {"CatalogId", "Description", "Expression", "Name"},
			"update-resource":                                       {"ExpectedResourceOwnerAccount", "HybridAccessEnabled", "ResourceArn", "RoleArn", "WithFederation"},
			"update-table-objects":                                  {"CatalogId", "DatabaseName", "TableName", "TransactionId", "WriteOperations"},
			"update-table-storage-optimizer":                        {"CatalogId", "DatabaseName", "StorageOptimizerConfig", "TableName"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-lf-tags-to-resource":                               {"CatalogId": "*string", "LFTags": "[]types.LFTagPair", "Resource": "*types.Resource"},
			"assume-decorated-role-with-saml":                       {"DurationSeconds": "*int32", "PrincipalArn": "*string", "RoleArn": "*string", "SAMLAssertion": "*string"},
			"batch-grant-permissions":                               {"CatalogId": "*string", "Entries": "[]types.BatchPermissionsRequestEntry"},
			"batch-revoke-permissions":                              {"CatalogId": "*string", "Entries": "[]types.BatchPermissionsRequestEntry"},
			"cancel-transaction":                                    {"TransactionId": "*string"},
			"commit-transaction":                                    {"TransactionId": "*string"},
			"create-data-cells-filter":                              {"TableData": "*types.DataCellsFilter"},
			"create-lake-formation-identity-center-configuration":   {"CatalogId": "*string", "ExternalFiltering": "*types.ExternalFilteringConfiguration", "InstanceArn": "*string", "ServiceIntegrations": "[]types.ServiceIntegrationUnion", "ShareRecipients": "[]types.DataLakePrincipal"},
			"create-lake-formation-opt-in":                          {"Condition": "*types.Condition", "Principal": "*types.DataLakePrincipal", "Resource": "*types.Resource"},
			"create-lf-tag":                                         {"CatalogId": "*string", "TagKey": "*string", "TagValues": "[]string"},
			"create-lf-tag-expression":                              {"CatalogId": "*string", "Description": "*string", "Expression": "[]types.LFTag", "Name": "*string"},
			"delete-data-cells-filter":                              {"DatabaseName": "*string", "Name": "*string", "TableCatalogId": "*string", "TableName": "*string"},
			"delete-lake-formation-identity-center-configuration":   {"CatalogId": "*string"},
			"delete-lake-formation-opt-in":                          {"Condition": "*types.Condition", "Principal": "*types.DataLakePrincipal", "Resource": "*types.Resource"},
			"delete-lf-tag":                                         {"CatalogId": "*string", "TagKey": "*string"},
			"delete-lf-tag-expression":                              {"CatalogId": "*string", "Name": "*string"},
			"delete-objects-on-cancel":                              {"CatalogId": "*string", "DatabaseName": "*string", "Objects": "[]types.VirtualObject", "TableName": "*string", "TransactionId": "*string"},
			"deregister-resource":                                   {"ResourceArn": "*string"},
			"describe-lake-formation-identity-center-configuration": {"CatalogId": "*string"},
			"describe-resource":                                     {"ResourceArn": "*string"},
			"describe-transaction":                                  {"TransactionId": "*string"},
			"extend-transaction":                                    {"TransactionId": "*string"},
			"get-data-cells-filter":                                 {"DatabaseName": "*string", "Name": "*string", "TableCatalogId": "*string", "TableName": "*string"},
			"get-data-lake-principal":                               {},
			"get-data-lake-settings":                                {"CatalogId": "*string"},
			"get-effective-permissions-for-path":                    {"CatalogId": "*string", "MaxResults": "*int32", "NextToken": "*string", "ResourceArn": "*string"},
			"get-lf-tag":                                            {"CatalogId": "*string", "TagKey": "*string"},
			"get-lf-tag-expression":                                 {"CatalogId": "*string", "Name": "*string"},
			"get-query-state":                                       {"QueryId": "*string"},
			"get-query-statistics":                                  {"QueryId": "*string"},
			"get-resource-lf-tags":                                  {"CatalogId": "*string", "Resource": "*types.Resource", "ShowAssignedLFTags": "*bool"},
			"get-table-objects":                                     {"CatalogId": "*string", "DatabaseName": "*string", "MaxResults": "*int32", "NextToken": "*string", "PartitionPredicate": "*string", "QueryAsOfTime": "*time.Time", "TableName": "*string", "TransactionId": "*string"},
			"get-temporary-data-location-credentials":               {"AuditContext": "*types.AuditContext", "CredentialsScope": "types.CredentialsScope", "DataLocations": "[]string", "DurationSeconds": "*int32"},
			"get-temporary-glue-partition-credentials":              {"AuditContext": "*types.AuditContext", "DurationSeconds": "*int32", "Partition": "*types.PartitionValueList", "Permissions": "[]types.Permission", "SupportedPermissionTypes": "[]types.PermissionType", "TableArn": "*string"},
			"get-temporary-glue-table-credentials":                  {"AuditContext": "*types.AuditContext", "DurationSeconds": "*int32", "Permissions": "[]types.Permission", "QuerySessionContext": "*types.QuerySessionContext", "S3Path": "*string", "SupportedPermissionTypes": "[]types.PermissionType", "TableArn": "*string"},
			"get-work-unit-results":                                 {"QueryId": "*string", "WorkUnitId": "int64", "WorkUnitToken": "*string"},
			"get-work-units":                                        {"NextToken": "*string", "PageSize": "*int32", "QueryId": "*string"},
			"grant-permissions":                                     {"CatalogId": "*string", "Condition": "*types.Condition", "Permissions": "[]types.Permission", "PermissionsWithGrantOption": "[]types.Permission", "Principal": "*types.DataLakePrincipal", "Resource": "*types.Resource"},
			"list-data-cells-filter":                                {"MaxResults": "*int32", "NextToken": "*string", "Table": "*types.TableResource"},
			"list-lake-formation-opt-ins":                           {"MaxResults": "*int32", "NextToken": "*string", "Principal": "*types.DataLakePrincipal", "Resource": "*types.Resource"},
			"list-lf-tag-expressions":                               {"CatalogId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-lf-tags":                                          {"CatalogId": "*string", "MaxResults": "*int32", "NextToken": "*string", "ResourceShareType": "types.ResourceShareType"},
			"list-permissions":                                      {"CatalogId": "*string", "IncludeRelated": "*string", "MaxResults": "*int32", "NextToken": "*string", "Principal": "*types.DataLakePrincipal", "Resource": "*types.Resource", "ResourceType": "types.DataLakeResourceType"},
			"list-resources":                                        {"FilterConditionList": "[]types.FilterCondition", "MaxResults": "*int32", "NextToken": "*string"},
			"list-table-storage-optimizers":                         {"CatalogId": "*string", "DatabaseName": "*string", "MaxResults": "*int32", "NextToken": "*string", "StorageOptimizerType": "types.OptimizerType", "TableName": "*string"},
			"list-transactions":                                     {"CatalogId": "*string", "MaxResults": "*int32", "NextToken": "*string", "StatusFilter": "types.TransactionStatusFilter"},
			"put-data-lake-settings":                                {"CatalogId": "*string", "DataLakeSettings": "*types.DataLakeSettings"},
			"register-resource":                                     {"ExpectedResourceOwnerAccount": "*string", "HybridAccessEnabled": "*bool", "ResourceArn": "*string", "RoleArn": "*string", "UseServiceLinkedRole": "*bool", "WithFederation": "*bool", "WithPrivilegedAccess": "bool"},
			"remove-lf-tags-from-resource":                          {"CatalogId": "*string", "LFTags": "[]types.LFTagPair", "Resource": "*types.Resource"},
			"revoke-permissions":                                    {"CatalogId": "*string", "Condition": "*types.Condition", "Permissions": "[]types.Permission", "PermissionsWithGrantOption": "[]types.Permission", "Principal": "*types.DataLakePrincipal", "Resource": "*types.Resource"},
			"search-databases-by-lf-tags":                           {"CatalogId": "*string", "Expression": "[]types.LFTag", "MaxResults": "*int32", "NextToken": "*string"},
			"search-tables-by-lf-tags":                              {"CatalogId": "*string", "Expression": "[]types.LFTag", "MaxResults": "*int32", "NextToken": "*string"},
			"start-query-planning":                                  {"QueryPlanningContext": "*types.QueryPlanningContext", "QueryString": "*string"},
			"start-transaction":                                     {"TransactionType": "types.TransactionType"},
			"update-data-cells-filter":                              {"TableData": "*types.DataCellsFilter"},
			"update-lake-formation-identity-center-configuration":   {"ApplicationStatus": "types.ApplicationStatus", "CatalogId": "*string", "ExternalFiltering": "*types.ExternalFilteringConfiguration", "ServiceIntegrations": "[]types.ServiceIntegrationUnion", "ShareRecipients": "[]types.DataLakePrincipal"},
			"update-lf-tag":                                         {"CatalogId": "*string", "TagKey": "*string", "TagValuesToAdd": "[]string", "TagValuesToDelete": "[]string"},
			"update-lf-tag-expression":                              {"CatalogId": "*string", "Description": "*string", "Expression": "[]types.LFTag", "Name": "*string"},
			"update-resource":                                       {"ExpectedResourceOwnerAccount": "*string", "HybridAccessEnabled": "*bool", "ResourceArn": "*string", "RoleArn": "*string", "WithFederation": "*bool"},
			"update-table-objects":                                  {"CatalogId": "*string", "DatabaseName": "*string", "TableName": "*string", "TransactionId": "*string", "WriteOperations": "[]types.WriteOperation"},
			"update-table-storage-optimizer":                        {"CatalogId": "*string", "DatabaseName": "*string", "StorageOptimizerConfig": "map[string]map[string]string", "TableName": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"add-lf-tags-to-resource":                               {"LFTags", "Resource"},
			"assume-decorated-role-with-saml":                       {"PrincipalArn", "RoleArn", "SAMLAssertion"},
			"batch-grant-permissions":                               {"Entries"},
			"batch-revoke-permissions":                              {"Entries"},
			"cancel-transaction":                                    {"TransactionId"},
			"commit-transaction":                                    {"TransactionId"},
			"create-data-cells-filter":                              {"TableData"},
			"create-lake-formation-identity-center-configuration":   {},
			"create-lake-formation-opt-in":                          {"Principal", "Resource"},
			"create-lf-tag":                                         {"TagKey", "TagValues"},
			"create-lf-tag-expression":                              {"Expression", "Name"},
			"delete-data-cells-filter":                              {},
			"delete-lake-formation-identity-center-configuration":   {},
			"delete-lake-formation-opt-in":                          {"Principal", "Resource"},
			"delete-lf-tag":                                         {"TagKey"},
			"delete-lf-tag-expression":                              {"Name"},
			"delete-objects-on-cancel":                              {"DatabaseName", "Objects", "TableName", "TransactionId"},
			"deregister-resource":                                   {"ResourceArn"},
			"describe-lake-formation-identity-center-configuration": {},
			"describe-resource":                                     {"ResourceArn"},
			"describe-transaction":                                  {"TransactionId"},
			"extend-transaction":                                    {},
			"get-data-cells-filter":                                 {"DatabaseName", "Name", "TableCatalogId", "TableName"},
			"get-data-lake-principal":                               {},
			"get-data-lake-settings":                                {},
			"get-effective-permissions-for-path":                    {"ResourceArn"},
			"get-lf-tag":                                            {"TagKey"},
			"get-lf-tag-expression":                                 {"Name"},
			"get-query-state":                                       {"QueryId"},
			"get-query-statistics":                                  {"QueryId"},
			"get-resource-lf-tags":                                  {"Resource"},
			"get-table-objects":                                     {"DatabaseName", "TableName"},
			"get-temporary-data-location-credentials":               {},
			"get-temporary-glue-partition-credentials":              {"Partition", "TableArn"},
			"get-temporary-glue-table-credentials":                  {"TableArn"},
			"get-work-unit-results":                                 {"QueryId", "WorkUnitId", "WorkUnitToken"},
			"get-work-units":                                        {"QueryId"},
			"grant-permissions":                                     {"Permissions", "Principal", "Resource"},
			"list-data-cells-filter":                                {},
			"list-lake-formation-opt-ins":                           {},
			"list-lf-tag-expressions":                               {},
			"list-lf-tags":                                          {},
			"list-permissions":                                      {},
			"list-resources":                                        {},
			"list-table-storage-optimizers":                         {"DatabaseName", "TableName"},
			"list-transactions":                                     {},
			"put-data-lake-settings":                                {"DataLakeSettings"},
			"register-resource":                                     {"ResourceArn"},
			"remove-lf-tags-from-resource":                          {"LFTags", "Resource"},
			"revoke-permissions":                                    {"Permissions", "Principal", "Resource"},
			"search-databases-by-lf-tags":                           {"Expression"},
			"search-tables-by-lf-tags":                              {"Expression"},
			"start-query-planning":                                  {"QueryPlanningContext", "QueryString"},
			"start-transaction":                                     {},
			"update-data-cells-filter":                              {"TableData"},
			"update-lake-formation-identity-center-configuration":   {},
			"update-lf-tag":                                         {"TagKey"},
			"update-lf-tag-expression":                              {"Expression", "Name"},
			"update-resource":                                       {"ResourceArn", "RoleArn"},
			"update-table-objects":                                  {"DatabaseName", "TableName", "WriteOperations"},
			"update-table-storage-optimizer":                        {"DatabaseName", "StorageOptimizerConfig", "TableName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("lakeformation", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
