package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/route53recoveryreadiness/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-cell", "create-cross-account-authorization", "create-readiness-check", "create-recovery-group", "create-resource-set", "delete-cell", "delete-cross-account-authorization", "delete-readiness-check", "delete-recovery-group", "delete-resource-set", "get-architecture-recommendations", "get-cell", "get-cell-readiness-summary", "get-readiness-check", "get-readiness-check-resource-status", "get-readiness-check-status", "get-recovery-group", "get-recovery-group-readiness-summary", "get-resource-set", "list-cells", "list-cross-account-authorizations", "list-readiness-checks", "list-recovery-groups", "list-resource-sets", "list-rules", "list-tags-for-resources", "tag-resource", "untag-resource", "update-cell", "update-readiness-check", "update-recovery-group", "update-resource-set"},
		OperationSet: map[string]bool{"create-cell": true, "create-cross-account-authorization": true, "create-readiness-check": true, "create-recovery-group": true, "create-resource-set": true, "delete-cell": true, "delete-cross-account-authorization": true, "delete-readiness-check": true, "delete-recovery-group": true, "delete-resource-set": true, "get-architecture-recommendations": true, "get-cell": true, "get-cell-readiness-summary": true, "get-readiness-check": true, "get-readiness-check-resource-status": true, "get-readiness-check-status": true, "get-recovery-group": true, "get-recovery-group-readiness-summary": true, "get-resource-set": true, "list-cells": true, "list-cross-account-authorizations": true, "list-readiness-checks": true, "list-recovery-groups": true, "list-resource-sets": true, "list-rules": true, "list-tags-for-resources": true, "tag-resource": true, "untag-resource": true, "update-cell": true, "update-readiness-check": true, "update-recovery-group": true, "update-resource-set": true},
		OperationInputs: map[string][]string{
			"create-cell":                          {"CellName", "Cells", "Tags"},
			"create-cross-account-authorization":   {"CrossAccountAuthorization"},
			"create-readiness-check":               {"ReadinessCheckName", "ResourceSetName", "Tags"},
			"create-recovery-group":                {"Cells", "RecoveryGroupName", "Tags"},
			"create-resource-set":                  {"ResourceSetName", "ResourceSetType", "Resources", "Tags"},
			"delete-cell":                          {"CellName"},
			"delete-cross-account-authorization":   {"CrossAccountAuthorization"},
			"delete-readiness-check":               {"ReadinessCheckName"},
			"delete-recovery-group":                {"RecoveryGroupName"},
			"delete-resource-set":                  {"ResourceSetName"},
			"get-architecture-recommendations":     {"MaxResults", "NextToken", "RecoveryGroupName"},
			"get-cell":                             {"CellName"},
			"get-cell-readiness-summary":           {"CellName", "MaxResults", "NextToken"},
			"get-readiness-check":                  {"ReadinessCheckName"},
			"get-readiness-check-resource-status":  {"MaxResults", "NextToken", "ReadinessCheckName", "ResourceIdentifier"},
			"get-readiness-check-status":           {"MaxResults", "NextToken", "ReadinessCheckName"},
			"get-recovery-group":                   {"RecoveryGroupName"},
			"get-recovery-group-readiness-summary": {"MaxResults", "NextToken", "RecoveryGroupName"},
			"get-resource-set":                     {"ResourceSetName"},
			"list-cells":                           {"MaxResults", "NextToken"},
			"list-cross-account-authorizations":    {"MaxResults", "NextToken"},
			"list-readiness-checks":                {"MaxResults", "NextToken"},
			"list-recovery-groups":                 {"MaxResults", "NextToken"},
			"list-resource-sets":                   {"MaxResults", "NextToken"},
			"list-rules":                           {"MaxResults", "NextToken", "ResourceType"},
			"list-tags-for-resources":              {"ResourceArn"},
			"tag-resource":                         {"ResourceArn", "Tags"},
			"untag-resource":                       {"ResourceArn", "TagKeys"},
			"update-cell":                          {"CellName", "Cells"},
			"update-readiness-check":               {"ReadinessCheckName", "ResourceSetName"},
			"update-recovery-group":                {"Cells", "RecoveryGroupName"},
			"update-resource-set":                  {"ResourceSetName", "ResourceSetType", "Resources"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-cell":                          {"CellName": "*string", "Cells": "[]string", "Tags": "map[string]string"},
			"create-cross-account-authorization":   {"CrossAccountAuthorization": "*string"},
			"create-readiness-check":               {"ReadinessCheckName": "*string", "ResourceSetName": "*string", "Tags": "map[string]string"},
			"create-recovery-group":                {"Cells": "[]string", "RecoveryGroupName": "*string", "Tags": "map[string]string"},
			"create-resource-set":                  {"ResourceSetName": "*string", "ResourceSetType": "*string", "Resources": "[]types.Resource", "Tags": "map[string]string"},
			"delete-cell":                          {"CellName": "*string"},
			"delete-cross-account-authorization":   {"CrossAccountAuthorization": "*string"},
			"delete-readiness-check":               {"ReadinessCheckName": "*string"},
			"delete-recovery-group":                {"RecoveryGroupName": "*string"},
			"delete-resource-set":                  {"ResourceSetName": "*string"},
			"get-architecture-recommendations":     {"MaxResults": "*int32", "NextToken": "*string", "RecoveryGroupName": "*string"},
			"get-cell":                             {"CellName": "*string"},
			"get-cell-readiness-summary":           {"CellName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-readiness-check":                  {"ReadinessCheckName": "*string"},
			"get-readiness-check-resource-status":  {"MaxResults": "*int32", "NextToken": "*string", "ReadinessCheckName": "*string", "ResourceIdentifier": "*string"},
			"get-readiness-check-status":           {"MaxResults": "*int32", "NextToken": "*string", "ReadinessCheckName": "*string"},
			"get-recovery-group":                   {"RecoveryGroupName": "*string"},
			"get-recovery-group-readiness-summary": {"MaxResults": "*int32", "NextToken": "*string", "RecoveryGroupName": "*string"},
			"get-resource-set":                     {"ResourceSetName": "*string"},
			"list-cells":                           {"MaxResults": "*int32", "NextToken": "*string"},
			"list-cross-account-authorizations":    {"MaxResults": "*int32", "NextToken": "*string"},
			"list-readiness-checks":                {"MaxResults": "*int32", "NextToken": "*string"},
			"list-recovery-groups":                 {"MaxResults": "*int32", "NextToken": "*string"},
			"list-resource-sets":                   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-rules":                           {"MaxResults": "*int32", "NextToken": "*string", "ResourceType": "*string"},
			"list-tags-for-resources":              {"ResourceArn": "*string"},
			"tag-resource":                         {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                       {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-cell":                          {"CellName": "*string", "Cells": "[]string"},
			"update-readiness-check":               {"ReadinessCheckName": "*string", "ResourceSetName": "*string"},
			"update-recovery-group":                {"Cells": "[]string", "RecoveryGroupName": "*string"},
			"update-resource-set":                  {"ResourceSetName": "*string", "ResourceSetType": "*string", "Resources": "[]types.Resource"},
		},
		OperationInputRequired: map[string][]string{
			"create-cell":                          {"CellName"},
			"create-cross-account-authorization":   {"CrossAccountAuthorization"},
			"create-readiness-check":               {"ReadinessCheckName", "ResourceSetName"},
			"create-recovery-group":                {"RecoveryGroupName"},
			"create-resource-set":                  {"ResourceSetName", "ResourceSetType", "Resources"},
			"delete-cell":                          {"CellName"},
			"delete-cross-account-authorization":   {"CrossAccountAuthorization"},
			"delete-readiness-check":               {"ReadinessCheckName"},
			"delete-recovery-group":                {"RecoveryGroupName"},
			"delete-resource-set":                  {"ResourceSetName"},
			"get-architecture-recommendations":     {"RecoveryGroupName"},
			"get-cell":                             {"CellName"},
			"get-cell-readiness-summary":           {"CellName"},
			"get-readiness-check":                  {"ReadinessCheckName"},
			"get-readiness-check-resource-status":  {"ReadinessCheckName", "ResourceIdentifier"},
			"get-readiness-check-status":           {"ReadinessCheckName"},
			"get-recovery-group":                   {"RecoveryGroupName"},
			"get-recovery-group-readiness-summary": {"RecoveryGroupName"},
			"get-resource-set":                     {"ResourceSetName"},
			"list-cells":                           {},
			"list-cross-account-authorizations":    {},
			"list-readiness-checks":                {},
			"list-recovery-groups":                 {},
			"list-resource-sets":                   {},
			"list-rules":                           {},
			"list-tags-for-resources":              {"ResourceArn"},
			"tag-resource":                         {"ResourceArn", "Tags"},
			"untag-resource":                       {"ResourceArn", "TagKeys"},
			"update-cell":                          {"CellName", "Cells"},
			"update-readiness-check":               {"ReadinessCheckName", "ResourceSetName"},
			"update-recovery-group":                {"Cells", "RecoveryGroupName"},
			"update-resource-set":                  {"ResourceSetName", "ResourceSetType", "Resources"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("route53recoveryreadiness", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
