package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/elasticbeanstalk/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"abort-environment-update", "apply-environment-managed-action", "associate-environment-operations-role", "check-dns-availability", "compose-environments", "create-application", "create-application-version", "create-configuration-template", "create-environment", "create-platform-version", "create-storage-location", "delete-application", "delete-application-version", "delete-configuration-template", "delete-environment-configuration", "delete-platform-version", "describe-account-attributes", "describe-application-versions", "describe-applications", "describe-configuration-options", "describe-configuration-settings", "describe-environment-health", "describe-environment-managed-action-history", "describe-environment-managed-actions", "describe-environment-resources", "describe-environments", "describe-events", "describe-instances-health", "describe-platform-version", "disassociate-environment-operations-role", "list-available-solution-stacks", "list-platform-branches", "list-platform-versions", "list-tags-for-resource", "rebuild-environment", "request-environment-info", "restart-app-server", "retrieve-environment-info", "swap-environment-cnames", "terminate-environment", "update-application", "update-application-resource-lifecycle", "update-application-version", "update-configuration-template", "update-environment", "update-tags-for-resource", "validate-configuration-settings"},
		OperationSet: map[string]bool{"abort-environment-update": true, "apply-environment-managed-action": true, "associate-environment-operations-role": true, "check-dns-availability": true, "compose-environments": true, "create-application": true, "create-application-version": true, "create-configuration-template": true, "create-environment": true, "create-platform-version": true, "create-storage-location": true, "delete-application": true, "delete-application-version": true, "delete-configuration-template": true, "delete-environment-configuration": true, "delete-platform-version": true, "describe-account-attributes": true, "describe-application-versions": true, "describe-applications": true, "describe-configuration-options": true, "describe-configuration-settings": true, "describe-environment-health": true, "describe-environment-managed-action-history": true, "describe-environment-managed-actions": true, "describe-environment-resources": true, "describe-environments": true, "describe-events": true, "describe-instances-health": true, "describe-platform-version": true, "disassociate-environment-operations-role": true, "list-available-solution-stacks": true, "list-platform-branches": true, "list-platform-versions": true, "list-tags-for-resource": true, "rebuild-environment": true, "request-environment-info": true, "restart-app-server": true, "retrieve-environment-info": true, "swap-environment-cnames": true, "terminate-environment": true, "update-application": true, "update-application-resource-lifecycle": true, "update-application-version": true, "update-configuration-template": true, "update-environment": true, "update-tags-for-resource": true, "validate-configuration-settings": true},
		OperationInputs: map[string][]string{
			"abort-environment-update":                    {"EnvironmentId", "EnvironmentName"},
			"apply-environment-managed-action":            {"ActionId", "EnvironmentId", "EnvironmentName"},
			"associate-environment-operations-role":       {"EnvironmentName", "OperationsRole"},
			"check-dns-availability":                      {"CNAMEPrefix"},
			"compose-environments":                        {"ApplicationName", "GroupName", "VersionLabels"},
			"create-application":                          {"ApplicationName", "Description", "ResourceLifecycleConfig", "Tags"},
			"create-application-version":                  {"ApplicationName", "AutoCreateApplication", "BuildConfiguration", "Description", "Process", "SourceBuildInformation", "SourceBundle", "Tags", "VersionLabel"},
			"create-configuration-template":               {"ApplicationName", "Description", "EnvironmentId", "OptionSettings", "PlatformArn", "SolutionStackName", "SourceConfiguration", "Tags", "TemplateName"},
			"create-environment":                          {"ApplicationName", "CNAMEPrefix", "Description", "EnvironmentName", "GroupName", "OperationsRole", "OptionSettings", "OptionsToRemove", "PlatformArn", "SolutionStackName", "Tags", "TemplateName", "Tier", "VersionLabel"},
			"create-platform-version":                     {"EnvironmentName", "OptionSettings", "PlatformDefinitionBundle", "PlatformName", "PlatformVersion", "Tags"},
			"create-storage-location":                     {},
			"delete-application":                          {"ApplicationName", "TerminateEnvByForce"},
			"delete-application-version":                  {"ApplicationName", "DeleteSourceBundle", "VersionLabel"},
			"delete-configuration-template":               {"ApplicationName", "TemplateName"},
			"delete-environment-configuration":            {"ApplicationName", "EnvironmentName"},
			"delete-platform-version":                     {"PlatformArn"},
			"describe-account-attributes":                 {},
			"describe-application-versions":               {"ApplicationName", "MaxRecords", "NextToken", "VersionLabels"},
			"describe-applications":                       {"ApplicationNames"},
			"describe-configuration-options":              {"ApplicationName", "EnvironmentName", "Options", "PlatformArn", "SolutionStackName", "TemplateName"},
			"describe-configuration-settings":             {"ApplicationName", "EnvironmentName", "TemplateName"},
			"describe-environment-health":                 {"AttributeNames", "EnvironmentId", "EnvironmentName"},
			"describe-environment-managed-action-history": {"EnvironmentId", "EnvironmentName", "MaxItems", "NextToken"},
			"describe-environment-managed-actions":        {"EnvironmentId", "EnvironmentName", "Status"},
			"describe-environment-resources":              {"EnvironmentId", "EnvironmentName"},
			"describe-environments":                       {"ApplicationName", "EnvironmentIds", "EnvironmentNames", "IncludeDeleted", "IncludedDeletedBackTo", "MaxRecords", "NextToken", "VersionLabel"},
			"describe-events":                             {"ApplicationName", "EndTime", "EnvironmentId", "EnvironmentName", "MaxRecords", "NextToken", "PlatformArn", "RequestId", "Severity", "StartTime", "TemplateName", "VersionLabel"},
			"describe-instances-health":                   {"AttributeNames", "EnvironmentId", "EnvironmentName", "NextToken"},
			"describe-platform-version":                   {"PlatformArn"},
			"disassociate-environment-operations-role":    {"EnvironmentName"},
			"list-available-solution-stacks":              {},
			"list-platform-branches":                      {"Filters", "MaxRecords", "NextToken"},
			"list-platform-versions":                      {"Filters", "MaxRecords", "NextToken"},
			"list-tags-for-resource":                      {"ResourceArn"},
			"rebuild-environment":                         {"EnvironmentId", "EnvironmentName"},
			"request-environment-info":                    {"EnvironmentId", "EnvironmentName", "InfoType"},
			"restart-app-server":                          {"EnvironmentId", "EnvironmentName"},
			"retrieve-environment-info":                   {"EnvironmentId", "EnvironmentName", "InfoType"},
			"swap-environment-cnames":                     {"DestinationEnvironmentId", "DestinationEnvironmentName", "SourceEnvironmentId", "SourceEnvironmentName"},
			"terminate-environment":                       {"EnvironmentId", "EnvironmentName", "ForceTerminate", "TerminateResources"},
			"update-application":                          {"ApplicationName", "Description"},
			"update-application-resource-lifecycle":       {"ApplicationName", "ResourceLifecycleConfig"},
			"update-application-version":                  {"ApplicationName", "Description", "VersionLabel"},
			"update-configuration-template":               {"ApplicationName", "Description", "OptionSettings", "OptionsToRemove", "TemplateName"},
			"update-environment":                          {"ApplicationName", "Description", "EnvironmentId", "EnvironmentName", "GroupName", "OptionSettings", "OptionsToRemove", "PlatformArn", "SolutionStackName", "TemplateName", "Tier", "VersionLabel"},
			"update-tags-for-resource":                    {"ResourceArn", "TagsToAdd", "TagsToRemove"},
			"validate-configuration-settings":             {"ApplicationName", "EnvironmentName", "OptionSettings", "TemplateName"},
		},
		OperationInputTypes: map[string]map[string]string{
			"abort-environment-update":                    {"EnvironmentId": "*string", "EnvironmentName": "*string"},
			"apply-environment-managed-action":            {"ActionId": "*string", "EnvironmentId": "*string", "EnvironmentName": "*string"},
			"associate-environment-operations-role":       {"EnvironmentName": "*string", "OperationsRole": "*string"},
			"check-dns-availability":                      {"CNAMEPrefix": "*string"},
			"compose-environments":                        {"ApplicationName": "*string", "GroupName": "*string", "VersionLabels": "[]string"},
			"create-application":                          {"ApplicationName": "*string", "Description": "*string", "ResourceLifecycleConfig": "*types.ApplicationResourceLifecycleConfig", "Tags": "[]types.Tag"},
			"create-application-version":                  {"ApplicationName": "*string", "AutoCreateApplication": "*bool", "BuildConfiguration": "*types.BuildConfiguration", "Description": "*string", "Process": "*bool", "SourceBuildInformation": "*types.SourceBuildInformation", "SourceBundle": "*types.S3Location", "Tags": "[]types.Tag", "VersionLabel": "*string"},
			"create-configuration-template":               {"ApplicationName": "*string", "Description": "*string", "EnvironmentId": "*string", "OptionSettings": "[]types.ConfigurationOptionSetting", "PlatformArn": "*string", "SolutionStackName": "*string", "SourceConfiguration": "*types.SourceConfiguration", "Tags": "[]types.Tag", "TemplateName": "*string"},
			"create-environment":                          {"ApplicationName": "*string", "CNAMEPrefix": "*string", "Description": "*string", "EnvironmentName": "*string", "GroupName": "*string", "OperationsRole": "*string", "OptionSettings": "[]types.ConfigurationOptionSetting", "OptionsToRemove": "[]types.OptionSpecification", "PlatformArn": "*string", "SolutionStackName": "*string", "Tags": "[]types.Tag", "TemplateName": "*string", "Tier": "*types.EnvironmentTier", "VersionLabel": "*string"},
			"create-platform-version":                     {"EnvironmentName": "*string", "OptionSettings": "[]types.ConfigurationOptionSetting", "PlatformDefinitionBundle": "*types.S3Location", "PlatformName": "*string", "PlatformVersion": "*string", "Tags": "[]types.Tag"},
			"create-storage-location":                     {},
			"delete-application":                          {"ApplicationName": "*string", "TerminateEnvByForce": "*bool"},
			"delete-application-version":                  {"ApplicationName": "*string", "DeleteSourceBundle": "*bool", "VersionLabel": "*string"},
			"delete-configuration-template":               {"ApplicationName": "*string", "TemplateName": "*string"},
			"delete-environment-configuration":            {"ApplicationName": "*string", "EnvironmentName": "*string"},
			"delete-platform-version":                     {"PlatformArn": "*string"},
			"describe-account-attributes":                 {},
			"describe-application-versions":               {"ApplicationName": "*string", "MaxRecords": "*int32", "NextToken": "*string", "VersionLabels": "[]string"},
			"describe-applications":                       {"ApplicationNames": "[]string"},
			"describe-configuration-options":              {"ApplicationName": "*string", "EnvironmentName": "*string", "Options": "[]types.OptionSpecification", "PlatformArn": "*string", "SolutionStackName": "*string", "TemplateName": "*string"},
			"describe-configuration-settings":             {"ApplicationName": "*string", "EnvironmentName": "*string", "TemplateName": "*string"},
			"describe-environment-health":                 {"AttributeNames": "[]types.EnvironmentHealthAttribute", "EnvironmentId": "*string", "EnvironmentName": "*string"},
			"describe-environment-managed-action-history": {"EnvironmentId": "*string", "EnvironmentName": "*string", "MaxItems": "*int32", "NextToken": "*string"},
			"describe-environment-managed-actions":        {"EnvironmentId": "*string", "EnvironmentName": "*string", "Status": "types.ActionStatus"},
			"describe-environment-resources":              {"EnvironmentId": "*string", "EnvironmentName": "*string"},
			"describe-environments":                       {"ApplicationName": "*string", "EnvironmentIds": "[]string", "EnvironmentNames": "[]string", "IncludeDeleted": "*bool", "IncludedDeletedBackTo": "*time.Time", "MaxRecords": "*int32", "NextToken": "*string", "VersionLabel": "*string"},
			"describe-events":                             {"ApplicationName": "*string", "EndTime": "*time.Time", "EnvironmentId": "*string", "EnvironmentName": "*string", "MaxRecords": "*int32", "NextToken": "*string", "PlatformArn": "*string", "RequestId": "*string", "Severity": "types.EventSeverity", "StartTime": "*time.Time", "TemplateName": "*string", "VersionLabel": "*string"},
			"describe-instances-health":                   {"AttributeNames": "[]types.InstancesHealthAttribute", "EnvironmentId": "*string", "EnvironmentName": "*string", "NextToken": "*string"},
			"describe-platform-version":                   {"PlatformArn": "*string"},
			"disassociate-environment-operations-role":    {"EnvironmentName": "*string"},
			"list-available-solution-stacks":              {},
			"list-platform-branches":                      {"Filters": "[]types.SearchFilter", "MaxRecords": "*int32", "NextToken": "*string"},
			"list-platform-versions":                      {"Filters": "[]types.PlatformFilter", "MaxRecords": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                      {"ResourceArn": "*string"},
			"rebuild-environment":                         {"EnvironmentId": "*string", "EnvironmentName": "*string"},
			"request-environment-info":                    {"EnvironmentId": "*string", "EnvironmentName": "*string", "InfoType": "types.EnvironmentInfoType"},
			"restart-app-server":                          {"EnvironmentId": "*string", "EnvironmentName": "*string"},
			"retrieve-environment-info":                   {"EnvironmentId": "*string", "EnvironmentName": "*string", "InfoType": "types.EnvironmentInfoType"},
			"swap-environment-cnames":                     {"DestinationEnvironmentId": "*string", "DestinationEnvironmentName": "*string", "SourceEnvironmentId": "*string", "SourceEnvironmentName": "*string"},
			"terminate-environment":                       {"EnvironmentId": "*string", "EnvironmentName": "*string", "ForceTerminate": "*bool", "TerminateResources": "*bool"},
			"update-application":                          {"ApplicationName": "*string", "Description": "*string"},
			"update-application-resource-lifecycle":       {"ApplicationName": "*string", "ResourceLifecycleConfig": "*types.ApplicationResourceLifecycleConfig"},
			"update-application-version":                  {"ApplicationName": "*string", "Description": "*string", "VersionLabel": "*string"},
			"update-configuration-template":               {"ApplicationName": "*string", "Description": "*string", "OptionSettings": "[]types.ConfigurationOptionSetting", "OptionsToRemove": "[]types.OptionSpecification", "TemplateName": "*string"},
			"update-environment":                          {"ApplicationName": "*string", "Description": "*string", "EnvironmentId": "*string", "EnvironmentName": "*string", "GroupName": "*string", "OptionSettings": "[]types.ConfigurationOptionSetting", "OptionsToRemove": "[]types.OptionSpecification", "PlatformArn": "*string", "SolutionStackName": "*string", "TemplateName": "*string", "Tier": "*types.EnvironmentTier", "VersionLabel": "*string"},
			"update-tags-for-resource":                    {"ResourceArn": "*string", "TagsToAdd": "[]types.Tag", "TagsToRemove": "[]string"},
			"validate-configuration-settings":             {"ApplicationName": "*string", "EnvironmentName": "*string", "OptionSettings": "[]types.ConfigurationOptionSetting", "TemplateName": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"abort-environment-update":                    {},
			"apply-environment-managed-action":            {"ActionId"},
			"associate-environment-operations-role":       {"EnvironmentName", "OperationsRole"},
			"check-dns-availability":                      {"CNAMEPrefix"},
			"compose-environments":                        {},
			"create-application":                          {"ApplicationName"},
			"create-application-version":                  {"ApplicationName", "VersionLabel"},
			"create-configuration-template":               {"ApplicationName", "TemplateName"},
			"create-environment":                          {"ApplicationName"},
			"create-platform-version":                     {"PlatformDefinitionBundle", "PlatformName", "PlatformVersion"},
			"create-storage-location":                     {},
			"delete-application":                          {"ApplicationName"},
			"delete-application-version":                  {"ApplicationName", "VersionLabel"},
			"delete-configuration-template":               {"ApplicationName", "TemplateName"},
			"delete-environment-configuration":            {"ApplicationName", "EnvironmentName"},
			"delete-platform-version":                     {},
			"describe-account-attributes":                 {},
			"describe-application-versions":               {},
			"describe-applications":                       {},
			"describe-configuration-options":              {},
			"describe-configuration-settings":             {"ApplicationName"},
			"describe-environment-health":                 {},
			"describe-environment-managed-action-history": {},
			"describe-environment-managed-actions":        {},
			"describe-environment-resources":              {},
			"describe-environments":                       {},
			"describe-events":                             {},
			"describe-instances-health":                   {},
			"describe-platform-version":                   {},
			"disassociate-environment-operations-role":    {"EnvironmentName"},
			"list-available-solution-stacks":              {},
			"list-platform-branches":                      {},
			"list-platform-versions":                      {},
			"list-tags-for-resource":                      {"ResourceArn"},
			"rebuild-environment":                         {},
			"request-environment-info":                    {"InfoType"},
			"restart-app-server":                          {},
			"retrieve-environment-info":                   {"InfoType"},
			"swap-environment-cnames":                     {},
			"terminate-environment":                       {},
			"update-application":                          {"ApplicationName"},
			"update-application-resource-lifecycle":       {"ApplicationName", "ResourceLifecycleConfig"},
			"update-application-version":                  {"ApplicationName", "VersionLabel"},
			"update-configuration-template":               {"ApplicationName", "TemplateName"},
			"update-environment":                          {},
			"update-tags-for-resource":                    {"ResourceArn"},
			"validate-configuration-settings":             {"ApplicationName", "OptionSettings"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("elasticbeanstalk", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
