package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/workspacesweb/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-browser-settings", "associate-data-protection-settings", "associate-ip-access-settings", "associate-network-settings", "associate-session-logger", "associate-trust-store", "associate-user-access-logging-settings", "associate-user-settings", "create-browser-settings", "create-data-protection-settings", "create-identity-provider", "create-ip-access-settings", "create-network-settings", "create-portal", "create-session-logger", "create-trust-store", "create-user-access-logging-settings", "create-user-settings", "delete-browser-settings", "delete-data-protection-settings", "delete-identity-provider", "delete-ip-access-settings", "delete-network-settings", "delete-portal", "delete-session-logger", "delete-trust-store", "delete-user-access-logging-settings", "delete-user-settings", "disassociate-browser-settings", "disassociate-data-protection-settings", "disassociate-ip-access-settings", "disassociate-network-settings", "disassociate-session-logger", "disassociate-trust-store", "disassociate-user-access-logging-settings", "disassociate-user-settings", "expire-session", "get-browser-settings", "get-data-protection-settings", "get-identity-provider", "get-ip-access-settings", "get-network-settings", "get-portal", "get-portal-service-provider-metadata", "get-session", "get-session-logger", "get-trust-store", "get-trust-store-certificate", "get-user-access-logging-settings", "get-user-settings", "list-browser-settings", "list-data-protection-settings", "list-identity-providers", "list-ip-access-settings", "list-network-settings", "list-portals", "list-session-loggers", "list-sessions", "list-tags-for-resource", "list-trust-store-certificates", "list-trust-stores", "list-user-access-logging-settings", "list-user-settings", "tag-resource", "untag-resource", "update-browser-settings", "update-data-protection-settings", "update-identity-provider", "update-ip-access-settings", "update-network-settings", "update-portal", "update-session-logger", "update-trust-store", "update-user-access-logging-settings", "update-user-settings"},
		OperationSet: map[string]bool{"associate-browser-settings": true, "associate-data-protection-settings": true, "associate-ip-access-settings": true, "associate-network-settings": true, "associate-session-logger": true, "associate-trust-store": true, "associate-user-access-logging-settings": true, "associate-user-settings": true, "create-browser-settings": true, "create-data-protection-settings": true, "create-identity-provider": true, "create-ip-access-settings": true, "create-network-settings": true, "create-portal": true, "create-session-logger": true, "create-trust-store": true, "create-user-access-logging-settings": true, "create-user-settings": true, "delete-browser-settings": true, "delete-data-protection-settings": true, "delete-identity-provider": true, "delete-ip-access-settings": true, "delete-network-settings": true, "delete-portal": true, "delete-session-logger": true, "delete-trust-store": true, "delete-user-access-logging-settings": true, "delete-user-settings": true, "disassociate-browser-settings": true, "disassociate-data-protection-settings": true, "disassociate-ip-access-settings": true, "disassociate-network-settings": true, "disassociate-session-logger": true, "disassociate-trust-store": true, "disassociate-user-access-logging-settings": true, "disassociate-user-settings": true, "expire-session": true, "get-browser-settings": true, "get-data-protection-settings": true, "get-identity-provider": true, "get-ip-access-settings": true, "get-network-settings": true, "get-portal": true, "get-portal-service-provider-metadata": true, "get-session": true, "get-session-logger": true, "get-trust-store": true, "get-trust-store-certificate": true, "get-user-access-logging-settings": true, "get-user-settings": true, "list-browser-settings": true, "list-data-protection-settings": true, "list-identity-providers": true, "list-ip-access-settings": true, "list-network-settings": true, "list-portals": true, "list-session-loggers": true, "list-sessions": true, "list-tags-for-resource": true, "list-trust-store-certificates": true, "list-trust-stores": true, "list-user-access-logging-settings": true, "list-user-settings": true, "tag-resource": true, "untag-resource": true, "update-browser-settings": true, "update-data-protection-settings": true, "update-identity-provider": true, "update-ip-access-settings": true, "update-network-settings": true, "update-portal": true, "update-session-logger": true, "update-trust-store": true, "update-user-access-logging-settings": true, "update-user-settings": true},
		OperationInputs: map[string][]string{
			"associate-browser-settings":                {"BrowserSettingsArn", "PortalArn"},
			"associate-data-protection-settings":        {"DataProtectionSettingsArn", "PortalArn"},
			"associate-ip-access-settings":              {"IpAccessSettingsArn", "PortalArn"},
			"associate-network-settings":                {"NetworkSettingsArn", "PortalArn"},
			"associate-session-logger":                  {"PortalArn", "SessionLoggerArn"},
			"associate-trust-store":                     {"PortalArn", "TrustStoreArn"},
			"associate-user-access-logging-settings":    {"PortalArn", "UserAccessLoggingSettingsArn"},
			"associate-user-settings":                   {"PortalArn", "UserSettingsArn"},
			"create-browser-settings":                   {"AdditionalEncryptionContext", "BrowserPolicy", "ClientToken", "CustomerManagedKey", "Tags", "WebContentFilteringPolicy"},
			"create-data-protection-settings":           {"AdditionalEncryptionContext", "ClientToken", "CustomerManagedKey", "Description", "DisplayName", "InlineRedactionConfiguration", "Tags"},
			"create-identity-provider":                  {"ClientToken", "IdentityProviderDetails", "IdentityProviderName", "IdentityProviderType", "PortalArn", "Tags"},
			"create-ip-access-settings":                 {"AdditionalEncryptionContext", "ClientToken", "CustomerManagedKey", "Description", "DisplayName", "IpRules", "Tags"},
			"create-network-settings":                   {"ClientToken", "SecurityGroupIds", "SubnetIds", "Tags", "VpcId"},
			"create-portal":                             {"AdditionalEncryptionContext", "AuthenticationType", "ClientToken", "CustomerManagedKey", "DisplayName", "InstanceType", "MaxConcurrentSessions", "PortalCustomDomain", "Tags"},
			"create-session-logger":                     {"AdditionalEncryptionContext", "ClientToken", "CustomerManagedKey", "DisplayName", "EventFilter", "LogConfiguration", "Tags"},
			"create-trust-store":                        {"CertificateList", "ClientToken", "Tags"},
			"create-user-access-logging-settings":       {"ClientToken", "KinesisStreamArn", "Tags"},
			"create-user-settings":                      {"AdditionalEncryptionContext", "BrandingConfigurationInput", "ClientToken", "CookieSynchronizationConfiguration", "CopyAllowed", "CustomerManagedKey", "DeepLinkAllowed", "DisconnectTimeoutInMinutes", "DownloadAllowed", "IdleDisconnectTimeoutInMinutes", "PasteAllowed", "PrintAllowed", "Tags", "ToolbarConfiguration", "UploadAllowed", "WebAuthnAllowed"},
			"delete-browser-settings":                   {"BrowserSettingsArn"},
			"delete-data-protection-settings":           {"DataProtectionSettingsArn"},
			"delete-identity-provider":                  {"IdentityProviderArn"},
			"delete-ip-access-settings":                 {"IpAccessSettingsArn"},
			"delete-network-settings":                   {"NetworkSettingsArn"},
			"delete-portal":                             {"PortalArn"},
			"delete-session-logger":                     {"SessionLoggerArn"},
			"delete-trust-store":                        {"TrustStoreArn"},
			"delete-user-access-logging-settings":       {"UserAccessLoggingSettingsArn"},
			"delete-user-settings":                      {"UserSettingsArn"},
			"disassociate-browser-settings":             {"PortalArn"},
			"disassociate-data-protection-settings":     {"PortalArn"},
			"disassociate-ip-access-settings":           {"PortalArn"},
			"disassociate-network-settings":             {"PortalArn"},
			"disassociate-session-logger":               {"PortalArn"},
			"disassociate-trust-store":                  {"PortalArn"},
			"disassociate-user-access-logging-settings": {"PortalArn"},
			"disassociate-user-settings":                {"PortalArn"},
			"expire-session":                            {"PortalId", "SessionId"},
			"get-browser-settings":                      {"BrowserSettingsArn"},
			"get-data-protection-settings":              {"DataProtectionSettingsArn"},
			"get-identity-provider":                     {"IdentityProviderArn"},
			"get-ip-access-settings":                    {"IpAccessSettingsArn"},
			"get-network-settings":                      {"NetworkSettingsArn"},
			"get-portal":                                {"PortalArn"},
			"get-portal-service-provider-metadata":      {"PortalArn"},
			"get-session":                               {"PortalId", "SessionId"},
			"get-session-logger":                        {"SessionLoggerArn"},
			"get-trust-store":                           {"TrustStoreArn"},
			"get-trust-store-certificate":               {"Thumbprint", "TrustStoreArn"},
			"get-user-access-logging-settings":          {"UserAccessLoggingSettingsArn"},
			"get-user-settings":                         {"UserSettingsArn"},
			"list-browser-settings":                     {"MaxResults", "NextToken"},
			"list-data-protection-settings":             {"MaxResults", "NextToken"},
			"list-identity-providers":                   {"MaxResults", "NextToken", "PortalArn"},
			"list-ip-access-settings":                   {"MaxResults", "NextToken"},
			"list-network-settings":                     {"MaxResults", "NextToken"},
			"list-portals":                              {"MaxResults", "NextToken"},
			"list-session-loggers":                      {"MaxResults", "NextToken"},
			"list-sessions":                             {"MaxResults", "NextToken", "PortalId", "SessionId", "SortBy", "Status", "Username"},
			"list-tags-for-resource":                    {"ResourceArn"},
			"list-trust-store-certificates":             {"MaxResults", "NextToken", "TrustStoreArn"},
			"list-trust-stores":                         {"MaxResults", "NextToken"},
			"list-user-access-logging-settings":         {"MaxResults", "NextToken"},
			"list-user-settings":                        {"MaxResults", "NextToken"},
			"tag-resource":                              {"ClientToken", "ResourceArn", "Tags"},
			"untag-resource":                            {"ResourceArn", "TagKeys"},
			"update-browser-settings":                   {"BrowserPolicy", "BrowserSettingsArn", "ClientToken", "WebContentFilteringPolicy"},
			"update-data-protection-settings":           {"ClientToken", "DataProtectionSettingsArn", "Description", "DisplayName", "InlineRedactionConfiguration"},
			"update-identity-provider":                  {"ClientToken", "IdentityProviderArn", "IdentityProviderDetails", "IdentityProviderName", "IdentityProviderType"},
			"update-ip-access-settings":                 {"ClientToken", "Description", "DisplayName", "IpAccessSettingsArn", "IpRules"},
			"update-network-settings":                   {"ClientToken", "NetworkSettingsArn", "SecurityGroupIds", "SubnetIds", "VpcId"},
			"update-portal":                             {"AuthenticationType", "DisplayName", "InstanceType", "MaxConcurrentSessions", "PortalArn", "PortalCustomDomain"},
			"update-session-logger":                     {"DisplayName", "EventFilter", "LogConfiguration", "SessionLoggerArn"},
			"update-trust-store":                        {"CertificatesToAdd", "CertificatesToDelete", "ClientToken", "TrustStoreArn"},
			"update-user-access-logging-settings":       {"ClientToken", "KinesisStreamArn", "UserAccessLoggingSettingsArn"},
			"update-user-settings":                      {"BrandingConfigurationInput", "ClientToken", "CookieSynchronizationConfiguration", "CopyAllowed", "DeepLinkAllowed", "DisconnectTimeoutInMinutes", "DownloadAllowed", "IdleDisconnectTimeoutInMinutes", "PasteAllowed", "PrintAllowed", "ToolbarConfiguration", "UploadAllowed", "UserSettingsArn", "WebAuthnAllowed"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-browser-settings":                {"BrowserSettingsArn": "*string", "PortalArn": "*string"},
			"associate-data-protection-settings":        {"DataProtectionSettingsArn": "*string", "PortalArn": "*string"},
			"associate-ip-access-settings":              {"IpAccessSettingsArn": "*string", "PortalArn": "*string"},
			"associate-network-settings":                {"NetworkSettingsArn": "*string", "PortalArn": "*string"},
			"associate-session-logger":                  {"PortalArn": "*string", "SessionLoggerArn": "*string"},
			"associate-trust-store":                     {"PortalArn": "*string", "TrustStoreArn": "*string"},
			"associate-user-access-logging-settings":    {"PortalArn": "*string", "UserAccessLoggingSettingsArn": "*string"},
			"associate-user-settings":                   {"PortalArn": "*string", "UserSettingsArn": "*string"},
			"create-browser-settings":                   {"AdditionalEncryptionContext": "map[string]string", "BrowserPolicy": "*string", "ClientToken": "*string", "CustomerManagedKey": "*string", "Tags": "[]types.Tag", "WebContentFilteringPolicy": "*types.WebContentFilteringPolicy"},
			"create-data-protection-settings":           {"AdditionalEncryptionContext": "map[string]string", "ClientToken": "*string", "CustomerManagedKey": "*string", "Description": "*string", "DisplayName": "*string", "InlineRedactionConfiguration": "*types.InlineRedactionConfiguration", "Tags": "[]types.Tag"},
			"create-identity-provider":                  {"ClientToken": "*string", "IdentityProviderDetails": "map[string]string", "IdentityProviderName": "*string", "IdentityProviderType": "types.IdentityProviderType", "PortalArn": "*string", "Tags": "[]types.Tag"},
			"create-ip-access-settings":                 {"AdditionalEncryptionContext": "map[string]string", "ClientToken": "*string", "CustomerManagedKey": "*string", "Description": "*string", "DisplayName": "*string", "IpRules": "[]types.IpRule", "Tags": "[]types.Tag"},
			"create-network-settings":                   {"ClientToken": "*string", "SecurityGroupIds": "[]string", "SubnetIds": "[]string", "Tags": "[]types.Tag", "VpcId": "*string"},
			"create-portal":                             {"AdditionalEncryptionContext": "map[string]string", "AuthenticationType": "types.AuthenticationType", "ClientToken": "*string", "CustomerManagedKey": "*string", "DisplayName": "*string", "InstanceType": "types.InstanceType", "MaxConcurrentSessions": "*int32", "PortalCustomDomain": "*string", "Tags": "[]types.Tag"},
			"create-session-logger":                     {"AdditionalEncryptionContext": "map[string]string", "ClientToken": "*string", "CustomerManagedKey": "*string", "DisplayName": "*string", "EventFilter": "types.EventFilter", "LogConfiguration": "*types.LogConfiguration", "Tags": "[]types.Tag"},
			"create-trust-store":                        {"CertificateList": "[][]byte", "ClientToken": "*string", "Tags": "[]types.Tag"},
			"create-user-access-logging-settings":       {"ClientToken": "*string", "KinesisStreamArn": "*string", "Tags": "[]types.Tag"},
			"create-user-settings":                      {"AdditionalEncryptionContext": "map[string]string", "BrandingConfigurationInput": "*types.BrandingConfigurationCreateInput", "ClientToken": "*string", "CookieSynchronizationConfiguration": "*types.CookieSynchronizationConfiguration", "CopyAllowed": "types.EnabledType", "CustomerManagedKey": "*string", "DeepLinkAllowed": "types.EnabledType", "DisconnectTimeoutInMinutes": "*int32", "DownloadAllowed": "types.EnabledType", "IdleDisconnectTimeoutInMinutes": "*int32", "PasteAllowed": "types.EnabledType", "PrintAllowed": "types.EnabledType", "Tags": "[]types.Tag", "ToolbarConfiguration": "*types.ToolbarConfiguration", "UploadAllowed": "types.EnabledType", "WebAuthnAllowed": "types.EnabledType"},
			"delete-browser-settings":                   {"BrowserSettingsArn": "*string"},
			"delete-data-protection-settings":           {"DataProtectionSettingsArn": "*string"},
			"delete-identity-provider":                  {"IdentityProviderArn": "*string"},
			"delete-ip-access-settings":                 {"IpAccessSettingsArn": "*string"},
			"delete-network-settings":                   {"NetworkSettingsArn": "*string"},
			"delete-portal":                             {"PortalArn": "*string"},
			"delete-session-logger":                     {"SessionLoggerArn": "*string"},
			"delete-trust-store":                        {"TrustStoreArn": "*string"},
			"delete-user-access-logging-settings":       {"UserAccessLoggingSettingsArn": "*string"},
			"delete-user-settings":                      {"UserSettingsArn": "*string"},
			"disassociate-browser-settings":             {"PortalArn": "*string"},
			"disassociate-data-protection-settings":     {"PortalArn": "*string"},
			"disassociate-ip-access-settings":           {"PortalArn": "*string"},
			"disassociate-network-settings":             {"PortalArn": "*string"},
			"disassociate-session-logger":               {"PortalArn": "*string"},
			"disassociate-trust-store":                  {"PortalArn": "*string"},
			"disassociate-user-access-logging-settings": {"PortalArn": "*string"},
			"disassociate-user-settings":                {"PortalArn": "*string"},
			"expire-session":                            {"PortalId": "*string", "SessionId": "*string"},
			"get-browser-settings":                      {"BrowserSettingsArn": "*string"},
			"get-data-protection-settings":              {"DataProtectionSettingsArn": "*string"},
			"get-identity-provider":                     {"IdentityProviderArn": "*string"},
			"get-ip-access-settings":                    {"IpAccessSettingsArn": "*string"},
			"get-network-settings":                      {"NetworkSettingsArn": "*string"},
			"get-portal":                                {"PortalArn": "*string"},
			"get-portal-service-provider-metadata":      {"PortalArn": "*string"},
			"get-session":                               {"PortalId": "*string", "SessionId": "*string"},
			"get-session-logger":                        {"SessionLoggerArn": "*string"},
			"get-trust-store":                           {"TrustStoreArn": "*string"},
			"get-trust-store-certificate":               {"Thumbprint": "*string", "TrustStoreArn": "*string"},
			"get-user-access-logging-settings":          {"UserAccessLoggingSettingsArn": "*string"},
			"get-user-settings":                         {"UserSettingsArn": "*string"},
			"list-browser-settings":                     {"MaxResults": "*int32", "NextToken": "*string"},
			"list-data-protection-settings":             {"MaxResults": "*int32", "NextToken": "*string"},
			"list-identity-providers":                   {"MaxResults": "*int32", "NextToken": "*string", "PortalArn": "*string"},
			"list-ip-access-settings":                   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-network-settings":                     {"MaxResults": "*int32", "NextToken": "*string"},
			"list-portals":                              {"MaxResults": "*int32", "NextToken": "*string"},
			"list-session-loggers":                      {"MaxResults": "*int32", "NextToken": "*string"},
			"list-sessions":                             {"MaxResults": "*int32", "NextToken": "*string", "PortalId": "*string", "SessionId": "*string", "SortBy": "types.SessionSortBy", "Status": "types.SessionStatus", "Username": "*string"},
			"list-tags-for-resource":                    {"ResourceArn": "*string"},
			"list-trust-store-certificates":             {"MaxResults": "*int32", "NextToken": "*string", "TrustStoreArn": "*string"},
			"list-trust-stores":                         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-user-access-logging-settings":         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-user-settings":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"tag-resource":                              {"ClientToken": "*string", "ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                            {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-browser-settings":                   {"BrowserPolicy": "*string", "BrowserSettingsArn": "*string", "ClientToken": "*string", "WebContentFilteringPolicy": "*types.WebContentFilteringPolicy"},
			"update-data-protection-settings":           {"ClientToken": "*string", "DataProtectionSettingsArn": "*string", "Description": "*string", "DisplayName": "*string", "InlineRedactionConfiguration": "*types.InlineRedactionConfiguration"},
			"update-identity-provider":                  {"ClientToken": "*string", "IdentityProviderArn": "*string", "IdentityProviderDetails": "map[string]string", "IdentityProviderName": "*string", "IdentityProviderType": "types.IdentityProviderType"},
			"update-ip-access-settings":                 {"ClientToken": "*string", "Description": "*string", "DisplayName": "*string", "IpAccessSettingsArn": "*string", "IpRules": "[]types.IpRule"},
			"update-network-settings":                   {"ClientToken": "*string", "NetworkSettingsArn": "*string", "SecurityGroupIds": "[]string", "SubnetIds": "[]string", "VpcId": "*string"},
			"update-portal":                             {"AuthenticationType": "types.AuthenticationType", "DisplayName": "*string", "InstanceType": "types.InstanceType", "MaxConcurrentSessions": "*int32", "PortalArn": "*string", "PortalCustomDomain": "*string"},
			"update-session-logger":                     {"DisplayName": "*string", "EventFilter": "types.EventFilter", "LogConfiguration": "*types.LogConfiguration", "SessionLoggerArn": "*string"},
			"update-trust-store":                        {"CertificatesToAdd": "[][]byte", "CertificatesToDelete": "[]string", "ClientToken": "*string", "TrustStoreArn": "*string"},
			"update-user-access-logging-settings":       {"ClientToken": "*string", "KinesisStreamArn": "*string", "UserAccessLoggingSettingsArn": "*string"},
			"update-user-settings":                      {"BrandingConfigurationInput": "*types.BrandingConfigurationUpdateInput", "ClientToken": "*string", "CookieSynchronizationConfiguration": "*types.CookieSynchronizationConfiguration", "CopyAllowed": "types.EnabledType", "DeepLinkAllowed": "types.EnabledType", "DisconnectTimeoutInMinutes": "*int32", "DownloadAllowed": "types.EnabledType", "IdleDisconnectTimeoutInMinutes": "*int32", "PasteAllowed": "types.EnabledType", "PrintAllowed": "types.EnabledType", "ToolbarConfiguration": "*types.ToolbarConfiguration", "UploadAllowed": "types.EnabledType", "UserSettingsArn": "*string", "WebAuthnAllowed": "types.EnabledType"},
		},
		OperationInputRequired: map[string][]string{
			"associate-browser-settings":                {"BrowserSettingsArn", "PortalArn"},
			"associate-data-protection-settings":        {"DataProtectionSettingsArn", "PortalArn"},
			"associate-ip-access-settings":              {"IpAccessSettingsArn", "PortalArn"},
			"associate-network-settings":                {"NetworkSettingsArn", "PortalArn"},
			"associate-session-logger":                  {"PortalArn", "SessionLoggerArn"},
			"associate-trust-store":                     {"PortalArn", "TrustStoreArn"},
			"associate-user-access-logging-settings":    {"PortalArn", "UserAccessLoggingSettingsArn"},
			"associate-user-settings":                   {"PortalArn", "UserSettingsArn"},
			"create-browser-settings":                   {},
			"create-data-protection-settings":           {},
			"create-identity-provider":                  {"IdentityProviderDetails", "IdentityProviderName", "IdentityProviderType", "PortalArn"},
			"create-ip-access-settings":                 {"IpRules"},
			"create-network-settings":                   {"SecurityGroupIds", "SubnetIds", "VpcId"},
			"create-portal":                             {},
			"create-session-logger":                     {"EventFilter", "LogConfiguration"},
			"create-trust-store":                        {"CertificateList"},
			"create-user-access-logging-settings":       {"KinesisStreamArn"},
			"create-user-settings":                      {"CopyAllowed", "DownloadAllowed", "PasteAllowed", "PrintAllowed", "UploadAllowed"},
			"delete-browser-settings":                   {"BrowserSettingsArn"},
			"delete-data-protection-settings":           {"DataProtectionSettingsArn"},
			"delete-identity-provider":                  {"IdentityProviderArn"},
			"delete-ip-access-settings":                 {"IpAccessSettingsArn"},
			"delete-network-settings":                   {"NetworkSettingsArn"},
			"delete-portal":                             {"PortalArn"},
			"delete-session-logger":                     {"SessionLoggerArn"},
			"delete-trust-store":                        {"TrustStoreArn"},
			"delete-user-access-logging-settings":       {"UserAccessLoggingSettingsArn"},
			"delete-user-settings":                      {"UserSettingsArn"},
			"disassociate-browser-settings":             {"PortalArn"},
			"disassociate-data-protection-settings":     {"PortalArn"},
			"disassociate-ip-access-settings":           {"PortalArn"},
			"disassociate-network-settings":             {"PortalArn"},
			"disassociate-session-logger":               {"PortalArn"},
			"disassociate-trust-store":                  {"PortalArn"},
			"disassociate-user-access-logging-settings": {"PortalArn"},
			"disassociate-user-settings":                {"PortalArn"},
			"expire-session":                            {"PortalId", "SessionId"},
			"get-browser-settings":                      {"BrowserSettingsArn"},
			"get-data-protection-settings":              {"DataProtectionSettingsArn"},
			"get-identity-provider":                     {"IdentityProviderArn"},
			"get-ip-access-settings":                    {"IpAccessSettingsArn"},
			"get-network-settings":                      {"NetworkSettingsArn"},
			"get-portal":                                {"PortalArn"},
			"get-portal-service-provider-metadata":      {"PortalArn"},
			"get-session":                               {"PortalId", "SessionId"},
			"get-session-logger":                        {"SessionLoggerArn"},
			"get-trust-store":                           {"TrustStoreArn"},
			"get-trust-store-certificate":               {"Thumbprint", "TrustStoreArn"},
			"get-user-access-logging-settings":          {"UserAccessLoggingSettingsArn"},
			"get-user-settings":                         {"UserSettingsArn"},
			"list-browser-settings":                     {},
			"list-data-protection-settings":             {},
			"list-identity-providers":                   {"PortalArn"},
			"list-ip-access-settings":                   {},
			"list-network-settings":                     {},
			"list-portals":                              {},
			"list-session-loggers":                      {},
			"list-sessions":                             {"PortalId"},
			"list-tags-for-resource":                    {"ResourceArn"},
			"list-trust-store-certificates":             {"TrustStoreArn"},
			"list-trust-stores":                         {},
			"list-user-access-logging-settings":         {},
			"list-user-settings":                        {},
			"tag-resource":                              {"ResourceArn", "Tags"},
			"untag-resource":                            {"ResourceArn", "TagKeys"},
			"update-browser-settings":                   {"BrowserSettingsArn"},
			"update-data-protection-settings":           {"DataProtectionSettingsArn"},
			"update-identity-provider":                  {"IdentityProviderArn"},
			"update-ip-access-settings":                 {"IpAccessSettingsArn"},
			"update-network-settings":                   {"NetworkSettingsArn"},
			"update-portal":                             {"PortalArn"},
			"update-session-logger":                     {"SessionLoggerArn"},
			"update-trust-store":                        {"TrustStoreArn"},
			"update-user-access-logging-settings":       {"UserAccessLoggingSettingsArn"},
			"update-user-settings":                      {"UserSettingsArn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("workspacesweb", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
