package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/guardduty/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-administrator-invitation", "accept-invitation", "archive-findings", "create-detector", "create-filter", "create-ip-set", "create-malware-protection-plan", "create-members", "create-publishing-destination", "create-sample-findings", "create-threat-entity-set", "create-threat-intel-set", "create-trusted-entity-set", "decline-invitations", "delete-detector", "delete-filter", "delete-invitations", "delete-ip-set", "delete-malware-protection-plan", "delete-members", "delete-publishing-destination", "delete-threat-entity-set", "delete-threat-intel-set", "delete-trusted-entity-set", "describe-malware-scans", "describe-organization-configuration", "describe-publishing-destination", "disable-organization-admin-account", "disassociate-from-administrator-account", "disassociate-from-master-account", "disassociate-members", "enable-organization-admin-account", "get-administrator-account", "get-coverage-statistics", "get-detector", "get-filter", "get-findings", "get-findings-statistics", "get-invitations-count", "get-ip-set", "get-malware-protection-plan", "get-malware-scan", "get-malware-scan-settings", "get-master-account", "get-member-detectors", "get-members", "get-organization-statistics", "get-remaining-free-trial-days", "get-threat-entity-set", "get-threat-intel-set", "get-trusted-entity-set", "get-usage-statistics", "invite-members", "list-coverage", "list-detectors", "list-filters", "list-findings", "list-invitations", "list-ip-sets", "list-malware-protection-plans", "list-malware-scans", "list-members", "list-organization-admin-accounts", "list-publishing-destinations", "list-tags-for-resource", "list-threat-entity-sets", "list-threat-intel-sets", "list-trusted-entity-sets", "send-object-malware-scan", "start-malware-scan", "start-monitoring-members", "stop-monitoring-members", "tag-resource", "unarchive-findings", "untag-resource", "update-detector", "update-filter", "update-findings-feedback", "update-ip-set", "update-malware-protection-plan", "update-malware-scan-settings", "update-member-detectors", "update-organization-configuration", "update-publishing-destination", "update-threat-entity-set", "update-threat-intel-set", "update-trusted-entity-set"},
		OperationSet: map[string]bool{"accept-administrator-invitation": true, "accept-invitation": true, "archive-findings": true, "create-detector": true, "create-filter": true, "create-ip-set": true, "create-malware-protection-plan": true, "create-members": true, "create-publishing-destination": true, "create-sample-findings": true, "create-threat-entity-set": true, "create-threat-intel-set": true, "create-trusted-entity-set": true, "decline-invitations": true, "delete-detector": true, "delete-filter": true, "delete-invitations": true, "delete-ip-set": true, "delete-malware-protection-plan": true, "delete-members": true, "delete-publishing-destination": true, "delete-threat-entity-set": true, "delete-threat-intel-set": true, "delete-trusted-entity-set": true, "describe-malware-scans": true, "describe-organization-configuration": true, "describe-publishing-destination": true, "disable-organization-admin-account": true, "disassociate-from-administrator-account": true, "disassociate-from-master-account": true, "disassociate-members": true, "enable-organization-admin-account": true, "get-administrator-account": true, "get-coverage-statistics": true, "get-detector": true, "get-filter": true, "get-findings": true, "get-findings-statistics": true, "get-invitations-count": true, "get-ip-set": true, "get-malware-protection-plan": true, "get-malware-scan": true, "get-malware-scan-settings": true, "get-master-account": true, "get-member-detectors": true, "get-members": true, "get-organization-statistics": true, "get-remaining-free-trial-days": true, "get-threat-entity-set": true, "get-threat-intel-set": true, "get-trusted-entity-set": true, "get-usage-statistics": true, "invite-members": true, "list-coverage": true, "list-detectors": true, "list-filters": true, "list-findings": true, "list-invitations": true, "list-ip-sets": true, "list-malware-protection-plans": true, "list-malware-scans": true, "list-members": true, "list-organization-admin-accounts": true, "list-publishing-destinations": true, "list-tags-for-resource": true, "list-threat-entity-sets": true, "list-threat-intel-sets": true, "list-trusted-entity-sets": true, "send-object-malware-scan": true, "start-malware-scan": true, "start-monitoring-members": true, "stop-monitoring-members": true, "tag-resource": true, "unarchive-findings": true, "untag-resource": true, "update-detector": true, "update-filter": true, "update-findings-feedback": true, "update-ip-set": true, "update-malware-protection-plan": true, "update-malware-scan-settings": true, "update-member-detectors": true, "update-organization-configuration": true, "update-publishing-destination": true, "update-threat-entity-set": true, "update-threat-intel-set": true, "update-trusted-entity-set": true},
		OperationInputs: map[string][]string{
			"accept-administrator-invitation":         {"AdministratorId", "DetectorId", "InvitationId"},
			"accept-invitation":                       {"DetectorId", "InvitationId", "MasterId"},
			"archive-findings":                        {"DetectorId", "FindingIds"},
			"create-detector":                         {"ClientToken", "DataSources", "Enable", "Features", "FindingPublishingFrequency", "Tags"},
			"create-filter":                           {"Action", "ClientToken", "Description", "DetectorId", "FindingCriteria", "Name", "Rank", "Tags"},
			"create-ip-set":                           {"Activate", "ClientToken", "DetectorId", "ExpectedBucketOwner", "Format", "Location", "Name", "Tags"},
			"create-malware-protection-plan":          {"Actions", "ClientToken", "ProtectedResource", "Role", "Tags"},
			"create-members":                          {"AccountDetails", "DetectorId"},
			"create-publishing-destination":           {"ClientToken", "DestinationProperties", "DestinationType", "DetectorId", "Tags"},
			"create-sample-findings":                  {"DetectorId", "FindingTypes"},
			"create-threat-entity-set":                {"Activate", "ClientToken", "DetectorId", "ExpectedBucketOwner", "Format", "Location", "Name", "Tags"},
			"create-threat-intel-set":                 {"Activate", "ClientToken", "DetectorId", "ExpectedBucketOwner", "Format", "Location", "Name", "Tags"},
			"create-trusted-entity-set":               {"Activate", "ClientToken", "DetectorId", "ExpectedBucketOwner", "Format", "Location", "Name", "Tags"},
			"decline-invitations":                     {"AccountIds"},
			"delete-detector":                         {"DetectorId"},
			"delete-filter":                           {"DetectorId", "FilterName"},
			"delete-invitations":                      {"AccountIds"},
			"delete-ip-set":                           {"DetectorId", "IpSetId"},
			"delete-malware-protection-plan":          {"MalwareProtectionPlanId"},
			"delete-members":                          {"AccountIds", "DetectorId"},
			"delete-publishing-destination":           {"DestinationId", "DetectorId"},
			"delete-threat-entity-set":                {"DetectorId", "ThreatEntitySetId"},
			"delete-threat-intel-set":                 {"DetectorId", "ThreatIntelSetId"},
			"delete-trusted-entity-set":               {"DetectorId", "TrustedEntitySetId"},
			"describe-malware-scans":                  {"DetectorId", "FilterCriteria", "MaxResults", "NextToken", "SortCriteria"},
			"describe-organization-configuration":     {"DetectorId", "MaxResults", "NextToken"},
			"describe-publishing-destination":         {"DestinationId", "DetectorId"},
			"disable-organization-admin-account":      {"AdminAccountId"},
			"disassociate-from-administrator-account": {"DetectorId"},
			"disassociate-from-master-account":        {"DetectorId"},
			"disassociate-members":                    {"AccountIds", "DetectorId"},
			"enable-organization-admin-account":       {"AdminAccountId"},
			"get-administrator-account":               {"DetectorId"},
			"get-coverage-statistics":                 {"DetectorId", "FilterCriteria", "StatisticsType"},
			"get-detector":                            {"DetectorId"},
			"get-filter":                              {"DetectorId", "FilterName"},
			"get-findings":                            {"DetectorId", "FindingIds", "SortCriteria"},
			"get-findings-statistics":                 {"DetectorId", "FindingCriteria", "FindingStatisticTypes", "GroupBy", "MaxResults", "OrderBy"},
			"get-invitations-count":                   {},
			"get-ip-set":                              {"DetectorId", "IpSetId"},
			"get-malware-protection-plan":             {"MalwareProtectionPlanId"},
			"get-malware-scan":                        {"ScanId"},
			"get-malware-scan-settings":               {"DetectorId"},
			"get-master-account":                      {"DetectorId"},
			"get-member-detectors":                    {"AccountIds", "DetectorId"},
			"get-members":                             {"AccountIds", "DetectorId"},
			"get-organization-statistics":             {},
			"get-remaining-free-trial-days":           {"AccountIds", "DetectorId"},
			"get-threat-entity-set":                   {"DetectorId", "ThreatEntitySetId"},
			"get-threat-intel-set":                    {"DetectorId", "ThreatIntelSetId"},
			"get-trusted-entity-set":                  {"DetectorId", "TrustedEntitySetId"},
			"get-usage-statistics":                    {"DetectorId", "MaxResults", "NextToken", "Unit", "UsageCriteria", "UsageStatisticType"},
			"invite-members":                          {"AccountIds", "DetectorId", "DisableEmailNotification", "Message"},
			"list-coverage":                           {"DetectorId", "FilterCriteria", "MaxResults", "NextToken", "SortCriteria"},
			"list-detectors":                          {"MaxResults", "NextToken"},
			"list-filters":                            {"DetectorId", "MaxResults", "NextToken"},
			"list-findings":                           {"DetectorId", "FindingCriteria", "MaxResults", "NextToken", "SortCriteria"},
			"list-invitations":                        {"MaxResults", "NextToken"},
			"list-ip-sets":                            {"DetectorId", "MaxResults", "NextToken"},
			"list-malware-protection-plans":           {"NextToken"},
			"list-malware-scans":                      {"FilterCriteria", "MaxResults", "NextToken", "SortCriteria"},
			"list-members":                            {"DetectorId", "MaxResults", "NextToken", "OnlyAssociated"},
			"list-organization-admin-accounts":        {"MaxResults", "NextToken"},
			"list-publishing-destinations":            {"DetectorId", "MaxResults", "NextToken"},
			"list-tags-for-resource":                  {"ResourceArn"},
			"list-threat-entity-sets":                 {"DetectorId", "MaxResults", "NextToken"},
			"list-threat-intel-sets":                  {"DetectorId", "MaxResults", "NextToken"},
			"list-trusted-entity-sets":                {"DetectorId", "MaxResults", "NextToken"},
			"send-object-malware-scan":                {"S3Object"},
			"start-malware-scan":                      {"ClientToken", "ResourceArn", "ScanConfiguration"},
			"start-monitoring-members":                {"AccountIds", "DetectorId"},
			"stop-monitoring-members":                 {"AccountIds", "DetectorId"},
			"tag-resource":                            {"ResourceArn", "Tags"},
			"unarchive-findings":                      {"DetectorId", "FindingIds"},
			"untag-resource":                          {"ResourceArn", "TagKeys"},
			"update-detector":                         {"DataSources", "DetectorId", "Enable", "Features", "FindingPublishingFrequency"},
			"update-filter":                           {"Action", "Description", "DetectorId", "FilterName", "FindingCriteria", "Rank"},
			"update-findings-feedback":                {"Comments", "DetectorId", "Feedback", "FindingIds"},
			"update-ip-set":                           {"Activate", "DetectorId", "ExpectedBucketOwner", "IpSetId", "Location", "Name"},
			"update-malware-protection-plan":          {"Actions", "MalwareProtectionPlanId", "ProtectedResource", "Role"},
			"update-malware-scan-settings":            {"DetectorId", "EbsSnapshotPreservation", "ScanResourceCriteria"},
			"update-member-detectors":                 {"AccountIds", "DataSources", "DetectorId", "Features"},
			"update-organization-configuration":       {"AutoEnable", "AutoEnableOrganizationMembers", "DataSources", "DetectorId", "Features"},
			"update-publishing-destination":           {"DestinationId", "DestinationProperties", "DetectorId"},
			"update-threat-entity-set":                {"Activate", "DetectorId", "ExpectedBucketOwner", "Location", "Name", "ThreatEntitySetId"},
			"update-threat-intel-set":                 {"Activate", "DetectorId", "ExpectedBucketOwner", "Location", "Name", "ThreatIntelSetId"},
			"update-trusted-entity-set":               {"Activate", "DetectorId", "ExpectedBucketOwner", "Location", "Name", "TrustedEntitySetId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-administrator-invitation":         {"AdministratorId": "*string", "DetectorId": "*string", "InvitationId": "*string"},
			"accept-invitation":                       {"DetectorId": "*string", "InvitationId": "*string", "MasterId": "*string"},
			"archive-findings":                        {"DetectorId": "*string", "FindingIds": "[]string"},
			"create-detector":                         {"ClientToken": "*string", "DataSources": "*types.DataSourceConfigurations", "Enable": "*bool", "Features": "[]types.DetectorFeatureConfiguration", "FindingPublishingFrequency": "types.FindingPublishingFrequency", "Tags": "map[string]string"},
			"create-filter":                           {"Action": "types.FilterAction", "ClientToken": "*string", "Description": "*string", "DetectorId": "*string", "FindingCriteria": "*types.FindingCriteria", "Name": "*string", "Rank": "*int32", "Tags": "map[string]string"},
			"create-ip-set":                           {"Activate": "*bool", "ClientToken": "*string", "DetectorId": "*string", "ExpectedBucketOwner": "*string", "Format": "types.IpSetFormat", "Location": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-malware-protection-plan":          {"Actions": "*types.MalwareProtectionPlanActions", "ClientToken": "*string", "ProtectedResource": "*types.CreateProtectedResource", "Role": "*string", "Tags": "map[string]string"},
			"create-members":                          {"AccountDetails": "[]types.AccountDetail", "DetectorId": "*string"},
			"create-publishing-destination":           {"ClientToken": "*string", "DestinationProperties": "*types.DestinationProperties", "DestinationType": "types.DestinationType", "DetectorId": "*string", "Tags": "map[string]string"},
			"create-sample-findings":                  {"DetectorId": "*string", "FindingTypes": "[]string"},
			"create-threat-entity-set":                {"Activate": "*bool", "ClientToken": "*string", "DetectorId": "*string", "ExpectedBucketOwner": "*string", "Format": "types.ThreatEntitySetFormat", "Location": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-threat-intel-set":                 {"Activate": "*bool", "ClientToken": "*string", "DetectorId": "*string", "ExpectedBucketOwner": "*string", "Format": "types.ThreatIntelSetFormat", "Location": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-trusted-entity-set":               {"Activate": "*bool", "ClientToken": "*string", "DetectorId": "*string", "ExpectedBucketOwner": "*string", "Format": "types.TrustedEntitySetFormat", "Location": "*string", "Name": "*string", "Tags": "map[string]string"},
			"decline-invitations":                     {"AccountIds": "[]string"},
			"delete-detector":                         {"DetectorId": "*string"},
			"delete-filter":                           {"DetectorId": "*string", "FilterName": "*string"},
			"delete-invitations":                      {"AccountIds": "[]string"},
			"delete-ip-set":                           {"DetectorId": "*string", "IpSetId": "*string"},
			"delete-malware-protection-plan":          {"MalwareProtectionPlanId": "*string"},
			"delete-members":                          {"AccountIds": "[]string", "DetectorId": "*string"},
			"delete-publishing-destination":           {"DestinationId": "*string", "DetectorId": "*string"},
			"delete-threat-entity-set":                {"DetectorId": "*string", "ThreatEntitySetId": "*string"},
			"delete-threat-intel-set":                 {"DetectorId": "*string", "ThreatIntelSetId": "*string"},
			"delete-trusted-entity-set":               {"DetectorId": "*string", "TrustedEntitySetId": "*string"},
			"describe-malware-scans":                  {"DetectorId": "*string", "FilterCriteria": "*types.FilterCriteria", "MaxResults": "*int32", "NextToken": "*string", "SortCriteria": "*types.SortCriteria"},
			"describe-organization-configuration":     {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-publishing-destination":         {"DestinationId": "*string", "DetectorId": "*string"},
			"disable-organization-admin-account":      {"AdminAccountId": "*string"},
			"disassociate-from-administrator-account": {"DetectorId": "*string"},
			"disassociate-from-master-account":        {"DetectorId": "*string"},
			"disassociate-members":                    {"AccountIds": "[]string", "DetectorId": "*string"},
			"enable-organization-admin-account":       {"AdminAccountId": "*string"},
			"get-administrator-account":               {"DetectorId": "*string"},
			"get-coverage-statistics":                 {"DetectorId": "*string", "FilterCriteria": "*types.CoverageFilterCriteria", "StatisticsType": "[]types.CoverageStatisticsType"},
			"get-detector":                            {"DetectorId": "*string"},
			"get-filter":                              {"DetectorId": "*string", "FilterName": "*string"},
			"get-findings":                            {"DetectorId": "*string", "FindingIds": "[]string", "SortCriteria": "*types.SortCriteria"},
			"get-findings-statistics":                 {"DetectorId": "*string", "FindingCriteria": "*types.FindingCriteria", "FindingStatisticTypes": "[]types.FindingStatisticType", "GroupBy": "types.GroupByType", "MaxResults": "*int32", "OrderBy": "types.OrderBy"},
			"get-invitations-count":                   {},
			"get-ip-set":                              {"DetectorId": "*string", "IpSetId": "*string"},
			"get-malware-protection-plan":             {"MalwareProtectionPlanId": "*string"},
			"get-malware-scan":                        {"ScanId": "*string"},
			"get-malware-scan-settings":               {"DetectorId": "*string"},
			"get-master-account":                      {"DetectorId": "*string"},
			"get-member-detectors":                    {"AccountIds": "[]string", "DetectorId": "*string"},
			"get-members":                             {"AccountIds": "[]string", "DetectorId": "*string"},
			"get-organization-statistics":             {},
			"get-remaining-free-trial-days":           {"AccountIds": "[]string", "DetectorId": "*string"},
			"get-threat-entity-set":                   {"DetectorId": "*string", "ThreatEntitySetId": "*string"},
			"get-threat-intel-set":                    {"DetectorId": "*string", "ThreatIntelSetId": "*string"},
			"get-trusted-entity-set":                  {"DetectorId": "*string", "TrustedEntitySetId": "*string"},
			"get-usage-statistics":                    {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string", "Unit": "*string", "UsageCriteria": "*types.UsageCriteria", "UsageStatisticType": "types.UsageStatisticType"},
			"invite-members":                          {"AccountIds": "[]string", "DetectorId": "*string", "DisableEmailNotification": "*bool", "Message": "*string"},
			"list-coverage":                           {"DetectorId": "*string", "FilterCriteria": "*types.CoverageFilterCriteria", "MaxResults": "*int32", "NextToken": "*string", "SortCriteria": "*types.CoverageSortCriteria"},
			"list-detectors":                          {"MaxResults": "*int32", "NextToken": "*string"},
			"list-filters":                            {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-findings":                           {"DetectorId": "*string", "FindingCriteria": "*types.FindingCriteria", "MaxResults": "*int32", "NextToken": "*string", "SortCriteria": "*types.SortCriteria"},
			"list-invitations":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-ip-sets":                            {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-malware-protection-plans":           {"NextToken": "*string"},
			"list-malware-scans":                      {"FilterCriteria": "*types.ListMalwareScansFilterCriteria", "MaxResults": "*int32", "NextToken": "*string", "SortCriteria": "*types.SortCriteria"},
			"list-members":                            {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string", "OnlyAssociated": "*string"},
			"list-organization-admin-accounts":        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-publishing-destinations":            {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                  {"ResourceArn": "*string"},
			"list-threat-entity-sets":                 {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-threat-intel-sets":                  {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-trusted-entity-sets":                {"DetectorId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"send-object-malware-scan":                {"S3Object": "*types.S3ObjectForSendObjectMalwareScan"},
			"start-malware-scan":                      {"ClientToken": "*string", "ResourceArn": "*string", "ScanConfiguration": "*types.StartMalwareScanConfiguration"},
			"start-monitoring-members":                {"AccountIds": "[]string", "DetectorId": "*string"},
			"stop-monitoring-members":                 {"AccountIds": "[]string", "DetectorId": "*string"},
			"tag-resource":                            {"ResourceArn": "*string", "Tags": "map[string]string"},
			"unarchive-findings":                      {"DetectorId": "*string", "FindingIds": "[]string"},
			"untag-resource":                          {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-detector":                         {"DataSources": "*types.DataSourceConfigurations", "DetectorId": "*string", "Enable": "*bool", "Features": "[]types.DetectorFeatureConfiguration", "FindingPublishingFrequency": "types.FindingPublishingFrequency"},
			"update-filter":                           {"Action": "types.FilterAction", "Description": "*string", "DetectorId": "*string", "FilterName": "*string", "FindingCriteria": "*types.FindingCriteria", "Rank": "*int32"},
			"update-findings-feedback":                {"Comments": "*string", "DetectorId": "*string", "Feedback": "types.Feedback", "FindingIds": "[]string"},
			"update-ip-set":                           {"Activate": "*bool", "DetectorId": "*string", "ExpectedBucketOwner": "*string", "IpSetId": "*string", "Location": "*string", "Name": "*string"},
			"update-malware-protection-plan":          {"Actions": "*types.MalwareProtectionPlanActions", "MalwareProtectionPlanId": "*string", "ProtectedResource": "*types.UpdateProtectedResource", "Role": "*string"},
			"update-malware-scan-settings":            {"DetectorId": "*string", "EbsSnapshotPreservation": "types.EbsSnapshotPreservation", "ScanResourceCriteria": "*types.ScanResourceCriteria"},
			"update-member-detectors":                 {"AccountIds": "[]string", "DataSources": "*types.DataSourceConfigurations", "DetectorId": "*string", "Features": "[]types.MemberFeaturesConfiguration"},
			"update-organization-configuration":       {"AutoEnable": "*bool", "AutoEnableOrganizationMembers": "types.AutoEnableMembers", "DataSources": "*types.OrganizationDataSourceConfigurations", "DetectorId": "*string", "Features": "[]types.OrganizationFeatureConfiguration"},
			"update-publishing-destination":           {"DestinationId": "*string", "DestinationProperties": "*types.DestinationProperties", "DetectorId": "*string"},
			"update-threat-entity-set":                {"Activate": "*bool", "DetectorId": "*string", "ExpectedBucketOwner": "*string", "Location": "*string", "Name": "*string", "ThreatEntitySetId": "*string"},
			"update-threat-intel-set":                 {"Activate": "*bool", "DetectorId": "*string", "ExpectedBucketOwner": "*string", "Location": "*string", "Name": "*string", "ThreatIntelSetId": "*string"},
			"update-trusted-entity-set":               {"Activate": "*bool", "DetectorId": "*string", "ExpectedBucketOwner": "*string", "Location": "*string", "Name": "*string", "TrustedEntitySetId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-administrator-invitation":         {"AdministratorId", "DetectorId", "InvitationId"},
			"accept-invitation":                       {"DetectorId", "InvitationId", "MasterId"},
			"archive-findings":                        {"DetectorId", "FindingIds"},
			"create-detector":                         {"Enable"},
			"create-filter":                           {"DetectorId", "FindingCriteria", "Name"},
			"create-ip-set":                           {"Activate", "DetectorId", "Format", "Location", "Name"},
			"create-malware-protection-plan":          {"ProtectedResource", "Role"},
			"create-members":                          {"AccountDetails", "DetectorId"},
			"create-publishing-destination":           {"DestinationProperties", "DestinationType", "DetectorId"},
			"create-sample-findings":                  {"DetectorId"},
			"create-threat-entity-set":                {"Activate", "DetectorId", "Format", "Location", "Name"},
			"create-threat-intel-set":                 {"Activate", "DetectorId", "Format", "Location", "Name"},
			"create-trusted-entity-set":               {"Activate", "DetectorId", "Format", "Location", "Name"},
			"decline-invitations":                     {"AccountIds"},
			"delete-detector":                         {"DetectorId"},
			"delete-filter":                           {"DetectorId", "FilterName"},
			"delete-invitations":                      {"AccountIds"},
			"delete-ip-set":                           {"DetectorId", "IpSetId"},
			"delete-malware-protection-plan":          {"MalwareProtectionPlanId"},
			"delete-members":                          {"AccountIds", "DetectorId"},
			"delete-publishing-destination":           {"DestinationId", "DetectorId"},
			"delete-threat-entity-set":                {"DetectorId", "ThreatEntitySetId"},
			"delete-threat-intel-set":                 {"DetectorId", "ThreatIntelSetId"},
			"delete-trusted-entity-set":               {"DetectorId", "TrustedEntitySetId"},
			"describe-malware-scans":                  {"DetectorId"},
			"describe-organization-configuration":     {"DetectorId"},
			"describe-publishing-destination":         {"DestinationId", "DetectorId"},
			"disable-organization-admin-account":      {"AdminAccountId"},
			"disassociate-from-administrator-account": {"DetectorId"},
			"disassociate-from-master-account":        {"DetectorId"},
			"disassociate-members":                    {"AccountIds", "DetectorId"},
			"enable-organization-admin-account":       {"AdminAccountId"},
			"get-administrator-account":               {"DetectorId"},
			"get-coverage-statistics":                 {"DetectorId", "StatisticsType"},
			"get-detector":                            {"DetectorId"},
			"get-filter":                              {"DetectorId", "FilterName"},
			"get-findings":                            {"DetectorId", "FindingIds"},
			"get-findings-statistics":                 {"DetectorId"},
			"get-invitations-count":                   {},
			"get-ip-set":                              {"DetectorId", "IpSetId"},
			"get-malware-protection-plan":             {"MalwareProtectionPlanId"},
			"get-malware-scan":                        {"ScanId"},
			"get-malware-scan-settings":               {"DetectorId"},
			"get-master-account":                      {"DetectorId"},
			"get-member-detectors":                    {"AccountIds", "DetectorId"},
			"get-members":                             {"AccountIds", "DetectorId"},
			"get-organization-statistics":             {},
			"get-remaining-free-trial-days":           {"AccountIds", "DetectorId"},
			"get-threat-entity-set":                   {"DetectorId", "ThreatEntitySetId"},
			"get-threat-intel-set":                    {"DetectorId", "ThreatIntelSetId"},
			"get-trusted-entity-set":                  {"DetectorId", "TrustedEntitySetId"},
			"get-usage-statistics":                    {"DetectorId", "UsageCriteria", "UsageStatisticType"},
			"invite-members":                          {"AccountIds", "DetectorId"},
			"list-coverage":                           {"DetectorId"},
			"list-detectors":                          {},
			"list-filters":                            {"DetectorId"},
			"list-findings":                           {"DetectorId"},
			"list-invitations":                        {},
			"list-ip-sets":                            {"DetectorId"},
			"list-malware-protection-plans":           {},
			"list-malware-scans":                      {},
			"list-members":                            {"DetectorId"},
			"list-organization-admin-accounts":        {},
			"list-publishing-destinations":            {"DetectorId"},
			"list-tags-for-resource":                  {"ResourceArn"},
			"list-threat-entity-sets":                 {"DetectorId"},
			"list-threat-intel-sets":                  {"DetectorId"},
			"list-trusted-entity-sets":                {"DetectorId"},
			"send-object-malware-scan":                {},
			"start-malware-scan":                      {"ResourceArn"},
			"start-monitoring-members":                {"AccountIds", "DetectorId"},
			"stop-monitoring-members":                 {"AccountIds", "DetectorId"},
			"tag-resource":                            {"ResourceArn", "Tags"},
			"unarchive-findings":                      {"DetectorId", "FindingIds"},
			"untag-resource":                          {"ResourceArn", "TagKeys"},
			"update-detector":                         {"DetectorId"},
			"update-filter":                           {"DetectorId", "FilterName"},
			"update-findings-feedback":                {"DetectorId", "Feedback", "FindingIds"},
			"update-ip-set":                           {"DetectorId", "IpSetId"},
			"update-malware-protection-plan":          {"MalwareProtectionPlanId"},
			"update-malware-scan-settings":            {"DetectorId"},
			"update-member-detectors":                 {"AccountIds", "DetectorId"},
			"update-organization-configuration":       {"DetectorId"},
			"update-publishing-destination":           {"DestinationId", "DetectorId"},
			"update-threat-entity-set":                {"DetectorId", "ThreatEntitySetId"},
			"update-threat-intel-set":                 {"DetectorId", "ThreatIntelSetId"},
			"update-trusted-entity-set":               {"DetectorId", "TrustedEntitySetId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("guardduty", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
