package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/resiliencehub/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-resource-grouping-recommendations", "add-draft-app-version-resource-mappings", "batch-update-recommendation-status", "create-app", "create-app-version-app-component", "create-app-version-resource", "create-recommendation-template", "create-resiliency-policy", "delete-app", "delete-app-assessment", "delete-app-input-source", "delete-app-version-app-component", "delete-app-version-resource", "delete-recommendation-template", "delete-resiliency-policy", "describe-app", "describe-app-assessment", "describe-app-version", "describe-app-version-app-component", "describe-app-version-resource", "describe-app-version-resources-resolution-status", "describe-app-version-template", "describe-draft-app-version-resources-import-status", "describe-metrics-export", "describe-resiliency-policy", "describe-resource-grouping-recommendation-task", "import-resources-to-draft-app-version", "list-alarm-recommendations", "list-app-assessment-compliance-drifts", "list-app-assessment-resource-drifts", "list-app-assessments", "list-app-component-compliances", "list-app-component-recommendations", "list-app-input-sources", "list-app-version-app-components", "list-app-version-resource-mappings", "list-app-version-resources", "list-app-versions", "list-apps", "list-metrics", "list-recommendation-templates", "list-resiliency-policies", "list-resource-grouping-recommendations", "list-sop-recommendations", "list-suggested-resiliency-policies", "list-tags-for-resource", "list-test-recommendations", "list-unsupported-app-version-resources", "publish-app-version", "put-draft-app-version-template", "reject-resource-grouping-recommendations", "remove-draft-app-version-resource-mappings", "resolve-app-version-resources", "start-app-assessment", "start-metrics-export", "start-resource-grouping-recommendation-task", "tag-resource", "untag-resource", "update-app", "update-app-version", "update-app-version-app-component", "update-app-version-resource", "update-resiliency-policy"},
		OperationSet: map[string]bool{"accept-resource-grouping-recommendations": true, "add-draft-app-version-resource-mappings": true, "batch-update-recommendation-status": true, "create-app": true, "create-app-version-app-component": true, "create-app-version-resource": true, "create-recommendation-template": true, "create-resiliency-policy": true, "delete-app": true, "delete-app-assessment": true, "delete-app-input-source": true, "delete-app-version-app-component": true, "delete-app-version-resource": true, "delete-recommendation-template": true, "delete-resiliency-policy": true, "describe-app": true, "describe-app-assessment": true, "describe-app-version": true, "describe-app-version-app-component": true, "describe-app-version-resource": true, "describe-app-version-resources-resolution-status": true, "describe-app-version-template": true, "describe-draft-app-version-resources-import-status": true, "describe-metrics-export": true, "describe-resiliency-policy": true, "describe-resource-grouping-recommendation-task": true, "import-resources-to-draft-app-version": true, "list-alarm-recommendations": true, "list-app-assessment-compliance-drifts": true, "list-app-assessment-resource-drifts": true, "list-app-assessments": true, "list-app-component-compliances": true, "list-app-component-recommendations": true, "list-app-input-sources": true, "list-app-version-app-components": true, "list-app-version-resource-mappings": true, "list-app-version-resources": true, "list-app-versions": true, "list-apps": true, "list-metrics": true, "list-recommendation-templates": true, "list-resiliency-policies": true, "list-resource-grouping-recommendations": true, "list-sop-recommendations": true, "list-suggested-resiliency-policies": true, "list-tags-for-resource": true, "list-test-recommendations": true, "list-unsupported-app-version-resources": true, "publish-app-version": true, "put-draft-app-version-template": true, "reject-resource-grouping-recommendations": true, "remove-draft-app-version-resource-mappings": true, "resolve-app-version-resources": true, "start-app-assessment": true, "start-metrics-export": true, "start-resource-grouping-recommendation-task": true, "tag-resource": true, "untag-resource": true, "update-app": true, "update-app-version": true, "update-app-version-app-component": true, "update-app-version-resource": true, "update-resiliency-policy": true},
		OperationInputs: map[string][]string{
			"accept-resource-grouping-recommendations":           {"AppArn", "Entries"},
			"add-draft-app-version-resource-mappings":            {"AppArn", "ResourceMappings"},
			"batch-update-recommendation-status":                 {"AppArn", "RequestEntries"},
			"create-app":                                         {"AssessmentSchedule", "AwsApplicationArn", "ClientToken", "Description", "EventSubscriptions", "Name", "PermissionModel", "PolicyArn", "Tags"},
			"create-app-version-app-component":                   {"AdditionalInfo", "AppArn", "ClientToken", "Id", "Name", "Type"},
			"create-app-version-resource":                        {"AdditionalInfo", "AppArn", "AppComponents", "AwsAccountId", "AwsRegion", "ClientToken", "LogicalResourceId", "PhysicalResourceId", "ResourceName", "ResourceType"},
			"create-recommendation-template":                     {"AssessmentArn", "BucketName", "ClientToken", "Format", "Name", "RecommendationIds", "RecommendationTypes", "Tags"},
			"create-resiliency-policy":                           {"ClientToken", "DataLocationConstraint", "Policy", "PolicyDescription", "PolicyName", "Tags", "Tier"},
			"delete-app":                                         {"AppArn", "ClientToken", "ForceDelete"},
			"delete-app-assessment":                              {"AssessmentArn", "ClientToken"},
			"delete-app-input-source":                            {"AppArn", "ClientToken", "EksSourceClusterNamespace", "SourceArn", "TerraformSource"},
			"delete-app-version-app-component":                   {"AppArn", "ClientToken", "Id"},
			"delete-app-version-resource":                        {"AppArn", "AwsAccountId", "AwsRegion", "ClientToken", "LogicalResourceId", "PhysicalResourceId", "ResourceName"},
			"delete-recommendation-template":                     {"ClientToken", "RecommendationTemplateArn"},
			"delete-resiliency-policy":                           {"ClientToken", "PolicyArn"},
			"describe-app":                                       {"AppArn"},
			"describe-app-assessment":                            {"AssessmentArn"},
			"describe-app-version":                               {"AppArn", "AppVersion"},
			"describe-app-version-app-component":                 {"AppArn", "AppVersion", "Id"},
			"describe-app-version-resource":                      {"AppArn", "AppVersion", "AwsAccountId", "AwsRegion", "LogicalResourceId", "PhysicalResourceId", "ResourceName"},
			"describe-app-version-resources-resolution-status":   {"AppArn", "AppVersion", "ResolutionId"},
			"describe-app-version-template":                      {"AppArn", "AppVersion"},
			"describe-draft-app-version-resources-import-status": {"AppArn"},
			"describe-metrics-export":                            {"MetricsExportId"},
			"describe-resiliency-policy":                         {"PolicyArn"},
			"describe-resource-grouping-recommendation-task":     {"AppArn", "GroupingId"},
			"import-resources-to-draft-app-version":              {"AppArn", "EksSources", "ImportStrategy", "SourceArns", "TerraformSources"},
			"list-alarm-recommendations":                         {"AssessmentArn", "MaxResults", "NextToken"},
			"list-app-assessment-compliance-drifts":              {"AssessmentArn", "MaxResults", "NextToken"},
			"list-app-assessment-resource-drifts":                {"AssessmentArn", "MaxResults", "NextToken"},
			"list-app-assessments":                               {"AppArn", "AssessmentName", "AssessmentStatus", "ComplianceStatus", "Invoker", "MaxResults", "NextToken", "ReverseOrder"},
			"list-app-component-compliances":                     {"AssessmentArn", "MaxResults", "NextToken"},
			"list-app-component-recommendations":                 {"AssessmentArn", "MaxResults", "NextToken"},
			"list-app-input-sources":                             {"AppArn", "AppVersion", "MaxResults", "NextToken"},
			"list-app-version-app-components":                    {"AppArn", "AppVersion", "MaxResults", "NextToken"},
			"list-app-version-resource-mappings":                 {"AppArn", "AppVersion", "MaxResults", "NextToken"},
			"list-app-version-resources":                         {"AppArn", "AppVersion", "MaxResults", "NextToken", "ResolutionId"},
			"list-app-versions":                                  {"AppArn", "EndTime", "MaxResults", "NextToken", "StartTime"},
			"list-apps":                                          {"AppArn", "AwsApplicationArn", "FromLastAssessmentTime", "MaxResults", "Name", "NextToken", "ReverseOrder", "ToLastAssessmentTime"},
			"list-metrics":                                       {"Conditions", "DataSource", "Fields", "MaxResults", "NextToken", "Sorts"},
			"list-recommendation-templates":                      {"AssessmentArn", "MaxResults", "Name", "NextToken", "RecommendationTemplateArn", "ReverseOrder", "Status"},
			"list-resiliency-policies":                           {"MaxResults", "NextToken", "PolicyName"},
			"list-resource-grouping-recommendations":             {"AppArn", "MaxResults", "NextToken"},
			"list-sop-recommendations":                           {"AssessmentArn", "MaxResults", "NextToken"},
			"list-suggested-resiliency-policies":                 {"MaxResults", "NextToken"},
			"list-tags-for-resource":                             {"ResourceArn"},
			"list-test-recommendations":                          {"AssessmentArn", "MaxResults", "NextToken"},
			"list-unsupported-app-version-resources":             {"AppArn", "AppVersion", "MaxResults", "NextToken", "ResolutionId"},
			"publish-app-version":                                {"AppArn", "VersionName"},
			"put-draft-app-version-template":                     {"AppArn", "AppTemplateBody"},
			"reject-resource-grouping-recommendations":           {"AppArn", "Entries"},
			"remove-draft-app-version-resource-mappings":         {"AppArn", "AppRegistryAppNames", "EksSourceNames", "LogicalStackNames", "ResourceGroupNames", "ResourceNames", "TerraformSourceNames"},
			"resolve-app-version-resources":                      {"AppArn", "AppVersion"},
			"start-app-assessment":                               {"AppArn", "AppVersion", "AssessmentName", "ClientToken", "Tags"},
			"start-metrics-export":                               {"BucketName", "ClientToken"},
			"start-resource-grouping-recommendation-task":        {"AppArn"},
			"tag-resource":                                       {"ResourceArn", "Tags"},
			"untag-resource":                                     {"ResourceArn", "TagKeys"},
			"update-app":                                         {"AppArn", "AssessmentSchedule", "ClearResiliencyPolicyArn", "Description", "EventSubscriptions", "PermissionModel", "PolicyArn"},
			"update-app-version":                                 {"AdditionalInfo", "AppArn"},
			"update-app-version-app-component":                   {"AdditionalInfo", "AppArn", "Id", "Name", "Type"},
			"update-app-version-resource":                        {"AdditionalInfo", "AppArn", "AppComponents", "AwsAccountId", "AwsRegion", "Excluded", "LogicalResourceId", "PhysicalResourceId", "ResourceName", "ResourceType"},
			"update-resiliency-policy":                           {"DataLocationConstraint", "Policy", "PolicyArn", "PolicyDescription", "PolicyName", "Tier"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-resource-grouping-recommendations":           {"AppArn": "*string", "Entries": "[]types.AcceptGroupingRecommendationEntry"},
			"add-draft-app-version-resource-mappings":            {"AppArn": "*string", "ResourceMappings": "[]types.ResourceMapping"},
			"batch-update-recommendation-status":                 {"AppArn": "*string", "RequestEntries": "[]types.UpdateRecommendationStatusRequestEntry"},
			"create-app":                                         {"AssessmentSchedule": "types.AppAssessmentScheduleType", "AwsApplicationArn": "*string", "ClientToken": "*string", "Description": "*string", "EventSubscriptions": "[]types.EventSubscription", "Name": "*string", "PermissionModel": "*types.PermissionModel", "PolicyArn": "*string", "Tags": "map[string]string"},
			"create-app-version-app-component":                   {"AdditionalInfo": "map[string][]string", "AppArn": "*string", "ClientToken": "*string", "Id": "*string", "Name": "*string", "Type": "*string"},
			"create-app-version-resource":                        {"AdditionalInfo": "map[string][]string", "AppArn": "*string", "AppComponents": "[]string", "AwsAccountId": "*string", "AwsRegion": "*string", "ClientToken": "*string", "LogicalResourceId": "*types.LogicalResourceId", "PhysicalResourceId": "*string", "ResourceName": "*string", "ResourceType": "*string"},
			"create-recommendation-template":                     {"AssessmentArn": "*string", "BucketName": "*string", "ClientToken": "*string", "Format": "types.TemplateFormat", "Name": "*string", "RecommendationIds": "[]string", "RecommendationTypes": "[]types.RenderRecommendationType", "Tags": "map[string]string"},
			"create-resiliency-policy":                           {"ClientToken": "*string", "DataLocationConstraint": "types.DataLocationConstraint", "Policy": "map[string]types.FailurePolicy", "PolicyDescription": "*string", "PolicyName": "*string", "Tags": "map[string]string", "Tier": "types.ResiliencyPolicyTier"},
			"delete-app":                                         {"AppArn": "*string", "ClientToken": "*string", "ForceDelete": "*bool"},
			"delete-app-assessment":                              {"AssessmentArn": "*string", "ClientToken": "*string"},
			"delete-app-input-source":                            {"AppArn": "*string", "ClientToken": "*string", "EksSourceClusterNamespace": "*types.EksSourceClusterNamespace", "SourceArn": "*string", "TerraformSource": "*types.TerraformSource"},
			"delete-app-version-app-component":                   {"AppArn": "*string", "ClientToken": "*string", "Id": "*string"},
			"delete-app-version-resource":                        {"AppArn": "*string", "AwsAccountId": "*string", "AwsRegion": "*string", "ClientToken": "*string", "LogicalResourceId": "*types.LogicalResourceId", "PhysicalResourceId": "*string", "ResourceName": "*string"},
			"delete-recommendation-template":                     {"ClientToken": "*string", "RecommendationTemplateArn": "*string"},
			"delete-resiliency-policy":                           {"ClientToken": "*string", "PolicyArn": "*string"},
			"describe-app":                                       {"AppArn": "*string"},
			"describe-app-assessment":                            {"AssessmentArn": "*string"},
			"describe-app-version":                               {"AppArn": "*string", "AppVersion": "*string"},
			"describe-app-version-app-component":                 {"AppArn": "*string", "AppVersion": "*string", "Id": "*string"},
			"describe-app-version-resource":                      {"AppArn": "*string", "AppVersion": "*string", "AwsAccountId": "*string", "AwsRegion": "*string", "LogicalResourceId": "*types.LogicalResourceId", "PhysicalResourceId": "*string", "ResourceName": "*string"},
			"describe-app-version-resources-resolution-status":   {"AppArn": "*string", "AppVersion": "*string", "ResolutionId": "*string"},
			"describe-app-version-template":                      {"AppArn": "*string", "AppVersion": "*string"},
			"describe-draft-app-version-resources-import-status": {"AppArn": "*string"},
			"describe-metrics-export":                            {"MetricsExportId": "*string"},
			"describe-resiliency-policy":                         {"PolicyArn": "*string"},
			"describe-resource-grouping-recommendation-task":     {"AppArn": "*string", "GroupingId": "*string"},
			"import-resources-to-draft-app-version":              {"AppArn": "*string", "EksSources": "[]types.EksSource", "ImportStrategy": "types.ResourceImportStrategyType", "SourceArns": "[]string", "TerraformSources": "[]types.TerraformSource"},
			"list-alarm-recommendations":                         {"AssessmentArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-assessment-compliance-drifts":              {"AssessmentArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-assessment-resource-drifts":                {"AssessmentArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-assessments":                               {"AppArn": "*string", "AssessmentName": "*string", "AssessmentStatus": "[]types.AssessmentStatus", "ComplianceStatus": "types.ComplianceStatus", "Invoker": "types.AssessmentInvoker", "MaxResults": "*int32", "NextToken": "*string", "ReverseOrder": "*bool"},
			"list-app-component-compliances":                     {"AssessmentArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-component-recommendations":                 {"AssessmentArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-input-sources":                             {"AppArn": "*string", "AppVersion": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-version-app-components":                    {"AppArn": "*string", "AppVersion": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-version-resource-mappings":                 {"AppArn": "*string", "AppVersion": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-app-version-resources":                         {"AppArn": "*string", "AppVersion": "*string", "MaxResults": "*int32", "NextToken": "*string", "ResolutionId": "*string"},
			"list-app-versions":                                  {"AppArn": "*string", "EndTime": "*time.Time", "MaxResults": "*int32", "NextToken": "*string", "StartTime": "*time.Time"},
			"list-apps":                                          {"AppArn": "*string", "AwsApplicationArn": "*string", "FromLastAssessmentTime": "*time.Time", "MaxResults": "*int32", "Name": "*string", "NextToken": "*string", "ReverseOrder": "*bool", "ToLastAssessmentTime": "*time.Time"},
			"list-metrics":                                       {"Conditions": "[]types.Condition", "DataSource": "*string", "Fields": "[]types.Field", "MaxResults": "*int32", "NextToken": "*string", "Sorts": "[]types.Sort"},
			"list-recommendation-templates":                      {"AssessmentArn": "*string", "MaxResults": "*int32", "Name": "*string", "NextToken": "*string", "RecommendationTemplateArn": "*string", "ReverseOrder": "*bool", "Status": "[]types.RecommendationTemplateStatus"},
			"list-resiliency-policies":                           {"MaxResults": "*int32", "NextToken": "*string", "PolicyName": "*string"},
			"list-resource-grouping-recommendations":             {"AppArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-sop-recommendations":                           {"AssessmentArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-suggested-resiliency-policies":                 {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                             {"ResourceArn": "*string"},
			"list-test-recommendations":                          {"AssessmentArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-unsupported-app-version-resources":             {"AppArn": "*string", "AppVersion": "*string", "MaxResults": "*int32", "NextToken": "*string", "ResolutionId": "*string"},
			"publish-app-version":                                {"AppArn": "*string", "VersionName": "*string"},
			"put-draft-app-version-template":                     {"AppArn": "*string", "AppTemplateBody": "*string"},
			"reject-resource-grouping-recommendations":           {"AppArn": "*string", "Entries": "[]types.RejectGroupingRecommendationEntry"},
			"remove-draft-app-version-resource-mappings":         {"AppArn": "*string", "AppRegistryAppNames": "[]string", "EksSourceNames": "[]string", "LogicalStackNames": "[]string", "ResourceGroupNames": "[]string", "ResourceNames": "[]string", "TerraformSourceNames": "[]string"},
			"resolve-app-version-resources":                      {"AppArn": "*string", "AppVersion": "*string"},
			"start-app-assessment":                               {"AppArn": "*string", "AppVersion": "*string", "AssessmentName": "*string", "ClientToken": "*string", "Tags": "map[string]string"},
			"start-metrics-export":                               {"BucketName": "*string", "ClientToken": "*string"},
			"start-resource-grouping-recommendation-task":        {"AppArn": "*string"},
			"tag-resource":                                       {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                                     {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-app":                                         {"AppArn": "*string", "AssessmentSchedule": "types.AppAssessmentScheduleType", "ClearResiliencyPolicyArn": "*bool", "Description": "*string", "EventSubscriptions": "[]types.EventSubscription", "PermissionModel": "*types.PermissionModel", "PolicyArn": "*string"},
			"update-app-version":                                 {"AdditionalInfo": "map[string][]string", "AppArn": "*string"},
			"update-app-version-app-component":                   {"AdditionalInfo": "map[string][]string", "AppArn": "*string", "Id": "*string", "Name": "*string", "Type": "*string"},
			"update-app-version-resource":                        {"AdditionalInfo": "map[string][]string", "AppArn": "*string", "AppComponents": "[]string", "AwsAccountId": "*string", "AwsRegion": "*string", "Excluded": "*bool", "LogicalResourceId": "*types.LogicalResourceId", "PhysicalResourceId": "*string", "ResourceName": "*string", "ResourceType": "*string"},
			"update-resiliency-policy":                           {"DataLocationConstraint": "types.DataLocationConstraint", "Policy": "map[string]types.FailurePolicy", "PolicyArn": "*string", "PolicyDescription": "*string", "PolicyName": "*string", "Tier": "types.ResiliencyPolicyTier"},
		},
		OperationInputRequired: map[string][]string{
			"accept-resource-grouping-recommendations":           {"AppArn", "Entries"},
			"add-draft-app-version-resource-mappings":            {"AppArn", "ResourceMappings"},
			"batch-update-recommendation-status":                 {"AppArn", "RequestEntries"},
			"create-app":                                         {"Name"},
			"create-app-version-app-component":                   {"AppArn", "Name", "Type"},
			"create-app-version-resource":                        {"AppArn", "AppComponents", "LogicalResourceId", "PhysicalResourceId", "ResourceType"},
			"create-recommendation-template":                     {"AssessmentArn", "Name"},
			"create-resiliency-policy":                           {"Policy", "PolicyName", "Tier"},
			"delete-app":                                         {"AppArn"},
			"delete-app-assessment":                              {"AssessmentArn"},
			"delete-app-input-source":                            {"AppArn"},
			"delete-app-version-app-component":                   {"AppArn", "Id"},
			"delete-app-version-resource":                        {"AppArn"},
			"delete-recommendation-template":                     {"RecommendationTemplateArn"},
			"delete-resiliency-policy":                           {"PolicyArn"},
			"describe-app":                                       {"AppArn"},
			"describe-app-assessment":                            {"AssessmentArn"},
			"describe-app-version":                               {"AppArn", "AppVersion"},
			"describe-app-version-app-component":                 {"AppArn", "AppVersion", "Id"},
			"describe-app-version-resource":                      {"AppArn", "AppVersion"},
			"describe-app-version-resources-resolution-status":   {"AppArn", "AppVersion"},
			"describe-app-version-template":                      {"AppArn", "AppVersion"},
			"describe-draft-app-version-resources-import-status": {"AppArn"},
			"describe-metrics-export":                            {"MetricsExportId"},
			"describe-resiliency-policy":                         {"PolicyArn"},
			"describe-resource-grouping-recommendation-task":     {"AppArn"},
			"import-resources-to-draft-app-version":              {"AppArn"},
			"list-alarm-recommendations":                         {"AssessmentArn"},
			"list-app-assessment-compliance-drifts":              {"AssessmentArn"},
			"list-app-assessment-resource-drifts":                {"AssessmentArn"},
			"list-app-assessments":                               {},
			"list-app-component-compliances":                     {"AssessmentArn"},
			"list-app-component-recommendations":                 {"AssessmentArn"},
			"list-app-input-sources":                             {"AppArn", "AppVersion"},
			"list-app-version-app-components":                    {"AppArn", "AppVersion"},
			"list-app-version-resource-mappings":                 {"AppArn", "AppVersion"},
			"list-app-version-resources":                         {"AppArn", "AppVersion"},
			"list-app-versions":                                  {"AppArn"},
			"list-apps":                                          {},
			"list-metrics":                                       {},
			"list-recommendation-templates":                      {},
			"list-resiliency-policies":                           {},
			"list-resource-grouping-recommendations":             {},
			"list-sop-recommendations":                           {"AssessmentArn"},
			"list-suggested-resiliency-policies":                 {},
			"list-tags-for-resource":                             {"ResourceArn"},
			"list-test-recommendations":                          {"AssessmentArn"},
			"list-unsupported-app-version-resources":             {"AppArn", "AppVersion"},
			"publish-app-version":                                {"AppArn"},
			"put-draft-app-version-template":                     {"AppArn", "AppTemplateBody"},
			"reject-resource-grouping-recommendations":           {"AppArn", "Entries"},
			"remove-draft-app-version-resource-mappings":         {"AppArn"},
			"resolve-app-version-resources":                      {"AppArn", "AppVersion"},
			"start-app-assessment":                               {"AppArn", "AppVersion", "AssessmentName"},
			"start-metrics-export":                               {},
			"start-resource-grouping-recommendation-task":        {"AppArn"},
			"tag-resource":                                       {"ResourceArn", "Tags"},
			"untag-resource":                                     {"ResourceArn", "TagKeys"},
			"update-app":                                         {"AppArn"},
			"update-app-version":                                 {"AppArn"},
			"update-app-version-app-component":                   {"AppArn", "Id"},
			"update-app-version-resource":                        {"AppArn"},
			"update-resiliency-policy":                           {"PolicyArn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("resiliencehub", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
