package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/ssoadmin/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-region", "attach-customer-managed-policy-reference-to-permission-set", "attach-managed-policy-to-permission-set", "create-account-assignment", "create-application", "create-application-assignment", "create-instance", "create-instance-access-control-attribute-configuration", "create-permission-set", "create-trusted-token-issuer", "delete-account-assignment", "delete-application", "delete-application-access-scope", "delete-application-assignment", "delete-application-authentication-method", "delete-application-grant", "delete-inline-policy-from-permission-set", "delete-instance", "delete-instance-access-control-attribute-configuration", "delete-permission-set", "delete-permissions-boundary-from-permission-set", "delete-trusted-token-issuer", "describe-account-assignment-creation-status", "describe-account-assignment-deletion-status", "describe-application", "describe-application-assignment", "describe-application-provider", "describe-instance", "describe-instance-access-control-attribute-configuration", "describe-permission-set", "describe-permission-set-provisioning-status", "describe-region", "describe-trusted-token-issuer", "detach-customer-managed-policy-reference-from-permission-set", "detach-managed-policy-from-permission-set", "get-application-access-scope", "get-application-assignment-configuration", "get-application-authentication-method", "get-application-grant", "get-application-session-configuration", "get-inline-policy-for-permission-set", "get-permissions-boundary-for-permission-set", "list-account-assignment-creation-status", "list-account-assignment-deletion-status", "list-account-assignments", "list-account-assignments-for-principal", "list-accounts-for-provisioned-permission-set", "list-application-access-scopes", "list-application-assignments", "list-application-assignments-for-principal", "list-application-authentication-methods", "list-application-grants", "list-application-providers", "list-applications", "list-customer-managed-policy-references-in-permission-set", "list-instances", "list-managed-policies-in-permission-set", "list-permission-set-provisioning-status", "list-permission-sets", "list-permission-sets-provisioned-to-account", "list-regions", "list-tags-for-resource", "list-trusted-token-issuers", "provision-permission-set", "put-application-access-scope", "put-application-assignment-configuration", "put-application-authentication-method", "put-application-grant", "put-application-session-configuration", "put-inline-policy-to-permission-set", "put-permissions-boundary-to-permission-set", "remove-region", "tag-resource", "untag-resource", "update-application", "update-instance", "update-instance-access-control-attribute-configuration", "update-permission-set", "update-trusted-token-issuer"},
		OperationSet: map[string]bool{"add-region": true, "attach-customer-managed-policy-reference-to-permission-set": true, "attach-managed-policy-to-permission-set": true, "create-account-assignment": true, "create-application": true, "create-application-assignment": true, "create-instance": true, "create-instance-access-control-attribute-configuration": true, "create-permission-set": true, "create-trusted-token-issuer": true, "delete-account-assignment": true, "delete-application": true, "delete-application-access-scope": true, "delete-application-assignment": true, "delete-application-authentication-method": true, "delete-application-grant": true, "delete-inline-policy-from-permission-set": true, "delete-instance": true, "delete-instance-access-control-attribute-configuration": true, "delete-permission-set": true, "delete-permissions-boundary-from-permission-set": true, "delete-trusted-token-issuer": true, "describe-account-assignment-creation-status": true, "describe-account-assignment-deletion-status": true, "describe-application": true, "describe-application-assignment": true, "describe-application-provider": true, "describe-instance": true, "describe-instance-access-control-attribute-configuration": true, "describe-permission-set": true, "describe-permission-set-provisioning-status": true, "describe-region": true, "describe-trusted-token-issuer": true, "detach-customer-managed-policy-reference-from-permission-set": true, "detach-managed-policy-from-permission-set": true, "get-application-access-scope": true, "get-application-assignment-configuration": true, "get-application-authentication-method": true, "get-application-grant": true, "get-application-session-configuration": true, "get-inline-policy-for-permission-set": true, "get-permissions-boundary-for-permission-set": true, "list-account-assignment-creation-status": true, "list-account-assignment-deletion-status": true, "list-account-assignments": true, "list-account-assignments-for-principal": true, "list-accounts-for-provisioned-permission-set": true, "list-application-access-scopes": true, "list-application-assignments": true, "list-application-assignments-for-principal": true, "list-application-authentication-methods": true, "list-application-grants": true, "list-application-providers": true, "list-applications": true, "list-customer-managed-policy-references-in-permission-set": true, "list-instances": true, "list-managed-policies-in-permission-set": true, "list-permission-set-provisioning-status": true, "list-permission-sets": true, "list-permission-sets-provisioned-to-account": true, "list-regions": true, "list-tags-for-resource": true, "list-trusted-token-issuers": true, "provision-permission-set": true, "put-application-access-scope": true, "put-application-assignment-configuration": true, "put-application-authentication-method": true, "put-application-grant": true, "put-application-session-configuration": true, "put-inline-policy-to-permission-set": true, "put-permissions-boundary-to-permission-set": true, "remove-region": true, "tag-resource": true, "untag-resource": true, "update-application": true, "update-instance": true, "update-instance-access-control-attribute-configuration": true, "update-permission-set": true, "update-trusted-token-issuer": true},
		OperationInputs: map[string][]string{
			"add-region": {"InstanceArn", "RegionName"},
			"attach-customer-managed-policy-reference-to-permission-set":   {"CustomerManagedPolicyReference", "InstanceArn", "PermissionSetArn"},
			"attach-managed-policy-to-permission-set":                      {"InstanceArn", "ManagedPolicyArn", "PermissionSetArn"},
			"create-account-assignment":                                    {"InstanceArn", "PermissionSetArn", "PrincipalId", "PrincipalType", "TargetId", "TargetType"},
			"create-application":                                           {"ApplicationProviderArn", "ClientToken", "Description", "InstanceArn", "Name", "PortalOptions", "Status", "Tags"},
			"create-application-assignment":                                {"ApplicationArn", "PrincipalId", "PrincipalType"},
			"create-instance":                                              {"ClientToken", "Name", "Tags"},
			"create-instance-access-control-attribute-configuration":       {"InstanceAccessControlAttributeConfiguration", "InstanceArn"},
			"create-permission-set":                                        {"Description", "InstanceArn", "Name", "RelayState", "SessionDuration", "Tags"},
			"create-trusted-token-issuer":                                  {"ClientToken", "InstanceArn", "Name", "Tags", "TrustedTokenIssuerConfiguration", "TrustedTokenIssuerType"},
			"delete-account-assignment":                                    {"InstanceArn", "PermissionSetArn", "PrincipalId", "PrincipalType", "TargetId", "TargetType"},
			"delete-application":                                           {"ApplicationArn"},
			"delete-application-access-scope":                              {"ApplicationArn", "Scope"},
			"delete-application-assignment":                                {"ApplicationArn", "PrincipalId", "PrincipalType"},
			"delete-application-authentication-method":                     {"ApplicationArn", "AuthenticationMethodType"},
			"delete-application-grant":                                     {"ApplicationArn", "GrantType"},
			"delete-inline-policy-from-permission-set":                     {"InstanceArn", "PermissionSetArn"},
			"delete-instance":                                              {"InstanceArn"},
			"delete-instance-access-control-attribute-configuration":       {"InstanceArn"},
			"delete-permission-set":                                        {"InstanceArn", "PermissionSetArn"},
			"delete-permissions-boundary-from-permission-set":              {"InstanceArn", "PermissionSetArn"},
			"delete-trusted-token-issuer":                                  {"TrustedTokenIssuerArn"},
			"describe-account-assignment-creation-status":                  {"AccountAssignmentCreationRequestId", "InstanceArn"},
			"describe-account-assignment-deletion-status":                  {"AccountAssignmentDeletionRequestId", "InstanceArn"},
			"describe-application":                                         {"ApplicationArn"},
			"describe-application-assignment":                              {"ApplicationArn", "PrincipalId", "PrincipalType"},
			"describe-application-provider":                                {"ApplicationProviderArn"},
			"describe-instance":                                            {"InstanceArn"},
			"describe-instance-access-control-attribute-configuration":     {"InstanceArn"},
			"describe-permission-set":                                      {"InstanceArn", "PermissionSetArn"},
			"describe-permission-set-provisioning-status":                  {"InstanceArn", "ProvisionPermissionSetRequestId"},
			"describe-region":                                              {"InstanceArn", "RegionName"},
			"describe-trusted-token-issuer":                                {"TrustedTokenIssuerArn"},
			"detach-customer-managed-policy-reference-from-permission-set": {"CustomerManagedPolicyReference", "InstanceArn", "PermissionSetArn"},
			"detach-managed-policy-from-permission-set":                    {"InstanceArn", "ManagedPolicyArn", "PermissionSetArn"},
			"get-application-access-scope":                                 {"ApplicationArn", "Scope"},
			"get-application-assignment-configuration":                     {"ApplicationArn"},
			"get-application-authentication-method":                        {"ApplicationArn", "AuthenticationMethodType"},
			"get-application-grant":                                        {"ApplicationArn", "GrantType"},
			"get-application-session-configuration":                        {"ApplicationArn"},
			"get-inline-policy-for-permission-set":                         {"InstanceArn", "PermissionSetArn"},
			"get-permissions-boundary-for-permission-set":                  {"InstanceArn", "PermissionSetArn"},
			"list-account-assignment-creation-status":                      {"Filter", "InstanceArn", "MaxResults", "NextToken"},
			"list-account-assignment-deletion-status":                      {"Filter", "InstanceArn", "MaxResults", "NextToken"},
			"list-account-assignments":                                     {"AccountId", "InstanceArn", "MaxResults", "NextToken", "PermissionSetArn"},
			"list-account-assignments-for-principal":                       {"Filter", "InstanceArn", "MaxResults", "NextToken", "PrincipalId", "PrincipalType"},
			"list-accounts-for-provisioned-permission-set":                 {"InstanceArn", "MaxResults", "NextToken", "PermissionSetArn", "ProvisioningStatus"},
			"list-application-access-scopes":                               {"ApplicationArn", "MaxResults", "NextToken"},
			"list-application-assignments":                                 {"ApplicationArn", "MaxResults", "NextToken"},
			"list-application-assignments-for-principal":                   {"Filter", "InstanceArn", "MaxResults", "NextToken", "PrincipalId", "PrincipalType"},
			"list-application-authentication-methods":                      {"ApplicationArn", "NextToken"},
			"list-application-grants":                                      {"ApplicationArn", "NextToken"},
			"list-application-providers":                                   {"MaxResults", "NextToken"},
			"list-applications":                                            {"Filter", "InstanceArn", "MaxResults", "NextToken"},
			"list-customer-managed-policy-references-in-permission-set":    {"InstanceArn", "MaxResults", "NextToken", "PermissionSetArn"},
			"list-instances":                                               {"MaxResults", "NextToken"},
			"list-managed-policies-in-permission-set":                      {"InstanceArn", "MaxResults", "NextToken", "PermissionSetArn"},
			"list-permission-set-provisioning-status":                      {"Filter", "InstanceArn", "MaxResults", "NextToken"},
			"list-permission-sets":                                         {"InstanceArn", "MaxResults", "NextToken"},
			"list-permission-sets-provisioned-to-account":                  {"AccountId", "InstanceArn", "MaxResults", "NextToken", "ProvisioningStatus"},
			"list-regions":                                                 {"InstanceArn", "MaxResults", "NextToken"},
			"list-tags-for-resource":                                       {"InstanceArn", "NextToken", "ResourceArn"},
			"list-trusted-token-issuers":                                   {"InstanceArn", "MaxResults", "NextToken"},
			"provision-permission-set":                                     {"InstanceArn", "PermissionSetArn", "TargetId", "TargetType"},
			"put-application-access-scope":                                 {"ApplicationArn", "AuthorizedTargets", "Scope"},
			"put-application-assignment-configuration":                     {"ApplicationArn", "AssignmentRequired"},
			"put-application-authentication-method":                        {"ApplicationArn", "AuthenticationMethod", "AuthenticationMethodType"},
			"put-application-grant":                                        {"ApplicationArn", "Grant", "GrantType"},
			"put-application-session-configuration":                        {"ApplicationArn", "UserBackgroundSessionApplicationStatus"},
			"put-inline-policy-to-permission-set":                          {"InlinePolicy", "InstanceArn", "PermissionSetArn"},
			"put-permissions-boundary-to-permission-set":                   {"InstanceArn", "PermissionSetArn", "PermissionsBoundary"},
			"remove-region":                                                {"InstanceArn", "RegionName"},
			"tag-resource":                                                 {"InstanceArn", "ResourceArn", "Tags"},
			"untag-resource":                                               {"InstanceArn", "ResourceArn", "TagKeys"},
			"update-application":                                           {"ApplicationArn", "Description", "Name", "PortalOptions", "Status"},
			"update-instance":                                              {"EncryptionConfiguration", "InstanceArn", "Name"},
			"update-instance-access-control-attribute-configuration":       {"InstanceAccessControlAttributeConfiguration", "InstanceArn"},
			"update-permission-set":                                        {"Description", "InstanceArn", "PermissionSetArn", "RelayState", "SessionDuration"},
			"update-trusted-token-issuer":                                  {"Name", "TrustedTokenIssuerArn", "TrustedTokenIssuerConfiguration"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-region": {"InstanceArn": "*string", "RegionName": "*string"},
			"attach-customer-managed-policy-reference-to-permission-set":   {"CustomerManagedPolicyReference": "*types.CustomerManagedPolicyReference", "InstanceArn": "*string", "PermissionSetArn": "*string"},
			"attach-managed-policy-to-permission-set":                      {"InstanceArn": "*string", "ManagedPolicyArn": "*string", "PermissionSetArn": "*string"},
			"create-account-assignment":                                    {"InstanceArn": "*string", "PermissionSetArn": "*string", "PrincipalId": "*string", "PrincipalType": "types.PrincipalType", "TargetId": "*string", "TargetType": "types.TargetType"},
			"create-application":                                           {"ApplicationProviderArn": "*string", "ClientToken": "*string", "Description": "*string", "InstanceArn": "*string", "Name": "*string", "PortalOptions": "*types.PortalOptions", "Status": "types.ApplicationStatus", "Tags": "[]types.Tag"},
			"create-application-assignment":                                {"ApplicationArn": "*string", "PrincipalId": "*string", "PrincipalType": "types.PrincipalType"},
			"create-instance":                                              {"ClientToken": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"create-instance-access-control-attribute-configuration":       {"InstanceAccessControlAttributeConfiguration": "*types.InstanceAccessControlAttributeConfiguration", "InstanceArn": "*string"},
			"create-permission-set":                                        {"Description": "*string", "InstanceArn": "*string", "Name": "*string", "RelayState": "*string", "SessionDuration": "*string", "Tags": "[]types.Tag"},
			"create-trusted-token-issuer":                                  {"ClientToken": "*string", "InstanceArn": "*string", "Name": "*string", "Tags": "[]types.Tag", "TrustedTokenIssuerConfiguration": "types.TrustedTokenIssuerConfiguration", "TrustedTokenIssuerType": "types.TrustedTokenIssuerType"},
			"delete-account-assignment":                                    {"InstanceArn": "*string", "PermissionSetArn": "*string", "PrincipalId": "*string", "PrincipalType": "types.PrincipalType", "TargetId": "*string", "TargetType": "types.TargetType"},
			"delete-application":                                           {"ApplicationArn": "*string"},
			"delete-application-access-scope":                              {"ApplicationArn": "*string", "Scope": "*string"},
			"delete-application-assignment":                                {"ApplicationArn": "*string", "PrincipalId": "*string", "PrincipalType": "types.PrincipalType"},
			"delete-application-authentication-method":                     {"ApplicationArn": "*string", "AuthenticationMethodType": "types.AuthenticationMethodType"},
			"delete-application-grant":                                     {"ApplicationArn": "*string", "GrantType": "types.GrantType"},
			"delete-inline-policy-from-permission-set":                     {"InstanceArn": "*string", "PermissionSetArn": "*string"},
			"delete-instance":                                              {"InstanceArn": "*string"},
			"delete-instance-access-control-attribute-configuration":       {"InstanceArn": "*string"},
			"delete-permission-set":                                        {"InstanceArn": "*string", "PermissionSetArn": "*string"},
			"delete-permissions-boundary-from-permission-set":              {"InstanceArn": "*string", "PermissionSetArn": "*string"},
			"delete-trusted-token-issuer":                                  {"TrustedTokenIssuerArn": "*string"},
			"describe-account-assignment-creation-status":                  {"AccountAssignmentCreationRequestId": "*string", "InstanceArn": "*string"},
			"describe-account-assignment-deletion-status":                  {"AccountAssignmentDeletionRequestId": "*string", "InstanceArn": "*string"},
			"describe-application":                                         {"ApplicationArn": "*string"},
			"describe-application-assignment":                              {"ApplicationArn": "*string", "PrincipalId": "*string", "PrincipalType": "types.PrincipalType"},
			"describe-application-provider":                                {"ApplicationProviderArn": "*string"},
			"describe-instance":                                            {"InstanceArn": "*string"},
			"describe-instance-access-control-attribute-configuration":     {"InstanceArn": "*string"},
			"describe-permission-set":                                      {"InstanceArn": "*string", "PermissionSetArn": "*string"},
			"describe-permission-set-provisioning-status":                  {"InstanceArn": "*string", "ProvisionPermissionSetRequestId": "*string"},
			"describe-region":                                              {"InstanceArn": "*string", "RegionName": "*string"},
			"describe-trusted-token-issuer":                                {"TrustedTokenIssuerArn": "*string"},
			"detach-customer-managed-policy-reference-from-permission-set": {"CustomerManagedPolicyReference": "*types.CustomerManagedPolicyReference", "InstanceArn": "*string", "PermissionSetArn": "*string"},
			"detach-managed-policy-from-permission-set":                    {"InstanceArn": "*string", "ManagedPolicyArn": "*string", "PermissionSetArn": "*string"},
			"get-application-access-scope":                                 {"ApplicationArn": "*string", "Scope": "*string"},
			"get-application-assignment-configuration":                     {"ApplicationArn": "*string"},
			"get-application-authentication-method":                        {"ApplicationArn": "*string", "AuthenticationMethodType": "types.AuthenticationMethodType"},
			"get-application-grant":                                        {"ApplicationArn": "*string", "GrantType": "types.GrantType"},
			"get-application-session-configuration":                        {"ApplicationArn": "*string"},
			"get-inline-policy-for-permission-set":                         {"InstanceArn": "*string", "PermissionSetArn": "*string"},
			"get-permissions-boundary-for-permission-set":                  {"InstanceArn": "*string", "PermissionSetArn": "*string"},
			"list-account-assignment-creation-status":                      {"Filter": "*types.OperationStatusFilter", "InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-account-assignment-deletion-status":                      {"Filter": "*types.OperationStatusFilter", "InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-account-assignments":                                     {"AccountId": "*string", "InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PermissionSetArn": "*string"},
			"list-account-assignments-for-principal":                       {"Filter": "*types.ListAccountAssignmentsFilter", "InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PrincipalId": "*string", "PrincipalType": "types.PrincipalType"},
			"list-accounts-for-provisioned-permission-set":                 {"InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PermissionSetArn": "*string", "ProvisioningStatus": "types.ProvisioningStatus"},
			"list-application-access-scopes":                               {"ApplicationArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-application-assignments":                                 {"ApplicationArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-application-assignments-for-principal":                   {"Filter": "*types.ListApplicationAssignmentsFilter", "InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PrincipalId": "*string", "PrincipalType": "types.PrincipalType"},
			"list-application-authentication-methods":                      {"ApplicationArn": "*string", "NextToken": "*string"},
			"list-application-grants":                                      {"ApplicationArn": "*string", "NextToken": "*string"},
			"list-application-providers":                                   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-applications":                                            {"Filter": "*types.ListApplicationsFilter", "InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-customer-managed-policy-references-in-permission-set":    {"InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PermissionSetArn": "*string"},
			"list-instances":                                               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-managed-policies-in-permission-set":                      {"InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PermissionSetArn": "*string"},
			"list-permission-set-provisioning-status":                      {"Filter": "*types.OperationStatusFilter", "InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-permission-sets":                                         {"InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-permission-sets-provisioned-to-account":                  {"AccountId": "*string", "InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "ProvisioningStatus": "types.ProvisioningStatus"},
			"list-regions":                                                 {"InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                                       {"InstanceArn": "*string", "NextToken": "*string", "ResourceArn": "*string"},
			"list-trusted-token-issuers":                                   {"InstanceArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"provision-permission-set":                                     {"InstanceArn": "*string", "PermissionSetArn": "*string", "TargetId": "*string", "TargetType": "types.ProvisionTargetType"},
			"put-application-access-scope":                                 {"ApplicationArn": "*string", "AuthorizedTargets": "[]string", "Scope": "*string"},
			"put-application-assignment-configuration":                     {"ApplicationArn": "*string", "AssignmentRequired": "*bool"},
			"put-application-authentication-method":                        {"ApplicationArn": "*string", "AuthenticationMethod": "types.AuthenticationMethod", "AuthenticationMethodType": "types.AuthenticationMethodType"},
			"put-application-grant":                                        {"ApplicationArn": "*string", "Grant": "types.Grant", "GrantType": "types.GrantType"},
			"put-application-session-configuration":                        {"ApplicationArn": "*string", "UserBackgroundSessionApplicationStatus": "types.UserBackgroundSessionApplicationStatus"},
			"put-inline-policy-to-permission-set":                          {"InlinePolicy": "*string", "InstanceArn": "*string", "PermissionSetArn": "*string"},
			"put-permissions-boundary-to-permission-set":                   {"InstanceArn": "*string", "PermissionSetArn": "*string", "PermissionsBoundary": "*types.PermissionsBoundary"},
			"remove-region":                                                {"InstanceArn": "*string", "RegionName": "*string"},
			"tag-resource":                                                 {"InstanceArn": "*string", "ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                                               {"InstanceArn": "*string", "ResourceArn": "*string", "TagKeys": "[]string"},
			"update-application":                                           {"ApplicationArn": "*string", "Description": "*string", "Name": "*string", "PortalOptions": "*types.UpdateApplicationPortalOptions", "Status": "types.ApplicationStatus"},
			"update-instance":                                              {"EncryptionConfiguration": "*types.EncryptionConfiguration", "InstanceArn": "*string", "Name": "*string"},
			"update-instance-access-control-attribute-configuration":       {"InstanceAccessControlAttributeConfiguration": "*types.InstanceAccessControlAttributeConfiguration", "InstanceArn": "*string"},
			"update-permission-set":                                        {"Description": "*string", "InstanceArn": "*string", "PermissionSetArn": "*string", "RelayState": "*string", "SessionDuration": "*string"},
			"update-trusted-token-issuer":                                  {"Name": "*string", "TrustedTokenIssuerArn": "*string", "TrustedTokenIssuerConfiguration": "types.TrustedTokenIssuerUpdateConfiguration"},
		},
		OperationInputRequired: map[string][]string{
			"add-region": {"InstanceArn", "RegionName"},
			"attach-customer-managed-policy-reference-to-permission-set":   {"CustomerManagedPolicyReference", "InstanceArn", "PermissionSetArn"},
			"attach-managed-policy-to-permission-set":                      {"InstanceArn", "ManagedPolicyArn", "PermissionSetArn"},
			"create-account-assignment":                                    {"InstanceArn", "PermissionSetArn", "PrincipalId", "PrincipalType", "TargetId", "TargetType"},
			"create-application":                                           {"ApplicationProviderArn", "InstanceArn", "Name"},
			"create-application-assignment":                                {"ApplicationArn", "PrincipalId", "PrincipalType"},
			"create-instance":                                              {},
			"create-instance-access-control-attribute-configuration":       {"InstanceAccessControlAttributeConfiguration", "InstanceArn"},
			"create-permission-set":                                        {"InstanceArn", "Name"},
			"create-trusted-token-issuer":                                  {"InstanceArn", "Name", "TrustedTokenIssuerConfiguration", "TrustedTokenIssuerType"},
			"delete-account-assignment":                                    {"InstanceArn", "PermissionSetArn", "PrincipalId", "PrincipalType", "TargetId", "TargetType"},
			"delete-application":                                           {"ApplicationArn"},
			"delete-application-access-scope":                              {"ApplicationArn", "Scope"},
			"delete-application-assignment":                                {"ApplicationArn", "PrincipalId", "PrincipalType"},
			"delete-application-authentication-method":                     {"ApplicationArn", "AuthenticationMethodType"},
			"delete-application-grant":                                     {"ApplicationArn", "GrantType"},
			"delete-inline-policy-from-permission-set":                     {"InstanceArn", "PermissionSetArn"},
			"delete-instance":                                              {"InstanceArn"},
			"delete-instance-access-control-attribute-configuration":       {"InstanceArn"},
			"delete-permission-set":                                        {"InstanceArn", "PermissionSetArn"},
			"delete-permissions-boundary-from-permission-set":              {"InstanceArn", "PermissionSetArn"},
			"delete-trusted-token-issuer":                                  {"TrustedTokenIssuerArn"},
			"describe-account-assignment-creation-status":                  {"AccountAssignmentCreationRequestId", "InstanceArn"},
			"describe-account-assignment-deletion-status":                  {"AccountAssignmentDeletionRequestId", "InstanceArn"},
			"describe-application":                                         {"ApplicationArn"},
			"describe-application-assignment":                              {"ApplicationArn", "PrincipalId", "PrincipalType"},
			"describe-application-provider":                                {"ApplicationProviderArn"},
			"describe-instance":                                            {"InstanceArn"},
			"describe-instance-access-control-attribute-configuration":     {"InstanceArn"},
			"describe-permission-set":                                      {"InstanceArn", "PermissionSetArn"},
			"describe-permission-set-provisioning-status":                  {"InstanceArn", "ProvisionPermissionSetRequestId"},
			"describe-region":                                              {"InstanceArn", "RegionName"},
			"describe-trusted-token-issuer":                                {"TrustedTokenIssuerArn"},
			"detach-customer-managed-policy-reference-from-permission-set": {"CustomerManagedPolicyReference", "InstanceArn", "PermissionSetArn"},
			"detach-managed-policy-from-permission-set":                    {"InstanceArn", "ManagedPolicyArn", "PermissionSetArn"},
			"get-application-access-scope":                                 {"ApplicationArn", "Scope"},
			"get-application-assignment-configuration":                     {"ApplicationArn"},
			"get-application-authentication-method":                        {"ApplicationArn", "AuthenticationMethodType"},
			"get-application-grant":                                        {"ApplicationArn", "GrantType"},
			"get-application-session-configuration":                        {"ApplicationArn"},
			"get-inline-policy-for-permission-set":                         {"InstanceArn", "PermissionSetArn"},
			"get-permissions-boundary-for-permission-set":                  {"InstanceArn", "PermissionSetArn"},
			"list-account-assignment-creation-status":                      {"InstanceArn"},
			"list-account-assignment-deletion-status":                      {"InstanceArn"},
			"list-account-assignments":                                     {"AccountId", "InstanceArn", "PermissionSetArn"},
			"list-account-assignments-for-principal":                       {"InstanceArn", "PrincipalId", "PrincipalType"},
			"list-accounts-for-provisioned-permission-set":                 {"InstanceArn", "PermissionSetArn"},
			"list-application-access-scopes":                               {"ApplicationArn"},
			"list-application-assignments":                                 {"ApplicationArn"},
			"list-application-assignments-for-principal":                   {"InstanceArn", "PrincipalId", "PrincipalType"},
			"list-application-authentication-methods":                      {"ApplicationArn"},
			"list-application-grants":                                      {"ApplicationArn"},
			"list-application-providers":                                   {},
			"list-applications":                                            {"InstanceArn"},
			"list-customer-managed-policy-references-in-permission-set":    {"InstanceArn", "PermissionSetArn"},
			"list-instances":                                               {},
			"list-managed-policies-in-permission-set":                      {"InstanceArn", "PermissionSetArn"},
			"list-permission-set-provisioning-status":                      {"InstanceArn"},
			"list-permission-sets":                                         {"InstanceArn"},
			"list-permission-sets-provisioned-to-account":                  {"AccountId", "InstanceArn"},
			"list-regions":                                                 {"InstanceArn"},
			"list-tags-for-resource":                                       {"ResourceArn"},
			"list-trusted-token-issuers":                                   {"InstanceArn"},
			"provision-permission-set":                                     {"InstanceArn", "PermissionSetArn", "TargetType"},
			"put-application-access-scope":                                 {"ApplicationArn", "Scope"},
			"put-application-assignment-configuration":                     {"ApplicationArn", "AssignmentRequired"},
			"put-application-authentication-method":                        {"ApplicationArn", "AuthenticationMethod", "AuthenticationMethodType"},
			"put-application-grant":                                        {"ApplicationArn", "Grant", "GrantType"},
			"put-application-session-configuration":                        {"ApplicationArn"},
			"put-inline-policy-to-permission-set":                          {"InlinePolicy", "InstanceArn", "PermissionSetArn"},
			"put-permissions-boundary-to-permission-set":                   {"InstanceArn", "PermissionSetArn", "PermissionsBoundary"},
			"remove-region":                                                {"InstanceArn", "RegionName"},
			"tag-resource":                                                 {"ResourceArn", "Tags"},
			"untag-resource":                                               {"ResourceArn", "TagKeys"},
			"update-application":                                           {"ApplicationArn"},
			"update-instance":                                              {"InstanceArn"},
			"update-instance-access-control-attribute-configuration":       {"InstanceAccessControlAttributeConfiguration", "InstanceArn"},
			"update-permission-set":                                        {"InstanceArn", "PermissionSetArn"},
			"update-trusted-token-issuer":                                  {"TrustedTokenIssuerArn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("ssoadmin", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
