package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/licensemanager/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-grant", "check-in-license", "checkout-borrow-license", "checkout-license", "create-grant", "create-grant-version", "create-license", "create-license-asset-group", "create-license-asset-ruleset", "create-license-configuration", "create-license-conversion-task-for-resource", "create-license-manager-report-generator", "create-license-version", "create-token", "delete-grant", "delete-license", "delete-license-asset-group", "delete-license-asset-ruleset", "delete-license-configuration", "delete-license-manager-report-generator", "delete-token", "extend-license-consumption", "get-access-token", "get-grant", "get-license", "get-license-asset-group", "get-license-asset-ruleset", "get-license-configuration", "get-license-conversion-task", "get-license-manager-report-generator", "get-license-usage", "get-service-settings", "list-assets-for-license-asset-group", "list-associations-for-license-configuration", "list-distributed-grants", "list-failures-for-license-configuration-operations", "list-license-asset-groups", "list-license-asset-rulesets", "list-license-configurations", "list-license-configurations-for-organization", "list-license-conversion-tasks", "list-license-manager-report-generators", "list-license-specifications-for-resource", "list-license-versions", "list-licenses", "list-received-grants", "list-received-grants-for-organization", "list-received-licenses", "list-received-licenses-for-organization", "list-resource-inventory", "list-tags-for-resource", "list-tokens", "list-usage-for-license-configuration", "reject-grant", "tag-resource", "untag-resource", "update-license-asset-group", "update-license-asset-ruleset", "update-license-configuration", "update-license-manager-report-generator", "update-license-specifications-for-resource", "update-service-settings"},
		OperationSet: map[string]bool{"accept-grant": true, "check-in-license": true, "checkout-borrow-license": true, "checkout-license": true, "create-grant": true, "create-grant-version": true, "create-license": true, "create-license-asset-group": true, "create-license-asset-ruleset": true, "create-license-configuration": true, "create-license-conversion-task-for-resource": true, "create-license-manager-report-generator": true, "create-license-version": true, "create-token": true, "delete-grant": true, "delete-license": true, "delete-license-asset-group": true, "delete-license-asset-ruleset": true, "delete-license-configuration": true, "delete-license-manager-report-generator": true, "delete-token": true, "extend-license-consumption": true, "get-access-token": true, "get-grant": true, "get-license": true, "get-license-asset-group": true, "get-license-asset-ruleset": true, "get-license-configuration": true, "get-license-conversion-task": true, "get-license-manager-report-generator": true, "get-license-usage": true, "get-service-settings": true, "list-assets-for-license-asset-group": true, "list-associations-for-license-configuration": true, "list-distributed-grants": true, "list-failures-for-license-configuration-operations": true, "list-license-asset-groups": true, "list-license-asset-rulesets": true, "list-license-configurations": true, "list-license-configurations-for-organization": true, "list-license-conversion-tasks": true, "list-license-manager-report-generators": true, "list-license-specifications-for-resource": true, "list-license-versions": true, "list-licenses": true, "list-received-grants": true, "list-received-grants-for-organization": true, "list-received-licenses": true, "list-received-licenses-for-organization": true, "list-resource-inventory": true, "list-tags-for-resource": true, "list-tokens": true, "list-usage-for-license-configuration": true, "reject-grant": true, "tag-resource": true, "untag-resource": true, "update-license-asset-group": true, "update-license-asset-ruleset": true, "update-license-configuration": true, "update-license-manager-report-generator": true, "update-license-specifications-for-resource": true, "update-service-settings": true},
		OperationInputs: map[string][]string{
			"accept-grant":                                       {"GrantArn"},
			"check-in-license":                                   {"Beneficiary", "LicenseConsumptionToken"},
			"checkout-borrow-license":                            {"CheckoutMetadata", "ClientToken", "DigitalSignatureMethod", "Entitlements", "LicenseArn", "NodeId"},
			"checkout-license":                                   {"Beneficiary", "CheckoutType", "ClientToken", "Entitlements", "KeyFingerprint", "NodeId", "ProductSKU"},
			"create-grant":                                       {"AllowedOperations", "ClientToken", "GrantName", "HomeRegion", "LicenseArn", "Principals", "Tags"},
			"create-grant-version":                               {"AllowedOperations", "ClientToken", "GrantArn", "GrantName", "Options", "SourceVersion", "Status", "StatusReason"},
			"create-license":                                     {"Beneficiary", "ClientToken", "ConsumptionConfiguration", "Entitlements", "HomeRegion", "Issuer", "LicenseMetadata", "LicenseName", "ProductName", "ProductSKU", "Tags", "Validity"},
			"create-license-asset-group":                         {"AssociatedLicenseAssetRulesetARNs", "ClientToken", "Description", "LicenseAssetGroupConfigurations", "Name", "Properties", "Tags"},
			"create-license-asset-ruleset":                       {"ClientToken", "Description", "Name", "Rules", "Tags"},
			"create-license-configuration":                       {"Description", "DisassociateWhenNotFound", "LicenseCount", "LicenseCountHardLimit", "LicenseCountingType", "LicenseExpiry", "LicenseRules", "Name", "ProductInformationList", "Tags"},
			"create-license-conversion-task-for-resource":        {"DestinationLicenseContext", "ResourceArn", "SourceLicenseContext"},
			"create-license-manager-report-generator":            {"ClientToken", "Description", "ReportContext", "ReportFrequency", "ReportGeneratorName", "Tags", "Type"},
			"create-license-version":                             {"ClientToken", "ConsumptionConfiguration", "Entitlements", "HomeRegion", "Issuer", "LicenseArn", "LicenseMetadata", "LicenseName", "ProductName", "SourceVersion", "Status", "Validity"},
			"create-token":                                       {"ClientToken", "ExpirationInDays", "LicenseArn", "RoleArns", "TokenProperties"},
			"delete-grant":                                       {"GrantArn", "StatusReason", "Version"},
			"delete-license":                                     {"LicenseArn", "SourceVersion"},
			"delete-license-asset-group":                         {"LicenseAssetGroupArn"},
			"delete-license-asset-ruleset":                       {"LicenseAssetRulesetArn"},
			"delete-license-configuration":                       {"LicenseConfigurationArn"},
			"delete-license-manager-report-generator":            {"LicenseManagerReportGeneratorArn"},
			"delete-token":                                       {"TokenId"},
			"extend-license-consumption":                         {"DryRun", "LicenseConsumptionToken"},
			"get-access-token":                                   {"Token", "TokenProperties"},
			"get-grant":                                          {"GrantArn", "Version"},
			"get-license":                                        {"LicenseArn", "Version"},
			"get-license-asset-group":                            {"LicenseAssetGroupArn"},
			"get-license-asset-ruleset":                          {"LicenseAssetRulesetArn"},
			"get-license-configuration":                          {"LicenseConfigurationArn"},
			"get-license-conversion-task":                        {"LicenseConversionTaskId"},
			"get-license-manager-report-generator":               {"LicenseManagerReportGeneratorArn"},
			"get-license-usage":                                  {"LicenseArn"},
			"get-service-settings":                               {},
			"list-assets-for-license-asset-group":                {"AssetType", "LicenseAssetGroupArn", "MaxResults", "NextToken"},
			"list-associations-for-license-configuration":        {"LicenseConfigurationArn", "MaxResults", "NextToken"},
			"list-distributed-grants":                            {"Filters", "GrantArns", "MaxResults", "NextToken"},
			"list-failures-for-license-configuration-operations": {"LicenseConfigurationArn", "MaxResults", "NextToken"},
			"list-license-asset-groups":                          {"Filters", "MaxResults", "NextToken"},
			"list-license-asset-rulesets":                        {"Filters", "MaxResults", "NextToken", "ShowAWSManagedLicenseAssetRulesets"},
			"list-license-configurations":                        {"Filters", "LicenseConfigurationArns", "MaxResults", "NextToken"},
			"list-license-configurations-for-organization":       {"Filters", "LicenseConfigurationArns", "MaxResults", "NextToken"},
			"list-license-conversion-tasks":                      {"Filters", "MaxResults", "NextToken"},
			"list-license-manager-report-generators":             {"Filters", "MaxResults", "NextToken"},
			"list-license-specifications-for-resource":           {"MaxResults", "NextToken", "ResourceArn"},
			"list-license-versions":                              {"LicenseArn", "MaxResults", "NextToken"},
			"list-licenses":                                      {"Filters", "LicenseArns", "MaxResults", "NextToken"},
			"list-received-grants":                               {"Filters", "GrantArns", "MaxResults", "NextToken"},
			"list-received-grants-for-organization":              {"Filters", "LicenseArn", "MaxResults", "NextToken"},
			"list-received-licenses":                             {"Filters", "LicenseArns", "MaxResults", "NextToken"},
			"list-received-licenses-for-organization":            {"Filters", "MaxResults", "NextToken"},
			"list-resource-inventory":                            {"Filters", "MaxResults", "NextToken"},
			"list-tags-for-resource":                             {"ResourceArn"},
			"list-tokens":                                        {"Filters", "MaxResults", "NextToken", "TokenIds"},
			"list-usage-for-license-configuration":               {"Filters", "LicenseConfigurationArn", "MaxResults", "NextToken"},
			"reject-grant":                                       {"GrantArn"},
			"tag-resource":                                       {"ResourceArn", "Tags"},
			"untag-resource":                                     {"ResourceArn", "TagKeys"},
			"update-license-asset-group":                         {"AssociatedLicenseAssetRulesetARNs", "ClientToken", "Description", "LicenseAssetGroupArn", "LicenseAssetGroupConfigurations", "Name", "Properties", "Status"},
			"update-license-asset-ruleset":                       {"ClientToken", "Description", "LicenseAssetRulesetArn", "Name", "Rules"},
			"update-license-configuration":                       {"Description", "DisassociateWhenNotFound", "LicenseConfigurationArn", "LicenseConfigurationStatus", "LicenseCount", "LicenseCountHardLimit", "LicenseExpiry", "LicenseRules", "Name", "ProductInformationList"},
			"update-license-manager-report-generator":            {"ClientToken", "Description", "LicenseManagerReportGeneratorArn", "ReportContext", "ReportFrequency", "ReportGeneratorName", "Type"},
			"update-license-specifications-for-resource":         {"AddLicenseSpecifications", "RemoveLicenseSpecifications", "ResourceArn"},
			"update-service-settings":                            {"EnableCrossAccountsDiscovery", "EnabledDiscoverySourceRegions", "OrganizationConfiguration", "S3BucketArn", "SnsTopicArn"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-grant":                                       {"GrantArn": "*string"},
			"check-in-license":                                   {"Beneficiary": "*string", "LicenseConsumptionToken": "*string"},
			"checkout-borrow-license":                            {"CheckoutMetadata": "[]types.Metadata", "ClientToken": "*string", "DigitalSignatureMethod": "types.DigitalSignatureMethod", "Entitlements": "[]types.EntitlementData", "LicenseArn": "*string", "NodeId": "*string"},
			"checkout-license":                                   {"Beneficiary": "*string", "CheckoutType": "types.CheckoutType", "ClientToken": "*string", "Entitlements": "[]types.EntitlementData", "KeyFingerprint": "*string", "NodeId": "*string", "ProductSKU": "*string"},
			"create-grant":                                       {"AllowedOperations": "[]types.AllowedOperation", "ClientToken": "*string", "GrantName": "*string", "HomeRegion": "*string", "LicenseArn": "*string", "Principals": "[]string", "Tags": "[]types.Tag"},
			"create-grant-version":                               {"AllowedOperations": "[]types.AllowedOperation", "ClientToken": "*string", "GrantArn": "*string", "GrantName": "*string", "Options": "*types.Options", "SourceVersion": "*string", "Status": "types.GrantStatus", "StatusReason": "*string"},
			"create-license":                                     {"Beneficiary": "*string", "ClientToken": "*string", "ConsumptionConfiguration": "*types.ConsumptionConfiguration", "Entitlements": "[]types.Entitlement", "HomeRegion": "*string", "Issuer": "*types.Issuer", "LicenseMetadata": "[]types.Metadata", "LicenseName": "*string", "ProductName": "*string", "ProductSKU": "*string", "Tags": "[]types.Tag", "Validity": "*types.DatetimeRange"},
			"create-license-asset-group":                         {"AssociatedLicenseAssetRulesetARNs": "[]string", "ClientToken": "*string", "Description": "*string", "LicenseAssetGroupConfigurations": "[]types.LicenseAssetGroupConfiguration", "Name": "*string", "Properties": "[]types.LicenseAssetGroupProperty", "Tags": "[]types.Tag"},
			"create-license-asset-ruleset":                       {"ClientToken": "*string", "Description": "*string", "Name": "*string", "Rules": "[]types.LicenseAssetRule", "Tags": "[]types.Tag"},
			"create-license-configuration":                       {"Description": "*string", "DisassociateWhenNotFound": "*bool", "LicenseCount": "*int64", "LicenseCountHardLimit": "*bool", "LicenseCountingType": "types.LicenseCountingType", "LicenseExpiry": "*int64", "LicenseRules": "[]string", "Name": "*string", "ProductInformationList": "[]types.ProductInformation", "Tags": "[]types.Tag"},
			"create-license-conversion-task-for-resource":        {"DestinationLicenseContext": "*types.LicenseConversionContext", "ResourceArn": "*string", "SourceLicenseContext": "*types.LicenseConversionContext"},
			"create-license-manager-report-generator":            {"ClientToken": "*string", "Description": "*string", "ReportContext": "*types.ReportContext", "ReportFrequency": "*types.ReportFrequency", "ReportGeneratorName": "*string", "Tags": "[]types.Tag", "Type": "[]types.ReportType"},
			"create-license-version":                             {"ClientToken": "*string", "ConsumptionConfiguration": "*types.ConsumptionConfiguration", "Entitlements": "[]types.Entitlement", "HomeRegion": "*string", "Issuer": "*types.Issuer", "LicenseArn": "*string", "LicenseMetadata": "[]types.Metadata", "LicenseName": "*string", "ProductName": "*string", "SourceVersion": "*string", "Status": "types.LicenseStatus", "Validity": "*types.DatetimeRange"},
			"create-token":                                       {"ClientToken": "*string", "ExpirationInDays": "*int32", "LicenseArn": "*string", "RoleArns": "[]string", "TokenProperties": "[]string"},
			"delete-grant":                                       {"GrantArn": "*string", "StatusReason": "*string", "Version": "*string"},
			"delete-license":                                     {"LicenseArn": "*string", "SourceVersion": "*string"},
			"delete-license-asset-group":                         {"LicenseAssetGroupArn": "*string"},
			"delete-license-asset-ruleset":                       {"LicenseAssetRulesetArn": "*string"},
			"delete-license-configuration":                       {"LicenseConfigurationArn": "*string"},
			"delete-license-manager-report-generator":            {"LicenseManagerReportGeneratorArn": "*string"},
			"delete-token":                                       {"TokenId": "*string"},
			"extend-license-consumption":                         {"DryRun": "bool", "LicenseConsumptionToken": "*string"},
			"get-access-token":                                   {"Token": "*string", "TokenProperties": "[]string"},
			"get-grant":                                          {"GrantArn": "*string", "Version": "*string"},
			"get-license":                                        {"LicenseArn": "*string", "Version": "*string"},
			"get-license-asset-group":                            {"LicenseAssetGroupArn": "*string"},
			"get-license-asset-ruleset":                          {"LicenseAssetRulesetArn": "*string"},
			"get-license-configuration":                          {"LicenseConfigurationArn": "*string"},
			"get-license-conversion-task":                        {"LicenseConversionTaskId": "*string"},
			"get-license-manager-report-generator":               {"LicenseManagerReportGeneratorArn": "*string"},
			"get-license-usage":                                  {"LicenseArn": "*string"},
			"get-service-settings":                               {},
			"list-assets-for-license-asset-group":                {"AssetType": "*string", "LicenseAssetGroupArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-associations-for-license-configuration":        {"LicenseConfigurationArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-distributed-grants":                            {"Filters": "[]types.Filter", "GrantArns": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-failures-for-license-configuration-operations": {"LicenseConfigurationArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-license-asset-groups":                          {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-license-asset-rulesets":                        {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string", "ShowAWSManagedLicenseAssetRulesets": "bool"},
			"list-license-configurations":                        {"Filters": "[]types.Filter", "LicenseConfigurationArns": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-license-configurations-for-organization":       {"Filters": "[]types.Filter", "LicenseConfigurationArns": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-license-conversion-tasks":                      {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-license-manager-report-generators":             {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-license-specifications-for-resource":           {"MaxResults": "*int32", "NextToken": "*string", "ResourceArn": "*string"},
			"list-license-versions":                              {"LicenseArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-licenses":                                      {"Filters": "[]types.Filter", "LicenseArns": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-received-grants":                               {"Filters": "[]types.Filter", "GrantArns": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-received-grants-for-organization":              {"Filters": "[]types.Filter", "LicenseArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-received-licenses":                             {"Filters": "[]types.Filter", "LicenseArns": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-received-licenses-for-organization":            {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-resource-inventory":                            {"Filters": "[]types.InventoryFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                             {"ResourceArn": "*string"},
			"list-tokens":                                        {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string", "TokenIds": "[]string"},
			"list-usage-for-license-configuration":               {"Filters": "[]types.Filter", "LicenseConfigurationArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"reject-grant":                                       {"GrantArn": "*string"},
			"tag-resource":                                       {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                                     {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-license-asset-group":                         {"AssociatedLicenseAssetRulesetARNs": "[]string", "ClientToken": "*string", "Description": "*string", "LicenseAssetGroupArn": "*string", "LicenseAssetGroupConfigurations": "[]types.LicenseAssetGroupConfiguration", "Name": "*string", "Properties": "[]types.LicenseAssetGroupProperty", "Status": "types.LicenseAssetGroupStatus"},
			"update-license-asset-ruleset":                       {"ClientToken": "*string", "Description": "*string", "LicenseAssetRulesetArn": "*string", "Name": "*string", "Rules": "[]types.LicenseAssetRule"},
			"update-license-configuration":                       {"Description": "*string", "DisassociateWhenNotFound": "*bool", "LicenseConfigurationArn": "*string", "LicenseConfigurationStatus": "types.LicenseConfigurationStatus", "LicenseCount": "*int64", "LicenseCountHardLimit": "*bool", "LicenseExpiry": "*int64", "LicenseRules": "[]string", "Name": "*string", "ProductInformationList": "[]types.ProductInformation"},
			"update-license-manager-report-generator":            {"ClientToken": "*string", "Description": "*string", "LicenseManagerReportGeneratorArn": "*string", "ReportContext": "*types.ReportContext", "ReportFrequency": "*types.ReportFrequency", "ReportGeneratorName": "*string", "Type": "[]types.ReportType"},
			"update-license-specifications-for-resource":         {"AddLicenseSpecifications": "[]types.LicenseSpecification", "RemoveLicenseSpecifications": "[]types.LicenseSpecification", "ResourceArn": "*string"},
			"update-service-settings":                            {"EnableCrossAccountsDiscovery": "*bool", "EnabledDiscoverySourceRegions": "[]string", "OrganizationConfiguration": "*types.OrganizationConfiguration", "S3BucketArn": "*string", "SnsTopicArn": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-grant":                                       {"GrantArn"},
			"check-in-license":                                   {"LicenseConsumptionToken"},
			"checkout-borrow-license":                            {"ClientToken", "DigitalSignatureMethod", "Entitlements", "LicenseArn"},
			"checkout-license":                                   {"CheckoutType", "ClientToken", "Entitlements", "KeyFingerprint", "ProductSKU"},
			"create-grant":                                       {"AllowedOperations", "ClientToken", "GrantName", "HomeRegion", "LicenseArn", "Principals"},
			"create-grant-version":                               {"ClientToken", "GrantArn"},
			"create-license":                                     {"Beneficiary", "ClientToken", "ConsumptionConfiguration", "Entitlements", "HomeRegion", "Issuer", "LicenseName", "ProductName", "ProductSKU", "Validity"},
			"create-license-asset-group":                         {"AssociatedLicenseAssetRulesetARNs", "ClientToken", "LicenseAssetGroupConfigurations", "Name"},
			"create-license-asset-ruleset":                       {"ClientToken", "Name", "Rules"},
			"create-license-configuration":                       {"LicenseCountingType", "Name"},
			"create-license-conversion-task-for-resource":        {"DestinationLicenseContext", "ResourceArn", "SourceLicenseContext"},
			"create-license-manager-report-generator":            {"ClientToken", "ReportContext", "ReportFrequency", "ReportGeneratorName", "Type"},
			"create-license-version":                             {"ClientToken", "ConsumptionConfiguration", "Entitlements", "HomeRegion", "Issuer", "LicenseArn", "LicenseName", "ProductName", "Status", "Validity"},
			"create-token":                                       {"ClientToken", "LicenseArn"},
			"delete-grant":                                       {"GrantArn", "Version"},
			"delete-license":                                     {"LicenseArn", "SourceVersion"},
			"delete-license-asset-group":                         {"LicenseAssetGroupArn"},
			"delete-license-asset-ruleset":                       {"LicenseAssetRulesetArn"},
			"delete-license-configuration":                       {"LicenseConfigurationArn"},
			"delete-license-manager-report-generator":            {"LicenseManagerReportGeneratorArn"},
			"delete-token":                                       {"TokenId"},
			"extend-license-consumption":                         {"LicenseConsumptionToken"},
			"get-access-token":                                   {"Token"},
			"get-grant":                                          {"GrantArn"},
			"get-license":                                        {"LicenseArn"},
			"get-license-asset-group":                            {"LicenseAssetGroupArn"},
			"get-license-asset-ruleset":                          {"LicenseAssetRulesetArn"},
			"get-license-configuration":                          {"LicenseConfigurationArn"},
			"get-license-conversion-task":                        {"LicenseConversionTaskId"},
			"get-license-manager-report-generator":               {"LicenseManagerReportGeneratorArn"},
			"get-license-usage":                                  {"LicenseArn"},
			"get-service-settings":                               {},
			"list-assets-for-license-asset-group":                {"AssetType", "LicenseAssetGroupArn"},
			"list-associations-for-license-configuration":        {"LicenseConfigurationArn"},
			"list-distributed-grants":                            {},
			"list-failures-for-license-configuration-operations": {"LicenseConfigurationArn"},
			"list-license-asset-groups":                          {},
			"list-license-asset-rulesets":                        {},
			"list-license-configurations":                        {},
			"list-license-configurations-for-organization":       {},
			"list-license-conversion-tasks":                      {},
			"list-license-manager-report-generators":             {},
			"list-license-specifications-for-resource":           {"ResourceArn"},
			"list-license-versions":                              {"LicenseArn"},
			"list-licenses":                                      {},
			"list-received-grants":                               {},
			"list-received-grants-for-organization":              {"LicenseArn"},
			"list-received-licenses":                             {},
			"list-received-licenses-for-organization":            {},
			"list-resource-inventory":                            {},
			"list-tags-for-resource":                             {"ResourceArn"},
			"list-tokens":                                        {},
			"list-usage-for-license-configuration":               {"LicenseConfigurationArn"},
			"reject-grant":                                       {"GrantArn"},
			"tag-resource":                                       {"ResourceArn", "Tags"},
			"untag-resource":                                     {"ResourceArn", "TagKeys"},
			"update-license-asset-group":                         {"AssociatedLicenseAssetRulesetARNs", "ClientToken", "LicenseAssetGroupArn"},
			"update-license-asset-ruleset":                       {"ClientToken", "LicenseAssetRulesetArn", "Rules"},
			"update-license-configuration":                       {"LicenseConfigurationArn"},
			"update-license-manager-report-generator":            {"ClientToken", "LicenseManagerReportGeneratorArn", "ReportContext", "ReportFrequency", "ReportGeneratorName", "Type"},
			"update-license-specifications-for-resource":         {"ResourceArn"},
			"update-service-settings":                            {},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("licensemanager", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
