package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/wisdom/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-assistant", "create-assistant-association", "create-content", "create-knowledge-base", "create-quick-response", "create-session", "delete-assistant", "delete-assistant-association", "delete-content", "delete-import-job", "delete-knowledge-base", "delete-quick-response", "get-assistant", "get-assistant-association", "get-content", "get-content-summary", "get-import-job", "get-knowledge-base", "get-quick-response", "get-recommendations", "get-session", "list-assistant-associations", "list-assistants", "list-contents", "list-import-jobs", "list-knowledge-bases", "list-quick-responses", "list-tags-for-resource", "notify-recommendations-received", "query-assistant", "remove-knowledge-base-template-uri", "search-content", "search-quick-responses", "search-sessions", "start-content-upload", "start-import-job", "tag-resource", "untag-resource", "update-content", "update-knowledge-base-template-uri", "update-quick-response"},
		OperationSet: map[string]bool{"create-assistant": true, "create-assistant-association": true, "create-content": true, "create-knowledge-base": true, "create-quick-response": true, "create-session": true, "delete-assistant": true, "delete-assistant-association": true, "delete-content": true, "delete-import-job": true, "delete-knowledge-base": true, "delete-quick-response": true, "get-assistant": true, "get-assistant-association": true, "get-content": true, "get-content-summary": true, "get-import-job": true, "get-knowledge-base": true, "get-quick-response": true, "get-recommendations": true, "get-session": true, "list-assistant-associations": true, "list-assistants": true, "list-contents": true, "list-import-jobs": true, "list-knowledge-bases": true, "list-quick-responses": true, "list-tags-for-resource": true, "notify-recommendations-received": true, "query-assistant": true, "remove-knowledge-base-template-uri": true, "search-content": true, "search-quick-responses": true, "search-sessions": true, "start-content-upload": true, "start-import-job": true, "tag-resource": true, "untag-resource": true, "update-content": true, "update-knowledge-base-template-uri": true, "update-quick-response": true},
		OperationInputs: map[string][]string{
			"create-assistant":                   {"ClientToken", "Description", "Name", "ServerSideEncryptionConfiguration", "Tags", "Type"},
			"create-assistant-association":       {"AssistantId", "Association", "AssociationType", "ClientToken", "Tags"},
			"create-content":                     {"ClientToken", "KnowledgeBaseId", "Metadata", "Name", "OverrideLinkOutUri", "Tags", "Title", "UploadId"},
			"create-knowledge-base":              {"ClientToken", "Description", "KnowledgeBaseType", "Name", "RenderingConfiguration", "ServerSideEncryptionConfiguration", "SourceConfiguration", "Tags"},
			"create-quick-response":              {"Channels", "ClientToken", "Content", "ContentType", "Description", "GroupingConfiguration", "IsActive", "KnowledgeBaseId", "Language", "Name", "ShortcutKey", "Tags"},
			"create-session":                     {"AssistantId", "ClientToken", "Description", "Name", "Tags"},
			"delete-assistant":                   {"AssistantId"},
			"delete-assistant-association":       {"AssistantAssociationId", "AssistantId"},
			"delete-content":                     {"ContentId", "KnowledgeBaseId"},
			"delete-import-job":                  {"ImportJobId", "KnowledgeBaseId"},
			"delete-knowledge-base":              {"KnowledgeBaseId"},
			"delete-quick-response":              {"KnowledgeBaseId", "QuickResponseId"},
			"get-assistant":                      {"AssistantId"},
			"get-assistant-association":          {"AssistantAssociationId", "AssistantId"},
			"get-content":                        {"ContentId", "KnowledgeBaseId"},
			"get-content-summary":                {"ContentId", "KnowledgeBaseId"},
			"get-import-job":                     {"ImportJobId", "KnowledgeBaseId"},
			"get-knowledge-base":                 {"KnowledgeBaseId"},
			"get-quick-response":                 {"KnowledgeBaseId", "QuickResponseId"},
			"get-recommendations":                {"AssistantId", "MaxResults", "SessionId", "WaitTimeSeconds"},
			"get-session":                        {"AssistantId", "SessionId"},
			"list-assistant-associations":        {"AssistantId", "MaxResults", "NextToken"},
			"list-assistants":                    {"MaxResults", "NextToken"},
			"list-contents":                      {"KnowledgeBaseId", "MaxResults", "NextToken"},
			"list-import-jobs":                   {"KnowledgeBaseId", "MaxResults", "NextToken"},
			"list-knowledge-bases":               {"MaxResults", "NextToken"},
			"list-quick-responses":               {"KnowledgeBaseId", "MaxResults", "NextToken"},
			"list-tags-for-resource":             {"ResourceArn"},
			"notify-recommendations-received":    {"AssistantId", "RecommendationIds", "SessionId"},
			"query-assistant":                    {"AssistantId", "MaxResults", "NextToken", "QueryText"},
			"remove-knowledge-base-template-uri": {"KnowledgeBaseId"},
			"search-content":                     {"KnowledgeBaseId", "MaxResults", "NextToken", "SearchExpression"},
			"search-quick-responses":             {"Attributes", "KnowledgeBaseId", "MaxResults", "NextToken", "SearchExpression"},
			"search-sessions":                    {"AssistantId", "MaxResults", "NextToken", "SearchExpression"},
			"start-content-upload":               {"ContentType", "KnowledgeBaseId", "PresignedUrlTimeToLive"},
			"start-import-job":                   {"ClientToken", "ExternalSourceConfiguration", "ImportJobType", "KnowledgeBaseId", "Metadata", "UploadId"},
			"tag-resource":                       {"ResourceArn", "Tags"},
			"untag-resource":                     {"ResourceArn", "TagKeys"},
			"update-content":                     {"ContentId", "KnowledgeBaseId", "Metadata", "OverrideLinkOutUri", "RemoveOverrideLinkOutUri", "RevisionId", "Title", "UploadId"},
			"update-knowledge-base-template-uri": {"KnowledgeBaseId", "TemplateUri"},
			"update-quick-response":              {"Channels", "Content", "ContentType", "Description", "GroupingConfiguration", "IsActive", "KnowledgeBaseId", "Language", "Name", "QuickResponseId", "RemoveDescription", "RemoveGroupingConfiguration", "RemoveShortcutKey", "ShortcutKey"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-assistant":                   {"ClientToken": "*string", "Description": "*string", "Name": "*string", "ServerSideEncryptionConfiguration": "*types.ServerSideEncryptionConfiguration", "Tags": "map[string]string", "Type": "types.AssistantType"},
			"create-assistant-association":       {"AssistantId": "*string", "Association": "types.AssistantAssociationInputData", "AssociationType": "types.AssociationType", "ClientToken": "*string", "Tags": "map[string]string"},
			"create-content":                     {"ClientToken": "*string", "KnowledgeBaseId": "*string", "Metadata": "map[string]string", "Name": "*string", "OverrideLinkOutUri": "*string", "Tags": "map[string]string", "Title": "*string", "UploadId": "*string"},
			"create-knowledge-base":              {"ClientToken": "*string", "Description": "*string", "KnowledgeBaseType": "types.KnowledgeBaseType", "Name": "*string", "RenderingConfiguration": "*types.RenderingConfiguration", "ServerSideEncryptionConfiguration": "*types.ServerSideEncryptionConfiguration", "SourceConfiguration": "types.SourceConfiguration", "Tags": "map[string]string"},
			"create-quick-response":              {"Channels": "[]string", "ClientToken": "*string", "Content": "types.QuickResponseDataProvider", "ContentType": "*string", "Description": "*string", "GroupingConfiguration": "*types.GroupingConfiguration", "IsActive": "*bool", "KnowledgeBaseId": "*string", "Language": "*string", "Name": "*string", "ShortcutKey": "*string", "Tags": "map[string]string"},
			"create-session":                     {"AssistantId": "*string", "ClientToken": "*string", "Description": "*string", "Name": "*string", "Tags": "map[string]string"},
			"delete-assistant":                   {"AssistantId": "*string"},
			"delete-assistant-association":       {"AssistantAssociationId": "*string", "AssistantId": "*string"},
			"delete-content":                     {"ContentId": "*string", "KnowledgeBaseId": "*string"},
			"delete-import-job":                  {"ImportJobId": "*string", "KnowledgeBaseId": "*string"},
			"delete-knowledge-base":              {"KnowledgeBaseId": "*string"},
			"delete-quick-response":              {"KnowledgeBaseId": "*string", "QuickResponseId": "*string"},
			"get-assistant":                      {"AssistantId": "*string"},
			"get-assistant-association":          {"AssistantAssociationId": "*string", "AssistantId": "*string"},
			"get-content":                        {"ContentId": "*string", "KnowledgeBaseId": "*string"},
			"get-content-summary":                {"ContentId": "*string", "KnowledgeBaseId": "*string"},
			"get-import-job":                     {"ImportJobId": "*string", "KnowledgeBaseId": "*string"},
			"get-knowledge-base":                 {"KnowledgeBaseId": "*string"},
			"get-quick-response":                 {"KnowledgeBaseId": "*string", "QuickResponseId": "*string"},
			"get-recommendations":                {"AssistantId": "*string", "MaxResults": "*int32", "SessionId": "*string", "WaitTimeSeconds": "int32"},
			"get-session":                        {"AssistantId": "*string", "SessionId": "*string"},
			"list-assistant-associations":        {"AssistantId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-assistants":                    {"MaxResults": "*int32", "NextToken": "*string"},
			"list-contents":                      {"KnowledgeBaseId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-import-jobs":                   {"KnowledgeBaseId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-knowledge-bases":               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-quick-responses":               {"KnowledgeBaseId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":             {"ResourceArn": "*string"},
			"notify-recommendations-received":    {"AssistantId": "*string", "RecommendationIds": "[]string", "SessionId": "*string"},
			"query-assistant":                    {"AssistantId": "*string", "MaxResults": "*int32", "NextToken": "*string", "QueryText": "*string"},
			"remove-knowledge-base-template-uri": {"KnowledgeBaseId": "*string"},
			"search-content":                     {"KnowledgeBaseId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SearchExpression": "*types.SearchExpression"},
			"search-quick-responses":             {"Attributes": "map[string]string", "KnowledgeBaseId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SearchExpression": "*types.QuickResponseSearchExpression"},
			"search-sessions":                    {"AssistantId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SearchExpression": "*types.SearchExpression"},
			"start-content-upload":               {"ContentType": "*string", "KnowledgeBaseId": "*string", "PresignedUrlTimeToLive": "*int32"},
			"start-import-job":                   {"ClientToken": "*string", "ExternalSourceConfiguration": "*types.ExternalSourceConfiguration", "ImportJobType": "types.ImportJobType", "KnowledgeBaseId": "*string", "Metadata": "map[string]string", "UploadId": "*string"},
			"tag-resource":                       {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                     {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-content":                     {"ContentId": "*string", "KnowledgeBaseId": "*string", "Metadata": "map[string]string", "OverrideLinkOutUri": "*string", "RemoveOverrideLinkOutUri": "*bool", "RevisionId": "*string", "Title": "*string", "UploadId": "*string"},
			"update-knowledge-base-template-uri": {"KnowledgeBaseId": "*string", "TemplateUri": "*string"},
			"update-quick-response":              {"Channels": "[]string", "Content": "types.QuickResponseDataProvider", "ContentType": "*string", "Description": "*string", "GroupingConfiguration": "*types.GroupingConfiguration", "IsActive": "*bool", "KnowledgeBaseId": "*string", "Language": "*string", "Name": "*string", "QuickResponseId": "*string", "RemoveDescription": "*bool", "RemoveGroupingConfiguration": "*bool", "RemoveShortcutKey": "*bool", "ShortcutKey": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-assistant":                   {"Name", "Type"},
			"create-assistant-association":       {"AssistantId", "Association", "AssociationType"},
			"create-content":                     {"KnowledgeBaseId", "Name", "UploadId"},
			"create-knowledge-base":              {"KnowledgeBaseType", "Name"},
			"create-quick-response":              {"Content", "KnowledgeBaseId", "Name"},
			"create-session":                     {"AssistantId", "Name"},
			"delete-assistant":                   {"AssistantId"},
			"delete-assistant-association":       {"AssistantAssociationId", "AssistantId"},
			"delete-content":                     {"ContentId", "KnowledgeBaseId"},
			"delete-import-job":                  {"ImportJobId", "KnowledgeBaseId"},
			"delete-knowledge-base":              {"KnowledgeBaseId"},
			"delete-quick-response":              {"KnowledgeBaseId", "QuickResponseId"},
			"get-assistant":                      {"AssistantId"},
			"get-assistant-association":          {"AssistantAssociationId", "AssistantId"},
			"get-content":                        {"ContentId", "KnowledgeBaseId"},
			"get-content-summary":                {"ContentId", "KnowledgeBaseId"},
			"get-import-job":                     {"ImportJobId", "KnowledgeBaseId"},
			"get-knowledge-base":                 {"KnowledgeBaseId"},
			"get-quick-response":                 {"KnowledgeBaseId", "QuickResponseId"},
			"get-recommendations":                {"AssistantId", "SessionId"},
			"get-session":                        {"AssistantId", "SessionId"},
			"list-assistant-associations":        {"AssistantId"},
			"list-assistants":                    {},
			"list-contents":                      {"KnowledgeBaseId"},
			"list-import-jobs":                   {"KnowledgeBaseId"},
			"list-knowledge-bases":               {},
			"list-quick-responses":               {"KnowledgeBaseId"},
			"list-tags-for-resource":             {"ResourceArn"},
			"notify-recommendations-received":    {"AssistantId", "RecommendationIds", "SessionId"},
			"query-assistant":                    {"AssistantId", "QueryText"},
			"remove-knowledge-base-template-uri": {"KnowledgeBaseId"},
			"search-content":                     {"KnowledgeBaseId", "SearchExpression"},
			"search-quick-responses":             {"KnowledgeBaseId", "SearchExpression"},
			"search-sessions":                    {"AssistantId", "SearchExpression"},
			"start-content-upload":               {"ContentType", "KnowledgeBaseId"},
			"start-import-job":                   {"ImportJobType", "KnowledgeBaseId", "UploadId"},
			"tag-resource":                       {"ResourceArn", "Tags"},
			"untag-resource":                     {"ResourceArn", "TagKeys"},
			"update-content":                     {"ContentId", "KnowledgeBaseId"},
			"update-knowledge-base-template-uri": {"KnowledgeBaseId", "TemplateUri"},
			"update-quick-response":              {"KnowledgeBaseId", "QuickResponseId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("wisdom", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
