package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/odb/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-marketplace-registration", "associate-iam-role-to-resource", "create-cloud-autonomous-vm-cluster", "create-cloud-exadata-infrastructure", "create-cloud-vm-cluster", "create-odb-network", "create-odb-peering-connection", "delete-cloud-autonomous-vm-cluster", "delete-cloud-exadata-infrastructure", "delete-cloud-vm-cluster", "delete-odb-network", "delete-odb-peering-connection", "disassociate-iam-role-from-resource", "get-cloud-autonomous-vm-cluster", "get-cloud-exadata-infrastructure", "get-cloud-exadata-infrastructure-unallocated-resources", "get-cloud-vm-cluster", "get-db-node", "get-db-server", "get-oci-onboarding-status", "get-odb-network", "get-odb-peering-connection", "initialize-service", "list-autonomous-virtual-machines", "list-cloud-autonomous-vm-clusters", "list-cloud-exadata-infrastructures", "list-cloud-vm-clusters", "list-db-nodes", "list-db-servers", "list-db-system-shapes", "list-gi-versions", "list-odb-networks", "list-odb-peering-connections", "list-system-versions", "list-tags-for-resource", "reboot-db-node", "start-db-node", "stop-db-node", "tag-resource", "untag-resource", "update-cloud-exadata-infrastructure", "update-odb-network", "update-odb-peering-connection"},
		OperationSet: map[string]bool{"accept-marketplace-registration": true, "associate-iam-role-to-resource": true, "create-cloud-autonomous-vm-cluster": true, "create-cloud-exadata-infrastructure": true, "create-cloud-vm-cluster": true, "create-odb-network": true, "create-odb-peering-connection": true, "delete-cloud-autonomous-vm-cluster": true, "delete-cloud-exadata-infrastructure": true, "delete-cloud-vm-cluster": true, "delete-odb-network": true, "delete-odb-peering-connection": true, "disassociate-iam-role-from-resource": true, "get-cloud-autonomous-vm-cluster": true, "get-cloud-exadata-infrastructure": true, "get-cloud-exadata-infrastructure-unallocated-resources": true, "get-cloud-vm-cluster": true, "get-db-node": true, "get-db-server": true, "get-oci-onboarding-status": true, "get-odb-network": true, "get-odb-peering-connection": true, "initialize-service": true, "list-autonomous-virtual-machines": true, "list-cloud-autonomous-vm-clusters": true, "list-cloud-exadata-infrastructures": true, "list-cloud-vm-clusters": true, "list-db-nodes": true, "list-db-servers": true, "list-db-system-shapes": true, "list-gi-versions": true, "list-odb-networks": true, "list-odb-peering-connections": true, "list-system-versions": true, "list-tags-for-resource": true, "reboot-db-node": true, "start-db-node": true, "stop-db-node": true, "tag-resource": true, "untag-resource": true, "update-cloud-exadata-infrastructure": true, "update-odb-network": true, "update-odb-peering-connection": true},
		OperationInputs: map[string][]string{
			"accept-marketplace-registration":                        {"MarketplaceRegistrationToken"},
			"associate-iam-role-to-resource":                         {"AwsIntegration", "IamRoleArn", "ResourceArn"},
			"create-cloud-autonomous-vm-cluster":                     {"AutonomousDataStorageSizeInTBs", "ClientToken", "CloudExadataInfrastructureId", "CpuCoreCountPerNode", "DbServers", "Description", "DisplayName", "IsMtlsEnabledVmCluster", "LicenseModel", "MaintenanceWindow", "MemoryPerOracleComputeUnitInGBs", "OdbNetworkId", "ScanListenerPortNonTls", "ScanListenerPortTls", "Tags", "TimeZone", "TotalContainerDatabases"},
			"create-cloud-exadata-infrastructure":                    {"AvailabilityZone", "AvailabilityZoneId", "ClientToken", "ComputeCount", "CustomerContactsToSendToOCI", "DatabaseServerType", "DisplayName", "MaintenanceWindow", "Shape", "StorageCount", "StorageServerType", "Tags"},
			"create-cloud-vm-cluster":                                {"ClientToken", "CloudExadataInfrastructureId", "ClusterName", "CpuCoreCount", "DataCollectionOptions", "DataStorageSizeInTBs", "DbNodeStorageSizeInGBs", "DbServers", "DisplayName", "GiVersion", "Hostname", "IsLocalBackupEnabled", "IsSparseDiskgroupEnabled", "LicenseModel", "MemorySizeInGBs", "OdbNetworkId", "ScanListenerPortTcp", "SshPublicKeys", "SystemVersion", "Tags", "TimeZone"},
			"create-odb-network":                                     {"AvailabilityZone", "AvailabilityZoneId", "BackupSubnetCidr", "ClientSubnetCidr", "ClientToken", "CrossRegionS3RestoreSourcesToEnable", "CustomDomainName", "DefaultDnsPrefix", "DisplayName", "KmsAccess", "KmsPolicyDocument", "S3Access", "S3PolicyDocument", "StsAccess", "StsPolicyDocument", "Tags", "ZeroEtlAccess"},
			"create-odb-peering-connection":                          {"ClientToken", "DisplayName", "OdbNetworkId", "PeerNetworkCidrsToBeAdded", "PeerNetworkId", "PeerNetworkRouteTableIds", "Tags"},
			"delete-cloud-autonomous-vm-cluster":                     {"CloudAutonomousVmClusterId"},
			"delete-cloud-exadata-infrastructure":                    {"CloudExadataInfrastructureId"},
			"delete-cloud-vm-cluster":                                {"CloudVmClusterId"},
			"delete-odb-network":                                     {"DeleteAssociatedResources", "OdbNetworkId"},
			"delete-odb-peering-connection":                          {"OdbPeeringConnectionId"},
			"disassociate-iam-role-from-resource":                    {"AwsIntegration", "IamRoleArn", "ResourceArn"},
			"get-cloud-autonomous-vm-cluster":                        {"CloudAutonomousVmClusterId"},
			"get-cloud-exadata-infrastructure":                       {"CloudExadataInfrastructureId"},
			"get-cloud-exadata-infrastructure-unallocated-resources": {"CloudExadataInfrastructureId", "DbServers"},
			"get-cloud-vm-cluster":                                   {"CloudVmClusterId"},
			"get-db-node":                                            {"CloudVmClusterId", "DbNodeId"},
			"get-db-server":                                          {"CloudExadataInfrastructureId", "DbServerId"},
			"get-oci-onboarding-status":                              {},
			"get-odb-network":                                        {"OdbNetworkId"},
			"get-odb-peering-connection":                             {"OdbPeeringConnectionId"},
			"initialize-service":                                     {"OciIdentityDomain"},
			"list-autonomous-virtual-machines":                       {"CloudAutonomousVmClusterId", "MaxResults", "NextToken"},
			"list-cloud-autonomous-vm-clusters":                      {"CloudExadataInfrastructureId", "MaxResults", "NextToken"},
			"list-cloud-exadata-infrastructures":                     {"MaxResults", "NextToken"},
			"list-cloud-vm-clusters":                                 {"CloudExadataInfrastructureId", "MaxResults", "NextToken"},
			"list-db-nodes":                                          {"CloudVmClusterId", "MaxResults", "NextToken"},
			"list-db-servers":                                        {"CloudExadataInfrastructureId", "MaxResults", "NextToken"},
			"list-db-system-shapes":                                  {"AvailabilityZone", "AvailabilityZoneId", "MaxResults", "NextToken"},
			"list-gi-versions":                                       {"MaxResults", "NextToken", "Shape"},
			"list-odb-networks":                                      {"MaxResults", "NextToken"},
			"list-odb-peering-connections":                           {"MaxResults", "NextToken", "OdbNetworkId"},
			"list-system-versions":                                   {"GiVersion", "MaxResults", "NextToken", "Shape"},
			"list-tags-for-resource":                                 {"ResourceArn"},
			"reboot-db-node":                                         {"CloudVmClusterId", "DbNodeId"},
			"start-db-node":                                          {"CloudVmClusterId", "DbNodeId"},
			"stop-db-node":                                           {"CloudVmClusterId", "DbNodeId"},
			"tag-resource":                                           {"ResourceArn", "Tags"},
			"untag-resource":                                         {"ResourceArn", "TagKeys"},
			"update-cloud-exadata-infrastructure":                    {"CloudExadataInfrastructureId", "MaintenanceWindow"},
			"update-odb-network":                                     {"CrossRegionS3RestoreSourcesToDisable", "CrossRegionS3RestoreSourcesToEnable", "DisplayName", "KmsAccess", "KmsPolicyDocument", "OdbNetworkId", "PeeredCidrsToBeAdded", "PeeredCidrsToBeRemoved", "S3Access", "S3PolicyDocument", "StsAccess", "StsPolicyDocument", "ZeroEtlAccess"},
			"update-odb-peering-connection":                          {"DisplayName", "OdbPeeringConnectionId", "PeerNetworkCidrsToBeAdded", "PeerNetworkCidrsToBeRemoved"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-marketplace-registration":                        {"MarketplaceRegistrationToken": "*string"},
			"associate-iam-role-to-resource":                         {"AwsIntegration": "types.SupportedAwsIntegration", "IamRoleArn": "*string", "ResourceArn": "*string"},
			"create-cloud-autonomous-vm-cluster":                     {"AutonomousDataStorageSizeInTBs": "*float64", "ClientToken": "*string", "CloudExadataInfrastructureId": "*string", "CpuCoreCountPerNode": "*int32", "DbServers": "[]string", "Description": "*string", "DisplayName": "*string", "IsMtlsEnabledVmCluster": "*bool", "LicenseModel": "types.LicenseModel", "MaintenanceWindow": "*types.MaintenanceWindow", "MemoryPerOracleComputeUnitInGBs": "*int32", "OdbNetworkId": "*string", "ScanListenerPortNonTls": "*int32", "ScanListenerPortTls": "*int32", "Tags": "map[string]string", "TimeZone": "*string", "TotalContainerDatabases": "*int32"},
			"create-cloud-exadata-infrastructure":                    {"AvailabilityZone": "*string", "AvailabilityZoneId": "*string", "ClientToken": "*string", "ComputeCount": "*int32", "CustomerContactsToSendToOCI": "[]types.CustomerContact", "DatabaseServerType": "*string", "DisplayName": "*string", "MaintenanceWindow": "*types.MaintenanceWindow", "Shape": "*string", "StorageCount": "*int32", "StorageServerType": "*string", "Tags": "map[string]string"},
			"create-cloud-vm-cluster":                                {"ClientToken": "*string", "CloudExadataInfrastructureId": "*string", "ClusterName": "*string", "CpuCoreCount": "*int32", "DataCollectionOptions": "*types.DataCollectionOptions", "DataStorageSizeInTBs": "*float64", "DbNodeStorageSizeInGBs": "*int32", "DbServers": "[]string", "DisplayName": "*string", "GiVersion": "*string", "Hostname": "*string", "IsLocalBackupEnabled": "*bool", "IsSparseDiskgroupEnabled": "*bool", "LicenseModel": "types.LicenseModel", "MemorySizeInGBs": "*int32", "OdbNetworkId": "*string", "ScanListenerPortTcp": "*int32", "SshPublicKeys": "[]string", "SystemVersion": "*string", "Tags": "map[string]string", "TimeZone": "*string"},
			"create-odb-network":                                     {"AvailabilityZone": "*string", "AvailabilityZoneId": "*string", "BackupSubnetCidr": "*string", "ClientSubnetCidr": "*string", "ClientToken": "*string", "CrossRegionS3RestoreSourcesToEnable": "[]string", "CustomDomainName": "*string", "DefaultDnsPrefix": "*string", "DisplayName": "*string", "KmsAccess": "types.Access", "KmsPolicyDocument": "*string", "S3Access": "types.Access", "S3PolicyDocument": "*string", "StsAccess": "types.Access", "StsPolicyDocument": "*string", "Tags": "map[string]string", "ZeroEtlAccess": "types.Access"},
			"create-odb-peering-connection":                          {"ClientToken": "*string", "DisplayName": "*string", "OdbNetworkId": "*string", "PeerNetworkCidrsToBeAdded": "[]string", "PeerNetworkId": "*string", "PeerNetworkRouteTableIds": "[]string", "Tags": "map[string]string"},
			"delete-cloud-autonomous-vm-cluster":                     {"CloudAutonomousVmClusterId": "*string"},
			"delete-cloud-exadata-infrastructure":                    {"CloudExadataInfrastructureId": "*string"},
			"delete-cloud-vm-cluster":                                {"CloudVmClusterId": "*string"},
			"delete-odb-network":                                     {"DeleteAssociatedResources": "*bool", "OdbNetworkId": "*string"},
			"delete-odb-peering-connection":                          {"OdbPeeringConnectionId": "*string"},
			"disassociate-iam-role-from-resource":                    {"AwsIntegration": "types.SupportedAwsIntegration", "IamRoleArn": "*string", "ResourceArn": "*string"},
			"get-cloud-autonomous-vm-cluster":                        {"CloudAutonomousVmClusterId": "*string"},
			"get-cloud-exadata-infrastructure":                       {"CloudExadataInfrastructureId": "*string"},
			"get-cloud-exadata-infrastructure-unallocated-resources": {"CloudExadataInfrastructureId": "*string", "DbServers": "[]string"},
			"get-cloud-vm-cluster":                                   {"CloudVmClusterId": "*string"},
			"get-db-node":                                            {"CloudVmClusterId": "*string", "DbNodeId": "*string"},
			"get-db-server":                                          {"CloudExadataInfrastructureId": "*string", "DbServerId": "*string"},
			"get-oci-onboarding-status":                              {},
			"get-odb-network":                                        {"OdbNetworkId": "*string"},
			"get-odb-peering-connection":                             {"OdbPeeringConnectionId": "*string"},
			"initialize-service":                                     {"OciIdentityDomain": "*bool"},
			"list-autonomous-virtual-machines":                       {"CloudAutonomousVmClusterId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-cloud-autonomous-vm-clusters":                      {"CloudExadataInfrastructureId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-cloud-exadata-infrastructures":                     {"MaxResults": "*int32", "NextToken": "*string"},
			"list-cloud-vm-clusters":                                 {"CloudExadataInfrastructureId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-db-nodes":                                          {"CloudVmClusterId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-db-servers":                                        {"CloudExadataInfrastructureId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-db-system-shapes":                                  {"AvailabilityZone": "*string", "AvailabilityZoneId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-gi-versions":                                       {"MaxResults": "*int32", "NextToken": "*string", "Shape": "*string"},
			"list-odb-networks":                                      {"MaxResults": "*int32", "NextToken": "*string"},
			"list-odb-peering-connections":                           {"MaxResults": "*int32", "NextToken": "*string", "OdbNetworkId": "*string"},
			"list-system-versions":                                   {"GiVersion": "*string", "MaxResults": "*int32", "NextToken": "*string", "Shape": "*string"},
			"list-tags-for-resource":                                 {"ResourceArn": "*string"},
			"reboot-db-node":                                         {"CloudVmClusterId": "*string", "DbNodeId": "*string"},
			"start-db-node":                                          {"CloudVmClusterId": "*string", "DbNodeId": "*string"},
			"stop-db-node":                                           {"CloudVmClusterId": "*string", "DbNodeId": "*string"},
			"tag-resource":                                           {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                                         {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-cloud-exadata-infrastructure":                    {"CloudExadataInfrastructureId": "*string", "MaintenanceWindow": "*types.MaintenanceWindow"},
			"update-odb-network":                                     {"CrossRegionS3RestoreSourcesToDisable": "[]string", "CrossRegionS3RestoreSourcesToEnable": "[]string", "DisplayName": "*string", "KmsAccess": "types.Access", "KmsPolicyDocument": "*string", "OdbNetworkId": "*string", "PeeredCidrsToBeAdded": "[]string", "PeeredCidrsToBeRemoved": "[]string", "S3Access": "types.Access", "S3PolicyDocument": "*string", "StsAccess": "types.Access", "StsPolicyDocument": "*string", "ZeroEtlAccess": "types.Access"},
			"update-odb-peering-connection":                          {"DisplayName": "*string", "OdbPeeringConnectionId": "*string", "PeerNetworkCidrsToBeAdded": "[]string", "PeerNetworkCidrsToBeRemoved": "[]string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-marketplace-registration":                        {"MarketplaceRegistrationToken"},
			"associate-iam-role-to-resource":                         {"AwsIntegration", "IamRoleArn", "ResourceArn"},
			"create-cloud-autonomous-vm-cluster":                     {"AutonomousDataStorageSizeInTBs", "CloudExadataInfrastructureId", "CpuCoreCountPerNode", "DisplayName", "MemoryPerOracleComputeUnitInGBs", "OdbNetworkId", "TotalContainerDatabases"},
			"create-cloud-exadata-infrastructure":                    {"ComputeCount", "DisplayName", "Shape", "StorageCount"},
			"create-cloud-vm-cluster":                                {"CloudExadataInfrastructureId", "CpuCoreCount", "DisplayName", "GiVersion", "Hostname", "OdbNetworkId", "SshPublicKeys"},
			"create-odb-network":                                     {"ClientSubnetCidr", "DisplayName"},
			"create-odb-peering-connection":                          {"OdbNetworkId", "PeerNetworkId"},
			"delete-cloud-autonomous-vm-cluster":                     {"CloudAutonomousVmClusterId"},
			"delete-cloud-exadata-infrastructure":                    {"CloudExadataInfrastructureId"},
			"delete-cloud-vm-cluster":                                {"CloudVmClusterId"},
			"delete-odb-network":                                     {"DeleteAssociatedResources", "OdbNetworkId"},
			"delete-odb-peering-connection":                          {"OdbPeeringConnectionId"},
			"disassociate-iam-role-from-resource":                    {"AwsIntegration", "IamRoleArn", "ResourceArn"},
			"get-cloud-autonomous-vm-cluster":                        {"CloudAutonomousVmClusterId"},
			"get-cloud-exadata-infrastructure":                       {"CloudExadataInfrastructureId"},
			"get-cloud-exadata-infrastructure-unallocated-resources": {"CloudExadataInfrastructureId"},
			"get-cloud-vm-cluster":                                   {"CloudVmClusterId"},
			"get-db-node":                                            {"CloudVmClusterId", "DbNodeId"},
			"get-db-server":                                          {"CloudExadataInfrastructureId", "DbServerId"},
			"get-oci-onboarding-status":                              {},
			"get-odb-network":                                        {"OdbNetworkId"},
			"get-odb-peering-connection":                             {"OdbPeeringConnectionId"},
			"initialize-service":                                     {},
			"list-autonomous-virtual-machines":                       {"CloudAutonomousVmClusterId"},
			"list-cloud-autonomous-vm-clusters":                      {},
			"list-cloud-exadata-infrastructures":                     {},
			"list-cloud-vm-clusters":                                 {},
			"list-db-nodes":                                          {"CloudVmClusterId"},
			"list-db-servers":                                        {"CloudExadataInfrastructureId"},
			"list-db-system-shapes":                                  {},
			"list-gi-versions":                                       {},
			"list-odb-networks":                                      {},
			"list-odb-peering-connections":                           {},
			"list-system-versions":                                   {"GiVersion", "Shape"},
			"list-tags-for-resource":                                 {"ResourceArn"},
			"reboot-db-node":                                         {"CloudVmClusterId", "DbNodeId"},
			"start-db-node":                                          {"CloudVmClusterId", "DbNodeId"},
			"stop-db-node":                                           {"CloudVmClusterId", "DbNodeId"},
			"tag-resource":                                           {"ResourceArn", "Tags"},
			"untag-resource":                                         {"ResourceArn", "TagKeys"},
			"update-cloud-exadata-infrastructure":                    {"CloudExadataInfrastructureId"},
			"update-odb-network":                                     {"OdbNetworkId"},
			"update-odb-peering-connection":                          {"OdbPeeringConnectionId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("odb", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
