package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/elasticsearchservice/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-inbound-cross-cluster-search-connection", "add-tags", "associate-package", "authorize-vpc-endpoint-access", "cancel-domain-config-change", "cancel-elasticsearch-service-software-update", "create-elasticsearch-domain", "create-outbound-cross-cluster-search-connection", "create-package", "create-vpc-endpoint", "delete-elasticsearch-domain", "delete-elasticsearch-service-role", "delete-inbound-cross-cluster-search-connection", "delete-outbound-cross-cluster-search-connection", "delete-package", "delete-vpc-endpoint", "describe-domain-auto-tunes", "describe-domain-change-progress", "describe-elasticsearch-domain", "describe-elasticsearch-domain-config", "describe-elasticsearch-domains", "describe-elasticsearch-instance-type-limits", "describe-inbound-cross-cluster-search-connections", "describe-outbound-cross-cluster-search-connections", "describe-packages", "describe-reserved-elasticsearch-instance-offerings", "describe-reserved-elasticsearch-instances", "describe-vpc-endpoints", "dissociate-package", "get-compatible-elasticsearch-versions", "get-package-version-history", "get-upgrade-history", "get-upgrade-status", "list-domain-names", "list-domains-for-package", "list-elasticsearch-instance-types", "list-elasticsearch-versions", "list-packages-for-domain", "list-tags", "list-vpc-endpoint-access", "list-vpc-endpoints", "list-vpc-endpoints-for-domain", "purchase-reserved-elasticsearch-instance-offering", "reject-inbound-cross-cluster-search-connection", "remove-tags", "revoke-vpc-endpoint-access", "start-elasticsearch-service-software-update", "update-elasticsearch-domain-config", "update-package", "update-vpc-endpoint", "upgrade-elasticsearch-domain"},
		OperationSet: map[string]bool{"accept-inbound-cross-cluster-search-connection": true, "add-tags": true, "associate-package": true, "authorize-vpc-endpoint-access": true, "cancel-domain-config-change": true, "cancel-elasticsearch-service-software-update": true, "create-elasticsearch-domain": true, "create-outbound-cross-cluster-search-connection": true, "create-package": true, "create-vpc-endpoint": true, "delete-elasticsearch-domain": true, "delete-elasticsearch-service-role": true, "delete-inbound-cross-cluster-search-connection": true, "delete-outbound-cross-cluster-search-connection": true, "delete-package": true, "delete-vpc-endpoint": true, "describe-domain-auto-tunes": true, "describe-domain-change-progress": true, "describe-elasticsearch-domain": true, "describe-elasticsearch-domain-config": true, "describe-elasticsearch-domains": true, "describe-elasticsearch-instance-type-limits": true, "describe-inbound-cross-cluster-search-connections": true, "describe-outbound-cross-cluster-search-connections": true, "describe-packages": true, "describe-reserved-elasticsearch-instance-offerings": true, "describe-reserved-elasticsearch-instances": true, "describe-vpc-endpoints": true, "dissociate-package": true, "get-compatible-elasticsearch-versions": true, "get-package-version-history": true, "get-upgrade-history": true, "get-upgrade-status": true, "list-domain-names": true, "list-domains-for-package": true, "list-elasticsearch-instance-types": true, "list-elasticsearch-versions": true, "list-packages-for-domain": true, "list-tags": true, "list-vpc-endpoint-access": true, "list-vpc-endpoints": true, "list-vpc-endpoints-for-domain": true, "purchase-reserved-elasticsearch-instance-offering": true, "reject-inbound-cross-cluster-search-connection": true, "remove-tags": true, "revoke-vpc-endpoint-access": true, "start-elasticsearch-service-software-update": true, "update-elasticsearch-domain-config": true, "update-package": true, "update-vpc-endpoint": true, "upgrade-elasticsearch-domain": true},
		OperationInputs: map[string][]string{
			"accept-inbound-cross-cluster-search-connection": {"CrossClusterSearchConnectionId"},
			"add-tags":                                           {"ARN", "TagList"},
			"associate-package":                                  {"DomainName", "PackageID"},
			"authorize-vpc-endpoint-access":                      {"Account", "DomainName"},
			"cancel-domain-config-change":                        {"DomainName", "DryRun"},
			"cancel-elasticsearch-service-software-update":       {"DomainName"},
			"create-elasticsearch-domain":                        {"AccessPolicies", "AdvancedOptions", "AdvancedSecurityOptions", "AutoTuneOptions", "CognitoOptions", "DomainEndpointOptions", "DomainName", "EBSOptions", "ElasticsearchClusterConfig", "ElasticsearchVersion", "EncryptionAtRestOptions", "LogPublishingOptions", "NodeToNodeEncryptionOptions", "SnapshotOptions", "TagList", "VPCOptions"},
			"create-outbound-cross-cluster-search-connection":    {"ConnectionAlias", "DestinationDomainInfo", "SourceDomainInfo"},
			"create-package":                                     {"PackageDescription", "PackageName", "PackageSource", "PackageType"},
			"create-vpc-endpoint":                                {"ClientToken", "DomainArn", "VpcOptions"},
			"delete-elasticsearch-domain":                        {"DomainName"},
			"delete-elasticsearch-service-role":                  {},
			"delete-inbound-cross-cluster-search-connection":     {"CrossClusterSearchConnectionId"},
			"delete-outbound-cross-cluster-search-connection":    {"CrossClusterSearchConnectionId"},
			"delete-package":                                     {"PackageID"},
			"delete-vpc-endpoint":                                {"VpcEndpointId"},
			"describe-domain-auto-tunes":                         {"DomainName", "MaxResults", "NextToken"},
			"describe-domain-change-progress":                    {"ChangeId", "DomainName"},
			"describe-elasticsearch-domain":                      {"DomainName"},
			"describe-elasticsearch-domain-config":               {"DomainName"},
			"describe-elasticsearch-domains":                     {"DomainNames"},
			"describe-elasticsearch-instance-type-limits":        {"DomainName", "ElasticsearchVersion", "InstanceType"},
			"describe-inbound-cross-cluster-search-connections":  {"Filters", "MaxResults", "NextToken"},
			"describe-outbound-cross-cluster-search-connections": {"Filters", "MaxResults", "NextToken"},
			"describe-packages":                                  {"Filters", "MaxResults", "NextToken"},
			"describe-reserved-elasticsearch-instance-offerings": {"MaxResults", "NextToken", "ReservedElasticsearchInstanceOfferingId"},
			"describe-reserved-elasticsearch-instances":          {"MaxResults", "NextToken", "ReservedElasticsearchInstanceId"},
			"describe-vpc-endpoints":                             {"VpcEndpointIds"},
			"dissociate-package":                                 {"DomainName", "PackageID"},
			"get-compatible-elasticsearch-versions":              {"DomainName"},
			"get-package-version-history":                        {"MaxResults", "NextToken", "PackageID"},
			"get-upgrade-history":                                {"DomainName", "MaxResults", "NextToken"},
			"get-upgrade-status":                                 {"DomainName"},
			"list-domain-names":                                  {"EngineType"},
			"list-domains-for-package":                           {"MaxResults", "NextToken", "PackageID"},
			"list-elasticsearch-instance-types":                  {"DomainName", "ElasticsearchVersion", "MaxResults", "NextToken"},
			"list-elasticsearch-versions":                        {"MaxResults", "NextToken"},
			"list-packages-for-domain":                           {"DomainName", "MaxResults", "NextToken"},
			"list-tags":                                          {"ARN"},
			"list-vpc-endpoint-access":                           {"DomainName", "NextToken"},
			"list-vpc-endpoints":                                 {"NextToken"},
			"list-vpc-endpoints-for-domain":                      {"DomainName", "NextToken"},
			"purchase-reserved-elasticsearch-instance-offering":  {"InstanceCount", "ReservationName", "ReservedElasticsearchInstanceOfferingId"},
			"reject-inbound-cross-cluster-search-connection":     {"CrossClusterSearchConnectionId"},
			"remove-tags":                                        {"ARN", "TagKeys"},
			"revoke-vpc-endpoint-access":                         {"Account", "DomainName"},
			"start-elasticsearch-service-software-update":        {"DomainName"},
			"update-elasticsearch-domain-config":                 {"AccessPolicies", "AdvancedOptions", "AdvancedSecurityOptions", "AutoTuneOptions", "CognitoOptions", "DomainEndpointOptions", "DomainName", "DryRun", "EBSOptions", "ElasticsearchClusterConfig", "EncryptionAtRestOptions", "LogPublishingOptions", "NodeToNodeEncryptionOptions", "SnapshotOptions", "VPCOptions"},
			"update-package":                                     {"CommitMessage", "PackageDescription", "PackageID", "PackageSource"},
			"update-vpc-endpoint":                                {"VpcEndpointId", "VpcOptions"},
			"upgrade-elasticsearch-domain":                       {"DomainName", "PerformCheckOnly", "TargetVersion"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-inbound-cross-cluster-search-connection": {"CrossClusterSearchConnectionId": "*string"},
			"add-tags":                                           {"ARN": "*string", "TagList": "[]types.Tag"},
			"associate-package":                                  {"DomainName": "*string", "PackageID": "*string"},
			"authorize-vpc-endpoint-access":                      {"Account": "*string", "DomainName": "*string"},
			"cancel-domain-config-change":                        {"DomainName": "*string", "DryRun": "*bool"},
			"cancel-elasticsearch-service-software-update":       {"DomainName": "*string"},
			"create-elasticsearch-domain":                        {"AccessPolicies": "*string", "AdvancedOptions": "map[string]string", "AdvancedSecurityOptions": "*types.AdvancedSecurityOptionsInput", "AutoTuneOptions": "*types.AutoTuneOptionsInput", "CognitoOptions": "*types.CognitoOptions", "DomainEndpointOptions": "*types.DomainEndpointOptions", "DomainName": "*string", "EBSOptions": "*types.EBSOptions", "ElasticsearchClusterConfig": "*types.ElasticsearchClusterConfig", "ElasticsearchVersion": "*string", "EncryptionAtRestOptions": "*types.EncryptionAtRestOptions", "LogPublishingOptions": "map[string]types.LogPublishingOption", "NodeToNodeEncryptionOptions": "*types.NodeToNodeEncryptionOptions", "SnapshotOptions": "*types.SnapshotOptions", "TagList": "[]types.Tag", "VPCOptions": "*types.VPCOptions"},
			"create-outbound-cross-cluster-search-connection":    {"ConnectionAlias": "*string", "DestinationDomainInfo": "*types.DomainInformation", "SourceDomainInfo": "*types.DomainInformation"},
			"create-package":                                     {"PackageDescription": "*string", "PackageName": "*string", "PackageSource": "*types.PackageSource", "PackageType": "types.PackageType"},
			"create-vpc-endpoint":                                {"ClientToken": "*string", "DomainArn": "*string", "VpcOptions": "*types.VPCOptions"},
			"delete-elasticsearch-domain":                        {"DomainName": "*string"},
			"delete-elasticsearch-service-role":                  {},
			"delete-inbound-cross-cluster-search-connection":     {"CrossClusterSearchConnectionId": "*string"},
			"delete-outbound-cross-cluster-search-connection":    {"CrossClusterSearchConnectionId": "*string"},
			"delete-package":                                     {"PackageID": "*string"},
			"delete-vpc-endpoint":                                {"VpcEndpointId": "*string"},
			"describe-domain-auto-tunes":                         {"DomainName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"describe-domain-change-progress":                    {"ChangeId": "*string", "DomainName": "*string"},
			"describe-elasticsearch-domain":                      {"DomainName": "*string"},
			"describe-elasticsearch-domain-config":               {"DomainName": "*string"},
			"describe-elasticsearch-domains":                     {"DomainNames": "[]string"},
			"describe-elasticsearch-instance-type-limits":        {"DomainName": "*string", "ElasticsearchVersion": "*string", "InstanceType": "types.ESPartitionInstanceType"},
			"describe-inbound-cross-cluster-search-connections":  {"Filters": "[]types.Filter", "MaxResults": "int32", "NextToken": "*string"},
			"describe-outbound-cross-cluster-search-connections": {"Filters": "[]types.Filter", "MaxResults": "int32", "NextToken": "*string"},
			"describe-packages":                                  {"Filters": "[]types.DescribePackagesFilter", "MaxResults": "int32", "NextToken": "*string"},
			"describe-reserved-elasticsearch-instance-offerings": {"MaxResults": "int32", "NextToken": "*string", "ReservedElasticsearchInstanceOfferingId": "*string"},
			"describe-reserved-elasticsearch-instances":          {"MaxResults": "int32", "NextToken": "*string", "ReservedElasticsearchInstanceId": "*string"},
			"describe-vpc-endpoints":                             {"VpcEndpointIds": "[]string"},
			"dissociate-package":                                 {"DomainName": "*string", "PackageID": "*string"},
			"get-compatible-elasticsearch-versions":              {"DomainName": "*string"},
			"get-package-version-history":                        {"MaxResults": "int32", "NextToken": "*string", "PackageID": "*string"},
			"get-upgrade-history":                                {"DomainName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"get-upgrade-status":                                 {"DomainName": "*string"},
			"list-domain-names":                                  {"EngineType": "types.EngineType"},
			"list-domains-for-package":                           {"MaxResults": "int32", "NextToken": "*string", "PackageID": "*string"},
			"list-elasticsearch-instance-types":                  {"DomainName": "*string", "ElasticsearchVersion": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-elasticsearch-versions":                        {"MaxResults": "int32", "NextToken": "*string"},
			"list-packages-for-domain":                           {"DomainName": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-tags":                                          {"ARN": "*string"},
			"list-vpc-endpoint-access":                           {"DomainName": "*string", "NextToken": "*string"},
			"list-vpc-endpoints":                                 {"NextToken": "*string"},
			"list-vpc-endpoints-for-domain":                      {"DomainName": "*string", "NextToken": "*string"},
			"purchase-reserved-elasticsearch-instance-offering":  {"InstanceCount": "*int32", "ReservationName": "*string", "ReservedElasticsearchInstanceOfferingId": "*string"},
			"reject-inbound-cross-cluster-search-connection":     {"CrossClusterSearchConnectionId": "*string"},
			"remove-tags":                                        {"ARN": "*string", "TagKeys": "[]string"},
			"revoke-vpc-endpoint-access":                         {"Account": "*string", "DomainName": "*string"},
			"start-elasticsearch-service-software-update":        {"DomainName": "*string"},
			"update-elasticsearch-domain-config":                 {"AccessPolicies": "*string", "AdvancedOptions": "map[string]string", "AdvancedSecurityOptions": "*types.AdvancedSecurityOptionsInput", "AutoTuneOptions": "*types.AutoTuneOptions", "CognitoOptions": "*types.CognitoOptions", "DomainEndpointOptions": "*types.DomainEndpointOptions", "DomainName": "*string", "DryRun": "*bool", "EBSOptions": "*types.EBSOptions", "ElasticsearchClusterConfig": "*types.ElasticsearchClusterConfig", "EncryptionAtRestOptions": "*types.EncryptionAtRestOptions", "LogPublishingOptions": "map[string]types.LogPublishingOption", "NodeToNodeEncryptionOptions": "*types.NodeToNodeEncryptionOptions", "SnapshotOptions": "*types.SnapshotOptions", "VPCOptions": "*types.VPCOptions"},
			"update-package":                                     {"CommitMessage": "*string", "PackageDescription": "*string", "PackageID": "*string", "PackageSource": "*types.PackageSource"},
			"update-vpc-endpoint":                                {"VpcEndpointId": "*string", "VpcOptions": "*types.VPCOptions"},
			"upgrade-elasticsearch-domain":                       {"DomainName": "*string", "PerformCheckOnly": "*bool", "TargetVersion": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-inbound-cross-cluster-search-connection": {"CrossClusterSearchConnectionId"},
			"add-tags":                                           {"ARN", "TagList"},
			"associate-package":                                  {"DomainName", "PackageID"},
			"authorize-vpc-endpoint-access":                      {"Account", "DomainName"},
			"cancel-domain-config-change":                        {"DomainName"},
			"cancel-elasticsearch-service-software-update":       {"DomainName"},
			"create-elasticsearch-domain":                        {"DomainName"},
			"create-outbound-cross-cluster-search-connection":    {"ConnectionAlias", "DestinationDomainInfo", "SourceDomainInfo"},
			"create-package":                                     {"PackageName", "PackageSource", "PackageType"},
			"create-vpc-endpoint":                                {"DomainArn", "VpcOptions"},
			"delete-elasticsearch-domain":                        {"DomainName"},
			"delete-elasticsearch-service-role":                  {},
			"delete-inbound-cross-cluster-search-connection":     {"CrossClusterSearchConnectionId"},
			"delete-outbound-cross-cluster-search-connection":    {"CrossClusterSearchConnectionId"},
			"delete-package":                                     {"PackageID"},
			"delete-vpc-endpoint":                                {"VpcEndpointId"},
			"describe-domain-auto-tunes":                         {"DomainName"},
			"describe-domain-change-progress":                    {"DomainName"},
			"describe-elasticsearch-domain":                      {"DomainName"},
			"describe-elasticsearch-domain-config":               {"DomainName"},
			"describe-elasticsearch-domains":                     {"DomainNames"},
			"describe-elasticsearch-instance-type-limits":        {"ElasticsearchVersion", "InstanceType"},
			"describe-inbound-cross-cluster-search-connections":  {},
			"describe-outbound-cross-cluster-search-connections": {},
			"describe-packages":                                  {},
			"describe-reserved-elasticsearch-instance-offerings": {},
			"describe-reserved-elasticsearch-instances":          {},
			"describe-vpc-endpoints":                             {"VpcEndpointIds"},
			"dissociate-package":                                 {"DomainName", "PackageID"},
			"get-compatible-elasticsearch-versions":              {},
			"get-package-version-history":                        {"PackageID"},
			"get-upgrade-history":                                {"DomainName"},
			"get-upgrade-status":                                 {"DomainName"},
			"list-domain-names":                                  {},
			"list-domains-for-package":                           {"PackageID"},
			"list-elasticsearch-instance-types":                  {"ElasticsearchVersion"},
			"list-elasticsearch-versions":                        {},
			"list-packages-for-domain":                           {"DomainName"},
			"list-tags":                                          {"ARN"},
			"list-vpc-endpoint-access":                           {"DomainName"},
			"list-vpc-endpoints":                                 {},
			"list-vpc-endpoints-for-domain":                      {"DomainName"},
			"purchase-reserved-elasticsearch-instance-offering":  {"ReservationName", "ReservedElasticsearchInstanceOfferingId"},
			"reject-inbound-cross-cluster-search-connection":     {"CrossClusterSearchConnectionId"},
			"remove-tags":                                        {"ARN", "TagKeys"},
			"revoke-vpc-endpoint-access":                         {"Account", "DomainName"},
			"start-elasticsearch-service-software-update":        {"DomainName"},
			"update-elasticsearch-domain-config":                 {"DomainName"},
			"update-package":                                     {"PackageID", "PackageSource"},
			"update-vpc-endpoint":                                {"VpcEndpointId", "VpcOptions"},
			"upgrade-elasticsearch-domain":                       {"DomainName", "TargetVersion"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("elasticsearchservice", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
