package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/xray/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-get-traces", "cancel-trace-retrieval", "create-group", "create-sampling-rule", "delete-group", "delete-resource-policy", "delete-sampling-rule", "get-encryption-config", "get-group", "get-groups", "get-indexing-rules", "get-insight", "get-insight-events", "get-insight-impact-graph", "get-insight-summaries", "get-retrieved-traces-graph", "get-sampling-rules", "get-sampling-statistic-summaries", "get-sampling-targets", "get-service-graph", "get-time-series-service-statistics", "get-trace-graph", "get-trace-segment-destination", "get-trace-summaries", "list-resource-policies", "list-retrieved-traces", "list-tags-for-resource", "put-encryption-config", "put-resource-policy", "put-telemetry-records", "put-trace-segments", "start-trace-retrieval", "tag-resource", "untag-resource", "update-group", "update-indexing-rule", "update-sampling-rule", "update-trace-segment-destination"},
		OperationSet: map[string]bool{"batch-get-traces": true, "cancel-trace-retrieval": true, "create-group": true, "create-sampling-rule": true, "delete-group": true, "delete-resource-policy": true, "delete-sampling-rule": true, "get-encryption-config": true, "get-group": true, "get-groups": true, "get-indexing-rules": true, "get-insight": true, "get-insight-events": true, "get-insight-impact-graph": true, "get-insight-summaries": true, "get-retrieved-traces-graph": true, "get-sampling-rules": true, "get-sampling-statistic-summaries": true, "get-sampling-targets": true, "get-service-graph": true, "get-time-series-service-statistics": true, "get-trace-graph": true, "get-trace-segment-destination": true, "get-trace-summaries": true, "list-resource-policies": true, "list-retrieved-traces": true, "list-tags-for-resource": true, "put-encryption-config": true, "put-resource-policy": true, "put-telemetry-records": true, "put-trace-segments": true, "start-trace-retrieval": true, "tag-resource": true, "untag-resource": true, "update-group": true, "update-indexing-rule": true, "update-sampling-rule": true, "update-trace-segment-destination": true},
		OperationInputs: map[string][]string{
			"batch-get-traces":                   {"NextToken", "TraceIds"},
			"cancel-trace-retrieval":             {"RetrievalToken"},
			"create-group":                       {"FilterExpression", "GroupName", "InsightsConfiguration", "Tags"},
			"create-sampling-rule":               {"SamplingRule", "Tags"},
			"delete-group":                       {"GroupARN", "GroupName"},
			"delete-resource-policy":             {"PolicyName", "PolicyRevisionId"},
			"delete-sampling-rule":               {"RuleARN", "RuleName"},
			"get-encryption-config":              {},
			"get-group":                          {"GroupARN", "GroupName"},
			"get-groups":                         {"NextToken"},
			"get-indexing-rules":                 {"NextToken"},
			"get-insight":                        {"InsightId"},
			"get-insight-events":                 {"InsightId", "MaxResults", "NextToken"},
			"get-insight-impact-graph":           {"EndTime", "InsightId", "NextToken", "StartTime"},
			"get-insight-summaries":              {"EndTime", "GroupARN", "GroupName", "MaxResults", "NextToken", "StartTime", "States"},
			"get-retrieved-traces-graph":         {"NextToken", "RetrievalToken"},
			"get-sampling-rules":                 {"NextToken"},
			"get-sampling-statistic-summaries":   {"NextToken"},
			"get-sampling-targets":               {"SamplingBoostStatisticsDocuments", "SamplingStatisticsDocuments"},
			"get-service-graph":                  {"EndTime", "GroupARN", "GroupName", "NextToken", "StartTime"},
			"get-time-series-service-statistics": {"EndTime", "EntitySelectorExpression", "ForecastStatistics", "GroupARN", "GroupName", "NextToken", "Period", "StartTime"},
			"get-trace-graph":                    {"NextToken", "TraceIds"},
			"get-trace-segment-destination":      {},
			"get-trace-summaries":                {"EndTime", "FilterExpression", "NextToken", "Sampling", "SamplingStrategy", "StartTime", "TimeRangeType"},
			"list-resource-policies":             {"NextToken"},
			"list-retrieved-traces":              {"NextToken", "RetrievalToken", "TraceFormat"},
			"list-tags-for-resource":             {"NextToken", "ResourceARN"},
			"put-encryption-config":              {"KeyId", "Type"},
			"put-resource-policy":                {"BypassPolicyLockoutCheck", "PolicyDocument", "PolicyName", "PolicyRevisionId"},
			"put-telemetry-records":              {"EC2InstanceId", "Hostname", "ResourceARN", "TelemetryRecords"},
			"put-trace-segments":                 {"TraceSegmentDocuments"},
			"start-trace-retrieval":              {"EndTime", "StartTime", "TraceIds"},
			"tag-resource":                       {"ResourceARN", "Tags"},
			"untag-resource":                     {"ResourceARN", "TagKeys"},
			"update-group":                       {"FilterExpression", "GroupARN", "GroupName", "InsightsConfiguration"},
			"update-indexing-rule":               {"Name", "Rule"},
			"update-sampling-rule":               {"SamplingRuleUpdate"},
			"update-trace-segment-destination":   {"Destination"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-get-traces":                   {"NextToken": "*string", "TraceIds": "[]string"},
			"cancel-trace-retrieval":             {"RetrievalToken": "*string"},
			"create-group":                       {"FilterExpression": "*string", "GroupName": "*string", "InsightsConfiguration": "*types.InsightsConfiguration", "Tags": "[]types.Tag"},
			"create-sampling-rule":               {"SamplingRule": "*types.SamplingRule", "Tags": "[]types.Tag"},
			"delete-group":                       {"GroupARN": "*string", "GroupName": "*string"},
			"delete-resource-policy":             {"PolicyName": "*string", "PolicyRevisionId": "*string"},
			"delete-sampling-rule":               {"RuleARN": "*string", "RuleName": "*string"},
			"get-encryption-config":              {},
			"get-group":                          {"GroupARN": "*string", "GroupName": "*string"},
			"get-groups":                         {"NextToken": "*string"},
			"get-indexing-rules":                 {"NextToken": "*string"},
			"get-insight":                        {"InsightId": "*string"},
			"get-insight-events":                 {"InsightId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"get-insight-impact-graph":           {"EndTime": "*time.Time", "InsightId": "*string", "NextToken": "*string", "StartTime": "*time.Time"},
			"get-insight-summaries":              {"EndTime": "*time.Time", "GroupARN": "*string", "GroupName": "*string", "MaxResults": "*int32", "NextToken": "*string", "StartTime": "*time.Time", "States": "[]types.InsightState"},
			"get-retrieved-traces-graph":         {"NextToken": "*string", "RetrievalToken": "*string"},
			"get-sampling-rules":                 {"NextToken": "*string"},
			"get-sampling-statistic-summaries":   {"NextToken": "*string"},
			"get-sampling-targets":               {"SamplingBoostStatisticsDocuments": "[]types.SamplingBoostStatisticsDocument", "SamplingStatisticsDocuments": "[]types.SamplingStatisticsDocument"},
			"get-service-graph":                  {"EndTime": "*time.Time", "GroupARN": "*string", "GroupName": "*string", "NextToken": "*string", "StartTime": "*time.Time"},
			"get-time-series-service-statistics": {"EndTime": "*time.Time", "EntitySelectorExpression": "*string", "ForecastStatistics": "*bool", "GroupARN": "*string", "GroupName": "*string", "NextToken": "*string", "Period": "*int32", "StartTime": "*time.Time"},
			"get-trace-graph":                    {"NextToken": "*string", "TraceIds": "[]string"},
			"get-trace-segment-destination":      {},
			"get-trace-summaries":                {"EndTime": "*time.Time", "FilterExpression": "*string", "NextToken": "*string", "Sampling": "*bool", "SamplingStrategy": "*types.SamplingStrategy", "StartTime": "*time.Time", "TimeRangeType": "types.TimeRangeType"},
			"list-resource-policies":             {"NextToken": "*string"},
			"list-retrieved-traces":              {"NextToken": "*string", "RetrievalToken": "*string", "TraceFormat": "types.TraceFormatType"},
			"list-tags-for-resource":             {"NextToken": "*string", "ResourceARN": "*string"},
			"put-encryption-config":              {"KeyId": "*string", "Type": "types.EncryptionType"},
			"put-resource-policy":                {"BypassPolicyLockoutCheck": "bool", "PolicyDocument": "*string", "PolicyName": "*string", "PolicyRevisionId": "*string"},
			"put-telemetry-records":              {"EC2InstanceId": "*string", "Hostname": "*string", "ResourceARN": "*string", "TelemetryRecords": "[]types.TelemetryRecord"},
			"put-trace-segments":                 {"TraceSegmentDocuments": "[]string"},
			"start-trace-retrieval":              {"EndTime": "*time.Time", "StartTime": "*time.Time", "TraceIds": "[]string"},
			"tag-resource":                       {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                     {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-group":                       {"FilterExpression": "*string", "GroupARN": "*string", "GroupName": "*string", "InsightsConfiguration": "*types.InsightsConfiguration"},
			"update-indexing-rule":               {"Name": "*string", "Rule": "types.IndexingRuleValueUpdate"},
			"update-sampling-rule":               {"SamplingRuleUpdate": "*types.SamplingRuleUpdate"},
			"update-trace-segment-destination":   {"Destination": "types.TraceSegmentDestination"},
		},
		OperationInputRequired: map[string][]string{
			"batch-get-traces":                   {"TraceIds"},
			"cancel-trace-retrieval":             {"RetrievalToken"},
			"create-group":                       {"GroupName"},
			"create-sampling-rule":               {"SamplingRule"},
			"delete-group":                       {},
			"delete-resource-policy":             {"PolicyName"},
			"delete-sampling-rule":               {},
			"get-encryption-config":              {},
			"get-group":                          {},
			"get-groups":                         {},
			"get-indexing-rules":                 {},
			"get-insight":                        {"InsightId"},
			"get-insight-events":                 {"InsightId"},
			"get-insight-impact-graph":           {"EndTime", "InsightId", "StartTime"},
			"get-insight-summaries":              {"EndTime", "StartTime"},
			"get-retrieved-traces-graph":         {"RetrievalToken"},
			"get-sampling-rules":                 {},
			"get-sampling-statistic-summaries":   {},
			"get-sampling-targets":               {"SamplingStatisticsDocuments"},
			"get-service-graph":                  {"EndTime", "StartTime"},
			"get-time-series-service-statistics": {"EndTime", "StartTime"},
			"get-trace-graph":                    {"TraceIds"},
			"get-trace-segment-destination":      {},
			"get-trace-summaries":                {"EndTime", "StartTime"},
			"list-resource-policies":             {},
			"list-retrieved-traces":              {"RetrievalToken"},
			"list-tags-for-resource":             {"ResourceARN"},
			"put-encryption-config":              {"Type"},
			"put-resource-policy":                {"PolicyDocument", "PolicyName"},
			"put-telemetry-records":              {"TelemetryRecords"},
			"put-trace-segments":                 {"TraceSegmentDocuments"},
			"start-trace-retrieval":              {"EndTime", "StartTime", "TraceIds"},
			"tag-resource":                       {"ResourceARN", "Tags"},
			"untag-resource":                     {"ResourceARN", "TagKeys"},
			"update-group":                       {},
			"update-indexing-rule":               {"Name", "Rule"},
			"update-sampling-rule":               {"SamplingRuleUpdate"},
			"update-trace-segment-destination":   {},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("xray", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
