package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/iotfleetwise/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-vehicle-fleet", "batch-create-vehicle", "batch-update-vehicle", "create-campaign", "create-decoder-manifest", "create-fleet", "create-model-manifest", "create-signal-catalog", "create-state-template", "create-vehicle", "delete-campaign", "delete-decoder-manifest", "delete-fleet", "delete-model-manifest", "delete-signal-catalog", "delete-state-template", "delete-vehicle", "disassociate-vehicle-fleet", "get-campaign", "get-decoder-manifest", "get-encryption-configuration", "get-fleet", "get-logging-options", "get-model-manifest", "get-register-account-status", "get-signal-catalog", "get-state-template", "get-vehicle", "get-vehicle-status", "import-decoder-manifest", "import-signal-catalog", "list-campaigns", "list-decoder-manifest-network-interfaces", "list-decoder-manifest-signals", "list-decoder-manifests", "list-fleets", "list-fleets-for-vehicle", "list-model-manifest-nodes", "list-model-manifests", "list-signal-catalog-nodes", "list-signal-catalogs", "list-state-templates", "list-tags-for-resource", "list-vehicles", "list-vehicles-in-fleet", "put-encryption-configuration", "put-logging-options", "register-account", "tag-resource", "untag-resource", "update-campaign", "update-decoder-manifest", "update-fleet", "update-model-manifest", "update-signal-catalog", "update-state-template", "update-vehicle"},
		OperationSet: map[string]bool{"associate-vehicle-fleet": true, "batch-create-vehicle": true, "batch-update-vehicle": true, "create-campaign": true, "create-decoder-manifest": true, "create-fleet": true, "create-model-manifest": true, "create-signal-catalog": true, "create-state-template": true, "create-vehicle": true, "delete-campaign": true, "delete-decoder-manifest": true, "delete-fleet": true, "delete-model-manifest": true, "delete-signal-catalog": true, "delete-state-template": true, "delete-vehicle": true, "disassociate-vehicle-fleet": true, "get-campaign": true, "get-decoder-manifest": true, "get-encryption-configuration": true, "get-fleet": true, "get-logging-options": true, "get-model-manifest": true, "get-register-account-status": true, "get-signal-catalog": true, "get-state-template": true, "get-vehicle": true, "get-vehicle-status": true, "import-decoder-manifest": true, "import-signal-catalog": true, "list-campaigns": true, "list-decoder-manifest-network-interfaces": true, "list-decoder-manifest-signals": true, "list-decoder-manifests": true, "list-fleets": true, "list-fleets-for-vehicle": true, "list-model-manifest-nodes": true, "list-model-manifests": true, "list-signal-catalog-nodes": true, "list-signal-catalogs": true, "list-state-templates": true, "list-tags-for-resource": true, "list-vehicles": true, "list-vehicles-in-fleet": true, "put-encryption-configuration": true, "put-logging-options": true, "register-account": true, "tag-resource": true, "untag-resource": true, "update-campaign": true, "update-decoder-manifest": true, "update-fleet": true, "update-model-manifest": true, "update-signal-catalog": true, "update-state-template": true, "update-vehicle": true},
		OperationInputs: map[string][]string{
			"associate-vehicle-fleet":                  {"FleetId", "VehicleName"},
			"batch-create-vehicle":                     {"Vehicles"},
			"batch-update-vehicle":                     {"Vehicles"},
			"create-campaign":                          {"CollectionScheme", "Compression", "DataDestinationConfigs", "DataExtraDimensions", "DataPartitions", "Description", "DiagnosticsMode", "ExpiryTime", "Name", "PostTriggerCollectionDuration", "Priority", "SignalCatalogArn", "SignalsToCollect", "SignalsToFetch", "SpoolingMode", "StartTime", "Tags", "TargetArn"},
			"create-decoder-manifest":                  {"DefaultForUnmappedSignals", "Description", "ModelManifestArn", "Name", "NetworkInterfaces", "SignalDecoders", "Tags"},
			"create-fleet":                             {"Description", "FleetId", "SignalCatalogArn", "Tags"},
			"create-model-manifest":                    {"Description", "Name", "Nodes", "SignalCatalogArn", "Tags"},
			"create-signal-catalog":                    {"Description", "Name", "Nodes", "Tags"},
			"create-state-template":                    {"DataExtraDimensions", "Description", "MetadataExtraDimensions", "Name", "SignalCatalogArn", "StateTemplateProperties", "Tags"},
			"create-vehicle":                           {"AssociationBehavior", "Attributes", "DecoderManifestArn", "ModelManifestArn", "StateTemplates", "Tags", "VehicleName"},
			"delete-campaign":                          {"Name"},
			"delete-decoder-manifest":                  {"Name"},
			"delete-fleet":                             {"FleetId"},
			"delete-model-manifest":                    {"Name"},
			"delete-signal-catalog":                    {"Name"},
			"delete-state-template":                    {"Identifier"},
			"delete-vehicle":                           {"VehicleName"},
			"disassociate-vehicle-fleet":               {"FleetId", "VehicleName"},
			"get-campaign":                             {"Name"},
			"get-decoder-manifest":                     {"Name"},
			"get-encryption-configuration":             {},
			"get-fleet":                                {"FleetId"},
			"get-logging-options":                      {},
			"get-model-manifest":                       {"Name"},
			"get-register-account-status":              {},
			"get-signal-catalog":                       {"Name"},
			"get-state-template":                       {"Identifier"},
			"get-vehicle":                              {"VehicleName"},
			"get-vehicle-status":                       {"MaxResults", "NextToken", "VehicleName"},
			"import-decoder-manifest":                  {"Name", "NetworkFileDefinitions"},
			"import-signal-catalog":                    {"Description", "Name", "Tags", "Vss"},
			"list-campaigns":                           {"ListResponseScope", "MaxResults", "NextToken", "Status"},
			"list-decoder-manifest-network-interfaces": {"MaxResults", "Name", "NextToken"},
			"list-decoder-manifest-signals":            {"MaxResults", "Name", "NextToken"},
			"list-decoder-manifests":                   {"ListResponseScope", "MaxResults", "ModelManifestArn", "NextToken"},
			"list-fleets":                              {"ListResponseScope", "MaxResults", "NextToken"},
			"list-fleets-for-vehicle":                  {"MaxResults", "NextToken", "VehicleName"},
			"list-model-manifest-nodes":                {"MaxResults", "Name", "NextToken"},
			"list-model-manifests":                     {"ListResponseScope", "MaxResults", "NextToken", "SignalCatalogArn"},
			"list-signal-catalog-nodes":                {"MaxResults", "Name", "NextToken", "SignalNodeType"},
			"list-signal-catalogs":                     {"MaxResults", "NextToken"},
			"list-state-templates":                     {"ListResponseScope", "MaxResults", "NextToken"},
			"list-tags-for-resource":                   {"ResourceARN"},
			"list-vehicles":                            {"AttributeNames", "AttributeValues", "ListResponseScope", "MaxResults", "ModelManifestArn", "NextToken"},
			"list-vehicles-in-fleet":                   {"FleetId", "MaxResults", "NextToken"},
			"put-encryption-configuration":             {"EncryptionType", "KmsKeyId"},
			"put-logging-options":                      {"CloudWatchLogDelivery"},
			"register-account":                         {"IamResources", "TimestreamResources"},
			"tag-resource":                             {"ResourceARN", "Tags"},
			"untag-resource":                           {"ResourceARN", "TagKeys"},
			"update-campaign":                          {"Action", "DataExtraDimensions", "Description", "Name"},
			"update-decoder-manifest":                  {"DefaultForUnmappedSignals", "Description", "Name", "NetworkInterfacesToAdd", "NetworkInterfacesToRemove", "NetworkInterfacesToUpdate", "SignalDecodersToAdd", "SignalDecodersToRemove", "SignalDecodersToUpdate", "Status"},
			"update-fleet":                             {"Description", "FleetId"},
			"update-model-manifest":                    {"Description", "Name", "NodesToAdd", "NodesToRemove", "Status"},
			"update-signal-catalog":                    {"Description", "Name", "NodesToAdd", "NodesToRemove", "NodesToUpdate"},
			"update-state-template":                    {"DataExtraDimensions", "Description", "Identifier", "MetadataExtraDimensions", "StateTemplatePropertiesToAdd", "StateTemplatePropertiesToRemove"},
			"update-vehicle":                           {"AttributeUpdateMode", "Attributes", "DecoderManifestArn", "ModelManifestArn", "StateTemplatesToAdd", "StateTemplatesToRemove", "StateTemplatesToUpdate", "VehicleName"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-vehicle-fleet":                  {"FleetId": "*string", "VehicleName": "*string"},
			"batch-create-vehicle":                     {"Vehicles": "[]types.CreateVehicleRequestItem"},
			"batch-update-vehicle":                     {"Vehicles": "[]types.UpdateVehicleRequestItem"},
			"create-campaign":                          {"CollectionScheme": "types.CollectionScheme", "Compression": "types.Compression", "DataDestinationConfigs": "[]types.DataDestinationConfig", "DataExtraDimensions": "[]string", "DataPartitions": "[]types.DataPartition", "Description": "*string", "DiagnosticsMode": "types.DiagnosticsMode", "ExpiryTime": "*time.Time", "Name": "*string", "PostTriggerCollectionDuration": "*int64", "Priority": "*int32", "SignalCatalogArn": "*string", "SignalsToCollect": "[]types.SignalInformation", "SignalsToFetch": "[]types.SignalFetchInformation", "SpoolingMode": "types.SpoolingMode", "StartTime": "*time.Time", "Tags": "[]types.Tag", "TargetArn": "*string"},
			"create-decoder-manifest":                  {"DefaultForUnmappedSignals": "types.DefaultForUnmappedSignalsType", "Description": "*string", "ModelManifestArn": "*string", "Name": "*string", "NetworkInterfaces": "[]types.NetworkInterface", "SignalDecoders": "[]types.SignalDecoder", "Tags": "[]types.Tag"},
			"create-fleet":                             {"Description": "*string", "FleetId": "*string", "SignalCatalogArn": "*string", "Tags": "[]types.Tag"},
			"create-model-manifest":                    {"Description": "*string", "Name": "*string", "Nodes": "[]string", "SignalCatalogArn": "*string", "Tags": "[]types.Tag"},
			"create-signal-catalog":                    {"Description": "*string", "Name": "*string", "Nodes": "[]types.Node", "Tags": "[]types.Tag"},
			"create-state-template":                    {"DataExtraDimensions": "[]string", "Description": "*string", "MetadataExtraDimensions": "[]string", "Name": "*string", "SignalCatalogArn": "*string", "StateTemplateProperties": "[]string", "Tags": "[]types.Tag"},
			"create-vehicle":                           {"AssociationBehavior": "types.VehicleAssociationBehavior", "Attributes": "map[string]string", "DecoderManifestArn": "*string", "ModelManifestArn": "*string", "StateTemplates": "[]types.StateTemplateAssociation", "Tags": "[]types.Tag", "VehicleName": "*string"},
			"delete-campaign":                          {"Name": "*string"},
			"delete-decoder-manifest":                  {"Name": "*string"},
			"delete-fleet":                             {"FleetId": "*string"},
			"delete-model-manifest":                    {"Name": "*string"},
			"delete-signal-catalog":                    {"Name": "*string"},
			"delete-state-template":                    {"Identifier": "*string"},
			"delete-vehicle":                           {"VehicleName": "*string"},
			"disassociate-vehicle-fleet":               {"FleetId": "*string", "VehicleName": "*string"},
			"get-campaign":                             {"Name": "*string"},
			"get-decoder-manifest":                     {"Name": "*string"},
			"get-encryption-configuration":             {},
			"get-fleet":                                {"FleetId": "*string"},
			"get-logging-options":                      {},
			"get-model-manifest":                       {"Name": "*string"},
			"get-register-account-status":              {},
			"get-signal-catalog":                       {"Name": "*string"},
			"get-state-template":                       {"Identifier": "*string"},
			"get-vehicle":                              {"VehicleName": "*string"},
			"get-vehicle-status":                       {"MaxResults": "*int32", "NextToken": "*string", "VehicleName": "*string"},
			"import-decoder-manifest":                  {"Name": "*string", "NetworkFileDefinitions": "[]types.NetworkFileDefinition"},
			"import-signal-catalog":                    {"Description": "*string", "Name": "*string", "Tags": "[]types.Tag", "Vss": "types.FormattedVss"},
			"list-campaigns":                           {"ListResponseScope": "types.ListResponseScope", "MaxResults": "*int32", "NextToken": "*string", "Status": "*string"},
			"list-decoder-manifest-network-interfaces": {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string"},
			"list-decoder-manifest-signals":            {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string"},
			"list-decoder-manifests":                   {"ListResponseScope": "types.ListResponseScope", "MaxResults": "*int32", "ModelManifestArn": "*string", "NextToken": "*string"},
			"list-fleets":                              {"ListResponseScope": "types.ListResponseScope", "MaxResults": "*int32", "NextToken": "*string"},
			"list-fleets-for-vehicle":                  {"MaxResults": "*int32", "NextToken": "*string", "VehicleName": "*string"},
			"list-model-manifest-nodes":                {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string"},
			"list-model-manifests":                     {"ListResponseScope": "types.ListResponseScope", "MaxResults": "*int32", "NextToken": "*string", "SignalCatalogArn": "*string"},
			"list-signal-catalog-nodes":                {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string", "SignalNodeType": "types.SignalNodeType"},
			"list-signal-catalogs":                     {"MaxResults": "*int32", "NextToken": "*string"},
			"list-state-templates":                     {"ListResponseScope": "types.ListResponseScope", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                   {"ResourceARN": "*string"},
			"list-vehicles":                            {"AttributeNames": "[]string", "AttributeValues": "[]string", "ListResponseScope": "types.ListResponseScope", "MaxResults": "*int32", "ModelManifestArn": "*string", "NextToken": "*string"},
			"list-vehicles-in-fleet":                   {"FleetId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"put-encryption-configuration":             {"EncryptionType": "types.EncryptionType", "KmsKeyId": "*string"},
			"put-logging-options":                      {"CloudWatchLogDelivery": "*types.CloudWatchLogDeliveryOptions"},
			"register-account":                         {"IamResources": "*types.IamResources", "TimestreamResources": "*types.TimestreamResources"},
			"tag-resource":                             {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                           {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-campaign":                          {"Action": "types.UpdateCampaignAction", "DataExtraDimensions": "[]string", "Description": "*string", "Name": "*string"},
			"update-decoder-manifest":                  {"DefaultForUnmappedSignals": "types.DefaultForUnmappedSignalsType", "Description": "*string", "Name": "*string", "NetworkInterfacesToAdd": "[]types.NetworkInterface", "NetworkInterfacesToRemove": "[]string", "NetworkInterfacesToUpdate": "[]types.NetworkInterface", "SignalDecodersToAdd": "[]types.SignalDecoder", "SignalDecodersToRemove": "[]string", "SignalDecodersToUpdate": "[]types.SignalDecoder", "Status": "types.ManifestStatus"},
			"update-fleet":                             {"Description": "*string", "FleetId": "*string"},
			"update-model-manifest":                    {"Description": "*string", "Name": "*string", "NodesToAdd": "[]string", "NodesToRemove": "[]string", "Status": "types.ManifestStatus"},
			"update-signal-catalog":                    {"Description": "*string", "Name": "*string", "NodesToAdd": "[]types.Node", "NodesToRemove": "[]string", "NodesToUpdate": "[]types.Node"},
			"update-state-template":                    {"DataExtraDimensions": "[]string", "Description": "*string", "Identifier": "*string", "MetadataExtraDimensions": "[]string", "StateTemplatePropertiesToAdd": "[]string", "StateTemplatePropertiesToRemove": "[]string"},
			"update-vehicle":                           {"AttributeUpdateMode": "types.UpdateMode", "Attributes": "map[string]string", "DecoderManifestArn": "*string", "ModelManifestArn": "*string", "StateTemplatesToAdd": "[]types.StateTemplateAssociation", "StateTemplatesToRemove": "[]string", "StateTemplatesToUpdate": "[]types.StateTemplateAssociation", "VehicleName": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-vehicle-fleet":                  {"FleetId", "VehicleName"},
			"batch-create-vehicle":                     {"Vehicles"},
			"batch-update-vehicle":                     {"Vehicles"},
			"create-campaign":                          {"CollectionScheme", "Name", "SignalCatalogArn", "TargetArn"},
			"create-decoder-manifest":                  {"ModelManifestArn", "Name"},
			"create-fleet":                             {"FleetId", "SignalCatalogArn"},
			"create-model-manifest":                    {"Name", "Nodes", "SignalCatalogArn"},
			"create-signal-catalog":                    {"Name"},
			"create-state-template":                    {"Name", "SignalCatalogArn", "StateTemplateProperties"},
			"create-vehicle":                           {"DecoderManifestArn", "ModelManifestArn", "VehicleName"},
			"delete-campaign":                          {"Name"},
			"delete-decoder-manifest":                  {"Name"},
			"delete-fleet":                             {"FleetId"},
			"delete-model-manifest":                    {"Name"},
			"delete-signal-catalog":                    {"Name"},
			"delete-state-template":                    {"Identifier"},
			"delete-vehicle":                           {"VehicleName"},
			"disassociate-vehicle-fleet":               {"FleetId", "VehicleName"},
			"get-campaign":                             {"Name"},
			"get-decoder-manifest":                     {"Name"},
			"get-encryption-configuration":             {},
			"get-fleet":                                {"FleetId"},
			"get-logging-options":                      {},
			"get-model-manifest":                       {"Name"},
			"get-register-account-status":              {},
			"get-signal-catalog":                       {"Name"},
			"get-state-template":                       {"Identifier"},
			"get-vehicle":                              {"VehicleName"},
			"get-vehicle-status":                       {"VehicleName"},
			"import-decoder-manifest":                  {"Name", "NetworkFileDefinitions"},
			"import-signal-catalog":                    {"Name"},
			"list-campaigns":                           {},
			"list-decoder-manifest-network-interfaces": {"Name"},
			"list-decoder-manifest-signals":            {"Name"},
			"list-decoder-manifests":                   {},
			"list-fleets":                              {},
			"list-fleets-for-vehicle":                  {"VehicleName"},
			"list-model-manifest-nodes":                {"Name"},
			"list-model-manifests":                     {},
			"list-signal-catalog-nodes":                {"Name"},
			"list-signal-catalogs":                     {},
			"list-state-templates":                     {},
			"list-tags-for-resource":                   {"ResourceARN"},
			"list-vehicles":                            {},
			"list-vehicles-in-fleet":                   {"FleetId"},
			"put-encryption-configuration":             {"EncryptionType"},
			"put-logging-options":                      {"CloudWatchLogDelivery"},
			"register-account":                         {},
			"tag-resource":                             {"ResourceARN", "Tags"},
			"untag-resource":                           {"ResourceARN", "TagKeys"},
			"update-campaign":                          {"Action", "Name"},
			"update-decoder-manifest":                  {"Name"},
			"update-fleet":                             {"FleetId"},
			"update-model-manifest":                    {"Name"},
			"update-signal-catalog":                    {"Name"},
			"update-state-template":                    {"Identifier"},
			"update-vehicle":                           {"VehicleName"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("iotfleetwise", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
