package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/fms/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-admin-account", "associate-third-party-firewall", "batch-associate-resource", "batch-disassociate-resource", "delete-apps-list", "delete-notification-channel", "delete-policy", "delete-protocols-list", "delete-resource-set", "disassociate-admin-account", "disassociate-third-party-firewall", "get-admin-account", "get-admin-scope", "get-apps-list", "get-compliance-detail", "get-notification-channel", "get-policy", "get-protection-status", "get-protocols-list", "get-resource-set", "get-third-party-firewall-association-status", "get-violation-details", "list-admin-accounts-for-organization", "list-admins-managing-account", "list-apps-lists", "list-compliance-status", "list-discovered-resources", "list-member-accounts", "list-policies", "list-protocols-lists", "list-resource-set-resources", "list-resource-sets", "list-tags-for-resource", "list-third-party-firewall-firewall-policies", "put-admin-account", "put-apps-list", "put-notification-channel", "put-policy", "put-protocols-list", "put-resource-set", "tag-resource", "untag-resource"},
		OperationSet: map[string]bool{"associate-admin-account": true, "associate-third-party-firewall": true, "batch-associate-resource": true, "batch-disassociate-resource": true, "delete-apps-list": true, "delete-notification-channel": true, "delete-policy": true, "delete-protocols-list": true, "delete-resource-set": true, "disassociate-admin-account": true, "disassociate-third-party-firewall": true, "get-admin-account": true, "get-admin-scope": true, "get-apps-list": true, "get-compliance-detail": true, "get-notification-channel": true, "get-policy": true, "get-protection-status": true, "get-protocols-list": true, "get-resource-set": true, "get-third-party-firewall-association-status": true, "get-violation-details": true, "list-admin-accounts-for-organization": true, "list-admins-managing-account": true, "list-apps-lists": true, "list-compliance-status": true, "list-discovered-resources": true, "list-member-accounts": true, "list-policies": true, "list-protocols-lists": true, "list-resource-set-resources": true, "list-resource-sets": true, "list-tags-for-resource": true, "list-third-party-firewall-firewall-policies": true, "put-admin-account": true, "put-apps-list": true, "put-notification-channel": true, "put-policy": true, "put-protocols-list": true, "put-resource-set": true, "tag-resource": true, "untag-resource": true},
		OperationInputs: map[string][]string{
			"associate-admin-account":                     {"AdminAccount"},
			"associate-third-party-firewall":              {"ThirdPartyFirewall"},
			"batch-associate-resource":                    {"Items", "ResourceSetIdentifier"},
			"batch-disassociate-resource":                 {"Items", "ResourceSetIdentifier"},
			"delete-apps-list":                            {"ListId"},
			"delete-notification-channel":                 {},
			"delete-policy":                               {"DeleteAllPolicyResources", "PolicyId"},
			"delete-protocols-list":                       {"ListId"},
			"delete-resource-set":                         {"Identifier"},
			"disassociate-admin-account":                  {},
			"disassociate-third-party-firewall":           {"ThirdPartyFirewall"},
			"get-admin-account":                           {},
			"get-admin-scope":                             {"AdminAccount"},
			"get-apps-list":                               {"DefaultList", "ListId"},
			"get-compliance-detail":                       {"MemberAccount", "PolicyId"},
			"get-notification-channel":                    {},
			"get-policy":                                  {"PolicyId"},
			"get-protection-status":                       {"EndTime", "MaxResults", "MemberAccountId", "NextToken", "PolicyId", "StartTime"},
			"get-protocols-list":                          {"DefaultList", "ListId"},
			"get-resource-set":                            {"Identifier"},
			"get-third-party-firewall-association-status": {"ThirdPartyFirewall"},
			"get-violation-details":                       {"MemberAccount", "PolicyId", "ResourceId", "ResourceType"},
			"list-admin-accounts-for-organization":        {"MaxResults", "NextToken"},
			"list-admins-managing-account":                {"MaxResults", "NextToken"},
			"list-apps-lists":                             {"DefaultLists", "MaxResults", "NextToken"},
			"list-compliance-status":                      {"MaxResults", "NextToken", "PolicyId"},
			"list-discovered-resources":                   {"MaxResults", "MemberAccountIds", "NextToken", "ResourceType"},
			"list-member-accounts":                        {"MaxResults", "NextToken"},
			"list-policies":                               {"MaxResults", "NextToken"},
			"list-protocols-lists":                        {"DefaultLists", "MaxResults", "NextToken"},
			"list-resource-set-resources":                 {"Identifier", "MaxResults", "NextToken"},
			"list-resource-sets":                          {"MaxResults", "NextToken"},
			"list-tags-for-resource":                      {"ResourceArn"},
			"list-third-party-firewall-firewall-policies": {"MaxResults", "NextToken", "ThirdPartyFirewall"},
			"put-admin-account":                           {"AdminAccount", "AdminScope"},
			"put-apps-list":                               {"AppsList", "TagList"},
			"put-notification-channel":                    {"SnsRoleName", "SnsTopicArn"},
			"put-policy":                                  {"Policy", "TagList"},
			"put-protocols-list":                          {"ProtocolsList", "TagList"},
			"put-resource-set":                            {"ResourceSet", "TagList"},
			"tag-resource":                                {"ResourceArn", "TagList"},
			"untag-resource":                              {"ResourceArn", "TagKeys"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-admin-account":                     {"AdminAccount": "*string"},
			"associate-third-party-firewall":              {"ThirdPartyFirewall": "types.ThirdPartyFirewall"},
			"batch-associate-resource":                    {"Items": "[]string", "ResourceSetIdentifier": "*string"},
			"batch-disassociate-resource":                 {"Items": "[]string", "ResourceSetIdentifier": "*string"},
			"delete-apps-list":                            {"ListId": "*string"},
			"delete-notification-channel":                 {},
			"delete-policy":                               {"DeleteAllPolicyResources": "bool", "PolicyId": "*string"},
			"delete-protocols-list":                       {"ListId": "*string"},
			"delete-resource-set":                         {"Identifier": "*string"},
			"disassociate-admin-account":                  {},
			"disassociate-third-party-firewall":           {"ThirdPartyFirewall": "types.ThirdPartyFirewall"},
			"get-admin-account":                           {},
			"get-admin-scope":                             {"AdminAccount": "*string"},
			"get-apps-list":                               {"DefaultList": "bool", "ListId": "*string"},
			"get-compliance-detail":                       {"MemberAccount": "*string", "PolicyId": "*string"},
			"get-notification-channel":                    {},
			"get-policy":                                  {"PolicyId": "*string"},
			"get-protection-status":                       {"EndTime": "*time.Time", "MaxResults": "*int32", "MemberAccountId": "*string", "NextToken": "*string", "PolicyId": "*string", "StartTime": "*time.Time"},
			"get-protocols-list":                          {"DefaultList": "bool", "ListId": "*string"},
			"get-resource-set":                            {"Identifier": "*string"},
			"get-third-party-firewall-association-status": {"ThirdPartyFirewall": "types.ThirdPartyFirewall"},
			"get-violation-details":                       {"MemberAccount": "*string", "PolicyId": "*string", "ResourceId": "*string", "ResourceType": "*string"},
			"list-admin-accounts-for-organization":        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-admins-managing-account":                {"MaxResults": "*int32", "NextToken": "*string"},
			"list-apps-lists":                             {"DefaultLists": "bool", "MaxResults": "*int32", "NextToken": "*string"},
			"list-compliance-status":                      {"MaxResults": "*int32", "NextToken": "*string", "PolicyId": "*string"},
			"list-discovered-resources":                   {"MaxResults": "*int32", "MemberAccountIds": "[]string", "NextToken": "*string", "ResourceType": "*string"},
			"list-member-accounts":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-policies":                               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-protocols-lists":                        {"DefaultLists": "bool", "MaxResults": "*int32", "NextToken": "*string"},
			"list-resource-set-resources":                 {"Identifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-resource-sets":                          {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                      {"ResourceArn": "*string"},
			"list-third-party-firewall-firewall-policies": {"MaxResults": "*int32", "NextToken": "*string", "ThirdPartyFirewall": "types.ThirdPartyFirewall"},
			"put-admin-account":                           {"AdminAccount": "*string", "AdminScope": "*types.AdminScope"},
			"put-apps-list":                               {"AppsList": "*types.AppsListData", "TagList": "[]types.Tag"},
			"put-notification-channel":                    {"SnsRoleName": "*string", "SnsTopicArn": "*string"},
			"put-policy":                                  {"Policy": "*types.Policy", "TagList": "[]types.Tag"},
			"put-protocols-list":                          {"ProtocolsList": "*types.ProtocolsListData", "TagList": "[]types.Tag"},
			"put-resource-set":                            {"ResourceSet": "*types.ResourceSet", "TagList": "[]types.Tag"},
			"tag-resource":                                {"ResourceArn": "*string", "TagList": "[]types.Tag"},
			"untag-resource":                              {"ResourceArn": "*string", "TagKeys": "[]string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-admin-account":                     {"AdminAccount"},
			"associate-third-party-firewall":              {"ThirdPartyFirewall"},
			"batch-associate-resource":                    {"Items", "ResourceSetIdentifier"},
			"batch-disassociate-resource":                 {"Items", "ResourceSetIdentifier"},
			"delete-apps-list":                            {"ListId"},
			"delete-notification-channel":                 {},
			"delete-policy":                               {"PolicyId"},
			"delete-protocols-list":                       {"ListId"},
			"delete-resource-set":                         {"Identifier"},
			"disassociate-admin-account":                  {},
			"disassociate-third-party-firewall":           {"ThirdPartyFirewall"},
			"get-admin-account":                           {},
			"get-admin-scope":                             {"AdminAccount"},
			"get-apps-list":                               {"ListId"},
			"get-compliance-detail":                       {"MemberAccount", "PolicyId"},
			"get-notification-channel":                    {},
			"get-policy":                                  {"PolicyId"},
			"get-protection-status":                       {"PolicyId"},
			"get-protocols-list":                          {"ListId"},
			"get-resource-set":                            {"Identifier"},
			"get-third-party-firewall-association-status": {"ThirdPartyFirewall"},
			"get-violation-details":                       {"MemberAccount", "PolicyId", "ResourceId", "ResourceType"},
			"list-admin-accounts-for-organization":        {},
			"list-admins-managing-account":                {},
			"list-apps-lists":                             {"MaxResults"},
			"list-compliance-status":                      {"PolicyId"},
			"list-discovered-resources":                   {"MemberAccountIds", "ResourceType"},
			"list-member-accounts":                        {},
			"list-policies":                               {},
			"list-protocols-lists":                        {"MaxResults"},
			"list-resource-set-resources":                 {"Identifier"},
			"list-resource-sets":                          {},
			"list-tags-for-resource":                      {"ResourceArn"},
			"list-third-party-firewall-firewall-policies": {"MaxResults", "ThirdPartyFirewall"},
			"put-admin-account":                           {"AdminAccount"},
			"put-apps-list":                               {"AppsList"},
			"put-notification-channel":                    {"SnsRoleName", "SnsTopicArn"},
			"put-policy":                                  {"Policy"},
			"put-protocols-list":                          {"ProtocolsList"},
			"put-resource-set":                            {"ResourceSet"},
			"tag-resource":                                {"ResourceArn", "TagList"},
			"untag-resource":                              {"ResourceArn", "TagKeys"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("fms", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
