package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/shield/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-drt-log-bucket", "associate-drt-role", "associate-health-check", "associate-proactive-engagement-details", "create-protection", "create-protection-group", "create-subscription", "delete-protection", "delete-protection-group", "delete-subscription", "describe-attack", "describe-attack-statistics", "describe-drt-access", "describe-emergency-contact-settings", "describe-protection", "describe-protection-group", "describe-subscription", "disable-application-layer-automatic-response", "disable-proactive-engagement", "disassociate-drt-log-bucket", "disassociate-drt-role", "disassociate-health-check", "enable-application-layer-automatic-response", "enable-proactive-engagement", "get-subscription-state", "list-attacks", "list-protection-groups", "list-protections", "list-resources-in-protection-group", "list-tags-for-resource", "tag-resource", "untag-resource", "update-application-layer-automatic-response", "update-emergency-contact-settings", "update-protection-group", "update-subscription"},
		OperationSet: map[string]bool{"associate-drt-log-bucket": true, "associate-drt-role": true, "associate-health-check": true, "associate-proactive-engagement-details": true, "create-protection": true, "create-protection-group": true, "create-subscription": true, "delete-protection": true, "delete-protection-group": true, "delete-subscription": true, "describe-attack": true, "describe-attack-statistics": true, "describe-drt-access": true, "describe-emergency-contact-settings": true, "describe-protection": true, "describe-protection-group": true, "describe-subscription": true, "disable-application-layer-automatic-response": true, "disable-proactive-engagement": true, "disassociate-drt-log-bucket": true, "disassociate-drt-role": true, "disassociate-health-check": true, "enable-application-layer-automatic-response": true, "enable-proactive-engagement": true, "get-subscription-state": true, "list-attacks": true, "list-protection-groups": true, "list-protections": true, "list-resources-in-protection-group": true, "list-tags-for-resource": true, "tag-resource": true, "untag-resource": true, "update-application-layer-automatic-response": true, "update-emergency-contact-settings": true, "update-protection-group": true, "update-subscription": true},
		OperationInputs: map[string][]string{
			"associate-drt-log-bucket":                     {"LogBucket"},
			"associate-drt-role":                           {"RoleArn"},
			"associate-health-check":                       {"HealthCheckArn", "ProtectionId"},
			"associate-proactive-engagement-details":       {"EmergencyContactList"},
			"create-protection":                            {"Name", "ResourceArn", "Tags"},
			"create-protection-group":                      {"Aggregation", "Members", "Pattern", "ProtectionGroupId", "ResourceType", "Tags"},
			"create-subscription":                          {},
			"delete-protection":                            {"ProtectionId"},
			"delete-protection-group":                      {"ProtectionGroupId"},
			"delete-subscription":                          {},
			"describe-attack":                              {"AttackId"},
			"describe-attack-statistics":                   {},
			"describe-drt-access":                          {},
			"describe-emergency-contact-settings":          {},
			"describe-protection":                          {"ProtectionId", "ResourceArn"},
			"describe-protection-group":                    {"ProtectionGroupId"},
			"describe-subscription":                        {},
			"disable-application-layer-automatic-response": {"ResourceArn"},
			"disable-proactive-engagement":                 {},
			"disassociate-drt-log-bucket":                  {"LogBucket"},
			"disassociate-drt-role":                        {},
			"disassociate-health-check":                    {"HealthCheckArn", "ProtectionId"},
			"enable-application-layer-automatic-response":  {"Action", "ResourceArn"},
			"enable-proactive-engagement":                  {},
			"get-subscription-state":                       {},
			"list-attacks":                                 {"EndTime", "MaxResults", "NextToken", "ResourceArns", "StartTime"},
			"list-protection-groups":                       {"InclusionFilters", "MaxResults", "NextToken"},
			"list-protections":                             {"InclusionFilters", "MaxResults", "NextToken"},
			"list-resources-in-protection-group":           {"MaxResults", "NextToken", "ProtectionGroupId"},
			"list-tags-for-resource":                       {"ResourceARN"},
			"tag-resource":                                 {"ResourceARN", "Tags"},
			"untag-resource":                               {"ResourceARN", "TagKeys"},
			"update-application-layer-automatic-response":  {"Action", "ResourceArn"},
			"update-emergency-contact-settings":            {"EmergencyContactList"},
			"update-protection-group":                      {"Aggregation", "Members", "Pattern", "ProtectionGroupId", "ResourceType"},
			"update-subscription":                          {"AutoRenew"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-drt-log-bucket":                     {"LogBucket": "*string"},
			"associate-drt-role":                           {"RoleArn": "*string"},
			"associate-health-check":                       {"HealthCheckArn": "*string", "ProtectionId": "*string"},
			"associate-proactive-engagement-details":       {"EmergencyContactList": "[]types.EmergencyContact"},
			"create-protection":                            {"Name": "*string", "ResourceArn": "*string", "Tags": "[]types.Tag"},
			"create-protection-group":                      {"Aggregation": "types.ProtectionGroupAggregation", "Members": "[]string", "Pattern": "types.ProtectionGroupPattern", "ProtectionGroupId": "*string", "ResourceType": "types.ProtectedResourceType", "Tags": "[]types.Tag"},
			"create-subscription":                          {},
			"delete-protection":                            {"ProtectionId": "*string"},
			"delete-protection-group":                      {"ProtectionGroupId": "*string"},
			"delete-subscription":                          {},
			"describe-attack":                              {"AttackId": "*string"},
			"describe-attack-statistics":                   {},
			"describe-drt-access":                          {},
			"describe-emergency-contact-settings":          {},
			"describe-protection":                          {"ProtectionId": "*string", "ResourceArn": "*string"},
			"describe-protection-group":                    {"ProtectionGroupId": "*string"},
			"describe-subscription":                        {},
			"disable-application-layer-automatic-response": {"ResourceArn": "*string"},
			"disable-proactive-engagement":                 {},
			"disassociate-drt-log-bucket":                  {"LogBucket": "*string"},
			"disassociate-drt-role":                        {},
			"disassociate-health-check":                    {"HealthCheckArn": "*string", "ProtectionId": "*string"},
			"enable-application-layer-automatic-response":  {"Action": "*types.ResponseAction", "ResourceArn": "*string"},
			"enable-proactive-engagement":                  {},
			"get-subscription-state":                       {},
			"list-attacks":                                 {"EndTime": "*types.TimeRange", "MaxResults": "*int32", "NextToken": "*string", "ResourceArns": "[]string", "StartTime": "*types.TimeRange"},
			"list-protection-groups":                       {"InclusionFilters": "*types.InclusionProtectionGroupFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"list-protections":                             {"InclusionFilters": "*types.InclusionProtectionFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"list-resources-in-protection-group":           {"MaxResults": "*int32", "NextToken": "*string", "ProtectionGroupId": "*string"},
			"list-tags-for-resource":                       {"ResourceARN": "*string"},
			"tag-resource":                                 {"ResourceARN": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                               {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-application-layer-automatic-response":  {"Action": "*types.ResponseAction", "ResourceArn": "*string"},
			"update-emergency-contact-settings":            {"EmergencyContactList": "[]types.EmergencyContact"},
			"update-protection-group":                      {"Aggregation": "types.ProtectionGroupAggregation", "Members": "[]string", "Pattern": "types.ProtectionGroupPattern", "ProtectionGroupId": "*string", "ResourceType": "types.ProtectedResourceType"},
			"update-subscription":                          {"AutoRenew": "types.AutoRenew"},
		},
		OperationInputRequired: map[string][]string{
			"associate-drt-log-bucket":                     {"LogBucket"},
			"associate-drt-role":                           {"RoleArn"},
			"associate-health-check":                       {"HealthCheckArn", "ProtectionId"},
			"associate-proactive-engagement-details":       {"EmergencyContactList"},
			"create-protection":                            {"Name", "ResourceArn"},
			"create-protection-group":                      {"Aggregation", "Pattern", "ProtectionGroupId"},
			"create-subscription":                          {},
			"delete-protection":                            {"ProtectionId"},
			"delete-protection-group":                      {"ProtectionGroupId"},
			"delete-subscription":                          {},
			"describe-attack":                              {"AttackId"},
			"describe-attack-statistics":                   {},
			"describe-drt-access":                          {},
			"describe-emergency-contact-settings":          {},
			"describe-protection":                          {},
			"describe-protection-group":                    {"ProtectionGroupId"},
			"describe-subscription":                        {},
			"disable-application-layer-automatic-response": {"ResourceArn"},
			"disable-proactive-engagement":                 {},
			"disassociate-drt-log-bucket":                  {"LogBucket"},
			"disassociate-drt-role":                        {},
			"disassociate-health-check":                    {"HealthCheckArn", "ProtectionId"},
			"enable-application-layer-automatic-response":  {"Action", "ResourceArn"},
			"enable-proactive-engagement":                  {},
			"get-subscription-state":                       {},
			"list-attacks":                                 {},
			"list-protection-groups":                       {},
			"list-protections":                             {},
			"list-resources-in-protection-group":           {"ProtectionGroupId"},
			"list-tags-for-resource":                       {"ResourceARN"},
			"tag-resource":                                 {"ResourceARN", "Tags"},
			"untag-resource":                               {"ResourceARN", "TagKeys"},
			"update-application-layer-automatic-response":  {"Action", "ResourceArn"},
			"update-emergency-contact-settings":            {},
			"update-protection-group":                      {"Aggregation", "Pattern", "ProtectionGroupId"},
			"update-subscription":                          {},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("shield", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
