package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/elasticloadbalancingv2/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-listener-certificates", "add-tags", "add-trust-store-revocations", "create-listener", "create-load-balancer", "create-rule", "create-target-group", "create-trust-store", "delete-listener", "delete-load-balancer", "delete-rule", "delete-shared-trust-store-association", "delete-target-group", "delete-trust-store", "deregister-targets", "describe-account-limits", "describe-capacity-reservation", "describe-listener-attributes", "describe-listener-certificates", "describe-listeners", "describe-load-balancer-attributes", "describe-load-balancers", "describe-rules", "describe-ssl-policies", "describe-tags", "describe-target-group-attributes", "describe-target-groups", "describe-target-health", "describe-trust-store-associations", "describe-trust-store-revocations", "describe-trust-stores", "get-resource-policy", "get-trust-store-ca-certificates-bundle", "get-trust-store-revocation-content", "modify-capacity-reservation", "modify-ip-pools", "modify-listener", "modify-listener-attributes", "modify-load-balancer-attributes", "modify-rule", "modify-target-group", "modify-target-group-attributes", "modify-trust-store", "register-targets", "remove-listener-certificates", "remove-tags", "remove-trust-store-revocations", "set-ip-address-type", "set-rule-priorities", "set-security-groups", "set-subnets"},
		OperationSet: map[string]bool{"add-listener-certificates": true, "add-tags": true, "add-trust-store-revocations": true, "create-listener": true, "create-load-balancer": true, "create-rule": true, "create-target-group": true, "create-trust-store": true, "delete-listener": true, "delete-load-balancer": true, "delete-rule": true, "delete-shared-trust-store-association": true, "delete-target-group": true, "delete-trust-store": true, "deregister-targets": true, "describe-account-limits": true, "describe-capacity-reservation": true, "describe-listener-attributes": true, "describe-listener-certificates": true, "describe-listeners": true, "describe-load-balancer-attributes": true, "describe-load-balancers": true, "describe-rules": true, "describe-ssl-policies": true, "describe-tags": true, "describe-target-group-attributes": true, "describe-target-groups": true, "describe-target-health": true, "describe-trust-store-associations": true, "describe-trust-store-revocations": true, "describe-trust-stores": true, "get-resource-policy": true, "get-trust-store-ca-certificates-bundle": true, "get-trust-store-revocation-content": true, "modify-capacity-reservation": true, "modify-ip-pools": true, "modify-listener": true, "modify-listener-attributes": true, "modify-load-balancer-attributes": true, "modify-rule": true, "modify-target-group": true, "modify-target-group-attributes": true, "modify-trust-store": true, "register-targets": true, "remove-listener-certificates": true, "remove-tags": true, "remove-trust-store-revocations": true, "set-ip-address-type": true, "set-rule-priorities": true, "set-security-groups": true, "set-subnets": true},
		OperationInputs: map[string][]string{
			"add-listener-certificates":              {"Certificates", "ListenerArn"},
			"add-tags":                               {"ResourceArns", "Tags"},
			"add-trust-store-revocations":            {"RevocationContents", "TrustStoreArn"},
			"create-listener":                        {"AlpnPolicy", "Certificates", "DefaultActions", "LoadBalancerArn", "MutualAuthentication", "Port", "Protocol", "SslPolicy", "Tags"},
			"create-load-balancer":                   {"CustomerOwnedIpv4Pool", "EnablePrefixForIpv6SourceNat", "IpAddressType", "IpamPools", "Name", "Scheme", "SecurityGroups", "SubnetMappings", "Subnets", "Tags", "Type"},
			"create-rule":                            {"Actions", "Conditions", "ListenerArn", "Priority", "Tags", "Transforms"},
			"create-target-group":                    {"HealthCheckEnabled", "HealthCheckIntervalSeconds", "HealthCheckPath", "HealthCheckPort", "HealthCheckProtocol", "HealthCheckTimeoutSeconds", "HealthyThresholdCount", "IpAddressType", "Matcher", "Name", "Port", "Protocol", "ProtocolVersion", "Tags", "TargetControlPort", "TargetType", "UnhealthyThresholdCount", "VpcId"},
			"create-trust-store":                     {"CaCertificatesBundleS3Bucket", "CaCertificatesBundleS3Key", "CaCertificatesBundleS3ObjectVersion", "Name", "Tags"},
			"delete-listener":                        {"ListenerArn"},
			"delete-load-balancer":                   {"LoadBalancerArn"},
			"delete-rule":                            {"RuleArn"},
			"delete-shared-trust-store-association":  {"ResourceArn", "TrustStoreArn"},
			"delete-target-group":                    {"TargetGroupArn"},
			"delete-trust-store":                     {"TrustStoreArn"},
			"deregister-targets":                     {"TargetGroupArn", "Targets"},
			"describe-account-limits":                {"Marker", "PageSize"},
			"describe-capacity-reservation":          {"LoadBalancerArn"},
			"describe-listener-attributes":           {"ListenerArn"},
			"describe-listener-certificates":         {"ListenerArn", "Marker", "PageSize"},
			"describe-listeners":                     {"ListenerArns", "LoadBalancerArn", "Marker", "PageSize"},
			"describe-load-balancer-attributes":      {"LoadBalancerArn"},
			"describe-load-balancers":                {"LoadBalancerArns", "Marker", "Names", "PageSize"},
			"describe-rules":                         {"ListenerArn", "Marker", "PageSize", "RuleArns"},
			"describe-ssl-policies":                  {"LoadBalancerType", "Marker", "Names", "PageSize"},
			"describe-tags":                          {"ResourceArns"},
			"describe-target-group-attributes":       {"TargetGroupArn"},
			"describe-target-groups":                 {"LoadBalancerArn", "Marker", "Names", "PageSize", "TargetGroupArns"},
			"describe-target-health":                 {"Include", "TargetGroupArn", "Targets"},
			"describe-trust-store-associations":      {"Marker", "PageSize", "TrustStoreArn"},
			"describe-trust-store-revocations":       {"Marker", "PageSize", "RevocationIds", "TrustStoreArn"},
			"describe-trust-stores":                  {"Marker", "Names", "PageSize", "TrustStoreArns"},
			"get-resource-policy":                    {"ResourceArn"},
			"get-trust-store-ca-certificates-bundle": {"TrustStoreArn"},
			"get-trust-store-revocation-content":     {"RevocationId", "TrustStoreArn"},
			"modify-capacity-reservation":            {"LoadBalancerArn", "MinimumLoadBalancerCapacity", "ResetCapacityReservation"},
			"modify-ip-pools":                        {"IpamPools", "LoadBalancerArn", "RemoveIpamPools"},
			"modify-listener":                        {"AlpnPolicy", "Certificates", "DefaultActions", "ListenerArn", "MutualAuthentication", "Port", "Protocol", "SslPolicy"},
			"modify-listener-attributes":             {"Attributes", "ListenerArn"},
			"modify-load-balancer-attributes":        {"Attributes", "LoadBalancerArn"},
			"modify-rule":                            {"Actions", "Conditions", "ResetTransforms", "RuleArn", "Transforms"},
			"modify-target-group":                    {"HealthCheckEnabled", "HealthCheckIntervalSeconds", "HealthCheckPath", "HealthCheckPort", "HealthCheckProtocol", "HealthCheckTimeoutSeconds", "HealthyThresholdCount", "Matcher", "TargetGroupArn", "UnhealthyThresholdCount"},
			"modify-target-group-attributes":         {"Attributes", "TargetGroupArn"},
			"modify-trust-store":                     {"CaCertificatesBundleS3Bucket", "CaCertificatesBundleS3Key", "CaCertificatesBundleS3ObjectVersion", "TrustStoreArn"},
			"register-targets":                       {"TargetGroupArn", "Targets"},
			"remove-listener-certificates":           {"Certificates", "ListenerArn"},
			"remove-tags":                            {"ResourceArns", "TagKeys"},
			"remove-trust-store-revocations":         {"RevocationIds", "TrustStoreArn"},
			"set-ip-address-type":                    {"IpAddressType", "LoadBalancerArn"},
			"set-rule-priorities":                    {"RulePriorities"},
			"set-security-groups":                    {"EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic", "LoadBalancerArn", "SecurityGroups"},
			"set-subnets":                            {"EnablePrefixForIpv6SourceNat", "IpAddressType", "LoadBalancerArn", "SubnetMappings", "Subnets"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-listener-certificates":              {"Certificates": "[]types.Certificate", "ListenerArn": "*string"},
			"add-tags":                               {"ResourceArns": "[]string", "Tags": "[]types.Tag"},
			"add-trust-store-revocations":            {"RevocationContents": "[]types.RevocationContent", "TrustStoreArn": "*string"},
			"create-listener":                        {"AlpnPolicy": "[]string", "Certificates": "[]types.Certificate", "DefaultActions": "[]types.Action", "LoadBalancerArn": "*string", "MutualAuthentication": "*types.MutualAuthenticationAttributes", "Port": "*int32", "Protocol": "types.ProtocolEnum", "SslPolicy": "*string", "Tags": "[]types.Tag"},
			"create-load-balancer":                   {"CustomerOwnedIpv4Pool": "*string", "EnablePrefixForIpv6SourceNat": "types.EnablePrefixForIpv6SourceNatEnum", "IpAddressType": "types.IpAddressType", "IpamPools": "*types.IpamPools", "Name": "*string", "Scheme": "types.LoadBalancerSchemeEnum", "SecurityGroups": "[]string", "SubnetMappings": "[]types.SubnetMapping", "Subnets": "[]string", "Tags": "[]types.Tag", "Type": "types.LoadBalancerTypeEnum"},
			"create-rule":                            {"Actions": "[]types.Action", "Conditions": "[]types.RuleCondition", "ListenerArn": "*string", "Priority": "*int32", "Tags": "[]types.Tag", "Transforms": "[]types.RuleTransform"},
			"create-target-group":                    {"HealthCheckEnabled": "*bool", "HealthCheckIntervalSeconds": "*int32", "HealthCheckPath": "*string", "HealthCheckPort": "*string", "HealthCheckProtocol": "types.ProtocolEnum", "HealthCheckTimeoutSeconds": "*int32", "HealthyThresholdCount": "*int32", "IpAddressType": "types.TargetGroupIpAddressTypeEnum", "Matcher": "*types.Matcher", "Name": "*string", "Port": "*int32", "Protocol": "types.ProtocolEnum", "ProtocolVersion": "*string", "Tags": "[]types.Tag", "TargetControlPort": "*int32", "TargetType": "types.TargetTypeEnum", "UnhealthyThresholdCount": "*int32", "VpcId": "*string"},
			"create-trust-store":                     {"CaCertificatesBundleS3Bucket": "*string", "CaCertificatesBundleS3Key": "*string", "CaCertificatesBundleS3ObjectVersion": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"delete-listener":                        {"ListenerArn": "*string"},
			"delete-load-balancer":                   {"LoadBalancerArn": "*string"},
			"delete-rule":                            {"RuleArn": "*string"},
			"delete-shared-trust-store-association":  {"ResourceArn": "*string", "TrustStoreArn": "*string"},
			"delete-target-group":                    {"TargetGroupArn": "*string"},
			"delete-trust-store":                     {"TrustStoreArn": "*string"},
			"deregister-targets":                     {"TargetGroupArn": "*string", "Targets": "[]types.TargetDescription"},
			"describe-account-limits":                {"Marker": "*string", "PageSize": "*int32"},
			"describe-capacity-reservation":          {"LoadBalancerArn": "*string"},
			"describe-listener-attributes":           {"ListenerArn": "*string"},
			"describe-listener-certificates":         {"ListenerArn": "*string", "Marker": "*string", "PageSize": "*int32"},
			"describe-listeners":                     {"ListenerArns": "[]string", "LoadBalancerArn": "*string", "Marker": "*string", "PageSize": "*int32"},
			"describe-load-balancer-attributes":      {"LoadBalancerArn": "*string"},
			"describe-load-balancers":                {"LoadBalancerArns": "[]string", "Marker": "*string", "Names": "[]string", "PageSize": "*int32"},
			"describe-rules":                         {"ListenerArn": "*string", "Marker": "*string", "PageSize": "*int32", "RuleArns": "[]string"},
			"describe-ssl-policies":                  {"LoadBalancerType": "types.LoadBalancerTypeEnum", "Marker": "*string", "Names": "[]string", "PageSize": "*int32"},
			"describe-tags":                          {"ResourceArns": "[]string"},
			"describe-target-group-attributes":       {"TargetGroupArn": "*string"},
			"describe-target-groups":                 {"LoadBalancerArn": "*string", "Marker": "*string", "Names": "[]string", "PageSize": "*int32", "TargetGroupArns": "[]string"},
			"describe-target-health":                 {"Include": "[]types.DescribeTargetHealthInputIncludeEnum", "TargetGroupArn": "*string", "Targets": "[]types.TargetDescription"},
			"describe-trust-store-associations":      {"Marker": "*string", "PageSize": "*int32", "TrustStoreArn": "*string"},
			"describe-trust-store-revocations":       {"Marker": "*string", "PageSize": "*int32", "RevocationIds": "[]int64", "TrustStoreArn": "*string"},
			"describe-trust-stores":                  {"Marker": "*string", "Names": "[]string", "PageSize": "*int32", "TrustStoreArns": "[]string"},
			"get-resource-policy":                    {"ResourceArn": "*string"},
			"get-trust-store-ca-certificates-bundle": {"TrustStoreArn": "*string"},
			"get-trust-store-revocation-content":     {"RevocationId": "*int64", "TrustStoreArn": "*string"},
			"modify-capacity-reservation":            {"LoadBalancerArn": "*string", "MinimumLoadBalancerCapacity": "*types.MinimumLoadBalancerCapacity", "ResetCapacityReservation": "*bool"},
			"modify-ip-pools":                        {"IpamPools": "*types.IpamPools", "LoadBalancerArn": "*string", "RemoveIpamPools": "[]types.RemoveIpamPoolEnum"},
			"modify-listener":                        {"AlpnPolicy": "[]string", "Certificates": "[]types.Certificate", "DefaultActions": "[]types.Action", "ListenerArn": "*string", "MutualAuthentication": "*types.MutualAuthenticationAttributes", "Port": "*int32", "Protocol": "types.ProtocolEnum", "SslPolicy": "*string"},
			"modify-listener-attributes":             {"Attributes": "[]types.ListenerAttribute", "ListenerArn": "*string"},
			"modify-load-balancer-attributes":        {"Attributes": "[]types.LoadBalancerAttribute", "LoadBalancerArn": "*string"},
			"modify-rule":                            {"Actions": "[]types.Action", "Conditions": "[]types.RuleCondition", "ResetTransforms": "*bool", "RuleArn": "*string", "Transforms": "[]types.RuleTransform"},
			"modify-target-group":                    {"HealthCheckEnabled": "*bool", "HealthCheckIntervalSeconds": "*int32", "HealthCheckPath": "*string", "HealthCheckPort": "*string", "HealthCheckProtocol": "types.ProtocolEnum", "HealthCheckTimeoutSeconds": "*int32", "HealthyThresholdCount": "*int32", "Matcher": "*types.Matcher", "TargetGroupArn": "*string", "UnhealthyThresholdCount": "*int32"},
			"modify-target-group-attributes":         {"Attributes": "[]types.TargetGroupAttribute", "TargetGroupArn": "*string"},
			"modify-trust-store":                     {"CaCertificatesBundleS3Bucket": "*string", "CaCertificatesBundleS3Key": "*string", "CaCertificatesBundleS3ObjectVersion": "*string", "TrustStoreArn": "*string"},
			"register-targets":                       {"TargetGroupArn": "*string", "Targets": "[]types.TargetDescription"},
			"remove-listener-certificates":           {"Certificates": "[]types.Certificate", "ListenerArn": "*string"},
			"remove-tags":                            {"ResourceArns": "[]string", "TagKeys": "[]string"},
			"remove-trust-store-revocations":         {"RevocationIds": "[]int64", "TrustStoreArn": "*string"},
			"set-ip-address-type":                    {"IpAddressType": "types.IpAddressType", "LoadBalancerArn": "*string"},
			"set-rule-priorities":                    {"RulePriorities": "[]types.RulePriorityPair"},
			"set-security-groups":                    {"EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic": "types.EnforceSecurityGroupInboundRulesOnPrivateLinkTrafficEnum", "LoadBalancerArn": "*string", "SecurityGroups": "[]string"},
			"set-subnets":                            {"EnablePrefixForIpv6SourceNat": "types.EnablePrefixForIpv6SourceNatEnum", "IpAddressType": "types.IpAddressType", "LoadBalancerArn": "*string", "SubnetMappings": "[]types.SubnetMapping", "Subnets": "[]string"},
		},
		OperationInputRequired: map[string][]string{
			"add-listener-certificates":              {"Certificates", "ListenerArn"},
			"add-tags":                               {"ResourceArns", "Tags"},
			"add-trust-store-revocations":            {"TrustStoreArn"},
			"create-listener":                        {"DefaultActions", "LoadBalancerArn"},
			"create-load-balancer":                   {"Name"},
			"create-rule":                            {"Actions", "Conditions", "ListenerArn", "Priority"},
			"create-target-group":                    {"Name"},
			"create-trust-store":                     {"CaCertificatesBundleS3Bucket", "CaCertificatesBundleS3Key", "Name"},
			"delete-listener":                        {"ListenerArn"},
			"delete-load-balancer":                   {"LoadBalancerArn"},
			"delete-rule":                            {"RuleArn"},
			"delete-shared-trust-store-association":  {"ResourceArn", "TrustStoreArn"},
			"delete-target-group":                    {"TargetGroupArn"},
			"delete-trust-store":                     {"TrustStoreArn"},
			"deregister-targets":                     {"TargetGroupArn", "Targets"},
			"describe-account-limits":                {},
			"describe-capacity-reservation":          {"LoadBalancerArn"},
			"describe-listener-attributes":           {"ListenerArn"},
			"describe-listener-certificates":         {"ListenerArn"},
			"describe-listeners":                     {},
			"describe-load-balancer-attributes":      {"LoadBalancerArn"},
			"describe-load-balancers":                {},
			"describe-rules":                         {},
			"describe-ssl-policies":                  {},
			"describe-tags":                          {"ResourceArns"},
			"describe-target-group-attributes":       {"TargetGroupArn"},
			"describe-target-groups":                 {},
			"describe-target-health":                 {"TargetGroupArn"},
			"describe-trust-store-associations":      {"TrustStoreArn"},
			"describe-trust-store-revocations":       {"TrustStoreArn"},
			"describe-trust-stores":                  {},
			"get-resource-policy":                    {"ResourceArn"},
			"get-trust-store-ca-certificates-bundle": {"TrustStoreArn"},
			"get-trust-store-revocation-content":     {"RevocationId", "TrustStoreArn"},
			"modify-capacity-reservation":            {"LoadBalancerArn"},
			"modify-ip-pools":                        {"LoadBalancerArn"},
			"modify-listener":                        {"ListenerArn"},
			"modify-listener-attributes":             {"Attributes", "ListenerArn"},
			"modify-load-balancer-attributes":        {"Attributes", "LoadBalancerArn"},
			"modify-rule":                            {"RuleArn"},
			"modify-target-group":                    {"TargetGroupArn"},
			"modify-target-group-attributes":         {"Attributes", "TargetGroupArn"},
			"modify-trust-store":                     {"CaCertificatesBundleS3Bucket", "CaCertificatesBundleS3Key", "TrustStoreArn"},
			"register-targets":                       {"TargetGroupArn", "Targets"},
			"remove-listener-certificates":           {"Certificates", "ListenerArn"},
			"remove-tags":                            {"ResourceArns", "TagKeys"},
			"remove-trust-store-revocations":         {"RevocationIds", "TrustStoreArn"},
			"set-ip-address-type":                    {"IpAddressType", "LoadBalancerArn"},
			"set-rule-priorities":                    {"RulePriorities"},
			"set-security-groups":                    {"LoadBalancerArn", "SecurityGroups"},
			"set-subnets":                            {"LoadBalancerArn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("elasticloadbalancingv2", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
