package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/transfer/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-access", "create-agreement", "create-connector", "create-profile", "create-server", "create-user", "create-web-app", "create-workflow", "delete-access", "delete-agreement", "delete-certificate", "delete-connector", "delete-host-key", "delete-profile", "delete-server", "delete-ssh-public-key", "delete-user", "delete-web-app", "delete-web-app-customization", "delete-workflow", "describe-access", "describe-agreement", "describe-certificate", "describe-connector", "describe-execution", "describe-host-key", "describe-profile", "describe-security-policy", "describe-server", "describe-user", "describe-web-app", "describe-web-app-customization", "describe-workflow", "import-certificate", "import-host-key", "import-ssh-public-key", "list-accesses", "list-agreements", "list-certificates", "list-connectors", "list-executions", "list-file-transfer-results", "list-host-keys", "list-profiles", "list-security-policies", "list-servers", "list-tags-for-resource", "list-users", "list-web-apps", "list-workflows", "send-workflow-step-state", "start-directory-listing", "start-file-transfer", "start-remote-delete", "start-remote-move", "start-server", "stop-server", "tag-resource", "test-connection", "test-identity-provider", "untag-resource", "update-access", "update-agreement", "update-certificate", "update-connector", "update-host-key", "update-profile", "update-server", "update-user", "update-web-app", "update-web-app-customization"},
		OperationSet: map[string]bool{"create-access": true, "create-agreement": true, "create-connector": true, "create-profile": true, "create-server": true, "create-user": true, "create-web-app": true, "create-workflow": true, "delete-access": true, "delete-agreement": true, "delete-certificate": true, "delete-connector": true, "delete-host-key": true, "delete-profile": true, "delete-server": true, "delete-ssh-public-key": true, "delete-user": true, "delete-web-app": true, "delete-web-app-customization": true, "delete-workflow": true, "describe-access": true, "describe-agreement": true, "describe-certificate": true, "describe-connector": true, "describe-execution": true, "describe-host-key": true, "describe-profile": true, "describe-security-policy": true, "describe-server": true, "describe-user": true, "describe-web-app": true, "describe-web-app-customization": true, "describe-workflow": true, "import-certificate": true, "import-host-key": true, "import-ssh-public-key": true, "list-accesses": true, "list-agreements": true, "list-certificates": true, "list-connectors": true, "list-executions": true, "list-file-transfer-results": true, "list-host-keys": true, "list-profiles": true, "list-security-policies": true, "list-servers": true, "list-tags-for-resource": true, "list-users": true, "list-web-apps": true, "list-workflows": true, "send-workflow-step-state": true, "start-directory-listing": true, "start-file-transfer": true, "start-remote-delete": true, "start-remote-move": true, "start-server": true, "stop-server": true, "tag-resource": true, "test-connection": true, "test-identity-provider": true, "untag-resource": true, "update-access": true, "update-agreement": true, "update-certificate": true, "update-connector": true, "update-host-key": true, "update-profile": true, "update-server": true, "update-user": true, "update-web-app": true, "update-web-app-customization": true},
		OperationInputs: map[string][]string{
			"create-access":                  {"ExternalId", "HomeDirectory", "HomeDirectoryMappings", "HomeDirectoryType", "Policy", "PosixProfile", "Role", "ServerId"},
			"create-agreement":               {"AccessRole", "BaseDirectory", "CustomDirectories", "Description", "EnforceMessageSigning", "LocalProfileId", "PartnerProfileId", "PreserveFilename", "ServerId", "Status", "Tags"},
			"create-connector":               {"AccessRole", "As2Config", "EgressConfig", "LoggingRole", "SecurityPolicyName", "SftpConfig", "Tags", "Url"},
			"create-profile":                 {"As2Id", "CertificateIds", "ProfileType", "Tags"},
			"create-server":                  {"Certificate", "Domain", "EndpointDetails", "EndpointType", "HostKey", "IdentityProviderDetails", "IdentityProviderType", "IpAddressType", "LoggingRole", "PostAuthenticationLoginBanner", "PreAuthenticationLoginBanner", "ProtocolDetails", "Protocols", "S3StorageOptions", "SecurityPolicyName", "StructuredLogDestinations", "Tags", "WorkflowDetails"},
			"create-user":                    {"HomeDirectory", "HomeDirectoryMappings", "HomeDirectoryType", "Policy", "PosixProfile", "Role", "ServerId", "SshPublicKeyBody", "Tags", "UserName"},
			"create-web-app":                 {"AccessEndpoint", "EndpointDetails", "IdentityProviderDetails", "Tags", "WebAppEndpointPolicy", "WebAppUnits"},
			"create-workflow":                {"Description", "OnExceptionSteps", "Steps", "Tags"},
			"delete-access":                  {"ExternalId", "ServerId"},
			"delete-agreement":               {"AgreementId", "ServerId"},
			"delete-certificate":             {"CertificateId"},
			"delete-connector":               {"ConnectorId"},
			"delete-host-key":                {"HostKeyId", "ServerId"},
			"delete-profile":                 {"ProfileId"},
			"delete-server":                  {"ServerId"},
			"delete-ssh-public-key":          {"ServerId", "SshPublicKeyId", "UserName"},
			"delete-user":                    {"ServerId", "UserName"},
			"delete-web-app":                 {"WebAppId"},
			"delete-web-app-customization":   {"WebAppId"},
			"delete-workflow":                {"WorkflowId"},
			"describe-access":                {"ExternalId", "ServerId"},
			"describe-agreement":             {"AgreementId", "ServerId"},
			"describe-certificate":           {"CertificateId"},
			"describe-connector":             {"ConnectorId"},
			"describe-execution":             {"ExecutionId", "WorkflowId"},
			"describe-host-key":              {"HostKeyId", "ServerId"},
			"describe-profile":               {"ProfileId"},
			"describe-security-policy":       {"SecurityPolicyName"},
			"describe-server":                {"ServerId"},
			"describe-user":                  {"ServerId", "UserName"},
			"describe-web-app":               {"WebAppId"},
			"describe-web-app-customization": {"WebAppId"},
			"describe-workflow":              {"WorkflowId"},
			"import-certificate":             {"ActiveDate", "Certificate", "CertificateChain", "Description", "InactiveDate", "PrivateKey", "Tags", "Usage"},
			"import-host-key":                {"Description", "HostKeyBody", "ServerId", "Tags"},
			"import-ssh-public-key":          {"ServerId", "SshPublicKeyBody", "UserName"},
			"list-accesses":                  {"MaxResults", "NextToken", "ServerId"},
			"list-agreements":                {"MaxResults", "NextToken", "ServerId"},
			"list-certificates":              {"MaxResults", "NextToken"},
			"list-connectors":                {"MaxResults", "NextToken"},
			"list-executions":                {"MaxResults", "NextToken", "WorkflowId"},
			"list-file-transfer-results":     {"ConnectorId", "MaxResults", "NextToken", "TransferId"},
			"list-host-keys":                 {"MaxResults", "NextToken", "ServerId"},
			"list-profiles":                  {"MaxResults", "NextToken", "ProfileType"},
			"list-security-policies":         {"MaxResults", "NextToken"},
			"list-servers":                   {"MaxResults", "NextToken"},
			"list-tags-for-resource":         {"Arn", "MaxResults", "NextToken"},
			"list-users":                     {"MaxResults", "NextToken", "ServerId"},
			"list-web-apps":                  {"MaxResults", "NextToken"},
			"list-workflows":                 {"MaxResults", "NextToken"},
			"send-workflow-step-state":       {"ExecutionId", "Status", "Token", "WorkflowId"},
			"start-directory-listing":        {"ConnectorId", "MaxItems", "OutputDirectoryPath", "RemoteDirectoryPath"},
			"start-file-transfer":            {"ConnectorId", "CustomHttpHeaders", "LocalDirectoryPath", "RemoteDirectoryPath", "RetrieveFilePaths", "SendFilePaths"},
			"start-remote-delete":            {"ConnectorId", "DeletePath"},
			"start-remote-move":              {"ConnectorId", "SourcePath", "TargetPath"},
			"start-server":                   {"ServerId"},
			"stop-server":                    {"ServerId"},
			"tag-resource":                   {"Arn", "Tags"},
			"test-connection":                {"ConnectorId"},
			"test-identity-provider":         {"ServerId", "ServerProtocol", "SourceIp", "UserName", "UserPassword"},
			"untag-resource":                 {"Arn", "TagKeys"},
			"update-access":                  {"ExternalId", "HomeDirectory", "HomeDirectoryMappings", "HomeDirectoryType", "Policy", "PosixProfile", "Role", "ServerId"},
			"update-agreement":               {"AccessRole", "AgreementId", "BaseDirectory", "CustomDirectories", "Description", "EnforceMessageSigning", "LocalProfileId", "PartnerProfileId", "PreserveFilename", "ServerId", "Status"},
			"update-certificate":             {"ActiveDate", "CertificateId", "Description", "InactiveDate"},
			"update-connector":               {"AccessRole", "As2Config", "ConnectorId", "EgressConfig", "LoggingRole", "SecurityPolicyName", "SftpConfig", "Url"},
			"update-host-key":                {"Description", "HostKeyId", "ServerId"},
			"update-profile":                 {"CertificateIds", "ProfileId"},
			"update-server":                  {"Certificate", "EndpointDetails", "EndpointType", "HostKey", "IdentityProviderDetails", "IdentityProviderType", "IpAddressType", "LoggingRole", "PostAuthenticationLoginBanner", "PreAuthenticationLoginBanner", "ProtocolDetails", "Protocols", "S3StorageOptions", "SecurityPolicyName", "ServerId", "StructuredLogDestinations", "WorkflowDetails"},
			"update-user":                    {"HomeDirectory", "HomeDirectoryMappings", "HomeDirectoryType", "Policy", "PosixProfile", "Role", "ServerId", "UserName"},
			"update-web-app":                 {"AccessEndpoint", "EndpointDetails", "IdentityProviderDetails", "WebAppId", "WebAppUnits"},
			"update-web-app-customization":   {"FaviconFile", "LogoFile", "Title", "WebAppId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-access":                  {"ExternalId": "*string", "HomeDirectory": "*string", "HomeDirectoryMappings": "[]types.HomeDirectoryMapEntry", "HomeDirectoryType": "types.HomeDirectoryType", "Policy": "*string", "PosixProfile": "*types.PosixProfile", "Role": "*string", "ServerId": "*string"},
			"create-agreement":               {"AccessRole": "*string", "BaseDirectory": "*string", "CustomDirectories": "*types.CustomDirectoriesType", "Description": "*string", "EnforceMessageSigning": "types.EnforceMessageSigningType", "LocalProfileId": "*string", "PartnerProfileId": "*string", "PreserveFilename": "types.PreserveFilenameType", "ServerId": "*string", "Status": "types.AgreementStatusType", "Tags": "[]types.Tag"},
			"create-connector":               {"AccessRole": "*string", "As2Config": "*types.As2ConnectorConfig", "EgressConfig": "types.ConnectorEgressConfig", "LoggingRole": "*string", "SecurityPolicyName": "*string", "SftpConfig": "*types.SftpConnectorConfig", "Tags": "[]types.Tag", "Url": "*string"},
			"create-profile":                 {"As2Id": "*string", "CertificateIds": "[]string", "ProfileType": "types.ProfileType", "Tags": "[]types.Tag"},
			"create-server":                  {"Certificate": "*string", "Domain": "types.Domain", "EndpointDetails": "*types.EndpointDetails", "EndpointType": "types.EndpointType", "HostKey": "*string", "IdentityProviderDetails": "*types.IdentityProviderDetails", "IdentityProviderType": "types.IdentityProviderType", "IpAddressType": "types.IpAddressType", "LoggingRole": "*string", "PostAuthenticationLoginBanner": "*string", "PreAuthenticationLoginBanner": "*string", "ProtocolDetails": "*types.ProtocolDetails", "Protocols": "[]types.Protocol", "S3StorageOptions": "*types.S3StorageOptions", "SecurityPolicyName": "*string", "StructuredLogDestinations": "[]string", "Tags": "[]types.Tag", "WorkflowDetails": "*types.WorkflowDetails"},
			"create-user":                    {"HomeDirectory": "*string", "HomeDirectoryMappings": "[]types.HomeDirectoryMapEntry", "HomeDirectoryType": "types.HomeDirectoryType", "Policy": "*string", "PosixProfile": "*types.PosixProfile", "Role": "*string", "ServerId": "*string", "SshPublicKeyBody": "*string", "Tags": "[]types.Tag", "UserName": "*string"},
			"create-web-app":                 {"AccessEndpoint": "*string", "EndpointDetails": "types.WebAppEndpointDetails", "IdentityProviderDetails": "types.WebAppIdentityProviderDetails", "Tags": "[]types.Tag", "WebAppEndpointPolicy": "types.WebAppEndpointPolicy", "WebAppUnits": "types.WebAppUnits"},
			"create-workflow":                {"Description": "*string", "OnExceptionSteps": "[]types.WorkflowStep", "Steps": "[]types.WorkflowStep", "Tags": "[]types.Tag"},
			"delete-access":                  {"ExternalId": "*string", "ServerId": "*string"},
			"delete-agreement":               {"AgreementId": "*string", "ServerId": "*string"},
			"delete-certificate":             {"CertificateId": "*string"},
			"delete-connector":               {"ConnectorId": "*string"},
			"delete-host-key":                {"HostKeyId": "*string", "ServerId": "*string"},
			"delete-profile":                 {"ProfileId": "*string"},
			"delete-server":                  {"ServerId": "*string"},
			"delete-ssh-public-key":          {"ServerId": "*string", "SshPublicKeyId": "*string", "UserName": "*string"},
			"delete-user":                    {"ServerId": "*string", "UserName": "*string"},
			"delete-web-app":                 {"WebAppId": "*string"},
			"delete-web-app-customization":   {"WebAppId": "*string"},
			"delete-workflow":                {"WorkflowId": "*string"},
			"describe-access":                {"ExternalId": "*string", "ServerId": "*string"},
			"describe-agreement":             {"AgreementId": "*string", "ServerId": "*string"},
			"describe-certificate":           {"CertificateId": "*string"},
			"describe-connector":             {"ConnectorId": "*string"},
			"describe-execution":             {"ExecutionId": "*string", "WorkflowId": "*string"},
			"describe-host-key":              {"HostKeyId": "*string", "ServerId": "*string"},
			"describe-profile":               {"ProfileId": "*string"},
			"describe-security-policy":       {"SecurityPolicyName": "*string"},
			"describe-server":                {"ServerId": "*string"},
			"describe-user":                  {"ServerId": "*string", "UserName": "*string"},
			"describe-web-app":               {"WebAppId": "*string"},
			"describe-web-app-customization": {"WebAppId": "*string"},
			"describe-workflow":              {"WorkflowId": "*string"},
			"import-certificate":             {"ActiveDate": "*time.Time", "Certificate": "*string", "CertificateChain": "*string", "Description": "*string", "InactiveDate": "*time.Time", "PrivateKey": "*string", "Tags": "[]types.Tag", "Usage": "types.CertificateUsageType"},
			"import-host-key":                {"Description": "*string", "HostKeyBody": "*string", "ServerId": "*string", "Tags": "[]types.Tag"},
			"import-ssh-public-key":          {"ServerId": "*string", "SshPublicKeyBody": "*string", "UserName": "*string"},
			"list-accesses":                  {"MaxResults": "*int32", "NextToken": "*string", "ServerId": "*string"},
			"list-agreements":                {"MaxResults": "*int32", "NextToken": "*string", "ServerId": "*string"},
			"list-certificates":              {"MaxResults": "*int32", "NextToken": "*string"},
			"list-connectors":                {"MaxResults": "*int32", "NextToken": "*string"},
			"list-executions":                {"MaxResults": "*int32", "NextToken": "*string", "WorkflowId": "*string"},
			"list-file-transfer-results":     {"ConnectorId": "*string", "MaxResults": "*int32", "NextToken": "*string", "TransferId": "*string"},
			"list-host-keys":                 {"MaxResults": "*int32", "NextToken": "*string", "ServerId": "*string"},
			"list-profiles":                  {"MaxResults": "*int32", "NextToken": "*string", "ProfileType": "types.ProfileType"},
			"list-security-policies":         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-servers":                   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":         {"Arn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-users":                     {"MaxResults": "*int32", "NextToken": "*string", "ServerId": "*string"},
			"list-web-apps":                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-workflows":                 {"MaxResults": "*int32", "NextToken": "*string"},
			"send-workflow-step-state":       {"ExecutionId": "*string", "Status": "types.CustomStepStatus", "Token": "*string", "WorkflowId": "*string"},
			"start-directory-listing":        {"ConnectorId": "*string", "MaxItems": "*int32", "OutputDirectoryPath": "*string", "RemoteDirectoryPath": "*string"},
			"start-file-transfer":            {"ConnectorId": "*string", "CustomHttpHeaders": "[]types.CustomHttpHeader", "LocalDirectoryPath": "*string", "RemoteDirectoryPath": "*string", "RetrieveFilePaths": "[]string", "SendFilePaths": "[]string"},
			"start-remote-delete":            {"ConnectorId": "*string", "DeletePath": "*string"},
			"start-remote-move":              {"ConnectorId": "*string", "SourcePath": "*string", "TargetPath": "*string"},
			"start-server":                   {"ServerId": "*string"},
			"stop-server":                    {"ServerId": "*string"},
			"tag-resource":                   {"Arn": "*string", "Tags": "[]types.Tag"},
			"test-connection":                {"ConnectorId": "*string"},
			"test-identity-provider":         {"ServerId": "*string", "ServerProtocol": "types.Protocol", "SourceIp": "*string", "UserName": "*string", "UserPassword": "*string"},
			"untag-resource":                 {"Arn": "*string", "TagKeys": "[]string"},
			"update-access":                  {"ExternalId": "*string", "HomeDirectory": "*string", "HomeDirectoryMappings": "[]types.HomeDirectoryMapEntry", "HomeDirectoryType": "types.HomeDirectoryType", "Policy": "*string", "PosixProfile": "*types.PosixProfile", "Role": "*string", "ServerId": "*string"},
			"update-agreement":               {"AccessRole": "*string", "AgreementId": "*string", "BaseDirectory": "*string", "CustomDirectories": "*types.CustomDirectoriesType", "Description": "*string", "EnforceMessageSigning": "types.EnforceMessageSigningType", "LocalProfileId": "*string", "PartnerProfileId": "*string", "PreserveFilename": "types.PreserveFilenameType", "ServerId": "*string", "Status": "types.AgreementStatusType"},
			"update-certificate":             {"ActiveDate": "*time.Time", "CertificateId": "*string", "Description": "*string", "InactiveDate": "*time.Time"},
			"update-connector":               {"AccessRole": "*string", "As2Config": "*types.As2ConnectorConfig", "ConnectorId": "*string", "EgressConfig": "types.UpdateConnectorEgressConfig", "LoggingRole": "*string", "SecurityPolicyName": "*string", "SftpConfig": "*types.SftpConnectorConfig", "Url": "*string"},
			"update-host-key":                {"Description": "*string", "HostKeyId": "*string", "ServerId": "*string"},
			"update-profile":                 {"CertificateIds": "[]string", "ProfileId": "*string"},
			"update-server":                  {"Certificate": "*string", "EndpointDetails": "*types.EndpointDetails", "EndpointType": "types.EndpointType", "HostKey": "*string", "IdentityProviderDetails": "*types.IdentityProviderDetails", "IdentityProviderType": "types.IdentityProviderType", "IpAddressType": "types.IpAddressType", "LoggingRole": "*string", "PostAuthenticationLoginBanner": "*string", "PreAuthenticationLoginBanner": "*string", "ProtocolDetails": "*types.ProtocolDetails", "Protocols": "[]types.Protocol", "S3StorageOptions": "*types.S3StorageOptions", "SecurityPolicyName": "*string", "ServerId": "*string", "StructuredLogDestinations": "[]string", "WorkflowDetails": "*types.WorkflowDetails"},
			"update-user":                    {"HomeDirectory": "*string", "HomeDirectoryMappings": "[]types.HomeDirectoryMapEntry", "HomeDirectoryType": "types.HomeDirectoryType", "Policy": "*string", "PosixProfile": "*types.PosixProfile", "Role": "*string", "ServerId": "*string", "UserName": "*string"},
			"update-web-app":                 {"AccessEndpoint": "*string", "EndpointDetails": "types.UpdateWebAppEndpointDetails", "IdentityProviderDetails": "types.UpdateWebAppIdentityProviderDetails", "WebAppId": "*string", "WebAppUnits": "types.WebAppUnits"},
			"update-web-app-customization":   {"FaviconFile": "[]byte", "LogoFile": "[]byte", "Title": "*string", "WebAppId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-access":                  {"ExternalId", "Role", "ServerId"},
			"create-agreement":               {"AccessRole", "LocalProfileId", "PartnerProfileId", "ServerId"},
			"create-connector":               {"AccessRole"},
			"create-profile":                 {"As2Id", "ProfileType"},
			"create-server":                  {},
			"create-user":                    {"Role", "ServerId", "UserName"},
			"create-web-app":                 {"IdentityProviderDetails"},
			"create-workflow":                {"Steps"},
			"delete-access":                  {"ExternalId", "ServerId"},
			"delete-agreement":               {"AgreementId", "ServerId"},
			"delete-certificate":             {"CertificateId"},
			"delete-connector":               {"ConnectorId"},
			"delete-host-key":                {"HostKeyId", "ServerId"},
			"delete-profile":                 {"ProfileId"},
			"delete-server":                  {"ServerId"},
			"delete-ssh-public-key":          {"ServerId", "SshPublicKeyId", "UserName"},
			"delete-user":                    {"ServerId", "UserName"},
			"delete-web-app":                 {"WebAppId"},
			"delete-web-app-customization":   {"WebAppId"},
			"delete-workflow":                {"WorkflowId"},
			"describe-access":                {"ExternalId", "ServerId"},
			"describe-agreement":             {"AgreementId", "ServerId"},
			"describe-certificate":           {"CertificateId"},
			"describe-connector":             {"ConnectorId"},
			"describe-execution":             {"ExecutionId", "WorkflowId"},
			"describe-host-key":              {"HostKeyId", "ServerId"},
			"describe-profile":               {"ProfileId"},
			"describe-security-policy":       {"SecurityPolicyName"},
			"describe-server":                {"ServerId"},
			"describe-user":                  {"ServerId", "UserName"},
			"describe-web-app":               {"WebAppId"},
			"describe-web-app-customization": {"WebAppId"},
			"describe-workflow":              {"WorkflowId"},
			"import-certificate":             {"Certificate", "Usage"},
			"import-host-key":                {"HostKeyBody", "ServerId"},
			"import-ssh-public-key":          {"ServerId", "SshPublicKeyBody", "UserName"},
			"list-accesses":                  {"ServerId"},
			"list-agreements":                {"ServerId"},
			"list-certificates":              {},
			"list-connectors":                {},
			"list-executions":                {"WorkflowId"},
			"list-file-transfer-results":     {"ConnectorId", "TransferId"},
			"list-host-keys":                 {"ServerId"},
			"list-profiles":                  {},
			"list-security-policies":         {},
			"list-servers":                   {},
			"list-tags-for-resource":         {"Arn"},
			"list-users":                     {"ServerId"},
			"list-web-apps":                  {},
			"list-workflows":                 {},
			"send-workflow-step-state":       {"ExecutionId", "Status", "Token", "WorkflowId"},
			"start-directory-listing":        {"ConnectorId", "OutputDirectoryPath", "RemoteDirectoryPath"},
			"start-file-transfer":            {"ConnectorId"},
			"start-remote-delete":            {"ConnectorId", "DeletePath"},
			"start-remote-move":              {"ConnectorId", "SourcePath", "TargetPath"},
			"start-server":                   {"ServerId"},
			"stop-server":                    {"ServerId"},
			"tag-resource":                   {"Arn", "Tags"},
			"test-connection":                {"ConnectorId"},
			"test-identity-provider":         {"ServerId", "UserName"},
			"untag-resource":                 {"Arn", "TagKeys"},
			"update-access":                  {"ExternalId", "ServerId"},
			"update-agreement":               {"AgreementId", "ServerId"},
			"update-certificate":             {"CertificateId"},
			"update-connector":               {"ConnectorId"},
			"update-host-key":                {"Description", "HostKeyId", "ServerId"},
			"update-profile":                 {"ProfileId"},
			"update-server":                  {"ServerId"},
			"update-user":                    {"ServerId", "UserName"},
			"update-web-app":                 {"WebAppId"},
			"update-web-app-customization":   {"WebAppId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("transfer", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
