package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/notifications/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-channel", "associate-managed-notification-account-contact", "associate-managed-notification-additional-channel", "associate-organizational-unit", "create-event-rule", "create-notification-configuration", "delete-event-rule", "delete-notification-configuration", "deregister-notification-hub", "disable-notifications-access-for-organization", "disassociate-channel", "disassociate-managed-notification-account-contact", "disassociate-managed-notification-additional-channel", "disassociate-organizational-unit", "enable-notifications-access-for-organization", "get-event-rule", "get-managed-notification-child-event", "get-managed-notification-configuration", "get-managed-notification-event", "get-notification-configuration", "get-notification-event", "get-notifications-access-for-organization", "list-channels", "list-event-rules", "list-managed-notification-channel-associations", "list-managed-notification-child-events", "list-managed-notification-configurations", "list-managed-notification-events", "list-member-accounts", "list-notification-configurations", "list-notification-events", "list-notification-hubs", "list-organizational-units", "list-tags-for-resource", "register-notification-hub", "tag-resource", "untag-resource", "update-event-rule", "update-notification-configuration"},
		OperationSet: map[string]bool{"associate-channel": true, "associate-managed-notification-account-contact": true, "associate-managed-notification-additional-channel": true, "associate-organizational-unit": true, "create-event-rule": true, "create-notification-configuration": true, "delete-event-rule": true, "delete-notification-configuration": true, "deregister-notification-hub": true, "disable-notifications-access-for-organization": true, "disassociate-channel": true, "disassociate-managed-notification-account-contact": true, "disassociate-managed-notification-additional-channel": true, "disassociate-organizational-unit": true, "enable-notifications-access-for-organization": true, "get-event-rule": true, "get-managed-notification-child-event": true, "get-managed-notification-configuration": true, "get-managed-notification-event": true, "get-notification-configuration": true, "get-notification-event": true, "get-notifications-access-for-organization": true, "list-channels": true, "list-event-rules": true, "list-managed-notification-channel-associations": true, "list-managed-notification-child-events": true, "list-managed-notification-configurations": true, "list-managed-notification-events": true, "list-member-accounts": true, "list-notification-configurations": true, "list-notification-events": true, "list-notification-hubs": true, "list-organizational-units": true, "list-tags-for-resource": true, "register-notification-hub": true, "tag-resource": true, "untag-resource": true, "update-event-rule": true, "update-notification-configuration": true},
		OperationInputs: map[string][]string{
			"associate-channel": {"Arn", "NotificationConfigurationArn"},
			"associate-managed-notification-account-contact":       {"ContactIdentifier", "ManagedNotificationConfigurationArn"},
			"associate-managed-notification-additional-channel":    {"ChannelArn", "ManagedNotificationConfigurationArn"},
			"associate-organizational-unit":                        {"NotificationConfigurationArn", "OrganizationalUnitId"},
			"create-event-rule":                                    {"EventPattern", "EventType", "NotificationConfigurationArn", "Regions", "Source"},
			"create-notification-configuration":                    {"AggregationDuration", "Description", "Name", "Tags"},
			"delete-event-rule":                                    {"Arn"},
			"delete-notification-configuration":                    {"Arn"},
			"deregister-notification-hub":                          {"NotificationHubRegion"},
			"disable-notifications-access-for-organization":        {},
			"disassociate-channel":                                 {"Arn", "NotificationConfigurationArn"},
			"disassociate-managed-notification-account-contact":    {"ContactIdentifier", "ManagedNotificationConfigurationArn"},
			"disassociate-managed-notification-additional-channel": {"ChannelArn", "ManagedNotificationConfigurationArn"},
			"disassociate-organizational-unit":                     {"NotificationConfigurationArn", "OrganizationalUnitId"},
			"enable-notifications-access-for-organization":         {},
			"get-event-rule":                                       {"Arn"},
			"get-managed-notification-child-event":                 {"Arn", "Locale"},
			"get-managed-notification-configuration":               {"Arn"},
			"get-managed-notification-event":                       {"Arn", "Locale"},
			"get-notification-configuration":                       {"Arn"},
			"get-notification-event":                               {"Arn", "Locale"},
			"get-notifications-access-for-organization":            {},
			"list-channels":                                        {"MaxResults", "NextToken", "NotificationConfigurationArn"},
			"list-event-rules":                                     {"MaxResults", "NextToken", "NotificationConfigurationArn"},
			"list-managed-notification-channel-associations":       {"ManagedNotificationConfigurationArn", "MaxResults", "NextToken"},
			"list-managed-notification-child-events":               {"AggregateManagedNotificationEventArn", "EndTime", "Locale", "MaxResults", "NextToken", "OrganizationalUnitId", "RelatedAccount", "StartTime"},
			"list-managed-notification-configurations":             {"ChannelIdentifier", "MaxResults", "NextToken"},
			"list-managed-notification-events":                     {"EndTime", "Locale", "MaxResults", "NextToken", "OrganizationalUnitId", "RelatedAccount", "Source", "StartTime"},
			"list-member-accounts":                                 {"MaxResults", "MemberAccount", "NextToken", "NotificationConfigurationArn", "OrganizationalUnitId", "Status"},
			"list-notification-configurations":                     {"ChannelArn", "EventRuleSource", "MaxResults", "NextToken", "Status", "Subtype"},
			"list-notification-events":                             {"AggregateNotificationEventArn", "EndTime", "IncludeChildEvents", "Locale", "MaxResults", "NextToken", "OrganizationalUnitId", "Source", "StartTime"},
			"list-notification-hubs":                               {"MaxResults", "NextToken"},
			"list-organizational-units":                            {"MaxResults", "NextToken", "NotificationConfigurationArn"},
			"list-tags-for-resource":                               {"Arn"},
			"register-notification-hub":                            {"NotificationHubRegion"},
			"tag-resource":                                         {"Arn", "Tags"},
			"untag-resource":                                       {"Arn", "TagKeys"},
			"update-event-rule":                                    {"Arn", "EventPattern", "Regions"},
			"update-notification-configuration":                    {"AggregationDuration", "Arn", "Description", "Name"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-channel": {"Arn": "*string", "NotificationConfigurationArn": "*string"},
			"associate-managed-notification-account-contact":       {"ContactIdentifier": "types.AccountContactType", "ManagedNotificationConfigurationArn": "*string"},
			"associate-managed-notification-additional-channel":    {"ChannelArn": "*string", "ManagedNotificationConfigurationArn": "*string"},
			"associate-organizational-unit":                        {"NotificationConfigurationArn": "*string", "OrganizationalUnitId": "*string"},
			"create-event-rule":                                    {"EventPattern": "*string", "EventType": "*string", "NotificationConfigurationArn": "*string", "Regions": "[]string", "Source": "*string"},
			"create-notification-configuration":                    {"AggregationDuration": "types.AggregationDuration", "Description": "*string", "Name": "*string", "Tags": "map[string]string"},
			"delete-event-rule":                                    {"Arn": "*string"},
			"delete-notification-configuration":                    {"Arn": "*string"},
			"deregister-notification-hub":                          {"NotificationHubRegion": "*string"},
			"disable-notifications-access-for-organization":        {},
			"disassociate-channel":                                 {"Arn": "*string", "NotificationConfigurationArn": "*string"},
			"disassociate-managed-notification-account-contact":    {"ContactIdentifier": "types.AccountContactType", "ManagedNotificationConfigurationArn": "*string"},
			"disassociate-managed-notification-additional-channel": {"ChannelArn": "*string", "ManagedNotificationConfigurationArn": "*string"},
			"disassociate-organizational-unit":                     {"NotificationConfigurationArn": "*string", "OrganizationalUnitId": "*string"},
			"enable-notifications-access-for-organization":         {},
			"get-event-rule":                                       {"Arn": "*string"},
			"get-managed-notification-child-event":                 {"Arn": "*string", "Locale": "types.LocaleCode"},
			"get-managed-notification-configuration":               {"Arn": "*string"},
			"get-managed-notification-event":                       {"Arn": "*string", "Locale": "types.LocaleCode"},
			"get-notification-configuration":                       {"Arn": "*string"},
			"get-notification-event":                               {"Arn": "*string", "Locale": "types.LocaleCode"},
			"get-notifications-access-for-organization":            {},
			"list-channels":                                        {"MaxResults": "*int32", "NextToken": "*string", "NotificationConfigurationArn": "*string"},
			"list-event-rules":                                     {"MaxResults": "*int32", "NextToken": "*string", "NotificationConfigurationArn": "*string"},
			"list-managed-notification-channel-associations":       {"ManagedNotificationConfigurationArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-managed-notification-child-events":               {"AggregateManagedNotificationEventArn": "*string", "EndTime": "*time.Time", "Locale": "types.LocaleCode", "MaxResults": "*int32", "NextToken": "*string", "OrganizationalUnitId": "*string", "RelatedAccount": "*string", "StartTime": "*time.Time"},
			"list-managed-notification-configurations":             {"ChannelIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-managed-notification-events":                     {"EndTime": "*time.Time", "Locale": "types.LocaleCode", "MaxResults": "*int32", "NextToken": "*string", "OrganizationalUnitId": "*string", "RelatedAccount": "*string", "Source": "*string", "StartTime": "*time.Time"},
			"list-member-accounts":                                 {"MaxResults": "*int32", "MemberAccount": "*string", "NextToken": "*string", "NotificationConfigurationArn": "*string", "OrganizationalUnitId": "*string", "Status": "types.MemberAccountNotificationConfigurationStatus"},
			"list-notification-configurations":                     {"ChannelArn": "*string", "EventRuleSource": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.NotificationConfigurationStatus", "Subtype": "types.NotificationConfigurationSubtype"},
			"list-notification-events":                             {"AggregateNotificationEventArn": "*string", "EndTime": "*time.Time", "IncludeChildEvents": "*bool", "Locale": "types.LocaleCode", "MaxResults": "*int32", "NextToken": "*string", "OrganizationalUnitId": "*string", "Source": "*string", "StartTime": "*time.Time"},
			"list-notification-hubs":                               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-organizational-units":                            {"MaxResults": "*int32", "NextToken": "*string", "NotificationConfigurationArn": "*string"},
			"list-tags-for-resource":                               {"Arn": "*string"},
			"register-notification-hub":                            {"NotificationHubRegion": "*string"},
			"tag-resource":                                         {"Arn": "*string", "Tags": "map[string]string"},
			"untag-resource":                                       {"Arn": "*string", "TagKeys": "[]string"},
			"update-event-rule":                                    {"Arn": "*string", "EventPattern": "*string", "Regions": "[]string"},
			"update-notification-configuration":                    {"AggregationDuration": "types.AggregationDuration", "Arn": "*string", "Description": "*string", "Name": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-channel": {"Arn", "NotificationConfigurationArn"},
			"associate-managed-notification-account-contact":       {"ContactIdentifier", "ManagedNotificationConfigurationArn"},
			"associate-managed-notification-additional-channel":    {"ChannelArn", "ManagedNotificationConfigurationArn"},
			"associate-organizational-unit":                        {"NotificationConfigurationArn", "OrganizationalUnitId"},
			"create-event-rule":                                    {"EventType", "NotificationConfigurationArn", "Regions", "Source"},
			"create-notification-configuration":                    {"Description", "Name"},
			"delete-event-rule":                                    {"Arn"},
			"delete-notification-configuration":                    {"Arn"},
			"deregister-notification-hub":                          {"NotificationHubRegion"},
			"disable-notifications-access-for-organization":        {},
			"disassociate-channel":                                 {"Arn", "NotificationConfigurationArn"},
			"disassociate-managed-notification-account-contact":    {"ContactIdentifier", "ManagedNotificationConfigurationArn"},
			"disassociate-managed-notification-additional-channel": {"ChannelArn", "ManagedNotificationConfigurationArn"},
			"disassociate-organizational-unit":                     {"NotificationConfigurationArn", "OrganizationalUnitId"},
			"enable-notifications-access-for-organization":         {},
			"get-event-rule":                                       {"Arn"},
			"get-managed-notification-child-event":                 {"Arn"},
			"get-managed-notification-configuration":               {"Arn"},
			"get-managed-notification-event":                       {"Arn"},
			"get-notification-configuration":                       {"Arn"},
			"get-notification-event":                               {"Arn"},
			"get-notifications-access-for-organization":            {},
			"list-channels":                                        {"NotificationConfigurationArn"},
			"list-event-rules":                                     {"NotificationConfigurationArn"},
			"list-managed-notification-channel-associations":       {"ManagedNotificationConfigurationArn"},
			"list-managed-notification-child-events":               {"AggregateManagedNotificationEventArn"},
			"list-managed-notification-configurations":             {},
			"list-managed-notification-events":                     {},
			"list-member-accounts":                                 {"NotificationConfigurationArn"},
			"list-notification-configurations":                     {},
			"list-notification-events":                             {},
			"list-notification-hubs":                               {},
			"list-organizational-units":                            {"NotificationConfigurationArn"},
			"list-tags-for-resource":                               {"Arn"},
			"register-notification-hub":                            {"NotificationHubRegion"},
			"tag-resource":                                         {"Arn", "Tags"},
			"untag-resource":                                       {"Arn", "TagKeys"},
			"update-event-rule":                                    {"Arn"},
			"update-notification-configuration":                    {"Arn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("notifications", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
