package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/proton/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-environment-account-connection", "cancel-component-deployment", "cancel-environment-deployment", "cancel-service-instance-deployment", "cancel-service-pipeline-deployment", "create-component", "create-environment", "create-environment-account-connection", "create-environment-template", "create-environment-template-version", "create-repository", "create-service", "create-service-instance", "create-service-sync-config", "create-service-template", "create-service-template-version", "create-template-sync-config", "delete-component", "delete-deployment", "delete-environment", "delete-environment-account-connection", "delete-environment-template", "delete-environment-template-version", "delete-repository", "delete-service", "delete-service-sync-config", "delete-service-template", "delete-service-template-version", "delete-template-sync-config", "get-account-settings", "get-component", "get-deployment", "get-environment", "get-environment-account-connection", "get-environment-template", "get-environment-template-version", "get-repository", "get-repository-sync-status", "get-resources-summary", "get-service", "get-service-instance", "get-service-instance-sync-status", "get-service-sync-blocker-summary", "get-service-sync-config", "get-service-template", "get-service-template-version", "get-template-sync-config", "get-template-sync-status", "list-component-outputs", "list-component-provisioned-resources", "list-components", "list-deployments", "list-environment-account-connections", "list-environment-outputs", "list-environment-provisioned-resources", "list-environment-template-versions", "list-environment-templates", "list-environments", "list-repositories", "list-repository-sync-definitions", "list-service-instance-outputs", "list-service-instance-provisioned-resources", "list-service-instances", "list-service-pipeline-outputs", "list-service-pipeline-provisioned-resources", "list-service-template-versions", "list-service-templates", "list-services", "list-tags-for-resource", "notify-resource-deployment-status-change", "reject-environment-account-connection", "tag-resource", "untag-resource", "update-account-settings", "update-component", "update-environment", "update-environment-account-connection", "update-environment-template", "update-environment-template-version", "update-service", "update-service-instance", "update-service-pipeline", "update-service-sync-blocker", "update-service-sync-config", "update-service-template", "update-service-template-version", "update-template-sync-config"},
		OperationSet: map[string]bool{"accept-environment-account-connection": true, "cancel-component-deployment": true, "cancel-environment-deployment": true, "cancel-service-instance-deployment": true, "cancel-service-pipeline-deployment": true, "create-component": true, "create-environment": true, "create-environment-account-connection": true, "create-environment-template": true, "create-environment-template-version": true, "create-repository": true, "create-service": true, "create-service-instance": true, "create-service-sync-config": true, "create-service-template": true, "create-service-template-version": true, "create-template-sync-config": true, "delete-component": true, "delete-deployment": true, "delete-environment": true, "delete-environment-account-connection": true, "delete-environment-template": true, "delete-environment-template-version": true, "delete-repository": true, "delete-service": true, "delete-service-sync-config": true, "delete-service-template": true, "delete-service-template-version": true, "delete-template-sync-config": true, "get-account-settings": true, "get-component": true, "get-deployment": true, "get-environment": true, "get-environment-account-connection": true, "get-environment-template": true, "get-environment-template-version": true, "get-repository": true, "get-repository-sync-status": true, "get-resources-summary": true, "get-service": true, "get-service-instance": true, "get-service-instance-sync-status": true, "get-service-sync-blocker-summary": true, "get-service-sync-config": true, "get-service-template": true, "get-service-template-version": true, "get-template-sync-config": true, "get-template-sync-status": true, "list-component-outputs": true, "list-component-provisioned-resources": true, "list-components": true, "list-deployments": true, "list-environment-account-connections": true, "list-environment-outputs": true, "list-environment-provisioned-resources": true, "list-environment-template-versions": true, "list-environment-templates": true, "list-environments": true, "list-repositories": true, "list-repository-sync-definitions": true, "list-service-instance-outputs": true, "list-service-instance-provisioned-resources": true, "list-service-instances": true, "list-service-pipeline-outputs": true, "list-service-pipeline-provisioned-resources": true, "list-service-template-versions": true, "list-service-templates": true, "list-services": true, "list-tags-for-resource": true, "notify-resource-deployment-status-change": true, "reject-environment-account-connection": true, "tag-resource": true, "untag-resource": true, "update-account-settings": true, "update-component": true, "update-environment": true, "update-environment-account-connection": true, "update-environment-template": true, "update-environment-template-version": true, "update-service": true, "update-service-instance": true, "update-service-pipeline": true, "update-service-sync-blocker": true, "update-service-sync-config": true, "update-service-template": true, "update-service-template-version": true, "update-template-sync-config": true},
		OperationInputs: map[string][]string{
			"accept-environment-account-connection":       {"Id"},
			"cancel-component-deployment":                 {"ComponentName"},
			"cancel-environment-deployment":               {"EnvironmentName"},
			"cancel-service-instance-deployment":          {"ServiceInstanceName", "ServiceName"},
			"cancel-service-pipeline-deployment":          {"ServiceName"},
			"create-component":                            {"ClientToken", "Description", "EnvironmentName", "Manifest", "Name", "ServiceInstanceName", "ServiceName", "ServiceSpec", "Tags", "TemplateFile"},
			"create-environment":                          {"CodebuildRoleArn", "ComponentRoleArn", "Description", "EnvironmentAccountConnectionId", "Name", "ProtonServiceRoleArn", "ProvisioningRepository", "Spec", "Tags", "TemplateMajorVersion", "TemplateMinorVersion", "TemplateName"},
			"create-environment-account-connection":       {"ClientToken", "CodebuildRoleArn", "ComponentRoleArn", "EnvironmentName", "ManagementAccountId", "RoleArn", "Tags"},
			"create-environment-template":                 {"Description", "DisplayName", "EncryptionKey", "Name", "Provisioning", "Tags"},
			"create-environment-template-version":         {"ClientToken", "Description", "MajorVersion", "Source", "Tags", "TemplateName"},
			"create-repository":                           {"ConnectionArn", "EncryptionKey", "Name", "Provider", "Tags"},
			"create-service":                              {"BranchName", "Description", "Name", "RepositoryConnectionArn", "RepositoryId", "Spec", "Tags", "TemplateMajorVersion", "TemplateMinorVersion", "TemplateName"},
			"create-service-instance":                     {"ClientToken", "Name", "ServiceName", "Spec", "Tags", "TemplateMajorVersion", "TemplateMinorVersion"},
			"create-service-sync-config":                  {"Branch", "FilePath", "RepositoryName", "RepositoryProvider", "ServiceName"},
			"create-service-template":                     {"Description", "DisplayName", "EncryptionKey", "Name", "PipelineProvisioning", "Tags"},
			"create-service-template-version":             {"ClientToken", "CompatibleEnvironmentTemplates", "Description", "MajorVersion", "Source", "SupportedComponentSources", "Tags", "TemplateName"},
			"create-template-sync-config":                 {"Branch", "RepositoryName", "RepositoryProvider", "Subdirectory", "TemplateName", "TemplateType"},
			"delete-component":                            {"Name"},
			"delete-deployment":                           {"Id"},
			"delete-environment":                          {"Name"},
			"delete-environment-account-connection":       {"Id"},
			"delete-environment-template":                 {"Name"},
			"delete-environment-template-version":         {"MajorVersion", "MinorVersion", "TemplateName"},
			"delete-repository":                           {"Name", "Provider"},
			"delete-service":                              {"Name"},
			"delete-service-sync-config":                  {"ServiceName"},
			"delete-service-template":                     {"Name"},
			"delete-service-template-version":             {"MajorVersion", "MinorVersion", "TemplateName"},
			"delete-template-sync-config":                 {"TemplateName", "TemplateType"},
			"get-account-settings":                        {},
			"get-component":                               {"Name"},
			"get-deployment":                              {"ComponentName", "EnvironmentName", "Id", "ServiceInstanceName", "ServiceName"},
			"get-environment":                             {"Name"},
			"get-environment-account-connection":          {"Id"},
			"get-environment-template":                    {"Name"},
			"get-environment-template-version":            {"MajorVersion", "MinorVersion", "TemplateName"},
			"get-repository":                              {"Name", "Provider"},
			"get-repository-sync-status":                  {"Branch", "RepositoryName", "RepositoryProvider", "SyncType"},
			"get-resources-summary":                       {},
			"get-service":                                 {"Name"},
			"get-service-instance":                        {"Name", "ServiceName"},
			"get-service-instance-sync-status":            {"ServiceInstanceName", "ServiceName"},
			"get-service-sync-blocker-summary":            {"ServiceInstanceName", "ServiceName"},
			"get-service-sync-config":                     {"ServiceName"},
			"get-service-template":                        {"Name"},
			"get-service-template-version":                {"MajorVersion", "MinorVersion", "TemplateName"},
			"get-template-sync-config":                    {"TemplateName", "TemplateType"},
			"get-template-sync-status":                    {"TemplateName", "TemplateType", "TemplateVersion"},
			"list-component-outputs":                      {"ComponentName", "DeploymentId", "NextToken"},
			"list-component-provisioned-resources":        {"ComponentName", "NextToken"},
			"list-components":                             {"EnvironmentName", "MaxResults", "NextToken", "ServiceInstanceName", "ServiceName"},
			"list-deployments":                            {"ComponentName", "EnvironmentName", "MaxResults", "NextToken", "ServiceInstanceName", "ServiceName"},
			"list-environment-account-connections":        {"EnvironmentName", "MaxResults", "NextToken", "RequestedBy", "Statuses"},
			"list-environment-outputs":                    {"DeploymentId", "EnvironmentName", "NextToken"},
			"list-environment-provisioned-resources":      {"EnvironmentName", "NextToken"},
			"list-environment-template-versions":          {"MajorVersion", "MaxResults", "NextToken", "TemplateName"},
			"list-environment-templates":                  {"MaxResults", "NextToken"},
			"list-environments":                           {"EnvironmentTemplates", "MaxResults", "NextToken"},
			"list-repositories":                           {"MaxResults", "NextToken"},
			"list-repository-sync-definitions":            {"NextToken", "RepositoryName", "RepositoryProvider", "SyncType"},
			"list-service-instance-outputs":               {"DeploymentId", "NextToken", "ServiceInstanceName", "ServiceName"},
			"list-service-instance-provisioned-resources": {"NextToken", "ServiceInstanceName", "ServiceName"},
			"list-service-instances":                      {"Filters", "MaxResults", "NextToken", "ServiceName", "SortBy", "SortOrder"},
			"list-service-pipeline-outputs":               {"DeploymentId", "NextToken", "ServiceName"},
			"list-service-pipeline-provisioned-resources": {"NextToken", "ServiceName"},
			"list-service-template-versions":              {"MajorVersion", "MaxResults", "NextToken", "TemplateName"},
			"list-service-templates":                      {"MaxResults", "NextToken"},
			"list-services":                               {"MaxResults", "NextToken"},
			"list-tags-for-resource":                      {"MaxResults", "NextToken", "ResourceArn"},
			"notify-resource-deployment-status-change":    {"DeploymentId", "Outputs", "ResourceArn", "Status", "StatusMessage"},
			"reject-environment-account-connection":       {"Id"},
			"tag-resource":                                {"ResourceArn", "Tags"},
			"untag-resource":                              {"ResourceArn", "TagKeys"},
			"update-account-settings":                     {"DeletePipelineProvisioningRepository", "PipelineCodebuildRoleArn", "PipelineProvisioningRepository", "PipelineServiceRoleArn"},
			"update-component":                            {"ClientToken", "DeploymentType", "Description", "Name", "ServiceInstanceName", "ServiceName", "ServiceSpec", "TemplateFile"},
			"update-environment":                          {"CodebuildRoleArn", "ComponentRoleArn", "DeploymentType", "Description", "EnvironmentAccountConnectionId", "Name", "ProtonServiceRoleArn", "ProvisioningRepository", "Spec", "TemplateMajorVersion", "TemplateMinorVersion"},
			"update-environment-account-connection":       {"CodebuildRoleArn", "ComponentRoleArn", "Id", "RoleArn"},
			"update-environment-template":                 {"Description", "DisplayName", "Name"},
			"update-environment-template-version":         {"Description", "MajorVersion", "MinorVersion", "Status", "TemplateName"},
			"update-service":                              {"Description", "Name", "Spec"},
			"update-service-instance":                     {"ClientToken", "DeploymentType", "Name", "ServiceName", "Spec", "TemplateMajorVersion", "TemplateMinorVersion"},
			"update-service-pipeline":                     {"DeploymentType", "ServiceName", "Spec", "TemplateMajorVersion", "TemplateMinorVersion"},
			"update-service-sync-blocker":                 {"Id", "ResolvedReason"},
			"update-service-sync-config":                  {"Branch", "FilePath", "RepositoryName", "RepositoryProvider", "ServiceName"},
			"update-service-template":                     {"Description", "DisplayName", "Name"},
			"update-service-template-version":             {"CompatibleEnvironmentTemplates", "Description", "MajorVersion", "MinorVersion", "Status", "SupportedComponentSources", "TemplateName"},
			"update-template-sync-config":                 {"Branch", "RepositoryName", "RepositoryProvider", "Subdirectory", "TemplateName", "TemplateType"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-environment-account-connection":       {"Id": "*string"},
			"cancel-component-deployment":                 {"ComponentName": "*string"},
			"cancel-environment-deployment":               {"EnvironmentName": "*string"},
			"cancel-service-instance-deployment":          {"ServiceInstanceName": "*string", "ServiceName": "*string"},
			"cancel-service-pipeline-deployment":          {"ServiceName": "*string"},
			"create-component":                            {"ClientToken": "*string", "Description": "*string", "EnvironmentName": "*string", "Manifest": "*string", "Name": "*string", "ServiceInstanceName": "*string", "ServiceName": "*string", "ServiceSpec": "*string", "Tags": "[]types.Tag", "TemplateFile": "*string"},
			"create-environment":                          {"CodebuildRoleArn": "*string", "ComponentRoleArn": "*string", "Description": "*string", "EnvironmentAccountConnectionId": "*string", "Name": "*string", "ProtonServiceRoleArn": "*string", "ProvisioningRepository": "*types.RepositoryBranchInput", "Spec": "*string", "Tags": "[]types.Tag", "TemplateMajorVersion": "*string", "TemplateMinorVersion": "*string", "TemplateName": "*string"},
			"create-environment-account-connection":       {"ClientToken": "*string", "CodebuildRoleArn": "*string", "ComponentRoleArn": "*string", "EnvironmentName": "*string", "ManagementAccountId": "*string", "RoleArn": "*string", "Tags": "[]types.Tag"},
			"create-environment-template":                 {"Description": "*string", "DisplayName": "*string", "EncryptionKey": "*string", "Name": "*string", "Provisioning": "types.Provisioning", "Tags": "[]types.Tag"},
			"create-environment-template-version":         {"ClientToken": "*string", "Description": "*string", "MajorVersion": "*string", "Source": "types.TemplateVersionSourceInput", "Tags": "[]types.Tag", "TemplateName": "*string"},
			"create-repository":                           {"ConnectionArn": "*string", "EncryptionKey": "*string", "Name": "*string", "Provider": "types.RepositoryProvider", "Tags": "[]types.Tag"},
			"create-service":                              {"BranchName": "*string", "Description": "*string", "Name": "*string", "RepositoryConnectionArn": "*string", "RepositoryId": "*string", "Spec": "*string", "Tags": "[]types.Tag", "TemplateMajorVersion": "*string", "TemplateMinorVersion": "*string", "TemplateName": "*string"},
			"create-service-instance":                     {"ClientToken": "*string", "Name": "*string", "ServiceName": "*string", "Spec": "*string", "Tags": "[]types.Tag", "TemplateMajorVersion": "*string", "TemplateMinorVersion": "*string"},
			"create-service-sync-config":                  {"Branch": "*string", "FilePath": "*string", "RepositoryName": "*string", "RepositoryProvider": "types.RepositoryProvider", "ServiceName": "*string"},
			"create-service-template":                     {"Description": "*string", "DisplayName": "*string", "EncryptionKey": "*string", "Name": "*string", "PipelineProvisioning": "types.Provisioning", "Tags": "[]types.Tag"},
			"create-service-template-version":             {"ClientToken": "*string", "CompatibleEnvironmentTemplates": "[]types.CompatibleEnvironmentTemplateInput", "Description": "*string", "MajorVersion": "*string", "Source": "types.TemplateVersionSourceInput", "SupportedComponentSources": "[]types.ServiceTemplateSupportedComponentSourceType", "Tags": "[]types.Tag", "TemplateName": "*string"},
			"create-template-sync-config":                 {"Branch": "*string", "RepositoryName": "*string", "RepositoryProvider": "types.RepositoryProvider", "Subdirectory": "*string", "TemplateName": "*string", "TemplateType": "types.TemplateType"},
			"delete-component":                            {"Name": "*string"},
			"delete-deployment":                           {"Id": "*string"},
			"delete-environment":                          {"Name": "*string"},
			"delete-environment-account-connection":       {"Id": "*string"},
			"delete-environment-template":                 {"Name": "*string"},
			"delete-environment-template-version":         {"MajorVersion": "*string", "MinorVersion": "*string", "TemplateName": "*string"},
			"delete-repository":                           {"Name": "*string", "Provider": "types.RepositoryProvider"},
			"delete-service":                              {"Name": "*string"},
			"delete-service-sync-config":                  {"ServiceName": "*string"},
			"delete-service-template":                     {"Name": "*string"},
			"delete-service-template-version":             {"MajorVersion": "*string", "MinorVersion": "*string", "TemplateName": "*string"},
			"delete-template-sync-config":                 {"TemplateName": "*string", "TemplateType": "types.TemplateType"},
			"get-account-settings":                        {},
			"get-component":                               {"Name": "*string"},
			"get-deployment":                              {"ComponentName": "*string", "EnvironmentName": "*string", "Id": "*string", "ServiceInstanceName": "*string", "ServiceName": "*string"},
			"get-environment":                             {"Name": "*string"},
			"get-environment-account-connection":          {"Id": "*string"},
			"get-environment-template":                    {"Name": "*string"},
			"get-environment-template-version":            {"MajorVersion": "*string", "MinorVersion": "*string", "TemplateName": "*string"},
			"get-repository":                              {"Name": "*string", "Provider": "types.RepositoryProvider"},
			"get-repository-sync-status":                  {"Branch": "*string", "RepositoryName": "*string", "RepositoryProvider": "types.RepositoryProvider", "SyncType": "types.SyncType"},
			"get-resources-summary":                       {},
			"get-service":                                 {"Name": "*string"},
			"get-service-instance":                        {"Name": "*string", "ServiceName": "*string"},
			"get-service-instance-sync-status":            {"ServiceInstanceName": "*string", "ServiceName": "*string"},
			"get-service-sync-blocker-summary":            {"ServiceInstanceName": "*string", "ServiceName": "*string"},
			"get-service-sync-config":                     {"ServiceName": "*string"},
			"get-service-template":                        {"Name": "*string"},
			"get-service-template-version":                {"MajorVersion": "*string", "MinorVersion": "*string", "TemplateName": "*string"},
			"get-template-sync-config":                    {"TemplateName": "*string", "TemplateType": "types.TemplateType"},
			"get-template-sync-status":                    {"TemplateName": "*string", "TemplateType": "types.TemplateType", "TemplateVersion": "*string"},
			"list-component-outputs":                      {"ComponentName": "*string", "DeploymentId": "*string", "NextToken": "*string"},
			"list-component-provisioned-resources":        {"ComponentName": "*string", "NextToken": "*string"},
			"list-components":                             {"EnvironmentName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ServiceInstanceName": "*string", "ServiceName": "*string"},
			"list-deployments":                            {"ComponentName": "*string", "EnvironmentName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ServiceInstanceName": "*string", "ServiceName": "*string"},
			"list-environment-account-connections":        {"EnvironmentName": "*string", "MaxResults": "*int32", "NextToken": "*string", "RequestedBy": "types.EnvironmentAccountConnectionRequesterAccountType", "Statuses": "[]types.EnvironmentAccountConnectionStatus"},
			"list-environment-outputs":                    {"DeploymentId": "*string", "EnvironmentName": "*string", "NextToken": "*string"},
			"list-environment-provisioned-resources":      {"EnvironmentName": "*string", "NextToken": "*string"},
			"list-environment-template-versions":          {"MajorVersion": "*string", "MaxResults": "*int32", "NextToken": "*string", "TemplateName": "*string"},
			"list-environment-templates":                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-environments":                           {"EnvironmentTemplates": "[]types.EnvironmentTemplateFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-repositories":                           {"MaxResults": "*int32", "NextToken": "*string"},
			"list-repository-sync-definitions":            {"NextToken": "*string", "RepositoryName": "*string", "RepositoryProvider": "types.RepositoryProvider", "SyncType": "types.SyncType"},
			"list-service-instance-outputs":               {"DeploymentId": "*string", "NextToken": "*string", "ServiceInstanceName": "*string", "ServiceName": "*string"},
			"list-service-instance-provisioned-resources": {"NextToken": "*string", "ServiceInstanceName": "*string", "ServiceName": "*string"},
			"list-service-instances":                      {"Filters": "[]types.ListServiceInstancesFilter", "MaxResults": "*int32", "NextToken": "*string", "ServiceName": "*string", "SortBy": "types.ListServiceInstancesSortBy", "SortOrder": "types.SortOrder"},
			"list-service-pipeline-outputs":               {"DeploymentId": "*string", "NextToken": "*string", "ServiceName": "*string"},
			"list-service-pipeline-provisioned-resources": {"NextToken": "*string", "ServiceName": "*string"},
			"list-service-template-versions":              {"MajorVersion": "*string", "MaxResults": "*int32", "NextToken": "*string", "TemplateName": "*string"},
			"list-service-templates":                      {"MaxResults": "*int32", "NextToken": "*string"},
			"list-services":                               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                      {"MaxResults": "*int32", "NextToken": "*string", "ResourceArn": "*string"},
			"notify-resource-deployment-status-change":    {"DeploymentId": "*string", "Outputs": "[]types.Output", "ResourceArn": "*string", "Status": "types.ResourceDeploymentStatus", "StatusMessage": "*string"},
			"reject-environment-account-connection":       {"Id": "*string"},
			"tag-resource":                                {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                              {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-account-settings":                     {"DeletePipelineProvisioningRepository": "*bool", "PipelineCodebuildRoleArn": "*string", "PipelineProvisioningRepository": "*types.RepositoryBranchInput", "PipelineServiceRoleArn": "*string"},
			"update-component":                            {"ClientToken": "*string", "DeploymentType": "types.ComponentDeploymentUpdateType", "Description": "*string", "Name": "*string", "ServiceInstanceName": "*string", "ServiceName": "*string", "ServiceSpec": "*string", "TemplateFile": "*string"},
			"update-environment":                          {"CodebuildRoleArn": "*string", "ComponentRoleArn": "*string", "DeploymentType": "types.DeploymentUpdateType", "Description": "*string", "EnvironmentAccountConnectionId": "*string", "Name": "*string", "ProtonServiceRoleArn": "*string", "ProvisioningRepository": "*types.RepositoryBranchInput", "Spec": "*string", "TemplateMajorVersion": "*string", "TemplateMinorVersion": "*string"},
			"update-environment-account-connection":       {"CodebuildRoleArn": "*string", "ComponentRoleArn": "*string", "Id": "*string", "RoleArn": "*string"},
			"update-environment-template":                 {"Description": "*string", "DisplayName": "*string", "Name": "*string"},
			"update-environment-template-version":         {"Description": "*string", "MajorVersion": "*string", "MinorVersion": "*string", "Status": "types.TemplateVersionStatus", "TemplateName": "*string"},
			"update-service":                              {"Description": "*string", "Name": "*string", "Spec": "*string"},
			"update-service-instance":                     {"ClientToken": "*string", "DeploymentType": "types.DeploymentUpdateType", "Name": "*string", "ServiceName": "*string", "Spec": "*string", "TemplateMajorVersion": "*string", "TemplateMinorVersion": "*string"},
			"update-service-pipeline":                     {"DeploymentType": "types.DeploymentUpdateType", "ServiceName": "*string", "Spec": "*string", "TemplateMajorVersion": "*string", "TemplateMinorVersion": "*string"},
			"update-service-sync-blocker":                 {"Id": "*string", "ResolvedReason": "*string"},
			"update-service-sync-config":                  {"Branch": "*string", "FilePath": "*string", "RepositoryName": "*string", "RepositoryProvider": "types.RepositoryProvider", "ServiceName": "*string"},
			"update-service-template":                     {"Description": "*string", "DisplayName": "*string", "Name": "*string"},
			"update-service-template-version":             {"CompatibleEnvironmentTemplates": "[]types.CompatibleEnvironmentTemplateInput", "Description": "*string", "MajorVersion": "*string", "MinorVersion": "*string", "Status": "types.TemplateVersionStatus", "SupportedComponentSources": "[]types.ServiceTemplateSupportedComponentSourceType", "TemplateName": "*string"},
			"update-template-sync-config":                 {"Branch": "*string", "RepositoryName": "*string", "RepositoryProvider": "types.RepositoryProvider", "Subdirectory": "*string", "TemplateName": "*string", "TemplateType": "types.TemplateType"},
		},
		OperationInputRequired: map[string][]string{
			"accept-environment-account-connection":       {"Id"},
			"cancel-component-deployment":                 {"ComponentName"},
			"cancel-environment-deployment":               {"EnvironmentName"},
			"cancel-service-instance-deployment":          {"ServiceInstanceName", "ServiceName"},
			"cancel-service-pipeline-deployment":          {"ServiceName"},
			"create-component":                            {"Manifest", "Name", "TemplateFile"},
			"create-environment":                          {"Name", "Spec", "TemplateMajorVersion", "TemplateName"},
			"create-environment-account-connection":       {"EnvironmentName", "ManagementAccountId"},
			"create-environment-template":                 {"Name"},
			"create-environment-template-version":         {"Source", "TemplateName"},
			"create-repository":                           {"ConnectionArn", "Name", "Provider"},
			"create-service":                              {"Name", "Spec", "TemplateMajorVersion", "TemplateName"},
			"create-service-instance":                     {"Name", "ServiceName", "Spec"},
			"create-service-sync-config":                  {"Branch", "FilePath", "RepositoryName", "RepositoryProvider", "ServiceName"},
			"create-service-template":                     {"Name"},
			"create-service-template-version":             {"CompatibleEnvironmentTemplates", "Source", "TemplateName"},
			"create-template-sync-config":                 {"Branch", "RepositoryName", "RepositoryProvider", "TemplateName", "TemplateType"},
			"delete-component":                            {"Name"},
			"delete-deployment":                           {"Id"},
			"delete-environment":                          {"Name"},
			"delete-environment-account-connection":       {"Id"},
			"delete-environment-template":                 {"Name"},
			"delete-environment-template-version":         {"MajorVersion", "MinorVersion", "TemplateName"},
			"delete-repository":                           {"Name", "Provider"},
			"delete-service":                              {"Name"},
			"delete-service-sync-config":                  {"ServiceName"},
			"delete-service-template":                     {"Name"},
			"delete-service-template-version":             {"MajorVersion", "MinorVersion", "TemplateName"},
			"delete-template-sync-config":                 {"TemplateName", "TemplateType"},
			"get-account-settings":                        {},
			"get-component":                               {"Name"},
			"get-deployment":                              {"Id"},
			"get-environment":                             {"Name"},
			"get-environment-account-connection":          {"Id"},
			"get-environment-template":                    {"Name"},
			"get-environment-template-version":            {"MajorVersion", "MinorVersion", "TemplateName"},
			"get-repository":                              {"Name", "Provider"},
			"get-repository-sync-status":                  {"Branch", "RepositoryName", "RepositoryProvider", "SyncType"},
			"get-resources-summary":                       {},
			"get-service":                                 {"Name"},
			"get-service-instance":                        {"Name", "ServiceName"},
			"get-service-instance-sync-status":            {"ServiceInstanceName", "ServiceName"},
			"get-service-sync-blocker-summary":            {"ServiceName"},
			"get-service-sync-config":                     {"ServiceName"},
			"get-service-template":                        {"Name"},
			"get-service-template-version":                {"MajorVersion", "MinorVersion", "TemplateName"},
			"get-template-sync-config":                    {"TemplateName", "TemplateType"},
			"get-template-sync-status":                    {"TemplateName", "TemplateType", "TemplateVersion"},
			"list-component-outputs":                      {"ComponentName"},
			"list-component-provisioned-resources":        {"ComponentName"},
			"list-components":                             {},
			"list-deployments":                            {},
			"list-environment-account-connections":        {"RequestedBy"},
			"list-environment-outputs":                    {"EnvironmentName"},
			"list-environment-provisioned-resources":      {"EnvironmentName"},
			"list-environment-template-versions":          {"TemplateName"},
			"list-environment-templates":                  {},
			"list-environments":                           {},
			"list-repositories":                           {},
			"list-repository-sync-definitions":            {"RepositoryName", "RepositoryProvider", "SyncType"},
			"list-service-instance-outputs":               {"ServiceInstanceName", "ServiceName"},
			"list-service-instance-provisioned-resources": {"ServiceInstanceName", "ServiceName"},
			"list-service-instances":                      {},
			"list-service-pipeline-outputs":               {"ServiceName"},
			"list-service-pipeline-provisioned-resources": {"ServiceName"},
			"list-service-template-versions":              {"TemplateName"},
			"list-service-templates":                      {},
			"list-services":                               {},
			"list-tags-for-resource":                      {"ResourceArn"},
			"notify-resource-deployment-status-change":    {"ResourceArn"},
			"reject-environment-account-connection":       {"Id"},
			"tag-resource":                                {"ResourceArn", "Tags"},
			"untag-resource":                              {"ResourceArn", "TagKeys"},
			"update-account-settings":                     {},
			"update-component":                            {"DeploymentType", "Name"},
			"update-environment":                          {"DeploymentType", "Name"},
			"update-environment-account-connection":       {"Id"},
			"update-environment-template":                 {"Name"},
			"update-environment-template-version":         {"MajorVersion", "MinorVersion", "TemplateName"},
			"update-service":                              {"Name"},
			"update-service-instance":                     {"DeploymentType", "Name", "ServiceName"},
			"update-service-pipeline":                     {"DeploymentType", "ServiceName", "Spec"},
			"update-service-sync-blocker":                 {"Id", "ResolvedReason"},
			"update-service-sync-config":                  {"Branch", "FilePath", "RepositoryName", "RepositoryProvider", "ServiceName"},
			"update-service-template":                     {"Name"},
			"update-service-template-version":             {"MajorVersion", "MinorVersion", "TemplateName"},
			"update-template-sync-config":                 {"Branch", "RepositoryName", "RepositoryProvider", "TemplateName", "TemplateType"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("proton", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
