package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/s3tables/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-namespace", "create-table", "create-table-bucket", "delete-namespace", "delete-table", "delete-table-bucket", "delete-table-bucket-encryption", "delete-table-bucket-metrics-configuration", "delete-table-bucket-policy", "delete-table-bucket-replication", "delete-table-policy", "delete-table-replication", "get-namespace", "get-table", "get-table-bucket", "get-table-bucket-encryption", "get-table-bucket-maintenance-configuration", "get-table-bucket-metrics-configuration", "get-table-bucket-policy", "get-table-bucket-replication", "get-table-bucket-storage-class", "get-table-encryption", "get-table-maintenance-configuration", "get-table-maintenance-job-status", "get-table-metadata-location", "get-table-policy", "get-table-record-expiration-configuration", "get-table-record-expiration-job-status", "get-table-replication", "get-table-replication-status", "get-table-storage-class", "list-namespaces", "list-table-buckets", "list-tables", "list-tags-for-resource", "put-table-bucket-encryption", "put-table-bucket-maintenance-configuration", "put-table-bucket-metrics-configuration", "put-table-bucket-policy", "put-table-bucket-replication", "put-table-bucket-storage-class", "put-table-maintenance-configuration", "put-table-policy", "put-table-record-expiration-configuration", "put-table-replication", "rename-table", "tag-resource", "untag-resource", "update-table-metadata-location"},
		OperationSet: map[string]bool{"create-namespace": true, "create-table": true, "create-table-bucket": true, "delete-namespace": true, "delete-table": true, "delete-table-bucket": true, "delete-table-bucket-encryption": true, "delete-table-bucket-metrics-configuration": true, "delete-table-bucket-policy": true, "delete-table-bucket-replication": true, "delete-table-policy": true, "delete-table-replication": true, "get-namespace": true, "get-table": true, "get-table-bucket": true, "get-table-bucket-encryption": true, "get-table-bucket-maintenance-configuration": true, "get-table-bucket-metrics-configuration": true, "get-table-bucket-policy": true, "get-table-bucket-replication": true, "get-table-bucket-storage-class": true, "get-table-encryption": true, "get-table-maintenance-configuration": true, "get-table-maintenance-job-status": true, "get-table-metadata-location": true, "get-table-policy": true, "get-table-record-expiration-configuration": true, "get-table-record-expiration-job-status": true, "get-table-replication": true, "get-table-replication-status": true, "get-table-storage-class": true, "list-namespaces": true, "list-table-buckets": true, "list-tables": true, "list-tags-for-resource": true, "put-table-bucket-encryption": true, "put-table-bucket-maintenance-configuration": true, "put-table-bucket-metrics-configuration": true, "put-table-bucket-policy": true, "put-table-bucket-replication": true, "put-table-bucket-storage-class": true, "put-table-maintenance-configuration": true, "put-table-policy": true, "put-table-record-expiration-configuration": true, "put-table-replication": true, "rename-table": true, "tag-resource": true, "untag-resource": true, "update-table-metadata-location": true},
		OperationInputs: map[string][]string{
			"create-namespace":                           {"Namespace", "TableBucketARN"},
			"create-table":                               {"EncryptionConfiguration", "Format", "Metadata", "Name", "Namespace", "StorageClassConfiguration", "TableBucketARN", "Tags"},
			"create-table-bucket":                        {"EncryptionConfiguration", "Name", "StorageClassConfiguration", "Tags"},
			"delete-namespace":                           {"Namespace", "TableBucketARN"},
			"delete-table":                               {"Name", "Namespace", "TableBucketARN", "VersionToken"},
			"delete-table-bucket":                        {"TableBucketARN"},
			"delete-table-bucket-encryption":             {"TableBucketARN"},
			"delete-table-bucket-metrics-configuration":  {"TableBucketARN"},
			"delete-table-bucket-policy":                 {"TableBucketARN"},
			"delete-table-bucket-replication":            {"TableBucketARN", "VersionToken"},
			"delete-table-policy":                        {"Name", "Namespace", "TableBucketARN"},
			"delete-table-replication":                   {"TableArn", "VersionToken"},
			"get-namespace":                              {"Namespace", "TableBucketARN"},
			"get-table":                                  {"Name", "Namespace", "TableArn", "TableBucketARN"},
			"get-table-bucket":                           {"TableBucketARN"},
			"get-table-bucket-encryption":                {"TableBucketARN"},
			"get-table-bucket-maintenance-configuration": {"TableBucketARN"},
			"get-table-bucket-metrics-configuration":     {"TableBucketARN"},
			"get-table-bucket-policy":                    {"TableBucketARN"},
			"get-table-bucket-replication":               {"TableBucketARN"},
			"get-table-bucket-storage-class":             {"TableBucketARN"},
			"get-table-encryption":                       {"Name", "Namespace", "TableBucketARN"},
			"get-table-maintenance-configuration":        {"Name", "Namespace", "TableBucketARN"},
			"get-table-maintenance-job-status":           {"Name", "Namespace", "TableBucketARN"},
			"get-table-metadata-location":                {"Name", "Namespace", "TableBucketARN"},
			"get-table-policy":                           {"Name", "Namespace", "TableBucketARN"},
			"get-table-record-expiration-configuration":  {"TableArn"},
			"get-table-record-expiration-job-status":     {"TableArn"},
			"get-table-replication":                      {"TableArn"},
			"get-table-replication-status":               {"TableArn"},
			"get-table-storage-class":                    {"Name", "Namespace", "TableBucketARN"},
			"list-namespaces":                            {"ContinuationToken", "MaxNamespaces", "Prefix", "TableBucketARN"},
			"list-table-buckets":                         {"ContinuationToken", "MaxBuckets", "Prefix", "Type"},
			"list-tables":                                {"ContinuationToken", "MaxTables", "Namespace", "Prefix", "TableBucketARN"},
			"list-tags-for-resource":                     {"ResourceArn"},
			"put-table-bucket-encryption":                {"EncryptionConfiguration", "TableBucketARN"},
			"put-table-bucket-maintenance-configuration": {"TableBucketARN", "Type", "Value"},
			"put-table-bucket-metrics-configuration":     {"TableBucketARN"},
			"put-table-bucket-policy":                    {"ResourcePolicy", "TableBucketARN"},
			"put-table-bucket-replication":               {"Configuration", "TableBucketARN", "VersionToken"},
			"put-table-bucket-storage-class":             {"StorageClassConfiguration", "TableBucketARN"},
			"put-table-maintenance-configuration":        {"Name", "Namespace", "TableBucketARN", "Type", "Value"},
			"put-table-policy":                           {"Name", "Namespace", "ResourcePolicy", "TableBucketARN"},
			"put-table-record-expiration-configuration":  {"TableArn", "Value"},
			"put-table-replication":                      {"Configuration", "TableArn", "VersionToken"},
			"rename-table":                               {"Name", "Namespace", "NewName", "NewNamespaceName", "TableBucketARN", "VersionToken"},
			"tag-resource":                               {"ResourceArn", "Tags"},
			"untag-resource":                             {"ResourceArn", "TagKeys"},
			"update-table-metadata-location":             {"MetadataLocation", "Name", "Namespace", "TableBucketARN", "VersionToken"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-namespace":                           {"Namespace": "[]string", "TableBucketARN": "*string"},
			"create-table":                               {"EncryptionConfiguration": "*types.EncryptionConfiguration", "Format": "types.OpenTableFormat", "Metadata": "types.TableMetadata", "Name": "*string", "Namespace": "*string", "StorageClassConfiguration": "*types.StorageClassConfiguration", "TableBucketARN": "*string", "Tags": "map[string]string"},
			"create-table-bucket":                        {"EncryptionConfiguration": "*types.EncryptionConfiguration", "Name": "*string", "StorageClassConfiguration": "*types.StorageClassConfiguration", "Tags": "map[string]string"},
			"delete-namespace":                           {"Namespace": "*string", "TableBucketARN": "*string"},
			"delete-table":                               {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string", "VersionToken": "*string"},
			"delete-table-bucket":                        {"TableBucketARN": "*string"},
			"delete-table-bucket-encryption":             {"TableBucketARN": "*string"},
			"delete-table-bucket-metrics-configuration":  {"TableBucketARN": "*string"},
			"delete-table-bucket-policy":                 {"TableBucketARN": "*string"},
			"delete-table-bucket-replication":            {"TableBucketARN": "*string", "VersionToken": "*string"},
			"delete-table-policy":                        {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string"},
			"delete-table-replication":                   {"TableArn": "*string", "VersionToken": "*string"},
			"get-namespace":                              {"Namespace": "*string", "TableBucketARN": "*string"},
			"get-table":                                  {"Name": "*string", "Namespace": "*string", "TableArn": "*string", "TableBucketARN": "*string"},
			"get-table-bucket":                           {"TableBucketARN": "*string"},
			"get-table-bucket-encryption":                {"TableBucketARN": "*string"},
			"get-table-bucket-maintenance-configuration": {"TableBucketARN": "*string"},
			"get-table-bucket-metrics-configuration":     {"TableBucketARN": "*string"},
			"get-table-bucket-policy":                    {"TableBucketARN": "*string"},
			"get-table-bucket-replication":               {"TableBucketARN": "*string"},
			"get-table-bucket-storage-class":             {"TableBucketARN": "*string"},
			"get-table-encryption":                       {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string"},
			"get-table-maintenance-configuration":        {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string"},
			"get-table-maintenance-job-status":           {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string"},
			"get-table-metadata-location":                {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string"},
			"get-table-policy":                           {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string"},
			"get-table-record-expiration-configuration":  {"TableArn": "*string"},
			"get-table-record-expiration-job-status":     {"TableArn": "*string"},
			"get-table-replication":                      {"TableArn": "*string"},
			"get-table-replication-status":               {"TableArn": "*string"},
			"get-table-storage-class":                    {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string"},
			"list-namespaces":                            {"ContinuationToken": "*string", "MaxNamespaces": "*int32", "Prefix": "*string", "TableBucketARN": "*string"},
			"list-table-buckets":                         {"ContinuationToken": "*string", "MaxBuckets": "*int32", "Prefix": "*string", "Type": "types.TableBucketType"},
			"list-tables":                                {"ContinuationToken": "*string", "MaxTables": "*int32", "Namespace": "*string", "Prefix": "*string", "TableBucketARN": "*string"},
			"list-tags-for-resource":                     {"ResourceArn": "*string"},
			"put-table-bucket-encryption":                {"EncryptionConfiguration": "*types.EncryptionConfiguration", "TableBucketARN": "*string"},
			"put-table-bucket-maintenance-configuration": {"TableBucketARN": "*string", "Type": "types.TableBucketMaintenanceType", "Value": "*types.TableBucketMaintenanceConfigurationValue"},
			"put-table-bucket-metrics-configuration":     {"TableBucketARN": "*string"},
			"put-table-bucket-policy":                    {"ResourcePolicy": "*string", "TableBucketARN": "*string"},
			"put-table-bucket-replication":               {"Configuration": "*types.TableBucketReplicationConfiguration", "TableBucketARN": "*string", "VersionToken": "*string"},
			"put-table-bucket-storage-class":             {"StorageClassConfiguration": "*types.StorageClassConfiguration", "TableBucketARN": "*string"},
			"put-table-maintenance-configuration":        {"Name": "*string", "Namespace": "*string", "TableBucketARN": "*string", "Type": "types.TableMaintenanceType", "Value": "*types.TableMaintenanceConfigurationValue"},
			"put-table-policy":                           {"Name": "*string", "Namespace": "*string", "ResourcePolicy": "*string", "TableBucketARN": "*string"},
			"put-table-record-expiration-configuration":  {"TableArn": "*string", "Value": "*types.TableRecordExpirationConfigurationValue"},
			"put-table-replication":                      {"Configuration": "*types.TableReplicationConfiguration", "TableArn": "*string", "VersionToken": "*string"},
			"rename-table":                               {"Name": "*string", "Namespace": "*string", "NewName": "*string", "NewNamespaceName": "*string", "TableBucketARN": "*string", "VersionToken": "*string"},
			"tag-resource":                               {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                             {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-table-metadata-location":             {"MetadataLocation": "*string", "Name": "*string", "Namespace": "*string", "TableBucketARN": "*string", "VersionToken": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-namespace":                           {"Namespace", "TableBucketARN"},
			"create-table":                               {"Format", "Name", "Namespace", "TableBucketARN"},
			"create-table-bucket":                        {"Name"},
			"delete-namespace":                           {"Namespace", "TableBucketARN"},
			"delete-table":                               {"Name", "Namespace", "TableBucketARN"},
			"delete-table-bucket":                        {"TableBucketARN"},
			"delete-table-bucket-encryption":             {"TableBucketARN"},
			"delete-table-bucket-metrics-configuration":  {"TableBucketARN"},
			"delete-table-bucket-policy":                 {"TableBucketARN"},
			"delete-table-bucket-replication":            {"TableBucketARN"},
			"delete-table-policy":                        {"Name", "Namespace", "TableBucketARN"},
			"delete-table-replication":                   {"TableArn", "VersionToken"},
			"get-namespace":                              {"Namespace", "TableBucketARN"},
			"get-table":                                  {},
			"get-table-bucket":                           {"TableBucketARN"},
			"get-table-bucket-encryption":                {"TableBucketARN"},
			"get-table-bucket-maintenance-configuration": {"TableBucketARN"},
			"get-table-bucket-metrics-configuration":     {"TableBucketARN"},
			"get-table-bucket-policy":                    {"TableBucketARN"},
			"get-table-bucket-replication":               {"TableBucketARN"},
			"get-table-bucket-storage-class":             {"TableBucketARN"},
			"get-table-encryption":                       {"Name", "Namespace", "TableBucketARN"},
			"get-table-maintenance-configuration":        {"Name", "Namespace", "TableBucketARN"},
			"get-table-maintenance-job-status":           {"Name", "Namespace", "TableBucketARN"},
			"get-table-metadata-location":                {"Name", "Namespace", "TableBucketARN"},
			"get-table-policy":                           {"Name", "Namespace", "TableBucketARN"},
			"get-table-record-expiration-configuration":  {"TableArn"},
			"get-table-record-expiration-job-status":     {"TableArn"},
			"get-table-replication":                      {"TableArn"},
			"get-table-replication-status":               {"TableArn"},
			"get-table-storage-class":                    {"Name", "Namespace", "TableBucketARN"},
			"list-namespaces":                            {"TableBucketARN"},
			"list-table-buckets":                         {},
			"list-tables":                                {"TableBucketARN"},
			"list-tags-for-resource":                     {"ResourceArn"},
			"put-table-bucket-encryption":                {"EncryptionConfiguration", "TableBucketARN"},
			"put-table-bucket-maintenance-configuration": {"TableBucketARN", "Type", "Value"},
			"put-table-bucket-metrics-configuration":     {"TableBucketARN"},
			"put-table-bucket-policy":                    {"ResourcePolicy", "TableBucketARN"},
			"put-table-bucket-replication":               {"Configuration", "TableBucketARN"},
			"put-table-bucket-storage-class":             {"StorageClassConfiguration", "TableBucketARN"},
			"put-table-maintenance-configuration":        {"Name", "Namespace", "TableBucketARN", "Type", "Value"},
			"put-table-policy":                           {"Name", "Namespace", "ResourcePolicy", "TableBucketARN"},
			"put-table-record-expiration-configuration":  {"TableArn", "Value"},
			"put-table-replication":                      {"Configuration", "TableArn"},
			"rename-table":                               {"Name", "Namespace", "TableBucketARN"},
			"tag-resource":                               {"ResourceArn", "Tags"},
			"untag-resource":                             {"ResourceArn", "TagKeys"},
			"update-table-metadata-location":             {"MetadataLocation", "Name", "Namespace", "TableBucketARN", "VersionToken"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("s3tables", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
