package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/clouddirectory/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-facet-to-object", "apply-schema", "attach-object", "attach-policy", "attach-to-index", "attach-typed-link", "batch-read", "batch-write", "create-directory", "create-facet", "create-index", "create-object", "create-schema", "create-typed-link-facet", "delete-directory", "delete-facet", "delete-object", "delete-schema", "delete-typed-link-facet", "detach-from-index", "detach-object", "detach-policy", "detach-typed-link", "disable-directory", "enable-directory", "get-applied-schema-version", "get-directory", "get-facet", "get-link-attributes", "get-object-attributes", "get-object-information", "get-schema-as-json", "get-typed-link-facet-information", "list-applied-schema-arns", "list-attached-indices", "list-development-schema-arns", "list-directories", "list-facet-attributes", "list-facet-names", "list-incoming-typed-links", "list-index", "list-managed-schema-arns", "list-object-attributes", "list-object-children", "list-object-parent-paths", "list-object-parents", "list-object-policies", "list-outgoing-typed-links", "list-policy-attachments", "list-published-schema-arns", "list-tags-for-resource", "list-typed-link-facet-attributes", "list-typed-link-facet-names", "lookup-policy", "publish-schema", "put-schema-from-json", "remove-facet-from-object", "tag-resource", "untag-resource", "update-facet", "update-link-attributes", "update-object-attributes", "update-schema", "update-typed-link-facet", "upgrade-applied-schema", "upgrade-published-schema"},
		OperationSet: map[string]bool{"add-facet-to-object": true, "apply-schema": true, "attach-object": true, "attach-policy": true, "attach-to-index": true, "attach-typed-link": true, "batch-read": true, "batch-write": true, "create-directory": true, "create-facet": true, "create-index": true, "create-object": true, "create-schema": true, "create-typed-link-facet": true, "delete-directory": true, "delete-facet": true, "delete-object": true, "delete-schema": true, "delete-typed-link-facet": true, "detach-from-index": true, "detach-object": true, "detach-policy": true, "detach-typed-link": true, "disable-directory": true, "enable-directory": true, "get-applied-schema-version": true, "get-directory": true, "get-facet": true, "get-link-attributes": true, "get-object-attributes": true, "get-object-information": true, "get-schema-as-json": true, "get-typed-link-facet-information": true, "list-applied-schema-arns": true, "list-attached-indices": true, "list-development-schema-arns": true, "list-directories": true, "list-facet-attributes": true, "list-facet-names": true, "list-incoming-typed-links": true, "list-index": true, "list-managed-schema-arns": true, "list-object-attributes": true, "list-object-children": true, "list-object-parent-paths": true, "list-object-parents": true, "list-object-policies": true, "list-outgoing-typed-links": true, "list-policy-attachments": true, "list-published-schema-arns": true, "list-tags-for-resource": true, "list-typed-link-facet-attributes": true, "list-typed-link-facet-names": true, "lookup-policy": true, "publish-schema": true, "put-schema-from-json": true, "remove-facet-from-object": true, "tag-resource": true, "untag-resource": true, "update-facet": true, "update-link-attributes": true, "update-object-attributes": true, "update-schema": true, "update-typed-link-facet": true, "upgrade-applied-schema": true, "upgrade-published-schema": true},
		OperationInputs: map[string][]string{
			"add-facet-to-object":              {"DirectoryArn", "ObjectAttributeList", "ObjectReference", "SchemaFacet"},
			"apply-schema":                     {"DirectoryArn", "PublishedSchemaArn"},
			"attach-object":                    {"ChildReference", "DirectoryArn", "LinkName", "ParentReference"},
			"attach-policy":                    {"DirectoryArn", "ObjectReference", "PolicyReference"},
			"attach-to-index":                  {"DirectoryArn", "IndexReference", "TargetReference"},
			"attach-typed-link":                {"Attributes", "DirectoryArn", "SourceObjectReference", "TargetObjectReference", "TypedLinkFacet"},
			"batch-read":                       {"ConsistencyLevel", "DirectoryArn", "Operations"},
			"batch-write":                      {"DirectoryArn", "Operations"},
			"create-directory":                 {"Name", "SchemaArn"},
			"create-facet":                     {"Attributes", "FacetStyle", "Name", "ObjectType", "SchemaArn"},
			"create-index":                     {"DirectoryArn", "IsUnique", "LinkName", "OrderedIndexedAttributeList", "ParentReference"},
			"create-object":                    {"DirectoryArn", "LinkName", "ObjectAttributeList", "ParentReference", "SchemaFacets"},
			"create-schema":                    {"Name"},
			"create-typed-link-facet":          {"Facet", "SchemaArn"},
			"delete-directory":                 {"DirectoryArn"},
			"delete-facet":                     {"Name", "SchemaArn"},
			"delete-object":                    {"DirectoryArn", "ObjectReference"},
			"delete-schema":                    {"SchemaArn"},
			"delete-typed-link-facet":          {"Name", "SchemaArn"},
			"detach-from-index":                {"DirectoryArn", "IndexReference", "TargetReference"},
			"detach-object":                    {"DirectoryArn", "LinkName", "ParentReference"},
			"detach-policy":                    {"DirectoryArn", "ObjectReference", "PolicyReference"},
			"detach-typed-link":                {"DirectoryArn", "TypedLinkSpecifier"},
			"disable-directory":                {"DirectoryArn"},
			"enable-directory":                 {"DirectoryArn"},
			"get-applied-schema-version":       {"SchemaArn"},
			"get-directory":                    {"DirectoryArn"},
			"get-facet":                        {"Name", "SchemaArn"},
			"get-link-attributes":              {"AttributeNames", "ConsistencyLevel", "DirectoryArn", "TypedLinkSpecifier"},
			"get-object-attributes":            {"AttributeNames", "ConsistencyLevel", "DirectoryArn", "ObjectReference", "SchemaFacet"},
			"get-object-information":           {"ConsistencyLevel", "DirectoryArn", "ObjectReference"},
			"get-schema-as-json":               {"SchemaArn"},
			"get-typed-link-facet-information": {"Name", "SchemaArn"},
			"list-applied-schema-arns":         {"DirectoryArn", "MaxResults", "NextToken", "SchemaArn"},
			"list-attached-indices":            {"ConsistencyLevel", "DirectoryArn", "MaxResults", "NextToken", "TargetReference"},
			"list-development-schema-arns":     {"MaxResults", "NextToken"},
			"list-directories":                 {"MaxResults", "NextToken", "State"},
			"list-facet-attributes":            {"MaxResults", "Name", "NextToken", "SchemaArn"},
			"list-facet-names":                 {"MaxResults", "NextToken", "SchemaArn"},
			"list-incoming-typed-links":        {"ConsistencyLevel", "DirectoryArn", "FilterAttributeRanges", "FilterTypedLink", "MaxResults", "NextToken", "ObjectReference"},
			"list-index":                       {"ConsistencyLevel", "DirectoryArn", "IndexReference", "MaxResults", "NextToken", "RangesOnIndexedValues"},
			"list-managed-schema-arns":         {"MaxResults", "NextToken", "SchemaArn"},
			"list-object-attributes":           {"ConsistencyLevel", "DirectoryArn", "FacetFilter", "MaxResults", "NextToken", "ObjectReference"},
			"list-object-children":             {"ConsistencyLevel", "DirectoryArn", "MaxResults", "NextToken", "ObjectReference"},
			"list-object-parent-paths":         {"DirectoryArn", "MaxResults", "NextToken", "ObjectReference"},
			"list-object-parents":              {"ConsistencyLevel", "DirectoryArn", "IncludeAllLinksToEachParent", "MaxResults", "NextToken", "ObjectReference"},
			"list-object-policies":             {"ConsistencyLevel", "DirectoryArn", "MaxResults", "NextToken", "ObjectReference"},
			"list-outgoing-typed-links":        {"ConsistencyLevel", "DirectoryArn", "FilterAttributeRanges", "FilterTypedLink", "MaxResults", "NextToken", "ObjectReference"},
			"list-policy-attachments":          {"ConsistencyLevel", "DirectoryArn", "MaxResults", "NextToken", "PolicyReference"},
			"list-published-schema-arns":       {"MaxResults", "NextToken", "SchemaArn"},
			"list-tags-for-resource":           {"MaxResults", "NextToken", "ResourceArn"},
			"list-typed-link-facet-attributes": {"MaxResults", "Name", "NextToken", "SchemaArn"},
			"list-typed-link-facet-names":      {"MaxResults", "NextToken", "SchemaArn"},
			"lookup-policy":                    {"DirectoryArn", "MaxResults", "NextToken", "ObjectReference"},
			"publish-schema":                   {"DevelopmentSchemaArn", "MinorVersion", "Name", "Version"},
			"put-schema-from-json":             {"Document", "SchemaArn"},
			"remove-facet-from-object":         {"DirectoryArn", "ObjectReference", "SchemaFacet"},
			"tag-resource":                     {"ResourceArn", "Tags"},
			"untag-resource":                   {"ResourceArn", "TagKeys"},
			"update-facet":                     {"AttributeUpdates", "Name", "ObjectType", "SchemaArn"},
			"update-link-attributes":           {"AttributeUpdates", "DirectoryArn", "TypedLinkSpecifier"},
			"update-object-attributes":         {"AttributeUpdates", "DirectoryArn", "ObjectReference"},
			"update-schema":                    {"Name", "SchemaArn"},
			"update-typed-link-facet":          {"AttributeUpdates", "IdentityAttributeOrder", "Name", "SchemaArn"},
			"upgrade-applied-schema":           {"DirectoryArn", "DryRun", "PublishedSchemaArn"},
			"upgrade-published-schema":         {"DevelopmentSchemaArn", "DryRun", "MinorVersion", "PublishedSchemaArn"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-facet-to-object":              {"DirectoryArn": "*string", "ObjectAttributeList": "[]types.AttributeKeyAndValue", "ObjectReference": "*types.ObjectReference", "SchemaFacet": "*types.SchemaFacet"},
			"apply-schema":                     {"DirectoryArn": "*string", "PublishedSchemaArn": "*string"},
			"attach-object":                    {"ChildReference": "*types.ObjectReference", "DirectoryArn": "*string", "LinkName": "*string", "ParentReference": "*types.ObjectReference"},
			"attach-policy":                    {"DirectoryArn": "*string", "ObjectReference": "*types.ObjectReference", "PolicyReference": "*types.ObjectReference"},
			"attach-to-index":                  {"DirectoryArn": "*string", "IndexReference": "*types.ObjectReference", "TargetReference": "*types.ObjectReference"},
			"attach-typed-link":                {"Attributes": "[]types.AttributeNameAndValue", "DirectoryArn": "*string", "SourceObjectReference": "*types.ObjectReference", "TargetObjectReference": "*types.ObjectReference", "TypedLinkFacet": "*types.TypedLinkSchemaAndFacetName"},
			"batch-read":                       {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "Operations": "[]types.BatchReadOperation"},
			"batch-write":                      {"DirectoryArn": "*string", "Operations": "[]types.BatchWriteOperation"},
			"create-directory":                 {"Name": "*string", "SchemaArn": "*string"},
			"create-facet":                     {"Attributes": "[]types.FacetAttribute", "FacetStyle": "types.FacetStyle", "Name": "*string", "ObjectType": "types.ObjectType", "SchemaArn": "*string"},
			"create-index":                     {"DirectoryArn": "*string", "IsUnique": "bool", "LinkName": "*string", "OrderedIndexedAttributeList": "[]types.AttributeKey", "ParentReference": "*types.ObjectReference"},
			"create-object":                    {"DirectoryArn": "*string", "LinkName": "*string", "ObjectAttributeList": "[]types.AttributeKeyAndValue", "ParentReference": "*types.ObjectReference", "SchemaFacets": "[]types.SchemaFacet"},
			"create-schema":                    {"Name": "*string"},
			"create-typed-link-facet":          {"Facet": "*types.TypedLinkFacet", "SchemaArn": "*string"},
			"delete-directory":                 {"DirectoryArn": "*string"},
			"delete-facet":                     {"Name": "*string", "SchemaArn": "*string"},
			"delete-object":                    {"DirectoryArn": "*string", "ObjectReference": "*types.ObjectReference"},
			"delete-schema":                    {"SchemaArn": "*string"},
			"delete-typed-link-facet":          {"Name": "*string", "SchemaArn": "*string"},
			"detach-from-index":                {"DirectoryArn": "*string", "IndexReference": "*types.ObjectReference", "TargetReference": "*types.ObjectReference"},
			"detach-object":                    {"DirectoryArn": "*string", "LinkName": "*string", "ParentReference": "*types.ObjectReference"},
			"detach-policy":                    {"DirectoryArn": "*string", "ObjectReference": "*types.ObjectReference", "PolicyReference": "*types.ObjectReference"},
			"detach-typed-link":                {"DirectoryArn": "*string", "TypedLinkSpecifier": "*types.TypedLinkSpecifier"},
			"disable-directory":                {"DirectoryArn": "*string"},
			"enable-directory":                 {"DirectoryArn": "*string"},
			"get-applied-schema-version":       {"SchemaArn": "*string"},
			"get-directory":                    {"DirectoryArn": "*string"},
			"get-facet":                        {"Name": "*string", "SchemaArn": "*string"},
			"get-link-attributes":              {"AttributeNames": "[]string", "ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "TypedLinkSpecifier": "*types.TypedLinkSpecifier"},
			"get-object-attributes":            {"AttributeNames": "[]string", "ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "ObjectReference": "*types.ObjectReference", "SchemaFacet": "*types.SchemaFacet"},
			"get-object-information":           {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "ObjectReference": "*types.ObjectReference"},
			"get-schema-as-json":               {"SchemaArn": "*string"},
			"get-typed-link-facet-information": {"Name": "*string", "SchemaArn": "*string"},
			"list-applied-schema-arns":         {"DirectoryArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "SchemaArn": "*string"},
			"list-attached-indices":            {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "TargetReference": "*types.ObjectReference"},
			"list-development-schema-arns":     {"MaxResults": "*int32", "NextToken": "*string"},
			"list-directories":                 {"MaxResults": "*int32", "NextToken": "*string", "State": "types.DirectoryState"},
			"list-facet-attributes":            {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string", "SchemaArn": "*string"},
			"list-facet-names":                 {"MaxResults": "*int32", "NextToken": "*string", "SchemaArn": "*string"},
			"list-incoming-typed-links":        {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "FilterAttributeRanges": "[]types.TypedLinkAttributeRange", "FilterTypedLink": "*types.TypedLinkSchemaAndFacetName", "MaxResults": "*int32", "NextToken": "*string", "ObjectReference": "*types.ObjectReference"},
			"list-index":                       {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "IndexReference": "*types.ObjectReference", "MaxResults": "*int32", "NextToken": "*string", "RangesOnIndexedValues": "[]types.ObjectAttributeRange"},
			"list-managed-schema-arns":         {"MaxResults": "*int32", "NextToken": "*string", "SchemaArn": "*string"},
			"list-object-attributes":           {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "FacetFilter": "*types.SchemaFacet", "MaxResults": "*int32", "NextToken": "*string", "ObjectReference": "*types.ObjectReference"},
			"list-object-children":             {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "ObjectReference": "*types.ObjectReference"},
			"list-object-parent-paths":         {"DirectoryArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "ObjectReference": "*types.ObjectReference"},
			"list-object-parents":              {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "IncludeAllLinksToEachParent": "bool", "MaxResults": "*int32", "NextToken": "*string", "ObjectReference": "*types.ObjectReference"},
			"list-object-policies":             {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "ObjectReference": "*types.ObjectReference"},
			"list-outgoing-typed-links":        {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "FilterAttributeRanges": "[]types.TypedLinkAttributeRange", "FilterTypedLink": "*types.TypedLinkSchemaAndFacetName", "MaxResults": "*int32", "NextToken": "*string", "ObjectReference": "*types.ObjectReference"},
			"list-policy-attachments":          {"ConsistencyLevel": "types.ConsistencyLevel", "DirectoryArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "PolicyReference": "*types.ObjectReference"},
			"list-published-schema-arns":       {"MaxResults": "*int32", "NextToken": "*string", "SchemaArn": "*string"},
			"list-tags-for-resource":           {"MaxResults": "*int32", "NextToken": "*string", "ResourceArn": "*string"},
			"list-typed-link-facet-attributes": {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string", "SchemaArn": "*string"},
			"list-typed-link-facet-names":      {"MaxResults": "*int32", "NextToken": "*string", "SchemaArn": "*string"},
			"lookup-policy":                    {"DirectoryArn": "*string", "MaxResults": "*int32", "NextToken": "*string", "ObjectReference": "*types.ObjectReference"},
			"publish-schema":                   {"DevelopmentSchemaArn": "*string", "MinorVersion": "*string", "Name": "*string", "Version": "*string"},
			"put-schema-from-json":             {"Document": "*string", "SchemaArn": "*string"},
			"remove-facet-from-object":         {"DirectoryArn": "*string", "ObjectReference": "*types.ObjectReference", "SchemaFacet": "*types.SchemaFacet"},
			"tag-resource":                     {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                   {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-facet":                     {"AttributeUpdates": "[]types.FacetAttributeUpdate", "Name": "*string", "ObjectType": "types.ObjectType", "SchemaArn": "*string"},
			"update-link-attributes":           {"AttributeUpdates": "[]types.LinkAttributeUpdate", "DirectoryArn": "*string", "TypedLinkSpecifier": "*types.TypedLinkSpecifier"},
			"update-object-attributes":         {"AttributeUpdates": "[]types.ObjectAttributeUpdate", "DirectoryArn": "*string", "ObjectReference": "*types.ObjectReference"},
			"update-schema":                    {"Name": "*string", "SchemaArn": "*string"},
			"update-typed-link-facet":          {"AttributeUpdates": "[]types.TypedLinkFacetAttributeUpdate", "IdentityAttributeOrder": "[]string", "Name": "*string", "SchemaArn": "*string"},
			"upgrade-applied-schema":           {"DirectoryArn": "*string", "DryRun": "bool", "PublishedSchemaArn": "*string"},
			"upgrade-published-schema":         {"DevelopmentSchemaArn": "*string", "DryRun": "bool", "MinorVersion": "*string", "PublishedSchemaArn": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"add-facet-to-object":              {"DirectoryArn", "ObjectReference", "SchemaFacet"},
			"apply-schema":                     {"DirectoryArn", "PublishedSchemaArn"},
			"attach-object":                    {"ChildReference", "DirectoryArn", "LinkName", "ParentReference"},
			"attach-policy":                    {"DirectoryArn", "ObjectReference", "PolicyReference"},
			"attach-to-index":                  {"DirectoryArn", "IndexReference", "TargetReference"},
			"attach-typed-link":                {"Attributes", "DirectoryArn", "SourceObjectReference", "TargetObjectReference", "TypedLinkFacet"},
			"batch-read":                       {"DirectoryArn", "Operations"},
			"batch-write":                      {"DirectoryArn", "Operations"},
			"create-directory":                 {"Name", "SchemaArn"},
			"create-facet":                     {"Name", "SchemaArn"},
			"create-index":                     {"DirectoryArn", "IsUnique", "OrderedIndexedAttributeList"},
			"create-object":                    {"DirectoryArn", "SchemaFacets"},
			"create-schema":                    {"Name"},
			"create-typed-link-facet":          {"Facet", "SchemaArn"},
			"delete-directory":                 {"DirectoryArn"},
			"delete-facet":                     {"Name", "SchemaArn"},
			"delete-object":                    {"DirectoryArn", "ObjectReference"},
			"delete-schema":                    {"SchemaArn"},
			"delete-typed-link-facet":          {"Name", "SchemaArn"},
			"detach-from-index":                {"DirectoryArn", "IndexReference", "TargetReference"},
			"detach-object":                    {"DirectoryArn", "LinkName", "ParentReference"},
			"detach-policy":                    {"DirectoryArn", "ObjectReference", "PolicyReference"},
			"detach-typed-link":                {"DirectoryArn", "TypedLinkSpecifier"},
			"disable-directory":                {"DirectoryArn"},
			"enable-directory":                 {"DirectoryArn"},
			"get-applied-schema-version":       {"SchemaArn"},
			"get-directory":                    {"DirectoryArn"},
			"get-facet":                        {"Name", "SchemaArn"},
			"get-link-attributes":              {"AttributeNames", "DirectoryArn", "TypedLinkSpecifier"},
			"get-object-attributes":            {"AttributeNames", "DirectoryArn", "ObjectReference", "SchemaFacet"},
			"get-object-information":           {"DirectoryArn", "ObjectReference"},
			"get-schema-as-json":               {"SchemaArn"},
			"get-typed-link-facet-information": {"Name", "SchemaArn"},
			"list-applied-schema-arns":         {"DirectoryArn"},
			"list-attached-indices":            {"DirectoryArn", "TargetReference"},
			"list-development-schema-arns":     {},
			"list-directories":                 {},
			"list-facet-attributes":            {"Name", "SchemaArn"},
			"list-facet-names":                 {"SchemaArn"},
			"list-incoming-typed-links":        {"DirectoryArn", "ObjectReference"},
			"list-index":                       {"DirectoryArn", "IndexReference"},
			"list-managed-schema-arns":         {},
			"list-object-attributes":           {"DirectoryArn", "ObjectReference"},
			"list-object-children":             {"DirectoryArn", "ObjectReference"},
			"list-object-parent-paths":         {"DirectoryArn", "ObjectReference"},
			"list-object-parents":              {"DirectoryArn", "ObjectReference"},
			"list-object-policies":             {"DirectoryArn", "ObjectReference"},
			"list-outgoing-typed-links":        {"DirectoryArn", "ObjectReference"},
			"list-policy-attachments":          {"DirectoryArn", "PolicyReference"},
			"list-published-schema-arns":       {},
			"list-tags-for-resource":           {"ResourceArn"},
			"list-typed-link-facet-attributes": {"Name", "SchemaArn"},
			"list-typed-link-facet-names":      {"SchemaArn"},
			"lookup-policy":                    {"DirectoryArn", "ObjectReference"},
			"publish-schema":                   {"DevelopmentSchemaArn", "Version"},
			"put-schema-from-json":             {"Document", "SchemaArn"},
			"remove-facet-from-object":         {"DirectoryArn", "ObjectReference", "SchemaFacet"},
			"tag-resource":                     {"ResourceArn", "Tags"},
			"untag-resource":                   {"ResourceArn", "TagKeys"},
			"update-facet":                     {"Name", "SchemaArn"},
			"update-link-attributes":           {"AttributeUpdates", "DirectoryArn", "TypedLinkSpecifier"},
			"update-object-attributes":         {"AttributeUpdates", "DirectoryArn", "ObjectReference"},
			"update-schema":                    {"Name", "SchemaArn"},
			"update-typed-link-facet":          {"AttributeUpdates", "IdentityAttributeOrder", "Name", "SchemaArn"},
			"upgrade-applied-schema":           {"DirectoryArn", "PublishedSchemaArn"},
			"upgrade-published-schema":         {"DevelopmentSchemaArn", "MinorVersion", "PublishedSchemaArn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("clouddirectory", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
