package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/networkfirewall/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-network-firewall-transit-gateway-attachment", "associate-availability-zones", "associate-firewall-policy", "associate-subnets", "attach-rule-groups-to-proxy-configuration", "create-firewall", "create-firewall-policy", "create-proxy", "create-proxy-configuration", "create-proxy-rule-group", "create-proxy-rules", "create-rule-group", "create-tls-inspection-configuration", "create-vpc-endpoint-association", "delete-firewall", "delete-firewall-policy", "delete-network-firewall-transit-gateway-attachment", "delete-proxy", "delete-proxy-configuration", "delete-proxy-rule-group", "delete-proxy-rules", "delete-resource-policy", "delete-rule-group", "delete-tls-inspection-configuration", "delete-vpc-endpoint-association", "describe-firewall", "describe-firewall-metadata", "describe-firewall-policy", "describe-flow-operation", "describe-logging-configuration", "describe-proxy", "describe-proxy-configuration", "describe-proxy-rule", "describe-proxy-rule-group", "describe-resource-policy", "describe-rule-group", "describe-rule-group-metadata", "describe-rule-group-summary", "describe-tls-inspection-configuration", "describe-vpc-endpoint-association", "detach-rule-groups-from-proxy-configuration", "disassociate-availability-zones", "disassociate-subnets", "get-analysis-report-results", "list-analysis-reports", "list-firewall-policies", "list-firewalls", "list-flow-operation-results", "list-flow-operations", "list-proxies", "list-proxy-configurations", "list-proxy-rule-groups", "list-rule-groups", "list-tags-for-resource", "list-tls-inspection-configurations", "list-vpc-endpoint-associations", "put-resource-policy", "reject-network-firewall-transit-gateway-attachment", "start-analysis-report", "start-flow-capture", "start-flow-flush", "tag-resource", "untag-resource", "update-availability-zone-change-protection", "update-firewall-analysis-settings", "update-firewall-delete-protection", "update-firewall-description", "update-firewall-encryption-configuration", "update-firewall-policy", "update-firewall-policy-change-protection", "update-logging-configuration", "update-proxy", "update-proxy-configuration", "update-proxy-rule", "update-proxy-rule-group-priorities", "update-proxy-rule-priorities", "update-rule-group", "update-subnet-change-protection", "update-tls-inspection-configuration"},
		OperationSet: map[string]bool{"accept-network-firewall-transit-gateway-attachment": true, "associate-availability-zones": true, "associate-firewall-policy": true, "associate-subnets": true, "attach-rule-groups-to-proxy-configuration": true, "create-firewall": true, "create-firewall-policy": true, "create-proxy": true, "create-proxy-configuration": true, "create-proxy-rule-group": true, "create-proxy-rules": true, "create-rule-group": true, "create-tls-inspection-configuration": true, "create-vpc-endpoint-association": true, "delete-firewall": true, "delete-firewall-policy": true, "delete-network-firewall-transit-gateway-attachment": true, "delete-proxy": true, "delete-proxy-configuration": true, "delete-proxy-rule-group": true, "delete-proxy-rules": true, "delete-resource-policy": true, "delete-rule-group": true, "delete-tls-inspection-configuration": true, "delete-vpc-endpoint-association": true, "describe-firewall": true, "describe-firewall-metadata": true, "describe-firewall-policy": true, "describe-flow-operation": true, "describe-logging-configuration": true, "describe-proxy": true, "describe-proxy-configuration": true, "describe-proxy-rule": true, "describe-proxy-rule-group": true, "describe-resource-policy": true, "describe-rule-group": true, "describe-rule-group-metadata": true, "describe-rule-group-summary": true, "describe-tls-inspection-configuration": true, "describe-vpc-endpoint-association": true, "detach-rule-groups-from-proxy-configuration": true, "disassociate-availability-zones": true, "disassociate-subnets": true, "get-analysis-report-results": true, "list-analysis-reports": true, "list-firewall-policies": true, "list-firewalls": true, "list-flow-operation-results": true, "list-flow-operations": true, "list-proxies": true, "list-proxy-configurations": true, "list-proxy-rule-groups": true, "list-rule-groups": true, "list-tags-for-resource": true, "list-tls-inspection-configurations": true, "list-vpc-endpoint-associations": true, "put-resource-policy": true, "reject-network-firewall-transit-gateway-attachment": true, "start-analysis-report": true, "start-flow-capture": true, "start-flow-flush": true, "tag-resource": true, "untag-resource": true, "update-availability-zone-change-protection": true, "update-firewall-analysis-settings": true, "update-firewall-delete-protection": true, "update-firewall-description": true, "update-firewall-encryption-configuration": true, "update-firewall-policy": true, "update-firewall-policy-change-protection": true, "update-logging-configuration": true, "update-proxy": true, "update-proxy-configuration": true, "update-proxy-rule": true, "update-proxy-rule-group-priorities": true, "update-proxy-rule-priorities": true, "update-rule-group": true, "update-subnet-change-protection": true, "update-tls-inspection-configuration": true},
		OperationInputs: map[string][]string{
			"accept-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId"},
			"associate-availability-zones":                       {"AvailabilityZoneMappings", "FirewallArn", "FirewallName", "UpdateToken"},
			"associate-firewall-policy":                          {"FirewallArn", "FirewallName", "FirewallPolicyArn", "UpdateToken"},
			"associate-subnets":                                  {"FirewallArn", "FirewallName", "SubnetMappings", "UpdateToken"},
			"attach-rule-groups-to-proxy-configuration":          {"ProxyConfigurationArn", "ProxyConfigurationName", "RuleGroups", "UpdateToken"},
			"create-firewall":                                    {"AvailabilityZoneChangeProtection", "AvailabilityZoneMappings", "DeleteProtection", "Description", "EnabledAnalysisTypes", "EncryptionConfiguration", "FirewallName", "FirewallPolicyArn", "FirewallPolicyChangeProtection", "SubnetChangeProtection", "SubnetMappings", "Tags", "TransitGatewayId", "VpcId"},
			"create-firewall-policy":                             {"Description", "DryRun", "EncryptionConfiguration", "FirewallPolicy", "FirewallPolicyName", "Tags"},
			"create-proxy":                                       {"ListenerProperties", "NatGatewayId", "ProxyConfigurationArn", "ProxyConfigurationName", "ProxyName", "Tags", "TlsInterceptProperties"},
			"create-proxy-configuration":                         {"DefaultRulePhaseActions", "Description", "ProxyConfigurationName", "RuleGroupArns", "RuleGroupNames", "Tags"},
			"create-proxy-rule-group":                            {"Description", "ProxyRuleGroupName", "Rules", "Tags"},
			"create-proxy-rules":                                 {"ProxyRuleGroupArn", "ProxyRuleGroupName", "Rules"},
			"create-rule-group":                                  {"AnalyzeRuleGroup", "Capacity", "Description", "DryRun", "EncryptionConfiguration", "RuleGroup", "RuleGroupName", "Rules", "SourceMetadata", "SummaryConfiguration", "Tags", "Type"},
			"create-tls-inspection-configuration":                {"Description", "EncryptionConfiguration", "TLSInspectionConfiguration", "TLSInspectionConfigurationName", "Tags"},
			"create-vpc-endpoint-association":                    {"Description", "FirewallArn", "SubnetMapping", "Tags", "VpcId"},
			"delete-firewall":                                    {"FirewallArn", "FirewallName"},
			"delete-firewall-policy":                             {"FirewallPolicyArn", "FirewallPolicyName"},
			"delete-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId"},
			"delete-proxy":                                       {"NatGatewayId", "ProxyArn", "ProxyName"},
			"delete-proxy-configuration":                         {"ProxyConfigurationArn", "ProxyConfigurationName"},
			"delete-proxy-rule-group":                            {"ProxyRuleGroupArn", "ProxyRuleGroupName"},
			"delete-proxy-rules":                                 {"ProxyRuleGroupArn", "ProxyRuleGroupName", "Rules"},
			"delete-resource-policy":                             {"ResourceArn"},
			"delete-rule-group":                                  {"RuleGroupArn", "RuleGroupName", "Type"},
			"delete-tls-inspection-configuration":                {"TLSInspectionConfigurationArn", "TLSInspectionConfigurationName"},
			"delete-vpc-endpoint-association":                    {"VpcEndpointAssociationArn"},
			"describe-firewall":                                  {"FirewallArn", "FirewallName"},
			"describe-firewall-metadata":                         {"FirewallArn"},
			"describe-firewall-policy":                           {"FirewallPolicyArn", "FirewallPolicyName"},
			"describe-flow-operation":                            {"AvailabilityZone", "FirewallArn", "FlowOperationId", "VpcEndpointAssociationArn", "VpcEndpointId"},
			"describe-logging-configuration":                     {"FirewallArn", "FirewallName"},
			"describe-proxy":                                     {"ProxyArn", "ProxyName"},
			"describe-proxy-configuration":                       {"ProxyConfigurationArn", "ProxyConfigurationName"},
			"describe-proxy-rule":                                {"ProxyRuleGroupArn", "ProxyRuleGroupName", "ProxyRuleName"},
			"describe-proxy-rule-group":                          {"ProxyRuleGroupArn", "ProxyRuleGroupName"},
			"describe-resource-policy":                           {"ResourceArn"},
			"describe-rule-group":                                {"AnalyzeRuleGroup", "RuleGroupArn", "RuleGroupName", "Type"},
			"describe-rule-group-metadata":                       {"RuleGroupArn", "RuleGroupName", "Type"},
			"describe-rule-group-summary":                        {"RuleGroupArn", "RuleGroupName", "Type"},
			"describe-tls-inspection-configuration":              {"TLSInspectionConfigurationArn", "TLSInspectionConfigurationName"},
			"describe-vpc-endpoint-association":                  {"VpcEndpointAssociationArn"},
			"detach-rule-groups-from-proxy-configuration":        {"ProxyConfigurationArn", "ProxyConfigurationName", "RuleGroupArns", "RuleGroupNames", "UpdateToken"},
			"disassociate-availability-zones":                    {"AvailabilityZoneMappings", "FirewallArn", "FirewallName", "UpdateToken"},
			"disassociate-subnets":                               {"FirewallArn", "FirewallName", "SubnetIds", "UpdateToken"},
			"get-analysis-report-results":                        {"AnalysisReportId", "FirewallArn", "FirewallName", "MaxResults", "NextToken"},
			"list-analysis-reports":                              {"FirewallArn", "FirewallName", "MaxResults", "NextToken"},
			"list-firewall-policies":                             {"MaxResults", "NextToken"},
			"list-firewalls":                                     {"MaxResults", "NextToken", "VpcIds"},
			"list-flow-operation-results":                        {"AvailabilityZone", "FirewallArn", "FlowOperationId", "MaxResults", "NextToken", "VpcEndpointAssociationArn", "VpcEndpointId"},
			"list-flow-operations":                               {"AvailabilityZone", "FirewallArn", "FlowOperationType", "MaxResults", "NextToken", "VpcEndpointAssociationArn", "VpcEndpointId"},
			"list-proxies":                                       {"MaxResults", "NextToken"},
			"list-proxy-configurations":                          {"MaxResults", "NextToken"},
			"list-proxy-rule-groups":                             {"MaxResults", "NextToken"},
			"list-rule-groups":                                   {"ManagedType", "MaxResults", "NextToken", "Scope", "SubscriptionStatus", "Type"},
			"list-tags-for-resource":                             {"MaxResults", "NextToken", "ResourceArn"},
			"list-tls-inspection-configurations":                 {"MaxResults", "NextToken"},
			"list-vpc-endpoint-associations":                     {"FirewallArn", "MaxResults", "NextToken"},
			"put-resource-policy":                                {"Policy", "ResourceArn"},
			"reject-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId"},
			"start-analysis-report":                              {"AnalysisType", "FirewallArn", "FirewallName"},
			"start-flow-capture":                                 {"AvailabilityZone", "FirewallArn", "FlowFilters", "MinimumFlowAgeInSeconds", "VpcEndpointAssociationArn", "VpcEndpointId"},
			"start-flow-flush":                                   {"AvailabilityZone", "FirewallArn", "FlowFilters", "MinimumFlowAgeInSeconds", "VpcEndpointAssociationArn", "VpcEndpointId"},
			"tag-resource":                                       {"ResourceArn", "Tags"},
			"untag-resource":                                     {"ResourceArn", "TagKeys"},
			"update-availability-zone-change-protection":         {"AvailabilityZoneChangeProtection", "FirewallArn", "FirewallName", "UpdateToken"},
			"update-firewall-analysis-settings":                  {"EnabledAnalysisTypes", "FirewallArn", "FirewallName", "UpdateToken"},
			"update-firewall-delete-protection":                  {"DeleteProtection", "FirewallArn", "FirewallName", "UpdateToken"},
			"update-firewall-description":                        {"Description", "FirewallArn", "FirewallName", "UpdateToken"},
			"update-firewall-encryption-configuration":           {"EncryptionConfiguration", "FirewallArn", "FirewallName", "UpdateToken"},
			"update-firewall-policy":                             {"Description", "DryRun", "EncryptionConfiguration", "FirewallPolicy", "FirewallPolicyArn", "FirewallPolicyName", "UpdateToken"},
			"update-firewall-policy-change-protection":           {"FirewallArn", "FirewallName", "FirewallPolicyChangeProtection", "UpdateToken"},
			"update-logging-configuration":                       {"EnableMonitoringDashboard", "FirewallArn", "FirewallName", "LoggingConfiguration"},
			"update-proxy":                                       {"ListenerPropertiesToAdd", "ListenerPropertiesToRemove", "NatGatewayId", "ProxyArn", "ProxyName", "TlsInterceptProperties", "UpdateToken"},
			"update-proxy-configuration":                         {"DefaultRulePhaseActions", "ProxyConfigurationArn", "ProxyConfigurationName", "UpdateToken"},
			"update-proxy-rule":                                  {"Action", "AddConditions", "Description", "ProxyRuleGroupArn", "ProxyRuleGroupName", "ProxyRuleName", "RemoveConditions", "UpdateToken"},
			"update-proxy-rule-group-priorities":                 {"ProxyConfigurationArn", "ProxyConfigurationName", "RuleGroups", "UpdateToken"},
			"update-proxy-rule-priorities":                       {"ProxyRuleGroupArn", "ProxyRuleGroupName", "RuleGroupRequestPhase", "Rules", "UpdateToken"},
			"update-rule-group":                                  {"AnalyzeRuleGroup", "Description", "DryRun", "EncryptionConfiguration", "RuleGroup", "RuleGroupArn", "RuleGroupName", "Rules", "SourceMetadata", "SummaryConfiguration", "Type", "UpdateToken"},
			"update-subnet-change-protection":                    {"FirewallArn", "FirewallName", "SubnetChangeProtection", "UpdateToken"},
			"update-tls-inspection-configuration":                {"Description", "EncryptionConfiguration", "TLSInspectionConfiguration", "TLSInspectionConfigurationArn", "TLSInspectionConfigurationName", "UpdateToken"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId": "*string"},
			"associate-availability-zones":                       {"AvailabilityZoneMappings": "[]types.AvailabilityZoneMapping", "FirewallArn": "*string", "FirewallName": "*string", "UpdateToken": "*string"},
			"associate-firewall-policy":                          {"FirewallArn": "*string", "FirewallName": "*string", "FirewallPolicyArn": "*string", "UpdateToken": "*string"},
			"associate-subnets":                                  {"FirewallArn": "*string", "FirewallName": "*string", "SubnetMappings": "[]types.SubnetMapping", "UpdateToken": "*string"},
			"attach-rule-groups-to-proxy-configuration":          {"ProxyConfigurationArn": "*string", "ProxyConfigurationName": "*string", "RuleGroups": "[]types.ProxyRuleGroupAttachment", "UpdateToken": "*string"},
			"create-firewall":                                    {"AvailabilityZoneChangeProtection": "bool", "AvailabilityZoneMappings": "[]types.AvailabilityZoneMapping", "DeleteProtection": "bool", "Description": "*string", "EnabledAnalysisTypes": "[]types.EnabledAnalysisType", "EncryptionConfiguration": "*types.EncryptionConfiguration", "FirewallName": "*string", "FirewallPolicyArn": "*string", "FirewallPolicyChangeProtection": "bool", "SubnetChangeProtection": "bool", "SubnetMappings": "[]types.SubnetMapping", "Tags": "[]types.Tag", "TransitGatewayId": "*string", "VpcId": "*string"},
			"create-firewall-policy":                             {"Description": "*string", "DryRun": "bool", "EncryptionConfiguration": "*types.EncryptionConfiguration", "FirewallPolicy": "*types.FirewallPolicy", "FirewallPolicyName": "*string", "Tags": "[]types.Tag"},
			"create-proxy":                                       {"ListenerProperties": "[]types.ListenerPropertyRequest", "NatGatewayId": "*string", "ProxyConfigurationArn": "*string", "ProxyConfigurationName": "*string", "ProxyName": "*string", "Tags": "[]types.Tag", "TlsInterceptProperties": "*types.TlsInterceptPropertiesRequest"},
			"create-proxy-configuration":                         {"DefaultRulePhaseActions": "*types.ProxyConfigDefaultRulePhaseActionsRequest", "Description": "*string", "ProxyConfigurationName": "*string", "RuleGroupArns": "[]string", "RuleGroupNames": "[]string", "Tags": "[]types.Tag"},
			"create-proxy-rule-group":                            {"Description": "*string", "ProxyRuleGroupName": "*string", "Rules": "*types.ProxyRulesByRequestPhase", "Tags": "[]types.Tag"},
			"create-proxy-rules":                                 {"ProxyRuleGroupArn": "*string", "ProxyRuleGroupName": "*string", "Rules": "*types.CreateProxyRulesByRequestPhase"},
			"create-rule-group":                                  {"AnalyzeRuleGroup": "bool", "Capacity": "*int32", "Description": "*string", "DryRun": "bool", "EncryptionConfiguration": "*types.EncryptionConfiguration", "RuleGroup": "*types.RuleGroup", "RuleGroupName": "*string", "Rules": "*string", "SourceMetadata": "*types.SourceMetadata", "SummaryConfiguration": "*types.SummaryConfiguration", "Tags": "[]types.Tag", "Type": "types.RuleGroupType"},
			"create-tls-inspection-configuration":                {"Description": "*string", "EncryptionConfiguration": "*types.EncryptionConfiguration", "TLSInspectionConfiguration": "*types.TLSInspectionConfiguration", "TLSInspectionConfigurationName": "*string", "Tags": "[]types.Tag"},
			"create-vpc-endpoint-association":                    {"Description": "*string", "FirewallArn": "*string", "SubnetMapping": "*types.SubnetMapping", "Tags": "[]types.Tag", "VpcId": "*string"},
			"delete-firewall":                                    {"FirewallArn": "*string", "FirewallName": "*string"},
			"delete-firewall-policy":                             {"FirewallPolicyArn": "*string", "FirewallPolicyName": "*string"},
			"delete-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId": "*string"},
			"delete-proxy":                                       {"NatGatewayId": "*string", "ProxyArn": "*string", "ProxyName": "*string"},
			"delete-proxy-configuration":                         {"ProxyConfigurationArn": "*string", "ProxyConfigurationName": "*string"},
			"delete-proxy-rule-group":                            {"ProxyRuleGroupArn": "*string", "ProxyRuleGroupName": "*string"},
			"delete-proxy-rules":                                 {"ProxyRuleGroupArn": "*string", "ProxyRuleGroupName": "*string", "Rules": "[]string"},
			"delete-resource-policy":                             {"ResourceArn": "*string"},
			"delete-rule-group":                                  {"RuleGroupArn": "*string", "RuleGroupName": "*string", "Type": "types.RuleGroupType"},
			"delete-tls-inspection-configuration":                {"TLSInspectionConfigurationArn": "*string", "TLSInspectionConfigurationName": "*string"},
			"delete-vpc-endpoint-association":                    {"VpcEndpointAssociationArn": "*string"},
			"describe-firewall":                                  {"FirewallArn": "*string", "FirewallName": "*string"},
			"describe-firewall-metadata":                         {"FirewallArn": "*string"},
			"describe-firewall-policy":                           {"FirewallPolicyArn": "*string", "FirewallPolicyName": "*string"},
			"describe-flow-operation":                            {"AvailabilityZone": "*string", "FirewallArn": "*string", "FlowOperationId": "*string", "VpcEndpointAssociationArn": "*string", "VpcEndpointId": "*string"},
			"describe-logging-configuration":                     {"FirewallArn": "*string", "FirewallName": "*string"},
			"describe-proxy":                                     {"ProxyArn": "*string", "ProxyName": "*string"},
			"describe-proxy-configuration":                       {"ProxyConfigurationArn": "*string", "ProxyConfigurationName": "*string"},
			"describe-proxy-rule":                                {"ProxyRuleGroupArn": "*string", "ProxyRuleGroupName": "*string", "ProxyRuleName": "*string"},
			"describe-proxy-rule-group":                          {"ProxyRuleGroupArn": "*string", "ProxyRuleGroupName": "*string"},
			"describe-resource-policy":                           {"ResourceArn": "*string"},
			"describe-rule-group":                                {"AnalyzeRuleGroup": "bool", "RuleGroupArn": "*string", "RuleGroupName": "*string", "Type": "types.RuleGroupType"},
			"describe-rule-group-metadata":                       {"RuleGroupArn": "*string", "RuleGroupName": "*string", "Type": "types.RuleGroupType"},
			"describe-rule-group-summary":                        {"RuleGroupArn": "*string", "RuleGroupName": "*string", "Type": "types.RuleGroupType"},
			"describe-tls-inspection-configuration":              {"TLSInspectionConfigurationArn": "*string", "TLSInspectionConfigurationName": "*string"},
			"describe-vpc-endpoint-association":                  {"VpcEndpointAssociationArn": "*string"},
			"detach-rule-groups-from-proxy-configuration":        {"ProxyConfigurationArn": "*string", "ProxyConfigurationName": "*string", "RuleGroupArns": "[]string", "RuleGroupNames": "[]string", "UpdateToken": "*string"},
			"disassociate-availability-zones":                    {"AvailabilityZoneMappings": "[]types.AvailabilityZoneMapping", "FirewallArn": "*string", "FirewallName": "*string", "UpdateToken": "*string"},
			"disassociate-subnets":                               {"FirewallArn": "*string", "FirewallName": "*string", "SubnetIds": "[]string", "UpdateToken": "*string"},
			"get-analysis-report-results":                        {"AnalysisReportId": "*string", "FirewallArn": "*string", "FirewallName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-analysis-reports":                              {"FirewallArn": "*string", "FirewallName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-firewall-policies":                             {"MaxResults": "*int32", "NextToken": "*string"},
			"list-firewalls":                                     {"MaxResults": "*int32", "NextToken": "*string", "VpcIds": "[]string"},
			"list-flow-operation-results":                        {"AvailabilityZone": "*string", "FirewallArn": "*string", "FlowOperationId": "*string", "MaxResults": "*int32", "NextToken": "*string", "VpcEndpointAssociationArn": "*string", "VpcEndpointId": "*string"},
			"list-flow-operations":                               {"AvailabilityZone": "*string", "FirewallArn": "*string", "FlowOperationType": "types.FlowOperationType", "MaxResults": "*int32", "NextToken": "*string", "VpcEndpointAssociationArn": "*string", "VpcEndpointId": "*string"},
			"list-proxies":                                       {"MaxResults": "*int32", "NextToken": "*string"},
			"list-proxy-configurations":                          {"MaxResults": "*int32", "NextToken": "*string"},
			"list-proxy-rule-groups":                             {"MaxResults": "*int32", "NextToken": "*string"},
			"list-rule-groups":                                   {"ManagedType": "types.ResourceManagedType", "MaxResults": "*int32", "NextToken": "*string", "Scope": "types.ResourceManagedStatus", "SubscriptionStatus": "types.SubscriptionStatus", "Type": "types.RuleGroupType"},
			"list-tags-for-resource":                             {"MaxResults": "*int32", "NextToken": "*string", "ResourceArn": "*string"},
			"list-tls-inspection-configurations":                 {"MaxResults": "*int32", "NextToken": "*string"},
			"list-vpc-endpoint-associations":                     {"FirewallArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"put-resource-policy":                                {"Policy": "*string", "ResourceArn": "*string"},
			"reject-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId": "*string"},
			"start-analysis-report":                              {"AnalysisType": "types.EnabledAnalysisType", "FirewallArn": "*string", "FirewallName": "*string"},
			"start-flow-capture":                                 {"AvailabilityZone": "*string", "FirewallArn": "*string", "FlowFilters": "[]types.FlowFilter", "MinimumFlowAgeInSeconds": "*int32", "VpcEndpointAssociationArn": "*string", "VpcEndpointId": "*string"},
			"start-flow-flush":                                   {"AvailabilityZone": "*string", "FirewallArn": "*string", "FlowFilters": "[]types.FlowFilter", "MinimumFlowAgeInSeconds": "*int32", "VpcEndpointAssociationArn": "*string", "VpcEndpointId": "*string"},
			"tag-resource":                                       {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                                     {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-availability-zone-change-protection":         {"AvailabilityZoneChangeProtection": "bool", "FirewallArn": "*string", "FirewallName": "*string", "UpdateToken": "*string"},
			"update-firewall-analysis-settings":                  {"EnabledAnalysisTypes": "[]types.EnabledAnalysisType", "FirewallArn": "*string", "FirewallName": "*string", "UpdateToken": "*string"},
			"update-firewall-delete-protection":                  {"DeleteProtection": "bool", "FirewallArn": "*string", "FirewallName": "*string", "UpdateToken": "*string"},
			"update-firewall-description":                        {"Description": "*string", "FirewallArn": "*string", "FirewallName": "*string", "UpdateToken": "*string"},
			"update-firewall-encryption-configuration":           {"EncryptionConfiguration": "*types.EncryptionConfiguration", "FirewallArn": "*string", "FirewallName": "*string", "UpdateToken": "*string"},
			"update-firewall-policy":                             {"Description": "*string", "DryRun": "bool", "EncryptionConfiguration": "*types.EncryptionConfiguration", "FirewallPolicy": "*types.FirewallPolicy", "FirewallPolicyArn": "*string", "FirewallPolicyName": "*string", "UpdateToken": "*string"},
			"update-firewall-policy-change-protection":           {"FirewallArn": "*string", "FirewallName": "*string", "FirewallPolicyChangeProtection": "bool", "UpdateToken": "*string"},
			"update-logging-configuration":                       {"EnableMonitoringDashboard": "*bool", "FirewallArn": "*string", "FirewallName": "*string", "LoggingConfiguration": "*types.LoggingConfiguration"},
			"update-proxy":                                       {"ListenerPropertiesToAdd": "[]types.ListenerPropertyRequest", "ListenerPropertiesToRemove": "[]types.ListenerPropertyRequest", "NatGatewayId": "*string", "ProxyArn": "*string", "ProxyName": "*string", "TlsInterceptProperties": "*types.TlsInterceptPropertiesRequest", "UpdateToken": "*string"},
			"update-proxy-configuration":                         {"DefaultRulePhaseActions": "*types.ProxyConfigDefaultRulePhaseActionsRequest", "ProxyConfigurationArn": "*string", "ProxyConfigurationName": "*string", "UpdateToken": "*string"},
			"update-proxy-rule":                                  {"Action": "types.ProxyRulePhaseAction", "AddConditions": "[]types.ProxyRuleCondition", "Description": "*string", "ProxyRuleGroupArn": "*string", "ProxyRuleGroupName": "*string", "ProxyRuleName": "*string", "RemoveConditions": "[]types.ProxyRuleCondition", "UpdateToken": "*string"},
			"update-proxy-rule-group-priorities":                 {"ProxyConfigurationArn": "*string", "ProxyConfigurationName": "*string", "RuleGroups": "[]types.ProxyRuleGroupPriority", "UpdateToken": "*string"},
			"update-proxy-rule-priorities":                       {"ProxyRuleGroupArn": "*string", "ProxyRuleGroupName": "*string", "RuleGroupRequestPhase": "types.RuleGroupRequestPhase", "Rules": "[]types.ProxyRulePriority", "UpdateToken": "*string"},
			"update-rule-group":                                  {"AnalyzeRuleGroup": "bool", "Description": "*string", "DryRun": "bool", "EncryptionConfiguration": "*types.EncryptionConfiguration", "RuleGroup": "*types.RuleGroup", "RuleGroupArn": "*string", "RuleGroupName": "*string", "Rules": "*string", "SourceMetadata": "*types.SourceMetadata", "SummaryConfiguration": "*types.SummaryConfiguration", "Type": "types.RuleGroupType", "UpdateToken": "*string"},
			"update-subnet-change-protection":                    {"FirewallArn": "*string", "FirewallName": "*string", "SubnetChangeProtection": "bool", "UpdateToken": "*string"},
			"update-tls-inspection-configuration":                {"Description": "*string", "EncryptionConfiguration": "*types.EncryptionConfiguration", "TLSInspectionConfiguration": "*types.TLSInspectionConfiguration", "TLSInspectionConfigurationArn": "*string", "TLSInspectionConfigurationName": "*string", "UpdateToken": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId"},
			"associate-availability-zones":                       {"AvailabilityZoneMappings"},
			"associate-firewall-policy":                          {"FirewallPolicyArn"},
			"associate-subnets":                                  {"SubnetMappings"},
			"attach-rule-groups-to-proxy-configuration":          {"RuleGroups", "UpdateToken"},
			"create-firewall":                                    {"FirewallName", "FirewallPolicyArn"},
			"create-firewall-policy":                             {"FirewallPolicy", "FirewallPolicyName"},
			"create-proxy":                                       {"NatGatewayId", "ProxyName", "TlsInterceptProperties"},
			"create-proxy-configuration":                         {"DefaultRulePhaseActions", "ProxyConfigurationName"},
			"create-proxy-rule-group":                            {"ProxyRuleGroupName"},
			"create-proxy-rules":                                 {"Rules"},
			"create-rule-group":                                  {"Capacity", "RuleGroupName", "Type"},
			"create-tls-inspection-configuration":                {"TLSInspectionConfiguration", "TLSInspectionConfigurationName"},
			"create-vpc-endpoint-association":                    {"FirewallArn", "SubnetMapping", "VpcId"},
			"delete-firewall":                                    {},
			"delete-firewall-policy":                             {},
			"delete-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId"},
			"delete-proxy":                                       {"NatGatewayId"},
			"delete-proxy-configuration":                         {},
			"delete-proxy-rule-group":                            {},
			"delete-proxy-rules":                                 {"Rules"},
			"delete-resource-policy":                             {"ResourceArn"},
			"delete-rule-group":                                  {},
			"delete-tls-inspection-configuration":                {},
			"delete-vpc-endpoint-association":                    {"VpcEndpointAssociationArn"},
			"describe-firewall":                                  {},
			"describe-firewall-metadata":                         {},
			"describe-firewall-policy":                           {},
			"describe-flow-operation":                            {"FirewallArn", "FlowOperationId"},
			"describe-logging-configuration":                     {},
			"describe-proxy":                                     {},
			"describe-proxy-configuration":                       {},
			"describe-proxy-rule":                                {"ProxyRuleName"},
			"describe-proxy-rule-group":                          {},
			"describe-resource-policy":                           {"ResourceArn"},
			"describe-rule-group":                                {},
			"describe-rule-group-metadata":                       {},
			"describe-rule-group-summary":                        {},
			"describe-tls-inspection-configuration":              {},
			"describe-vpc-endpoint-association":                  {"VpcEndpointAssociationArn"},
			"detach-rule-groups-from-proxy-configuration":        {"UpdateToken"},
			"disassociate-availability-zones":                    {"AvailabilityZoneMappings"},
			"disassociate-subnets":                               {"SubnetIds"},
			"get-analysis-report-results":                        {"AnalysisReportId"},
			"list-analysis-reports":                              {},
			"list-firewall-policies":                             {},
			"list-firewalls":                                     {},
			"list-flow-operation-results":                        {"FirewallArn", "FlowOperationId"},
			"list-flow-operations":                               {"FirewallArn"},
			"list-proxies":                                       {},
			"list-proxy-configurations":                          {},
			"list-proxy-rule-groups":                             {},
			"list-rule-groups":                                   {},
			"list-tags-for-resource":                             {"ResourceArn"},
			"list-tls-inspection-configurations":                 {},
			"list-vpc-endpoint-associations":                     {},
			"put-resource-policy":                                {"Policy", "ResourceArn"},
			"reject-network-firewall-transit-gateway-attachment": {"TransitGatewayAttachmentId"},
			"start-analysis-report":                              {"AnalysisType"},
			"start-flow-capture":                                 {"FirewallArn", "FlowFilters"},
			"start-flow-flush":                                   {"FirewallArn", "FlowFilters"},
			"tag-resource":                                       {"ResourceArn", "Tags"},
			"untag-resource":                                     {"ResourceArn", "TagKeys"},
			"update-availability-zone-change-protection":         {"AvailabilityZoneChangeProtection"},
			"update-firewall-analysis-settings":                  {},
			"update-firewall-delete-protection":                  {"DeleteProtection"},
			"update-firewall-description":                        {},
			"update-firewall-encryption-configuration":           {},
			"update-firewall-policy":                             {"FirewallPolicy", "UpdateToken"},
			"update-firewall-policy-change-protection":           {"FirewallPolicyChangeProtection"},
			"update-logging-configuration":                       {},
			"update-proxy":                                       {"NatGatewayId", "UpdateToken"},
			"update-proxy-configuration":                         {"DefaultRulePhaseActions", "UpdateToken"},
			"update-proxy-rule":                                  {"ProxyRuleName", "UpdateToken"},
			"update-proxy-rule-group-priorities":                 {"RuleGroups", "UpdateToken"},
			"update-proxy-rule-priorities":                       {"RuleGroupRequestPhase", "Rules", "UpdateToken"},
			"update-rule-group":                                  {"UpdateToken"},
			"update-subnet-change-protection":                    {"SubnetChangeProtection"},
			"update-tls-inspection-configuration":                {"TLSInspectionConfiguration", "UpdateToken"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("networkfirewall", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
