package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/ivsrealtime/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-encoder-configuration", "create-ingest-configuration", "create-participant-token", "create-stage", "create-storage-configuration", "delete-encoder-configuration", "delete-ingest-configuration", "delete-public-key", "delete-stage", "delete-storage-configuration", "disconnect-participant", "get-composition", "get-encoder-configuration", "get-ingest-configuration", "get-participant", "get-public-key", "get-stage", "get-stage-session", "get-storage-configuration", "import-public-key", "list-compositions", "list-encoder-configurations", "list-ingest-configurations", "list-participant-events", "list-participant-replicas", "list-participants", "list-public-keys", "list-stage-sessions", "list-stages", "list-storage-configurations", "list-tags-for-resource", "start-composition", "start-participant-replication", "stop-composition", "stop-participant-replication", "tag-resource", "untag-resource", "update-ingest-configuration", "update-stage"},
		OperationSet: map[string]bool{"create-encoder-configuration": true, "create-ingest-configuration": true, "create-participant-token": true, "create-stage": true, "create-storage-configuration": true, "delete-encoder-configuration": true, "delete-ingest-configuration": true, "delete-public-key": true, "delete-stage": true, "delete-storage-configuration": true, "disconnect-participant": true, "get-composition": true, "get-encoder-configuration": true, "get-ingest-configuration": true, "get-participant": true, "get-public-key": true, "get-stage": true, "get-stage-session": true, "get-storage-configuration": true, "import-public-key": true, "list-compositions": true, "list-encoder-configurations": true, "list-ingest-configurations": true, "list-participant-events": true, "list-participant-replicas": true, "list-participants": true, "list-public-keys": true, "list-stage-sessions": true, "list-stages": true, "list-storage-configurations": true, "list-tags-for-resource": true, "start-composition": true, "start-participant-replication": true, "stop-composition": true, "stop-participant-replication": true, "tag-resource": true, "untag-resource": true, "update-ingest-configuration": true, "update-stage": true},
		OperationInputs: map[string][]string{
			"create-encoder-configuration":  {"Name", "Tags", "Video"},
			"create-ingest-configuration":   {"Attributes", "IngestProtocol", "InsecureIngest", "Name", "StageArn", "Tags", "UserId"},
			"create-participant-token":      {"Attributes", "Capabilities", "Duration", "StageArn", "UserId"},
			"create-stage":                  {"AutoParticipantRecordingConfiguration", "Name", "ParticipantTokenConfigurations", "Tags"},
			"create-storage-configuration":  {"Name", "S3", "Tags"},
			"delete-encoder-configuration":  {"Arn"},
			"delete-ingest-configuration":   {"Arn", "Force"},
			"delete-public-key":             {"Arn"},
			"delete-stage":                  {"Arn"},
			"delete-storage-configuration":  {"Arn"},
			"disconnect-participant":        {"ParticipantId", "Reason", "StageArn"},
			"get-composition":               {"Arn"},
			"get-encoder-configuration":     {"Arn"},
			"get-ingest-configuration":      {"Arn"},
			"get-participant":               {"ParticipantId", "SessionId", "StageArn"},
			"get-public-key":                {"Arn"},
			"get-stage":                     {"Arn"},
			"get-stage-session":             {"SessionId", "StageArn"},
			"get-storage-configuration":     {"Arn"},
			"import-public-key":             {"Name", "PublicKeyMaterial", "Tags"},
			"list-compositions":             {"FilterByEncoderConfigurationArn", "FilterByStageArn", "MaxResults", "NextToken"},
			"list-encoder-configurations":   {"MaxResults", "NextToken"},
			"list-ingest-configurations":    {"FilterByStageArn", "FilterByState", "MaxResults", "NextToken"},
			"list-participant-events":       {"MaxResults", "NextToken", "ParticipantId", "SessionId", "StageArn"},
			"list-participant-replicas":     {"MaxResults", "NextToken", "ParticipantId", "SourceStageArn"},
			"list-participants":             {"FilterByPublished", "FilterByRecordingState", "FilterByState", "FilterByUserId", "MaxResults", "NextToken", "SessionId", "StageArn"},
			"list-public-keys":              {"MaxResults", "NextToken"},
			"list-stage-sessions":           {"MaxResults", "NextToken", "StageArn"},
			"list-stages":                   {"MaxResults", "NextToken"},
			"list-storage-configurations":   {"MaxResults", "NextToken"},
			"list-tags-for-resource":        {"ResourceArn"},
			"start-composition":             {"Destinations", "IdempotencyToken", "Layout", "StageArn", "Tags"},
			"start-participant-replication": {"Attributes", "DestinationStageArn", "ParticipantId", "ReconnectWindowSeconds", "SourceStageArn"},
			"stop-composition":              {"Arn"},
			"stop-participant-replication":  {"DestinationStageArn", "ParticipantId", "SourceStageArn"},
			"tag-resource":                  {"ResourceArn", "Tags"},
			"untag-resource":                {"ResourceArn", "TagKeys"},
			"update-ingest-configuration":   {"Arn", "StageArn"},
			"update-stage":                  {"Arn", "AutoParticipantRecordingConfiguration", "Name"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-encoder-configuration":  {"Name": "*string", "Tags": "map[string]string", "Video": "*types.Video"},
			"create-ingest-configuration":   {"Attributes": "map[string]string", "IngestProtocol": "types.IngestProtocol", "InsecureIngest": "bool", "Name": "*string", "StageArn": "*string", "Tags": "map[string]string", "UserId": "*string"},
			"create-participant-token":      {"Attributes": "map[string]string", "Capabilities": "[]types.ParticipantTokenCapability", "Duration": "*int32", "StageArn": "*string", "UserId": "*string"},
			"create-stage":                  {"AutoParticipantRecordingConfiguration": "*types.AutoParticipantRecordingConfiguration", "Name": "*string", "ParticipantTokenConfigurations": "[]types.ParticipantTokenConfiguration", "Tags": "map[string]string"},
			"create-storage-configuration":  {"Name": "*string", "S3": "*types.S3StorageConfiguration", "Tags": "map[string]string"},
			"delete-encoder-configuration":  {"Arn": "*string"},
			"delete-ingest-configuration":   {"Arn": "*string", "Force": "bool"},
			"delete-public-key":             {"Arn": "*string"},
			"delete-stage":                  {"Arn": "*string"},
			"delete-storage-configuration":  {"Arn": "*string"},
			"disconnect-participant":        {"ParticipantId": "*string", "Reason": "*string", "StageArn": "*string"},
			"get-composition":               {"Arn": "*string"},
			"get-encoder-configuration":     {"Arn": "*string"},
			"get-ingest-configuration":      {"Arn": "*string"},
			"get-participant":               {"ParticipantId": "*string", "SessionId": "*string", "StageArn": "*string"},
			"get-public-key":                {"Arn": "*string"},
			"get-stage":                     {"Arn": "*string"},
			"get-stage-session":             {"SessionId": "*string", "StageArn": "*string"},
			"get-storage-configuration":     {"Arn": "*string"},
			"import-public-key":             {"Name": "*string", "PublicKeyMaterial": "*string", "Tags": "map[string]string"},
			"list-compositions":             {"FilterByEncoderConfigurationArn": "*string", "FilterByStageArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-encoder-configurations":   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-ingest-configurations":    {"FilterByStageArn": "*string", "FilterByState": "types.IngestConfigurationState", "MaxResults": "*int32", "NextToken": "*string"},
			"list-participant-events":       {"MaxResults": "*int32", "NextToken": "*string", "ParticipantId": "*string", "SessionId": "*string", "StageArn": "*string"},
			"list-participant-replicas":     {"MaxResults": "*int32", "NextToken": "*string", "ParticipantId": "*string", "SourceStageArn": "*string"},
			"list-participants":             {"FilterByPublished": "bool", "FilterByRecordingState": "types.ParticipantRecordingFilterByRecordingState", "FilterByState": "types.ParticipantState", "FilterByUserId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SessionId": "*string", "StageArn": "*string"},
			"list-public-keys":              {"MaxResults": "*int32", "NextToken": "*string"},
			"list-stage-sessions":           {"MaxResults": "*int32", "NextToken": "*string", "StageArn": "*string"},
			"list-stages":                   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-storage-configurations":   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":        {"ResourceArn": "*string"},
			"start-composition":             {"Destinations": "[]types.DestinationConfiguration", "IdempotencyToken": "*string", "Layout": "*types.LayoutConfiguration", "StageArn": "*string", "Tags": "map[string]string"},
			"start-participant-replication": {"Attributes": "map[string]string", "DestinationStageArn": "*string", "ParticipantId": "*string", "ReconnectWindowSeconds": "*int32", "SourceStageArn": "*string"},
			"stop-composition":              {"Arn": "*string"},
			"stop-participant-replication":  {"DestinationStageArn": "*string", "ParticipantId": "*string", "SourceStageArn": "*string"},
			"tag-resource":                  {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-ingest-configuration":   {"Arn": "*string", "StageArn": "*string"},
			"update-stage":                  {"Arn": "*string", "AutoParticipantRecordingConfiguration": "*types.AutoParticipantRecordingConfiguration", "Name": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-encoder-configuration":  {},
			"create-ingest-configuration":   {"IngestProtocol"},
			"create-participant-token":      {"StageArn"},
			"create-stage":                  {},
			"create-storage-configuration":  {"S3"},
			"delete-encoder-configuration":  {"Arn"},
			"delete-ingest-configuration":   {"Arn"},
			"delete-public-key":             {"Arn"},
			"delete-stage":                  {"Arn"},
			"delete-storage-configuration":  {"Arn"},
			"disconnect-participant":        {"ParticipantId", "StageArn"},
			"get-composition":               {"Arn"},
			"get-encoder-configuration":     {"Arn"},
			"get-ingest-configuration":      {"Arn"},
			"get-participant":               {"ParticipantId", "SessionId", "StageArn"},
			"get-public-key":                {"Arn"},
			"get-stage":                     {"Arn"},
			"get-stage-session":             {"SessionId", "StageArn"},
			"get-storage-configuration":     {"Arn"},
			"import-public-key":             {"PublicKeyMaterial"},
			"list-compositions":             {},
			"list-encoder-configurations":   {},
			"list-ingest-configurations":    {},
			"list-participant-events":       {"ParticipantId", "SessionId", "StageArn"},
			"list-participant-replicas":     {"ParticipantId", "SourceStageArn"},
			"list-participants":             {"SessionId", "StageArn"},
			"list-public-keys":              {},
			"list-stage-sessions":           {"StageArn"},
			"list-stages":                   {},
			"list-storage-configurations":   {},
			"list-tags-for-resource":        {"ResourceArn"},
			"start-composition":             {"Destinations", "StageArn"},
			"start-participant-replication": {"DestinationStageArn", "ParticipantId", "SourceStageArn"},
			"stop-composition":              {"Arn"},
			"stop-participant-replication":  {"DestinationStageArn", "ParticipantId", "SourceStageArn"},
			"tag-resource":                  {"ResourceArn", "Tags"},
			"untag-resource":                {"ResourceArn", "TagKeys"},
			"update-ingest-configuration":   {"Arn"},
			"update-stage":                  {"Arn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("ivsrealtime", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
