package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/route53resolver/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-firewall-rule-group", "associate-resolver-endpoint-ip-address", "associate-resolver-query-log-config", "associate-resolver-rule", "create-firewall-domain-list", "create-firewall-rule", "create-firewall-rule-group", "create-outpost-resolver", "create-resolver-endpoint", "create-resolver-query-log-config", "create-resolver-rule", "delete-firewall-domain-list", "delete-firewall-rule", "delete-firewall-rule-group", "delete-outpost-resolver", "delete-resolver-endpoint", "delete-resolver-query-log-config", "delete-resolver-rule", "disassociate-firewall-rule-group", "disassociate-resolver-endpoint-ip-address", "disassociate-resolver-query-log-config", "disassociate-resolver-rule", "get-firewall-config", "get-firewall-domain-list", "get-firewall-rule-group", "get-firewall-rule-group-association", "get-firewall-rule-group-policy", "get-outpost-resolver", "get-resolver-config", "get-resolver-dnssec-config", "get-resolver-endpoint", "get-resolver-query-log-config", "get-resolver-query-log-config-association", "get-resolver-query-log-config-policy", "get-resolver-rule", "get-resolver-rule-association", "get-resolver-rule-policy", "import-firewall-domains", "list-firewall-configs", "list-firewall-domain-lists", "list-firewall-domains", "list-firewall-rule-group-associations", "list-firewall-rule-groups", "list-firewall-rules", "list-outpost-resolvers", "list-resolver-configs", "list-resolver-dnssec-configs", "list-resolver-endpoint-ip-addresses", "list-resolver-endpoints", "list-resolver-query-log-config-associations", "list-resolver-query-log-configs", "list-resolver-rule-associations", "list-resolver-rules", "list-tags-for-resource", "put-firewall-rule-group-policy", "put-resolver-query-log-config-policy", "put-resolver-rule-policy", "tag-resource", "untag-resource", "update-firewall-config", "update-firewall-domains", "update-firewall-rule", "update-firewall-rule-group-association", "update-outpost-resolver", "update-resolver-config", "update-resolver-dnssec-config", "update-resolver-endpoint", "update-resolver-rule"},
		OperationSet: map[string]bool{"associate-firewall-rule-group": true, "associate-resolver-endpoint-ip-address": true, "associate-resolver-query-log-config": true, "associate-resolver-rule": true, "create-firewall-domain-list": true, "create-firewall-rule": true, "create-firewall-rule-group": true, "create-outpost-resolver": true, "create-resolver-endpoint": true, "create-resolver-query-log-config": true, "create-resolver-rule": true, "delete-firewall-domain-list": true, "delete-firewall-rule": true, "delete-firewall-rule-group": true, "delete-outpost-resolver": true, "delete-resolver-endpoint": true, "delete-resolver-query-log-config": true, "delete-resolver-rule": true, "disassociate-firewall-rule-group": true, "disassociate-resolver-endpoint-ip-address": true, "disassociate-resolver-query-log-config": true, "disassociate-resolver-rule": true, "get-firewall-config": true, "get-firewall-domain-list": true, "get-firewall-rule-group": true, "get-firewall-rule-group-association": true, "get-firewall-rule-group-policy": true, "get-outpost-resolver": true, "get-resolver-config": true, "get-resolver-dnssec-config": true, "get-resolver-endpoint": true, "get-resolver-query-log-config": true, "get-resolver-query-log-config-association": true, "get-resolver-query-log-config-policy": true, "get-resolver-rule": true, "get-resolver-rule-association": true, "get-resolver-rule-policy": true, "import-firewall-domains": true, "list-firewall-configs": true, "list-firewall-domain-lists": true, "list-firewall-domains": true, "list-firewall-rule-group-associations": true, "list-firewall-rule-groups": true, "list-firewall-rules": true, "list-outpost-resolvers": true, "list-resolver-configs": true, "list-resolver-dnssec-configs": true, "list-resolver-endpoint-ip-addresses": true, "list-resolver-endpoints": true, "list-resolver-query-log-config-associations": true, "list-resolver-query-log-configs": true, "list-resolver-rule-associations": true, "list-resolver-rules": true, "list-tags-for-resource": true, "put-firewall-rule-group-policy": true, "put-resolver-query-log-config-policy": true, "put-resolver-rule-policy": true, "tag-resource": true, "untag-resource": true, "update-firewall-config": true, "update-firewall-domains": true, "update-firewall-rule": true, "update-firewall-rule-group-association": true, "update-outpost-resolver": true, "update-resolver-config": true, "update-resolver-dnssec-config": true, "update-resolver-endpoint": true, "update-resolver-rule": true},
		OperationInputs: map[string][]string{
			"associate-firewall-rule-group":               {"CreatorRequestId", "FirewallRuleGroupId", "MutationProtection", "Name", "Priority", "Tags", "VpcId"},
			"associate-resolver-endpoint-ip-address":      {"IpAddress", "ResolverEndpointId"},
			"associate-resolver-query-log-config":         {"ResolverQueryLogConfigId", "ResourceId"},
			"associate-resolver-rule":                     {"Name", "ResolverRuleId", "VPCId"},
			"create-firewall-domain-list":                 {"CreatorRequestId", "Name", "Tags"},
			"create-firewall-rule":                        {"Action", "BlockOverrideDnsType", "BlockOverrideDomain", "BlockOverrideTtl", "BlockResponse", "ConfidenceThreshold", "CreatorRequestId", "DnsThreatProtection", "FirewallDomainListId", "FirewallDomainRedirectionAction", "FirewallRuleGroupId", "Name", "Priority", "Qtype"},
			"create-firewall-rule-group":                  {"CreatorRequestId", "Name", "Tags"},
			"create-outpost-resolver":                     {"CreatorRequestId", "InstanceCount", "Name", "OutpostArn", "PreferredInstanceType", "Tags"},
			"create-resolver-endpoint":                    {"CreatorRequestId", "Direction", "IpAddresses", "Name", "OutpostArn", "PreferredInstanceType", "Protocols", "ResolverEndpointType", "RniEnhancedMetricsEnabled", "SecurityGroupIds", "Tags", "TargetNameServerMetricsEnabled"},
			"create-resolver-query-log-config":            {"CreatorRequestId", "DestinationArn", "Name", "Tags"},
			"create-resolver-rule":                        {"CreatorRequestId", "DelegationRecord", "DomainName", "Name", "ResolverEndpointId", "RuleType", "Tags", "TargetIps"},
			"delete-firewall-domain-list":                 {"FirewallDomainListId"},
			"delete-firewall-rule":                        {"FirewallDomainListId", "FirewallRuleGroupId", "FirewallThreatProtectionId", "Qtype"},
			"delete-firewall-rule-group":                  {"FirewallRuleGroupId"},
			"delete-outpost-resolver":                     {"Id"},
			"delete-resolver-endpoint":                    {"ResolverEndpointId"},
			"delete-resolver-query-log-config":            {"ResolverQueryLogConfigId"},
			"delete-resolver-rule":                        {"ResolverRuleId"},
			"disassociate-firewall-rule-group":            {"FirewallRuleGroupAssociationId"},
			"disassociate-resolver-endpoint-ip-address":   {"IpAddress", "ResolverEndpointId"},
			"disassociate-resolver-query-log-config":      {"ResolverQueryLogConfigId", "ResourceId"},
			"disassociate-resolver-rule":                  {"ResolverRuleId", "VPCId"},
			"get-firewall-config":                         {"ResourceId"},
			"get-firewall-domain-list":                    {"FirewallDomainListId"},
			"get-firewall-rule-group":                     {"FirewallRuleGroupId"},
			"get-firewall-rule-group-association":         {"FirewallRuleGroupAssociationId"},
			"get-firewall-rule-group-policy":              {"Arn"},
			"get-outpost-resolver":                        {"Id"},
			"get-resolver-config":                         {"ResourceId"},
			"get-resolver-dnssec-config":                  {"ResourceId"},
			"get-resolver-endpoint":                       {"ResolverEndpointId"},
			"get-resolver-query-log-config":               {"ResolverQueryLogConfigId"},
			"get-resolver-query-log-config-association":   {"ResolverQueryLogConfigAssociationId"},
			"get-resolver-query-log-config-policy":        {"Arn"},
			"get-resolver-rule":                           {"ResolverRuleId"},
			"get-resolver-rule-association":               {"ResolverRuleAssociationId"},
			"get-resolver-rule-policy":                    {"Arn"},
			"import-firewall-domains":                     {"DomainFileUrl", "FirewallDomainListId", "Operation"},
			"list-firewall-configs":                       {"MaxResults", "NextToken"},
			"list-firewall-domain-lists":                  {"MaxResults", "NextToken"},
			"list-firewall-domains":                       {"FirewallDomainListId", "MaxResults", "NextToken"},
			"list-firewall-rule-group-associations":       {"FirewallRuleGroupId", "MaxResults", "NextToken", "Priority", "Status", "VpcId"},
			"list-firewall-rule-groups":                   {"MaxResults", "NextToken"},
			"list-firewall-rules":                         {"Action", "FirewallRuleGroupId", "MaxResults", "NextToken", "Priority"},
			"list-outpost-resolvers":                      {"MaxResults", "NextToken", "OutpostArn"},
			"list-resolver-configs":                       {"MaxResults", "NextToken"},
			"list-resolver-dnssec-configs":                {"Filters", "MaxResults", "NextToken"},
			"list-resolver-endpoint-ip-addresses":         {"MaxResults", "NextToken", "ResolverEndpointId"},
			"list-resolver-endpoints":                     {"Filters", "MaxResults", "NextToken"},
			"list-resolver-query-log-config-associations": {"Filters", "MaxResults", "NextToken", "SortBy", "SortOrder"},
			"list-resolver-query-log-configs":             {"Filters", "MaxResults", "NextToken", "SortBy", "SortOrder"},
			"list-resolver-rule-associations":             {"Filters", "MaxResults", "NextToken"},
			"list-resolver-rules":                         {"Filters", "MaxResults", "NextToken"},
			"list-tags-for-resource":                      {"MaxResults", "NextToken", "ResourceArn"},
			"put-firewall-rule-group-policy":              {"Arn", "FirewallRuleGroupPolicy"},
			"put-resolver-query-log-config-policy":        {"Arn", "ResolverQueryLogConfigPolicy"},
			"put-resolver-rule-policy":                    {"Arn", "ResolverRulePolicy"},
			"tag-resource":                                {"ResourceArn", "Tags"},
			"untag-resource":                              {"ResourceArn", "TagKeys"},
			"update-firewall-config":                      {"FirewallFailOpen", "ResourceId"},
			"update-firewall-domains":                     {"Domains", "FirewallDomainListId", "Operation"},
			"update-firewall-rule":                        {"Action", "BlockOverrideDnsType", "BlockOverrideDomain", "BlockOverrideTtl", "BlockResponse", "ConfidenceThreshold", "DnsThreatProtection", "FirewallDomainListId", "FirewallDomainRedirectionAction", "FirewallRuleGroupId", "FirewallThreatProtectionId", "Name", "Priority", "Qtype"},
			"update-firewall-rule-group-association":      {"FirewallRuleGroupAssociationId", "MutationProtection", "Name", "Priority"},
			"update-outpost-resolver":                     {"Id", "InstanceCount", "Name", "PreferredInstanceType"},
			"update-resolver-config":                      {"AutodefinedReverseFlag", "ResourceId"},
			"update-resolver-dnssec-config":               {"ResourceId", "Validation"},
			"update-resolver-endpoint":                    {"Name", "Protocols", "ResolverEndpointId", "ResolverEndpointType", "RniEnhancedMetricsEnabled", "TargetNameServerMetricsEnabled", "UpdateIpAddresses"},
			"update-resolver-rule":                        {"Config", "ResolverRuleId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-firewall-rule-group":               {"CreatorRequestId": "*string", "FirewallRuleGroupId": "*string", "MutationProtection": "types.MutationProtectionStatus", "Name": "*string", "Priority": "*int32", "Tags": "[]types.Tag", "VpcId": "*string"},
			"associate-resolver-endpoint-ip-address":      {"IpAddress": "*types.IpAddressUpdate", "ResolverEndpointId": "*string"},
			"associate-resolver-query-log-config":         {"ResolverQueryLogConfigId": "*string", "ResourceId": "*string"},
			"associate-resolver-rule":                     {"Name": "*string", "ResolverRuleId": "*string", "VPCId": "*string"},
			"create-firewall-domain-list":                 {"CreatorRequestId": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"create-firewall-rule":                        {"Action": "types.Action", "BlockOverrideDnsType": "types.BlockOverrideDnsType", "BlockOverrideDomain": "*string", "BlockOverrideTtl": "*int32", "BlockResponse": "types.BlockResponse", "ConfidenceThreshold": "types.ConfidenceThreshold", "CreatorRequestId": "*string", "DnsThreatProtection": "types.DnsThreatProtection", "FirewallDomainListId": "*string", "FirewallDomainRedirectionAction": "types.FirewallDomainRedirectionAction", "FirewallRuleGroupId": "*string", "Name": "*string", "Priority": "*int32", "Qtype": "*string"},
			"create-firewall-rule-group":                  {"CreatorRequestId": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"create-outpost-resolver":                     {"CreatorRequestId": "*string", "InstanceCount": "*int32", "Name": "*string", "OutpostArn": "*string", "PreferredInstanceType": "*string", "Tags": "[]types.Tag"},
			"create-resolver-endpoint":                    {"CreatorRequestId": "*string", "Direction": "types.ResolverEndpointDirection", "IpAddresses": "[]types.IpAddressRequest", "Name": "*string", "OutpostArn": "*string", "PreferredInstanceType": "*string", "Protocols": "[]types.Protocol", "ResolverEndpointType": "types.ResolverEndpointType", "RniEnhancedMetricsEnabled": "*bool", "SecurityGroupIds": "[]string", "Tags": "[]types.Tag", "TargetNameServerMetricsEnabled": "*bool"},
			"create-resolver-query-log-config":            {"CreatorRequestId": "*string", "DestinationArn": "*string", "Name": "*string", "Tags": "[]types.Tag"},
			"create-resolver-rule":                        {"CreatorRequestId": "*string", "DelegationRecord": "*string", "DomainName": "*string", "Name": "*string", "ResolverEndpointId": "*string", "RuleType": "types.RuleTypeOption", "Tags": "[]types.Tag", "TargetIps": "[]types.TargetAddress"},
			"delete-firewall-domain-list":                 {"FirewallDomainListId": "*string"},
			"delete-firewall-rule":                        {"FirewallDomainListId": "*string", "FirewallRuleGroupId": "*string", "FirewallThreatProtectionId": "*string", "Qtype": "*string"},
			"delete-firewall-rule-group":                  {"FirewallRuleGroupId": "*string"},
			"delete-outpost-resolver":                     {"Id": "*string"},
			"delete-resolver-endpoint":                    {"ResolverEndpointId": "*string"},
			"delete-resolver-query-log-config":            {"ResolverQueryLogConfigId": "*string"},
			"delete-resolver-rule":                        {"ResolverRuleId": "*string"},
			"disassociate-firewall-rule-group":            {"FirewallRuleGroupAssociationId": "*string"},
			"disassociate-resolver-endpoint-ip-address":   {"IpAddress": "*types.IpAddressUpdate", "ResolverEndpointId": "*string"},
			"disassociate-resolver-query-log-config":      {"ResolverQueryLogConfigId": "*string", "ResourceId": "*string"},
			"disassociate-resolver-rule":                  {"ResolverRuleId": "*string", "VPCId": "*string"},
			"get-firewall-config":                         {"ResourceId": "*string"},
			"get-firewall-domain-list":                    {"FirewallDomainListId": "*string"},
			"get-firewall-rule-group":                     {"FirewallRuleGroupId": "*string"},
			"get-firewall-rule-group-association":         {"FirewallRuleGroupAssociationId": "*string"},
			"get-firewall-rule-group-policy":              {"Arn": "*string"},
			"get-outpost-resolver":                        {"Id": "*string"},
			"get-resolver-config":                         {"ResourceId": "*string"},
			"get-resolver-dnssec-config":                  {"ResourceId": "*string"},
			"get-resolver-endpoint":                       {"ResolverEndpointId": "*string"},
			"get-resolver-query-log-config":               {"ResolverQueryLogConfigId": "*string"},
			"get-resolver-query-log-config-association":   {"ResolverQueryLogConfigAssociationId": "*string"},
			"get-resolver-query-log-config-policy":        {"Arn": "*string"},
			"get-resolver-rule":                           {"ResolverRuleId": "*string"},
			"get-resolver-rule-association":               {"ResolverRuleAssociationId": "*string"},
			"get-resolver-rule-policy":                    {"Arn": "*string"},
			"import-firewall-domains":                     {"DomainFileUrl": "*string", "FirewallDomainListId": "*string", "Operation": "types.FirewallDomainImportOperation"},
			"list-firewall-configs":                       {"MaxResults": "*int32", "NextToken": "*string"},
			"list-firewall-domain-lists":                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-firewall-domains":                       {"FirewallDomainListId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-firewall-rule-group-associations":       {"FirewallRuleGroupId": "*string", "MaxResults": "*int32", "NextToken": "*string", "Priority": "*int32", "Status": "types.FirewallRuleGroupAssociationStatus", "VpcId": "*string"},
			"list-firewall-rule-groups":                   {"MaxResults": "*int32", "NextToken": "*string"},
			"list-firewall-rules":                         {"Action": "types.Action", "FirewallRuleGroupId": "*string", "MaxResults": "*int32", "NextToken": "*string", "Priority": "*int32"},
			"list-outpost-resolvers":                      {"MaxResults": "*int32", "NextToken": "*string", "OutpostArn": "*string"},
			"list-resolver-configs":                       {"MaxResults": "*int32", "NextToken": "*string"},
			"list-resolver-dnssec-configs":                {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-resolver-endpoint-ip-addresses":         {"MaxResults": "*int32", "NextToken": "*string", "ResolverEndpointId": "*string"},
			"list-resolver-endpoints":                     {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-resolver-query-log-config-associations": {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string", "SortBy": "*string", "SortOrder": "types.SortOrder"},
			"list-resolver-query-log-configs":             {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string", "SortBy": "*string", "SortOrder": "types.SortOrder"},
			"list-resolver-rule-associations":             {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-resolver-rules":                         {"Filters": "[]types.Filter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                      {"MaxResults": "*int32", "NextToken": "*string", "ResourceArn": "*string"},
			"put-firewall-rule-group-policy":              {"Arn": "*string", "FirewallRuleGroupPolicy": "*string"},
			"put-resolver-query-log-config-policy":        {"Arn": "*string", "ResolverQueryLogConfigPolicy": "*string"},
			"put-resolver-rule-policy":                    {"Arn": "*string", "ResolverRulePolicy": "*string"},
			"tag-resource":                                {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                              {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-firewall-config":                      {"FirewallFailOpen": "types.FirewallFailOpenStatus", "ResourceId": "*string"},
			"update-firewall-domains":                     {"Domains": "[]string", "FirewallDomainListId": "*string", "Operation": "types.FirewallDomainUpdateOperation"},
			"update-firewall-rule":                        {"Action": "types.Action", "BlockOverrideDnsType": "types.BlockOverrideDnsType", "BlockOverrideDomain": "*string", "BlockOverrideTtl": "*int32", "BlockResponse": "types.BlockResponse", "ConfidenceThreshold": "types.ConfidenceThreshold", "DnsThreatProtection": "types.DnsThreatProtection", "FirewallDomainListId": "*string", "FirewallDomainRedirectionAction": "types.FirewallDomainRedirectionAction", "FirewallRuleGroupId": "*string", "FirewallThreatProtectionId": "*string", "Name": "*string", "Priority": "*int32", "Qtype": "*string"},
			"update-firewall-rule-group-association":      {"FirewallRuleGroupAssociationId": "*string", "MutationProtection": "types.MutationProtectionStatus", "Name": "*string", "Priority": "*int32"},
			"update-outpost-resolver":                     {"Id": "*string", "InstanceCount": "*int32", "Name": "*string", "PreferredInstanceType": "*string"},
			"update-resolver-config":                      {"AutodefinedReverseFlag": "types.AutodefinedReverseFlag", "ResourceId": "*string"},
			"update-resolver-dnssec-config":               {"ResourceId": "*string", "Validation": "types.Validation"},
			"update-resolver-endpoint":                    {"Name": "*string", "Protocols": "[]types.Protocol", "ResolverEndpointId": "*string", "ResolverEndpointType": "types.ResolverEndpointType", "RniEnhancedMetricsEnabled": "*bool", "TargetNameServerMetricsEnabled": "*bool", "UpdateIpAddresses": "[]types.UpdateIpAddress"},
			"update-resolver-rule":                        {"Config": "*types.ResolverRuleConfig", "ResolverRuleId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"associate-firewall-rule-group":               {"CreatorRequestId", "FirewallRuleGroupId", "Name", "Priority", "VpcId"},
			"associate-resolver-endpoint-ip-address":      {"IpAddress", "ResolverEndpointId"},
			"associate-resolver-query-log-config":         {"ResolverQueryLogConfigId", "ResourceId"},
			"associate-resolver-rule":                     {"ResolverRuleId", "VPCId"},
			"create-firewall-domain-list":                 {"CreatorRequestId", "Name"},
			"create-firewall-rule":                        {"Action", "CreatorRequestId", "FirewallRuleGroupId", "Name", "Priority"},
			"create-firewall-rule-group":                  {"CreatorRequestId", "Name"},
			"create-outpost-resolver":                     {"CreatorRequestId", "Name", "OutpostArn", "PreferredInstanceType"},
			"create-resolver-endpoint":                    {"CreatorRequestId", "Direction", "IpAddresses", "SecurityGroupIds"},
			"create-resolver-query-log-config":            {"CreatorRequestId", "DestinationArn", "Name"},
			"create-resolver-rule":                        {"CreatorRequestId", "RuleType"},
			"delete-firewall-domain-list":                 {"FirewallDomainListId"},
			"delete-firewall-rule":                        {"FirewallRuleGroupId"},
			"delete-firewall-rule-group":                  {"FirewallRuleGroupId"},
			"delete-outpost-resolver":                     {"Id"},
			"delete-resolver-endpoint":                    {"ResolverEndpointId"},
			"delete-resolver-query-log-config":            {"ResolverQueryLogConfigId"},
			"delete-resolver-rule":                        {"ResolverRuleId"},
			"disassociate-firewall-rule-group":            {"FirewallRuleGroupAssociationId"},
			"disassociate-resolver-endpoint-ip-address":   {"IpAddress", "ResolverEndpointId"},
			"disassociate-resolver-query-log-config":      {"ResolverQueryLogConfigId", "ResourceId"},
			"disassociate-resolver-rule":                  {"ResolverRuleId", "VPCId"},
			"get-firewall-config":                         {"ResourceId"},
			"get-firewall-domain-list":                    {"FirewallDomainListId"},
			"get-firewall-rule-group":                     {"FirewallRuleGroupId"},
			"get-firewall-rule-group-association":         {"FirewallRuleGroupAssociationId"},
			"get-firewall-rule-group-policy":              {"Arn"},
			"get-outpost-resolver":                        {"Id"},
			"get-resolver-config":                         {"ResourceId"},
			"get-resolver-dnssec-config":                  {"ResourceId"},
			"get-resolver-endpoint":                       {"ResolverEndpointId"},
			"get-resolver-query-log-config":               {"ResolverQueryLogConfigId"},
			"get-resolver-query-log-config-association":   {"ResolverQueryLogConfigAssociationId"},
			"get-resolver-query-log-config-policy":        {"Arn"},
			"get-resolver-rule":                           {"ResolverRuleId"},
			"get-resolver-rule-association":               {"ResolverRuleAssociationId"},
			"get-resolver-rule-policy":                    {"Arn"},
			"import-firewall-domains":                     {"DomainFileUrl", "FirewallDomainListId", "Operation"},
			"list-firewall-configs":                       {},
			"list-firewall-domain-lists":                  {},
			"list-firewall-domains":                       {"FirewallDomainListId"},
			"list-firewall-rule-group-associations":       {},
			"list-firewall-rule-groups":                   {},
			"list-firewall-rules":                         {"FirewallRuleGroupId"},
			"list-outpost-resolvers":                      {},
			"list-resolver-configs":                       {},
			"list-resolver-dnssec-configs":                {},
			"list-resolver-endpoint-ip-addresses":         {"ResolverEndpointId"},
			"list-resolver-endpoints":                     {},
			"list-resolver-query-log-config-associations": {},
			"list-resolver-query-log-configs":             {},
			"list-resolver-rule-associations":             {},
			"list-resolver-rules":                         {},
			"list-tags-for-resource":                      {"ResourceArn"},
			"put-firewall-rule-group-policy":              {"Arn", "FirewallRuleGroupPolicy"},
			"put-resolver-query-log-config-policy":        {"Arn", "ResolverQueryLogConfigPolicy"},
			"put-resolver-rule-policy":                    {"Arn", "ResolverRulePolicy"},
			"tag-resource":                                {"ResourceArn", "Tags"},
			"untag-resource":                              {"ResourceArn", "TagKeys"},
			"update-firewall-config":                      {"FirewallFailOpen", "ResourceId"},
			"update-firewall-domains":                     {"Domains", "FirewallDomainListId", "Operation"},
			"update-firewall-rule":                        {"FirewallRuleGroupId"},
			"update-firewall-rule-group-association":      {"FirewallRuleGroupAssociationId"},
			"update-outpost-resolver":                     {"Id"},
			"update-resolver-config":                      {"AutodefinedReverseFlag", "ResourceId"},
			"update-resolver-dnssec-config":               {"ResourceId", "Validation"},
			"update-resolver-endpoint":                    {"ResolverEndpointId"},
			"update-resolver-rule":                        {"Config", "ResolverRuleId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("route53resolver", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
