package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/medialive/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-input-device-transfer", "batch-delete", "batch-start", "batch-stop", "batch-update-schedule", "cancel-input-device-transfer", "claim-device", "create-channel", "create-channel-placement-group", "create-cloud-watch-alarm-template", "create-cloud-watch-alarm-template-group", "create-cluster", "create-event-bridge-rule-template", "create-event-bridge-rule-template-group", "create-input", "create-input-security-group", "create-multiplex", "create-multiplex-program", "create-network", "create-node", "create-node-registration-script", "create-partner-input", "create-sdi-source", "create-signal-map", "create-tags", "delete-channel", "delete-channel-placement-group", "delete-cloud-watch-alarm-template", "delete-cloud-watch-alarm-template-group", "delete-cluster", "delete-event-bridge-rule-template", "delete-event-bridge-rule-template-group", "delete-input", "delete-input-security-group", "delete-multiplex", "delete-multiplex-program", "delete-network", "delete-node", "delete-reservation", "delete-schedule", "delete-sdi-source", "delete-signal-map", "delete-tags", "describe-account-configuration", "describe-channel", "describe-channel-placement-group", "describe-cluster", "describe-input", "describe-input-device", "describe-input-device-thumbnail", "describe-input-security-group", "describe-multiplex", "describe-multiplex-program", "describe-network", "describe-node", "describe-offering", "describe-reservation", "describe-schedule", "describe-sdi-source", "describe-thumbnails", "get-cloud-watch-alarm-template", "get-cloud-watch-alarm-template-group", "get-event-bridge-rule-template", "get-event-bridge-rule-template-group", "get-signal-map", "list-alerts", "list-channel-placement-groups", "list-channels", "list-cloud-watch-alarm-template-groups", "list-cloud-watch-alarm-templates", "list-cluster-alerts", "list-clusters", "list-event-bridge-rule-template-groups", "list-event-bridge-rule-templates", "list-input-device-transfers", "list-input-devices", "list-input-security-groups", "list-inputs", "list-multiplex-alerts", "list-multiplex-programs", "list-multiplexes", "list-networks", "list-nodes", "list-offerings", "list-reservations", "list-sdi-sources", "list-signal-maps", "list-tags-for-resource", "list-versions", "purchase-offering", "reboot-input-device", "reject-input-device-transfer", "restart-channel-pipelines", "start-channel", "start-delete-monitor-deployment", "start-input-device", "start-input-device-maintenance-window", "start-monitor-deployment", "start-multiplex", "start-update-signal-map", "stop-channel", "stop-input-device", "stop-multiplex", "transfer-input-device", "update-account-configuration", "update-channel", "update-channel-class", "update-channel-placement-group", "update-cloud-watch-alarm-template", "update-cloud-watch-alarm-template-group", "update-cluster", "update-event-bridge-rule-template", "update-event-bridge-rule-template-group", "update-input", "update-input-device", "update-input-security-group", "update-multiplex", "update-multiplex-program", "update-network", "update-node", "update-node-state", "update-reservation", "update-sdi-source"},
		OperationSet: map[string]bool{"accept-input-device-transfer": true, "batch-delete": true, "batch-start": true, "batch-stop": true, "batch-update-schedule": true, "cancel-input-device-transfer": true, "claim-device": true, "create-channel": true, "create-channel-placement-group": true, "create-cloud-watch-alarm-template": true, "create-cloud-watch-alarm-template-group": true, "create-cluster": true, "create-event-bridge-rule-template": true, "create-event-bridge-rule-template-group": true, "create-input": true, "create-input-security-group": true, "create-multiplex": true, "create-multiplex-program": true, "create-network": true, "create-node": true, "create-node-registration-script": true, "create-partner-input": true, "create-sdi-source": true, "create-signal-map": true, "create-tags": true, "delete-channel": true, "delete-channel-placement-group": true, "delete-cloud-watch-alarm-template": true, "delete-cloud-watch-alarm-template-group": true, "delete-cluster": true, "delete-event-bridge-rule-template": true, "delete-event-bridge-rule-template-group": true, "delete-input": true, "delete-input-security-group": true, "delete-multiplex": true, "delete-multiplex-program": true, "delete-network": true, "delete-node": true, "delete-reservation": true, "delete-schedule": true, "delete-sdi-source": true, "delete-signal-map": true, "delete-tags": true, "describe-account-configuration": true, "describe-channel": true, "describe-channel-placement-group": true, "describe-cluster": true, "describe-input": true, "describe-input-device": true, "describe-input-device-thumbnail": true, "describe-input-security-group": true, "describe-multiplex": true, "describe-multiplex-program": true, "describe-network": true, "describe-node": true, "describe-offering": true, "describe-reservation": true, "describe-schedule": true, "describe-sdi-source": true, "describe-thumbnails": true, "get-cloud-watch-alarm-template": true, "get-cloud-watch-alarm-template-group": true, "get-event-bridge-rule-template": true, "get-event-bridge-rule-template-group": true, "get-signal-map": true, "list-alerts": true, "list-channel-placement-groups": true, "list-channels": true, "list-cloud-watch-alarm-template-groups": true, "list-cloud-watch-alarm-templates": true, "list-cluster-alerts": true, "list-clusters": true, "list-event-bridge-rule-template-groups": true, "list-event-bridge-rule-templates": true, "list-input-device-transfers": true, "list-input-devices": true, "list-input-security-groups": true, "list-inputs": true, "list-multiplex-alerts": true, "list-multiplex-programs": true, "list-multiplexes": true, "list-networks": true, "list-nodes": true, "list-offerings": true, "list-reservations": true, "list-sdi-sources": true, "list-signal-maps": true, "list-tags-for-resource": true, "list-versions": true, "purchase-offering": true, "reboot-input-device": true, "reject-input-device-transfer": true, "restart-channel-pipelines": true, "start-channel": true, "start-delete-monitor-deployment": true, "start-input-device": true, "start-input-device-maintenance-window": true, "start-monitor-deployment": true, "start-multiplex": true, "start-update-signal-map": true, "stop-channel": true, "stop-input-device": true, "stop-multiplex": true, "transfer-input-device": true, "update-account-configuration": true, "update-channel": true, "update-channel-class": true, "update-channel-placement-group": true, "update-cloud-watch-alarm-template": true, "update-cloud-watch-alarm-template-group": true, "update-cluster": true, "update-event-bridge-rule-template": true, "update-event-bridge-rule-template-group": true, "update-input": true, "update-input-device": true, "update-input-security-group": true, "update-multiplex": true, "update-multiplex-program": true, "update-network": true, "update-node": true, "update-node-state": true, "update-reservation": true, "update-sdi-source": true},
		OperationInputs: map[string][]string{
			"accept-input-device-transfer":            {"InputDeviceId"},
			"batch-delete":                            {"ChannelIds", "InputIds", "InputSecurityGroupIds", "MultiplexIds"},
			"batch-start":                             {"ChannelIds", "MultiplexIds"},
			"batch-stop":                              {"ChannelIds", "MultiplexIds"},
			"batch-update-schedule":                   {"ChannelId", "Creates", "Deletes"},
			"cancel-input-device-transfer":            {"InputDeviceId"},
			"claim-device":                            {"Id"},
			"create-channel":                          {"AnywhereSettings", "CdiInputSpecification", "ChannelClass", "ChannelEngineVersion", "ChannelSecurityGroups", "Destinations", "DryRun", "EncoderSettings", "InferenceSettings", "InputAttachments", "InputSpecification", "LinkedChannelSettings", "LogLevel", "Maintenance", "Name", "RequestId", "Reserved", "RoleArn", "Tags", "Vpc"},
			"create-channel-placement-group":          {"ClusterId", "Name", "Nodes", "RequestId", "Tags"},
			"create-cloud-watch-alarm-template":       {"ComparisonOperator", "DatapointsToAlarm", "Description", "EvaluationPeriods", "GroupIdentifier", "MetricName", "Name", "Period", "RequestId", "Statistic", "Tags", "TargetResourceType", "Threshold", "TreatMissingData"},
			"create-cloud-watch-alarm-template-group": {"Description", "Name", "RequestId", "Tags"},
			"create-cluster":                          {"ClusterType", "InstanceRoleArn", "Name", "NetworkSettings", "RequestId", "Tags"},
			"create-event-bridge-rule-template":       {"Description", "EventTargets", "EventType", "GroupIdentifier", "Name", "RequestId", "Tags"},
			"create-event-bridge-rule-template-group": {"Description", "Name", "RequestId", "Tags"},
			"create-input":                            {"Destinations", "InputDevices", "InputNetworkLocation", "InputSecurityGroups", "MediaConnectFlows", "MulticastSettings", "Name", "RequestId", "RoleArn", "RouterSettings", "SdiSources", "Smpte2110ReceiverGroupSettings", "Sources", "SrtSettings", "Tags", "Type", "Vpc"},
			"create-input-security-group":             {"Tags", "WhitelistRules"},
			"create-multiplex":                        {"AvailabilityZones", "MultiplexSettings", "Name", "RequestId", "Tags"},
			"create-multiplex-program":                {"MultiplexId", "MultiplexProgramSettings", "ProgramName", "RequestId"},
			"create-network":                          {"IpPools", "Name", "RequestId", "Routes", "Tags"},
			"create-node":                             {"ClusterId", "Name", "NodeInterfaceMappings", "RequestId", "Role", "Tags"},
			"create-node-registration-script":         {"ClusterId", "Id", "Name", "NodeInterfaceMappings", "RequestId", "Role"},
			"create-partner-input":                    {"InputId", "RequestId", "Tags"},
			"create-sdi-source":                       {"Mode", "Name", "RequestId", "Tags", "Type"},
			"create-signal-map":                       {"CloudWatchAlarmTemplateGroupIdentifiers", "Description", "DiscoveryEntryPointArn", "EventBridgeRuleTemplateGroupIdentifiers", "Name", "RequestId", "Tags"},
			"create-tags":                             {"ResourceArn", "Tags"},
			"delete-channel":                          {"ChannelId"},
			"delete-channel-placement-group":          {"ChannelPlacementGroupId", "ClusterId"},
			"delete-cloud-watch-alarm-template":       {"Identifier"},
			"delete-cloud-watch-alarm-template-group": {"Identifier"},
			"delete-cluster":                          {"ClusterId"},
			"delete-event-bridge-rule-template":       {"Identifier"},
			"delete-event-bridge-rule-template-group": {"Identifier"},
			"delete-input":                            {"InputId"},
			"delete-input-security-group":             {"InputSecurityGroupId"},
			"delete-multiplex":                        {"MultiplexId"},
			"delete-multiplex-program":                {"MultiplexId", "ProgramName"},
			"delete-network":                          {"NetworkId"},
			"delete-node":                             {"ClusterId", "NodeId"},
			"delete-reservation":                      {"ReservationId"},
			"delete-schedule":                         {"ChannelId"},
			"delete-sdi-source":                       {"SdiSourceId"},
			"delete-signal-map":                       {"Identifier"},
			"delete-tags":                             {"ResourceArn", "TagKeys"},
			"describe-account-configuration":          {},
			"describe-channel":                        {"ChannelId"},
			"describe-channel-placement-group":        {"ChannelPlacementGroupId", "ClusterId"},
			"describe-cluster":                        {"ClusterId"},
			"describe-input":                          {"InputId"},
			"describe-input-device":                   {"InputDeviceId"},
			"describe-input-device-thumbnail":         {"Accept", "InputDeviceId"},
			"describe-input-security-group":           {"InputSecurityGroupId"},
			"describe-multiplex":                      {"MultiplexId"},
			"describe-multiplex-program":              {"MultiplexId", "ProgramName"},
			"describe-network":                        {"NetworkId"},
			"describe-node":                           {"ClusterId", "NodeId"},
			"describe-offering":                       {"OfferingId"},
			"describe-reservation":                    {"ReservationId"},
			"describe-schedule":                       {"ChannelId", "MaxResults", "NextToken"},
			"describe-sdi-source":                     {"SdiSourceId"},
			"describe-thumbnails":                     {"ChannelId", "PipelineId", "ThumbnailType"},
			"get-cloud-watch-alarm-template":          {"Identifier"},
			"get-cloud-watch-alarm-template-group":    {"Identifier"},
			"get-event-bridge-rule-template":          {"Identifier"},
			"get-event-bridge-rule-template-group":    {"Identifier"},
			"get-signal-map":                          {"Identifier"},
			"list-alerts":                             {"ChannelId", "MaxResults", "NextToken", "StateFilter"},
			"list-channel-placement-groups":           {"ClusterId", "MaxResults", "NextToken"},
			"list-channels":                           {"MaxResults", "NextToken"},
			"list-cloud-watch-alarm-template-groups":  {"MaxResults", "NextToken", "Scope", "SignalMapIdentifier"},
			"list-cloud-watch-alarm-templates":        {"GroupIdentifier", "MaxResults", "NextToken", "Scope", "SignalMapIdentifier"},
			"list-cluster-alerts":                     {"ClusterId", "MaxResults", "NextToken", "StateFilter"},
			"list-clusters":                           {"MaxResults", "NextToken"},
			"list-event-bridge-rule-template-groups":  {"MaxResults", "NextToken", "SignalMapIdentifier"},
			"list-event-bridge-rule-templates":        {"GroupIdentifier", "MaxResults", "NextToken", "SignalMapIdentifier"},
			"list-input-device-transfers":             {"MaxResults", "NextToken", "TransferType"},
			"list-input-devices":                      {"MaxResults", "NextToken"},
			"list-input-security-groups":              {"MaxResults", "NextToken"},
			"list-inputs":                             {"MaxResults", "NextToken"},
			"list-multiplex-alerts":                   {"MaxResults", "MultiplexId", "NextToken", "StateFilter"},
			"list-multiplex-programs":                 {"MaxResults", "MultiplexId", "NextToken"},
			"list-multiplexes":                        {"MaxResults", "NextToken"},
			"list-networks":                           {"MaxResults", "NextToken"},
			"list-nodes":                              {"ClusterId", "MaxResults", "NextToken"},
			"list-offerings":                          {"ChannelClass", "ChannelConfiguration", "Codec", "Duration", "MaxResults", "MaximumBitrate", "MaximumFramerate", "NextToken", "Resolution", "ResourceType", "SpecialFeature", "VideoQuality"},
			"list-reservations":                       {"ChannelClass", "Codec", "MaxResults", "MaximumBitrate", "MaximumFramerate", "NextToken", "Resolution", "ResourceType", "SpecialFeature", "VideoQuality"},
			"list-sdi-sources":                        {"MaxResults", "NextToken"},
			"list-signal-maps":                        {"CloudWatchAlarmTemplateGroupIdentifier", "EventBridgeRuleTemplateGroupIdentifier", "MaxResults", "NextToken"},
			"list-tags-for-resource":                  {"ResourceArn"},
			"list-versions":                           {},
			"purchase-offering":                       {"Count", "Name", "OfferingId", "RenewalSettings", "RequestId", "Start", "Tags"},
			"reboot-input-device":                     {"Force", "InputDeviceId"},
			"reject-input-device-transfer":            {"InputDeviceId"},
			"restart-channel-pipelines":               {"ChannelId", "PipelineIds"},
			"start-channel":                           {"ChannelId"},
			"start-delete-monitor-deployment":         {"Identifier"},
			"start-input-device":                      {"InputDeviceId"},
			"start-input-device-maintenance-window":   {"InputDeviceId"},
			"start-monitor-deployment":                {"DryRun", "Identifier"},
			"start-multiplex":                         {"MultiplexId"},
			"start-update-signal-map":                 {"CloudWatchAlarmTemplateGroupIdentifiers", "Description", "DiscoveryEntryPointArn", "EventBridgeRuleTemplateGroupIdentifiers", "ForceRediscovery", "Identifier", "Name"},
			"stop-channel":                            {"ChannelId"},
			"stop-input-device":                       {"InputDeviceId"},
			"stop-multiplex":                          {"MultiplexId"},
			"transfer-input-device":                   {"InputDeviceId", "TargetCustomerId", "TargetRegion", "TransferMessage"},
			"update-account-configuration":            {"AccountConfiguration"},
			"update-channel":                          {"AnywhereSettings", "CdiInputSpecification", "ChannelEngineVersion", "ChannelId", "ChannelSecurityGroups", "Destinations", "DryRun", "EncoderSettings", "InferenceSettings", "InputAttachments", "InputSpecification", "LinkedChannelSettings", "LogLevel", "Maintenance", "Name", "RoleArn"},
			"update-channel-class":                    {"ChannelClass", "ChannelId", "Destinations"},
			"update-channel-placement-group":          {"ChannelPlacementGroupId", "ClusterId", "Name", "Nodes"},
			"update-cloud-watch-alarm-template":       {"ComparisonOperator", "DatapointsToAlarm", "Description", "EvaluationPeriods", "GroupIdentifier", "Identifier", "MetricName", "Name", "Period", "Statistic", "TargetResourceType", "Threshold", "TreatMissingData"},
			"update-cloud-watch-alarm-template-group": {"Description", "Identifier"},
			"update-cluster":                          {"ClusterId", "Name", "NetworkSettings"},
			"update-event-bridge-rule-template":       {"Description", "EventTargets", "EventType", "GroupIdentifier", "Identifier", "Name"},
			"update-event-bridge-rule-template-group": {"Description", "Identifier"},
			"update-input":                            {"Destinations", "InputDevices", "InputId", "InputSecurityGroups", "MediaConnectFlows", "MulticastSettings", "Name", "RoleArn", "SdiSources", "Smpte2110ReceiverGroupSettings", "Sources", "SpecialRouterSettings", "SrtSettings"},
			"update-input-device":                     {"AvailabilityZone", "HdDeviceSettings", "InputDeviceId", "Name", "UhdDeviceSettings"},
			"update-input-security-group":             {"InputSecurityGroupId", "Tags", "WhitelistRules"},
			"update-multiplex":                        {"MultiplexId", "MultiplexSettings", "Name", "PacketIdentifiersMapping"},
			"update-multiplex-program":                {"MultiplexId", "MultiplexProgramSettings", "ProgramName"},
			"update-network":                          {"IpPools", "Name", "NetworkId", "Routes"},
			"update-node":                             {"ClusterId", "Name", "NodeId", "Role", "SdiSourceMappings"},
			"update-node-state":                       {"ClusterId", "NodeId", "State"},
			"update-reservation":                      {"Name", "RenewalSettings", "ReservationId"},
			"update-sdi-source":                       {"Mode", "Name", "SdiSourceId", "Type"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-input-device-transfer":            {"InputDeviceId": "*string"},
			"batch-delete":                            {"ChannelIds": "[]string", "InputIds": "[]string", "InputSecurityGroupIds": "[]string", "MultiplexIds": "[]string"},
			"batch-start":                             {"ChannelIds": "[]string", "MultiplexIds": "[]string"},
			"batch-stop":                              {"ChannelIds": "[]string", "MultiplexIds": "[]string"},
			"batch-update-schedule":                   {"ChannelId": "*string", "Creates": "*types.BatchScheduleActionCreateRequest", "Deletes": "*types.BatchScheduleActionDeleteRequest"},
			"cancel-input-device-transfer":            {"InputDeviceId": "*string"},
			"claim-device":                            {"Id": "*string"},
			"create-channel":                          {"AnywhereSettings": "*types.AnywhereSettings", "CdiInputSpecification": "*types.CdiInputSpecification", "ChannelClass": "types.ChannelClass", "ChannelEngineVersion": "*types.ChannelEngineVersionRequest", "ChannelSecurityGroups": "[]string", "Destinations": "[]types.OutputDestination", "DryRun": "*bool", "EncoderSettings": "*types.EncoderSettings", "InferenceSettings": "*types.InferenceSettings", "InputAttachments": "[]types.InputAttachment", "InputSpecification": "*types.InputSpecification", "LinkedChannelSettings": "*types.LinkedChannelSettings", "LogLevel": "types.LogLevel", "Maintenance": "*types.MaintenanceCreateSettings", "Name": "*string", "RequestId": "*string", "Reserved": "*string", "RoleArn": "*string", "Tags": "map[string]string", "Vpc": "*types.VpcOutputSettings"},
			"create-channel-placement-group":          {"ClusterId": "*string", "Name": "*string", "Nodes": "[]string", "RequestId": "*string", "Tags": "map[string]string"},
			"create-cloud-watch-alarm-template":       {"ComparisonOperator": "types.CloudWatchAlarmTemplateComparisonOperator", "DatapointsToAlarm": "*int32", "Description": "*string", "EvaluationPeriods": "*int32", "GroupIdentifier": "*string", "MetricName": "*string", "Name": "*string", "Period": "*int32", "RequestId": "*string", "Statistic": "types.CloudWatchAlarmTemplateStatistic", "Tags": "map[string]string", "TargetResourceType": "types.CloudWatchAlarmTemplateTargetResourceType", "Threshold": "*float64", "TreatMissingData": "types.CloudWatchAlarmTemplateTreatMissingData"},
			"create-cloud-watch-alarm-template-group": {"Description": "*string", "Name": "*string", "RequestId": "*string", "Tags": "map[string]string"},
			"create-cluster":                          {"ClusterType": "types.ClusterType", "InstanceRoleArn": "*string", "Name": "*string", "NetworkSettings": "*types.ClusterNetworkSettingsCreateRequest", "RequestId": "*string", "Tags": "map[string]string"},
			"create-event-bridge-rule-template":       {"Description": "*string", "EventTargets": "[]types.EventBridgeRuleTemplateTarget", "EventType": "types.EventBridgeRuleTemplateEventType", "GroupIdentifier": "*string", "Name": "*string", "RequestId": "*string", "Tags": "map[string]string"},
			"create-event-bridge-rule-template-group": {"Description": "*string", "Name": "*string", "RequestId": "*string", "Tags": "map[string]string"},
			"create-input":                            {"Destinations": "[]types.InputDestinationRequest", "InputDevices": "[]types.InputDeviceSettings", "InputNetworkLocation": "types.InputNetworkLocation", "InputSecurityGroups": "[]string", "MediaConnectFlows": "[]types.MediaConnectFlowRequest", "MulticastSettings": "*types.MulticastSettingsCreateRequest", "Name": "*string", "RequestId": "*string", "RoleArn": "*string", "RouterSettings": "*types.RouterSettings", "SdiSources": "[]string", "Smpte2110ReceiverGroupSettings": "*types.Smpte2110ReceiverGroupSettings", "Sources": "[]types.InputSourceRequest", "SrtSettings": "*types.SrtSettingsRequest", "Tags": "map[string]string", "Type": "types.InputType", "Vpc": "*types.InputVpcRequest"},
			"create-input-security-group":             {"Tags": "map[string]string", "WhitelistRules": "[]types.InputWhitelistRuleCidr"},
			"create-multiplex":                        {"AvailabilityZones": "[]string", "MultiplexSettings": "*types.MultiplexSettings", "Name": "*string", "RequestId": "*string", "Tags": "map[string]string"},
			"create-multiplex-program":                {"MultiplexId": "*string", "MultiplexProgramSettings": "*types.MultiplexProgramSettings", "ProgramName": "*string", "RequestId": "*string"},
			"create-network":                          {"IpPools": "[]types.IpPoolCreateRequest", "Name": "*string", "RequestId": "*string", "Routes": "[]types.RouteCreateRequest", "Tags": "map[string]string"},
			"create-node":                             {"ClusterId": "*string", "Name": "*string", "NodeInterfaceMappings": "[]types.NodeInterfaceMappingCreateRequest", "RequestId": "*string", "Role": "types.NodeRole", "Tags": "map[string]string"},
			"create-node-registration-script":         {"ClusterId": "*string", "Id": "*string", "Name": "*string", "NodeInterfaceMappings": "[]types.NodeInterfaceMapping", "RequestId": "*string", "Role": "types.NodeRole"},
			"create-partner-input":                    {"InputId": "*string", "RequestId": "*string", "Tags": "map[string]string"},
			"create-sdi-source":                       {"Mode": "types.SdiSourceMode", "Name": "*string", "RequestId": "*string", "Tags": "map[string]string", "Type": "types.SdiSourceType"},
			"create-signal-map":                       {"CloudWatchAlarmTemplateGroupIdentifiers": "[]string", "Description": "*string", "DiscoveryEntryPointArn": "*string", "EventBridgeRuleTemplateGroupIdentifiers": "[]string", "Name": "*string", "RequestId": "*string", "Tags": "map[string]string"},
			"create-tags":                             {"ResourceArn": "*string", "Tags": "map[string]string"},
			"delete-channel":                          {"ChannelId": "*string"},
			"delete-channel-placement-group":          {"ChannelPlacementGroupId": "*string", "ClusterId": "*string"},
			"delete-cloud-watch-alarm-template":       {"Identifier": "*string"},
			"delete-cloud-watch-alarm-template-group": {"Identifier": "*string"},
			"delete-cluster":                          {"ClusterId": "*string"},
			"delete-event-bridge-rule-template":       {"Identifier": "*string"},
			"delete-event-bridge-rule-template-group": {"Identifier": "*string"},
			"delete-input":                            {"InputId": "*string"},
			"delete-input-security-group":             {"InputSecurityGroupId": "*string"},
			"delete-multiplex":                        {"MultiplexId": "*string"},
			"delete-multiplex-program":                {"MultiplexId": "*string", "ProgramName": "*string"},
			"delete-network":                          {"NetworkId": "*string"},
			"delete-node":                             {"ClusterId": "*string", "NodeId": "*string"},
			"delete-reservation":                      {"ReservationId": "*string"},
			"delete-schedule":                         {"ChannelId": "*string"},
			"delete-sdi-source":                       {"SdiSourceId": "*string"},
			"delete-signal-map":                       {"Identifier": "*string"},
			"delete-tags":                             {"ResourceArn": "*string", "TagKeys": "[]string"},
			"describe-account-configuration":          {},
			"describe-channel":                        {"ChannelId": "*string"},
			"describe-channel-placement-group":        {"ChannelPlacementGroupId": "*string", "ClusterId": "*string"},
			"describe-cluster":                        {"ClusterId": "*string"},
			"describe-input":                          {"InputId": "*string"},
			"describe-input-device":                   {"InputDeviceId": "*string"},
			"describe-input-device-thumbnail":         {"Accept": "types.AcceptHeader", "InputDeviceId": "*string"},
			"describe-input-security-group":           {"InputSecurityGroupId": "*string"},
			"describe-multiplex":                      {"MultiplexId": "*string"},
			"describe-multiplex-program":              {"MultiplexId": "*string", "ProgramName": "*string"},
			"describe-network":                        {"NetworkId": "*string"},
			"describe-node":                           {"ClusterId": "*string", "NodeId": "*string"},
			"describe-offering":                       {"OfferingId": "*string"},
			"describe-reservation":                    {"ReservationId": "*string"},
			"describe-schedule":                       {"ChannelId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-sdi-source":                     {"SdiSourceId": "*string"},
			"describe-thumbnails":                     {"ChannelId": "*string", "PipelineId": "*string", "ThumbnailType": "*string"},
			"get-cloud-watch-alarm-template":          {"Identifier": "*string"},
			"get-cloud-watch-alarm-template-group":    {"Identifier": "*string"},
			"get-event-bridge-rule-template":          {"Identifier": "*string"},
			"get-event-bridge-rule-template-group":    {"Identifier": "*string"},
			"get-signal-map":                          {"Identifier": "*string"},
			"list-alerts":                             {"ChannelId": "*string", "MaxResults": "*int32", "NextToken": "*string", "StateFilter": "*string"},
			"list-channel-placement-groups":           {"ClusterId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-channels":                           {"MaxResults": "*int32", "NextToken": "*string"},
			"list-cloud-watch-alarm-template-groups":  {"MaxResults": "*int32", "NextToken": "*string", "Scope": "*string", "SignalMapIdentifier": "*string"},
			"list-cloud-watch-alarm-templates":        {"GroupIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "Scope": "*string", "SignalMapIdentifier": "*string"},
			"list-cluster-alerts":                     {"ClusterId": "*string", "MaxResults": "*int32", "NextToken": "*string", "StateFilter": "*string"},
			"list-clusters":                           {"MaxResults": "*int32", "NextToken": "*string"},
			"list-event-bridge-rule-template-groups":  {"MaxResults": "*int32", "NextToken": "*string", "SignalMapIdentifier": "*string"},
			"list-event-bridge-rule-templates":        {"GroupIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "SignalMapIdentifier": "*string"},
			"list-input-device-transfers":             {"MaxResults": "*int32", "NextToken": "*string", "TransferType": "*string"},
			"list-input-devices":                      {"MaxResults": "*int32", "NextToken": "*string"},
			"list-input-security-groups":              {"MaxResults": "*int32", "NextToken": "*string"},
			"list-inputs":                             {"MaxResults": "*int32", "NextToken": "*string"},
			"list-multiplex-alerts":                   {"MaxResults": "*int32", "MultiplexId": "*string", "NextToken": "*string", "StateFilter": "*string"},
			"list-multiplex-programs":                 {"MaxResults": "*int32", "MultiplexId": "*string", "NextToken": "*string"},
			"list-multiplexes":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-networks":                           {"MaxResults": "*int32", "NextToken": "*string"},
			"list-nodes":                              {"ClusterId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-offerings":                          {"ChannelClass": "*string", "ChannelConfiguration": "*string", "Codec": "*string", "Duration": "*string", "MaxResults": "*int32", "MaximumBitrate": "*string", "MaximumFramerate": "*string", "NextToken": "*string", "Resolution": "*string", "ResourceType": "*string", "SpecialFeature": "*string", "VideoQuality": "*string"},
			"list-reservations":                       {"ChannelClass": "*string", "Codec": "*string", "MaxResults": "*int32", "MaximumBitrate": "*string", "MaximumFramerate": "*string", "NextToken": "*string", "Resolution": "*string", "ResourceType": "*string", "SpecialFeature": "*string", "VideoQuality": "*string"},
			"list-sdi-sources":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-signal-maps":                        {"CloudWatchAlarmTemplateGroupIdentifier": "*string", "EventBridgeRuleTemplateGroupIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                  {"ResourceArn": "*string"},
			"list-versions":                           {},
			"purchase-offering":                       {"Count": "*int32", "Name": "*string", "OfferingId": "*string", "RenewalSettings": "*types.RenewalSettings", "RequestId": "*string", "Start": "*string", "Tags": "map[string]string"},
			"reboot-input-device":                     {"Force": "types.RebootInputDeviceForce", "InputDeviceId": "*string"},
			"reject-input-device-transfer":            {"InputDeviceId": "*string"},
			"restart-channel-pipelines":               {"ChannelId": "*string", "PipelineIds": "[]types.ChannelPipelineIdToRestart"},
			"start-channel":                           {"ChannelId": "*string"},
			"start-delete-monitor-deployment":         {"Identifier": "*string"},
			"start-input-device":                      {"InputDeviceId": "*string"},
			"start-input-device-maintenance-window":   {"InputDeviceId": "*string"},
			"start-monitor-deployment":                {"DryRun": "*bool", "Identifier": "*string"},
			"start-multiplex":                         {"MultiplexId": "*string"},
			"start-update-signal-map":                 {"CloudWatchAlarmTemplateGroupIdentifiers": "[]string", "Description": "*string", "DiscoveryEntryPointArn": "*string", "EventBridgeRuleTemplateGroupIdentifiers": "[]string", "ForceRediscovery": "*bool", "Identifier": "*string", "Name": "*string"},
			"stop-channel":                            {"ChannelId": "*string"},
			"stop-input-device":                       {"InputDeviceId": "*string"},
			"stop-multiplex":                          {"MultiplexId": "*string"},
			"transfer-input-device":                   {"InputDeviceId": "*string", "TargetCustomerId": "*string", "TargetRegion": "*string", "TransferMessage": "*string"},
			"update-account-configuration":            {"AccountConfiguration": "*types.AccountConfiguration"},
			"update-channel":                          {"AnywhereSettings": "*types.AnywhereSettings", "CdiInputSpecification": "*types.CdiInputSpecification", "ChannelEngineVersion": "*types.ChannelEngineVersionRequest", "ChannelId": "*string", "ChannelSecurityGroups": "[]string", "Destinations": "[]types.OutputDestination", "DryRun": "*bool", "EncoderSettings": "*types.EncoderSettings", "InferenceSettings": "*types.InferenceSettings", "InputAttachments": "[]types.InputAttachment", "InputSpecification": "*types.InputSpecification", "LinkedChannelSettings": "*types.LinkedChannelSettings", "LogLevel": "types.LogLevel", "Maintenance": "*types.MaintenanceUpdateSettings", "Name": "*string", "RoleArn": "*string"},
			"update-channel-class":                    {"ChannelClass": "types.ChannelClass", "ChannelId": "*string", "Destinations": "[]types.OutputDestination"},
			"update-channel-placement-group":          {"ChannelPlacementGroupId": "*string", "ClusterId": "*string", "Name": "*string", "Nodes": "[]string"},
			"update-cloud-watch-alarm-template":       {"ComparisonOperator": "types.CloudWatchAlarmTemplateComparisonOperator", "DatapointsToAlarm": "*int32", "Description": "*string", "EvaluationPeriods": "*int32", "GroupIdentifier": "*string", "Identifier": "*string", "MetricName": "*string", "Name": "*string", "Period": "*int32", "Statistic": "types.CloudWatchAlarmTemplateStatistic", "TargetResourceType": "types.CloudWatchAlarmTemplateTargetResourceType", "Threshold": "*float64", "TreatMissingData": "types.CloudWatchAlarmTemplateTreatMissingData"},
			"update-cloud-watch-alarm-template-group": {"Description": "*string", "Identifier": "*string"},
			"update-cluster":                          {"ClusterId": "*string", "Name": "*string", "NetworkSettings": "*types.ClusterNetworkSettingsUpdateRequest"},
			"update-event-bridge-rule-template":       {"Description": "*string", "EventTargets": "[]types.EventBridgeRuleTemplateTarget", "EventType": "types.EventBridgeRuleTemplateEventType", "GroupIdentifier": "*string", "Identifier": "*string", "Name": "*string"},
			"update-event-bridge-rule-template-group": {"Description": "*string", "Identifier": "*string"},
			"update-input":                            {"Destinations": "[]types.InputDestinationRequest", "InputDevices": "[]types.InputDeviceRequest", "InputId": "*string", "InputSecurityGroups": "[]string", "MediaConnectFlows": "[]types.MediaConnectFlowRequest", "MulticastSettings": "*types.MulticastSettingsUpdateRequest", "Name": "*string", "RoleArn": "*string", "SdiSources": "[]string", "Smpte2110ReceiverGroupSettings": "*types.Smpte2110ReceiverGroupSettings", "Sources": "[]types.InputSourceRequest", "SpecialRouterSettings": "*types.SpecialRouterSettings", "SrtSettings": "*types.SrtSettingsRequest"},
			"update-input-device":                     {"AvailabilityZone": "*string", "HdDeviceSettings": "*types.InputDeviceConfigurableSettings", "InputDeviceId": "*string", "Name": "*string", "UhdDeviceSettings": "*types.InputDeviceConfigurableSettings"},
			"update-input-security-group":             {"InputSecurityGroupId": "*string", "Tags": "map[string]string", "WhitelistRules": "[]types.InputWhitelistRuleCidr"},
			"update-multiplex":                        {"MultiplexId": "*string", "MultiplexSettings": "*types.MultiplexSettings", "Name": "*string", "PacketIdentifiersMapping": "map[string]types.MultiplexProgramPacketIdentifiersMap"},
			"update-multiplex-program":                {"MultiplexId": "*string", "MultiplexProgramSettings": "*types.MultiplexProgramSettings", "ProgramName": "*string"},
			"update-network":                          {"IpPools": "[]types.IpPoolUpdateRequest", "Name": "*string", "NetworkId": "*string", "Routes": "[]types.RouteUpdateRequest"},
			"update-node":                             {"ClusterId": "*string", "Name": "*string", "NodeId": "*string", "Role": "types.NodeRole", "SdiSourceMappings": "[]types.SdiSourceMappingUpdateRequest"},
			"update-node-state":                       {"ClusterId": "*string", "NodeId": "*string", "State": "types.UpdateNodeStateShape"},
			"update-reservation":                      {"Name": "*string", "RenewalSettings": "*types.RenewalSettings", "ReservationId": "*string"},
			"update-sdi-source":                       {"Mode": "types.SdiSourceMode", "Name": "*string", "SdiSourceId": "*string", "Type": "types.SdiSourceType"},
		},
		OperationInputRequired: map[string][]string{
			"accept-input-device-transfer":            {"InputDeviceId"},
			"batch-delete":                            {},
			"batch-start":                             {},
			"batch-stop":                              {},
			"batch-update-schedule":                   {"ChannelId"},
			"cancel-input-device-transfer":            {"InputDeviceId"},
			"claim-device":                            {},
			"create-channel":                          {},
			"create-channel-placement-group":          {"ClusterId"},
			"create-cloud-watch-alarm-template":       {"ComparisonOperator", "EvaluationPeriods", "GroupIdentifier", "MetricName", "Name", "Period", "Statistic", "TargetResourceType", "Threshold", "TreatMissingData"},
			"create-cloud-watch-alarm-template-group": {"Name"},
			"create-cluster":                          {},
			"create-event-bridge-rule-template":       {"EventType", "GroupIdentifier", "Name"},
			"create-event-bridge-rule-template-group": {"Name"},
			"create-input":                            {},
			"create-input-security-group":             {},
			"create-multiplex":                        {"AvailabilityZones", "MultiplexSettings", "Name", "RequestId"},
			"create-multiplex-program":                {"MultiplexId", "MultiplexProgramSettings", "ProgramName", "RequestId"},
			"create-network":                          {},
			"create-node":                             {"ClusterId"},
			"create-node-registration-script":         {"ClusterId"},
			"create-partner-input":                    {"InputId"},
			"create-sdi-source":                       {},
			"create-signal-map":                       {"DiscoveryEntryPointArn", "Name"},
			"create-tags":                             {"ResourceArn"},
			"delete-channel":                          {"ChannelId"},
			"delete-channel-placement-group":          {"ChannelPlacementGroupId", "ClusterId"},
			"delete-cloud-watch-alarm-template":       {"Identifier"},
			"delete-cloud-watch-alarm-template-group": {"Identifier"},
			"delete-cluster":                          {"ClusterId"},
			"delete-event-bridge-rule-template":       {"Identifier"},
			"delete-event-bridge-rule-template-group": {"Identifier"},
			"delete-input":                            {"InputId"},
			"delete-input-security-group":             {"InputSecurityGroupId"},
			"delete-multiplex":                        {"MultiplexId"},
			"delete-multiplex-program":                {"MultiplexId", "ProgramName"},
			"delete-network":                          {"NetworkId"},
			"delete-node":                             {"ClusterId", "NodeId"},
			"delete-reservation":                      {"ReservationId"},
			"delete-schedule":                         {"ChannelId"},
			"delete-sdi-source":                       {"SdiSourceId"},
			"delete-signal-map":                       {"Identifier"},
			"delete-tags":                             {"ResourceArn", "TagKeys"},
			"describe-account-configuration":          {},
			"describe-channel":                        {"ChannelId"},
			"describe-channel-placement-group":        {"ChannelPlacementGroupId", "ClusterId"},
			"describe-cluster":                        {"ClusterId"},
			"describe-input":                          {"InputId"},
			"describe-input-device":                   {"InputDeviceId"},
			"describe-input-device-thumbnail":         {"Accept", "InputDeviceId"},
			"describe-input-security-group":           {"InputSecurityGroupId"},
			"describe-multiplex":                      {"MultiplexId"},
			"describe-multiplex-program":              {"MultiplexId", "ProgramName"},
			"describe-network":                        {"NetworkId"},
			"describe-node":                           {"ClusterId", "NodeId"},
			"describe-offering":                       {"OfferingId"},
			"describe-reservation":                    {"ReservationId"},
			"describe-schedule":                       {"ChannelId"},
			"describe-sdi-source":                     {"SdiSourceId"},
			"describe-thumbnails":                     {"ChannelId", "PipelineId", "ThumbnailType"},
			"get-cloud-watch-alarm-template":          {"Identifier"},
			"get-cloud-watch-alarm-template-group":    {"Identifier"},
			"get-event-bridge-rule-template":          {"Identifier"},
			"get-event-bridge-rule-template-group":    {"Identifier"},
			"get-signal-map":                          {"Identifier"},
			"list-alerts":                             {"ChannelId"},
			"list-channel-placement-groups":           {"ClusterId"},
			"list-channels":                           {},
			"list-cloud-watch-alarm-template-groups":  {},
			"list-cloud-watch-alarm-templates":        {},
			"list-cluster-alerts":                     {"ClusterId"},
			"list-clusters":                           {},
			"list-event-bridge-rule-template-groups":  {},
			"list-event-bridge-rule-templates":        {},
			"list-input-device-transfers":             {"TransferType"},
			"list-input-devices":                      {},
			"list-input-security-groups":              {},
			"list-inputs":                             {},
			"list-multiplex-alerts":                   {"MultiplexId"},
			"list-multiplex-programs":                 {"MultiplexId"},
			"list-multiplexes":                        {},
			"list-networks":                           {},
			"list-nodes":                              {"ClusterId"},
			"list-offerings":                          {},
			"list-reservations":                       {},
			"list-sdi-sources":                        {},
			"list-signal-maps":                        {},
			"list-tags-for-resource":                  {"ResourceArn"},
			"list-versions":                           {},
			"purchase-offering":                       {"Count", "OfferingId"},
			"reboot-input-device":                     {"InputDeviceId"},
			"reject-input-device-transfer":            {"InputDeviceId"},
			"restart-channel-pipelines":               {"ChannelId"},
			"start-channel":                           {"ChannelId"},
			"start-delete-monitor-deployment":         {"Identifier"},
			"start-input-device":                      {"InputDeviceId"},
			"start-input-device-maintenance-window":   {"InputDeviceId"},
			"start-monitor-deployment":                {"Identifier"},
			"start-multiplex":                         {"MultiplexId"},
			"start-update-signal-map":                 {"Identifier"},
			"stop-channel":                            {"ChannelId"},
			"stop-input-device":                       {"InputDeviceId"},
			"stop-multiplex":                          {"MultiplexId"},
			"transfer-input-device":                   {"InputDeviceId"},
			"update-account-configuration":            {},
			"update-channel":                          {"ChannelId"},
			"update-channel-class":                    {"ChannelClass", "ChannelId"},
			"update-channel-placement-group":          {"ChannelPlacementGroupId", "ClusterId"},
			"update-cloud-watch-alarm-template":       {"Identifier"},
			"update-cloud-watch-alarm-template-group": {"Identifier"},
			"update-cluster":                          {"ClusterId"},
			"update-event-bridge-rule-template":       {"Identifier"},
			"update-event-bridge-rule-template-group": {"Identifier"},
			"update-input":                            {"InputId"},
			"update-input-device":                     {"InputDeviceId"},
			"update-input-security-group":             {"InputSecurityGroupId"},
			"update-multiplex":                        {"MultiplexId"},
			"update-multiplex-program":                {"MultiplexId", "ProgramName"},
			"update-network":                          {"NetworkId"},
			"update-node":                             {"ClusterId", "NodeId"},
			"update-node-state":                       {"ClusterId", "NodeId"},
			"update-reservation":                      {"ReservationId"},
			"update-sdi-source":                       {"SdiSourceId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("medialive", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
