package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/cleanrooms/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-get-collaboration-analysis-template", "batch-get-schema", "batch-get-schema-analysis-rule", "create-analysis-template", "create-collaboration", "create-collaboration-change-request", "create-configured-audience-model-association", "create-configured-table", "create-configured-table-analysis-rule", "create-configured-table-association", "create-configured-table-association-analysis-rule", "create-id-mapping-table", "create-id-namespace-association", "create-membership", "create-privacy-budget-template", "delete-analysis-template", "delete-collaboration", "delete-configured-audience-model-association", "delete-configured-table", "delete-configured-table-analysis-rule", "delete-configured-table-association", "delete-configured-table-association-analysis-rule", "delete-id-mapping-table", "delete-id-namespace-association", "delete-member", "delete-membership", "delete-privacy-budget-template", "get-analysis-template", "get-collaboration", "get-collaboration-analysis-template", "get-collaboration-change-request", "get-collaboration-configured-audience-model-association", "get-collaboration-id-namespace-association", "get-collaboration-privacy-budget-template", "get-configured-audience-model-association", "get-configured-table", "get-configured-table-analysis-rule", "get-configured-table-association", "get-configured-table-association-analysis-rule", "get-id-mapping-table", "get-id-namespace-association", "get-membership", "get-privacy-budget-template", "get-protected-job", "get-protected-query", "get-schema", "get-schema-analysis-rule", "list-analysis-templates", "list-collaboration-analysis-templates", "list-collaboration-change-requests", "list-collaboration-configured-audience-model-associations", "list-collaboration-id-namespace-associations", "list-collaboration-privacy-budget-templates", "list-collaboration-privacy-budgets", "list-collaborations", "list-configured-audience-model-associations", "list-configured-table-associations", "list-configured-tables", "list-id-mapping-tables", "list-id-namespace-associations", "list-members", "list-memberships", "list-privacy-budget-templates", "list-privacy-budgets", "list-protected-jobs", "list-protected-queries", "list-schemas", "list-tags-for-resource", "populate-id-mapping-table", "preview-privacy-impact", "start-protected-job", "start-protected-query", "tag-resource", "untag-resource", "update-analysis-template", "update-collaboration", "update-collaboration-change-request", "update-configured-audience-model-association", "update-configured-table", "update-configured-table-analysis-rule", "update-configured-table-association", "update-configured-table-association-analysis-rule", "update-id-mapping-table", "update-id-namespace-association", "update-membership", "update-privacy-budget-template", "update-protected-job", "update-protected-query"},
		OperationSet: map[string]bool{"batch-get-collaboration-analysis-template": true, "batch-get-schema": true, "batch-get-schema-analysis-rule": true, "create-analysis-template": true, "create-collaboration": true, "create-collaboration-change-request": true, "create-configured-audience-model-association": true, "create-configured-table": true, "create-configured-table-analysis-rule": true, "create-configured-table-association": true, "create-configured-table-association-analysis-rule": true, "create-id-mapping-table": true, "create-id-namespace-association": true, "create-membership": true, "create-privacy-budget-template": true, "delete-analysis-template": true, "delete-collaboration": true, "delete-configured-audience-model-association": true, "delete-configured-table": true, "delete-configured-table-analysis-rule": true, "delete-configured-table-association": true, "delete-configured-table-association-analysis-rule": true, "delete-id-mapping-table": true, "delete-id-namespace-association": true, "delete-member": true, "delete-membership": true, "delete-privacy-budget-template": true, "get-analysis-template": true, "get-collaboration": true, "get-collaboration-analysis-template": true, "get-collaboration-change-request": true, "get-collaboration-configured-audience-model-association": true, "get-collaboration-id-namespace-association": true, "get-collaboration-privacy-budget-template": true, "get-configured-audience-model-association": true, "get-configured-table": true, "get-configured-table-analysis-rule": true, "get-configured-table-association": true, "get-configured-table-association-analysis-rule": true, "get-id-mapping-table": true, "get-id-namespace-association": true, "get-membership": true, "get-privacy-budget-template": true, "get-protected-job": true, "get-protected-query": true, "get-schema": true, "get-schema-analysis-rule": true, "list-analysis-templates": true, "list-collaboration-analysis-templates": true, "list-collaboration-change-requests": true, "list-collaboration-configured-audience-model-associations": true, "list-collaboration-id-namespace-associations": true, "list-collaboration-privacy-budget-templates": true, "list-collaboration-privacy-budgets": true, "list-collaborations": true, "list-configured-audience-model-associations": true, "list-configured-table-associations": true, "list-configured-tables": true, "list-id-mapping-tables": true, "list-id-namespace-associations": true, "list-members": true, "list-memberships": true, "list-privacy-budget-templates": true, "list-privacy-budgets": true, "list-protected-jobs": true, "list-protected-queries": true, "list-schemas": true, "list-tags-for-resource": true, "populate-id-mapping-table": true, "preview-privacy-impact": true, "start-protected-job": true, "start-protected-query": true, "tag-resource": true, "untag-resource": true, "update-analysis-template": true, "update-collaboration": true, "update-collaboration-change-request": true, "update-configured-audience-model-association": true, "update-configured-table": true, "update-configured-table-analysis-rule": true, "update-configured-table-association": true, "update-configured-table-association-analysis-rule": true, "update-id-mapping-table": true, "update-id-namespace-association": true, "update-membership": true, "update-privacy-budget-template": true, "update-protected-job": true, "update-protected-query": true},
		OperationInputs: map[string][]string{
			"batch-get-collaboration-analysis-template":                 {"AnalysisTemplateArns", "CollaborationIdentifier"},
			"batch-get-schema":                                          {"CollaborationIdentifier", "Names"},
			"batch-get-schema-analysis-rule":                            {"CollaborationIdentifier", "SchemaAnalysisRuleRequests"},
			"create-analysis-template":                                  {"AnalysisParameters", "Description", "ErrorMessageConfiguration", "Format", "MembershipIdentifier", "Name", "Schema", "Source", "SyntheticDataParameters", "Tags"},
			"create-collaboration":                                      {"AllowedResultRegions", "AnalyticsEngine", "AutoApprovedChangeRequestTypes", "CreatorDisplayName", "CreatorMLMemberAbilities", "CreatorMemberAbilities", "CreatorPaymentConfiguration", "DataEncryptionMetadata", "Description", "IsMetricsEnabled", "JobLogStatus", "Members", "Name", "QueryLogStatus", "Tags"},
			"create-collaboration-change-request":                       {"Changes", "CollaborationIdentifier"},
			"create-configured-audience-model-association":              {"ConfiguredAudienceModelArn", "ConfiguredAudienceModelAssociationName", "Description", "ManageResourcePolicies", "MembershipIdentifier", "Tags"},
			"create-configured-table":                                   {"AllowedColumns", "AnalysisMethod", "Description", "Name", "SelectedAnalysisMethods", "TableReference", "Tags"},
			"create-configured-table-analysis-rule":                     {"AnalysisRulePolicy", "AnalysisRuleType", "ConfiguredTableIdentifier"},
			"create-configured-table-association":                       {"ConfiguredTableIdentifier", "Description", "MembershipIdentifier", "Name", "RoleArn", "Tags"},
			"create-configured-table-association-analysis-rule":         {"AnalysisRulePolicy", "AnalysisRuleType", "ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"create-id-mapping-table":                                   {"Description", "InputReferenceConfig", "KmsKeyArn", "MembershipIdentifier", "Name", "Tags"},
			"create-id-namespace-association":                           {"Description", "IdMappingConfig", "InputReferenceConfig", "MembershipIdentifier", "Name", "Tags"},
			"create-membership":                                         {"CollaborationIdentifier", "DefaultJobResultConfiguration", "DefaultResultConfiguration", "IsMetricsEnabled", "JobLogStatus", "PaymentConfiguration", "QueryLogStatus", "Tags"},
			"create-privacy-budget-template":                            {"AutoRefresh", "MembershipIdentifier", "Parameters", "PrivacyBudgetType", "Tags"},
			"delete-analysis-template":                                  {"AnalysisTemplateIdentifier", "MembershipIdentifier"},
			"delete-collaboration":                                      {"CollaborationIdentifier"},
			"delete-configured-audience-model-association":              {"ConfiguredAudienceModelAssociationIdentifier", "MembershipIdentifier"},
			"delete-configured-table":                                   {"ConfiguredTableIdentifier"},
			"delete-configured-table-analysis-rule":                     {"AnalysisRuleType", "ConfiguredTableIdentifier"},
			"delete-configured-table-association":                       {"ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"delete-configured-table-association-analysis-rule":         {"AnalysisRuleType", "ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"delete-id-mapping-table":                                   {"IdMappingTableIdentifier", "MembershipIdentifier"},
			"delete-id-namespace-association":                           {"IdNamespaceAssociationIdentifier", "MembershipIdentifier"},
			"delete-member":                                             {"AccountId", "CollaborationIdentifier"},
			"delete-membership":                                         {"MembershipIdentifier"},
			"delete-privacy-budget-template":                            {"MembershipIdentifier", "PrivacyBudgetTemplateIdentifier"},
			"get-analysis-template":                                     {"AnalysisTemplateIdentifier", "MembershipIdentifier"},
			"get-collaboration":                                         {"CollaborationIdentifier"},
			"get-collaboration-analysis-template":                       {"AnalysisTemplateArn", "CollaborationIdentifier"},
			"get-collaboration-change-request":                          {"ChangeRequestIdentifier", "CollaborationIdentifier"},
			"get-collaboration-configured-audience-model-association":   {"CollaborationIdentifier", "ConfiguredAudienceModelAssociationIdentifier"},
			"get-collaboration-id-namespace-association":                {"CollaborationIdentifier", "IdNamespaceAssociationIdentifier"},
			"get-collaboration-privacy-budget-template":                 {"CollaborationIdentifier", "PrivacyBudgetTemplateIdentifier"},
			"get-configured-audience-model-association":                 {"ConfiguredAudienceModelAssociationIdentifier", "MembershipIdentifier"},
			"get-configured-table":                                      {"ConfiguredTableIdentifier"},
			"get-configured-table-analysis-rule":                        {"AnalysisRuleType", "ConfiguredTableIdentifier"},
			"get-configured-table-association":                          {"ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"get-configured-table-association-analysis-rule":            {"AnalysisRuleType", "ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"get-id-mapping-table":                                      {"IdMappingTableIdentifier", "MembershipIdentifier"},
			"get-id-namespace-association":                              {"IdNamespaceAssociationIdentifier", "MembershipIdentifier"},
			"get-membership":                                            {"MembershipIdentifier"},
			"get-privacy-budget-template":                               {"MembershipIdentifier", "PrivacyBudgetTemplateIdentifier"},
			"get-protected-job":                                         {"MembershipIdentifier", "ProtectedJobIdentifier"},
			"get-protected-query":                                       {"MembershipIdentifier", "ProtectedQueryIdentifier"},
			"get-schema":                                                {"CollaborationIdentifier", "Name"},
			"get-schema-analysis-rule":                                  {"CollaborationIdentifier", "Name", "Type"},
			"list-analysis-templates":                                   {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-collaboration-analysis-templates":                     {"CollaborationIdentifier", "MaxResults", "NextToken"},
			"list-collaboration-change-requests":                        {"CollaborationIdentifier", "MaxResults", "NextToken", "Status"},
			"list-collaboration-configured-audience-model-associations": {"CollaborationIdentifier", "MaxResults", "NextToken"},
			"list-collaboration-id-namespace-associations":              {"CollaborationIdentifier", "MaxResults", "NextToken"},
			"list-collaboration-privacy-budget-templates":               {"CollaborationIdentifier", "MaxResults", "NextToken"},
			"list-collaboration-privacy-budgets":                        {"AccessBudgetResourceArn", "CollaborationIdentifier", "MaxResults", "NextToken", "PrivacyBudgetType"},
			"list-collaborations":                                       {"MaxResults", "MemberStatus", "NextToken"},
			"list-configured-audience-model-associations":               {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-configured-table-associations":                        {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-configured-tables":                                    {"MaxResults", "NextToken"},
			"list-id-mapping-tables":                                    {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-id-namespace-associations":                            {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-members":                                              {"CollaborationIdentifier", "MaxResults", "NextToken"},
			"list-memberships":                                          {"MaxResults", "NextToken", "Status"},
			"list-privacy-budget-templates":                             {"MaxResults", "MembershipIdentifier", "NextToken"},
			"list-privacy-budgets":                                      {"AccessBudgetResourceArn", "MaxResults", "MembershipIdentifier", "NextToken", "PrivacyBudgetType"},
			"list-protected-jobs":                                       {"MaxResults", "MembershipIdentifier", "NextToken", "Status"},
			"list-protected-queries":                                    {"MaxResults", "MembershipIdentifier", "NextToken", "Status"},
			"list-schemas":                                              {"CollaborationIdentifier", "MaxResults", "NextToken", "SchemaType"},
			"list-tags-for-resource":                                    {"ResourceArn"},
			"populate-id-mapping-table":                                 {"IdMappingTableIdentifier", "JobType", "MembershipIdentifier"},
			"preview-privacy-impact":                                    {"MembershipIdentifier", "Parameters"},
			"start-protected-job":                                       {"ComputeConfiguration", "JobParameters", "MembershipIdentifier", "ResultConfiguration", "Type"},
			"start-protected-query":                                     {"ComputeConfiguration", "MembershipIdentifier", "ResultConfiguration", "SqlParameters", "Type"},
			"tag-resource":                                              {"ResourceArn", "Tags"},
			"untag-resource":                                            {"ResourceArn", "TagKeys"},
			"update-analysis-template":                                  {"AnalysisTemplateIdentifier", "Description", "MembershipIdentifier"},
			"update-collaboration":                                      {"AnalyticsEngine", "CollaborationIdentifier", "Description", "Name"},
			"update-collaboration-change-request":                       {"Action", "ChangeRequestIdentifier", "CollaborationIdentifier"},
			"update-configured-audience-model-association":              {"ConfiguredAudienceModelAssociationIdentifier", "Description", "MembershipIdentifier", "Name"},
			"update-configured-table":                                   {"AllowedColumns", "AnalysisMethod", "ConfiguredTableIdentifier", "Description", "Name", "SelectedAnalysisMethods", "TableReference"},
			"update-configured-table-analysis-rule":                     {"AnalysisRulePolicy", "AnalysisRuleType", "ConfiguredTableIdentifier"},
			"update-configured-table-association":                       {"ConfiguredTableAssociationIdentifier", "Description", "MembershipIdentifier", "RoleArn"},
			"update-configured-table-association-analysis-rule":         {"AnalysisRulePolicy", "AnalysisRuleType", "ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"update-id-mapping-table":                                   {"Description", "IdMappingTableIdentifier", "KmsKeyArn", "MembershipIdentifier"},
			"update-id-namespace-association":                           {"Description", "IdMappingConfig", "IdNamespaceAssociationIdentifier", "MembershipIdentifier", "Name"},
			"update-membership":                                         {"DefaultJobResultConfiguration", "DefaultResultConfiguration", "JobLogStatus", "MembershipIdentifier", "QueryLogStatus"},
			"update-privacy-budget-template":                            {"MembershipIdentifier", "Parameters", "PrivacyBudgetTemplateIdentifier", "PrivacyBudgetType"},
			"update-protected-job":                                      {"MembershipIdentifier", "ProtectedJobIdentifier", "TargetStatus"},
			"update-protected-query":                                    {"MembershipIdentifier", "ProtectedQueryIdentifier", "TargetStatus"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-get-collaboration-analysis-template":                 {"AnalysisTemplateArns": "[]string", "CollaborationIdentifier": "*string"},
			"batch-get-schema":                                          {"CollaborationIdentifier": "*string", "Names": "[]string"},
			"batch-get-schema-analysis-rule":                            {"CollaborationIdentifier": "*string", "SchemaAnalysisRuleRequests": "[]types.SchemaAnalysisRuleRequest"},
			"create-analysis-template":                                  {"AnalysisParameters": "[]types.AnalysisParameter", "Description": "*string", "ErrorMessageConfiguration": "*types.ErrorMessageConfiguration", "Format": "types.AnalysisFormat", "MembershipIdentifier": "*string", "Name": "*string", "Schema": "*types.AnalysisSchema", "Source": "types.AnalysisSource", "SyntheticDataParameters": "types.SyntheticDataParameters", "Tags": "map[string]string"},
			"create-collaboration":                                      {"AllowedResultRegions": "[]types.SupportedS3Region", "AnalyticsEngine": "types.AnalyticsEngine", "AutoApprovedChangeRequestTypes": "[]types.AutoApprovedChangeType", "CreatorDisplayName": "*string", "CreatorMLMemberAbilities": "*types.MLMemberAbilities", "CreatorMemberAbilities": "[]types.MemberAbility", "CreatorPaymentConfiguration": "*types.PaymentConfiguration", "DataEncryptionMetadata": "*types.DataEncryptionMetadata", "Description": "*string", "IsMetricsEnabled": "*bool", "JobLogStatus": "types.CollaborationJobLogStatus", "Members": "[]types.MemberSpecification", "Name": "*string", "QueryLogStatus": "types.CollaborationQueryLogStatus", "Tags": "map[string]string"},
			"create-collaboration-change-request":                       {"Changes": "[]types.ChangeInput", "CollaborationIdentifier": "*string"},
			"create-configured-audience-model-association":              {"ConfiguredAudienceModelArn": "*string", "ConfiguredAudienceModelAssociationName": "*string", "Description": "*string", "ManageResourcePolicies": "*bool", "MembershipIdentifier": "*string", "Tags": "map[string]string"},
			"create-configured-table":                                   {"AllowedColumns": "[]string", "AnalysisMethod": "types.AnalysisMethod", "Description": "*string", "Name": "*string", "SelectedAnalysisMethods": "[]types.SelectedAnalysisMethod", "TableReference": "types.TableReference", "Tags": "map[string]string"},
			"create-configured-table-analysis-rule":                     {"AnalysisRulePolicy": "types.ConfiguredTableAnalysisRulePolicy", "AnalysisRuleType": "types.ConfiguredTableAnalysisRuleType", "ConfiguredTableIdentifier": "*string"},
			"create-configured-table-association":                       {"ConfiguredTableIdentifier": "*string", "Description": "*string", "MembershipIdentifier": "*string", "Name": "*string", "RoleArn": "*string", "Tags": "map[string]string"},
			"create-configured-table-association-analysis-rule":         {"AnalysisRulePolicy": "types.ConfiguredTableAssociationAnalysisRulePolicy", "AnalysisRuleType": "types.ConfiguredTableAssociationAnalysisRuleType", "ConfiguredTableAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"create-id-mapping-table":                                   {"Description": "*string", "InputReferenceConfig": "*types.IdMappingTableInputReferenceConfig", "KmsKeyArn": "*string", "MembershipIdentifier": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-id-namespace-association":                           {"Description": "*string", "IdMappingConfig": "*types.IdMappingConfig", "InputReferenceConfig": "*types.IdNamespaceAssociationInputReferenceConfig", "MembershipIdentifier": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-membership":                                         {"CollaborationIdentifier": "*string", "DefaultJobResultConfiguration": "*types.MembershipProtectedJobResultConfiguration", "DefaultResultConfiguration": "*types.MembershipProtectedQueryResultConfiguration", "IsMetricsEnabled": "*bool", "JobLogStatus": "types.MembershipJobLogStatus", "PaymentConfiguration": "*types.MembershipPaymentConfiguration", "QueryLogStatus": "types.MembershipQueryLogStatus", "Tags": "map[string]string"},
			"create-privacy-budget-template":                            {"AutoRefresh": "types.PrivacyBudgetTemplateAutoRefresh", "MembershipIdentifier": "*string", "Parameters": "types.PrivacyBudgetTemplateParametersInput", "PrivacyBudgetType": "types.PrivacyBudgetType", "Tags": "map[string]string"},
			"delete-analysis-template":                                  {"AnalysisTemplateIdentifier": "*string", "MembershipIdentifier": "*string"},
			"delete-collaboration":                                      {"CollaborationIdentifier": "*string"},
			"delete-configured-audience-model-association":              {"ConfiguredAudienceModelAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"delete-configured-table":                                   {"ConfiguredTableIdentifier": "*string"},
			"delete-configured-table-analysis-rule":                     {"AnalysisRuleType": "types.ConfiguredTableAnalysisRuleType", "ConfiguredTableIdentifier": "*string"},
			"delete-configured-table-association":                       {"ConfiguredTableAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"delete-configured-table-association-analysis-rule":         {"AnalysisRuleType": "types.ConfiguredTableAssociationAnalysisRuleType", "ConfiguredTableAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"delete-id-mapping-table":                                   {"IdMappingTableIdentifier": "*string", "MembershipIdentifier": "*string"},
			"delete-id-namespace-association":                           {"IdNamespaceAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"delete-member":                                             {"AccountId": "*string", "CollaborationIdentifier": "*string"},
			"delete-membership":                                         {"MembershipIdentifier": "*string"},
			"delete-privacy-budget-template":                            {"MembershipIdentifier": "*string", "PrivacyBudgetTemplateIdentifier": "*string"},
			"get-analysis-template":                                     {"AnalysisTemplateIdentifier": "*string", "MembershipIdentifier": "*string"},
			"get-collaboration":                                         {"CollaborationIdentifier": "*string"},
			"get-collaboration-analysis-template":                       {"AnalysisTemplateArn": "*string", "CollaborationIdentifier": "*string"},
			"get-collaboration-change-request":                          {"ChangeRequestIdentifier": "*string", "CollaborationIdentifier": "*string"},
			"get-collaboration-configured-audience-model-association":   {"CollaborationIdentifier": "*string", "ConfiguredAudienceModelAssociationIdentifier": "*string"},
			"get-collaboration-id-namespace-association":                {"CollaborationIdentifier": "*string", "IdNamespaceAssociationIdentifier": "*string"},
			"get-collaboration-privacy-budget-template":                 {"CollaborationIdentifier": "*string", "PrivacyBudgetTemplateIdentifier": "*string"},
			"get-configured-audience-model-association":                 {"ConfiguredAudienceModelAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"get-configured-table":                                      {"ConfiguredTableIdentifier": "*string"},
			"get-configured-table-analysis-rule":                        {"AnalysisRuleType": "types.ConfiguredTableAnalysisRuleType", "ConfiguredTableIdentifier": "*string"},
			"get-configured-table-association":                          {"ConfiguredTableAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"get-configured-table-association-analysis-rule":            {"AnalysisRuleType": "types.ConfiguredTableAssociationAnalysisRuleType", "ConfiguredTableAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"get-id-mapping-table":                                      {"IdMappingTableIdentifier": "*string", "MembershipIdentifier": "*string"},
			"get-id-namespace-association":                              {"IdNamespaceAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"get-membership":                                            {"MembershipIdentifier": "*string"},
			"get-privacy-budget-template":                               {"MembershipIdentifier": "*string", "PrivacyBudgetTemplateIdentifier": "*string"},
			"get-protected-job":                                         {"MembershipIdentifier": "*string", "ProtectedJobIdentifier": "*string"},
			"get-protected-query":                                       {"MembershipIdentifier": "*string", "ProtectedQueryIdentifier": "*string"},
			"get-schema":                                                {"CollaborationIdentifier": "*string", "Name": "*string"},
			"get-schema-analysis-rule":                                  {"CollaborationIdentifier": "*string", "Name": "*string", "Type": "types.AnalysisRuleType"},
			"list-analysis-templates":                                   {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-collaboration-analysis-templates":                     {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-collaboration-change-requests":                        {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "Status": "types.ChangeRequestStatus"},
			"list-collaboration-configured-audience-model-associations": {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-collaboration-id-namespace-associations":              {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-collaboration-privacy-budget-templates":               {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-collaboration-privacy-budgets":                        {"AccessBudgetResourceArn": "*string", "CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "PrivacyBudgetType": "types.PrivacyBudgetType"},
			"list-collaborations":                                       {"MaxResults": "*int32", "MemberStatus": "types.FilterableMemberStatus", "NextToken": "*string"},
			"list-configured-audience-model-associations":               {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-configured-table-associations":                        {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-configured-tables":                                    {"MaxResults": "*int32", "NextToken": "*string"},
			"list-id-mapping-tables":                                    {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-id-namespace-associations":                            {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-members":                                              {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-memberships":                                          {"MaxResults": "*int32", "NextToken": "*string", "Status": "types.MembershipStatus"},
			"list-privacy-budget-templates":                             {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string"},
			"list-privacy-budgets":                                      {"AccessBudgetResourceArn": "*string", "MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string", "PrivacyBudgetType": "types.PrivacyBudgetType"},
			"list-protected-jobs":                                       {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string", "Status": "types.ProtectedJobStatus"},
			"list-protected-queries":                                    {"MaxResults": "*int32", "MembershipIdentifier": "*string", "NextToken": "*string", "Status": "types.ProtectedQueryStatus"},
			"list-schemas":                                              {"CollaborationIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string", "SchemaType": "types.SchemaType"},
			"list-tags-for-resource":                                    {"ResourceArn": "*string"},
			"populate-id-mapping-table":                                 {"IdMappingTableIdentifier": "*string", "JobType": "types.JobType", "MembershipIdentifier": "*string"},
			"preview-privacy-impact":                                    {"MembershipIdentifier": "*string", "Parameters": "types.PreviewPrivacyImpactParametersInput"},
			"start-protected-job":                                       {"ComputeConfiguration": "types.ProtectedJobComputeConfiguration", "JobParameters": "*types.ProtectedJobParameters", "MembershipIdentifier": "*string", "ResultConfiguration": "*types.ProtectedJobResultConfigurationInput", "Type": "types.ProtectedJobType"},
			"start-protected-query":                                     {"ComputeConfiguration": "types.ComputeConfiguration", "MembershipIdentifier": "*string", "ResultConfiguration": "*types.ProtectedQueryResultConfiguration", "SqlParameters": "*types.ProtectedQuerySQLParameters", "Type": "types.ProtectedQueryType"},
			"tag-resource":                                              {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                                            {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-analysis-template":                                  {"AnalysisTemplateIdentifier": "*string", "Description": "*string", "MembershipIdentifier": "*string"},
			"update-collaboration":                                      {"AnalyticsEngine": "types.AnalyticsEngine", "CollaborationIdentifier": "*string", "Description": "*string", "Name": "*string"},
			"update-collaboration-change-request":                       {"Action": "types.ChangeRequestAction", "ChangeRequestIdentifier": "*string", "CollaborationIdentifier": "*string"},
			"update-configured-audience-model-association":              {"ConfiguredAudienceModelAssociationIdentifier": "*string", "Description": "*string", "MembershipIdentifier": "*string", "Name": "*string"},
			"update-configured-table":                                   {"AllowedColumns": "[]string", "AnalysisMethod": "types.AnalysisMethod", "ConfiguredTableIdentifier": "*string", "Description": "*string", "Name": "*string", "SelectedAnalysisMethods": "[]types.SelectedAnalysisMethod", "TableReference": "types.TableReference"},
			"update-configured-table-analysis-rule":                     {"AnalysisRulePolicy": "types.ConfiguredTableAnalysisRulePolicy", "AnalysisRuleType": "types.ConfiguredTableAnalysisRuleType", "ConfiguredTableIdentifier": "*string"},
			"update-configured-table-association":                       {"ConfiguredTableAssociationIdentifier": "*string", "Description": "*string", "MembershipIdentifier": "*string", "RoleArn": "*string"},
			"update-configured-table-association-analysis-rule":         {"AnalysisRulePolicy": "types.ConfiguredTableAssociationAnalysisRulePolicy", "AnalysisRuleType": "types.ConfiguredTableAssociationAnalysisRuleType", "ConfiguredTableAssociationIdentifier": "*string", "MembershipIdentifier": "*string"},
			"update-id-mapping-table":                                   {"Description": "*string", "IdMappingTableIdentifier": "*string", "KmsKeyArn": "*string", "MembershipIdentifier": "*string"},
			"update-id-namespace-association":                           {"Description": "*string", "IdMappingConfig": "*types.IdMappingConfig", "IdNamespaceAssociationIdentifier": "*string", "MembershipIdentifier": "*string", "Name": "*string"},
			"update-membership":                                         {"DefaultJobResultConfiguration": "*types.MembershipProtectedJobResultConfiguration", "DefaultResultConfiguration": "*types.MembershipProtectedQueryResultConfiguration", "JobLogStatus": "types.MembershipJobLogStatus", "MembershipIdentifier": "*string", "QueryLogStatus": "types.MembershipQueryLogStatus"},
			"update-privacy-budget-template":                            {"MembershipIdentifier": "*string", "Parameters": "types.PrivacyBudgetTemplateUpdateParameters", "PrivacyBudgetTemplateIdentifier": "*string", "PrivacyBudgetType": "types.PrivacyBudgetType"},
			"update-protected-job":                                      {"MembershipIdentifier": "*string", "ProtectedJobIdentifier": "*string", "TargetStatus": "types.TargetProtectedJobStatus"},
			"update-protected-query":                                    {"MembershipIdentifier": "*string", "ProtectedQueryIdentifier": "*string", "TargetStatus": "types.TargetProtectedQueryStatus"},
		},
		OperationInputRequired: map[string][]string{
			"batch-get-collaboration-analysis-template":                 {"AnalysisTemplateArns", "CollaborationIdentifier"},
			"batch-get-schema":                                          {"CollaborationIdentifier", "Names"},
			"batch-get-schema-analysis-rule":                            {"CollaborationIdentifier", "SchemaAnalysisRuleRequests"},
			"create-analysis-template":                                  {"Format", "MembershipIdentifier", "Name", "Source"},
			"create-collaboration":                                      {"CreatorDisplayName", "CreatorMemberAbilities", "Description", "Members", "Name", "QueryLogStatus"},
			"create-collaboration-change-request":                       {"Changes", "CollaborationIdentifier"},
			"create-configured-audience-model-association":              {"ConfiguredAudienceModelArn", "ConfiguredAudienceModelAssociationName", "ManageResourcePolicies", "MembershipIdentifier"},
			"create-configured-table":                                   {"AllowedColumns", "AnalysisMethod", "Name", "TableReference"},
			"create-configured-table-analysis-rule":                     {"AnalysisRulePolicy", "AnalysisRuleType", "ConfiguredTableIdentifier"},
			"create-configured-table-association":                       {"ConfiguredTableIdentifier", "MembershipIdentifier", "Name", "RoleArn"},
			"create-configured-table-association-analysis-rule":         {"AnalysisRulePolicy", "AnalysisRuleType", "ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"create-id-mapping-table":                                   {"InputReferenceConfig", "MembershipIdentifier", "Name"},
			"create-id-namespace-association":                           {"InputReferenceConfig", "MembershipIdentifier", "Name"},
			"create-membership":                                         {"CollaborationIdentifier", "QueryLogStatus"},
			"create-privacy-budget-template":                            {"MembershipIdentifier", "Parameters", "PrivacyBudgetType"},
			"delete-analysis-template":                                  {"AnalysisTemplateIdentifier", "MembershipIdentifier"},
			"delete-collaboration":                                      {"CollaborationIdentifier"},
			"delete-configured-audience-model-association":              {"ConfiguredAudienceModelAssociationIdentifier", "MembershipIdentifier"},
			"delete-configured-table":                                   {"ConfiguredTableIdentifier"},
			"delete-configured-table-analysis-rule":                     {"AnalysisRuleType", "ConfiguredTableIdentifier"},
			"delete-configured-table-association":                       {"ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"delete-configured-table-association-analysis-rule":         {"AnalysisRuleType", "ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"delete-id-mapping-table":                                   {"IdMappingTableIdentifier", "MembershipIdentifier"},
			"delete-id-namespace-association":                           {"IdNamespaceAssociationIdentifier", "MembershipIdentifier"},
			"delete-member":                                             {"AccountId", "CollaborationIdentifier"},
			"delete-membership":                                         {"MembershipIdentifier"},
			"delete-privacy-budget-template":                            {"MembershipIdentifier", "PrivacyBudgetTemplateIdentifier"},
			"get-analysis-template":                                     {"AnalysisTemplateIdentifier", "MembershipIdentifier"},
			"get-collaboration":                                         {"CollaborationIdentifier"},
			"get-collaboration-analysis-template":                       {"AnalysisTemplateArn", "CollaborationIdentifier"},
			"get-collaboration-change-request":                          {"ChangeRequestIdentifier", "CollaborationIdentifier"},
			"get-collaboration-configured-audience-model-association":   {"CollaborationIdentifier", "ConfiguredAudienceModelAssociationIdentifier"},
			"get-collaboration-id-namespace-association":                {"CollaborationIdentifier", "IdNamespaceAssociationIdentifier"},
			"get-collaboration-privacy-budget-template":                 {"CollaborationIdentifier", "PrivacyBudgetTemplateIdentifier"},
			"get-configured-audience-model-association":                 {"ConfiguredAudienceModelAssociationIdentifier", "MembershipIdentifier"},
			"get-configured-table":                                      {"ConfiguredTableIdentifier"},
			"get-configured-table-analysis-rule":                        {"AnalysisRuleType", "ConfiguredTableIdentifier"},
			"get-configured-table-association":                          {"ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"get-configured-table-association-analysis-rule":            {"AnalysisRuleType", "ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"get-id-mapping-table":                                      {"IdMappingTableIdentifier", "MembershipIdentifier"},
			"get-id-namespace-association":                              {"IdNamespaceAssociationIdentifier", "MembershipIdentifier"},
			"get-membership":                                            {"MembershipIdentifier"},
			"get-privacy-budget-template":                               {"MembershipIdentifier", "PrivacyBudgetTemplateIdentifier"},
			"get-protected-job":                                         {"MembershipIdentifier", "ProtectedJobIdentifier"},
			"get-protected-query":                                       {"MembershipIdentifier", "ProtectedQueryIdentifier"},
			"get-schema":                                                {"CollaborationIdentifier", "Name"},
			"get-schema-analysis-rule":                                  {"CollaborationIdentifier", "Name", "Type"},
			"list-analysis-templates":                                   {"MembershipIdentifier"},
			"list-collaboration-analysis-templates":                     {"CollaborationIdentifier"},
			"list-collaboration-change-requests":                        {"CollaborationIdentifier"},
			"list-collaboration-configured-audience-model-associations": {"CollaborationIdentifier"},
			"list-collaboration-id-namespace-associations":              {"CollaborationIdentifier"},
			"list-collaboration-privacy-budget-templates":               {"CollaborationIdentifier"},
			"list-collaboration-privacy-budgets":                        {"CollaborationIdentifier", "PrivacyBudgetType"},
			"list-collaborations":                                       {},
			"list-configured-audience-model-associations":               {"MembershipIdentifier"},
			"list-configured-table-associations":                        {"MembershipIdentifier"},
			"list-configured-tables":                                    {},
			"list-id-mapping-tables":                                    {"MembershipIdentifier"},
			"list-id-namespace-associations":                            {"MembershipIdentifier"},
			"list-members":                                              {"CollaborationIdentifier"},
			"list-memberships":                                          {},
			"list-privacy-budget-templates":                             {"MembershipIdentifier"},
			"list-privacy-budgets":                                      {"MembershipIdentifier", "PrivacyBudgetType"},
			"list-protected-jobs":                                       {"MembershipIdentifier"},
			"list-protected-queries":                                    {"MembershipIdentifier"},
			"list-schemas":                                              {"CollaborationIdentifier"},
			"list-tags-for-resource":                                    {"ResourceArn"},
			"populate-id-mapping-table":                                 {"IdMappingTableIdentifier", "MembershipIdentifier"},
			"preview-privacy-impact":                                    {"MembershipIdentifier", "Parameters"},
			"start-protected-job":                                       {"JobParameters", "MembershipIdentifier", "Type"},
			"start-protected-query":                                     {"MembershipIdentifier", "SqlParameters", "Type"},
			"tag-resource":                                              {"ResourceArn", "Tags"},
			"untag-resource":                                            {"ResourceArn", "TagKeys"},
			"update-analysis-template":                                  {"AnalysisTemplateIdentifier", "MembershipIdentifier"},
			"update-collaboration":                                      {"CollaborationIdentifier"},
			"update-collaboration-change-request":                       {"Action", "ChangeRequestIdentifier", "CollaborationIdentifier"},
			"update-configured-audience-model-association":              {"ConfiguredAudienceModelAssociationIdentifier", "MembershipIdentifier"},
			"update-configured-table":                                   {"ConfiguredTableIdentifier"},
			"update-configured-table-analysis-rule":                     {"AnalysisRulePolicy", "AnalysisRuleType", "ConfiguredTableIdentifier"},
			"update-configured-table-association":                       {"ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"update-configured-table-association-analysis-rule":         {"AnalysisRulePolicy", "AnalysisRuleType", "ConfiguredTableAssociationIdentifier", "MembershipIdentifier"},
			"update-id-mapping-table":                                   {"IdMappingTableIdentifier", "MembershipIdentifier"},
			"update-id-namespace-association":                           {"IdNamespaceAssociationIdentifier", "MembershipIdentifier"},
			"update-membership":                                         {"MembershipIdentifier"},
			"update-privacy-budget-template":                            {"MembershipIdentifier", "PrivacyBudgetTemplateIdentifier", "PrivacyBudgetType"},
			"update-protected-job":                                      {"MembershipIdentifier", "ProtectedJobIdentifier", "TargetStatus"},
			"update-protected-query":                                    {"MembershipIdentifier", "ProtectedQueryIdentifier", "TargetStatus"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("cleanrooms", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
