package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/m2/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"cancel-batch-job-execution", "create-application", "create-data-set-export-task", "create-data-set-import-task", "create-deployment", "create-environment", "delete-application", "delete-application-from-environment", "delete-environment", "get-application", "get-application-version", "get-batch-job-execution", "get-data-set-details", "get-data-set-export-task", "get-data-set-import-task", "get-deployment", "get-environment", "get-signed-bluinsights-url", "list-application-versions", "list-applications", "list-batch-job-definitions", "list-batch-job-executions", "list-batch-job-restart-points", "list-data-set-export-history", "list-data-set-import-history", "list-data-sets", "list-deployments", "list-engine-versions", "list-environments", "list-tags-for-resource", "start-application", "start-batch-job", "stop-application", "tag-resource", "untag-resource", "update-application", "update-environment"},
		OperationSet: map[string]bool{"cancel-batch-job-execution": true, "create-application": true, "create-data-set-export-task": true, "create-data-set-import-task": true, "create-deployment": true, "create-environment": true, "delete-application": true, "delete-application-from-environment": true, "delete-environment": true, "get-application": true, "get-application-version": true, "get-batch-job-execution": true, "get-data-set-details": true, "get-data-set-export-task": true, "get-data-set-import-task": true, "get-deployment": true, "get-environment": true, "get-signed-bluinsights-url": true, "list-application-versions": true, "list-applications": true, "list-batch-job-definitions": true, "list-batch-job-executions": true, "list-batch-job-restart-points": true, "list-data-set-export-history": true, "list-data-set-import-history": true, "list-data-sets": true, "list-deployments": true, "list-engine-versions": true, "list-environments": true, "list-tags-for-resource": true, "start-application": true, "start-batch-job": true, "stop-application": true, "tag-resource": true, "untag-resource": true, "update-application": true, "update-environment": true},
		OperationInputs: map[string][]string{
			"cancel-batch-job-execution":          {"ApplicationId", "AuthSecretsManagerArn", "ExecutionId"},
			"create-application":                  {"ClientToken", "Definition", "Description", "EngineType", "KmsKeyId", "Name", "RoleArn", "Tags"},
			"create-data-set-export-task":         {"ApplicationId", "ClientToken", "ExportConfig", "KmsKeyId"},
			"create-data-set-import-task":         {"ApplicationId", "ClientToken", "ImportConfig"},
			"create-deployment":                   {"ApplicationId", "ApplicationVersion", "ClientToken", "EnvironmentId"},
			"create-environment":                  {"ClientToken", "Description", "EngineType", "EngineVersion", "HighAvailabilityConfig", "InstanceType", "KmsKeyId", "Name", "NetworkType", "PreferredMaintenanceWindow", "PubliclyAccessible", "SecurityGroupIds", "StorageConfigurations", "SubnetIds", "Tags"},
			"delete-application":                  {"ApplicationId"},
			"delete-application-from-environment": {"ApplicationId", "EnvironmentId"},
			"delete-environment":                  {"EnvironmentId"},
			"get-application":                     {"ApplicationId"},
			"get-application-version":             {"ApplicationId", "ApplicationVersion"},
			"get-batch-job-execution":             {"ApplicationId", "ExecutionId"},
			"get-data-set-details":                {"ApplicationId", "DataSetName"},
			"get-data-set-export-task":            {"ApplicationId", "TaskId"},
			"get-data-set-import-task":            {"ApplicationId", "TaskId"},
			"get-deployment":                      {"ApplicationId", "DeploymentId"},
			"get-environment":                     {"EnvironmentId"},
			"get-signed-bluinsights-url":          {},
			"list-application-versions":           {"ApplicationId", "MaxResults", "NextToken"},
			"list-applications":                   {"EnvironmentId", "MaxResults", "Names", "NextToken"},
			"list-batch-job-definitions":          {"ApplicationId", "MaxResults", "NextToken", "Prefix"},
			"list-batch-job-executions":           {"ApplicationId", "ExecutionIds", "JobName", "MaxResults", "NextToken", "StartedAfter", "StartedBefore", "Status"},
			"list-batch-job-restart-points":       {"ApplicationId", "AuthSecretsManagerArn", "ExecutionId"},
			"list-data-set-export-history":        {"ApplicationId", "MaxResults", "NextToken"},
			"list-data-set-import-history":        {"ApplicationId", "MaxResults", "NextToken"},
			"list-data-sets":                      {"ApplicationId", "MaxResults", "NameFilter", "NextToken", "Prefix"},
			"list-deployments":                    {"ApplicationId", "MaxResults", "NextToken"},
			"list-engine-versions":                {"EngineType", "MaxResults", "NextToken"},
			"list-environments":                   {"EngineType", "MaxResults", "Names", "NextToken"},
			"list-tags-for-resource":              {"ResourceArn"},
			"start-application":                   {"ApplicationId"},
			"start-batch-job":                     {"ApplicationId", "AuthSecretsManagerArn", "BatchJobIdentifier", "JobParams"},
			"stop-application":                    {"ApplicationId", "ForceStop"},
			"tag-resource":                        {"ResourceArn", "Tags"},
			"untag-resource":                      {"ResourceArn", "TagKeys"},
			"update-application":                  {"ApplicationId", "CurrentApplicationVersion", "Definition", "Description"},
			"update-environment":                  {"ApplyDuringMaintenanceWindow", "DesiredCapacity", "EngineVersion", "EnvironmentId", "ForceUpdate", "InstanceType", "PreferredMaintenanceWindow"},
		},
		OperationInputTypes: map[string]map[string]string{
			"cancel-batch-job-execution":          {"ApplicationId": "*string", "AuthSecretsManagerArn": "*string", "ExecutionId": "*string"},
			"create-application":                  {"ClientToken": "*string", "Definition": "types.Definition", "Description": "*string", "EngineType": "types.EngineType", "KmsKeyId": "*string", "Name": "*string", "RoleArn": "*string", "Tags": "map[string]string"},
			"create-data-set-export-task":         {"ApplicationId": "*string", "ClientToken": "*string", "ExportConfig": "types.DataSetExportConfig", "KmsKeyId": "*string"},
			"create-data-set-import-task":         {"ApplicationId": "*string", "ClientToken": "*string", "ImportConfig": "types.DataSetImportConfig"},
			"create-deployment":                   {"ApplicationId": "*string", "ApplicationVersion": "*int32", "ClientToken": "*string", "EnvironmentId": "*string"},
			"create-environment":                  {"ClientToken": "*string", "Description": "*string", "EngineType": "types.EngineType", "EngineVersion": "*string", "HighAvailabilityConfig": "*types.HighAvailabilityConfig", "InstanceType": "*string", "KmsKeyId": "*string", "Name": "*string", "NetworkType": "types.NetworkType", "PreferredMaintenanceWindow": "*string", "PubliclyAccessible": "bool", "SecurityGroupIds": "[]string", "StorageConfigurations": "[]types.StorageConfiguration", "SubnetIds": "[]string", "Tags": "map[string]string"},
			"delete-application":                  {"ApplicationId": "*string"},
			"delete-application-from-environment": {"ApplicationId": "*string", "EnvironmentId": "*string"},
			"delete-environment":                  {"EnvironmentId": "*string"},
			"get-application":                     {"ApplicationId": "*string"},
			"get-application-version":             {"ApplicationId": "*string", "ApplicationVersion": "*int32"},
			"get-batch-job-execution":             {"ApplicationId": "*string", "ExecutionId": "*string"},
			"get-data-set-details":                {"ApplicationId": "*string", "DataSetName": "*string"},
			"get-data-set-export-task":            {"ApplicationId": "*string", "TaskId": "*string"},
			"get-data-set-import-task":            {"ApplicationId": "*string", "TaskId": "*string"},
			"get-deployment":                      {"ApplicationId": "*string", "DeploymentId": "*string"},
			"get-environment":                     {"EnvironmentId": "*string"},
			"get-signed-bluinsights-url":          {},
			"list-application-versions":           {"ApplicationId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-applications":                   {"EnvironmentId": "*string", "MaxResults": "*int32", "Names": "[]string", "NextToken": "*string"},
			"list-batch-job-definitions":          {"ApplicationId": "*string", "MaxResults": "*int32", "NextToken": "*string", "Prefix": "*string"},
			"list-batch-job-executions":           {"ApplicationId": "*string", "ExecutionIds": "[]string", "JobName": "*string", "MaxResults": "*int32", "NextToken": "*string", "StartedAfter": "*time.Time", "StartedBefore": "*time.Time", "Status": "types.BatchJobExecutionStatus"},
			"list-batch-job-restart-points":       {"ApplicationId": "*string", "AuthSecretsManagerArn": "*string", "ExecutionId": "*string"},
			"list-data-set-export-history":        {"ApplicationId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-data-set-import-history":        {"ApplicationId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-data-sets":                      {"ApplicationId": "*string", "MaxResults": "*int32", "NameFilter": "*string", "NextToken": "*string", "Prefix": "*string"},
			"list-deployments":                    {"ApplicationId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-engine-versions":                {"EngineType": "types.EngineType", "MaxResults": "*int32", "NextToken": "*string"},
			"list-environments":                   {"EngineType": "types.EngineType", "MaxResults": "*int32", "Names": "[]string", "NextToken": "*string"},
			"list-tags-for-resource":              {"ResourceArn": "*string"},
			"start-application":                   {"ApplicationId": "*string"},
			"start-batch-job":                     {"ApplicationId": "*string", "AuthSecretsManagerArn": "*string", "BatchJobIdentifier": "types.BatchJobIdentifier", "JobParams": "map[string]string"},
			"stop-application":                    {"ApplicationId": "*string", "ForceStop": "bool"},
			"tag-resource":                        {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                      {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-application":                  {"ApplicationId": "*string", "CurrentApplicationVersion": "*int32", "Definition": "types.Definition", "Description": "*string"},
			"update-environment":                  {"ApplyDuringMaintenanceWindow": "bool", "DesiredCapacity": "*int32", "EngineVersion": "*string", "EnvironmentId": "*string", "ForceUpdate": "bool", "InstanceType": "*string", "PreferredMaintenanceWindow": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"cancel-batch-job-execution":          {"ApplicationId", "ExecutionId"},
			"create-application":                  {"Definition", "EngineType", "Name"},
			"create-data-set-export-task":         {"ApplicationId", "ExportConfig"},
			"create-data-set-import-task":         {"ApplicationId", "ImportConfig"},
			"create-deployment":                   {"ApplicationId", "ApplicationVersion", "EnvironmentId"},
			"create-environment":                  {"EngineType", "InstanceType", "Name"},
			"delete-application":                  {"ApplicationId"},
			"delete-application-from-environment": {"ApplicationId", "EnvironmentId"},
			"delete-environment":                  {"EnvironmentId"},
			"get-application":                     {"ApplicationId"},
			"get-application-version":             {"ApplicationId", "ApplicationVersion"},
			"get-batch-job-execution":             {"ApplicationId", "ExecutionId"},
			"get-data-set-details":                {"ApplicationId", "DataSetName"},
			"get-data-set-export-task":            {"ApplicationId", "TaskId"},
			"get-data-set-import-task":            {"ApplicationId", "TaskId"},
			"get-deployment":                      {"ApplicationId", "DeploymentId"},
			"get-environment":                     {"EnvironmentId"},
			"get-signed-bluinsights-url":          {},
			"list-application-versions":           {"ApplicationId"},
			"list-applications":                   {},
			"list-batch-job-definitions":          {"ApplicationId"},
			"list-batch-job-executions":           {"ApplicationId"},
			"list-batch-job-restart-points":       {"ApplicationId", "ExecutionId"},
			"list-data-set-export-history":        {"ApplicationId"},
			"list-data-set-import-history":        {"ApplicationId"},
			"list-data-sets":                      {"ApplicationId"},
			"list-deployments":                    {"ApplicationId"},
			"list-engine-versions":                {},
			"list-environments":                   {},
			"list-tags-for-resource":              {"ResourceArn"},
			"start-application":                   {"ApplicationId"},
			"start-batch-job":                     {"ApplicationId", "BatchJobIdentifier"},
			"stop-application":                    {"ApplicationId"},
			"tag-resource":                        {"ResourceArn", "Tags"},
			"untag-resource":                      {"ResourceArn", "TagKeys"},
			"update-application":                  {"ApplicationId", "CurrentApplicationVersion"},
			"update-environment":                  {"EnvironmentId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("m2", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
