package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/directconnect/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"accept-direct-connect-gateway-association-proposal", "allocate-connection-on-interconnect", "allocate-hosted-connection", "allocate-private-virtual-interface", "allocate-public-virtual-interface", "allocate-transit-virtual-interface", "associate-connection-with-lag", "associate-hosted-connection", "associate-mac-sec-key", "associate-virtual-interface", "confirm-connection", "confirm-customer-agreement", "confirm-private-virtual-interface", "confirm-public-virtual-interface", "confirm-transit-virtual-interface", "create-bgp-peer", "create-connection", "create-direct-connect-gateway", "create-direct-connect-gateway-association", "create-direct-connect-gateway-association-proposal", "create-interconnect", "create-lag", "create-private-virtual-interface", "create-public-virtual-interface", "create-transit-virtual-interface", "delete-bgp-peer", "delete-connection", "delete-direct-connect-gateway", "delete-direct-connect-gateway-association", "delete-direct-connect-gateway-association-proposal", "delete-interconnect", "delete-lag", "delete-virtual-interface", "describe-connection-loa", "describe-connections", "describe-connections-on-interconnect", "describe-customer-metadata", "describe-direct-connect-gateway-association-proposals", "describe-direct-connect-gateway-associations", "describe-direct-connect-gateway-attachments", "describe-direct-connect-gateways", "describe-hosted-connections", "describe-interconnect-loa", "describe-interconnects", "describe-lags", "describe-loa", "describe-locations", "describe-router-configuration", "describe-tags", "describe-virtual-gateways", "describe-virtual-interfaces", "disassociate-connection-from-lag", "disassociate-mac-sec-key", "list-virtual-interface-test-history", "start-bgp-failover-test", "stop-bgp-failover-test", "tag-resource", "untag-resource", "update-connection", "update-direct-connect-gateway", "update-direct-connect-gateway-association", "update-lag", "update-virtual-interface-attributes"},
		OperationSet: map[string]bool{"accept-direct-connect-gateway-association-proposal": true, "allocate-connection-on-interconnect": true, "allocate-hosted-connection": true, "allocate-private-virtual-interface": true, "allocate-public-virtual-interface": true, "allocate-transit-virtual-interface": true, "associate-connection-with-lag": true, "associate-hosted-connection": true, "associate-mac-sec-key": true, "associate-virtual-interface": true, "confirm-connection": true, "confirm-customer-agreement": true, "confirm-private-virtual-interface": true, "confirm-public-virtual-interface": true, "confirm-transit-virtual-interface": true, "create-bgp-peer": true, "create-connection": true, "create-direct-connect-gateway": true, "create-direct-connect-gateway-association": true, "create-direct-connect-gateway-association-proposal": true, "create-interconnect": true, "create-lag": true, "create-private-virtual-interface": true, "create-public-virtual-interface": true, "create-transit-virtual-interface": true, "delete-bgp-peer": true, "delete-connection": true, "delete-direct-connect-gateway": true, "delete-direct-connect-gateway-association": true, "delete-direct-connect-gateway-association-proposal": true, "delete-interconnect": true, "delete-lag": true, "delete-virtual-interface": true, "describe-connection-loa": true, "describe-connections": true, "describe-connections-on-interconnect": true, "describe-customer-metadata": true, "describe-direct-connect-gateway-association-proposals": true, "describe-direct-connect-gateway-associations": true, "describe-direct-connect-gateway-attachments": true, "describe-direct-connect-gateways": true, "describe-hosted-connections": true, "describe-interconnect-loa": true, "describe-interconnects": true, "describe-lags": true, "describe-loa": true, "describe-locations": true, "describe-router-configuration": true, "describe-tags": true, "describe-virtual-gateways": true, "describe-virtual-interfaces": true, "disassociate-connection-from-lag": true, "disassociate-mac-sec-key": true, "list-virtual-interface-test-history": true, "start-bgp-failover-test": true, "stop-bgp-failover-test": true, "tag-resource": true, "untag-resource": true, "update-connection": true, "update-direct-connect-gateway": true, "update-direct-connect-gateway-association": true, "update-lag": true, "update-virtual-interface-attributes": true},
		OperationInputs: map[string][]string{
			"accept-direct-connect-gateway-association-proposal":    {"AssociatedGatewayOwnerAccount", "DirectConnectGatewayId", "OverrideAllowedPrefixesToDirectConnectGateway", "ProposalId"},
			"allocate-connection-on-interconnect":                   {"Bandwidth", "ConnectionName", "InterconnectId", "OwnerAccount", "Vlan"},
			"allocate-hosted-connection":                            {"Bandwidth", "ConnectionId", "ConnectionName", "OwnerAccount", "Tags", "Vlan"},
			"allocate-private-virtual-interface":                    {"ConnectionId", "NewPrivateVirtualInterfaceAllocation", "OwnerAccount"},
			"allocate-public-virtual-interface":                     {"ConnectionId", "NewPublicVirtualInterfaceAllocation", "OwnerAccount"},
			"allocate-transit-virtual-interface":                    {"ConnectionId", "NewTransitVirtualInterfaceAllocation", "OwnerAccount"},
			"associate-connection-with-lag":                         {"ConnectionId", "LagId"},
			"associate-hosted-connection":                           {"ConnectionId", "ParentConnectionId"},
			"associate-mac-sec-key":                                 {"Cak", "Ckn", "ConnectionId", "SecretARN"},
			"associate-virtual-interface":                           {"ConnectionId", "VirtualInterfaceId"},
			"confirm-connection":                                    {"ConnectionId"},
			"confirm-customer-agreement":                            {"AgreementName"},
			"confirm-private-virtual-interface":                     {"DirectConnectGatewayId", "VirtualGatewayId", "VirtualInterfaceId"},
			"confirm-public-virtual-interface":                      {"VirtualInterfaceId"},
			"confirm-transit-virtual-interface":                     {"DirectConnectGatewayId", "VirtualInterfaceId"},
			"create-bgp-peer":                                       {"NewBGPPeer", "VirtualInterfaceId"},
			"create-connection":                                     {"Bandwidth", "ConnectionName", "LagId", "Location", "ProviderName", "RequestMACSec", "Tags"},
			"create-direct-connect-gateway":                         {"AmazonSideAsn", "DirectConnectGatewayName", "Tags"},
			"create-direct-connect-gateway-association":             {"AddAllowedPrefixesToDirectConnectGateway", "DirectConnectGatewayId", "GatewayId", "VirtualGatewayId"},
			"create-direct-connect-gateway-association-proposal":    {"AddAllowedPrefixesToDirectConnectGateway", "DirectConnectGatewayId", "DirectConnectGatewayOwnerAccount", "GatewayId", "RemoveAllowedPrefixesToDirectConnectGateway"},
			"create-interconnect":                                   {"Bandwidth", "InterconnectName", "LagId", "Location", "ProviderName", "RequestMACSec", "Tags"},
			"create-lag":                                            {"ChildConnectionTags", "ConnectionId", "ConnectionsBandwidth", "LagName", "Location", "NumberOfConnections", "ProviderName", "RequestMACSec", "Tags"},
			"create-private-virtual-interface":                      {"ConnectionId", "NewPrivateVirtualInterface"},
			"create-public-virtual-interface":                       {"ConnectionId", "NewPublicVirtualInterface"},
			"create-transit-virtual-interface":                      {"ConnectionId", "NewTransitVirtualInterface"},
			"delete-bgp-peer":                                       {"Asn", "AsnLong", "BgpPeerId", "CustomerAddress", "VirtualInterfaceId"},
			"delete-connection":                                     {"ConnectionId"},
			"delete-direct-connect-gateway":                         {"DirectConnectGatewayId"},
			"delete-direct-connect-gateway-association":             {"AssociationId", "DirectConnectGatewayId", "VirtualGatewayId"},
			"delete-direct-connect-gateway-association-proposal":    {"ProposalId"},
			"delete-interconnect":                                   {"InterconnectId"},
			"delete-lag":                                            {"LagId"},
			"delete-virtual-interface":                              {"VirtualInterfaceId"},
			"describe-connection-loa":                               {"ConnectionId", "LoaContentType", "ProviderName"},
			"describe-connections":                                  {"ConnectionId", "MaxResults", "NextToken"},
			"describe-connections-on-interconnect":                  {"InterconnectId"},
			"describe-customer-metadata":                            {},
			"describe-direct-connect-gateway-association-proposals": {"AssociatedGatewayId", "DirectConnectGatewayId", "MaxResults", "NextToken", "ProposalId"},
			"describe-direct-connect-gateway-associations":          {"AssociatedGatewayId", "AssociationId", "DirectConnectGatewayId", "MaxResults", "NextToken", "VirtualGatewayId"},
			"describe-direct-connect-gateway-attachments":           {"DirectConnectGatewayId", "MaxResults", "NextToken", "VirtualInterfaceId"},
			"describe-direct-connect-gateways":                      {"DirectConnectGatewayId", "MaxResults", "NextToken"},
			"describe-hosted-connections":                           {"ConnectionId", "MaxResults", "NextToken"},
			"describe-interconnect-loa":                             {"InterconnectId", "LoaContentType", "ProviderName"},
			"describe-interconnects":                                {"InterconnectId", "MaxResults", "NextToken"},
			"describe-lags":                                         {"LagId", "MaxResults", "NextToken"},
			"describe-loa":                                          {"ConnectionId", "LoaContentType", "ProviderName"},
			"describe-locations":                                    {},
			"describe-router-configuration":                         {"RouterTypeIdentifier", "VirtualInterfaceId"},
			"describe-tags":                                         {"ResourceArns"},
			"describe-virtual-gateways":                             {},
			"describe-virtual-interfaces":                           {"ConnectionId", "MaxResults", "NextToken", "VirtualInterfaceId"},
			"disassociate-connection-from-lag":                      {"ConnectionId", "LagId"},
			"disassociate-mac-sec-key":                              {"ConnectionId", "SecretARN"},
			"list-virtual-interface-test-history":                   {"BgpPeers", "MaxResults", "NextToken", "Status", "TestId", "VirtualInterfaceId"},
			"start-bgp-failover-test":                               {"BgpPeers", "TestDurationInMinutes", "VirtualInterfaceId"},
			"stop-bgp-failover-test":                                {"VirtualInterfaceId"},
			"tag-resource":                                          {"ResourceArn", "Tags"},
			"untag-resource":                                        {"ResourceArn", "TagKeys"},
			"update-connection":                                     {"ConnectionId", "ConnectionName", "EncryptionMode"},
			"update-direct-connect-gateway":                         {"DirectConnectGatewayId", "NewDirectConnectGatewayName"},
			"update-direct-connect-gateway-association":             {"AddAllowedPrefixesToDirectConnectGateway", "AssociationId", "RemoveAllowedPrefixesToDirectConnectGateway"},
			"update-lag":                                            {"EncryptionMode", "LagId", "LagName", "MinimumLinks"},
			"update-virtual-interface-attributes":                   {"EnableSiteLink", "Mtu", "VirtualInterfaceId", "VirtualInterfaceName"},
		},
		OperationInputTypes: map[string]map[string]string{
			"accept-direct-connect-gateway-association-proposal":    {"AssociatedGatewayOwnerAccount": "*string", "DirectConnectGatewayId": "*string", "OverrideAllowedPrefixesToDirectConnectGateway": "[]types.RouteFilterPrefix", "ProposalId": "*string"},
			"allocate-connection-on-interconnect":                   {"Bandwidth": "*string", "ConnectionName": "*string", "InterconnectId": "*string", "OwnerAccount": "*string", "Vlan": "int32"},
			"allocate-hosted-connection":                            {"Bandwidth": "*string", "ConnectionId": "*string", "ConnectionName": "*string", "OwnerAccount": "*string", "Tags": "[]types.Tag", "Vlan": "int32"},
			"allocate-private-virtual-interface":                    {"ConnectionId": "*string", "NewPrivateVirtualInterfaceAllocation": "*types.NewPrivateVirtualInterfaceAllocation", "OwnerAccount": "*string"},
			"allocate-public-virtual-interface":                     {"ConnectionId": "*string", "NewPublicVirtualInterfaceAllocation": "*types.NewPublicVirtualInterfaceAllocation", "OwnerAccount": "*string"},
			"allocate-transit-virtual-interface":                    {"ConnectionId": "*string", "NewTransitVirtualInterfaceAllocation": "*types.NewTransitVirtualInterfaceAllocation", "OwnerAccount": "*string"},
			"associate-connection-with-lag":                         {"ConnectionId": "*string", "LagId": "*string"},
			"associate-hosted-connection":                           {"ConnectionId": "*string", "ParentConnectionId": "*string"},
			"associate-mac-sec-key":                                 {"Cak": "*string", "Ckn": "*string", "ConnectionId": "*string", "SecretARN": "*string"},
			"associate-virtual-interface":                           {"ConnectionId": "*string", "VirtualInterfaceId": "*string"},
			"confirm-connection":                                    {"ConnectionId": "*string"},
			"confirm-customer-agreement":                            {"AgreementName": "*string"},
			"confirm-private-virtual-interface":                     {"DirectConnectGatewayId": "*string", "VirtualGatewayId": "*string", "VirtualInterfaceId": "*string"},
			"confirm-public-virtual-interface":                      {"VirtualInterfaceId": "*string"},
			"confirm-transit-virtual-interface":                     {"DirectConnectGatewayId": "*string", "VirtualInterfaceId": "*string"},
			"create-bgp-peer":                                       {"NewBGPPeer": "*types.NewBGPPeer", "VirtualInterfaceId": "*string"},
			"create-connection":                                     {"Bandwidth": "*string", "ConnectionName": "*string", "LagId": "*string", "Location": "*string", "ProviderName": "*string", "RequestMACSec": "*bool", "Tags": "[]types.Tag"},
			"create-direct-connect-gateway":                         {"AmazonSideAsn": "*int64", "DirectConnectGatewayName": "*string", "Tags": "[]types.Tag"},
			"create-direct-connect-gateway-association":             {"AddAllowedPrefixesToDirectConnectGateway": "[]types.RouteFilterPrefix", "DirectConnectGatewayId": "*string", "GatewayId": "*string", "VirtualGatewayId": "*string"},
			"create-direct-connect-gateway-association-proposal":    {"AddAllowedPrefixesToDirectConnectGateway": "[]types.RouteFilterPrefix", "DirectConnectGatewayId": "*string", "DirectConnectGatewayOwnerAccount": "*string", "GatewayId": "*string", "RemoveAllowedPrefixesToDirectConnectGateway": "[]types.RouteFilterPrefix"},
			"create-interconnect":                                   {"Bandwidth": "*string", "InterconnectName": "*string", "LagId": "*string", "Location": "*string", "ProviderName": "*string", "RequestMACSec": "*bool", "Tags": "[]types.Tag"},
			"create-lag":                                            {"ChildConnectionTags": "[]types.Tag", "ConnectionId": "*string", "ConnectionsBandwidth": "*string", "LagName": "*string", "Location": "*string", "NumberOfConnections": "int32", "ProviderName": "*string", "RequestMACSec": "*bool", "Tags": "[]types.Tag"},
			"create-private-virtual-interface":                      {"ConnectionId": "*string", "NewPrivateVirtualInterface": "*types.NewPrivateVirtualInterface"},
			"create-public-virtual-interface":                       {"ConnectionId": "*string", "NewPublicVirtualInterface": "*types.NewPublicVirtualInterface"},
			"create-transit-virtual-interface":                      {"ConnectionId": "*string", "NewTransitVirtualInterface": "*types.NewTransitVirtualInterface"},
			"delete-bgp-peer":                                       {"Asn": "int32", "AsnLong": "*int64", "BgpPeerId": "*string", "CustomerAddress": "*string", "VirtualInterfaceId": "*string"},
			"delete-connection":                                     {"ConnectionId": "*string"},
			"delete-direct-connect-gateway":                         {"DirectConnectGatewayId": "*string"},
			"delete-direct-connect-gateway-association":             {"AssociationId": "*string", "DirectConnectGatewayId": "*string", "VirtualGatewayId": "*string"},
			"delete-direct-connect-gateway-association-proposal":    {"ProposalId": "*string"},
			"delete-interconnect":                                   {"InterconnectId": "*string"},
			"delete-lag":                                            {"LagId": "*string"},
			"delete-virtual-interface":                              {"VirtualInterfaceId": "*string"},
			"describe-connection-loa":                               {"ConnectionId": "*string", "LoaContentType": "types.LoaContentType", "ProviderName": "*string"},
			"describe-connections":                                  {"ConnectionId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-connections-on-interconnect":                  {"InterconnectId": "*string"},
			"describe-customer-metadata":                            {},
			"describe-direct-connect-gateway-association-proposals": {"AssociatedGatewayId": "*string", "DirectConnectGatewayId": "*string", "MaxResults": "*int32", "NextToken": "*string", "ProposalId": "*string"},
			"describe-direct-connect-gateway-associations":          {"AssociatedGatewayId": "*string", "AssociationId": "*string", "DirectConnectGatewayId": "*string", "MaxResults": "*int32", "NextToken": "*string", "VirtualGatewayId": "*string"},
			"describe-direct-connect-gateway-attachments":           {"DirectConnectGatewayId": "*string", "MaxResults": "*int32", "NextToken": "*string", "VirtualInterfaceId": "*string"},
			"describe-direct-connect-gateways":                      {"DirectConnectGatewayId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-hosted-connections":                           {"ConnectionId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-interconnect-loa":                             {"InterconnectId": "*string", "LoaContentType": "types.LoaContentType", "ProviderName": "*string"},
			"describe-interconnects":                                {"InterconnectId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-lags":                                         {"LagId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-loa":                                          {"ConnectionId": "*string", "LoaContentType": "types.LoaContentType", "ProviderName": "*string"},
			"describe-locations":                                    {},
			"describe-router-configuration":                         {"RouterTypeIdentifier": "*string", "VirtualInterfaceId": "*string"},
			"describe-tags":                                         {"ResourceArns": "[]string"},
			"describe-virtual-gateways":                             {},
			"describe-virtual-interfaces":                           {"ConnectionId": "*string", "MaxResults": "*int32", "NextToken": "*string", "VirtualInterfaceId": "*string"},
			"disassociate-connection-from-lag":                      {"ConnectionId": "*string", "LagId": "*string"},
			"disassociate-mac-sec-key":                              {"ConnectionId": "*string", "SecretARN": "*string"},
			"list-virtual-interface-test-history":                   {"BgpPeers": "[]string", "MaxResults": "*int32", "NextToken": "*string", "Status": "*string", "TestId": "*string", "VirtualInterfaceId": "*string"},
			"start-bgp-failover-test":                               {"BgpPeers": "[]string", "TestDurationInMinutes": "*int32", "VirtualInterfaceId": "*string"},
			"stop-bgp-failover-test":                                {"VirtualInterfaceId": "*string"},
			"tag-resource":                                          {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"untag-resource":                                        {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-connection":                                     {"ConnectionId": "*string", "ConnectionName": "*string", "EncryptionMode": "*string"},
			"update-direct-connect-gateway":                         {"DirectConnectGatewayId": "*string", "NewDirectConnectGatewayName": "*string"},
			"update-direct-connect-gateway-association":             {"AddAllowedPrefixesToDirectConnectGateway": "[]types.RouteFilterPrefix", "AssociationId": "*string", "RemoveAllowedPrefixesToDirectConnectGateway": "[]types.RouteFilterPrefix"},
			"update-lag":                                            {"EncryptionMode": "*string", "LagId": "*string", "LagName": "*string", "MinimumLinks": "int32"},
			"update-virtual-interface-attributes":                   {"EnableSiteLink": "*bool", "Mtu": "*int32", "VirtualInterfaceId": "*string", "VirtualInterfaceName": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"accept-direct-connect-gateway-association-proposal":    {"AssociatedGatewayOwnerAccount", "DirectConnectGatewayId", "ProposalId"},
			"allocate-connection-on-interconnect":                   {"Bandwidth", "ConnectionName", "InterconnectId", "OwnerAccount", "Vlan"},
			"allocate-hosted-connection":                            {"Bandwidth", "ConnectionId", "ConnectionName", "OwnerAccount", "Vlan"},
			"allocate-private-virtual-interface":                    {"ConnectionId", "NewPrivateVirtualInterfaceAllocation", "OwnerAccount"},
			"allocate-public-virtual-interface":                     {"ConnectionId", "NewPublicVirtualInterfaceAllocation", "OwnerAccount"},
			"allocate-transit-virtual-interface":                    {"ConnectionId", "NewTransitVirtualInterfaceAllocation", "OwnerAccount"},
			"associate-connection-with-lag":                         {"ConnectionId", "LagId"},
			"associate-hosted-connection":                           {"ConnectionId", "ParentConnectionId"},
			"associate-mac-sec-key":                                 {"ConnectionId"},
			"associate-virtual-interface":                           {"ConnectionId", "VirtualInterfaceId"},
			"confirm-connection":                                    {"ConnectionId"},
			"confirm-customer-agreement":                            {},
			"confirm-private-virtual-interface":                     {"VirtualInterfaceId"},
			"confirm-public-virtual-interface":                      {"VirtualInterfaceId"},
			"confirm-transit-virtual-interface":                     {"DirectConnectGatewayId", "VirtualInterfaceId"},
			"create-bgp-peer":                                       {},
			"create-connection":                                     {"Bandwidth", "ConnectionName", "Location"},
			"create-direct-connect-gateway":                         {"DirectConnectGatewayName"},
			"create-direct-connect-gateway-association":             {"DirectConnectGatewayId"},
			"create-direct-connect-gateway-association-proposal":    {"DirectConnectGatewayId", "DirectConnectGatewayOwnerAccount", "GatewayId"},
			"create-interconnect":                                   {"Bandwidth", "InterconnectName", "Location"},
			"create-lag":                                            {"ConnectionsBandwidth", "LagName", "Location", "NumberOfConnections"},
			"create-private-virtual-interface":                      {"ConnectionId", "NewPrivateVirtualInterface"},
			"create-public-virtual-interface":                       {"ConnectionId", "NewPublicVirtualInterface"},
			"create-transit-virtual-interface":                      {"ConnectionId", "NewTransitVirtualInterface"},
			"delete-bgp-peer":                                       {},
			"delete-connection":                                     {"ConnectionId"},
			"delete-direct-connect-gateway":                         {"DirectConnectGatewayId"},
			"delete-direct-connect-gateway-association":             {},
			"delete-direct-connect-gateway-association-proposal":    {"ProposalId"},
			"delete-interconnect":                                   {"InterconnectId"},
			"delete-lag":                                            {"LagId"},
			"delete-virtual-interface":                              {"VirtualInterfaceId"},
			"describe-connection-loa":                               {"ConnectionId"},
			"describe-connections":                                  {},
			"describe-connections-on-interconnect":                  {"InterconnectId"},
			"describe-customer-metadata":                            {},
			"describe-direct-connect-gateway-association-proposals": {},
			"describe-direct-connect-gateway-associations":          {},
			"describe-direct-connect-gateway-attachments":           {},
			"describe-direct-connect-gateways":                      {},
			"describe-hosted-connections":                           {"ConnectionId"},
			"describe-interconnect-loa":                             {"InterconnectId"},
			"describe-interconnects":                                {},
			"describe-lags":                                         {},
			"describe-loa":                                          {"ConnectionId"},
			"describe-locations":                                    {},
			"describe-router-configuration":                         {"VirtualInterfaceId"},
			"describe-tags":                                         {"ResourceArns"},
			"describe-virtual-gateways":                             {},
			"describe-virtual-interfaces":                           {},
			"disassociate-connection-from-lag":                      {"ConnectionId", "LagId"},
			"disassociate-mac-sec-key":                              {"ConnectionId", "SecretARN"},
			"list-virtual-interface-test-history":                   {},
			"start-bgp-failover-test":                               {"VirtualInterfaceId"},
			"stop-bgp-failover-test":                                {"VirtualInterfaceId"},
			"tag-resource":                                          {"ResourceArn", "Tags"},
			"untag-resource":                                        {"ResourceArn", "TagKeys"},
			"update-connection":                                     {"ConnectionId"},
			"update-direct-connect-gateway":                         {"DirectConnectGatewayId", "NewDirectConnectGatewayName"},
			"update-direct-connect-gateway-association":             {},
			"update-lag":                                            {"LagId"},
			"update-virtual-interface-attributes":                   {"VirtualInterfaceId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("directconnect", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
