package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/wickr/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-create-user", "batch-delete-user", "batch-lookup-user-uname", "batch-reinvite-user", "batch-reset-devices-for-user", "batch-toggle-user-suspend-status", "create-bot", "create-data-retention-bot", "create-data-retention-bot-challenge", "create-network", "create-security-group", "delete-bot", "delete-data-retention-bot", "delete-network", "delete-security-group", "get-bot", "get-bots-count", "get-data-retention-bot", "get-guest-user-history-count", "get-network", "get-network-settings", "get-oidc-info", "get-opentdf-config", "get-security-group", "get-user", "get-users-count", "list-blocked-guest-users", "list-bots", "list-devices-for-user", "list-guest-users", "list-networks", "list-security-group-users", "list-security-groups", "list-users", "register-oidc-config", "register-oidc-config-test", "register-opentdf-config", "update-bot", "update-data-retention", "update-guest-user", "update-network", "update-network-settings", "update-security-group", "update-user"},
		OperationSet: map[string]bool{"batch-create-user": true, "batch-delete-user": true, "batch-lookup-user-uname": true, "batch-reinvite-user": true, "batch-reset-devices-for-user": true, "batch-toggle-user-suspend-status": true, "create-bot": true, "create-data-retention-bot": true, "create-data-retention-bot-challenge": true, "create-network": true, "create-security-group": true, "delete-bot": true, "delete-data-retention-bot": true, "delete-network": true, "delete-security-group": true, "get-bot": true, "get-bots-count": true, "get-data-retention-bot": true, "get-guest-user-history-count": true, "get-network": true, "get-network-settings": true, "get-oidc-info": true, "get-opentdf-config": true, "get-security-group": true, "get-user": true, "get-users-count": true, "list-blocked-guest-users": true, "list-bots": true, "list-devices-for-user": true, "list-guest-users": true, "list-networks": true, "list-security-group-users": true, "list-security-groups": true, "list-users": true, "register-oidc-config": true, "register-oidc-config-test": true, "register-opentdf-config": true, "update-bot": true, "update-data-retention": true, "update-guest-user": true, "update-network": true, "update-network-settings": true, "update-security-group": true, "update-user": true},
		OperationInputs: map[string][]string{
			"batch-create-user":                   {"ClientToken", "NetworkId", "Users"},
			"batch-delete-user":                   {"ClientToken", "NetworkId", "UserIds"},
			"batch-lookup-user-uname":             {"ClientToken", "NetworkId", "Unames"},
			"batch-reinvite-user":                 {"ClientToken", "NetworkId", "UserIds"},
			"batch-reset-devices-for-user":        {"AppIds", "ClientToken", "NetworkId", "UserId"},
			"batch-toggle-user-suspend-status":    {"ClientToken", "NetworkId", "Suspend", "UserIds"},
			"create-bot":                          {"Challenge", "DisplayName", "GroupId", "NetworkId", "Username"},
			"create-data-retention-bot":           {"NetworkId"},
			"create-data-retention-bot-challenge": {"NetworkId"},
			"create-network":                      {"AccessLevel", "EnablePremiumFreeTrial", "EncryptionKeyArn", "NetworkName"},
			"create-security-group":               {"ClientToken", "Name", "NetworkId", "SecurityGroupSettings"},
			"delete-bot":                          {"BotId", "NetworkId"},
			"delete-data-retention-bot":           {"NetworkId"},
			"delete-network":                      {"ClientToken", "NetworkId"},
			"delete-security-group":               {"GroupId", "NetworkId"},
			"get-bot":                             {"BotId", "NetworkId"},
			"get-bots-count":                      {"NetworkId"},
			"get-data-retention-bot":              {"NetworkId"},
			"get-guest-user-history-count":        {"NetworkId"},
			"get-network":                         {"NetworkId"},
			"get-network-settings":                {"NetworkId"},
			"get-oidc-info":                       {"Certificate", "ClientId", "ClientSecret", "Code", "CodeVerifier", "GrantType", "NetworkId", "RedirectUri", "Url"},
			"get-opentdf-config":                  {"NetworkId"},
			"get-security-group":                  {"GroupId", "NetworkId"},
			"get-user":                            {"EndTime", "NetworkId", "StartTime", "UserId"},
			"get-users-count":                     {"NetworkId"},
			"list-blocked-guest-users":            {"Admin", "MaxResults", "NetworkId", "NextToken", "SortDirection", "SortFields", "Username"},
			"list-bots":                           {"DisplayName", "GroupId", "MaxResults", "NetworkId", "NextToken", "SortDirection", "SortFields", "Status", "Username"},
			"list-devices-for-user":               {"MaxResults", "NetworkId", "NextToken", "SortDirection", "SortFields", "UserId"},
			"list-guest-users":                    {"BillingPeriod", "MaxResults", "NetworkId", "NextToken", "SortDirection", "SortFields", "Username"},
			"list-networks":                       {"MaxResults", "NextToken", "SortDirection", "SortFields"},
			"list-security-group-users":           {"GroupId", "MaxResults", "NetworkId", "NextToken", "SortDirection", "SortFields"},
			"list-security-groups":                {"MaxResults", "NetworkId", "NextToken", "SortDirection", "SortFields"},
			"list-users":                          {"FirstName", "GroupId", "LastName", "MaxResults", "NetworkId", "NextToken", "SortDirection", "SortFields", "Status", "Username"},
			"register-oidc-config":                {"CompanyId", "CustomUsername", "ExtraAuthParams", "Issuer", "NetworkId", "Scopes", "Secret", "SsoTokenBufferMinutes", "UserId"},
			"register-oidc-config-test":           {"Certificate", "ExtraAuthParams", "Issuer", "NetworkId", "Scopes"},
			"register-opentdf-config":             {"ClientId", "ClientSecret", "Domain", "DryRun", "NetworkId", "Provider"},
			"update-bot":                          {"BotId", "Challenge", "DisplayName", "GroupId", "NetworkId", "Suspend"},
			"update-data-retention":               {"ActionType", "NetworkId"},
			"update-guest-user":                   {"Block", "NetworkId", "UsernameHash"},
			"update-network":                      {"ClientToken", "EncryptionKeyArn", "NetworkId", "NetworkName"},
			"update-network-settings":             {"NetworkId", "Settings"},
			"update-security-group":               {"GroupId", "Name", "NetworkId", "SecurityGroupSettings"},
			"update-user":                         {"NetworkId", "UserDetails", "UserId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-create-user":                   {"ClientToken": "*string", "NetworkId": "*string", "Users": "[]types.BatchCreateUserRequestItem"},
			"batch-delete-user":                   {"ClientToken": "*string", "NetworkId": "*string", "UserIds": "[]string"},
			"batch-lookup-user-uname":             {"ClientToken": "*string", "NetworkId": "*string", "Unames": "[]string"},
			"batch-reinvite-user":                 {"ClientToken": "*string", "NetworkId": "*string", "UserIds": "[]string"},
			"batch-reset-devices-for-user":        {"AppIds": "[]string", "ClientToken": "*string", "NetworkId": "*string", "UserId": "*string"},
			"batch-toggle-user-suspend-status":    {"ClientToken": "*string", "NetworkId": "*string", "Suspend": "*bool", "UserIds": "[]string"},
			"create-bot":                          {"Challenge": "*string", "DisplayName": "*string", "GroupId": "*string", "NetworkId": "*string", "Username": "*string"},
			"create-data-retention-bot":           {"NetworkId": "*string"},
			"create-data-retention-bot-challenge": {"NetworkId": "*string"},
			"create-network":                      {"AccessLevel": "types.AccessLevel", "EnablePremiumFreeTrial": "*bool", "EncryptionKeyArn": "*string", "NetworkName": "*string"},
			"create-security-group":               {"ClientToken": "*string", "Name": "*string", "NetworkId": "*string", "SecurityGroupSettings": "*types.SecurityGroupSettingsRequest"},
			"delete-bot":                          {"BotId": "*string", "NetworkId": "*string"},
			"delete-data-retention-bot":           {"NetworkId": "*string"},
			"delete-network":                      {"ClientToken": "*string", "NetworkId": "*string"},
			"delete-security-group":               {"GroupId": "*string", "NetworkId": "*string"},
			"get-bot":                             {"BotId": "*string", "NetworkId": "*string"},
			"get-bots-count":                      {"NetworkId": "*string"},
			"get-data-retention-bot":              {"NetworkId": "*string"},
			"get-guest-user-history-count":        {"NetworkId": "*string"},
			"get-network":                         {"NetworkId": "*string"},
			"get-network-settings":                {"NetworkId": "*string"},
			"get-oidc-info":                       {"Certificate": "*string", "ClientId": "*string", "ClientSecret": "*string", "Code": "*string", "CodeVerifier": "*string", "GrantType": "*string", "NetworkId": "*string", "RedirectUri": "*string", "Url": "*string"},
			"get-opentdf-config":                  {"NetworkId": "*string"},
			"get-security-group":                  {"GroupId": "*string", "NetworkId": "*string"},
			"get-user":                            {"EndTime": "*time.Time", "NetworkId": "*string", "StartTime": "*time.Time", "UserId": "*string"},
			"get-users-count":                     {"NetworkId": "*string"},
			"list-blocked-guest-users":            {"Admin": "*string", "MaxResults": "*int32", "NetworkId": "*string", "NextToken": "*string", "SortDirection": "types.SortDirection", "SortFields": "*string", "Username": "*string"},
			"list-bots":                           {"DisplayName": "*string", "GroupId": "*string", "MaxResults": "*int32", "NetworkId": "*string", "NextToken": "*string", "SortDirection": "types.SortDirection", "SortFields": "*string", "Status": "types.BotStatus", "Username": "*string"},
			"list-devices-for-user":               {"MaxResults": "*int32", "NetworkId": "*string", "NextToken": "*string", "SortDirection": "types.SortDirection", "SortFields": "*string", "UserId": "*string"},
			"list-guest-users":                    {"BillingPeriod": "*string", "MaxResults": "*int32", "NetworkId": "*string", "NextToken": "*string", "SortDirection": "types.SortDirection", "SortFields": "*string", "Username": "*string"},
			"list-networks":                       {"MaxResults": "*int32", "NextToken": "*string", "SortDirection": "types.SortDirection", "SortFields": "*string"},
			"list-security-group-users":           {"GroupId": "*string", "MaxResults": "*int32", "NetworkId": "*string", "NextToken": "*string", "SortDirection": "types.SortDirection", "SortFields": "*string"},
			"list-security-groups":                {"MaxResults": "*int32", "NetworkId": "*string", "NextToken": "*string", "SortDirection": "types.SortDirection", "SortFields": "*string"},
			"list-users":                          {"FirstName": "*string", "GroupId": "*string", "LastName": "*string", "MaxResults": "*int32", "NetworkId": "*string", "NextToken": "*string", "SortDirection": "types.SortDirection", "SortFields": "*string", "Status": "types.UserStatus", "Username": "*string"},
			"register-oidc-config":                {"CompanyId": "*string", "CustomUsername": "*string", "ExtraAuthParams": "*string", "Issuer": "*string", "NetworkId": "*string", "Scopes": "*string", "Secret": "*string", "SsoTokenBufferMinutes": "*int32", "UserId": "*string"},
			"register-oidc-config-test":           {"Certificate": "*string", "ExtraAuthParams": "*string", "Issuer": "*string", "NetworkId": "*string", "Scopes": "*string"},
			"register-opentdf-config":             {"ClientId": "*string", "ClientSecret": "*string", "Domain": "*string", "DryRun": "*bool", "NetworkId": "*string", "Provider": "*string"},
			"update-bot":                          {"BotId": "*string", "Challenge": "*string", "DisplayName": "*string", "GroupId": "*string", "NetworkId": "*string", "Suspend": "*bool"},
			"update-data-retention":               {"ActionType": "types.DataRetentionActionType", "NetworkId": "*string"},
			"update-guest-user":                   {"Block": "*bool", "NetworkId": "*string", "UsernameHash": "*string"},
			"update-network":                      {"ClientToken": "*string", "EncryptionKeyArn": "*string", "NetworkId": "*string", "NetworkName": "*string"},
			"update-network-settings":             {"NetworkId": "*string", "Settings": "*types.NetworkSettings"},
			"update-security-group":               {"GroupId": "*string", "Name": "*string", "NetworkId": "*string", "SecurityGroupSettings": "*types.SecurityGroupSettings"},
			"update-user":                         {"NetworkId": "*string", "UserDetails": "*types.UpdateUserDetails", "UserId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-create-user":                   {"NetworkId", "Users"},
			"batch-delete-user":                   {"NetworkId", "UserIds"},
			"batch-lookup-user-uname":             {"NetworkId", "Unames"},
			"batch-reinvite-user":                 {"NetworkId", "UserIds"},
			"batch-reset-devices-for-user":        {"AppIds", "NetworkId", "UserId"},
			"batch-toggle-user-suspend-status":    {"NetworkId", "Suspend", "UserIds"},
			"create-bot":                          {"Challenge", "GroupId", "NetworkId", "Username"},
			"create-data-retention-bot":           {"NetworkId"},
			"create-data-retention-bot-challenge": {"NetworkId"},
			"create-network":                      {"AccessLevel", "NetworkName"},
			"create-security-group":               {"Name", "NetworkId", "SecurityGroupSettings"},
			"delete-bot":                          {"BotId", "NetworkId"},
			"delete-data-retention-bot":           {"NetworkId"},
			"delete-network":                      {"NetworkId"},
			"delete-security-group":               {"GroupId", "NetworkId"},
			"get-bot":                             {"BotId", "NetworkId"},
			"get-bots-count":                      {"NetworkId"},
			"get-data-retention-bot":              {"NetworkId"},
			"get-guest-user-history-count":        {"NetworkId"},
			"get-network":                         {"NetworkId"},
			"get-network-settings":                {"NetworkId"},
			"get-oidc-info":                       {"NetworkId"},
			"get-opentdf-config":                  {"NetworkId"},
			"get-security-group":                  {"GroupId", "NetworkId"},
			"get-user":                            {"NetworkId", "UserId"},
			"get-users-count":                     {"NetworkId"},
			"list-blocked-guest-users":            {"NetworkId"},
			"list-bots":                           {"NetworkId"},
			"list-devices-for-user":               {"NetworkId", "UserId"},
			"list-guest-users":                    {"NetworkId"},
			"list-networks":                       {},
			"list-security-group-users":           {"GroupId", "NetworkId"},
			"list-security-groups":                {"NetworkId"},
			"list-users":                          {"NetworkId"},
			"register-oidc-config":                {"CompanyId", "Issuer", "NetworkId", "Scopes"},
			"register-oidc-config-test":           {"Issuer", "NetworkId", "Scopes"},
			"register-opentdf-config":             {"ClientId", "ClientSecret", "Domain", "NetworkId", "Provider"},
			"update-bot":                          {"BotId", "NetworkId"},
			"update-data-retention":               {"ActionType", "NetworkId"},
			"update-guest-user":                   {"Block", "NetworkId", "UsernameHash"},
			"update-network":                      {"NetworkId", "NetworkName"},
			"update-network-settings":             {"NetworkId", "Settings"},
			"update-security-group":               {"GroupId", "NetworkId"},
			"update-user":                         {"NetworkId", "UserId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("wickr", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
