package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/ses/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"clone-receipt-rule-set", "create-configuration-set", "create-configuration-set-event-destination", "create-configuration-set-tracking-options", "create-custom-verification-email-template", "create-receipt-filter", "create-receipt-rule", "create-receipt-rule-set", "create-template", "delete-configuration-set", "delete-configuration-set-event-destination", "delete-configuration-set-tracking-options", "delete-custom-verification-email-template", "delete-identity", "delete-identity-policy", "delete-receipt-filter", "delete-receipt-rule", "delete-receipt-rule-set", "delete-template", "delete-verified-email-address", "describe-active-receipt-rule-set", "describe-configuration-set", "describe-receipt-rule", "describe-receipt-rule-set", "get-account-sending-enabled", "get-custom-verification-email-template", "get-identity-dkim-attributes", "get-identity-mail-from-domain-attributes", "get-identity-notification-attributes", "get-identity-policies", "get-identity-verification-attributes", "get-send-quota", "get-send-statistics", "get-template", "list-configuration-sets", "list-custom-verification-email-templates", "list-identities", "list-identity-policies", "list-receipt-filters", "list-receipt-rule-sets", "list-templates", "list-verified-email-addresses", "put-configuration-set-delivery-options", "put-identity-policy", "reorder-receipt-rule-set", "send-bounce", "send-bulk-templated-email", "send-custom-verification-email", "send-email", "send-raw-email", "send-templated-email", "set-active-receipt-rule-set", "set-identity-dkim-enabled", "set-identity-feedback-forwarding-enabled", "set-identity-headers-in-notifications-enabled", "set-identity-mail-from-domain", "set-identity-notification-topic", "set-receipt-rule-position", "test-render-template", "update-account-sending-enabled", "update-configuration-set-event-destination", "update-configuration-set-reputation-metrics-enabled", "update-configuration-set-sending-enabled", "update-configuration-set-tracking-options", "update-custom-verification-email-template", "update-receipt-rule", "update-template", "verify-domain-dkim", "verify-domain-identity", "verify-email-address", "verify-email-identity"},
		OperationSet: map[string]bool{"clone-receipt-rule-set": true, "create-configuration-set": true, "create-configuration-set-event-destination": true, "create-configuration-set-tracking-options": true, "create-custom-verification-email-template": true, "create-receipt-filter": true, "create-receipt-rule": true, "create-receipt-rule-set": true, "create-template": true, "delete-configuration-set": true, "delete-configuration-set-event-destination": true, "delete-configuration-set-tracking-options": true, "delete-custom-verification-email-template": true, "delete-identity": true, "delete-identity-policy": true, "delete-receipt-filter": true, "delete-receipt-rule": true, "delete-receipt-rule-set": true, "delete-template": true, "delete-verified-email-address": true, "describe-active-receipt-rule-set": true, "describe-configuration-set": true, "describe-receipt-rule": true, "describe-receipt-rule-set": true, "get-account-sending-enabled": true, "get-custom-verification-email-template": true, "get-identity-dkim-attributes": true, "get-identity-mail-from-domain-attributes": true, "get-identity-notification-attributes": true, "get-identity-policies": true, "get-identity-verification-attributes": true, "get-send-quota": true, "get-send-statistics": true, "get-template": true, "list-configuration-sets": true, "list-custom-verification-email-templates": true, "list-identities": true, "list-identity-policies": true, "list-receipt-filters": true, "list-receipt-rule-sets": true, "list-templates": true, "list-verified-email-addresses": true, "put-configuration-set-delivery-options": true, "put-identity-policy": true, "reorder-receipt-rule-set": true, "send-bounce": true, "send-bulk-templated-email": true, "send-custom-verification-email": true, "send-email": true, "send-raw-email": true, "send-templated-email": true, "set-active-receipt-rule-set": true, "set-identity-dkim-enabled": true, "set-identity-feedback-forwarding-enabled": true, "set-identity-headers-in-notifications-enabled": true, "set-identity-mail-from-domain": true, "set-identity-notification-topic": true, "set-receipt-rule-position": true, "test-render-template": true, "update-account-sending-enabled": true, "update-configuration-set-event-destination": true, "update-configuration-set-reputation-metrics-enabled": true, "update-configuration-set-sending-enabled": true, "update-configuration-set-tracking-options": true, "update-custom-verification-email-template": true, "update-receipt-rule": true, "update-template": true, "verify-domain-dkim": true, "verify-domain-identity": true, "verify-email-address": true, "verify-email-identity": true},
		OperationInputs: map[string][]string{
			"clone-receipt-rule-set":                              {"OriginalRuleSetName", "RuleSetName"},
			"create-configuration-set":                            {"ConfigurationSet"},
			"create-configuration-set-event-destination":          {"ConfigurationSetName", "EventDestination"},
			"create-configuration-set-tracking-options":           {"ConfigurationSetName", "TrackingOptions"},
			"create-custom-verification-email-template":           {"FailureRedirectionURL", "FromEmailAddress", "SuccessRedirectionURL", "TemplateContent", "TemplateName", "TemplateSubject"},
			"create-receipt-filter":                               {"Filter"},
			"create-receipt-rule":                                 {"After", "Rule", "RuleSetName"},
			"create-receipt-rule-set":                             {"RuleSetName"},
			"create-template":                                     {"Template"},
			"delete-configuration-set":                            {"ConfigurationSetName"},
			"delete-configuration-set-event-destination":          {"ConfigurationSetName", "EventDestinationName"},
			"delete-configuration-set-tracking-options":           {"ConfigurationSetName"},
			"delete-custom-verification-email-template":           {"TemplateName"},
			"delete-identity":                                     {"Identity"},
			"delete-identity-policy":                              {"Identity", "PolicyName"},
			"delete-receipt-filter":                               {"FilterName"},
			"delete-receipt-rule":                                 {"RuleName", "RuleSetName"},
			"delete-receipt-rule-set":                             {"RuleSetName"},
			"delete-template":                                     {"TemplateName"},
			"delete-verified-email-address":                       {"EmailAddress"},
			"describe-active-receipt-rule-set":                    {},
			"describe-configuration-set":                          {"ConfigurationSetAttributeNames", "ConfigurationSetName"},
			"describe-receipt-rule":                               {"RuleName", "RuleSetName"},
			"describe-receipt-rule-set":                           {"RuleSetName"},
			"get-account-sending-enabled":                         {},
			"get-custom-verification-email-template":              {"TemplateName"},
			"get-identity-dkim-attributes":                        {"Identities"},
			"get-identity-mail-from-domain-attributes":            {"Identities"},
			"get-identity-notification-attributes":                {"Identities"},
			"get-identity-policies":                               {"Identity", "PolicyNames"},
			"get-identity-verification-attributes":                {"Identities"},
			"get-send-quota":                                      {},
			"get-send-statistics":                                 {},
			"get-template":                                        {"TemplateName"},
			"list-configuration-sets":                             {"MaxItems", "NextToken"},
			"list-custom-verification-email-templates":            {"MaxResults", "NextToken"},
			"list-identities":                                     {"IdentityType", "MaxItems", "NextToken"},
			"list-identity-policies":                              {"Identity"},
			"list-receipt-filters":                                {},
			"list-receipt-rule-sets":                              {"NextToken"},
			"list-templates":                                      {"MaxItems", "NextToken"},
			"list-verified-email-addresses":                       {},
			"put-configuration-set-delivery-options":              {"ConfigurationSetName", "DeliveryOptions"},
			"put-identity-policy":                                 {"Identity", "Policy", "PolicyName"},
			"reorder-receipt-rule-set":                            {"RuleNames", "RuleSetName"},
			"send-bounce":                                         {"BounceSender", "BounceSenderArn", "BouncedRecipientInfoList", "Explanation", "MessageDsn", "OriginalMessageId"},
			"send-bulk-templated-email":                           {"ConfigurationSetName", "DefaultTags", "DefaultTemplateData", "Destinations", "ReplyToAddresses", "ReturnPath", "ReturnPathArn", "Source", "SourceArn", "Template", "TemplateArn"},
			"send-custom-verification-email":                      {"ConfigurationSetName", "EmailAddress", "TemplateName"},
			"send-email":                                          {"ConfigurationSetName", "Destination", "Message", "ReplyToAddresses", "ReturnPath", "ReturnPathArn", "Source", "SourceArn", "Tags"},
			"send-raw-email":                                      {"ConfigurationSetName", "Destinations", "FromArn", "RawMessage", "ReturnPathArn", "Source", "SourceArn", "Tags"},
			"send-templated-email":                                {"ConfigurationSetName", "Destination", "ReplyToAddresses", "ReturnPath", "ReturnPathArn", "Source", "SourceArn", "Tags", "Template", "TemplateArn", "TemplateData"},
			"set-active-receipt-rule-set":                         {"RuleSetName"},
			"set-identity-dkim-enabled":                           {"DkimEnabled", "Identity"},
			"set-identity-feedback-forwarding-enabled":            {"ForwardingEnabled", "Identity"},
			"set-identity-headers-in-notifications-enabled":       {"Enabled", "Identity", "NotificationType"},
			"set-identity-mail-from-domain":                       {"BehaviorOnMXFailure", "Identity", "MailFromDomain"},
			"set-identity-notification-topic":                     {"Identity", "NotificationType", "SnsTopic"},
			"set-receipt-rule-position":                           {"After", "RuleName", "RuleSetName"},
			"test-render-template":                                {"TemplateData", "TemplateName"},
			"update-account-sending-enabled":                      {"Enabled"},
			"update-configuration-set-event-destination":          {"ConfigurationSetName", "EventDestination"},
			"update-configuration-set-reputation-metrics-enabled": {"ConfigurationSetName", "Enabled"},
			"update-configuration-set-sending-enabled":            {"ConfigurationSetName", "Enabled"},
			"update-configuration-set-tracking-options":           {"ConfigurationSetName", "TrackingOptions"},
			"update-custom-verification-email-template":           {"FailureRedirectionURL", "FromEmailAddress", "SuccessRedirectionURL", "TemplateContent", "TemplateName", "TemplateSubject"},
			"update-receipt-rule":                                 {"Rule", "RuleSetName"},
			"update-template":                                     {"Template"},
			"verify-domain-dkim":                                  {"Domain"},
			"verify-domain-identity":                              {"Domain"},
			"verify-email-address":                                {"EmailAddress"},
			"verify-email-identity":                               {"EmailAddress"},
		},
		OperationInputTypes: map[string]map[string]string{
			"clone-receipt-rule-set":                              {"OriginalRuleSetName": "*string", "RuleSetName": "*string"},
			"create-configuration-set":                            {"ConfigurationSet": "*types.ConfigurationSet"},
			"create-configuration-set-event-destination":          {"ConfigurationSetName": "*string", "EventDestination": "*types.EventDestination"},
			"create-configuration-set-tracking-options":           {"ConfigurationSetName": "*string", "TrackingOptions": "*types.TrackingOptions"},
			"create-custom-verification-email-template":           {"FailureRedirectionURL": "*string", "FromEmailAddress": "*string", "SuccessRedirectionURL": "*string", "TemplateContent": "*string", "TemplateName": "*string", "TemplateSubject": "*string"},
			"create-receipt-filter":                               {"Filter": "*types.ReceiptFilter"},
			"create-receipt-rule":                                 {"After": "*string", "Rule": "*types.ReceiptRule", "RuleSetName": "*string"},
			"create-receipt-rule-set":                             {"RuleSetName": "*string"},
			"create-template":                                     {"Template": "*types.Template"},
			"delete-configuration-set":                            {"ConfigurationSetName": "*string"},
			"delete-configuration-set-event-destination":          {"ConfigurationSetName": "*string", "EventDestinationName": "*string"},
			"delete-configuration-set-tracking-options":           {"ConfigurationSetName": "*string"},
			"delete-custom-verification-email-template":           {"TemplateName": "*string"},
			"delete-identity":                                     {"Identity": "*string"},
			"delete-identity-policy":                              {"Identity": "*string", "PolicyName": "*string"},
			"delete-receipt-filter":                               {"FilterName": "*string"},
			"delete-receipt-rule":                                 {"RuleName": "*string", "RuleSetName": "*string"},
			"delete-receipt-rule-set":                             {"RuleSetName": "*string"},
			"delete-template":                                     {"TemplateName": "*string"},
			"delete-verified-email-address":                       {"EmailAddress": "*string"},
			"describe-active-receipt-rule-set":                    {},
			"describe-configuration-set":                          {"ConfigurationSetAttributeNames": "[]types.ConfigurationSetAttribute", "ConfigurationSetName": "*string"},
			"describe-receipt-rule":                               {"RuleName": "*string", "RuleSetName": "*string"},
			"describe-receipt-rule-set":                           {"RuleSetName": "*string"},
			"get-account-sending-enabled":                         {},
			"get-custom-verification-email-template":              {"TemplateName": "*string"},
			"get-identity-dkim-attributes":                        {"Identities": "[]string"},
			"get-identity-mail-from-domain-attributes":            {"Identities": "[]string"},
			"get-identity-notification-attributes":                {"Identities": "[]string"},
			"get-identity-policies":                               {"Identity": "*string", "PolicyNames": "[]string"},
			"get-identity-verification-attributes":                {"Identities": "[]string"},
			"get-send-quota":                                      {},
			"get-send-statistics":                                 {},
			"get-template":                                        {"TemplateName": "*string"},
			"list-configuration-sets":                             {"MaxItems": "*int32", "NextToken": "*string"},
			"list-custom-verification-email-templates":            {"MaxResults": "*int32", "NextToken": "*string"},
			"list-identities":                                     {"IdentityType": "types.IdentityType", "MaxItems": "*int32", "NextToken": "*string"},
			"list-identity-policies":                              {"Identity": "*string"},
			"list-receipt-filters":                                {},
			"list-receipt-rule-sets":                              {"NextToken": "*string"},
			"list-templates":                                      {"MaxItems": "*int32", "NextToken": "*string"},
			"list-verified-email-addresses":                       {},
			"put-configuration-set-delivery-options":              {"ConfigurationSetName": "*string", "DeliveryOptions": "*types.DeliveryOptions"},
			"put-identity-policy":                                 {"Identity": "*string", "Policy": "*string", "PolicyName": "*string"},
			"reorder-receipt-rule-set":                            {"RuleNames": "[]string", "RuleSetName": "*string"},
			"send-bounce":                                         {"BounceSender": "*string", "BounceSenderArn": "*string", "BouncedRecipientInfoList": "[]types.BouncedRecipientInfo", "Explanation": "*string", "MessageDsn": "*types.MessageDsn", "OriginalMessageId": "*string"},
			"send-bulk-templated-email":                           {"ConfigurationSetName": "*string", "DefaultTags": "[]types.MessageTag", "DefaultTemplateData": "*string", "Destinations": "[]types.BulkEmailDestination", "ReplyToAddresses": "[]string", "ReturnPath": "*string", "ReturnPathArn": "*string", "Source": "*string", "SourceArn": "*string", "Template": "*string", "TemplateArn": "*string"},
			"send-custom-verification-email":                      {"ConfigurationSetName": "*string", "EmailAddress": "*string", "TemplateName": "*string"},
			"send-email":                                          {"ConfigurationSetName": "*string", "Destination": "*types.Destination", "Message": "*types.Message", "ReplyToAddresses": "[]string", "ReturnPath": "*string", "ReturnPathArn": "*string", "Source": "*string", "SourceArn": "*string", "Tags": "[]types.MessageTag"},
			"send-raw-email":                                      {"ConfigurationSetName": "*string", "Destinations": "[]string", "FromArn": "*string", "RawMessage": "*types.RawMessage", "ReturnPathArn": "*string", "Source": "*string", "SourceArn": "*string", "Tags": "[]types.MessageTag"},
			"send-templated-email":                                {"ConfigurationSetName": "*string", "Destination": "*types.Destination", "ReplyToAddresses": "[]string", "ReturnPath": "*string", "ReturnPathArn": "*string", "Source": "*string", "SourceArn": "*string", "Tags": "[]types.MessageTag", "Template": "*string", "TemplateArn": "*string", "TemplateData": "*string"},
			"set-active-receipt-rule-set":                         {"RuleSetName": "*string"},
			"set-identity-dkim-enabled":                           {"DkimEnabled": "bool", "Identity": "*string"},
			"set-identity-feedback-forwarding-enabled":            {"ForwardingEnabled": "bool", "Identity": "*string"},
			"set-identity-headers-in-notifications-enabled":       {"Enabled": "bool", "Identity": "*string", "NotificationType": "types.NotificationType"},
			"set-identity-mail-from-domain":                       {"BehaviorOnMXFailure": "types.BehaviorOnMXFailure", "Identity": "*string", "MailFromDomain": "*string"},
			"set-identity-notification-topic":                     {"Identity": "*string", "NotificationType": "types.NotificationType", "SnsTopic": "*string"},
			"set-receipt-rule-position":                           {"After": "*string", "RuleName": "*string", "RuleSetName": "*string"},
			"test-render-template":                                {"TemplateData": "*string", "TemplateName": "*string"},
			"update-account-sending-enabled":                      {"Enabled": "bool"},
			"update-configuration-set-event-destination":          {"ConfigurationSetName": "*string", "EventDestination": "*types.EventDestination"},
			"update-configuration-set-reputation-metrics-enabled": {"ConfigurationSetName": "*string", "Enabled": "bool"},
			"update-configuration-set-sending-enabled":            {"ConfigurationSetName": "*string", "Enabled": "bool"},
			"update-configuration-set-tracking-options":           {"ConfigurationSetName": "*string", "TrackingOptions": "*types.TrackingOptions"},
			"update-custom-verification-email-template":           {"FailureRedirectionURL": "*string", "FromEmailAddress": "*string", "SuccessRedirectionURL": "*string", "TemplateContent": "*string", "TemplateName": "*string", "TemplateSubject": "*string"},
			"update-receipt-rule":                                 {"Rule": "*types.ReceiptRule", "RuleSetName": "*string"},
			"update-template":                                     {"Template": "*types.Template"},
			"verify-domain-dkim":                                  {"Domain": "*string"},
			"verify-domain-identity":                              {"Domain": "*string"},
			"verify-email-address":                                {"EmailAddress": "*string"},
			"verify-email-identity":                               {"EmailAddress": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"clone-receipt-rule-set":                              {"OriginalRuleSetName", "RuleSetName"},
			"create-configuration-set":                            {"ConfigurationSet"},
			"create-configuration-set-event-destination":          {"ConfigurationSetName", "EventDestination"},
			"create-configuration-set-tracking-options":           {"ConfigurationSetName", "TrackingOptions"},
			"create-custom-verification-email-template":           {"FailureRedirectionURL", "FromEmailAddress", "SuccessRedirectionURL", "TemplateContent", "TemplateName", "TemplateSubject"},
			"create-receipt-filter":                               {"Filter"},
			"create-receipt-rule":                                 {"Rule", "RuleSetName"},
			"create-receipt-rule-set":                             {"RuleSetName"},
			"create-template":                                     {"Template"},
			"delete-configuration-set":                            {"ConfigurationSetName"},
			"delete-configuration-set-event-destination":          {"ConfigurationSetName", "EventDestinationName"},
			"delete-configuration-set-tracking-options":           {"ConfigurationSetName"},
			"delete-custom-verification-email-template":           {"TemplateName"},
			"delete-identity":                                     {"Identity"},
			"delete-identity-policy":                              {"Identity", "PolicyName"},
			"delete-receipt-filter":                               {"FilterName"},
			"delete-receipt-rule":                                 {"RuleName", "RuleSetName"},
			"delete-receipt-rule-set":                             {"RuleSetName"},
			"delete-template":                                     {"TemplateName"},
			"delete-verified-email-address":                       {"EmailAddress"},
			"describe-active-receipt-rule-set":                    {},
			"describe-configuration-set":                          {"ConfigurationSetName"},
			"describe-receipt-rule":                               {"RuleName", "RuleSetName"},
			"describe-receipt-rule-set":                           {"RuleSetName"},
			"get-account-sending-enabled":                         {},
			"get-custom-verification-email-template":              {"TemplateName"},
			"get-identity-dkim-attributes":                        {"Identities"},
			"get-identity-mail-from-domain-attributes":            {"Identities"},
			"get-identity-notification-attributes":                {"Identities"},
			"get-identity-policies":                               {"Identity", "PolicyNames"},
			"get-identity-verification-attributes":                {"Identities"},
			"get-send-quota":                                      {},
			"get-send-statistics":                                 {},
			"get-template":                                        {"TemplateName"},
			"list-configuration-sets":                             {},
			"list-custom-verification-email-templates":            {},
			"list-identities":                                     {},
			"list-identity-policies":                              {"Identity"},
			"list-receipt-filters":                                {},
			"list-receipt-rule-sets":                              {},
			"list-templates":                                      {},
			"list-verified-email-addresses":                       {},
			"put-configuration-set-delivery-options":              {"ConfigurationSetName"},
			"put-identity-policy":                                 {"Identity", "Policy", "PolicyName"},
			"reorder-receipt-rule-set":                            {"RuleNames", "RuleSetName"},
			"send-bounce":                                         {"BounceSender", "BouncedRecipientInfoList", "OriginalMessageId"},
			"send-bulk-templated-email":                           {"DefaultTemplateData", "Destinations", "Source", "Template"},
			"send-custom-verification-email":                      {"EmailAddress", "TemplateName"},
			"send-email":                                          {"Destination", "Message", "Source"},
			"send-raw-email":                                      {"RawMessage"},
			"send-templated-email":                                {"Destination", "Source", "Template", "TemplateData"},
			"set-active-receipt-rule-set":                         {},
			"set-identity-dkim-enabled":                           {"DkimEnabled", "Identity"},
			"set-identity-feedback-forwarding-enabled":            {"ForwardingEnabled", "Identity"},
			"set-identity-headers-in-notifications-enabled":       {"Enabled", "Identity", "NotificationType"},
			"set-identity-mail-from-domain":                       {"Identity"},
			"set-identity-notification-topic":                     {"Identity", "NotificationType"},
			"set-receipt-rule-position":                           {"RuleName", "RuleSetName"},
			"test-render-template":                                {"TemplateData", "TemplateName"},
			"update-account-sending-enabled":                      {},
			"update-configuration-set-event-destination":          {"ConfigurationSetName", "EventDestination"},
			"update-configuration-set-reputation-metrics-enabled": {"ConfigurationSetName", "Enabled"},
			"update-configuration-set-sending-enabled":            {"ConfigurationSetName", "Enabled"},
			"update-configuration-set-tracking-options":           {"ConfigurationSetName", "TrackingOptions"},
			"update-custom-verification-email-template":           {"TemplateName"},
			"update-receipt-rule":                                 {"Rule", "RuleSetName"},
			"update-template":                                     {"Template"},
			"verify-domain-dkim":                                  {"Domain"},
			"verify-domain-identity":                              {"Domain"},
			"verify-email-address":                                {"EmailAddress"},
			"verify-email-identity":                               {"EmailAddress"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("ses", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
