package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/databrew/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-delete-recipe-version", "create-dataset", "create-profile-job", "create-project", "create-recipe", "create-recipe-job", "create-ruleset", "create-schedule", "delete-dataset", "delete-job", "delete-project", "delete-recipe-version", "delete-ruleset", "delete-schedule", "describe-dataset", "describe-job", "describe-job-run", "describe-project", "describe-recipe", "describe-ruleset", "describe-schedule", "list-datasets", "list-job-runs", "list-jobs", "list-projects", "list-recipe-versions", "list-recipes", "list-rulesets", "list-schedules", "list-tags-for-resource", "publish-recipe", "send-project-session-action", "start-job-run", "start-project-session", "stop-job-run", "tag-resource", "untag-resource", "update-dataset", "update-profile-job", "update-project", "update-recipe", "update-recipe-job", "update-ruleset", "update-schedule"},
		OperationSet: map[string]bool{"batch-delete-recipe-version": true, "create-dataset": true, "create-profile-job": true, "create-project": true, "create-recipe": true, "create-recipe-job": true, "create-ruleset": true, "create-schedule": true, "delete-dataset": true, "delete-job": true, "delete-project": true, "delete-recipe-version": true, "delete-ruleset": true, "delete-schedule": true, "describe-dataset": true, "describe-job": true, "describe-job-run": true, "describe-project": true, "describe-recipe": true, "describe-ruleset": true, "describe-schedule": true, "list-datasets": true, "list-job-runs": true, "list-jobs": true, "list-projects": true, "list-recipe-versions": true, "list-recipes": true, "list-rulesets": true, "list-schedules": true, "list-tags-for-resource": true, "publish-recipe": true, "send-project-session-action": true, "start-job-run": true, "start-project-session": true, "stop-job-run": true, "tag-resource": true, "untag-resource": true, "update-dataset": true, "update-profile-job": true, "update-project": true, "update-recipe": true, "update-recipe-job": true, "update-ruleset": true, "update-schedule": true},
		OperationInputs: map[string][]string{
			"batch-delete-recipe-version": {"Name", "RecipeVersions"},
			"create-dataset":              {"Format", "FormatOptions", "Input", "Name", "PathOptions", "Tags"},
			"create-profile-job":          {"Configuration", "DatasetName", "EncryptionKeyArn", "EncryptionMode", "JobSample", "LogSubscription", "MaxCapacity", "MaxRetries", "Name", "OutputLocation", "RoleArn", "Tags", "Timeout", "ValidationConfigurations"},
			"create-project":              {"DatasetName", "Name", "RecipeName", "RoleArn", "Sample", "Tags"},
			"create-recipe":               {"Description", "Name", "Steps", "Tags"},
			"create-recipe-job":           {"DataCatalogOutputs", "DatabaseOutputs", "DatasetName", "EncryptionKeyArn", "EncryptionMode", "LogSubscription", "MaxCapacity", "MaxRetries", "Name", "Outputs", "ProjectName", "RecipeReference", "RoleArn", "Tags", "Timeout"},
			"create-ruleset":              {"Description", "Name", "Rules", "Tags", "TargetArn"},
			"create-schedule":             {"CronExpression", "JobNames", "Name", "Tags"},
			"delete-dataset":              {"Name"},
			"delete-job":                  {"Name"},
			"delete-project":              {"Name"},
			"delete-recipe-version":       {"Name", "RecipeVersion"},
			"delete-ruleset":              {"Name"},
			"delete-schedule":             {"Name"},
			"describe-dataset":            {"Name"},
			"describe-job":                {"Name"},
			"describe-job-run":            {"Name", "RunId"},
			"describe-project":            {"Name"},
			"describe-recipe":             {"Name", "RecipeVersion"},
			"describe-ruleset":            {"Name"},
			"describe-schedule":           {"Name"},
			"list-datasets":               {"MaxResults", "NextToken"},
			"list-job-runs":               {"MaxResults", "Name", "NextToken"},
			"list-jobs":                   {"DatasetName", "MaxResults", "NextToken", "ProjectName"},
			"list-projects":               {"MaxResults", "NextToken"},
			"list-recipe-versions":        {"MaxResults", "Name", "NextToken"},
			"list-recipes":                {"MaxResults", "NextToken", "RecipeVersion"},
			"list-rulesets":               {"MaxResults", "NextToken", "TargetArn"},
			"list-schedules":              {"JobName", "MaxResults", "NextToken"},
			"list-tags-for-resource":      {"ResourceArn"},
			"publish-recipe":              {"Description", "Name"},
			"send-project-session-action": {"ClientSessionId", "Name", "Preview", "RecipeStep", "StepIndex", "ViewFrame"},
			"start-job-run":               {"Name"},
			"start-project-session":       {"AssumeControl", "Name"},
			"stop-job-run":                {"Name", "RunId"},
			"tag-resource":                {"ResourceArn", "Tags"},
			"untag-resource":              {"ResourceArn", "TagKeys"},
			"update-dataset":              {"Format", "FormatOptions", "Input", "Name", "PathOptions"},
			"update-profile-job":          {"Configuration", "EncryptionKeyArn", "EncryptionMode", "JobSample", "LogSubscription", "MaxCapacity", "MaxRetries", "Name", "OutputLocation", "RoleArn", "Timeout", "ValidationConfigurations"},
			"update-project":              {"Name", "RoleArn", "Sample"},
			"update-recipe":               {"Description", "Name", "Steps"},
			"update-recipe-job":           {"DataCatalogOutputs", "DatabaseOutputs", "EncryptionKeyArn", "EncryptionMode", "LogSubscription", "MaxCapacity", "MaxRetries", "Name", "Outputs", "RoleArn", "Timeout"},
			"update-ruleset":              {"Description", "Name", "Rules"},
			"update-schedule":             {"CronExpression", "JobNames", "Name"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-delete-recipe-version": {"Name": "*string", "RecipeVersions": "[]string"},
			"create-dataset":              {"Format": "types.InputFormat", "FormatOptions": "*types.FormatOptions", "Input": "*types.Input", "Name": "*string", "PathOptions": "*types.PathOptions", "Tags": "map[string]string"},
			"create-profile-job":          {"Configuration": "*types.ProfileConfiguration", "DatasetName": "*string", "EncryptionKeyArn": "*string", "EncryptionMode": "types.EncryptionMode", "JobSample": "*types.JobSample", "LogSubscription": "types.LogSubscription", "MaxCapacity": "int32", "MaxRetries": "int32", "Name": "*string", "OutputLocation": "*types.S3Location", "RoleArn": "*string", "Tags": "map[string]string", "Timeout": "int32", "ValidationConfigurations": "[]types.ValidationConfiguration"},
			"create-project":              {"DatasetName": "*string", "Name": "*string", "RecipeName": "*string", "RoleArn": "*string", "Sample": "*types.Sample", "Tags": "map[string]string"},
			"create-recipe":               {"Description": "*string", "Name": "*string", "Steps": "[]types.RecipeStep", "Tags": "map[string]string"},
			"create-recipe-job":           {"DataCatalogOutputs": "[]types.DataCatalogOutput", "DatabaseOutputs": "[]types.DatabaseOutput", "DatasetName": "*string", "EncryptionKeyArn": "*string", "EncryptionMode": "types.EncryptionMode", "LogSubscription": "types.LogSubscription", "MaxCapacity": "int32", "MaxRetries": "int32", "Name": "*string", "Outputs": "[]types.Output", "ProjectName": "*string", "RecipeReference": "*types.RecipeReference", "RoleArn": "*string", "Tags": "map[string]string", "Timeout": "int32"},
			"create-ruleset":              {"Description": "*string", "Name": "*string", "Rules": "[]types.Rule", "Tags": "map[string]string", "TargetArn": "*string"},
			"create-schedule":             {"CronExpression": "*string", "JobNames": "[]string", "Name": "*string", "Tags": "map[string]string"},
			"delete-dataset":              {"Name": "*string"},
			"delete-job":                  {"Name": "*string"},
			"delete-project":              {"Name": "*string"},
			"delete-recipe-version":       {"Name": "*string", "RecipeVersion": "*string"},
			"delete-ruleset":              {"Name": "*string"},
			"delete-schedule":             {"Name": "*string"},
			"describe-dataset":            {"Name": "*string"},
			"describe-job":                {"Name": "*string"},
			"describe-job-run":            {"Name": "*string", "RunId": "*string"},
			"describe-project":            {"Name": "*string"},
			"describe-recipe":             {"Name": "*string", "RecipeVersion": "*string"},
			"describe-ruleset":            {"Name": "*string"},
			"describe-schedule":           {"Name": "*string"},
			"list-datasets":               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-job-runs":               {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string"},
			"list-jobs":                   {"DatasetName": "*string", "MaxResults": "*int32", "NextToken": "*string", "ProjectName": "*string"},
			"list-projects":               {"MaxResults": "*int32", "NextToken": "*string"},
			"list-recipe-versions":        {"MaxResults": "*int32", "Name": "*string", "NextToken": "*string"},
			"list-recipes":                {"MaxResults": "*int32", "NextToken": "*string", "RecipeVersion": "*string"},
			"list-rulesets":               {"MaxResults": "*int32", "NextToken": "*string", "TargetArn": "*string"},
			"list-schedules":              {"JobName": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":      {"ResourceArn": "*string"},
			"publish-recipe":              {"Description": "*string", "Name": "*string"},
			"send-project-session-action": {"ClientSessionId": "*string", "Name": "*string", "Preview": "bool", "RecipeStep": "*types.RecipeStep", "StepIndex": "*int32", "ViewFrame": "*types.ViewFrame"},
			"start-job-run":               {"Name": "*string"},
			"start-project-session":       {"AssumeControl": "bool", "Name": "*string"},
			"stop-job-run":                {"Name": "*string", "RunId": "*string"},
			"tag-resource":                {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":              {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-dataset":              {"Format": "types.InputFormat", "FormatOptions": "*types.FormatOptions", "Input": "*types.Input", "Name": "*string", "PathOptions": "*types.PathOptions"},
			"update-profile-job":          {"Configuration": "*types.ProfileConfiguration", "EncryptionKeyArn": "*string", "EncryptionMode": "types.EncryptionMode", "JobSample": "*types.JobSample", "LogSubscription": "types.LogSubscription", "MaxCapacity": "int32", "MaxRetries": "int32", "Name": "*string", "OutputLocation": "*types.S3Location", "RoleArn": "*string", "Timeout": "int32", "ValidationConfigurations": "[]types.ValidationConfiguration"},
			"update-project":              {"Name": "*string", "RoleArn": "*string", "Sample": "*types.Sample"},
			"update-recipe":               {"Description": "*string", "Name": "*string", "Steps": "[]types.RecipeStep"},
			"update-recipe-job":           {"DataCatalogOutputs": "[]types.DataCatalogOutput", "DatabaseOutputs": "[]types.DatabaseOutput", "EncryptionKeyArn": "*string", "EncryptionMode": "types.EncryptionMode", "LogSubscription": "types.LogSubscription", "MaxCapacity": "int32", "MaxRetries": "int32", "Name": "*string", "Outputs": "[]types.Output", "RoleArn": "*string", "Timeout": "int32"},
			"update-ruleset":              {"Description": "*string", "Name": "*string", "Rules": "[]types.Rule"},
			"update-schedule":             {"CronExpression": "*string", "JobNames": "[]string", "Name": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-delete-recipe-version": {"Name", "RecipeVersions"},
			"create-dataset":              {"Input", "Name"},
			"create-profile-job":          {"DatasetName", "Name", "OutputLocation", "RoleArn"},
			"create-project":              {"DatasetName", "Name", "RecipeName", "RoleArn"},
			"create-recipe":               {"Name", "Steps"},
			"create-recipe-job":           {"Name", "RoleArn"},
			"create-ruleset":              {"Name", "Rules", "TargetArn"},
			"create-schedule":             {"CronExpression", "Name"},
			"delete-dataset":              {"Name"},
			"delete-job":                  {"Name"},
			"delete-project":              {"Name"},
			"delete-recipe-version":       {"Name", "RecipeVersion"},
			"delete-ruleset":              {"Name"},
			"delete-schedule":             {"Name"},
			"describe-dataset":            {"Name"},
			"describe-job":                {"Name"},
			"describe-job-run":            {"Name", "RunId"},
			"describe-project":            {"Name"},
			"describe-recipe":             {"Name"},
			"describe-ruleset":            {"Name"},
			"describe-schedule":           {"Name"},
			"list-datasets":               {},
			"list-job-runs":               {"Name"},
			"list-jobs":                   {},
			"list-projects":               {},
			"list-recipe-versions":        {"Name"},
			"list-recipes":                {},
			"list-rulesets":               {},
			"list-schedules":              {},
			"list-tags-for-resource":      {"ResourceArn"},
			"publish-recipe":              {"Name"},
			"send-project-session-action": {"Name"},
			"start-job-run":               {"Name"},
			"start-project-session":       {"Name"},
			"stop-job-run":                {"Name", "RunId"},
			"tag-resource":                {"ResourceArn", "Tags"},
			"untag-resource":              {"ResourceArn", "TagKeys"},
			"update-dataset":              {"Input", "Name"},
			"update-profile-job":          {"Name", "OutputLocation", "RoleArn"},
			"update-project":              {"Name", "RoleArn"},
			"update-recipe":               {"Name"},
			"update-recipe-job":           {"Name", "RoleArn"},
			"update-ruleset":              {"Name", "Rules"},
			"update-schedule":             {"CronExpression", "Name"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("databrew", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
