package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/observabilityadmin/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-centralization-rule-for-organization", "create-s3-table-integration", "create-telemetry-pipeline", "create-telemetry-rule", "create-telemetry-rule-for-organization", "delete-centralization-rule-for-organization", "delete-s3-table-integration", "delete-telemetry-pipeline", "delete-telemetry-rule", "delete-telemetry-rule-for-organization", "get-centralization-rule-for-organization", "get-s3-table-integration", "get-telemetry-enrichment-status", "get-telemetry-evaluation-status", "get-telemetry-evaluation-status-for-organization", "get-telemetry-pipeline", "get-telemetry-rule", "get-telemetry-rule-for-organization", "list-centralization-rules-for-organization", "list-resource-telemetry", "list-resource-telemetry-for-organization", "list-s3-table-integrations", "list-tags-for-resource", "list-telemetry-pipelines", "list-telemetry-rules", "list-telemetry-rules-for-organization", "start-telemetry-enrichment", "start-telemetry-evaluation", "start-telemetry-evaluation-for-organization", "stop-telemetry-enrichment", "stop-telemetry-evaluation", "stop-telemetry-evaluation-for-organization", "tag-resource", "test-telemetry-pipeline", "untag-resource", "update-centralization-rule-for-organization", "update-telemetry-pipeline", "update-telemetry-rule", "update-telemetry-rule-for-organization", "validate-telemetry-pipeline-configuration"},
		OperationSet: map[string]bool{"create-centralization-rule-for-organization": true, "create-s3-table-integration": true, "create-telemetry-pipeline": true, "create-telemetry-rule": true, "create-telemetry-rule-for-organization": true, "delete-centralization-rule-for-organization": true, "delete-s3-table-integration": true, "delete-telemetry-pipeline": true, "delete-telemetry-rule": true, "delete-telemetry-rule-for-organization": true, "get-centralization-rule-for-organization": true, "get-s3-table-integration": true, "get-telemetry-enrichment-status": true, "get-telemetry-evaluation-status": true, "get-telemetry-evaluation-status-for-organization": true, "get-telemetry-pipeline": true, "get-telemetry-rule": true, "get-telemetry-rule-for-organization": true, "list-centralization-rules-for-organization": true, "list-resource-telemetry": true, "list-resource-telemetry-for-organization": true, "list-s3-table-integrations": true, "list-tags-for-resource": true, "list-telemetry-pipelines": true, "list-telemetry-rules": true, "list-telemetry-rules-for-organization": true, "start-telemetry-enrichment": true, "start-telemetry-evaluation": true, "start-telemetry-evaluation-for-organization": true, "stop-telemetry-enrichment": true, "stop-telemetry-evaluation": true, "stop-telemetry-evaluation-for-organization": true, "tag-resource": true, "test-telemetry-pipeline": true, "untag-resource": true, "update-centralization-rule-for-organization": true, "update-telemetry-pipeline": true, "update-telemetry-rule": true, "update-telemetry-rule-for-organization": true, "validate-telemetry-pipeline-configuration": true},
		OperationInputs: map[string][]string{
			"create-centralization-rule-for-organization":      {"Rule", "RuleName", "Tags"},
			"create-s3-table-integration":                      {"Encryption", "RoleArn", "Tags"},
			"create-telemetry-pipeline":                        {"Configuration", "Name", "Tags"},
			"create-telemetry-rule":                            {"Rule", "RuleName", "Tags"},
			"create-telemetry-rule-for-organization":           {"Rule", "RuleName", "Tags"},
			"delete-centralization-rule-for-organization":      {"RuleIdentifier"},
			"delete-s3-table-integration":                      {"Arn"},
			"delete-telemetry-pipeline":                        {"PipelineIdentifier"},
			"delete-telemetry-rule":                            {"RuleIdentifier"},
			"delete-telemetry-rule-for-organization":           {"RuleIdentifier"},
			"get-centralization-rule-for-organization":         {"RuleIdentifier"},
			"get-s3-table-integration":                         {"Arn"},
			"get-telemetry-enrichment-status":                  {},
			"get-telemetry-evaluation-status":                  {},
			"get-telemetry-evaluation-status-for-organization": {},
			"get-telemetry-pipeline":                           {"PipelineIdentifier"},
			"get-telemetry-rule":                               {"RuleIdentifier"},
			"get-telemetry-rule-for-organization":              {"RuleIdentifier"},
			"list-centralization-rules-for-organization":       {"AllRegions", "MaxResults", "NextToken", "RuleNamePrefix"},
			"list-resource-telemetry":                          {"MaxResults", "NextToken", "ResourceIdentifierPrefix", "ResourceTags", "ResourceTypes", "TelemetryConfigurationState"},
			"list-resource-telemetry-for-organization":         {"AccountIdentifiers", "MaxResults", "NextToken", "ResourceIdentifierPrefix", "ResourceTags", "ResourceTypes", "TelemetryConfigurationState"},
			"list-s3-table-integrations":                       {"MaxResults", "NextToken"},
			"list-tags-for-resource":                           {"ResourceARN"},
			"list-telemetry-pipelines":                         {"MaxResults", "NextToken"},
			"list-telemetry-rules":                             {"MaxResults", "NextToken", "RuleNamePrefix"},
			"list-telemetry-rules-for-organization":            {"MaxResults", "NextToken", "RuleNamePrefix", "SourceAccountIds", "SourceOrganizationUnitIds"},
			"start-telemetry-enrichment":                       {},
			"start-telemetry-evaluation":                       {},
			"start-telemetry-evaluation-for-organization":      {},
			"stop-telemetry-enrichment":                        {},
			"stop-telemetry-evaluation":                        {},
			"stop-telemetry-evaluation-for-organization":       {},
			"tag-resource":                                     {"ResourceARN", "Tags"},
			"test-telemetry-pipeline":                          {"Configuration", "Records"},
			"untag-resource":                                   {"ResourceARN", "TagKeys"},
			"update-centralization-rule-for-organization":      {"Rule", "RuleIdentifier"},
			"update-telemetry-pipeline":                        {"Configuration", "PipelineIdentifier"},
			"update-telemetry-rule":                            {"Rule", "RuleIdentifier"},
			"update-telemetry-rule-for-organization":           {"Rule", "RuleIdentifier"},
			"validate-telemetry-pipeline-configuration":        {"Configuration"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-centralization-rule-for-organization":      {"Rule": "*types.CentralizationRule", "RuleName": "*string", "Tags": "map[string]string"},
			"create-s3-table-integration":                      {"Encryption": "*types.Encryption", "RoleArn": "*string", "Tags": "map[string]string"},
			"create-telemetry-pipeline":                        {"Configuration": "*types.TelemetryPipelineConfiguration", "Name": "*string", "Tags": "map[string]string"},
			"create-telemetry-rule":                            {"Rule": "*types.TelemetryRule", "RuleName": "*string", "Tags": "map[string]string"},
			"create-telemetry-rule-for-organization":           {"Rule": "*types.TelemetryRule", "RuleName": "*string", "Tags": "map[string]string"},
			"delete-centralization-rule-for-organization":      {"RuleIdentifier": "*string"},
			"delete-s3-table-integration":                      {"Arn": "*string"},
			"delete-telemetry-pipeline":                        {"PipelineIdentifier": "*string"},
			"delete-telemetry-rule":                            {"RuleIdentifier": "*string"},
			"delete-telemetry-rule-for-organization":           {"RuleIdentifier": "*string"},
			"get-centralization-rule-for-organization":         {"RuleIdentifier": "*string"},
			"get-s3-table-integration":                         {"Arn": "*string"},
			"get-telemetry-enrichment-status":                  {},
			"get-telemetry-evaluation-status":                  {},
			"get-telemetry-evaluation-status-for-organization": {},
			"get-telemetry-pipeline":                           {"PipelineIdentifier": "*string"},
			"get-telemetry-rule":                               {"RuleIdentifier": "*string"},
			"get-telemetry-rule-for-organization":              {"RuleIdentifier": "*string"},
			"list-centralization-rules-for-organization":       {"AllRegions": "*bool", "MaxResults": "*int32", "NextToken": "*string", "RuleNamePrefix": "*string"},
			"list-resource-telemetry":                          {"MaxResults": "*int32", "NextToken": "*string", "ResourceIdentifierPrefix": "*string", "ResourceTags": "map[string]string", "ResourceTypes": "[]types.ResourceType", "TelemetryConfigurationState": "map[string]types.TelemetryState"},
			"list-resource-telemetry-for-organization":         {"AccountIdentifiers": "[]string", "MaxResults": "*int32", "NextToken": "*string", "ResourceIdentifierPrefix": "*string", "ResourceTags": "map[string]string", "ResourceTypes": "[]types.ResourceType", "TelemetryConfigurationState": "map[string]types.TelemetryState"},
			"list-s3-table-integrations":                       {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                           {"ResourceARN": "*string"},
			"list-telemetry-pipelines":                         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-telemetry-rules":                             {"MaxResults": "*int32", "NextToken": "*string", "RuleNamePrefix": "*string"},
			"list-telemetry-rules-for-organization":            {"MaxResults": "*int32", "NextToken": "*string", "RuleNamePrefix": "*string", "SourceAccountIds": "[]string", "SourceOrganizationUnitIds": "[]string"},
			"start-telemetry-enrichment":                       {},
			"start-telemetry-evaluation":                       {},
			"start-telemetry-evaluation-for-organization":      {},
			"stop-telemetry-enrichment":                        {},
			"stop-telemetry-evaluation":                        {},
			"stop-telemetry-evaluation-for-organization":       {},
			"tag-resource":                                     {"ResourceARN": "*string", "Tags": "map[string]string"},
			"test-telemetry-pipeline":                          {"Configuration": "*types.TelemetryPipelineConfiguration", "Records": "[]types.Record"},
			"untag-resource":                                   {"ResourceARN": "*string", "TagKeys": "[]string"},
			"update-centralization-rule-for-organization":      {"Rule": "*types.CentralizationRule", "RuleIdentifier": "*string"},
			"update-telemetry-pipeline":                        {"Configuration": "*types.TelemetryPipelineConfiguration", "PipelineIdentifier": "*string"},
			"update-telemetry-rule":                            {"Rule": "*types.TelemetryRule", "RuleIdentifier": "*string"},
			"update-telemetry-rule-for-organization":           {"Rule": "*types.TelemetryRule", "RuleIdentifier": "*string"},
			"validate-telemetry-pipeline-configuration":        {"Configuration": "*types.TelemetryPipelineConfiguration"},
		},
		OperationInputRequired: map[string][]string{
			"create-centralization-rule-for-organization":      {"Rule", "RuleName"},
			"create-s3-table-integration":                      {"Encryption", "RoleArn"},
			"create-telemetry-pipeline":                        {"Configuration", "Name"},
			"create-telemetry-rule":                            {"Rule", "RuleName"},
			"create-telemetry-rule-for-organization":           {"Rule", "RuleName"},
			"delete-centralization-rule-for-organization":      {"RuleIdentifier"},
			"delete-s3-table-integration":                      {"Arn"},
			"delete-telemetry-pipeline":                        {"PipelineIdentifier"},
			"delete-telemetry-rule":                            {"RuleIdentifier"},
			"delete-telemetry-rule-for-organization":           {"RuleIdentifier"},
			"get-centralization-rule-for-organization":         {"RuleIdentifier"},
			"get-s3-table-integration":                         {"Arn"},
			"get-telemetry-enrichment-status":                  {},
			"get-telemetry-evaluation-status":                  {},
			"get-telemetry-evaluation-status-for-organization": {},
			"get-telemetry-pipeline":                           {"PipelineIdentifier"},
			"get-telemetry-rule":                               {"RuleIdentifier"},
			"get-telemetry-rule-for-organization":              {"RuleIdentifier"},
			"list-centralization-rules-for-organization":       {},
			"list-resource-telemetry":                          {},
			"list-resource-telemetry-for-organization":         {},
			"list-s3-table-integrations":                       {},
			"list-tags-for-resource":                           {"ResourceARN"},
			"list-telemetry-pipelines":                         {},
			"list-telemetry-rules":                             {},
			"list-telemetry-rules-for-organization":            {},
			"start-telemetry-enrichment":                       {},
			"start-telemetry-evaluation":                       {},
			"start-telemetry-evaluation-for-organization":      {},
			"stop-telemetry-enrichment":                        {},
			"stop-telemetry-evaluation":                        {},
			"stop-telemetry-evaluation-for-organization":       {},
			"tag-resource":                                     {"ResourceARN", "Tags"},
			"test-telemetry-pipeline":                          {"Configuration", "Records"},
			"untag-resource":                                   {"ResourceARN", "TagKeys"},
			"update-centralization-rule-for-organization":      {"Rule", "RuleIdentifier"},
			"update-telemetry-pipeline":                        {"Configuration", "PipelineIdentifier"},
			"update-telemetry-rule":                            {"Rule", "RuleIdentifier"},
			"update-telemetry-rule-for-organization":           {"Rule", "RuleIdentifier"},
			"validate-telemetry-pipeline-configuration":        {"Configuration"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("observabilityadmin", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
