package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/verifiedpermissions/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"batch-get-policy", "batch-is-authorized", "batch-is-authorized-with-token", "create-identity-source", "create-policy", "create-policy-store", "create-policy-template", "delete-identity-source", "delete-policy", "delete-policy-store", "delete-policy-template", "get-identity-source", "get-policy", "get-policy-store", "get-policy-template", "get-schema", "is-authorized", "is-authorized-with-token", "list-identity-sources", "list-policies", "list-policy-stores", "list-policy-templates", "list-tags-for-resource", "put-schema", "tag-resource", "untag-resource", "update-identity-source", "update-policy", "update-policy-store", "update-policy-template"},
		OperationSet: map[string]bool{"batch-get-policy": true, "batch-is-authorized": true, "batch-is-authorized-with-token": true, "create-identity-source": true, "create-policy": true, "create-policy-store": true, "create-policy-template": true, "delete-identity-source": true, "delete-policy": true, "delete-policy-store": true, "delete-policy-template": true, "get-identity-source": true, "get-policy": true, "get-policy-store": true, "get-policy-template": true, "get-schema": true, "is-authorized": true, "is-authorized-with-token": true, "list-identity-sources": true, "list-policies": true, "list-policy-stores": true, "list-policy-templates": true, "list-tags-for-resource": true, "put-schema": true, "tag-resource": true, "untag-resource": true, "update-identity-source": true, "update-policy": true, "update-policy-store": true, "update-policy-template": true},
		OperationInputs: map[string][]string{
			"batch-get-policy":               {"Requests"},
			"batch-is-authorized":            {"Entities", "PolicyStoreId", "Requests"},
			"batch-is-authorized-with-token": {"AccessToken", "Entities", "IdentityToken", "PolicyStoreId", "Requests"},
			"create-identity-source":         {"ClientToken", "Configuration", "PolicyStoreId", "PrincipalEntityType"},
			"create-policy":                  {"ClientToken", "Definition", "PolicyStoreId"},
			"create-policy-store":            {"ClientToken", "DeletionProtection", "Description", "EncryptionSettings", "Tags", "ValidationSettings"},
			"create-policy-template":         {"ClientToken", "Description", "PolicyStoreId", "Statement"},
			"delete-identity-source":         {"IdentitySourceId", "PolicyStoreId"},
			"delete-policy":                  {"PolicyId", "PolicyStoreId"},
			"delete-policy-store":            {"PolicyStoreId"},
			"delete-policy-template":         {"PolicyStoreId", "PolicyTemplateId"},
			"get-identity-source":            {"IdentitySourceId", "PolicyStoreId"},
			"get-policy":                     {"PolicyId", "PolicyStoreId"},
			"get-policy-store":               {"PolicyStoreId", "Tags"},
			"get-policy-template":            {"PolicyStoreId", "PolicyTemplateId"},
			"get-schema":                     {"PolicyStoreId"},
			"is-authorized":                  {"Action", "Context", "Entities", "PolicyStoreId", "Principal", "Resource"},
			"is-authorized-with-token":       {"AccessToken", "Action", "Context", "Entities", "IdentityToken", "PolicyStoreId", "Resource"},
			"list-identity-sources":          {"Filters", "MaxResults", "NextToken", "PolicyStoreId"},
			"list-policies":                  {"Filter", "MaxResults", "NextToken", "PolicyStoreId"},
			"list-policy-stores":             {"MaxResults", "NextToken"},
			"list-policy-templates":          {"MaxResults", "NextToken", "PolicyStoreId"},
			"list-tags-for-resource":         {"ResourceArn"},
			"put-schema":                     {"Definition", "PolicyStoreId"},
			"tag-resource":                   {"ResourceArn", "Tags"},
			"untag-resource":                 {"ResourceArn", "TagKeys"},
			"update-identity-source":         {"IdentitySourceId", "PolicyStoreId", "PrincipalEntityType", "UpdateConfiguration"},
			"update-policy":                  {"Definition", "PolicyId", "PolicyStoreId"},
			"update-policy-store":            {"DeletionProtection", "Description", "PolicyStoreId", "ValidationSettings"},
			"update-policy-template":         {"Description", "PolicyStoreId", "PolicyTemplateId", "Statement"},
		},
		OperationInputTypes: map[string]map[string]string{
			"batch-get-policy":               {"Requests": "[]types.BatchGetPolicyInputItem"},
			"batch-is-authorized":            {"Entities": "types.EntitiesDefinition", "PolicyStoreId": "*string", "Requests": "[]types.BatchIsAuthorizedInputItem"},
			"batch-is-authorized-with-token": {"AccessToken": "*string", "Entities": "types.EntitiesDefinition", "IdentityToken": "*string", "PolicyStoreId": "*string", "Requests": "[]types.BatchIsAuthorizedWithTokenInputItem"},
			"create-identity-source":         {"ClientToken": "*string", "Configuration": "types.Configuration", "PolicyStoreId": "*string", "PrincipalEntityType": "*string"},
			"create-policy":                  {"ClientToken": "*string", "Definition": "types.PolicyDefinition", "PolicyStoreId": "*string"},
			"create-policy-store":            {"ClientToken": "*string", "DeletionProtection": "types.DeletionProtection", "Description": "*string", "EncryptionSettings": "types.EncryptionSettings", "Tags": "map[string]string", "ValidationSettings": "*types.ValidationSettings"},
			"create-policy-template":         {"ClientToken": "*string", "Description": "*string", "PolicyStoreId": "*string", "Statement": "*string"},
			"delete-identity-source":         {"IdentitySourceId": "*string", "PolicyStoreId": "*string"},
			"delete-policy":                  {"PolicyId": "*string", "PolicyStoreId": "*string"},
			"delete-policy-store":            {"PolicyStoreId": "*string"},
			"delete-policy-template":         {"PolicyStoreId": "*string", "PolicyTemplateId": "*string"},
			"get-identity-source":            {"IdentitySourceId": "*string", "PolicyStoreId": "*string"},
			"get-policy":                     {"PolicyId": "*string", "PolicyStoreId": "*string"},
			"get-policy-store":               {"PolicyStoreId": "*string", "Tags": "bool"},
			"get-policy-template":            {"PolicyStoreId": "*string", "PolicyTemplateId": "*string"},
			"get-schema":                     {"PolicyStoreId": "*string"},
			"is-authorized":                  {"Action": "*types.ActionIdentifier", "Context": "types.ContextDefinition", "Entities": "types.EntitiesDefinition", "PolicyStoreId": "*string", "Principal": "*types.EntityIdentifier", "Resource": "*types.EntityIdentifier"},
			"is-authorized-with-token":       {"AccessToken": "*string", "Action": "*types.ActionIdentifier", "Context": "types.ContextDefinition", "Entities": "types.EntitiesDefinition", "IdentityToken": "*string", "PolicyStoreId": "*string", "Resource": "*types.EntityIdentifier"},
			"list-identity-sources":          {"Filters": "[]types.IdentitySourceFilter", "MaxResults": "*int32", "NextToken": "*string", "PolicyStoreId": "*string"},
			"list-policies":                  {"Filter": "*types.PolicyFilter", "MaxResults": "*int32", "NextToken": "*string", "PolicyStoreId": "*string"},
			"list-policy-stores":             {"MaxResults": "*int32", "NextToken": "*string"},
			"list-policy-templates":          {"MaxResults": "*int32", "NextToken": "*string", "PolicyStoreId": "*string"},
			"list-tags-for-resource":         {"ResourceArn": "*string"},
			"put-schema":                     {"Definition": "types.SchemaDefinition", "PolicyStoreId": "*string"},
			"tag-resource":                   {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                 {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-identity-source":         {"IdentitySourceId": "*string", "PolicyStoreId": "*string", "PrincipalEntityType": "*string", "UpdateConfiguration": "types.UpdateConfiguration"},
			"update-policy":                  {"Definition": "types.UpdatePolicyDefinition", "PolicyId": "*string", "PolicyStoreId": "*string"},
			"update-policy-store":            {"DeletionProtection": "types.DeletionProtection", "Description": "*string", "PolicyStoreId": "*string", "ValidationSettings": "*types.ValidationSettings"},
			"update-policy-template":         {"Description": "*string", "PolicyStoreId": "*string", "PolicyTemplateId": "*string", "Statement": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"batch-get-policy":               {"Requests"},
			"batch-is-authorized":            {"PolicyStoreId", "Requests"},
			"batch-is-authorized-with-token": {"PolicyStoreId", "Requests"},
			"create-identity-source":         {"Configuration", "PolicyStoreId"},
			"create-policy":                  {"Definition", "PolicyStoreId"},
			"create-policy-store":            {"ValidationSettings"},
			"create-policy-template":         {"PolicyStoreId", "Statement"},
			"delete-identity-source":         {"IdentitySourceId", "PolicyStoreId"},
			"delete-policy":                  {"PolicyId", "PolicyStoreId"},
			"delete-policy-store":            {"PolicyStoreId"},
			"delete-policy-template":         {"PolicyStoreId", "PolicyTemplateId"},
			"get-identity-source":            {"IdentitySourceId", "PolicyStoreId"},
			"get-policy":                     {"PolicyId", "PolicyStoreId"},
			"get-policy-store":               {"PolicyStoreId"},
			"get-policy-template":            {"PolicyStoreId", "PolicyTemplateId"},
			"get-schema":                     {"PolicyStoreId"},
			"is-authorized":                  {"PolicyStoreId"},
			"is-authorized-with-token":       {"PolicyStoreId"},
			"list-identity-sources":          {"PolicyStoreId"},
			"list-policies":                  {"PolicyStoreId"},
			"list-policy-stores":             {},
			"list-policy-templates":          {"PolicyStoreId"},
			"list-tags-for-resource":         {"ResourceArn"},
			"put-schema":                     {"Definition", "PolicyStoreId"},
			"tag-resource":                   {"ResourceArn", "Tags"},
			"untag-resource":                 {"ResourceArn", "TagKeys"},
			"update-identity-source":         {"IdentitySourceId", "PolicyStoreId", "UpdateConfiguration"},
			"update-policy":                  {"PolicyId", "PolicyStoreId"},
			"update-policy-store":            {"PolicyStoreId", "ValidationSettings"},
			"update-policy-template":         {"PolicyStoreId", "PolicyTemplateId", "Statement"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("verifiedpermissions", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
