package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/drs/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-source-network-stack", "create-extended-source-server", "create-launch-configuration-template", "create-replication-configuration-template", "create-source-network", "delete-job", "delete-launch-action", "delete-launch-configuration-template", "delete-recovery-instance", "delete-replication-configuration-template", "delete-source-network", "delete-source-server", "describe-job-log-items", "describe-jobs", "describe-launch-configuration-templates", "describe-recovery-instances", "describe-recovery-snapshots", "describe-replication-configuration-templates", "describe-source-networks", "describe-source-servers", "disconnect-recovery-instance", "disconnect-source-server", "export-source-network-cfn-template", "get-failback-replication-configuration", "get-launch-configuration", "get-replication-configuration", "initialize-service", "list-extensible-source-servers", "list-launch-actions", "list-staging-accounts", "list-tags-for-resource", "put-launch-action", "retry-data-replication", "reverse-replication", "start-failback-launch", "start-recovery", "start-replication", "start-source-network-recovery", "start-source-network-replication", "stop-failback", "stop-replication", "stop-source-network-replication", "tag-resource", "terminate-recovery-instances", "untag-resource", "update-failback-replication-configuration", "update-launch-configuration", "update-launch-configuration-template", "update-replication-configuration", "update-replication-configuration-template"},
		OperationSet: map[string]bool{"associate-source-network-stack": true, "create-extended-source-server": true, "create-launch-configuration-template": true, "create-replication-configuration-template": true, "create-source-network": true, "delete-job": true, "delete-launch-action": true, "delete-launch-configuration-template": true, "delete-recovery-instance": true, "delete-replication-configuration-template": true, "delete-source-network": true, "delete-source-server": true, "describe-job-log-items": true, "describe-jobs": true, "describe-launch-configuration-templates": true, "describe-recovery-instances": true, "describe-recovery-snapshots": true, "describe-replication-configuration-templates": true, "describe-source-networks": true, "describe-source-servers": true, "disconnect-recovery-instance": true, "disconnect-source-server": true, "export-source-network-cfn-template": true, "get-failback-replication-configuration": true, "get-launch-configuration": true, "get-replication-configuration": true, "initialize-service": true, "list-extensible-source-servers": true, "list-launch-actions": true, "list-staging-accounts": true, "list-tags-for-resource": true, "put-launch-action": true, "retry-data-replication": true, "reverse-replication": true, "start-failback-launch": true, "start-recovery": true, "start-replication": true, "start-source-network-recovery": true, "start-source-network-replication": true, "stop-failback": true, "stop-replication": true, "stop-source-network-replication": true, "tag-resource": true, "terminate-recovery-instances": true, "untag-resource": true, "update-failback-replication-configuration": true, "update-launch-configuration": true, "update-launch-configuration-template": true, "update-replication-configuration": true, "update-replication-configuration-template": true},
		OperationInputs: map[string][]string{
			"associate-source-network-stack":               {"CfnStackName", "SourceNetworkID"},
			"create-extended-source-server":                {"SourceServerArn", "Tags"},
			"create-launch-configuration-template":         {"CopyPrivateIp", "CopyTags", "ExportBucketArn", "LaunchDisposition", "LaunchIntoSourceInstance", "Licensing", "PostLaunchEnabled", "Tags", "TargetInstanceTypeRightSizingMethod"},
			"create-replication-configuration-template":    {"AssociateDefaultSecurityGroup", "AutoReplicateNewDisks", "BandwidthThrottling", "CreatePublicIP", "DataPlaneRouting", "DefaultLargeStagingDiskType", "EbsEncryption", "EbsEncryptionKeyArn", "PitPolicy", "ReplicationServerInstanceType", "ReplicationServersSecurityGroupsIDs", "StagingAreaSubnetId", "StagingAreaTags", "Tags", "UseDedicatedReplicationServer"},
			"create-source-network":                        {"OriginAccountID", "OriginRegion", "Tags", "VpcID"},
			"delete-job":                                   {"JobID"},
			"delete-launch-action":                         {"ActionId", "ResourceId"},
			"delete-launch-configuration-template":         {"LaunchConfigurationTemplateID"},
			"delete-recovery-instance":                     {"RecoveryInstanceID"},
			"delete-replication-configuration-template":    {"ReplicationConfigurationTemplateID"},
			"delete-source-network":                        {"SourceNetworkID"},
			"delete-source-server":                         {"SourceServerID"},
			"describe-job-log-items":                       {"JobID", "MaxResults", "NextToken"},
			"describe-jobs":                                {"Filters", "MaxResults", "NextToken"},
			"describe-launch-configuration-templates":      {"LaunchConfigurationTemplateIDs", "MaxResults", "NextToken"},
			"describe-recovery-instances":                  {"Filters", "MaxResults", "NextToken"},
			"describe-recovery-snapshots":                  {"Filters", "MaxResults", "NextToken", "Order", "SourceServerID"},
			"describe-replication-configuration-templates": {"MaxResults", "NextToken", "ReplicationConfigurationTemplateIDs"},
			"describe-source-networks":                     {"Filters", "MaxResults", "NextToken"},
			"describe-source-servers":                      {"Filters", "MaxResults", "NextToken"},
			"disconnect-recovery-instance":                 {"RecoveryInstanceID"},
			"disconnect-source-server":                     {"SourceServerID"},
			"export-source-network-cfn-template":           {"SourceNetworkID"},
			"get-failback-replication-configuration":       {"RecoveryInstanceID"},
			"get-launch-configuration":                     {"SourceServerID"},
			"get-replication-configuration":                {"SourceServerID"},
			"initialize-service":                           {},
			"list-extensible-source-servers":               {"MaxResults", "NextToken", "StagingAccountID"},
			"list-launch-actions":                          {"Filters", "MaxResults", "NextToken", "ResourceId"},
			"list-staging-accounts":                        {"MaxResults", "NextToken"},
			"list-tags-for-resource":                       {"ResourceArn"},
			"put-launch-action":                            {"ActionCode", "ActionId", "ActionVersion", "Active", "Category", "Description", "Name", "Optional", "Order", "Parameters", "ResourceId"},
			"retry-data-replication":                       {"SourceServerID"},
			"reverse-replication":                          {"RecoveryInstanceID"},
			"start-failback-launch":                        {"RecoveryInstanceIDs", "Tags"},
			"start-recovery":                               {"IsDrill", "SourceServers", "Tags"},
			"start-replication":                            {"SourceServerID"},
			"start-source-network-recovery":                {"DeployAsNew", "SourceNetworks", "Tags"},
			"start-source-network-replication":             {"SourceNetworkID"},
			"stop-failback":                                {"RecoveryInstanceID"},
			"stop-replication":                             {"SourceServerID"},
			"stop-source-network-replication":              {"SourceNetworkID"},
			"tag-resource":                                 {"ResourceArn", "Tags"},
			"terminate-recovery-instances":                 {"RecoveryInstanceIDs"},
			"untag-resource":                               {"ResourceArn", "TagKeys"},
			"update-failback-replication-configuration":    {"BandwidthThrottling", "Name", "RecoveryInstanceID", "UsePrivateIP"},
			"update-launch-configuration":                  {"CopyPrivateIp", "CopyTags", "LaunchDisposition", "LaunchIntoInstanceProperties", "Licensing", "Name", "PostLaunchEnabled", "SourceServerID", "TargetInstanceTypeRightSizingMethod"},
			"update-launch-configuration-template":         {"CopyPrivateIp", "CopyTags", "ExportBucketArn", "LaunchConfigurationTemplateID", "LaunchDisposition", "LaunchIntoSourceInstance", "Licensing", "PostLaunchEnabled", "TargetInstanceTypeRightSizingMethod"},
			"update-replication-configuration":             {"AssociateDefaultSecurityGroup", "AutoReplicateNewDisks", "BandwidthThrottling", "CreatePublicIP", "DataPlaneRouting", "DefaultLargeStagingDiskType", "EbsEncryption", "EbsEncryptionKeyArn", "Name", "PitPolicy", "ReplicatedDisks", "ReplicationServerInstanceType", "ReplicationServersSecurityGroupsIDs", "SourceServerID", "StagingAreaSubnetId", "StagingAreaTags", "UseDedicatedReplicationServer"},
			"update-replication-configuration-template":    {"Arn", "AssociateDefaultSecurityGroup", "AutoReplicateNewDisks", "BandwidthThrottling", "CreatePublicIP", "DataPlaneRouting", "DefaultLargeStagingDiskType", "EbsEncryption", "EbsEncryptionKeyArn", "PitPolicy", "ReplicationConfigurationTemplateID", "ReplicationServerInstanceType", "ReplicationServersSecurityGroupsIDs", "StagingAreaSubnetId", "StagingAreaTags", "UseDedicatedReplicationServer"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-source-network-stack":               {"CfnStackName": "*string", "SourceNetworkID": "*string"},
			"create-extended-source-server":                {"SourceServerArn": "*string", "Tags": "map[string]string"},
			"create-launch-configuration-template":         {"CopyPrivateIp": "*bool", "CopyTags": "*bool", "ExportBucketArn": "*string", "LaunchDisposition": "types.LaunchDisposition", "LaunchIntoSourceInstance": "*bool", "Licensing": "*types.Licensing", "PostLaunchEnabled": "*bool", "Tags": "map[string]string", "TargetInstanceTypeRightSizingMethod": "types.TargetInstanceTypeRightSizingMethod"},
			"create-replication-configuration-template":    {"AssociateDefaultSecurityGroup": "*bool", "AutoReplicateNewDisks": "*bool", "BandwidthThrottling": "int64", "CreatePublicIP": "*bool", "DataPlaneRouting": "types.ReplicationConfigurationDataPlaneRouting", "DefaultLargeStagingDiskType": "types.ReplicationConfigurationDefaultLargeStagingDiskType", "EbsEncryption": "types.ReplicationConfigurationEbsEncryption", "EbsEncryptionKeyArn": "*string", "PitPolicy": "[]types.PITPolicyRule", "ReplicationServerInstanceType": "*string", "ReplicationServersSecurityGroupsIDs": "[]string", "StagingAreaSubnetId": "*string", "StagingAreaTags": "map[string]string", "Tags": "map[string]string", "UseDedicatedReplicationServer": "*bool"},
			"create-source-network":                        {"OriginAccountID": "*string", "OriginRegion": "*string", "Tags": "map[string]string", "VpcID": "*string"},
			"delete-job":                                   {"JobID": "*string"},
			"delete-launch-action":                         {"ActionId": "*string", "ResourceId": "*string"},
			"delete-launch-configuration-template":         {"LaunchConfigurationTemplateID": "*string"},
			"delete-recovery-instance":                     {"RecoveryInstanceID": "*string"},
			"delete-replication-configuration-template":    {"ReplicationConfigurationTemplateID": "*string"},
			"delete-source-network":                        {"SourceNetworkID": "*string"},
			"delete-source-server":                         {"SourceServerID": "*string"},
			"describe-job-log-items":                       {"JobID": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-jobs":                                {"Filters": "*types.DescribeJobsRequestFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-launch-configuration-templates":      {"LaunchConfigurationTemplateIDs": "[]string", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-recovery-instances":                  {"Filters": "*types.DescribeRecoveryInstancesRequestFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-recovery-snapshots":                  {"Filters": "*types.DescribeRecoverySnapshotsRequestFilters", "MaxResults": "*int32", "NextToken": "*string", "Order": "types.RecoverySnapshotsOrder", "SourceServerID": "*string"},
			"describe-replication-configuration-templates": {"MaxResults": "*int32", "NextToken": "*string", "ReplicationConfigurationTemplateIDs": "[]string"},
			"describe-source-networks":                     {"Filters": "*types.DescribeSourceNetworksRequestFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"describe-source-servers":                      {"Filters": "*types.DescribeSourceServersRequestFilters", "MaxResults": "*int32", "NextToken": "*string"},
			"disconnect-recovery-instance":                 {"RecoveryInstanceID": "*string"},
			"disconnect-source-server":                     {"SourceServerID": "*string"},
			"export-source-network-cfn-template":           {"SourceNetworkID": "*string"},
			"get-failback-replication-configuration":       {"RecoveryInstanceID": "*string"},
			"get-launch-configuration":                     {"SourceServerID": "*string"},
			"get-replication-configuration":                {"SourceServerID": "*string"},
			"initialize-service":                           {},
			"list-extensible-source-servers":               {"MaxResults": "*int32", "NextToken": "*string", "StagingAccountID": "*string"},
			"list-launch-actions":                          {"Filters": "*types.LaunchActionsRequestFilters", "MaxResults": "*int32", "NextToken": "*string", "ResourceId": "*string"},
			"list-staging-accounts":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-resource":                       {"ResourceArn": "*string"},
			"put-launch-action":                            {"ActionCode": "*string", "ActionId": "*string", "ActionVersion": "*string", "Active": "*bool", "Category": "types.LaunchActionCategory", "Description": "*string", "Name": "*string", "Optional": "*bool", "Order": "*int32", "Parameters": "map[string]types.LaunchActionParameter", "ResourceId": "*string"},
			"retry-data-replication":                       {"SourceServerID": "*string"},
			"reverse-replication":                          {"RecoveryInstanceID": "*string"},
			"start-failback-launch":                        {"RecoveryInstanceIDs": "[]string", "Tags": "map[string]string"},
			"start-recovery":                               {"IsDrill": "*bool", "SourceServers": "[]types.StartRecoveryRequestSourceServer", "Tags": "map[string]string"},
			"start-replication":                            {"SourceServerID": "*string"},
			"start-source-network-recovery":                {"DeployAsNew": "*bool", "SourceNetworks": "[]types.StartSourceNetworkRecoveryRequestNetworkEntry", "Tags": "map[string]string"},
			"start-source-network-replication":             {"SourceNetworkID": "*string"},
			"stop-failback":                                {"RecoveryInstanceID": "*string"},
			"stop-replication":                             {"SourceServerID": "*string"},
			"stop-source-network-replication":              {"SourceNetworkID": "*string"},
			"tag-resource":                                 {"ResourceArn": "*string", "Tags": "map[string]string"},
			"terminate-recovery-instances":                 {"RecoveryInstanceIDs": "[]string"},
			"untag-resource":                               {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-failback-replication-configuration":    {"BandwidthThrottling": "int64", "Name": "*string", "RecoveryInstanceID": "*string", "UsePrivateIP": "*bool"},
			"update-launch-configuration":                  {"CopyPrivateIp": "*bool", "CopyTags": "*bool", "LaunchDisposition": "types.LaunchDisposition", "LaunchIntoInstanceProperties": "*types.LaunchIntoInstanceProperties", "Licensing": "*types.Licensing", "Name": "*string", "PostLaunchEnabled": "*bool", "SourceServerID": "*string", "TargetInstanceTypeRightSizingMethod": "types.TargetInstanceTypeRightSizingMethod"},
			"update-launch-configuration-template":         {"CopyPrivateIp": "*bool", "CopyTags": "*bool", "ExportBucketArn": "*string", "LaunchConfigurationTemplateID": "*string", "LaunchDisposition": "types.LaunchDisposition", "LaunchIntoSourceInstance": "*bool", "Licensing": "*types.Licensing", "PostLaunchEnabled": "*bool", "TargetInstanceTypeRightSizingMethod": "types.TargetInstanceTypeRightSizingMethod"},
			"update-replication-configuration":             {"AssociateDefaultSecurityGroup": "*bool", "AutoReplicateNewDisks": "*bool", "BandwidthThrottling": "int64", "CreatePublicIP": "*bool", "DataPlaneRouting": "types.ReplicationConfigurationDataPlaneRouting", "DefaultLargeStagingDiskType": "types.ReplicationConfigurationDefaultLargeStagingDiskType", "EbsEncryption": "types.ReplicationConfigurationEbsEncryption", "EbsEncryptionKeyArn": "*string", "Name": "*string", "PitPolicy": "[]types.PITPolicyRule", "ReplicatedDisks": "[]types.ReplicationConfigurationReplicatedDisk", "ReplicationServerInstanceType": "*string", "ReplicationServersSecurityGroupsIDs": "[]string", "SourceServerID": "*string", "StagingAreaSubnetId": "*string", "StagingAreaTags": "map[string]string", "UseDedicatedReplicationServer": "*bool"},
			"update-replication-configuration-template":    {"Arn": "*string", "AssociateDefaultSecurityGroup": "*bool", "AutoReplicateNewDisks": "*bool", "BandwidthThrottling": "int64", "CreatePublicIP": "*bool", "DataPlaneRouting": "types.ReplicationConfigurationDataPlaneRouting", "DefaultLargeStagingDiskType": "types.ReplicationConfigurationDefaultLargeStagingDiskType", "EbsEncryption": "types.ReplicationConfigurationEbsEncryption", "EbsEncryptionKeyArn": "*string", "PitPolicy": "[]types.PITPolicyRule", "ReplicationConfigurationTemplateID": "*string", "ReplicationServerInstanceType": "*string", "ReplicationServersSecurityGroupsIDs": "[]string", "StagingAreaSubnetId": "*string", "StagingAreaTags": "map[string]string", "UseDedicatedReplicationServer": "*bool"},
		},
		OperationInputRequired: map[string][]string{
			"associate-source-network-stack":               {"CfnStackName", "SourceNetworkID"},
			"create-extended-source-server":                {"SourceServerArn"},
			"create-launch-configuration-template":         {},
			"create-replication-configuration-template":    {"AssociateDefaultSecurityGroup", "BandwidthThrottling", "CreatePublicIP", "DataPlaneRouting", "DefaultLargeStagingDiskType", "EbsEncryption", "PitPolicy", "ReplicationServerInstanceType", "ReplicationServersSecurityGroupsIDs", "StagingAreaSubnetId", "StagingAreaTags", "UseDedicatedReplicationServer"},
			"create-source-network":                        {"OriginAccountID", "OriginRegion", "VpcID"},
			"delete-job":                                   {"JobID"},
			"delete-launch-action":                         {"ActionId", "ResourceId"},
			"delete-launch-configuration-template":         {"LaunchConfigurationTemplateID"},
			"delete-recovery-instance":                     {"RecoveryInstanceID"},
			"delete-replication-configuration-template":    {"ReplicationConfigurationTemplateID"},
			"delete-source-network":                        {"SourceNetworkID"},
			"delete-source-server":                         {"SourceServerID"},
			"describe-job-log-items":                       {"JobID"},
			"describe-jobs":                                {},
			"describe-launch-configuration-templates":      {},
			"describe-recovery-instances":                  {},
			"describe-recovery-snapshots":                  {"SourceServerID"},
			"describe-replication-configuration-templates": {},
			"describe-source-networks":                     {},
			"describe-source-servers":                      {},
			"disconnect-recovery-instance":                 {"RecoveryInstanceID"},
			"disconnect-source-server":                     {"SourceServerID"},
			"export-source-network-cfn-template":           {"SourceNetworkID"},
			"get-failback-replication-configuration":       {"RecoveryInstanceID"},
			"get-launch-configuration":                     {"SourceServerID"},
			"get-replication-configuration":                {"SourceServerID"},
			"initialize-service":                           {},
			"list-extensible-source-servers":               {"StagingAccountID"},
			"list-launch-actions":                          {"ResourceId"},
			"list-staging-accounts":                        {},
			"list-tags-for-resource":                       {"ResourceArn"},
			"put-launch-action":                            {"ActionCode", "ActionId", "ActionVersion", "Active", "Category", "Description", "Name", "Optional", "Order", "ResourceId"},
			"retry-data-replication":                       {"SourceServerID"},
			"reverse-replication":                          {"RecoveryInstanceID"},
			"start-failback-launch":                        {"RecoveryInstanceIDs"},
			"start-recovery":                               {"SourceServers"},
			"start-replication":                            {"SourceServerID"},
			"start-source-network-recovery":                {"SourceNetworks"},
			"start-source-network-replication":             {"SourceNetworkID"},
			"stop-failback":                                {"RecoveryInstanceID"},
			"stop-replication":                             {"SourceServerID"},
			"stop-source-network-replication":              {"SourceNetworkID"},
			"tag-resource":                                 {"ResourceArn", "Tags"},
			"terminate-recovery-instances":                 {"RecoveryInstanceIDs"},
			"untag-resource":                               {"ResourceArn", "TagKeys"},
			"update-failback-replication-configuration":    {"RecoveryInstanceID"},
			"update-launch-configuration":                  {"SourceServerID"},
			"update-launch-configuration-template":         {"LaunchConfigurationTemplateID"},
			"update-replication-configuration":             {"SourceServerID"},
			"update-replication-configuration-template":    {"ReplicationConfigurationTemplateID"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("drs", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
