package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/apigateway/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-api-key", "create-authorizer", "create-base-path-mapping", "create-deployment", "create-documentation-part", "create-documentation-version", "create-domain-name", "create-domain-name-access-association", "create-model", "create-request-validator", "create-resource", "create-rest-api", "create-stage", "create-usage-plan", "create-usage-plan-key", "create-vpc-link", "delete-api-key", "delete-authorizer", "delete-base-path-mapping", "delete-client-certificate", "delete-deployment", "delete-documentation-part", "delete-documentation-version", "delete-domain-name", "delete-domain-name-access-association", "delete-gateway-response", "delete-integration", "delete-integration-response", "delete-method", "delete-method-response", "delete-model", "delete-request-validator", "delete-resource", "delete-rest-api", "delete-stage", "delete-usage-plan", "delete-usage-plan-key", "delete-vpc-link", "flush-stage-authorizers-cache", "flush-stage-cache", "generate-client-certificate", "get-account", "get-api-key", "get-api-keys", "get-authorizer", "get-authorizers", "get-base-path-mapping", "get-base-path-mappings", "get-client-certificate", "get-client-certificates", "get-deployment", "get-deployments", "get-documentation-part", "get-documentation-parts", "get-documentation-version", "get-documentation-versions", "get-domain-name", "get-domain-name-access-associations", "get-domain-names", "get-export", "get-gateway-response", "get-gateway-responses", "get-integration", "get-integration-response", "get-method", "get-method-response", "get-model", "get-model-template", "get-models", "get-request-validator", "get-request-validators", "get-resource", "get-resources", "get-rest-api", "get-rest-apis", "get-sdk", "get-sdk-type", "get-sdk-types", "get-stage", "get-stages", "get-tags", "get-usage", "get-usage-plan", "get-usage-plan-key", "get-usage-plan-keys", "get-usage-plans", "get-vpc-link", "get-vpc-links", "import-api-keys", "import-documentation-parts", "import-rest-api", "put-gateway-response", "put-integration", "put-integration-response", "put-method", "put-method-response", "put-rest-api", "reject-domain-name-access-association", "tag-resource", "test-invoke-authorizer", "test-invoke-method", "untag-resource", "update-account", "update-api-key", "update-authorizer", "update-base-path-mapping", "update-client-certificate", "update-deployment", "update-documentation-part", "update-documentation-version", "update-domain-name", "update-gateway-response", "update-integration", "update-integration-response", "update-method", "update-method-response", "update-model", "update-request-validator", "update-resource", "update-rest-api", "update-stage", "update-usage", "update-usage-plan", "update-vpc-link"},
		OperationSet: map[string]bool{"create-api-key": true, "create-authorizer": true, "create-base-path-mapping": true, "create-deployment": true, "create-documentation-part": true, "create-documentation-version": true, "create-domain-name": true, "create-domain-name-access-association": true, "create-model": true, "create-request-validator": true, "create-resource": true, "create-rest-api": true, "create-stage": true, "create-usage-plan": true, "create-usage-plan-key": true, "create-vpc-link": true, "delete-api-key": true, "delete-authorizer": true, "delete-base-path-mapping": true, "delete-client-certificate": true, "delete-deployment": true, "delete-documentation-part": true, "delete-documentation-version": true, "delete-domain-name": true, "delete-domain-name-access-association": true, "delete-gateway-response": true, "delete-integration": true, "delete-integration-response": true, "delete-method": true, "delete-method-response": true, "delete-model": true, "delete-request-validator": true, "delete-resource": true, "delete-rest-api": true, "delete-stage": true, "delete-usage-plan": true, "delete-usage-plan-key": true, "delete-vpc-link": true, "flush-stage-authorizers-cache": true, "flush-stage-cache": true, "generate-client-certificate": true, "get-account": true, "get-api-key": true, "get-api-keys": true, "get-authorizer": true, "get-authorizers": true, "get-base-path-mapping": true, "get-base-path-mappings": true, "get-client-certificate": true, "get-client-certificates": true, "get-deployment": true, "get-deployments": true, "get-documentation-part": true, "get-documentation-parts": true, "get-documentation-version": true, "get-documentation-versions": true, "get-domain-name": true, "get-domain-name-access-associations": true, "get-domain-names": true, "get-export": true, "get-gateway-response": true, "get-gateway-responses": true, "get-integration": true, "get-integration-response": true, "get-method": true, "get-method-response": true, "get-model": true, "get-model-template": true, "get-models": true, "get-request-validator": true, "get-request-validators": true, "get-resource": true, "get-resources": true, "get-rest-api": true, "get-rest-apis": true, "get-sdk": true, "get-sdk-type": true, "get-sdk-types": true, "get-stage": true, "get-stages": true, "get-tags": true, "get-usage": true, "get-usage-plan": true, "get-usage-plan-key": true, "get-usage-plan-keys": true, "get-usage-plans": true, "get-vpc-link": true, "get-vpc-links": true, "import-api-keys": true, "import-documentation-parts": true, "import-rest-api": true, "put-gateway-response": true, "put-integration": true, "put-integration-response": true, "put-method": true, "put-method-response": true, "put-rest-api": true, "reject-domain-name-access-association": true, "tag-resource": true, "test-invoke-authorizer": true, "test-invoke-method": true, "untag-resource": true, "update-account": true, "update-api-key": true, "update-authorizer": true, "update-base-path-mapping": true, "update-client-certificate": true, "update-deployment": true, "update-documentation-part": true, "update-documentation-version": true, "update-domain-name": true, "update-gateway-response": true, "update-integration": true, "update-integration-response": true, "update-method": true, "update-method-response": true, "update-model": true, "update-request-validator": true, "update-resource": true, "update-rest-api": true, "update-stage": true, "update-usage": true, "update-usage-plan": true, "update-vpc-link": true},
		OperationInputs: map[string][]string{
			"create-api-key":                        {"CustomerId", "Description", "Enabled", "GenerateDistinctId", "Name", "StageKeys", "Tags", "Value"},
			"create-authorizer":                     {"AuthType", "AuthorizerCredentials", "AuthorizerResultTtlInSeconds", "AuthorizerUri", "IdentitySource", "IdentityValidationExpression", "Name", "ProviderARNs", "RestApiId", "Type"},
			"create-base-path-mapping":              {"BasePath", "DomainName", "DomainNameId", "RestApiId", "Stage"},
			"create-deployment":                     {"CacheClusterEnabled", "CacheClusterSize", "CanarySettings", "Description", "RestApiId", "StageDescription", "StageName", "TracingEnabled", "Variables"},
			"create-documentation-part":             {"Location", "Properties", "RestApiId"},
			"create-documentation-version":          {"Description", "DocumentationVersion", "RestApiId", "StageName"},
			"create-domain-name":                    {"CertificateArn", "CertificateBody", "CertificateChain", "CertificateName", "CertificatePrivateKey", "DomainName", "EndpointAccessMode", "EndpointConfiguration", "MutualTlsAuthentication", "OwnershipVerificationCertificateArn", "Policy", "RegionalCertificateArn", "RegionalCertificateName", "RoutingMode", "SecurityPolicy", "Tags"},
			"create-domain-name-access-association": {"AccessAssociationSource", "AccessAssociationSourceType", "DomainNameArn", "Tags"},
			"create-model":                          {"ContentType", "Description", "Name", "RestApiId", "Schema"},
			"create-request-validator":              {"Name", "RestApiId", "ValidateRequestBody", "ValidateRequestParameters"},
			"create-resource":                       {"ParentId", "PathPart", "RestApiId"},
			"create-rest-api":                       {"ApiKeySource", "BinaryMediaTypes", "CloneFrom", "Description", "DisableExecuteApiEndpoint", "EndpointAccessMode", "EndpointConfiguration", "MinimumCompressionSize", "Name", "Policy", "SecurityPolicy", "Tags", "Version"},
			"create-stage":                          {"CacheClusterEnabled", "CacheClusterSize", "CanarySettings", "DeploymentId", "Description", "DocumentationVersion", "RestApiId", "StageName", "Tags", "TracingEnabled", "Variables"},
			"create-usage-plan":                     {"ApiStages", "Description", "Name", "Quota", "Tags", "Throttle"},
			"create-usage-plan-key":                 {"KeyId", "KeyType", "UsagePlanId"},
			"create-vpc-link":                       {"Description", "Name", "Tags", "TargetArns"},
			"delete-api-key":                        {"ApiKey"},
			"delete-authorizer":                     {"AuthorizerId", "RestApiId"},
			"delete-base-path-mapping":              {"BasePath", "DomainName", "DomainNameId"},
			"delete-client-certificate":             {"ClientCertificateId"},
			"delete-deployment":                     {"DeploymentId", "RestApiId"},
			"delete-documentation-part":             {"DocumentationPartId", "RestApiId"},
			"delete-documentation-version":          {"DocumentationVersion", "RestApiId"},
			"delete-domain-name":                    {"DomainName", "DomainNameId"},
			"delete-domain-name-access-association": {"DomainNameAccessAssociationArn"},
			"delete-gateway-response":               {"ResponseType", "RestApiId"},
			"delete-integration":                    {"HttpMethod", "ResourceId", "RestApiId"},
			"delete-integration-response":           {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"delete-method":                         {"HttpMethod", "ResourceId", "RestApiId"},
			"delete-method-response":                {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"delete-model":                          {"ModelName", "RestApiId"},
			"delete-request-validator":              {"RequestValidatorId", "RestApiId"},
			"delete-resource":                       {"ResourceId", "RestApiId"},
			"delete-rest-api":                       {"RestApiId"},
			"delete-stage":                          {"RestApiId", "StageName"},
			"delete-usage-plan":                     {"UsagePlanId"},
			"delete-usage-plan-key":                 {"KeyId", "UsagePlanId"},
			"delete-vpc-link":                       {"VpcLinkId"},
			"flush-stage-authorizers-cache":         {"RestApiId", "StageName"},
			"flush-stage-cache":                     {"RestApiId", "StageName"},
			"generate-client-certificate":           {"Description", "Tags"},
			"get-account":                           {},
			"get-api-key":                           {"ApiKey", "IncludeValue"},
			"get-api-keys":                          {"CustomerId", "IncludeValues", "Limit", "NameQuery", "Position"},
			"get-authorizer":                        {"AuthorizerId", "RestApiId"},
			"get-authorizers":                       {"Limit", "Position", "RestApiId"},
			"get-base-path-mapping":                 {"BasePath", "DomainName", "DomainNameId"},
			"get-base-path-mappings":                {"DomainName", "DomainNameId", "Limit", "Position"},
			"get-client-certificate":                {"ClientCertificateId"},
			"get-client-certificates":               {"Limit", "Position"},
			"get-deployment":                        {"DeploymentId", "Embed", "RestApiId"},
			"get-deployments":                       {"Limit", "Position", "RestApiId"},
			"get-documentation-part":                {"DocumentationPartId", "RestApiId"},
			"get-documentation-parts":               {"Limit", "LocationStatus", "NameQuery", "Path", "Position", "RestApiId", "Type"},
			"get-documentation-version":             {"DocumentationVersion", "RestApiId"},
			"get-documentation-versions":            {"Limit", "Position", "RestApiId"},
			"get-domain-name":                       {"DomainName", "DomainNameId"},
			"get-domain-name-access-associations":   {"Limit", "Position", "ResourceOwner"},
			"get-domain-names":                      {"Limit", "Position", "ResourceOwner"},
			"get-export":                            {"Accepts", "ExportType", "Parameters", "RestApiId", "StageName"},
			"get-gateway-response":                  {"ResponseType", "RestApiId"},
			"get-gateway-responses":                 {"Limit", "Position", "RestApiId"},
			"get-integration":                       {"HttpMethod", "ResourceId", "RestApiId"},
			"get-integration-response":              {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"get-method":                            {"HttpMethod", "ResourceId", "RestApiId"},
			"get-method-response":                   {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"get-model":                             {"Flatten", "ModelName", "RestApiId"},
			"get-model-template":                    {"ModelName", "RestApiId"},
			"get-models":                            {"Limit", "Position", "RestApiId"},
			"get-request-validator":                 {"RequestValidatorId", "RestApiId"},
			"get-request-validators":                {"Limit", "Position", "RestApiId"},
			"get-resource":                          {"Embed", "ResourceId", "RestApiId"},
			"get-resources":                         {"Embed", "Limit", "Position", "RestApiId"},
			"get-rest-api":                          {"RestApiId"},
			"get-rest-apis":                         {"Limit", "Position"},
			"get-sdk":                               {"Parameters", "RestApiId", "SdkType", "StageName"},
			"get-sdk-type":                          {"Id"},
			"get-sdk-types":                         {"Limit", "Position"},
			"get-stage":                             {"RestApiId", "StageName"},
			"get-stages":                            {"DeploymentId", "RestApiId"},
			"get-tags":                              {"Limit", "Position", "ResourceArn"},
			"get-usage":                             {"EndDate", "KeyId", "Limit", "Position", "StartDate", "UsagePlanId"},
			"get-usage-plan":                        {"UsagePlanId"},
			"get-usage-plan-key":                    {"KeyId", "UsagePlanId"},
			"get-usage-plan-keys":                   {"Limit", "NameQuery", "Position", "UsagePlanId"},
			"get-usage-plans":                       {"KeyId", "Limit", "Position"},
			"get-vpc-link":                          {"VpcLinkId"},
			"get-vpc-links":                         {"Limit", "Position"},
			"import-api-keys":                       {"Body", "FailOnWarnings", "Format"},
			"import-documentation-parts":            {"Body", "FailOnWarnings", "Mode", "RestApiId"},
			"import-rest-api":                       {"Body", "FailOnWarnings", "Parameters"},
			"put-gateway-response":                  {"ResponseParameters", "ResponseTemplates", "ResponseType", "RestApiId", "StatusCode"},
			"put-integration":                       {"CacheKeyParameters", "CacheNamespace", "ConnectionId", "ConnectionType", "ContentHandling", "Credentials", "HttpMethod", "IntegrationHttpMethod", "IntegrationTarget", "PassthroughBehavior", "RequestParameters", "RequestTemplates", "ResourceId", "ResponseTransferMode", "RestApiId", "TimeoutInMillis", "TlsConfig", "Type", "Uri"},
			"put-integration-response":              {"ContentHandling", "HttpMethod", "ResourceId", "ResponseParameters", "ResponseTemplates", "RestApiId", "SelectionPattern", "StatusCode"},
			"put-method":                            {"ApiKeyRequired", "AuthorizationScopes", "AuthorizationType", "AuthorizerId", "HttpMethod", "OperationName", "RequestModels", "RequestParameters", "RequestValidatorId", "ResourceId", "RestApiId"},
			"put-method-response":                   {"HttpMethod", "ResourceId", "ResponseModels", "ResponseParameters", "RestApiId", "StatusCode"},
			"put-rest-api":                          {"Body", "FailOnWarnings", "Mode", "Parameters", "RestApiId"},
			"reject-domain-name-access-association": {"DomainNameAccessAssociationArn", "DomainNameArn"},
			"tag-resource":                          {"ResourceArn", "Tags"},
			"test-invoke-authorizer":                {"AdditionalContext", "AuthorizerId", "Body", "Headers", "MultiValueHeaders", "PathWithQueryString", "RestApiId", "StageVariables"},
			"test-invoke-method":                    {"Body", "ClientCertificateId", "Headers", "HttpMethod", "MultiValueHeaders", "PathWithQueryString", "ResourceId", "RestApiId", "StageVariables"},
			"untag-resource":                        {"ResourceArn", "TagKeys"},
			"update-account":                        {"PatchOperations"},
			"update-api-key":                        {"ApiKey", "PatchOperations"},
			"update-authorizer":                     {"AuthorizerId", "PatchOperations", "RestApiId"},
			"update-base-path-mapping":              {"BasePath", "DomainName", "DomainNameId", "PatchOperations"},
			"update-client-certificate":             {"ClientCertificateId", "PatchOperations"},
			"update-deployment":                     {"DeploymentId", "PatchOperations", "RestApiId"},
			"update-documentation-part":             {"DocumentationPartId", "PatchOperations", "RestApiId"},
			"update-documentation-version":          {"DocumentationVersion", "PatchOperations", "RestApiId"},
			"update-domain-name":                    {"DomainName", "DomainNameId", "PatchOperations"},
			"update-gateway-response":               {"PatchOperations", "ResponseType", "RestApiId"},
			"update-integration":                    {"HttpMethod", "PatchOperations", "ResourceId", "RestApiId"},
			"update-integration-response":           {"HttpMethod", "PatchOperations", "ResourceId", "RestApiId", "StatusCode"},
			"update-method":                         {"HttpMethod", "PatchOperations", "ResourceId", "RestApiId"},
			"update-method-response":                {"HttpMethod", "PatchOperations", "ResourceId", "RestApiId", "StatusCode"},
			"update-model":                          {"ModelName", "PatchOperations", "RestApiId"},
			"update-request-validator":              {"PatchOperations", "RequestValidatorId", "RestApiId"},
			"update-resource":                       {"PatchOperations", "ResourceId", "RestApiId"},
			"update-rest-api":                       {"PatchOperations", "RestApiId"},
			"update-stage":                          {"PatchOperations", "RestApiId", "StageName"},
			"update-usage":                          {"KeyId", "PatchOperations", "UsagePlanId"},
			"update-usage-plan":                     {"PatchOperations", "UsagePlanId"},
			"update-vpc-link":                       {"PatchOperations", "VpcLinkId"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-api-key":                        {"CustomerId": "*string", "Description": "*string", "Enabled": "bool", "GenerateDistinctId": "bool", "Name": "*string", "StageKeys": "[]types.StageKey", "Tags": "map[string]string", "Value": "*string"},
			"create-authorizer":                     {"AuthType": "*string", "AuthorizerCredentials": "*string", "AuthorizerResultTtlInSeconds": "*int32", "AuthorizerUri": "*string", "IdentitySource": "*string", "IdentityValidationExpression": "*string", "Name": "*string", "ProviderARNs": "[]string", "RestApiId": "*string", "Type": "types.AuthorizerType"},
			"create-base-path-mapping":              {"BasePath": "*string", "DomainName": "*string", "DomainNameId": "*string", "RestApiId": "*string", "Stage": "*string"},
			"create-deployment":                     {"CacheClusterEnabled": "*bool", "CacheClusterSize": "types.CacheClusterSize", "CanarySettings": "*types.DeploymentCanarySettings", "Description": "*string", "RestApiId": "*string", "StageDescription": "*string", "StageName": "*string", "TracingEnabled": "*bool", "Variables": "map[string]string"},
			"create-documentation-part":             {"Location": "*types.DocumentationPartLocation", "Properties": "*string", "RestApiId": "*string"},
			"create-documentation-version":          {"Description": "*string", "DocumentationVersion": "*string", "RestApiId": "*string", "StageName": "*string"},
			"create-domain-name":                    {"CertificateArn": "*string", "CertificateBody": "*string", "CertificateChain": "*string", "CertificateName": "*string", "CertificatePrivateKey": "*string", "DomainName": "*string", "EndpointAccessMode": "types.EndpointAccessMode", "EndpointConfiguration": "*types.EndpointConfiguration", "MutualTlsAuthentication": "*types.MutualTlsAuthenticationInput", "OwnershipVerificationCertificateArn": "*string", "Policy": "*string", "RegionalCertificateArn": "*string", "RegionalCertificateName": "*string", "RoutingMode": "types.RoutingMode", "SecurityPolicy": "types.SecurityPolicy", "Tags": "map[string]string"},
			"create-domain-name-access-association": {"AccessAssociationSource": "*string", "AccessAssociationSourceType": "types.AccessAssociationSourceType", "DomainNameArn": "*string", "Tags": "map[string]string"},
			"create-model":                          {"ContentType": "*string", "Description": "*string", "Name": "*string", "RestApiId": "*string", "Schema": "*string"},
			"create-request-validator":              {"Name": "*string", "RestApiId": "*string", "ValidateRequestBody": "bool", "ValidateRequestParameters": "bool"},
			"create-resource":                       {"ParentId": "*string", "PathPart": "*string", "RestApiId": "*string"},
			"create-rest-api":                       {"ApiKeySource": "types.ApiKeySourceType", "BinaryMediaTypes": "[]string", "CloneFrom": "*string", "Description": "*string", "DisableExecuteApiEndpoint": "bool", "EndpointAccessMode": "types.EndpointAccessMode", "EndpointConfiguration": "*types.EndpointConfiguration", "MinimumCompressionSize": "*int32", "Name": "*string", "Policy": "*string", "SecurityPolicy": "types.SecurityPolicy", "Tags": "map[string]string", "Version": "*string"},
			"create-stage":                          {"CacheClusterEnabled": "bool", "CacheClusterSize": "types.CacheClusterSize", "CanarySettings": "*types.CanarySettings", "DeploymentId": "*string", "Description": "*string", "DocumentationVersion": "*string", "RestApiId": "*string", "StageName": "*string", "Tags": "map[string]string", "TracingEnabled": "bool", "Variables": "map[string]string"},
			"create-usage-plan":                     {"ApiStages": "[]types.ApiStage", "Description": "*string", "Name": "*string", "Quota": "*types.QuotaSettings", "Tags": "map[string]string", "Throttle": "*types.ThrottleSettings"},
			"create-usage-plan-key":                 {"KeyId": "*string", "KeyType": "*string", "UsagePlanId": "*string"},
			"create-vpc-link":                       {"Description": "*string", "Name": "*string", "Tags": "map[string]string", "TargetArns": "[]string"},
			"delete-api-key":                        {"ApiKey": "*string"},
			"delete-authorizer":                     {"AuthorizerId": "*string", "RestApiId": "*string"},
			"delete-base-path-mapping":              {"BasePath": "*string", "DomainName": "*string", "DomainNameId": "*string"},
			"delete-client-certificate":             {"ClientCertificateId": "*string"},
			"delete-deployment":                     {"DeploymentId": "*string", "RestApiId": "*string"},
			"delete-documentation-part":             {"DocumentationPartId": "*string", "RestApiId": "*string"},
			"delete-documentation-version":          {"DocumentationVersion": "*string", "RestApiId": "*string"},
			"delete-domain-name":                    {"DomainName": "*string", "DomainNameId": "*string"},
			"delete-domain-name-access-association": {"DomainNameAccessAssociationArn": "*string"},
			"delete-gateway-response":               {"ResponseType": "types.GatewayResponseType", "RestApiId": "*string"},
			"delete-integration":                    {"HttpMethod": "*string", "ResourceId": "*string", "RestApiId": "*string"},
			"delete-integration-response":           {"HttpMethod": "*string", "ResourceId": "*string", "RestApiId": "*string", "StatusCode": "*string"},
			"delete-method":                         {"HttpMethod": "*string", "ResourceId": "*string", "RestApiId": "*string"},
			"delete-method-response":                {"HttpMethod": "*string", "ResourceId": "*string", "RestApiId": "*string", "StatusCode": "*string"},
			"delete-model":                          {"ModelName": "*string", "RestApiId": "*string"},
			"delete-request-validator":              {"RequestValidatorId": "*string", "RestApiId": "*string"},
			"delete-resource":                       {"ResourceId": "*string", "RestApiId": "*string"},
			"delete-rest-api":                       {"RestApiId": "*string"},
			"delete-stage":                          {"RestApiId": "*string", "StageName": "*string"},
			"delete-usage-plan":                     {"UsagePlanId": "*string"},
			"delete-usage-plan-key":                 {"KeyId": "*string", "UsagePlanId": "*string"},
			"delete-vpc-link":                       {"VpcLinkId": "*string"},
			"flush-stage-authorizers-cache":         {"RestApiId": "*string", "StageName": "*string"},
			"flush-stage-cache":                     {"RestApiId": "*string", "StageName": "*string"},
			"generate-client-certificate":           {"Description": "*string", "Tags": "map[string]string"},
			"get-account":                           {},
			"get-api-key":                           {"ApiKey": "*string", "IncludeValue": "*bool"},
			"get-api-keys":                          {"CustomerId": "*string", "IncludeValues": "*bool", "Limit": "*int32", "NameQuery": "*string", "Position": "*string"},
			"get-authorizer":                        {"AuthorizerId": "*string", "RestApiId": "*string"},
			"get-authorizers":                       {"Limit": "*int32", "Position": "*string", "RestApiId": "*string"},
			"get-base-path-mapping":                 {"BasePath": "*string", "DomainName": "*string", "DomainNameId": "*string"},
			"get-base-path-mappings":                {"DomainName": "*string", "DomainNameId": "*string", "Limit": "*int32", "Position": "*string"},
			"get-client-certificate":                {"ClientCertificateId": "*string"},
			"get-client-certificates":               {"Limit": "*int32", "Position": "*string"},
			"get-deployment":                        {"DeploymentId": "*string", "Embed": "[]string", "RestApiId": "*string"},
			"get-deployments":                       {"Limit": "*int32", "Position": "*string", "RestApiId": "*string"},
			"get-documentation-part":                {"DocumentationPartId": "*string", "RestApiId": "*string"},
			"get-documentation-parts":               {"Limit": "*int32", "LocationStatus": "types.LocationStatusType", "NameQuery": "*string", "Path": "*string", "Position": "*string", "RestApiId": "*string", "Type": "types.DocumentationPartType"},
			"get-documentation-version":             {"DocumentationVersion": "*string", "RestApiId": "*string"},
			"get-documentation-versions":            {"Limit": "*int32", "Position": "*string", "RestApiId": "*string"},
			"get-domain-name":                       {"DomainName": "*string", "DomainNameId": "*string"},
			"get-domain-name-access-associations":   {"Limit": "*int32", "Position": "*string", "ResourceOwner": "types.ResourceOwner"},
			"get-domain-names":                      {"Limit": "*int32", "Position": "*string", "ResourceOwner": "types.ResourceOwner"},
			"get-export":                            {"Accepts": "*string", "ExportType": "*string", "Parameters": "map[string]string", "RestApiId": "*string", "StageName": "*string"},
			"get-gateway-response":                  {"ResponseType": "types.GatewayResponseType", "RestApiId": "*string"},
			"get-gateway-responses":                 {"Limit": "*int32", "Position": "*string", "RestApiId": "*string"},
			"get-integration":                       {"HttpMethod": "*string", "ResourceId": "*string", "RestApiId": "*string"},
			"get-integration-response":              {"HttpMethod": "*string", "ResourceId": "*string", "RestApiId": "*string", "StatusCode": "*string"},
			"get-method":                            {"HttpMethod": "*string", "ResourceId": "*string", "RestApiId": "*string"},
			"get-method-response":                   {"HttpMethod": "*string", "ResourceId": "*string", "RestApiId": "*string", "StatusCode": "*string"},
			"get-model":                             {"Flatten": "bool", "ModelName": "*string", "RestApiId": "*string"},
			"get-model-template":                    {"ModelName": "*string", "RestApiId": "*string"},
			"get-models":                            {"Limit": "*int32", "Position": "*string", "RestApiId": "*string"},
			"get-request-validator":                 {"RequestValidatorId": "*string", "RestApiId": "*string"},
			"get-request-validators":                {"Limit": "*int32", "Position": "*string", "RestApiId": "*string"},
			"get-resource":                          {"Embed": "[]string", "ResourceId": "*string", "RestApiId": "*string"},
			"get-resources":                         {"Embed": "[]string", "Limit": "*int32", "Position": "*string", "RestApiId": "*string"},
			"get-rest-api":                          {"RestApiId": "*string"},
			"get-rest-apis":                         {"Limit": "*int32", "Position": "*string"},
			"get-sdk":                               {"Parameters": "map[string]string", "RestApiId": "*string", "SdkType": "*string", "StageName": "*string"},
			"get-sdk-type":                          {"Id": "*string"},
			"get-sdk-types":                         {"Limit": "*int32", "Position": "*string"},
			"get-stage":                             {"RestApiId": "*string", "StageName": "*string"},
			"get-stages":                            {"DeploymentId": "*string", "RestApiId": "*string"},
			"get-tags":                              {"Limit": "*int32", "Position": "*string", "ResourceArn": "*string"},
			"get-usage":                             {"EndDate": "*string", "KeyId": "*string", "Limit": "*int32", "Position": "*string", "StartDate": "*string", "UsagePlanId": "*string"},
			"get-usage-plan":                        {"UsagePlanId": "*string"},
			"get-usage-plan-key":                    {"KeyId": "*string", "UsagePlanId": "*string"},
			"get-usage-plan-keys":                   {"Limit": "*int32", "NameQuery": "*string", "Position": "*string", "UsagePlanId": "*string"},
			"get-usage-plans":                       {"KeyId": "*string", "Limit": "*int32", "Position": "*string"},
			"get-vpc-link":                          {"VpcLinkId": "*string"},
			"get-vpc-links":                         {"Limit": "*int32", "Position": "*string"},
			"import-api-keys":                       {"Body": "[]byte", "FailOnWarnings": "bool", "Format": "types.ApiKeysFormat"},
			"import-documentation-parts":            {"Body": "[]byte", "FailOnWarnings": "bool", "Mode": "types.PutMode", "RestApiId": "*string"},
			"import-rest-api":                       {"Body": "[]byte", "FailOnWarnings": "bool", "Parameters": "map[string]string"},
			"put-gateway-response":                  {"ResponseParameters": "map[string]string", "ResponseTemplates": "map[string]string", "ResponseType": "types.GatewayResponseType", "RestApiId": "*string", "StatusCode": "*string"},
			"put-integration":                       {"CacheKeyParameters": "[]string", "CacheNamespace": "*string", "ConnectionId": "*string", "ConnectionType": "types.ConnectionType", "ContentHandling": "types.ContentHandlingStrategy", "Credentials": "*string", "HttpMethod": "*string", "IntegrationHttpMethod": "*string", "IntegrationTarget": "*string", "PassthroughBehavior": "*string", "RequestParameters": "map[string]string", "RequestTemplates": "map[string]string", "ResourceId": "*string", "ResponseTransferMode": "types.ResponseTransferMode", "RestApiId": "*string", "TimeoutInMillis": "*int32", "TlsConfig": "*types.TlsConfig", "Type": "types.IntegrationType", "Uri": "*string"},
			"put-integration-response":              {"ContentHandling": "types.ContentHandlingStrategy", "HttpMethod": "*string", "ResourceId": "*string", "ResponseParameters": "map[string]string", "ResponseTemplates": "map[string]string", "RestApiId": "*string", "SelectionPattern": "*string", "StatusCode": "*string"},
			"put-method":                            {"ApiKeyRequired": "bool", "AuthorizationScopes": "[]string", "AuthorizationType": "*string", "AuthorizerId": "*string", "HttpMethod": "*string", "OperationName": "*string", "RequestModels": "map[string]string", "RequestParameters": "map[string]bool", "RequestValidatorId": "*string", "ResourceId": "*string", "RestApiId": "*string"},
			"put-method-response":                   {"HttpMethod": "*string", "ResourceId": "*string", "ResponseModels": "map[string]string", "ResponseParameters": "map[string]bool", "RestApiId": "*string", "StatusCode": "*string"},
			"put-rest-api":                          {"Body": "[]byte", "FailOnWarnings": "bool", "Mode": "types.PutMode", "Parameters": "map[string]string", "RestApiId": "*string"},
			"reject-domain-name-access-association": {"DomainNameAccessAssociationArn": "*string", "DomainNameArn": "*string"},
			"tag-resource":                          {"ResourceArn": "*string", "Tags": "map[string]string"},
			"test-invoke-authorizer":                {"AdditionalContext": "map[string]string", "AuthorizerId": "*string", "Body": "*string", "Headers": "map[string]string", "MultiValueHeaders": "map[string][]string", "PathWithQueryString": "*string", "RestApiId": "*string", "StageVariables": "map[string]string"},
			"test-invoke-method":                    {"Body": "*string", "ClientCertificateId": "*string", "Headers": "map[string]string", "HttpMethod": "*string", "MultiValueHeaders": "map[string][]string", "PathWithQueryString": "*string", "ResourceId": "*string", "RestApiId": "*string", "StageVariables": "map[string]string"},
			"untag-resource":                        {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-account":                        {"PatchOperations": "[]types.PatchOperation"},
			"update-api-key":                        {"ApiKey": "*string", "PatchOperations": "[]types.PatchOperation"},
			"update-authorizer":                     {"AuthorizerId": "*string", "PatchOperations": "[]types.PatchOperation", "RestApiId": "*string"},
			"update-base-path-mapping":              {"BasePath": "*string", "DomainName": "*string", "DomainNameId": "*string", "PatchOperations": "[]types.PatchOperation"},
			"update-client-certificate":             {"ClientCertificateId": "*string", "PatchOperations": "[]types.PatchOperation"},
			"update-deployment":                     {"DeploymentId": "*string", "PatchOperations": "[]types.PatchOperation", "RestApiId": "*string"},
			"update-documentation-part":             {"DocumentationPartId": "*string", "PatchOperations": "[]types.PatchOperation", "RestApiId": "*string"},
			"update-documentation-version":          {"DocumentationVersion": "*string", "PatchOperations": "[]types.PatchOperation", "RestApiId": "*string"},
			"update-domain-name":                    {"DomainName": "*string", "DomainNameId": "*string", "PatchOperations": "[]types.PatchOperation"},
			"update-gateway-response":               {"PatchOperations": "[]types.PatchOperation", "ResponseType": "types.GatewayResponseType", "RestApiId": "*string"},
			"update-integration":                    {"HttpMethod": "*string", "PatchOperations": "[]types.PatchOperation", "ResourceId": "*string", "RestApiId": "*string"},
			"update-integration-response":           {"HttpMethod": "*string", "PatchOperations": "[]types.PatchOperation", "ResourceId": "*string", "RestApiId": "*string", "StatusCode": "*string"},
			"update-method":                         {"HttpMethod": "*string", "PatchOperations": "[]types.PatchOperation", "ResourceId": "*string", "RestApiId": "*string"},
			"update-method-response":                {"HttpMethod": "*string", "PatchOperations": "[]types.PatchOperation", "ResourceId": "*string", "RestApiId": "*string", "StatusCode": "*string"},
			"update-model":                          {"ModelName": "*string", "PatchOperations": "[]types.PatchOperation", "RestApiId": "*string"},
			"update-request-validator":              {"PatchOperations": "[]types.PatchOperation", "RequestValidatorId": "*string", "RestApiId": "*string"},
			"update-resource":                       {"PatchOperations": "[]types.PatchOperation", "ResourceId": "*string", "RestApiId": "*string"},
			"update-rest-api":                       {"PatchOperations": "[]types.PatchOperation", "RestApiId": "*string"},
			"update-stage":                          {"PatchOperations": "[]types.PatchOperation", "RestApiId": "*string", "StageName": "*string"},
			"update-usage":                          {"KeyId": "*string", "PatchOperations": "[]types.PatchOperation", "UsagePlanId": "*string"},
			"update-usage-plan":                     {"PatchOperations": "[]types.PatchOperation", "UsagePlanId": "*string"},
			"update-vpc-link":                       {"PatchOperations": "[]types.PatchOperation", "VpcLinkId": "*string"},
		},
		OperationInputRequired: map[string][]string{
			"create-api-key":                        {},
			"create-authorizer":                     {"Name", "RestApiId", "Type"},
			"create-base-path-mapping":              {"DomainName", "RestApiId"},
			"create-deployment":                     {"RestApiId"},
			"create-documentation-part":             {"Location", "Properties", "RestApiId"},
			"create-documentation-version":          {"DocumentationVersion", "RestApiId"},
			"create-domain-name":                    {"DomainName"},
			"create-domain-name-access-association": {"AccessAssociationSource", "AccessAssociationSourceType", "DomainNameArn"},
			"create-model":                          {"ContentType", "Name", "RestApiId"},
			"create-request-validator":              {"RestApiId"},
			"create-resource":                       {"ParentId", "PathPart", "RestApiId"},
			"create-rest-api":                       {"Name"},
			"create-stage":                          {"DeploymentId", "RestApiId", "StageName"},
			"create-usage-plan":                     {"Name"},
			"create-usage-plan-key":                 {"KeyId", "KeyType", "UsagePlanId"},
			"create-vpc-link":                       {"Name", "TargetArns"},
			"delete-api-key":                        {"ApiKey"},
			"delete-authorizer":                     {"AuthorizerId", "RestApiId"},
			"delete-base-path-mapping":              {"BasePath", "DomainName"},
			"delete-client-certificate":             {"ClientCertificateId"},
			"delete-deployment":                     {"DeploymentId", "RestApiId"},
			"delete-documentation-part":             {"DocumentationPartId", "RestApiId"},
			"delete-documentation-version":          {"DocumentationVersion", "RestApiId"},
			"delete-domain-name":                    {"DomainName"},
			"delete-domain-name-access-association": {"DomainNameAccessAssociationArn"},
			"delete-gateway-response":               {"ResponseType", "RestApiId"},
			"delete-integration":                    {"HttpMethod", "ResourceId", "RestApiId"},
			"delete-integration-response":           {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"delete-method":                         {"HttpMethod", "ResourceId", "RestApiId"},
			"delete-method-response":                {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"delete-model":                          {"ModelName", "RestApiId"},
			"delete-request-validator":              {"RequestValidatorId", "RestApiId"},
			"delete-resource":                       {"ResourceId", "RestApiId"},
			"delete-rest-api":                       {"RestApiId"},
			"delete-stage":                          {"RestApiId", "StageName"},
			"delete-usage-plan":                     {"UsagePlanId"},
			"delete-usage-plan-key":                 {"KeyId", "UsagePlanId"},
			"delete-vpc-link":                       {"VpcLinkId"},
			"flush-stage-authorizers-cache":         {"RestApiId", "StageName"},
			"flush-stage-cache":                     {"RestApiId", "StageName"},
			"generate-client-certificate":           {},
			"get-account":                           {},
			"get-api-key":                           {"ApiKey"},
			"get-api-keys":                          {},
			"get-authorizer":                        {"AuthorizerId", "RestApiId"},
			"get-authorizers":                       {"RestApiId"},
			"get-base-path-mapping":                 {"BasePath", "DomainName"},
			"get-base-path-mappings":                {"DomainName"},
			"get-client-certificate":                {"ClientCertificateId"},
			"get-client-certificates":               {},
			"get-deployment":                        {"DeploymentId", "RestApiId"},
			"get-deployments":                       {"RestApiId"},
			"get-documentation-part":                {"DocumentationPartId", "RestApiId"},
			"get-documentation-parts":               {"RestApiId"},
			"get-documentation-version":             {"DocumentationVersion", "RestApiId"},
			"get-documentation-versions":            {"RestApiId"},
			"get-domain-name":                       {"DomainName"},
			"get-domain-name-access-associations":   {},
			"get-domain-names":                      {},
			"get-export":                            {"ExportType", "RestApiId", "StageName"},
			"get-gateway-response":                  {"ResponseType", "RestApiId"},
			"get-gateway-responses":                 {"RestApiId"},
			"get-integration":                       {"HttpMethod", "ResourceId", "RestApiId"},
			"get-integration-response":              {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"get-method":                            {"HttpMethod", "ResourceId", "RestApiId"},
			"get-method-response":                   {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"get-model":                             {"ModelName", "RestApiId"},
			"get-model-template":                    {"ModelName", "RestApiId"},
			"get-models":                            {"RestApiId"},
			"get-request-validator":                 {"RequestValidatorId", "RestApiId"},
			"get-request-validators":                {"RestApiId"},
			"get-resource":                          {"ResourceId", "RestApiId"},
			"get-resources":                         {"RestApiId"},
			"get-rest-api":                          {"RestApiId"},
			"get-rest-apis":                         {},
			"get-sdk":                               {"RestApiId", "SdkType", "StageName"},
			"get-sdk-type":                          {"Id"},
			"get-sdk-types":                         {},
			"get-stage":                             {"RestApiId", "StageName"},
			"get-stages":                            {"RestApiId"},
			"get-tags":                              {"ResourceArn"},
			"get-usage":                             {"EndDate", "StartDate", "UsagePlanId"},
			"get-usage-plan":                        {"UsagePlanId"},
			"get-usage-plan-key":                    {"KeyId", "UsagePlanId"},
			"get-usage-plan-keys":                   {"UsagePlanId"},
			"get-usage-plans":                       {},
			"get-vpc-link":                          {"VpcLinkId"},
			"get-vpc-links":                         {},
			"import-api-keys":                       {"Body", "Format"},
			"import-documentation-parts":            {"Body", "RestApiId"},
			"import-rest-api":                       {"Body"},
			"put-gateway-response":                  {"ResponseType", "RestApiId"},
			"put-integration":                       {"HttpMethod", "ResourceId", "RestApiId", "Type"},
			"put-integration-response":              {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"put-method":                            {"AuthorizationType", "HttpMethod", "ResourceId", "RestApiId"},
			"put-method-response":                   {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"put-rest-api":                          {"Body", "RestApiId"},
			"reject-domain-name-access-association": {"DomainNameAccessAssociationArn", "DomainNameArn"},
			"tag-resource":                          {"ResourceArn", "Tags"},
			"test-invoke-authorizer":                {"AuthorizerId", "RestApiId"},
			"test-invoke-method":                    {"HttpMethod", "ResourceId", "RestApiId"},
			"untag-resource":                        {"ResourceArn", "TagKeys"},
			"update-account":                        {},
			"update-api-key":                        {"ApiKey"},
			"update-authorizer":                     {"AuthorizerId", "RestApiId"},
			"update-base-path-mapping":              {"BasePath", "DomainName"},
			"update-client-certificate":             {"ClientCertificateId"},
			"update-deployment":                     {"DeploymentId", "RestApiId"},
			"update-documentation-part":             {"DocumentationPartId", "RestApiId"},
			"update-documentation-version":          {"DocumentationVersion", "RestApiId"},
			"update-domain-name":                    {"DomainName"},
			"update-gateway-response":               {"ResponseType", "RestApiId"},
			"update-integration":                    {"HttpMethod", "ResourceId", "RestApiId"},
			"update-integration-response":           {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"update-method":                         {"HttpMethod", "ResourceId", "RestApiId"},
			"update-method-response":                {"HttpMethod", "ResourceId", "RestApiId", "StatusCode"},
			"update-model":                          {"ModelName", "RestApiId"},
			"update-request-validator":              {"RequestValidatorId", "RestApiId"},
			"update-resource":                       {"ResourceId", "RestApiId"},
			"update-rest-api":                       {"RestApiId"},
			"update-stage":                          {"RestApiId", "StageName"},
			"update-usage":                          {"KeyId", "UsagePlanId"},
			"update-usage-plan":                     {"UsagePlanId"},
			"update-vpc-link":                       {"VpcLinkId"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("apigateway", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
