package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/bedrockagent/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"associate-agent-collaborator", "associate-agent-knowledge-base", "create-agent", "create-agent-action-group", "create-agent-alias", "create-data-source", "create-flow", "create-flow-alias", "create-flow-version", "create-knowledge-base", "create-prompt", "create-prompt-version", "delete-agent", "delete-agent-action-group", "delete-agent-alias", "delete-agent-version", "delete-data-source", "delete-flow", "delete-flow-alias", "delete-flow-version", "delete-knowledge-base", "delete-knowledge-base-documents", "delete-prompt", "disassociate-agent-collaborator", "disassociate-agent-knowledge-base", "get-agent", "get-agent-action-group", "get-agent-alias", "get-agent-collaborator", "get-agent-knowledge-base", "get-agent-version", "get-data-source", "get-flow", "get-flow-alias", "get-flow-version", "get-ingestion-job", "get-knowledge-base", "get-knowledge-base-documents", "get-prompt", "ingest-knowledge-base-documents", "list-agent-action-groups", "list-agent-aliases", "list-agent-collaborators", "list-agent-knowledge-bases", "list-agent-versions", "list-agents", "list-data-sources", "list-flow-aliases", "list-flow-versions", "list-flows", "list-ingestion-jobs", "list-knowledge-base-documents", "list-knowledge-bases", "list-prompts", "list-tags-for-resource", "prepare-agent", "prepare-flow", "start-ingestion-job", "stop-ingestion-job", "tag-resource", "untag-resource", "update-agent", "update-agent-action-group", "update-agent-alias", "update-agent-collaborator", "update-agent-knowledge-base", "update-data-source", "update-flow", "update-flow-alias", "update-knowledge-base", "update-prompt", "validate-flow-definition"},
		OperationSet: map[string]bool{"associate-agent-collaborator": true, "associate-agent-knowledge-base": true, "create-agent": true, "create-agent-action-group": true, "create-agent-alias": true, "create-data-source": true, "create-flow": true, "create-flow-alias": true, "create-flow-version": true, "create-knowledge-base": true, "create-prompt": true, "create-prompt-version": true, "delete-agent": true, "delete-agent-action-group": true, "delete-agent-alias": true, "delete-agent-version": true, "delete-data-source": true, "delete-flow": true, "delete-flow-alias": true, "delete-flow-version": true, "delete-knowledge-base": true, "delete-knowledge-base-documents": true, "delete-prompt": true, "disassociate-agent-collaborator": true, "disassociate-agent-knowledge-base": true, "get-agent": true, "get-agent-action-group": true, "get-agent-alias": true, "get-agent-collaborator": true, "get-agent-knowledge-base": true, "get-agent-version": true, "get-data-source": true, "get-flow": true, "get-flow-alias": true, "get-flow-version": true, "get-ingestion-job": true, "get-knowledge-base": true, "get-knowledge-base-documents": true, "get-prompt": true, "ingest-knowledge-base-documents": true, "list-agent-action-groups": true, "list-agent-aliases": true, "list-agent-collaborators": true, "list-agent-knowledge-bases": true, "list-agent-versions": true, "list-agents": true, "list-data-sources": true, "list-flow-aliases": true, "list-flow-versions": true, "list-flows": true, "list-ingestion-jobs": true, "list-knowledge-base-documents": true, "list-knowledge-bases": true, "list-prompts": true, "list-tags-for-resource": true, "prepare-agent": true, "prepare-flow": true, "start-ingestion-job": true, "stop-ingestion-job": true, "tag-resource": true, "untag-resource": true, "update-agent": true, "update-agent-action-group": true, "update-agent-alias": true, "update-agent-collaborator": true, "update-agent-knowledge-base": true, "update-data-source": true, "update-flow": true, "update-flow-alias": true, "update-knowledge-base": true, "update-prompt": true, "validate-flow-definition": true},
		OperationInputs: map[string][]string{
			"associate-agent-collaborator":      {"AgentDescriptor", "AgentId", "AgentVersion", "ClientToken", "CollaborationInstruction", "CollaboratorName", "RelayConversationHistory"},
			"associate-agent-knowledge-base":    {"AgentId", "AgentVersion", "Description", "KnowledgeBaseId", "KnowledgeBaseState"},
			"create-agent":                      {"AgentCollaboration", "AgentName", "AgentResourceRoleArn", "ClientToken", "CustomOrchestration", "CustomerEncryptionKeyArn", "Description", "FoundationModel", "GuardrailConfiguration", "IdleSessionTTLInSeconds", "Instruction", "MemoryConfiguration", "OrchestrationType", "PromptOverrideConfiguration", "Tags"},
			"create-agent-action-group":         {"ActionGroupExecutor", "ActionGroupName", "ActionGroupState", "AgentId", "AgentVersion", "ApiSchema", "ClientToken", "Description", "FunctionSchema", "ParentActionGroupSignature", "ParentActionGroupSignatureParams"},
			"create-agent-alias":                {"AgentAliasName", "AgentId", "ClientToken", "Description", "RoutingConfiguration", "Tags"},
			"create-data-source":                {"ClientToken", "DataDeletionPolicy", "DataSourceConfiguration", "Description", "KnowledgeBaseId", "Name", "ServerSideEncryptionConfiguration", "VectorIngestionConfiguration"},
			"create-flow":                       {"ClientToken", "CustomerEncryptionKeyArn", "Definition", "Description", "ExecutionRoleArn", "Name", "Tags"},
			"create-flow-alias":                 {"ClientToken", "ConcurrencyConfiguration", "Description", "FlowIdentifier", "Name", "RoutingConfiguration", "Tags"},
			"create-flow-version":               {"ClientToken", "Description", "FlowIdentifier"},
			"create-knowledge-base":             {"ClientToken", "Description", "KnowledgeBaseConfiguration", "Name", "RoleArn", "StorageConfiguration", "Tags"},
			"create-prompt":                     {"ClientToken", "CustomerEncryptionKeyArn", "DefaultVariant", "Description", "Name", "Tags", "Variants"},
			"create-prompt-version":             {"ClientToken", "Description", "PromptIdentifier", "Tags"},
			"delete-agent":                      {"AgentId", "SkipResourceInUseCheck"},
			"delete-agent-action-group":         {"ActionGroupId", "AgentId", "AgentVersion", "SkipResourceInUseCheck"},
			"delete-agent-alias":                {"AgentAliasId", "AgentId"},
			"delete-agent-version":              {"AgentId", "AgentVersion", "SkipResourceInUseCheck"},
			"delete-data-source":                {"DataSourceId", "KnowledgeBaseId"},
			"delete-flow":                       {"FlowIdentifier", "SkipResourceInUseCheck"},
			"delete-flow-alias":                 {"AliasIdentifier", "FlowIdentifier"},
			"delete-flow-version":               {"FlowIdentifier", "FlowVersion", "SkipResourceInUseCheck"},
			"delete-knowledge-base":             {"KnowledgeBaseId"},
			"delete-knowledge-base-documents":   {"ClientToken", "DataSourceId", "DocumentIdentifiers", "KnowledgeBaseId"},
			"delete-prompt":                     {"PromptIdentifier", "PromptVersion"},
			"disassociate-agent-collaborator":   {"AgentId", "AgentVersion", "CollaboratorId"},
			"disassociate-agent-knowledge-base": {"AgentId", "AgentVersion", "KnowledgeBaseId"},
			"get-agent":                         {"AgentId"},
			"get-agent-action-group":            {"ActionGroupId", "AgentId", "AgentVersion"},
			"get-agent-alias":                   {"AgentAliasId", "AgentId"},
			"get-agent-collaborator":            {"AgentId", "AgentVersion", "CollaboratorId"},
			"get-agent-knowledge-base":          {"AgentId", "AgentVersion", "KnowledgeBaseId"},
			"get-agent-version":                 {"AgentId", "AgentVersion"},
			"get-data-source":                   {"DataSourceId", "KnowledgeBaseId"},
			"get-flow":                          {"FlowIdentifier"},
			"get-flow-alias":                    {"AliasIdentifier", "FlowIdentifier"},
			"get-flow-version":                  {"FlowIdentifier", "FlowVersion"},
			"get-ingestion-job":                 {"DataSourceId", "IngestionJobId", "KnowledgeBaseId"},
			"get-knowledge-base":                {"KnowledgeBaseId"},
			"get-knowledge-base-documents":      {"DataSourceId", "DocumentIdentifiers", "KnowledgeBaseId"},
			"get-prompt":                        {"PromptIdentifier", "PromptVersion"},
			"ingest-knowledge-base-documents":   {"ClientToken", "DataSourceId", "Documents", "KnowledgeBaseId"},
			"list-agent-action-groups":          {"AgentId", "AgentVersion", "MaxResults", "NextToken"},
			"list-agent-aliases":                {"AgentId", "MaxResults", "NextToken"},
			"list-agent-collaborators":          {"AgentId", "AgentVersion", "MaxResults", "NextToken"},
			"list-agent-knowledge-bases":        {"AgentId", "AgentVersion", "MaxResults", "NextToken"},
			"list-agent-versions":               {"AgentId", "MaxResults", "NextToken"},
			"list-agents":                       {"MaxResults", "NextToken"},
			"list-data-sources":                 {"KnowledgeBaseId", "MaxResults", "NextToken"},
			"list-flow-aliases":                 {"FlowIdentifier", "MaxResults", "NextToken"},
			"list-flow-versions":                {"FlowIdentifier", "MaxResults", "NextToken"},
			"list-flows":                        {"MaxResults", "NextToken"},
			"list-ingestion-jobs":               {"DataSourceId", "Filters", "KnowledgeBaseId", "MaxResults", "NextToken", "SortBy"},
			"list-knowledge-base-documents":     {"DataSourceId", "KnowledgeBaseId", "MaxResults", "NextToken"},
			"list-knowledge-bases":              {"MaxResults", "NextToken"},
			"list-prompts":                      {"MaxResults", "NextToken", "PromptIdentifier"},
			"list-tags-for-resource":            {"ResourceArn"},
			"prepare-agent":                     {"AgentId"},
			"prepare-flow":                      {"FlowIdentifier"},
			"start-ingestion-job":               {"ClientToken", "DataSourceId", "Description", "KnowledgeBaseId"},
			"stop-ingestion-job":                {"DataSourceId", "IngestionJobId", "KnowledgeBaseId"},
			"tag-resource":                      {"ResourceArn", "Tags"},
			"untag-resource":                    {"ResourceArn", "TagKeys"},
			"update-agent":                      {"AgentCollaboration", "AgentId", "AgentName", "AgentResourceRoleArn", "CustomOrchestration", "CustomerEncryptionKeyArn", "Description", "FoundationModel", "GuardrailConfiguration", "IdleSessionTTLInSeconds", "Instruction", "MemoryConfiguration", "OrchestrationType", "PromptOverrideConfiguration"},
			"update-agent-action-group":         {"ActionGroupExecutor", "ActionGroupId", "ActionGroupName", "ActionGroupState", "AgentId", "AgentVersion", "ApiSchema", "Description", "FunctionSchema", "ParentActionGroupSignature", "ParentActionGroupSignatureParams"},
			"update-agent-alias":                {"AgentAliasId", "AgentAliasName", "AgentId", "AliasInvocationState", "Description", "RoutingConfiguration"},
			"update-agent-collaborator":         {"AgentDescriptor", "AgentId", "AgentVersion", "CollaborationInstruction", "CollaboratorId", "CollaboratorName", "RelayConversationHistory"},
			"update-agent-knowledge-base":       {"AgentId", "AgentVersion", "Description", "KnowledgeBaseId", "KnowledgeBaseState"},
			"update-data-source":                {"DataDeletionPolicy", "DataSourceConfiguration", "DataSourceId", "Description", "KnowledgeBaseId", "Name", "ServerSideEncryptionConfiguration", "VectorIngestionConfiguration"},
			"update-flow":                       {"CustomerEncryptionKeyArn", "Definition", "Description", "ExecutionRoleArn", "FlowIdentifier", "Name"},
			"update-flow-alias":                 {"AliasIdentifier", "ConcurrencyConfiguration", "Description", "FlowIdentifier", "Name", "RoutingConfiguration"},
			"update-knowledge-base":             {"Description", "KnowledgeBaseConfiguration", "KnowledgeBaseId", "Name", "RoleArn", "StorageConfiguration"},
			"update-prompt":                     {"CustomerEncryptionKeyArn", "DefaultVariant", "Description", "Name", "PromptIdentifier", "Variants"},
			"validate-flow-definition":          {"Definition"},
		},
		OperationInputTypes: map[string]map[string]string{
			"associate-agent-collaborator":      {"AgentDescriptor": "*types.AgentDescriptor", "AgentId": "*string", "AgentVersion": "*string", "ClientToken": "*string", "CollaborationInstruction": "*string", "CollaboratorName": "*string", "RelayConversationHistory": "types.RelayConversationHistory"},
			"associate-agent-knowledge-base":    {"AgentId": "*string", "AgentVersion": "*string", "Description": "*string", "KnowledgeBaseId": "*string", "KnowledgeBaseState": "types.KnowledgeBaseState"},
			"create-agent":                      {"AgentCollaboration": "types.AgentCollaboration", "AgentName": "*string", "AgentResourceRoleArn": "*string", "ClientToken": "*string", "CustomOrchestration": "*types.CustomOrchestration", "CustomerEncryptionKeyArn": "*string", "Description": "*string", "FoundationModel": "*string", "GuardrailConfiguration": "*types.GuardrailConfiguration", "IdleSessionTTLInSeconds": "*int32", "Instruction": "*string", "MemoryConfiguration": "*types.MemoryConfiguration", "OrchestrationType": "types.OrchestrationType", "PromptOverrideConfiguration": "*types.PromptOverrideConfiguration", "Tags": "map[string]string"},
			"create-agent-action-group":         {"ActionGroupExecutor": "types.ActionGroupExecutor", "ActionGroupName": "*string", "ActionGroupState": "types.ActionGroupState", "AgentId": "*string", "AgentVersion": "*string", "ApiSchema": "types.APISchema", "ClientToken": "*string", "Description": "*string", "FunctionSchema": "types.FunctionSchema", "ParentActionGroupSignature": "types.ActionGroupSignature", "ParentActionGroupSignatureParams": "map[string]string"},
			"create-agent-alias":                {"AgentAliasName": "*string", "AgentId": "*string", "ClientToken": "*string", "Description": "*string", "RoutingConfiguration": "[]types.AgentAliasRoutingConfigurationListItem", "Tags": "map[string]string"},
			"create-data-source":                {"ClientToken": "*string", "DataDeletionPolicy": "types.DataDeletionPolicy", "DataSourceConfiguration": "*types.DataSourceConfiguration", "Description": "*string", "KnowledgeBaseId": "*string", "Name": "*string", "ServerSideEncryptionConfiguration": "*types.ServerSideEncryptionConfiguration", "VectorIngestionConfiguration": "*types.VectorIngestionConfiguration"},
			"create-flow":                       {"ClientToken": "*string", "CustomerEncryptionKeyArn": "*string", "Definition": "*types.FlowDefinition", "Description": "*string", "ExecutionRoleArn": "*string", "Name": "*string", "Tags": "map[string]string"},
			"create-flow-alias":                 {"ClientToken": "*string", "ConcurrencyConfiguration": "*types.FlowAliasConcurrencyConfiguration", "Description": "*string", "FlowIdentifier": "*string", "Name": "*string", "RoutingConfiguration": "[]types.FlowAliasRoutingConfigurationListItem", "Tags": "map[string]string"},
			"create-flow-version":               {"ClientToken": "*string", "Description": "*string", "FlowIdentifier": "*string"},
			"create-knowledge-base":             {"ClientToken": "*string", "Description": "*string", "KnowledgeBaseConfiguration": "*types.KnowledgeBaseConfiguration", "Name": "*string", "RoleArn": "*string", "StorageConfiguration": "*types.StorageConfiguration", "Tags": "map[string]string"},
			"create-prompt":                     {"ClientToken": "*string", "CustomerEncryptionKeyArn": "*string", "DefaultVariant": "*string", "Description": "*string", "Name": "*string", "Tags": "map[string]string", "Variants": "[]types.PromptVariant"},
			"create-prompt-version":             {"ClientToken": "*string", "Description": "*string", "PromptIdentifier": "*string", "Tags": "map[string]string"},
			"delete-agent":                      {"AgentId": "*string", "SkipResourceInUseCheck": "bool"},
			"delete-agent-action-group":         {"ActionGroupId": "*string", "AgentId": "*string", "AgentVersion": "*string", "SkipResourceInUseCheck": "bool"},
			"delete-agent-alias":                {"AgentAliasId": "*string", "AgentId": "*string"},
			"delete-agent-version":              {"AgentId": "*string", "AgentVersion": "*string", "SkipResourceInUseCheck": "bool"},
			"delete-data-source":                {"DataSourceId": "*string", "KnowledgeBaseId": "*string"},
			"delete-flow":                       {"FlowIdentifier": "*string", "SkipResourceInUseCheck": "bool"},
			"delete-flow-alias":                 {"AliasIdentifier": "*string", "FlowIdentifier": "*string"},
			"delete-flow-version":               {"FlowIdentifier": "*string", "FlowVersion": "*string", "SkipResourceInUseCheck": "bool"},
			"delete-knowledge-base":             {"KnowledgeBaseId": "*string"},
			"delete-knowledge-base-documents":   {"ClientToken": "*string", "DataSourceId": "*string", "DocumentIdentifiers": "[]types.DocumentIdentifier", "KnowledgeBaseId": "*string"},
			"delete-prompt":                     {"PromptIdentifier": "*string", "PromptVersion": "*string"},
			"disassociate-agent-collaborator":   {"AgentId": "*string", "AgentVersion": "*string", "CollaboratorId": "*string"},
			"disassociate-agent-knowledge-base": {"AgentId": "*string", "AgentVersion": "*string", "KnowledgeBaseId": "*string"},
			"get-agent":                         {"AgentId": "*string"},
			"get-agent-action-group":            {"ActionGroupId": "*string", "AgentId": "*string", "AgentVersion": "*string"},
			"get-agent-alias":                   {"AgentAliasId": "*string", "AgentId": "*string"},
			"get-agent-collaborator":            {"AgentId": "*string", "AgentVersion": "*string", "CollaboratorId": "*string"},
			"get-agent-knowledge-base":          {"AgentId": "*string", "AgentVersion": "*string", "KnowledgeBaseId": "*string"},
			"get-agent-version":                 {"AgentId": "*string", "AgentVersion": "*string"},
			"get-data-source":                   {"DataSourceId": "*string", "KnowledgeBaseId": "*string"},
			"get-flow":                          {"FlowIdentifier": "*string"},
			"get-flow-alias":                    {"AliasIdentifier": "*string", "FlowIdentifier": "*string"},
			"get-flow-version":                  {"FlowIdentifier": "*string", "FlowVersion": "*string"},
			"get-ingestion-job":                 {"DataSourceId": "*string", "IngestionJobId": "*string", "KnowledgeBaseId": "*string"},
			"get-knowledge-base":                {"KnowledgeBaseId": "*string"},
			"get-knowledge-base-documents":      {"DataSourceId": "*string", "DocumentIdentifiers": "[]types.DocumentIdentifier", "KnowledgeBaseId": "*string"},
			"get-prompt":                        {"PromptIdentifier": "*string", "PromptVersion": "*string"},
			"ingest-knowledge-base-documents":   {"ClientToken": "*string", "DataSourceId": "*string", "Documents": "[]types.KnowledgeBaseDocument", "KnowledgeBaseId": "*string"},
			"list-agent-action-groups":          {"AgentId": "*string", "AgentVersion": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-agent-aliases":                {"AgentId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-agent-collaborators":          {"AgentId": "*string", "AgentVersion": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-agent-knowledge-bases":        {"AgentId": "*string", "AgentVersion": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-agent-versions":               {"AgentId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-agents":                       {"MaxResults": "*int32", "NextToken": "*string"},
			"list-data-sources":                 {"KnowledgeBaseId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-flow-aliases":                 {"FlowIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-flow-versions":                {"FlowIdentifier": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-flows":                        {"MaxResults": "*int32", "NextToken": "*string"},
			"list-ingestion-jobs":               {"DataSourceId": "*string", "Filters": "[]types.IngestionJobFilter", "KnowledgeBaseId": "*string", "MaxResults": "*int32", "NextToken": "*string", "SortBy": "*types.IngestionJobSortBy"},
			"list-knowledge-base-documents":     {"DataSourceId": "*string", "KnowledgeBaseId": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-knowledge-bases":              {"MaxResults": "*int32", "NextToken": "*string"},
			"list-prompts":                      {"MaxResults": "*int32", "NextToken": "*string", "PromptIdentifier": "*string"},
			"list-tags-for-resource":            {"ResourceArn": "*string"},
			"prepare-agent":                     {"AgentId": "*string"},
			"prepare-flow":                      {"FlowIdentifier": "*string"},
			"start-ingestion-job":               {"ClientToken": "*string", "DataSourceId": "*string", "Description": "*string", "KnowledgeBaseId": "*string"},
			"stop-ingestion-job":                {"DataSourceId": "*string", "IngestionJobId": "*string", "KnowledgeBaseId": "*string"},
			"tag-resource":                      {"ResourceArn": "*string", "Tags": "map[string]string"},
			"untag-resource":                    {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-agent":                      {"AgentCollaboration": "types.AgentCollaboration", "AgentId": "*string", "AgentName": "*string", "AgentResourceRoleArn": "*string", "CustomOrchestration": "*types.CustomOrchestration", "CustomerEncryptionKeyArn": "*string", "Description": "*string", "FoundationModel": "*string", "GuardrailConfiguration": "*types.GuardrailConfiguration", "IdleSessionTTLInSeconds": "*int32", "Instruction": "*string", "MemoryConfiguration": "*types.MemoryConfiguration", "OrchestrationType": "types.OrchestrationType", "PromptOverrideConfiguration": "*types.PromptOverrideConfiguration"},
			"update-agent-action-group":         {"ActionGroupExecutor": "types.ActionGroupExecutor", "ActionGroupId": "*string", "ActionGroupName": "*string", "ActionGroupState": "types.ActionGroupState", "AgentId": "*string", "AgentVersion": "*string", "ApiSchema": "types.APISchema", "Description": "*string", "FunctionSchema": "types.FunctionSchema", "ParentActionGroupSignature": "types.ActionGroupSignature", "ParentActionGroupSignatureParams": "map[string]string"},
			"update-agent-alias":                {"AgentAliasId": "*string", "AgentAliasName": "*string", "AgentId": "*string", "AliasInvocationState": "types.AliasInvocationState", "Description": "*string", "RoutingConfiguration": "[]types.AgentAliasRoutingConfigurationListItem"},
			"update-agent-collaborator":         {"AgentDescriptor": "*types.AgentDescriptor", "AgentId": "*string", "AgentVersion": "*string", "CollaborationInstruction": "*string", "CollaboratorId": "*string", "CollaboratorName": "*string", "RelayConversationHistory": "types.RelayConversationHistory"},
			"update-agent-knowledge-base":       {"AgentId": "*string", "AgentVersion": "*string", "Description": "*string", "KnowledgeBaseId": "*string", "KnowledgeBaseState": "types.KnowledgeBaseState"},
			"update-data-source":                {"DataDeletionPolicy": "types.DataDeletionPolicy", "DataSourceConfiguration": "*types.DataSourceConfiguration", "DataSourceId": "*string", "Description": "*string", "KnowledgeBaseId": "*string", "Name": "*string", "ServerSideEncryptionConfiguration": "*types.ServerSideEncryptionConfiguration", "VectorIngestionConfiguration": "*types.VectorIngestionConfiguration"},
			"update-flow":                       {"CustomerEncryptionKeyArn": "*string", "Definition": "*types.FlowDefinition", "Description": "*string", "ExecutionRoleArn": "*string", "FlowIdentifier": "*string", "Name": "*string"},
			"update-flow-alias":                 {"AliasIdentifier": "*string", "ConcurrencyConfiguration": "*types.FlowAliasConcurrencyConfiguration", "Description": "*string", "FlowIdentifier": "*string", "Name": "*string", "RoutingConfiguration": "[]types.FlowAliasRoutingConfigurationListItem"},
			"update-knowledge-base":             {"Description": "*string", "KnowledgeBaseConfiguration": "*types.KnowledgeBaseConfiguration", "KnowledgeBaseId": "*string", "Name": "*string", "RoleArn": "*string", "StorageConfiguration": "*types.StorageConfiguration"},
			"update-prompt":                     {"CustomerEncryptionKeyArn": "*string", "DefaultVariant": "*string", "Description": "*string", "Name": "*string", "PromptIdentifier": "*string", "Variants": "[]types.PromptVariant"},
			"validate-flow-definition":          {"Definition": "*types.FlowDefinition"},
		},
		OperationInputRequired: map[string][]string{
			"associate-agent-collaborator":      {"AgentDescriptor", "AgentId", "AgentVersion", "CollaborationInstruction", "CollaboratorName"},
			"associate-agent-knowledge-base":    {"AgentId", "AgentVersion", "Description", "KnowledgeBaseId"},
			"create-agent":                      {"AgentName"},
			"create-agent-action-group":         {"ActionGroupName", "AgentId", "AgentVersion"},
			"create-agent-alias":                {"AgentAliasName", "AgentId"},
			"create-data-source":                {"DataSourceConfiguration", "KnowledgeBaseId", "Name"},
			"create-flow":                       {"ExecutionRoleArn", "Name"},
			"create-flow-alias":                 {"FlowIdentifier", "Name", "RoutingConfiguration"},
			"create-flow-version":               {"FlowIdentifier"},
			"create-knowledge-base":             {"KnowledgeBaseConfiguration", "Name", "RoleArn"},
			"create-prompt":                     {"Name"},
			"create-prompt-version":             {"PromptIdentifier"},
			"delete-agent":                      {"AgentId"},
			"delete-agent-action-group":         {"ActionGroupId", "AgentId", "AgentVersion"},
			"delete-agent-alias":                {"AgentAliasId", "AgentId"},
			"delete-agent-version":              {"AgentId", "AgentVersion"},
			"delete-data-source":                {"DataSourceId", "KnowledgeBaseId"},
			"delete-flow":                       {"FlowIdentifier"},
			"delete-flow-alias":                 {"AliasIdentifier", "FlowIdentifier"},
			"delete-flow-version":               {"FlowIdentifier", "FlowVersion"},
			"delete-knowledge-base":             {"KnowledgeBaseId"},
			"delete-knowledge-base-documents":   {"DataSourceId", "DocumentIdentifiers", "KnowledgeBaseId"},
			"delete-prompt":                     {"PromptIdentifier"},
			"disassociate-agent-collaborator":   {"AgentId", "AgentVersion", "CollaboratorId"},
			"disassociate-agent-knowledge-base": {"AgentId", "AgentVersion", "KnowledgeBaseId"},
			"get-agent":                         {"AgentId"},
			"get-agent-action-group":            {"ActionGroupId", "AgentId", "AgentVersion"},
			"get-agent-alias":                   {"AgentAliasId", "AgentId"},
			"get-agent-collaborator":            {"AgentId", "AgentVersion", "CollaboratorId"},
			"get-agent-knowledge-base":          {"AgentId", "AgentVersion", "KnowledgeBaseId"},
			"get-agent-version":                 {"AgentId", "AgentVersion"},
			"get-data-source":                   {"DataSourceId", "KnowledgeBaseId"},
			"get-flow":                          {"FlowIdentifier"},
			"get-flow-alias":                    {"AliasIdentifier", "FlowIdentifier"},
			"get-flow-version":                  {"FlowIdentifier", "FlowVersion"},
			"get-ingestion-job":                 {"DataSourceId", "IngestionJobId", "KnowledgeBaseId"},
			"get-knowledge-base":                {"KnowledgeBaseId"},
			"get-knowledge-base-documents":      {"DataSourceId", "DocumentIdentifiers", "KnowledgeBaseId"},
			"get-prompt":                        {"PromptIdentifier"},
			"ingest-knowledge-base-documents":   {"DataSourceId", "Documents", "KnowledgeBaseId"},
			"list-agent-action-groups":          {"AgentId", "AgentVersion"},
			"list-agent-aliases":                {"AgentId"},
			"list-agent-collaborators":          {"AgentId", "AgentVersion"},
			"list-agent-knowledge-bases":        {"AgentId", "AgentVersion"},
			"list-agent-versions":               {"AgentId"},
			"list-agents":                       {},
			"list-data-sources":                 {"KnowledgeBaseId"},
			"list-flow-aliases":                 {"FlowIdentifier"},
			"list-flow-versions":                {"FlowIdentifier"},
			"list-flows":                        {},
			"list-ingestion-jobs":               {"DataSourceId", "KnowledgeBaseId"},
			"list-knowledge-base-documents":     {"DataSourceId", "KnowledgeBaseId"},
			"list-knowledge-bases":              {},
			"list-prompts":                      {},
			"list-tags-for-resource":            {"ResourceArn"},
			"prepare-agent":                     {"AgentId"},
			"prepare-flow":                      {"FlowIdentifier"},
			"start-ingestion-job":               {"DataSourceId", "KnowledgeBaseId"},
			"stop-ingestion-job":                {"DataSourceId", "IngestionJobId", "KnowledgeBaseId"},
			"tag-resource":                      {"ResourceArn", "Tags"},
			"untag-resource":                    {"ResourceArn", "TagKeys"},
			"update-agent":                      {"AgentId", "AgentName", "AgentResourceRoleArn", "FoundationModel"},
			"update-agent-action-group":         {"ActionGroupId", "ActionGroupName", "AgentId", "AgentVersion"},
			"update-agent-alias":                {"AgentAliasId", "AgentAliasName", "AgentId"},
			"update-agent-collaborator":         {"AgentDescriptor", "AgentId", "AgentVersion", "CollaborationInstruction", "CollaboratorId", "CollaboratorName"},
			"update-agent-knowledge-base":       {"AgentId", "AgentVersion", "KnowledgeBaseId"},
			"update-data-source":                {"DataSourceConfiguration", "DataSourceId", "KnowledgeBaseId", "Name"},
			"update-flow":                       {"ExecutionRoleArn", "FlowIdentifier", "Name"},
			"update-flow-alias":                 {"AliasIdentifier", "FlowIdentifier", "Name", "RoutingConfiguration"},
			"update-knowledge-base":             {"KnowledgeBaseConfiguration", "KnowledgeBaseId", "Name", "RoleArn"},
			"update-prompt":                     {"Name", "PromptIdentifier"},
			"validate-flow-definition":          {"Definition"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("bedrockagent", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
