package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/sfn/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"create-activity", "create-state-machine", "create-state-machine-alias", "delete-activity", "delete-state-machine", "delete-state-machine-alias", "delete-state-machine-version", "describe-activity", "describe-execution", "describe-map-run", "describe-state-machine", "describe-state-machine-alias", "describe-state-machine-for-execution", "get-activity-task", "get-execution-history", "list-activities", "list-executions", "list-map-runs", "list-state-machine-aliases", "list-state-machine-versions", "list-state-machines", "list-tags-for-resource", "publish-state-machine-version", "redrive-execution", "send-task-failure", "send-task-heartbeat", "send-task-success", "start-execution", "start-sync-execution", "stop-execution", "tag-resource", "test-state", "untag-resource", "update-map-run", "update-state-machine", "update-state-machine-alias", "validate-state-machine-definition"},
		OperationSet: map[string]bool{"create-activity": true, "create-state-machine": true, "create-state-machine-alias": true, "delete-activity": true, "delete-state-machine": true, "delete-state-machine-alias": true, "delete-state-machine-version": true, "describe-activity": true, "describe-execution": true, "describe-map-run": true, "describe-state-machine": true, "describe-state-machine-alias": true, "describe-state-machine-for-execution": true, "get-activity-task": true, "get-execution-history": true, "list-activities": true, "list-executions": true, "list-map-runs": true, "list-state-machine-aliases": true, "list-state-machine-versions": true, "list-state-machines": true, "list-tags-for-resource": true, "publish-state-machine-version": true, "redrive-execution": true, "send-task-failure": true, "send-task-heartbeat": true, "send-task-success": true, "start-execution": true, "start-sync-execution": true, "stop-execution": true, "tag-resource": true, "test-state": true, "untag-resource": true, "update-map-run": true, "update-state-machine": true, "update-state-machine-alias": true, "validate-state-machine-definition": true},
		OperationInputs: map[string][]string{
			"create-activity":                      {"EncryptionConfiguration", "Name", "Tags"},
			"create-state-machine":                 {"Definition", "EncryptionConfiguration", "LoggingConfiguration", "Name", "Publish", "RoleArn", "Tags", "TracingConfiguration", "Type", "VersionDescription"},
			"create-state-machine-alias":           {"Description", "Name", "RoutingConfiguration"},
			"delete-activity":                      {"ActivityArn"},
			"delete-state-machine":                 {"StateMachineArn"},
			"delete-state-machine-alias":           {"StateMachineAliasArn"},
			"delete-state-machine-version":         {"StateMachineVersionArn"},
			"describe-activity":                    {"ActivityArn"},
			"describe-execution":                   {"ExecutionArn", "IncludedData"},
			"describe-map-run":                     {"MapRunArn"},
			"describe-state-machine":               {"IncludedData", "StateMachineArn"},
			"describe-state-machine-alias":         {"StateMachineAliasArn"},
			"describe-state-machine-for-execution": {"ExecutionArn", "IncludedData"},
			"get-activity-task":                    {"ActivityArn", "WorkerName"},
			"get-execution-history":                {"ExecutionArn", "IncludeExecutionData", "MaxResults", "NextToken", "ReverseOrder"},
			"list-activities":                      {"MaxResults", "NextToken"},
			"list-executions":                      {"MapRunArn", "MaxResults", "NextToken", "RedriveFilter", "StateMachineArn", "StatusFilter"},
			"list-map-runs":                        {"ExecutionArn", "MaxResults", "NextToken"},
			"list-state-machine-aliases":           {"MaxResults", "NextToken", "StateMachineArn"},
			"list-state-machine-versions":          {"MaxResults", "NextToken", "StateMachineArn"},
			"list-state-machines":                  {"MaxResults", "NextToken"},
			"list-tags-for-resource":               {"ResourceArn"},
			"publish-state-machine-version":        {"Description", "RevisionId", "StateMachineArn"},
			"redrive-execution":                    {"ClientToken", "ExecutionArn"},
			"send-task-failure":                    {"Cause", "Error", "TaskToken"},
			"send-task-heartbeat":                  {"TaskToken"},
			"send-task-success":                    {"Output", "TaskToken"},
			"start-execution":                      {"Input", "Name", "StateMachineArn", "TraceHeader"},
			"start-sync-execution":                 {"IncludedData", "Input", "Name", "StateMachineArn", "TraceHeader"},
			"stop-execution":                       {"Cause", "Error", "ExecutionArn"},
			"tag-resource":                         {"ResourceArn", "Tags"},
			"test-state":                           {"Context", "Definition", "Input", "InspectionLevel", "Mock", "RevealSecrets", "RoleArn", "StateConfiguration", "StateName", "Variables"},
			"untag-resource":                       {"ResourceArn", "TagKeys"},
			"update-map-run":                       {"MapRunArn", "MaxConcurrency", "ToleratedFailureCount", "ToleratedFailurePercentage"},
			"update-state-machine":                 {"Definition", "EncryptionConfiguration", "LoggingConfiguration", "Publish", "RoleArn", "StateMachineArn", "TracingConfiguration", "VersionDescription"},
			"update-state-machine-alias":           {"Description", "RoutingConfiguration", "StateMachineAliasArn"},
			"validate-state-machine-definition":    {"Definition", "MaxResults", "Severity", "Type"},
		},
		OperationInputTypes: map[string]map[string]string{
			"create-activity":                      {"EncryptionConfiguration": "*types.EncryptionConfiguration", "Name": "*string", "Tags": "[]types.Tag"},
			"create-state-machine":                 {"Definition": "*string", "EncryptionConfiguration": "*types.EncryptionConfiguration", "LoggingConfiguration": "*types.LoggingConfiguration", "Name": "*string", "Publish": "bool", "RoleArn": "*string", "Tags": "[]types.Tag", "TracingConfiguration": "*types.TracingConfiguration", "Type": "types.StateMachineType", "VersionDescription": "*string"},
			"create-state-machine-alias":           {"Description": "*string", "Name": "*string", "RoutingConfiguration": "[]types.RoutingConfigurationListItem"},
			"delete-activity":                      {"ActivityArn": "*string"},
			"delete-state-machine":                 {"StateMachineArn": "*string"},
			"delete-state-machine-alias":           {"StateMachineAliasArn": "*string"},
			"delete-state-machine-version":         {"StateMachineVersionArn": "*string"},
			"describe-activity":                    {"ActivityArn": "*string"},
			"describe-execution":                   {"ExecutionArn": "*string", "IncludedData": "types.IncludedData"},
			"describe-map-run":                     {"MapRunArn": "*string"},
			"describe-state-machine":               {"IncludedData": "types.IncludedData", "StateMachineArn": "*string"},
			"describe-state-machine-alias":         {"StateMachineAliasArn": "*string"},
			"describe-state-machine-for-execution": {"ExecutionArn": "*string", "IncludedData": "types.IncludedData"},
			"get-activity-task":                    {"ActivityArn": "*string", "WorkerName": "*string"},
			"get-execution-history":                {"ExecutionArn": "*string", "IncludeExecutionData": "*bool", "MaxResults": "int32", "NextToken": "*string", "ReverseOrder": "bool"},
			"list-activities":                      {"MaxResults": "int32", "NextToken": "*string"},
			"list-executions":                      {"MapRunArn": "*string", "MaxResults": "int32", "NextToken": "*string", "RedriveFilter": "types.ExecutionRedriveFilter", "StateMachineArn": "*string", "StatusFilter": "types.ExecutionStatus"},
			"list-map-runs":                        {"ExecutionArn": "*string", "MaxResults": "int32", "NextToken": "*string"},
			"list-state-machine-aliases":           {"MaxResults": "int32", "NextToken": "*string", "StateMachineArn": "*string"},
			"list-state-machine-versions":          {"MaxResults": "int32", "NextToken": "*string", "StateMachineArn": "*string"},
			"list-state-machines":                  {"MaxResults": "int32", "NextToken": "*string"},
			"list-tags-for-resource":               {"ResourceArn": "*string"},
			"publish-state-machine-version":        {"Description": "*string", "RevisionId": "*string", "StateMachineArn": "*string"},
			"redrive-execution":                    {"ClientToken": "*string", "ExecutionArn": "*string"},
			"send-task-failure":                    {"Cause": "*string", "Error": "*string", "TaskToken": "*string"},
			"send-task-heartbeat":                  {"TaskToken": "*string"},
			"send-task-success":                    {"Output": "*string", "TaskToken": "*string"},
			"start-execution":                      {"Input": "*string", "Name": "*string", "StateMachineArn": "*string", "TraceHeader": "*string"},
			"start-sync-execution":                 {"IncludedData": "types.IncludedData", "Input": "*string", "Name": "*string", "StateMachineArn": "*string", "TraceHeader": "*string"},
			"stop-execution":                       {"Cause": "*string", "Error": "*string", "ExecutionArn": "*string"},
			"tag-resource":                         {"ResourceArn": "*string", "Tags": "[]types.Tag"},
			"test-state":                           {"Context": "*string", "Definition": "*string", "Input": "*string", "InspectionLevel": "types.InspectionLevel", "Mock": "*types.MockInput", "RevealSecrets": "bool", "RoleArn": "*string", "StateConfiguration": "*types.TestStateConfiguration", "StateName": "*string", "Variables": "*string"},
			"untag-resource":                       {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-map-run":                       {"MapRunArn": "*string", "MaxConcurrency": "*int32", "ToleratedFailureCount": "*int64", "ToleratedFailurePercentage": "*float32"},
			"update-state-machine":                 {"Definition": "*string", "EncryptionConfiguration": "*types.EncryptionConfiguration", "LoggingConfiguration": "*types.LoggingConfiguration", "Publish": "bool", "RoleArn": "*string", "StateMachineArn": "*string", "TracingConfiguration": "*types.TracingConfiguration", "VersionDescription": "*string"},
			"update-state-machine-alias":           {"Description": "*string", "RoutingConfiguration": "[]types.RoutingConfigurationListItem", "StateMachineAliasArn": "*string"},
			"validate-state-machine-definition":    {"Definition": "*string", "MaxResults": "int32", "Severity": "types.ValidateStateMachineDefinitionSeverity", "Type": "types.StateMachineType"},
		},
		OperationInputRequired: map[string][]string{
			"create-activity":                      {"Name"},
			"create-state-machine":                 {"Definition", "Name", "RoleArn"},
			"create-state-machine-alias":           {"Name", "RoutingConfiguration"},
			"delete-activity":                      {"ActivityArn"},
			"delete-state-machine":                 {"StateMachineArn"},
			"delete-state-machine-alias":           {"StateMachineAliasArn"},
			"delete-state-machine-version":         {"StateMachineVersionArn"},
			"describe-activity":                    {"ActivityArn"},
			"describe-execution":                   {"ExecutionArn"},
			"describe-map-run":                     {"MapRunArn"},
			"describe-state-machine":               {"StateMachineArn"},
			"describe-state-machine-alias":         {"StateMachineAliasArn"},
			"describe-state-machine-for-execution": {"ExecutionArn"},
			"get-activity-task":                    {"ActivityArn"},
			"get-execution-history":                {"ExecutionArn"},
			"list-activities":                      {},
			"list-executions":                      {},
			"list-map-runs":                        {"ExecutionArn"},
			"list-state-machine-aliases":           {"StateMachineArn"},
			"list-state-machine-versions":          {"StateMachineArn"},
			"list-state-machines":                  {},
			"list-tags-for-resource":               {"ResourceArn"},
			"publish-state-machine-version":        {"StateMachineArn"},
			"redrive-execution":                    {"ExecutionArn"},
			"send-task-failure":                    {"TaskToken"},
			"send-task-heartbeat":                  {"TaskToken"},
			"send-task-success":                    {"Output", "TaskToken"},
			"start-execution":                      {"StateMachineArn"},
			"start-sync-execution":                 {"StateMachineArn"},
			"stop-execution":                       {"ExecutionArn"},
			"tag-resource":                         {"ResourceArn", "Tags"},
			"test-state":                           {"Definition"},
			"untag-resource":                       {"ResourceArn", "TagKeys"},
			"update-map-run":                       {"MapRunArn"},
			"update-state-machine":                 {"StateMachineArn"},
			"update-state-machine-alias":           {"StateMachineAliasArn"},
			"validate-state-machine-definition":    {"Definition"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("sfn", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
