package main

import (
	"fmt"
	"os"

	runtime "aws/awsgo/svcruntime"
	servicecmd "aws/generated/mediaconnect/cmd"
)

func main() {
	svc := runtime.ServiceDef{
		Operations:   []string{"add-bridge-outputs", "add-bridge-sources", "add-flow-media-streams", "add-flow-outputs", "add-flow-sources", "add-flow-vpc-interfaces", "batch-get-router-input", "batch-get-router-network-interface", "batch-get-router-output", "create-bridge", "create-flow", "create-gateway", "create-router-input", "create-router-network-interface", "create-router-output", "delete-bridge", "delete-flow", "delete-gateway", "delete-router-input", "delete-router-network-interface", "delete-router-output", "deregister-gateway-instance", "describe-bridge", "describe-flow", "describe-flow-source-metadata", "describe-flow-source-thumbnail", "describe-gateway", "describe-gateway-instance", "describe-offering", "describe-reservation", "get-router-input", "get-router-input-source-metadata", "get-router-input-thumbnail", "get-router-network-interface", "get-router-output", "grant-flow-entitlements", "list-bridges", "list-entitlements", "list-flows", "list-gateway-instances", "list-gateways", "list-offerings", "list-reservations", "list-router-inputs", "list-router-network-interfaces", "list-router-outputs", "list-tags-for-global-resource", "list-tags-for-resource", "purchase-offering", "remove-bridge-output", "remove-bridge-source", "remove-flow-media-stream", "remove-flow-output", "remove-flow-source", "remove-flow-vpc-interface", "restart-router-input", "restart-router-output", "revoke-flow-entitlement", "start-flow", "start-router-input", "start-router-output", "stop-flow", "stop-router-input", "stop-router-output", "tag-global-resource", "tag-resource", "take-router-input", "untag-global-resource", "untag-resource", "update-bridge", "update-bridge-output", "update-bridge-source", "update-bridge-state", "update-flow", "update-flow-entitlement", "update-flow-media-stream", "update-flow-output", "update-flow-source", "update-gateway-instance", "update-router-input", "update-router-network-interface", "update-router-output"},
		OperationSet: map[string]bool{"add-bridge-outputs": true, "add-bridge-sources": true, "add-flow-media-streams": true, "add-flow-outputs": true, "add-flow-sources": true, "add-flow-vpc-interfaces": true, "batch-get-router-input": true, "batch-get-router-network-interface": true, "batch-get-router-output": true, "create-bridge": true, "create-flow": true, "create-gateway": true, "create-router-input": true, "create-router-network-interface": true, "create-router-output": true, "delete-bridge": true, "delete-flow": true, "delete-gateway": true, "delete-router-input": true, "delete-router-network-interface": true, "delete-router-output": true, "deregister-gateway-instance": true, "describe-bridge": true, "describe-flow": true, "describe-flow-source-metadata": true, "describe-flow-source-thumbnail": true, "describe-gateway": true, "describe-gateway-instance": true, "describe-offering": true, "describe-reservation": true, "get-router-input": true, "get-router-input-source-metadata": true, "get-router-input-thumbnail": true, "get-router-network-interface": true, "get-router-output": true, "grant-flow-entitlements": true, "list-bridges": true, "list-entitlements": true, "list-flows": true, "list-gateway-instances": true, "list-gateways": true, "list-offerings": true, "list-reservations": true, "list-router-inputs": true, "list-router-network-interfaces": true, "list-router-outputs": true, "list-tags-for-global-resource": true, "list-tags-for-resource": true, "purchase-offering": true, "remove-bridge-output": true, "remove-bridge-source": true, "remove-flow-media-stream": true, "remove-flow-output": true, "remove-flow-source": true, "remove-flow-vpc-interface": true, "restart-router-input": true, "restart-router-output": true, "revoke-flow-entitlement": true, "start-flow": true, "start-router-input": true, "start-router-output": true, "stop-flow": true, "stop-router-input": true, "stop-router-output": true, "tag-global-resource": true, "tag-resource": true, "take-router-input": true, "untag-global-resource": true, "untag-resource": true, "update-bridge": true, "update-bridge-output": true, "update-bridge-source": true, "update-bridge-state": true, "update-flow": true, "update-flow-entitlement": true, "update-flow-media-stream": true, "update-flow-output": true, "update-flow-source": true, "update-gateway-instance": true, "update-router-input": true, "update-router-network-interface": true, "update-router-output": true},
		OperationInputs: map[string][]string{
			"add-bridge-outputs":                 {"BridgeArn", "Outputs"},
			"add-bridge-sources":                 {"BridgeArn", "Sources"},
			"add-flow-media-streams":             {"FlowArn", "MediaStreams"},
			"add-flow-outputs":                   {"FlowArn", "Outputs"},
			"add-flow-sources":                   {"FlowArn", "Sources"},
			"add-flow-vpc-interfaces":            {"FlowArn", "VpcInterfaces"},
			"batch-get-router-input":             {"Arns"},
			"batch-get-router-network-interface": {"Arns"},
			"batch-get-router-output":            {"Arns"},
			"create-bridge":                      {"EgressGatewayBridge", "IngressGatewayBridge", "Name", "Outputs", "PlacementArn", "SourceFailoverConfig", "Sources"},
			"create-flow":                        {"AvailabilityZone", "EncodingConfig", "Entitlements", "FlowSize", "FlowTags", "Maintenance", "MediaStreams", "Name", "NdiConfig", "Outputs", "Source", "SourceFailoverConfig", "SourceMonitoringConfig", "Sources", "VpcInterfaces"},
			"create-gateway":                     {"EgressCidrBlocks", "Name", "Networks"},
			"create-router-input":                {"AvailabilityZone", "ClientToken", "Configuration", "MaintenanceConfiguration", "MaximumBitrate", "Name", "RegionName", "RoutingScope", "Tags", "Tier", "TransitEncryption"},
			"create-router-network-interface":    {"ClientToken", "Configuration", "Name", "RegionName", "Tags"},
			"create-router-output":               {"AvailabilityZone", "ClientToken", "Configuration", "MaintenanceConfiguration", "MaximumBitrate", "Name", "RegionName", "RoutingScope", "Tags", "Tier"},
			"delete-bridge":                      {"BridgeArn"},
			"delete-flow":                        {"FlowArn"},
			"delete-gateway":                     {"GatewayArn"},
			"delete-router-input":                {"Arn"},
			"delete-router-network-interface":    {"Arn"},
			"delete-router-output":               {"Arn"},
			"deregister-gateway-instance":        {"Force", "GatewayInstanceArn"},
			"describe-bridge":                    {"BridgeArn"},
			"describe-flow":                      {"FlowArn"},
			"describe-flow-source-metadata":      {"FlowArn"},
			"describe-flow-source-thumbnail":     {"FlowArn"},
			"describe-gateway":                   {"GatewayArn"},
			"describe-gateway-instance":          {"GatewayInstanceArn"},
			"describe-offering":                  {"OfferingArn"},
			"describe-reservation":               {"ReservationArn"},
			"get-router-input":                   {"Arn"},
			"get-router-input-source-metadata":   {"Arn"},
			"get-router-input-thumbnail":         {"Arn"},
			"get-router-network-interface":       {"Arn"},
			"get-router-output":                  {"Arn"},
			"grant-flow-entitlements":            {"Entitlements", "FlowArn"},
			"list-bridges":                       {"FilterArn", "MaxResults", "NextToken"},
			"list-entitlements":                  {"MaxResults", "NextToken"},
			"list-flows":                         {"MaxResults", "NextToken"},
			"list-gateway-instances":             {"FilterArn", "MaxResults", "NextToken"},
			"list-gateways":                      {"MaxResults", "NextToken"},
			"list-offerings":                     {"MaxResults", "NextToken"},
			"list-reservations":                  {"MaxResults", "NextToken"},
			"list-router-inputs":                 {"Filters", "MaxResults", "NextToken"},
			"list-router-network-interfaces":     {"Filters", "MaxResults", "NextToken"},
			"list-router-outputs":                {"Filters", "MaxResults", "NextToken"},
			"list-tags-for-global-resource":      {"ResourceArn"},
			"list-tags-for-resource":             {"ResourceArn"},
			"purchase-offering":                  {"OfferingArn", "ReservationName", "Start"},
			"remove-bridge-output":               {"BridgeArn", "OutputName"},
			"remove-bridge-source":               {"BridgeArn", "SourceName"},
			"remove-flow-media-stream":           {"FlowArn", "MediaStreamName"},
			"remove-flow-output":                 {"FlowArn", "OutputArn"},
			"remove-flow-source":                 {"FlowArn", "SourceArn"},
			"remove-flow-vpc-interface":          {"FlowArn", "VpcInterfaceName"},
			"restart-router-input":               {"Arn"},
			"restart-router-output":              {"Arn"},
			"revoke-flow-entitlement":            {"EntitlementArn", "FlowArn"},
			"start-flow":                         {"FlowArn"},
			"start-router-input":                 {"Arn"},
			"start-router-output":                {"Arn"},
			"stop-flow":                          {"FlowArn"},
			"stop-router-input":                  {"Arn"},
			"stop-router-output":                 {"Arn"},
			"tag-global-resource":                {"ResourceArn", "Tags"},
			"tag-resource":                       {"ResourceArn", "Tags"},
			"take-router-input":                  {"RouterInputArn", "RouterOutputArn"},
			"untag-global-resource":              {"ResourceArn", "TagKeys"},
			"untag-resource":                     {"ResourceArn", "TagKeys"},
			"update-bridge":                      {"BridgeArn", "EgressGatewayBridge", "IngressGatewayBridge", "SourceFailoverConfig"},
			"update-bridge-output":               {"BridgeArn", "NetworkOutput", "OutputName"},
			"update-bridge-source":               {"BridgeArn", "FlowSource", "NetworkSource", "SourceName"},
			"update-bridge-state":                {"BridgeArn", "DesiredState"},
			"update-flow":                        {"EncodingConfig", "FlowArn", "FlowSize", "Maintenance", "NdiConfig", "SourceFailoverConfig", "SourceMonitoringConfig"},
			"update-flow-entitlement":            {"Description", "Encryption", "EntitlementArn", "EntitlementStatus", "FlowArn", "Subscribers"},
			"update-flow-media-stream":           {"Attributes", "ClockRate", "Description", "FlowArn", "MediaStreamName", "MediaStreamType", "VideoFormat"},
			"update-flow-output":                 {"CidrAllowList", "Description", "Destination", "Encryption", "FlowArn", "MaxLatency", "MediaStreamOutputConfigurations", "MinLatency", "NdiProgramName", "NdiSpeedHqQuality", "OutputArn", "OutputStatus", "Port", "Protocol", "RemoteId", "RouterIntegrationState", "RouterIntegrationTransitEncryption", "SenderControlPort", "SenderIpAddress", "SmoothingLatency", "StreamId", "VpcInterfaceAttachment"},
			"update-flow-source":                 {"Decryption", "Description", "EntitlementArn", "FlowArn", "GatewayBridgeSource", "IngestPort", "MaxBitrate", "MaxLatency", "MaxSyncBuffer", "MediaStreamSourceConfigurations", "MinLatency", "NdiSourceSettings", "Protocol", "RouterIntegrationState", "RouterIntegrationTransitDecryption", "SenderControlPort", "SenderIpAddress", "SourceArn", "SourceListenerAddress", "SourceListenerPort", "StreamId", "VpcInterfaceName", "WhitelistCidr"},
			"update-gateway-instance":            {"BridgePlacement", "GatewayInstanceArn"},
			"update-router-input":                {"Arn", "Configuration", "MaintenanceConfiguration", "MaximumBitrate", "Name", "RoutingScope", "Tier", "TransitEncryption"},
			"update-router-network-interface":    {"Arn", "Configuration", "Name"},
			"update-router-output":               {"Arn", "Configuration", "MaintenanceConfiguration", "MaximumBitrate", "Name", "RoutingScope", "Tier"},
		},
		OperationInputTypes: map[string]map[string]string{
			"add-bridge-outputs":                 {"BridgeArn": "*string", "Outputs": "[]types.AddBridgeOutputRequest"},
			"add-bridge-sources":                 {"BridgeArn": "*string", "Sources": "[]types.AddBridgeSourceRequest"},
			"add-flow-media-streams":             {"FlowArn": "*string", "MediaStreams": "[]types.AddMediaStreamRequest"},
			"add-flow-outputs":                   {"FlowArn": "*string", "Outputs": "[]types.AddOutputRequest"},
			"add-flow-sources":                   {"FlowArn": "*string", "Sources": "[]types.SetSourceRequest"},
			"add-flow-vpc-interfaces":            {"FlowArn": "*string", "VpcInterfaces": "[]types.VpcInterfaceRequest"},
			"batch-get-router-input":             {"Arns": "[]string"},
			"batch-get-router-network-interface": {"Arns": "[]string"},
			"batch-get-router-output":            {"Arns": "[]string"},
			"create-bridge":                      {"EgressGatewayBridge": "*types.AddEgressGatewayBridgeRequest", "IngressGatewayBridge": "*types.AddIngressGatewayBridgeRequest", "Name": "*string", "Outputs": "[]types.AddBridgeOutputRequest", "PlacementArn": "*string", "SourceFailoverConfig": "*types.FailoverConfig", "Sources": "[]types.AddBridgeSourceRequest"},
			"create-flow":                        {"AvailabilityZone": "*string", "EncodingConfig": "*types.EncodingConfig", "Entitlements": "[]types.GrantEntitlementRequest", "FlowSize": "types.FlowSize", "FlowTags": "map[string]string", "Maintenance": "*types.AddMaintenance", "MediaStreams": "[]types.AddMediaStreamRequest", "Name": "*string", "NdiConfig": "*types.NdiConfig", "Outputs": "[]types.AddOutputRequest", "Source": "*types.SetSourceRequest", "SourceFailoverConfig": "*types.FailoverConfig", "SourceMonitoringConfig": "*types.MonitoringConfig", "Sources": "[]types.SetSourceRequest", "VpcInterfaces": "[]types.VpcInterfaceRequest"},
			"create-gateway":                     {"EgressCidrBlocks": "[]string", "Name": "*string", "Networks": "[]types.GatewayNetwork"},
			"create-router-input":                {"AvailabilityZone": "*string", "ClientToken": "*string", "Configuration": "types.RouterInputConfiguration", "MaintenanceConfiguration": "types.MaintenanceConfiguration", "MaximumBitrate": "*int64", "Name": "*string", "RegionName": "*string", "RoutingScope": "types.RoutingScope", "Tags": "map[string]string", "Tier": "types.RouterInputTier", "TransitEncryption": "*types.RouterInputTransitEncryption"},
			"create-router-network-interface":    {"ClientToken": "*string", "Configuration": "types.RouterNetworkInterfaceConfiguration", "Name": "*string", "RegionName": "*string", "Tags": "map[string]string"},
			"create-router-output":               {"AvailabilityZone": "*string", "ClientToken": "*string", "Configuration": "types.RouterOutputConfiguration", "MaintenanceConfiguration": "types.MaintenanceConfiguration", "MaximumBitrate": "*int64", "Name": "*string", "RegionName": "*string", "RoutingScope": "types.RoutingScope", "Tags": "map[string]string", "Tier": "types.RouterOutputTier"},
			"delete-bridge":                      {"BridgeArn": "*string"},
			"delete-flow":                        {"FlowArn": "*string"},
			"delete-gateway":                     {"GatewayArn": "*string"},
			"delete-router-input":                {"Arn": "*string"},
			"delete-router-network-interface":    {"Arn": "*string"},
			"delete-router-output":               {"Arn": "*string"},
			"deregister-gateway-instance":        {"Force": "*bool", "GatewayInstanceArn": "*string"},
			"describe-bridge":                    {"BridgeArn": "*string"},
			"describe-flow":                      {"FlowArn": "*string"},
			"describe-flow-source-metadata":      {"FlowArn": "*string"},
			"describe-flow-source-thumbnail":     {"FlowArn": "*string"},
			"describe-gateway":                   {"GatewayArn": "*string"},
			"describe-gateway-instance":          {"GatewayInstanceArn": "*string"},
			"describe-offering":                  {"OfferingArn": "*string"},
			"describe-reservation":               {"ReservationArn": "*string"},
			"get-router-input":                   {"Arn": "*string"},
			"get-router-input-source-metadata":   {"Arn": "*string"},
			"get-router-input-thumbnail":         {"Arn": "*string"},
			"get-router-network-interface":       {"Arn": "*string"},
			"get-router-output":                  {"Arn": "*string"},
			"grant-flow-entitlements":            {"Entitlements": "[]types.GrantEntitlementRequest", "FlowArn": "*string"},
			"list-bridges":                       {"FilterArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-entitlements":                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-flows":                         {"MaxResults": "*int32", "NextToken": "*string"},
			"list-gateway-instances":             {"FilterArn": "*string", "MaxResults": "*int32", "NextToken": "*string"},
			"list-gateways":                      {"MaxResults": "*int32", "NextToken": "*string"},
			"list-offerings":                     {"MaxResults": "*int32", "NextToken": "*string"},
			"list-reservations":                  {"MaxResults": "*int32", "NextToken": "*string"},
			"list-router-inputs":                 {"Filters": "[]types.RouterInputFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-router-network-interfaces":     {"Filters": "[]types.RouterNetworkInterfaceFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-router-outputs":                {"Filters": "[]types.RouterOutputFilter", "MaxResults": "*int32", "NextToken": "*string"},
			"list-tags-for-global-resource":      {"ResourceArn": "*string"},
			"list-tags-for-resource":             {"ResourceArn": "*string"},
			"purchase-offering":                  {"OfferingArn": "*string", "ReservationName": "*string", "Start": "*string"},
			"remove-bridge-output":               {"BridgeArn": "*string", "OutputName": "*string"},
			"remove-bridge-source":               {"BridgeArn": "*string", "SourceName": "*string"},
			"remove-flow-media-stream":           {"FlowArn": "*string", "MediaStreamName": "*string"},
			"remove-flow-output":                 {"FlowArn": "*string", "OutputArn": "*string"},
			"remove-flow-source":                 {"FlowArn": "*string", "SourceArn": "*string"},
			"remove-flow-vpc-interface":          {"FlowArn": "*string", "VpcInterfaceName": "*string"},
			"restart-router-input":               {"Arn": "*string"},
			"restart-router-output":              {"Arn": "*string"},
			"revoke-flow-entitlement":            {"EntitlementArn": "*string", "FlowArn": "*string"},
			"start-flow":                         {"FlowArn": "*string"},
			"start-router-input":                 {"Arn": "*string"},
			"start-router-output":                {"Arn": "*string"},
			"stop-flow":                          {"FlowArn": "*string"},
			"stop-router-input":                  {"Arn": "*string"},
			"stop-router-output":                 {"Arn": "*string"},
			"tag-global-resource":                {"ResourceArn": "*string", "Tags": "map[string]string"},
			"tag-resource":                       {"ResourceArn": "*string", "Tags": "map[string]string"},
			"take-router-input":                  {"RouterInputArn": "*string", "RouterOutputArn": "*string"},
			"untag-global-resource":              {"ResourceArn": "*string", "TagKeys": "[]string"},
			"untag-resource":                     {"ResourceArn": "*string", "TagKeys": "[]string"},
			"update-bridge":                      {"BridgeArn": "*string", "EgressGatewayBridge": "*types.UpdateEgressGatewayBridgeRequest", "IngressGatewayBridge": "*types.UpdateIngressGatewayBridgeRequest", "SourceFailoverConfig": "*types.UpdateFailoverConfig"},
			"update-bridge-output":               {"BridgeArn": "*string", "NetworkOutput": "*types.UpdateBridgeNetworkOutputRequest", "OutputName": "*string"},
			"update-bridge-source":               {"BridgeArn": "*string", "FlowSource": "*types.UpdateBridgeFlowSourceRequest", "NetworkSource": "*types.UpdateBridgeNetworkSourceRequest", "SourceName": "*string"},
			"update-bridge-state":                {"BridgeArn": "*string", "DesiredState": "types.DesiredState"},
			"update-flow":                        {"EncodingConfig": "*types.EncodingConfig", "FlowArn": "*string", "FlowSize": "types.FlowSize", "Maintenance": "*types.UpdateMaintenance", "NdiConfig": "*types.NdiConfig", "SourceFailoverConfig": "*types.UpdateFailoverConfig", "SourceMonitoringConfig": "*types.MonitoringConfig"},
			"update-flow-entitlement":            {"Description": "*string", "Encryption": "*types.UpdateEncryption", "EntitlementArn": "*string", "EntitlementStatus": "types.EntitlementStatus", "FlowArn": "*string", "Subscribers": "[]string"},
			"update-flow-media-stream":           {"Attributes": "*types.MediaStreamAttributesRequest", "ClockRate": "*int32", "Description": "*string", "FlowArn": "*string", "MediaStreamName": "*string", "MediaStreamType": "types.MediaStreamType", "VideoFormat": "*string"},
			"update-flow-output":                 {"CidrAllowList": "[]string", "Description": "*string", "Destination": "*string", "Encryption": "*types.UpdateEncryption", "FlowArn": "*string", "MaxLatency": "*int32", "MediaStreamOutputConfigurations": "[]types.MediaStreamOutputConfigurationRequest", "MinLatency": "*int32", "NdiProgramName": "*string", "NdiSpeedHqQuality": "*int32", "OutputArn": "*string", "OutputStatus": "types.OutputStatus", "Port": "*int32", "Protocol": "types.Protocol", "RemoteId": "*string", "RouterIntegrationState": "types.State", "RouterIntegrationTransitEncryption": "*types.FlowTransitEncryption", "SenderControlPort": "*int32", "SenderIpAddress": "*string", "SmoothingLatency": "*int32", "StreamId": "*string", "VpcInterfaceAttachment": "*types.VpcInterfaceAttachment"},
			"update-flow-source":                 {"Decryption": "*types.UpdateEncryption", "Description": "*string", "EntitlementArn": "*string", "FlowArn": "*string", "GatewayBridgeSource": "*types.UpdateGatewayBridgeSourceRequest", "IngestPort": "*int32", "MaxBitrate": "*int32", "MaxLatency": "*int32", "MaxSyncBuffer": "*int32", "MediaStreamSourceConfigurations": "[]types.MediaStreamSourceConfigurationRequest", "MinLatency": "*int32", "NdiSourceSettings": "*types.NdiSourceSettings", "Protocol": "types.Protocol", "RouterIntegrationState": "types.State", "RouterIntegrationTransitDecryption": "*types.FlowTransitEncryption", "SenderControlPort": "*int32", "SenderIpAddress": "*string", "SourceArn": "*string", "SourceListenerAddress": "*string", "SourceListenerPort": "*int32", "StreamId": "*string", "VpcInterfaceName": "*string", "WhitelistCidr": "*string"},
			"update-gateway-instance":            {"BridgePlacement": "types.BridgePlacement", "GatewayInstanceArn": "*string"},
			"update-router-input":                {"Arn": "*string", "Configuration": "types.RouterInputConfiguration", "MaintenanceConfiguration": "types.MaintenanceConfiguration", "MaximumBitrate": "*int64", "Name": "*string", "RoutingScope": "types.RoutingScope", "Tier": "types.RouterInputTier", "TransitEncryption": "*types.RouterInputTransitEncryption"},
			"update-router-network-interface":    {"Arn": "*string", "Configuration": "types.RouterNetworkInterfaceConfiguration", "Name": "*string"},
			"update-router-output":               {"Arn": "*string", "Configuration": "types.RouterOutputConfiguration", "MaintenanceConfiguration": "types.MaintenanceConfiguration", "MaximumBitrate": "*int64", "Name": "*string", "RoutingScope": "types.RoutingScope", "Tier": "types.RouterOutputTier"},
		},
		OperationInputRequired: map[string][]string{
			"add-bridge-outputs":                 {"BridgeArn", "Outputs"},
			"add-bridge-sources":                 {"BridgeArn", "Sources"},
			"add-flow-media-streams":             {"FlowArn", "MediaStreams"},
			"add-flow-outputs":                   {"FlowArn", "Outputs"},
			"add-flow-sources":                   {"FlowArn", "Sources"},
			"add-flow-vpc-interfaces":            {"FlowArn", "VpcInterfaces"},
			"batch-get-router-input":             {"Arns"},
			"batch-get-router-network-interface": {"Arns"},
			"batch-get-router-output":            {"Arns"},
			"create-bridge":                      {"Name", "PlacementArn", "Sources"},
			"create-flow":                        {"Name"},
			"create-gateway":                     {"EgressCidrBlocks", "Name", "Networks"},
			"create-router-input":                {"Configuration", "MaximumBitrate", "Name", "RoutingScope", "Tier"},
			"create-router-network-interface":    {"Configuration", "Name"},
			"create-router-output":               {"Configuration", "MaximumBitrate", "Name", "RoutingScope", "Tier"},
			"delete-bridge":                      {"BridgeArn"},
			"delete-flow":                        {"FlowArn"},
			"delete-gateway":                     {"GatewayArn"},
			"delete-router-input":                {"Arn"},
			"delete-router-network-interface":    {"Arn"},
			"delete-router-output":               {"Arn"},
			"deregister-gateway-instance":        {"GatewayInstanceArn"},
			"describe-bridge":                    {"BridgeArn"},
			"describe-flow":                      {"FlowArn"},
			"describe-flow-source-metadata":      {"FlowArn"},
			"describe-flow-source-thumbnail":     {"FlowArn"},
			"describe-gateway":                   {"GatewayArn"},
			"describe-gateway-instance":          {"GatewayInstanceArn"},
			"describe-offering":                  {"OfferingArn"},
			"describe-reservation":               {"ReservationArn"},
			"get-router-input":                   {"Arn"},
			"get-router-input-source-metadata":   {"Arn"},
			"get-router-input-thumbnail":         {"Arn"},
			"get-router-network-interface":       {"Arn"},
			"get-router-output":                  {"Arn"},
			"grant-flow-entitlements":            {"Entitlements", "FlowArn"},
			"list-bridges":                       {},
			"list-entitlements":                  {},
			"list-flows":                         {},
			"list-gateway-instances":             {},
			"list-gateways":                      {},
			"list-offerings":                     {},
			"list-reservations":                  {},
			"list-router-inputs":                 {},
			"list-router-network-interfaces":     {},
			"list-router-outputs":                {},
			"list-tags-for-global-resource":      {"ResourceArn"},
			"list-tags-for-resource":             {"ResourceArn"},
			"purchase-offering":                  {"OfferingArn", "ReservationName", "Start"},
			"remove-bridge-output":               {"BridgeArn", "OutputName"},
			"remove-bridge-source":               {"BridgeArn", "SourceName"},
			"remove-flow-media-stream":           {"FlowArn", "MediaStreamName"},
			"remove-flow-output":                 {"FlowArn", "OutputArn"},
			"remove-flow-source":                 {"FlowArn", "SourceArn"},
			"remove-flow-vpc-interface":          {"FlowArn", "VpcInterfaceName"},
			"restart-router-input":               {"Arn"},
			"restart-router-output":              {"Arn"},
			"revoke-flow-entitlement":            {"EntitlementArn", "FlowArn"},
			"start-flow":                         {"FlowArn"},
			"start-router-input":                 {"Arn"},
			"start-router-output":                {"Arn"},
			"stop-flow":                          {"FlowArn"},
			"stop-router-input":                  {"Arn"},
			"stop-router-output":                 {"Arn"},
			"tag-global-resource":                {"ResourceArn", "Tags"},
			"tag-resource":                       {"ResourceArn", "Tags"},
			"take-router-input":                  {"RouterOutputArn"},
			"untag-global-resource":              {"ResourceArn", "TagKeys"},
			"untag-resource":                     {"ResourceArn", "TagKeys"},
			"update-bridge":                      {"BridgeArn"},
			"update-bridge-output":               {"BridgeArn", "OutputName"},
			"update-bridge-source":               {"BridgeArn", "SourceName"},
			"update-bridge-state":                {"BridgeArn", "DesiredState"},
			"update-flow":                        {"FlowArn"},
			"update-flow-entitlement":            {"EntitlementArn", "FlowArn"},
			"update-flow-media-stream":           {"FlowArn", "MediaStreamName"},
			"update-flow-output":                 {"FlowArn", "OutputArn"},
			"update-flow-source":                 {"FlowArn", "SourceArn"},
			"update-gateway-instance":            {"GatewayInstanceArn"},
			"update-router-input":                {"Arn"},
			"update-router-network-interface":    {"Arn"},
			"update-router-output":               {"Arn"},
		},
		Run: servicecmd.Execute,
	}
	if err := runtime.ExecuteService("mediaconnect", svc, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
